### ISSUE TITLE
Add multiple request handlers for onnotfound and onfileupload

### ISSUE THREAD

**Issue by sticilface** [esp8266/Arduino#1000]
issue.. 1000....  

I've been writing a lib that uses onnotfound and onfileupload.  However, it is possible / likely that different libraries may which to have access to these functions and not just one. 

For example I'm using the FSbrowser, but also HTTP upload libs.  At the moment I have this in my setup 
```
  HTTP.onFileUpload([&](){ 
    handleFileUpdate();
    handleUpgrade(); }
    );
```

but this requires the user to correctly place the right functions in their setup function to use the libs. 

Would it be possible to have an AddonFileUpload function to the ESP8266WebServer that would append callbacks to a list in the onfileupload or onnotfound functions (in a similar manor to the handle function),  these functions could return a bool which would then cause the web server to stop or continue through the functions. 

Bit of a confusing explanation there, but hopefully it makes sense.

**Comment by igrr** [comment]
Ideally, I would like to move `handleFileUpload` and `handleNotFound` to RequestHandler interface.
Every library would inherit from RequestHandler, and WebServer would walk all registered request handlers in sequence, looking for the first one which is able to handle particular request.
Currently RequestHandler is used only for "normal" requests but adding another two methods is certainly possible.

**Comment by sticilface** [comment]
That would be great.  Its probably a bit/quite beyond me to attempt this.  at least in a way that would not just require loads more work from you guys to debug it.

**Comment by igrr** [comment]
Ok, not sure this falls into next Monday release, but I'll put this on my list.

**Comment by sticilface** [comment]
:)  thanks

**Comment by igrr** [comment]
RequestHandler class now includes upload handlers.
