### ISSUE TITLE
OTA Update example sketch missing 

### ISSUE THREAD

**Issue by jeffryr** [esp8266/Arduino#1001]
The OTA Update documentation refers to the DNS_SD_Arduino_OTA.ino sketch available under File > Examples > ESP8266mDNS but that sketch has not yet been merged.

**Comment by igrr** [comment]
It was removed in https://github.com/esp8266/Arduino/pull/980, but the documentation has not been updated yet.

**Comment by igrr** [comment]
Merged in https://github.com/esp8266/Arduino/pull/1024
