### ISSUE TITLE
digitalWrite 4 & 5 are backwards?

### ISSUE THREAD

**Issue by RussMathis** [esp8266/Arduino#103]
For the Esp-12,
digitalWrite(4,HIGH);//Sets Esp8266 physical pin 5 HIGH
digitalWrite(4,LOW);//Sets Esp8266 physical pin 5 LOW

digitalWrite(5,HIGH);//Sets Esp8266 physical pin 4 HIGH
digitalWrite(5,LOW;//Sets Esp8266 physical pin 5 HIGH

Is this correct? I get this when using the ESP-12.

**Comment by Zeron** [comment]
GPIO4 and GPIO5 are swapped on some versions of the ESP-12
See:  http://www.esp8266.com/viewtopic.php?f=21&t=1388
