### ISSUE TITLE
Serilal.printf is not working

### ISSUE THREAD

**Issue by divertom** [esp8266/Arduino#1030]
I am using an ESP 01 module with a FTDI 232 USB board. I can program the ESP and all seem to work fine beside the serial.printf. I tried different baud rates, but no success. When using a NodeMCU 1.0 with ESP 12E all works fine. Any help or suggestion how to fix this?

I am using the current stable version from 7/23.

Thanks,
Tom

**Comment by Rickgg** [comment]
Hi, I had the same problem a while ago, and solved it by using an external power source for to the FTDI. Hopefully that helps

**Comment by Links2004** [comment]
is ```Serial.print()``` working?
do you use the Serial Monitor of the IDE?
how the connection between FTDI and ESP looks like?
