### ISSUE TITLE
ArduinoOTA stops working together with ESP8266WebServer (Generic 512k no SPIFFS)

### ISSUE THREAD

**Issue by reaper7** [esp8266/Arduino#1042]
when I try to add WebServer to BasicOTA example then OTA stops working (Generic 512k no SPIFFS).
I add only (before setup):
```
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiUdp.h>
#include <ArduinoOTA.h>

#include <ESP8266WebServer.h>

ESP8266WebServer server(80); 
``` 
serial console messages when I try upload via OTA:
```
Booting
Ready
IP address: 192.168.4.28
Error[1]: Begin Failed
```
arduino ide message:
```
11:22:26 [ERROR]: No response from device
```

**Comment by me-no-dev** [comment]
your sketch becomes too large and there is no space to write the new one.
OTA is really intended for larger Flash chips. 512K is way not enough :)

**Comment by reaper7** [comment]
seems to be true :)
without WebServer 245714b(49%)
with      WebServer 247662b(49%)
this is bad news, because OTA could be good solution for some devices like esp-05 (only with rx+tx pins) where programming is little difficult.
I have few esp-05, so...maybe changing flash ic's is last chance for them.
BTW...is any good and tested type of bigger flash memory?

**Comment by me-no-dev** [comment]
any 25Q compatible chip should do :) i bought some 8MB Winbond chips that I use (up to 4MB of them).

**Comment by reaper7** [comment]
bought W25Q32 :)
tnx!
close!

**Comment by reaper7** [comment]
I only notice that
with latest release size of final sketch is OK:)
without WebServer 222006b(44%)
with WebServer 224094b(44%)
