### ISSUE TITLE
OTA question

### ISSUE THREAD

**Issue by bbasil2012** [esp8266/Arduino#1043]
Hi guys!

Is it possible to use the OTA to update the firmware and SPIFFS image separately?
for example:
Step1:  firmware download and injection
Step2:  SPIFFS image download and injection

**Comment by me-no-dev** [comment]
you want to do it in one go or you are fine with reboot in between?
ArduinoOTA and espota.py do support updating of both things, but only one at a time.

**Comment by bbasil2012** [comment]
Hi!
It does not matter. Both ways are suitable.
The main thing to understand how to do it by ESPhttpUpdate (not by Arduino IDE)

**Comment by bbasil2012** [comment]
Yes, I found it !!!
Update.begin(maxSketchSpace,U_SPIFFS)
