### ISSUE TITLE
Upload docs for staging version

### ISSUE THREAD

**Issue by hubbsy** [esp8266/Arduino#1044]
The "reference" link for STAGING at https://github.com/esp8266/Arduino is a broken link.

**Comment by nibelungen** [comment]
+1 still not available

**Comment by geovanisouza92** [comment]
+1

**Comment by igrr** [comment]
Guys, esp8266.com NS records are gone for some reason so arduino.esp8266.com is not available.
Also, reference wasn't even generated for the latest staging release.

**Comment by nibelungen** [comment]
any chance to store the json somewhere else online??

**Comment by plinioseniore** [comment]
Looks also that images in stable reference documentation are gone.
