### ISSUE TITLE
Support for SPI0 in SPI library

### ISSUE THREAD

**Issue by Shibonja** [esp8266/Arduino#1062]
Hi guys,

First of all Thanks for the good work, you made development much easier with esp integration with Arduino IDE. 
I have one question if someone can answer on them. 
1) are the extra SPI pins on esp-12e supported in Arduino IDE and if yes are they using bit-banging.

ESP8226-12E https://www.adafruit.com/products/2491

Thanks in advance, Haris.
##

**Comment by igrr** [comment]
SPI library uses hardware HSPI (a.k.a. SPI1) peripheral (pins 12-15).
Extra pins on ESP-12E are connected to SPI0 peripheral, which is not supported by SPI0 library at the moment.

**Comment by Shibonja** [comment]
Hi @igrr ,
Thanks for quick answer.
Are you planning to add support for them in future releases?

**Comment by igrr** [comment]
Actually I did implement this in a hacky manner about a month ago, need to revisit these changes and clean up the code.

**Comment by Shibonja** [comment]
Hi @igrr ,
I ordered a few ESP8226-12E, so if u need any help, maybe I can be at your service. I am not a C/C++ guru but I can find my way around.

**Comment by Links2004** [comment]
is SPI0 not shared with the flash?
so all the SPI code need to be in ram,
may gives problems with other interrupts too?

**Comment by igrr** [comment]
Actually this is done as follows: you are still using SPI1 peripheral (i.e. registers are the same), but its pins are mapped to the same pins as SPI0. There is a hardware arbiter which can demultiplex two SPI peripherals to the same physical set of pins, controlling two CS lines automatically. SPI0 has higher priority, so flash requests are still serviced, and you can use cached code. Access times via SPI1 become a bit unpredictable in this mode, but you can have an SPI peripheral and keep pins 12-15 free at the same time.

**Comment by reaper7** [comment]
@igrr - very interesting...is there any chance for tests this solution?

**Comment by steffenmauch** [comment]
@igrr Is there any possiblity to test your solution?

**Comment by KaloNK** [comment]
+1 for this feature.

Will it be possible to switch SPI1 between hardware and pins 12-15 at runtime?

I was looking for something similar to https://github.com/espressif/esp8266_mp3_decoder implementation for SPI SRAM (or [FRAM](https://github.com/adafruit/Adafruit_FRAM_SPI) ) chip access.
The idea is to use the same pins in SQI mode or better yet in SDI mode with the CS0 attached to the HOLD, so flash access will not interfere with a RAM stream if interrupted and still have the pins 12-15 as dedicated SPI for other devices ... as if there are 3 SPI:
SPI0 - flash
SPI1 - user
SPI2 - RAM in SDI mode, paralel to the flash, but with user defined CS

**Comment by KaloNK** [comment]
> Actually I did implement this in a hacky manner about a month ago, need to revisit these changes and clean up the code.

@igrr shouldn't it be enough to call hspi_dev_sel() ( esp_iot_sdk
\examples\driver_lib\driver\spi_overlap.c ) inside beginTransaction()?
It can actually replace the <code>while(SPI1CMD & SPIBUSY) {}</code> call as it uses WAIT_HSPI_IDLE() macro which does the same.
So when we use HSPI we call hspi_dev_sel(0) and for RAM we call hspi_dev_sel(2) which will use GPIO0 (1 for GPIO1 is an option, but as it is TX0 can't be used). Settings should be extended with the mode (DIO or QIO) in addition to the spi dev used.

If such approach is acceptable I can try to modify the SPI driver in a backward compatible way and post a pull request with the changes.

**Comment by KaloNK** [comment]
I have made a patch to implement this based on the SDK example code https://github.com/KaloNK/Arduino/commit/48ef8c434678ebd41cbdcc750ab0859489efbcd9 but it is not tested yet, because I am still waiting for the SRAM chip.
I am about to add support for (S/F/M)RAM attached parallel to the flash in (S/D/Q)IO modes too, but i guess it should be separate patch

**Comment by whhsn** [comment]
Check this:

https://hackaday.io/project/8678-rpi-wifi/log/32008-on-sdio-and-the-mysteries-of-the-universe

**Comment by KaloNK** [comment]
I have some code [here](https://github.com/KaloNK/Arduino/tree/ExtendSPI) and [here](https://github.com/KaloNK/Arduino/tree/SPI_RAM), but couldn't make it work with SRAM ( 23LC1024 ) attached to the same bus as flash (it does not read anything from SPI0 for some reason). I do not have a logic analyzer, so it is difficult to debug what is happening.
I will come back to this some time later, but if someone can review the code and see a mistake there causing it not to work, will help a lot

**Comment by igrr** [comment]
@KaloNK, thank you for your work.
FYI, there is a $250 [bounty](https://www.bountysource.com/issues/28455602-support-for-spi0-in-spi-library) on this issue.

**Comment by mkeyno** [comment]
@igrr  can you elaborate, regards to this topic, what feature will be added to the ESP8266? if new HW SPI will be available for user , it is only break out on ESP-12E and not break out for most current available module in market

**Comment by boks21** [comment]
Hi,
 im' new using esp8266 with spi( i used it with uart)

Now i need use esp12E with (H)SPI and im doing first steps and have some doubts:

Its factory ready to use HSPI? or i need to reprogram?
Some special pin conections to use HSPI?

Someone knows registers adress to write/read data to Wi-Fi?

Thanks a lot,

Loureiro

**Comment by pipi61** [comment]
http://www.esp8266.com/viewtopic.php?f=32&t=11396&p=54834&hilit=spi+gpio+12+13+14#p54834

**Comment by igrr** [comment]
Implemented in #3189.

@riataman please go to bountysource to claim your bounty.

**Comment by WillyKirsch** [comment]
Hi, I'm trying to use the SPI library to read an SD card, with the previous version (without the PSI.pins() method) and worked fine, now with the SPI.Pins() method, I'm having this error when compile:

...esp8266\2.3.0\libraries\SPI\SPI.cpp:132:52: error: 'SPIPCS2DIS' was not declared in this scope

                 SPI1P |= SPIPCS1DIS | SPIPCS0DIS | SPIPCS2DIS;

in any line where that names are used.

can anybody help me?

thanks!!

**Comment by usonix** [comment]
Hi, I'm new here and also not very experienced in programming, I read what is described above, but it was not very clear to me. What I need is to use the SD card on the SPI0 pins, leaving the SPI1 pins free for other applications, if not ask too much, could someone publish an example code how to do this?

**Comment by riataman** [comment]
I never got around getting a SD card working in SPI0 (I did got a SPI memory workking), I think the sd card library would need changes to make it work. 

I didn't had the proper tools at the time to try and debug this and right now I lack to time :(

**Comment by javadhabibi1500** [comment]
Except power-up, when the esp needs to use flash memory through SPi0? In other words, when my overlaped SPI is busy?
