### ISSUE TITLE
Eclipse data folder to spiffs  upload.

### ISSUE THREAD

**Issue by far5893** [esp8266/Arduino#1063]
Under eclipse compiled with (512k/64k) option  there is no way  to build and flash  data directory.
##

**Comment by igrr** [comment]
Do you mean you want SPIFFS upload function implemented in Eclipse?
Eclipse isn't officially supported, but I think @Links2004 is using it for development. Perhaps he can give some advice.

**Comment by Links2004** [comment]
you can create your own make targets for example mkspiffs.

1. create a file ```makefile.init``` in the project root

```makefile
vecho := @echo
Q := @

ARDUINO_BASE      = D:/Coding/avr/Programme/arduino-nightly
ESP8266_BASE      = $(ARDUINO_BASE)/hardware/esp8266com/esp8266
ESP8266_TOOLS     = $(ESP8266_BASE)/tools

mkspiffs:
	$(vecho) Staring mkspiffs...
	$(ESP8266_TOOLS)/mkspiffs/mkspiffs.exe -c "../data" mkspiffs.bin

```

2.
![image](https://cloud.githubusercontent.com/assets/974709/11307490/dae1807a-8fb8-11e5-8170-23d8cbd3386c.png)

3.
![image](https://cloud.githubusercontent.com/assets/974709/11307502/e86cadaa-8fb8-11e5-8bf6-eccfcb2eb4c0.png)


@igrr can you check the mkspiff command, i never used it before ;) is the block, size and page needed?
 
@far5893 may your ESP8266_BASE path is in your user arduino dir (when you have installed via json)

**Comment by igrr** [comment]
You also need to pass block size, page size, and image size to mkspiffs.
These are defined for each flash size variant in boards.txt, i.e. for 512k(64k SPIFFS):
```
generic.menu.FlashSize.512K64.build.spiffs_start=0x6B000
generic.menu.FlashSize.512K64.build.spiffs_end=0x7B000
generic.menu.FlashSize.512K64.build.spiffs_blocksize=4096
```

These values must be given to mkspiffs, otherwise created image will not be compatible with SPIFFS configuration in firmware.

mkspiffs command line arguments are described here: https://github.com/igrr/mkspiffs#usage

**Comment by devyte** [comment]
Closing per #3655 .
