### ISSUE TITLE
WDT reset with mqtt

### ISSUE THREAD

**Issue by dmarkey** [esp8266/Arduino#1067]
Hi,

I need to run a load of MQTT work at startup.

This is about 8 or so tasks that take a few 300ms each

However AFTER these are complete I get a WDT reset. Any ideas here?

**Comment by igrr** [comment]
Could you please upload your sketch to gist and share a link?

**Comment by dmarkey** [comment]
Yes, i'll put it on GH

**Comment by dmarkey** [comment]
Just curious, would it be possible that MQTT callbacks might be happening in parallel(if they take a long time?)

**Comment by itsjustvenky** [comment]
Interesting issue, post the code so that we can see what going on.

**Comment by igrr** [comment]
Closing due to lack of feedback
