### ISSUE TITLE
Deprecated: recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "

### ISSUE THREAD

**Issue by jimbolimbo3** [esp8266/Arduino#1080]
Sorry for the italian, but the content is clear enough, I think.
My Arduino IDE shows this advice:

*Attenzione: platform.txt del core 'ESP8266 Modules' contiene la stringa deprecata recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{build.path}/{archive_file}" "{object_file}" convertita automaticamente in recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} {compiler.ar.extra_flags} "{archive_file_path}" "{object_file}". Verifica la disponibilità di un aggiornamento di questo core.*

**Comment by igrr** [comment]
Closing this as duplicate of #948
