### ISSUE TITLE
ESP8266WiFiClass::begin returns int but in reality its used as a wl_status_t

### ISSUE THREAD

**Issue by Makuna** [esp8266/Arduino#109]
ESP8266WiFiClass::status returns a uint8_t, but also should be a wl_status_t.  There are probably others.

The reason this is a concern is that I am getting compile errors when I used the correct type or reuse a result variable between several of this calls. Having it consistent would be a good thing.

**Comment by Links2004** [comment]
fixed in the mean time.
https://github.com/esp8266/Arduino/blob/342c4ae6fb847bfc787f80b89a2bb888d942dc32/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp#L637
