### ISSUE TITLE
not able to program my board with arduino IDE

### ISSUE THREAD

**Issue by shirish47** [esp8266/Arduino#1099]
Hi,

I have been using this library from last 4-5 months and my board used to work perfectly.. I am using a shielded version of ESP with ceramic antenna .. my board has a button connected to gpio0 and another button connected to REST pin.. for programming I used to press both button and release REST and it used to program(so I have wired other GPIO perfect ).I used this board for long and other similar ones.. but I had a month vacation and now when I am back to work.. it does not seem to program this way.. :(  I am using a stable version of ESP library... I have tried this with all settings ..nothing works ... :( what significant change have happen into library... ?

Sketch uses 201,034 bytes (46%) of program storage space. Maximum is 434,160 bytes.
Global variables use 44,592 bytes (54%) of dynamic memory, leaving 37,328 bytes for local variables. Maximum is 81,920 bytes.
C:\Users\ASUS-PC\AppData\Roaming\Arduino15\packages\esp8266\tools\esptool\0.4.5/esptool.exe -vv -cd ck -cb 115200 -cp COM3 -ca 0x00000 -cf C:\Users\ASUS-PC\AppData\Local\Temp\build8980351354168875094.tmp/sketch_nov28a.cpp.bin 
esptool v0.4.5 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to ck
	setting baudrate from 115200 to 115200
	setting port from COM1 to COM3
	setting address from 0x00000000 to 0x00000000
	espcomm_upload_file
	stat C:\Users\ASUS-PC\AppData\Local\Temp\build8980351354168875094.tmp/sketch_nov28a.cpp.bin success
	setting serial port timeouts to 1000 ms
opening bootloader
resetting board
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
trying to connect

**Comment by igrr** [comment]
> what significant change have happen into library

The stable version has not changed since June.
