### ISSUE TITLE
itoa (utoa) is not found if including arduino.h nor stdlib.h

### ISSUE THREAD

**Issue by Makuna** [esp8266/Arduino#110]
current workaround is to include stdlib_noniso.h.

this makes it hard to write a library that can compile for AVR and ESP8266.

**Comment by Links2004** [comment]
```utoa``` is a non std function AVR do a bad style and at it to the ```stdlib.h``` but the normal ```stdlib.h``` of the C/C++ standard does not include it.
the only change i see is at the the ```stdlib_noniso.h``` include in the ```Arduino.h```.

more infos here:
http://www.atmel.com/webdoc/AVRLibcReferenceManual/group__avr__stdlib.html
and 
http://www.cplusplus.com/reference/cstdlib/

**Comment by igrr** [comment]
fixed in 6a7d94a
