### ISSUE TITLE
Error while loading index.htm using serveStatic

### ISSUE THREAD

**Issue by tbnobody** [esp8266/Arduino#1105]
When using the webserver with serveStatic:
server.serveStatic("", SPIFFS, "");
and making a request like
http://esp8266/
it seems that the index.htm file isn't appended. If I look to the code: 
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h#L84
I would say we have to check the requestUri instead of path? Because path refers to the file system, but index.htm should be added to the user request!

**Comment by sticilface** [comment]
See
https://github.com/esp8266/Arduino/pull/1085

**Comment by igrr** [comment]
Fixed in a6e01b8
