### ISSUE TITLE
IDE 1.6.6 compatibility

### ISSUE THREAD

**Issue by pbecchi** [esp8266/Arduino#1115]
I have installed IDE 1.6.6 but now i get the error:

nodeMCU ..........board not found

Apparently all board packet are installed (2.0.0 version)!

**Comment by PaoloP74** [comment]
Idem

**Comment by asetyde** [comment]
i think it’s better use 1.6.5 for a stable version , also i ‘ve nodemcu

**Comment by pbecchi** [comment]
Yes... but I have tried deleting all files except "preferences.txt" from his directory and reloading staging 2.0.0 and now it works....!
At least I can compile and upload...... I hope to not find other bugs!
