### ISSUE TITLE
EEPROM Example

### ISSUE THREAD

**Issue by Lexander24** [esp8266/Arduino#1129]
Hello, today i try the eeprom example. After finish flash the program (uploading status : done uploading) and open the serial monitor.
Nothing appear on my serial monitor.

Nb. I try eeprom read example.

How i must set the board parameter to run this example.
Thx.
##

**Comment by ricardojlrufino** [comment]
Is resolved ?

try call EEPROM.begin(4096);

**Comment by devyte** [comment]
No basic info, no sketch.
The EEPROM code is workin in latest git => closing.
