### ISSUE TITLE
SPIFFS OTA Upload

### ISSUE THREAD

**Issue by lbthomsen** [esp8266/Arduino#1131]
I am actually not sure if this is supposed to work.  Arduino 1.6.5, Latest ESP 2.0.0.  OTA Flash works perfectly.  Trying to upload data results in:

[SPIFFS] data   : /home/lth/Arduino/tm8901/data
[SPIFFS] size   : 1004
[SPIFFS] page   : 256
[SPIFFS] block  : 8192
/index.html
[SPIFFS] upload : /tmp/build2830610088099707211.tmp/tm8901.spiffs.bin
[SPIFFS] reset  : ck
[SPIFFS] port   : 10.1.192.100
[SPIFFS] speed  : 115200
[SPIFFS] address: 0x300000

error: cannot access 10.1.192.100

error: espcomm_open failed

It works over a serial link.

**Comment by igrr** [comment]
Please see https://github.com/esp8266/arduino-esp8266fs-plugin/issues/4.
