### ISSUE TITLE
SPIFFS data directory  subfolder not converted in prefixed files.

### ISSUE THREAD

**Issue by far5893** [esp8266/Arduino#1139]
SPIFFS does not support directories so dir is only a prefix of filename,
if i prepare SPIFFS  filesystem in linux (data directory) i cannot prefix files with /somewhere/ (/ is not allowed)  but i can create directories , spiffs flash tool does not convert directories name in file prefixes!

**Comment by igrr** [comment]
This issue was moved to esp8266/arduino-esp8266fs-plugin#5
