### ISSUE TITLE
Scan during wifi connection process interrupts connection

### ISSUE THREAD

**Issue by joostjager** [esp8266/Arduino#1140]
In method ESP8266WiFiClass::scanNetworks, the following code is present:
```    
int status = wifi_station_get_connect_status();
if (status != STATION_GOT_IP && status != STATION_IDLE)
{
    disconnect();
}
```

If connection is in progress, but an IP has not yet been obtained AND a scan is started at that moment, connection will never happen anymore. Is there a specific reason to disconnect here?

**Comment by Links2004** [comment]
yes, its a limitation of the SDK.
but i currently not find the docs for this.

**Comment by joostjager** [comment]
I removed the disconnect call, but this indeed did not take away the limitation. Thanks for your comment.
