### ISSUE TITLE
http://arduino.esp8266.com/stable/package_esp8266com_index.json file signature verification failed. File ignored.

### ISSUE THREAD

**Issue by Marsfan** [esp8266/Arduino#1176]
I know that #1051 covers this, but it seems to be happening again. I will go with the temporary fix, but I thought I should let you know.

**Comment by Marsfan** [comment]
Fixed this. It turned out to have to do with the network I was on

**Comment by VeggieVampire** [comment]
any other way to download it on a proxy network? such as a dirty install?
