### ISSUE TITLE
ESP8266 mDNS client library

### ISSUE THREAD

**Issue by gvuyk** [esp8266/Arduino#1184]
I'm unable to connect the ESP8266 to a .local domain (ex: raspberry.local hosted by a raspberry) same thing with a linux and windows box (with bonjour)
Is the functionality implemented?

The problem is reproducible with the WiFiClient example

**Comment by igrr** [comment]
There is no mDNS client on the ESP by default. So no, this won't work out of the box.

**Comment by probonopd** [comment]
Check out https://github.com/mrdunk/esp8266_mdns

**Comment by igrr** [comment]
Implemented in #1741.
