### ISSUE TITLE
How to get function "FreeRAM()" to work?

### ISSUE THREAD

**Issue by rudi48** [esp8266/Arduino#1195]
Hello,
I have seen in `libraries/SD/src/utility/SdFatUtil.h`
a function **FreeRAM()**, but it does not compile, with error:
    `undefined reference to `__brkval'`

What can I do to make **FreeRAM()** work?

Regards, Rudolf

**Comment by Links2004** [comment]
```ESP.getFreeHeap();``` shut do the job just fine.
https://github.com/esp8266/Arduino/blob/master/doc/libraries.md#esp-specific-apis

**Comment by rudi48** [comment]
Hello Markus,
Thank you very much again for your help.
I have searched for **memory** and **RAM** only, so I could not find **getFreeHeap**.
Regards, Rudolf
