### ISSUE TITLE
Boot loader failsafe mechanism

### ISSUE THREAD

**Issue by mangelajo** [esp8266/Arduino#1199]
I'm theorising here, so there are chances I got something wrong. As I understood, if the boot loader copy process fails (device switched off during boot loader copy process) there's no recovery mechanism, because the copy orders are in RTC memory, and not in flash.

So, an idea here.

Why don't we save the end of the flash to set the boot loader command for upgrade?, then when an upgrade has properly finished, we erase that area.

Thoughts?
##

**Comment by igrr** [comment]
Or rather, write a few more "finalizing" bytes to that area, indicating that the command has been processed. This would avoid having to erase that sector twice per update.

**Comment by mangelajo** [comment]
@igrr, right, that sounds even better.

**Comment by devyte** [comment]
While this is (probably) not a breaking change, I consider it non-trivial, so pushing back milestone.

**Comment by davisonja** [comment]
This is #6538

**Comment by d-a-v** [comment]
duplicate #6538
