### ISSUE TITLE
ESP-07 or ESP-12 ili9341 2.4" tft Color problem

### ISSUE THREAD

**Issue by tontito** [esp8266/Arduino#120]
http://www.esp8266.com/viewtopic.php?f=32&t=2625&start=10

background not black always white colors incorrect 

RED = CYAN 
CYAN = RED
YELLOW = BLUE

All colors incorrect and background always white.

My TFT 
http://www.ebay.com/itm/121428170555?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT

**Comment by igrr** [comment]
@Sermus any idea what could be wrong here?

**Comment by tontito** [comment]
i don`t know.

maybe 2.2" ili9341 different 2.4" ili9341.

**Comment by tontito** [comment]
hi again.

02.05.2015 windows build
(https://ci.appveyor.com/api/buildjobs/dbj2egv85gam6s8t/artifacts/build/windows/arduino-1.6.1-windows.zip)
download and copile ili9341 example no error compiling but not working screen always white screen.

**Comment by stonemull** [comment]
I had the same with an ILI9341 2.4 TFT (different library though so your code may be different)  and changed the driver to initialise with inversion turned on.

//    writeRegister8(ILI9341_INVERTOFF, 0);		// original
    writeRegister8(ILI9341_INVERTON, 0);	//set by col

addresses are ..

#define ILI9341_INVERTOFF          0x21 //
#define ILI9341_INVERTON           0x20 //

if you want to check the ILI9341 datasheet

**Comment by tontito** [comment]
New screen receive. No problem good color
