### ISSUE TITLE
Sleep mode that maintains Wifi network connection

### ISSUE THREAD

**Issue by raimohanska** [esp8266/Arduino#1240]
Is there a way to put the chip in a mode like deep sleep but so that it would maintain the Wifi connection?

I'd like to monitor a TCP socket say, once a second and consume as little power as possible in the mean time.

**Comment by Links2004** [comment]
deep sleep disables the MCU core only the RTC component keeps running, 
in this mode it is not possible to keep the WiFi connection,

**Comment by raimohanska** [comment]
I'm aware of that fact. I was just wondering if you could use one of the other power modes somehow to keep the Wifi+TCP connection up with minimal energy.

**Comment by Links2004** [comment]
the SDK goes by default in Modem Sleep if possible, more can not be done.
