### ISSUE TITLE
ESP8266 wroom-02 creates a AP even with no code

### ISSUE THREAD

**Issue by TurBoss** [esp8266/Arduino#1253]
I have my module setup with the blink example

but it creates an AP no matter what code i put in it, the network is created
is named ESP_0XXXXX

Any ideas??

**Comment by TurBoss** [comment]
Arduino 1.6.6
ESP 2.0.0

**Comment by TurBoss** [comment]
this happened before flashing OTA-mDNS-SPIFFS

**Comment by Links2004** [comment]
the SDK stores the latest WiFi config in flash, this config is Keep during the flash process,
use 
```
WiFi.softAPdisconnect();
WiFi.disconnect();
```

**Comment by TurBoss** [comment]
it worked thank you!
