### ISSUE TITLE
Strange behaviour with SoftAP

### ISSUE THREAD

**Issue by IoT64** [esp8266/Arduino#1254]
String ssid = "test";
WiFi.mode(WIFI_AP);
WiFi.softAPConfig(ip, ipgw, ipnm);
WiFi.softAP(ssid.c_str()); // WiFi.softAP("test"); give same result

This code don't create an open "test" network but instead an open "ESP_xxxxxx" network where xxxxxx are hexadecimal numbers... Why?

esp8266 v2.0.0_rc2

**Comment by igrr** [comment]
This is a known issue with 2.0.0-rc2. It has been fixed in 2.0.0 (stable)
and in git version.

**Comment by IoT64** [comment]
Thank you. 2.0.0 stable solve this.
