### ISSUE TITLE
Adding supported firmware

### ISSUE THREAD

**Issue by delcom5** [esp8266/Arduino#1264]
It would be nice to see SUPPORTED FIRMWARE listed on the Read me page.

**Comment by penfold42** [comment]
I'm not sure that's relevant.

When you upload your code, it replaces any existing espressif firmware that was on the device

**Comment by delcom5** [comment]
After uploading the simple blink nothing happened. Then when I tried to send simple AT commands and got no response. After research I flashed the firmware. After that I was able to send AT commands with success. I uploaded the simple blink and it finally worked...which is why I thought it could be a firmware issue.

**Comment by itsjustvenky** [comment]
@delcom5  AT firmware is a app and blink is also an app. AT firmware is developed by espresiff itself and blink is done by people like yourself. What firmware version has to do here. I suggest you read more about ESP development.

**Comment by pgollor** [comment]
Any other app (AT commands app or so) could overwrite some other registers.
It will be the same if you clear the spi memory and flash your blink app after that. There is no correlation between the firmware apps and the arduino apps.

Therefore i will close this issue.
