### ISSUE TITLE
Maximum frequency PWM

### ISSUE THREAD

**Issue by sabas1080** [esp8266/Arduino#1265]
Hi

What is the maximum frequency of the PWM ESP8266 ?

Thanks

**Comment by me-no-dev** [comment]
theoretical max frequency is 80000000/range, or for default 1024 range that is 78.125KHz in reality, depending on the number channels and the values that are given, the resolution and timing at that speed might be slightly off.
I'll make a pull request with some optimizations :) looking at the code, there are some that can be done.

**Comment by sabas1080** [comment]
Thanks @me-no-dev, I'll try a 1Mhz

**Comment by mottab** [comment]
So, can I reach (32.768Khz) for master clock in PWM ??

Thanks.

**Comment by tablatronix** [comment]
Care to add some references to this? Technical docs note 

> the function of PWM is realized by interruption of the
timer, the minimum resolution reaches as much as 44 ns. PWM frequency range is
adjustable from 1000 μs to 10000 μs, i.e., between 100Hz and 1 kHz. When the PWM
frequency is 1 kHz, the duty ratio will be 1/22727

**Comment by drelephant** [comment]
From [here](http://esp8266.github.io/Arduino/versions/2.0.0/doc/reference.html#analog-output):

> analogWrite(pin, value) enables software PWM on the given pin. PWM may be used on pins 0 to 16. Call analogWrite(pin, 0) to disable PWM on the pin. value may be in range from 0 to PWMRANGE, which is equal to 1023 by default. PWM range may be changed by calling analogWriteRange(new_range).
>
> PWM frequency is 1kHz by default. Call analogWriteFreq(new_frequency) to change the frequency.

So I think all you have to do is call analogWriteFreq(32768) to run at 32.768kHz.

**Comment by diraniyoussef** [comment]
[Here](https://github.com/esp8266/Arduino/blob/master/doc/reference.rst) they made it clear, check "Analog output" section. It's 40 KHz the maximum.

**Comment by quetzalcoatl** [comment]
@me-no-dev you've pointed out that the theoretical max is:
> 80000000/range
I can't help but notice that's the 80MHz clock rate. I suppose it's only achievable with software and ~50% duty cycle.
That should mean that when ESP8266 is switched to 160MHz, it's theor.max. 160000000/range?
Could you confirm?

**Comment by me-no-dev** [comment]
@quetzalcoatl no. peripherals run from the APB clock which is always 80MHz. Same is true for ESP32
