### ISSUE TITLE
Support for ESP-32

### ISSUE THREAD

**Issue by nccchirag** [esp8266/Arduino#1266]
Will ESP-32 module work out of the box? As per John Lee, Arduino support would be added later.
Kindly guide if the contributors to this projects would be beta testing the new module.

Thank you

**Comment by igrr** [comment]
This core does not work for the ESP32, due to different register layouts,
different threading models, and sufficiently different SDKs. Some code may
be reused, mostly in libraries.

**Comment by nccchirag** [comment]
thank you for the prompt reply.
