### ISSUE TITLE
[sdk 1.5] Wifi does not connect sometimes

### ISSUE THREAD

**Issue by vlast3k** [esp8266/Arduino#1278]
I have a very strange problem with SDK 1.5. And a standard Nodemcu v0.9 board
I am testing with the standard WifiClient example. 
In my case I enable it and disable it via the CH_PD from an arduino. (with the nodemcu board, simply connect one wire from the "EN" pin to ground for a second)
With SDK 1.5 (current) - sometimes maybe half of the times - after enabling it, the Wifi does not connect
With SDK 1.3 (latest change before SDK 1.5 was introduced) - it always connects
With the AT FW 0.51 (that came with SDK 1.5), it also connects each time.

I wonder if somebody else will be able to repeat this ?

**Comment by me-no-dev** [comment]
same here. need to power cycle most of the time in order to connect to the WiFi.
some changes to the init were introduced today that might help you in getting better chance for connection. Pull the latest git and give it another go :)

**Comment by windalser** [comment]
Try  
WiFi.disconnect(); 
somewhere inside setup() before any  client.connect(...)

**Comment by vlast3k** [comment]
It took me some time to retest it, but now it seems to be working fine
So i am closing the issue
