### ISSUE TITLE
ArduinoIDE 1.6.6 doesn't find BasicOTA port on Windows7 x64

### ISSUE THREAD

**Issue by andig** [esp8266/Arduino#1282]
Following the OTA examples and install instructions. Sketch uploads fine, ESP is responding to mDNS. However, the OTA port doesn't show up (1.6.6 IDE, 2.0.0rc2 library, GenericESP).

*Update*: I've verified that `boards.txt` contains the OTA entries for the Generic board.

Any hints where to look?

And- lest I forget- awesome project, thank you  so much!

**Comment by me-no-dev** [comment]
1.6.6 is the only version that can not run OTA :) try 1.6.7

**Comment by andig** [comment]
Same problem with 1.6.7.

```
Booting
OTA server at: esp8266-06ac87.local:8266
Ready
IP address: 192.168.0.71

Even though the sketch is running (see above) I cannot see the OTA port. Running upload via OTA without previously selecting the port consequently fails.

**Comment by andig** [comment]
Hah! Problem solved. I had to disable "Auto" proxy settings in the IDE. No clue why board manager was fine, but now OTA is visible- thank you!

**Comment by me-no-dev** [comment]
it's a known issue with Arduino IDE which fails to see the boards after it has been open for a while. Restarting the IDE helps
