### ISSUE TITLE
No random() function

### ISSUE THREAD

**Issue by NicoHood** [esp8266/Arduino#1283]
Arduino uses `random` as identifier for a random function. However I just tested and rand() was available. Maybe someone should set a shortcut. It would be also interesting how relyable this random is (can it used for cryptography or better not)?

**Comment by Links2004** [comment]
we have random:
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Arduino.h#L267-L269

the question regarding cryptography its most depends on your seed.
the best seed src we have is this:

https://github.com/esp8266/Arduino/blob/master/cores/esp8266/esp8266_peri.h#L837-L841

**Comment by NicoHood** [comment]
random cannot be found within this program:
https://github.com/NicoHood/tweetnacl-usable/blob/arduino/randombytes.c#L11

Maybe because its .c not .cpp?

**Comment by Links2004** [comment]
rand != random,

**Comment by NicoHood** [comment]
Yes, if you replace it with random, it will not work anymore.

Also whats the difference between those functions?

**Comment by Links2004** [comment]
rand is part of the cstdlib from C
http://www.cplusplus.com/reference/cstdlib/rand/
needs for C:
```c
#include <stdlib.h>  
```
or
CPP:
```cpp
extern "C" {
#include <stdlib.h>  
}
```
random is a API function from Arduino
https://www.arduino.cc/en/Reference/Random
not working on C

and needs for CPP 
```cpp
#include <Arduino.h>  
```

the ESP supports both.
rand and random

**Comment by NicoHood** [comment]
Okay then it was my mistake, nevermind. Thx for the infos!
