### ISSUE TITLE
HTTPS doesn't send SNI

### ISSUE THREAD

**Issue by securityguy** [esp8266/Arduino#1285]
WiFiClientSecure doesn't appear to have the ability to send Server Name Indication (SNI), making it difficult to connect to SNI-enabled servers with multiple certificates.

**Comment by igrr** [comment]
axTLS now has support for SNI, so we can expose this feature via WiFiClientSecure.

**Comment by doom369** [comment]
Heh. Just got same problem and ticket already is here.

**Comment by emilfihlman** [comment]
So umm, dunno about you but SNI is still not sent, how can I force it?

**Comment by kotfarepra** [comment]
Any news on this ? Im using to connect to some websites that has SNI enabled and HTTPS forced . Would be great if it didnt softreset for those
