### ISSUE TITLE
160Mhz selection does not work

### ISSUE THREAD

**Issue by NicoHood** [esp8266/Arduino#1286]
I measured the speed of my code, but 160Mhz took the same time (via IDE menu). However this manual patch makes the speed doubled:
https://github.com/NicoHood/tweetnacl-usable/commit/5374a77b1a92a860f7654826105d31badfd3f288

Project to test this:
https://github.com/NicoHood/tweetnacl-usable

Using the board manager with version 2.0.0 and IDE 1.6.8 linux x64, self compiled (not much changed since official 1.6.7 release however).

**Comment by igrr** [comment]
This is fixed in https://github.com/esp8266/Arduino/commit/6620ec6e3610e30639d1eae1b6a3f60e93c26f70, released in 2.1.0
