### ISSUE TITLE
How to get the value of VVC over internal ADC?

### ISSUE THREAD

**Issue by DimIsaev** [esp8266/Arduino#1296]

**Comment by DimIsaev** [comment]
UP!

**Comment by Testato** [comment]
Do you mean VCC ?

It is explained in the documentation, find it in the readme.md also

**Comment by lnxbil** [comment]
For future reference and actual solution:

https://github.com/esp8266/Arduino/blob/master/doc/reference.md#analog-input

**Comment by lnxbil** [comment]
The ```analogRead``` code didn't work for me, I used ```ESP.getVcc();``` which read VCC (at least with approximately 10% accuracy)

**Comment by lnxbil** [comment]
I created a pull request for this #1509
