### ISSUE TITLE
WiFi softAP strange problem (2.0.0-stable)

### ISSUE THREAD

**Issue by bbasil2012** [esp8266/Arduino#1298]
I complled example WiFiAccessPoint.ino
I can connect to this example softAP from two different PC. it run fine
I can ping softAP IP address from all PC, it also fine
But I can't ping  one PC from the another !
ping 192.168.4.1 - Ok
ping 192.168.4.3 - request time out
ping 192.168.4.16 - request time out

Why?

**Comment by Links2004** [comment]
that is normal the ESP has no routing functionality,
Theoretically, it is possible but rewrite + rework and recompile of lwip.

**Comment by bbasil2012** [comment]
Ok, many thanks :)
