### ISSUE TITLE
OneWire library, when use  ESP8266 and DS18B20 with parasite power - pin must be cofigured as push-pull

### ISSUE THREAD

**Issue by KAlexK** [esp8266/Arduino#1307]
In OneWire library, when use ESP8266 and DS18B20 with parasite power pin must be configured as push-pull (DRIVER(NORMAL)) before use. Otherwise power from external pull-up resistor will be not enough to drive DS18B20 in conversion stage. For example this not work:
OneWire::OneWire(uint8_t pin)
{
	pinMode(pin, INPUT);
	bitmask = PIN_TO_BITMASK(pin);
	baseReg = PIN_TO_BASEREG(pin);
#if ONEWIRE_SEARCH
	reset_search();
#endif
}

But this will work:
OneWire::OneWire(uint8_t pin)
{
        pinMode(pin, OUTPUT); // Set to DRIVER(NORMAL)
	pinMode(pin, INPUT);
	bitmask = PIN_TO_BITMASK(pin);
	baseReg = PIN_TO_BASEREG(pin);
#if ONEWIRE_SEARCH
	reset_search();
#endif
}

**Comment by vlast3k** [comment]
I tried both - this approach, and invoking the constructor with the internal pullup - in both cases i get 85c.. how have you connected the DS18B20 ? I connect its vcc+gnd to gnd and the data pin to GPIO 14.
There is also another closed issue on this topic, but even also with a resitor it is giving the same results (though i would expect that no resistor is needed for parasitic power)

**Comment by KAlexK** [comment]
Yes. Vdd and GND pin of DS18B20 to GND. Data pin (DQ) to GPIO5 and pull-up by 3.3k resistor to power (3.3V). Work fine. I got 85C only if I did not connect Vdd pin of DS18B20 to GND. Try to connect Vdd pin to power and do not use parasite power mode.

**Comment by igrr** [comment]
Since we have removed OneWire from this repository in favour of the official version, please open the issue at https://github.com/PaulStoffregen/OneWire.
