### ISSUE TITLE
Question: How to make non-blocking http requests?

### ISSUE THREAD

**Issue by subodh-malgonde** [esp8266/Arduino#1311]
Hi, I am an ESP8266 beginner. I am trying to get a simple application up and running. I want to make an HTTP POST request to a server, and while that request is being processed I want to blink an LED. I know I can use a timer to blink the LED but since the http request is blocking the timer interrupt is never run. Is there a way to make a non-blocking http request?

**Comment by Links2004** [comment]
HTTPClient will not block any interrupts.
the current concept of the HTTPClient is not usable for async request.

but the timer or ticker will work fine, you can use them to blink with the LED

**Comment by subodh-malgonde** [comment]
Thanks!
