### ISSUE TITLE
WiFi debug not correct

### ISSUE THREAD

**Issue by onkelfunny** [esp8266/Arduino#1316]
the wifi-debug show a wrong ip address:
```
IPAddress apIP(192, 168, 1, 1);
WiFi.softAPConfig(apIP, apIP, IPAddress(255, 255, 255, 0));
WiFi.softAP("SSID");
```
Debug-Ouput:
```
mode : softAP(1a:fe:34:aa:4f:33)
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bin 100
```
i can connect and have a ip address in the network 192.168.1/24

**Comment by Links2004** [comment]
shut be fixed in #1323, there where a mode problem.

**Comment by Links2004** [comment]
can you retest it with the latest git?

**Comment by onkelfunny** [comment]
the wrong params are still present

**Comment by Links2004** [comment]
what is reported by:
```cpp
  IPAddress myIP = WiFi.softAPIP();
    Serail.print("AP IP address: ");
    Serail.println(myIP);
```
the ```dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)```
message is from the SDK so we can not change it.

**Comment by onkelfunny** [comment]
WiFi.softAPIP() shows the correct ip

**Comment by Links2004** [comment]
ok will close the issues, since we can not fix it.
