### ISSUE TITLE
OSX port

### ISSUE THREAD

**Issue by DaveCalaway** [esp8266/Arduino#1318]
Hi guys, i have a problem to detect the port on my mac.
I installed drivers for mac (https://goo.gl/hhkua7), but when i write in the terminal: 
 sudo ls -l /dev/cu.* 
i don't see the port in the list.
The Arduino IDE, indeed, don't see the port.

Can we help me?

I have nodemcu dev kit 0.9, Arduino IDE 1.6.7 and OSX 10.11.2 .

**Comment by DaveCalaway** [comment]
Solved: https://goo.gl/WHEDea

**Comment by asetyde** [comment]
good help but close issue
