### ISSUE TITLE
5V out to my hx711 sensor ,can not boot?

### ISSUE THREAD

**Issue by EagleShi** [esp8266/Arduino#1322]
SCK = sck;
    DOUT = dout;
    set_amp(amp);
    COEFFICIENT = co;
    pinMode(SCK, OUTPUT);//14
    pinMode(DOUT, INPUT);//15
    digitalWrite(SCK, LOW);
    read();

it's can not boot ,why ?
my board is esprduino

**Comment by Links2004** [comment]
GPIO15 need too be low to boot, may your sensor pull it up.
https://github.com/esp8266/Arduino/blob/master/doc/boards.md#minimal-hardware-setup-for-bootloading-and-usage

**Comment by EagleShi** [comment]
Links2004,thank you for your help,it's working now.i changed GPIO 15 to GPIO 16.thanks!
