### ISSUE TITLE
HTTPClient does not support chunked HTTP responses

### ISSUE THREAD

**Issue by furyfire** [esp8266/Arduino#1324]
Chunked HTTP responses are not parsed in the ESP8266HTTPClient lib leading to confusing return data from a http.getString() call.

Sample URL with chunked data. 
http://api.openweathermap.org/data/2.5/weather?q=London,uk&appid=2de143494c0b295cca9337e1e96b00e0

ESP8266HTTPClient should abstract this in the implementation

https://en.wikipedia.org/wiki/Chunked_transfer_encoding

**Comment by Links2004** [comment]
will implement it, after I finish my WiFi code rework.

**Comment by igrr** [comment]
Released in 2.1.0
