### ISSUE TITLE
Storing Persistent Data in ESP8266

### ISSUE THREAD

**Issue by sukhmeet032795** [esp8266/Arduino#1325]
I am trying to store data permanently in ESP8266. I found out two ways of doing so i.e. Writing in EEPROM or storing a txt file to the ESP and reading the data later on from it.I am using Arduino 1.6.7 along with esp8266. What is the best way to write persistent data to ESP8266 and an example to execute it?

**Comment by subodh-malgonde** [comment]
For EEPROM you can checkout the EEPROM library https://github.com/esp8266/Arduino/tree/master/libraries/EEPROM There are examples on how to read/write data.

**Comment by sukhmeet032795** [comment]
Thanks Subodh....it helped.....
