### ISSUE TITLE
WiFi.SoftAP(ssid, password) still not working in v2.0.0

### ISSUE THREAD

**Issue by EnochHwang** [esp8266/Arduino#1327]
I think I've found the problem (or solution).
When the password length is less than 8 characters, then the softAP(ssid, password) will NOT set to the given ssid. The command will only work if the password length is 8 characters or more.

Please verify that this is the case.

-----------------------
I read in other posts that v2.0.0 has fixed the problem with softAP not changing the ssid and/or password. It was working for me last week, but now it is no longer working. Whatever ssid I use in the WiFi.softAP command, the WiFi I get is always the original ESP_DAFA99. I'm using Arduino IDE v1.6.7. How should I debug this?
The relevant part of my set up code is just the standard...
 
  char ssid[] = "ABC";
  char password[] = "123"
  WiFi.mode(WIFI_AP);
  WiFi.softAP(ssid, password);
  server.begin();

**Comment by tzapu** [comment]
i can cofirm the same behaviour @EnochHwang , you need to set a valid password for the configuration to be updated.

**Comment by Links2004** [comment]
in #1323 i add a check for this and softAP will return false if password is to short.
https://github.com/esp8266/Arduino/pull/1323/files#diff-49f133721a21472dcdbc6beb4394f329R96
