### ISSUE TITLE
OTA update: passing -auth incorrectly to espota.py script

### ISSUE THREAD

**Issue by dannybackx** [esp8266/Arduino#1340]
See findings on http://www.esp8266.com/viewtopic.php?f=33&t=7136&p=37555#p37552 , and my reply to it.
The -auth parameter doesn't appear to get passed to the script the right way.
Krzysztof reported two cases, I found a slightly different scenario.

Could actually be two bugs : 
- -auth doesn't get passed at all with "Tools->Upload using : OTA"
- (in my case) inconsistent setting of "Tools->Upload using:" and "Tools->Port" (one indicating Serial, the other indicating OTA), the IDE never asked me for a password

  Danny

**Comment by igrr** [comment]
We should remove "Upload using" menu since it is not needed starting from Arduino 1.6.7.
#1702
