### ISSUE TITLE
Enabling exception handling

### ISSUE THREAD

**Issue by grahamehorner** [esp8266/Arduino#1351]
please consider enabling exception handling, for better developer experience and allowing try { } catch(...) { } which would enhance overall stability and reduce code when developing libraries.  

'exception handling disabled, use -fexceptions to enable'
##

**Comment by devyte** [comment]
I'm wondering if this will be implemented? I was rather surprised to find out exceptions are disabled.
Is there a specific reason for disabling?

**Comment by smitthhyy** [comment]
Please look at enabling this. It should be part of the core. Thanks. PS: This is a vote to get it included ASAP! (Just in case that's not clear :) )

**Comment by devyte** [comment]
I would like to point out that exception handling increases RAM usage. It
may not be appropriate for all use cases, so enabling it is not as simple
as flipping a switch.

**Comment by besyildiz** [comment]
is not there any offer, how it is?

**Comment by devyte** [comment]
Temporarily assigning to @d-a-v to put the issue on the map, per his exception playground.

**Comment by artus9033** [comment]
Any progress on this?

**Comment by ascillato** [comment]
Hi, I'm also very interested on this.

**Comment by d-a-v** [comment]
There is some work about that in https://github.com/d-a-v/esp-quick-toolchain/

**Comment by earlephilhower** [comment]
Exceptions now a menu option, closing.
