### ISSUE TITLE
ESP.deepSleep causes "hang" after wakeup?

### ISSUE THREAD

**Issue by dariopb** [esp8266/Arduino#1363]
ESP201, Arduino esp8266 (using platformio, but same happens if I compile using the arduino env), XDP pin connected to RST

void setup() {
  Serial.println("Setup");
  ESP.deepSleep(5 * 1000000);
}

```
 ets Jan  8 2013,rst cause:1, boot mode:(3,7)

load 0x4010f000, len 1264, room 16
tail 0
chksum 0x42
csum 0x42
~ld
Setup
```

Seems the chip enters deep sleep and then resets correctly, but:

```
ets Jan  8 2013,rst cause:5, boot mode:(3,7)
ets_main.c
```
and my setup code is not reached...

How can I troubleshoot the issue?

**Comment by Links2004** [comment]
gpio 16 is connected to ch_pd?

**Comment by dariopb** [comment]
gpio 16 is connected to RST.

**Comment by dariopb** [comment]
That was it! I went and looked and it seems the board i am using had **RST connected to CD_PD!** After removing this tie deep sleep and restart works as expected!  Thanks Links2004!
