### ISSUE TITLE
SoftAP SSID not honored?

### ISSUE THREAD

**Issue by andig** [esp8266/Arduino#1367]
Running 2.0.0rc2, starting the SoftAP via 

	const char* ap_default_ssid = "esp8266"; // Default SSID
	const char* ap_default_psk = "00000000"; // Default PSK
	
	WiFi.mode(WIFI_AP);
	delay(10);

	WiFi.softAP(ap_default_ssid, ap_default_psk);

I do see an access point named `AI-THINKER-` plus chip id. I was expecting esp8266?

**Comment by Links2004** [comment]
the staging is older then the stable.
it fixed in stable and in the git version.

#1356
#1054
#1103
#1123
#1141

**Comment by andig** [comment]
Will check, thank you. Might make sense to remove staging now that stable is available.
