### ISSUE TITLE
PWM not working always HIGH or LOW 2.1 git version

### ISSUE THREAD

**Issue by tontito** [esp8266/Arduino#1382]
Hi,

PWM not working always HIGH or LOW 2.1 git version 
SDK 1.5

int ledPin = 5;    // LED connected to digital pin 5
void setup() {
  pinMode(ledPin, OUTPUT);
  analogWriteRange(255);
}

void loop() {
  for (int fadeValue = 0 ; fadeValue <= 255; fadeValue += 5) {
    analogWrite(ledPin, fadeValue);
    delay(30);
  }

  for (int fadeValue = 255 ; fadeValue >= 0; fadeValue -= 5) {
    analogWrite(ledPin, fadeValue);
    delay(30);
  }
}

Led high or low

**Comment by SmartArduino** [comment]
It's worked in my case using your code. I use ESP-13 based module(ESPduino).

**Comment by tontito** [comment]
İ'm using esp-07 and esp-12 

Not working pwm

Analogwrite (50-100-200) always High
Analogwrite (0) low

**Comment by SmartArduino** [comment]
Change to 2.0 version may solve your prolem.
As I'm using pwm to control a rgb led light via tcp client, I found it worked well in 2.0 version(sdk is 1.3), but something not good under 2.1 version(sdk is 1.5).

**Comment by tontito** [comment]
i tested 2.0 stable version it`s worked but 2.1 github version not working.

**Comment by tablatronix** [comment]
Same problem here, spent all day thinking I was doing something wrong.
Rolled back to 2.0 and its working fine.

**Comment by tablatronix** [comment]
revert 1ae423021a3327b416919b95c17de6eafeffcffc

**Comment by tablatronix** [comment]
typo fix works for me now
https://github.com/esp8266/Arduino/commit/1ae423021a3327b416919b95c17de6eafeffcffc#commitcomment-15344434

**Comment by tontito** [comment]
fix works for me now
1ae4230#commitcomment-15344434

**Comment by tablatronix** [comment]
Can we get this fix merged?
