### ISSUE TITLE
help with the installation of libraries

### ISSUE THREAD

**Issue by Amayak777** [esp8266/Arduino#1400]
doing everything so as described here https://github.com/esp8266/Arduino#installing-with-boards-manager, before the library was in the folder -С:\Users\ХХХ\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\libraries. I tried to download GitHab project gives many errors at compile time. Compared with the downloaded ZIP archive GitHab and the library project that I had - I found a lot of fixes and changes in the structure of folders. I suspect that this is a completely different project. What to do? I can not build the project https://gist.github.com/4refr0nt/829052635894da0f5715
##

**Comment by Amayak777** [comment]
You may need to reinstall the library, how to do it?

**Comment by Links2004** [comment]
```С:\Users\ХХХ\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\libraries```
is for core library only if you add own stuff there it will be deleted on every update of the core you do.

if you want to add libraries to your Arduino follow this guide:
https://www.arduino.cc/en/Guide/Libraries

**Comment by Amayak777** [comment]
I installed all the libraries by keyword ESP. Don't know what else to do? Probably a library, esp not updated.
here is what I have installed, see figure
![default](https://cloud.githubusercontent.com/assets/16634931/12374118/1deb6c2a-bca3-11e5-97e8-7e6b8f4163f6.jpg)

**Comment by Amayak777** [comment]
when you remove the IDE library are not deleted. How to delete all settings and files? to try to re-install ESP the library

**Comment by Amayak777** [comment]
1) Deleted all the folder:C:\Users\User\AppData\Roaming\Arduino15, E:\Users\User\Documents\Arduino and the IDE. 2) Downloaded from the IDE website and re-installed version 1.6.5. 3)write in URL: http://arduino.esp8266.com/package_esp8266com_index.json. 4) now in the library Manager does not find the project titled esp8266. What to do?

**Comment by Amayak777** [comment]
here is my project Manager with filter esp8266
![default](https://cloud.githubusercontent.com/assets/16634931/12379084/06626a38-bd64-11e5-99ff-679d827a6b23.jpg)

**Comment by Amayak777** [comment]
Кто-нибудь попробуйте сами установить ядро.

**Comment by igrr** [comment]
The first three steps you did were correct, but you need to use Boards Manager to install the package, not Library Manager. It's in `Tools > Board > Boards Manager...` menu.
Should look like this:

<img width="800" alt="screen shot 2016-02-29 at 12 15 19" src="https://cloud.githubusercontent.com/assets/4349050/13390249/4ed8bb64-dede-11e5-8ff8-7a3a1d082247.png">
