### ISSUE TITLE
Generating a pulse 1Hmz?

### ISSUE THREAD

**Issue by sabas1080** [esp8266/Arduino#1402]
Hi

You could generate a pulse of 1 MHz with the ESP8266 ?

Is there any example?

Thanks
##

**Comment by Links2004** [comment]
ESP supports only Software PWM 1Mhz is to high for this.
based on how long the pulse need to by may us SPI clock.
you can get up to 512 pulses with up to 80Mhz when you send 64Byte.

**Comment by devyte** [comment]
The I2S interface could support such high frequency output. 
Closing per #3655 .
