### ISSUE TITLE
Variable unused (Staging 2.1.0 - 1.5.0 sdk)

### ISSUE THREAD

**Issue by asetyde** [esp8266/Arduino#1407]
![screen shot 2016-01-11 at 15 42 11](https://cloud.githubusercontent.com/assets/6162152/12236440/0e94891e-b87a-11e5-9e5c-40c0c659cd91.png)

**Comment by Links2004** [comment]
it only used when DEBUG_ESP_WIFI is defined.

**Comment by asetyde** [comment]
ah ok . thanks
