### ISSUE TITLE
Can't connect to all SSIDs on Multi-SSID AP

### ISSUE THREAD

**Issue by franklinvv** [esp8266/Arduino#1412]
I own a D-Link DAP-2660, which supports 8 different SSIDs per band. However, using the Arduino core on the ESP8266, I can only connect to the primary SSID, and not to the remaining 7 SSIDs.

The result that WiFi.status() returns is usually either 4 (WL_CONNECT_FAILED) or 0 (WL_IDLE_STATUS).

Using the default AT firmware, this is no problem at all, so it seems to be in the Arduino core.

**Comment by Links2004** [comment]
which version of the core do you use?

**Comment by franklinvv** [comment]
According to the boars manager in the Arduino IDE, it's 2.0.0.

**Comment by Links2004** [comment]
WiFi has been has been reworked and and the SDK has been updated in 2.1.0-rc1 try using staring.

**Comment by franklinvv** [comment]
Indeed, with 2.1.0-rc1, this seems to be working properly. Thanks! I'm closing this issue.
