### ISSUE TITLE
Using ESP8266 with an old style TTY that uses 50 baud and 5 bit code

### ISSUE THREAD

**Issue by ulflan** [esp8266/Arduino#1418]
Hi! 

I would like to use a baud rate of 50 bit /second. (In order to hook up and print data on an old TTY.) 
I guess one can’t use AT-commands to select this odd low baud rate? But can one flash (program) some instructions to Esp8266 in order to transmit data using the built in UART or is 50 bit/s too slow?
##

**Comment by penfold42** [comment]
You could use softwareSerial library to bit bash it if the inbuilt uart won't go that low.

**Comment by devyte** [comment]
Closing per #3655 .
