### ISSUE TITLE
Install to Arm (Odroid U3)

### ISSUE THREAD

**Issue by vbextreme** [esp8266/Arduino#1421]
If you want to install esp core to Arm with arduino IDE:
1. Open Arduino IDE and Boards manager link: http://arduino.esp8266.com/stable/package_esp8266com_index.json
2. Boards Manager and install esp8266
3. git https://github.com/pfalcon/esp-open-sdk and make standalone=y
4. copy all file and directory from /esp-open-sdk/xtensa-lx106-elf in to /packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2
5. find platform.txt in /packages/esp8266, search this line

```
## Combine gc-sections, archives, and objects
recipe.c.combine.pattern="{compiler.path}{compiler.c.elf.cmd}" {compiler.c.elf.flags} {compiler.c.elf.extra_flags} -o "{build.path}/{build.project_name}.elf" -Wl,--start-group {object_files} "{build.path}/arduino.ar" {compiler.c.elf.libs} -Wl,--end-group  "-L{build.path}"
```

edit this

```
"{build.path}/arduino.ar"
```

with

```
"{build.path}/core/arduino.ar"
```
1. git https://github.com/igrr/esptool-ck and make
2. copy esptool in to /packages/esp8266/tools/esptool/0.4.6

ok open Arduino IDE select esp board and make your project
##

**Comment by devyte** [comment]
Thank you for the instructions.
Closing per #3655 .
