### ISSUE TITLE
OTA End Failed on spiffs upload

### ISSUE THREAD

**Issue by hallard** [esp8266/Arduino#1422]
Hi there,
I'm using OTA for long time without any problem in command line with espota.py.

Starting few days, I'm not able to upload SPIFFS anymore (sketch upload works fine) and I didn't changed anything in my code related to OTA
```shell
build0c3ea91603fe6795abd4c568f834b507.tmp # ota -i 192.168.1.229 -r s- -f ../build0c3ea91603fe6795abd4c568f834b507.spiffs/MultiSensor.spiffs.bin -a ch2i_MultiSensor
Uploading: [============================================================] 100% Done...

12:36:29 [ERROR]: No Result!
build0c3ea91603fe6795abd4c568f834b507.tmp # 
```
and the debug output on ESP serial is
```
Update Started
Update Error[4]: End Failed
```

Am I the only one experiencing this issue ? I'm using latest git + Arduino 1.6.7 + OTA Class

```arduino
 // OTA callbacks
  ArduinoOTA.onStart([]() { 
    LedRGBON(COLOR_PURPLE);
    DebuglnF("Update Started");
    ota_blink = true;
  });

  ArduinoOTA.onEnd([]() { 
    LedRGBOFF();
    DebuglnF("Update finished restarting");
  });

  ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
    if (ota_blink) {
      LedRGBON(COLOR_PURPLE);
    } else {
      LedRGBOFF();
    }
    ota_blink = !ota_blink;
    //Serial.printf("Progress: %u%%\n", (progress / (total / 100)));
  });

  ArduinoOTA.onError([](ota_error_t error) {
    LedRGBON(COLOR_RED);
    Debugf("Update Error[%u]: ", error);
    if (error == OTA_AUTH_ERROR) DebuglnF("Auth Failed");
    else if (error == OTA_BEGIN_ERROR) DebuglnF("Begin Failed");
    else if (error == OTA_CONNECT_ERROR) DebuglnF("Connect Failed");
    else if (error == OTA_RECEIVE_ERROR) DebuglnF("Receive Failed");
    else if (error == OTA_END_ERROR) DebuglnF("End Failed");
    ESP.restart(); 
  });
```

**Comment by reaper7** [comment]
did you update ESP8266FS to 0.2.0?
https://github.com/esp8266/Arduino/blob/master/doc/filesystem.md#uploading-files-to-file-system

https://github.com/esp8266/Arduino/commit/b4ef8cf0fab1f28ae1297f8d08512df92352328f

**Comment by hallard** [comment]
@reaper7 
Nope, I will thanks to mention
But not sure it will solve my problem, because I did not mention but SPIFFS upload from Arduino IDE (Serial) works fine, it's just from OTA with command line with espota that I've got this problem (can't test OTA from IDE device does not appears on my Windows)

**Comment by hallard** [comment]
Updated, but as I suspected, same thing SPIFFS over OTA ends with error, so strange...

**Comment by andig** [comment]
I've just noted this: https://github.com/esp8266/Arduino/issues/1450 However I can only reproduce if the esp is busy.

**Comment by hallard** [comment]
yeah, correct if browser is making request to ESP during upload it sometimes fail closing browser and this problem went away :-)
