### ISSUE TITLE
SoftwareSerial

### ISSUE THREAD

**Issue by RussMathis** [esp8266/Arduino#143]
How would I go about connecting a second serial device to digital pins? Trying to connect a RDM6300 RFID read but have had no success on the UART (rx/tx) lines in. Maybe some SoftwareSerial exists for the ESP?

**Comment by igrr** [comment]
UART1 is TX only, it may be used to print debug messages.

You can either use GPIO1/3 pins with UART0 (which are normal pins you use to upload the sketch), or call ```Serial.swap();``` in your setup() function, which changes the UART pins to use GPIO13 and GPIO15 as RX and TX.

By using the swap function you can have your usb-serial connected to GPIO1/3 for sketch upload and your RFID reader connected to GPIO13/15 at the same time.

**Comment by RussMathis** [comment]
Can you call Serial.swap() repeatedly in other places of code besides setup(). For example, when data arrives at GPIO13/15, (RFID scanned) then output back to the GPIO1/3 pins by calling Serial.swap() again?

By the way, great job on this project! The ESP is a fantastic new arena for development. For those like myself with low level skills suited to the Arduino your work has opened a larger arena to explore. THANK YOU VERY MUCH.

**Comment by RussMathis** [comment]
If seems that GPIO15 must be grounded to run/start the chip? How would you go about wiring pin GPIO15 for use with UART1? Common closed on a relay that would be changed to open from setup()?
Any input would help. Thanks!

**Comment by duncan-a** [comment]
The GPIOs should be pulled up or down via a resistor (around 10K ohm is
normally adequate) so, for GPIO15 to conform with the bootup requirement,
connect it to ground via a 10K - the Serial signal will overcome that
easily in use.

**Comment by igrr** [comment]
> Can you call Serial.swap() repeatedly in other places of code besides setup()

Yes you can — it will swap between GPIO3/1 and GPIO13/15.

**Comment by RussMathis** [comment]
Having issue with swap: currently have 10K from GPIO15 to Gnd. 
The following code works and sends "test" to the monitor window once per second;
void setup(){
    Serial.begin(9600);
    while(true){
        Serial.println("test");
        delay(1000);
    }
}
void loop(){}

However, this code does not output print "test" to the monitor window, in face nothing
is ever seen in the monitor window;
void setup(){
    Serial.begin(9600);
    while(true){
        Serial.println("test);
        Serial.flush();
        Serial.swap();
        delay(1000);
        Serial.swap();
    }
}

What is wrong?

**Comment by igrr** [comment]
Do you have the usb-serial RX line connected to the GPIO15 in this case?

**Comment by RussMathis** [comment]
I finally got the example I posted to work by updating the hardware folder. 

... I'm thinking it might be my version of the ESP IDE. I've been trying to get the latest version since my version does not have Serial2 defined in the HardwareSerial.h file.
Finally, after getting the latest source Download.zip from: https://github.com/rogerclarkmelbourne/arduino-esp8266/, 
 and putting it in my sketch folder's hardware directory I can compile and upload successfully from Arduino software 1.6.3.

However, Visual Micro does not seem to work since it can't find the esptool to upload. Working on that now...

Any input?

Thanks for the help iggr

**Comment by igrr** [comment]
Sorry I don't have any experience with Visual Micro...

**Comment by flyandi** [comment]
This is older but I have a question regarding the swap, too. Is it ok, to constantly between the two pin assignments, e.g. 

Read from TX/RX 
Swap
Read
Swap
Read .. Write
Swap
Read
...
and so on?

**Comment by Links2004** [comment]
@flyandi  you can swap as often you like.
but keep in mind that the ```write``` and ```read``` are asynchronous.
also you may loos bytes of the RX from the non active part. 

if you use ```flush``` after ```write``` and 
you need add some ```delay```  before ```read``` then it shut work.

**Comment by flyandi** [comment]
Cool. Thanks Links2004.
