### ISSUE TITLE
no calibration, and scan throws exception

### ISSUE THREAD

**Issue by stevescot** [esp8266/Arduino#1434]
if you run these commands in setup, then on the second run (with Calibration disabled) the ESP chip will crash. 
Is there some way to read whether calibration / wifi are enabled  

WiFi.mode(WIFI_STA);
WiFi.disconnect();
delay(100);
int n = WiFi.scanNetworks();//crash here.
Serial.println("rebooting without calibration");
ESP.deepSleep(1000,  WAKE_NO_RFCAL);
##

**Comment by stevescot** [comment]
note also - once NO_RFCAL has been set, default is without calibration

**Comment by devyte** [comment]
I am doing scans in my app, and it is working correctly with latest git. Closing.
