### ISSUE TITLE
Missing uart defines in tools/sdk/include/user_interface.h

### ISSUE THREAD

**Issue by tbnobody** [esp8266/Arduino#1436]
I tried to control a WS1812 LED using Serial1. To do this, it's required to invert the uart signal. 

In the original file (I think, https://raw.githubusercontent.com/espressif/ESP8266_IOT_PLATFORM/master/include/driver/uart_register.h) there is a define called 
```#define UART_TXD_INV                        (BIT(22))```
to invert the uart signal.
In the file for the arduino environment which is located here: tools/sdk/include/uart_register.h
this define, and also all other invert defines are missing.

Was this done on purpose or is this a mistake?

**Comment by Links2004** [comment]
its there but not in the SDK notation
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/esp8266_peri.h#L262

**Comment by me-no-dev** [comment]
```cpp
U0C0 |= (1 << USTXI);
```

**Comment by tbnobody** [comment]
Oh sorry. Didn't see this define when looking at the source. Will close that issue.
