### ISSUE TITLE
Boot.bin Esp.getBootVersion() wrong return value and boot.bin old 1.3

### ISSUE THREAD

**Issue by tontito** [esp8266/Arduino#1439]
Hi,

Esp.getBootVersion(); return value 31; (boot version 1.3);

with Esp flasher boot.bin (v1.5)
Esp.getBootVersion(); return value 5;

and flash my sketch with arduino ide 
Esp.getBootVersion(); return value 31; again

How Can I update boot.bin arduino ide sdk ???

(Sorry my english)

**Comment by Links2004** [comment]
there is no "boot.bin" when you use the Arduino SDK.
we use eboot.

**Comment by tontito** [comment]
Ohh sorry. I don`t now. thank you
