### ISSUE TITLE
How to compile with HTTP Debug 

### ISSUE THREAD

**Issue by vlast3k** [esp8266/Arduino#1443]
Excuse me for the stupid question, but i cannot make my sketch compile with the debug macros turned on by default
I want to make the HTTP Update dump debug statements by default and up to now the only way i succeeded in doing it is by adding
#define DEBUG_ESP_HTTP_UPDATE
#define DEBUG_ESP_PORT Serial

to ESP8266httpUpdate.h
Shouldn't it work if i just add them to the beginning of my sketch

**Comment by Links2004** [comment]
no it not work when you add it to sketch.
check:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

**Comment by vlast3k** [comment]
Thank you !
