### ISSUE TITLE
Crash on WiFi.mode(WIFI_AP)

### ISSUE THREAD

**Issue by odilonafonso** [esp8266/Arduino#1456]
I get the WiFiAccessPoint.ino from IDE examples and do some modifications.
(the sketch is attached
[WiFiAccessPoint.zip](https://github.com/esp8266/Arduino/files/93372/WiFiAccessPoint.zip)
)

I got this when try to set the mode to WIFI_AP:

WiFi.enableAP(true):true

WiFi.getMode():3
WiFi.mode(WIFI_AP):
Exception (28):
epc1=0x4000df2f epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000033 depc=0x00000000

ctx: cont 
sp: 3fff0290 end: 3fff0720 offset: 01a0

>>>stack>>>
3fff0430:  3fff1558 0000015d 40239030 4020b9f9  
3fff0440:  40211599 00000000 00000000 00000484  
3fff0450:  00000033 00000010 40211e35 3ffed64c  
3fff0460:  3fff14e8 00000000 3ffed64c 3fff12a0  
3fff0470:  00000004 40211d81 3ffed64c 00000030  
3fff0480:  3ffe8ec7 0188d8fd 00000000 3ffe9af0  
3fff0490:  3fff158a 00000000 3ffe8ec7 3ffe8ec7  
3fff04a0:  00000033 3ffed678 3fff0ff8 00000000  
3fff04b0:  402138c3 3ffedd20 3ffeddf8 0000010f  
3fff04c0:  00000001 3fffc718 3fff05b0 08000000  
3fff04d0:  402135a0 40213574 08000000 00000000  
3fff04e0:  4021535d 00000121 ffffffff 0007f000  
3fff04f0:  3ffed6d0 40215324 00000001 00000012  
3fff0500:  4021356a 402134d1 00000003 3ffedd20  
3fff0510:  40213511 00000001 00000012 0000010f  
3fff0520:  40213a04 00000001 3ffedd20 0000010f  
3fff0530:  4021348c 3ffed7c0 00000000 00000000  
3fff0540:  3ffed6d0 3ffed7c0 40229804 402156e3  
3fff0550:  3fff0590 3ffed7c0 40229804 0000010f  
3fff0560:  40227e7d 3ffedd20 40229804 3ffee910  
3fff0570:  3fff0680 3fff0ff8 3fff0ff8 3fff2308  
3fff0580:  3fff0590 40229804 3fff0ff8 40229a71  
3fff0590:  00000000 00000000 00000100 40229a12  
3fff05a0:  40213743 3ffedd20 40229804 3fff0ff8  
3fff05b0:  3fff0680 3ffedd20 4010574a 3ffef6cc  
3fff05c0:  402135f9 3ffedd20 00000001 3ffe850e  
3fff05d0:  00000001 3ffedd20 0000001c 402275bb  
3fff05e0:  402153b3 402153c1 3fff0ff8 00000001  
3fff05f0:  00000004 402153f8 402135b0 0007e000  
3fff0600:  4021368c 3fff0ff8 00000001 3ffe850e  
3fff0610:  40228094 40228062 3fff0ff8 00000000  
3fff0620:  40215223 00000002 00000010 0000001c  
3fff0630:  40227359 000000bb 000000b9 0000007d  
3fff0640:  402274c5 00000002 00000001 3ffe850e  
3fff0650:  3fff1e78 4022753a 00000002 3ffef5a0  
3fff0660:  40203499 3ffef5a0 3ffef6cc 40206bb0  
3fff0670:  00000020 3ffef5a0 3ffef6cc 4020242d  
3fff0680:  3ffef6cc 00000001 3ffe885c 40206b24  
3fff0690:  3ffef6cc 00000008 3ffe868c 3ffef6f4  
3fff06a0:  3fffdad0 00000009 3ffef6cc 40205e2d  
3fff06b0:  3ffe885b 00000000 3ffef6cc 40205e2d  
3fff06c0:  3ffe8684 00000003 3ffef6cc 40206bfc  
3fff06d0:  40227312 3ffef6cc 3ffef6cc 3ffef6f4  
3fff06e0:  3fffdad0 00000000 3ffef6cc 40202b85  
3fff06f0:  feefeffe 00000000 3ffef6cc 40202c97  
3fff0700:  feefeffe feefeffe 3ffef6ec 4020672b  
3fff0710:  feefeffe feefeffe 3ffef700 40100114  
<<<stack<<<
J�
�7!a!�

**Comment by Tibus** [comment]
I've the same error... did you fix it?
