### ISSUE TITLE
Watchdog reset

### ISSUE THREAD

**Issue by GerryKeely** [esp8266/Arduino#146]
While the watchdog reset(feed) function compiles ok it does not appear to be working.
I presume this is because  Espressif have not yet released it as an API  rather than it being an ESP8266Arduino issue..

Is this correct?

Gerry

**Comment by tomaja** [comment]
From README:
> "ESP.wdtEnable(), ESP.wdtDisable(), and ESP.wdtFeed() provide some control over the watchdog timer."

*ESP.wdtFeed()* shoud probably do the job.

**Comment by igrr** [comment]
@GerryKeely could you please post the sketch you are using?

**Comment by HenryCoarite** [comment]
Iggr, es usted un capo.

**Comment by HenryCoarite** [comment]
Good afternoon; And how can I know when I rebooted the ESP8266 by WDT?
