### ISSUE TITLE
SPIFFS erase or overwrite file

### ISSUE THREAD

**Issue by aug2uag** [esp8266/Arduino#1465]
I have a file `f.txt` that holds configurations, and I'd like to reset them based on user actions.

The docs don't have a file delete; and I noticed the following fails to erase the data

```
File f = SPIFFS.open("/f.txt", "w+");
// clear configs
f.println("");
ESP.restart();
```

The reset with the above doesn't operate as intended. Would this operation be appropriate for the intended outcome or another solution? Thanks Ivan and the team for the excellent resources you've developed.

**Comment by Links2004** [comment]
use this one ;)
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/FS.h#L119

**Comment by aug2uag** [comment]
Hey thanks!

**Comment by romanseidl** [comment]
```
bool remove(const char* path);
bool remove(const String& path);
```
now on https://github.com/esp8266/Arduino/blob/master/cores/esp8266/FS.h#L120 as lines move...
