### ISSUE TITLE
Arduino IDE 1.6.7 can not found include files

### ISSUE THREAD

**Issue by odilonafonso** [esp8266/Arduino#1466]
Yesterday, after installing the 1.6.7 release of the Arduino IDE, I could run for a while.
For this, I went to the installation directory and directly executed the "arduino" file.
After however, run the shell "install.sh", to generate a desktop shortcut, the compiler no longer find the include files - "ESP8266WiFi.h" and others.
Can anyone tell me what I did wrong?
What did the install.sh shell may have changed so that things no longer work?
After I run it, I got:
Adding desktop shortcut, menu item and file associations for Arduino IDE... done!

**Comment by odilonafonso** [comment]
Well, I tried again, something happened - returned to work.
I am seriously considering to downgrade to 1.6.5 .....

**Comment by asetyde** [comment]
There is no problem with 1.6.7 , please clean all data  and reinstall it

**Comment by odilonafonso** [comment]
Hi asetyde,
Can you compile the .ino attached, please ?
[testfun.zip](https://github.com/esp8266/Arduino/files/95921/testfun.zip)

**Comment by asetyde** [comment]
i’m not sure you can do this …

**Comment by asetyde** [comment]
i'm not ve this problem because i use c old style common write : 

![screen shot 2016-01-19 at 14 32 29](https://cloud.githubusercontent.com/assets/6162152/12419966/a83a0c20-beb9-11e5-8153-3388c658890b.png)

**Comment by odilonafonso** [comment]
Ok, thanks..

**Comment by itsjustvenky** [comment]
@odilonafonso  Things have changed recently. So if you have function and it needs to be declared at the top.

void test();

and then you can refer it any where in the code, else the called function should be on top of calling function.

**Comment by odilonafonso** [comment]
Hi itsjustvenky,
Try this:
```
#include <ESP8266WiFi.h>
#define LED 2
void test1(){
  pinMode(LED, OUTPUT);
  test2(LED);
  test3(LED, LOW);
}
void test2(int led){
  digitalWrite(led, HIGH);
  delay(500);
}
bool test3(int led, int what){
  digitalWrite(led, what);
  delay(500);
  return true;
}
void setup() {
  // put your setup code here, to run once:
  test1();
}
void loop() {
  // put your main code here, to run repeatedly:
  test2(LED);
  test3(LED, LOW);
}
```

**Comment by odilonafonso** [comment]
And try this:
```
#include <ESP8266WiFi.h>
#define LED 2
void test2(int);
bool test3(int, int);
void test1(){
  pinMode(LED, OUTPUT);
  test2(LED);
  test3(LED, LOW);
}
void test2(int led){
  digitalWrite(led, HIGH);
  delay(500);
}
bool test3(int led, int what){
  digitalWrite(led, what);
  delay(500);
  return true;
}
void setup() {
  // put your setup code here, to run once:
  test1();
}
void loop() {
  // put your main code here, to run repeatedly:
  test2(LED);
  test3(LED, LOW);
}
```
The problem is with the pre-processor...
The "mens" are working to solution.
https://github.com/arduino/arduino-builder/issues/68
