### ISSUE TITLE
Is LwIP in the base firmware or in the SDK?

### ISSUE THREAD

**Issue by plinioseniore** [esp8266/Arduino#147]
Hi,

I'm trying to collect information on this ESP8266 SoC, as far as I can see the LwIP stack is included in the EspressIf SDK as well into this porting of the Arduino IDE.  At same time, looks that the base firmware/bootloader included in the ESP8266 handle the AT commands.

So, what's is inside the ESP8266 base firmware that can be flashed on this module? Does it contains a full IP stack (it should, otherwise AT commands will be useless)?
Are we loading the IP stack twice, once in the SDK and once embed into the base firmware?

Thanks

**Comment by igrr** [comment]
The bootloader included in the ESP does not handle AT commands. This is usually done using a special "AT" firmware which is installed into the flash memory. The sketches replace any previously installed firmware, so at the moment nothing is duplicated.
