### ISSUE TITLE
gcc function auto-prototyping don't work?

### ISSUE THREAD

**Issue by gorec2005** [esp8266/Arduino#1472]
Hi!
have two .ino
first :

```
void somefunction()
{
}
setup()
{
}
loop()
{
somefunction();
}
```
and second:
```
setup()
{
}
loop()
{
somefunction();
}
void somefunction()
{
}
```
first work ok, but second no ( error: 'somefunction' was not declared in this scope) if used latest ide from git...
but some time ago (i think ~1.6.5 version did work)...

**Comment by igrr** [comment]
This issue is tracked in [arduino-builder](https://github.com/arduino/arduino-builder/issues/68) and there is a [pull request](https://github.com/arduino/ctags/issues/4) which fixes this issue.

**Comment by gorec2005** [comment]
ok. so i close this issue...
