### ISSUE TITLE
json library esp8266

### ISSUE THREAD

**Issue by qblacksheep** [esp8266/Arduino#1473]
Hi, do you know any json library on esp 8266? I use websockets library too. 
I tried to compile example from this library: https://github.com/bblanchon/ArduinoJson
but i can't. Here is compiler report:
![json](https://cloud.githubusercontent.com/assets/16727999/12455941/fb6bc264-bf9d-11e5-86d5-fcd8d3b37c65.jpg)

**Comment by Duality4Y** [comment]
maybe you should post your code and full error output.
do it through pastebin or so, looks like allot of output :)
the picture isn't verry usefull.
though it says that it can't find the library parts.

**Comment by qblacksheep** [comment]
Ok, there was problem with library, i just reinstall it and its working now.
