### ISSUE TITLE
opendir failed on root

### ISSUE THREAD

**Issue by mytrain** [esp8266/Arduino#1475]
With a 1.6.x version I created a file system with two (virtual) folders f1 and f2 each of them containing files

in 1.6.0 invoking opendir("") returned all the files of the FS.
in 2.1.0 opendir("") returns nothing.
I've tried opendir("/") but returns also nothing
opendir("/f1") returns nothing
but opendir("f1") returns correctly all the files of f1 folder.

Question: Knowing that I do not want to regenerate the File System how can I access the full list of file without know first level folder names ?

Thanks

**Comment by me-no-dev** [comment]
make sure your folders and files start with slash when you are creating the filesystem. From then on you will not have any issues.
You can use the plugin for ArduinoIDE to auto generate the image for you as well :)
Also always save files with starting slash!

**Comment by mytrain** [comment]
Unfortunately I'm not using IDE for uploading files, my ESP is part of a bigger project and it download information files from a server. 
Does anybody know where, in the code, the regression come from ?

**Comment by me-no-dev** [comment]
opendir calles isSpiffsFilenameValid(fileName) which checks if the fileName length is greater than 0 and less than the max filename length. In your case "" has 0 length

**Comment by mytrain** [comment]
Thanks

**Comment by mytrain** [comment]
Now its working.
