### ISSUE TITLE
Logging exceptions to EEPROM?

### ISSUE THREAD

**Issue by schokocappucino** [esp8266/Arduino#1478]
Is it possible to catch and log exceptions and saving them in the EEPROM? That way you could send it to some server after reboot.
I want do run multiple ESPs without a connected UART and at the moment I wouldn't get any feedback if they crash.

**Comment by Links2004** [comment]
you can get the boot / reboot reason with:
```ESP.getResetInfo()```
```ESP.getResetInfoPtr()```
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Esp.cpp#L332-L343
if there where a crash you will get the address of the code location.

**Comment by schokocappucino** [comment]
wow, perfect. thank you ;)
