### ISSUE TITLE
nodeMCU + ArduinoIDE zero crossing

### ISSUE THREAD

**Issue by brunoudi** [esp8266/Arduino#1483]
I'm trying to make a dimmer with nodeMCU and ArduinoIDE, but I'm having a problem with the zero cross detection.

Considering 60hz, i would get a interrupt every 8,33 ms, but in 10% of the cases I get a interrupt at 7,86ms and then another at 0,47ms. 

Those "mistakes" is causing the lamp to flicker.

My code is below, as my schematic.

I would like to hear your opinion and sugetions.

Thanks.

const int pulsePin = D2; //pin to pulse the triac

cont inst zcPin = D1; //pin to zero cross detection

int tempo = 0; //time to wait to send the pulse in microseconds

void zeroCrossing() {
    if (tempo == 0) {
        digitalWrite(pulsePin, LOW);
    }
    else {
        delayMicroseconds(tempo);
        digitalWrite(pulsePin, HIGH);
        delayMicroseconds(20);
        digitalWrite(pulsePin, LOW);
    }

void setup() {
    Serial.begin(115200);
    pinMode(pulsePin, OUTPUT);
    pinMode(zcPin, INPUT);
    attachInterrupt(digitalPinToInterrupt(zcPin), zeroCrossing, FALLING);
}

void loop () {
int temp;
    if (Serial.available()) {
        temp = Serial.parseInt();
        if (temp != 0) {
        tempo = temp;
        }
    }
}
![fqznyv7h8cvg9tk medium](https://cloud.githubusercontent.com/assets/16839854/12515425/7f422106-c10f-11e5-9300-cfb82ffdf6ef.jpg)
##

**Comment by Links2004** [comment]
if you get the interrupt before the real one it must be some noise on the line.
simulate or calculate if you can add some capacitor to filter it. 

keep in mind the the WiFi and OS from the SDK, 
have interrupts too and this can delay other interrupts.
for this reason i habe used a AVR + a ESP01 for my project.

I have used this on the AVR:
![image](https://cloud.githubusercontent.com/assets/974709/12517395/c007da46-c132-11e5-942c-c67574f9f9cc.png)

**Comment by drmpf** [comment]
I am making a wifi controlled house light.  A retrofit for an existing light without changing the house wiring and keeping the existing wall switch operational.
There is the circuit.  Note this is only detecting missing AC not zero crossing, but has some features that may help you.  
![esp8266_wifi_lightswitch](https://cloud.githubusercontent.com/assets/5945337/12526035/3a84911c-c1bd-11e5-835c-7cc44d8a8b06.png)

It has larger resistors to reduce the power loss, a high frequency filter on the front of the opto-isolator, and a reverse diode to protect the optos led from reverse voltage and a diode on the GPIO2 input so you can still flash the ESP with the circuit connected.

Zero crossing can by very noise prone.  You may do better to use a circuit like this and infer the next zero cross from the mid point of the input pulse.  i.e. top of the AC waveform

**Comment by drmpf** [comment]
p.s. As been mentioned elsewhere the standard ESP wifi blocks on sending packets so you should use the newer Async library. https://github.com/esp8266/Arduino/issues/1430
  Even then you may have delays introduced by the Wifi code.  The newer ESP32 may solve this

**Comment by me-no-dev** [comment]
@drmpf looking at the code above, can't the triac be controlled by the PWM driver? So you do not need to delay and switch in the callback. If only one interrupt is attached, I have measured about 2-3us delay between the event and the time the callback is called. At 50Hz that should be OK :)
What are the requirements for the signal to the triac?

**Comment by me-no-dev** [comment]
Maybe if not the PWM driver, then use timer0 or timer1 to control switching and not delay at all in the callback.
I have noticed that as little you do in those callback, the more the end result is reliable. Switching a pin and starting the timer will take less than 1us to complete and let the rest of the system run without noticing at all that process. Then when the timer hits, you only switch the pin (way under 1us) and you'll be ready to get the next zero pulse

**Comment by ilendemli** [comment]
@me-no-dev do you have an example? @brunoudi have you figured a reliable way to detect zero crossing? Is there a way to add timer intervals?

**Comment by me-no-dev** [comment]
https://gist.github.com/me-no-dev/2e185a909000f6ac9605
this is one example using timers and interrupts

**Comment by mkeyno** [comment]
hi @me-no-dev , the links you passed,it is  implemented in ESP?, I don't recognize GPOS  or GPI term in the code
@drmpf why don't you using MOC3040 as cross detector , I saw many sketch use such opto device 
![0_1 - esp8266 - wifi mpsw_v2 - sch - 0_1 1](https://cloud.githubusercontent.com/assets/6232001/14579946/2573cae8-03d2-11e6-9e9b-0ef1ab74b610.jpg)
![fg3hv1khla0woes large](https://cloud.githubusercontent.com/assets/6232001/14579955/9585cf98-03d2-11e6-86a4-bf3a9d036267.jpg)

**Comment by me-no-dev** [comment]
yes that is ESP :) it's direct register manipulation (if you look in the core files you will see many things like that)

**Comment by devyte** [comment]
Interesting discussion, but closing per #3655 .

**Comment by junior700** [comment]
I sugest this circuit: 
[https://www.circuitar.com.br/media/product/26/files/Zero_Cross_v1.0.pdf](url)

**Comment by junior700** [comment]
https://www.circuitar.com.br/media/product/26/files/Zero_Cross_v1.0.pdf

**Comment by junior700** [comment]
> @drmpf why don't you using MOC3040 as cross detector , I saw many sketch use such opto device

Hi @mkeyno , this circuit is useful for heating resistor, but has a lot of flickering on the lamps!

**Comment by junior700** [comment]
You could use multitask (free RTOS) with ESP.
