### ISSUE TITLE
detect esp8266 board?

### ISSUE THREAD

**Issue by tuxedo0801** [esp8266/Arduino#1497]
Hi there,

i'm trying to write a small library that can be used with avr arduinos as well as with the esp8266.
Problem is: My avr arduino code does is not directly working on esp8266 (f.i. avr/pgmspace.h does not exists). I need to rework some parts and use some #ifdef ...

Is there already something defined for esp8266?

br,
  Alex

**Comment by igrr** [comment]
`ARDUINO_ARCH_ESP8266` and `ESP8266` are defined for ESP8266 boards.

**Comment by tuxedo0801** [comment]
Thx.
