### ISSUE TITLE
Mini Router WN523N2 shocked ESP8266 every Minute

### ISSUE THREAD

**Issue by CombiesGit** [esp8266/Arduino#1505]
I noticed it at my OTA experiments. Once mDNS is used, the ESP throws an exception(0). It does this exactly 1 times per Minute. It makes no difference whether the WN523N2 is running in bridge or repeater mode. The error only occurs with mDNS. Web servers, etc. are stable

A new router firmware I have not found.
All other devices in the WLAN working well.

**Comment by CombiesGit** [comment]
Logs and Source files attached

[Log_with_repeater.txt](https://github.com/esp8266/Arduino/files/108182/Log_with_repeater.txt)
[Log_without_repeater.txt](https://github.com/esp8266/Arduino/files/108183/Log_without_repeater.txt)

[OTA03.ino.txt](https://github.com/esp8266/Arduino/files/108184/OTA03.ino.txt)

**Comment by CombiesGit** [comment]
The Bug is marked with  <<<< --------------- 
An ill Statement.

How can I fix this?

[obj_dump.txt](https://github.com/esp8266/Arduino/files/108784/obj_dump.txt)

**Comment by Links2004** [comment]
the address is in the SDK part, only espressif can fix it.

**Comment by CombiesGit** [comment]
Espressif has an Answer.
See http://bbs.espressif.com/viewtopic.php?f=66&t=1701

A simple exchange of the sdk throws an error:
```

In file included from E:\Programme\Arduino\hardware\esp8266com\esp8266\cores\esp8266/esp8266_peri.h:24:0,

                 from E:\Programme\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Arduino.h:38,

                 from E:\Temp\build8d1efe75cc663826dc7dfe795abebf41.tmp\sketch\OTA03.ino.cpp:1:

E:\Programme\Arduino\hardware\esp8266com\esp8266/tools/sdk/include/c_types.h:15:29: error: conflicting declaration 'typedef long unsigned int uint32_t'

 typedef unsigned long       uint32_t;
```

**Comment by igrr** [comment]
SDK update is a bit more involved than replacing files. I was planning to update to 1.5.2, hold on a bit.

**Comment by CombiesGit** [comment]
Hi
THX for the update to  1.5.2
the Problem persist.

**Comment by igrr** [comment]
Should be fixed in git version. If you're still having issues, please follow up in #1826.

**Comment by CombiesGit** [comment]
> If you're still having issues
Yes!
No Connection over the Repeater/Bridge.
No Problem, without Repeater
All other (smartphone, Tablet, PC) are working fine

with repeater:
> Booting
> Connection Failed! Rebooting...

without repeater:

> Booting
> Ready
> IP address: 192.168.2.104
> Start!


code fragment:
```
void setup() {
  Serial.begin(115200);
  Serial.println("Booting");
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  while (WiFi.waitForConnectResult() != WL_CONNECTED)
  {
    Serial.println("Connection Failed! Rebooting...");
    delay(5000);
    ESP.restart();
  }

  ArduinoOTA.onStart([]() {
    Serial.println("Start");
  });
//.........
}


```

**Comment by igrr** [comment]
The issue was about a crash related to IGMP messages. 
Connection failure is likely something different, do you agree?
Please open another issue, and provide steps to reproduce this (i.e. how you configure your AP, your repeater, etc.)
