### ISSUE TITLE
Board generic (platform esp8266, package esp8266) is unknown

### ISSUE THREAD

**Issue by kapilpawar** [esp8266/Arduino#1514]
i am using ARDUINO UNO and ESP8266 V1.

my board setting like this.

board : generic esp8266 module.
programmer : AVRISP mkII

while i upload my code then i get the error.

Board generic (platform esp8266, package esp8266) is unknown
Error compiling.

please help me 
thanks in advance

**Comment by EduardUA** [comment]
I had this error when I used a version Arduino IDE 1.6.7. In version 1.6.5 all good.

**Comment by Links2004** [comment]
may the same as #1377, #1387 
try to delete the 2.0.0 and rc2 folder, and then install the rc2 new.

https://github.com/esp8266/Arduino#installing-with-boards-manager

**Comment by tuxedo0801** [comment]
HaD the same error. Intuitively did the same as Links2004 suggested. Works for me.

**Comment by SunboX** [comment]
On Mac OS X, the folder is located at
`/Users/$USER/Library/Arduino15/packages/esp8266/hardware`

**Comment by pspranav7** [comment]
Check out step 5 of this [Instructable](http://www.instructables.com/id/Programming-Esp8266-12e-With-Arduino-IDE/) ...
It will solve this problem.... :)

**Comment by kevin192291** [comment]
Link is Broken :( what was it?

**Comment by borhanreo** [comment]
I was face same problem. I fix that problem
Goto C:\Users\"Your Username"\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266
Now you will see two version. you need to old version then restart your arduino IDE.

**Comment by ksrivasu** [comment]
i am using ARDUINO UNO and ESP8266 

my board setting like this.

board : generic esp8266 module
Board esp8285 (platform esp8266, package esp8266) is unknown

Error compiling for board Generic ESP8285 Module.

**Comment by castor666** [comment]
Thx! @borhanreo
greetings

**Comment by palivoda** [comment]
After boards update you need to restart IDE. 
Check there is no previous version in ....\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266

**Comment by SYAMBABUDARSI** [comment]
Board nodemcuv2 (platform esp8266, package esp8266) is unknown

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by blakeedwards823** [comment]
> #1377

A concise tutorial explaining the issue can be found here! 
https://arduino-esp8266.readthedocs.io/en/latest/faq/a04-board-generic-is-unknown.html
