### ISSUE TITLE
SSID hide

### ISSUE THREAD

**Issue by kapilpawar** [esp8266/Arduino#1521]
how to hide my SSID of esp8266..

is there any AT command in esp8266....

thanks in advance ..

**Comment by Links2004** [comment]
this repo is a full release for AT firmware.
with the software here you can Programm the ESP module like any other Arduino board.

for this repo its possible:
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiAP.h#L39
no idea for AT never used it.

**Comment by kapilpawar** [comment]
Hi Links2004,

do i need to update the firmware of esp8266 before programing

**Comment by kapilpawar** [comment]
@Links2004 

can  you please give me full steps for hiding the ssid of esp8266

**Comment by Links2004** [comment]
start here:
https://github.com/esp8266/Arduino#installing-with-boards-manager

use the AP example
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/WiFiAccessPoint/WiFiAccessPoint.ino#L56

but with:
```cpp
// ssid, password, channel, hide
WiFi.softAP(ssid, password, 1, 1);
```

**Comment by kapilpawar** [comment]
@Links2004 

Thanks dear


but it can not be uploaded 
it is showing some error.
the error is like ....



Sketch uses 246,926 bytes (56%) of program storage space. Maximum is 434,160 bytes.
Global variables use 38,144 bytes (46%) of dynamic memory, leaving 43,776 bytes for local variables. Maximum is 81,920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed





please give me resolution...

**Comment by Links2004** [comment]
i not can give you a "resolution", 
I not know how you wired the ESP with you PC or whats connected to all the GPIOs or what ESP module you use.
I only can give you hints whats going wrong.

check list:
 - select the correct board in the IDE.
 - is the wirering correct https://github.com/esp8266/Arduino/blob/master/doc/boards.md#esp-to-serial
 - is the power supply stable, 3.3V with more then 250mA (not use the usb chip as supply) https://github.com/esp8266/Arduino/blob/master/doc/boards.md#serial-adapter
 - have alle the pins the correct level at bootup (Uart mode) https://github.com/esp8266/Arduino/blob/master/doc/boards.md#boot-mode

**Comment by kapilpawar** [comment]
@Links2004 
Thanks

**Comment by ariffinzulkifli** [comment]
thank you @Links2004

**Comment by thebeswick** [comment]
I just had the same problem, you can set 
`WiFi.enableAP(0);`

before starting your wireless client.

**Comment by majidmp97** [comment]
> WiFi.enableAP(0);

thank you very much. i need this very long time
