### ISSUE TITLE
ESP8266-12E and Ethernet Shield

### ISSUE THREAD

**Issue by folny** [esp8266/Arduino#1528]
Hi Friends

Someone has tried to use ESP and Ethernet Shield (W5100) together ? If so what you should do to make it work and what should be the involvement of pins thanks.

**Comment by pieman64** [comment]
@folny can't you tie the ESP to the Arduino without the Ethernet Shield?

**Comment by folny** [comment]
I would like to use ESP and connecting via ethernet cable would that be ?. Have you tried it ?.

**Comment by asetyde** [comment]
It’s possible but i’ve no information about this

**Comment by folny** [comment]
He writes about it in this post but I'm not sure what you should do to make it work.

https://github.com/esp8266/Arduino/issues/962

**Comment by asetyde** [comment]
Simple , connect all necessary pin , load ethernet library and use esp as cpu only ,but it's good use nodemcu with more pin .

**Comment by Links2004** [comment]
yes its possible:
https://github.com/esp8266/Arduino/tree/master/libraries/Ethernet
connect the W5100 to the SPI pins of the ESP.
if you have the uno compatible board of the W5100 use the SPI pins of the ISP header to connect.
the normal one are not routed.

**Comment by folny** [comment]
Yes it works now the problem was the involvement of pins thanks for the advice.

**Comment by burner-** [comment]
I currently try draw nodemcu - arduino uno adapter. I mean adapter where is slot for nodemcu2 and it provide arduino uno layout for ethernet shield. But I dont know what are right pins? There is only info that use SPI pins but at nodemcu there is several SPI pins so what are right ones?

**Comment by dvjcodec** [comment]
Maybe will help
http://arduino.esp8266.com/versions/1.6.5-1160-gef26c5f/doc/esp12.png

**Comment by mkeyno** [comment]
hi @folny , do you have any success to bin ESP and Ethernet?

**Comment by burner-** [comment]
If someone manage to use that code, can he or she please post what pin out he use. I have hit head to wall with this but I must say that given links does not help. They give hint how to you may connect your esp but really there is still multiple ways and none of them seems to work. Also do I need pull up or down resistors?

**Comment by tusharvb19** [comment]
I got it working but the example code web-server does not getting the static ip rather it takes 192.168.0.240
Dont know why!
I have used the normal SPI pins on NodeMCU which are:

#define D0 16
#define D1 5 // I2C Bus SCL (clock)
#define D2 4 // I2C Bus SDA (data)
#define D3 0
#define D4 2 // Same as "LED_BUILTIN", but inverted logic
#define D5 14 // SPI Bus SCK (clock)
#define D6 12 // SPI Bus MISO 
#define D7 13 // SPI Bus MOSI
#define D8 15 // SPI Bus SS (CS)
#define D9 3 // RX0 (Serial console)
#define D10 1 // TX0 (Serial console)

**Comment by Arslanqayyum** [comment]
Hi Friends

Any success in connecting ESP8266 with Ethernet ?

**Comment by burner-** [comment]
I did long while a go BUT it was quite unstable after all because shared WDT interrupt. I suggest that use esp32 because it have proper WDT.
