### ISSUE TITLE
CoAP library

### ISSUE THREAD

**Issue by Vitorbnc** [esp8266/Arduino#1529]
Hi,
Do you know any CoAP library for esp8266?
##

**Comment by Makuna** [comment]
I have a personal library I am working on for Arduino (that I make sure works on esp8266) but its not ready yet.  Did you search using Google/Bing/Yahoo?  I just did and hit several with source code available.

**Comment by hashin** [comment]
Hi there!

Are there any updates to this one? I am looking for a CoAP library for ESP8266 Arduino.  Thanks in advance!

**Comment by hashin** [comment]
@Makuna Thanks for your input! I have been searching around and cannot find any reliable solutions. It would be great if you can give some leads into this.  :)

**Comment by devyte** [comment]
Closing per #3655 .
