### ISSUE TITLE
Auto discover board in wifi

### ISSUE THREAD

**Issue by gepd** [esp8266/Arduino#1534]
Hi, I'm working a [plugin](https://github.com/gepd/Deviot) for Sublime Text to work with Arduino, and I have a doubt, how the Arduino IDE does to discover the boards connected to the wifi network, like Yun board?

I'll apreciate any information (document/code) to do this.

**Comment by Links2004** [comment]
the IDE use mDNS.
the services for OTA are listed here:
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266mDNS/ESP8266mDNS.cpp#L477

**Comment by gepd** [comment]
Thanks for the information @Links2004 !
I'm looking into it
