### ISSUE TITLE
Store any struct in flash.

### ISSUE THREAD

**Issue by Duality4Y** [esp8266/Arduino#1539]
Hi there I have been writing some code to store any struct that you can create.

so here is the functional code.
```cpp
void storeStruct(void *data_source, size_t size)
{
  EEPROM.begin(size * 2);
  for(size_t i = 0; i < size; i++)
  {
    char data = ((char *)data_source)[i];
    EEPROM.write(i, data);
  }
  EEPROM.commit();
}

void loadStruct(void *data_dest, size_t size)
{
    EEPROM.begin(size * 2);
    for(size_t i = 0; i < size; i++)
    {
        char data = EEPROM.read(i);
        ((char *)data_dest)[i] = data;
    }
}
```

it is verry simple every struct is passed by reference,
say  you have this code:
```cpp
typedef struct {
  char board_name[64];
  char ssid[64];
  char pass[64];
} settings_t __attribute__ ((packed));

settings_t settings
{
    "test_host",
    "ssid",
    "pass"
};
```

and you want to store that struct in eeprom/flash! you'd do:
```cpp
storeStruct(&settings, sizeof(settings));
```

and to load it:
```cpp
loadStruct(&settings, sizeof(settings));
```

here is my test code and that passes:
```cpp
settings_t settings_original;
void printCmpSettings(settings_t s1, settings_t s2)
{
    Serial.printf("board_name: %s | %s \n"
                  "ssid: %s | %s \n"
                  "pass: %s | %s \n",
                  s1.board_name, s2.board_name,
                  s1.ssid, s2.ssid,
                  s1.pass, s2.pass
                  );
}

memcpy(&settings_original, &settings, sizeof(settings));
storeStruct(&settings, sizeof(settings));
loadStruct(&settings, sizeof(settings));
if(!memcmp(&settings_original, &settings, sizeof(settings)))
{
    Serial.println("settings are the same!");
    printCmpSettings(settings_original, settings);
}
else
{
    Serial.println("settings are not the same!");
    printCmpSettings(settings_original, settings);
}

memcpy(&settings_original, &settings, sizeof(settings));
strcpy(settings.board_name, "test_host");
storeStruct(&settings, sizeof(settings));
loadStruct(&settings, sizeof(settings));
if(!memcmp(&settings_original, &settings, sizeof(settings)))
{
    Serial.println("settings are the same!");
    printCmpSettings(settings_original, settings);
}
else
{
    Serial.println("settings are not the same!");
    printCmpSettings(settings_original, settings);
}
```

it is really nice because you can make those structs as complicated or simple as you want.
a few notes. your struct needs to be packed!
and it needs to be alligned with flash!
also if you want to put structs in a struct you want to do it like this:
```cpp
struct Employee
{
   char ename[20];
   int ssn;
   float salary;
   struct date
       {
       int date;
       int month;
       int year; 
       }doj;
}emp1;
```

I hope it is usefull! :)

**Comment by marvinroger** [comment]
That's nice, thanks for sharing. But, there are already `EEPROM.get` and `EEPROM.put` that do exactly the same thing.

**Comment by Duality4Y** [comment]
There is no example of this for the esp8266, so I decided to write it myself :)

**Comment by marvinroger** [comment]
This is a great way to learn, good idea. The fact is the EEPROM API is the same as the Arduino one, except for `EEPROM.begin()` and `EEPROM.commit()`, so `put` and `get` are implemented just like on AVR. Given there are 300+ issues, I guess we can close this one, if you don't mind. ;)

**Comment by shinnlu** [comment]
found a problem when writing a String variable in struct, esp8266 crash with Exception(3).

**Comment by Makuna** [comment]
@shinnlu You can't store "complex" objects this way.  Any class that allocates memory to store anything will require special work to serialize and de-serialize that member otherwise you are just storing the pointer to the memory.  String is such a class.  

A common way to store variable length strings is to convert them to a BSTR (basic string) format, which starts with a 8 bit or 16 bit value that is the length of the string, followed by a buffer that is that length long containing the string.

**Comment by shinnlu** [comment]
@Makuna i will change to char array or save with Json object, thanks.

**Comment by YasirShahahzad** [comment]
Great Help, some people are saying its alternatives. But some times we need this type of code, thanks once again

**Comment by pbravoz2** [comment]
Hi Robert,
                    this is a very usefull sketch for use efficiently and easy the EEPROM in NODEMCU. It solves a lot of problems for me. Congratulations!!. Is excellent!!
With best regards,
Pedro (from Chile)

**Comment by lasofre** [comment]
Hi i haves this error 
warning:'packed' attribute ignored [-Wattributes]}settings_t __attribute__ ((packed));  
what can a i do ?

**Comment by Duality4Y** [comment]
I might have put the packed attribute in the wrong place :)

**Comment by doditsuprianto** [comment]
in August 2020, your code very useful. this solves my problem.
thanks, Duality4Y

**Comment by Shumatic** [comment]
> ```c++
> EEPROM.begin(size * 2);
> ```

I knw it is anold post... but
Why do you multiply size with 2?
