### ISSUE TITLE
Implement hardware SPI module functions

### ISSUE THREAD

**Issue by MetalPhreak** [esp8266/Arduino#154]
I've written a library for using the hardware SPI module that add's a lot more functionality than the standard espressif spi code. However, I don't have any experience with the Arduino IDE (nor am I that interested in doing so). The library currently is written for native coding on the ESP8266 using the espressif SDK.

If anyone is an Arduino IDE guru, shouldn't be hard to port the functions:

https://github.com/MetalPhreak/ESP8266_SPI_Driver

**Comment by igrr** [comment]
SPI library has now been released.
