### ISSUE TITLE
Nodemcu Devkit v0.9 not recognized by computer, unable to upload new code.

### ISSUE THREAD

**Issue by sokeeffe10** [esp8266/Arduino#1545]
Hi there , I was given the nodemcu devkit v0.9 with code on it already uploaded using Arduino IDE, I have been trying to upload to this again but the Board would appear in device manager but then I would try to upload using arduino IDE and receive , com error. 

I have tried different usb cables, different ports , and now there is simply a blue light on steady when the board is plugged into usb. The user button no longer turns on the small blue light , and my comp does not recognize the board being plugged in our out at all. 

Please help as this has been very frustrating. Thank you

**Comment by tuxedo0801** [comment]
Sounds like module is broken?

**Comment by sokeeffe10** [comment]
Yeah it was,  I bricked it stupidly,  thanks anyway

**Comment by tuxedo0801** [comment]
Issue can be closed?

**Comment by sokeeffe10** [comment]
Yes thank you

**Comment by tuxedo0801** [comment]
Then close it?

**Comment by rolf5649** [comment]
> Jo, byl, hloupě jsem to zablokoval, každopádně díky.
