### ISSUE TITLE
How can I make copy about UART_TX_FIFO in Arduino skatch?

### ISSUE THREAD

**Issue by Galilei11** [esp8266/Arduino#1551]
I need to catch and store all of characters coming out UART0 tx pin,  and send them to another direction.
It have to do inside ESP, with software, because no free pin on ESP already (read back tx pin).  
I think, if I can get every characters when is written to UART_TX_FIFO it can solve this problem.
But I dont know how, any idea?

**Comment by Links2004** [comment]
is it needed to do it register level?
simple create a class with stream interface.
```cpp
HardwareSerial mirror(&Serial);

class SerialMirror: public Stream {
        HardwareSerial * _serial;
        SerialMirror(Serial * s) {
            _serial = s;
        }

        size_t write(const uint8_t *data, size_t size) {
             /// add code for your mirror here
            return _serial->write(data, size);
        }

        size_t write(uint8_t data) {
             /// add code for your mirror here
            return _serial->write(data);
        }

        int available() {
            return _serial->available();
        }

        int read() {
            return _serial->read();;
        }

        int peek() {
            return _serial->peek();
        }

        void flush() {
            _serial->flush();
        }
}
```

usage:
```cpp
mirror.println('test');
```

**Comment by Galilei11** [comment]
thx, I will test it
but I am beginner yet, I started 2 month ago with ESP and Arduino, I try to understand and use it :)
how do you think: register level?

**Comment by me-no-dev** [comment]
@Links2004 I think he means that he wants to output at two locations at the same time.
For example: mirror.println(blah); to actually print to Serial and a Client (or some other destiantion)

**Comment by Links2004** [comment]
@me-no-dev yes think so, that is why I write ```add code for your mirror here```` as comment in the code ;)

**Comment by tzapu** [comment]
@Links2004 will this make it possible for instance to stream serial to websockets? got any sample of that somewhere? :)

**Comment by Links2004** [comment]
@tzapu yes you can write a class that can "print" to websocktes in the same way, or eaven combine them to print to Serial and WS.
for many small prints I recommend the usage of the Async mode for websocktes or it will be slow.

```cpp
class SerialMirror: public Stream {
        WebSocketsServer* _ws;
        SerialMirror(WebSocketsServer * s) {            _ws = s;        }

        size_t write(const uint8_t *data, size_t size) {    _ws->broadcastTXT(data, size); return size;        }
        size_t write(uint8_t data) {            return _ws->broadcastTXT(data);    return 1;    }

        int available() { return 0;  }
        int read() {    return -1;    }
        int peek() {    return -1;    }
        void flush() {       }
}
```

**Comment by tzapu** [comment]
hi, thank you very much for the hints, i assume i can combine the two above to proxy reading from serial to websockets... need to lear more :D

**Comment by Links2004** [comment]
yes for serial to websockets bridge you not need a stream interface for websockets .
simple buffering:
```cpp
    Serial.setTimeout(200);
    String line = Serial.readStringUntil('\n');
    if(line.length() > 0) {
        // add back line ending
        line+='\n';
        ws->broadcastTXT(line);
    }
```
sends all 200ms (when data is there) or on every line ending.

**Comment by tzapu** [comment]
how cool is that :D
thank you very much

**Comment by tzapu** [comment]
@Links2004 this seems to be missing some strings at 115200, is there something i can do to make it more reliable?
p.s. i don t know yet, and i should check, if it is missing while reading or it s missing while sending over websockets... i ll check and be back

**Comment by tzapu** [comment]
@Links2004 , double checked, it seems it s missing strings when reading from serial.
cand i make it more reliable somhow?
thanks for all your help

**Comment by Links2004** [comment]
so you not get echoed back all data?

you can try:
```cpp
void setup() {
 ....
 Serial.setTimeout(200);
}

void loop() {
    webSocket.loop();
    if(Serial.available()) {
        String line = Serial.readStringUntil('\n');
        if(line.length() > 0) {
            // add back line ending
            line+='\n';
            ws->broadcastTXT(line);
        }
    }
}
```

**Comment by tzapu** [comment]
nop, somhow it s eating characters.

tried with timeout in setup, still no go
```
connecting to 
emoncms.org
RequHTTP/1.1 200 OK
Date: Wed, 17 Feb 2016 17:29:59 GMT
Server: Apache/2.2.22 (Ubuntu)
X-Powentent-Length: 2
ok
```
that should have the full url there somewhere and headers, etc

**Comment by tzapu** [comment]
i have also tried without timeout, larger timeout, still the same.
a 500ms timeout does seem to make it a bit better, but still misses some stuff

**Comment by tzapu** [comment]
this seems to yield some better results on some fast tests
```
void serialEvent() {
  while (Serial.available()) {
    char inChar = (char)Serial.read();
    if (inChar == '\n') {
      stringComplete = true;
      return;
    } else {
      inputString += inChar;
    }
  }
}


void loop() {
  serialEvent();
  if (stringComplete) {
    
    String line = inputString;
       // clear the string:
    inputString = "";
    stringComplete = false;

    //line += '\n';
    webSocket.broadcastTXT(line);
    Serial.print(line);
  }
}
```

**Comment by tzapu** [comment]
although i just realised in the latest example i forgot to add the websockets loop...
more testing tomorrow
thanks

**Comment by tzapu** [comment]
hi @Links2004 , took longer than i expected to try this

it seems that indeed if i use the serialEvent loop like above, it does not miss characters....

weird

**Comment by Links2004** [comment]
that you lost the empty lines make sens with your code.
if you find a \n you not add it and then you send a empty buffer to the browser.
may this is part of the problem.

you can try to:
reserve some space in the string too
check the return value of the broadcastTXT may simple the TCP buffer is full.

**Comment by tzapu** [comment]
thanks for the hints, will play with it more 
not loosing just new lines, in the example above Connection: close is truncated, application/html or whatever was there is also trucated
also, not just broadcast, i mirror it on serial as well before sending and it s truncated there as well
i am also doing this inputString.reserve(256); , it doesn t seem to be larger than that, seeing that it reads only one line at a time and also the ones truncated are quite short

**Comment by Links2004** [comment]
the internal serial hardware buffer is 128Byte with the code above I not see a reason why it can
have a overflow, you read fast form it.
have you tried a other Serial adapter in best case with other chip may yours is defektiv.

**Comment by tzapu** [comment]
i m using a nodemcu as a serial reader of stuff spat out by an esp01
the project is this https://github.com/tzapu/WebSocketSerialMonitor
i will try to read from the esp01 directly with a usb to serial reader, see if that output comes out ok, and will try another things instad of the nodemcu i currently use as proxy

**Comment by tablatronix** [comment]
Did you give up on serial tx mirror ? I am looking for the same, but not websockets, although that would be nice also.

**Comment by tzapu** [comment]
well, my repo above does mirroring over websockets to a page, also on github pages
so far, it eats some characters up, still yet to find why

**Comment by tablatronix** [comment]
hmm I thought `Serial.read();` only reads RX buffer... 
Is the magic somewhere else ?

**Comment by tablatronix** [comment]
Oh you are using a hardware rx.

I am wanting what the op wanted.

Mirror all Serial tx to a server stream say telnet write or websockets whatever. Like overloading or interxepting Serial writes.

**Comment by tzapu** [comment]
sorry for waking the dead with this one @Links2004 , i got around to plugging a real serial adapter into the GND/TX of the sending ESP, and unline the NodeMCU that was reading with the code above, this does not miss any characters.

It does seem that somehow serial rx is missing characters, and quite a bit of them

**Comment by Links2004** [comment]
you can try:
https://github.com/Links2004/arduinoWebSockets/issues/61#issuecomment-198231422

how high is you data rate, may you overload the Hardware serial RX buffer.

**Comment by tablatronix** [comment]
looks nice, how big is the hardware buffer?

![screen shot 2016-03-19 at 12 29 11 pm](https://cloud.githubusercontent.com/assets/807787/13900289/d55cfcf8-edd0-11e5-9f01-ff966714acdc.png)

**Comment by tzapu** [comment]
hi, baud is set at 115200, data is rather little, should not go over buffer. longest line seems to be around 115 characters, and it seems to eat random parts of the buffer anyway, not always the same one.

i will try the sample you kindly provided. thank you. i ll also try slower baud rates

**Comment by tablatronix** [comment]
Ah I reread, harsware buffer is 128 byte.

Do you have a reproduction test, I have two boards in my dev, i can try, or try a loopback. I a. Assumig you do not have a problem ge erating data internally , but only when reading harsware serial?

**Comment by tablatronix** [comment]
as an aside
@Links2004  serialmirror code above doesn't work and is confusing me ( which is easy in C++)
The errors make sense I think, HardwareSerial wants an int eg. `UART0`

And I am guessing Serial is not typedefed or something for the second error.

```
SerialMirror.h:1:30: error: invalid conversion from 'HardwareSerial*' to 'int' [-fpermissive]
 HardwareSerial mirror(&Serial);
                              ^
```

```
/SerialMirror.h:5:29: error: expected ')' before '*' token
         SerialMirror(Serial * s) {
                             ^
```

Nor do I get how mirrro() is using the SerialMirror class , or was that all supposed to be handled via the &Serial reference ? Since there is no explicit instantiation of the class...
:confused:

**Comment by Links2004** [comment]
for https://github.com/esp8266/Arduino/issues/1551#issuecomment-178058579
```SerialMirror(Serial * s) {``` need to be ```   SerialMirror(HardwareSerial* s) {```
its never tested code, only to show the way.

for a Serial to WS bridge is currently use 
https://github.com/Links2004/arduinoWebSockets/issues/61#issuecomment-198231422
without any problems, it has a more advanced buffering and can run without blocking in the loop.

**Comment by tablatronix** [comment]
That bridge is what I am using above (screenshot), I was interested in having a stream to websockets/hardwareserial/telnet so i figured a serial mirror like that would be useful for easily pluggin into existing sketches and redirecting to wherever I wanted.

**Comment by Links2004** [comment]
for mirroring the "Serial out" to multible interfaces you need to create a class with the ```Stream``` interface like:

```cpp

class SerialMirror: public Stream {
        size_t write(const uint8_t *data, size_t size) {   
              ws.broadcastTXT(data, size); 
              Serial.write(data, size);
              Serial1.write(data, size);
              return size;       
         }

        size_t write(uint8_t data) { 
             ws.broadcastTXT(data);    
             Serial.write(data);
             Serial1.write(data);
             return 1;
    }

        int available() { return 0;  }
        int read() {    return -1;    }
        int peek() {    return -1;    }
        void flush() {       }
}

SerialMirror SerialM;

SeriaM.println("print to all interfaces");
```

**Comment by tablatronix** [comment]
Sounds easy enough, do i need to alias the print/ln stuff or is that done by the stream class?

**Comment by Links2004** [comment]
the Stream class will do this for you.
you only need the functions shown above.
the code will handle the sending / print / write stuff.
