### ISSUE TITLE
CRC doesn't match/file is corrupt from the Boards Manager

### ISSUE THREAD

**Issue by dandandandandandandan** [esp8266/Arduino#1553]
during install/update both on stable and staging version (2.0)

**Comment by dandandandandandandan** [comment]
Deleting everything from the (windows 7) \AppData\Local\Arduino15\packages and \AppData\Local\Arduino15\staging folders solved it.

**Comment by Juppit** [comment]
rename your arduino folder and download it again.
Under Windows I find myn here:C:\Users\Peter\AppData\Local\Arduino15
If you like preserve your old preferences.txt

Am 02.02.2016 um 10:58 schrieb dandandandandandandan:
