### ISSUE TITLE
BUILTIN_LED should be LED_BUILTIN

### ISSUE THREAD

**Issue by SukkoPera** [esp8266/Arduino#1555]
Arduino's macro that holds the number of the built-in led in boards is `LED_BUILTIN`. For some reason, this core uses `BUILTIN_LED`, leading to unportable code.

See: https://www.arduino.cc/en/Reference/Constants

**Comment by tuxedo0801** [comment]
I also stumbled on this. 

Is there a reason why the macro does not match?

**Comment by tuxedo0801** [comment]
Added a PR for this: #1556

**Comment by SukkoPera** [comment]
Well done :)

**Comment by tuxedo0801** [comment]
@SukkoPera 
Please close, PR #1556 is been merged.

**Comment by SukkoPera** [comment]
Ok, thanks. I'm not really for keeping both macros, but fair enough.
