### ISSUE TITLE
Float to string "dtostrf" & logarithm (log) functions not working

### ISSUE THREAD

**Issue by tanck2** [esp8266/Arduino#156]
The dtostrf function for converting float to string is missing.  In addition I received the following error message when I tried to use the logarithm function log:

temp_test_log.cpp:(.text+0x3c): undefined reference to `log'

The log function seems to work with explicit number but not with variables.

Thanks.

**Comment by CptanPanic** [comment]
The function dtostrf is actually part of avr library, so this is why it is not available for esp8266.  But I do think an alternative should be available.

**Comment by Makuna** [comment]
Dtostrf is supported and present.
