### ISSUE TITLE
Please include ESP8266Ping

### ISSUE THREAD

**Issue by PsY4** [esp8266/Arduino#1561]
After days of searching, i finally found a library to ping : https://github.com/dancol90/ESP8266Ping 

This lib should be included in this project.

**Comment by tuxedo0801** [comment]
+1

**Comment by ry60003333** [comment]
+1

**Comment by lnxbil** [comment]
+1

**Comment by Lstt2005** [comment]
+1

**Comment by cunchem** [comment]
+1

**Comment by igrr** [comment]
Added in ef80030
