### ISSUE TITLE
PWM doesn't working

### ISSUE THREAD

**Issue by qblacksheep** [esp8266/Arduino#1562]
Hi,
 i want to control my led strip with PWM on the ESP 8266-07 (i want to control brithness of my led strip). At first the LED strip shine decidedly to weak in the full cycle (1023). I tested it at normal LED too and i didnt see any chagnes when i was changing value of analogWrite, only when its nearly 0, led stop lighting. 
I tested this same program, and this same MOSFET on the arduino and it worked.
Any ideas?
Have u trying to control LED from the ESP PWM? 

Ofc i am using wifi and WebSockets.

**Comment by Links2004** [comment]
the WebSockets example for RGB LED dimming, is working for me,
but i not use a Mosfet its a single RGB LED.
what version of the core do you use?
there where some bug in the PWM handling, its fixed in 2.1.0-rc2

**Comment by qblacksheep** [comment]
Thanks, in this version PWM its working. But my leds still shine decidedly to weak in the full cycle (1023). Maybe ESP output gives me too low current? I have ~42mA in the full cycle, from arduino i have ~60mA

**Comment by Links2004** [comment]
the Arduino runs with 5V the ESP with 3.3V.
so the lower current looks in the expected range of change to me.
how you wiring with the mos looks like?

**Comment by qblacksheep** [comment]
But i measure the current from arduino when i had ~3.3V on the output.
![image](https://cloud.githubusercontent.com/assets/16727999/12795930/c3289290-cabc-11e5-9da7-41f8d9138884.png)


i am using P16NF0b

**Comment by Links2004** [comment]
your R9 is on the wrong place.
try:
![image](https://cloud.githubusercontent.com/assets/974709/12796091/677fb062-cabd-11e5-8f90-6f8bbc44abcc.png)

**Comment by qblacksheep** [comment]
Yes, these schematic was wrong, i uploaded a new. Sorry

**Comment by Links2004** [comment]
no problem,

have take a look to the datasheet of the MOS.
the Threshold Voltage (Vgs) is not optimal for the ESP.
the MOS needs up to 4V to work properly. 

![image](https://cloud.githubusercontent.com/assets/974709/12796206/e3c5ddf4-cabd-11e5-8feb-13c8d999938c.png)

**Comment by qblacksheep** [comment]
Ah, so MOS will be full opened when Vgs > 4V? You suggest to find new mosfet 
which will be full open at Vgs> 1-2,5V or try to add amplifiler at the output and get about ~5v from 3,3v

**Comment by Links2004** [comment]
AO3400 is a good chose for the ESP, can handle 4.5A and up to 30V and its small.
yes the MOS open fully in between from 2V to 4V depending on manufacturing process.

**Comment by qblacksheep** [comment]
Thanks! I will buy it tomorrow and test. If it works, ill write  there. Thanks again:)

**Comment by qblacksheep** [comment]
Yea, its working. Thanks for help. Ill close it.

**Comment by vargham** [comment]
> yes the MOS open fully in between from 2V to 4V depending on manufacturing process.
No, the opposite is true. The MOSFET will be fully closed somewhere between these values, depending on manufacturing process.
You have to check other part of the datasheet: RDS(ON) It is usually a sub-table, with specific Vgs values, resistance and maximum Id (Drain current). You will see, lower gate voltage means lower maximum drain current.
Logic level MOSFETs usually will be fully close between 2 and 4 V and will be fully opened at 4.5 or 5 V, so the full opening will be somewhere near 4.5 - 5 V, not between 2 and 4. You heave to be sure, so use voltage values given in RDS(ON).

Source:
[How to Read a Power MOSFET Datasheet](http://www.embeddedrelated.com/showarticle/809.php)

**Comment by vargham** [comment]
> AO3400 is a good chose for the ESP

Yes, this is a good choice.
It handles 5.8A at Vgs = 10 V, and 4A at Vgs = 2.5 V

[AO3400 datasheet](http://www.aosmd.com/pdfs/datasheet/ao3400.pdf)
