### ISSUE TITLE
issues not marked/flagged --> help required?

### ISSUE THREAD

**Issue by tuxedo0801** [esp8266/Arduino#1564]
it's getting more and more issues, but noone tries to categorize or clean up a bit. 

How about adding some people to help organize things a bit?

**Comment by Duality4Y** [comment]
What do you meen? what issues do you talk about? the general issues on the github issue page for this repo ?

**Comment by tuxedo0801** [comment]
Yes. There a lot of issue-pages with issues without any label or milestone attached.
It's confusing which issue is handled or which issue is "on hold" or need more details...
