### ISSUE TITLE
Connections timing out when using WebClientSecure

### ISSUE THREAD

**Issue by InconceivableDuck** [esp8266/Arduino#1567]
Arduino 1.6.7
ESP8266 2.0.0

I'm using the WebClientSecure to open persistent mqtt connections using [PubSubClient](https://github.com/knolleary/pubsubclient). Depending on the rate at which I publish messages, the connection continually drops somewhere between 2-10 minutes. The return code from PubSubClient is usually "Connection Lost". Sometimes it's "Connection Timed Out".

The dropped connections do not occur when using WebClient (non-secure).

I'm going to attempt to clone down master and attempt more debugging, but wanted to post this now in case there's a known issue I don't know about.

**Comment by sglvladi** [comment]
Hi there,

I am experiencing the same issues, but using WiFiClientSecure (not sure what WebClientSecure is).

Was the issue closed because it has been solved?
