### ISSUE TITLE
umm_malloc enabled without doing anything?

### ISSUE THREAD

**Issue by marvinroger** [esp8266/Arduino#1571]
Just a quick question, does calling malloc/realloc/free automatically uses umm_malloc without any code changes? I saw `libmain.o` was changed, so I think yes, but I'd like to have some confirmation. Thanks!

**Comment by igrr** [comment]
No changes in the sketch are necessary, umm_malloc will be used by default. 
As a bonus, you can use `system_show_malloc();` in the sketch to print heap usage info to UART. You may have to use `Serial.setDebugOutput(true);` and add 
```c++
extern "C" { 
#include "user_interface.h" 
}
```
to get `system_show_malloc` declaration.

**Comment by marvinroger** [comment]
Great, thanks for the information!
