### ISSUE TITLE
AP + STA mode need to enable

### ISSUE THREAD

**Issue by Shaheers** [esp8266/Arduino#1578]
hi, its found that as in AT mode we can enable AP + client mode and also Lua have this capability to oprate in that mode, if we implement that in it, we can the enable the mash network buy using a simple protocol or either use MQTT or such
##

**Comment by marvinroger** [comment]
Actually, AP + client mode is [already implemented](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFiMesh/src/ESP8266WiFiMesh.cpp#L43), just like [a mesh library](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFiMesh/examples/HelloMesh/HelloMesh.ino).

**Comment by pgScorpio** [comment]
But all "standard" services like mdns, webserver and ftp only bind to the AP interface in this mode and can't be accessed via STA interface !!!!

**Comment by devyte** [comment]
@Shaheers wifi mode with AP+STA is already implemented.
Closing.
