### ISSUE TITLE
String concatenation and ostringstream undefined reference

### ISSUE THREAD

**Issue by hubertokf** [esp8266/Arduino#1584]
So this is my code. This is just a test, the real problem happen on my other project. Im trying to generate some xml by concatenating strings. 

`#include "Arduino.h"
#include <stdio.h>
#include <string>
#include <sstream>

using namespace std;

template class basic_string<char>;

void setup() { Serial.begin(115200); }

void loop() {
  ostringstream stream;
  stream << "<icon>";

  string s1("toto");
  string s2("313");
  string s;

  s = "www." + s2;
}`

ERRORS:

.pioenvs/nodemcu/src/main.o:(.text._ZNSs12_S_constructIPKcEEPcT_S3_RKSaIcESt20forward_iterator_tag$isra$25+0x8): undefined reference to `std::__throw_logic_error(char const*)'
.pioenvs/nodemcu/src/main.o: In function `_ZNSs12_S_constructIPKcEEPcT_S3_RKSaIcESt20forward_iterator_tag$isra$25':
main.cpp:(.text._ZNSs12_S_constructIPKcEEPcT_S3_RKSaIcESt20forward_iterator_tag$isra$25+0x37): undefined reference to `std::__throw_logic_error(char const*)'
.pioenvs/nodemcu/src/main.o:(.text.loop+0x10): undefined reference to `std::basic_ostringstream, std::allocator >::basic_ostringstream(std::_Ios_Openmode)'
.pioenvs/nodemcu/src/main.o:(.text.loop+0x14): undefined reference to `std::basic_ostream >& std::operator<<  >(std::basic_ostream >&, char const*)'
.pioenvs/nodemcu/src/main.o:(.text.loop+0x18): undefined reference to `std::basic_ostringstream, std::allocator >::~basic_ostringstream()'
.pioenvs/nodemcu/src/main.o:(.text.loop+0x29): undefined reference to `std::basic_ostringstream, std::allocator >::basic_ostringstream(std::_Ios_Openmode)'
.pioenvs/nodemcu/src/main.o:(.text.loop+0x34): undefined reference to `std::basic_ostream >& std::operator<<  >(std::basic_ostream >&, char const*)'
.pioenvs/nodemcu/src/main.o: In function `loop':
main.cpp:(.text.loop+0xbe): undefined reference to `std::basic_ostringstream, std::allocator >::~basic_ostringstream()'
collect2: error: ld returned 1 exit status
scons: *** [.pioenvs/nodemcu/firmware.elf] Error 1
========================= [ ERROR ] Took 1.30 seconds =========================

**Comment by neu-rah** [comment]
confirmed using headers:
```c++
#include <iostream>     // std::cout, std::ios
#include <sstream>
```

**Comment by neu-rah** [comment]
from similar problems it seems to be in uClibc, but uClibc would have to be re-linked with some extra options and then the platform linked with the new version...
