### ISSUE TITLE
SoftwareSerial causes leads to watchdog error?

### ISSUE THREAD

**Issue by shayo** [esp8266/Arduino#1591]
Hi,
I am experiencing weird watchdog crashes, and the only thing I can potentially trace this to is perhaps using SoftwareSerial. I'm not sending long strings, but I am using "slow" 9600 baud rate.
Is it possible that this can cause watchdog error such as this one:

ets Jan  8 2013,rst cause:4, boot mode:(1,6)
wdt reset

If so, what is the recommendation to fix this? Should I throw a couple of yield calls in the read/write commands of that library?

**Comment by supersjimmie** [comment]
See issue: https://github.com/esp8266/Arduino/issues/1426
