### ISSUE TITLE
Recovering from <wdt reset>?

### ISSUE THREAD

**Issue by shayo** [esp8266/Arduino#1592]
After encountering wdt reset, why isn't it possible to do a soft reset?
Pulling the RST to GND after wdt reset has no effect and the only way I can restart the device is by pulling VCC to ground.
?
Is this the way things are suppose to work?

**Comment by Links2004** [comment]
a wdt reset, will end in a reboot normally, no need to do something.

**Comment by shayo** [comment]
Hmm. I think It's because I kept GPIO pulled down and it went back to bootloader mode.
