### ISSUE TITLE
Code compilation takes too much time. Build code in parallel.

### ISSUE THREAD

**Issue by EUA** [esp8266/Arduino#1599]
It really takes too much time to compile. For example it takes 18 seconds to compile BasicOTA.
I observer that my CPU cores are idle while compiling.
Why don't compile files in parallel?

**Comment by igrr** [comment]
This really depends on the IDE and arduino-builder, please see the relevant issue: https://github.com/arduino/arduino-builder/issues/17

**Comment by igrr** [comment]
Also see this IDE ticket — it has test builds available: https://github.com/arduino/Arduino/pull/4240

**Comment by EUA** [comment]
Thanks.
