### ISSUE TITLE
Add support for static ttf fonts files .

### ISSUE THREAD

**Issue by far5893** [esp8266/Arduino#1601]
I supose it's only nedded to add a line here:

 static String getContentType(const String& path) {
        if (path.endsWith(".html")) return "text/html";
        else if (path.endsWith(".htm")) return "text/html";
        else if (path.endsWith(".css")) return "text/css";
        else if (path.endsWith(".txt")) return "text/plain";
        else if (path.endsWith(".js")) return "application/javascript";
        else if (path.endsWith(".png")) return "image/png";
        else if (path.endsWith(".gif")) return "image/gif";
        else if (path.endsWith(".jpg")) return "image/jpeg";
        else if (path.endsWith(".ico")) return "image/x-icon";
        else if (path.endsWith(".svg")) return "image/svg+xml";
        else if (path.endsWith(".xml")) return "text/xml";
        else if (path.endsWith(".pdf")) return "application/pdf";
        else if (path.endsWith(".zip")) return "application/zip";
        else if (path.endsWith(".ttf")) return "font/ttf";
        else if(path.endsWith(".gz")) return "application/x-gzip";
        return "application/octet-stream";
    }

The line added worksforme!

**Comment by hallard** [comment]
correct it's there ;)

I strongly recommend activate browser caching for SPIFFS to avoid requesting font each time
`server.serveStatic("/", SPIFFS, "/", "max-age=86400");`

I added font/woff and /font/woff2 for bootstrap in my code also
