### ISSUE TITLE
    not able to use sendRequest(const char [5], String&)

### ISSUE THREAD

**Issue by shirish47** [esp8266/Arduino#1607]
not able to use   int sendRequest(const char * type, String payload);

getting this error "\hardware\esp8266\2.1.0-rc2\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:151:13: note:   no known conversion for argument 2 from 'String' to 'Stream*'
no matching function for call to 'HTTPClient::sendRequest(const char [5], String&)'
"
I am using it as 
       String pl="just trying this";
        int httpCode =http.sendRequest("POST",pl);

I have updated core to v2.1.0-rc2.

**Comment by shirish47** [comment]
ok I directly used this same as that function. :) 
        String pl="just trying this";
        int httpCode =http.sendRequest("POST",(uint8_t*)pl.c_str(),pl.length());

**Comment by igrr** [comment]
Fixed in 27f1a631 and released in 2.1.0
