### ISSUE TITLE
Sketch uses too much space

### ISSUE THREAD

**Issue by tuxedo0801** [esp8266/Arduino#1609]
I just tried to evaluate how much space my code is using, and figured out, that even the simple "Blink" sketch from the examples uses 216.650 bytes --> 49% ... (Board is generic with 512K (64K SPIFFS))

Same example eats on an Arduino Leonardo just 4.454 bytes --> 15% ...

So the ESP8266 needs about 48 times more space for the same sketch as the Leonardo does...
That's in my eyes very strange... Any ideas how to digg into this issue?

p.s. Tested with 2.1.0-rc2 ...

**Comment by Links2004** [comment]
that is normal the 216.650 includes the full SDK with WiFi (including WPA, WPA2, WPS), OS, SSL and so one.
but you need to add many code to get the 512K full, and the most ESP8266 have now 1MB flash or more. 
a full VNC client for example needs only 253 KB.

**Comment by jimibi** [comment]
The SDK takes a lot of space.

**Comment by igrr** [comment]
Yep, there is a lot of code which is pulled in by the SDK even if you are not, in fact, utilizing WiFi and TCP stuff.
