### ISSUE TITLE
GIT version section '.text'will not fit in region 'iram-_0_seg'

### ISSUE THREAD

**Issue by supersjimmie** [esp8266/Arduino#1611]
My code (too long to post here) compiles fine under 2.0.0 stable and also under a git version from a few weeks ago. But under the latest GIT (redownloaded twide to be sure)I now suddenly cannot compile.
<long path>ld.exe <long path>Temp\xxyy.tmp\mycode.ino.elf section '.text' will not fit in region 'iram1_0_seg'.
It does not give a clue why, I have no idea where to start searching for a solution.
(except that it seems to compiles fine under older versions)

**Comment by igrr** [comment]
Duplicate of #1582?

**Comment by supersjimmie** [comment]
Sorry, Google missed that one.  :)
