### ISSUE TITLE
Core Esp definition

### ISSUE THREAD

**Issue by Icesory** [esp8266/Arduino#1618]
We use some #if statements to detect for which platform our code is build. Like this
```
#if (defined(__AVR_ATmega32U4__))
```
Which defined name has the ESP8266? I cant find it in the ESP core files.

https://github.com/pimatic/RFControl/issues/10

**Comment by tuxedo0801** [comment]
You can use

```c++
#ifdef ESP8266
....
#endif
```

br,
  Alex

**Comment by Icesory** [comment]
Some times the things are so easy. Big thanks.
