### ISSUE TITLE
Problem cloning library

### ISSUE THREAD

**Issue by tytower** [esp8266/Arduino#162]
This may also be related to the 32 bit / 64 bit error , but I get this message when trying to clone the source -Is the reason known to anyone?

# git clone https://github.com/esp8266/Arduino.git
Cloning into 'Arduino'...
error: Problem with the SSL CA cert (path? access rights?) while accessing https://github.com/esp8266/Arduino.git

**Comment by Links2004** [comment]
ssl looks good here.
https://www.ssllabs.com/ssltest/analyze.html?d=https%3A%2F%2Fgithub.com%2Fesp8266%2FArduino.git
you shut check you local installation and update you ca-certificates.
```apt-get update && apt-get upgrade```

**Comment by tytower** [comment]
Funny I can clone other libraries here on git hub but not this one . I use Puppy Linux and run as root . I dont have apt-get at all and use a Puppy Package Manager , not that I think any of that should affect this cloning operation

**Comment by tytower** [comment]
Please look a little closer at this . I updated what I could and ended up with 100Meg of unnecessary crud on my system and it made not the slightest bit of difference . I think the problem is there with you

--------------------------------------------------------On Sun, 03 May 2015 02:00:23 -0700
Markus <notifications@github.com> wrote:

> ssl looks good here.
> https://www.ssllabs.com/ssltest/analyze.html?d=https%3A%2F%2Fgithub.com%2Fesp8266%2FArduino.git
> you shut check you local installation and update you ca-certificates.
> ```apt-get update && apt-get upgrade```
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/esp8266/Arduino/issues/162#issuecomment-98458115


-- 
Yahoo <tytower@yahoo.com>

**Comment by webguy16** [comment]
Not on linux... but it's currently working for me.
![cloningarduino](https://cloud.githubusercontent.com/assets/7414264/7447977/14b5ba86-f1db-11e4-80a0-847c1f8cf076.jpg)

**Comment by igrr** [comment]
A bit of googling shows a lot of answers how to solve this issue, like this
one: http://stackoverflow.com/a/4454754

This is obviously a client side problem, your trusted certificates are not
up to date or not accessible to git for some reason.

**Comment by tytower** [comment]
OK Thanks - Google is excellent if you know what you are looking for . I have no idea on this certificate business.
Its clearly security you choose to set up on your repository and thats your affair but it would help if there was a warning that it is secured (maybe there is ,I didn't see one)

My way round this was to clone via 
 "env GIT_SSL_NO_VERIFY=true git clone https://github.com/esp8266/Arduino" 
No security but it saves wasting a day trying to find out whats wrong


--------------------------------------------------------On Sun, 03 May 2015 18:37:32 -0700
Ivan Grokhotkov <notifications@github.com> wrote:

> A bit of googling shows a lot of answers how to solve this issue, like this
> one: http://stackoverflow.com/a/4454754
> 
> This is obviously a client side problem, your trusted certificates are not
> up to date or not accessible to git for some reason.
> On May 4, 2015 09:27, "webguy16" <notifications@github.com> wrote:
> 
> > Not on linux... but it's currently working for me.
> > [image: cloningarduino]
> > <https://cloud.githubusercontent.com/assets/7414264/7447977/14b5ba86-f1db-11e4-80a0-847c1f8cf076.jpg>
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/esp8266/Arduino/issues/162#issuecomment-98564659>.
> >
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/esp8266/Arduino/issues/162#issuecomment-98565139


-- 
Yahoo <tytower@yahoo.com>

**Comment by igrr** [comment]
> you choose to set up on your repository

I don't think Github offers any particular "choice" in terms of HTTPS certificates.

You can although use git protocol instead of https when cloning (as in ``` git clone git@github.com:esp8266/Arduino.git```) — this might resolve the certificate issue as well.
