### ISSUE TITLE
Exception 9 but epc1=0x(address) not found

### ISSUE THREAD

**Issue by supersjimmie** [esp8266/Arduino#1635]
I got an exception
```
Exception (9):
epc1=0x40000e62 epc2=0x00000000 epc3=0x00000000 excvaddr=0x3a382d32 depc=0x00000                                                                                                                                                             000

ctx: cont
sp: 3fff23a0 end: 3fff25c0 offset: 01a0
```
But when I start:
<path>xtensa-lx106-elf-objdump.exe -S <tempdir>\file.ino.elf > c:\temp\sdump.S
Then there is no 40000e62 range in the code (nothing beginning as low as 40000xxx).
It starts with 40201010, and at the end there is a part with Disassembly of section .text:
40100000 
But nothing even near 40000e62 

How could I figure out what caused the exception?

**Comment by igrr** [comment]
This address is within ROM bootloader.
However looking at [the disassembly](http://dflund.se/~kongo/esp8266.bin/iram0.txt), it seems that 0x40000e62 isnt' actually a valid instruction address.
Could you please post the complete crash dump decoded with ESP Exception Decoder, and the sketch which triggers it?
