### ISSUE TITLE
The Esp8266 creates a network using only a blink code

### ISSUE THREAD

**Issue by memristor** [esp8266/Arduino#1638]
I did tests in some codes and worked well, but if I use the "blink" code, the Esp8266 uses a WiFi channel (SSID ESP_997E13).
How can I avoid this problem?

![screenshot_20160216131616](https://cloud.githubusercontent.com/assets/11094410/13083787/480785fa-d4b5-11e5-914d-4a0b1b826b78.png)

**Comment by Links2004** [comment]
the default config in the SDK for WiFi on delivery is to open a AP (on factory reset / full wipe too).
Simple disable it with:
```cpp
WiFi.softAPdisconnect(true);
```

**Comment by memristor** [comment]
But need include:
#include <ESP8266WiFi.h>
void setup() {
  WiFi.softAPdisconnect(true);
  //your code
}

Thank you
