### ISSUE TITLE
FSBrowser editor saving

### ISSUE THREAD

**Issue by holla2040** [esp8266/Arduino#1639]
The create handler functions from the browser but can't find a way to save the edited file.

https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer/examples/FSBrowser

**Comment by holla2040** [comment]
ctrl-s saves. duh!

**Comment by vaclavvava** [comment]
OMG, where You find this VERY useful information ?

**Comment by holla2040** [comment]
I just tried it because there was no other way to see how to save.

**Comment by Dark-Smile** [comment]
hmm can someone add a SaveButton to the Code?
Thank you :)
