### ISSUE TITLE
FSBrowser data files unminified

### ISSUE THREAD

**Issue by holla2040** [esp8266/Arduino#1640]
Where is the unminified edit.htm file?

https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer/examples/FSBrowser

**Comment by comino** [comment]
dont have the resource of the non-minified one, but its based on https://ace.c9.io/   https://github.com/ajaxorg/ace-builds/

**Comment by igrr** [comment]
I think it should be pretty similar to this one: https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/examples/SDWebServer/SdRoot/edit/index.htm

Perhaps @me-no-dev has the unminified version.

**Comment by holla2040** [comment]
Looked over this link, I think you're correct. For my purposes, similar enough. Thanks.
