### ISSUE TITLE
DNS and SPIFF can't work together?

### ISSUE THREAD

**Issue by Rickgg** [esp8266/Arduino#1641]
I'm trying ot make a DNSWebServer with the included library and a SPIFF backend, but it doesn't work. Debug says: `ets Jan  8 2013, rst cause:2, boot mode: (3,7)`

Code is:
```
void setup() {
  SPIFFS.begin();
  USE_SERIAL.begin(9600);
 
  WiFi.mode(WIFI_AP);
  WiFi.softAPConfig(apIP, apIP, IPAddress(255, 255, 255, 0));
  WiFi.softAP(netName, netPass);

  dnsServer.start(DNS_PORT, "editShow.com", apIP);
 
  // handle index
  server.onNotFound([]() {
    String message = "Hello World!\n\n";
    message += "URI: ";
    message += server.uri();

    server.send(200, "text/plain", message);
  });

  server.begin();`
```

Any help or ideas for me to help would be welcome.

**Comment by Rickgg** [comment]
Found the issue, didn't include a FS header in the makefile.

**Comment by marvinroger** [comment]
What is your loop code?

**Comment by Rickgg** [comment]
Found the problem: I didn't specify the Flash size (1 mB). Now all I need is to upload the files...
