### ISSUE TITLE
ESP8266WebServer: abort requests which can not be handled

### ISSUE THREAD

**Issue by mkeyno** [esp8266/Arduino#1642]
I used the last staging version of the library and set up module for access point and run the SPIFF simple authentication sample code , the problem is when just open  one tab of browser , there is no problem but if you concurrently have couple of open tabs (for example my gmail, yahoo mail, ...) which they are constantly send the request to the server , the ESP will chocked soon and need the hardware reset, and firmware auto-reset is not working
what I'm thinking about is to find the way that close the connection  As Soon As find requested page or file is not located in the SPIFF or anywhere inside the chip
maybe following code would be helpful to my idea

`
/////////////// in set up
server.onNotFound(handleOther);
///////////////////////////
handleOther()
{
check if the requested file not exits sever the concretion before choking the ESP
}
`

**Comment by mkeyno** [comment]
@igrr  @Links2004  guys any suggestion?

**Comment by Links2004** [comment]
your requests overload the ESP socktes.
do you run CaptivePortal example or the DNS server with settings like this:
```cpp
 dnsServer.start(DNS_PORT, "*", apIP);
```
normally the browser do a DNS first before it connects to a IP.

some more infos will sure help:
 - your code or link to the examle you use (when not modified)
 - serial debug log of the ESP (https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md)
 - if you have a stack dump (https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md)

**Comment by mkeyno** [comment]
@igrr @Links2004 
yes , I used `dnsServer.start(DNS_PORT, "*", apIP);  ` in AP mode  and MDSN in station mode, but my questions is how to optimize the respond speed and reliability when normally people open couple of tabs in browsers ? is there way to cut down the request when server realize , it is not from the true client, or make Q to not let the serve  be choken

**Comment by Links2004** [comment]
to make this filtering at least the HTTP header from the client need to be revised.
you can try the async webserver form @me-no-dev it can handle multible requests way better.
https://github.com/me-no-dev/ESPAsyncWebServer
