### ISSUE TITLE
Wemos d1 mini pin mapping with MFRC522(RFID Reader)

### ISSUE THREAD

**Issue by KumJay** [esp8266/Arduino#1647]
Hi,

I cannot get the Di mini working with the RFID reader. It works fine with Arduino board. 

The issue is with the "Reset" pin. How do we map the reset with RC522?

Thanks
Jayant

**Comment by thunderace** [comment]
Don't use the ESP8266 GPIO15 for RST (GPIO4 is OK), tested on NodeMCU v1.0
