### ISSUE TITLE
Support PUT with HTTPClient

### ISSUE THREAD

**Issue by torntrousers** [esp8266/Arduino#1649]
I need to do do an HTTP PUT for a service but it looks like HTTPClient only supports GET and POST. 

Could PUT be added too?

(And I suppose the other HTTP verbs might be useful one day, but I'm only missing PUT presently)

**Comment by Links2004** [comment]
all possible "verbs" are supported GET and POST have own functions to get easyer to it.
```cpp
http.sendRequest("PUT", dataptr, len);
```
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.cpp#L288-L304

**Comment by torntrousers** [comment]
Oh, I see. Thanks.
Why not add easier way for all the verbs? (but I'll close this as it will do what I need)
