### ISSUE TITLE
Espressif SDK 1.5.2 released

### ISSUE THREAD

**Issue by osos** [esp8266/Arduino#1653]
http://bbs.espressif.com/viewtopic.php?f=46&t=850

Might be worth to include in the upcoming 2.1.0 release of esp8266-arduino?

**Comment by andig** [comment]
Would be great if we were able to recompile lwip, too? Imho higher priority than sdk version bump?

**Comment by andig** [comment]
from gitter:

> to use (gcc lwip) instead of Espressif-provided one, you need to replace `-llwip` with `-llwip_gcc` in `platform.txt`, and restart the IDE.

**Comment by kaeferfreund** [comment]
@andig 
thx for the advice. Is there any obvious advantage with that?

**Comment by andig** [comment]
> thx for the advice. Is there any obvious advantage with that?

Not unless you're debugging and get stuck when the code touches the lwip internals.

**Comment by andig** [comment]
Quick note here- async web server is running rock stable with sdk 1.5.2 according to my tests. The ugly crashes have been fixed thanks to @igrr and the insights from lwip.

**Comment by kaeferfreund** [comment]
are you referring to your fork or me-no-devs version?

**Comment by andig** [comment]
me-no-dev plus the open pr on the webserver for handling lowmem.
