### ISSUE TITLE
ESP8266WebServer Handle JSON post via request body.

### ISSUE THREAD

**Issue by mikehole** [esp8266/Arduino#1670]
#### Hardware
Hardware:			All versions
Core Version:      	       Latest

### Description

Apologies for using an issue to post this question. 

I am looking to have the web server handle JSON that is posted to the server as the request contents. How would it be possible to achieve this?

**Comment by ajvpot** [comment]
Here's my code.
```
#include <ArduinoJson.h>
...

  server.on("/config/set", HTTP_POST, [](){
    StaticJsonBuffer<200> newBuffer;
    JsonObject& newjson = newBuffer.parseObject(server.arg("plain"));

...

    server.send ( 200, "text/json", "{success:true}" );
  });

**Comment by mikehole** [comment]
Aha got it was looking through the code and didn't spot that the whole body was being placed in the plain argument!

**Comment by mikehole** [comment]
Works a treat thanks for your help by the way :+1:

**Comment by enzosagretti** [comment]
I am traing this Serial.println("plain: " + server.arg(val)); but i cant get to work. Return Empty

**Comment by bkomac** [comment]
Look out for the size of the buffer. If your post payload is bigger then 200 it will be empty at the end.
Try with something bigger (StaticJsonBuffer<500> newBuffer;) or with  'DynamicBuffer'.

**Comment by michaelvar** [comment]
What part of the request is the "plain"?
