### ISSUE TITLE
SPIFFS 128kb ?

### ISSUE THREAD

**Issue by bbasil2012** [esp8266/Arduino#1680]
Can I create and use SPIFFS 128kb size on 512kb module?
If yes, how to I can do it ?

**Comment by krzychb** [comment]
Hi bbasil2012,

Set up of custom SPIFFS size has been done and documented by hallard - please check out https://github.com/esp8266/Arduino/issues/1163

Krzysztof

**Comment by hallard** [comment]
Done with PR #1684
