### ISSUE TITLE
UART RX BUFFER SIZE

### ISSUE THREAD

**Issue by snowbizz** [esp8266/Arduino#1683]
Hi, 
In 2.0.0 version there were two definitions of UART's buffer size in HardwareSerial.h file:
#define SERIAL_TX_BUFFER_SIZE 256
#define SERIAL_RX_BUFFER_SIZE 256

After 2.1.0 it is gone and buffer size can't be changed.
I can't receive more than 128 chars which is default value.

I found also in uart.h file:
#define UART_TX_FIFO_SIZE 0x80
But it is only for TX and I am not sure is this works.

Cheers.

**Comment by igrr** [comment]
Software managed UART buffer has been removed in favor of hardware RX buffer, which is 128 characters long.

**Comment by snowbizz** [comment]
So there is no chance to receive more than 128 chars by Hardware Serial?
Because in version 2.0.0 I was able to receive more than 128 chars by Hardware Serial.

**Comment by penfold42** [comment]
You I'll have to grab the characters more often and maintain your own bigger software buffer.

The main purpose of the uart buffer is to catch characters while your software is busy doing other things.

**Comment by snowbizz** [comment]
It is working this way, but in my opinion - having a possibilty to change a buffer size will be a nice feature :)

**Comment by far5893** [comment]
You only need is to listen hw buffer overrun interrupt .
