### ISSUE TITLE
Watchdog fires after 100 WiFi clients connctions

### ISSUE THREAD

**Issue by Picatek** [esp8266/Arduino#169]
The following code stopped after 100 loops with a wdt reset
void loop(){
if (!client.connect(hostUrl, hostPort)) {
                Serial.println("connection failed");
                return;
            }else{
               Serial.println("Sending to server"+String(hostUrl)+String("  ")+String(cnt++));
               uint32_t ctime=millis();
            client.print(String("POST /page?tstampe=") + String(ctime) +
            " HTTP/1.1\r\n" + "Host: " + hostUrl + "\r\n" + "Connection: close\r\n\r\n");
            }
            yield();
          delay(10);
          while(client.available()){
              String line = client.readStringUntil(0);
              Serial.print(line);
          }
          client.read();
          client.flush();
          client.stop();
}

**Comment by Links2004** [comment]
is the problem still present?
