### ISSUE TITLE
The Board manager links are timing out

### ISSUE THREAD

**Issue by bmitov** [esp8266/Arduino#1691]
http://arduino.esp8266.com/stable/package_esp8266com_index.json
and
http://arduino.esp8266.com/staging/package_esp8266com_index.json

are both timing out both from the Arduino IDE and in Chrome.
It seems the server is down, or the links are broken.
Pasting any of them in Chrome or Firefox will come back with timeout error 'The connection has timed out'

**Comment by spi-ke** [comment]
duplicate https://github.com/esp8266/Arduino/issues/1689
