### ISSUE TITLE
Check return value of udp_send and forward it WiFiUdp::endPacket

### ISSUE THREAD

**Issue by everslick** [esp8266/Arduino#1696]
I see high packet loss when sending rapid UDP packets without yield() or delay(). A yield() after each packet does only help slightly, but delay(1) after each Udp.write() works around that bug.

Problem description:

The MAC layer seems to drop packets if the send queue is full, but this condition is not reported back to the application (endPacket() should return 0 in this case).

**Comment by igrr** [comment]
I have addressed this in commit aa67d1c, however it appears that udp_sendto doesn't actually return errors when underlying packet buffer is full.

**Comment by everslick** [comment]
so i guess it's up to espressif to fix this then. :-/ no idea where to
report this though.

**Comment by barsznica** [comment]
May be related to [my problem](Similar to my problem. [Issue #2340](https://github.com/esp8266/Arduino/issues/2340)).
