### ISSUE TITLE
N25Q032A SPI Flash Memory unsupported?

### ISSUE THREAD

**Issue by kriswiner** [esp8266/Arduino#1700]
Thanks for a great Arduino overlay for the ESP8266. I have used it successfully for custom ESP8266 boards I have been designing. Here is an example:

https://www.tindie.com/products/onehorse/esp8266-add-on-for-teensy-32/

I started using the 4 Mbit Macronix MX25L4006E, then switched to the 8 Mbit Winbond W25Q80BLUX1G, both of which work very well using the Arduino overlay. I usually use 80 MHz CPU, 40 MHz SPI and either DIO or QIO (both usually work). When using the W25 I choose 1 M (64k SPIFFS), which also works well. I have used the OTA capability and find the chip and the Arduino overlay very useful.

I recently tried a larger SPI NOR flash the 32Mbit Micron N25Q032A but I have been unable to get any program to run using the Arduino IDE. I was successful using a recent ESP-SDK compiled firmware (i.e., \Documents\Downloads\esp_iot_sdk_v1.5.0_15_11_27\esp_iot_sdk_v1.5.0\bin\esp_init_data_default.bin, etc) flashing the board and getting the ESP8266 with 32Mbit N25 flash to respond to AT commands and it seems to flash and work just fine.

I tried all the available variants including 4M(1 M SPIFFS) and 4M(3M SPIFFS) as well as Adafruit's Huzzah, Sparkfun Thing, Olimex's board settings, etc. Nothing works. By that I mean the code compiles, it's flashed to the SPI flash, but when finished and restarted nothing happens. I ran a simple led blink program including serial out and not a thing happens after successful flashing. This is in contrast to a blinking led and serial output when using the exact same program and board (exact same circuit) redesigned with the W25Q80 flash.

So in sum, the board design works well, I can use it in AT mode using the precompiled SDK, I can flash the board using the Arduino IDE in the usual way, but no program seems to run after flashing using the Arduino IDE even though the same board design and program as well as procedure works well with another (W25) flash memory.  Very strange.

Thomas Roell suggests the following:
"
>I did discover an odditiy with N25Q. SFDP lists 1-4-4 with 9 dummy         
>cycles, and 1 mode bit cycles. Normally a QSPI controller cannot do 1     
>mode bit in 1-4-4. It needs to use 8 dummy cycles and 2 mode bit cycles      
>(i.e 8 bits of mode data). I wonder whether the ESP8266 code trips over that.    
>Winbond/Macronics always use mode bit cycles that equate to full bytes ...    
>
>Perhaps the ESP8266 code can read the SDFP correctly figures out the 
>size and then decides it does not know what to do with the device.
"

I wonder, is the Arduino IDE somehow hardwired to not support the N25Q032A and can you recommend anything I could do to make use of this flash with your Arduino IDE? Thanks.

**Comment by Duality4Y** [comment]
correct me if i am wrong, but the spi bus for the flash chip is weird to some hardware in the chip that makes it appear memory mapped. there for if the chip has some different communictation protocol it's not supported and no software can do anything about it.

**Comment by kriswiner** [comment]
There is no reason for the memory map or commo protocol to be different, but indeed if they are different in some way and this is not supported by the Arduino IDE, then yes, this could be the reason for the flash not allowing the ESP program to run.

The ESP SDK doesn't seem to have any trouble with it though.

**Comment by igrr** [comment]
Could you please do the following:
- capture and post here serial output from bootloader at 74880 baud
- use esptool.py to read back the contents of flash and then use diff or some other tool to verify that the binary is uploaded correctly

**Comment by kriswiner** [comment]
Here is the program I compiled and flashed:
`#include "Wire.h"   
//#include <i2c_t3.h>
#include <SPI.h>
#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <ESP8266WebServer.h>
#include <ESP8266mDNS.h>
#include <ArduinoOTA.h>

void setup() {
      pinMode(15, OUTPUT);
      Serial.begin(57600);
      
    }
     
    void loop() {
      digitalWrite(15, HIGH);
      Serial.println("test");
      delay(500);
      digitalWrite(15, LOW);
      delay(500);
    }`


Here's what I see upon flashing. I don't have a choice of 74880 baud so I picked 57600:

`Sketch uses 235,194 bytes (22%) of program storage space. Maximum is 1,044,464 bytes.
Global variables use 34,820 bytes (42%) of dynamic memory, leaving 47,100 bytes for local variables. Maximum is 81,920 bytes.
C:\Documents and Settings\Kris\Local Settings\Application Data\Arduino15\packages\esp8266\tools\esptool\0.4.6/esptool.exe -vv -cd ck -cb 57600 -cp COM4 -ca 0x00000 -cf C:\DOCUME~1\Kris\LOCALS~1\Temp\buildbb6dc20b0e4f3063ce19eebcbd902ae8.tmp/esp8266blinky.ino.bin 
esptool v0.4.6 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to ck
	setting baudrate from 115200 to 57600
	setting port from COM1 to COM4
	setting address from 0x00000000 to 0x00000000
	espcomm_upload_file
	stat C:\DOCUME~1\Kris\LOCALS~1\Temp\buildbb6dc20b0e4f3063ce19eebcbd902ae8.tmp/esp8266blinky.ino.bin success
	setting serial port timeouts to 1000 ms
opening bootloader
resetting board
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_open
Uploading 239344 bytes from C:\DOCUME~1\Kris\LOCALS~1\Temp\buildbb6dc20b0e4f3063ce19eebcbd902ae8.tmp/esp8266blinky.ino.bin to flash at 0x00000000
	erasing flash
	size: 03a6f0 address: 000000
	first_sector_index: 0
	total_sector_count: 59
	head_sector_count: 16
	adjusted_sector_count: 43
	adjusted_size: 02b000
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	setting serial port timeouts to 10000 ms
	setting serial port timeouts to 1000 ms
	espcomm_send_command: receiving 2 bytes of data
	writing flash
..........................................................................................................................................................................................................................................
starting app without reboot
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	espcomm_send_command: receiving 2 bytes of data
closing bootloader
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
`

It looks just like it should and on my other ESP modules with the 8 Mbit Winbond flash I would expect the TX led to be blinking once a second; not with the 32 Mbit flash though.

I am not sure I know how to use esptool.py. Where can I get this and is there a description of how to use it?

**Comment by igrr** [comment]
Sure, you can get esptool.py here: `https://github.com/themadinventor/esptool`. This page also has instructions on how to use it. You need `read_flash` command.

Also please do post the output from serial port captured at 74880 baud. Open Arduino serial monitor, set baud rate to 74880, and then reset the ESP. Copy&paste what you see.

**Comment by igrr** [comment]
<img width="569" alt="screen shot 2016-03-01 at 11 04 16" src="https://cloud.githubusercontent.com/assets/4349050/13421147/68b02508-df9d-11e5-8067-b63c2bf81f3e.png">

Attaching an illustration of what I mean when I say "Serial monitor" and "74880 baud".

**Comment by kriswiner** [comment]
![espcapture](https://cloud.githubusercontent.com/assets/6698410/13421608/3a2c8fb8-df44-11e5-8ada-b3abef28efff.jpg)

**Comment by igrr** [comment]
Okay, this shows that the binary was not written correctly to the chip (see `csum err` message).
Now you need to use esptool.py to read back contents of flash memory and compare them to the original binary. See if there some random errors, or the binary wasn't written at all...

**Comment by kriswiner** [comment]
Yes, but which contents. it seems I need to specify a memory address, memory size and a filename. What are these then?

**Comment by igrr** [comment]
It's there in the log you have posted above:
`Uploading 239344 bytes from C:\DOCUME~1\Kris\LOCALS~1\Temp\buildbb6dc20b0e4f3063ce19eebcbd902ae8.tmp/esp8266blinky.ino.bin to flash at 0x00000000`

So you need to read 239344 bytes starting at address 0. Pick any file name you like. esptool.py will read flash contents into the file you have specified. Then compare the contents of the file with the contents of `C:\DOCUME~1\Kris\LOCALS~1\Temp\buildbb6dc20b0e4f3063ce19eebcbd902ae8.tmp/esp8266blinky.ino.bin`.

**Comment by kriswiner** [comment]
Not sure what I am looking for, but the first page seems to be identical:

![comparebin](https://cloud.githubusercontent.com/assets/6698410/13422549/72a8d92c-df4a-11e5-8627-40712d024bab.jpg)

**Comment by kriswiner** [comment]
So as I reported, the board seems to get flashed correctly (modulo the checksum error). It really has to be something in the Arduino IDE since when I load the SDK firmware binaries I can get the board to respond with AT commands. In other words, there is no hardware design error or component malfunction but something about the Arduino IDE memory allocation which messes up the ESP function? I did not specifically add a SPIFFS and my only choices seem to be either 3M + 1 M SPIFFS or 1M + 3 M SPIFFS. Does this matter? I tried flashing at 9600 baud (painfully slow) but the behavior didn't change. Can't be power since using the same setup the AT commands work. How can I tell if the bootloader is missing? Running out of options...

**Comment by igrr** [comment]
Serial output you have posted above indicates that the first stage bootloader (inside the ESP8266 mask ROM) was not able to load second stage bootloader from flash successfully, signalling a checksum error.

Did i get that correctly that you were able to run the same binary produced by Arduino IDE on other board, which used a different flash chip? If that is the case, then we can rule out the possibility that Arduino IDE generated a binary with incorrect checksum.

Since you have verified that the flash chip contents match the original binary *(have you verified just the first & last pages or the full contents?)*, only one option is left. Apparently ROM bootloader is not able to read the contents of flash correctly, thereby reporting a checksum error. ROM bootloader reads flash configuration for the header of binary image. Initially it talks to the flash chip over SPI at low speed, reads a few bytes at the beginning, obtains flash configuration parameters stored in these bytes, and proceeds to set up flash interface according to these parameters. Could you please do a hex dump of the first 16 bytes of a binary (produced by the SDK) which works for you and responds to the AT commands?
Then we can compare flash configuration from that binary with flash configuration from the binary generated by Arduino.

**Comment by kriswiner** [comment]
Yes, I was able to run this program successfully using the exact same board design but with the W2580 1 Mbit flash.

I didn't check that every entry of the .bin files was the same; I don't seem to have a diff function in the CMD window.

This what I get from the board with the 32 Mbit N25 flash after loading with the ESP SDK and using AT+RST:

`AT version:0.51.0.0(Nov 27 2015 13:37:21)
SDK version:1.5.0
compile time:Nov 27 2015 13:58:02
OK
AT+RST


OK

 ets Jan  8 2013,rst cause:1, boot mode:(3,0)

load 0x40100000, len 1396, room 16 
tail 4
chksum 0x89
load 0x3ffe8000, len 776, room 4 
tail 4
chksum 0xe8
load 0x3ffe8308, len 540, room 4 
tail 8
chksum 0xc0
csum 0xc0

2nd boot version : 1.4(b1)
  SPI Speed      : 40MHz
  SPI Mode       : DOUT
  SPI Flash Size & Map: 32Mbit(1024KB+1024KB)
jump to run user1 @ 1000

r
ready
`

**Comment by kriswiner** [comment]
This is what the first 16 bytes look like starting at address 0x000000:
![Uploading test2.bin.jpg…]()

**Comment by kriswiner** [comment]
![test2 bin](https://cloud.githubusercontent.com/assets/6698410/13451892/f49aec4c-dff7-11e5-8692-116a9b4ea24f.jpg)
![Uploading test2.bin.jpg…]()

**Comment by igrr** [comment]
Okay, so this binary has "DOUT" flash mode (third byte 0 = QIO, 1 = QOUT, 2 = DIO, 3 = DOUT).
Your binary, OTOH, has "DIO" flash mode. We don't have DOUT mode configurable via Arduino IDE menu, so you will have to add it manually. 
Close the IDE and find `boards.txt` file in the ESP8266 package. If you have installed it via Boards Manager, it'll be somewhere under AppData/Arduino15/packages/esp8266.
Find the following two lines:
```
generic.menu.FlashMode.dio=DIO
generic.menu.FlashMode.dio.build.flash_mode=dio
```

and add another two next to them:
```
generic.menu.FlashMode.dout=DOUT
generic.menu.FlashMode.dout.build.flash_mode=dout
```
Save the file, start the IDE, select new mode from the list and build the binary again.

**Comment by kriswiner** [comment]
Outstanding!

That worked. Thanks you very much for your expert an patient help!

Can this option be added to a future Arduino IDE release or must anyone who uses this 32 Mbit flash also have to add these lines manually?

In any case it works for me now, so thank you again!
