### ISSUE TITLE
Readme.md image links broken

### ISSUE THREAD

**Issue by TheQuestor** [esp8266/Arduino#1701]
nearly all of the image links in the README,md are 404/broken

**Comment by igrr** [comment]
You mean https://github.com/esp8266/Arduino/blob/master/README.md? Seem to work fine here...

**Comment by TheQuestor** [comment]
odd I thought I had the proper links which is https://github.com/esp8266/Arduino/tree/d218c4ead3df50ac9cbdfa7144698850a03f2066 which has all the images pointing to non-existant [404] images.

**Comment by igrr** [comment]
That link points to the repository at commit d218c4ead3df50ac9cbdfa7144698850a03f2066, which was a few months ago. If you need the current version, please visit https://github.com/esp8266/Arduino/.
