### ISSUE TITLE
Typo in eagle_soc.h ?

### ISSUE THREAD

**Issue by gdhgdhgdh** [esp8266/Arduino#1705]
Please excuse any naivety!

In https://github.com/esp8266/Arduino/blob/master/tools/sdk/include/eagle_soc.h#L151-L153 should these three lines not be using `PERIPHS_RTC_BASEADDR` instead of `PERIPHS_TIMER_BASEDDR` ?

Cheers,
Gavin.
##

**Comment by igrr** [comment]
I think these should be TIMER_REG_READ, TIMER_REG_WRITE, etc., because later on there is `#define NOW()` which reads the value of timer 2 count register. So it's probably a typo, but not in `*_BASEADDR`, but in define name.

**Comment by devyte** [comment]
I agree with @igrr, I think the names are just wrong.
They correct ones should be defined, and these should be deprecated most likely.
