### ISSUE TITLE
HardwareSerial do not Read

### ISSUE THREAD

**Issue by shguro** [esp8266/Arduino#172]
Hi Guys,
the serial interface do not read in the recent Git Version. I have tested them with an small easy Sketch but it read not correct.
I have tested an older Revision of the HardwareSerial.cpp that work.

**Comment by reaper7** [comment]
Serial still do not read.
Last good commit are from 1 may,
All changes made after 1 may => reading impossible

**Comment by igrr** [comment]
Fixed in the latest trunk.
