### ISSUE TITLE
Support all SPI modes

### ISSUE THREAD

**Issue by PlatenySmartiks** [esp8266/Arduino#1751]
Hardware:			ESP13
Core Version:      	2.1.0-rc2

How can i change the SPI data mode? The setDataMode is TODO.

**Comment by Links2004** [comment]
SPI mode 0 + 1 are possible with the ESP.
SPI mode 2 + 3 are not possible with the Hardware SPI.

https://github.com/esp8266/Arduino/blob/master/doc/libraries.md#spi

**Comment by igrr** [comment]
@Links2004 check this out: https://github.com/UncleRus/esp-open-rtos/blob/core/spi/core/esp_spi.c#L73-L86
