### ISSUE TITLE
ESP8266 SUBNET in AP Mode

### ISSUE THREAD

**Issue by alaintanguay** [esp8266/Arduino#1756]
Hello
I try to change the Mask on softAPConfig , to 255.0.0.0 , but still 255.255.255.0
The IP have change , but not the mask

this is my code

IPAddress ip(10,0,0,101);
WiFi.softAP(apssid,appassword);
WiFi.softAPConfig(ip, ip, IPAddress(255,0,0,0));

Thanks for your support
##

**Comment by mtongnz** [comment]
I Bellerive my pull request should fix this
https://github.com/esp8266/Arduino/pull/2619

**Comment by devyte** [comment]
I can't reproduce this with latest git, netif params work fine.
Closing.
