### ISSUE TITLE
Usage of new functions in WiFiClientSecure.h

### ISSUE THREAD

**Issue by noelgeorgi** [esp8266/Arduino#1762]
Any help regarding usage of these functions is appreciated:
** void setCertificate(const uint8_t* cert_data, size_t size);
  void setPrivateKey(const uint8_t* pk, size_t size);

  bool loadCertificate(Stream& stream, size_t size);
  bool loadPrivateKey(Stream& stream, size_t size);

  template<typename TFile>
  bool loadCertificate(TFile& file) {
    return loadCertificate(file, file.size());
  }

  template<typename TFile>
  bool loadPrivateKey(TFile& file) {
    return loadPrivateKey(file, file.size());
  }**

I am using mqtt with ssl, so i have to provide ca.crt to esp any idea?

**Comment by sabas1080** [comment]
+1

**Comment by igrr** [comment]
There is an open issue regarding documentation for these methods: #1743. Closing this one as duplicate.
