### ISSUE TITLE
Firmware is lost when I reset my ESP.

### ISSUE THREAD

**Issue by polishdude20** [esp8266/Arduino#1777]
----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-07?
Core Version:      	?2.1.0-rc2?

### Description

I've got the ESP8266-07 and I flashed it with the v0.9.5.2_ AT_Firmware and it works great! I can send AT commands and even get my Arduino to send them and all is working until..

When I power off my unit and power it on again without grounding the reset pin, it works. Once I ground the reset pin and pull it back up to 3.3 volts, it just loses its firmware. No more AT responses just gibberish. I have to reflash the firmware again for it to work. Any help?

### Settings in IDE

Module:  			Generic ESP8266-07 Module
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?

**Comment by igrr** [comment]
Hi, unfortunately this repository is not about using ESP8266 with AT commands. This repository is about running your own Arduino code *on* the ESP8266. Please post your question related to AT commands on the ESP8266 community forum or Espressif BBS. Thanks.
