### ISSUE TITLE
Update docs with new HardwareSerial buffer size

### ISSUE THREAD

**Issue by PhilColbert** [esp8266/Arduino#1786]
From 2.0.0. to 2.1.0 the TX and RX buffer sizes are gone  :(

My code is dealing with GPS input therefore requires a large buffer size to cope.... please put it back  ! :)
##

**Comment by igrr** [comment]
Removing the software-managed buffers was intentional (#1496), because otherwise we had issues when Serial was used from tasks other than main arduino task. For your application you can probably poll data at a higher rate. There is also a suggestion to support Arduino serialEvent API (#752).

**Comment by PhilColbert** [comment]
Thank you for the reply.

Unfortunately I cant poll at a higher rate as the data requires parsing as it comes in and this requires uploading back to a wificlient and to a radio transmitter, this takes some time, in that time the serial buffer fills ...

Sorry I am still new to coding with the esp so might be coding it incorrectly.

I will just have to stick with 2.0.0 for now.

Thank you anyway.

**Comment by PhilColbert** [comment]
I am receiving around 500 - 1000 bytes  / sec...  any idea how to deal with this issue in 2.1.0 without the serial buffer issue?

Thanks

**Comment by tablatronix** [comment]
Does this mean the docs need to change ?

> Apart from hardware FIFO (128 bytes for TX and RX) HardwareSerial has additional 256-byte TX and RX buffers

**Comment by far5893** [comment]
I suppose that hardaware fifo is still used.

**Comment by devyte** [comment]
The docs for HardwareSerial need to be updated to describe the setRxBufferSize() method.
