### ISSUE TITLE
Hardware Reset

### ISSUE THREAD

**Issue by rokison** [esp8266/Arduino#179]
Is there a way to trigger a hardware reset?
It would be great after the AP stores an SSID and password into the EEPROM it rebooted automatically to try and connect to it.

**Comment by Zeron** [comment]
From the readme file:

ESP.reset() resets the CPU.

**Comment by rokison** [comment]
Couldn't find that in the readme I have.
It also doesn't compile, saying "ESP was not declared in this scope".
Sure I'm making a rookie error, but any further guidance much appreciated!

**Comment by rokison** [comment]
Am I just using an old build?!

**Comment by Zeron** [comment]
ESP.reset() was added with this commit: https://github.com/esp8266/Arduino/commit/7b70acf3377d08e52d4ed3da364eb36da037c7d6  on April 11

**Comment by rokison** [comment]
I am feeling like a complete noob but I can't get a working version with the ESP feature.
Is there any way the "download" for windows linked to from the home page of this repository could be updated to contain this functionality. I'm afraid I'm not quite capable of building from source!

**Comment by duncan-a** [comment]
The last Windows version I managed to download and install (
https://ci.appveyor.com/api/buildjobs/8s54dteakqvt3e3q/artifacts/build/windows/arduino-1.6.1-windows.zip)
appears to be Win64 only - trying to run Arduino.exe briefly flashes up an
error message that it's not a valid Win32 file...

I am a complete noob, so there may be something I'[m not understanding...

**Comment by igrr** [comment]
@duncan-a  The appveyor builds are 64-bit, so you can't run them on 32-bit Windows.

**Comment by duncan-a** [comment]
OK - where can I find a recent 32 bit version?

Many of the problems I had with the .zip file on 'Releases' (downloaded
about a month ago) are, reputedly, fixed now...

As an aside, I can't get the 1.6.1 IDE to recognise the RF24 library (for
the nRF24L01)
