### ISSUE TITLE
question about NTPclient

### ISSUE THREAD

**Issue by SharonX4** [esp8266/Arduino#1793]
how can i use it  on Arudino Leonardo and ESP8266-05?

**Comment by igrr** [comment]
NTPClient sample is written to run on an ESP8266, not on Arduino Leonardo. If you want to use ESP8266 as a serial-to-wifi adapter, you have to look at other libraries, such as https://github.com/sparkfun/SparkFun_ESP8266_AT_Arduino_Library. This repository is dedicated to tools and libraries which run on the ESP8266 itself, without an external MCU.
