### ISSUE TITLE
Infinite crash/reboot loop

### ISSUE THREAD

**Issue by StewieTee** [esp8266/Arduino#1797]
- decoded 1st stack dump, at end of this message. Several others stack-dumps also included as part of the crash/reboot loop

### Basic Infos
Arduino 1.6.7 (windows and MAC)

#### Hardware
Hardware:			multiple types as below
Core Version:      	       tried feb-28th-stable and github version as of 19th March. Windows and Mac.

### Description
Trying to use the provided example 'WIFITelnetToSerial' which causes an infinite crash/reboot loop.
I can compile/run other assorted software with no problem but when I try the above example I get the reboot-loop every time.
I have tried this on a:
NodeMCU 1.0 board (setting as per default arduino IDE)
ESP-01 (512KB) & 1MB version
ESP-07 (1MB)
WEMOS mini (setting as per arduino IDE)

### Settings in IDE
All with 80Mhz cpu, 40Mhz flash, reset method nodeMCU, serial upload. Tried DIO and QIO.

After trying the failing software above, I can still compile and upload other software and it runs OK.
Tried complete flash-erase using esptool and then loading the failing software into the clean chip but no difference.
When the software is first uploaded and it starts up, after the first crash-fail it just sits and does nothing. Pressing reset then causes the infinite loop of reboot cycles.
exception type is:
exception 2 	InstructionFetchErrorCause

There are other items/programs that cause the same effect, compiled size does not seem to be relevant.
Sometimes the boot process gets as far as trying to connect to the local wifi. Sometimes works, sometimes crashes mid way.

### Sketch
supplied example 'WIFITelnetToSerial' in the distribution.

### Debug Messages
This is the first load into a flash erased chip. After the first crash, the RST button was pressed and the reboot loop commences.

om 16 
�
Exception (2):
epc1=0x3ffe84a7 epc2=0x00000000 epc3=0x00000000 excvaddr=0x3ffe84a4 depc=0x00000000

ctx: sys 
sp: 3ffffca0 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffe40:  4010418a 0000002d 7fffffff 00000002  
3ffffe50:  0000012d 00000030 0000001c ffffffff  
3ffffe60:  401030ef 00080000 00000001 fffffffe  
3ffffe70:  00000000 40206868 00002200 4000050c  
3ffffe80:  3fffc278 40102dec 3fffc200 00000022  
3ffffe90:  3ffffea0 00000004 3ffffef0 3fffff01  
3ffffea0:  40107020 00000000 3ffeff60 00000000  
3ffffeb0:  3ffe8004 00000000 000000a5 00000000  
3ffffec0:  feefeffe 00000000 00000000 3ffffe50  
3ffffed0:  00000000 00000000 00000001 3ffeed00  
3ffffee0:  3fffff00 3ffffef0 00000004 00000030  
3ffffef0:  000000ff 3ffe85aa 3ffeff60 000000e5  
3fffff00:  000000a5 00000005 00000081 00000001  
3fffff10:  3fff01dc 40221c4a 3fff098c 4010031d  
3fffff20:  3ffe8984 000001c0 3ffeeca0 40100426  
3fffff30:  00000000 00000001 40206807 40100537  
3fffff40:  3ffee3e0 00000000 3fff015c 401008c1  
3fffff50:  40206870 3ffe8984 3fff0164 40107218  
3fffff60:  3ffeeca0 0000008c 0000008c 40219060  
3fffff70:  402070f4 ffffffff 00000000 00000001  
3fffff80:  3ffec2c0 40206a6a 3fffdab0 00000000  
3fffff90:  3fffdcc0 3ffe8bb8 00000000 4020379b  
3fffffa0:  3ffe8bb8 40000f49 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset
rl

**Comment by igrr** [comment]
See #1695.
