### ISSUE TITLE
This is not a real issue but more a suggestion about avrisp over wifi

### ISSUE THREAD

**Issue by fredericplante** [esp8266/Arduino#1803]
messages here
Hi Would it be possible to use the same kind of process to upload a sketch to an arv unit, arduino nano for example, using the ESP8266 as programmer, but instead of sending it using wifi, it could simply use a binary pre stored on a SDcard, instead of using the computer to send it.

This could allow to programme a bunch of mode on a SDcard for the AVRs and simply up load them using the ESP as it need

**Comment by Duality4Y** [comment]
sounds like that should be possible :)
