### ISSUE TITLE
ESP-WROOM-02 support?  Supported module list?

### ISSUE THREAD

**Issue by Humancell** [esp8266/Arduino#1805]
I'm curious if there is a list of supported modules, and specifically is the ESP-WROOM-02 is supported?

We're using the ESP-12F extensively, and have been testing on the ESP07 also ... with the upcoming ESP-07s coming soon.

Are their "officially" supported modules?

**Comment by krzychb** [comment]
Hi Humancell,

The list of supported modules is [here](https://github.com/esp8266/Arduino/blob/master/doc/boards.md). Among them I see ESPino (WROOM-02 Module) by ThaiEasyElec that has ESP-WROOM-02 on board.

If you have a bare ESP-WROOM-02 module, then I would select "Generic ESP8266 Module" and adjust settings to match ESP-WROOM-02.

Krzysztof

**Comment by deepikavira** [comment]
@krzychb When you say change the settings to match ESP-WROOM-02 does that mean going to tools and then change the flash size, flash frequency etc..

**Comment by krzychb** [comment]
@deepikavira, yes, this is what I meant.  "Generic ESP8266 Module" has all possible options available / exposed to talk to any supported module.

![new picture 1](https://cloud.githubusercontent.com/assets/12953787/17079802/ff658b84-511a-11e6-840f-c087e63e7e67.png)

**Comment by deepikavira** [comment]
Ok thank you I will try this and let you know how it works
