### ISSUE TITLE
ethernet class

### ISSUE THREAD

**Issue by rbkulkarni811** [esp8266/Arduino#1806]
very beginning of project I came across below problem....

Please anyone suggest me solution......  

error: local class 'class setup()::EthernetClass' shall not have static data member 'uint16_t setup()::EthernetClass::_server_port [4]' [-fpermissive]

   static uint16_t _server_port[MAX_SOCK_NUM];

**Comment by igrr** [comment]
Hi,
To help us provide you with support please fill out all the fields of the issue template. Also please share the sketch which you are trying to compile.
