### ISSUE TITLE
not able to start

### ISSUE THREAD

**Issue by rbkulkarni811** [esp8266/Arduino#1808]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```
Arduino: 1.6.8 (Windows 7), Board: "Arduino/Genuino Uno"

sketch_mar22a:9: error: unable to find numeric literal operator 'operator"" O'

 byte mac[] = { 0x38, 0x59, 0xF9, 0x35, 0xFO, 0x5F }; // <â€?â€?â€?â€?â€?â€?â€? PUT YOUR MAC Address Here

                                        ^

exit status 1
unable to find numeric literal operator 'operator"" O'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

I am getting above message please help to proceed

**Comment by igrr** [comment]
You are compiling for Arduino/Genuino Uno. This repository and issue tracker is related to esp8266 boards, not Arduino boards.

The error seems to occur because you have letter O instead of zero in the fifth octet of mac address (FO has to be F0).
