### ISSUE TITLE
message after compiling  

### ISSUE THREAD

**Issue by rbkulkarni811** [esp8266/Arduino#1811]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

sketch_mar23a.ino: In function 'void loop()':
sketch_mar23a:56: error: unknown escape sequence: '\040'

client.println("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://arduino‐autohome.googlecode.com/svn/trunk/autohome.css\ />");

I have came across above it is not error but coming after compiling

**Comment by igrr** [comment]
Do you have client.println in the sketch? Because you posted an empty sketch...
