### ISSUE TITLE
Unable to upload file image using Tools->ESP8266 Sketch Data Upload

### ISSUE THREAD

**Issue by anisimovsergey** [esp8266/Arduino#1813]
#### Hardware
Hardware:		olimex mod-wifi-esp8266
Core Version:      	2.1.0

### Description

I can successfully upload compiled code using Sketch->Upload (Ctrl+U) but whenever I try to upload a bin file for SPIFFS, the esptool.exe (0.4.8) flashing process stops at random moments (but always on flashing the actual data) with the error saying **"read 0, requested 1
warning: espcomm_send_command: didn't receive command response"** 

I investigated the issue a bit and found out that I can actually upload compiled program (not a SPIFFS image) in the same memory area 0x00100000 without a problem (!) and it made me thinking that there must be some difference in the files content. 

I checked the files and found out that the file produced by mkspiffs.exe (0.1.2) contains a lot of sequential 0xFFs (11111111). I forcefully replaced them by 0xAAs (10101010) just for sake of experiment and tried to upload the file. It worked! So I'm assuming that the there is a RS232 timer synchronization problem here. I searched on the Web and it seems like I'm not alone having this problem, so is it possible to solve it somehow? Sorry for my naive question, but does SPIFFS format requires 0xFFs or they can be replaced with 0xAA? Is it possible to make an optional parameter for mkspiffs?

### Settings in IDE

Module:  			olimex mod-wifi-esp8266
Flash Size: 		2M
CPU Frequency:	80Mhz
Flash Mode:		qio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		none

### Sketch

\libraries\ESP8266WebServer\examples\FSBrowser\

### Debug Messages

	espcomm_send_command: sending command payload
	setting serial port timeouts to 15000 ms
	setting serial port timeouts to 1000 ms
	espcomm_send_command: receiving 2 bytes of data
	writing flash
..........................	read 0, requested 1
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_DATA) failed
warning: espcomm_send_command: wrong direction/command: 0x01 0x03, expected 0x01 0x04
closing bootloader
```

**Comment by igrr** [comment]
This issue was moved to igrr/esptool-ck#33
