### ISSUE TITLE
ArduinoOTA mDNS announcements don't work if .begin is called before WiFi is connected

### ISSUE THREAD

**Issue by mangelajo** [esp8266/Arduino#1828]
### Basic Infos

_arduino._tcp service can't be discovered of ArduinoOTA.begin() is called before WiFi is ready, because the igmp subscription does not happen.

ArduinoOTA may need to track WiFi status via the .handle() function to wait for WiFi connectivity.

**Comment by igrr** [comment]
ESP8266mDNS is now aware of WiFi connects/disconnects and will restart itself as required.

**Comment by far5893** [comment]
Good work!
