### ISSUE TITLE
[Wire Library]: Address passed in to Wire.beginTransmission gets doubled 

### ISSUE THREAD

**Issue by yiannis-spyridakis** [esp8266/Arduino#1838]
Hi,
While trying to setup a camera module (OV7670 @ slave address 0x42) via i2c, I noticed with a logic analyzer that the address that is passed in to `Wire.beginTransmission()` gets doubled on the wire.
It looks like this is happening in `twi_writeTo()` in `core_esp8266_si2c.c` (address is left shifted by 1 before being passed to `twi-write_byte()`):
> if(!twi_write_byte(((address << 1) | 0) & 0xFF)) {...

Cheers,
Yiannis

#### Hardware
Hardware:			ESP-12E
Core Version:      	2.1.0

**Comment by igrr** [comment]
Quoting Wikipedia,

> The master is initially in master transmit mode by sending a start bit followed by the 7-bit address of the slave it wishes to communicate with, which is finally followed by a single bit representing whether it wishes to write(0) to or read(1) from the slave.

So the 7 bit address is transferred first (as 7 MSBs), followed by a single bit which indicates read or write operation (as an LSB). So for write operation the byte on the wire is indeed double of the 7-bit slave address.
