### ISSUE TITLE
Connect to Wifi with Access Points

### ISSUE THREAD

**Issue by GrexAut** [esp8266/Arduino#1854]
Hi,

I'm trying to connect to an Wifi Network where 2 APs streaming the network.
I'm using the example "connect to wifi", and it is only printing "Connecting to xxx ........" - If I do 2 WifiScan, I find the Wifi SSIDs (Main AP, and secondary AP).

Is there an option to connect via BSSID (MAC Address)

**Comment by igrr** [comment]
Yes you can specify BSSID as fourth (optional) argument in `WiFi.begin` call.
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h#L38

**Comment by GrexAut** [comment]
Hi, thank you! - Can you give me an example too?


Thx
