### ISSUE TITLE
Components for home automation

### ISSUE THREAD

**Issue by rbkulkarni811** [esp8266/Arduino#1863]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

I want to do Home automation project 

Please confirm below selected components are ok for it or need to buy something else

1. Arduino UNO rev3.

2. Ethernet shield-please tell model number.

Regards,

Rahul

**Comment by igrr** [comment]
Hi Rahul,
This isn't a support forum for home automation project, this is an issue tracker for the ESP8266 Arduino core. I'm sure your question will get answered on [esp8266.com](http://www.esp8266.com/) forum!
Thanks.
