### ISSUE TITLE
Can't flash wroom anymore after using TX and RX as GPIO

### ISSUE THREAD

**Issue by Banzai00** [esp8266/Arduino#1868]
Hi guys, i have a Wroom 02, i wanted to use TX RX as gpio so uploaded a sketch where i set gpio 1 and gpio 3 as output. the code didn't work but that's not my problem.
The problem is that now i can't upload any other program and i get the message espcomm failed.
I tried different codes with an another wroom 02  and it's working fine so there's nothing wrong with my configuration and equipments.

So can i repair the first wroom or there's no solution ??

**Comment by duncan-a** [comment]
I've just been trying to use TX/RX for I2C SCL/SDA on an ESP-01, and I couldn't get it to work either.

However, reverting to GPIO-0/2 threw up no more problems with uploading than I usually experience - i.e. nothing was 'bricked' on the ESP-01...

**Comment by tablatronix** [comment]
erase_flash via esptool

**Comment by Banzai00** [comment]
tablatronix i tried multiple flash tools but i get the same result : failed to connect.

**Comment by tablatronix** [comment]
Are you able to get into flash boot mode manually? Do you get any serial output on reset?

**Comment by Banzai00** [comment]
No, no response i cant' acess flash boot mode

**Comment by philippe-gregoire** [comment]
Any possibility that you'd have inadvertently applied +5V to those pins?

**Comment by Banzai00** [comment]
No i connected them to leds.
i think there's no hope and i'm gonna buy another one.

**Comment by duncan-a** [comment]
What value current- limiting resistors did you use?

We're you sourcing current to the LEDs or sinking it?

Are the LEDs still connected when you are trying to upload new code to the
device?

**Comment by philippe-gregoire** [comment]
Good point. Even output could toast GPIO (aren't they protected against this?)

Would there be a difference sinking (e.g. connecting LED to VCC, and having LED ON on Low GPIO ) or sourcing (e.g. connecting LED to GND and thus having LED ON on High GPIO)?

Thanks.

**Comment by tablatronix** [comment]
They are rated at 20ma, a straight led could fry them i suppose. You didn't accidently conect them to a 5v supply did you ? That could also do it.

Some say you might try external pullups? But I would see about taking some measurements on the pins first.

**Comment by duncan-a** [comment]
External pullups would eliminate the possibility of fried internal
pullups/pulldowns and provide known levels to the pins that need them, and
thus ensure correct bootup.

Obviously, that doesn't apply to TX and Rx - these should be direct to the
'programming lines', without LEDs, or anything else, pulling them in one
direction or the other.

The "20mA" is, I think, the quoted maximum current - much safer to use
less. Other than blue LEDs, which often have a Vf in excess of 3.3V, 330R
or 220R resistors work well in most circumstances.

**Comment by Banzai00** [comment]
I use 1 kohm current- limiting resistors and it's working fine with other pins.
I'm sourcing current to the LED and the leds are no more connected when i am trying to upload the code.
tablatronix, philippe-gregoire : i didn't  applied +5V to those pins. i have a regulated 3.3v voltage supply .
thank you guys for your help and sorry for my bad english.

**Comment by arlaor** [comment]
Do you have disconnected the LEDs RX and TX pins when you try to upload the code ?.
I had the same problem and I did was turn off the LEDs of these ports and then allowed me to program the board
