### ISSUE TITLE
How does ESP8266 support Multi task with Arduino?

### ISSUE THREAD

**Issue by jackshu** [esp8266/Arduino#1874]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by igrr** [comment]
You can use task API described in the ESP8266 non-OS SDK documentation. I don't think there is an Arduino library which wraps this API, but it is quite straightforward, so you should be able to use it as is.
Just remember that calling blocking functions (i.e. WiFiClient.read/write) is not possible from tasks other than the main task (the one where setup/loop run).
