### ISSUE TITLE
New Built Version Please

### ISSUE THREAD

**Issue by rokison** [esp8266/Arduino#188]
The current built version for windows 32bit as linked from the main page is quite old, and lacking several key features such as the ESP library.
Please could a more recent built version be uploaded for those of us without the technical competence to build ourselves!

**Comment by RussMathis** [comment]
Second this request, the last build was in March and there are many changes. Especially Serial2 support.
Thanks!

**Comment by igrr** [comment]
Current trunk has several regressions, my plan was to address them and have a more stable release by the end of next week.

**Comment by RussMathis** [comment]
Also, please an article or doc on how to update our libraries/hardware folders so we can simply update those instead of requiring a complete build? I've read some articles describing how to update the hardware and library folders but these seem out of date?

**Comment by igrr** [comment]
@RussMathis once we implement #13 this will be taken care of by the Arduino board manager.

**Comment by marvinroger** [comment]
Buy you can download the builds from [AppVeyor](https://ci.appveyor.com/project/igrr/Arduino/build/artifacts).

**Comment by RussMathis** [comment]
OK, I'll give the AppVeyor build a try. Thanks.

**Comment by RussMathis** [comment]
I tried the AppVeyor build. But when trying to start the arduino.exe file it comes up with a dialog titled "Launch4j" saying "An error occurred while starting the applicationr" and will not launch.

**Comment by igrr** [comment]
Board manager package released.
