### ISSUE TITLE
Function not declared in this scope

### ISSUE THREAD

**Issue by torntrousers** [esp8266/Arduino#1881]
With Arduino IDE 1.6.8 and the 2.1.0 esp code this sketch fails to compile:
```
#include <ESP8266WiFi.h>
#include <PubSubClient.h>
WiFiClient wifiClient;
PubSubClient client("bla", 1883, callback, wifiClient);
void setup() {
}
void loop() {
}
void callback(char* topic, byte* payload, unsigned int payloadLength) {  
}
```
It gets a compile error saying: 'callback' was not declared in this scope
Is this supposed to be working now after #1472 was fixed?

**Comment by igrr** [comment]
This is an arduino-builder issue, it affects all cores (not only ESP8266): https://github.com/arduino/arduino-builder/issues/85

**Comment by torntrousers** [comment]
Ah I see. Thanks.
