### ISSUE TITLE
Flash bin file to esp

### ISSUE THREAD

**Issue by Lexander24** [esp8266/Arduino#1893]
I want to ask.
Can i flash the bin file to esp after i made the code using arduino?

Thx

**Comment by Rickgg** [comment]
Sure, you can use [EspTool](https://github.com/themadinventor/esptool) to upload it directly. Also support for OTA updates is already in the Arduino IDE.

**Comment by Lexander24** [comment]
Hey rick thx for reply.
Yesterday i try to upload using flash download tool by expressif but i confuse with the configuration. What configuration i must set? Thx

**Comment by igrr** [comment]
You need to upload a single "bin" file, at address 0x00000. Also make sure you set flash size to the same value as the size you selected in Arduino IDE.

**Comment by Lexander24** [comment]
Thx for reply, i will try again today and inform you what happen. Thx

**Comment by hason124** [comment]
I have flashed your firmware and I get the green flash on boot. But I am guessing its configured for your network so I cant access it on the hue app since its not connected to my network. I dont see the New Hue Light ssid.
