### ISSUE TITLE
New staging release? 

### ISSUE THREAD

**Issue by obsoleted** [esp8266/Arduino#1899]
Would it be possible to get a new version with the latest changes published to the staging url? (http://arduino.esp8266.com/staging/package_esp8266com_index.json) I think the current version there is the 2.1.0 rc.

There have been some great fixes that would be easier to get at if available via the board manager method. (Easier to document anyway :wink: )

**Comment by marvinroger** [comment]
Definitely! What about a release schedule? The staging version is often older than the stable version.

**Comment by igrr** [comment]
The release *was* scheduled on April 1. I'm working to get it ready as soon as possible, running tests against pending pull requests for the last few days :)

**Comment by WoodsterDK** [comment]
Hi there,
I think the board manager link for the latest release of the staging version hasn't been updated...

**Comment by marvinroger** [comment]
@WoodsterDK I see 2.2.0-rc1 in the boards manager, so it seems it is.

**Comment by PhilColbert** [comment]
Think thats just the documentation link that hasnt been changed, yes it is confusing ! :)

**Comment by WoodsterDK** [comment]
Looking in the http://arduino.esp8266.com/staging/package_esp8266com_index.json file just shows links to 2.1zips. I think the header is OK, but not the content....

**Comment by igrr** [comment]
Have you scrolled down a bit? 2.2.0-rc1 is the last on in the list of packages, before the list of tools.

**Comment by obsoleted** [comment]
I see 2.2.0-rc1 and was able to use it. Thanks for updating it!

The issue can be closed as far as I'm concerned. Unless others object?

 Perhaps a separate issue is needed for doc updates if any are needed though.

**Comment by WoodsterDK** [comment]
But why does the json file link to https://github.com/esp8266/Arduino/releases/download/2.1.0-rc1/esp8266-2.1.0-rc1.zip",

**Comment by igrr** [comment]
Json file lists all previous versions as well. You can select the version to install from the dropdown in boards manager.

**Comment by WoodsterDK** [comment]
Ahh sorry my mistake.... Didn't look at the end of the file....
