### ISSUE TITLE
Split the esp8266 core out into a core repository that can be downloaded into the Arduino/hardware folder in documents

### ISSUE THREAD

**Issue by ricklon** [esp8266/Arduino#19]
Split the esp8266 core out into a core repository that can be downloaded into the Arduino/hardware folder in documents.

This allows for the development of the core not to be tied directly to the IDE.

I've created a core based on this here:
https://github.com/ricklon/esp8266-core

The only major issue is that the tools folder should be inside esp8266com

**Comment by igrr** [comment]
We're already tracking this issue in #14, closing as duplicate.
