### ISSUE TITLE
Problem sending email from web server

### ISSUE THREAD

**Issue by CosmicBoris** [esp8266/Arduino#1900]
Hello, I am using WiFiClientSecure and SMTP commands to send email  throw Gmail server,
the problem I`m faced with is I can successfully send only one message, chip restarts on second call of send message function.

0x4020b762: ClientContext::read(char_, unsigned int) at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WiFi\src/WiFiClientSecure.cpp line 471
0x4020bbca: ax_port_read at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WiFi\src/WiFiClientSecure.cpp line 497
0x40234f3f: basic_read at /Users/igrokhotkov/e/axtls/e1/ssl/tls1.c line 1224
0x402338b0: increase_bm_data_size at /Users/igrokhotkov/e/axtls/e1/ssl/tls1.c line 1426
0x401006d8: malloc at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266\umm_malloc/umm_malloc.c line 1658
0x4020e3b0: esp_yield at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266/core_esp8266_main.cpp line 43
0x40235325: ssl_read at /Users/igrokhotkov/e/axtls/e1/ssl/tls1.c line 266
0x4020e3b0: esp_yield at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266/core_esp8266_main.cpp line 43
0x4020e46c: optimistic_yield at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266/core_esp8266_main.cpp line 43
0x4020b8b4: SSLContext::_readAll() at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WiFi\src/WiFiClientSecure.cpp line 471
0x402115c2: String::changeBuffer(unsigned int) at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266/WString.cpp line 156
0x4020ba69: SSLContext::available() at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WiFi\src/WiFiClientSecure.cpp line 471
0x4020ba98: WiFiClientSecure::available() at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WiFi\src/WiFiClientSecure.cpp line 471
0x4020767f: AwaitServerResponse(WiFiClientSecure&, String const&) at C:\Program Files (x86)\Arduino/ESP_FileServer.ino line 374
0x4020bd38: WiFiClientSecure::connect(char const_, unsigned short) at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WiFi\src/WiFiClientSecure.cpp line 239
0x402084b9: SendEmail(char const*) at C:\Program Files (x86)\Arduino/ESP_FileServer.ino line 460
0x401008c8: free at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266\umm_malloc/umm_malloc.c line 1727
0x40207205: SendJson(ArduinoJson::JsonObject&) at C:\Program Files (x86)\Arduino/ESP_FileServer.ino line 374
0x402087eb: actionLogin() at C:\Program Files (x86)\Arduino/ESP_FileServer.ino line 222
0x402115c2: String::changeBuffer(unsigned int) at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266/WString.cpp line 156
0x4021161a: String::reserve(unsigned int) at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266/WString.cpp line 146
0x4020c9dc: FunctionRequestHandler::handle(ESP8266WebServer&, HTTPMethod, String) at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WebServer\src\detail/RequestHandlersImpl.h line 53
0x4020f786: std::_Function_handler ::_M_invoke(std::_Any_data const&) at c:\users\boris\appdata\roaming\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2/functional line 2073
0x4020c9d2: std::function ::operator()() const at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WebServer\src\detail/RequestHandlersImpl.h line 53
0x4020ca0e: FunctionRequestHandler::handle(ESP8266WebServer&, HTTPMethod, String) at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WebServer\src\detail/RequestHandlersImpl.h line 53
0x40211770: String::String(String const&) at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266/WString.cpp line 46
0x4020caa1: ESP8266WebServer::_handleRequest() at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WebServer\src\detail/RequestHandlersImpl.h line 53
0x4020b2fc: WiFiClient::~WiFiClient() at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WiFi\src/WiFiClient.cpp line 362
0x4020b286: ClientContext::unref() at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WiFi\src/WiFiClient.cpp line 362
0x4020cd27: ESP8266WebServer::handleClient() at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WebServer\src\detail/RequestHandlersImpl.h line 53
0x40207112: SerialCommand() at C:\Program Files (x86)\Arduino/ESP_FileServer.ino line 374
0x4020e7ba: HardwareSerial::available() at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266/HardwareSerial.cpp line 186
0x402076df: loop at C:\Program Files (x86)\Arduino/ESP_FileServer.ino line 374
0x4020e3fc: loop_wrapper at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266/core_esp8266_main.cpp line 43
0x40100958: cont_norm at C:\Users\boris\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\cores\esp8266/cont.S line 109
#### Hardware

Hardware:           ESP-07
Core Version:       ?2.1.0-rc2?
### Settings in IDE

Module:             Generic ESP8266 Module
Flash Size:         1MB
CPU Frequency:  80Mhz
Flash Mode:     DIO
Flash Frequency:    40Mhz
Upload Using:       SERIAL
Reset Method:       ck
### Sketch

```
bool AwaitServerResponse(WiFiClientSecure &client, const String &resp = "")
{
    while ( !client.available() ){}
    String line = client.readStringUntil('\n');
    Serial.println(line);
    if( resp ){
        if (line.indexOf(resp) == -1) return false;
    } 
    return true;
}

bool SendEmail(const char *message)
{
    WiFiClientSecure client;
    S.print("Connecting to :");
    S.println(Config::SMTP_SERVER);
    if (!client.connect(Config::SMTP_SERVER, Config::SMTP_PORT)) {
        Serial.println("Could not connect to mail server");
        return false;
     }
     AwaitServerResponse(client);
     client.println("HELO friend");
     AwaitServerResponse(client);
     client.println("AUTH LOGIN");
     AwaitServerResponse(client);
     client.println(Config::EMAILBASE64_LOGIN);
     AwaitServerResponse(client);
     client.println(Config::EMAILBASE64_PASSWORD);
     if(!AwaitServerResponse(client, "235")){
         S.println("SMTP error");
         return false;
     }
     client.println("MAIL FROM: <myEmail@gmail.com>");
     AwaitServerResponse(client);
     client.println("RCPT TO: <myAnotherEmail@live.com>");
     AwaitServerResponse(client);
     client.println("DATA");
     if( !AwaitServerResponse(client, "354") ){
          S.println("SMTP error");
          return false;
    }
    client.println("From: My self <myEmail@gmail.com>");
    client.println("To: Me <myEmail@gmail.com><myEmail@live.com>");
    client.println("Subject: Home");
    client.println("Mime-Version: 1.0");
    client.println("Content-Type: text/html; charset=\"UTF-8\"");
    client.println("Content-Transfer-Encoding: 7bit");
    client.println();
    String body = "<!DOCTYPE html><html lang=\"en\"><h3>";
    body += message;
    body += "</h3><p></p><a href=\"http://myIP\">GoHome</a></html>";
    client.println(body);
    client.println(".");
    if( !AwaitServerResponse(client, "250") ){
         S.println("SMTP error");
         return false;
    }
    client.println("QUIT");
    if( !AwaitServerResponse(client, "221") ){
        S.println("SMTP error");
        return false;
    }
    client.stop();
}
```

I will be grateful for any help.
##

**Comment by devyte** [comment]
Closing per #3655 .
