### ISSUE TITLE
HTTP POST Issue 2.2rc1

### ISSUE THREAD

**Issue by PhilColbert** [esp8266/Arduino#1910]
Not sure if this is how its supposed to be or not but it seems if the webserver is called with a POST request, then if theres no arguments it doesnt call anything, as soon as an input type is added, it calls the function....

Seemingly if bypasses the  

server.on ( "/page", HTTP_POST, function_to_call );

and 

server.on ( "/page", HTTP_ANY, function_to_call );

also doesnt call

server.onNotFound([]() {}

**Comment by igrr** [comment]
Fixed in f6516b0.
