### ISSUE TITLE
Raspberry Pi version

### ISSUE THREAD

**Issue by hulkco** [esp8266/Arduino#1928]
### Description
Hi iam a Teacher in mexico,  after many tries the Arduino IDE (1.6.9) was compiling sucesful, im Raspberry,  but went a trie to install the ESP8266 Arduino tool, i have a error.

1.- In Stable version: Tool esptool is not available for your operating system
2.- In Staging version: Tool mkspiffs is not vailable for your operating system
Thanks for your atention.
Best Regarts

### Screen Capture

![002](https://cloud.githubusercontent.com/assets/16407513/14587960/21370eb0-047a-11e6-8b1c-07cf778db170.png)
![001](https://cloud.githubusercontent.com/assets/16407513/14587962/27b47b10-047a-11e6-9fd4-24caf82c4012.png)

**Comment by igrr** [comment]
I have added ARM tools last week, they are not yet part of stable/staging versions. You can try using git version of the core (see instructions on the front page).

**Comment by hulkco** [comment]
Thanks Igor, i check rigth now.
:)

**Comment by hulkco** [comment]
Thanks Ivan Works like a charm!!!!
![screenshot at 2016-04-17 10 29 56](https://cloud.githubusercontent.com/assets/16407513/14588476/e4a56506-0487-11e6-81e1-dcd616287da1.png)
![20160417_102747](https://cloud.githubusercontent.com/assets/16407513/14588480/ee538ae2-0487-11e6-94b4-50cca3163878.jpg)
