### ISSUE TITLE
Q: ESP8266/axTLS X509 sign and sign verification

### ISSUE THREAD

**Issue by capablegh** [esp8266/Arduino#1936]
Is there capability to sign a small string or integer value (say 128 bits) using X509 cert/private key? Also, is there a capability to verify a signature given the CA cert/public key of signer is available? If yes, is there an example code for this, or some description?
##

**Comment by capablegh** [comment]
Perhaps I can use RSA_encrypt(...., int is_signing) for signing and RSA_decrypt(..., int is_decryption) for verifying the signature. Both are in 'crypto/rsa.c'. A reference Openssl lcode that seems to be with similar API may be [https://wiki.openssl.org/index.php/EVP_Signing_and_Verifying](url).

**Comment by devyte** [comment]
Closing per #3655 .
