### ISSUE TITLE
Mqtt with WifiClientSecure

### ISSUE THREAD

**Issue by korg1000** [esp8266/Arduino#1947]
Hi, with the new update stable 2.2.0, the subscribe topic dont work, whats means, not arrive the data. The publish action work fine.
I use the pubsubclient library.
With the old 2.1.0, or with the 2.2.0 without ssl, works fine.
But not with ssl (wificlientsecure).

Thanks

**Comment by whyameye** [comment]
I have just updated from 2.1.0-rc1 to 2.2.0 stable and can confirm subscribe is not working with SSL. In addition, the certification verification fails and the 8266 keeps disconnecting and reconnecting to the broker. Both of these things were not issues with 2.1.0-rc1 using SSL.

**Comment by korg1000** [comment]
There is any estimated release date to 2.3.0?
