### ISSUE TITLE
Arduino IDE does not load the manager

### ISSUE THREAD

**Issue by zeroprime790** [esp8266/Arduino#1951]
Hello, 

I'm using this board manager the last few months and today a board manager of the arduino IDE upgraded and the esp8266 board manager disappeared. I checked the link in preferences and everything is on place. I tried also to uninstall and reinstall the IDE without any luck.

Currently i'm running in Arduino IDE 1.6.8 and the Arduino AVR Boards upgraded to v1.6.10

**Comment by Dom1n1c** [comment]
I can confirm that issue, the IDE is trying to contact arduino.esp8266.com but it fails.

**Comment by mcauser** [comment]
I am unable to reach `http://arduino.esp8266.com/stable/package_esp8266com_index.json` from several computers and networks.

Networking issue?

`$ host arduino.esp8266.com`
`arduino.esp8266.com has address 104.131.82.128`

**Comment by mcauser** [comment]
http://www.downforeveryoneorjustme.com/http://arduino.esp8266.com/stable/package_esp8266com_index.json

> It's not just you! http://arduino.esp8266.com looks down from here.

**Comment by rasendubi** [comment]
Confirm network issue. http://arduino.esp2866.com is down for me.

**Comment by mcauser** [comment]
The .json file is linked in the footer here: https://github.com/esp8266/Arduino/releases/tag/2.2.0
Unfortunately, urls inside also refer to arduino.esp8266.com

**Comment by monkeyBone** [comment]
Still confirmed. Are there any alternates?

**Comment by cfrodca** [comment]
http://arduino.esp8266.com is up!

**Comment by zeroprime790** [comment]
yes, I can confirm that. But since the manager was installed how it is related with the URL and became unavailable?
