### ISSUE TITLE
Direct Stream ArduinoJson to client with ESP266WebServer

### ISSUE THREAD

**Issue by hallard** [esp8266/Arduino#1952]
Hi there

I recently moved to ArduinoJson library to do my json stuff. This lib is just awesome. But I have an optimization question, this lib can stream the json data to Serial with for example

``` arduino
root.prettyPrintTo(Serial);
```

but I would like to direct stream this to client browser, today I'm copying json buffer to string like this but it's too much overhead (twice buffer size) plus copy time

``` arduino
  String myString;
  root.prettyPrintTo(myString);
  server.send ( 200, "text/json", myString );
```

any way to do something that could be like this 

``` arduino
  server.send ( 200, "text/json");
  root.prettyPrintTo(server.client);
```

thanks for any advice
##

**Comment by hallard** [comment]
I think something similar to this can do the trick, but once again we need to declare a buffer.
https://github.com/bblanchon/ArduinoJson/issues/166

**Comment by me-no-dev** [comment]
there is this: https://github.com/me-no-dev/ESPAsyncWebServer#arduinojson-basic-response

**Comment by hallard** [comment]
@me-no-dev 
thanks for this, I did not switched to async TCP yet, is it considered as "stable" ?

**Comment by kaeferfreund** [comment]
works very well for me. Have 5 devices running 24/7, with no prob.
It's so incredibly fast... Loving it 💃

**Comment by me-no-dev** [comment]
it is really stable at this point :) maybe it's time to change the readme for the TCP lib :D

**Comment by hallard** [comment]
Guys, are you testing me, you want me to spend my whole remaining day to integrate async ?!?
No, no, you got other things to do, no, no don't do that ;-)
ok see that tomorrow or this night, good deal ;-)

**Comment by kaeferfreund** [comment]
Its totally worth it, seriously! :D

Have fun ;)

**Comment by me-no-dev** [comment]
Should not be that much work :) it's mostly the same. The rest is explained in the README (make sure you read it through)

**Comment by hallard** [comment]
Guess what, I'm also using WebSocket, I will try all of this ASAP, need to take some time on the README, but looks nice ;-)

**Comment by me-no-dev** [comment]
try the included example first :) it has the spiffs editor and websocket example onboard (with the html and all)

**Comment by devyte** [comment]
The buffered response is the way to go. If that is not enough, then a streaming json lib is needed.
Closing per #3655 .
