### ISSUE TITLE
arduino 1.6.8 not work with esp8266

### ISSUE THREAD

**Issue by dkumariet** [esp8266/Arduino#1953]
today auto removed esp8266 board from my arduino...........
then i try the  steps according this link 
https://github.com/esp8266/Arduino
but i occur some error 
"git clone https://github.com/esp8266/Arduino.git esp8266"
this cmd not work, this msg show on terminal
fatal: unable to access 'https://github.com/esp8266/Arduino.git/': Failed to connect to github.com port 443: Network is unreachable
and,arduino show msg

WARNING: Error loading hardware folder /opt/arduino-1.6.8/hardware/esp8266com
  No valid hardware definitions found in folder esp8266com.
please help me

**Comment by igrr** [comment]
"unable to access 'https://github.com/esp8266/Arduino.git/': Failed to connect to github.com port 443: Network is unreachable"

Looks like a network issue if you can't connect to Github.
