### ISSUE TITLE
QR generator library

### ISSUE THREAD

**Issue by chrisfraser** [esp8266/Arduino#1960]
Hi there guys,

I am trying to use the QR Generator discussed here: https://forums.adafruit.com/viewtopic.php?f=25&t=33715

Namely: https://github.com/tz1/qrduino

I keep getting wdt resets. Please can someone give advice on how to port this over.

Thanks
##

**Comment by WereCatf** [comment]
Find any for- and while-loops and try adding calls to yield() - there, that'll most likely fix it.

**Comment by devyte** [comment]
Not the right place to ask for help for your particular project. Closing per #3655 .
