### ISSUE TITLE
addServiceTxt String  return void not bool

### ISSUE THREAD

**Issue by miky2k** [esp8266/Arduino#1962]
void addServiceTxt(String name, String proto, String key, String value){
    addServiceTxt(name.c_str(), proto.c_str(), key.c_str(), value.c_str());
  }

should be 

bool  addServiceTxt(String name, String proto, String key, String value){
    return addServiceTxt(name.c_str(), proto.c_str(), key.c_str(), value.c_str());
}

I'm trying to access txt of queried services can you give me an example ?

i found only 
  String hostname(int idx);
  IPAddress IP(int idx);
  uint16_t port(int idx);
to access queried services.
##

**Comment by igrr** [comment]
I don't think mDNS library currently supports TXT queries. Looking at the code, only PTR queries are implemented.

**Comment by devyte** [comment]
The referenced functions still have the wrong return type in latest git.

**Comment by devyte** [comment]
This is already fixed.
