### ISSUE TITLE
Where does the pre-processor look for these included files?

### ISSUE THREAD

**Issue by electronicsguy** [esp8266/Arduino#1966]
ESP8266WiFi/src/WiFiClient.h contains these lines:

#include "Arduino.h"
#include "Print.h"
#include "Client.h"
#include "IPAddress.h"

Since you're using double-quotes for the include, instead of angle brackets, the pre-processor would look in the src/ directory first. Since these are not files are not present there, it'll look in the default include path. Isn't this correct?

So if these files are not here, why use quoted include instead of angled include? Could someone explain?

Secondly, if someone will be kind enough to explain: I am confused about which file it eventually picks. For example the file "IPAddress.h" is present on "esp8266/hardware" as well as "Arduino/hardware...". What exactly determines which file is used? 
Thank you.

**Comment by WereCatf** [comment]
> Secondly, if someone will be kind enough to explain: I am confused about which file it eventually picks. For example the file "IPAddress.h" is present on "esp8266/hardware" as well as "Arduino/hardware...". What exactly determines which file is used? 

The board you've chosen determines which file-path they are searched for. When you select your board as the esp8266 it looks under hardware/esp8266, and when you select something else it looks in hardware/something_else.
