### ISSUE TITLE
EEPROM can only read one string at once?

### ISSUE THREAD

**Issue by dandandandandandandan** [esp8266/Arduino#1967]
IDE 1.6.8
ESP8266 Arduino 2.2.0
nodeMCU 0.9

I don't get any compilation errors or warnings.

If i read more than 1 string from the EEPROM the ESP only displays the latest one. It's like it somehow empties the first string.

```
Serial.println("Printing out SSID and password");
     //read saved wifi SSID
     while (addr1 < 133)
    {
      savedSsid[addr3] = EEPROM.read(addr1);
      addr3 = addr3 + 1;
      addr1 = addr1 + 1;
    }
    //read saved wifi PASS
    while (addr2 < 183)
    {
      savedPass[addr4] = EEPROM.read(addr2);
      addr4 = addr4 + 1;
      addr2 = addr2 + 1;
     }
  Serial.println(savedSsid);
  Serial.println(savedPass);
```

In this case only the "savedPass" would show up in the serial window.
If i put a Serial.print after each while loops then both of the strings show up in the serial window (so that kinda confirms that i can read them and saved them properly in the EEPROM, i confirmed the latter with an EEPROM dump) but when it comes to the last two lines the first string "savedSsid" fails to display again.
If i put an EEPROM.end() and EEPROM.begin(512) between the two while()s then the strings show up with all kinds of errors.

When i comment out either one of the while loops the uncommented one shows up good.

This is how the code would show up in the serial monitor:

```
Printing out SSID and password

weakwifipass1234
```

**Comment by dandandandandandandan** [comment]
This is more interesting:

I put a Serial.print after each while into the code:

```
Serial.println("Printing out SSID and password");
     //read saved wifi SSID
     while (addr1 < 133)
    {
      savedSsid[addr3] = EEPROM.read(addr1);
      addr3 = addr3 + 1;
      addr1 = addr1 + 1;
    }
    Serial.println(savedSsid);
    //read saved wifi PASS
    while (addr2 < 183)
    {
      savedPass[addr4] = EEPROM.read(addr2);
      addr4 = addr4 + 1;
      addr2 = addr2 + 1;
     }
  Serial.println(savedPass);
  Serial.println(savedSsid);
  Serial.println(savedPass);
```

Then this is what it would display in the serial monitor:

```
Printing out SSID and password
myssid
weakwifipass1234

weakwifipass1234
```

**Comment by WereCatf** [comment]
It looks like you may have a buffer-overrun. How do you define savedPass and savedSsid?

**Comment by dandandandandandandan** [comment]
As
```
char savedSsid[32];
char savedPass[32];
```
after the includes.

**Comment by WereCatf** [comment]
Well, then your addr4 is incorrect.

**Comment by WereCatf** [comment]
`savedPass[addr4] = EEPROM.read(addr2);`
Is the only line that actually changes anything after the first while-loop, so I would like you to double-check that your addr4 is actually correct.

**Comment by dandandandandandandan** [comment]
Inspired by your comment i started to mess with the sizes of the char arrays and setting both of them to [33] seemingly solved the problem.

**Comment by WereCatf** [comment]
Aye, very classic buffer-overrun -- you were reading one byte too many in your while-loop. Well, good thing that it's solved then!

**Comment by dandandandandandandan** [comment]
Thanks!
