### ISSUE TITLE
enable sprintf to support printing floats, let the user choose.

### ISSUE THREAD

**Issue by aguaviva** [esp8266/Arduino#1974]
Given that an ESP is as powerful as a Pentium Pro, does it make sense to remove the floating point support just to save some mem? 

At a minimum we should let the user choose whether to support %f feature or not.

**Comment by TheAustrian** [comment]
I concatenate with String(floatVariable, numberOfDecimals) to print floats - I don't know if that helps in your application, though. I would not mind having %f, though.

**Comment by aguaviva** [comment]
thanks and I'd also appreciate a proper fix, there a lots of confused people out there.

Even basic could print floating point numbers :) lets fix this please :)

**Comment by igrr** [comment]
Closing as duplicate of #1179.

**Comment by aguaviva** [comment]
Is anybody working in this? If anybody submits a pull request with the c implementation used in gcc, would it be accepted?

**Comment by igrr** [comment]
This can be implemented as part of a pending pull request: #1752.
Please follow up in the issue linked above: #1179.

**Comment by aguaviva** [comment]
Thanks, this helps! BTW you guys rock!
