### ISSUE TITLE
Latest ESP8266httpUpdate client does not work.

### ISSUE THREAD

**Issue by sk1tt1sh** [esp8266/Arduino#1991]
Hello,

I have verified by making 2.1.0 sketch and uploading to the ESP, and putting a slightly modified 2.1.0 sketch and putting in a folder with the name that the sketch is looking for. When I call the update it works and I see the new serial output.

However I update arduino boards package for esp to 2.2.0 and repeat the same process and the sketch attempts to update but then resets the board and runs the original sketch.

Oddly it prints this at 115200 instead of 74880 when it resets into the previous version sketch:

---------
 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x0f
csum 0x0f
~ld

---------

I also ran ESP8266/CheckFlashConfig sketch: 

---------
Flash real id:   001640E0
Flash real size: 4194304

Flash ide  size: 4194304
Flash ide speed: 40000000
Flash ide mode:  DIO
Flash Chip configuration ok.

---------

**I tested that it is problem in ESP8266httpUpdate.cpp by keeping version 2.1.0 of arduino esp package installed and then pulling the ESP8266httpUpdate.cpp/h from here and overwriting the existing. (Had to remove F("") on the set user agent line 173**

Debug from HTTP Update:

---------
[performUpdateCheck] Checking for update at:	http://10.1.10.76/Sensor.TEST-0.01.026.bin
[httpUpdate] Header read fin.
[httpUpdate] Server header:
[httpUpdate]  - code: 200
[httpUpdate]  - len: 297296
[httpUpdate] ESP8266 info:
[httpUpdate]  - free Space: 749568
[httpUpdate]  - current Sketch Size: 298760
[httpUpdate] runUpdate spiffs...
[httpUpdate] Update ok
����O�0}=��1ӡ����O�0}�z2�1�!:���
^Here it tries to reboot but just goes dead...
WDT Output From reboot:

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld

---------

Thank you.

**Comment by sk1tt1sh** [comment]
Is there a change to how to use this library?

**Comment by igrr** [comment]
You need to reset the board after uploading sketch over serial, otherwise it will get stuck while doing software reset later on.

**Comment by sk1tt1sh** [comment]
When doing httpUpdate from 2.1.0 based app to 2.2.0 app with httpUpdate even resetting power for the board does not allow it to complete update. However 2.1.0 can use httpupdate to 2.1.0 version over and over without power reset at all. 

Also, thank you so much for all your work on this project I sincerely hope my tone does not appear ungrateful as I appreciate everything in this project!

**Comment by sk1tt1sh** [comment]
https://github.com/esp8266/Arduino/pull/2251 

Issue is caused by a call to reboot being made when updateSPIFFS is called.
