### ISSUE TITLE
Q: Minimum delay/yield time

### ISSUE THREAD

**Issue by chaz003** [esp8266/Arduino#2021]
I'm just curious, what is the minimum amount of delay that should be used on a continuous basis? I ask because I tend to try to write non-blocking code. At the moment I have a delay(2) in my loop for ESP code but I'm curious about how just having yield()/delay(0) instead would affect the wifi system? Assuming my code is pretty efficient, would it be ok to just call yield() only and never actually delay any real amount of time?

 
Ex.
```cpp

void loop() {
  //non-blocking code
  yield();
}

**Comment by igrr** [comment]
There is no minimum delay requirement. Doing `yield` (or `delay(0)`, which is equivalent) once in a while is sufficient. Also note that there is an implicit `yield` which happens at the end of each loop.
