### ISSUE TITLE
Callback for WiFi event is not std::function + WiFi.removeEvent has bug 

### ISSUE THREAD

**Issue by sticilface** [esp8266/Arduino#2026]
@igrr as, discussed. 

https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h#L38
is not an std::function.

These features are not documented. 

https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.cpp#L87

Needs to be refactored, as there is no == operator for std::function, and as you mentioned better to have RAII implementation.  (I did try, and you've mentioned there is an error).

**Comment by igrr** [comment]
Created #2119 which address this issue.
