### ISSUE TITLE
'using' in FS.h

### ISSUE THREAD

**Issue by BuzzBurrowes** [esp8266/Arduino#2030]
Awesome that the classes in FS.h are in a namespace. Nice. But...

The 'usings' at the bottom of the file are no good...

```
using fs::FS;
using fs::File;
using fs::Dir;
using fs::SeekMode;
using fs::SeekSet;
using fs::SeekCur;
using fs::SeekEnd;
using fs::FSInfo;
```
I get the idea... by doing this, you can easily take code that was using the Sd Library and substitute SPIFFS. 

BUT... if you need to use both, which I do, then I need to comment out those usings... which leads to a code maintenance issues with library updates.

I would propose something like the following...

```
#ifndef _NO_FS_USINGS
using fs::FS;
using fs::File;
using fs::Dir;
using fs::SeekMode;
using fs::SeekSet;
using fs::SeekCur;
using fs::SeekEnd;
using fs::FSInfo;
#endif
```
Then current functionality is maintained, and I can just modify my project's build settings to get what I need. Well, at least I am going to try that on my branch.

- Buzz

**Comment by igrr** [comment]
Added `FS_NO_GLOBALS`.
