### ISSUE TITLE
Putty and other serial terminals(arduino ser terminal) does not recognize nodemcu

### ISSUE THREAD

**Issue by lucifer43** [esp8266/Arduino#2031]
Hardware:			nodemcu
Core Version:      	0.9.6
### Description

Problem description
i have connected the nodemcu to arduino and the examples(like blink) works fine and i could upload the sketch without any problem, but the serial monitor does not respond to the AT commands
and other terminals like putty, realterm etc. doesn't respond to the commands.
what can the problem be?

### Settings in IDE

Module:  			Nodemcu
Flash Size: 		?4MB
CPU Frequency:		80Mhz
Flash Mode:			?qio?
Flash Frequency:	40Mhz
Upload Using:		OTA / SERIAL
Reset Method:		nodemcu

**Comment by WereCatf** [comment]
If you've uploaded a sketch on your Nodemcu-kit then you've replaced the AT-firmware. Of course it won't respond to AT-commands anymore.
