### ISSUE TITLE
connection closed on client

### ISSUE THREAD

**Issue by lucifer43** [esp8266/Arduino#2032]
#### Hardware
Hardware:			ESP-12
Core Version:      	0.9.6
### Description

Problem description
the serial monitor shows the following message when i tried connecting to the server.
Server Started.

New client: 0
GET http://connectivitycheck.android.com/generate_204 HTTP/1.1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1; TegraNote-P1640 Build/LMY47D)
Host: connectivitycheck.android.com
Connection: Keep-Alive
Accept-Encoding: gzip

Connection closed on client: 0

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

#include <ESP8266WiFi.h>
//#include <WebSocketClient/WebSocketClient.h>
#include <WiFiClient.h>

/* Set these to your desired credentials. */
const char *AP_ssid = "AP_chas";
const char *AP_passkey = "12345678";

int status = WL_IDLE_STATUS;
boolean alreadyConnected[2] ; // whether or not the client was connected previously

WiFiServer server(6000);
WiFiClient client[2];

#define Config_Led D2

void setup()
{
    delay(1000);
    Serial.begin(115200);
    Serial.println();
    Serial.println("\nConfiguring access point...");
    WiFi.mode(WIFI_AP);
    WiFi.softAP(AP_ssid, AP_passkey);
    delay(10000);
    IPAddress myIP = WiFi.softAPIP();
    WiFi.mode(WIFI_AP);
    Serial.print("AP IP address: ");
    Serial.println(myIP);

    Serial.println("\nStarting server...");
    // start the server:
    server.begin(); 
    Serial.println("\nServer Started.");
}

void loop()
{
    unsigned int i;
    for (i= 0; i<2; i++)
    {
        // wait for a new client:
        if (!client[i])
        {
            client[i] = server.available();
        }
        else
        {
            if (client[i].status() == CLOSED)
            {
                client[i].stop();
                Serial.print("\nConnection closed on client: "  );
                Serial.println(i);
                Serial.println();
                alreadyConnected[i] = false;
            }

            else
            {
                if(!alreadyConnected[i]) // when the client sends the first byte, say hello:
                {
                    // clean out the input buffer:
                    client[i].flush();
                    Serial.print("\nNew client: ");
                    client[i].println("Hello, client !");
                    Serial.println(i);
                    alreadyConnected[i] = true;
                }

                if (client[i].available())
                {
                    // read the bytes incoming from the client:
                    String data = client[i].readString();
                    // echo the bytes back to the client:
                    client[i].print(data);
                    // echo the bytes to the server as well:
                    Serial.println(data);
                }               
            }
        }
    }
}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by igrr** [comment]
Well the client sends you an HTTP GET request, to which you respond with "Hello, client !". Seeing an invalid HTTP response client closes the connection.
If your intent is to send HTTP response to the client, please take a look at the ESP8266WebServer library, it has some examples to get you started.
