### ISSUE TITLE
Espressif SDK 1.5.3 released

### ISSUE THREAD

**Issue by marvinroger** [esp8266/Arduino#2033]
http://bbs.espressif.com/viewtopic.php?f=46&t=2041

Just pinging you.

**Comment by igrr** [comment]
https://github.com/esp8266/Arduino/commit/f266f8a2ff0f7a48c4de28b2e83346a0958c0c34

Already in staging release!

**Comment by marvinroger** [comment]
Oh, we're in may, not april, I thought it was released today. :confused: 
My bad!
