### ISSUE TITLE
Add official esp8266com repository to new Arduino 1.6.4

### ISSUE THREAD

**Issue by Testato** [esp8266/Arduino#204]
Arduino IDE 1.6.4 have a new function, is it possible add a board whit a simple json URL link.
Adafruit already use this way for add his repository whit, i think, a copy of esp8266.com work

It is good if directly you create an official esp8266.com json URL link for the Arduino IDE.

Here how it work:
https://learn.adafruit.com/add-boards-arduino-v164

**Comment by marvinroger** [comment]
Duplicate of #13, this is already in the plans.

**Comment by igrr** [comment]
closing as duplicate
