### ISSUE TITLE
Is sniffing packet (monitor mode) in ESP8266 possible with arduino core 

### ISSUE THREAD

**Issue by pratiklodha95** [esp8266/Arduino#2056]
We want to analyse the packets without assigning any IP address to the client.

**Comment by igrr** [comment]
It is, although there is no Arduino-specific API for that. You can use ESP IoT SDK functions if you add `user_interface.h` to your sketch:

```c++
extern "C" {
  #include <user_interface.h>
}
```

and then call `wifi_set_promiscuous_rx_cb`, `wifi_promiscuous_enable`, `wifi_set_channel`, etc, as described in SDK documentation.
