### ISSUE TITLE
How to connect to an open wifi that has a login  web page?

### ISSUE THREAD

**Issue by seinecle** [esp8266/Arduino#2059]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			ESP82266MODCore Version:      	2.2

### Description
The wifi I'd like to connect to is from a school, where you can connect without a password, but then you need to enter a login and password in the first web page you see (hotel wifi often works the same way). I could not find a tutorial on how to do in this case, do you have useful pointers for me? Thanks!

**Comment by gmag11** [comment]
I guess you need to send password data. Most probably you will have to deal with Session ID from captive server.
