### ISSUE TITLE
ESP8266HTTPClient non blocking

### ISSUE THREAD

**Issue by ramarro123** [esp8266/Arduino#2064]
Hello,

i can't find anything of related to this topic, maybe someone can give me an advice :)

i would like to know if it's possible to make non blocking request with httpClient library.

something like

```
bool new_req = true;
HTTPClient http;

void setup() {

}

void loop() {
  if (WiFiMulti.run() == WL_CONNECTED) {
    if (http.requestComplete()) {
    String result = http. getString();
    //do stuff with results
    new_req = true;
   }   
 
   if (do_new_req) {
    http.begin("iamslow.php");
    http.GET_NONBLOCKING();
    new_req = false;
   }
}

  //do other things, that aren't doesn't wait for iamslow.php



}
```

**Comment by igrr** [comment]
It isn't possible with ESP8266HTTPClient, but you can use https://github.com/me-no-dev/ESPAsyncTCP to implement a non-blocking HTTP request.
