### ISSUE TITLE
Update ESP8266 library on Arduino IDE

### ISSUE THREAD

**Issue by odilonafonso** [esp8266/Arduino#2076]
Please, how can I update the esp8266 librarys on Ubuntu.

I did it (in January) :

<"git clone https://github.com/esp8266/Arduino.git esp8266">

Now I want update, but git does not clone over an existing directory.

**Comment by WereCatf** [comment]
`git pull`

**Comment by WereCatf** [comment]
Oh, and don't forget to run the get.py in the tools-directory to get the latest tools.

**Comment by odilonafonso** [comment]
Hi @WereCatf .. thanks for help.

I tried git pull. But....

```
git pull https://github.com/esp8266/Arduino.git esp8266
fatal: Not a git repository (or any of the parent directories): .git
```

For now, i did :
```
mv esp8266 esp8266old
git clone https://github.com/esp8266/Arduino.git esp8266

```

I know, is not the best solution !!!

**Comment by WereCatf** [comment]
I said, inside the esp8266-directory. You tried to run `git pull` outside the directory, that's why you got an error. It's a lot easier and faster than doing a full clone every time.
