### ISSUE TITLE
Factory reset ESP8266

### ISSUE THREAD

**Issue by romuye123** [esp8266/Arduino#2091]
#### Hardware
Hardware:			ESP-12
Core Version:      	2.1.0-rc2

### Description

Is there any way to factory reset your ESP8266? Want to achieve following:

1) Delete all data from EEPROM
2) Delete SSID() and psk() so that it should not connect to WIFI automatically.

3) Do not delete sketch from ESP memory.

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB/1MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz
Upload Using:		 SERIAL
Reset Method:		ck

**Comment by krzychb** [comment]
@romuye123,

Please check [this post](http://www.esp8266.com/viewtopic.php?f=32&t=8204) that I believe addresses all your questions.

Krzysztof
