### ISSUE TITLE
Serial.begin(,,SERIAL_TX_ONLY) doesn't works

### ISSUE THREAD

**Issue by stephjj** [esp8266/Arduino#2098]
Hello,

If I use Serial.begin(,,SERIAL_TX_ONLY) to use GPIO3 as a LED output on ESP-01, I got no output on TX.
But GPIO3 is usable with digitalWrite.

In uart.c (line 174), the tx_pin is set to 255 if rx_enable is false.
If I set it to 1, every thing is working fine.

Thanks.

**Comment by looxonline** [comment]
I was actually about to post about this myself. Thanks for your hard work Igrr!

**Comment by igrr** [comment]
I have attempted to fix this in #2141.
