### ISSUE TITLE
Review/remove usages of Access-Control-Allow-Origin in libraries and examples

### ISSUE THREAD

**Issue by igrr** [esp8266/Arduino#2102]
There are a bunch of [instances](https://github.com/esp8266/Arduino/search?utf8=%E2%9C%93&q=Access-Control-Allow-Origin) of `Access-Control-Allow-Origin` header in libraries and examples. The ones which are in libraries are hidden from sight and are potential security issues.

Need to review the uses of this header and document, remove, or make them optional as appropriate.
- [ ] [ESP8266WebServer library](https://github.com/esp8266/Arduino/blob/7450dd39ca93ca849f9198b0151e4c7c747e43ef/libraries/ESP8266WebServer/src/ESP8266WebServer.cpp#L262)
- [ ] [ESP8266SSDP library](https://github.com/esp8266/Arduino/blob/966329575563b21ba96e77ef141d3f0b41a6d96c/libraries/ESP8266SSDP/ESP8266SSDP.cpp#L81)
- [ ] [ESP8266HTTPUpdateServer library](https://github.com/esp8266/Arduino/blob/633e48f3aec5f1c3c11d4498fc90d378d49e6e9f/libraries/ESP8266HTTPUpdateServer/src/ESP8266HTTPUpdateServer.cpp#L29-L36)
- [ ] [WebUpdate example](https://github.com/esp8266/Arduino/blob/633e48f3aec5f1c3c11d4498fc90d378d49e6e9f/libraries/ESP8266WebServer/examples/WebUpdate/WebUpdate.ino#L27-L32)
##

**Comment by me-no-dev** [comment]
Appart from the SSDP lib, for which I am not positive, the rest can go for sure. I believe some of those were added in testing of some scenarios back then, when we were trying to get all connections closed at the end of the response. The rest are probably copy/paste

**Comment by yoursunny** [comment]
As of commit 2f4380777ef3f1a32a7d539371d910820d0c6f6a, the only occurrence of "Access-Control-Allow-Origin" is in SSDP library. Thus, this issue should be closed.

**Comment by devyte** [comment]
Ok, closing per previous comment.
