### ISSUE TITLE
Arduino Uno POST HTTP request using library for http

### ISSUE THREAD

**Issue by thorburn1** [esp8266/Arduino#2106]
I want to POST (http request) any string / json data to a server using arduino UNO and wifi esp8266.
I need to use a httpclient library to handle most part.
please guide
I am a newbie to this world.
ANY EXAMPLE WOULD HELP.

**Comment by igrr** [comment]
This question is not exactly on topic in this issue tracker.
This project is about programming an ESP8266 as a stand-alone processor, without an external Arduino involved. Please check out [Arduino section of esp8266 community forum](http://www.esp8266.com/viewforum.php?f=8), someone there may be able to help you.
