### ISSUE TITLE
POST request for adruino UNO using esp8266   error timed out

### ISSUE THREAD

**Issue by thorburn1** [esp8266/Arduino#2113]
//can someone explain me what is the mistake i am doing in POST request?
// my library link //https://github.com/bportaluri/WiFiEsp

//code is below 

#include "WiFiEsp.h"

#ifndef HAVE_HWSERIAL1
#include "SoftwareSerial.h"
SoftwareSerial Serial1(3, 4);
#endif

char ssid[] = "iot";            // your network SSID (name)
char pass[] = "iot09078";        // your network password
int status = WL_IDLE_STATUS;     // the Wifi radio's status

char server[] = "api-engine.shephertz.com";

WiFiEspClient client;

void setup()
{
  // initialize serial for debugging
  Serial.begin(115200);
  // initialize serial for ESP module
  Serial1.begin(9600);
  // initialize ESP module
  WiFi.init(&Serial1);

  // check for the presence of the shield
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("WiFi shield not present");
    // don't continue
    while (true);
  }

  // attempt to connect to WiFi network
  while ( status != WL_CONNECTED) {
    Serial.print("Attempting to connect to WPA SSID: ");
    Serial.println(ssid);
    // Connect to WPA/WPA2 network
    status = WiFi.begin(ssid, pass);
  }

  // you're connected now, so print out the data
  Serial.println("You're connected to the network");
  printWifiStatus();

  

  Serial.println();
   client.stop();  
  Serial.println("Starting connection to server...");
   
  

String PostData = "title=foo&body=bar&userId=1";
  // if you get a connection, report back via serial
  if (client.connect(server, 80)) {
    Serial.println("Connected to server");
    // Make a HTTP request
   client.println("POST /1.0/iot_api?apiKey=a7ef2e069dd6a04a08ee1c3a23364db9c8b624bc738335dfaf7539d4e7d3e14d HTTP/1.1\r\n");
  client.println("Host: api-engine.shephertz.com");
  client.println("Cache-Control: no-cache");
  client.println("User-Agent: Arduino/1.0");
  client.println("Connection: close");
  client.print("Content-Length: ");
  client.println(PostData.length());
  client.println();
  client.println(PostData);
  
}
  }

void loop()
{
  // if there are incoming bytes available
  // from the server, read them and print them
  while (client.available()) {
    char c = client.read();
    Serial.write(c);
  }

  // if the server's disconnected, stop the client
  if (!client.connected()) {
    Serial.println();
    Serial.println("Disconnecting from server...");
    client.stop();

    // do nothing forevermore
    while (true);
  }
}

void printWifiStatus()
{
  // print the SSID of the network you're attached to
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print your WiFi shield's IP address
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  // print the received signal strength
  long rssi = WiFi.RSSI();
  Serial.print("Signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
}

**Comment by igrr** [comment]
Dear @thorburn1, you have already opened the issue in the relevant issue tracker: https://github.com/bportaluri/WiFiEsp/issues/50. Please do not cross-post issues and do not abuse this issue tracker by asking questions about unrelated projects. Thank you.
