### ISSUE TITLE
Changing Wifi Server Port at runtime 

### ISSUE THREAD

**Issue by thedroid** [esp8266/Arduino#2128]
Is there anyway to change the port that Wifi Server is listening on at run time.

i.e. Initially start the server on a default port, but give the user the ability to change from the default to a port of their choosing at run time?
##

**Comment by devyte** [comment]
It looks to me like assigning a new temp object like below causes a mem leak:
```
ESP8266WebServer server(80);
...
server = ESP8266WebServer(12345);
```

Also, close() doesn't free internal resources.

**Comment by devyte** [comment]
This is already implemented. Usage:
```
WiFiServer server(80);
server.begin();
...

server.begin(8080); //closes, then opens again on the new port.
```

Please test latest git.

**Comment by devyte** [comment]
Pulled into 2.4.1'as it's already implemented, and closing.
