### ISSUE TITLE
Baud rate in the serial monitor

### ISSUE THREAD

**Issue by tejaswigowda** [esp8266/Arduino#2130]
Really simple issue. 

I am getting gibberish in the serial monitor. Maybe something to do with the baud rate. Any suggestions?

**Comment by krzychb** [comment]
Hi @tejaswigowda,

Yes, it may be because of selecting different baud rate in  sketch and in the serial monitor.
Check the sketch you have loaded to your module for a line like:

``` 
Serial.begin(115200);
````
Then select the same baud rate in serial monitor as in the sketch.
