### ISSUE TITLE
WebServer should match headers using equalsIgnoreCase

### ISSUE THREAD

**Issue by enzosagretti** [esp8266/Arduino#2131]
I found an issue in "Parsing.cpp". (line 164)
`else if (headerName == "Content-Length"){
        contentLength = headerValue.toInt();`

The compare between **"headerName"** and  **"Content-Length"** must **not be** case sensitive. For this problem i can´t read HTTP_POST payload. I change this in my enviroment and work fine!!
`else if (headerName == "content-length"){
        contentLength = headerValue.toInt();`

**Could you change all HTTP header compare to not be case sensitive?**
##

**Comment by me-no-dev** [comment]
Should be fixed in the above commit
