### ISSUE TITLE
Add a hook to run code from user_init

### ISSUE THREAD

**Issue by igrr** [esp8266/Arduino#2133]
As seen [in #2111](https://github.com/esp8266/Arduino/issues/2111#issuecomment-224251391), would be useful to disable WiFi early, and maybe for some other cases as well.
##

**Comment by devyte** [comment]
@igrr I suggest pushing this one back to 2.5.0 (unless it's trivial to implement?)

**Comment by igrr** [comment]
Sure. At this point i am not planning on adding more features to 2.4.0, only bug fixes are considered. I guess we can mass-reassign all feature requests from 2.4.0 to 2.5.0.

**Comment by d-a-v** [comment]
Closed by #5395
