### ISSUE TITLE
Error: Could not find or load main class processing.app.Base Building from source Linux Ubuntu

### ISSUE THREAD

**Issue by ValerioCietto** [esp8266/Arduino#214]
I built from source using git clone and ant dist.
When I launch the program from terminal I get: 
Error: Could not find or load main class processing.app.Base

**Comment by auspex-nl** [comment]
Assuming you run linux, after you run ant dist, there should be a archive containing the build arduino ide (arduino-1.6.1-linux64.tar.xz) in the build/linux folder

Extract that somewhere and run the IDE from there

**Comment by ValerioCietto** [comment]
Ok it works. I extracted the package before, but the extraction was currupted somehow. I downloaded it again and done again the procedure, and it worked.

**Comment by igrr** [comment]
@ValerioCietto can we close this issue?

**Comment by ValerioCietto** [comment]
Yes, you can close the issue.

**Comment by ValerioCietto** [comment]
Yes, you can close the issue.
