### ISSUE TITLE
ESP EEPROM for dynamic data

### ISSUE THREAD

**Issue by vishalkothari** [esp8266/Arduino#2144]
Hello,
I am designing a feature where ESP-12E is required to retain 2 variables after power cycle. The variables are refreshed every 1 second in loop. I can overwrite variables from earlier loop cycle in new loop cycle. 

Is ESP-12E EEPROM suitable for storing this type of dynamic data?

I looked at https://github.com/esp8266/Arduino/issues/414, its seems EEPROM has limited erase/write cycles (100.000). 
If EEPROM is not suitable, does ESP have any other option for storing dynamic data?

Thanks.

Regards,
Vishal Kothari

**Comment by WereCatf** [comment]
There is the RTC-memory which does retain its contents even if the ESP is restarted or goes to deep-sleep, but it does not survive full power-loss. If you need the variables to survive full power-loss then no, there is no other option than using an external device or facing the eventual death of the internal flash.
