### ISSUE TITLE
ESP07 Timeout problem on CMD

### ISSUE THREAD

**Issue by heroseller17** [esp8266/Arduino#2148]
Hi
i have a problem with esp-07 
in my home every thing is good and i have no problem with esp
but in office i have a problem! and i always send 5bit packet but the time is app about~200ms -400ms and many times timeout!
the same board and the same circuit i just change the ssid and password and ip...thats it
but i have this problem ....
why its happend?
##

**Comment by heroseller17** [comment]
is it possible on range of wifi ?

**Comment by devyte** [comment]
@heroseller17 The amount of wifi traffic dictates how much work must be done servicing the wifi stack. Most likely there is much higher traffic at work, which means you're allowed less CPU time for your app.
Most likely your app needs to be redesigned and broken down into pieces that have shorter execution time.
Not the right place to discuss. Closing per #3655 .
