### ISSUE TITLE
Connect ESP to Windows 7 native Access point?

### ISSUE THREAD

**Issue by nouser2013** [esp8266/Arduino#2149]
Dear all, I'm trying to connect several ESP12F's to a windows 7 machine. I used the VirtualRouter software to turn the laptop into an access point and while my cellphone connects without trouble, the ESPs do not. Unfortunately, neither the VirtualRouter application nor the commandline version offer much configuration options. Just SSID and password.

However, when I use the hotspot function of my cellphone, the ESPs connect to that flawlessly, as well as to the OpenWRT based router by TP-Link serving as access point .

Has anybody ever created an access point on with a windows 7 machine that ESPs cann connect to?
##

**Comment by devyte** [comment]
Closing per #3655 .
