### ISSUE TITLE
timer interrupt

### ISSUE THREAD

**Issue by yakirmalka** [esp8266/Arduino#215]
is ther any way to start timer interrupt?
in lua its "tmr.alarm(1, 200, 1,function()"

**Comment by gerardwr** [comment]
Ticker!

**Comment by gerardwr** [comment]
Ticker!?

**Comment by yakirmalka** [comment]
10x alot.

**Comment by madsci1016** [comment]
Anything with uS precision? Looks like ticker is only mS.

**Comment by igrr** [comment]
Yes we have two timers, please see Servo library for an example:
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/Servo/src/esp8266/ServoTimers.h

No other documentation right now, unfortunately.

**Comment by mralexgray** [comment]
@igrr link is broken..  really need clarification on how to use timers with this platform.  is it possible to just use `Timer1`, `Timer2`, etc?

**Comment by GeorgeHahn** [comment]
@mralexgray https://github.com/esp8266/Arduino/blob/master/libraries/Servo/src/esp8266/ServoTimers.h
