### ISSUE TITLE
Incorrect ADC readings while WiFi enabled

### ISSUE THREAD

**Issue by Gorkde** [esp8266/Arduino#2159]
#### Hardware
Hardware:			ESP-12F and Wemos D1

### Description

When WiFi is transmitting the ADC is reading incorrectly after some time.
ADC grounded reads 0 in the beginning, later it jumps up to 7 on the other module to 50 even.

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB/1MB
CPU Frequency:		80Mhz
Upload Using:		 SERIAL

### Sketch

#include <ESP8266WiFi.h>  // ESP8266WiFi.h

char WLANname[] = "***";
char WLANpw[] = "***";

void setup()
{
  Serial.begin(115200);

  WiFi.begin(WLANname, WLANpw);
  Serial.println(" ");
  
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("\nCONNECTED");
  
  // WiFi.disconnect();

}

void loop()
{
  Serial.println(analogRead(0));
  delay(100);
}

*** FOR SOME REASON INSERT CODE DOESNT WORK CORRECTLY ***

**Comment by supersjimmie** [comment]
Looks like https://github.com/esp8266/Arduino/issues/2070
