### ISSUE TITLE
Support for hardware PWM?

### ISSUE THREAD

**Issue by Janjanus** [esp8266/Arduino#216]
Hello,

Is there support for hardware PWM on the ESP8266? Since the README.md tell there is only software PWM available but this is not suitable for my application. 

The ESP8266 is capable of hardware PWM right?

**Comment by igrr** [comment]
If it does have hardware PWM, it is not documented anywhere. So for now software PWM is the only option.

**Comment by cherowley** [comment]
Hi iggr,

Just wondering how accurate will your software PWM be? 
Also, will it support 4 pwm at the same time - thinking rgbw led strips you see :)

Cheers!

**Comment by Toshik** [comment]
I'd suppose to use special module for PWM based on PCA9685 chip.
It is nice and driven by I2C

http://www.ebay.com/itm/311188037855

**Comment by pRoFlT** [comment]
Does software PWM work? when i try analogWrite(pin#,255) i don't get anything on that pin? I've tried several DIO and several levels from 0-255 with nothing. I'm using the nodeMCU V0.9 ESP8266 board. I've also tried on the Huzzah ESP8266 from adafruit. Same results. Am i missing something?
 
code is:
in setup
pinMode(4,OUTPUT);

in loop
analogWrite(4,127);

**Comment by mralexgray** [comment]
Why was this closed, with no resolution?

**Comment by 9H1LO** [comment]
up to 3 ch soft pwm is fine, also trying to do rgbw and get a flicker (when there is network activity) when introducing 4th channel i have tried pca9685 with i2c and it works great but overkill to use a 16ch chip just for 1 rgbw

**Comment by seidler2547** [comment]
Sorry to ressurect this old topic. I don't  know if it is a recent change, but the [datasheet](https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf) clearly states (chapter 4.7) that the ESP8266 *has* 4 hardware PWMs. Any chance to implement support for that?

**Comment by devyte** [comment]
@seidler2547 why do you think it has hw pwm? Section 4.7 clearly says that pwm is done by timer interrupt.
