### ISSUE TITLE
I2C hang with very slow I2C slave (pic12f1840@500khz)

### ISSUE THREAD

**Issue by miky2k** [esp8266/Arduino#2162]
----------------------------- Remove above -----------------------------
#### Hardware

Hardware:           ESP-07
Core Version:       2.2.0
### Description

On very slow device i2c hang SDA low and give strange results  01111001 instead 00111100 .
### Settings in IDE

Module:             Generic ESP8266 Module
Flash Size:         512K/64K
CPU Frequency:  80Mhz
Flash Mode:     qio
Flash Frequency:    40Mhz?
Upload Using:       SERIAL?
Reset Method:       ck
### Sketch

Wire.begin(12,13); //I2C pin
Wire.setClockStretchLimit(2000);

In my software(l is not important) : 
    Wire.beginTransmission(Addr);
    Wire.write(0b00111100);
    Serial.println("I2C write---"+String(l));
    Serial.println(Wire.endTransmission(1));

Serial Output:

I2C write---4
3

![i2c](https://cloud.githubusercontent.com/assets/6616232/16148978/b0b028f4-348d-11e6-80ab-75bbe38f1bd6.jpg)
##

**Comment by me-no-dev** [comment]
any particular reason why your slave does not release SDA?

**Comment by far5893** [comment]
I disconnect physically only sda from device but bus remain low .

**Comment by devyte** [comment]
@igrr this has milestone 2.4.0. However, I don't fully understand the issue, let alone what needs to be fixed in Wire.
Is the issue still relevant?

**Comment by far5893** [comment]
If you have different clock stretch need on devices  is relevant!

**Comment by enjoyneering** [comment]
check this - https://github.com/enjoyneering/ESP8266-I2C-Driver

**Comment by d-a-v** [comment]
For reference ([link](https://github.com/esp8266/Arduino/issues/2330#issuecomment-391303255))
I will make a PR for that

**Comment by devyte** [comment]
CC @Tech-TX
