### ISSUE TITLE
i have a nodemcu ESP8266 device is not detacting firmware in ESplorer

### ISSUE THREAD

**Issue by Shockwave7747** [esp8266/Arduino#2163]
i have a nodemcu ESP8266 device with 4 Mb memory.
it is not detecting its firmware in ESplorer software
here the device sometimes even did not showing its port, but when i flash it with blank or some other firmware's it starts detecting the port, but it shows ESplorer that the module is not supported, or firmware is not detected, please help me out. any little help will be appreciated. thanks.
#### Hardware

Hardware:       ESP8266
Core Version:       ?2.1.0-rc2?
### Description

i have a nodemcu ESP8266 device with 4 Mb memory.
it is not detecting its firmware in ESplorer software
here the device sometimes even did not showing its port, but when i flash it with blank or some other firmware's it starts detecting the port, but it shows ESplorer that the module is not supported, or firmware is not detected, please help me out. any little help will be appreciated. thanks.
### Settings in IDE

Module:             ?Generic ESP8266 Module?
Flash Size:         ?4MB?
CPU Frequency:      ?80Mhz?
Flash Mode:         ?qio?
Flash Frequency:    ?40Mhz?
Upload Using:       ?SERIAL?
Reset Method:       ? nodemcu?
### Sketch

``` cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```
### Debug Messages

```
messages here
```

**Comment by devyte** [comment]
As far as I know, Esplorer is not meant to autodetect this firmware. It is meant for the Lua and Python firmwares.
Arduino IDE has its own Serial Monitor.
Closing.
