### ISSUE TITLE
esp8266 test board question

### ISSUE THREAD

**Issue by jjssoftware** [esp8266/Arduino#2165]
A question for Ivan (igrr) about this comment: https://github.com/esp8266/Arduino/issues/2070#issuecomment-222891420. You referenced a test board and included a link to an image in that comment (http://gd1.alicdn.com/bao/uploaded/i1/TB1fX1KHFXXXXXWXFXXXXXXXXXX_!!2-item_pic.png_600x600.jpg). This looks like a phenomenal test board and I'm wondering what it is and where it's built - can you give me some details please?. The ESP board in the image also looks like one I've not see before - can you tell me what type of ESP board that is?
Many thanks,
Joe

**Comment by igrr** [comment]
The board is called "ESP-LAUNCHER", schematics and layout files are available from https://espressif.com/en/support/download/documents, inside "ESP8266 Hardware Resources" archive. If you search by its name, it shows up in a number of online stores.
