### ISSUE TITLE
ESP8266 Master to many Slaves broadcast

### ISSUE THREAD

**Issue by iVisionary** [esp8266/Arduino#2171]
Dears,

I've got fed up of searching over the internet on this - now I want a straight forward solution or guidance please.

My project simply is to have one ESP8266 connected to a host Microcontroller to be like a hub or master to establish a local private network no need to connect to the internet. On the other hand, I have many ESP8266 devices connected to the same network and receiving data from the master ESP8266 or the Microcontroller. These ESP slave devices will receive the message from the master and turn on/off a relay on one of the gpio pins and return a status feedback to the master. That's it!
Please guide me to the correct direction. I'm so confused right now and don't know what should I focus on! Thanks in advance!

**Comment by igrr** [comment]
Dear @iVisionary, this issue tracker is not a good place for "how do I..." kind of questions. Its main purpose is to keep track of issues and feature requests related to esp8266 Arduino core and libraries. Please use esp8266.com community forum for coding help. Thank you.
