### ISSUE TITLE
digitalWrite and digitalRead should cancel analogWrite enabled on a pin

### ISSUE THREAD

**Issue by igrr** [esp8266/Arduino#2175]
https://www.arduino.cc/en/Reference/AnalogWrite

**Comment by rgwood1234567890** [comment]
I'm not sure if this is related or not but if I:

setPinMode(D0, OUTPUT); // red led
setPinMode(D4, OUTPUT); // blue led

digitalWrite(D0, ...) //works fine
digitalWrite(D4, ...) //works fine

analogWrite(D0, anyVal); // led full on
// afterwards digWr on D0 stops working.
// analogWrite on D4 always turns it full on no matter what value but digWrite still works

I've only tried this on the D0, D4 leds as they are physically on this NodeMCU board.

Hardware: NodeMCU v1 esp-12e.
Arduino esp8266 v2.3
eclipse ide plugin, latest
windows 7, 64bit
