### ISSUE TITLE
client.print no send  when this statement is inside a conditional "if () {

### ISSUE THREAD

**Issue by Ciriaco08** [esp8266/Arduino#2179]
#### Hardware

Hardware:       ESP-12
Core Version:       2.1.0
### Description

Problem description
client.print no send to client when this instruccion is inside a conditional "if () {
### Settings in IDE

Module:             Generic ESP8266 Module
Flash Size:         1MB
CPU Frequency:  80Mhz
Flash Mode:     dio
Flash Frequency:    40Mhz?
Upload Using:       SERIAL
Reset Method:       ck 

[Controlando_ESP8286_desde_HTML_V4.tar.gz](https://github.com/esp8266/Arduino/files/328300/Controlando_ESP8286_desde_HTML_V4.tar.gz)

**Comment by igrr** [comment]
I checked your code and I'm confused. Do you get serial output from the following statement?
```c++
Serial.println("PIN en string: "+ dato_1);
```
If you see this printed, then `client.print` is also executed.

I would also suggest to use ESP8266WebServer library instead of writing your own HTTP parsing code. Library also parses request arguments for you.

**Comment by Ciriaco08** [comment]
Serial.println("PIN en string: "+ dato_1);

This line is just a check, all Serial.println instruccions  are for check 

This is the send:

 String s = "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<!DOCTYPE HTML>\r\n<html>\r\nGPIO esta ahora ";
       s += (dato_2_N)?"apagado":"encencido";
       s += "</html>\n";

       // Enviando respuesta a la página
       client.print(s);

**Comment by igrr** [comment]
This line looks okay as well. Just make sure you set Content-Type to `text/plain` if you aren't sending HTML, like in this case.

**Comment by Ciriaco08** [comment]
The problem is the "if" statement. 
If we remove that instruction  the code run normally and  client.print(s), send "s" variable

**Comment by igrr** [comment]
Could you please add `Serial.println(s);` line after `client.print(s);` line and post serial output please?

**Comment by Ciriaco08** [comment]
Serial output:

..
WiFi connected
Server started
192.168.1.44
new client
new client
new client
new client
new client
new client
new client

HTTP/1.1 200 OK
Content-Type: text/html

<!DOCTYPE HTML>
<html>
GPIO esta ahora apagado</html>

new client

**Comment by Ciriaco08** [comment]
with debug on:

Conectando a Neptuno marciana
.wifi evt: 0
wifi evt: 3
.
WiFi connected
Server started
192.168.1.44
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
WS:ac
:rn 298
:ref 1
WS:av
:ref 2
:ur 2
new client
:ur 1
:close
WS:dis
:del
WS:ac
:rn 298
:ref 1
WS:av
:ref 2
:ur 2
new client
:ur 1
:close
WS:dis
:del
WS:ac
:rn 298
:ref 1
WS:av
:ref 2
:ur 2
new client
:ur 1
:close
WS:dis
:del
WS:ac
:rn 298
:ref 1
WS:av
:ref 2
:ur 2
new client
:ur 1
:close
WS:dis
:del
WS:ac
:ref 1
WS:av
:ref 2
:ur 2
new client
:rn 298
:ur 1
:close
WS:dis
:del
WS:ac
:ref 1
WS:av
:ref 2
:ur 2
new client
:rn 298
:ur 1
:close
WS:dis
:del
WS:ac
:rn 264
:ref 1
WS:av
:ref 2
:ur 2
new client
:wr
:sent 100
:ww
HTTP/1.1 200 OK
Content-Type: text/html

<!DOCTYPE HTML>
<html>
GPIO esta ahora apagado</html>

:rcl
:abort
:ur 1
WS:dis
:del
WS:ac
:ref 1
WS:av
:ref 2
:ur 2
new client
wifi evt: 7
:rn 264
:wr
WS:ac
:rn 298
:sent 102
:ww
HTTP/1.1 200 OK
Content-Type: text/html

<!DOCTYPE HTML>
<html>
GPIO esta ahora encencido</html>

:ur 1
:close
WS:dis
:del
:ref 1
WS:av
:ref 2
:ur 2
new client

**Comment by Ciriaco08** [comment]
Hi , Is there any documentation for use ESP8266WebServer library?
regards

**Comment by devyte** [comment]
@Ciriaco08 no docs at this time, but there are many examples, and the object interface is pretty clear.
This looks like user error to me. Closing per #3655 .
