### ISSUE TITLE
UDP sendto is still broken

### ISSUE THREAD

**Issue by jwatte** [esp8266/Arduino#218]
The solution for udp beginPacket() makes the network stack filter out any packets that arrive from other sources while a packet is "begun."
It also does unnecessary amounts of work within the connect() and disconnect() functions.
Better is to remember the IP and port from the beginPacket() function, and use send(addr, port).
I will attempt to provide a patch, if I can get the raw clone to build/run.

**Comment by igrr** [comment]
That's already done, will push the updated version next week along with
other network related fixes.

**Comment by jwatte** [comment]
If by "that's already done" you mean the current HEAD on github, it has the bug that I already create. Using connect() temporarily in beginPacket() is not correct.

**Comment by igrr** [comment]
Done in my local working copy, I just haven't pushed the changes to github
yet. Thanks for the pull though.

**Comment by igrr** [comment]
fixed in ae2bc12
