### ISSUE TITLE
stable package.json for 2.3.0: wrong checksum for linux32-xtensa-lx106-elf.tar.gz

### ISSUE THREAD

**Issue by dotbr** [esp8266/Arduino#2185]
Hello!

There's a wrong checksum on the file linux32-xtensa-lx106-elf.tar.gz for the version 2.3.0 on linux32. On linux64 it works OK.

Cheers, and thank you guys for this amazing work!

**Comment by igrr** [comment]
Bummer, I was supposed to fix ARM toolchain signature in 7d56ea4 and instead changed linux32 one.
Thanks for pointing this out, fixing this now.

**Comment by dotbr** [comment]
Thanks Igrr!

**Comment by igrr** [comment]
Should be fixed now, json files on arduino.esp8266.com have been updated as well.
