### ISSUE TITLE
Serial port input causes reset on current HEAD

### ISSUE THREAD

**Issue by jwatte** [esp8266/Arduino#219]
I have a sketch that works fine on 1.6.1 release, but sending a byte into the serial port on current HEAD resets the module.
It also seems like the new built sketches are bigger, and they start at a different location in flash (0x10000 instead of 0x40000.) Perhaps this has something to do with it?

**Comment by igrr** [comment]
duplicate of #189

**Comment by igrr** [comment]
Actually that was a duplicate of #172. Should be fixed now.
