### ISSUE TITLE
WIFI reset

### ISSUE THREAD

**Issue by bastos1505** [esp8266/Arduino#2191]
Hi guys, I'm using ESP12 and I'm facing a problem with wifi connection. I connected my ESP in my router and everything was ok up to my Set-Top-Box (that as well is connected in same router) be turned ON.
  All the pins are OK and the VCC is very fine. I can't have a LOG because the ESP just resets.

   The reset msg is: rst #1 (normal boot). There is no glitches in VCC. I measured with a scope and didn't see anything.

Facts:
   - When I disconnect the ESP from my router, the problem doesn't happens;
   - The problem just happens when my Set-Top-Box is booting;
   - Even with a big data traffic, there's no problem;
   - I can't have a LOG, because the ESP just resets;
   - I'm using nodemcu 1.5.1 integer (Master) WIFI, UART, FILE, GPIO, HTTP, NODE, NET, TIMER.

**Comment by igrr** [comment]
You are using Nodemcu firmware? So you probably meant to open an issue at https://github.com/nodemcu/nodemcu-firmware/issues?
