### ISSUE TITLE
Update Sketch From SPIFFS

### ISSUE THREAD

**Issue by kumarmohan7** [esp8266/Arduino#2205]
Hi,

Please Give Ideas...

I Want Update Sketch from SPIFFS, i will store bin file in SPIFFS more then 3 bin files, i will select a file and update to ESP8266....

Please give example programs....

&

How to use ESP8266_AVRISP using ....

please give procedure to use ESP8266_AVRISP

Thanks & Regards

S.Mohankumar

**Comment by andig** [comment]
Unclear what you're asking. Updating sketch from spiffs should be possible similar to updating via OTA. Look at the OTA code for how to do this.

**Comment by devyte** [comment]
@kumarmohan7 there is an Updater class.
Closing per #3655 .
