### ISSUE TITLE
ESP8266WebServer::collectHeaders can not be used from libraries

### ISSUE THREAD

**Issue by igrr** [esp8266/Arduino#2225]
`collectHeaders` methods expects the headers list to be supplied in a single call. This effectively prevents other libraries from using `collectHeaders`. I.e. ESP8266HTTPUpdateServer should be able to request Content-Length header independently from other headers which may be requested from the sketch.

Add `collectHeader` method to collect just one header. Replace C array (`_currentHeaders`) with `std::map<String, String>` and `insert` into the map. Make `collectHeaders` call `collectHeader` for each array item.

**Comment by me-no-dev** [comment]
how about we use [this](https://github.com/me-no-dev/ESPAsyncWebServer/blob/master/src/StringArray.h)

**Comment by me-no-dev** [comment]
Ivan, please check this PR and tell me what you think
