### ISSUE TITLE
ESP8266HTTPUpdateServer fails to check sketch size versus available space

### ISSUE THREAD

**Issue by igrr** [esp8266/Arduino#2226]
Currently it is possible to upload a sketch which is larger than the space available in flash, i.e. upload 280k sketch into a module with 512k64 flash configuration.

**Comment by me-no-dev** [comment]
how? I checked the code and it calls Update.begin with max available space for OTA
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPUpdateServer/src/ESP8266HTTPUpdateServer.cpp#L64

**Comment by me-no-dev** [comment]
to maybe better explain, if the uploaded file is larger than the available space, Update should stop writing and flag an error. If that is not the behaviour you are seeing let me know. Maybe the problem is in the Updater class
