### ISSUE TITLE
time.h

### ISSUE THREAD

**Issue by yomasa** [esp8266/Arduino#2243]
how do I get the hour()  using time.h

void printTime() {
   time_t t = time(nullptr);
   Serial.println(ctime(&t));
   Serial.println((long)&t);
   Serial.println((hour(&t));   give error

  
  }

**Comment by igrr** [comment]
Use [mktime](http://www.cplusplus.com/reference/ctime/mktime/) function to fill in [struct tm](http://www.cplusplus.com/reference/ctime/tm/) and then check its `tm_hour` field.
