### ISSUE TITLE
Problem:  getVCC reading lower values since the last update...

### ISSUE THREAD

**Issue by egzola** [esp8266/Arduino#2245]
I've been testing in many ESP-12F, and I can guarantee that since the last software update (from 2.2.0-rc1 to 2.3.0-rc1) , getVcc function has returned 0.3V  lower than the previous software version.

**Comment by igrr** [comment]
There was an SDK update between these two versions. Apparently adc read routine from the SDK got "fixed".

**Comment by wyasuda** [comment]
Hi,
I have the same problem with 2.3.0.
When I measured Vcc with a voltmeter, it was 3.3V.
However the value I got from getVcc function was 3.02V.
It was lower than real value.
Would you please tell me why this might happen?

**Comment by Humancell** [comment]
Has anything been done on this?  I too am seeing ~0.2-0.3v low reading on all of my ESP-12F.

**Comment by devyte** [comment]
There is nothing much that can be done within this repo. The issue seems to be in the SDK side.
I suggest implementing a linear calibration via software, which is something that should be done anyways in these cases.
Closing.
