### ISSUE TITLE
Question: analogWrite() as PWM for ShiftRegister

### ISSUE THREAD

**Issue by Gorkde** [esp8266/Arduino#2249]
I'm using a shift register library (http://shiftregister.simsso.de/) to expand my ESP ports.

Since I need to fade some outputs on the shift register I just wrote my own PWM function that's probably not the best.....

Therefore is there a way to make analogWrite not output directly to a pin but call a function of the shift register library?

Thanks!

**Comment by Gorkde** [comment]
Anyone?

Btw... i don't know how to mark something as Question maybe someone can tell me how to as well.

**Comment by igrr** [comment]
`analogWrite` function is a weak function, so you can override it from your sketch or from a library:
```
extern "C" void analogWrite(int, int) {
  // custom stuff
}
```

**Comment by Gorkde** [comment]
@igrr 
I did already write my own but my routine would block the program so I thought to use the analogwrite since it doesn't block as far as I know.

**Comment by Gorkde** [comment]
Btw. am  I somehow able to mark a question as such or are just Admins allowed to?

**Comment by igrr** [comment]
analogWrite blocks for a bit because it needs to calculate periods, sort them, etc.

Only contributors can label issues afaik.

**Comment by Gorkde** [comment]
A bit would be no problem but my routine would block all the time while it's running since it doesn't use timers/interrupt. 

Is there a simple way to make analogwrite call a function instead setting a pin directly?

**Comment by Gorkde** [comment]
Thanks!
