### ISSUE TITLE
Calling Serial.begin() more than once causes wdt.  

### ISSUE THREAD

**Issue by sticilface** [esp8266/Arduino#2305]
### Basic Infos

Since introduction of f8a8a2a3595751c39ec8604ab21fdfbd7daccad6 changing serial speed by calling Serial.Begin again causes a wdt reset.  reproducible using the same serial speed. see below. 
#### Hardware

Hardware:   ESP-12
Core Version:       git head
### Description

see above 
### Settings in IDE

Module:     Generic ESP8266 Module?
Flash Size:         4MB
CPU Frequency:      160Mhz?
Flash Mode:         qio?
Flash Frequency:            80Mhz?
Upload Using:       Both 
Reset Method:       nodemcu
### Sketch

``` cpp
bool triggered = false; 
void setup() {
  Serial.begin(115200);
  Serial.println("BEGIN 115200"); 
}

// the loop routine runs over and over again forever:
void loop() {
  Serial.printf("Working...\n");
  delay(500);        

  if (!triggered && millis() > 5000) {
    triggered = true;
    Serial.println("Changing Serial Speed");
    Serial.flush(); 
    Serial.begin(115200);  
  }
}
```

**Comment by me-no-dev** [comment]
fixed: https://github.com/esp8266/Arduino/pull/2307
funny how I had the fix commented? I wander why
