### ISSUE TITLE
WDT & Software RESET in ESP8266 + Arduino IDE

### ISSUE THREAD

**Issue by anujmattoo** [esp8266/Arduino#2311]
#### Hardware
Hardware:			ESP-12F
Core Version:      	        2.1.0-rc2

### Description

I am working on ESP8266 in Arduino IDE. I want to know how to Software RESET the ESP8266. Any sketch/example would be useful. Moreover, how to initialise WDT in ESP8266.

Kindly help! @igrr @me-no-dev 

### Settings in IDE

Module:  		    NodeMCU(ESP-12F)
Flash Size: 	 	   4MB/1MB
CPU Frequency:       80Mhz
Flash Mode:		  qio
Flash Frequency:	 40Mhz
Upload Using:         OTA / SERIAL
Reset Method:        ck / nodemcu

**Comment by arcao** [comment]
For software reset `ESP.restart()` should works. See docs about [ESP specific functions](http://esp8266.github.io/Arduino/versions/2.1.0-rc2/doc/libraries.html#esp-specific-apis).

Note: Core version 2.1.0-rc2 is pretty old, the latest one is 2.3.0.
