### ISSUE TITLE
ESP WiFi ethernet shield bridge 

### ISSUE THREAD

**Issue by folny** [esp8266/Arduino#2313]
Hello friends

Please could anyone advise me how I could create a sketch that would work as a bridge between WiFi and ethernet shield sketch should work as a data wireless connect instead of a long cable RJ45 thanks.

**Comment by igrr** [comment]
Hi @folny, this issue tracker is not a good place for "how do I..." kind of questions. Its main purpose is to keep track of issues and feature requests related to esp8266 Arduino core and libraries. Please use esp8266.com community forum for coding help. Thank you.
