### ISSUE TITLE
Undefined reference to qsort and bsearch

### ISSUE THREAD

**Issue by arcao** [esp8266/Arduino#2314]
### Hardware

Hardware: ESP-12E
Core Version: 2.3.0
### Issue Description

For one of my project I need `bsearch` function for binary search in an array, which should be included in `stdlib` library. Unfortunately compilation for `NodeMCU 1.0 (ESP-12E Module)` returns undefined reference error. Bellow is example sketch including `qsort` which should be part of `stdlib` too, but it isn't. The same sketch is successfully compiled with Arduino UNO board configuration.
### Settings in IDE

Module: NodeMCU 1.0
Flash Size: 4MB/1MB
CPU Frequency: 80Mhz
Upload Using: SERIAL
Reset Method: nodemcu
### Sketch

``` c++
#include <Arduino.h>
#include <stdio.h>      /* printf */
#include <stdlib.h>     /* qsort, bsearch, NULL */

int values[] = { 50, 20, 60, 40, 10, 30 };

int compareints (const void * a, const void * b)
{
  return ( *(int*)a - *(int*)b );
}

void setup() {
}

void loop() {
  int * pItem;
  int key = 40;
  qsort (values, 6, sizeof (int), compareints);
  pItem = (int*) bsearch (&key, values, 6, sizeof (int), compareints);
  if (pItem!=NULL)
    printf ("%d is in the array.\n",*pItem);
  else
    printf ("%d is not in the array.\n",key);
}
```
### Console output

``` text
sketch_jul22a.ino.cpp.o:(.text.loop+0x10): undefined reference to `qsort'
sketch_jul22a.ino.cpp.o:(.text.loop+0x14): undefined reference to `bsearch'
sketch_jul22a.ino.cpp.o: In function `loop':
sketch_jul22a.ino:18: undefined reference to `qsort'
sketch_jul22a.ino:19: undefined reference to `bsearch'

collect2.exe: error: ld returned 1 exit status

exit status 1
Nastala chyba při kompilaci u desky NodeMCU 1.0 (ESP-12E Module).
```

**Comment by igrr** [comment]
This indeed fails with 2.3.0, but compiles fine with the latest git version.
