### ISSUE TITLE
ESP8266 Fatal exception (0) using NodeMCU

### ISSUE THREAD

**Issue by aditgupta100** [esp8266/Arduino#2318]
#### Hardware

Hardware:           ESP8266-1
### Description

When i boot ESP8266 i'm getting on my arduino MEGA serial monitor.  Fatal exception (0): e2= 0d00l(xp00v0xao1,00e0c pe80c00d0x:2= 0d00l(xp00v0xao1,00e0c pe80c00d0x:2= 0d00l(xp00v0xao1,00e0c e 0xp0= 0e)02,0d00a 0e00c00Fic00= 0p0e 0xp0= 0e)02.   I used NodeMcu flasher nodemcu_integer_0.9.5_20150318.bin and NodeMCU 0.9.5 build 20150318 powered by Lua 5.1.4. I'm using arduino UART (serial monitor) to talk to ESP8266. Module is powered with apt power (separate power supply)

It is flashed properly.
### Settings in IDE

Module:             ESP8266-1
Flash Size:         4MB
CPU Frequency:      ?80Mhz?
Flash Mode:         DIO
Flash Frequency:    40Mhz
Upload Using:       Arduino FTDI Serial
### Sketch

``` cpp

#include <Arduino.h>

#define esp8266 Serial2
#define CH_PD 4 // but needs a narrow low pulse
#define speed8266 115200 // This is the speed that worked with my ESP8266
void setup()
{
 esp8266.begin (speed8266);
 Serial.begin(9600);
 reset8266(); // Pin CH_PD need a reset before start communication
}
void loop()
{
 while(esp8266.available())
 { Serial.write(esp8266.read()); }
 while(Serial.available())
 { esp8266.write(Serial.read()); }
}
/*************************************************/
// Reset funtion to accept communication
void reset8266 ()
{
 pinMode(CH_PD, OUTPUT);
digitalWrite(CH_PD, LOW);
 delay(300);
 digitalWrite(CH_PD, HIGH);
}
```
### Debug Messages

```
Fatal exception (0): e2= 0d00l(xp00v0xao1,00e0c pe80c00d0x:2= 0d00l(xp00v0xao1,00e0c pe80c00d0x:2= 0d00l(xp00v0xao1,00e0c e 0xp0= 0e)02,0d00a 0e00c00Fic00= 0p0e 0xp0= 0e)02
```

**Comment by igrr** [comment]
It appears that something is wrong with your serial port connection. Exception line has all the characters messed up. I can imagine this may also affect upload process, so the code in flash may have been uploaded incorrectly.

**Comment by aditgupta100** [comment]
No, all connections are fine. I've tried with AT firmware and the same module was working perfectly fine. Now when i flashed NodeMCU firmware 0.9.x version nothing works.
It is giving Fatal exception 0(IllegalInstructionCause).

In the Esplorer IDE i'm getting 
Can't autodetect firmware , because proper answer not received (may be unknown firmware).

When i pull CH_PD high-low-high at this point then fatal exception comes.

 I'm not sure about the locations of all flash address and flash size but i hope .Bin firmware isn't corrupted (downloaded from github).

I have gone through instructions here : nodemcu.readthedocs.io/en/latest/en/#getting-started

**Comment by taeraeyttaejae** [comment]
any update on this issue ?

i have the same issue with one nodemcu 1.0 using arduino ide 1.8.1.

using anything causes the fatal exeption, and it prints out with 74880 baud rate.

**Comment by devyte** [comment]
@aditgupta100 said:

> nodemcu_integer_0.9.5_20150318.bin and NodeMCU 0.9.5 build 20150318 powered by Lua 5.1.4

That is the Lua firmware. What does that have to do with this firmware?

If you were trying to flash a firmware based on this repo over the Lua one, I suggest erasing the entire flash first (i.e.: with esptool), and only then flashing this one.

Not the right place to ask for assistance, please refer to a forum. Closing per #3655 .
