### ISSUE TITLE
Auto size spiffs file system. Universal binary creation. 

### ISSUE THREAD

**Issue by mmiscool** [esp8266/Arduino#2321]
I would really like to have an option to produce a generic binary that can be flashed to any device and auto size the spiffs file system to the max size.

Enhancement request.

**Comment by igrr** [comment]
If the device already has smaller SPIFFS partition flashed (e.g. someone was using a 1M binary on 4M flash), would you like the partition to be preserved? Or is it okay to just create new partition which fits actual flash size?

**Comment by mmiscool** [comment]
I would like it to max out the size of the file system automatically.

**Comment by igrr** [comment]
I.e. it has to overwrite older small partition, correct?

**Comment by mmiscool** [comment]
Yes. Wipe out the old smaller one. That would be great.

**Comment by mmiscool** [comment]
Somewhat related. Don't know if it is possible. I have run in to trouble compiling for 1 megabyte modules. The file system takes up half of the module and the firmware the other half. Unfortunately my firmware is now over the allowable size limit. Would be nice if this allowed for the size of spiffs system to shrink either tightly using space unused or reserved by the firmware or to size to the next step down for rigid size of the spiffs.

**Comment by mmiscool** [comment]
Any word on this becoming a possibility?

**Comment by devyte** [comment]
From what I can tell, this requires some rather deep and fundamental changes to code, ld scripts, and IDE menu.
Removing milestone for now.

**Comment by d-a-v** [comment]
This will be fixed by #6690.
Pushing to v3.0.1.
