### ISSUE TITLE
Unable to upload .bin file using "esp8266 flash download tool" 

### ISSUE THREAD

**Issue by romuye123** [esp8266/Arduino#2339]
#### Hardware

Hardware:           ESP-12
Core Version:               2.3.0
### Description

Generated a .bin file using "Export Compiled Binary"  with following settings in IDE.
Used EEPROM in the program. When we upload program using "esp8266 flash download tool" it uploads correctly for the first time. When we do some EEPROM related action it gives exception and restarts and repeated exception on boot "Exception (28):"
### Settings in IDE

Module:             Generic ESP8266 Module
Flash Size:         4MB
CPU Frequency:  80Mhz
Flash Mode:         dio
Flash Frequency:    40Mhz
Upload Using:       SERIAL
Reset Method:       ck

**Comment by me-no-dev** [comment]
It seems that you do not have problem uploading bin files, but instead probably have selected wrong flash size and the EEPROM lib overwrites system block. The information you give is way not enough for better guess. Please attach code and decoded exception stack trace

**Comment by igrr** [comment]
Could you please paste a screenshot of your settings in "esp8266 flash download tool"?

**Comment by romuye123** [comment]
@igrr 
Here are settings in "esp8266 flash download tool":

![whatsapp image 2016-07-29 at 12 01 28 am](https://cloud.githubusercontent.com/assets/1880131/17330596/07412f30-58e5-11e6-96fb-08ebbd973a65.jpeg)


@me-no-dev 
And the program is very basic program which uses storing few variables and reading them using EEPROM.

`
void setup() {
  Serial.begin(115200);  
  EEPROM.begin(1124);
}
`

**Comment by romuye123** [comment]
Exception occurring after you do some EEPROM related action. And the program restarts and exception appears and the cycle continues.......


![exception](https://cloud.githubusercontent.com/assets/1880131/17330887/3bf5e026-58e6-11e6-8024-6f97fd77d859.jpeg)

**Comment by romuye123** [comment]
@igrr @me-no-dev 
Any update on this ? Still not able to resolve the problem ?

**Comment by me-no-dev** [comment]
There is [this](https://github.com/me-no-dev/EspExceptionDecoder) to decode that stack trace and I have no knowledge of that "esp8266 flash download tool". We do not use that.

**Comment by romuye123** [comment]
@me-no-dev 
what should be used to upload bin files on esp12e? is there any other GUI tool ?
also request you to mention the address parameters on where the generated .bin file to uploaded ?

**Comment by igrr** [comment]
With the settings as in above photo it should work correctly. I'll try to reproduce.
Just to be sure i got this right, did you select "Generic" module in the IDE and "4M(3M SPIFFS)" as flash size (in Tools menu)?

**Comment by me-no-dev** [comment]
I use Arduino IDE to upload my sketches, which uses esptool-ck, which can be called from terminal (command prompt). Why are you using something else and not the Arduino IDE itself?

**Comment by romuye123** [comment]
@igrr: Yes following are my correct settings in tools menu

Module: Generic ESP8266 Module
Flash Size: 4M(3M SPIFFS)
CPU Frequency: 80Mhz
Flash Mode: dio
Flash Frequency: 40Mhz
Upload Using: SERIAL
Reset Method: ck

I generate **myapp.cpp.bin** file using Arduino IDE with above settings by pressing Verify button. 
Then using 'ESP download tool' i upload the myapp.cpp.bin file on 0x00000 address and it uploads at very first time but gives eeprom related issues. Then after that it keeps giving Exception (28):


@me-no-dev Yes i also use Arduino IDE itself to upload sketch. But i want to share the binary file to someone else and do not want to share the source code with him. Thats why asking is there any other simple option to upload? Something like select file and upload as mentioned in my earlier screenshot.

**Comment by krzychb** [comment]
> But i want to share the binary file to someone else and do not want to share the source code with him. Thats why asking is there any other simple option to upload?

Hi @romuye123,

Did you consider uploading from a [web browser](https://github.com/esp8266/Arduino/tree/master/doc/ota_updates#web-browser)?

Krzysztof

**Comment by roboticboyer** [comment]
Why don't use directly the esptool to write the bin file?
It's the upload tool of Arduino Ide for ESP.
It can be found inside the Arduino Ide folders:
packages/esp8266/tools/esptool/0.4.9/esptool -vv -cd ck -cb 115200 -cp /dev/ttyUSB1 -ca 0x00000 -cf /directories/file.bin

**Comment by devyte** [comment]
Not the right place to ask for this kind of help. Please refer to a forum for discussion.
Closing per #3655 .
