### ISSUE TITLE
No TXT data in answer

### ISSUE THREAD

**Issue by bitoadpl** [esp8266/Arduino#2342]
This is rather feature request then issue, but lack of TXT data in answer is very limiting

**Comment by me-no-dev** [comment]
I am not quite sure what you are requesting. Lack of what TXT answer and where?

**Comment by devyte** [comment]
@igrr I almost closed this due to lack of info, but you added the enhancement tag for a library component. What is the request here?

**Comment by igrr** [comment]
I suppose this is covered by https://github.com/esp8266/Arduino/pull/3107

**Comment by devyte** [comment]
Let's assume it is. Closing.
