### ISSUE TITLE
Is there any "WiFi Direct " example available ? 

### ISSUE THREAD

**Issue by waqas-ogc** [esp8266/Arduino#2343]

**Comment by igrr** [comment]
This isn't available in non-OS SDK at the moment, and therefore not available in Arduino core.

**Comment by stern0m1** [comment]
Is this possible with with rtos?
Can you post an example?
Thanks

**Comment by Androbin** [comment]
Someone seems to have done it:
https://github.com/youmebangbang/esp8266-wifi-direct-examples

**Comment by cristiandc** [comment]
> Someone seems to have done it:
> https://github.com/youmebangbang/esp8266-wifi-direct-examples

That isnt look like a wifi direct protocol. Instead its just a server-client simple communication with some-guy-made protocol
