### ISSUE TITLE
Finding Mac address of the connected SSID 

### ISSUE THREAD

**Issue by adithyaselv** [esp8266/Arduino#2346]
Hi ,
 Is there any method available in the api to find the mac address of the ssid to which the esp is connected to in STA mode ? If not, what is the way to find the same ?

Thanks

**Comment by krzychb** [comment]
Hi @adithyaselv,

To obtain mac address of the access point your station is connected to you can use:
```cpp
WiFi.BSSID()
```
_Example:_  https://www.arduino.cc/en/Reference/WiFiBSSID

Alternatively you can use:
```cpp
WiFi.BSSIDstr()
```
_Example:_
```cpp
Serial.printf("BSSID: %s\n", WiFi.BSSIDstr().c_str());
```

Krzysztof

**Comment by adithyaselv** [comment]
Thank you so much
