### ISSUE TITLE
Wifi not working after a deep sleep

### ISSUE THREAD

**Issue by apicquot** [esp8266/Arduino#2348]
#### Hardware
Hardware:	       ESP-12 E or F (Huzzah board)
Core Version:      	2.3.0

### Description

After a hard reset I connect fine to the wifi. The connection works fine after a pin pull down reset as well.

After a deep sleep and a consequent reset on wake up (pin16 and reset connected), I can no longer connect to the wifi. The error is WL_NO_SSID_AVAIL. No network can be found if performing a scan at that point.

I tried to use  in setup():
`  ESP.eraseConfig();
  WiFi.persistent(false);`
as some blogs mention the risk of flash config getting corrupted after successive connections. I also check for the stored Wifi.SSID() and use WiFi.begin() without parameters if there are already correct.

### Settings in IDE

Module:  			Huzzah
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		SERIAL
Reset Method:		?ck / nodemcu?

### Sketch

```
#include <Arduino.h>
#include <ESP8266WiFi.h>

const char* ssid = "ssid here";
const char *pwd = "password here";

void setup() {

  ESP.eraseConfig();
  
  Serial.begin(115200);
  delay(10);
  Serial.println("Hello World");
  
  WiFi.persistent(false);
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  
}

void loop() {

  //after 10sec got to deep sleep for 5sec
  if (millis() > 10000) {
    Serial.println("Going to sleep");
    ESP.deepSleep(5000000, WAKE_RF_DISABLED);
  };

  //nothing to do if connected
  if (WiFi.status() == WL_CONNECTED) 
    return;

  //try not to reuse begin(ssid,pwd) as some blogs
  //mention possible corruption of the flash memory
  if (String(ssid) != WiFi.SSID())
  {
    Serial.print("Connecting to ");
    Serial.print(ssid);
    WiFi.begin(ssid, pwd);
  }
  else
  {
    //not supposed to happen with WiFi.persistent(false)
    Serial.print("Connecting using saved credentials");
    WiFi.begin();
  }

  Serial.println("...");
  if (WiFi.waitForConnectResult() == WL_CONNECTED) 
  {
    Serial.println("WiFi connected");
  }
  else
  {
      //scan for networks if connection fails
      Serial.println("scan start");
      // WiFi.scanNetworks will return the number of networks found
      int n = WiFi.scanNetworks();
      Serial.println("scan done");
      if (n == 0)
        Serial.println("no networks found");
      else
      {
        Serial.print(n);
        Serial.println(" networks found");
        for (int i = 0; i < n; ++i)
        {
          // Print SSID and RSSI for each network found
          Serial.print(i + 1);
          Serial.print(": ");
          Serial.print(WiFi.SSID(i));
          Serial.print(" (");
          Serial.print(WiFi.RSSI(i));
          Serial.print(")");
          Serial.println((WiFi.encryptionType(i) == ENC_TYPE_NONE) ? " " : "*");
          delay(10);
        }
      }
    }
  
  

}
```

### Debug Messages

```
Connecting to network...
WiFi connected
Going to sleep
Connecting to network...
scan start
scan done
no networks found

```

It works the first time, does not work after the deep sleep

**Comment by igrr** [comment]
`ESP.deepSleep(5000000, WAKE_RF_DISABLED);`
Seriously? You configure it to wake up with RF disabled. How can WiFi keep working when RF is disabled?

**Comment by apicquot** [comment]
Thank you igrr and apologize for the rookie mistake, the wifi works fine with WAKE_RF_DEFAULT:
```
    //ESP.deepSleep(5000000, WAKE_RF_DISABLED);
    ESP.deepSleep(5000000, WAKE_RF_DEFAULT);
```

I thought WAKE_RF_DISABLED was a mode to save even more energy and that wifi will be turn on back after a reset... my bad.

**Comment by SherlockHolmes95** [comment]
Please can someone help me. When I run my code without the "ESP.deepSleep(5000000, WAKE_RF_DEFAULT);" it works but when I run it with "ESP.deepSleep(5000000, WAKE_RF_DEFAULT);" it gives me a wrong output. Here is my code :  

#include <ESP8266WiFi.h>
#include <OneWire.h>
//#include <DallasTemperature.h>
static uint32_t minutes=0;
int rtcValue=0;
//Def
#define myPeriodic 4 //in sec | Thingspeak pub is 15sec
#define ONE_WIRE_BUS 2  // DS18B20 on arduino pin2 corresponds to D4 on physical board
//#define mySSR 0  // Solid State Relay on pin 0
float prevTemp = 0;
const char* server = "api.thingspeak.com";
//String apiKey ="RJD8Y6OVCHEU5578"; First thingspeak channel
String apiKey ="9Q62GZYMZOAHPJUW"; //second channel
const char* MY_SSID = "ENOVA-GUEST"; 
const char* MY_PWD = "ENOVA-GUEST";
int sent = 0;
void connectWifi()
{
  Serial.print("Connecting to "+*MY_SSID);
  WiFi.begin(MY_SSID, MY_PWD);
  while (WiFi.status() != WL_CONNECTED) {
  delay(1000);
  Serial.print(".");
  }
  
  Serial.println("");
  Serial.println("Connected");
  Serial.println("");  
}
//OneWire oneWire(ONE_WIRE_BUS);
//DallasTemperature DS18B20(&oneWire);
void sendNumber(int inc)
{  
  
   WiFiClient client;
  
   if (client.connect(server, 80)) { // use ip 184.106.153.149 or api.thingspeak.com
   Serial.println("WiFi Client connected ");
   
   String postStr = apiKey;
   postStr += "&field1=";
   postStr += String(inc);
   postStr += "\r\n\r\n";
   
   client.print("POST /update HTTP/1.1\n");
   client.print("Host: api.thingspeak.com\n");
   client.print("Connection: close\n");
   client.print("X-THINGSPEAKAPIKEY: " + apiKey + "\n");
   client.print("Content-Type: application/x-www-form-urlencoded\n");
   client.print("Content-Length: ");
   client.print(postStr.length());
   client.print("\n\n");
   client.print(postStr);
   delay(1000);
   
   }//end if
   sent++;
 client.stop();
}
void setup() {
  Serial.begin(115200);
  connectWifi();
}

void loop() {
  float temp;
 
  Serial.print(String(sent)+" Temperature: ");
  Serial.println("Test ESP");
  }
}
  Serial.println("I'm awake.");

  Serial.println("Going into deep sleep for 20 seconds");
  //ESP.rtcUserMemoryWrite(0, &minutes, sizeof(minutes));
  ESP.deepSleep(2000000,WAKE_RF_DEFAULT);
  //ESP.rtcUserMemoryRead(0, &rtcValue, sizeof(rtcValue));
  sendNumber(rtcValue);
  
  //rtcValue+=0.333;
}

**Comment by liebman** [comment]
`ESP.deepSleep(2000000,WAKE_RF_DEFAULT);` will never return so `sendNumber(rtcValue);` will never be executed.  Its a reset and when the sleep is over it starts back at `setup()`.

**Comment by SherlockHolmes95** [comment]
Thanks for your help.
