### ISSUE TITLE
Detect the board type inside the code

### ISSUE THREAD

**Issue by marcoschwartz** [esp8266/Arduino#2350]
Hello, 

I would like to know if there was a way to detect in the code which ESP8266 board/variant is currently selected by the user, for example by something like:

#if define(NODEMCU)
// Some code specific to this board
#endif

Thanks!

**Comment by me-no-dev** [comment]
```cpp
#ifdef ARDUINO_ESP8266_ NODEMCU
// Some code specific to this board
#endif
```
Defined by build.board in [boards.txt](https://github.com/esp8266/Arduino/blob/master/boards.txt#L892)
