### ISSUE TITLE
unable to upload scripts to the nodemcu through arduino ide

### ISSUE THREAD

**Issue by shinong** [esp8266/Arduino#2359]
#### Hardware

Hardware:           ESP-8266
Core Version:       ?
### Description

Problem description
first set up with arduino ide and try to upload the sketch, it can't be processed. returned with an error code : 
Arduino: 1.6.6 Hourly Build 2015/06/29 09:13 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

xtensa-lx106-elf-gcc: error: arduino.ar: No such file or directory
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
### Settings in IDE

Module:             ?Generic ESP8266 Module?
Flash Size:         ?4MB/1MB?
CPU Frequency:      ?80Mhz?
Flash Mode:         ?qio?
Flash Frequency:    ?40Mhz?
Upload Using:       ?ERIAL?
Reset Method:       ?nodemcu?

```


```

**Comment by devyte** [comment]
@shinong Installation procedure is documented.
Not the right place to ask for help. Closing per #3655 .
