### ISSUE TITLE
Parse HTTP Request Arduino

### ISSUE THREAD

**Issue by anujmattoo** [esp8266/Arduino#2372]

**Comment by majenkotech** [comment]
I have told you what you need to do on Arduino.SE. This is not a discussion forum. This is a bug tracking system.

**Comment by anujmattoo** [comment]
I read that, but I am unable to find out other way to do this. I didn't get reply there. Had to post on other forums as well. Please help! I'm in real trouble.

**Comment by majenkotech** [comment]
You haven't looked recently then.
