### ISSUE TITLE
How to created static ip address or DNS server to collect data from URL

### ISSUE THREAD

**Issue by simonreuben** [esp8266/Arduino#2374]
I'm trying to collect sensor data using a URL. So I wanna create either a Static IP or DNS to collect the data.

Hardware: DHT11 & ESP8266-ESP01
# include ESP8266WiFi.h
# include WiFiClient.h
# include ESP8266WebServer.h
# include DHT.h
# define DHTPIN  2

const char\* ssid     = " ";
const char\* password = " ";
// config static IP
  //IPAddress ip(192, 168, 2, 84); 
  //IPAddress gateway(192, 168, 2, 1); 
  //IPAddress subnet(255, 255, 255, 0); 

ESP8266WebServer server(80);

DHT dht(DHTPIN, DHT11, 15); // 11 works fine for ESP8266

float h, t;  // Values read from sensor
String webString="";  

unsigned long previousMillis = 0;  
const long interval = 5000;             

void handle_root() {
  server.send(200, "text/plain", "Hello from the weather esp8266, read from /temp or /humidity");
  delay(100);
}

void setup(void)
{

  Serial.begin(115200);  
  dht.begin();          

  // Connect to WiFi network
  WiFi.begin(ssid, password);
 // WiFi.config(ip, gateway, subnet);
  Serial.print("\n\r \n\rWorking to connect");

  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("DHT Weather Reading Server");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  server.on("/", handle_root);

  server.on("/temp", [](){  
    gettemperature();  
    webString="Temperature(°C)\n" + String((int)t);  
    server.send(200, "text/plain", webString);  
  });

  server.on("/humidity", [](){  
    gettemperature();  
    webString="Humidity(%)\n "+String((int)h);
    server.send(200, "text/plain", webString);  
  });

  server.on("/dht11", [](){  
    gettemperature();  
    webString="Temperature(°C),Humidity(%)\n"+String((int)t)+","+String((int)h);
    server.send(200, "text/plain", webString);  
  });

  server.begin();
  Serial.println("HTTP server started");
}

void loop(void)
{
  server.handleClient();
} 

void gettemperature() {

  unsigned long currentMillis = millis();

  if(currentMillis - previousMillis >= interval) {

```
previousMillis = currentMillis;   



h = dht.readHumidity();        
t = dht.readTemperature();  

if (isnan(h) || isnan(t)) {
  Serial.println("Failed to read from DHT sensor!");
  return;
}
```

  }
}
###### 

 //IPAddress ip(192, 168, 2, 84); 
  //IPAddress gateway(192, 168, 2, 1); 
  //IPAddress subnet(255, 255, 255, 0); 

I tried using these values and using WiFi.config() to create static IP. However when i called 192.168.2.84/dht11...... 

the results would show that the page took too long to respond.

Anyone know how I can fix this?

**Comment by devyte** [comment]
@simonreuben I could be mistaken, but your setup of the callbacks in the webserver looks wrong to me. I think it should be something like this:

```
server.on("/humidity", [] () {
    gettemperature();
    webString="Humidity(%)\n "+String((int)h);
    server.send(200, "text/plain", webString);
  }
);

```
i.e.: you're missing the square brackets and parenthesis of the lambda function.

Not the right place to ask for help for your particular code. Closing per #3655 .
