### ISSUE TITLE
String operates wrong with float values

### ISSUE THREAD

**Issue by Toshik** [esp8266/Arduino#239]
Weird, but... 

```
    String test = "Float 10.01 is magically converted to: ";
    test += 10.01;
    Serial.println(test);
```

Will give you such output:

```
Float 10.01 is magically converted to: 10.1
```

Seems it "eats" leading zeroes of fractional part

**Comment by Makuna** [comment]
It just calls ...
```
dtostrf(num, 4, 2, buf);
```

And yes, there is a bug in this method where it will drop all zeros before, so
10.0004 would print as 10.4.

**Comment by Makuna** [comment]
https://github.com/esp8266/Arduino/pull/242 created to fix this

**Comment by igrr** [comment]
merged
