### ISSUE TITLE
#ifdefs and compatible libraries

### ISSUE THREAD

**Issue by guipoletto** [esp8266/Arduino#2391]
So, i am working in a port of a library to make it multi-plataform (AVR, ESP8266 and STM32). 

i was digging in the core files #defines for a flag i could match, and  cat **.** |grep "#define ESP" 
outputs the following:
## 
# define ESP_H
# define ESP8266_PERI_H_INCLUDED
# define ESP8266_REG(addr) *((volatile uint32_t *)(0x60000000+(addr)))
# define ESP8266_DREG(addr) *((volatile uint32_t *)(0x3FF00000+(addr)))
# define ESP8266_CLOCK 80000000UL
# define ESP_SCHEDULE_H
# define ESP8266UPDATER_H
## 

I guess the most reliable option there would be ESP8266_CLOCK

But may i suggest adding a  #define ESP8266 true  in one of the files that will reliably be used for the whole platform?

Or i am missing something obvious here, and going about it the hard way?

And Thanks and congrats for the great job here!! ;)

**Comment by igrr** [comment]
define ESP8266 is added to the compiler command line, see platform.txt file.
