### ISSUE TITLE
HTTPUpdate security

### ISSUE THREAD

**Issue by AdamMiltonBarker** [esp8266/Arduino#2392]
Using the MAC as an identifier for an update is not very secure as it can be easily spoofed, does anyone have any suggestions for a more secure approach?

**Comment by carlosrodriguesIT** [comment]
Maybe you can use a MAC address and a static IP address to secure a connection...

**Comment by AdamMiltonBarker** [comment]
Possibly although both could be found with an app like Fing. I was thinking of maybe adding api key and secret to spiffs and replicating my other API auth using an extra header in the update.

**Comment by carlosrodriguesIT** [comment]
I think you have thought of a solution , now only have to apply, API key is a good solution, because is a long private string, not easy to discover, but HTTP is a weak protocol, any snnifer can be used to find your key.

**Comment by AdamMiltonBarker** [comment]
Not if it is encrypted though. I have secure MQTT implemented as well any ideas for the future for support of MQTT

**Comment by carlosrodriguesIT** [comment]
OK, if you use MQTT over SSL port 8883 by default is a good security measure, for MQTT I have many ideias, but still in resource.

**Comment by AdamMiltonBarker** [comment]
Yes I have my own broker which is used for clients and devs and it only allows connection on port 8883.

**Comment by carlosrodriguesIT** [comment]
Anyway, your broker is based in mosquitto, or do you have your own code?

**Comment by AdamMiltonBarker** [comment]
Yes it is a mosquitto broker mixed with the auth plugin.

**Comment by devyte** [comment]
Not the right place to have this discussion.
Closing as non-issue per #3655 .
