### ISSUE TITLE
ESP crashes, throwing exception 29

### ISSUE THREAD

**Issue by anujmattoo** [esp8266/Arduino#2395]
#### Hardware

Hardware: ESP-12F
Core Version: 2.3.0
### Description

I am getting exception 29 and it crashes the ESP12F. I am sending HTTP Request every 15-30ms to ESP. It sometimes crashes after thousand request and sometimes crashes after few hundred request. My project requires HTTP Request to be sent every 15-30ms. I have increased the CPU Frequency from 80Mhz to 120Mhz, but it still crashes.

I have attached the ESP Exception stack decoder result.

Please help! @me-no-dev @igrr @majenkotech 
### Settings in IDE

Module: NodeMCU(12-E)
Flash Size: 4MB
CPU Frequency: 120Mhz
Flash Mode: qio
Flash Frequency: 40Mhz
Upload Using: SERIAL
Reset Method: ck / nodemcu
### Sketch

```
#include <ESP8266WiFi.h>
#include <EEPROM.h>
#include <ESP8266WebServer.h>


WiFiServer server(80);

void setup()
{
  WiFi.mode(WIFI_AP); //Our ESP8266-12E is an AccessPoint
  WiFi.softAP("Hello_IoT", "12345678"); // Provide the (SSID, password); .
  server.begin(); // Start the HTTP Server

  Serial.begin(115200); //Start communication between the ESP8266-12E and the monitor window
  IPAddress HTTPS_ServerIP = WiFi.softAPIP(); // Obtain the IP of the Server
  Serial.print("Server IP is: "); // Print the IP to the monitor window
  Serial.println(HTTPS_ServerIP);
}

void loop()
{
  WiFiClient client = server.available();
  if (!client)
  {
    return;
  }

  Serial.println("Somebody has connected :)");

  String incoming = client.readStringUntil('\r');
  Serial.println(incoming);
  client.flush();

  String s = "HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Length: 0\r\n\r\n";

  // Send the response to the client
  client.print(s);
  delay(1);
  Serial.println("Client disonnected");
}

```
### Debug Messages

<img width="1168" alt="screen shot 2016-08-15 at 2 41 21 pm 1" src="https://cloud.githubusercontent.com/assets/15719098/17660571/b3e023ec-62f7-11e6-90a4-b36fb887ab5c.png">

**Comment by igrr** [comment]
If you are sending "Connection: close" header, you probably want to wait until client actually closes the connection.
Alternatively, try git version of the core — it has a tweak by @me-no-dev to eliminate TCP connections in TIME_WAIT state, freeing up memory.

**Comment by anujmattoo** [comment]
Can you please mention the link to the Git version of the core?

**Comment by igrr** [comment]
See readme for instructions: https://github.com/esp8266/Arduino#using-git-version

**Comment by anujmattoo** [comment]
I am unable to use git version for mac! Please help

**Comment by igrr** [comment]
Sure, what's the problem?

**Comment by anujmattoo** [comment]
The commands use in the instructions are for windows command prompt and how can use that with mac terminal. I have downloaded the python 2.7 for mac and how to clone the repository and to where in mac?

**Comment by igrr** [comment]
These commands work in mac and linux as well.
Download arduino IDE to any location you like (though i suggest to use some directory under your home directory). Then open terminal and use cd command to go inside Arduino.app directory. 
For example, i have my Arduino.app in ~/Apps/arduino/nightly/. So in Terminal, i type:
```
cd ~/Apps/arduino/nightly/Arduino.app/Contents/Java/hardware
mkdir -p esp8266com
cd esp8266com
git clone https://github.com/esp8266/Arduino.git esp8266
cd esp8266/tools
python get.py
```

By the way, before you do that, make sure you uninstall the esp8266 package installed via boards manager. Failure to do that will cause errors in Arduino IDE.

**Comment by igrr** [comment]
Also, you don't need to download python 2.7 if you're on a recent OS X version. OS X comes with python already installed.

**Comment by anujmattoo** [comment]
Thanks! It worked. Can you please explain what is the difference between the git version and stable version.? How  TIME_WAIT solves the crash issue?

**Comment by igrr** [comment]
You can navigate repository history using GitHub to see the changes since the last release.
TIME_WAIT doesn't solve the problem, it is a state defined by the TCP spec.
This commit adds a limit to the number of pcbs in time_wait state, violating the spec but adapting the stack to the limited RAM of the 8266: https://github.com/esp8266/Arduino/commit/07f4d4c241df2c552899857f39a4295164f686f2

**Comment by devyte** [comment]
Per OP's last comment, closing as resolved.
