### ISSUE TITLE
Port pwm code problem

### ISSUE THREAD

**Issue by baoxianzhang** [esp8266/Arduino#2402]
#### Hardware

Hardware:           ESP-12
Core Version:       2.1.0-rc2
### Description

I ported the pwm code (core_esp8266_wiring_pwm.c) to my personal project. But it didn't work, no wave displayed in the oscilloscope. 
I barely changed the code. So please guide me to find out the problem. How to debug? How to detect the pwm timer whether start or not?  Are there any documentation about the register usage?
Thanks!
### Settings in IDE

Module:             Generic ESP8266 Module
Flash Size:         4MB
CPU Frequency:      80Mhz
Flash Mode:         qio
Flash Frequency:    40Mhz
Upload Using:  
Reset Method:       nodemcu
### Sketch

``` cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```
### Debug Messages

```
messages here
```

**Comment by devyte** [comment]
Not the right place to ask for help for your personal project. Closing per #3655 .
