### ISSUE TITLE
clean up SPI_FLASH_SEC_SIZE and/or FLASH_SECTOR_SIZE

### ISSUE THREAD

**Issue by holgerlembke** [esp8266/Arduino#2421]
FLASH_SECTOR_SIZE is defined in cores/esp8266/flash_utils.h, while the SPI_FLASH_SEC_SIZE is defined in tools/sdk/include/spi_flash.h. They have both the same value and I assume they shall have the same meaning.

EEPROM uses SPI_FLASH_SEC_SIZE.

just to not confuse ppl...

**Comment by devyte** [comment]
The referenced code is still present in latest git.
I think FLASH_SECTOR_SIZE  should be #defined in terms of SPI_FLASH_SEC_SIZE, which comes from the Espressif SDK.
