### ISSUE TITLE
Get time

### ISSUE THREAD

**Issue by panagorn** [esp8266/Arduino#2439]
Is it possible to get the current time without using any hardware or internet connection?

**Comment by supersjimmie** [comment]
Enter current time after startup over Serial?

**Comment by panagorn** [comment]
my esp is connected with battery

**Comment by supersjimmie** [comment]
So your esp has really nothing: no internet, no serial, no other input not any way to reach anything?
Then it is impossible.  It has no builtin clock so when it is booted it has no idea about time.

**Comment by panagorn** [comment]
If it has internet is it possible to get it one time at boot and then know the time without any other request?

**Comment by everslick** [comment]
yes, but the internal software clock will drift over time. here i see a drift of around 160ms per hour.

**Comment by supersjimmie** [comment]
Since you say it runs on a battery, I think it is not running for too many hours without a reboot (deep sleep).
So if you do have internet and read a time source over internet at boot, you will be able to use that time for hours if you don't mind losing perhaps a second.

**Comment by panagorn** [comment]
@supersjimmie how can i do that?

**Comment by supersjimmie** [comment]
Just do a qck search for the Time library?

**Comment by perryc** [comment]
It was not the primary reason to include it in the design but I set time from a cheap GPS chip.

**Comment by devyte** [comment]
@panagorn There are RTC modules that keep time. They all have some drift, although minimal.
Alternatively, there is TimeLib, which can keep time using the internal cpu counter after you set it. It will drift slightly over time, you'll want to sync via NTP once in a while (e.g.: once a day, once every few days), You can use e.g.: NtpClientLib to sync via NTP. 
Closing per #3655 .
