### ISSUE TITLE
Running ESP8266 Serial WiFi example on Arduino Uno

### ISSUE THREAD

**Issue by titusece** [esp8266/Arduino#2446]
Hi,

I've ESP8266 Serial WiFi module, want to run some wifi examples using Arduino UNO board, I did the following but not able to find the ESP8266 based WiFI examples after restart the arduino IDE.

Can you please help me out of this problem ?

cd hardware
mkdir esp8266com
cd esp8266com
git clone https://github.com/esp8266/Arduino.git esp8266
cd esp8266/tools
python get.py

**Comment by WereCatf** [comment]
All this code is meant for running the ESP8266 **itself** as an Arduino-device, not as a device to provide another Arduino with WiFi. If you want to use another Arduino and use an ESP8266 to provide WiFi for it you should flash the AT-firmware and look elsewhere for examples on how to use it with your Arduino.

**Comment by titusece** [comment]
Thanks WereCatf

**Comment by LuizHAP** [comment]
@WereCatf do u have another library for that?

**Comment by WereCatf** [comment]
@LuizHAP No, I do not. Google for "esp8266 arduino uno" or something for examples on how to use it.

**Comment by supersjimmie** [comment]
Take a look at https://github.com/sparkfun/SparkFun_ESP8266_AT_Arduino_Library
(don't let the picture mislead you, just look at the code, I think that is what you need)
