### ISSUE TITLE
Is it possible to change HSPI pins?

### ISSUE THREAD

**Issue by Ignat-Georgiev** [esp8266/Arduino#2455]
Recently I made a custom PCB but didn't pay attention that I exchanged the HSPI pins. MISO and MOSI are replacing each other. Is there a way to exchange them, otherwise I'll have to rework a lot of PCBs?

**Comment by WereCatf** [comment]
I do not think the hardware supports swapping the pins around.

**Comment by devyte** [comment]
From the code, it doesn't seem possible to change the pins. Closing.
