### ISSUE TITLE
esp8266 web server ( reading the content of web server )

### ISSUE THREAD

**Issue by mostafa-khedrawy** [esp8266/Arduino#2458]
#### Hardware

Hardware:           ?ESP-12?
Core Version:       ?2.1.0-rc2?
### Description

Problem description
### Settings in IDE

Module:             ?Generic ESP8266 Module?
Flash Size:         ?4MB?
CPU Frequency:      80Mhz
Flash Mode:         qio
Flash Frequency:    40Mhz
Upload Using:        SERIAL
Reset Method:       ck 

I make web server on my esp8266 all i want is to read the content of this web server 
I make my web server with this line of code and send to it some html and javascript 
this line of HTML code i send with wifi module

stop

now I need to read the content of my web page and see what in this div I am noob with this module :D

**Comment by devyte** [comment]
Not the right place to ask for assistance. Closing per #3655 .
