### ISSUE TITLE
Use Arduino Mega + ESP8266

### ISSUE THREAD

**Issue by LuizHAP** [esp8266/Arduino#2467]
Hi guys, i need some help in my Project.
This library works for connection ESP8266 with Arduino Mega like a connection below?

ESP8266 TX -> Arduino MEGA RX (19)
ESP8266 RX -> Arduino MEGA TX (18) with 3.3v

I will use this project for my Home Automation, then will receive HTTPS request from a Node.js.

Can you help me?

Thanks!

**Comment by supersjimmie** [comment]
Take a look at https://github.com/sparkfun/SparkFun_ESP8266_AT_Arduino_Library
(don't let the picture mislead you, just look at the code, I think that is what you need)

**Comment by Bushii7** [comment]
i am also having difficulties in connection with arduino mega 
can u guys help me with the connections?PIN config ?

**Comment by devyte** [comment]
Not the right place to request help for your particular project. Closing per #3655 .
