### ISSUE TITLE
WiFiMulti.run looped when passphrase is incorrect

### ISSUE THREAD

**Issue by denisn73** [esp8266/Arduino#2468]
## Hi. I'm use WiFiMulti.run in AP_STA mode, and when i'm change passphrase of remote AP, programm loops in WiFi multi.run. I assume that the program is looped here:

// wait for connection or fail
while(status != WL_CONNECTED && status != WL_NO_SSID_AVAIL && status != WL_CONNECT_FAILED)  {
  delay(10);
  status = WiFi.status();
}

---

Because of that I can not go to the server to reconfigure the passphrase, as 'server.handleClient();' function in the my main loop is not processed.
How can I stop WiFi Multi if the key phrase has changed and accordingly become incorrect?
Please fix this bug.

**Comment by denisn73** [comment]
I'm correct function run() to:
----
// wait for connection or fail
//while(status != WL_CONNECTED && status != WL_NO_SSID_AVAIL && status != WL_CONNECT_FAILED) {
while(status != WL_CONNECTED && status != WL_NO_SSID_AVAIL && status != WL_CONNECT_FAILED && status != WL_DISCONNECTED) {
  delay(10);
  status = WiFi.status();
 }

---
And now this work for me.

**Comment by devyte** [comment]
@denisn73 is this issue still valid in latest git? does it also happen with PR #3215 ?

**Comment by devyte** [comment]
Closing as duplicate of #3993 .

**Comment by ConstantinCreations** [comment]
Still an issue. Wrong password and wifimulti will fail to try another network.
