### ISSUE TITLE
How to know TX fifo ended send?

### ISSUE THREAD

**Issue by MrD2** [esp8266/Arduino#2476]
DUMP:::

`    128
                                                                                           
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
128
                                                                                               
     
                                                                                             
Soft WDT reset
                                                                                    
                
                                                                                  
ctx: cont 
                                                                                        
sp: 3ffef370 end: 3ffef610 offset: 01b0
                                                           
                                         
                                                         
>>>stack>>>
                                                                                       
3ffef520:  3ffef654 000000f7 000000f7 401002a8  
                                                  
3ffef530:  3fffdad0 00000067 3ffef5c7 4020255c  
                                                  
3ffef540:  feefeffe feefeffe 3ffef5e4 3ffee5e4  
                                                  
3ffef550:  3fffdad0 00000000 3ffee5c0 40201d87  
                                                  
3ffef560:  64757453 73746e65 65657320 6572206b  
                                                  
3ffef570:  6665696c 6f726620 6972206d 676e6973  
                                                  
3ffef580:  69727020 20736563 6f726874 20686775  
                                                  
3ffef590:  20656874 63727570 65736168 20666f20  
                                                  
3ffef5a0:  64657375 706f6320 20736569 7420666f  
                                                  
3ffef5b0:  62747865 736b6f6f 6877202c 20686369  
                                                  
3ffef5c0:  62206574 61662079 746c7563 65642079  
                                                  
3ffef5d0:  646e616d 6854202e 74532065 6e656475  
                                                  
3ffef5e0:  3fffda00 00000000 00000000 00000000  
                                                  
3ffef5f0:  feefeffe feefeffe 3ffee5dc 4020235c  
                                                  
3ffef600:  feefeffe feefeffe 3ffee5f0 40100114  
                                                  
<<<stack<<<
                                                                                       
             
                                                                                     
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)
                                                     
                                               
                                                   
load 0x4010f000, len 1384, room 16 
                                                               
tail 8
                                                                                            
chksum 0x2d
                                                                                       
csum 0x2d
                                                                                         
v09f0c112
                                                                                         
~ld
  
`

How can i know after the Serial.write or Serial.print or Serial.println commands when the TXfifo has stopped sending? By pooling or other way (ex interrupt), using arduino IDE??

I searched the Expressiff repo src files and i found here -> [here](https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/include/espressif/esp8266/uart_register.h) but it dosen't work for me...

my code,

`char derp[] = "Students seek relief from rising prices through the purchase of used copies of textbooks, which te by faculty demand. The Studen";
  while(1){
    Serial1.println(String(Serial.write(derp)));
    while( (UART_STATUS(0) & (UART_TXFIFO_CNT<<UART_TXFIFO_CNT_S))){
      Serial1.print("AVAILABLE ");
      Serial1.print(String((UART_STATUS(0) & (UART_TXFIFO_CNT<<UART_TXFIFO_CNT_S))>>UART_TXFIFO_CNT_S));
      }
  }`

Apparently, the size returned by `Serial1.print(String((UART_STATUS(0) & (UART_TXFIFO_CNT<<UART_TXFIFO_CNT_S))>>UART_TXFIFO_CNT_S));` is always the same **128Bytes** which also **corresponds to the UART_TXFIFO_SIZE buffer** configuration flag from HardwareSerial.h (if i'm not mistaken)

But even though it say's buffer is clear to send, program breaks after some time (See DUMP)

Is there any other way of **waiting for full TX send completion** within the Arduino IDE??? 

#### Hardware
Hardware:			ESP8266-12

Module:  			Generic ESP8266 Module
Flash Size: 		512KB
CPU Frequency:	80Mhz
Flash Mode:		dio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		down RST down FLASH up RST up FLASH

**Comment by WereCatf** [comment]
Use `Serial1.flush()`
