### ISSUE TITLE
You must hard reset after serial uploading an OTA sketch ?

### ISSUE THREAD

**Issue by penfold42** [esp8266/Arduino#2485]
Is it an absolute fact that you must hard reset (with the reset pin) after serial uploading an OTA sketch before you do an OTA update ?

Will this always be the case ?

Is it documented anywhere "official" ?

**Comment by krzychb** [comment]
Hi @penfold42,

Yes, this is the fact.
Will this always be the case ? - Ref. https://github.com/esp8266/Arduino/issues/1017#issuecomment-200605576
It has been recently documented in [FAQ](https://github.com/esp8266/Arduino/tree/master/doc/faq#i-have-observed-a-case-when-esprestart-doesnt-work-what-is-the-reason-for-that). 
There is also an update to OTA documentation queued for merging - https://github.com/esp8266/Arduino/pull/2444/commits/cd2e04b6dd494627ccbb12137717f94f386df4d1

Krzysztof

**Comment by penfold42** [comment]
Thanks !
