### ISSUE TITLE
ESP8266HttpClient - PUT (String payload) calls POST(payload, size) instead of PUT(payload, size)

### ISSUE THREAD

**Issue by PeterEinberger** [esp8266/Arduino#2486]
pretty straight forward

int HTTPClient::PUT(String payload) {
    return POST((uint8_t *) payload.c_str(), payload.length());
}

should be:

int HTTPClient::PUT(String payload) {
    return PUT((uint8_t *) payload.c_str(), payload.length());
}

**Comment by devyte** [comment]
Closing due to already fixed in latest git.
