### ISSUE TITLE
spi on esp12e

### ISSUE THREAD

**Issue by sarwadenj** [esp8266/Arduino#2492]
I'm using esp12e, GPIO 12,13,14 pins already i have connected to motors using mosfet. And my other Gpio's are also busy in doing another task. 
Now i want to connect SPI bus so what can i do?
as gpio 12,13,14,15 having alternate function for spi and as gpio so how i configure it.

**Comment by WereCatf** [comment]
If you're already using the SPI-pins for your MOSFETs then you can't use them for SPI. Simple as that.
