### ISSUE TITLE
i get this message every time i power my esp.:ets Jan  8 2013,rst cause:2, boot mode:(3,6).Do i have to necessary flash it now or it can be resolved otherwise to ? connections are as follows:  vcc,ch-pd :3.3v,gnd:gnd,rx:pin 3,tx:pin 2.

### ISSUE THREAD

**Issue by rohit765** [esp8266/Arduino#2496]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------
#### Hardware

Hardware:           ?ESP-12?
Core Version:       ?2.1.0-rc2?
### Description

Problem description
### Settings in IDE

Module:             ?Generic ESP8266 Module?
Flash Size:         ?4MB/1MB?
CPU Frequency:      ?80Mhz?
Flash Mode:         ?qio?
Flash Frequency:    ?40Mhz?
Upload Using:             software serial
Reset Method:       ?ck / nodemcu?
### Sketch

``` cpp

#include <SoftwareSerial.h>
SoftwareSerial esp8266(2, 3);
void setup() {
Serial.begin(9600);
  esp8266.begin(74880);
}

void loop() {
 if (esp8266.available())   {
    while (esp8266.available())
    {
         char c = esp8266.read();
      Serial.write(c);
    }
  }



  if (Serial.available())
  {


    delay(1000);

    String command = "";

    while (Serial.available())
    {
      // read one character
      command += (char)Serial.read();
    }
    esp8266.println(command); 
  }
}
```
### Debug Messages

```
messages here
```

**Comment by devyte** [comment]
Not the right place to ask such questions. Closing per #3655 .
