### ISSUE TITLE
Example ESP8266WebServer/examples/HelloServer does not call   WiFi.mode(WIFI_*);

### ISSUE THREAD

**Issue by asmeureanu** [esp8266/Arduino#2516]
Depending on the use case; by not calling  WiFi.mode(WIFI_STA); you create as well an additional AP with the same SSID and password as you original AP that you want to connect to.

This causes issues for the other devices on you wifi network, ranging from disconnect to very bad wifi performance. 

Please adapt the example to point that the user should chose one the mode he needs to use.

**Comment by devyte** [comment]
@asmeureanu no basic info, no IDE settings.
I don't understand the issue here. I can run the example just fine, I have never seen "an additional AP with same SSID and password".
Is the issue still relevant with latest git? if so, please provide a better explanation.

**Comment by devyte** [comment]
The mentioned example already calls WiFi.mode(WIFI_STA). 
Closing.
