### ISSUE TITLE
can't connect to my wifi router anymore!

### ISSUE THREAD

**Issue by mushfiq-cse05-buet** [esp8266/Arduino#2518]
hello everyone, i'm facing a brand new problem that didn't happen to me before, a week ago i have changed my wifi router's settings and after that my esp8266(esp-01) can't connect to my wifi router anymore ??? can anybody tell me whats the problem???

**Comment by WereCatf** [comment]
> can anybody tell me whats the problem???

"I changed stuff, but I'm not telling you what I changed and I just want you to magically know what's wrong." -- Mmmno. How about telling what settings you changed, or reverting your changes?

**Comment by devyte** [comment]
If this issue is still valid, I suggest doing a fill reset of your router, and configuring from scratch.
Not the right place to ask for such help, closing per #3655 .
