### ISSUE TITLE
Real API Doc for ESP8266WebServer 

### ISSUE THREAD

**Issue by xetra11** [esp8266/Arduino#2523]
I wonder if there will be a complete documentation of the API of ESP8266WebServer in the future? Functions like "on" are trivial but should be explained netherless!

**Comment by guatedude2** [comment]
+1

**Comment by devyte** [comment]
@xetra11 you probably already realized this, but right now this is not a priority. There are many examples available, and the object interface is pretty clear.

**Comment by earlephilhower** [comment]
Closing as a dup of #2811
