### ISSUE TITLE
ESP8266 12  automatic wake-up and  external wake-up on deep sleep

### ISSUE THREAD

**Issue by dasarathsbricks** [esp8266/Arduino#2531]
ESP8266 

RST --- connect to GPIO16 with Diode

and using GPIO2 for external wake up 

need pull up from 1K from VCC to GPIO2 
manage GPIO2 to be LOW on Setup

**Comment by middelink** [comment]
And what is the issue (for the Arduino lib) here exactly?

**Comment by dasarathsbricks** [comment]
not related to Arduino lib wrong thread  my Bad :)

**Comment by StuckInLoop** [comment]
dasarathsbricks, are you able to get the external wake up working? if so, can you share on how to get it working? thanks

**Comment by devyte** [comment]
Non-issue, closing.
