### ISSUE TITLE
axTLS 2.0.0 and TLS 1.2 support

### ISSUE THREAD

**Issue by cllu** [esp8266/Arduino#2537]
axTLS 2.0.0 has been released [last month with TLS 1.2 support](http://axtls.sourceforge.net/README/index.html). Any plan to test and upgrade axTLS library? It seems that lots of people are concerned about TLS 1.2 support in issue #43.

**Comment by igrr** [comment]
Updated already in https://github.com/esp8266/Arduino/commit/35ee060c098a1a69ab5b545f54babffb7ada50df.
