### ISSUE TITLE
How do I finish using and dispose of mdns after I used it to resolve addresses

### ISSUE THREAD

**Issue by lorneb** [esp8266/Arduino#2559]
Question Only:

I'm using mDNS to resolve sope ip addresses and ports for two services, once that done it no longer need it.  What would be the best practice for disposing of it?

Thanks

**Comment by WereCatf** [comment]
I dunno if it would be the best practice, but you could call its destructor as `MDNS.~MDNSResponder()` to clean it up, or disable the global MDNSResponder-instance "MDNS" altogether and allocate/deallocate it yourself when needed.

**Comment by devyte** [comment]
@lorneb previous comment is correct: disable the global object, and instantiate your own, either dynamically or scoped.
In any case, this is not the right place to ask such questions. Closing per #3655 .
