### ISSUE TITLE
Which IDE I preferred to write my freeRTOS code for ESP12E. 

### ISSUE THREAD

**Issue by sarwadenj** [esp8266/Arduino#2563]
Hi, 
I seen freeRTOS is supported to ESP 12E. So which IDE i used to write,compile and upload the freeRTOS code into ESP12E.

So please tell me the steps to compile RTOS sdk based program and how to upload the program to the ESP8266? I am very new and familiar with ESP8266 programming in arduino IDE only.
And which IDE i use for writing.

**Comment by sarwadenj** [comment]
Hi,
Anyone have any IDEA about this. Please give me suggestions.

Thanks in advance.

**Comment by a-andreyev** [comment]
take a look [here](https://github.com/espressif/ESP8266_RTOS_SDK) or [there](https://github.com/SuperHouse/esp-open-rtos)

**Comment by devyte** [comment]
Duplicate, closing.
