### ISSUE TITLE
IDE and setup for freeRTOS based code in ESP12E

### ISSUE THREAD

**Issue by sarwadenj** [esp8266/Arduino#2564]
Can anybody tell me the steps to compile RTOS sdk based program and how to upload the program to the ESP12E ? I am very new and familiar with ESP8266 programming in arduino IDE only.
Also somewhere i seen that Arduino IDE is also used to write, compile the freeRTOS based code for ESP12E.

Thanks in advance.

**Comment by sarwadenj** [comment]
Hi,
Anyone have any IDEA about this. Please give me suggestions.

Thanks in advance.

**Comment by rahuldeo2047** [comment]
Can you please link to the 'somewhere' ?

> Also somewhere i seen that Arduino IDE is also used to write, compile the freeRTOS based code for ESP12E.

**Comment by devyte** [comment]
@sarwadenj wrong repo, this is the NON-OS firmware (i.e.: no FreeRTOS).
Closing.
