### ISSUE TITLE
New signatures to ESP8266WebServer::sendContent

### ISSUE THREAD

**Issue by wellrats** [esp8266/Arduino#2567]
Hi all,
Would it be possible in next version of this lib insert another signatures for
ESP8266WebServer::sendContent as follow

```
void ESP8266WebServer::sendContent(const char* content, size_t len);
void ESP8266WebServer::sendContent(const char* content)
```

Useful when parsing a `char*` buffer like a HTML template from a file, and sending little pieces of this buffer to client after parsed. Call `<server_instance>.client().write( ... )` directly is not an option, because final length of parsed buffer is unknown and encoding is `chunked`

Thanks in advance

The implementation.

```
void ESP8266WebServer::sendContent(const char* content, size_t len) {
  const char * footer = "\r\n";
  if(_chunked) {
    char * chunkSize = (char *)malloc(11);
    if(chunkSize){
      sprintf(chunkSize, "%x%s", len, footer);
      _currentClient.write(chunkSize, strlen(chunkSize));
      free(chunkSize);
    }
  }
  _currentClient.write(content, len);
  if(_chunked){
    _currentClient.write(footer, 2);
  }
}

void ESP8266WebServer::sendContent(const char* content) {
  sendContent(content, strlen(content));
}

void ESP8266WebServer::sendContent(const String& content) {
  sendContent(content.c_str(), content.length());
}
```

**Comment by luc-github** [comment]
Actually you do not need to specify size when sending if you use `setContentLength(CONTENT_LENGTH_UNKNOWN);` you just need to finish your sending by `sendContent("");`

you can see how it can be used with template on my project : https://github.com/luc-github/ESP3D/blob/master/esp3d/webinterface.cpp#L214-L394

one send part is here FYR: https://github.com/luc-github/ESP3D/blob/master/esp3d/webinterface.cpp#L379-L392

**Comment by wellrats** [comment]
I understand that.

I just think it's not necessary duplicate my big ```char *``` buffer, turning it into a ```String``` to call ```sendContent```.

**Comment by luc-github** [comment]
Sorry I misunderstood the question - but I would say why duplicate ? why not use `String` only instead of big `char *` buffer, this is what I do reading template files and processing them

**Comment by wellrats** [comment]
OK. no problem.
The point is, more signatures means more flexibility.
The code posted above is working to ```String``` and ```char*```

Just a suggestion.

**Comment by devyte** [comment]
@wellrats could you please make a PR with your suggestion?
