### ISSUE TITLE
How can I use NTC thermistor to read the temp?

### ISSUE THREAD

**Issue by youdemo** [esp8266/Arduino#2573]
Hello,
The wiring is essentially
+3.3v ------ 10k resistor ------ (A)------ NTC 100k thermistor ------- GND
The board is ESP8266 12F,With point (A) connected to the ADC pin.

How can I use NTC thermistor to read the temp?
thanks
Lee

**Comment by yagizhanugur** [comment]
Hello,

You can read that article

http://esp8266tutorials.blogspot.com.tr/2016/09/esp8266-ntc-temperature-thermistor.html

Thanks.

**Comment by devyte** [comment]
Not the right place to ask such questions. Closing per #3655 .
