### ISSUE TITLE
How to completely erase SPIFFS contents?

### ISSUE THREAD

**Issue by helpme1** [esp8266/Arduino#2580]
I am using SPIFFS to store configuration settings using this example https://github.com/esp8266/Arduino/blob/master/libraries/esp8266/examples/ConfigFile/ConfigFile.ino

I am using NodeMCU board. What command should I use for esptool.exe to erase and empty the SPIFFS?

**Comment by devyte** [comment]
@helpme1 SPIFFS.format()
Please see documentation on readthedocs.
Closing due to documented feature.
