### ISSUE TITLE
verifyCertChain(const char* domain_name)

### ISSUE THREAD

**Issue by supersjimmie** [esp8266/Arduino#2586]
I see that @igrr created https://github.com/esp8266/Arduino/commit/b41266097fe6d39d0021c29bb09fdbb69c7d5df4
That added `bool verifyCertChain(const char* domain_name);`
But how do I use it? If I use this, the manual httpsFingerprint is no longer needed?
There is no example or explanation on this change.

**Comment by salqadri** [comment]
Really looking forward to an example please. I'm unable to get it to work.

**Comment by devyte** [comment]
@supersjimmie a quick google found [this](http://www.esp8266.com/viewtopic.php?f=32&t=14301).
Please discuss at a forum, this is an issue tracker. Closing per #3655 .
