### ISSUE TITLE
ESP.reset() does not affect millis() counter

### ISSUE THREAD

**Issue by thomasfla** [esp8266/Arduino#259]
Hi, ESP.reset() does not affect millis() counter like a material reset do,
might not be very important but for me this isn't a normal behavior

>``millis and micros return the number of milliseconds and microseconds elapsed after reset, respectively.``

**Comment by Links2004** [comment]
is I still a problem in the last version?

**Comment by GanjaFarmer** [comment]
Yes, still a problem, and same thing with ESP.restart(). I noticed this when doing debouncing code for a push button that calls ESP.reset() or ESP.restart() when pressed for a few seconds. The button code works once, then after the ESP was automatically reset, the button code doesn't work anymore.
