### ISSUE TITLE
dead code in spiffs_api.h

### ISSUE THREAD

**Issue by everslick** [esp8266/Arduino#2597]
actually not dead, but redundant.

```
bool seek(uint32_t pos, SeekMode mode) override
{
    CHECKFD();

    int32_t offset = static_cast<int32_t>(pos);
    if (mode == SeekEnd) {
        offset = -offset;
    }
    auto rc = SPIFFS_lseek(_fs->getFs(), _fd, pos, (int) mode);
    if (rc < 0) {
        DEBUGV("SPIFFS_lseek rc=%d\r\n", rc);
        return false;
    }

    return true;
}
```

int32_t offset is calculated but not used afterwards. maybe the idea was to use offset instead of pos in lseek?

**Comment by devyte** [comment]
This issue looks like a bug to me, and is still present in latest git. Probably a typo:
`        auto rc = SPIFFS_lseek(_fs->getFs(), _fd, pos, (int) mode);
`
should read:
`        auto rc = SPIFFS_lseek(_fs->getFs(), _fd, offset, (int) mode);
`

**Comment by devyte** [comment]
@everslick please try #4287 .
