### ISSUE TITLE
OTA example correction 

### ISSUE THREAD

**Issue by valerio-vaccaro** [esp8266/Arduino#2599]
Hello all,
   can you please provide  a simple correction on page 
http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota_updates.html ?

In the example PHP script on line 
    if($db[$_SERVER['HTTP_X_ESP8266_STA_MAC']] != $_SERVER['HTTP_X_ESP8266_VERSION']) ) 
last char ) has to be removed in order to have a valid instruction!

Thanks in advance!

**Comment by WereCatf** [comment]
The ESP8266-core is at version 2.3.0 already, your 2.0.0 is way outdated.
