### ISSUE TITLE
time to connect wifi with static ip

### ISSUE THREAD

**Issue by chaeplin** [esp8266/Arduino#261]
I have tested a simple sketch.

https://gist.github.com/chaeplin/190ba7175d1e8098a629

time to connect wifi with static ip
---> power on : 2.018 sec
---> reset with deepsleep : 1.109 sec

Is there a way to set a channel(skip scanning) ?

**Comment by chaeplin** [comment]
#include <ESP8266WiFi.h>
extern "C"{
#include "user_interface.h"
}

~~~~

  WiFi.begin(ssid, password);
  wifi_set_channel(7);

**Comment by Tareq-Sulaiman** [comment]
The best I could achieve is 1.45 seconds.
You need to add the channel and the bssid(MAC address of the AP), and of course a static IP address.
