### ISSUE TITLE
HttpClient put issue

### ISSUE THREAD

**Issue by arcanon** [esp8266/Arduino#2615]
simple code issue:

int HTTPClient::PUT(String payload) {
    return **POST**((uint8_t *) payload.c_str(), payload.length());
}

should be

int HTTPClient::PUT(String payload) {
    return **PUT**((uint8_t *) payload.c_str(), payload.length());
}

**Comment by devyte** [comment]
@arcanon this seems to no longer apply, I don't see the mentioned code in current git (i.e.: it's already fixed).
Closing.
