### ISSUE TITLE
Current board version does not recognize ARDUINO_ESP8266_ESP12

### ISSUE THREAD

**Issue by RogerSchaefer** [esp8266/Arduino#2616]
#### Hardware
Hardware:			ESP-12
Core Version:      	2.3.0
### Description
In core version 2.1.0 the following code yielded the desired result for an ESP-12
#ifdef ARDUINO_ESP8266_ESP01
  Serial.println("it is an ESP-01");
  #elif ARDUINO_ESP8266_ESP12           // only works with board version 2.1.0
  Serial.println("it is an ESP-12");
  #elif ARDUINO_ESP8266_ESP210
  Serial.println("it is an ESP-210");
  #endif
In later core versions it no longer gives result for ESP-12 but does for ESP-01.
Is there an alternative?
### Settings in IDE

Module:  			NodeMCU V1
Roger Schaefer

**Comment by WereCatf** [comment]
Look for build.board - field in boards.txt -- Nodemcu defines it as ARDUINO_ESP8266_NODEMCU, for example.
