### ISSUE TITLE
Big problem NODEMCU ENDED SUPPORT

### ISSUE THREAD

**Issue by asetyde** [esp8266/Arduino#2622]
![img_0707](https://cloud.githubusercontent.com/assets/6162152/19521503/2f779a54-9614-11e6-9183-b5e85586b14b.PNG)

**Comment by asetyde** [comment]
This is big problem for me .. this affect also this project ? Hope no

**Comment by WereCatf** [comment]
The Arduino-core for ESP8266 isn't made by the Nodemcu-team, it has literally zero effect on this project.

**Comment by asetyde** [comment]
Nodemcu is good board , use only chip 8266 is so limited
