### ISSUE TITLE
Serial.print not working after ArduinoOTA.begin() for ESP-01

### ISSUE THREAD

**Issue by RogerSchaefer** [esp8266/Arduino#2629]
#### Hardware

Hardware:           ESP-01
Core Version:       2.3.0
### Description

When using a slightly modified OTA example there is no Serial Print after ArduinoOTA.begin(); when using ESP-01.  Serial output is normal when using a NodeMCU module.
### Settings in IDE

Module:             Generic ESP8266 Module
Flash Size:         1MB
CPU Frequency:      ?80Mhz?
Flash Mode:         ?qio?
Flash Frequency:    ?40Mhz?
Upload Using:       either
Reset Method:       ?ck / nodemcu?
### Sketch

 ArduinoOTA.begin();   //  No Serial Print after this point ESP-01
  Serial.begin(9600);     //  This doesn't help 
  Serial.println("OTA Ready");  //  Everything from this point prints with NodeMCU not ESP-01
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
  String psk = WiFi.psk();
  String ssid = WiFi.SSID();
  Serial.print("The SSID of WiFi is ");
  Serial.println(ssid);
  Serial.print("with a password of ");
  Serial.println(psk);

**Comment by devyte** [comment]
@RogerSchaefer is this issue still valid? Have you tested with latest git? Please report back here.
