### ISSUE TITLE
Question: How to make POST call to Slack Webhooks ?

### ISSUE THREAD

**Issue by YHSX88** [esp8266/Arduino#2631]
#### Hardware

Hardware:   ESP-01
### Description

I wanted to use Slack as notification system so when something is happening esp8266-01 to send me message in Slack with some status string.

Can you please help me by pointing me all I need to do in order to make POST calls to the slack webhooks.  https://api.slack.com/incoming-webhooks

I'm using latest version of the library. How I can do this what libraries to use.

Thank you in advance.

**Comment by devyte** [comment]
@YHSX88 this is not the right place to request help for your particular project. Closing per #3655 .
