### ISSUE TITLE
Add SPIFFS.check()  to implement checking capabilities.

### ISSUE THREAD

**Issue by miky2k** [esp8266/Arduino#2634]
In sensors log with casual power loss may happen that file-system stop working (especially remove()),
there is a check implementation in SPIFFS library that  should  exposed in Arduino.

**Comment by ABH10** [comment]
I would appreciate this enhancement very much. Once in a while SPIFFS seems to mess up for no obvious reason. Currently an SPIFFS.format() is the only cure.
