### ISSUE TITLE
HTTP Body recognition in adafruit huzzah

### ISSUE THREAD

**Issue by giv86** [esp8266/Arduino#2637]
Hello lads, I've been looking for over two days good tutorial showing how to read POST sended to ESP8266 from other software. 

Right now I can undestand GET and send answer to host, but still can;t recognize POST and perform suitable actions.

I would be most gratefull for any good tutorials.

**Comment by devyte** [comment]
@giv86 No basic info, no IDE settings, no sketch.
The FSBrowser examples in the repo shows how to do this. 
Closing.
