### ISSUE TITLE
Short Pulse in Input GPIO when reset Occurs

### ISSUE THREAD

**Issue by cyguevara** [esp8266/Arduino#2645]
Hardware:           ESP-12F
Core Version:       2.3.0

I use a GPIO send a signal to the ESP8266, I configure the port as Input (No Pull_UP), and after sending some data to a server it goes to deep sleep, and the system wakes up every 30 seconds automatically, and repeat the process.

Problem description
Every time the system starts again or wakes up the input GPIO generates a short positive pulse. How can I avoid this pulse?
### Settings in IDE

Module:             Generic ESP8266 Module
Flash Size:         4MB
CPU Frequency:  80Mhz
Flash Mode:         ?qio?
Flash Frequency:    40Mhz?
Upload Using:        SERIAL
Reset Method:

**Comment by jrobeson** [comment]
you didn't mention which pin you used.

**Comment by RudyFiero** [comment]
Most of the pins are started with pull up resistors, or have some activity. The only ones that don't are D4 and D5. All of this happens in the bootloader code (Expressif)  and has nothing to do with the ESP-Arduino code. It sucks but it is just something we have to live with.

**Comment by devyte** [comment]
@cyguevara this is normal, and it can't be avoided because it's in the Espressif SDK and not in the Arduino core.
Closing.
