### ISSUE TITLE
Example OTA code always denies password

### ISSUE THREAD

**Issue by Thijxx** [esp8266/Arduino#2654]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			ESP-12
Core Version:      	dont know

### Description

OTA Example copy/paste fails. Board connects, has IP, accepts connection but denies password. Password is 123 and I have tried it many times. Reflashed code many times. Disabling the password results in `22:05:30 [ERROR]: No response from device`

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		512K
CPU Frequency:		80Mhz
Flash Mode:			DIO
Flash Frequency:	40Mhz
Upload Using:		using SERIAL, trying OTA
Reset Method:		power cycle

### Sketch

```#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiUdp.h>
#include <ArduinoOTA.h>

const char* ssid = "mynetwork";
const char* password = "password";

void setup() {
  Serial.begin(115200);
  Serial.println("Booting");
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  while (WiFi.waitForConnectResult() != WL_CONNECTED) {
    Serial.println("Connection Failed! Rebooting...");
    delay(5000);
    ESP.restart();
  }

  // Port defaults to 8266
  // ArduinoOTA.setPort(8266);

  // Hostname defaults to esp8266-[ChipID]
  // ArduinoOTA.setHostname("myesp8266");

  // No authentication by default
  // ArduinoOTA.setPassword((const char *)"123");

  ArduinoOTA.onStart([]() {
    Serial.println("Start");
  });
  ArduinoOTA.onEnd([]() {
    Serial.println("\nEnd");
  });
  ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
    Serial.printf("Progress: %u%%\r", (progress / (total / 100)));
  });
  ArduinoOTA.onError([](ota_error_t error) {
    Serial.printf("Error[%u]: ", error);
    if (error == OTA_AUTH_ERROR) Serial.println("Auth Failed");
    else if (error == OTA_BEGIN_ERROR) Serial.println("Begin Failed");
    else if (error == OTA_CONNECT_ERROR) Serial.println("Connect Failed");
    else if (error == OTA_RECEIVE_ERROR) Serial.println("Receive Failed");
    else if (error == OTA_END_ERROR) Serial.println("End Failed");
  });
  ArduinoOTA.begin();
  Serial.println("Ready");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
}

void loop() {
  ArduinoOTA.handle();
}
```

### Debug Messages
Unable to open serial monitor
```
Unable to connect: wrong password?
OR 22:05:30 [ERROR]: No response from device
```

**Comment by gerab** [comment]
Same msg:
Unable to connect: wrong password?

Any advice?

**Comment by kvoit** [comment]
Second that, same problem.

**Comment by suculent** [comment]
I have same issue. Don't see any error in the example code, though.

**Comment by duncan-a** [comment]
Same for me too...

**Comment by suculent** [comment]
Well, this is apparently a bug as besides the Serial monitor I was able to do the OTA Update through both own server and platform.io IDE. 

It's worth fetching latest Arduino repository as ArduinoOTA lib is outdated in some bundles. 

Odesláno z iPhonu

26. 3. 2017 v 21:34, duncan-a <notifications@github.com>:

> Same for me too...
>

**Comment by gerab** [comment]
as i did understand from ide docs ota debug via serial has not been implemented yet on esp

**Comment by devyte** [comment]
@Thijxx is this issue still valid with latest git? I'm not aware of a password problem with OTA.
Please test and report back here.

**Comment by Thijxx** [comment]
The solution, for me, was a firewall setting.

The OTA updates creates a connection between the local computer and the ESP, for this a local service is started from a Python script. This service uses some obscure port that needs to be opened in the firewall for bi-lateral traffic (incoming & outgoing).

It would be nice if the Arduino IDE reported the port number and a message about opening the port. Please do not advice people to turn off the firewall :D

**Comment by devyte** [comment]
Glad it's resolved. Closing.

**Comment by suculent** [comment]
I just want to confirm that it works, as it failed to me as well before latest update.

**Comment by Roycinger** [comment]
> The solution, for me, was a firewall setting.
> 
> The OTA updates creates a connection between the local computer and the ESP, for this a local service is started from a Python script. This service uses some obscure port that needs to be opened in the firewall for bi-lateral traffic (incoming & outgoing).
> 
> It would be nice if the Arduino IDE reported the port number and a message about opening the port. Please do not advice people to turn off the firewall :D

Would be nice if you'd add the actual ports that need to be opened

**Comment by kvoit** [comment]
> Would be nice if you'd add the actual ports that need to be opened

The PlatformIO documentation says that the port is random. `--host_port=...` is supported as an upload flag, though.
No idea how this is done in the Arduino IDE, haven't used that in ages.

**Comment by d-a-v** [comment]
Arduino IDE: port is 8266  (check sketch in OP)

**Comment by kvoit** [comment]
> Arduino IDE: port is 8266 (check sketch in OP)

That is the port the ESP is listening on. However, there is also a port on the host computer involved, that the ESP needs to be able to access. That one is random at least for PlatformIO.
