### ISSUE TITLE
Can not download esp8266 board manager url (again)

### ISSUE THREAD

**Issue by davolesh** [esp8266/Arduino#2664]
Similar to Issue https://github.com/esp8266/Arduino/issues/1689

![error](https://cloud.githubusercontent.com/assets/10506816/20034637/c23f6ef0-a39a-11e6-9ba3-fbccd32f01cd.png)

When manually downloading both from domain and Ip:

![error 2](https://cloud.githubusercontent.com/assets/10506816/20034641/040a6a56-a39b-11e6-9d98-3137bba248da.png)

I tried from multiple networks, including cellular and same issue reoccurs. Any help would be highly appreciated, thanks!

**Comment by hashin** [comment]
I am getting this issue again. Any possible reason? @igrr 

Please update @davolesh

**Comment by davolesh** [comment]
I figured out the issue for me. I have OpenDNS on my network. So I got the free version of TunnelBear and once i got that running the setup went through flawlessly! It must have been a DNS issue. Give it a shot. Either disable any DNS or try a VPN.

**Comment by davolesh** [comment]
Let me know if this works for you and if I can close the issue.

**Comment by hashin** [comment]
Working for me now. You can close the issue. :+1:
