### ISSUE TITLE
FeatureRequest: Add PATCH Request to HTTP Client 

### ISSUE THREAD

**Issue by Heizelmann** [esp8266/Arduino#2670]

**Comment by devyte** [comment]
@Heizelmann does PR #2413 address your needs?

**Comment by Heizelmann** [comment]
Thanks a lot! At a glance it looks good. Currently I have no time to test it. I will do it as soon as possible.

**Comment by Heizelmann** [comment]
Sorry for double posting. I will continue on #2830.

**Comment by earlephilhower** [comment]
This was moved to another bug, which is already closed for years.
