### ISSUE TITLE
Basic example for modified ethernet.h

### ISSUE THREAD

**Issue by FernandoGarcia** [esp8266/Arduino#2671]
Hi !

Is possible give us a working basic example for this modified ethernet.h library?
The default examples available here doesn't work without changes.
https://github.com/esp8266/Arduino/tree/master/libraries/Ethernet/examples
Best regards.

**Comment by Humancell** [comment]
Also ... is there a clear document or diff that can show exactly what was changed in this version of the lib to work with the ESP?

I'm wanting to use both the W5100, and the better/faster W5500 for Ethernet, and so I want to update this support to support both ... but I'm hoping I don't have to start from scratch and guess?

**Comment by neu-rah** [comment]
no docs yet, v3 (dev branch ) was a rewrite, and not just because of esp8266, so a lot has changed from 2.x.. the good news it's that i'm already started from scratch :D

**Comment by Humancell** [comment]
Curious if anyone has any experience using this with the W5500?  I'm digging in to see if I can get it working, but was curious if anyone knows the pitfalls I might run into?

**Comment by devyte** [comment]
@Humancell did you make any progress? if so, you may want to open a new issue as a feature request, and make a PR.

**Comment by devyte** [comment]
@FernandoGarcia There are examples provided together with the lib.
Closing.

**Comment by FernandoGarcia** [comment]
You should check my issue firts!
As I told the examples doesn't work.

https://github.com/esp8266/Arduino/tree/master/libraries/Ethernet/examples

**Comment by devyte** [comment]
@FernandoGarcia sorry, I took your post to mean you were requesting examples.
You're sayying the current examples don't work with the 510?

**Comment by FernandoGarcia** [comment]
Look for examples and tell me where to put SSID and password at least. It was just a copy and paste from Arduino IDE

**Comment by d-a-v** [comment]
@Humancell since you have W5100 (which I don't have),
can you try https://github.com/d-a-v/W5500lwIP with both W5100 and W5500 ?
