### ISSUE TITLE
GETTING A LIST OF CONNECTED CLIENTS

### ISSUE THREAD

**Issue by sergiom968** [esp8266/Arduino#2681]
How I can get a list of devices connected to my esp8266 in Access Point mode, with MAC address and IP address?

**Comment by leonyuhanov** [comment]
I use this:

```
struct station_info *stat_info;
struct ip_addr *IPaddress;
IPAddress address;

void dumpClients()
{
  Serial.print(" Clients:\r\n");
  stat_info = wifi_softap_get_station_info();
  while (stat_info != NULL)
  {
    IPaddress = &stat_info->ip;
    address = IPaddress->addr;
    Serial.print("\t");
    Serial.print(address);
    Serial.print("\r\n");
    stat_info = STAILQ_NEXT(stat_info, next);
  } 
}
```

**Comment by sergiom968** [comment]
Thank you so much

**Comment by leonyuhanov** [comment]
@sergiom968 You should close this ticket if its solved

**Comment by mkeyno** [comment]
@leonyuhanov  what header file should be inculcated to avoid scope error  
`error: 'wifi_softap_get_station_info' was not declared in this scope`

**Comment by leonyuhanov** [comment]
put this at the top:
```
extern "C" { 
#include<user_interface.h>
}
```

**Comment by franciscogimeno2000** [comment]
error: invalid conversion from 'ip4_addr*' to 'ip_addr*' [-fpermissive]
IPaddress = &stat_info->ip

Hi, when compiling, I get this error, someone knows
why?

Thank you

**Comment by phisp** [comment]
It cannot convert from the "ip4_addr" type to the "ip_addr" type. There is no conversion function defined.
I resolved the problem with:
`ipv4_addr *IPaddress = &stat_info->ip;`
`address = IPaddress->addr;`
