### ISSUE TITLE
OTA TCP transfer fails

### ISSUE THREAD

**Issue by readmodifywrite** [esp8266/Arduino#2689]
With ESP-12F, core 2.3.0, BasicOTA example.

The mDNS discovery and TCP connection work fine, but then the TCP connection breaks.  See attached Wireshark capture.

The error status I get is OTA_END_ERROR.

The actual wifi connection is fine, and I can stream UDP all day with no issues.  OTA is the only thing I use TCP for, so I do not know if there is a problem with the OTA code or in lwip.

<img width="1363" alt="screen shot 2016-11-14 at 4 00 47 pm" src="https://cloud.githubusercontent.com/assets/3618507/20287801/9a70539a-aa83-11e6-99d0-8eb4b5fcfa66.png">

**Comment by devyte** [comment]
@readmodifywrite is this issue still valid in latest git?

**Comment by readmodifywrite** [comment]
Sorry, no idea. I ended up designing my own OTA system.  Feel free to close if no one else is having an issue.
