### ISSUE TITLE
docs: staging version is currently behind stable

### ISSUE THREAD

**Issue by karlp** [esp8266/Arduino#2691]
#### Hardware
Hardware:			N/A
Core Version: master

### Description

The readme.md refers to "stable" v2.3.0, and also a "staging" version, http://arduino.esp8266.com/versions/2.3.0-rc2/package_esp8266com_index.json  The most recent release in "staging" is 2.3.0-rc2, which is behind stable.  

See https://github.com/esp8266/Arduino/blob/master/README.md#staging-version-

### Settings in IDE

N/A

### Sketch

N/A
### Debug Messages

N/A

**Comment by igrr** [comment]
If you scroll the file down a bit, you'll find 2.3.0-rc2 in there.

**Comment by karlp** [comment]
Ok, yes, the staging json file lists multiple packages.  I've edited the description.  The main point that "staging" is currently behind the stable release still stands.

**Comment by devyte** [comment]
@igrr I have no idea how to check this, or how to tell what the current status is for latest git/2.4-rc1 etc. Could you please provide guidance? Can this be closed?

**Comment by igrr** [comment]
Yes, this can be closed. "Staging" links have been removed, and current pre-release version (2.4.0-rc1) is ahead of the stable one.
