### ISSUE TITLE
feature req: arduino ota

### ISSUE THREAD

**Issue by ramarro123** [esp8266/Arduino#2696]
it's possible or someone can give me some hinte about the ability of update firmware with an esp connected via serial on an arduino mega?

downloading the hex it's the easy part :) but I presume it doesn't have to be just sent raw to serial but following the stk500 protocol?

someone is aware of something like that?

**Comment by devyte** [comment]
@ramarro123 there is the ESPAVRISP example, which should serve as guideline, or starting point in case it needs to be adapted for your purpose.
Closing as off-topic, see #3655 .
