### ISSUE TITLE
Active tcp closing socket

### ISSUE THREAD

**Issue by akaJes** [esp8266/Arduino#2700]
how can I send from ESP(as server) active closing command (to client)? because stop() not working
as described https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Connection_termination
![](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Tcp_state_diagram_fixed_new.svg/1084px-Tcp_state_diagram_fixed_new.svg.png)

code similar to #1365
I dont know content length - because it huge auto zipped file
tcpdump says that connection interrupted by browser in 2 seconds after last packet was acknowledged

**Comment by akaJes** [comment]
after code digging I have one question "why You destroy tcp_pcb after sending `tcp_close()`?"
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi/src/include#L69-L89
after `tcp_close()` socket(pcb) sends FIN_WAIT_1 and must wait acknowledge from another side for proper closing and cleanup it after some timeout
like it is doing `espconn` interface

**Comment by devyte** [comment]
@akaJes is this issue still relevant in latest git? If so, please provide a MCVE sketch, as well as any relevant additional details.

**Comment by devyte** [comment]
Closing due to no feedback in almost 2 months, and due to age.
