### ISSUE TITLE
transparent serial forward

### ISSUE THREAD

**Issue by ramarro123** [esp8266/Arduino#2709]
Hi,

looking at 
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/WiFiTelnetToSerial/WiFiTelnetToSerial.ino

i have try to use avrdude to upload a sketch on the chained arduino connected on serial.

i got some results, the arduino get correctly idenfitied, and some command pass, but  i got some timeout as well, that break the comunication.

i have try to write byte by byte, results are better, but still got some timeout that prevent the upload

someone can point me into the right direction for that?

i have already remove the "delay(1)" from the code, with or without it doesn't make much difference

**Comment by penfold42** [comment]
This doesn't address your question but might be an alternative:
https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266AVRISP

**Comment by ramarro123** [comment]
umm, i have an 01 module, i don't see spi pin header, but i can be wrong on that

**Comment by devyte** [comment]
@ramarro123 did you get this working?
ESP8266AVRISP should serve as a guideline, don't take it literally. In other words, I think it should work, as long as you adapt it to your case (e.g.: change the pins, adapt voltage, etc).
Having said that, this is not the right place to ask for assistance. Closing as non-issue, see #3655 .
