### ISSUE TITLE
Serial.available() and Serial.read() issue

### ISSUE THREAD

**Issue by TThanhXuan** [esp8266/Arduino#2710]
Hi everyone, I'm trying to use ESP8266 to read a string from keyboard and then print to Serial monitor. This is the code:
void setup() {
 Serial.begin(9600);
}

void loop() {
 if (Serial.available()>0) {
  String r = Serial.readStringUntil('\r');
  Serial.print("r: ");
  Serial.println(r);
 }
}

There is nothing happen when I run the code, nothing on Serial monitor.

Could you please help me with this issue ?
Thank you very much.

**Comment by tablatronix** [comment]
Are you sure your client is sending \r, try using \n

**Comment by devyte** [comment]
@TThanhXuan I suggest testing by reading and echoing char by char instead of reading until '\r'. Also, should that really be '\r' or 'n'?
In any case, this is not the right place to ask for assistance. Closing, see #3655 .
