### ISSUE TITLE
Master: Can't create a ssl/tls connection to p2TestHub.azure-devices.net or https://httpbin.org/ using WiFiClientSecure

### ISSUE THREAD

**Issue by tdesmet** [esp8266/Arduino#2711]
#### Hardware
Hardware:			ESP-12E
Core Version:      	Master

### Description

Can't create a ssl/tls connection to p2TestHub.azure-devices.net or https://httpbin.org/ using WiFiClientSecure.
With version 2.3.0 I could create a ssl/tls connection to azure iot hub (p2TestHub.azure-devices.net) But after installing master from github the same code won't connect anymore.

I also tried to connect to google.com and that works. 

The only differences between the azure and httpbin server and google that I can find is that google uses EC 256 bits for the certificate key and azure and httpbin use RSA 2048 bits (e 65537).

The reason I am using master is that I wanted to use the ca certificate verification instead of using a certificate thumbprint.

### Settings in IDE

Module:  			NodeMCU 1.0
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		 SERIAL
Reset Method:		?ck / nodemcu?

**Comment by igrr** [comment]
Same root cause as #3340
