### ISSUE TITLE
"package_esp8266com_index.json" points to missing file on OSX

### ISSUE THREAD

**Issue by andySigler** [esp8266/Arduino#272]
The .json file for the Board Manager [here](http://arduino.esp8266.com/package_esp8266com_index.json) points my system to [this file](http://arduino.esp8266.com/osx-xtensa-lx106-elf-gb404fb9.tar.gz), which doesn't seem to exist.

**Comment by igrr** [comment]
Can you please try again? This link seems to work now.

**Comment by UweGruenefeld** [comment]
The file is currently not accessible.
