### ISSUE TITLE
Arduino 'optimistic_yield' was not declared in this scope

### ISSUE THREAD

**Issue by jinsungga** [esp8266/Arduino#2727]
Hi guys I'm programming Gyro sensor and acceleration sensor  with Arduino

but when I compile, the problem is showed as arduino-1.6.13\libraries\Wire\Wire.cpp:172:24: error: 'optimistic_yield' was not declared in this scope..

  optimistic_yield(1000);

so I dunno how to change to succeed in compiling ..

thank you so much !

**Comment by devyte** [comment]
@jinsungga Is this issue still valid in latest git? I'm not aware of any compilation issues.

**Comment by devyte** [comment]
Closing as can't reproduce, and lack of feedback.
