### ISSUE TITLE
OTA can be disabled ?

### ISSUE THREAD

**Issue by asetyde** [esp8266/Arduino#2753]
Hi i want use OTA but i want to switch off after 5 minutes ... it can be done ? How ?

many thanks

**Comment by SpaceTeddy** [comment]
you could deactivate the .handle() function with an own software timer.

**Comment by asetyde** [comment]
i try it but ota device it still active

**Comment by asetyde** [comment]
yes it can be activated after , out of setup , therefore at the end Ota is disabled . safe control
