### ISSUE TITLE
Problem with packet install

### ISSUE THREAD

**Issue by WoodsterDK** [esp8266/Arduino#276]
Hi there,
the packet install in arduino has a problem downloading the esptool for windows...

**Comment by igrr** [comment]
Can you please provide more context? Operating system, exact error messages, anything else that will help me help you solve this problem?

**Comment by WoodsterDK** [comment]
Yes of course...
Win7 64bit - arduino 1.6.4
I press, boards -> Boards manager -> scroll down to "esp8266 by esp8266 community" and press install.
It begins downloading, but stops and says "error downloading https://github.com/igrr/esptool-ck/releases/download/0.4.4/esptool-0.4.4-win32.zip"....

Strange thing is that I can manually download the file using a browser....

**Comment by igrr** [comment]
Strange indeed. Perhaps some files were only partially downloaded.
Can you please try deleting the archives found in ```%APPDATA%\Arduino15\staging\packages\``` and install again?

**Comment by WoodsterDK** [comment]
The "esp8266-1.6.4-628-g545ffde.zip" is created and downloaded, but "esptool-0.4.4-win32.zip" only gets created, but with the size of 0, and then the installer fails.

**Comment by igrr** [comment]
What happens if you download the file using the browser into this folder, and try installing the board again?

**Comment by WoodsterDK** [comment]
It actually begins downloading the xtensa toolkit... so it seems to be progressing...It takes a while... I will be back... ;)

**Comment by WoodsterDK** [comment]
The installation completes, and the board can be selected.
So the actual installation works - only the error with the esptool....

**Comment by igrr** [comment]
Can you post the full error message? Does it happen when you verify the sketch or when you upload it?

**Comment by WoodsterDK** [comment]
Sorry - it works now. The package has been installed, and everything seems to be working.
I was just referring to the fact, that the actual package install is broken.
If I manually copy the "esptool-0.4.4-win32.zip" into the %APPDATA%\Arduino15\staging\packages\ folder, and run the package install, then the installation completes.

**Comment by igrr** [comment]
Okay, got it. Other users have reported successful installs on Windows so I don't know what to make of it. Perhaps running arduino_debug.exe can help (it shows some error messages on the command line).

**Comment by WoodsterDK** [comment]
OK - I might make a fresh install later on, let's see how that goes....
Thanks for your help.
Have a nice day.

**Comment by PaulyLarry** [comment]
I encountered the same problem, on two separate machines, running win 7 64 bit OS.  The third machine I installed it on win 7 32 bit OS installed fine.  I also installed it on win xp sp3 and that was ok.  Any thoughts?

![new bitmap image](https://cloud.githubusercontent.com/assets/20424249/16775892/d4fa53ea-4830-11e6-8019-7ddd6715ece7.jpg)
