### ISSUE TITLE
Problem with WIFI WPA personal TKIP again

### ISSUE THREAD

**Issue by sixbacon** [esp8266/Arduino#2760]
#### Hardware  
Hardware:		nodeMCU v1.0	
Core Version:      	2.3.0

### Description

Will not connect the wireless router

### Settings in IDE

Module:  			nodeMCU 12E v1.0
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			?qio?
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		nodemcu

I have had the same problem as in issue 2038, same error reports, when loading the sketches with version 2.3.0. either as nodeMCU 1.0 or generic ESP8266. The example programs would not connect to a Netgear DG834G - an old one - but would connect to various other wireless routers. The wifi scan program does work.

I too rolled back to version 2.0.0 and the sketches worked. I have various ESP12E and ESP01 units working, which I developed on this earlier version and never had any problems. 

If there is anything I can do to illuminate the problem let me know, but I suspect it will only affect a few people.

Thanks for all your efforts is developing this software.

**Comment by devyte** [comment]
@sixbacon is this issue still valid with latest git? There is also PR #3215 to test out, which has the latest sdk.
Please report back here.

**Comment by sixbacon** [comment]
Unfortunately I had to redo my network and replace the router since I notified the issue. I now have no issues, but the router has changed.
