### ISSUE TITLE
ESP8266 Wroom-02

### ISSUE THREAD

**Issue by anoirnasr** [esp8266/Arduino#2761]
i m using the ESP8266 Wroom-02 ,
i have a problem in using th pin GPIO15 both downloading firmware and after for PWM .in the first case is work fine but for the second case must be attached forevere to GND and then gives me an errore " wdt reset"

ets Jan 8 2013,rst cause:4, boot mode:(3,7)
wdt reset
ets_main.c
for this chip hi is presented 4 channel PWM R=GPIO12,B=GPIO13,G=GPIO15,W=GPO04 my problem for this channel hi is G=GPIO15 because he must work at the two ways but when i tray to attack him to the color G then give an error "wdt reset" thank you in advance can you help me and fixe this error

**Comment by devyte** [comment]
@anoirnasr no sketch, no basic info, no IDE settings.
GPIO15 has special requirements for its state on bootup. Please research GPIO15/GPIO0/GPIO2 on boot.
This is not the right place to request assistance. Closing due to lack of info, and off-topic, see #3655 .
