### ISSUE TITLE
fatal error: MSpanList_Insert

### ISSUE THREAD

**Issue by kiralikbeyin** [esp8266/Arduino#2762]
#### Hardware
Hardware:			LOLIN NODEMCUV3
Core Version:      	LATEST GİTHUB SİNCE NOVEMBER 2016 AND ALSO RC-2.3
 

### Sketch

SAME SKETCH CAN COMPILE WITH 1.6.13 IDE INSTALLED 1.6.8 AVR LIB
PROBLEM WITH 1.6.8 IDE AND 1.6.8 AVR LIB
 
failed MSpanList_Insert 0x30bd68 0x248d5ff3172c 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x2c6c90, 0x30bd68)
	/usr/local/go/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Free(0x2c6c20, 0x30bd68, 0x0)
	/usr/local/go/src/runtime/mheap.c:500 +0x5b
runtime.MCentral_FreeSpan(0x2d0138, 0x30bd68, 0x3, 0xc208270000, 0xc208271400, 0x10600, 0x64)
	/usr/local/go/src/runtime/mcentral.c:181 +0x1bb
runtime.MSpan_Sweep(0x30bd68, 0x3f00000000, 0xc200000001)
	/usr/local/go/src/runtime/mgc0.c:1099 +0x477

goroutine 3 [running]:
runtime.switchtoM()
	/usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc20801dfa8 sp=0xc20801dfa0
runtime.gosweepone(0x0)
	/usr/local/go/src/runtime/mgc0.c:1168 +0x1e fp=0xc20801dfc0 sp=0xc20801dfa8
runtime.bgsweep()
	/usr/local/go/src/runtime/mgc0.go:85 +0x36 fp=0xc20801dfe0 sp=0xc20801dfc0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
created by gc
	/usr/local/go/src/runtime/mgc0.c:1386

goroutine 1 [syscall]:
syscall.Syscall6(0x7, 0x3804, 0xc2082631dc, 0x0, 0xc2081f8000, 0x0, 0x0, 0xc208038660, 0x2b9a40, 0xc208038680)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:44 +0x5
syscall.wait4(0x3804, 0xc2082631dc, 0x0, 0xc2081f8000, 0x90, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:32 +0x79
syscall.Wait4(0x3804, 0xc208263224, 0x0, 0xc2081f8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_bsd.go:162 +0x60
os.(*Process).wait(0xc20807a900, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x103
os.(*Process).Wait(0xc20807a900, 0xc208021c00, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:45 +0x3a
os/exec.(*Cmd).Wait(0xc20813a140, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:364 +0x23c
os/exec.(*Cmd).Run(0xc20813a140, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:246 +0x71
arduino.cc/builder/builder_utils.ExecRecipeCollectStdErr(0xc2081d9950, 0x1efe10, 0x15, 0x1, 0x318f90, 0x2c0908, 0x0, 0x0, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/arduino-builder-macosx/src/arduino.cc/builder/builder_utils/utils.go:338 +0x1b1
arduino.cc/builder.(*GCCPreprocRunnerForDiscoveringIncludes).Run(0xc20805ef20, 0xc20803c510, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/arduino-builder-macosx/src/arduino.cc/builder/gcc_preproc_runner.go:80 +0x23e
arduino.cc/builder.runCommand(0xc20803c510, 0x31ebd0, 0xc20805ef20, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/arduino-builder-macosx/src/arduino.cc/builder/container_find_includes.go:93 +0x6c
arduino.cc/builder.findIncludesUntilDone(0xc20803c510, 0xc208185650, 0x6c, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/arduino-builder-macosx/src/arduino.cc/builder/container_find_includes.go:111 +0x3c2
arduino.cc/builder.(*ContainerFindIncludes).Run(0x2c0908, 0xc20803c510, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/arduino-builder-macosx/src/arduino.cc/builder/container_find_includes.go:73 +0xa5e
arduino.cc/builder.runCommands(0xc20803c510, 0xc208263b90, 0x1d, 0x1d, 0x19501, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/arduino-builder-macosx/src/arduino.cc/builder/builder.go:187 +0x139
arduino.cc/builder.(*Builder).Run(0xc208263d88, 0xc20803c510, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/arduino-builder-macosx/src/arduino.cc/builder/builder.go:118 +0xef7
arduino.cc/builder.RunBuilder(0xc20803c510, 0x0, 0x0)
	/Users/jenkins/jenkins/workspace/arduino-builder-macosx/src/arduino.cc/builder/builder.go:218 +0x49
main.main()
	/Users/jenkins/jenkins/workspace/arduino-builder-macosx/main.go:320 +0x1eb2

goroutine 25 [syscall]:
syscall.Syscall(0x3, 0x5, 0xc208173200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:20 +0x5
syscall.read(0x5, 0xc208173200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:970 +0x6e
syscall.Read(0x5, 0xc208173200, 0x200, 0x200, 0xc20801ada0, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc2080401e8, 0xc208173200, 0x200, 0x200, 0xc208173200, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x86
os.(*File).Read(0xc2080401e8, 0xc208173200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc208010770, 0x3192c0, 0xc2080401e8, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:169 +0x25a
io.Copy(0x31ec20, 0xc208010770, 0x3192c0, 0xc2080401e8, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:358 +0x13d
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc20807a6e0)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d
arduino-builder returned 2
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by devyte** [comment]
@kiralikbeyin the error messages seem to be related to Go language. A quick search for the title yields [this](https://github.com/golang/go/issues/17335).
I think your message is not related to the code in this repo.
Closing.
