### ISSUE TITLE
WifiClient.write repeat the same data

### ISSUE THREAD

**Issue by piastrina** [esp8266/Arduino#2766]
I'm just trying to forward serial data to a tcp server on my pc, 128 bytes at time
Every time i try, i receive the first chunk of data (about 700 bytes) repeated over and over
here's the code:

```
unsigned char data [1000];
while (1){
int a = Serial.available(); //when it's available, its 128 bytes long
 if (a>0){
 Serial.readBytes(data, a);
    Serial.write(data,a); //just for debug
   client.write((const char *)data,(size_t)a); 
  }
}
```

Serial baud rate is 230400
When i try 115200, the repeated chunk became about 1500 bytes long.
I checked the data through serial.write and it doesn't have any problem

**Comment by devyte** [comment]
@piastrina no MCVE, no basic info, no IDE settings.
You shouldn't do a while(1). The wifi stack needs to be serviced frequently, so your application can't be away from that for too long. There are timing guidelines that need to be observed.
Closing as code error, and off-topic.
