### ISSUE TITLE
Compile error on use I2C 

### ISSUE THREAD

**Issue by tytower** [esp8266/Arduino#277]

**Comment by tytower** [comment]
Well done Igrr - Thats a big change isn't it . That board system works well

Small problem from your read me notes I was trying
Error on compile

/tmp/build6729920515858897918.tmp/Phant_EthernetOriginalMinewithPressureESP8266Version.cpp.o 
Phant_EthernetOriginalMinewithPressureESP8266Version.ino:43:1: error: 'Wire' does not name a type
'Wire' does not name a type

**Comment by igrr** [comment]
Can you please post the sketch that triggers this problem?

**Comment by tytower** [comment]
See edit above -thats the only change . Compiles without it

**Comment by igrr** [comment]
Since you didn't post the complete sketch, I tried to compile this:
```C++
#include "Wire.h"


void setup() {
  Wire.begin(3,4);
}

void loop() {
}
```
and it compiles successfully.

**Comment by tytower** [comment]
Yes ,too much,too late at night ,Thank You
