### ISSUE TITLE
ESP-12 Clean/Erase Flash

### ISSUE THREAD

**Issue by ArGaspar** [esp8266/Arduino#2778]
Hi guys,
Once I saw a command to clean Esp flash from arduino ide, I cant find it right now, does anyone know it?

Thanks for your help.

**Comment by jjssoftware** [comment]
I don't know of any method to do this from the IDE but you can do it with esptool.py with the erase_flash option. It's also possible to erase flash using espressif's .exe flash tool if you flash an empty .bin binary across the entire surface of the flash. Someone has described how to do this here: http://www.pratikpanda.com/completely-format-erase-esp8266-flash-memory/

**Comment by devyte** [comment]
Closing as off-topic, see #3655 .
