### ISSUE TITLE
Flash bin file to ESP

### ISSUE THREAD

**Issue by Lexander24** [esp8266/Arduino#2790]
Hello guys i want ask more about this things
https://github.com/esp8266/Arduino/issues/1893

last time i try, i success flash bin to esp.
Now i want to try flash 2 code
1. Code for write eeprom, for basic config
2. Code to make board using normal function.

i flash code 1 to esp8266-01 and when i check using serial. Everything was OK. I can write and read EEPROM. But if i only using this code, every time power restart the board will rewrite the eeprom.

So i want to flash second file.
But when i flash second file, my eeprom configuration was  disappear. Any one can give me suggestion how to flash the second file?

thanks

**Comment by devyte** [comment]
@Lexander24 this is not the right place to ask these questions.
Closing due to off-topic, see #3655 .
