### ISSUE TITLE
Is critical timing possible?

### ISSUE THREAD

**Issue by sebokmarton** [esp8266/Arduino#2798]
I would like to show a few patterns on a LED strip when a sensor triggers. The challenge is that these patterns must follow the trigger according to a strict configurable timing for each execution. I figured that I could set a GPIO interrupt for the sensor output pin, update the LED strip using hardware SPI, and let the user configure the timing through a web server on the ESP in AP mode.

However, I'm not sure if I understand the underlying operation of the framework correctly, and I would like to validate this before jumping into the implementation.

1. If the code of my "critical section" uses busy waiting (doesn't contain any delays that yield to the OS) and I put it inside an InterruptLock, then will it be only my code that runs? So won't its execution time depend on the network activity or anything else that might be buried deep in the firmware?
2. Will the system survive if my code takes over for 10-100 milliseconds?
3. Is there a point in temporarily disabling the software WDT with ESP.wdtDisable()?
4. If the network activity does matter after all, how could I disable it temporarily?

**Comment by devyte** [comment]
@sebokmarton yes, it's possible to turn off interrupts for critical timings, but the time you take with interrupts disabled must be very short, especially if the wifi is enabled and double especially if you are serving web pages. The user app must return or yield to allow the wifi stack to be serviced, and there are timing guidelines for this.
Having said that, this is not the right place for these questions.
Closing as off-topic, see #3655 .
