### ISSUE TITLE
HTTPClient.Post returns HTTPC_ERROR_SEND_PAYLOAD_FAILED

### ISSUE THREAD

**Issue by yolofy** [esp8266/Arduino#2815]
I'm doing a post call from my esp8266 to a dotnetcore rest api.
I (sometimes) get HTTPCode -3 when posting to the rest api. 

The issue is resolved when I delay the rest call (server side) with 1000ms. The lower I set this delay the more likely it is I get this error. When the response time is <1ms I always get the error.

I'm using this board: https://www.olimex.com/Products/IoT/ESP8266-EVB/open-source-hardware

```
if((WiFiMulti.run() == WL_CONNECTED)) {
    HTTPClient http;
    http.begin("http://192.168.178.27:5102/api/Doorbell/Ring");
    int httpCode = http.POST("{}");
    Serial.println(httpCode);
    String payload = http.getString();
    Serial.println(payload);

    http.end();
  }
```

**Comment by devyte** [comment]
@yolofy is this still an issue with latest git? if so, could you please try #3362 ? 
Please report back here.

**Comment by devyte** [comment]
Closing due to lack of feedback in almost two months.
