### ISSUE TITLE
Telent server Exception(3) & (9)

### ISSUE THREAD

**Issue by MisterBE2** [esp8266/Arduino#2818]
### Basic Infos
I've got this error while connecting to Wi-Fi. I'm a bit confused, because moments ago it was working. But now no matter what I do it crashes.

#### Hardware

Module: ESP8266MOD - lolin nodemcu v3
Flash Size: 4MB
CPU Frequency:	80Mhz
Upload Using:	SERIAL
Reset Method:	nodemcu

### Description

Exception (3):
epc1=0x4010010e epc2=0x00000000 epc3=0x00000000 excvaddr=0x4006ff01 depc=0x00000000

ctx: cont 
sp: 3ffef4b0 end: 3ffef700 offset: 01a0

>>>stack>>>
3ffef650:  3ffee5a4 00000001 3ffee6a4 402038bd  
3ffef660:  3ffee684 0000fffc 0000fffc 4010020c  
3ffef670:  3ffee5a4 3ffee578 3ffef6a0 4010068c  
3ffef680:  3ffee5a4 3ffee578 3ffee6a4 40203b64  
3ffef690:  4954454e 3ffee578 3ffee6a4 402023a4  
3ffef6a0:  3ffeff00 0000000f 00000000 feefeffe  
3ffef6b0:  feefeffe feefeffe feefeffe feefeffe  
3ffef6c0:  3ffef680 3ffef6a0 0000000c feefeffe  
3ffef6d0:  feefeffe feefeffe feefeffe 3ffee6d0  
3ffef6e0:  3fffdad0 00000000 3ffee6c8 40203efc  
3ffef6f0:  feefeffe feefeffe 3ffee6e0 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v09f0c112
~ld

It looks like program crasches when it's entering void loop(){}

decoded stack:

0x4020385d: Print::write(char const*) at C:\Users\Kuba\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Print.cpp line 76
0x4010020c: _umm_free at C:\Users\Kuba\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266\umm_malloc/umm_malloc.c line 1287
0x4010068c: free at C:\Users\Kuba\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266\umm_malloc/umm_malloc.c line 1733
0x40203b04: String::~String() at C:\Users\Kuba\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/WString.cpp line 292
0x40202340: setup at D:\Projekty\Fabryka Pasji\ESP8266\Programy\5. Finalny program\ProgramESP8266-15/ProgramESP8266-15.ino line 355
0x40203ecc: loop_wrapper at C:\Users\Kuba\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/core_esp8266_main.cpp line 56
0x40100718: cont_norm at C:\Users\Kuba\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/cont.S line 109

### Sketch

Code : [Link to pastebin](http://pastebin.com/c4B59nG7)

**Comment by MisterBE2** [comment]
@igrr please look at These. Now all the sudden all of my previous working version of this code also do not work. I do not know what to do :/

**Comment by devyte** [comment]
@MisterBE2 you are storing strings in the EEPROM (which by itseld is not a very good idea, you should use the SPIFFS instead), and your loop for that is based on strlen. That means you don't store the null-terminator. Then, when you read the strings back, I don't see a null terminator either.
Most likely, you have garbage in your buffs, and then when trying to print, you crash due to the missing null terminator.
In any case, this is not the right place to ask for assistance for your particular project.
Closing as off-topic and language error, see #3655 .
