### ISSUE TITLE
Jun,23,2016 is the Lastest Stable version???

### ISSUE THREAD

**Issue by LittleNibble** [esp8266/Arduino#2828]
Jun,23,2016 is the Lastest Stable version???

**Comment by lrmoreno007** [comment]
Yes

**Comment by torntrousers** [comment]
Big +1 from me, was also about to raise the same issue asking for a new release.

**Comment by vicnevicne** [comment]
+1 
See http://www.esp8266.com/viewtopic.php?f=31&t=12000

**Comment by asetyde** [comment]
But i think esp32 be soler this library .. any idea of new realese ? 
Foundrising campaign can be help ?
