### ISSUE TITLE
Adafruit_ILI9341 not available [Arduino 1.6.4 + ESP8266 installed via Boards Manager]

### ISSUE THREAD

**Issue by reaper7** [esp8266/Arduino#283]
Adafruit_ILI9341 library:
https://github.com/esp8266/Arduino/tree/esp8266/libraries/Adafruit_ILI9341 
not available from Arduino 1.6.4 + ESP8266 installed via Boards Manager

**Comment by igrr** [comment]
Same thing as with the SD library.

**Comment by reaper7** [comment]
true, it looks similar
but I mark this as a "reminder" :)
anyway - tnx for hard work for All!

**Comment by igrr** [comment]
Updated package has been deployed.
