### ISSUE TITLE
Client mac address support

### ISSUE THREAD

**Issue by treii28** [esp8266/Arduino#2832]
Have any updates or consideration been addressed toward implementing the ability to retrieve a wifi client's MAC address yet? I researched the issue a number of months ago and was able to determine the original C code had support for polling clients to get info including their MAC addresses, but it was not as of yet implemented in any of the C++ wrappers for the Arduino code suite for anything other than the local shield. I don't have enough knowledge of C++ to implement my own wrapper for the older C code, but it would be nice to be able to get the MAC addresses for clients within range so you could uniquely identify them. (I'm trying to implement a beacon style device that searches for open wifi hubs for geo location purposes, but sometimes SSIDs alone aren't sufficient for avoiding re-using already seen open wifi hubs)

**Comment by treii28** [comment]
bump

**Comment by devyte** [comment]
@treii28 Please look into the onProbeRequest callback implemented in latest git (merged from PR #2917 ). The callback should get called when a wifi client probes the SoftAP, and the argument to the callback should provide what you need (see ESP8266WiFiType.h for argument struct).
Having said that, closing, see #3655 .
