### ISSUE TITLE
How many clients can connect in single server?

### ISSUE THREAD

**Issue by Joypacharya** [esp8266/Arduino#2835]
Hello everyone,
actually i am using client and server code for TCP data network.
In server side i am using ESP8266 and client side i am connecting computer using com operator send some text.
Problem i am facing currently is that,
Same time i can connect only client at time.So, how to connect multiple client same time?
If any has code then send me please i tried many method still can't work.

**Comment by devyte** [comment]
@Joypacharya Closing due to off-topic, please see #3655 .
