### ISSUE TITLE
WiFi server get reference on available function

### ISSUE THREAD

**Issue by cristovao-trevisan** [esp8266/Arduino#2838]
Hello, first of all thanks for the awesome work.
I just want to say that the return object on the method avaliable of the WiFiServer class (`WiFiClient available(uint8_t* status = NULL)`) should be returned be reference for further use of the connection.
I am writing a Server where I need to maintain multiple TCP connections, and stomped into this. I know that as an Arduino like project it should avoid pointers to make it easy for non professional programmers, but at least another function should be added.
I can do that, update the docs and submit a pull request if you want (just let me know).
For now I am maintaining my own fork, adding this: `WiFiClient* availableSocket(uint8_t* status = NULL)`  (I know it's bad naming, just made it on a hurry).

Thanks for your time, Cristóvão Trevisan.

**Comment by igrr** [comment]
WifiClient is already a reference counting pointer, and can be passed by value. What do you want to achieve be returning a pointer to it?
