### ISSUE TITLE
General info  - Nodemcu ESP32 is coming ! We've a brother 

### ISSUE THREAD

**Issue by asetyde** [esp8266/Arduino#2849]
I'm edite to see new esp32 comes on nodemcu from doit.am !

About esp8266 , roadmap in coming slow , there are problems ?

**Comment by vraj11** [comment]
i have nodemcu, i can't command it what should i do?

**Comment by bugraules** [comment]
download esplorer IDE and study the videos about it  to learn

**Comment by asetyde** [comment]
out of contest .
