### ISSUE TITLE
Hardware problem with ESP8266 RF with my prototype

### ISSUE THREAD

**Issue by williamesp2015** [esp8266/Arduino#2851]
#### Hardware
Hardware:			Custom ESP8266 Design with 32Mbit Flash, 5.6 pf capacitor connected to PCB Antenna
Core Version:      	3.2.1

Problem description
I have problem with wifi connection and I was thinking I have problem with Antenna so I bypassed it to an external Antenna but same problem. I changed 5.6 pf capacitor but no progress. If I flash it with SoftAP or WifiScan, can not detect network. How can check ESP8266 RF section or is there any other pin related to it except Pin31?

### Settings in IDE

Module:  			Generic ESP8266 Module?
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz
Upload Using:		 SERIAL
Reset Method:		nodemcu

### Sketch

```cpp

#include <Arduino.h>

  Serial.printf("Connecting to %s\n", ssid);
  delay(500);
  WiFi.begin(ssid, password);

  int Attempt = 0;
  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
    Attempt++;
    Serial.print(".");
    if (Attempt == 10)
    {
      Serial.println();
      Serial.println("Could not connect to WIFI");
      return;
    }
  }

**Comment by devyte** [comment]
@williamesp2015 I suggest trying with release 2.3.0 or latest git. Since SDK 2.0.0, there is a new rf calibration done on startup which might help you.
Having said that, this is not the right place to ask for assistance.
Closing as off-topic, see #3655 .
