### ISSUE TITLE
ESP.deepSleep

### ISSUE THREAD

**Issue by MisterBE2** [esp8266/Arduino#2857]
### Basic Infos

Hello everyone!

I had tried to put ESP to sleep with ESP.deepSleep() command. And it works, but when it should wake up it just keep restarting. I connected pin 16 (ESP 12-E) to rst...

**Comment by markusschweitzer** [comment]
ESP.deepSleep() should start with setup() again (It is like a "fresh" start).

**Comment by MisterBE2** [comment]
@markusschweitzer  Can you give me sample code? Because I applied your advice, and IDE tells me: "no matching function for call to 'EspClass::deepSleep()"

**Comment by duncan-a** [comment]
What Marcus was saying, is that when the ESP wakes from deep sleep, itis
exactly the same as a reset - the code begins running again from the
beginning.

What you were seeing is perfectly normal, and the only option.

**Comment by MisterBE2** [comment]
I feel like I should explain more :/

I'm using ESP12E (nodemcu v3), I connected pin 016 (wake) to rst. And I connected 10K pullup resistor to rst.

Then in void loop() I placed command ESP.deepSleep(10 * 1000000); Till this point everything works fine, but! When this 10 s delay elapse esp keeps restarting in loop. Built in LED is keeps blinking in 0.2 s intervals. 
Wasn't it supposed to restart once (till nex deep sleep command)?
How to fix it?

**Comment by MisterBE2** [comment]
I found the solution. You can't have open serial port connection.

**Comment by jaky000000** [comment]
overflow
把int改为unsigned int

**Comment by devyte** [comment]
@MisterBE2 last comment found a solution => closing as resolved.

**Comment by didietaja** [comment]
if you are going to use nodemcu in deepsleep mode, then you cannot use internal LED  in the same time, because they are using the same PIN, on D0/GPIO16.

**Comment by dan2600** [comment]
Nice catch, was having the same issue.
