### ISSUE TITLE
TLS support?

### ISSUE THREAD

**Issue by webworxshop** [esp8266/Arduino#286]
Any possibility of adding TLS support to the Wifi library? It is my understanding that the ESP8288 SDK supports TLS connections with 1024 bit keys.

**Comment by igrr** [comment]
#43 
That can be done, but I haven't started working on this yet.

**Comment by marvinroger** [comment]
Great, this will be a good thing as a lot of APIs now requires https.

**Comment by antelder** [comment]
So excited to read this! Would fab to have SSL support in WiFiClient.

**Comment by georgkreimer** [comment]
+1

**Comment by fhernand** [comment]
+1

**Comment by AndyKirby** [comment]
+1

MQTT is not terribly secure without it. A sniffer lets you open it up
real easy. SSL/TLS make sit a lot harder to do.

On 23/07/15 21:12, fhernand wrote:
>
> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/esp8266/Arduino/issues/286#issuecomment-124227003>.
>

-- 
andy@kirbyand.co.uk
www.kirbyand.co.uk

**Comment by tim-in-oakton** [comment]
+100

**Comment by asetyde** [comment]
+100

**Comment by JeffAshtonCT** [comment]
+1

**Comment by marvinroger** [comment]
I don't want to be tough, but could you please stop publishing `+1` as this is not really constructive and this is a feature everyone wants, so that's probably in the roadmap. These +1s won't make any difference about when it's going to be ready. Don't forget that people subscribed to this issue receive a mail for each comment. Thanks :)

**Comment by tim-in-oakton** [comment]
+1 marvin, great comment!  Feedback is clearly unnecessary!

**Comment by marvinroger** [comment]
Oh come on, the goal was not to offend anyone! Feedbacks are great, `+1`s only are not. Let's not make a debate, GitHub is one of the rare platforms where there is no fuss. :)

**Comment by igrr** [comment]
Closing this one, please follow #43 for updates.
