### ISSUE TITLE
Can we force the use of TLS v1.1?

### ISSUE THREAD

**Issue by Humancell** [esp8266/Arduino#2863]
Is there a way to force the use of TLS v1.1 (instead of TLS v1.2) in order to conserve memory/resources, in the case that we know the web server supports TLS v1.1?

I know of the issues with TLS v1.1 security, but if we are ok with that, and know our server supports TLS v1.1, then is there some way to stop the libraries from attempting to use the more resource intensive TLS v1.2?

**Comment by devyte** [comment]
@Humancell closing due to off-topic, see #3655 .
