### ISSUE TITLE
assembled new AsyncPing library

### ISSUE THREAD

**Issue by akaJes** [esp8266/Arduino#2867]
Hi
after a lot hours spent of pushing SDKs ping out from exceptions of whole my project
I have decided to write my own without glitches and with some improvements
help me to test it
https://github.com/akaJes/AsyncPing

thanks a lot

**Comment by devyte** [comment]
@akaJes Thank you for the implementation, the code looks good at first glance. I will likely be testing it at some point, I'll need to ping from the ESP for my own projects.
Closing, because it's not an issue for the repo.
