### ISSUE TITLE
Higher Flash Sizes

### ISSUE THREAD

**Issue by sticilface** [esp8266/Arduino#288]
It is great to see support being added.  But where/how do we get modules with extra flash?

I have seen 4M ESP-12 on ali express, but nothing higher.  I bought a bunch of ESP-12, but they are all 512K.  I've bought a node-mcc dev board, but that to is only 512.

**Comment by igrr** [comment]
I think this would make a great forum topic, but not a github issue really...
Some of my ESP-12s are 4M. Some people buy flash chips and rework their modules. Olimex modules also come with larger flash size.

**Comment by sticilface** [comment]
fair point!
