### ISSUE TITLE
ESP.eraseConfig() and ESP.restart() not erase WPS config.

### ISSUE THREAD

**Issue by rudacs** [esp8266/Arduino#2885]
#### Hardware
Hardware: ESP-12e
Core Version: 2.3.0

### Description

I need to clear the WPS configuration directly by code.
I Tried to do:

ESP.eraseConfig();
ESP.restart();

### Sketch

```cpp

#include <Arduino.h>
#include <ESP8266WiFi.h>

void setup() {
Serial.begin(74880);
}

void loop() {
if (Serial.available() > 0)
  {
    String text = Serial.readString();
    text.trim();

    Serial.print("Command: ");
    Serial.println(text);

    if (text == "CLEAR")
    {
      ESP.eraseConfig();
      ESP.restart();
    }
    else if (text == "WPS")
    {
      startWPSPBC();
    }
  }
}
```

**Comment by frankalicious** [comment]
Does replacing  
`ESP.restart();`
with 
`ESP.reset();`
work?
See https://github.com/esp8266/Arduino/issues/1494

**Comment by bestpika** [comment]
WiFi config not erase.
```cpp
void formatConfig() {
    Serial.println(ESP.eraseConfig());
    delay(5000);
    ESP.reset();
}
```

**Comment by devyte** [comment]
@rudacs @bestpika Could you please try PR #3215 ? It has the latest SDK. I'm not aware of any relevant changes, but it's worth a try.

**Comment by igrr** [comment]
Also please try https://github.com/esp8266/Arduino/pull/3635.

**Comment by tablatronix** [comment]
Only #3635 fixes this for me, I am unable to get eraseConfig to do anything in 1.5.3. FYI

**Comment by devyte** [comment]
The referenced PR is already merged, and there is confirmation by @tablatronix , so closing.
