### ISSUE TITLE
analogWrite is not compliant with standard Arduino API

### ISSUE THREAD

**Issue by Makuna** [esp8266/Arduino#2895]
The standard Arduino API `analogWrite()` takes a value from 0-254.  The Esp Arduino version defaults to a 10 bit value.  This makes code incompatible between all other Hardware and leads to confusion on the part of users.

`analogWrite()` should be modified to default to 8bit and the standard `analogWriteResolution()` should be implemented to set the resolution to 10bit (and/or what ever else it can support).

**Comment by Paul-Ver** [comment]
#295

Use the defined PWMRANGE.

You could then go along and calibrate it accordingly: https://www.arduino.cc/en/Tutorial/Calibration

**Comment by devyte** [comment]
@igrr is this something that we want to do? I _really_ don't like defaulting to 8bits and having to change to 10bits with a function call, it would break who know what out there, but the request has a point about compatibility with Arduino.

**Comment by igrr** [comment]
Maybe put this under "major breaking changes for new major release" category (i.e. if/when we bump the version to 3.0). I agree that this should be made Arduino compatible, at some point.

**Comment by Makuna** [comment]
@devyte It currently is breaking stuff all over the place.  Several libraries don't work out of the box with esp8266 due to this (internally they use analog write).

**Comment by igrr** [comment]
@Makuna can you mention some of these libraries? As in, it would probably take ~15min per library to send a PR to take PWMRANGE into account. That would be a reasonable short term solution, I think.

**Comment by devyte** [comment]
@Makuna will you be providing the requested info?

**Comment by Makuna** [comment]
The library issues came up in a maker class I was teaching where students applied specifics from their projects.  We discovered the issues with several, but I don't have the links to them sorry.

**Comment by majenkotech** [comment]
It is confusing for an Arduino user that expects `analogWrite()` to be 8 bit. 

* [Here is one example](https://arduino.stackexchange.com/questions/57718/passive-buzzer-works-with-analogwrite-but-not-with-digitalwrite-it-also-ha) where they are confused that `analogWrite(pin, 255);` doesn't act the same as `digitalWrite(pin, HIGH);`.
