### ISSUE TITLE
Read the ADC pin

### ISSUE THREAD

**Issue by oshlab** [esp8266/Arduino#29]
Is there any way to read the ADC pin to get an analogRead()?
![fp1yb93i7lqhxhs large](https://cloud.githubusercontent.com/assets/10917300/6949949/17a26c48-d87d-11e4-8eff-1917c0aa3471.jpg)

**Comment by 4refr0nt** [comment]
You can try analogRead(0).
TOUT=ADC
https://github.com/esp8266/esp8266-wiki/wiki/Pin-definition

**Comment by igrr** [comment]
As mentioned [in the readme](https://github.com/esp8266/Arduino#basic-wiring-functions), 

>```analogRead(0)``` reads the value of the ADC channel connected to the TOUT pin.

**Comment by oshlab** [comment]
Sorry about that. Somehow I missed it.
