### ISSUE TITLE
SD Web Server example fails with latest master code

### ISSUE THREAD

**Issue by torntrousers** [esp8266/Arduino#2915]
As also mentioned in the Issues 1853 comment [here](https://github.com/esp8266/Arduino/issues/1853#issuecomment-248483979) SD Web Server example fails to serve the complete pins.png image with Serial console message "sent less than expected!". Looks like anything larger than 32k gets truncated. Works ok going back to the 2.3.0 release.

**Comment by igrr** [comment]
Should be fixed by #3209.
