### ISSUE TITLE
CaptivePortalAdvanced.ino causes "server reset connection" errors in IE and Chrome

### ISSUE THREAD

**Issue by themindfactory** [esp8266/Arduino#2920]
The CaptivePortalAdvanced.ino example causes "Connection has been reset" conditions in both IE and Chrome in Windows 10.... maybe others.... have tried various things and they all cause the same issue.

A curious observation is once this happens say at 192.168.4.1 you can never access this IP again, even if the captive portal parts are removed and its a simple webserver, but if you change the IP to 192.168.5.1 the simple webserver will run, and once you put back captive portal parts (mainly the dns stuff) you will ge tthe server reset issue and it will never allow a connection to that IP again.

And yes, I have cleared caches, I have cleared browser settings/caches, and I have done a ipconfig /flushdns

RichardS

#### Hardware
Hardware:			ESP-12E
Core Version:      	2.2.x 2.3.x

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			dio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		nodemcu

**Comment by devyte** [comment]
@themindfactory is this issue still valid with latest git?

**Comment by devyte** [comment]
@themindfactory I just tested latest git (candidate for 2.4) on Windows 10, both with Chrome and Edge, and I can't reproduce this issue.
Closing due to old issue that is not reproducable, and no feedback in 24 days.
