### ISSUE TITLE
How can i send post request to a jsp Page?

### ISSUE THREAD

**Issue by drakehammer** [esp8266/Arduino#2921]
Hi to everyone, im making a trilateration app using wifi as technology and im usign esp8622 as tag, i made a java code with apache commons math to make all the calculus in android, but now i want to migrate it to web, and i dont know if it possible to send the post from the esp8622 to a jsp page.

Thanks for your help.

**Comment by wuwx** [comment]
http.POST(payload);

**Comment by drakehammer** [comment]
I was trying, but i cant use it, can you help me with a example? please

**Comment by torntrousers** [comment]
There's one [here](https://github.com/esp8266/Arduino/issues/1390#issuecomment-170343346).

**Comment by devyte** [comment]
@drakehammer there are examples viewable from within the Arduino IDE.
This is not the right place to ask for assistance. This is an issue tracker, meant to track issues in the core. Please refer to esp8266.com or stackoverflow for assistance, assuming you still need it.
Closing.
