### ISSUE TITLE
Updates and the board manager...

### ISSUE THREAD

**Issue by sticilface** [esp8266/Arduino#293]
How are updates handled using the board manager?  

ie... how do you get the latest commits etc....

**Comment by robotiko** [comment]
+1

**Comment by robotiko** [comment]
+1

**Comment by tzapu** [comment]
I am also interested in this
Cheers

**Comment by igrr** [comment]
When the update will be published, you will see "Install" button in the board manager instead of "uninstall". At the moment IDE doesn't notify you when an update is available.

**Comment by tzapu** [comment]
hi, thanks for that. i assume this will happen only for releases, or whenever there is a new commit ?

**Comment by igrr** [comment]
Only for releases. We break stuff too often to deploy new version after each commit :)

**Comment by duncan-a** [comment]
Yeayyyy!!! This bodes very well................

Thanks guys

**Comment by sticilface** [comment]
Worth adding here what you mentioned. 

Boards manager installs are independent of the ide! They will persist and override what is in the ide folder. 

For example.... To useatest commits with your own compiled ide uninstall the esp8266 in boards manager. 

I'm sure you could also overwrite the hardware folder in the boards manager location but that will vary by operating system and user! (I'm guessing)
