### ISSUE TITLE
Power does not seem to change

### ISSUE THREAD

**Issue by themindfactory** [esp8266/Arduino#2931]
Just a quick question about power... I set power high or low and my WIFI beacons don't seem to change the power reported by Windows/IOS/Android, might there be a reason? Or is this function not working correctly?

RichardS

**Comment by devyte** [comment]
@themindfactory is this question still valid with latest git? Is it still valid with the SDK2.1.0 branch?
Do you mean the espressif sdk api to set output transmit power of the wifi radio?

**Comment by devyte** [comment]
Closing due to lack of info, old, and no feedback in over a month.
