### ISSUE TITLE
Can i write a recovery program that eboot could boot it?

### ISSUE THREAD

**Issue by PlatenySmartiks** [esp8266/Arduino#2948]
Hardware:			ESP-13
Core Version:      	2.3.0

Is there a way for me to upload a recovery program in flash, aside the main one, that can take the main binary previously saved in the file system and reupload it? (using ESP.sketchUpdate)
The eboot bootloader would have to change so i could press a button on restart and the eboot could boot this recovery program. 
I have no idea how to do that.

**Comment by devyte** [comment]
@PlatenySmartiks there is currently a discussion ongoing about switching to rboot, which could allow something along the lines of what you ask.
Having said that, this is not the right place to ask such questions. This is an issue tracker, meant for tracking issues in the core. Please ask at esp8266.com or stackoverflow.
Closing.
