### ISSUE TITLE
ESP-12F: I2C communication DS1307 

### ISSUE THREAD

**Issue by channaq4** [esp8266/Arduino#2953]
----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			ESP-12F , DS1307

### Description

Problem description

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB
CPU Frequency:	80Mhz
Flash Frequency:	40Mhz
Upload Using:		 SERIAL
Reset Method:		ck 

### Sketch
#include "Wire.h"
#define DS1307_I2C_ADDRESS 0x68
#define SCL 14 //--GPIO5 / GPIO14
#define SDA 2 //-- GPIO4 / GPIO2

TwoWire twowire;

uint8_t _second, _minute, _hour, 
_dayOfMonth,_dayOfWeek,_month,_year;

void setup() {
  // put your setup code here, to run once:
  twowire.begin(2,14);
  twowire.setClock(100000);
  Serial.begin(115200);
}

void loop() {
  // put your main code here, to run repeatedly:
    delay(1000);
    Get_Date_Time();
}

void Get_Date_Time()
{
  ReadTime(&_second, &_minute, &_hour, &_dayOfWeek, &_dayOfMonth, &_month, &_year);
  Serial.println(_hour);
  
}

void ReadTime(byte *second,byte *minute,byte *hours,byte *DayOfWeek,byte *DayOfMonth,byte *month,byte *year)
{
  twowire.beginTransmission(DS1307_I2C_ADDRESS);
  twowire.write(0); 
  twowire.endTransmission();
  twowire.requestFrom(DS1307_I2C_ADDRESS, 7);
  
  *second = BCDToDEC(twowire.read() & 0x7f);
  *minute = BCDToDEC(twowire.read());
  *hours = BCDToDEC(twowire.read() & 0x3f);
  *DayOfWeek = BCDToDEC(twowire.read());
  *DayOfMonth = BCDToDEC(twowire.read());
  *month = BCDToDEC(twowire.read());
  *year = BCDToDEC(twowire.read());
  
}

//-- Convert decimal to binary code decimal
byte DECToBCD(byte value)
{
  return ( (value/10*16) + (value%10) );
}

//-- Convert binary code decimal to decimal
byte BCDToDEC(byte value)
{
  return ( (value/16*10) + (value%16) );
}

### Debug Messages
f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v60000318
~ld
45
45
45

_Hi I,m new to ESP8266.

I try to read time using I2C, DS1307 module gives me "45" in Serial console .
i have tried ,  SCL  - GPIO5 / GPIO14 
                    SDA - GPIO4 / GPIO2

with pins both configurations gives me same output. 

Please find my Sketch above.module works well with Arduino(ESP-12F with minimal configeration)

Please advice_
```

**Comment by devyte** [comment]
@channaq4 This is not the right place to ask for help with your particular project. This is an issue tracker, meant for tracking issues in the core. Please refer to esp8266.com or stackoverflow for discussions.
Closing.
