### ISSUE TITLE
Is there a spec for the OTA protocol

### ISSUE THREAD

**Issue by nqos8051** [esp8266/Arduino#2963]
Hi,
I am looking for the OTA protocol spec/doc. Any pointers are much appreciated. I apologize if this is not the right chat forum post the questions.
Jim

**Comment by devyte** [comment]
@nqos8051 it's not the right chat/forum. This is an issue tracker, meant for tracking issues in the core.
I don't know about the spec/doc, but in such cases: "use the source, Luke!".
Closing as off-topic.
