### ISSUE TITLE
"Official" list of supported SSL ciphers?

### ISSUE THREAD

**Issue by dandandandandandandan** [esp8266/Arduino#2971]
I've seen 
TLS_RSA_WITH_AES_128_CBC_SHA and TLS_RSA_WITH_AES_256_CBC_SHA
mentioned, are there any others?

**Comment by devyte** [comment]
@dandandandandandandan This is not the right place to have such discussions. This is an issue tracker meant for tracking issues in the core. Please refer to esp8266.com or stackoverflow for code discussions.
Closing.
