### ISSUE TITLE
Feature request: EAP hotspot

### ISSUE THREAD

**Issue by redfast00** [esp8266/Arduino#2972]
Hi,
First of all, thanks for this amazing project. It really makes it easy to program for the ESP8266. I'd like to have an access point with EAP authentication running on the ESP8266. I know it can already connect to another EAP access point, but I haven't found how to do it the other way around. It would be really helpfull if you could put me on the right track.

**Comment by devyte** [comment]
@redfast00 this is not the right place to ask "how do I..." type questions. This is an issue tracker, meant for tracking issues in the core. Please refer to esp8266.com or stackoverflow for assistance.
Closing.
