### ISSUE TITLE
Copyright violation by queue.h

### ISSUE THREAD

**Issue by Osteri** [esp8266/Arduino#2981]
### Basic Infos

[Queue.h](https://github.com/esp8266/Arduino/blob/master/tools/sdk/include/queue.h) is copied from [*BSD](https://github.com/freebsd/freebsd/blob/master/sys/sys/queue.h), without proper copyright information.

### Description

Your [licence](https://github.com/esp8266/Arduino/blob/master/tools/sdk/License) does not mention where the queue code is copied from, although it is required by BSD licences. You cannot just copy others code and re-licence it. The queue macros are clearly copied from some BSD based distro.

BSD licences:
1. _Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer._
2. _Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution._

### Solve

Either:

1. Add proper copyright/licencing information.
2. Remove the queue.h code.

**Comment by igrr** [comment]
Thanks for pointing this out, created #2982 which should fix this.
