### ISSUE TITLE
ESP is stuck, still WDT does not fire

### ISSUE THREAD

**Issue by everslick** [esp8266/Arduino#2986]
it often happens, that the ESP gets stuck, but no WDT fires, neither software nor hardware. i have the impression that bad wlan conditions have an influence on it. the point is, that loop() is not running anymore but still the WD gets fed internally.

proposal: provide a way, that the sketch can 'claim' responsibility to feed the WD so if loop() does not get executed anymore, the WD will reset the CPU.

**Comment by igrr** [comment]
The proposal part is possible duplicate of #1532.

**Comment by everslick** [comment]
thanks for the hint, this is a good workaround for the time being.
