### ISSUE TITLE
Question on using Serial1 versus serial

### ISSUE THREAD

**Issue by mjs513** [esp8266/Arduino#3008]
This is not an issue but a question.  If i have ESP8266 module attached to on serial1 on an arduino versus Serial.. How do I tell the library to use Serial1 for th 8266 while using Serial for output to the monitor? 

What I am trying to do is to use this library with a Mircroduino wifi module on top of the Microduino core+ core and what to know what I have to do to get it working.

Thanks
Mike

**Comment by jcmojj** [comment]
I am not sure if I understood your question, but you have hardware serial and software serial at arduino. When you write **serial.begin** you use hardware serial. You can create a software serial using any other two pins (ts and rs) you want. Check how to do it at [https://www.arduino.cc/en/Reference/softwareSerial](url).

**Comment by jcmojj** [comment]
Here it is some specific info about serial at ESP8266.
https://github.com/esp8266/Arduino/blob/master/doc/reference.md
