### ISSUE TITLE
An AP is created automatically, even without any code loaded in.

### ISSUE THREAD

**Issue by vgeraud** [esp8266/Arduino#3012]
Hi,

I'm using WeMos D1 mini with the simple following sketch : 

void setup() {
  Serial.begin(115200);
  Serial.println("test");
}

void loop() {}

I noticed that even though my sketch isn't involving any connection process, an access point is created by the D1 mini and that I can connect to it with any device. However there is nothing if I enter the board's IP in my browser...

It seems that the AP is automatically created on boot.
Any idea on how to disable this function ?

Thanks.

**Comment by kaofishy** [comment]
See the WiFiClientBasic example for ESP8266 included in the Arduino board library.

**Comment by 101010b** [comment]
Hi, 
I encountered the same problem and don't see how the WiFiClientBasic example helps here. Any additional hints are highly appreciated.
Thanks.

**Comment by themindfactory** [comment]
ESP8266 remembers its old settings, you do not need code to be an AP, the
module will do that all on its own....

If you want it not to be an AP then add WiFi.softAPdisconnect(false); and
WiFi.enableAP(false); to your code.

http://www.esp8266.com/viewtopic.php?p=56442

**Comment by 101010b** [comment]
Works! Thanks for the hint.
