### ISSUE TITLE
abs() Makro is broken

### ISSUE THREAD

**Issue by holgerlembke** [esp8266/Arduino#302]
Works:

    int k=Buttons[i, 0] - Buttons[j, 0];
	
    if ( abs(k) < ButtonDelta ) {
        ButtonDelta = abs(k);
      }

Compiler swears like a sailor:

    if ( abs(Buttons[i, 0] - Buttons[j, 0]) < ButtonDelta ) {
        ButtonDelta = abs(Buttons[i, 0] - Buttons[j, 0]);
      }
    }

**Comment by igrr** [comment]
Could you please post your sketch and the compiler output?

**Comment by holgerlembke** [comment]
No. I prefer to close it, dig a deep hole and hide myself in shame.

Too long worked with [a,b,c]-style of indexing instead of [a][b][c].... I didn't see my error.

**Comment by igrr** [comment]
Don't be so hard on yourself :)
