### ISSUE TITLE
list of available standard library features

### ISSUE THREAD

**Issue by kommancs96** [esp8266/Arduino#3033]
I know that I can run c++11 code, since the compiler links against libstdc++ library. But thi s library is limited, for example `std::vector`, `std::remove`, `std::end` etc. are working, but `std::thread` is not. 
Neither can I use c++14 features like `decltype(auto)`.

Is there a reference, where I can check exactly, which standard library features are available for this platform?

**Comment by devyte** [comment]
As far as I know, there is no reference for officially support. The current compiler is supposed to be C++11 compliant, but it's an xtensa specific one, so I'm not sure if it really is 100% compliant.
In addition, the compiler comes with the esp tools/sdk. There are libs from espressif that are distributed in precompiled form. In theory, if we were to use a newer compiler for app code, but linked against those libs built with an older one, there could be binary incompatibilities.

About libstdc++, currently there are at least 2 known issues with it: a bug in Arduino.h that clashes with definitions of min/max, and std::array. I don't know if there are other issues.
Features like std::thread are, of course, out of the question. This is an embedded system that doesn't even have an OS, let alone multitasking or threading.
If you would like to use a newer compiler, feel free to look for one, and open a new issue with the information. Personally, I'd love to move to a newer version, but I'm not even aware of the existence of a newer one for the ESP.

Closing as unactionable for the core libs.
