### ISSUE TITLE
NodeMCU ESP8266 cannot start

### ISSUE THREAD

**Issue by tranquang7979** [esp8266/Arduino#3039]
Please help! I'm building a small project that user can control 2 leds through the wifi. After I uploaded program to NodeMCU ESP8266. I got these messages

![image](https://cloud.githubusercontent.com/assets/2139635/23854973/786aea7a-0826-11e7-95a6-de0638391f3e.png)

----------------------------------------------------------

#### Hardware
Hardware:			NodeMCU ESP8266 MOD

### Description

![image](https://cloud.githubusercontent.com/assets/2139635/23855327/d8a60f22-0827-11e7-8f23-7062aab22d3e.png)

### Settings in IDE

![image](https://cloud.githubusercontent.com/assets/2139635/23855112/0ddf8656-0827-11e7-9362-3687687b90f6.png)

### Sketch
[wifi-ESP8266-blink-2leds-socket.zip](https://github.com/esp8266/Arduino/files/838244/wifi-ESP8266-blink-2leds-socket.zip)

**Comment by tomamarsanaa** [comment]
Hi, I had same problem and I have spent many weeks to try to solve this issue.
At last, I found out the reason. Try to set 16th pin mode in the 'setup' function as below.
Doing this, mine is resolved.

void setup() {
  pinMode(16, OUTPUT); // set mode for build in LED which is 16th pin
  ...
}

**Comment by devyte** [comment]
GPIOs 6 & 7 are used internally, and shouldn't be used for other purposes. Don't confuse GPIO6 & 7 with D6 & 7.
Please research more about the nodemcu and pinouts. 
Closing as user error.
