### ISSUE TITLE
SPIFFS end() and OTA

### ISSUE THREAD

**Issue by Daemach** [esp8266/Arduino#3041]
The 2.3.0 documentation says the following about the SPIFFS end() function:

SPIFFS.end()
This method unmounts SPIFFS file system. Use this method before updating SPIFFS using OTA.

I'm using OTA for firmware updates - do I need to unmount SPIFFS every time I do a check for new firmware?

**Comment by devyte** [comment]
Are you updating the sketch, or the SPIFFS? If the latter, I think you need to unmount first.

**Comment by devyte** [comment]
@Daemach no further comments in 7 days. Closing.

**Comment by FlashNoob98** [comment]
I have the same question.. I need to eventually update the sketch, do I need to put SPIFFS.end() anywhere in the sketch? I use SPIFFS for esp8266ftp
