### ISSUE TITLE
Doesn't upload

### ISSUE THREAD

**Issue by Pablotis** [esp8266/Arduino#305]
Since the last version it doesn't upload sketches to my ESP8266:

warning: espcomm_sync failed
error: espcomm_open failed

I the old version and the same cables it works, it also works with the ESP8266 Flash Downloader Tool and an official firmware

**Comment by igrr** [comment]
Which OS are you running?

**Comment by Pablotis** [comment]
Windows, thanks for helping =)

**Comment by Pablotis** [comment]
I added the log on the other comment

**Comment by Pablotis** [comment]
How can I install it on ubuntu and try if it works? I have installed the IDE but there isn't any option for adding a source as in Windows

**Comment by Pablotis** [comment]
The only difference I see from the other version that uploads is that now it uses 0x00000 and 0x10000 and before it used 0x00000 and 0x40000

**Comment by igrr** [comment]
Looking at the log, there seems to be no reply from the ESP...
Do you reset the board manually?

**Comment by Pablotis** [comment]
During the procces?
