### ISSUE TITLE
ESP8266 01 and Arduino programming. 

### ISSUE THREAD

**Issue by mayur111118** [esp8266/Arduino#3050]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-01?
Core Version:      	?2.1.0-rc2?

### Description

Problem description
I have first checked ESP8266 01 using AT commands then I have also uploaded Blinky, WifiScan, WifiAccessPoint programs. ESP8266 is not responding to AT commands now. 
 Now I am doing a project on Home Automation but its code is not getting uploaded. It uses SoftwareSerial.h header. So how to proceed further. Please can anyone help me with circuit diagram or some steps.

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / ?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```espcomm_mem_failed.
   espcomm_upload_failed.

**Comment by madpilot** [comment]
That generally means the IDE can't talk to the ESP8266.

Check:

1.  Your FTDI cable is plugged in correctly
2. You have selected the correct serial port in the IDE
3. You have put the ES8266 in program mode (Pull GPIO 0 low during a reset)

See http://hackaday.com/2015/03/18/how-to-directly-program-an-inexpensive-esp8266-wifi-module/
