### ISSUE TITLE
CBOR ESP8266

### ISSUE THREAD

**Issue by ravenrole** [esp8266/Arduino#3056]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

```

### Debug Messages

```
messages here
```

Anyone knows how to use cbor in arduino or esp8266 ? can someone explain how it work ?  thx

**Comment by igrr** [comment]
This issue tracker is not a good place for "how do I..." kind of questions. It's main purpose is to collect information on issues and possible improvements to the codebase. Please use the community forum for coding help. Thanks.
