### ISSUE TITLE
Remove "python 3 not supported" from OTA docs

### ISSUE THREAD

**Issue by ccoenen** [esp8266/Arduino#3058]
The Docs state that OTA is not supposed to work with python 3. It does work flawlessly without any change.

It works fine from both within Arduino IDE and from command line.

It's mentioned in a few tutorials as well, but most importantly it should be changed right here:
https://github.com/esp8266/Arduino/tree/master/doc/ota_updates#application-example

**Comment by igrr** [comment]
Removed mention of python3 in 1c4a48db.
