### ISSUE TITLE
Can't re-enable WiFi after ESP.deepSleep(uS, WAKE_RF_DISABLED) ?

### ISSUE THREAD

**Issue by sheffieldnick** [esp8266/Arduino#3072]
#### Hardware
Hardware:			WeMos D1 mini
Core Version:      	v2.2.0

### Description

My sketch spends most of its time in deep sleep, just using the WiFi when it first powers up. This works fine from a full power-cycle, but not if is reset (reset button, or new sketch uploaded over serial). In that case I can't seem to switch the WiFi back on? I presume the RF is disabled from the deep sleep, even through a reset, and WiFi.mode(WIFI_STA) isn't enough to switch it back on?

I get:

```mode : sta(MAC)
add if0
f r0, 
error: pll_cal exceeds 2ms!!!
error: pll_cal exceeds 2ms!!!
error: pll_cal exceeds 2ms!!!
....
error: pll_cal exceeds 2ms!!!
error: pll_cal exceeds 2ms!!!
scandone
reconnect
f 0, error: pll_cal exceeds 2ms!!!
error: pll_cal exceeds 2ms!!!
error: pll_cal exceeds 2ms!!!
....
error: pll_cal exceeds 2ms!!!
error: pll_cal exceeds 2ms!!!
scandone
reconnect
f -180, error: pll_cal exceeds 2ms!!!
error: pll_cal exceeds 2ms!!!
error: pll_cal exceeds 2ms!!!
....
error: pll_cal exceeds 2ms!!!
error: pll_cal exceeds 2ms!!!
scandone
del if0
usl
mode : null
```

### Settings in IDE

Module:  			WeMos D1 R2 & mini
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		SERIAL
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <ESP8266WiFi.h>
extern "C" {
#include <user_interface.h>
}

void setup() {
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  // Connect to WiFi if we have just powered on (*not* if waking from deep sleep)
  rst_info *resetInfo = ESP.getResetInfoPtr();
  if (resetInfo->reason != REASON_DEEP_SLEEP_AWAKE) {
    WiFi.mode(WIFI_STA);
    WiFi.begin(WLAN_SSID, WLAN_PWD);
    WiFi.setAutoConnect(false);
    WiFi.setAutoReconnect(false);
    WiFi.waitForConnectResult();
    // do some networky stuff


    WiFi.disconnect();
    WiFi.mode(WIFI_OFF);
  }
}

void loop() {
  // do regular non-networking stuff

  // enter deep sleep, with radio off upon waking
  unsigned int sleep_secs = 10;
  ESP.deepSleep(sleep_secs*1000000, WAKE_RF_DISABLED);
}
```

NB: I'm using WiFi.setAutoConnect(false)/setAutoReconnect because otherwise the board was always trying to connect to the WiFi immediately upon waking from deep sleep, even if WiFi.disconnect(), WiFi.mode(WIFI_OFF) and WAKE_RF_DISABLED had been called.

**Comment by sheffieldnick** [comment]
#644 mentions using:
ESP.deepSleep(1, WAKE_RF_DEFAULT)
as a hack to switch the RF back on, but surely there is a better way?

**Comment by igrr** [comment]
No, unfortunately there isn't. If you ask it to do a deep sleep reset and wake up with RF disabled, RF is going to be exactly that — disabled.

**Comment by sheffieldnick** [comment]
OK, is there a fast way to test the RF disabled/enabled state? So my code can distinguish between my 'normal' REASON_DEEP_SLEEP_AWAKE, and when it comes awake from a brief deep sleep used to enable the RF?

**Comment by igrr** [comment]
Writing a flag into RTC memory prior to going into deep sleep is probably the easiest way. ESP8266 SDK doesn't provide a function to query RF state.

**Comment by sheffieldnick** [comment]
Thanks, that seems to be working nicely.

**Comment by sheffieldnick** [comment]
Just noticed this line in Esp.h:

`#define RF_MODE(mode) int __get_rf_mode() { return mode; }`

can't I use __get_rf_mode() to read the current RF state?

**Comment by jeanfbrito** [comment]
This is what I'm searching for. I was using LUA scripts on Nodemcu, but it eats alot of battery.
Now I will program in "Arduino" and need to get if the RF is ON, to then send the packets.

**Comment by JamesNewton** [comment]
How does one call __get_rf_mode() in an ino file?

**Comment by pfabri** [comment]
@JamesNewton 

Not sure about a .ino file. In a .cpp file you could do this: `extern int __get_rf_mode();`. This will then give you access to `__get_rf_mode()`, . You could then do `int mode = __get_rf_mode()`but according to my test this always returns `-1` regardless of the active RF_MODE. Sad, I know.

**Comment by pfabri** [comment]
I've discovered a **workable solution** in a [gist](https://gist.github.com/chaeplin/be4d9ca41a991aa327bb)

This is all you need to be able to toggle your WiFi chip after `ESP.deepsleep()` calls. Both functions work before and after any of these deepsleep invokations: `WAKE_RF_DEFAULT`, `WAKE_RF_DISABLED`, and probably the other two too, (`WAKE_RFCAL`, `WAKE_NO_RFCAL`), but these I have not tested.

	extern "C" {
		#include "user_interface.h"  // Required for wifi_station_connect() to work
	}

	#include <Arduino.h>
	#include <ESP8266WiFi.h>

	#define FPM_SLEEP_MAX_TIME 0xFFFFFFF

	void WiFiOn();
	void WiFiOff();

	//------------------------------------------------------------------------------

	void setup() {

		WiFiOn();
		delay(5000);
		WifiOff();
		delay(5000);
		ESP.deepSleep(1e6 * 10, WAKE_RF_DISABLED); // sleep 10 seconds
	
	}

	void loop() {
		;
	}
	//------------------------------------------------------------------------------

	void WiFiOn() {

		wifi_fpm_do_wakeup();
		wifi_fpm_close();

		//Serial.println("Reconnecting");
		wifi_set_opmode(STATION_MODE);
		wifi_station_connect();
		//wifi_connect();
	}


	void WiFiOff() {

		//Serial.println("diconnecting client and wifi");
		//client.disconnect();
		wifi_station_disconnect();
		wifi_set_opmode(NULL_MODE);
		wifi_set_sleep_type(MODEM_SLEEP_T);
		wifi_fpm_open();
		wifi_fpm_do_sleep(FPM_SLEEP_MAX_TIME);

	}

**Comment by 2000jago** [comment]
The code above does not compile verbatim.  Arduino IDE complains about line 19 "'WifiOff' was not declared in this scope"...

**Comment by pfabri** [comment]
@2000jago Yup, I wrote `WifiOff` instead of  `WiFiOff` by mistake. Corrected.

**Comment by 2000jago** [comment]
@pfabri I can confirm (on wemos D1 mini) this does indeed work and it works well.  Thank you sir!

**Comment by torntrousers** [comment]
Would be nice to add those functions to the core ESP.h class

**Comment by angeloh1969** [comment]
else
      {line = ("Conexion OK a WiFi");
        Serial.println (line);
       
      }
  return;
}

**Comment by mahesh2000** [comment]
hi, has anyone tested the power usage while in sleep mode? i'm getting 3mA and can't go lower. 3mA is too much for my purpose. thanks!

**Comment by ibaranov-cp** [comment]
Does your module have an LED? is it on? If so, that's likely your power drain.

**Comment by Tech-TX** [comment]
Regarding the original post, I tried every trick I could think of, and I have to agree with **igrr** about whether you can re-enable WiFi after ESP.deepSleep(time, WAKE_RF_DISABLED)

> No, unfortunately there isn't. If you ask it to do a deep sleep reset and wake up with RF disabled, RF is going to be exactly that — disabled.

**Comment by devyte** [comment]
Closing in view of previous comment.

**Comment by amadeuspzs** [comment]
I have spent many many hours trying to fix this until I came across this (closed) issue.

Please @igrr and team can you add to the documentation a warning about using WAKE_RF_DISABLED and the tip about using WAKE_RF_DEFAULT to get things up and running again?

**Comment by devyte** [comment]
@amadeuspzs Please make your proposal in a PR.

**Comment by Cicicok** [comment]
Actually I found another solution, which I've successfully tested. The trick is after waking from `WAKE_RF_DISABLED` the radio has to be put into sleep and immediatelly woken up.

```
WiFi.forceSleepBegin();
delay(1);
WiFi.forceSleepWake();
delay(1);
```

Source: https://www.bakke.online/index.php/2017/05/21/reducing-wifi-power-consumption-on-esp8266-part-2/

**Comment by Tech-TX** [comment]
Yep, works fine to wake the modem after ESP.deepSleep(timeus, WAKE_RF_DISABLED), thanks for finding that!  It boots at 38mA for about 1.5ms, then drops to 18mA and stays there until you enable the modem.

![WAKE_RF_DISABLED](https://user-images.githubusercontent.com/53401742/102289478-63b29880-3f04-11eb-9cf0-c2498b4256b3.gif)

I'll do a PR to add it to the docs.

I've a suspicion @torntrousers might find this of interest.  ;-)

**Comment by panosss** [comment]
> Actually I found another solution, which I've successfully tested. The trick is after waking from `WAKE_RF_DISABLED` the radio has to be put into sleep and immediatelly woken up.
> 
> ```
> WiFi.forceSleepBegin();
> delay(1);
> WiFi.forceSleepWake();
> delay(1);
> ```
> 
> Source: https://www.bakke.online/index.php/2017/05/21/reducing-wifi-power-consumption-on-esp8266-part-2/

Does not work for me, maybe something has changed in the code?

**Comment by nbolton** [comment]
> Does not work for me

Seems to still work for me. Maybe we have different versions?

**Comment by nbolton** [comment]
Hmm, or maybe not. It's a bit unpredictable. Sometimes after using the workaround (below), the ESP8266 will consume 40 mA (not the expected 70 mA), the connection will fail.

```
WiFi.forceSleepBegin();
delay(1);
WiFi.forceSleepWake();
delay(1);
```

After it gets in this state, the only way to fix it is to hard power cycle the ESP8266, or call `ESP.deepSleep(n, WAKE_RF_DEFAULT)`

**Comment by DavvidU** [comment]
> Hmm, or maybe not. It's a bit unpredictable. 

I don't know Your specific scenario or wether this will help You, but I'm able to wake up radio like this:

`WiFi.forceSleepWake();
  delay(10);
  WiFi.persistent(false);
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);`

after 

`ESP.deepSleep(sleepTime_us, WAKE_RF_DISABLED);`

if in the previous cycle I had also done this wake up. After I hit a cycle where I'm not calling the wake up code, in the next cycle the same wake up code won't work anymore.
