### ISSUE TITLE
Question: ESP8266HTTPClient POST octet-stream

### ISSUE THREAD

**Issue by adjavaherian** [esp8266/Arduino#3081]
#### Hardware
Hardware:		ESP-12F
Core Version:      	2.1.0-rc2

### Description

I've been looking high and low for a good example of how to use ESP8266HTTPClient to POST a binary stream.  This is about as far as I can get, but basically it looks like the server is not seeing the content-length and each request is treated like a discrete POST as opposed to a part of the stream.  Any help would be greatly appreciated.

### Sketch

```cpp

  SD.begin(0);
  File myFile = SD.open("1.JPG");
  String contentLength = String(myFile.size());

  if (myFile) {

    // http stuff
    HTTPClient http;
    int httpCode = 0;

    // start connection and add HTTP headers
    http.begin("http://192.168.0.101:8888/"); //HTTP

    http.addHeader("Content-Type", "application/octet-stream");
    http.addHeader("Content-Length", contentLength);

    // buffer
    byte clientBuf[64];
    int clientCount = 0;

    while (myFile.available()) {

      clientBuf[clientCount] = myFile.read();

      clientCount++;

      if (clientCount > 63) {
        Serial.println("> 63 POSTing");
        httpCode = http.sendRequest("POST", &clientBuf[clientCount], clientCount);
        clientCount = 0;
      }

    }

    Serial.println("END WHILE");

    if (clientCount > 0) {
      Serial.println("Send LAST buffer");
      httpCode = http.sendRequest("POST", &clientBuf[clientCount], clientCount);
    }

    // close the file:
    myFile.close();

    Serial.println("http code---");
    Serial.println(String(httpCode));

    if(httpCode > 0) {
        // HTTP header has been send and Server response header has been handled
        Serial.printf("[HTTP] POST... code: %d\n", httpCode);

        // file found at server
        if(httpCode == HTTP_CODE_OK) {

          String payload = http.getString();
          Serial.println("payload...");
          Serial.println(payload);
        }
    } else {
        Serial.printf("[HTTP] POST... failed, error: %s\n", http.errorToString(httpCode).c_str());
    }

    // END HTTP
    Serial.println("END http");
    http.end();


  }
```

So I'm seeing the requests and the buffer bodies on my local express server, and I'm getting 200 OK, but it looks like there's no continuity between POST requests.  Any ideas how to make this actually stream?

Thanks!

**Comment by devyte** [comment]
@adjavaherian I believe sendRequest() is meant to handle the entire body at once. In your case, you are calling it once for each piece of 64bytes, which ends with the behavior you observe: multiple complete POSTs instead of a single one with a stream of all your data.
I'm not an expert on http client, but you should look at the docs for it. There I found e.g.: this:

int HTTPClient::sendRequest (  const char *  type,
 Stream * | stream,
 size_t | size = 0) 

which I think is meant to stream a file.

If you need further assistance, please refer to esp8266.com or stackoverflow.
Closing due to usage error.
