### ISSUE TITLE
arduino ; esp8266; data; GET php

### ISSUE THREAD

**Issue by riteshp887** [esp8266/Arduino#3099]
Hey people!
I am also doing the same thing on a local server. I am calling a php script using AT commands. I am doing it right from the serial monitor so, i have not developed a code for it. I am listing out the AT commands.
AT+CIPSTART="TCP","192.168.43.12",80
AT+CIPSEND=90
GET /pandeyji/post.php?sen1=p&sen2=q&sen3=r HTTP/1.0\r\nHost: 192.168.43.12:80\r\n\r\n\r\n

THIS ONLY REPLIES ME WITH SEND OK. There's no problem with the php script or anything else. it's just something in the format i think. please help me out guys. I am stuck with this. Thank You

**Comment by devyte** [comment]
You are in the wrong repo. This is the Arduino-like core, not the AT command firmware.
Closing.
