### ISSUE TITLE
Esp8266fs tool dont visible in  menu after update on Arduino 1.8.2

### ISSUE THREAD

**Issue by pilnikov** [esp8266/Arduino#3112]
Arduino 1.8.2 banned Esp8266fs tool in menu. In 1.8.1 all work.

**Comment by jjssoftware** [comment]
I think you'd have more chance of getting a decent response if you were to raise an issue here: https://github.com/esp8266/arduino-esp8266fs-plugin/issues

**Comment by pilnikov** [comment]
Thank you. Yes, I think there will be better.
