### ISSUE TITLE
Arduino Board Support doesn't remove old builds

### ISSUE THREAD

**Issue by Makuna** [esp8266/Arduino#312]
After using the board manager to "install" the latest version; I checked the drive and found the last version I was using still present taking up space.  

Shouldn't this remove the old one or replace it?  
Should the name not change even though the version does?

**Comment by igrr** [comment]
If the name doesn't change, board manager will not download the new version
at all.
At least this is what happens with 1.6.4. Perhaps by the time 1.6.5 is
released this will be fixed.
