### ISSUE TITLE
wifi got ip event not connection failure for http requests

### ISSUE THREAD

**Issue by spiri439** [esp8266/Arduino#3135]
Hello,
This is my code below, I am new to wifi event, but it dosen't seem to work if I try to run a http post when event occurs.
#include <SPI.h>
#include <SD.h>
#include "ESP8266WiFi.h"
#include <ESP8266HTTPClient.h>

unsigned long timeNow = 0;
unsigned long timeLast = 0;

const int chipSelect = 4;
int seconds = 0;
int minutes;
int hours;
String identificator;

const char* ssid     = "SpiriMobile";
const char* password = "heineken";

void setup() {
  Serial.begin(115200);
  if (!SD.begin(chipSelect)) {
    Serial.println("Card failed, or not present");
    // don't do anything more:
    return;
  }
  readfile();
  Serial.println("card initialized.");
  WiFi.disconnect(true);
  delay(100);
  WiFi.onEvent(WiFiEvent);
  WiFi.begin(ssid, password);
  Serial.println("Setup done");
  
  
}

void loop() {
  uptime();
}

void uptime(){
    
    timeNow = millis()/1000; // the number of milliseconds that have passed since boot
    seconds = timeNow - timeLast;//the number of seconds that have passed since the last time 60 seconds was reached.
 
    if (seconds == 60) {
      timeLast = timeNow;
      minutes = minutes + 1;
      //seconds = seconds + 6;
      writefile();

    
    }
    
    if (minutes == 60){ 
      minutes = 0;
      hours = hours + 1;
      writefile();
    
    }

}

void WiFiEvent(WiFiEvent_t event) {
    //Serial.printf("[WiFi-event] event: %d\n", event);

    switch(event) {
        case WIFI_EVENT_STAMODE_GOT_IP:
            gethttp();
            Serial.println("WiFi connected");
            Serial.println("IP address: ");
            Serial.println(WiFi.localIP());
                        
            break;

        case WIFI_EVENT_STAMODE_DISCONNECTED:
            //Serial.println("WiFi lost connection");
            break;
    }
}

void readfile(){
  File dataFile = SD.open("datalog.txt");
  if (dataFile) {
    Serial.println("data:");
    while (dataFile.available()) {
      String myString = dataFile.readStringUntil('\n');
      int commaIndex = myString.indexOf(',');
      int secondCommaIndex = myString.indexOf(',', commaIndex + 1);
      identificator = myString.substring(0, commaIndex);
      String secondValue = myString.substring(commaIndex + 1, secondCommaIndex);
      String thirdValue = myString.substring(secondCommaIndex + 1);
      hours = secondValue.toInt();
      minutes = thirdValue.toInt();
      Serial.println(identificator);
      Serial.println(hours);
      Serial.println(minutes);
            
    }
    dataFile.close();
    return;
  } else {
    Serial.println("error opening datalog.txt");
    return;
  }
}

void writefile(){
        File dataFile = SD.open("datalog.txt", FILE_WRITE);
        if (dataFile) {
          dataFile.seek(0);
          dataFile.print(identificator);
          dataFile.print(",");
          dataFile.print(hours);
          dataFile.print(",");
          dataFile.println(minutes);
          dataFile.close();
          Serial.print(hours);
          Serial.print(":");
          Serial.print(minutes);
          Serial.print(":");
          Serial.println("Data Stored");
        }
        else {
          Serial.println("error opening datalog.txt");
        }
}
void posthttp(){
      
      HTTPClient http;    //Declare object of class HTTPClient
      Serial.println("Start transmission");
      http.begin("http://95.76.141.190:80/");      //Specify request destination
      http.addHeader("Content-Type", "text/plain");  //Specify content-type header
      
      int httpCode = http.POST("Message from ESP8266");   //Send the request
      String payload = http.getString();                                        //Get the response payload
      
      Serial.println(httpCode);   //Print HTTP return code
      Serial.println(payload);    //Print request response payload
      http.end();  //Close connection
 
}

void gethttp(){
  WiFiClient client;
  const int httpPort = 80;
  const char* host = "http://95.76.141.190";

  if (!client.connect(host, httpPort)) {
    Serial.println("connection failed");
    return;
  }
  
  // We now create a URI for the request
  String url = "/input/";
  url += "streamId";
  url += "?private_key=";
  url += "privateKey";
  url += "&value=";
  url += "value";
  
  Serial.print("Requesting URL: ");
  Serial.println(url);
  
  // This will send the request to the server
  client.print(String("GET ") + url + " HTTP/1.1\r\n" +
               "Host: " + host + "\r\n" + 
               "Connection: close\r\n\r\n");
  unsigned long timeout = millis();
  while (client.available() == 0) {
    if (millis() - timeout > 5000) {
      Serial.println(">>> Client Timeout !");
      client.stop();
      return;
    }
  }
  
  // Read all the lines of the reply from server and print them to Serial
  while(client.available()){
    String line = client.readStringUntil('\r');
    Serial.print(line);
  }
  
  Serial.println();
  Serial.println("closing connection");
  
  }

**Comment by igrr** [comment]
You can't run blocking IO functions in wifi event callbacks. Treat them as interrupts, and do minimal work in the callback. Perform actual network IO in the main loop.
