### ISSUE TITLE
Automated builds from appveyor fail

### ISSUE THREAD

**Issue by ozayturay** [esp8266/Arduino#316]
All items in the near history are red @ https://ci.appveyor.com/project/igrr/Arduino/history so there are no downloads in artifacts. And the green ones do not work because of old java version, though it can easily be fixed with replacing java folder with a newer one from official Arduino build or Java Installation.

@igrr Please fix appveyor builds, so windows users can follow newest additions easily. :)

**Comment by igrr** [comment]
Now that we have the board manager package updated every couple of days, do you think downloading the full installer is still a good option?

**Comment by ozayturay** [comment]
Yes i do, unless the DTR and RTS patch make place in official Arduino IDE for the Serial Monitor to work without problems side by side with autoreset feature.

**Comment by igrr** [comment]
OK will investigate what has happened to windows build.

**Comment by ozayturay** [comment]
Thank you for the interest. Is there a chance for DTR and RTS patch pull request in official Arduino source?

**Comment by Toshik** [comment]
https://github.com/esp8266/Arduino/pull/350 fix windows build

**Comment by igrr** [comment]
Thanks to @Toshik Windows builds are back online.

Regarding the patch, Arduino.cc guys are not very active to reply to my posts on the mailing list, so i'm not sure the DTR/RTS patch will be mainlined soon.

**Comment by ozayturay** [comment]
It's broken again. The last succesfull compile with an artifact is https://ci.appveyor.com/project/igrr/arduino/build/0.0.153/artifacts and i'm using this build with a portable subfolder so that ESP8266 specific BM packages don't mix up my latest Arduino enviroment.

But i guess for new functions like OTA Update from Arduino IDE version 1.6.7 or newer is needed.

http://esp8266.github.io/Arduino/versions/2.3.0/doc/ota_updates/readme.html#arduino-ide

@igrr : Can you please fix it so that we can have a recent artifact at least one more time. Thank you. :)

**Comment by igrr** [comment]
@ozayturay as you may have noticed, IDE files have been removed from our repository about a year ago, as was appveyor.yml build script. We no longer support building the complete IDE package.

The method you use with portable subfolder makes sense, that's what i'm doing myself to keep different versions separate.

If what you need is the DTR/RTS patch, feel free to do a git clone of https://github.com/arduino/Arduino/pull/4102 and build IDE from source.

**Comment by ozayturay** [comment]
Oh i haven't noticed it since i was using board manager with 0.153 appveyor artifact. I better do as what you said and compile it myself one more time. :)

**Comment by cranphin** [comment]
Is that a 1.6.9 with support for controlling DTR/RTS in serial monitor? I'd be interested :) No idea why it isn't in main yet tho.. XD

**Comment by ozayturay** [comment]
Indeed. I have compiled currently latest 1.6.11 version with the same patch and it works as expected. You can download it from my https://github.com/ozayturay/Arduino-ESP8266 repository.

The package you download is only the Arduino IDE, you have to manually get the ESP8266 toolchain via board manager or any other method as instructed at https://github.com/esp8266/Arduino repository.

The archive has an empty folder named portable in it for not using user directories for the toolchain, if you don't want a portable installation just delete this folder before using the board manager.

**Comment by cranphin** [comment]
Works! Awesome, thanks :)

**Comment by ozayturay** [comment]
Compilation instuctions in the comment https://github.com/esp8266/Arduino/issues/22#issuecomment-91043388 updated, 1.6.11 compiled without problems and works as expected.
