### ISSUE TITLE
Client Page Bug

### ISSUE THREAD

**Issue by hackerjdx** [esp8266/Arduino#3174]
Whenever I go to client and then click "scan" then the wifi (pwned) logs me out and doesnt allow me to find or select my clients. Plz help!!!

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by igrr** [comment]
Guessing from the scarce issue description that you are using https://github.com/spacehuhn/esp8266_deauther. Please report the issue on that project's issue tracker instead.
