### ISSUE TITLE
Spi Slave onData

### ISSUE THREAD

**Issue by paraflou** [esp8266/Arduino#3175]
#### Hardware
Hardware:			?ESP8266EX?
Core Version:      	?2.1.0-rc2?

### Description

Error in rest request inside SPI slave interrupt handler

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch
#include "SPISlave.h"
#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <ESP8266HTTPClient.h>

ESP8266WiFiMulti WiFiMulti;

void setup()
{
  Serial.begin(115200);
  Serial.setDebugOutput(true);

  Serial.println();
  Serial.println();
  Serial.println();

  for (uint8_t t = 4; t > 0; t--) {
    Serial.printf("[SETUP] WAIT %d...\n", t);
    Serial.flush();
    delay(1000);
  }

  WiFiMulti.addAP("mywifi", "mypass");

  SPISlave.onData([](uint8_t * data, size_t len) {
    Serial.printf("Data sent from LPC ---> %s\n", (char *)data);
    if ((WiFiMulti.run() == WL_CONNECTED)) {
      HTTPClient http2;
      http2.begin("http://192.168.100.128/api/VCjFqKcClx7j71q68myC5GqzEDnRpcaNbJvlOF5r/lights/15/state");

      char putpayload2[30] = "";
      strcpy(putpayload2, "{\"hue\":10}");
      //strcat(putpayload2, (char *)data);
      //strcat(putpayload2, "}");
      Serial.printf("Put payload2 is: %s\n", putpayload2);
      int httpCode2 = http2.PUT(putpayload2);

      // httpCode will be negative on error
      if (httpCode2 > 0) {
        // HTTP header has been send and Server response header has been handled
        Serial.printf("[HTTP] PUT... code: %d\n", httpCode2);
        // file found at server
        if (httpCode2 == HTTP_CODE_OK) {
          String payload2 = http2.getString();
          Serial.println(payload2);
        }
      } else {
        Serial.printf("[HTTP] PUT... failed, error: %s\n", http2.errorToString(httpCode2).c_str());
      }
      http2.end();
    }
  });
  SPISlave.begin();
}

void loop() {}

### Debug Messages

Put payload2 is: {"hue":10}
[HTTP] PUT... failed, error: connection refused

### Issue
I am using httpclient and spi slave libraries. These libraries work fine on their own.
I can send rest requests to my specific rest server and I can "hear" interrupts in spi when my uC (LPC4367) sends data from spi.

The problem is when i try to implement a simple rest action inside interrupt hander onData from spi slave library the above error occurs. FIY in terms of c code i have implemented this and it works!

Any help or ideas?

Thanks a lot in advance

**Comment by igrr** [comment]
onData is essentially called from an interrupt handler. You can't call network or other IO functions from an interrupt; instead, set a flag in the interrupt handler and check it in the main loop.
