### ISSUE TITLE
using STA mode get ssid, password -> using AP mode!

### ISSUE THREAD

**Issue by gkgk3442** [esp8266/Arduino#3184]
Using esp 8266!
Always use STA mode, ssid and password are entered on the web page.
I want to enable AP mode using the ssid and password entered.
Is there a way?

1. Always use AP + STA
2. STA -> web page get ssid and password
3. AP -> get ssid, password using connect WIFI

Sorry about my inadequate English ability.

**Comment by jjssoftware** [comment]
Sure, that's possible - have you seen these:

* https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/doc/esp8266wifi/soft-access-point-examples.md
* https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/doc/esp8266wifi/soft-access-point-class.md
