### ISSUE TITLE
Json url on github ?

### ISSUE THREAD

**Issue by Testato** [esp8266/Arduino#319]
i have a pullrequest for your Board Manager Json Url. The file at http://arduino.esp8266.com/package_esp8266com_index.json

Is it present on GitHub ?

**Comment by igrr** [comment]
https://github.com/esp8266/Arduino/blob/esp8266/build/build_board_manager_package.sh

**Comment by Testato** [comment]
https://github.com/esp8266/Arduino/pull/320

**Comment by igrr** [comment]
Thanks, merged that.
