### ISSUE TITLE
Latest UART buffers break Serial.swap()

### ISSUE THREAD

**Issue by riataman** [esp8266/Arduino#3192]
I have a NodeMCU, I was using Serial.swap() just fine with 2.3.0. After upgrading to master Serial.swap doesn't work anymore. 

If I backup the serial buffer changes it works again.

**Comment by igrr** [comment]
By "doesn't work", you mean that the output is still sent to the original pins after `swap`? Or some other issue?

**Comment by igrr** [comment]
@riataman  Can you confirm that the issue is that you can not `swap` back to the original pins?

**Comment by riataman** [comment]
Sorry, I haven't been able to get back to test this, but as I remember I was just calling ´Serial.swap´ once and the alternative pins didn't worked.

I'll try to get back to test this again soon.

**Comment by devyte** [comment]
@riataman ping

**Comment by d-a-v** [comment]
Closing due to age and because `Serial.swap()` is working.
Please open a new issue with more details if your tests are not satisfactory.
