### ISSUE TITLE
sd card

### ISSUE THREAD

**Issue by schlaegerz** [esp8266/Arduino#3196]
I am trying to write a large string to an SD card (~16000 bytes)

 res = file.write(text, length);
Text is allocated on the heap and is about 2000 characters bigger than length.

And I'm getting this crash:
Exception 9: LoadStoreAlignmentCause: Load or store to an unaligned address
0x40214bfc: SPIClass::writeBytes_(unsigned char*, unsigned char) 
0x40213233: spiRec 
0x40214c64: SPIClass::writeBytes(unsigned char*, unsigned int)
0x402136d5: Sd2Card::writeData(unsigned char, unsigned char const*)
0x40213745: Sd2Card::writeBlock(unsigned int, unsigned char const*)
0x402140fd: SdFile::write(void const*, unsigned short) 
0x4010068c: free 

WIth the same code I was able to write bigger different files, but some particular times it just seems to crash. 

I am not sure what else to look into to figure out why this is crashing.

#### Hardware
Hardware:			NodeMCU (ESP-12E module)
Core Version:      	?2.1.0-rc2?

**Comment by akaJes** [comment]
you can try updated library https://github.com/greiman/SdFat/ or https://github.com/greiman/SdFat-beta
i had various issues with embedded library also

**Comment by devyte** [comment]
@schlaegerz which core version? What are the IDE settings? Ehat is the sketch?
Please attach a text file with the text content. Please post a minimal example to reproduce the issue.

**Comment by schlaegerz** [comment]
Its been a long time since I posted this, so its hard to say. I believe this ended up being an issue of the library corrupting the sd card when it shut down in the middle of a write.

**Comment by devyte** [comment]
@igrr I don't think there is much that can be done in this case. FAT file system corruption is always a risk with unexpected shutdowns.
Unless you had something specific in mind when you took a look, I propose closing this.

**Comment by schlaegerz** [comment]
It would help to suggest using O_SYNC more often, that helped corrupt my file system significantly less. 

Also, it should be possible to do a bit better validation so that it doesn't just completely crash when the file system isn't completely right.

**Comment by devyte** [comment]
This requires changes in the low level FAT lib, and I don't know if/when that will be done. Removing milestone in the meantime.

**Comment by devyte** [comment]
Will be addressed, as far as possible, with the new SDFS.

**Comment by earlephilhower** [comment]
Closing for now.  We've moved to a completely new SDFat library (and away from the old Arduino frozen copy of SD.h) and SPI is taking care of memory alignment as far as we've weel.  Open with a MCVE if you can reproduce with current GIT.
