### ISSUE TITLE
ESP8266 OTA updates using https not working - get Fatal exception 29(StoreProhibitedCause):

### ISSUE THREAD

**Issue by cirdiam** [esp8266/Arduino#3207]
I can get OTA updates working using http, but not using https
I'm using Arduino IDE 1.6.9, ESP8266 cores 2.3.0, an ESP8266-12E

code is:
#include <Arduino.h>

#include <ESP8266WiFi.h> 
#include <ESP8266WiFiMulti.h> 

#include <ESP8266HTTPClient.h>
#include <ESP8266httpUpdate.h>
#include <WiFiClientSecure.h>

#define USE_SERIAL Serial

ESP8266WiFiMulti WiFiMulti; //use this when using ESP8266WiFiMulti.h

const char* ssid = "...my ssid..";
const char* pass = "..my router password";
const char* host = "www.aquaswift.ca";  
const int httpsPort = 443;
const char* fingerprint = "fe a4 1f 46 64 35 19 6a d7 5a 08 a2 9d 20 62 24 6b e9 fd ef"; 

void setup() {

 //setup serial port
    USE_SERIAL.begin(115200);
    USE_SERIAL.setDebugOutput(true);

    USE_SERIAL.println();
    USE_SERIAL.println();
    USE_SERIAL.println();

    for(uint8_t t = 4; t > 0; t--) {
        USE_SERIAL.printf("[SETUP] WAIT %d...\n", t);
        USE_SERIAL.flush();
        delay(1000);
    }

  //connect to wifi
    WiFiMulti.addAP(ssid, pass); //use this when using ESP8266WiFiMulti.h
    
    // wait for WiFi connection
    Serial.println();    
    Serial.print("Waiting for wifi");    
    while (WiFiMulti.run() != WL_CONNECTED) { //use this when using ESP8266WiFiMulti.h
      Serial.print(".");
      delay(500);    
    }
    Serial.println();
    Serial.println("WiFi connected");
    Serial.println();
    Serial.print("WiFi connected.  IP address:");
    Serial.println(WiFi.localIP()); 

  //establish a connection to remote web server
    // Use WiFiClientSecure class to create TLS connection
    WiFiClientSecure client;
    Serial.print("connecting to ");
    Serial.println(host);
    if (!client.connect(host, httpsPort)) {
      Serial.println("connection failed");
      return;
    }
  
    if (client.verify(fingerprint, host)) {
      Serial.println("certificate matches");
    } else {
      Serial.println("certificate doesn't match");
    }

      if((WiFiMulti.run() == WL_CONNECTED)) { 
  
          //t_httpUpdate_return ret = ESPhttpUpdate.update("http://server/file.bin");
          //t_httpUpdate_return  ret = ESPhttpUpdate.update("https://server/file.bin");
  
          Serial.println("About to do OTA firmware update");
          delay(100);
          
          t_httpUpdate_return ret = ESPhttpUpdate.update("https://aquaswift.ca/fw/blink.bin","","fe a4 1f 46 64 35 19 6a d7 5a 08 a2 9d 20 62 24 6b e9 fd ef");

          switch(ret) {
              case HTTP_UPDATE_FAILED:
                  USE_SERIAL.printf("HTTP_UPDATE_FAILD Error (%d): %s", ESPhttpUpdate.getLastError(), ESPhttpUpdate.getLastErrorString().c_str());
                  break;
  
              case HTTP_UPDATE_NO_UPDATES:
                  USE_SERIAL.println("HTTP_UPDATE_NO_UPDATES");
                  break;
  
              case HTTP_UPDATE_OK:
                  USE_SERIAL.println("HTTP_UPDATE_OK");
                  break;
          }
          Serial.println("Finished attempt to do OTA firmware update");
      }
    
    Serial.println("Doing rest of setup");
    pinMode(2, OUTPUT);
    
}

void loop() {
  digitalWrite(2, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(200);              // wait for a second
  digitalWrite(2, LOW);    // turn the LED off by making the voltage LOW
  delay(200);              // wait for a second
}

=================================================
output on serial port after first run after download is:

[SETUP] WAIT 4...
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 16
cnt 

connected with 2GHz, channel 6
dhcp client start...
[SETUP] WAIT 3...
ip:192.168.1.147,mask:255.255.255.0,gw:192.168.1.1
[SETUP] WAIT 2...
[SETUP] WAIT 1...

Waiting for wifi
WiFi connected

WiFi connected.  IP address:192.168.1.147
connecting to www.aquaswift.ca
please start sntp first !
certificate matches
About to do OTA firmware update
please start sntp first !
Fatal exception 29(StoreProhibitedCause):
epc1=0x4000e1b2, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

Exception (29):
epc1=0x4000e1b2 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff0bc0 end: 3fff11b0 offset: 01a0

>>>stack>>>
3fff0d60:  00000040 00000082 3fffaf2c 402252c9  
3fff0d70:  3fff96e4 3fff91dc 00000000 00000041  
3fff0d80:  00000040 0000003f 00000000 00000041  
3fff0d90:  3fffbc5c 00000000 3fff8fbc 3fff96cc  
3fff0da0:  3fffbd58 3fff8fd4 3fff91dc 3fff91dc  
3fff0db0:  00000040 3fff91dc 3fffaf2c 3fff91dc  
3fff0dc0:  00000040 3fff91dc 3fffaf2c 40225dfe  
3fff0dd0:  3fff926c 0000003f 0be8633a 00000020  
3fff0de0:  3fff4b14 3fff91dc 3fff94c4 00000020  
3fff0df0:  3fff4b14 3fff91dc 00000010 402260e4  
3fff0e00:  3fff613c 3fff94ac 3fff94c4 00000001  
3fff0e10:  00000001 3fff94c4 3fff6fc1 40224ebc  
3fff0e20:  00000100 3fff923c 3fff6fbf 00000000  
3fff0e30:  00000100 3fff923c 3fff6fbf 402270e5  
3fff0e40:  3fff0e70 00000000 000000d0 00000030  
3fff0e50:  549ddb7a cd0b3f65 39fd87c3 00000004  
3fff0e60:  00000004 3fff406c 3fff6fb9 402231f0  
3fff0e70:  5b600203 6baea338 179e3d83 a83f3c9f  
3fff0e80:  f177addf 168a51ae d3e02927 84c336dd  
3fff0e90:  d6205a6d 9f1001f6 0461cecf db7af600  
3fff0ea0:  00000004 3fff6fb9 3fff406c 402235f1  
3fff0eb0:  e8942017 874aed4c 49a9eeb3 3fff60fc  
3fff0ec0:  00000000 00000004 00000004 40203877  
3fff0ed0:  3fff6fbd 3fff6fb9 3fff8aa4 00000e00  
3fff0ee0:  00000e98 3fff7e22 0000002e 00000004  
3fff0ef0:  3fff406c 3fff6fb9 00000004 00000004  
3fff0f00:  00000004 3fff6fb9 3fff406c 40222fe8  
3fff0f10:  00000000 3fff6fb9 3fff406c 40223390  
3fff0f20:  0000000c 3fff2424 0000000d 401004d8  
3fff0f30:  3fff0f80 0000000e 00000010 00000000  
3fff0f40:  3fff221c 3fff2424 3fff406c 01000000  
3fff0f50:  3fff0f80 3fff61dc 3fff406c 40223140  
3fff0f60:  40203658 00004ba0 3fff0190 00001387  
3fff0f70:  00007dbb 3fff61dc 3fff673c 40203d19  
3fff0f80:  000001bb 3fff6684 3fff61dc 402030d6  
3fff0f90:  252bb46b 00000000 3fff0fd0 00000000  
3fff0fa0:  000001bb 3fff61dc 3fff2424 4020406d  
3fff0fb0:  3ffe93b8 252bb46b 3ffe93b8 252bb46b  
3fff0fc0:  3fff1178 00000000 3fff10a0 40204880  
3fff0fd0:  00000000 00000000 3fff4b04 402065fb  
3fff0fe0:  00000000 00000000 3fff10a0 40204d60  
3fff0ff0:  3fff4b10 00000000 3fff4af8 402067a5  
3fff1000:  3ffe9210 00000000 00000000 40206f54  
3fff1010:  3ffe9198 0000093e 3fff10a0 4020472f  
3fff1020:  3fff105c 00000000 3fff105c 3fff00ac  
3fff1030:  3fff1178 3ffeffe0 3fff10a0 40204e0e  
3fff1040:  3fff1178 3ffeffe0 3fff10a0 402053ed  
3fff1050:  00000000 00000000 00000000 3ffe9210  
3fff1060:  00000000 00000000 000008c3 4010020c  
3fff1070:  00000000 3ffeffe0 3fff111c 4010068c  
3fff1080:  4021f2fe 3fff00cc 3fff1178 3fff116c  
3fff1090:  3fff1184 3ffeffe0 3fff1178 402055e5  
3fff10a0:  3fff652c 3fff61dc 3fff2424 0000000f  
3fff10b0:  0000000c 000001bb 00011f40 3fff243c  
3fff10c0:  0000000f 0000000d 3fff64bc 0000000f  
3fff10d0:  00000005 3fff49fc 000000ef 000000e7  
3fff10e0:  3fff64ec 0000001f 00000013 3fff6514  
3fff10f0:  0000000f 00000000 3fff4af8 00000001  
3fff1100:  00000000 ffffffff 3fff1100 00000000  
3fff1110:  00000000 00000000 00000000 00000000  
3fff1120:  00000000 00000000 3fff116c 4020667e  
3fff1130:  3ffe8f70 00000064 00000064 3fff0188  
3fff1140:  3ffeff84 3ffeffe0 3fff00cc 4020244f  
3fff1150:  3ffe90e8 00000000 000003e8 feefeffe  
3fff1160:  00000000 3fff21f4 3fff23d4 3fff6474  
3fff1170:  0000003f 0000003b 3fff2264 0000000f  
3fff1180:  00000000 3fff23ec 0000002f 00000021  
3fff1190:  3fffdad0 00000000 3fff0180 40207150  
3fff11a0:  feefeffe feefeffe 3fff0190 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,7)

 ets Jan  8 2013,rst cause:4, boot mode:(1,7)

wdt reset

=====if I power cycle then I get the following:
[SETUP] WAIT 4...
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
[SETUP] WAIT 3...
state: 3 -> 5 (10)
add 0
aid 16
cnt 

connected with 2GHz, channel 6
dhcp client start...
[SETUP] WAIT 2...
ip:192.168.1.147,mask:255.255.255.0,gw:192.168.1.1
[SETUP] WAIT 1...

Waiting for wifi
WiFi connected

WiFi connected.  IP address:192.168.1.147
connecting to www.aquaswift.ca
please start sntp first !
certificate matches
About to do OTA firmware update
please start sntp first !
Fatal exception 29(StoreProhibitedCause):
epc1=0x4000e1b2, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

Exception (29):
epc1=0x4000e1b2 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff0bc0 end: 3fff11b0 offset: 01a0

>>>stack>>>
3fff0d60:  00000040 00000082 3fffaf4c 402252c9  
3fff0d70:  3fff9664 3fff915c 00000000 00000041  
3fff0d80:  00000040 0000003f 00000000 00000041  
3fff0d90:  3fffbc04 3fff1f98 3fffaf64 3fff964c  
3fff0da0:  3fffbd00 3fff40ac 3fff915c 3fff915c  
3fff0db0:  00000040 3fff915c 3fffaf4c 3fff915c  
3fff0dc0:  00000040 3fff915c 3fffaf4c 40225dfe  
3fff0dd0:  3fff91ec 0000003f 8ae2a550 00000020  
3fff0de0:  3fff245c 3fff915c 3fff9444 00000020  
3fff0df0:  3fff245c 3fff915c 00000010 402260e4  
3fff0e00:  3fff2404 3fff942c 3fff9444 00000001  
3fff0e10:  00000001 3fff9444 3fff706c 40224ebc  
3fff0e20:  00000100 3fff91bc 3fff6fbf 00000000  
3fff0e30:  00000100 3fff91bc 3fff6fbf 402270e5  
3fff0e40:  3fff0e70 00000000 000000d0 00000030  
3fff0e50:  13cd9434 c7190000 3fff66cc 00000004  
3fff0e60:  00000004 3fff3ff4 3fff6fb9 402231f0  
3fff0e70:  afbc0203 2314a19f 6e1fc76b 3ab5d242  
3fff0e80:  5f70fb79 67032e76 f535803e a2065c98  
3fff0e90:  dcaa7085 9fa219f6 0b8a3c0c 943481cf  
3fff0ea0:  00000004 3fff6fb9 3fff3ff4 402235f1  
3fff0eb0:  00000000 600011f0 3fff66cc 3fff61a4  
3fff0ec0:  00000000 00000004 00000004 40203877  
3fff0ed0:  3fff6fbd 3fff6fb9 3fff8aa4 00000e00  
3fff0ee0:  00000e98 3fff7e22 0000002e 00000004  
3fff0ef0:  3fff3ff4 3fff6fb9 00000004 00000004  
3fff0f00:  00000004 3fff6fb9 3fff3ff4 40222fe8  
3fff0f10:  00000000 3fff6fb9 3fff3ff4 40223390  
3fff0f20:  0000000c 3fff64f4 0000000d 401004d8  
3fff0f30:  3fff0f80 0000000e 00000010 00000000  
3fff0f40:  3fff221c 3fff64f4 3fff3ff4 01000000  
3fff0f50:  3fff0f80 3fff6154 3fff3ff4 40223140  
3fff0f60:  40203658 00002510 3fff0190 00001387  
3fff0f70:  000016e9 3fff6154 3fff6174 40203d19  
3fff0f80:  000001bb 3fff66cc 3fff6154 402030d6  
3fff0f90:  252bb46b 00000000 3fff0fd0 00000000  
3fff0fa0:  000001bb 3fff6154 3fff64f4 4020406d  
3fff0fb0:  3ffe93b8 252bb46b 3ffe93b8 252bb46b  
3fff0fc0:  3fff1178 00000000 3fff10a0 40204880  
3fff0fd0:  00000000 00000000 3fff4b04 402065fb  
3fff0fe0:  00000000 00000000 3fff10a0 40204d60  
3fff0ff0:  3fff4b10 00000000 3fff4af8 402067a5  
3fff1000:  3ffe9210 00000000 00000000 40206f54  
3fff1010:  3ffe9198 000008c3 3fff10a0 4020472f  
3fff1020:  3fff105c 00000000 3fff105c 3fff00ac  
3fff1030:  3fff1178 3ffeffe0 3fff10a0 40204e0e  
3fff1040:  3fff1178 3ffeffe0 3fff10a0 402053ed  
3fff1050:  00000000 00000000 00000000 3ffe9210  
3fff1060:  00000000 00000000 000008ce 4010020c  
3fff1070:  00000000 3ffeffe0 3fff111c 4010068c  
3fff1080:  4021f2fe 3fff00cc 3fff1178 3fff116c  
3fff1090:  3fff1184 3ffeffe0 3fff1178 402055e5  
3fff10a0:  3fff61d4 3fff6154 3fff64f4 0000000f  
3fff10b0:  0000000c 000001bb 00011f40 3fff650c  
3fff10c0:  0000000f 0000000d 3fff6524 0000000f  
3fff10d0:  00000005 3fff49fc 000000ef 000000e7  
3fff10e0:  3fff6114 0000001f 00000013 3fff613c  
3fff10f0:  0000000f 00000000 3fff4af8 00000001  
3fff1100:  00000000 ffffffff 3fff1100 00000000  
3fff1110:  00000000 00000000 00000000 00000000  
3fff1120:  00000000 00000000 3fff116c 4020667e  
3fff1130:  3ffe8f70 00000064 00000064 3fff0188  
3fff1140:  3ffeff84 3ffeffe0 3fff00cc 4020244f  
3fff1150:  3ffe90e8 00000000 000003e8 feefeffe  
3fff1160:  00000000 3fff21f4 3fff23d4 3fff64ac  
3fff1170:  0000003f 0000003b 3fff2264 0000000f  
3fff1180:  00000000 3fff6474 0000002f 00000021  
3fff1190:  3fffdad0 00000000 3fff0180 40207150  
3fff11a0:  feefeffe feefeffe 3fff0190 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v09f0c112
~ld
ÿ

[SETUP] WAIT 4...
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 16
cnt 

connected with 2GHz, channel 6
dhcp client start...
[SETUP] WAIT 3...
ip:192.168.1.147,mask:255.255.255.0,gw:192.168.1.1
[SETUP] WAIT 2...
[SETUP] WAIT 1...

Waiting for wifi
WiFi connected

WiFi connected.  IP address:192.168.1.147
connecting to www.aquaswift.ca
please start sntp first !
certificate matches
About to do OTA firmware update
please start sntp first !
Fatal exception 29(StoreProhibitedCause):
epc1=0x4000e1b2, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

Exception (29):
epc1=0x4000e1b2 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff0bc0 end: 3fff11b0 offset: 01a0

>>>stack>>>
3fff0d60:  00000040 00000082 3fffaf34 402252c9  
3fff0d70:  3fff9664 3fff915c 00000000 00000041  
3fff0d80:  00000040 0000003f 00000000 00000041  
3fff0d90:  3fffbbec 3fff1f98 3fffaf4c 3fff964c  
3fff0da0:  3fffbce8 3fff3ff4 3fff915c 3fff915c  
3fff0db0:  00000040 3fff915c 3fffaf34 3fff915c  
3fff0dc0:  00000040 3fff915c 3fffaf34 40225dfe  
3fff0dd0:  3fff91ec 0000003f fe0f0e90 00000020  
3fff0de0:  3fff6784 3fff915c 3fff9444 00000020  
3fff0df0:  3fff6784 3fff915c 00000010 402260e4  
3fff0e00:  3fff6124 3fff942c 3fff9444 00000001  
3fff0e10:  00000001 3fff9444 3fff6ff4 40224ebc  
3fff0e20:  00000100 3fff91bc 3fff6fbf 00000000  
3fff0e30:  00000100 3fff91bc 3fff6fbf 402270e5  
3fff0e40:  3fff0e70 00000000 000000d0 00000030  
3fff0e50:  0eec9eb1 c7190000 3fff6684 00000004  
3fff0e60:  00000004 3fff406c 3fff6fb9 402231f0  
3fff0e70:  464d0203 6b895dbb 1f1c157f d477362e  
3fff0e80:  b62fab0b 2c9a415b 6c1be454 70a7fd75  
3fff0e90:  53289207 b50792a7 d4111440 9eb1f814  
3fff0ea0:  00000004 3fff6fb9 3fff406c 402235f1  
3fff0eb0:  00000000 600011f0 3fff6684 3fff60fc  
3fff0ec0:  00000000 00000004 00000004 40203877  
3fff0ed0:  3fff6fbd 3fff6fb9 3fff8aa4 00000e00  
3fff0ee0:  00000e98 3fff7e22 0000002e 00000004  
3fff0ef0:  3fff406c 3fff6fb9 00000004 00000004  
3fff0f00:  00000004 3fff6fb9 3fff406c 40222fe8  
3fff0f10:  00000000 3fff6fb9 3fff406c 40223390  
3fff0f20:  0000000c 3fff2424 0000000d 401004d8  
3fff0f30:  3fff0f80 0000000e 00000010 00000000  
3fff0f40:  3fff221c 3fff2424 3fff406c 01000000  
3fff0f50:  3fff0f80 3fff61dc 3fff406c 40223140  
3fff0f60:  40203658 00004ba0 3fff0190 00001387  
3fff0f70:  0000175b 3fff61dc 3fff673c 40203d19  
3fff0f80:  000001bb 3fff6684 3fff61dc 402030d6  
3fff0f90:  252bb46b 00000000 3fff0fd0 00000000  
3fff0fa0:  000001bb 3fff61dc 3fff2424 4020406d  
3fff0fb0:  3ffe93b8 252bb46b 3ffe93b8 252bb46b  
3fff0fc0:  3fff1178 00000000 3fff10a0 40204880  
3fff0fd0:  00000000 00000000 3fff4b04 402065fb  
3fff0fe0:  00000000 00000000 3fff10a0 40204d60  
3fff0ff0:  3fff4b10 00000000 3fff4af8 402067a5  
3fff1000:  3ffe9210 00000000 00000000 40206f54  
3fff1010:  3ffe9198 0000093e 3fff10a0 4020472f  
3fff1020:  3fff105c 00000000 3fff105c 3fff00ac  
3fff1030:  3fff1178 3ffeffe0 3fff10a0 40204e0e  
3fff1040:  3fff1178 3ffeffe0 3fff10a0 402053ed  
3fff1050:  00000000 00000000 00000000 3ffe9210  
3fff1060:  00000000 00000000 000008c3 4010020c  
3fff1070:  00000000 3ffeffe0 3fff111c 4010068c  
3fff1080:  4021f2fe 3fff00cc 3fff1178 3fff116c  
3fff1090:  3fff1184 3ffeffe0 3fff1178 402055e5  
3fff10a0:  3fff652c 3fff61dc 3fff2424 0000000f  
3fff10b0:  0000000c 000001bb 00011f40 3fff243c  
3fff10c0:  0000000f 0000000d 3fff64bc 0000000f  
3fff10d0:  00000005 3fff49fc 000000ef 000000e7  
3fff10e0:  3fff64ec 0000001f 00000013 3fff6514  
3fff10f0:  0000000f 00000000 3fff4af8 00000001  
3fff1100:  00000000 ffffffff 3fff1100 00000000  
3fff1110:  00000000 00000000 00000000 00000000  
3fff1120:  00000000 00000000 3fff116c 4020667e  
3fff1130:  3ffe8f70 00000064 00000064 3fff0188  
3fff1140:  3ffeff84 3ffeffe0 3fff00cc 4020244f  
3fff1150:  3ffe90e8 00000000 000003e8 feefeffe  
3fff1160:  00000000 3fff21f4 3fff23d4 3fff6474  
3fff1170:  0000003f 0000003b 3fff2264 0000000f  
3fff1180:  00000000 3fff23ec 0000002f 00000021  
3fff1190:  3fffdad0 00000000 3fff0180 40207150  
3fff11a0:  feefeffe feefeffe 3fff0190 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v09f0c112
~ld
þ

[SETUP] WAIT 4...
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 16
cnt 

connected with 2GHz, channel 6
dhcp client start...

======running flash config example gives the following output:
Flash real id:   001640E0
Flash real size: 4194304

Flash ide  size: 4194304
Flash ide speed: 40000000
Flash ide mode:  DIO
Flash Chip configuration ok.

=============
I've tried it with 2 different ESP8266-12E chips - both give same results
I've tried running off fully charged 6V battery thru a 1amp 3.3v regulator
and running off bench supply set to deliver 1amp at 5v thru 1amp 3.3v regulator
Same problem every time.  But works fine if I use http instead of https.  almost seems like there's a bug in ESP8266httpUpdate, as it works with http, but not https.

I've tried configuring as 4M (3M SPIFFS), and 4M (1M SPIFFS) and get same problem.

Anybody know what the fix is?  Could it be related to this: http://bbs.espressif.com/viewtopic.php?t=1791

**Comment by igrr** [comment]
OTA over https should now be possible, as memory footprint of axTLS has been improved.
