### ISSUE TITLE
vsnprintf => ESP crashes on start

### ISSUE THREAD

**Issue by Adminius** [esp8266/Arduino#3221]
#### Hardware
Hardware:			ESP-12F on WeMos D1 mini R2
Core Version:      	2.3.0

### Description

i have a problem with a vsnprintf function.
I use this https://github.com/KONNEKTING/KonnektingDeviceLibrary/blob/master/src/DebugUtil.h debug-lib
ESP crashes on start and only stack error is shown.
This lib works fine on 328p, 32u4 and SAMD21...

### Settings in IDE

Module:  			WeMos D1 R2 & mini
Flash Size: 		4MB (3M SPIFFS)
CPU Frequency:		80Mhz

### Debug Messages

Stack and decode:
https://gist.github.com/Adminius/4a08ac05888eb674dd5c11598214be49

### Sketch

```
//https://github.com/KONNEKTING/KonnektingDeviceLibrary/blob/master/src/DebugUtil.h
//https://github.com/KONNEKTING/KonnektingDeviceLibrary/blob/master/src/DebugUtil.cpp
#include <DebugUtil.h> 

// ESP8266 use the 2nd serial port with TX only (GPIO2 / D4)
#define DEBUGSERIAL Serial1

void setup() {
  DEBUGSERIAL.begin(9600);
  Debug.setPrintStream(&DEBUGSERIAL);
  Debug.println(F("Test"));
}

void loop() {

}

**Comment by gerrylenz** [comment]
void setup() {
  DEBUGSERIAL.begin(9600);
  Debug.setPrintStream(&DEBUGSERIAL);
  Debug.println(F("Test"));
}

 

Change to

 

void setup() {
  DEBUGSERIAL.begin(9600);
  DEBUGSERIAL.setPrintStream(&DEBUGSERIAL);
  DEBUGSERIAL.println(F("Test"));
}

 

Gerry

 

Von: Eugen [mailto:notifications@github.com] 
Gesendet: Dienstag, 9. Mai 2017 21:21
An: esp8266/Arduino <Arduino@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [esp8266/Arduino] vsnprintf => ESP crashes on start (#3221)

 


Basic Infos


Hardware


Hardware: ESP-12F on WeMos D1 mini R2
Core Version: 2.3.0


Description


i have a problem with a vsnprintf function.
I use this https://github.com/KONNEKTING/KonnektingDeviceLibrary/blob/master/src/DebugUtil.h debug-lib
ESP crashes on start and only stack error is shown.
This lib works fine on 328p, 32u4 and SAMD21...


Settings in IDE


Module: WeMos D1 R2 & mini
Flash Size: 4MB (3M SPIFFS)
CPU Frequency: 80Mhz


Debug Messages


Stack and decode:
https://gist.github.com/Adminius/4a08ac05888eb674dd5c11598214be49


Sketch

//https://github.com/KONNEKTING/KonnektingDeviceLibrary/blob/master/src/DebugUtil.h
//https://github.com/KONNEKTING/KonnektingDeviceLibrary/blob/master/src/DebugUtil.cpp
#include <DebugUtil.h> 
 
// ESP8266 use the 2nd serial port with TX only (GPIO2 / D4)
#define DEBUGSERIAL Serial1
 
void setup() {
  DEBUGSERIAL.begin(9600);
  Debug.setPrintStream(&DEBUGSERIAL);
  Debug.println(F("Test"));
}
 
void loop() {
 
}

**Comment by Adminius** [comment]
this is not a reason... and solves not my problem:
```
ESP_crash:10: error: 'class HardwareSerial' has no member named 'setPrintStream'

   DEBUGSERIAL.setPrintStream(&DEBUGSERIAL);

               ^

exit status 1
'class HardwareSerial' has no member named 'setPrintStream'

**Comment by Adminius** [comment]
@igrr is a release date of 2.4.0 already known? or do you have any temporarry solution for my problem?

**Comment by igrr** [comment]
No idea, TBH. See list of things to be done for 2.4.0 here: https://github.com/esp8266/Arduino/projects/1

**Comment by igrr** [comment]
Oh, this should actually be already fixed in git version. If you can follow "install from git" instructions in README.md, that would be the workaround.

**Comment by Adminius** [comment]
i've tried 2.4.0-rc1... 
the same bug as with 2.3.0

**Comment by pieman64** [comment]
@Adminius git version not rc1 version.

**Comment by Adminius** [comment]
i can't compile python on win10...

**Comment by igrr** [comment]
That's the bug in KonnektingDeviceLibrary, it attempts to use `vsnprintf` with a format string defined in PROGMEM, if the architecture is not AVR:
https://github.com/KONNEKTING/KonnektingDeviceLibrary/blob/master/src/DebugUtil.cpp#L46-L50

If you change these lines to use `vsnprintf_P` on the ESP8266 as well, the code will work.
