### ISSUE TITLE
Can ping esp, but not yet WL_CONNECTED

### ISSUE THREAD

**Issue by ygator** [esp8266/Arduino#3229]
```
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
  }

```
Sometimes WiFi.status() never equals WL_CONNECTED, but yet I can still ping the ESP.  I end up having to reboot the esp multiple times before it becomes WL_CONNECTED.

**Comment by igrr** [comment]
This looks like a duplicate of #2186
