### ISSUE TITLE
NOT_ON_TIMER is not defined

### ISSUE THREAD

**Issue by Duality4Y** [esp8266/Arduino#323]
so when running the new ide and trying to run code for a i2c display it tells me that NOT_ON_TIMER is not defined ... which is not defined in Arduino.h, which if you define it to be zero it also raises an error in which it is used to check if a pin is a timer. like:
digitalPinToTimer is not defined

so this is what i added to make it go away:
#define NOT_ON_TIMER             (0)
#define digitalPinToTimer(pin)      (NOT_ON_TIMER)

basicly it's this librarie that provided this issue:
https://bitbucket.org/fmalpartida/new-liquidcrystal/downloads

**Comment by igrr** [comment]
Does the library work after this change?

**Comment by Duality4Y** [comment]
yes, i did a pullrequest :)
