### ISSUE TITLE
how to fix no member listen

### ISSUE THREAD

**Issue by hungpkav** [esp8266/Arduino#3239]
i use lib pzem004t but error. how to fix no member listen. board arduino uno compile ok but node mcu cant compile
![image](https://cloud.githubusercontent.com/assets/28674659/26026865/f965be0c-382d-11e7-85c6-4a1a2d7b7291.png)

**Comment by igrr** [comment]
As the error message says, SoftwareSerial class on ESP8266 doesn't have member called `listen`. If you have some suggestion about this, please open an issue in SoftwareSerial repository here: https://github.com/plerup/espsoftwareserial

**Comment by olehs** [comment]
@igrr EspSoftwareSerial supports listen() method since 3.2.0.
Default version in ESP8266 is 3.1.0. 
Is there a chance to get an updated version?

**Comment by igrr** [comment]
Uhm, sure, i didn't know there was a more recent version. In the past @plerup would make a PR to update [the version used](https://github.com/esp8266/Arduino/blob/master/package/build_boards_manager_package.sh#L64). Should I update it to 3.2.3, which is the latest?

**Comment by olehs** [comment]
Yes, the latest version is compatible with AVR's one and seems to work fine

**Comment by plerup** [comment]
Sorry about that, forgot :grimacing:

**Comment by bruescor** [comment]
Good evening guys, I was researching on the softwareserial for nodemcu and came to stop here. I'm new here and I'm starting to program with the module and I had a problem with this listen class. I wonder if you have any library that solves this problem. Thanks in advance.
