### ISSUE TITLE
Package for nightly build

### ISSUE THREAD

**Issue by sanchosk** [esp8266/Arduino#324]
I'd like to help with testing, however I am not experienced with building software.
It would be great if there was a link for package manager, like
http://arduino.esp8266.com/package_esp8266com_nightly.json
with overnight builds, so I can easily replace the current package with a new one and test old code.

**Comment by igrr** [comment]
Good idea. I'll add a scheduled build for that.

**Comment by igrr** [comment]
http://arduino.esp8266.com/staging/package_esp8266com_index.json

**Comment by probonopd** [comment]
I added http://arduino.esp8266.com/staging/package_esp8266com_index.json as an additional source to my existing sources and installed 1.6.4-835-g77d77e8 using the Boards Manager. As a result, in $HOME/Library/Arduino15/packages/esp8266/hardware/esp8266 I had both 1.6.2/ and 1.6.4-835-g77d77e8/ - this was confusing the IDE to the point that it crashed immediately when starting the IDE. Removing 1.6.2/ solved this for me. Would be nice if this could work automatically.
(Please let me know if this must be filed upstream as an Arduino IDE bug instead.)

**Comment by Testato** [comment]
May you update the development board manager package ?

**Comment by Testato** [comment]
i updated this evening to the last development pachage whit  your staging json link.
I confirm that in the C:\Users\win7\AppData\Roaming\arduino15\staging and packages remain the old version. So the Ide do not know which one must use.
I must manually delete the old 1.6.4-835-g77d77e8 and leave only the last 1.6.5-804-g2d340c7

**Comment by igrr** [comment]
Package has been updated. If all goes well, will roll it out as stable later today.
