### ISSUE TITLE
Arduino OTA - Push from one ESP to another

### ISSUE THREAD

**Issue by thetemplar** [esp8266/Arduino#3250]
Hello,
a feature to let the ESP be the host of the new firmware would be great. 
IIRC in the current state, the ESP only can receive new firmware from a computer, but can't "forward" its new firmware to other ESPs.

**Comment by devyte** [comment]
I think this should be possible with the current tools available
(webserver, updater, http client, spiffs large enough). It would take some
effort to implement by yourself, though.
