### ISSUE TITLE
Network Scanner doesn’t work with Ticker

### ISSUE THREAD

**Issue by mcmega** [esp8266/Arduino#3251]
Hi All!
If there is no connection, turn on the STA+AP mode. I scan the network and try to reconnect with router. The scan function works fine if it is in a "loop()" arduino sketch. But I want to run a scan every 10 seconds. I create task **wifiCheck.attach(10, checkConnect)**, and the scan does not work.
**WiFi.scanNetworks ()** returns 0!
What to do?
```
void checkConnect() {
  if (WiFi.status() != WL_CONNECTED) {
    if (wifiMode == "STA") { Mode_STA_AP(); }
    if (wifiMode == "STA+AP") {
      for (int i = 0; i < WiFi.scanNetworks(); i++) {
        if (WiFi.SSID(i) == STAn) { Init_WiFi(); }
      }
      WiFi.scanDelete();
    }
  }
}
```
I'm using **#include <Ticker.h>**

**Comment by reaper7** [comment]
leave Your scan code inside loop
and inside ticker task set only global boolean flag for triggering,
something like this:
```
volatile bool scanFlag = false;

void setScanFlag() {
  scanFlag = true;
}

void setup() {
  //your code here
  wifiCheck.attach(10, setScanFlag)
}

void loop() {
  if (scanFlag) {
    if (WiFi.status() != WL_CONNECTED) {
      if (wifiMode == "STA") { Mode_STA_AP(); }
      if (wifiMode == "STA+AP") {
        for (int i = 0; i < WiFi.scanNetworks(); i++) {
          if (WiFi.SSID(i) == STAn) { Init_WiFi(); }
        }
        WiFi.scanDelete();
      }
    }
  }
  //your code here
}
```

**Comment by mcmega** [comment]
Thank you very much!
Added reset scanFlag.

**Comment by reaper7** [comment]
done :)
