### ISSUE TITLE
SPI library on ESP8266 doesnt work

### ISSUE THREAD

**Issue by patriks51** [esp8266/Arduino#3252]
#### Hardware
Hardware:			ESP8266 nodeMCU lolin V3
Core Version:      	?2.1.0-rc2?

### Description

Hello guys, I have some problem with this library: https://github.com/esp8266/Arduino/tree/master/libraries/SPI
I want control this digital potentiometer http://ww1.microchip.com/downloads/en/DeviceDoc/11195c.pdf and after add the library a can't compile my project. Where is the problem, please?

### Settings in IDE

Module:  			Lolin V3 nodemcu
Flash Size: 		4MB
CPU Frequency:	80Mhz
Flash Mode:		?qio?
Flash Frequency:	?40Mhz?
Upload Using:		SERIAL
Reset Method:		?ck / nodemcu?

### Debug Messages
In file included from C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:19:0:

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.h:41:1: error: unknown type name 'class'

 class SPISettings {

 ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.h:41:19: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token

 class SPISettings {

                   ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.h:50:1: error: unknown type name 'class'

 class SPIClass {

 ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.h:50:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token

 class SPIClass {

                ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.h:82:1: error: unknown type name 'SPIClass'

 extern SPIClass SPI;

 ^

In file included from C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Print.h:27:0,

                 from C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Stream.h:26,

                 from C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/HardwareSerial.h:31,

                 from C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:20:

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Printable.h:25:1: error: unknown type name 'class'

 class Print;

 ^

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Printable.h:33:1: error: unknown type name 'class'

 class Printable {

 ^

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Printable.h:33:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token

 class Printable {

                 ^

In file included from C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Stream.h:26:0,

                 from C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/HardwareSerial.h:31,

                 from C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:20:

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Print.h:34:1: error: unknown type name 'class'

 class Print {

 ^

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Print.h:34:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token

 class Print {

             ^

In file included from C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/HardwareSerial.h:31:0,

                 from C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:20:

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Stream.h:38:1: error: unknown type name 'class'

 class Stream: public Print {

 ^

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Stream.h:38:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 class Stream: public Print {

             ^

In file included from C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:20:0:

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/HardwareSerial.h:67:1: error: unknown type name 'class'

 class HardwareSerial: public Stream

 ^

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/HardwareSerial.h:67:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 class HardwareSerial: public Stream

                     ^

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/HardwareSerial.h:144:1: error: unknown type name 'HardwareSerial'

 extern HardwareSerial Serial;

 ^

C:\Users\Patrik\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/HardwareSerial.h:145:1: error: unknown type name 'HardwareSerial'

 extern HardwareSerial Serial1;

 ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:39:9: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 SPIClass::SPIClass() {

         ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:44:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 bool SPIClass::pins(int8_t sck, int8_t miso, int8_t mosi, int8_t ss)

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:62:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::begin() {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:86:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::end() {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:106:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::setHwCs(bool use) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:139:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::beginTransaction(SPISettings settings) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:146:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::endTransaction() {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:149:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::setDataMode(uint8_t dataMode) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:176:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::setBitOrder(uint8_t bitOrder) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:193:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::setFrequency(uint32_t freq) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:276:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::setClockDivider(uint32_t clockDiv) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:285:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 inline void SPIClass::setDataBits(uint16_t bits) {

                     ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:291:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 uint8_t SPIClass::transfer(uint8_t data) {

                 ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:301:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 uint16_t SPIClass::transfer16(uint16_t data) {

                  ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:323:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::write(uint8_t data) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:332:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::write16(uint16_t data) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:336:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::write16(uint16_t data, bool msb) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:352:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::write32(uint32_t data) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:356:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::write32(uint32_t data, bool msb) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:384:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::writeBytes(uint8_t * data, uint32_t size) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:397:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::writeBytes_(uint8_t * data, uint8_t size) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:421:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::writePattern(uint8_t * data, uint8_t size, uint32_t repeat) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:500:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::transferBytes(uint8_t * out, uint8_t * in, uint32_t size) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:514:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token

 void SPIClass::transferBytes_(uint8_t * out, uint8_t * in, uint8_t size) {

              ^

C:\Users\Patrik\Documents\Arduino\libraries\SPIn\SPIn.c:553:1: error: unknown type name 'SPIClass'

 SPIClass SPI;

 ^

**Comment by igrr** [comment]
The error message is pointing to `SPIn\SPIn.c`, which isn't the SPI library in this core. This one shoud be `SPI/SPI.cpp`.

**Comment by patriks51** [comment]
Thank you. I renamed these files, because I had problem with colide library name.

**Comment by igrr** [comment]
Well, in that case you may want to keep .cpp extension, because this is a C++ library.
