### ISSUE TITLE
lease renewal?

### ISSUE THREAD

**Issue by whyameye** [esp8266/Arduino#3255]
Issue 27 of PubSubClient states from the author: 

> if you connect using DHCP you have to renew your DHCP lease from time to time. If you fail to do that, all your connections will drop. Look into the Arduino docs into how to do it.

I wasn't finding a lot on renewing the lease for the ESP8266. Is there something I need to do to renew it or is it built into the ESP8266WiFI loop?

**Comment by earlephilhower** [comment]
@d-a-v can correct me if I'm wrong, but DHCP lease renewal should be taken care of in LWIP v2 internals and you shouldn't need to do anything in your own code.
