### ISSUE TITLE
No response from device error

### ISSUE THREAD

**Issue by iAchyut** [esp8266/Arduino#3256]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:                ESP8266 module
Core Version:      	Arduino 1.8.2 and Python 2.7 installed (Path added to environment)

### Description
Hi
I uploaded the OTA bootloader serially and then uploaded blink led program via OTA, it worked for the first time. Now I am trying to upload the same program again but Arduino IDE shows error. 

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			DIO
Flash Frequency:	40Mhz
Reset Method:		ck

### Sketch

#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiUdp.h>
#include <ArduinoOTA.h>

const char* ssid = "ABC";
const char* password = "123456789";

void setup() {
 Serial.begin(115200);
 Serial.println("Booting");
 WiFi.mode(WIFI_STA);
 WiFi.begin(ssid, password);
 while (WiFi.waitForConnectResult() != WL_CONNECTED) {
 Serial.println("Connection Failed! Rebooting...");
 delay(5000);
 ESP.restart();
 }

// Port defaults to 8266
 // ArduinoOTA.setPort(8266);

// Hostname defaults to esp8266-[ChipID]
 // ArduinoOTA.setHostname("myesp8266");

// No authentication by default
 // ArduinoOTA.setPassword((const char *)"123");

ArduinoOTA.onStart([]() {
 Serial.println("Start");
 });
 ArduinoOTA.onEnd([]() {
 Serial.println("\nEnd");
 });
 ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
 Serial.printf("Progress: %u%%\r", (progress / (total / 100)));
 });
 ArduinoOTA.onError([](ota_error_t error) {
 Serial.printf("Error[%u]: ", error);
 if (error == OTA_AUTH_ERROR) Serial.println("Auth Failed");
 else if (error == OTA_BEGIN_ERROR) Serial.println("Begin Failed");
 else if (error == OTA_CONNECT_ERROR) Serial.println("Connect Failed");
 else if (error == OTA_RECEIVE_ERROR) Serial.println("Receive Failed");
 else if (error == OTA_END_ERROR) Serial.println("End Failed");
 });
 ArduinoOTA.begin();
 Serial.println("Ready");
 Serial.print("IPess: ");
 Serial.println(WiFi.localIP());
 pinMode(2, OUTPUT);
}

void loop() {
 ArduinoOTA.handle();
 digitalWrite(2, HIGH); // turn the LED on (HIGH is the voltage level)
 delay(250); // wait for 2 second
 digitalWrite(2, LOW); // turn the LED off by making the voltage LOW
 delay(250); 
}

### Debug Messages
[19:02:36]:No Response from device

Although my ESP8266 is present in Tools>PORT option along with the local ip address. (My esp8266 is present in the network but still ArduinoIDE shows No response from Device error every time i upload the same program. )
This program worked for the very first time that too via OTA.

**Comment by igrr** [comment]
Once you overwrite the OTA sketch with the Blink sketch, the board will no longer be able to receive OTA. In the sketch you upload you still need to initialize `ArduinoOTA` and call `ArduinoOTA.handle()` in the same way it is done in OTA examples.

**Comment by iAchyut** [comment]
Sketch I uploaded above is my blink led sketch and it contains arduino Ota. Handle() and arduinoOTA. Moreover my esp8266 is still showing up in Port with local ip address that means my Ota is still working . Uploading same program again causes this error.  No response from Device.

**Comment by igrr** [comment]
Please upload the sketch again via serial, this time enabling debug options in Tools menu:
Debug level: OTA + Updater
Debug port: Serial

Then keep serial monitor (not the one from Arduino, use some other software) open while uploading same sketch again over OTA. Once you reproduce the "no response from the device" issue, copy the output from the serial terminal, and attach it here.

**Comment by devyte** [comment]
@iAchyut any progress with this?

**Comment by odilonafonso** [comment]
I have same error.

Got this output from Putty:

![puttyotaerror](https://user-images.githubusercontent.com/15105558/30939454-de95f8d4-a3b3-11e7-84d8-024e9dc2142e.png)

**Comment by odilonafonso** [comment]
it is definitely not possible to use OTA on a regular basis.

**Comment by devyte** [comment]
@iAchyut @odilonafonso  after flashing over serial, did you physically reset the esp before doing OTA?

**Comment by odilonafonso** [comment]
Hi @iAchyut. Yes.
I used OTA in my sketches earlier successfully. After implementing httpupdate, I stopped using OTA. Now I was trying to reuse OTA, as I made some changes to my application, but I can not re-record the firmware with OTA. Even the library examples do not work.
Thanks for help.

**Comment by bcmears** [comment]
I am experiencing the same problem.  My debug output is essentially the same as odilonafonso's.  I installed the arduino IDE on a second laptop (and Python 2.7) and I find that I can successfully program OTA with the second machine, so it isn't a sketch problem, it isn't a board or board library problem, but there must somehow be something different in the installations on the two Win10 laptops.  I've done a clean install of Python and the IDE on my problem machine, but it has not helped.  Any suggestions would be appreciated.

**Comment by dtbaker** [comment]
Following, Any ideas? First OTA worked great, now it shows up in the network list, the ESP is working fine, but I cannot OTA a second time. Have reset all the things. Is it to do with the chosen flash size when doing the OTA?

**Comment by odilonafonso** [comment]
I gave up. I'm using httpUpdate.

**Comment by supersjimmie** [comment]
I was using Arduino IDE 1.6.11 with esp8266-arduino v2.3.0 until now. 
The OTA always worked fine.

Today I switched to Arduino IDE 1.8.2 with esp8266-arduino Latest GIT.
First connection from the 1.8.2 IDE over OTA worked fine, at that moment the ESP was running the code compiled with 1.6.11/v2.3.0. So OTA, Wifi, network and the IDE (1.8.2) are fine. Note that I was connecting over OTA from IDE 1.8.2 and it worked.

After uploading the sketch where nothing ever changed to OTA or webserver or network, I was not able to use OTA anymore.  So to me it's clear that OTA is broke, not the IDE, my sketch or my network.

**Comment by prasenjit-roy** [comment]
1. For ESP-01 need to set TOOLS>Flash Size>512 ( no SPIFFS)
2. Take it out of BOOT mode else WDT reset occurs and 2nd run may not work

**Comment by gibo77** [comment]
My ArduinoOTA was working like a charm, until I incorporated it with WifiManager.h. The issue I have is "No Response from the device". I also got crash with Stack Dump, which another issue.
![capturearduinoota](https://user-images.githubusercontent.com/35072102/36263152-7c1bcc68-1237-11e8-8bf5-d6536720d04e.JPG)

So I removed the WifiManager.h and went back to the old ArduinoOTA that worked before. But unfortunately, I am having that same problem. Do you think it has something to do with flash memory being occupied by the WifiManager.h? I did some research and said that if you do serial firmware download you basically erase the whole sketch memory space. I am not sure if this is true. Do you think I have to erase the EEPROM? Can you point me to a resource discussing about how the memory is split by Arduino ESP8266? Thanks guys.

Below is some information about flash space availability.
![image](https://user-images.githubusercontent.com/35072102/36263455-4a29cbaa-1238-11e8-989f-d4a37bcf5cfc.png)

**Comment by gibo77** [comment]
UPDATE: I found the problem!

My laptop that I use to run the Arduino IDE is connected to 5GHz Wifi that is why ArduinoOTA will return "No Response". 
I knew about this 5GHz Wifi issue before with ESP8266, but that was for Http. Now that I tried the OTA I forgot about it. I did all kind of stunts to figure out the problem. I did SPIFFS format and EEPROM clear 512bytes memory. But this snag had put me to be close to expert on Arduino ESP8266 memory management SPIFFS, PROGMEM and EEPROM.

**Comment by bcmears** [comment]
Glad to hear you got yours working.  Still no joy for me.  I forced the
wifi to connect at 2.4GHz and I still get "No Response" from my esp8266.  I
even tried connecting my laptop through a 2.4GHz dongle.  Still won't
program.  I can program using an old laptop that doesn't have 5 GHz, and it
works fine.  I think you've gotten me closer to a solution but I don't have
it yet.

**Comment by andrepalma** [comment]
Hi, I'm quite new with this OTA thing.. But i'm facing the same issues and is not about 5GHz, my esp is connected to 2.4 (different SSID) and i'm using a Desktop with physical connection to network..
First thing I've tried is to disable firewall. and still the same error. After that i was looking for the message and noticed that it seems that the programmer (I use Atom with platformio) send a message to 0.0.0.0 (it means a broadcast message) so I try, disable every network adapter I have, except of course, the one for Ethernet and it work just fine... 
After successful I enable the firewall again and voilá, everything is working.

P.S. - The adapter that i disable is the VirtualBox Host Adapter...

I hope this help other, mainly the people that still doesn't have it working yet.

**Comment by prasenjit-roy** [comment]
For ESP-01 I had used 512 ( 64K SPIFFS) and it worked.
File size needs to be less than half of available Flash. 
Connect to serial port and you can see the fail reason if any.

**Comment by andrepalma** [comment]
Yap, that is another thing we have to keep in mind, if the IC we are using have 1MB of memory our program cannot exceed 512KB. This is because it needs to kept the all new software while is still have the old software.

**Comment by gibo77** [comment]
Do you have another esp8266 to try? I usually have two for comparison. 


Sent from Yahoo Mail for iPhone


On Friday, February 16, 2018, 12:17 AM, bcmears <notifications@github.com> wrote:

Glad to hear you got yours working. Still no joy for me. I forced the
wifi to connect at 2.4GHz and I still get "No Response" from my esp8266. I
even tried connecting my laptop through a 2.4GHz dongle. Still won't
program. I can program using an old laptop that doesn't have 5 GHz, and it
works fine. I think you've gotten me closer to a solution but I don't have
it yet.

**Comment by gibo77** [comment]
Yup. That is the rule now. When you change firmware the old one should still be in there, until the new one completely loads and run before wiping the old firmware. In the olden days they dont have this and if there is a power failure or comm error what you have is AN EXPENSIVE PAPER WEIGHT. 


Sent from Yahoo Mail for iPhone


On Saturday, February 17, 2018, 3:58 PM, andrepalma <notifications@github.com> wrote:


Yap, that is another thing we have to keep in mind, if the IC we are using have 1MB of memory our program cannot exceed 512KB. This is because it needs to kept the all new software while is still have the old software.

**Comment by bcmears** [comment]
Thanks for your suggestion.  I did try a 2nd esp8266 module (same
manufacturer) and it won't program (does program with old laptop).  Also
tried disabling all wifi & ethernet drivers except for the built-in wifi.
Still no good.  Disabled internal wifi and used a 2.4 GHz dongle.  Still
won't program.  I even tried a different router without success.  Any ideas
are welcome.

**Comment by LotusFly** [comment]
Try these settings on your Arduino>>Tools:

Board:  Generic ESP8266 Module
Flash Mode: DIO
Flash Size: 4M (1M SPIFFS)
Debug Port: Serial
Debug Level: OTA + Updater
Reset Method: ck

Use COM on first upload attempt.
Restart Arduino.
Change Port to Network Port you created.
Try uploading again.

Things i overlooked:
1. ArduinoOTA.setHostname("_yourHostnameHere_");     // _yourHostnameHere_ should include only alphabet characters
2. im using ESP8266MOD, it should use 4M (1M SPIFFS)

Verify if these will work for you.

**Comment by bcmears** [comment]
Thank you for your help.  I have an ESP-12E.  Using your suggested settings
I received an EPROM sync failed message when trying to program via the USB.

This module will program OTA when using the Default ESP-12E settings when I
use an old laptop.  Even using this new laptop, communication starts as I
see the LED turn on solid when upload begins, but it appears to time out
and give the  no response message.

**Comment by bcmears** [comment]
Finally, I've had some success.  Rather than use the Arduino IDE to program
OTA, I've used the web browser approach as described in the OTA github
project
https://github.com/esp8266/Arduino/tree/master/doc/ota_updates#web-browser

This works flawlessly for me.  I still would like to know why the IDE
approach won't work but at least I have a work-around.
Thank you all for your suggestions.

**Comment by LotusFly** [comment]
That's a good thing.  I'll check the same and try if the workaround will also work for me.

**Comment by gibo77** [comment]
Seems like using delay() could attribute to failure of OTA. I am not 100% sure. I have to counter check on this. But I throw in delay() just now and my OTA is unresponsive.

    On ‎Saturday‎, ‎March‎ ‎03‎, ‎2018‎ ‎10‎:‎52‎:‎03‎ ‎PM‎ ‎EST, LotusFly <notifications@github.com> wrote:  
 
 
That's a good thing. I'll check the same and try if the workaround will also work for me.

**Comment by daebikelinz** [comment]
I've encountered the same problem. I only signed up to github to make a post here because it could help others.

In my case it was also the delay() function. After i deleted it, it works perfect.

Greets from Germany

**Comment by dtbaker** [comment]
For what it's worth I just got a new computer and setup Arduino and the latest drivers from scratch, OTA is now working fine multiple times when I was previously getting these "no response from device" error messages. 

Just make sure to choose the right flash size, I chose 512M first when I should have chosen 4M.

**Comment by el-basko** [comment]
Tenía el mismo problema que @bcmears. Lo solucioné agregando Python y Arduino IDE a las excepciones del firewall.

I had the same problem as @bcmears. I solved it by adding Python and Arduino IDE to the firewall exceptions.

**Comment by ganan-s** [comment]
I have a wemos d1 mini pro, and solved it by using Auto Format (under tools menu) then re-uploaded my code and OTA worked. I was having an issue with OTA when I changed my SSID and password, where it would tell me the device did not respond.

**Comment by ltvanderkrogt** [comment]
19:25:25 [ERROR]: No Answer

4M (3M SPIFFS) worked for me with WEMOS.

**Comment by agraymd** [comment]
I was able to cure NO RESPONSE FROM DEVICE when trying to upload OTA to a Wemos D1 as well as a Wemos D1 Mini, by turning off the Windows firewall.   

Now I have to figure out how to add an exception so I can keep the firewall on.

**Comment by AitorCM** [comment]
Same error here, @el-basko solution worked for me, just add firewall exceptions for Arduino IDE and Python exe's files.

**Comment by devyte** [comment]
This discussion has become convoluted and there has been no response from OP. Closing.

**Comment by priyaru** [comment]
> Try these settings on your Arduino>>Tools:
> 
> Board: Generic ESP8266 Module
> Flash Mode: DIO
> Flash Size: 4M (1M SPIFFS)
> Debug Port: Serial
> Debug Level: OTA + Updater
> Reset Method: ck
> 
> Use COM on first upload attempt.
> Restart Arduino.
> Change Port to Network Port you created.
> Try uploading again.
> 
> Things i overlooked:
> 
> 1. ArduinoOTA.setHostname("_yourHostnameHere_");     // _yourHostnameHere_ should include only alphabet characters
> 2. im using ESP8266MOD, it should use 4M (1M SPIFFS)
> 
> Verify if these will work for you.

**Comment by priyaru** [comment]
For me , debug level is shown as OTA  not OTA+UPDATER..which cause any issues? and why it is shown like this to me only..? Moreover I didnt get the OTA output.. i doesnt upload a code even single time..  :(

**Comment by yoosamui** [comment]
ESP8266-12E
OTA definitively don't work with static IP
  
Firewall is off!!!
  WiFi.mode(WIFI_STA);
  WiFi.config(IPADDRESS, GATEWAY, NETMASK);  // static ip, gateway, netmask
  WiFi.begin(credentials::m_credentials.m_wifi_ssid,           
 credentials::m_credentials.m_wifi_password);  
DON"T WORK!!!
-----------------------------------
Without static IP after enter the OTA password in the IDE the download over Wifi finish successfully.
  WiFi.mode(WIFI_STA);
//  WiFi.config(IPADDRESS, GATEWAY, NETMASK);  // static ip, gateway, netmask
  WiFi.begin(credentials::m_credentials.m_wifi_ssid,   
     credentials::m_credentials.m_wifi_password);  

Way is that?
the NTPClient lib also don't work with static IP
do i missing something?
Thanks!

**Comment by khyarul** [comment]
My best config for OTA, more than 3 times upload with success
I'm using this in my Attandance Node project with **Scheduler.h** to handle much task like:
- buzzer & button
- lcd & rfid
- MQTT loop

![image](https://user-images.githubusercontent.com/50608159/77872779-26bd4d80-7272-11ea-82d8-16f99a1ea84d.png)

**Comment by yoosamui** [comment]
OTA is working now with static IP's  upload with success
I just use the OTABasic example and add an static IP.
i did not change anything in the tools settings

I don't know exactly  way now is working.
Anyway thanks to khyarul and all of you.

**Comment by m4rc77** [comment]
I also had the infamous `No response from device error`. In my case (on macOS  Mojave, 10.14.6, with Plattform IO) it was definitively the firewall from macOS. Just tested it by quickly disabling the firewall, and it worked!

**As a final solution I had to add add `python 3.8` in the "Firewall Options" and `Allow incoming connections`. Which then solved the issue.**

**Comment by ratnick** [comment]
For me, it was the firewall blocking Python for access to private networks (Windows 10).

**Comment by siparker** [comment]
same for me. checked for python in my windows 10 firewall. change settings to allow the Arduino folder >  tools >  python 3.x to be allowed to communicate with the network.

**Comment by chimeranzl** [comment]
Just for the record, I got this same error and realised that in my code, I forgot to call my "setup wifi" routine in setup{} prior to the arduinoota.onstart etc calls - of course, there was no response from the device coz wifi wasn't started first _facepalm_

**Comment by sscholle** [comment]
Likely a Python/Firewall issue. You need to allow Python on your Firewall
