### ISSUE TITLE
Create ID from MAC address

### ISSUE THREAD

**Issue by mcmega** [esp8266/Arduino#3262]
Hi All!

I want to create an ID for an ESP8266 device, but the MAC address length is too large. Is it possible to use MAC address mapping through CRC16 (32)? On how much it is expedient?
For example, CRC16:

```
unsigned short CRC16(unsigned short CRC, unsigned char Data) {
	Data ^= CRC& 255;
	Data ^= Data << 4;
	unsigned short t = (((unsigned short)Data << 8) | ((CRC>> 8) & 255));
	t ^= (unsigned char)(Data >> 4);
	t ^= ((unsigned short)Data << 3);
	return t;
}
```
Or maybe there are some other ways of identification?

**Comment by Jorgen-VikingGod** [comment]
why not using the internal chipID?
`ESP.getChipId()`

**Comment by igrr** [comment]
MAC address is 6 bytes, if you need to cut it down to 4, just remove the two MSBs.
