### ISSUE TITLE
win32-xtensa-lx106-elf-gb404fb9-2.tar.gz very slow download

### ISSUE THREAD

**Issue by jonhp** [esp8266/Arduino#3269]
sometimes it fails. sometimes it takes a very long time. can this be hosted on a faster, more reliable server?

C:\Users\jon\Documents\Arduino\hardware\esp8266com\esp8266\tools>python get.py
Platform: i686-mingw32
Downloading esptool-0.4.9-win32.zip
Done
Extracting dist/esptool-0.4.9-win32.zip
Renaming esptool-0.4.9-win32/ to esptool
Downloading win32-xtensa-lx106-elf-gb404fb9-2.tar.gz
22%Traceback (most recent call last):
  File "get.py", line 116, in <module>
    get_tool(tool)
  File "get.py", line 75, in get_tool
    urlretrieve(url, local_path, report_progress)
  File "C:\Python27\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\Python27\lib\urllib.py", line 273, in retrieve
    block = fp.read(bs)
  File "C:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "C:\Python27\lib\ssl.py", line 756, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 643, in read
    v = self._sslobj.read(len)
socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host

**Comment by igrr** [comment]
We've recently moved downloads to Github Releases, which are hosted on AWS. Same files can still be downloaded from arduino.esp8266.com (i.e. http://arduino.esp8266.com/win32-xtensa-lx106-elf-gb404fb9-2.tar.gz). You have an option of downloading from that URL and dropping the file into dist folder, then running `get.py` again to unpack it.

For most users, downloads from Github Releases are more reliable than the old server, which had a few hours of downtime every couple of months. In some regions, like here in China, for example, downloads from the AWS are less reliable, but that's the trouble with Chinese internet in general.
Out of curiosity, which region are you located in?

**Comment by jonhp** [comment]
I am in USA and I have had this problem using multiple systems over the last two days at different times. From a user perspective this issue and 3267, I think, are different problems.
