### ISSUE TITLE
ESP8266WebServer.cpp does not parse get  parameters.

### ISSUE THREAD

**Issue by far5893** [esp8266/Arduino#327]
In esp8266webserver library there is not parsing of GET parameters,
this library is only for examples or can i extend with parameters parsing ?

**Comment by igrr** [comment]
I think GET parameter parsing is implemented:
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.h#L70

Do you have any issues using ```arg```, ```argName```, ```argCount```, ```hasArg``` APIs?

**Comment by far5893** [comment]
Ok , i suppose that webserver should call fn(function associated to uri) like a c main with argc/argv
array , but it's one-client/one-query server so parameters are stored   in web server object.
All it's clear now, may be more complex example with get should be done..

**Comment by marvinroger** [comment]
Well, there is already an example showing get URL params:
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WebServer/examples/AdvancedWebServer/AdvancedWebServer.ino#L82

**Comment by far5893** [comment]
Put arg example in 404 error handler is not so friendly!!
Ok, it's' open source and you must read all code , but there is a lot of project to read code outside.......

**Comment by marvinroger** [comment]
Arduino on ESP8266 is still in early stage and as you can see there is currently no real docs available. I guess you will have to dig into the code for now. But I am pretty sure it will come one day, but there is probably a lot more important stuff to do right now.

**Comment by far5893** [comment]
Ok,thank.
