### ISSUE TITLE
portOutputRegister() & friends not working for pin #16

### ISSUE THREAD

**Issue by ladyada** [esp8266/Arduino#3272]
With ESP8266 (Feather Huzzah) core version=2.4.0

It appears PortOutput/InputRegister does not account for pin 16

Current macro definition is here
https://github.com/esp8266/Arduino/blob/4897e0006b5b0123a2fa31f67b14a3fff65ce561/cores/esp8266/Arduino.h#L222

but it should account for pin 16 like here
https://github.com/esp8266/Arduino/blob/2126146e20042878026f03a19107555f32e3431c/cores/esp8266/core_esp8266_wiring_digital.c#L87

if possible! thanks :)

```
#define PIN 16  // works with pin 0, 2, 15, etc

volatile uint32_t *portout;
uint32_t mask;

void setup() {
  pinMode(PIN, OUTPUT);
  
  portout = portOutputRegister(digitalPinToPort(PIN));
  mask = digitalPinToBitMask(PIN);
}

void loop() {
  *portout |= mask;
  delay(1);
  *portout &= ~mask;
  delay(1);
}
```

**Comment by devyte** [comment]
This is already implemented.
