### ISSUE TITLE
Help with ESP8266 and GET REQUEST

### ISSUE THREAD

**Issue by ViictorG1** [esp8266/Arduino#3276]
Hi,

I'm needing help to build a project and I'm looking to use a library for my ESP8266 module in my ARDUINO UNO.

If you know a Library to use the ESP8266 I appriciate it.

I need the arduino reading the DB every time to receive a simple value 0 or 1, I just need to know how to receive this answer.

portaoeletronico.esy.es/recebe.php (I NEED READ THIS BODY)

At the moment I am not able to make a code on the arduino with this library: https://github.com/itead/ITEADLIB_Arduino_WeeESP8266

That makes the GET request work, could someone show me a code that would work? Thank you.

My PHP:

Code: [Select]
<?php
 $servername = "mysql.hostinger.com.br";
 $username = "root";
 $password = "*****";
 $dbname = "esp1";
 $conn = new mysqli($servername, $username, $password);
 
 header("content-type: application/json");

 $sql = "SELECT  * FROM `u582151594_esp82`.`esp1`";
 $result = $conn->query($sql);
 while($data = $result->fetch_object()) {
  $value = $data->value;      
 }
 
 echo '{"value":';
 echo $value;
 echo '}';
 
 $conn->close();
?>

The code returns me:
{"value":0}

I need the arduino to read this JSON, parse, and remove this VALUE for me to use in my code.

Some help?

**Comment by igrr** [comment]
@ViictorG1, this issue tracker is not a good place for "how do I..." kind of questions. Its main purpose is to keep track of issues and feature requests related to esp8266 Arduino core and libraries. Please use esp8266.com community forum for coding help. Thank you.
