### ISSUE TITLE
ESP8266WebServer, two remarks

### ISSUE THREAD

**Issue by holgerlembke** [esp8266/Arduino#328]
First: Am I right that 
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WebServer/src/ESP8266WebServer.cpp#L150 always sends the "Access-Control-Allow-Origin" - header for everything? So how do I limit it?

 (I would only send the least needed headers and make all other headers optional (by flag to set or add by user)).

Second: How to get the raw response headers? Any documented way I missed?

**Comment by igrr** [comment]
Access-Control-Allow-Origin issue will be addressed in #2102.

Access to request headers have been implemented here: ee0b8621f3d49ab45db53aeda054f45e7bea6af9.
