### ISSUE TITLE
[SDK2.1.0] Colliding time functions

### ISSUE THREAD

**Issue by NiklasFauth** [esp8266/Arduino#3281]
When using millis() with SDK2.1.0, there seems to be a multiple definition of several time functions:

esp8266/tools/sdk/lib/libmain.a(time.o): In function `time':
(.irom0.text+0x1dc): multiple definition of `time'

esp8266/tools/sdk/lib/libmain.a(time.o): In function `millis':
(.irom0.text+0x94): multiple definition of `millis'

**Comment by igrr** [comment]
Hey, appreciate your submission. If you are testing PR #3281 (which isn't merged yet) and having an issue, please post your observations as comments there. Will be much easier to track everything.

Btw, the issue was already reported for SDK 2.0: https://github.com/esp8266/Arduino/issues/2998.
