### ISSUE TITLE
Connect wifi with wps pincode

### ISSUE THREAD

**Issue by vasilevichra** [esp8266/Arduino#3283]
Hello!

Is it possible to connect to WiFi with WPS pincode as `reaver` tool?
https://github.com/t6x/reaver-wps-fork-t6x

Best regards, Roman.

**Comment by igrr** [comment]
WPS PIN connection is supported by the underlying SDK, but in a not-very-useful way: it will output PIN to the UART directly. So it is difficult to integrate this meaningfully into the ESP8266WiFi library to return the PIN to the application for display. So for now, the answer is no.
