### ISSUE TITLE
Can't install ESP8266 Boards through Board Manager in Arduino IDE 1.6.4

### ISSUE THREAD

**Issue by rvbcrs** [esp8266/Arduino#329]
I downloaded the Arduino 1.6.4 IDE and copied this URL: http://arduino.esp8266.com/package_esp8266com_index.json in the additional board managers url. When I open the board manager I see the ESP8266 Package but when I press install I get the error as shown in image!

![boardmanager-error](https://cloud.githubusercontent.com/assets/11782065/7800346/3a82d542-0314-11e5-970b-24e541c325f1.PNG)

**Comment by WoodsterDK** [comment]
Hi,
I had that as well - if you manually copy the file into the following folder .."Roaming\Arduino15\staging\packages" and restart the installation then the installation succeeds....

**Comment by rvbcrs** [comment]
Ok, it seems to be working now! Haven't done what you suggested maybe Ivan fixed it :)

**Comment by igrr** [comment]
I haven't touched anything on the server today, so might have been an intermittent issue...

**Comment by faisalzed** [comment]
you mean i need to change the link to the preferences  ?

**Comment by harshgar** [comment]
Its probably just a network error keep trying it will work.
