### ISSUE TITLE
Using NodeMcu v1.0 (ESP8266 12E) with an Android app via internet

### ISSUE THREAD

**Issue by SurtrTch** [esp8266/Arduino#3293]
Hello all,
I don't know if I can talk about my issue here but I've been looking for a week and didn't find concrete solutions, so I'm trying here
I'm using a NodeMcu v1.0 (ESP8266 12E) with a little android app I've created using MIT App Inventor, It works fine like this (NodeMcu <------>Router <-------> Phone), All I do is connect both board and phone on the same router and type the local IP adress of the board on the phone, and I can execute my things.
Now I want to be able to do this over the internet (even if my phone isn't connected on the same router, or uses 3G/4G network). I want to use my own app not (Blynk or something....), so I really don't know where to start, I can rent a server or something later but know I want to try it locally if it's possible.
Thanks

**Comment by devyte** [comment]
This is not the right forum for questions like "how do I blah...". You
should visit a developers forum for that.

Having said that, here's what I did:
-use a dd-wrt router, make sure it is demilitarized by your modem if needed
-set up a vpn server on your router
-get a free ddns service account and set it up
-set up a ddns server on your router
-connect your cel to the public vpn IP address set up on your ddns server
service

With that, you'll be securely connected to the inside of your home network
with access to all internal IP addresses.

I did the above as a quick test setup just to prove the concept. If you
find a better/easier solution, please let me know, I have to do something
similar in the future, but on a larger scale.
