### ISSUE TITLE
Flash exported bin file

### ISSUE THREAD

**Issue by DcloudGit** [esp8266/Arduino#3317]
Hi all! I'm able to upload a sketch from the Arduino IDE, but if I export the bin file and flash it with the Espressif tool: https://espressif.com/en/support/download/other-tools?keys=&field_type_tid%5B%5D=14
it won't works. These are my settings: 
![flash](https://cloud.githubusercontent.com/assets/28861145/26626523/c8798e7c-45f7-11e7-93d6-b3e4f47b5bac.PNG)
![arduino ide](https://cloud.githubusercontent.com/assets/28861145/26626524/c87e428c-45f7-11e7-91c8-82dc383c54bd.png)

I knew that there's the esptool.py but why this does not work with the official tool? Am I doing something wrong?

Thank you

**Comment by reaper7** [comment]
Your FLASH SIZE setting is wrong
4Mbytes flash must be set as 32Mbit

**Comment by DcloudGit** [comment]
!!!What a stupid mistake!
now it's working... thanks :-)
