### ISSUE TITLE
AT command implementation location?

### ISSUE THREAD

**Issue by hoangnh0194** [esp8266/Arduino#3324]
Hi,
i'm trying to understand your lib, could you show me where 'd you used AT command in this lib.
thanks,

**Comment by me-no-dev** [comment]
We do not use AT commands at all. We use the chip as Arduino, not as a WiFi chip attached through UART to another Arduino.

**Comment by hoangnh0194** [comment]
@me-no-dev  :if we dont use AT command,how it can send/receive data through ESP8266,bro?

**Comment by me-no-dev** [comment]
you receive it on the ESP8266. Imagine that you miraculously got a WiFi in your Arduino and that it somehow became 10 times faster. That is what ESP8266 is. It's a MCU with WiFi and you program it using the Arduino IDE the same way you do your other Arduinos

**Comment by hoangnh0194** [comment]
oops,, finaly understand. thank you!
