### ISSUE TITLE
Does esp8266SSDP only track devices and not the services they implement? 

### ISSUE THREAD

**Issue by nikolac** [esp8266/Arduino#3326]
The code seems to support configuring devices, but I do not see a way to set the service descriptions for those devices. 

I was hoping for a way to define services then link them to functions I would implement. 

Am I missing something?

**Comment by earlephilhower** [comment]
Closing as this is not an issue but a general use question.  Please use some other forum like https://www.esp8266.com to get answers to these kinds of questions.
