### ISSUE TITLE
Clarify changelog

### ISSUE THREAD

**Issue by marvinroger** [esp8266/Arduino#333]
I think [the changelog](https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/changes.md) might be confusing. People can misunderstand the **Current version** as being the current, latest release. I think something like **Next version** or **Current working-on version** can be better. What do you think?

**Comment by duncan-a** [comment]
Good idea in my view - it confused me...

**Comment by Links2004** [comment]
we create release document which always include the latest change log, shut now be a problem any  more.
