### ISSUE TITLE
WiFiClientSecure verifyCertChain - problem with Google API (GeoTrust Global CA) certificate

### ISSUE THREAD

**Issue by AlexMegel** [esp8266/Arduino#3339]
#### Hardware
Hardware:	wemos d1 mini
Core Version: 2.4.0

### Description
I tried example sketch HTTPSRequestCACert.ino - it worked correctly.
Then I tried to verify certificate on "www.googleapis.com". There is root certificate "GeoTrust Global CA" - I downloaded it, converted to array, replaced "caCert" array and "caCertLen" (see in attached zip file). In main sketch I only changed host" variable to  "www.googleapis.com".
When I run sketch - there is false condition on "client.verifyCertChain(host)".

[GeoTrust_cert.zip](https://github.com/esp8266/Arduino/files/1064911/GeoTrust_cert.zip)

**Comment by igrr** [comment]
Fixed in https://github.com/esp8266/Arduino/commit/80e9a841d62916b46366d01c62b3a5015805eda9.
