### ISSUE TITLE
Remove SSID duplicates?

### ISSUE THREAD

**Issue by stozk** [esp8266/Arduino#334]
Hi,

the WiFi.SSID(i) function gives me the networks which have been detected via WiFi.scanNetworks(), but it will also list all the duplicates for the multiple AP/repeater network config, which means that I end up with like 60+ SSIDs in my list and this seems to be too much for my esp-webserver to handle.

Is there a way to remove the duplicate SSIDs out of the box or do I have to handle this myself?

Thanks & BR
Daniel

**Comment by Links2004** [comment]
that is normal. because each of this has an other BBSID (MAC) Address. 
you can use ```WiFi.BSSID(i)``` to get them (since #300).
but normally the webserver don't care about the data size he needs to transfer.
may you need to add ```delay(0);``` so the wtd is retested and the os has time to send the data out.
