### ISSUE TITLE
Accidently set baud rate

### ISSUE THREAD

**Issue by Hashifier** [esp8266/Arduino#3344]
I accidantly set my baudrate on my ESP-12E to 100,000 using AT+CIOBAUD and now I cannot do anything with it. I cannot even flash it, anyone has an idea how to resolve this?
PC: Windows 10
ESP-12E

**Comment by devyte** [comment]
I think you're in the wrong repository. You're referring to the AT command
set, but this firmware implements an on-board app that is not related.

**Comment by devyte** [comment]
Closing due to lack of response.
