### ISSUE TITLE
esp8266 httpclient Image file posting

### ISSUE THREAD

**Issue by GreenturnLabs** [esp8266/Arduino#3345]
I am trying to post image files of size around 15Kb, form my esp8266 device to non-sql database. The database support image attachment as base64 encoded data. I could post the json files of size less than 1KB, But the http post fails for size grater than 1460 bytes.

`HTTPClient http;
if( http.begin(myurl) ){
   delay(1000);
   char *auth = authString;
   http.setAuthorization(auth);

   http.addHeader("Content-Type","application/json",  false, true);
   int err = http.POST(largejsondata);
   Serial1.print("HTTP Post reutrns : ");Serial1.println(err);
}`

**Comment by d-a-v** [comment]
Dos it fail with an error, or simply http.POST() does not return ?

**Comment by GreenturnLabs** [comment]
Returns "-3" . That means "HTTPC_ERROR_SEND_PAYLOAD_FAILED".
In ESP8266HTTPClient.h:
`#define HTTPC_ERROR_SEND_PAYLOAD_FAILED (-3)`

Hardware : NodeMCU1.0
Arduino Version : 2.3.0

**Comment by d-a-v** [comment]
You could first try using the latest git version of esp8266/arduino which is the pre-2.4.0 version and contains a number of improvements.

**Comment by devyte** [comment]
@GreenturnLabs any progress with this?
