### ISSUE TITLE
Adding a board to the board.txt

### ISSUE THREAD

**Issue by lazyzero** [esp8266/Arduino#3346]
Hi,

it is more a general question about adding a board to the board.txt? Is there a policy? We are currently working on the design of a educational development board, and we like to have it with its own name in the list of ESP8266 boards. The definitions in the list are more or less the same as for the Wemos D1 mini.  

Sincerely yours

#### Hardware
Hardware:			?ESP-12e
Core Version:      	?2.1.0-rc2?

### Description

Problem description

**Comment by devyte** [comment]
The standing policy (which will be formalized in the short term), is to include boards that have a known manufacturer, have a product page, and are rather well known. In addition, we do not want to include boards that are redundant, i.e.: have the same definition as some other board that already exists.
If your board is not a formal product, i.e.: with a manufacturer and product page, and has the same definition as the Wemos D1 mini, then I suggest just using the wemos d1 mini board in the IDE.
Alternatively, you can probably keep private changes to board.txt in a git repo. You can then pull your changes on top of the officlal board.txt after installation, thereby accomplishing what you need.
Closing for now. 

BTW, if you do formalize your board as a product in the future, and it does become well known/popular, feel free to open a new issue, and then a PR with the relevant changes.
