### ISSUE TITLE
ConfigFile example

### ISSUE THREAD

**Issue by nguyenhunga5** [esp8266/Arduino#3355]
Hi,

I have problem with esp-12f module, after try ConfigFile, OTA update examples with latest Arduino IDE, my module cannot boot. I don't known why.

This is my flash_id

./esptool.py -p /dev/cu.usbserial-A602VN87 flash_id
esptool.py v2.0-beta3
Connecting........_____....._
Detecting chip type... ESP8266
Uploading stub...
Running stub...
Stub running...
Manufacturer: e0
Device: 4016
Hard resetting...

#### Hardware
Hardware:			ESP-12F
Core Version:      	?2.1.0-rc2?

### Sketch

ConfigFile example sketch

### Debug Messages
Exception 28: LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads
Decoding 441 results
0x40101ca3: trc_NeedRTS at ?? line ?
0x401021a6: wDev_ProcessFiq at ?? line ?
0x40101f40: wDev_ProcessFiq at ?? line ?
0x40201569: uart1_write_char_d at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_postmortem.c line 197
:  (inlined by) uart_write_char_d at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_postmortem.c line 161
0x40207e9c: esp_yield at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_main.cpp line 57
0x402010a7: delay at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_wiring.c line 51
0x402017c4: uart0_write_char at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/uart.c line 461
0x4020170d: print_stack at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_postmortem.c line 197
:  (inlined by) __wrap_system_restart_local at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_postmortem.c line 119
0x401044c4: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x4023ad80: sleep_reset_analog_rtcreg_8266 at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x4022c86b: user_uart_wait_tx_fifo_empty at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x40102243: wDev_ProcessFiq at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x40101f40: wDev_ProcessFiq at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x40100764: pp_soft_wdt_feed_local at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x40219f34: esf_buf_setup at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x4021b8cc: LightSleepWakedCbSetFunc at ?? line ?
0x4021b910: LightSleepWakedCbSetFunc at ?? line ?
0x4021b990: LightSleepWakedCbSetFunc at ?? line ?
0x4021af3c: pm_idle_sleep at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x4021c458: wifi_fpm_set_wakeup_cb at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x4010020c: umm_assimilate_down at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/umm_malloc/umm_malloc.c line 1186
0x4010068c: _umm_realloc at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/umm_malloc/umm_malloc.c line 1591
:  (inlined by) realloc at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/umm_malloc/umm_malloc.c line 1709
0x4021dfad: hostap_input at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x40224e00: cnx_start_handoff_cb at ?? line ?
0x4022266c: ieee80211_scan_attach at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x40222948: scan_pm_channel_op_cb at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x4022b754: ppInstallKey at ?? line ?
0x4022b808: wpa_config_assoc_ie at ?? line ?
0x4022b614: ppInstallKey at ?? line ?
0x4022b770: ppInstallKey at ?? line ?
0x4022b9d8: wpa_neg_complete at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x40222d54: scan_clear_channles at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x40207f70: init_done() at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_main.cpp line 57
0x4022c7a0: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x40201030: micros_overflow_tick at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_wiring.c line 56
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x40100110: cont_ret at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/cont.S line 118
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x4022c788: user_uart_wait_tx_fifo_empty at ?? line ?
0x401044e3: wdt_feed at ?? line ?
0x401044c4: wdt_feed at ?? line ?
0x40103109: lmacProcessTXStartData at ?? line ?
0x40103106: lmacProcessTXStartData at ?? line ?
0x401020ea: wDev_ProcessFiq at ?? line ?
0x401044dd: wdt_feed at ?? line ?
0x401044da: wdt_feed at ?? line ?
0x40101f40: wDev_ProcessFiq at ?? line ?
0x40208de6: EspClass::flashWrite(unsigned int, unsigned int*, unsigned int) at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/Esp.cpp line 511
0x40208de6: EspClass::flashWrite(unsigned int, unsigned int*, unsigned int) at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/Esp.cpp line 511
0x40105568: spi_flash_write at ?? line ?
0x40207f14: __yield at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_main.cpp line 57
0x40208de6: EspClass::flashWrite(unsigned int, unsigned int*, unsigned int) at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/Esp.cpp line 511
0x40208c68: spiffs_hal_write(unsigned int, unsigned int, unsigned char*) at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs_hal.cpp line 116
0x40100ec2: pp_post at ?? line ?
0x401041bf: lmacRxDone at ?? line ?
0x40101bd9: trc_NeedRTS at ?? line ?
0x40101d68: trc_NeedRTS at ?? line ?
0x401021a6: wDev_ProcessFiq at ?? line ?
0x40101f40: wDev_ProcessFiq at ?? line ?
0x40208bca: spiffs_hal_read(unsigned int, unsigned int, unsigned char*) at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs_hal.cpp line 78
0x402056c9: spiffs_phys_rd at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_cache.c line 140
0x402035d4: spiffs_obj_lu_scan at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_nucleus.c line 941
0x401052a3: flash_gd25q32c_read_status at ?? line ?
0x4020580c: spiffs_phys_wr at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_cache.c line 204
0x40208dac: EspClass::flashEraseSector(unsigned int) at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/Esp.cpp line 507
0x40207f54: optimistic_yield at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_main.cpp line 57
0x402034dc: spiffs_erase_block at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_nucleus.c line 941
0x40208b3c: spiffs_hal_read(unsigned int, unsigned int, unsigned char*) at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs_hal.cpp line 45
0x40208bf8: spiffs_hal_write(unsigned int, unsigned int, unsigned char*) at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs_hal.cpp line 102
0x40208d34: spiffs_hal_erase(unsigned int, unsigned int) at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs_hal.cpp line 168
0x4020206c: SPIFFS_format at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs_hydrogen.c line 981
0x40208a10: SPIFFSImpl::begin() at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/spiffs_api.h line 128
0x402010b2: delay at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_wiring.c line 54
0x40209185: fs::FS::begin() at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/FS.cpp line 251
0x40207808: setup at /Users/hungnguyenthanh/Documents/untitled folder/ConfigFile/ConfigFile.ino line 78
0x40207ee0: loop_wrapper at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_main.cpp line 57
0x40100108: cont_norm at /Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/cores/esp8266/cont.S line 109
0x4022c7a0: user_uart_wait_tx_fifo_empty at ?? line ?
0x402106c4: dns_recv at /Users/ivan/e/arduino-esp8266/tools/sdk/lwip/src/core/dns.c line 300
0x40212980: arp_timer at /Users/ivan/e/arduino-esp8266/tools/sdk/lwip/src/core/timers.c line 372
0x40212960: dhcp_timer_coarse at /Users/ivan/e/arduino-esp8266/tools/sdk/lwip/src/core/timers.c line 372
0x40212940: dhcp_timer_fine at /Users/ivan/e/arduino-esp8266/tools/sdk/lwip/src/core/timers.c line 372
0x40212920: igmp_timer at /Users/ivan/e/arduino-esp8266/tools/sdk/lwip/src/core/timers.c line 372
0x40212900: dns_timer at /Users/ivan/e/arduino-esp8266/tools/sdk/lwip/src/core/timers.c line 372
0x4021283c: tcpip_tcp_timer at /Users/ivan/e/arduino-esp8266/tools/sdk/lwip/src/core/timers.c line 372
0x40224cfc: cnx_connect_timeout at ?? line ?
```
messages here
```

**Comment by devyte** [comment]
Are you working from Windows? Are you programming trying to flash from the Arduino IDE? Specifically which sketch is giving you trouble? Which core version? Which board? or is it a standalone ESP-12?
I can confirm that both 2.3.0 and the current git works fine on a all of Nodemcu v3 lolin, Wittycloud, and Wemos D1 mini v2, so I suspect user error of some kind.

**Comment by nguyenhunga5** [comment]
hi @devyte My fault, my power not enough.
