### ISSUE TITLE
esp8266

### ISSUE THREAD

**Issue by tarunhv** [esp8266/Arduino#336]
I'm getting this error in each and every program i compile in arduino.
Arduino: 1.6.4 (Windows 7), Board: "Generic ESP8266 Module, 80 MHz, 115200, 512K (64K SPIFFS)"

In file included from Blink.ino:18:0:
C:\Users\user\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.4-673-g8cd3697\cores\esp8266/Arduino.h:27:20: fatal error: stdlib.h: No such file or directory
#include 
^
compilation terminated.
Error compiling.

This report would have more information with
"Show verbose output during compilation"
enabled in File > Preferences.

DO any one have any solution??

**Comment by Links2004** [comment]
please retry in last release, If it still a problem feel free to reopen.
