### ISSUE TITLE
Does analogWrite(pin, MAX_PWM_VALUE) uses PWM or just sets the pin high?

### ISSUE THREAD

**Issue by Defozo** [esp8266/Arduino#3364]
#### Hardware
Hardware:			ESP-07S
Core Version:      	2.4.0-rc1

### Description

Does `analogWrite(BLUE_LED_PIN, 1024)` uses PWM or just sets the pin high?
I'm asking because I have a problem with DHT22 - I get many timeouts and I wonder if changing this line  with analogWrite to setting pin like `digitalWrite(BLUE_LED_PIN, HIGH);` would help?
I'm using analogWrite because I'm using PWM sometimes but most of the time I have just set it to max value.

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB
CPU Frequency:		160Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz
Upload Using:		OTA / SERIAL
Reset Method:		ck

**Comment by vicnevicne** [comment]
According to the documentation at https://github.com/esp8266/Arduino/blob/master/doc/reference.rst , only a value of 0 disables PWM. 
This is in line with the the implementation at https://github.com/esp8266/Arduino/blob/master/cores/esp8266/core_esp8266_wiring_pwm.c , so all other values - including the maximum, lead to PWM being initialized and used. 

Anyway, as this is not an issue with the Arduino core, I suggest you close this issue and direct further questions to esp8266.com or stackoverflow.
