### ISSUE TITLE
ESP Exception (9) and wdt reset when accessing a derived class through a base class pointer

### ISSUE THREAD

**Issue by ashiroji** [esp8266/Arduino#3365]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			ESP-12E
Core Version:      	2.4.0-rc1-12-gb695898

### Description
Hi , I'm building some classes to deal with various things in my project .

I have a Base Class that I use to access  its Children Template Classes via a pointer .

I'm currently facing a problem that I don't understand . 
I'm using runtime polymorphism to get the correct data from the correct sensor.
but in the "optimal" use case my code fails(see code V1 ) . On the first run I get an exception , after reset I always get the  watch dog  reset message .

Although trying it in another way works perfectly ( see code V0).

Am I losing my references when going out of the begin function ?

Thank you for the help

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB/1MB
CPU Frequency:		80Mhz
Flash Mode:			dio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		ck 

### Sketch V0 : works correctly 
```
void read() {
        Serial.println("enter the for");	
	for(int i=0;i<sensorsNumber;i++)
	{		
		if( (sensors[i].reference) == "NDIR_I2C" )
		{	

			ExternalSensor<NDIR_I2C> ndirCO2(77);
			sensors[i].exSensor=&ndirCO2;
			sensors[i].exSensor->begin();
                        Serial.println("reading " );	 
		        Serial.println(sensors[i].exSensor->read() );
		        	
		         delay(100); 

		}
	}
}

```

### Sketch V1 : crashes ESP with the following exception and/or reset msg

```
void begin() {
for(int i=0;i< this->sensorsNumber ; i++)
	{
		if( (sensors[i].reference) == "NDIR_I2C" )
		{	

			ExternalSensor<NDIR_I2C> ndirCO2(77);
			sensors[i].exSensor=&ndirCO2;
			sensors[i].exSensor->begin();

		}
        }
}
void read() {
        Serial.println("enter the for");	
	for(int i=0;i<sensorsNumber;i++)
	{		
		Serial.println("reading " );	 
		Serial.println(sensors[i].exSensor->read() );
		delay(100); 
	}
}
```

### Debug Messages
reset message :
```
 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
vb6958986
~ld
```

Stack decode:
```

Exception 9: LoadStoreAlignmentCause: Load or store to an unaligned address
Decoding 12 results
0x4020bb4d: ExternalSensors::read() at /home/ashiroji/Arduino/libraries/ArduinoJson/src/ArduinoJson/Deserialization/JsonParserImpl.hpp line 130
0x4023f94b: wifi_station_get_connect_status at ?? line ?
0x4020bb49: ExternalSensors::read() at /home/ashiroji/Arduino/libraries/ArduinoJson/src/ArduinoJson/Deserialization/JsonParserImpl.hpp line 130
0x4010020c: _umm_free at /home/ashiroji/Téléchargements/arduino-1.8.2/hardware/esp8266com/esp8266/cores/esp8266/umm_malloc/umm_malloc.c line 1287
0x4010068c: free at /home/ashiroji/Téléchargements/arduino-1.8.2/hardware/esp8266com/esp8266/cores/esp8266/umm_malloc/umm_malloc.c line 1733
0x40215b07: String::move(String&) at /home/ashiroji/Téléchargements/arduino-1.8.2/hardware/esp8266com/esp8266/cores/esp8266/WString.cpp line 519
0x4023f947: wifi_station_get_connect_status at ?? line ?
0x40207ed6: String::operator+=(String const&) at /home/ashiroji/Téléchargements/arduino-1.8.2/hardware/esp8266com/esp8266/cores/esp8266/WString.h line 117
:  (inlined by) CoolBoard::onLineMode() at /home/ashiroji/Arduino/libraries/CoolBoard/CoolBoard.cpp line 100
0x40207164: CoolBoard::connect() at /home/ashiroji/Arduino/libraries/CoolBoard/CoolBoard.cpp line 86
0x40206efc: loop at /tmp/arduino_modified_sketch_267956/CoolBoardExemple.ino line 32
0x402164bc: loop_wrapper at /home/ashiroji/Téléchargements/arduino-1.8.2/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_main.cpp line 57
0x4010070c: cont_norm at /home/ashiroji/Téléchargements/arduino-1.8.2/hardware/esp8266com/esp8266/cores/esp8266/cont.S line 109


```

**Comment by devyte** [comment]
```
{
ExternalSensor<NDIR_I2C> ndirCO2(77);
sensors[i].exSensor=&ndirCO2;
sensors[i].exSensor->begin();
}
```

You are instantiating an object on the stack, then saving the ptr in a global structure. You then go out of scope, so the stack object is destroyed, and the ptr you saved points to garbage.

The first version works only because you don't seem to make use of the stack object outside of its scope.

This is language usage error. There is much wrong with your design, including the use of C++ polymorphism. I suggest researching more about C++ polymorphism, object scope, and C++ OOP in general.
If you need further assistance, please ask at esp8266.com or stackoverflow, as this is an issue tracker for the core libs, and not a discussion forum.
Closing.
