### ISSUE TITLE
Authentication and Data Encryption WPA-PSK, TKIP settings

### ISSUE THREAD

**Issue by beicnet** [esp8266/Arduino#3372]
Hello,

I'm trying to make a little **standalone AP Web Server** with **WeMos D1 mini**, but I can't figure out how to set the AP parameters to work with my HP iPAQ.

I need to configure my WeMos D1 mini AP with these specific parameters, to be able to connect:

Channel: **1**
Authentication: **WPA-PSK**
Data Encryption: **TKIP**

Sketch what I'm using:
```
#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <ESP8266WebServer.h>

const char* ssid = "MyAP";
const char* password = "12345678";
 
ESP8266WebServer server(80);

void handleRoot()
{
  server.send(200, "text/plain", "Hello from esp8266!");
}

void setup(void)
{
  Serial.begin(9600);
  Serial.println("");
  WiFi.mode(WIFI_AP);
  WiFi.softAP(ssid, password);
 
  IPAddress myIP = WiFi.softAPIP();
  Serial.print("IP Address: ");
  Serial.println(myIP);
 
  server.on("/", handleRoot);
 
  server.begin();
  Serial.println("HTTP server started");
}

void loop(void)
{
  server.handleClient();
}
```
Kind regards

**Comment by earlephilhower** [comment]
Closing as a "How do I...?" question.  For support like this, please consider using a forum like https://www.esp8266.com
