### ISSUE TITLE
New library for Wifi Connection

### ISSUE THREAD

**Issue by siriusgomes** [esp8266/Arduino#3373]
I've created a Library to allow me to change the wifi configuration (SSID and password) of a ESP8266 without re-flashing it.

It stores the SSID and password on the SPIFFS. On boot, it will read this data and attempt to connect, when it doesn't succeed, it would create an AP with both SSID and Password configurable by the user, where the user can connect to it and send new SSID and password to be written in the SPIFFS. After that, the ESP8266 reboots and it attempts again the connection. It's been very useful for me.

#include "WifiManeger.h"
WifiManeger wifiManeger;

void setup {
Serial.begin(9600);
// If it connects to the wifi on the SPIFFS file... 
if (wifiManeger.connectWifiSTA()) {
... // Run your program normally..
}
else {
    // This will start the AP mode...
    wifiManeger.connectWifiAP("<SSID>", "<password>");
... // Maybe turn on a led diagnostic, or show on the screen, or play a beep.
}

**Comment by devyte** [comment]
@siriusgomes it's always good to see initiative like this. I suggest looking at the current "official" WiFiManager, and comparing. You may want to compare usage with yours, and consider implementation of a compatible API. You could rename your lib SPIFFSWifiManager, for example.
Having said that, this is an issue tracker for the core, and not an announcement forum. I suggest publishing your lib in github, if you haven't already done so. Also, you may want to announce at a forum like esp8266.com or stackoverflow, and discuss with the community there.
Closing as off-topic.
