### ISSUE TITLE
ESP8266WebServer: Change HTTP_MAX_CLOSE_WAIT

### ISSUE THREAD

**Issue by gewisser** [esp8266/Arduino#3380]
#### Hardware
Hardware:			ESP-12

### Description
Hi.

In my project, ESP works as a web server. ESP receiving data, sends them to Arduino. Arduino sends out some sensors and returns the received data. Next, ESP sent data to the waiting client.

### Sending data to Arduino

```cpp
void handleRoot() {
  if (!server.hasArg("json")) {
    server.send(200, "application/json", "{\"ret\":false}");
    return;
  }
  // Send data to Arduino
  Serial.println(server.arg("json"));
}
```

### Receiving data from Arduino
```cpp
void loop() {
  server.handleClient();

  if(Serial.available()){
    String arduino_data = Serial.readStringUntil('\n');
    
    // It will work if less than 2 seconds have elapsed
    server.send(200, "application/json", arduino_data);
  }
}
```

Question:
Sensors can return a query for more than 2 seconds. ESP closes the connection as defined:
```cpp
#define HTTP_MAX_CLOSE_WAIT 2000
```
How to change this value?

## P.S.

```cpp
#undef HTTP_MAX_CLOSE_WAIT
#define HTTP_MAX_CLOSE_WAIT 10000
``` 
#### &uArr; does not work

**Comment by igrr** [comment]
`server.send` should only be used from web server callback (`handleRoot` in your example). In the case you describe, you can poll the sensor in the main loop and save the result into a global variable, then get the value of this variable in the web server callback, and call `server.send` there.
