### ISSUE TITLE
No networks when scanning?

### ISSUE THREAD

**Issue by MrBaconHawk** [esp8266/Arduino#3387]
Hardware:			ESP-12E Module
Core Version:      	2.0

-Description

When I log in and scan for networks, I get no results.  I've tried many times, everything else seems to be functioning but I cannot find networks at all.  Any reason why?

-Settings in IDE

Module:  			NodeMCU 1.0 ESP8266 Module
Flash Size: 		4MB/1MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	40Mhz
Upload Using:		USB

**Comment by MrBaconHawk** [comment]
Correction, Flash Size 4MB/3MB SPIFFS   and   Upload using: Serial

**Comment by MrBaconHawk** [comment]
And port was COM4

**Comment by devyte** [comment]
No sketch, old core. Closing due to lack of info, age. and can't reproduce.
