### ISSUE TITLE
DHCP client doesn't request new IP after release

### ISSUE THREAD

**Issue by imcatwhocode** [esp8266/Arduino#3388]
Most of DHCP-clients (dhcpd, for example) are catching server-initiated lease releasing and then, requesting new lease. But ESP8266 with ESP8266WiFi library does not.

When i removed dynamic lease, ESP8266 still use old lease, instead of requesting new one. At this time, dhcpd running on my Raspberry Pi 2 are requesting new lease, when i removes old one. Android and webOS built-in DHCP-clients have similar behavior.

**IDE:** Platform.io (espressif8266 1.3.0)
**Board:** NodeMCU 0.9
**Access Point:** Mikrotik hAP Lite
**DHCP Server:** RouterOS built-in

**Comment by d-a-v** [comment]
@imcatwhocode Have you tested this with the latest 2.4.2 release ?
