### ISSUE TITLE
Library folder not adding as a library in arduino IDE

### ISSUE THREAD

**Issue by rastogitech** [esp8266/Arduino#3393]
Hi, 
I wanna perform some http related tasks with Arduino. So, I tried to add `library` folder (https://github.com/esp8266/Arduino/tree/master/libraries) as a .zip library in Arduino IDE. But arduino not accepting this "library" folder as a .zip library and giving me an error message that `"Specified folder/zip file does not contain a valid library"`.

Help!

**Comment by devyte** [comment]
How is your issue related to ESP8266? I suspect you're in the wrong
repository.

Also, questions like that are better asked in forums, not in issue trackers
like this one.
