### ISSUE TITLE
Again WiFi.status()

### ISSUE THREAD

**Issue by SerhioRed** [esp8266/Arduino#3399]
2.4.1-rc1 still send 6 - Disconnected even if connected.

Using WiFiEventHandler - onSoftAPModeStationConnected I cannot check whether mobile phone connected to 8266 with right or wrong password. 

8266 use this handler while connecting but not when connected. 

Please help how to check that wifi connection established and right password entered.

**Comment by devyte** [comment]
Closing due to lack of info, and due to several fixes merged into lwip glule code and relevant heavy testing.
