### ISSUE TITLE
readme.md,  USB to ESP wiring diagram needs clarification

### ISSUE THREAD

**Issue by butchalline** [esp8266/Arduino#340]
Diagram label "USB - to - RS232" is incorrect.
Should be "USB to TTL" or even better, "USB to 3.3V TTL"

RS232C is a +/- 12 VDC protocol and would destroy(?) the ESP.

No problem for geeks, but fatal for noobs.

**Comment by Toshik** [comment]
AFAIK, ESP is 5v RX/TX levels tolerant

**Comment by butchalline** [comment]
Possibly, but 232 is still not a proper designation. TTL would be correct.

But why not be crystal clear and specify 3.3V TTL?

**Comment by duncan-a** [comment]
I'd certainly prefer to see 3.3V TTL (or maybe 3.3V FTDI?)

**Comment by Links2004** [comment]
fixed some time ago.
https://github.com/esp8266/Arduino/blob/master/doc/boards.md
