### ISSUE TITLE
Arduino CLI not working with D1  (cannot open linker script file {build.flash_ld})

### ISSUE THREAD

**Issue by odessa2** [esp8266/Arduino#3403]
I am unable to build any sketch for the Wemos D1 Mini. Using "Generic" the linking works fine. 
Compiling seems to work fine, the problem seems to appear afterwards.

I use the following command: 

`arduino --board esp8266:esp8266:d1_mini --port /dev/ttyUSB0 --upload ANYSKETCH.ino --verbose`

When building via IDE/GUI, no error occurs and everything works fine.

Am I doing something wrong? Am I missing some command line option? Is this a bug?

#### Software
IDE: 1.8.3
OS: Linux

#### Hardware
Hardware:		Wemos D1 Mini
Core Version:      	2.3

### Debug Message
```
/home/daniel/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: cannot open linker script file {build.flash_ld}: No such file or directory
collect2: error: ld returned 1 exit status
```

**Comment by igrr** [comment]
You need to include flash size into the board specification.
The wiki of arduino/Arduino repository had some document on specifying the fully qualified board name (FQBN). Here's how we do it in one of the headless build scripts: https://github.com/esp8266/Arduino/blob/master/tools/build.py#L47.
You can get the names of flash size options from boards.txt.
