### ISSUE TITLE
Fatal exception 0(IllegalInstructionCause): epc1=0x40106cf6, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

### ISSUE THREAD

**Issue by aatronics** [esp8266/Arduino#3404]
when i add "#include <ESP8266mDNS.h>" this file with "  if (!MDNS.begin("lighting")) {
    Serial.println("Error setting up MDNS responder!");
    while(1) { 
      delay(1000);
    }"
  MDNS.addService("http", "tcp", 80); "

I got the 
"Fatal exception 0(IllegalInstructionCause): epc1=0x40106cf6, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000 ................"
This message in serial monitor..

Plzzzzzzzzzz help

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by lrmoreno007** [comment]
You are making a infinite loop with
```
while(1) {}
```
And ESP8266 protects itself firing the WDT.

**Comment by aatronics** [comment]
Thanks a lot, I have used same example given in Arduino IDE

**Comment by devyte** [comment]
Please post your full minimal sketch that reproduces the problem. Otherwise this will be closed due to lack of info.
I am using MDNS myself, and it works for me.

**Comment by aatronics** [comment]
Ok I will send code

**Comment by devyte** [comment]
@aatronics also, please fill out the fields in the issue template. Providing that info is necessary.
And please try a fresh install (delete the old one, install from scratch), and try with latest git.
