### ISSUE TITLE
ESP8266httpUpdate: How to ensure correct/valid update-file?

### ISSUE THREAD

**Issue by tuxedo0801** [esp8266/Arduino#3412]
Hi there,
how do I prevent the http-ota-update from downloading a wrong/invalid firmware file?

Of course there is a MD5 check available. But what about a file-download which get's intercepted/redirected to a kind of malware source? The esp will download the "wrong" file, checks the file integrity with help of MD5 sum and will finally update with the malicious firmware...

Is there a https-example for http-ota-update somewhere?
Has anyone thought about signing the firmware-file? --> would be independant from https/ssl/tls/... 

br,
Alex

**Comment by tuxedo0801** [comment]
Just found this: #3105

**Comment by WheresWally** [comment]
Ok, I have been wondering about this for a while. I would not like to see a take over of ESP/Arduino cores via updater

**Comment by earlephilhower** [comment]
#5213 closed this with full crypto-signed update support, if you enable it.
