### ISSUE TITLE
SMTP program not running in my main program errors in below: I used here Wemos D1 ESP8266.. What i do plz send me in details.

### ISSUE THREAD

**Issue by abhijitsd55** [esp8266/Arduino#3422]
Please fill the info fields, it helps to get you faster support ;)

ERROR:

IP address: 192.168.1.144
Connect to  http://192.168.1.144

Panic C:\Users\ABHID\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WiFi\src\WiFiClientSecure.cpp:399 ax_port_realloc

ctx: cont 
sp: 3fff3670 end: 3fff3d40 offset: 01b0

>>>stack>>>
3fff3820:  40106cc6 3fffb7e8 00000082 3fffb580  
3fff3830:  00000478 00000001 00004840 40209ec9  
3fff3840:  3fffb6c0 40106c9a 3fffb6b0 40223cbb  
3fff3850:  3fffb580 3fffb7e8 00000081 40224921  
3fff3860:  00000001 00000000 00000000 00000000  
3fff3870:  3fffbb70 3fffba38 00000040 00000000  
3fff3880:  40101389 3fffabf0 00000041 00000041  
3fff3890:  00000000 00000001 00000081 3fffb7e8  
3fff38a0:  3fffb6b0 3fffabf0 00000000 40209ebb  
3fff38b0:  3fffb580 3fffabf0 3fffac48 0000007f  
3fff38c0:  3fffb7e8 3fffabf0 3fffabf0 40224be9  
3fff38d0:  00000002 00000001 00000000 40223d20  
3fff38e0:  00000100 00000100 3fffb438 3fffb548  
3fff38f0:  3fff8a74 00000100 3fffabf0 40225da4  
3fff3900:  3fffb438 3fffabd8 00000003 40226598  
3fff3910:  3fffab98 40106c9a 00000003 00000000  
3fff3920:  00000100 3fff9406 3fff3a48 40226a86  
3fff3930:  3fffabd8 3fffb438 3fff3a48 4022691c  
3fff3940:  3fff8a48 00000013 3fff3a48 402267bc  
3fff3950:  0000024f 00000004 3fff9406 00000000  
3fff3960:  00000004 3fff8a48 3fff9406 40222ae6  
3fff3970:  00000263 401034ab 00000002 3ffec380  
3fff3980:  00000001 00000000 00000020 40103b33  
3fff3990:  401033a4 3ffefe60 3ffec380 7fffffff  
3fff39a0:  126e4e4b 16128630 06b28108 cff008c7  
3fff39b0:  c7717e66 eec2edd4 3b1ffff0 f0c84ed6  
3fff39c0:  4338b0b9 307d18d0 5583a26a cb36119c  
3fff39d0:  424adbd1 c22ab5c0 38647811 6c186210  
3fff39e0:  af211b68 00000000 00000000 00000000  
3fff39f0:  00000000 00000000 00000000 00000000  
3fff3a00:  00000000 00000000 00000000 00000000  
3fff3a10:  00000000 00000000 00000000 00000000  
3fff3a20:  00000000 00000000 00000000 ef200000  
3fff3a30:  66469e1f ff71f7eb 67e9dd4a b7b7495e  
3fff3a40:  058ac940 0000042c 00000203 00000318  
3fff3a50:  3fff7540 00000263 00000001 00000000  
3fff3a60:  3fff7a10 00000000 50e23f2f d5d89814  
3fff3a70:  fd0db69f ef3d0e62 177c65fb 3fff8f75  
3fff3a80:  3fff7540 0000042c 00000491 40221392  
3fff3a90:  00000c3a 3fff75a0 00000c41 00020011  
3fff3aa0:  f31ec567 4cb8fdfd 47303529 764c0b80  
3fff3ab0:  206108fa a8a66205 3920b7a1 00000c41  
3fff3ac0:  3fff8f75 00000000 3fff75a0 402223d9  
3fff3ad0:  848d61c7 0e7ce849 b7efbb28 4507e417  
3fff3ae0:  620dd71d 1771e8ad d200f354 5545f5ce  
3fff3af0:  c06e4e09 3fff76c0 3fff7680 00000bc0  
3fff3b00:  00000c41 3fff9b77 0000003e 3fff76c0  
3fff3b10:  3fff75a0 3fff8f75 00000c41 00000c41  
3fff3b20:  3fff8f75 00000000 3fff75a0 40221f2e  
3fff3b30:  00000038 00000001 00000033 00000000  
3fff3b40:  3fff75a0 00000000 00000038 4022164c  
3fff3b50:  00020010 0000000b 00000010 00000c41  
3fff3b60:  00000033 00000016 3fff75a0 00000000  
3fff3b70:  00000000 3fff75a0 3fff75a0 40222062  
3fff3b80:  00000000 3fff8f75 3fff75a0 40222229  
3fff3b90:  00000000 3fff74a8 3fff75a0 402222b0  
3fff3ba0:  3fff51a0 4020c732 3fff3c5c 3fff2bac  
3fff3bb0:  3fff2bb0 3fff3c5c 3fff51b0 40209d3a  
3fff3bc0:  6cc87d4a 3fff2b84 4020c82c 3fff2b84  
3fff3bd0:  3ffea6f8 000001d1 3fff3c5c 40209f32  
3fff3be0:  3ffeaf60 6cc87d4a 3fff7310 4020a92d  
3fff3bf0:  00000009 000001d1 3fff3c5c 40209331  
3fff3c00:  3ffeaf60 6cc87d4a 3ffeaf60 6cc87d4a  
3fff3c10:  3ffea644 0000000a 00000003 4020e2a6  
3fff3c20:  3fff2ce0 3fff2ce0 3fff20b8 40209f48  
3fff3c30:  3fff2ce0 00000012 3fff20b8 402085da  
3fff3c40:  3ffea6f8 0000000d 3fff2ce0 4020c715  
3fff3c50:  3ffea534 3fff2ce0 3fff2ce0 3ffea8c8  
3fff3c60:  00000000 000003e8 3fff2ce0 3fff20d8  
3fff3c70:  3fff7470 3fff51b0 0101a8c0 4020e155  
3fff3c80:  00000009 3fff2ce0 3fff20b8 40208cbe  
3fff3c90:  3fff5b98 0000000f 00000000 3fff5bb8  
3fff3ca0:  0000000f 0000000e 3fff5bd8 0000000f  
3fff3cb0:  00000009 3ffeaf20 00000000 000003e8  
3fff3cc0:  00000850 00000000 00000000 3ffeaf60  
3fff3cd0:  9001a8c0 4020d718 4020d704 3fff5038  
3fff3ce0:  0000000f 00000009 3fff5018 0000000f  
3fff3cf0:  0000000e 3ffeaf60 320ba8c0 3ffeaf60  
3fff3d00:  00ffffff 3ffeaf60 9001a8c0 00000000  
3fff3d10:  00000000 00000000 00000000 3fff2d14  
3fff3d20:  3fffdc20 00000000 3fff2d0d 4020c86a  
3fff3d30:  00000000 00000000 3fff2d20 40100114  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld

My program:

/*
 * Demonstrate using an http server and an HTML form to control an LED.
 * The http server runs on the ESP8266.
 *
 * Connect to "http://esp8266WebForm.local" or "http://<IP address>"
 * to bring up an HTML form to control the LED connected GPIO#0. This works
 * for the Adafruit ESP8266 HUZZAH but the LED may be on a different pin on
 * other breakout boards.
 *
 * Imperatives to turn the LED on/off using a non-browser http client.
 * For example, using wget.
 * $ wget http://esp8266webform.local/ledon
 * $ wget http://esp8266webform.local/ledoff
*/

#include <ESP8266WiFi.h>    //main library of ESP8266 WIFI
//#include <WiFiClient.h>
#include <ESP8266WebServer.h>  //create server page
//#include <ESP8266mDNS.h>
//#include <WiFiClientSecure.h>

#include <EEPROM.h> //EEPROM read-write data
//#include <DNSServer.h>
#include "FS.h"
#include <stdio.h>
#include <string.h>

byte sendEmail();
byte eRcv(WiFiClientSecure client);
void efail(WiFiClientSecure client);
const char* user_base64 = "YWJoaWppdHNkNTVAZ21haWwuY29t"; //your gmail account in base64 - https://www.base64encode.org/
const char* user_password_base64 = "OTQwMzU0OTczMA=="; //your gmail password in base64
const char* from_email = "MAIL From:<abhijitsd55@gmail.com>"; //dummy from email
const char* to_email = "RCPT TO:<abhijitsd55@gmail.com>"; //your gmail account to sent to
int address = 0;
byte value;
const int IR = D8;  
const int LEDPIN1 = D5;
const int LEDPIN2 = D2;
const int LEDPIN3 = D1;
const int LEDPIN4 = D0;
const int LEDPIN5 = D10;
const int LEDPIN6 = D9;
const int LEDPIN7 = D3;
const int LEDPIN8 = D4;
const int WSensor = D7;
const int Alarm = D6;
//temperature sensor pin is A0 ..
// Fill in your WiFi router SSID and password
char ssidchar[20];
char passwordchar[20];
//const char* ssid1 = "JioFi2_AA53A5";
//const char* password1 = "PreciseA";
String msg="off";
String msg1;
String msg2;
String msg3;
String msg4;
String msg5;
String msg6;
String msg7;
String msg8;
String s[9]={"0","0","0","0","0","0","0","0","0"};
String data[]={"0","0","0","0","0","0","0","0","0"};
String t[]={"0","0","0","0","0"};
String c[]={"0","0","0","0","0"};
IPAddress apIP(192, 168, 11, 50);
IPAddress gateway(192,168,11,54);
//MDNSResponder mdns;
const char *myhostname = "precise1234";
ESP8266WebServer server( 80 );

void htmlcontent()
{ 
  
//working
  
 
  content +="</html>";
  server.send(200, "text/html", content);
}
// GPIO#0 is for Adafruit ESP8266 HUZZAH board. Your board LED might be on 13.
void htmlcontentConfig(){
  
//working

  
  String contents ="<!DOCTYPE HTML>";
  contents +="<html>";
  contents +="<head>";
contents +="</body>";
  contents +="<footer><a href=\"/\"> Monitor and Control </a> <a href=\"/help\"> Help </a></footer><br>";
  contents +="</html>";
  server.send(200, "text/html", contents);
}
void handlehelp(){
  String contenthelp ="<!DOCTYPE HTML>";
  contenthelp +="<html>";
contenthelp +="<head>";
  contenthelp +="<title>Help!!</title>";
 
  contenthelp +="</html>";
  server.send(200, "text/html", contenthelp);
}

void handleRoot()
{
  if (server.hasArg("USERNAME")) 
  {
    handleSubmit();
  }
  else {
    htmlcontent();
  }
}
void handleConfig()
{
  if (server.hasArg("USERNAME")) 
  {
    handleSubmit();
  }
  else {
    htmlcontentConfig();
  }
}
void handletheme(){
  if(server.hasArg("THEME1")){
    themes();
  }
  else{
    htmlcontentConfig();
  }
}
void themes(){
 
 //working
  htmlcontentConfig();  
}
void returnFail(String msg)
{
  server.sendHeader("Connection", "close");
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.send(500, "text/plain", msg + "\r\n");
}

void handleSubmit()
{

  //working

  htmlcontentConfig();
}
void emailadd()
{
  if (server.hasArg("EMAILID")) {
    handleaddemail();
  }
  else {
    htmlcontentConfig();
  }
  
  }
void handleaddemail()
{
  
//working

  }
void handleWSensor()
{
  if (server.hasArg("HEATCOOL")) {
    handleWlevel();
  }
  else {
    htmlcontentConfig();
  }
  
  }
void handleWlevel()
{

//working
 
  
  
  htmlcontentConfig(); 
}
void wifiIdPass()
{
//working
 
 
  htmlcontent();
  
  }

void returnOK()
{
  server.sendHeader("Connection", "close");
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.send(200, "text/plain", "OK\r\n");
}

/*
 * Imperative to turn the LED on using a non-browser http client.
 * For example, using wget.
 * $ wget http://esp8266webform/ledon
 */
void handleLEDon1()
{
//working
}
void handleLEDoff1()
{
//working
}
void handleLEDon2()
{
//working
}
void handleLEDoff2()
{
//working
}
void handleLEDon3()
{
//working
}
void handleLEDoff3()
{
 //working
}
void handleLEDon4()
{
//working
}
void handleLEDoff4()
{
//working
}
void handleWSensoron()
{
 //working 
}
void handleWSensoroff()
{
 //working
}

void handleNotFound()
{
  String message = "File Not Found\n\n";
  message += "URI: ";
  message += server.uri();
  message += "\nMethod: ";
  message += (server.method() == HTTP_GET)?"GET":"POST";
  message += "\nArguments: ";
  message += server.args();
  message += "\n";
  for (uint8_t i=0; i<server.args(); i++){
    message += " " + server.argName(i) + ": " + server.arg(i) + "\n";
  }
  server.send(404, "text/plain", message);
}
void  writeWSensor(bool WSon)
{
  if (WSon){
    digitalWrite(WSensor, 1);
    EEPROM.write(20,1);
  }else{
    digitalWrite(WSensor, 0);
    EEPROM.write(20,0);}
}
void writeLED1(bool LEDon)
{
  // Note inverted logic for Adafruit HUZZAH board
 if (LEDon){
    digitalWrite(LEDPIN1, 1);
    EEPROM.write(30,1);
 }else{
    EEPROM.write(30,0);
    digitalWrite(LEDPIN1, 0);}
}
void writeLED2(bool LEDon)
{
  // Note inverted logic for Adafruit HUZZAH board
  if (LEDon){
    digitalWrite(LEDPIN2, 1);
    EEPROM.write(40,1);  
  }else{
    EEPROM.write(40,0);
    digitalWrite(LEDPIN2, 0);}
}
void writeLED3(bool LEDon)
{
  // Note inverted logic for Adafruit HUZZAH board
  if (LEDon)
  {
    EEPROM.write(50,1);
    digitalWrite(LEDPIN3, 1);
  }else{
    EEPROM.write(50,0);
    digitalWrite(LEDPIN3, 0);}
}
void writeLED4(bool LEDon)
{
  // Note inverted logic for Adafruit HUZZAH board
  if (LEDon){
    EEPROM.write(60,1);
    digitalWrite(LEDPIN4, 1);
  }else{
    EEPROM.write(60,0);
    digitalWrite(LEDPIN4, 0);}
}

void setup(void)
{ 
  String wifipa[3];

  pinMode(LEDPIN1, OUTPUT);
  writeLED1(false);
  pinMode(LEDPIN2, OUTPUT);
  writeLED2(false);
  pinMode(LEDPIN3, OUTPUT);
  writeLED3(false);
  pinMode(IR, OUTPUT);
  digitalWrite(IR, 0);

  Serial.begin(115200);
 
  SPIFFS.begin();
  EEPROM.begin(512);
  WiFi.disconnect();
  WiFi.softAPdisconnect();
  WiFi.mode(WIFI_OFF);
  delay(500);
  File wpr = SPIFFS.open("/wifi.txt", "r");
  if (!wpr) {
      Serial.println("file open failed2");
  }
   for (int i=1; i<=2; i++){
    wifipa[i]= wpr.readStringUntil('\n');
   }
  wpr.close();
//  WiFi.mode(WIFI_AP_STA);
  String ssid = wifipa[1];                              // saved take from txt file..
  String password =  wifipa[2];                        //take saved txt data file..
  int ssidlen = ssid.length();                            //calculate length of string for convert to character
  int passwordlen = password.length();
  ssid.toCharArray(ssidchar, ssidlen);                    //convert string to char
  password.toCharArray(passwordchar, passwordlen);           //convert string into char
  //Serial.println(password.length());
  //Serial.println(ssid.length());
  Serial.println(ssidchar);
  Serial.println(passwordchar);
  WiFi.begin(ssidchar, passwordchar);
  Serial.println("");
  int con=0;
  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) 
  { con +=1;
    if(con==50){
      break;
    }
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
//  Serial.print("Connected to ");
 // Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
  IPAddress IP = WiFi.localIP();
  WiFi.softAPConfig(apIP, apIP, IPAddress(255, 255, 255, 0));
  WiFi.softAP("ESP_IOT","12345678");
  if((con==50)or(IP==IPAddress(0,0,0,0))){
    
    WiFi.mode(WIFI_AP);
    WiFi.softAPConfig(apIP, apIP, IPAddress(255, 255, 255, 0));
    WiFi.softAP("ESP_IOT","12345678");
    //server.begin();  
    IPAddress HTTPS_ServerIP = WiFi.softAPIP();
    Serial.print("Server IP is: ");
    Serial.println(HTTPS_ServerIP);
    
  }
//  if (MDNS.begin("precise18")) 
////  {
////    Serial.println("MDNS responder started");
//  }
 
  server.on("/", handleRoot);
  server.on("/config", handleConfig);
  server.on("/email", emailadd);
  server.on("/wifiid", wifiIdPass);
  server.on("/theme", handletheme);
  server.on("/help", handlehelp);
  server.on("/ledon1", handleLEDon1);
  server.on("/ledoff1", handleLEDoff1);
  server.on("/ledon2", handleLEDon2);
  server.on("/ledoff2", handleLEDoff2);
  server.on("/ledon3", handleLEDon3);
  server.on("/ledoff3", handleLEDoff3);
  server.on("/ledon3", handleLEDon3);
  server.on("/ledoff3", handleLEDoff3);
  server.on("/ledon4", handleLEDon4);
  server.on("/ledoff4", handleLEDoff4);
  server.on("/wsensor", handleWSensor);
  server.on("/wsensoron", handleWSensoron);
  server.on("/wsensoroff", handleWSensoroff);
  server.onNotFound(handleNotFound);
 
  server.begin();

  Serial.print("Connect to  http://");
  Serial.println(WiFi.localIP());
 // WiFiClientSecure client;
  
  if (sendEmail())                                        //errors for emailsending
  {Serial.println(F("Email sent"));}
  else {Serial.println(F("Email failed"));}
  
  
}

//void mailsend(){
//  if (sendEmail()) Serial.println(F("Email sent"));
//else Serial.println(F("Email failed"));
//}
byte sendEmail() //sending email function   //errors
{
  WiFiClientSecure client;

  if (client.connect("smtp.gmail.com", 465) == 1) {
    Serial.println(F("connected"));
  } else {
    Serial.println(F("connection failed"));
    return 0;
  }
  if (!eRcv(client)) return 0;
 // Serial.println(F("--- Sending EHLO"));
  client.println("EHLO 1.2.3.4"); if (!eRcv(client)) return 0;
  //Serial.println(F("--- Sending login")); 
  client.println("AUTH LOGIN"); if (!eRcv(client)) return 0;
  //Serial.println(F("--- Sending User base64")); 
  client.println(user_base64); if (!eRcv(client)) return 0;
  //Serial.println(F("--- Sending Password base64")); 
  client.println(user_password_base64); if (!eRcv(client)) return 0;
 // Serial.println(F("--- Sending From")); 
  client.println(from_email); if (!eRcv(client)) return 0;
 // Serial.println(F("--- Sending To")); 
  client.println(to_email); if (!eRcv(client)) return 0;
//  Serial.println(F("--- Sending DATA"));
  client.println(F("DATA")); if (!eRcv(client)) return 0;
  client.println(F("Subject: Esp8266 email test\r\n"));
  client.println(F("******This is from my ESP8266\n"));
  client.println(F("Hello "));
  client.println(F("."));
  if (!eRcv(client)) return 0;
  Serial.println(F("--- Sending QUIT"));
  client.println(F("QUIT"));
  if (!eRcv(client)) return 0;
  client.stop();
  Serial.println(F("disconnected"));
  return 1;
}

byte eRcv(WiFiClientSecure client)
{
  byte respCode;
  byte thisByte;
  int loopCount = 0;

  while (!client.available()) {
    delay(1);
    loopCount++;
    // if nothing received for 10 seconds, timeout
    if (loopCount > 10000) {
      client.stop();
      Serial.println(F("\r\nTimeout"));
      return 0;
    }
  }

  respCode = client.peek();
  while (client.available())
  {
    thisByte = client.read();
    Serial.write(thisByte);
  }

  if (respCode >= '4')
  {
    //  efail();
    return 0;
  }
  return 1;
}

void efail(WiFiClientSecure client)
{
  byte thisByte = 0;
  int loopCount = 0;

  client.println(F("QUIT"));

  while (!client.available()) {
    delay(1);
    loopCount++;
    // if nothing received for 10 seconds, timeout
    if (loopCount > 10000) {
      client.stop();
      Serial.println(F("\r\nTimeout"));
      return;
    }
  }

  while (client.available())
  {
    thisByte = client.read();
    Serial.write(thisByte);
  }
  client.stop();
  Serial.println(F("disconnected"));
}

void loop(void)
{
  
  server.handleClient();
  

}

**Comment by igrr** [comment]
WiFiClientSecure has received a number of fixes since this issue has been opened. Please try again with git version and report back.

**Comment by devyte** [comment]
Closing due to lack if feedback and bearssl integration.
