### ISSUE TITLE
i have the .h file in same as the ino file

### ISSUE THREAD

**Issue by jamieduk** [esp8266/Arduino#3426]
I get this error how do i fix?

Arduino: 1.8.2 (Windows 7), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

G:\Backup\New Arduino\RoboCar\RoboCar.ino:10:25: fatal error: ESP8266WiFi.h: No such file or directory

 #include <ESP8266WiFi.h>

                         ^

compilation terminated.

exit status 1

**Comment by devyte** [comment]
I don't even understand the description, but I suspect you have the wrong board selected.
This is not the correct place to ask for assistance, this is an issue tracker for the core libs. Please do some research and look at examples, or ask at esp8266.com/stackoverflow for discussion.
Closing.
