### ISSUE TITLE
How to read analog value on NodeMCU 0.9 ?

### ISSUE THREAD

**Issue by lesept777** [esp8266/Arduino#3427]
#### Hardware
Hardware:		NodeMCU 0.9
Core Version:      	??

### Description

Hello
I'm trying to read  an analog voltage using the ADC on a NodeMCU 0.9. I have seen some posts saying that there are some issues, but I don't know if they have been solved
My sketch is very simple: I connect a potentiometer between 3V3, GND and A0 and run the following program. The console always outputs 65535 whatever the value of the resistor.
I'm quite new to NodeMCU and ESP, so please be patient and start from the basics... I only know how to upload a program using the Arduino IDE...

Can anyone help me?

### Settings in IDE
Flash Mode:			Arduino IDE 1.8.2

### Sketch
ADC_MODE(ADC_VCC);
int val = 0;

void setup() {
  Serial.begin(9600);
}

void loop() {
  val = analogRead(A0);
  Serial.println(val);
}

**Comment by devyte** [comment]
ADC_MODE(ADC_VCC); is wrong, that is meant for using the ADC to read the internal supply voltage, not the analog input pin.

> I'm quite new

This is not the right place to ask for assistance. Please refer to esp8266.com or stackoverflow for discussion, and do research online.
Closing.
