### ISSUE TITLE
Only 31.5 KB sending by streamFile()

### ISSUE THREAD

**Issue by ElektroPrzewodnik** [esp8266/Arduino#3430]
Hello,

I'm sending files from SD card by server.streamFile() and receiving only 31.5 KB of them.
"ERR_CONTENT_LENGTH_MISMATCH"
Whats the deal!? 

esp version: 2.3.0
![shu_6jyavg](https://user-images.githubusercontent.com/22837585/28315687-d735df86-6bbf-11e7-9aa6-8865ba8fd359.jpeg)

**Comment by torntrousers** [comment]
Could it be the same as Issue 2915?

**Comment by igrr** [comment]
Fixed in #3209.
