### ISSUE TITLE
The module stops after the config

### ISSUE THREAD

**Issue by mcmega** [esp8266/Arduino#3432]
Hi all!
Use ESP8266-12 (D1 mini)
I write the firmware to the module, configure the connection parameters via the Web interface, reboot the module with the command ESP.restart ();
Reboot starts, but in the terminal I see:
ets Jan  8 2013,rst cause:2, boot mode:(1,6)
ets Jan  8 2013,rst cause:4, boot mode:(1,6)
wdt reset

And the module does not start!
The module is normally started only after pressing the Reset or power off button.

**Comment by mcmega** [comment]
Did so:
1. Connected Reset through a 100n capacitor to GND
2. Pullup Reset through the resistor to the VCC
3. GPIO15 connected with capacitor 10uF and Reset
When the module is started, I set "1" on GPIO 15. When you need to reset - set "0" and Wifi reboots.
Is this the correct solution?

**Comment by devyte** [comment]
@mcmega this is a known issue, and there is currently no known workaround. After uploading a sketch over serial, the module must be physically reset before using, or you'll get the described symptoms.
Closing.
