### ISSUE TITLE
Esp8266 error

### ISSUE THREAD

**Issue by Abdul2988** [esp8266/Arduino#3434]
### Description it keeps saying this: Arduino: 1.8.3 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

Archiving built core (caching) in: C:\Users\sosa\AppData\Local\Temp\arduino_cache_284288\core\core_esp8266_esp8266_nodemcuv2_CpuFrequency_80,UploadTool_esptool,UploadSpeed_115200,FlashSize_4M3M_4beafef8a25368dc356c168078b08d42.a
Sketch uses 198612 bytes (19%) of program storage space. Maximum is 1044464 bytes.
Global variables use 33014 bytes (40%) of dynamic memory, leaving 48906 bytes for local variables. Maximum is 81920 bytes.
error: Failed to open COM4
error: espcomm_open failed
error: espcomm_open failed

**Comment by Abdul2988** [comment]
and this Arduino: 1.8.3 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

Archiving built core (caching) in: C:\Users\sosa\AppData\Local\Temp\arduino_cache_284288\core\core_esp8266_esp8266_nodemcuv2_CpuFrequency_80,UploadTool_esptool,UploadSpeed_115200,FlashSize_4M3M_4beafef8a25368dc356c168078b08d42.a
Sketch uses 198612 bytes (19%) of program storage space. Maximum is 1044464 bytes.
Global variables use 33014 bytes (40%) of dynamic memory, leaving 48906 bytes for local variables. Maximum is 81920 bytes.
error: Failed to open COM4
error: espcomm_open failed
error: espcomm_open failed

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by JamesGKent** [comment]
this line: `error: Failed to open COM4` tells you everything you need to know. you do not have a COM4 on this pc, that is either because you are on the wrong port or you may have some driver issues.

**Comment by devyte** [comment]
If you unplug/replug the module, sometimes the COM can change.
In any case, this is not the right place to ask for usage assistance, as this is an issue tracker for the core libs. Please refer to esp8266.com or stackoverflow for discussion, or look at examples online.
Closing.

**Comment by yadakrishna21** [comment]
Archiving built core (caching) in: C:\Users\CHINTU\AppData\Local\Temp\arduino_cache_595012\core\core_esp8266_esp8266_nodemcuv2_CpuFrequency_80,UploadTool_esptool,UploadSpeed_115200,FlashSize_4M3M_67e4ff5307eb8c1eec9f1511e35f03cd.a
Sketch uses 554878 bytes (53%) of program storage space. Maximum is 1044464 bytes.
Global variables use 56968 bytes (69%) of dynamic memory, leaving 24952 bytes for local variables. Maximum is 81920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_open failed
