### ISSUE TITLE
Using GPIO on ESP-12 Ai-Thinker module

### ISSUE THREAD

**Issue by nccchirag** [esp8266/Arduino#344]
pinMode(5, OUTPUT);
digitalWrite(5, 1);

I'm not able to use any gpio ( ex 0,2,15 ).
Kindly can you please guide how to use various gpio pins alongwith the pin map.

eg. pinMode(6, FUNCTION_3); then how do we set its direction ?

**Comment by igrr** [comment]
```C++
pinMode(2, OUTPUT);
digitalWrite(2, HIGH);
delay(1000);
digitalWrite(2, LOW);
```
This should toggle GPIO 2.

GPIO6 is connected to the flash chip so it would be best not to reconfigure it.
Be aware that most ESP-12 modules gave GPIO4 and GPIO5 mixed up on the silk screen...

**Comment by nccchirag** [comment]
Yes 4 & 5 have been mixed up ! Thank you for the quick response
Got 4 & 5 working

**Comment by losaum** [comment]
Hi, 
Which board did you use to programming the AI-THINKER?

thanks!

**Comment by nccchirag** [comment]
Used a USB-UART module - Silicon Labs CP210x USB-UART Bridge

![usb-uart](https://cloud.githubusercontent.com/assets/7569367/9106247/6b7015fa-3c3c-11e5-9746-935d8bd50aad.jpg)

**Comment by losaum** [comment]
Hi!
But in IDE Arduino, NodeMCU 1.o or Generic ESP ... ?
For programming, you only put the jumper ?

Thanks!

**Comment by nccchirag** [comment]
Generic ESP
Yes just the jumper

**Comment by lucascastorina** [comment]
Hello from SPAIN!!!

IS possible to use GPIO6, GPIO7, GPIO11, GPIO8 on ESP8266-12E DEV BOARD?
I tried a simple sketch to do this, but nothing happened.
If you change to others GPIOxx seem to work well.

Thanks!!!!

**Comment by lrmoreno007** [comment]
This pins are used in SPI for communicate with flash memory and they are blocked. Nothing to do.
--------------------------------
Usa el buscador antes de preguntar "http://www.esp8266.com/viewtopic.php?f=13&t=3023" y no abras temas cerrados que no se corresponden siquiera. Este sitio de GitHub es para problemas en el código, no para consultar dudas tipo "How to". Para ese tipo de dudas utiliza el foro: www.esp8266.com

Saludos.
