### ISSUE TITLE
mDNS resolution is slow

### ISSUE THREAD

**Issue by mcmillion** [esp8266/Arduino#3449]
Quick question (sorry for opening an issue, but I couldn't find an answer anywhere else):

I've got mDNS working and I can hit the aREST API on my ESP8266. Using the IP address is instant, but I've noticed that when using the hostname that resolution is fairly slow (4 or 5 seconds). Is this expected, or am I maybe doing something wrong?

**Comment by Aminabdiyan** [comment]
It was slow for me, after first connection I send esp local IP (WiFi.localIP()) to the client and substitute url with local lP in javascript

**Comment by devyte** [comment]
Closing in view of #5442 with a full rewrite of mdns.
