### ISSUE TITLE
Looks like I had a bad 8266 - we can delete this post

### ISSUE THREAD

**Issue by wmweis62** [esp8266/Arduino#3453]
I thought my 8266 was going to sleep mode, but it appears to have been a bad chip.

Not sure how to delete this post, but it is no longer needed. 

### Basic Info

Hardware
Makerfocus ESP8266 Module ESP-12E NodeMcu LUA WiFi Internet New Version Development board.

JBtek 4 channel DC 5v Relay module for Arduino Raspberry Pi DSP AVR PIC ARM

AMS1117-3.3v Power Supply Module Input 4.5-12v Output 3.3v

SNANSHI 5v 5A 25W LED Switching Power Supply Transformer 110 to DC5v output for LED Strip Light

Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			NodeMcu 1.0 (ESP 12-E module)
Flash Size: 		4MB/1MB
CPU Frequency:		80Mhz
Flash Mode:			
Flash Frequency:	
Upload Using:		On board Serial
Reset Method:		

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by JamesGKent** [comment]
instead of completely changing the body of the post, you should be able to mark it closed, so it no longer appears as an active issue.

**Comment by wmweis62** [comment]
Got it, thanks

**Comment by wmweis62** [comment]
James,

I do not see how to mark it closed.  ( I will be offline for the next several hours)

**Comment by JamesGKent** [comment]
you will probably need to log in on the website rather than replying via email, and there should be a button near the reply box to close the issue.

**Comment by wmweis62** [comment]
Hi James,

I logged in and cannot see a button to close the posting near the Reply button. What am I missing?


[cid:image001.jpg@01D3048D.AA93A920]

**Comment by JamesGKent** [comment]
you should see something like this:

![image](https://user-images.githubusercontent.com/11315221/28562009-91dc5d9e-7118-11e7-8b9a-c178bdb4540a.png)
note the grey button next to the comment button labeled "close issue"

**Comment by wmweis62** [comment]
Bad 8266 chip

**Comment by wmweis62** [comment]
Ah, it is closed now. Sorry, I had a similar post on the 8266 forum and I made the assumption you were telling me how to “close the Issue” on that forum.  I should have looked closer that you were talking about the posting on Github
