### ISSUE TITLE
can i read 100 bytes of data 

### ISSUE THREAD

**Issue by shivalingaraju** [esp8266/Arduino#3456]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:		Esp8266 12E
Core Version:      	2.3.0

### Settings in IDE

Module:  			ESP8266 12 E module
Flash Size: 		4MB
CPU Frequency:	80Mhz?
Flash Mode:		arduino ide
Flash Frequency:	40Mhz
Upload Using:		 SERIAL
Reset Method:		 nodemcu 1.0

Arduino Ide 1.6.4 

I tried all the values changing from 256 to 512 but I am not able to increase the buffer size please do help me

**Comment by devyte** [comment]
The description is pretty much empty, and the one sentence provided makes no sense. Please gather your thoughts, do some research, look at examples, and open a new issue with details if still needed.
Closing.
