### ISSUE TITLE
How would you solve for take only the JSON response, ignoring all headers?

### ISSUE THREAD

**Issue by e1016** [esp8266/Arduino#3458]
WiFi connected
Server connected
Response: 
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json
etc...

but I only want a pice of this  (I solved it with algorithm)... exists any method or function?

**Comment by torntrousers** [comment]
Do you mean something like this: https://github.com/HarringayMakerSpace/usb-esp/blob/master/UsbEspDevice/UsbEspDevice.ino#L193-L203

**Comment by devyte** [comment]
This is a "how do I..." type of question. Please ask at esp8266.com/stackoverflow for assistance or discussion, as this is an issue tracker for tracking issues in the core.
Closing.
