### ISSUE TITLE
Cannot access my wifi router because there are two wifi with same SSID. How to write function wifi.begin()?

### ISSUE THREAD

**Issue by trungkiendt9** [esp8266/Arduino#3459]
When wifi scan, it see 2 wifi router:
1. "Netis", "-30dB", BSSID:.....
2. "Netis", "-78dB", BSSID:.....

Wifi.begin("Netis", "*******") cannot connectted?.

Pls help!

**Comment by JamesGKent** [comment]
i believe there is another `Wifi.begin` overload that takes a bssid parameter, you could check the docs and try adding the bssid for the one you want.

**Comment by trungkiendt9** [comment]
OK. Thanks. Now it resolved.
I found the syntax: 
begin(char* ssid, char *passphrase = NULL, int32_t channel = 0, const uint8_t* bssid = NULL, bool connect = true);
I re-write:

const char* my_ssid     = "netis";
const char* my_password = "password";
unsigned char my_bssid[18] = { 0x.. 0x.., 0x38, 0x24, 0xba, 0x..};
It connected!.

**Comment by JamesGKent** [comment]
if it worked then please close this issue.

Thanks
