### ISSUE TITLE
Error uploading ESP8266 WifiScan Sketch

### ISSUE THREAD

**Issue by ranjoy85** [esp8266/Arduino#347]
Hello everyone,
I am not able to upload WiFiScan Sketch. I am on Arduino 1.6.4
Here is the error

Sketch uses 231,360 bytes (44%) of program storage space. Maximum is 524,288 bytes.
warning: espcomm_send_command: wrong direction/command: 0x00 0x08, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x00 0x08, expected 0x01 0x08
warning: espcomm_send_command: wrong direction/command: 0x00 0x08, expected 0x01 0x08
warning: espcomm_sync failed
error: espcomm_open failed

Any help would be highly appreciated.
##

**Comment by igrr** [comment]
and your serial adapter and OS are..?

**Comment by ranjoy85** [comment]
I have just updated the firmware ...
now the error is 
warning: espcomm_sync failed
error: espcomm_open failed
OS - Mac 10.10.3
Board - Generic ESP
Programmer = esptool

**Comment by igrr** [comment]
You seem to be using a very old version... esptool should not appear in programmers list, it is not necessary to select the programmer now.
What is the USB-serial adapter that you are using?

**Comment by ranjoy** [comment]
I was using 1.6.4, but then All tutorials r talking about esptoot. So i somehow Found 1.6.1. M using an arduino to power up. Can u suggest proper steps

**Comment by ranjoy85** [comment]
Now I started using 1.6.4 .. 
Board - Generic
Error - Build options changed, rebuilding all 
Sketch uses 198,360 bytes (37%) of program storage space. Maximum is 524,288 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
Attahed sktch
![thumb_img_5871_1024](https://cloud.githubusercontent.com/assets/3196806/7843680/d5af04b8-04c8-11e5-9602-1b5e3f57d912.jpg)

**Comment by ranjoy** [comment]
I was using 1.6.4, but then All tutorials r talking about esptoot. So i somehow Found 1.6.1. M using an arduino to power up. Can u suggest proper steps

**Comment by Hermann-SW** [comment]
Does any other sketch upload work for you?

I got same error message when having forgotten to connect GPIO0 to GND for flashing. Your photo seems to show 5 cables reaching ESP8266, but 6 are needed -- did you connect GPIO0 to GND for flashing?

Hermann.

**Comment by Links2004** [comment]
the reset pin of the Arduino shut be at GND in this case.
otherwise the bootloader from Arduino may corrupt the boot loading to the ESP8266.

**Comment by ranjoy85** [comment]
Yes, I figured it out and its working .. :-)

**Comment by ranjoy85** [comment]
Getting this message when ever i try to upload my sketch. 
What could be the issue. It seems to be working but all of a sudden it stopped. Is there a way I can reset ESP or upload the boot loader, may sound crazy but anything as such.
 
Sketch uses 198,360 bytes (37%) of program storage space. Maximum is 524,288 bytes.
warning: espcomm_sync failed
error: espcomm_open failed

**Comment by kevinrhug** [comment]
Is it possible that the 3.3v pin on the UNO does not prvide enough POWER?  I connected the 5v pin to try to upload and it worked then to run the server I reconnected it to the 3.3v pin.  I think I am going to build a separate source for the ESP8266 that can provide more current at 3.3.. I was wondering if when it was connected to 5v that the arduino could not supply the amount of current necessary and as a result there was a voltage drop.

**Comment by CptanPanic** [comment]
Also the tx\rx pins on esp are not 5V tolerant and your arduino is prob using 5V on the serial.

**Comment by Links2004** [comment]
you have connected the 5V as VCC to the ESP? 
if yes you have mostly killed your ESP.
the esp require 3.3V and at least 250mA for working, more is better I mostly use a 3.3V 1A LDO or a step down regulator.

**Comment by kevinrhug** [comment]
It didn't kill it but it won't maintain the connection to my router for very long. I suppose that the damage may be the reason for this.  Do you program through the Arduino IDE? If so what programmer do you use?

**Comment by Links2004** [comment]
do you mean the serial adapter? its an FTDI.
programming works fine with it, including auto reset.
I add an LDO to the 5V of the usb to get stable 3V3 for the ESP.

**Comment by manojverma75** [comment]
Here it is the solution for this error. In this video also it was facing the same error but found the solution also
 Have a look to the youtube video
https://www.youtube.com/watch?v=0J1Nt4q7uCQ

**Comment by knsakib** [comment]
connect CH_PD to VCC/	3.3V. It should resolve this issue. After connecting turn of and on again. After correcting CH_PD if you see again, power off and on.

**Comment by narendra93** [comment]
it is not helping. It's repeatedly showing same error.

**Comment by SeanBannister** [comment]
To fix this, I realised I'd selected the wrong board under `Tools... Board...` you'll notice there's a list of ESP8266 boards listed under here.

**Comment by narendra93** [comment]
yes, but wont generic module work for basic esp - 07 or esp -01? One more thing, I found out while programming esp-01 that, only blink program uploaded, while others not.

**Comment by nomanahmed3** [comment]
had same issue...solution that worked for me....
gpio 0 at gnd permanentrly
when upload start....press reset button

i am using esp12e 
chpd---3.3v
rst----pullup with 10k and push button to pull down momenterily to reset 
gpio 2---3.3v
gpio 15 ---gnd

**Comment by lrmoreno007** [comment]
With ESP12, sometime I must hold GPIO0 connected to GND too. I don't know why.

**Comment by Igor50** [comment]
WARNING: No widget for SetWidgetProperty command?

**Comment by BananaAcid** [comment]
Just for your interest. I solved it, connecting the GND to the USB-Serial-Adapter (not only TX/RX) because I powered the device by my own circuit being powered by a micro-USB power not beeing connected to my PC.
BUT: using the USB power from my PC, as well as connecting the USB-Serial to the same PC, I did not need the GND connected to the USB-Serial (it works with Tx/Rx only).

**Comment by andreas-bulling** [comment]
@BananaAcid Thanks a lot for the hint with the GND - that solved my problem and certainly saved hours of further search online!
