### ISSUE TITLE
helloMesh sketch fails to compile: 'exchangeInfo' was not declared in this scope

### ISSUE THREAD

**Issue by rajasekarl** [esp8266/Arduino#3472]
C:\Users\LRAJA\Documents\Arduino\HELLO MESH-EXCHANGE INFO\HelloMesh\HelloMesh.ino: In function 'void loop()':

HelloMesh:54: error: 'exchangeInfo' was not declared in this scope

 bool flag=exchangeInfo("heloo",ESP.getChipId());

                                               ^

exit status 1
'exchangeInfo' was not declared in this scope

**Comment by devyte** [comment]
Closing due to lack of info.
