### ISSUE TITLE
FS does not work with WiFiClientSecure

### ISSUE THREAD

**Issue by jmseight** [esp8266/Arduino#3491]
Hi,

I have a ESP-12E sketch with the following libraries installed and used

#include <ESP8266WiFiMulti.h>
#include <ESP8266WebServer.h>
#include <RCSwitch.h>
#include <WiFiClientSecure.h>
#include <FS.h>
#include <WiFiUdp.h>
#include <Time.h>

This crashes when WiFiClientSecure is connected.  When I removed support for FS, it does not crash.  I suspect that this is a memory issue, that FS and WiFiClientSecure take too much memory.

The symptoms are as follows:
1) WiFiClient & FS: works well
2) WiFiClientSecure & FS: CRASHES
3) WiFiClientSecure & NO FS: works well

Thanks,
James

**Comment by igrr** [comment]
There have been some improvements in WiFiClientSecure memory footprint, so some usage of WiFiClientSecure + FS is now possible (for example to load certificates).
