### ISSUE TITLE
Is there any way to boost esp8266 power tx?

### ISSUE THREAD

**Issue by stevevaius77** [esp8266/Arduino#3493]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by devyte** [comment]
There is an espressif api to set tx power, which takes values from 1-82,
where 82 is max power, and the default.
So no.

Then, if you change PHY mode from 802.11n to b or g, you supposedly get
longer range.

For the ESP-7, you can use a high gain or directional antenna.

The ESP has a pretty good range, there was a range map done (I think it was
areresearch, I could be wrong), where they tested range in all directions.
If you need more, you might want to rethink your project.

Having said all the above, this is not the right place to ask this kind of
question. This is an issue tracker for the arduino core libs, and not a
support forum. Please close this.

**Comment by stevevaius77** [comment]
Thanks
