### ISSUE TITLE
Get PW from WPS configuration

### ISSUE THREAD

**Issue by MrD2** [esp8266/Arduino#3509]
How can i get Arduino WifiBeginWPS() password and ssid on successfull connection?

I tryed chasing the src code  but i'm stuck

(arduino) WifiSTA.h -> wifi_wps_enable/wifi_wps_disable -> (tools/sdk/include/user_interface.h) -> ??

I desire to save the configuration parameters of the successfull wps connection so i can use them on next reboot or in case power goes down.

How can i get these parameters without messing with ESP's core code? Is there a variable i can access?

**Comment by igrr** [comment]
`WiFi.SSID()` and `WiFi.psk()` return the currently stored password.

See docs: https://arduino-esp8266.readthedocs.io/en/2.4.0-rc2/esp8266wifi/station-class.html#ssid
