### ISSUE TITLE
NodeMCU as a WiFi adapter

### ISSUE THREAD

**Issue by sarimnaveed2** [esp8266/Arduino#3511]
I'm a little new to nodeMCU and I was wondering if I could use the nodeMCU esp8266 development board as a WiFi adapter for Raspberry pi 1 B+.

Can anyone tell me how can I use the nodeMCU as a WiFi adapter for the raspberry pi.

Sorry for my bad English.

**Comment by igrr** [comment]
Not exactly NodeMCU, but this is the closest you can get: https://hackaday.io/project/9300-esp-12f-raspberry-pi-gpio-sdio-wifi

**Comment by sarimnaveed2** [comment]
I've seen this before and I want for the nodeMCU....

_Sent from my Motorola XT1060 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
