### ISSUE TITLE
Sensor Flashing over I2C Bus

### ISSUE THREAD

**Issue by javiersenas** [esp8266/Arduino#3526]
Hello colleagues,

I am using a sensor connected to the ESP8266 via I2C pins. The FW (hex file) of the sensor (it has many configurable registers) can be preflashed before the main code runs.  Does any of you have an idea if I can use the ESP8266 to flash the FW (the hex file) of this sensor? I mean, is there any tool which routes a file from UART to I2C and, if possible, combine it in the bin file needed for the ESP8266 itself? Or can I use ESP8266 as bridge UART-I2C? Any suggestion is welcome.

Thanks in advance!

**Comment by suculent** [comment]
It would be worth mentioning which sensor. 

Depending on the firmware size you could store data on ESP,  turn the sensor to flashmode and send fw byte-by-byte. Depends on sensor documentation. 

Odesláno z iPhonu

16. 8. 2017 v 21:35, javiersenas <notifications@github.com>:

**Comment by javiersenas** [comment]
Sorry, I forgot it. This is a capacitive sensor Cypress' CY8MBR3008. Could
you please give more details about tools and procedures?

**Comment by devyte** [comment]
@javiersenas your project sounds interesting, but this is not the place to discuss it. This is an issue tracker for tracking issues in the core libs. Please ask for assistance/discussion at esp8266.com or stackoverflow.
