### ISSUE TITLE
WPA2-enterprise + PEAP

### ISSUE THREAD

**Issue by manzanazo** [esp8266/Arduino#3527]
How sells firmware to esp8266 with WPA2-enterprise + PEAP
Regards

**Comment by devyte** [comment]
The description of this issue makes absolutely no sense. Either improve it and add details, or close it.
If your intent is to use wpa2 enterprise, look through the PRs and open issues, there are some examples available.

**Comment by manzanazo** [comment]
Hi everybody,
I bought this module esp8266 wifi thinking to be able to advance in my project. We use Cisco Aironet 3700 Series Access Points, having a secure WPA2-enterprise + PEAP. But the command that we execute to integrate us to the Wi-Fi network, only asks ssid and password. And I have been looking for some update for this module and I found this website. And I have seen that a lot of you have already been working on the issue, and since I have not seen any trade that offers such an update I thought that if someone from here already made changes and worked, I could buy.
I bought this module esp8266 wifi thinking to be able to advance in my project. We use Cisco Aironet 3700 Series Access Points, having a secure WPA2-enterprise + PEAP. But the command that we execute to integrate to the Wi-Fi network, only asks for ssid and password. And I've been looking for some updates for this module and I came across this website. And I have seen that a lot of you have already been working on the issue, and since I have not seen any trade that offers such an update I thought that if someone from here already made changes and worked, I could buy.
Since I wrote this post, I studied the characteristics of the AP and it could be that there we could find the solution but could not confirm it right now.

Devyte, thanks for your attention.

**Comment by devyte** [comment]
The wpa2 enterprise topic has been asked several times, and there is a PR
somewhere with a reportedly working example, although I'm not sure about
PEAP. I suggest searching for that and giving it a try.
To try it, you have to use the latest git version of the core libs, and
pull the PR on top. If you don't know how to do that, there is an
explanation in readthedocs on how to use latest git, and research git for
pulling a PR, there are tutorials everywhere.

**Comment by ninjabe86** [comment]
this issue has a few workarounds in the following thread
https://github.com/esp8266/Arduino/issues/1032

**Comment by devyte** [comment]
@manzanazo any progress?

**Comment by manzanazo** [comment]
no yet.

**Comment by averri** [comment]
Why is this issue closed??? The problem has not been addressed, there are uncountable people asking for a solution to connect to WPA2-enterprise + PEAP. This is a very basic and mandatory requirement!

**Comment by d-a-v** [comment]
Because it's not an esp8266/arduino issue.
It has to do with espressif's firmware on which we do'nt have control.

https://github.com/espressif/ESP8266_NONOS_SDK/search?q=enterprise&type=Issues

which among other things relinks back here (as mentionned above, did you follow the link?)
[#1032(comment)](https://github.com/esp8266/Arduino/issues/1032#issuecomment-321812646)

**Comment by manzanazo** [comment]
Hello. The solution for my project was to use the esp8266 module without using access validation for each divice, an access point and a computer for each line, and also a tcp serial bridge.
Regards
