### ISSUE TITLE
Advanced Captive Portal Not Connecting in some PC's

### ISSUE THREAD

**Issue by santhosh8438** [esp8266/Arduino#3528]
Hi, I have used Advanced Captive portal for my code
In this the configuration page is not connecting(192.168.4.1) in some PC's,
I have disabled Anti-Virus in some PC's it's working well, But in some PC's it's not connecting 
I have checked with Windows 7,8 and 10 all have this issues!!!

This is my Code : 

#include <TimeLib.h> 
#include <ESP8266WiFi.h>
#include <WiFiUdp.h>
#include <ESP8266HTTPClient.h>
#include "user_interface.h"
#include <WiFiClient.h> 
#include <ESP8266WebServer.h>
#include <DNSServer.h>
#include <ESP8266mDNS.h>
#include <EEPROM.h>
#define ind_led 2
#define AC 4
#define L1 5
#define L2 12
#define L3 13
#define FAN 14

/* Set these to your desired softAP credentials. They are not configurable at runtime */
const char *softAP_ssid = "my_ESP";
const char *softAP_password = "123456789";

/* hostname for mDNS. Should work at least on windows. Try http://esp8266.local */
const char *myHostname = "esp8266";

/* Don't set this wifi credentials. They are configurated at runtime and stored on EEPROM */
char ssid[32] = "";
char password[32] = "";

// DNS server
const byte DNS_PORT = 53;
DNSServer dnsServer;

// Web server
ESP8266WebServer server(80);

/* Soft AP network parameters */
IPAddress apIP(192, 168, 4, 1);
IPAddress netMsk(255, 255, 255, 0);

/** Should I connect to WLAN asap? */
boolean connect;

/** Last time I tried to connect to WLAN */
long lastConnectTry = 0;

/** Current WLAN status */
int status = WL_IDLE_STATUS;

int dimming = 128;  // Dimming level (0-128)  0 = ON, 128 = OFF

int check_bit = 0;
String check_byte;
String req_data;
String MAC_ID = "CHM";
const char* host = "webapp.scoto.in";
String req_url ="/demo/homeauto/api/response/deviceget/deviceID/"+MAC_ID;
os_timer_t myTimer;
int httpPort = 80;
//const char ssid[] = "CIPL";              //  your network SSID (name)
//const char pass[] = "14062016";          // your network password

IPAddress timeServer(132, 163, 4, 101);  // time-a.timefreq.bldrdoc.gov

const float timeZone = 5.50;             // Central European Time

WiFiUDP Udp;
unsigned int localPort = 8888;           // local port to listen for UDP packets
int retry_ntp = 1;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  pinMode(AC,OUTPUT);
  pinMode(L1,OUTPUT);
  pinMode(L2,OUTPUT);
  pinMode(L3,OUTPUT);
  pinMode(FAN,OUTPUT);
  pinMode(ind_led,OUTPUT);
  get_macid();
  digitalWrite(ind_led,1);
  Serial.print("Configuring access point...");
  /* You can remove the password parameter if you want the AP to be open. */
   WiFi.softAPConfig(apIP, apIP, netMsk);
  WiFi.softAP(softAP_ssid, softAP_password);
  delay(500); // Without delay I've seen the IP address blank
  Serial.print("AP IP address: ");
  Serial.println(WiFi.softAPIP());
  Serial.println(softAP_ssid);
  /* Setup the DNS server redirecting all the domains to the apIP */  
  dnsServer.setErrorReplyCode(DNSReplyCode::NoError);
  dnsServer.start(DNS_PORT, "*", apIP);
  /* Setup web pages: root, wifi config pages, SO captive portal detectors and not found. */
  server.on("/", handleRoot);
  server.on("/wifi", handleWifi);
  server.on("/wifisave", handleWifiSave);
  server.on("/generate_204", handleRoot);  //Android captive portal. Maybe not needed. Might be handled by notFound handler.
  server.on("/fwlink", handleRoot);  //Microsoft captive portal. Maybe not needed. Might be handled by notFound handler.
  server.onNotFound ( handleNotFound );
  server.begin(); // Web server start
  Serial.println("HTTP server started");
  loadCredentials(); // Load WLAN credentials from network
  connect = strlen(ssid) > 0; // Request WLAN connect if there is a SSID
  
  attachInterrupt(15, zero_crosss_int, RISING);  // Choose the zero cross interrupt # from the table above
  while(WiFi.status() != WL_CONNECTED)
  {
    Serial.println("....");
    delay(10000);
    WiFi.printDiag(Serial);
    break;
  }
   Serial.println("connected");
}

void connectWifi() 
{
  Serial.println("Connecting as wifi client...");
  WiFi.mode(WIFI_STA);
  
  if
  (strlen(ssid)>0)
  {
     WiFi.disconnect();
     Serial.println(ssid);
     WiFi.begin ( ssid, password );
     delay(10000);
  } 
  int connRes = WiFi.waitForConnectResult();
  Serial.print ( "connRes: " );
  Serial.println ( connRes );
  delay(500);
  WiFi.printDiag(Serial);
  Udp.begin(localPort);
  setSyncProvider(getNtpTime);
}

void get_macid()
{
  String macid = WiFi.macAddress();       
  String macid1 = macid.substring(9,11);
  String macid2 = macid.substring(12,14);
  String macid3 = macid.substring(15,17);
  MAC_ID += macid1;
  MAC_ID += macid2;
  MAC_ID += macid3;
  Serial.print("MAC ID : ");
  Serial.println(MAC_ID);
}
time_t prevDisplay = 0; // when the digital clock was displayed

void loop() 
{
  while(WiFi.status() != WL_CONNECTED)
  {
    WiFi.mode(WIFI_AP);
    Serial.println("Configuration mode:!!!!!!!");
    delay(300);
    digitalWrite(ind_led,0);
    configure();        
  }
  delay(600);
  http_req();
  control_devices();
}

void configure()
{
  if (millis() > (lastConnectTry + 120000) ) 
    {
      /* If WLAN disconnected and idle try to connect */
      /* Don't set retry time too low as retry interfere the softAP operation */
      connectWifi();
      lastConnectTry = millis();
    }
    delay(300);
    digitalWrite(ind_led,1);
    // Do work:
    //DNS
    dnsServer.processNextRequest();
    //HTTP
    server.handleClient();
}

//the interrupt function must take no parameters and return nothing
void zero_crosss_int()  //function to be fired at the zero crossing to dim the light
{
  // Firing angle calculation : 1 full 50Hz wave =1/50=20ms 
  // Every zerocrossing thus: (50Hz)-> 10ms (1/2 Cycle) 
  // For 60Hz => 8.33ms (10.000/120)
  // 10ms=10000us
  // (10000us - 10us) / 128 = 75 (Approx) For 60Hz =>65

  int dimtime = (75*dimming);    // For 60Hz =>65    
  delayMicroseconds(dimtime);    // Wait till firing the TRIAC    
  digitalWrite(FAN, HIGH);   // Fire the TRIAC
  delayMicroseconds(10);         // triac On propogation delay 
         // (for 60Hz use 8.33) Some Triacs need a longer period
  digitalWrite(FAN, LOW);    // No longer trigger the TRIAC (the next zero crossing will swith it off) TRIAC  
}

void http_req()
{
  if (WiFi.status() == WL_CONNECTED) //Check WiFi connection status
  { 
    HTTPClient http;  //Declare an object of class HTTPClient
    Serial.print("starting HTTP Client\n");
    http.begin("http://webapp.scoto.in/demo/homeauto/api/response/deviceget/deviceID/"+MAC_ID);        //Specify request destination
    int httpCode = http.GET();                                                                  //Send the request
 
    if (httpCode > 0) //Check the returning code
    { 
      req_data = http.getString();   //Get the request response ssid_rec
      Serial.println(req_data);
      check_bit += 1;
    }
    http.end();   //Close connection
  }
}

/*-------- NTP code ----------*/

const int NTP_PACKET_SIZE = 48; // NTP time is in the first 48 bytes of message
byte packetBuffer[NTP_PACKET_SIZE]; //buffer to hold incoming & outgoing packets

time_t getNtpTime()
{
  while (Udp.parsePacket() > 0) ; // discard any previously received packets
  Serial.println("Transmit NTP Request");
  sendNTPpacket(timeServer);
  uint32_t beginWait = millis();
  while (millis() - beginWait < 1500) 
  {
    int size = Udp.parsePacket();
    if (size >= NTP_PACKET_SIZE) 
    {
      Serial.println("Receive NTP Response");
      Udp.read(packetBuffer, NTP_PACKET_SIZE);  // read packet into the buffer
      unsigned long secsSince1900;
      // convert four bytes starting at location 40 to a long integer
      secsSince1900 =  (unsigned long)packetBuffer[40] << 24;
      secsSince1900 |= (unsigned long)packetBuffer[41] << 16;
      secsSince1900 |= (unsigned long)packetBuffer[42] << 8;
      secsSince1900 |= (unsigned long)packetBuffer[43];
      retry_ntp=0;
      return secsSince1900 - 2208988800UL + timeZone * SECS_PER_HOUR;
    }
  }
  Serial.println("No NTP Response :( \n");
  retry_ntp = 1;
  return 0; // return 0 if unable to get the time
}

void user_init(void) 
{
      os_timer_setfn(&myTimer, timerCallback, NULL);
      os_timer_arm(&myTimer, 3600000, true);
}

void timerCallback(void *pArg) {
  Udp.begin(localPort);
  setSyncProvider(getNtpTime);
}

// send an NTP request to the time server at the given address
void sendNTPpacket(IPAddress &address)
{
  // set all bytes in the buffer to 0
  memset(packetBuffer, 0, NTP_PACKET_SIZE);
  // Initialize values needed to form NTP request
  // (see URL above for details on the packets)
  packetBuffer[0] = 0b11100011;   // LI, Version, Mode
  packetBuffer[1] = 0;     // Stratum, or type of clock
  packetBuffer[2] = 6;     // Polling Interval
  packetBuffer[3] = 0xEC;  // Peer Clock Precision
  // 8 bytes of zero for Root Delay & Root Dispersion
  packetBuffer[12]  = 49;
  packetBuffer[13]  = 0x4E;
  packetBuffer[14]  = 49;
  packetBuffer[15]  = 52;
  // all NTP fields have been given values, now
  // you can send a packet requesting a timestamp:                 
  Udp.beginPacket(address, 123); //NTP requests are to port 123
  Udp.write(packetBuffer, NTP_PACKET_SIZE);
  Udp.endPacket();
}

String dev_F1;
int rec_hour;
int rec_minute;
int RTC_hour;
int RTC_min;

void control_devices()
{
  if((check_bit == 1)) 
  {
    check_byte = "invalid";
  }
  
  if(check_byte != req_data)      //[{"status":"<000021245>"}]
  {
    check_byte = req_data;
    check_bit = 2;
    String dev_ac = req_data.substring(13,14);   
    String dev_L1 = req_data.substring(14,15);
    String dev_L2 = req_data.substring(15,16);
    String dev_L3 = req_data.substring(16,17);
    dev_F1 = req_data.substring(17,18);
    String dev_hour = req_data.substring(18,20);
    String dev_minute = req_data.substring(20,22);
    String dev_time = dev_hour+dev_minute;
    rec_hour = dev_hour.toInt();
    rec_minute = dev_minute.toInt();
    
    RTC_hour = hour();
    RTC_min = minute();
    Serial.print(RTC_hour);
    Serial.println(RTC_min);
    Serial.print(rec_hour);
    Serial.println(rec_minute);
    Serial.println(dev_F1);
    /********************************************* For Relay Board Control****************************************/
    
      if(dev_ac == "1") digitalWrite(AC,1);
      if(dev_ac == "0") digitalWrite(AC,0);
  
      if(dev_L1 == "1") digitalWrite(L1,1);
      if(dev_L1 == "0") digitalWrite(L1,0);
      
      if(dev_L2 == "1") digitalWrite(L2,1);
      if(dev_L2 == "0") digitalWrite(L2,0);
  
      if(dev_L3 == "1") digitalWrite(L3,1);
      if(dev_L3 == "0") digitalWrite(L3,0);
      
    /********************************************* For Fan Speed Control *******************************************/
                              /******************* Without OFF Time *********************/
       
      if(dev_F1 == "0")
      {
        dimming = 128;
        Serial.println("OFF");
      }
      if(dev_F1 == "1")
      {
        dimming = 80;
        Serial.println("\nLow Level");
      }
      if(dev_F1 == "2")
      {
        dimming = 64;
        Serial.println("\nMedium Level");
      }
      if(dev_F1 == "3")
      {
        dimming = 42;
        Serial.println("\nMedium High Level");
      }
      if(dev_F1 == "4")
      {
        dimming = 12;
        //Serial.println("\nHighLevel");
      }
      
    /**************************************************** Data Acknowledge ******************************************************/
                        
    WiFiClient client; 
    
    if (client.connect(host,httpPort)) 
    {
      Serial.println("Connected to server");
      String post_data  = ("/demo/homeauto/api/response/devicepost/data/");  
      post_data +=  dev_ac + ":" + dev_L1 + ":" + dev_L2 + ":" + dev_L3 + ":" + "0" + ":" + dev_F1 + ":"+ dev_time + ":" + MAC_ID;    
      //webapp.scoto.in/demo/homeauto/api/response/devicepost/data/1:1:1:1:0:0:0000:MAC_ID
      delay(10);
      client.print(String("GET ") + post_data + " HTTP/1.1\r\n" +"Host: " + host + "\r\n" + "Connection: close\r\n\r\n");
      Serial.println("\nAcknowledge sent successfully");
      Serial.print(host);
      Serial.println(post_data);
    }
    else
    {
      Serial.println("\nConnection to server failed!!! :( ");
      Serial.println("\nRetrying to connect with Server");
    }
  }
  else
  {
    Serial.println("No Change in Server!!!");
  }
  OFF_time();
}

void OFF_time()
{
    if((rec_hour != 88) && (rec_minute != 88))
      {
        while(retry_ntp == 1)
        {
          Serial.println("NTP server Time isn't Synchronized.... \n Wait for NTP server Sync....!!!");
          setSyncProvider(getNtpTime);
          delay(2000);
          Serial.println("Searching for NTP server.... Please Wait");
        }
        Serial.print(hour());
        Serial.println(minute());
        Serial.print(rec_hour);
        Serial.println(rec_minute);
        Serial.println("FAN OFF Time set");
        
        if((rec_hour == hour()) && (rec_minute == minute()))
        {
          dimming = 128;
          Serial.println("\nScheduling Off!!!");
        }
      }
}

handlehttp code : 
/** Handle root or redirect to captive portal */
void handleRoot() {
  if (captivePortal()) { // If caprive portal redirect instead of displaying the page.
    return;
  }
  server.sendHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  server.sendHeader("Pragma", "no-cache");
  server.sendHeader("Expires", "-1");
  server.setContentLength(CONTENT_LENGTH_UNKNOWN);
  server.send(200, "text/html", ""); // Empty content inhibits Content-length header so we have to close the socket ourselves.
  server.sendContent(
    "<html><head></head><body>"
    "<h1>Welcome to COMTUSTEC WiFi Configuration!!!</h1>"
  );
  if (server.client().localIP() == apIP) {
    server.sendContent(String("<p>You are connected through the soft AP: ") + softAP_ssid + "</p>");
  } else {
    server.sendContent(String("<p>You are connected through the wifi network: ") + ssid + "</p>");
  }
  server.sendContent(
    "<p><a href='/wifi'>CLICK ME</a> to Configure the WiFi Credentials.</p>"
    "</body></html>"
  );
  server.client().stop(); // Stop is needed because we sent no content length
}

/** Redirect to captive portal if we got a request for another domain. Return true in that case so the page handler do not try to handle the request again. */
boolean captivePortal() {
  if (!isIp(server.hostHeader()) && server.hostHeader() != (String(myHostname)+".local")) {
    Serial.print("Request redirected to captive portal");
    server.sendHeader("Location", String("http://") + toStringIp(server.client().localIP()), true);
    server.send ( 302, "text/plain", ""); // Empty content inhibits Content-length header so we have to close the socket ourselves.
    server.client().stop(); // Stop is needed because we sent no content length
    return true;
  }
  return false;
}

/** Wifi config page handler */
void handleWifi() {
  server.sendHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  server.sendHeader("Pragma", "no-cache");
  server.sendHeader("Expires", "-1");
  server.setContentLength(CONTENT_LENGTH_UNKNOWN);
  server.send(200, "text/html", ""); // Empty content inhibits Content-length header so we have to close the socket ourselves.
  server.sendContent(
    "<html><head></head><body>"
    "<h1>Wifi config</h1>"
  );
  if (server.client().localIP() == apIP) {
    server.sendContent(String("<p>You are connected through the soft AP: ") + softAP_ssid + "</p>");
  } else {
    server.sendContent(String("<p>You are connected through the wifi network: ") + ssid + "</p>");
  }
  server.sendContent(
    "\r\n<br />"
    "<table><tr><th align='left'>SoftAP config</th></tr>"
  );
  server.sendContent(String() + "<tr><td>SSID " + String(softAP_ssid) + "</td></tr>");
  server.sendContent(String() + "<tr><td>IP " + toStringIp(WiFi.softAPIP()) + "</td></tr>");
  server.sendContent(
    "</table>"
    "\r\n<br />"
    "<table><tr><th align='left'>WLAN config</th></tr>"
  );
  server.sendContent(String() + "<tr><td>SSID " + String(ssid) + "</td></tr>");
  server.sendContent(String() + "<tr><td>IP " + toStringIp(WiFi.localIP()) + "</td></tr>");
  server.sendContent(
    "</table>"
    "\r\n<br />"
    "<table><tr><th align='left'>WLAN list (refresh if any missing)</th></tr>"
  );
//  Serial.println("scan start");
//  int n = WiFi.scanNetworks();
//  Serial.println("scan done");
//  if (n > 0) {
//    for (int i = 0; i < n; i++) {
//      server.sendContent(String() + "\r\n<tr><td>SSID " + WiFi.SSID(i) + String((WiFi.encryptionType(i) == ENC_TYPE_NONE)?" ":" *") + " (" + WiFi.RSSI(i) + ")</td></tr>");
//    }
//  } else {
//    server.sendContent(String() + "<tr><td>No WLAN found</td></tr>");
//  }
  server.sendContent(
    "</table>"
    "\r\n<br /><form method='POST' action='wifisave'><h4>Connect to network:</h4>"
    "<input type='text' placeholder='network' name='n'/>"
    "<br /><input type='password' placeholder='password' name='p'/>"
    "<br /><input type='submit' value='Connect/Disconnect'/></form>"
    "<p>You may want to <a href='/'>return to the home page</a>.</p>"
    "</body></html>"
  );
  server.client().stop(); // Stop is needed because we sent no content length
}

/** Handle the WLAN save form and redirect to WLAN config page again */
void handleWifiSave() {
  Serial.println("wifi save");
  server.arg("n").toCharArray(ssid, sizeof(ssid) - 1);
  server.arg("p").toCharArray(password, sizeof(password) - 1);
  server.sendHeader("Location", "wifi", true);
  server.sendHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  server.sendHeader("Pragma", "no-cache");
  server.sendHeader("Expires", "-1");
  server.send ( 302, "text/plain", "");  // Empty content inhibits Content-length header so we have to close the socket ourselves.
  server.client().stop(); // Stop is needed because we sent no content length
  saveCredentials();
  connect = strlen(ssid) > 0; // Request WLAN connect with new credentials if there is a SSID
}

void handleNotFound() {
  if (captivePortal()) { // If caprive portal redirect instead of displaying the error page.
    return;
  }
  String message = "File Not Found\n\n";
  message += "URI: ";
  message += server.uri();
  message += "\nMethod: ";
  message += ( server.method() == HTTP_GET ) ? "GET" : "POST";
  message += "\nArguments: ";
  message += server.args();
  message += "\n";

  for ( uint8_t i = 0; i < server.args(); i++ ) {
    message += " " + server.argName ( i ) + ": " + server.arg ( i ) + "\n";
  }
  server.sendHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  server.sendHeader("Pragma", "no-cache");
  server.sendHeader("Expires", "-1");
  server.send ( 404, "text/plain", message );
}

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:		ESP8266 12E
Core Version:      	esp8266_nodemcuv2_CpuFrequency_80,UploadSpeed_921600,FlashSize_4M3M

### Description

Problem description

### Settings in IDE

Module:  			Generic ESP8266 12E Module
Flash Size: 		4MB
CPU Frequency:		80Mhz

**Comment by skx** [comment]
Please file your bug against the repository for the captive portal software you're using - this repository is for the esp8266 project itself, not random libraries that run upon it :)

**Comment by treii28** [comment]
I can't speak for the original poster, but I'm not so sure it's specific to a single project though. I have tried literally every captive portal example I have found on the internet, and I haven't been able to get one of them to work. There's an active thread right now over on the WiFiManager github and it refers back to the core code as a possible source of the problem.

**Comment by themindfactory** [comment]
I have implemented it this way in the past and when I connect to Android it
typically works but not always, on IOS its hit or miss and on Linux/Windows
its never.

Out of all that code only


*dnsServer.setErrorReplyCode(DNSReplyCode::NoError);dnsServer.start(DNS_PORT,
"*", apIP);
server.on("/generate_204", handleRoot); //Android captive portal. Maybe not
needed. Might be handled by notFound handler.
server.on("/fwlink", handleRoot); //Microsoft captive portal. Maybe not
needed. Might be handled by notFound handler.

are the important parts...

**Comment by nicogon** [comment]
Did some test with a raspberry and I got it working by 
-Setting the DNS to resolve all queries  to 172.217.28.206 (public ip of http://clients3.google.com/)
-Then have a tcp rule to forward all port 80 traffic to my host 
-> captive portal working in all platforms. 
The problem with esp libraries is that I haven't been able to forward outgoing 80 tcp traffic to esp host. 
Is there any way  of doing this?

**Comment by mcspr** [comment]
Should be covered with DNS server update and updated captive portal examples
