### ISSUE TITLE
Question: Http requests within isr

### ISSUE THREAD

**Issue by tonobo** [esp8266/Arduino#3543]
Is ist possible to use httpclient or wificlient or wifisecretclient within interrupt routines. I've discovered that i'm alway unable to open a connection within it. Within main loop all seems working

**Comment by davisonja** [comment]
I'd be very surprised if it worked.
Aside from supporting code reentrancy, it feels like a tcp connection would
take far too long.

**Comment by tonobo** [comment]
But the isr will be detached during runtime

Am 23.08.2017 23:30 schrieb "Julian Davison" <notifications@github.com>:

**Comment by tonobo** [comment]
I also tried to send a udp packet but this also won't work

**Comment by tttapa** [comment]
In an ISR, interrupts are disabled. You need interrupts for the TCP/IP and WiFi stuff to work.

If your ISR code does more than setting volatile flags, you're doing something wrong, and you need to rethink the design of your program.

Pieter

**Comment by suculent** [comment]
No that's not possible. You must store state in ISR only as it is not allowed to allocate any memory. You perform requests based on that state from main loop. 

Odesláno z iPhonu

23. 8. 2017 v 23:28, Tim Foerster <notifications@github.com>:
