### ISSUE TITLE
ESP8266 NodeMCU not detected by computer.

### ISSUE THREAD

**Issue by oemd001** [esp8266/Arduino#3551]
Hello I purchased a esp8266 NodeMCU and I connected the micro USB into the NodeMCU and connected via USB to my computer, which is running Windows 10 x64 bit. Nothing is showing up. However, the blue light on the esp8266 is flashing (occasionally) but no signal whatsoever from the computer.

Please help and respond?

Thanks!

**Comment by killa198921** [comment]
Did you install the USB driver ?
https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by NikolozCh** [comment]
Same problem, i have downloaded the drivers but still nothing :/ the blue lightning is flashing just

**Comment by devyte** [comment]
Either your board is bad, or your drivers are bad. The ones with ftdi can suffer from fake chips, which then get bricked on purpose by the original ftdi driver.
I have several Nodemcu boards, and they flash fine.
This is an issue tracker for the core, and not the right place to ask for support. Please refer to a community forum.
Closing per #3655 .

**Comment by SACHINKUMARHACKER** [comment]
Same situation happened with me, I also purchased a nodemcu board of amica which is not showing on my windows platform.

**Comment by pipi61** [comment]
check in device manager, if installed the usb driver, check serial port number,
and set this comp port number in arduino ide

**Comment by sshocked** [comment]
I had same problem but I solved it. My board flashed only flashed once(it all about I think what my usb wire works) but, pc still doesnt recognize it. So i installed like 1 thousand times drivers from silabs. But pc still doesnt see it and board still flashing. So i try to change my usb wire to another one, and pc recognized it)) So if yr pc doesnt see com port try ty change the wire.

**Comment by degustator** [comment]
Thanks to sshocked comment! Wire was the reason. Funniest moment  is that I expierenced this problem before and forgot. Lots of wires, that are supplied with devices for charging, aren't complete USB wires, there are probably ony 2 power leads inside

**Comment by phani5016** [comment]
@sshocked ; thankyou... it worked perfectly.. just changed the cable.... 

can i please know why  the cable makes  a difference? does it have anything to do with the length and impedance associated with it?

**Comment by ofSanjay** [comment]
thanks for these conversations. I try to change the cable and it works.

**Comment by arbelaju** [comment]
I tried to change my wire but it didn't work. So I solved installing this:

https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by SeppPenner** [comment]
I had to install the driver for the NodeMCU manually: https://github.com/nodemcu/nodemcu-devkit/tree/master/Drivers. Afterwards, it worked.

**Comment by chronoss09** [comment]
Thanks @SeppPenner

**Comment by WayneRiesterer** [comment]
@sshocked, nice work. It's been a while since I've dealt with hardware and forgot about this. I've faced this issue quite a few times before and keep forgetting that some cables don't offer a data connection. It's now working fine...on with the show :)

**Comment by EOM** [comment]
Same problem in the end was the change that does not have to pass data, was a cable for cellular charge, so I lost an hour in search of the solution.
**He passed**
1 - Install the USB-Serial Chip driver: CP2102 is CP210x (https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers)
2 - Connect USB cable with Data cable and ready
3 - Ready we enter Arduino and you have the COMx serial

**Comment by JPLoganlant** [comment]
Try a different cable

**Comment by cahbagus07** [comment]
if you use windows 10, use the windows 8 driver

**Comment by Harshac2** [comment]
> Hello I purchased a esp8266 NodeMCU and I connected the micro USB into the NodeMCU and connected via USB to my computer, which is running Windows 10 x64 bit. Nothing is showing up. However, the blue light on the esp8266 is flashing (occasionally) but no signal whatsoever from the computer.
> 
> Please help and respond?
> 
> Thank

same in case of my node mcu

**Comment by cahbagus07** [comment]
You can install the driver nodemcu

Pada tanggal Kam, 28 Feb 2019 21.05, Harshac2 <notifications@github.com>
menulis:

**Comment by jiashanzh** [comment]
Same problem.Finally, i find my micro usb-cable ,can only use for charge, cannot work well

**Comment by SeppPenner** [comment]
@jiashanzh This is also a quite common problem. Broken cables or cables that are usable for loading only...

**Comment by PabloVortex** [comment]
Same problem here. Resolved by changing wire. Thx

**Comment by MickPBduece** [comment]
> "I had same problem but I solved it. My board flashed only flashed once(it all about I think what my usb wire works) but, pc still doesnt recognize it. So i installed like 1 thousand times drivers from silabs. But pc still doesnt see it and board still flashing. So i try to change my usb wire to another one, and pc recognized it)) So if yr pc doesnt see com port try ty change the wire"

Some of ports work for flashing an some do not.  The ones that don't will power a device and copy files from my phone.   Maybe it's how the driver is applied?   I'd be curious if anyone has an idea why that would be.

**Comment by pixelartartist** [comment]
I have the same problem. I have downloaded ALL the drives, but they always say "Unable to find a device designed for this driver"
I have switch my Micro USB cables with the HUNDREDS I have at home and none of them work. It would be nice if they all were for charging, but most likely it's my pc.

Now, my pc does recognize that my a device is plugged in, but calls it Silicon labs CP210x USB to UART Bridge (COM3)

My Arduino IDE does not recognize this however. Any advice?

**Comment by Harshac2** [comment]
I finally  figured the problem out.
As it  my arduino editor softwares inability to find and access the
drivers.I just changed my arduino version 1.6.4 to 1.8.8 then the problem
was solved . With that I have done my mini project using esp8266.

**Comment by Harshac2** [comment]
If ur problem still not solved by turning from one arduino version to
another,then try it in another version .When  I struck with this problem I
checked 4-5 versions to solve the problem

**Comment by pixelartartist** [comment]
I have gone through versions 1.8.9-1.8.1
You sure this is will work?
Thanks for the advice though!

**Comment by Harshac2** [comment]
It worked for me in 1.8.8 after trying four versions

**Comment by pixelartartist** [comment]
Thanks @Harshac2, I seriously appreciate your help :)
Well, I look at the serial monitor and see that the module is scanning for networks, but not connecting to anything, it just continues to scan and nothing else WHILE telling me that there was an error compiling for the board.

**Comment by Harshac2** [comment]
Does it showing which port your node mcu is  connected?

**Comment by pixelartartist** [comment]
Yes but only in the Device Manager on my pc, not the IDE
I can connect my arduino Uno  and I will see on the IDE which port it is connected too, but not the ESP8266

**Comment by Harshac2** [comment]
Did you extracted all the driver in arduino files or not?

**Comment by Harshac2** [comment]
If your esp8266 still not connected then try with another arduino version
as l did like that

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
I have changed the usb cable, which worked...!

**Comment by jlar0che** [comment]
Same here - changing my USB cable solved the problem!

**Comment by TanmayNagdeve** [comment]
Leaving...
Hard resetting via RTS pin..

And nothing happens !!

**Comment by oldandslow1** [comment]
Also having similar issues of it not being detected by the pc, tried a couple of cables both of which work with Arduinos. 
Drivers are installed and work with other things (arduinos dispark).

I found if I press rts it will show for a second then the go off.
If I press rts then flash it will remain visible and I can upload blink sketch, it then starts to reboot and disconnect over and over.

last line is the same as the above post
Leaving...
Hard resetting via RTS pin..

It's not really possible to test other sketches as I can't access serial monitor because it's disconnected.

**Comment by oldandslow1** [comment]
Final update for anyone interested, the I believe the issue was lack of power.
I tried several cables all of which worked with arduinos and eSP32s but all failed with ESP8266.
They were all 1 meter long cables  so I purchased a shorter cable 0.5 meter and the ESP8266 works perfectly.

I did try the other cables again without success.

**Comment by SeppPenner** [comment]
@oldandslow1 I can't imagine that this issues corresponds to the length of the cables... Do both cables have a data wire? (Some USB cables only support power, not data...)

Nevertheless, checking the cables is always my first check now (I had this issue before with a broken USB cable and nearly needed half a day to figure that out)...

**Comment by oldandslow1** [comment]
> 
> 
> @oldandslow1 I can't imagine that this issues corresponds to the length of the cables... Do both cables have a data wire? (Some USB cables only support power, not data...)
> 
> Nevertheless, checking the cables is always my first check now (I had this issue before with a broken USB cable and nearly needed half a day to figure that out)...

The other cables came with various devices but I can use them to program other Arduinos and ESP32's without issues  and as mentioned they will program the ESP8266 but only after fiddling with the buttons (I don't need to do this with new cable)
Even after pressing the buttons  it wasn't working correctly, from what I read the ESP8266 draws quite a bit of current at start up and if it can't get enough it goes into a loop of trying to restart.

**Comment by SeppPenner** [comment]
> The other cables came with various devices but I can use them to program other Arduinos and ESP32's without issues and as mentioned they will program the ESP8266 but only after fiddling with the buttons (I don't need to do this with new cable)
Even after pressing the buttons it wasn't working correctly, from what I read the ESP8266 draws quite a bit of current at start up and if it can't get enough it goes into a loop of trying to restart.

Ok, really strange...

**Comment by pugrustler** [comment]
Had the same problem not connecting to pc. Tried other wires, install uninstall drivers, tried another cable. Nothing. Then I tried a good thick USB cable and it came to life. Don't use cheap USB cables.

**Comment by Googlewasmyidea** [comment]
I cannot believe this. The actual reason was because of the wire... Thanks @sshocked !

**Comment by boraaslan** [comment]
Some of usb wire is so dud. Please change the wire and try again. It will work %99.

**Comment by jpreiss** [comment]
For what it's worth, I was able to flash `blink` on a 2013 rMBP running 10.14 Mojave with no issues. I used the driver from https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers .

**Comment by parzibyte** [comment]
> I had to install the driver for the NodeMCU manually: https://github.com/nodemcu/nodemcu-devkit/tree/master/Drivers. Afterwards, it worked.

Yes, this is working. Thanks :)

**Comment by jeevansahu** [comment]
the blue led is not blinking in nodemcu(generic ) i install their driver also but its not working what would i do?

**Comment by disneyn** [comment]
> I had same problem but I solved it. My board flashed only flashed once(it all about I think what my usb wire works) but, pc still doesnt recognize it. So i installed like 1 thousand times drivers from silabs. But pc still doesnt see it and board still flashing. So i try to change my usb wire to another one, and pc recognized it)) So if yr pc doesnt see com port try ty change the wire.

I just wanted to say THANKS to user sshocked for helping me with this issue, it worked perfect just to swap to another cable! //Hans

**Comment by MickPBduece** [comment]
Maybe you did already but I marked a cable as being a good one after this
experience.

**Comment by sahilshaikh89** [comment]
Wire was the problem for me. Glad I found the comment from sshocked.

**Comment by tinashekadiki** [comment]
Installed drivers and it worked, https://github.com/nodemcu/nodemcu-devkit/tree/master/Drivers

**Comment by Langfo** [comment]
After a couple of months of trying different configurations to get my ESP8266 to work such as laptops running Windows, VM's running Linux, a Macbook and a Raspberry PI.  Then trying to install various drivers on Windows, OSX and Linux.  Then swapping in and out over 10 USB cables.  In the end what worked was finally finding a USB cable that was thicker (meaning this had the data wires connected and wasn't just a charging cable) as well as installing the nodemcu drivers for Windows as mentioned and linked throughout this comment thread.  You will know a data USB cable when you see it, it will look much thicker (see image)
![IMG_20200609_090828](https://user-images.githubusercontent.com/10135734/84088922-027bab00-aa31-11ea-8ff2-65b336cf5e21.jpg)

**Comment by dhajnes** [comment]
Hi,
I had a somewhat similar problem. I bought some spinoff ESP8266 NodeMCU, which is not really the NodeMCU, but a piece of hardware called "HW-628 V1.1".
I installed ALL THE DRIVERS on the internet (really, like at least 15 different) and then I read somewhere about those spinoffs not coming with any software installed on them, and thats apparentely an issue.

First, you need to get drivers for your UART/USB converter device built in your deck next to the USB (either CH340G - a rectangle or a CP2102 - a square).

For mine (CH340G) i found some here: https://sparks.gogo.co.nz/ch340.html . Downloaded .zip, installed .exe, installed the needed .inf file and then my wifimodule was finally recognised by my PC (Win 7 - yeah i know, its 2020 and i still got win7, so waht?).

Wish you luck!

**Comment by brother27** [comment]
Thanks for this post. I will have to go through my cables to find and mark the good ones.

**Comment by technoo10201** [comment]
> I had same problem but I solved it. My board flashed only flashed once(it all about I think what my usb wire works) but, pc still doesnt recognize it. So i installed like 1 thousand times drivers from silabs. But pc still doesnt see it and board still flashing. So i try to change my usb wire to another one, and pc recognized it)) So if yr pc doesnt see com port try ty change the wire.

Thanks you so much ! It worked for me.... Incredible 👍

**Comment by Al3x3i** [comment]
I had the same issue, luckily have found a cable that works. Some of them worked differently:
Cable:1 -> didn't do anything, just nothing, no LED
Cable 2 -> LED was blinking on the board but I could not connect/upload data. Did not appear in `sudo ls /dev/tty*`
Cable 3 -> worked fine, the USB cable was from Samsung S4 mini.

All cables which I have tried had the same thickness, only they had different physical "pinout". I tried on Windows10 and Ubuntu.

**Comment by Arjen997** [comment]
hi guys!

I also have some little troubles with this little device.
when i plug it into my computer, i can hear the sound, but...
my system does not recognize the device.

when i plug it in, the blue light will turn on and thats it.

an sound and an light.
i tried several things like installing the new driver, changing cables and at device management i turned hidden devices on.

i wonder if someone has any idea what to do.

**Comment by WiliTest** [comment]
When one nodemcu isn't detected by the PC (but the others are), is it necessarily dead(fried or bricked)?

**Comment by brother27** [comment]
These are small components. I use a magnifying glass in order to see anything. Glad you found the issue

**Comment by mikyjazz** [comment]
Just to have my say, after two days of testing and swearing I discovered that three (3) usb cables I was trying were "power only" !!! I have successfully used the cable from my Asus tablet!

**Comment by fkrnglc** [comment]
> I had to install the driver for the NodeMCU manually: https://github.com/nodemcu/nodemcu-devkit/tree/master/Drivers. Afterwards, it worked.

You are a life saver man. It solved my problem instantly.

**Comment by kyuzan22** [comment]
My node mcu was detected by my pc before, but after i used it for a while its not. Can anybody help?

**Comment by gsimon75** [comment]
In my case the problem was that the 12 MHz crystal wasn't soldered on well, so the CH340G usb-uart chip had no clock, and therefore couldn't talk usb at all, it hasn't even appeared in the device list.

After re-melting the solderings at the four corners of the crystal, it works fine. (The crystal is a 2mm by 3mm part right next to the usb-uart chip, with the label "12.000 MHz", soldered on at its four corners - at least it's supposed to... )

Recent linux kernels (mine is 5.6, Fedora 32) recognize the uart by default, there is no need for any custom kernel module building. The lsusb output for the device:

Bus 002 Device 030: ID 1a86:7523 QinHeng Electronics HL-340 USB-Serial adapter

**Comment by MoElaSec** [comment]
So to sum up everything:
1- check the cable if it's a Data or a power cable (old Samsung phones or Asus tablets for example will work great as noted ).
Note: thickness is not enough as we saw earlier on this thread (found [this](https://electronics.stackexchange.com/questions/140225/how-can-i-tell-charge-only-usb-cables-from-usb-data-cables#:~:text=The%20D%2B%2FD%2D%20lines,a%20%22charge%20only%20cable%22.) to know more info about cables).

2- check the correct drivers, Those are the drivers of the most used chips:

💾 [CP2102](https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers)
💾 [CH340](https://sparks.gogo.co.nz/ch340.html)

![image](https://user-images.githubusercontent.com/48570596/103398657-1fa3d280-4b57-11eb-9927-faeca40025ce.png)

**Comment by bonaminGR** [comment]
Hello everyone. 

This is gonna sound and look weird but I had the same problem as you guys. My NodeMCU could not connect to my PC. My Computer showed no COM device when I connected it. A blue light flashed on the ESP Module, but nothing else happened. 

After trying so many things I found online, (5 different data cables, many different USB ports, different PC, different software, installing CH340 Drivers etc) I still had no luck. 

AND THEN ! I stumbled upon this:
https://ceworkbench.wordpress.com/2017/01/15/fixing-ch340-problems-on-a-nodemcu-v3-board/

This guy found out that the USB Connector might not be soldered properly and an easy fix would solve the issue. 
But here is the fun part. Right when I was about to solder USB Data Wires on the CH340 chip, I saw something weird. 

The Chip was soldered the WRONG WAY from the factory.  ?DAFUQ? 

De-soldering the Chip and Soldering it again in the proper orientation solved the issue for me. 

I know. Sounds weird, but still, happened. :D 


![NodeMCU Fix](https://user-images.githubusercontent.com/46304806/104089231-ddc10d80-5275-11eb-9ed5-d9944e16c89a.jpg)

**Comment by abbottmd** [comment]
I never would have thought it would have mattered, but **changing the microusb cable to my nodemcu worked instantly**, after wasting an hour.  should have read these comments earlier. (ubuntu linux and using arduino IDE)

**Comment by matthijs88** [comment]
For people still having errors, I followed the steps on this website, which helped for me: https://www.usb-drivers.org/ft232r-usb-uart-driver.html

**Comment by gojimmypi** [comment]
I had this problem today... where the ESP8266 decided to just be another "not recognized" USB device after flashing, even though it was *just working* before the most recent flash.

Inspired by @sshocked [regarding a different cable](https://github.com/esp8266/Arduino/issues/3551#issuecomment-377798928), I tried removing it from my USB hub and plugging directly into the computer. TADA! Valid USB device. Oddly then, even moving it back to the hub, it was _still_ happy. Go figure.

**Comment by MrMinos** [comment]
For boards with the CH340 serial interface -- https://learn.sparkfun.com/tutorials/how-to-install-ch340-drivers/all

**Comment by gajanangomare79** [comment]
GUYS PLEASE HELP ME.
I HAVE INSTALL DRIVERS FOR SEVERAL TIME THEN ALSO PORT IS NOT VISIBLE IN ARDUINO IDE AND WHILE CONNECTION NO SOUND IS COMING AND ALSO NO LED IS BLINKING.

**Comment by brother27** [comment]
change your cable

**Comment by gajanangomare79** [comment]
i tried it.then also i'm getting same problem . before it was working well but i don't know why suddendly  it is not working.
guys please help me i have to submit by monday.

**Comment by pepe0pepe** [comment]
I tried everything whats in this forum too. what worked for me this: https://www.usb-drivers.org/ft232r-usb-uart-driver.html

**Comment by Bighoneypot** [comment]
Your S.O. version ??

**Comment by yelanetzichavez** [comment]
I just downloaded this driver and worked for me.

https://electropeak.com/learn/how-to-install-ch340-driver/

**Comment by QHuyCup** [comment]
> I had same problem but I solved it. My board flashed only flashed once(it all about I think what my usb wire works) but, pc still doesnt recognize it. So i installed like 1 thousand times drivers from silabs. But pc still doesnt see it and board still flashing. So i try to change my usb wire to another one, and pc recognized it)) So if yr pc doesnt see com port try ty change the wire.

It works !!!

**Comment by jovyllebermudez** [comment]
I have t he same problem,

And this one helped me, thanks for the images so I can quickly find this one. and understand that those are different hardwares
> So to sum up everything:
> 1- check the cable if it's a Data or a power cable (old Samsung phones or Asus tablets for example will work great as noted ).
> Note: thickness is not enough as we saw earlier on this thread (found [this](https://electronics.stackexchange.com/questions/140225/how-can-i-tell-charge-only-usb-cables-from-usb-data-cables#:~:text=The%20D%2B%2FD%2D%20lines,a%20%22charge%20only%20cable%22.) to know more info about cables).
> 
> 2- check the correct drivers, Those are the drivers of the most used chips:
> 
> 💾 [CP2102](https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers)
> 💾 [CH340](https://sparks.gogo.co.nz/ch340.html)
> 
> ![image](https://user-images.githubusercontent.com/48570596/103398657-1fa3d280-4b57-11eb-9927-faeca40025ce.png)
> 
> there are extra problems that people go throw like not being able to find the esp8266/NodeMCU on the bord manager in Ardunio IDE [this ](https://randomnerdtutorials.com/how-to-install-esp8266-board-arduino-ide/)helped me.
> I know this might look like another problem but many people think that the problem is with their cable/pc for not being able to see their board in the manager, hence why they might be reading this thread.

**Comment by MuhammadShafaullah** [comment]
still its not come on port or pc detects after entring it

**Comment by prof-redstone** [comment]
> Thanks to sshocked comment! Wire was the reason. Funniest moment is that I expierenced this problem before and forgot. Lots of wires, that are supplied with devices for charging, aren't complete USB wires, there are probably only 2 power leads inside, and missing D+ and D- wires

Thank it works !

**Comment by ertugrul-cakici** [comment]
i'd like to say thank you because the cable was the problem for me and I solved the problem

**Comment by shiviraj** [comment]
I also face the same issue, I bought a new usb cable 3 new nodemcu. I already had 3 different usb cables. I tried different combinations and also tried different drivers. I was not succeed. I also tried in different OS. after I got the idea. let's verify one by one item. nodemcu was correct. new and LED blinks while connecting to the cable. When I tried to verify the usb cables. I connect my android phone with PC with the help of usb cable. and tried to transfer the data from phone to PC. My phone was detected by my PC. So I got all the cables i have faulty one. Make sure you try to verify all items one by one. Thanks a lot

**Comment by ramanraja** [comment]
Sorry if this is off topic: But I am unable to upload Tasmota on my NodeMCU board ever since I upgraded my Windows 10. My old USB serial driver CH340 no longer works. Windows complains that the driver is 'not signed', so it cannot be installed. Windows Update also could not find any suitable driver for NodeMCU serial interface. The same board and cable work fine on a Linux laptop.
Everyone points me to a Chinese chip manufacturer's site to download the driver. But I am scared to download some unknown/ unsigned driver from PRC. A few drivers are available at the following places:
https://github.com/nodemcu/nodemcu-devkit/tree/master/Drivers
https://sparks.gogo.co.nz/ch340.html
But no one seems to know if these are safe or contain Trojans. If the driver is genuine, why doesn't the manufacturer sign it?
I just want a certified and safe serial driver for my ESP chips. Please help.

**Comment by d-a-v** [comment]
The firmware you will upload in the esp8266 is closed source, Chinese, and has access to your local network. Will you trust it more @ramanraja ?
If your esp-s are in an isolated vlan, you can also install this driver in a VM.

**Comment by ramanraja** [comment]
@d-a-v , you have a valid point!
But in my defence, I can state that I use the Arduino stack on the 8266. I use the open source firmware Tasmota and compile it from source. The devices interact with my PC and mobile through MQTT, using known payloads. 
This doesn't guarantee fool-proof security, but at least I need not install an uncertified software on my development machines.
What I fail to understand is: why should it be a black art to send a few bytes over my serial port? Can there not be any public, open and standards-based handshake mechanism and message format?

**Comment by d-a-v** [comment]
> I use the open source firmware Tasmota 

[These files](https://github.com/esp8266/Arduino/tree/master/tools/sdk/lib/NONOSDK22x_191122) are closed source binaries downloaded from espressif website and are included in every sketch build (arduino or platformio or tasmota or anything related to this arduino core).

>  Can there not be any public, open and standards-based handshake mechanism and message format?

Hardware usb<=>uart converters (ch340, cp2103, pl2303, ftdi) all need an USB driver for your OS. Sometimes there are open source versions for some OS, sometimes not. They sometimes need to be upgraded along with OS when they are themselves upgraded. Worst cases are about macOS. For all OSes there should be a signed binary version downloadable from  manufacturer websites. Signed or not for the OS, if you don't compile the driver yourself, you can do little except from downloading the binary version from the manufacturer website.

**Comment by Dwirizkifahrezi** [comment]
I want to ask, my nodemcu esp8266 does not turn on and is not detected on the computer, even when it is plugged into the computer, the esp led indicator does not turn on, anyone knows the problem.

**Comment by LukhmanHakim** [comment]
i think it's broken 

> I want to ask, my nodemcu esp8266 does not turn on and is not detected on the computer, even when it is plugged into the computer, the esp led indicator does not turn on, anyone knows the problem.

**Comment by BurakDemirdelen** [comment]
> I had same problem but I solved it. My board flashed only flashed once(it all about I think what my usb wire works) but, pc still doesnt recognize it. So i installed like 1 thousand times drivers from silabs. But pc still doesnt see it and board still flashing. So i try to change my usb wire to another one, and pc recognized it)) So if yr pc doesnt see com port try ty change the wire.

thank you for your help, it is working now.

**Comment by melihkaragoz** [comment]
> Just to have my say, after two days of testing and swearing I discovered that three (3) usb cables I was trying were "power only" !!! I have successfully used the cable from my Asus tablet!

thank you so much 😍😍

**Comment by melihkaragoz** [comment]
> Just to have my say, after two days of testing and swearing I discovered that three (3) usb cables I was trying were "power only" !!! I have successfully used the cable from my Asus tablet!

you saved my day

**Comment by Pradeepmanoharan19** [comment]
> I tried to change my wire but it didn't work. So I solved installing this:
> 
> https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

if the com port not show how you choose the port and  upload I too tried changing the wire but I doesn't work

**Comment by Bighoneypot** [comment]
> I have installed the drives changed the cable but no changes in the port display still the port is not visible in the device manager 

Dear, what is your SO? Your cable is a data cable? Type of your board?

**Comment by lk2626** [comment]
It is windows 11 64 bit mi usb cable

**Comment by MortyFleem** [comment]
WHAT WORKED FOR ME (why can't developers/sellers provide a list of common headaches and how to fix???): - 
I downloaded the drivers from the Silicon Labs website.
And the KEY for me was to install said drivers using the .exe file that came in the downloaded driver package .zip!!!

This was after trying a zillion different cables and all sorts of other timewastery.

**Comment by ahmedsalah32** [comment]
> I had same problem but I solved it. My board flashed only flashed once(it all about I think what my usb wire works) but, pc still doesnt recognize it. So i installed like 1 thousand times drivers from silabs. But pc still doesnt see it and board still flashing. So i try to change my usb wire to another one, and pc recognized it)) So if yr pc doesnt see com port try ty change the wire.

Yes i face the same problem and the problem was in the usb wire

**Comment by gsimon75** [comment]
My symptoms:
USB power is OK, led blinking, the ESP8266 is accessible via external serial Rx/Tx, but the on-board USB-serial adapter is not detected as a USB device, not even as an unknown one.

The problem:
The 12 MHz oscillator of the USB-serial chip (CH340G) was not working.
(Detect: Attach a scope to th 7th or 8th pin of CH340G, you should see a 12 MHz signal.)
At least one soldering was faulty, probably because my board is a cheap replica...

The solution:
Unsoldered the crystal resonator (12 MHz) and the 2 capacitors (20-30 pF), re-tinned the PCB pads (don't spare the flux), re-soldered the parts.

Result:
```
PS C:\Temp> usbipd list
Connected:
BUSID  VID:PID    DEVICE                                                        STATE
...
2-2    1a86:7523  USB2.0-Serial                                                 Not shared
...
```

(The moral of the story: No amount of software tinkering will solve a faulty solder joint :D )

**Comment by P-bytes** [comment]
I had the same problem and already solved it! i recommend changing wires first then if the issue still occurs try downloading the drivers here (https://www.silabs.com/developer-tools/usb-to-uart-bridge-vcp-drivers?tab=downloads) extract it then install the silabser.inf file. after that the device manager already detects my device :))
