### ISSUE TITLE
Profiling esp8266 arduino based code

### ISSUE THREAD

**Issue by yadavravi079** [esp8266/Arduino#3559]
#### Hardware
Hardware:			ESP8266
Core Version:      	

### Description

Hi guys! I have developed a project based on NodeMCU, Now I am trying to debugging and profiling it.
Can any could please help how to profile the code?
I am able to debug it using gdb over eclipse and now I am trying to compile it using -pg Flag so that it gnenerate some info using mcount() and then I could use Gprof for further profiling.
Share some ideas would be appreciated.

### Settings in IDE

Module:  			NodeMCU
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			dio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		nodemcu

**Comment by devyte** [comment]
This is not the right place to ask such questions. This is an issue tracker, to track issues in the core lib source code. Please ask at a forum like esp8266.com or stackoverflow.
Please close this.
