### ISSUE TITLE
compiling errors by using library Adafruit_TSL2561 

### ISSUE THREAD

**Issue by J-Arnold** [esp8266/Arduino#3567]
### Basic Infos

after change to Core Version 2.4.0-rc1 the library Adafruit_TSL2561 is not working anymore, after switching back to 2.3.0 all is working again.

#### Hardware
Hardware:			ESP-12
Core Version:      	2.4.0-rc1

### Description

exit status 1
Error compiling for board Generic ESP8266 Module.
is shown when compiling the example script.

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB/1MB
CPU Frequency:	80Mhz
Flash Mode:		qio
Flash Frequency:	40Mhz
Upload Using:		OTA and SERIAL
Reset Method:		?ck / nodemcu?

Adafruit_TSL2561 Example -> sensorapi

#include <Wire.h>
#include <Adafruit_Sensor.h>
#include <Adafruit_TSL2561_U.h>

Adafruit_TSL2561_Unified tsl = Adafruit_TSL2561_Unified(TSL2561_ADDR_FLOAT, 12345);

void displaySensorDetails(void)
{
  sensor_t sensor;
  tsl.getSensor(&sensor);
  Serial.println("------------------------------------");
  Serial.print  ("Sensor:       "); Serial.println(sensor.name);
  Serial.print  ("Driver Ver:   "); Serial.println(sensor.version);
  Serial.print  ("Unique ID:    "); Serial.println(sensor.sensor_id);
  Serial.print  ("Max Value:    "); Serial.print(sensor.max_value); Serial.println(" lux");
  Serial.print  ("Min Value:    "); Serial.print(sensor.min_value); Serial.println(" lux");
  Serial.print  ("Resolution:   "); Serial.print(sensor.resolution); Serial.println(" lux");  
  Serial.println("------------------------------------");
  Serial.println("");
  delay(500);
}

void configureSensor(void)
{
  tsl.enableAutoRange(true);
  tsl.setIntegrationTime(TSL2561_INTEGRATIONTIME_13MS);
  Serial.println("------------------------------------");
  Serial.print  ("Gain:         "); Serial.println("Auto");
  Serial.print  ("Timing:       "); Serial.println("13 ms");
  Serial.println("------------------------------------");
}

void setup(void) 
{
  Serial.begin(9600);
  Serial.println("Light Sensor Test"); Serial.println("");
  if(!tsl.begin())
  {
    Serial.print("Ooops, no TSL2561 detected ... Check your wiring or I2C ADDR!");
    while(1);
  }
  displaySensorDetails();
  configureSensor();
  Serial.println("");
}

void loop(void) 
{  
  sensors_event_t event;
  tsl.getEvent(&event);
 
  if (event.light)
  {
    Serial.print(event.light); Serial.println(" lux");
  }
  else
  {
    Serial.println("Sensor overload");
  }
  delay(250);
}

### Debug Messages

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\XXXX\AppData\Local\Arduino15\packages -hardware C:\Users\XXXX\Documents\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\XXXX\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\XXXX\Documents\Arduino\libraries -fqbn=esp8266:esp8266:generic:CpuFrequency=80,FlashFreq=40,FlashMode=dio,UploadSpeed=115200,FlashSize=4M1M,ResetMethod=ck,Debug=Serial,DebugLevel=OTA2____ -ide-version=10802 -build-path C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875 -warnings=none -build-cache C:\Users\XXXX\AppData\Local\Temp\arduino_cache_948728 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.esptool.path=C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.9 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2 -prefs=runtime.tools.mkspiffs.path=C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\mkspiffs\0.1.2 -verbose C:\Users\XXXX\Documents\Arduino\sensorapi\sensorapi.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\XXXX\AppData\Local\Arduino15\packages -hardware C:\Users\XXXX\Documents\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\XXXX\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\XXXX\Documents\Arduino\libraries -fqbn=esp8266:esp8266:generic:CpuFrequency=80,FlashFreq=40,FlashMode=dio,UploadSpeed=115200,FlashSize=4M1M,ResetMethod=ck,Debug=Serial,DebugLevel=OTA2____ -ide-version=10802 -build-path C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875 -warnings=none -build-cache C:\Users\XXXX\AppData\Local\Temp\arduino_cache_948728 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.esptool.path=C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.9 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2 -prefs=runtime.tools.mkspiffs.path=C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\mkspiffs\0.1.2 -verbose C:\Users\XXXX\Documents\Arduino\sensorapi\sensorapi.ino
Using board 'generic' from platform in folder: C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1
Using core 'esp8266' from platform in folder: C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1
Detecting libraries used...
"C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/lwip/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\Users\XXXX\AppData\Local\Temp\arduino_build_958875/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_OTA -DDEBUG_ESP_UPDATER -DARDUINO=10802 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\variants\generic" "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\sketch\sensorapi.ino.cpp" -o "nul"
"C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/lwip/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\Users\XXXX\AppData\Local\Temp\arduino_build_958875/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_OTA -DDEBUG_ESP_UPDATER -DARDUINO=10802 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\variants\generic" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire" "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\sketch\sensorapi.ino.cpp" -o "nul"
"C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/lwip/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\Users\XXXX\AppData\Local\Temp\arduino_build_958875/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_OTA -DDEBUG_ESP_UPDATER -DARDUINO=10802 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\variants\generic" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_Sensor" "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\sketch\sensorapi.ino.cpp" -o "nul"
"C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/lwip/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\Users\XXXX\AppData\Local\Temp\arduino_build_958875/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_OTA -DDEBUG_ESP_UPDATER -DARDUINO=10802 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\variants\generic" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_Sensor" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561" "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\sketch\sensorapi.ino.cpp" -o "nul"
"C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/lwip/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\Users\XXXX\AppData\Local\Temp\arduino_build_958875/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_OTA -DDEBUG_ESP_UPDATER -DARDUINO=10802 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\variants\generic" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_Sensor" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561" "C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire\Wire.cpp" -o "nul"
"C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/lwip/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\Users\XXXX\AppData\Local\Temp\arduino_build_958875/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_OTA -DDEBUG_ESP_UPDATER -DARDUINO=10802 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\variants\generic" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_Sensor" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561" "C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561\Adafruit_TSL2561_U.cpp" -o "nul"
Generating function prototypes...
"C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/lwip/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\Users\XXXX\AppData\Local\Temp\arduino_build_958875/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11  -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_OTA -DDEBUG_ESP_UPDATER -DARDUINO=10802 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\variants\generic" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_Sensor" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561" "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\sketch\sensorapi.ino.cpp" -o "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files (x86)\Arduino\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\preproc\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/lwip/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\Users\XXXX\AppData\Local\Temp\arduino_build_958875/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_OTA -DDEBUG_ESP_UPDATER -DARDUINO=10802 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\variants\generic" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_Sensor" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561" "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\sketch\sensorapi.ino.cpp" -o "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\sketch\sensorapi.ino.cpp.o"
Compiling libraries...
Compiling library "Wire"
"C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/lwip/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\Users\XXXX\AppData\Local\Temp\arduino_build_958875/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_OTA -DDEBUG_ESP_UPDATER -DARDUINO=10802 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\variants\generic" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_Sensor" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561" "C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire\Wire.cpp" -o "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\libraries\Wire\Wire.cpp.o"
Compiling library "Adafruit_Sensor"
Compiling library "Adafruit_TSL2561"
"C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/lwip/include" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\Users\XXXX\AppData\Local\Temp\arduino_build_958875/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC -DDEBUG_ESP_PORT=Serial -DDEBUG_ESP_OTA -DDEBUG_ESP_UPDATER -DARDUINO=10802 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\variants\generic" "-IC:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_Sensor" "-IC:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561" "C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561\Adafruit_TSL2561_U.cpp" -o "C:\Users\XXXX\AppData\Local\Temp\arduino_build_958875\libraries\Adafruit_TSL2561\Adafruit_TSL2561_U.cpp.o"
In file included from C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561\Adafruit_TSL2561_U.cpp:26:0:

C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561\pgmspace.h:60:32: error: expected unqualified-id before 'const'

 #define pgm_read_byte(addr) (*(const unsigned char *)(addr))

                                ^

C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266/pgmspace.h:102:23: note: in expansion of macro 'pgm_read_byte'

 static inline uint8_t pgm_read_byte(const void* addr) {

                       ^

C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561\pgmspace.h:60:32: error: expected ')' before 'const'

 #define pgm_read_byte(addr) (*(const unsigned char *)(addr))

                                ^

C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266/pgmspace.h:102:23: note: in expansion of macro 'pgm_read_byte'

 static inline uint8_t pgm_read_byte(const void* addr) {

                       ^

C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561\pgmspace.h:60:32: error: expected ')' before 'const'

 #define pgm_read_byte(addr) (*(const unsigned char *)(addr))

                                ^

C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266/pgmspace.h:102:23: note: in expansion of macro 'pgm_read_byte'

 static inline uint8_t pgm_read_byte(const void* addr) {

                       ^

C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561\pgmspace.h:61:32: error: expected unqualified-id before 'const'

 #define pgm_read_word(addr) (*(const unsigned short *)(addr))

                                ^

C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266/pgmspace.h:109:24: note: in expansion of macro 'pgm_read_word'

 static inline uint16_t pgm_read_word(const void* addr) {

                        ^

C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561\pgmspace.h:61:32: error: expected ')' before 'const'

 #define pgm_read_word(addr) (*(const unsigned short *)(addr))

                                ^

C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266/pgmspace.h:109:24: note: in expansion of macro 'pgm_read_word'

 static inline uint16_t pgm_read_word(const void* addr) {

                        ^

C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561\pgmspace.h:61:32: error: expected ')' before 'const'

 #define pgm_read_word(addr) (*(const unsigned short *)(addr))

                                ^

C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\cores\esp8266/pgmspace.h:109:24: note: in expansion of macro 'pgm_read_word'

 static inline uint16_t pgm_read_word(const void* addr) {

                        ^

Using library Wire at version 1.0 in folder: C:\Users\XXXX\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0-rc1\libraries\Wire 
Using library Adafruit_Sensor at version 1.0.2 in folder: C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_Sensor 
Using library Adafruit_TSL2561 at version 1.0.0 in folder: C:\Users\XXXX\Documents\Arduino\libraries\Adafruit_TSL2561 
exit status 1
Error compiling for board Generic ESP8266 Module.

**Comment by igrr** [comment]
This has been fixed in https://github.com/esp8266/Arduino/commit/c52b0da11cfd9666e45d576d3fdd2533415c4ab6, the fix will be available in the next (pre-)release.
