### ISSUE TITLE
Burn the bootloader to an ATmega328P using the ESP-12S

### ISSUE THREAD

**Issue by Shikartoos** [esp8266/Arduino#3573]
Hi All,
I am trying to flash the bootloader on ATmega328P using the following:

- ESP-12S (using the Feather HUZZAH board)
- ATmega328P (using an Arduino NANO clone)
- Arduino IDE

What I did so far is the following:

- Uploaded the "Examples > ArduinoISP > ArduinoISP" sketch using the Arduino IDE to the ESP-12S
- Made the following connection between the ESP-12S and the ATmega328P

ESP MISO -> ATmega328P MISO
ESP MOSI -> ATmega328P MOSI
ESP SCK -> ATmega328P SCK
ESP RST -> ATmega328P RESET
ESP 5V -> ATmega328P VCC

- Chose the Arduino NANO board from the Arduino IDE
- Connected the ESP-12S once again and chose the correct serial port from the Arduino IDE
- Chose the "Arduino as ISP" from Tools > Programmer
- Ran "Burn Bootloader" from Tools

I am getting the below output in the Arduino IDE console

---- OUTPUT START ----
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x0d
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x0a
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x20
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x65
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x74
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x73
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x20
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x4a
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x61
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x6e
Error while burning bootloader.
---- OUTPUT END ----

Please advise me :

- Is what I am trying to do possible?
- If yes, is there anything I am doing wrong?
- Is there an example for doing such thing?

Thank you. Appreciate the help.

Shikartoos.

**Comment by devyte** [comment]
It should be possible, but this is not the correct place to discuss it. This is an issue tracker for issues in the core libs, not a discussion forum. Please ask at esp8266.com or stackoverflow.
