### ISSUE TITLE
client.write() is not work with WiFiClientSecure

### ISSUE THREAD

**Issue by Vladimir-Kondratiev** [esp8266/Arduino#3601]
esp8266 last git version 2017_09_12.
Arduino sketch is attached.

Function client.write(webFile) for file upload  [https://github.com/esp8266/Arduino/issues/1853](url) is not work with WiFiClientSecure:
///
error: no matching function for call to 'WiFiClientSecure::write(fs::File&)'
client.write(webFile);
///
[ESP8266HUZZAN_8421.zip](https://github.com/esp8266/Arduino/files/1297003/ESP8266HUZZAN_8421.zip)

**Comment by earlephilhower** [comment]
This was fixed a while back.  Both BearSSL and axTLS clients have `write(Stream)` methods, which can take `File` objects since a File inherits from a Stream.

As a test I built the attached .ino without any errors.
