### ISSUE TITLE
HTTP_UPDATE_FAILED HTTP/1.B Protocol

### ISSUE THREAD

**Issue by jamestutton** [esp8266/Arduino#3603]
#### Hardware
Hardware:	        ESP-12E Node MCU 1.0
Core Version:      	2.3.0-rc2 but also 2.3  others unknown

### Description

HTTP_UPDATE_FAILED Error (-104):

Update Request fails due to using wrong protocol. HTTP/1.B

tcpdump trace:

E..............>....q..P...p...tP...#k..GET /esp/bin/Blink.ino.nodemcu.bin HTTP/1.1B
Host: 192.168.x.x
User-Agent: ESP8266-http-Update
Connection: close
x-ESP8266-STA-MAC: XX:XX:XX:XX:XX:XX
x-ESP8266-AP-MAC: XX:XX:XX:XX:XX:XX
x-ESP8266-free-space: 712704
x-ESP8266-sketch-size: 333664
x-ESP8266-chip-size: 4194304
x-ESP8266-sdk-version: 1.5.3(aec24ac9)
x-ESP8266-mode: sketch
x-ESP8266-version: optional current version string here

### Sketch

Will Try to create a minimal sketch to replicate issue as current script is fairly long.  Proved not an issue with basic examples but not doing anything special with headers so possibly memory related.

### Debug Messages

Issue appear to be from this section of ESP8266HTTPClient.cpp if hard code this section can bypass the issue. 

    String header = String(type) + " " + _uri + F(" HTTP/1.");

    if(_useHTTP10) {
        header += "0";
    } else {
        header += "1";
    }

**Comment by devyte** [comment]
2.3.0-rc2 is ancient. Please try latest git.

This looks like a heap memory problem at first glance. When String needs to grow, it calls realloc. If there is no mem, or no contigous chunk big enough to hold the new size, it fails silently.
My suggestion: check available mem at different parts of your code.
Also, keep in mind that the max stack size is only 4KB. If you blow up the stack due to local variables, it will corrupt the nearest heap allocations. You could try to increase the stack size (cont.cpp in the core if memory serves), but it diminishes your available heap.

**Comment by jamestutton** [comment]
May have found the issue or a workarond at least.  Seems to have fix it if replacing the "0" in the ESP8266HTTPClient.cpp with '0' So it almost seems its interprepting 0 or 1 as B possible trunkating a Boolean type to B or something odd but just wide guess. 

```cpp
    if(_useHTTP10) {
        header += '0';
    } else {
        header += '1';
    }
```

Looking at the other appendments to headers maybe it needs S("0")  but haven't dug that deep in the code.

**Comment by devyte** [comment]
@jamestutton I can't reproduce this within my development environment. I strongly suspect you have either mem corruption (stack of heap), or mem fragmentation with resulting (re)allocation failure.
I can't help further without a MCVE sketch. Can you provide it?

**Comment by devyte** [comment]
Closing due to can't reproduce, lack of feedback in a long while, and recent unit testcase coverage for the String class. If you think the problem is sitll present, please open a new issue and fill in the required info.
