### ISSUE TITLE
sdk question , determine sta ip is static or not ?

### ISSUE THREAD

**Issue by tablatronix** [esp8266/Arduino#3608]
How can we determine if sta is using static ip or not ?
wifi_get_ip_info nor ip_info stuct does not seem to reflect anything

Ideas?

**Comment by devyte** [comment]
@tablatronix AFAIK, you can't. You have to keep track of that yourself with an in-mem config from which you set up the Wifi. You can then ask your in-mem data what the current status is.
Or you can roll your own WiFi object.
Be aware that setting IP to 0.0.0.0 enables dhcpc, while setting  it to something else enables static IP.
Please ask such question in a forum, this is an issue tracker, and not meant for general support questions.
Closing.
