### ISSUE TITLE
SPIFFS doesn't read Files when loaded with the tool .

### ISSUE THREAD

**Issue by ashiroji** [esp8266/Arduino#3612]
#### Hardware
Hardware:			ESP-12 
Core Version:      	 Commit : Update spiffs 0.3.7 to and mkspiffs 0.1.3 (6ac48124bd10151cdbc5c1003e41e4483f8f1f11 )

### Description
Updating my esp8266 repo to the latest git version  causes the following issues :+1: 
-Ability to read/write SPIFFS through software (verified with ConfigFile example )
-Inability to read SPIFFS when files loaded via ESP8266 Sketch Data Upload tool (veirfied with the FS Browser example )

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB/1MB
CPU Frequency:		80Mhz
Flash Mode:			dio
Flash Frequency:	40Mhz
Upload Using:		 SERIAL
Reset Method:		ck 

### Sketch
ConfigFile Example 

Messages : 
            Config saved
            Config loaded

FSBrowser 

Messages :
              File Not Found

**Comment by me-no-dev** [comment]
did you run get.py to update mkspiffs as well? If you are using old mkspiffs and new spiffs it will not work

**Comment by igrr** [comment]
@ashiroji which OS are you running mkspiffs on?

**Comment by ashiroji** [comment]
I'm using Ubuntu 16.04

**Comment by igrr** [comment]
Linking related mkspiffs ticket: https://github.com/igrr/mkspiffs/issues/26#issuecomment-329740890

**Comment by ashiroji** [comment]
@me-no-dev No i didn't run get.py.

If I understand this , the new lib is in a way incompatible with the old tool ?
so I need to update both lib and tool right ?
 
Thank you all for the quick answer

**Comment by universam1** [comment]
I tried the latest tool 1.3 and did not create a readable image!

**Comment by reaper7** [comment]
I have similar problem.
I use current github version + mkspiffs updated,
for test I uploaded ESP8266WebServer->FSBrowser example with additional binary file (277 552bytes) inside data folder.
WebFileEditor in this example shows all files (with my bin) but downloaded bin is different than uploaded!
Downloaded file size is 276 667bytes and simple compare in WinMerge shows 9 differences in separate places.
![diff](https://user-images.githubusercontent.com/4134851/30538866-265542d8-9c70-11e7-8df5-da5e042a2d9f.jpg)

**Comment by me-no-dev** [comment]
@reaper7 can you please show the differences in hex format? and more than one if possible? maybe the bytes can make some sense of this.

**Comment by me-no-dev** [comment]
their offsets can also point to something... seems to happen at equal intervals

**Comment by reaper7** [comment]
can you recommend some tool for this?
I can send two binaries for You but where? ;)
![diff2](https://user-images.githubusercontent.com/4134851/30539866-b95d52f6-9c74-11e7-9e6f-c943659ab384.jpg)

**Comment by me-no-dev** [comment]
you can see a pattern there :) I have downloaded the files and will have a look ;) surely we will figure it out!

**Comment by reaper7** [comment]
except first diff, next diffs cut 109 bytes

**Comment by me-no-dev** [comment]
can you try to upload the same files but add one that will be put before the bin, so we can see if the first offset will change. If so that would mean that something wrong is read from the file system. Also please point which config you are using (4M/3MB SPIFFS or something else) You could try different config maybe so it would change the block size.

**Comment by reaper7** [comment]
nodemcu1.0 4M/3SPIFFS

the same binary as second file (after jpg img  468 909bytes):
![diff_bin_as_second_file](https://user-images.githubusercontent.com/4134851/30541318-2b58a94a-9c7b-11e7-93bc-40b1ab7a225f.jpg)

**Comment by reaper7** [comment]
and binary as a single file
![diff_bin_as_single_file](https://user-images.githubusercontent.com/4134851/30541422-a30d8fe6-9c7b-11e7-8796-5bfde48d3e5d.jpg)

looks identical

**Comment by reaper7** [comment]
nodemcu1.0 4M/**1**SPIFFS
![diff_bin_as_single_file_1mspiffs](https://user-images.githubusercontent.com/4134851/30541651-9e1f8eb6-9c7c-11e7-8d71-bf2f594e0101.jpg)

so...spiffs size and file count/location does not affect the result

**Comment by reaper7** [comment]
and finally, a completely different file (single) 4M/1M
upload file size: 468 909
downloaded file size: 467 370

![different_file_diff](https://user-images.githubusercontent.com/4134851/30542282-10d03422-9c7f-11e7-9678-eb8844d6506e.jpg)

the same patern

**Comment by Lan-Hekary** [comment]
I am having the same problem here 
but I used a different approach to check and found that the problem is in `mkspiffs.exe` tool ..

I used `mkspiffs.exe` version 0.1.3 in command line on windows to pack the files into `spiffs.bin` file ..
`mkspiffs.exe -c original_data -b 8192 -p 256 -s 1028096 spiffs.bin`
the block,page and fs sizes are from the ld script for 1m spiffs on a 4m flash

then I used this line to unpack: 
`mkspiffs.exe -u extracted_data -b 8192 -p 256 -s 1028096 spiffs.bin`

the two folder's are not identical ...
some file are identical only 
![image](https://user-images.githubusercontent.com/13420623/30588777-bb4c9a64-9d40-11e7-85ab-0f3b486ac5cf.png)

I can upload the content of the data if that would help ..
but I think it can be reproduced easily ..

I also tested it with version 0.1.2 but I found that the extracted files are all identical .. 
so the bug is in the tool for sure ..

**Comment by me-no-dev** [comment]
This is a great clue!!! I might have an idea! See this: https://github.com/pellepl/spiffs/commit/f5e26c4e933189593a71c6b82cda381a7b21e41c and this: https://github.com/pellepl/spiffs/issues/165

this fix was released after we changed the version

**Comment by Lan-Hekary** [comment]
yup .. that's true ..
the corrupted files are over 25k ..
I think the fix is easy .. merge the new fix into the tool and core of the esp8266

**Comment by me-no-dev** [comment]
will try to do all that tomorrow :)

**Comment by Lan-Hekary** [comment]
I am trying to fix it now and test the result 
but I am not sure how to fix the problem across all these repositories :D 
after all I am new to this kind of integration ..

I will override the SPIFFS src files with the new one in the esp8266 core 
but how can I change the compiled version of the tool ??
all I see is the source code from
https://github.com/igrr/mkspiffs

I can edit that and compile it on my PC but I have no Idea how to export it ..

**Comment by me-no-dev** [comment]
just copy the binary to your esp8266-arduino folder :) we  will do the release (@igrr)

**Comment by me-no-dev** [comment]
Oh, make sure you also update the spiffs files in the Arduino as well (cores/esp8266/spiffs/...)

**Comment by Lan-Hekary** [comment]
I am doing it right now ..
if I can make a pull request I will make one ..
for the esp core and the mkspiffs tool ..

**Comment by Lan-Hekary** [comment]
I tested it multiple times with multiple files and I believe the fix works perfectly now ..
I also made pull requests to both the mkspiffs tool and the Arduino core with the new modifications ..
I guess you'll have to make a new release for the mkspiffs tool after all too ..

**Comment by reaper7** [comment]
someone can test ESP8266WebServer->FSBrowser example after latest changes on spiffs and mkspiffs tool (current master branch) ?
Seems like new mkspiffs 2.0 create propertly image but this example do not show any files
tested on nodemcu1.0 4M/3M & 4M/1M

**Comment by Pablo2048** [comment]
Same problem here - after update my IDE, upload new sketch and then upload spiffs image, SPIFFS.begin() return true, but FSBrowser (SPIFFSEditor form AsyncWebServer actually) show empty volume.

**Comment by igrr** [comment]
Not all updates are in folks, sorry, i got distracted for a meeting :)
One thing remaining is to set `SPIFFS_USE_MAGIC_LENGTH` to 0 in spiffs_config in arduino. Will push the commit soon.

**Comment by Pablo2048** [comment]
Ok, no problem with that :-) I'll wait...

**Comment by Lan-Hekary** [comment]
I tested it originally with `SPIFFS_USE_MAGIC_LENGTH` set to 0 so it's going to be OK

**Comment by igrr** [comment]
Tested with 35d5fab, looks okay on my side.

**Comment by reaper7** [comment]
yes :)
tnx!

**Comment by Pablo2048** [comment]
LGTM! (4/1M, 4/3M). Thx.
