### ISSUE TITLE
I2C on GPIO1 & GPIO3

### ISSUE THREAD

**Issue by pauleilio** [esp8266/Arduino#3614]
-

#### Hardware
Hardware:		NodeMCU v1.0
Core Version:      	2.3.0

Is it possible to use I2C on GPIO1 & GPIO3 usually used for UART

**Comment by devyte** [comment]
@pauleilio this is not the right place to ask these questions. This is an issue tracker, meant to track issues in the core. Please refer to esp8266.com or stackoverflow for assistance.
Closing as off-topic.
