### ISSUE TITLE
connected two esp8266 

### ISSUE THREAD

**Issue by marcgrc** [esp8266/Arduino#3615]
hello
I would like to ask you a question and I hope you will answer.
I am developing a project to turn on a led connected to an esp8266 with a button connected to another esp8266.
could you help me?
thank you so much
I look forward to your kind reply.

**Comment by devyte** [comment]
@marcgrc this is not the right place to ask for help for your particular project. This is an issue tracker, meant for tracking issues in the core.
Please refer to esp8266.com or stackoverflow for assistance.
Closing as off-topic.

**Comment by marcgrc** [comment]
sorry thank
