### ISSUE TITLE
SPIFFS usage

### ISSUE THREAD

**Issue by adrianrb** [esp8266/Arduino#362]
Hi all.

I´m trying to use the SPIFFS bundled with this project, but stuck.
How use it? Miss a examples folder?

My code:

FSClass fs(0x30000, 0x40000, 256, 64, 5); // how make this values? I´ve put 0x40000 - 0x10000 (64k before API?) sorry i´m a beginner

void setup()
{
    Serial.begin(9600);

    Serial.println("###### Trying create SPIFFS filesystems on address 0x30000 size 64k");
    Serial.println("###### mounting...");
    fs.mount();
    Serial.println("###### formatting...");
    fs.format();
    Serial.print("###### Total bytes: ");
    Serial.println(fs.totalBytes());
    Serial.print("###### Used bytes: ");
    Serial.println(fs.usedBytes()); // <<<<<<<<<< ok till here
    
    Serial.println("###### creating a file...");// >>>>>>>> from here resets over n over...
    char* fname= "test.txt";
    if (!fs.exists(fname)) fs.create(fname);
    
    FSFile f = fs.open(fname, FSFILE_OVERWRITE);
    f.write("testing... line one\r\nline two");
    f.flush();
    f.close();
    
    Serial.print("###### Total bytes: ");
    Serial.println(fs.totalBytes());
    Serial.print("###### Used bytes: ");
    Serial.println(fs.usedBytes());
    fs.umount();
}

Adrian

**Comment by igrr** [comment]
My suggestion is — don't use it in it's current form. This API will be
removed in the coming release.

**Comment by adrianrb** [comment]
Ohh... But SPIFFS will be bundled with this project in the future or abandoned?
I so, any clue how use flash as FS w/o rewrite an API?
(this removing is related to the issue with SPIFFS creator and/or smings we´ve seen here?)

Adrian

**Comment by igrr** [comment]
Yes, rewritten FS is also coming...

**Comment by adrianrb** [comment]
thank you. closing...

**Comment by bkrajendra** [comment]
Any update on new Filesystem library from FalshFS.
Im searching for this solution to store some hardware settings to flash.

**Comment by seclorum** [comment]
Is this re-write why FSFILE_OVERWRITE is no longer available in the current FileSystem.h set of mode enums?  If so: why remove the enum?  Very frustrating practice ..
