### ISSUE TITLE
ESP12E i2c communication with MPU6050

### ISSUE THREAD

**Issue by adi44ram** [esp8266/Arduino#3629]
Hello friends,
I am trying to read the data from MPU6050 using ESPwifi12E module (80Mhz). I have established a i2c communication between MPU6050 and ESP12E by seeing the schematics of esp12E module. I have pinned D4 to SDA and D5 to scl. When I upload the code I am not getting proper values.  When I turn the MPU in all the directions I am getting only positive values. I am not getting negative values at all. I uploaded the same code in my ARDUINO mega board and I get exact values. I don't think there is a problem with the code. What can be the issue. Is there an issue with the communication? Kindly help me out guys.
**I didn't change the data type of the variable where the MPU values gets stored. I used the same code in both the boards but getting different results.**
I have attached my code. 
Thanks
[MPU.txt](https://github.com/esp8266/Arduino/files/1320642/MPU.txt)

**Comment by me-no-dev** [comment]
AVR Arduino int is 16 bits and ESP is 32 bits. Change the two functions to this:
```cpp

int16_t accResult[3], gyroResult[3];

//Function that reads the accelerometer readings
void GetAccelerometerReadings(int16_t Result[])
{
byte buffer[6];
readFrom(MPU, 0x3B, 6, buffer);
Result[0] = (((int)buffer[0]) << 8) | buffer[1];
Result[1] = (((int)buffer[2]) << 8) | buffer[3];
Result[2] = (((int)buffer[4]) << 8) | buffer[5];
}

//Function that reads gyroscope readings
void GetGyroscopeReadings(int16_t Result[])
{
byte buffer[6];
readFrom(MPU, 0x43, 6, buffer);
Result[0] = (((int)buffer[0]) << 8) | buffer[1];
Result[1] = (((int)buffer[2]) << 8) | buffer[3];
Result[2] = (((int)buffer[4]) << 8) | buffer[5];
}
```
