### ISSUE TITLE
Wemos Board D1 mini Pro

### ISSUE THREAD

**Issue by Ciriaco08** [esp8266/Arduino#3640]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			Wemos Board D1 mini Pro
Core Version:      	2.3.0-rc

### Description

Problem description

This board have  16M bytes(128M bit) Flash and this Arduino environment. only recognize 4 MB

### Settings in IDE

Module:  			Wemos Board D1 mini Pro
Flash Size: 		16 MB
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by Uttarwarsanket33** [comment]
Use ESP8266WIFI.h header file Instead of Arduino.h in your program.
you need to add library for Wemos Board D1 mini Pro!!

**Comment by larsjohn** [comment]
How do you add that library?

**Comment by Ciriaco08** [comment]
The Arduino software does no option , 16M Memory, with the ESP8266WIFI.h 
header file installed and Wemos board cheked.

Do not read the code sent is not representative
