### ISSUE TITLE
Documentation for WiFi.persistent() is misleading

### ISSUE THREAD

**Issue by herm** [esp8266/Arduino#3641]
Documentation at http://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/generic-class.html says
```Setting persistent to false will get SSID / password written to flash only if currently used values do not match what is already stored in flash.```

But the code does something different:
https://github.com/esp8266/Arduino/blob/35d5fabe33c24931bc629704b645119c0218a0ed/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp#L136-L151

It writes settings to flash if they don't match the values in flash if persistent is set to **true**. If it is false it will not write to flash independent of the current value in flash.

**Comment by tablatronix** [comment]
All functions that use persistent and config equal or saves needs to have default/current conditional based on persistent. There are a few, I will make note of them.

**Comment by tablatronix** [comment]
`ESP8266WiFiAPClass::softAP`
`ESP8266WiFiSTAClass::begin`
`ESP8266WiFiGenericClass::mode`

**Comment by tablatronix** [comment]
This is what I am thinking

https://github.com/esp8266/Arduino/pull/3798

**Comment by herm** [comment]
I'm not sure if the changes you propose are required or not. However they are unrelated to this issue. The problem here was that the code does something else than the documentation says. But the code's behavior is good so the documentation has to be changed.

**Comment by tablatronix** [comment]
Then I will create another issue, because I believe it is wrong and badly implemented.

**Comment by Raynman77** [comment]
@herm Just curious, whats the reason for the underscore in your line containing WiFi._persistent?

**Comment by tablatronix** [comment]
That is the name of the variable used in the library.

**Comment by Raynman77** [comment]
I haven't looked into it yet. Was looking at storing wireless credentials,
read the esp8266 core general class docs, and "WiFi.persistent(false)"
didn't contain the underscore. Was just curious if this was going to be a
"gotcha" when I finally come around to coding for the esp8266

**Comment by Raynman77** [comment]
Cool, thanx Shawn

**Comment by tablatronix** [comment]
"Frequently calling these functions could cause wear on the flash memory"

Only if ! notconfigequals, perhaps we should add debugging strings when doing set config defualts to help debug that?

**Comment by devyte** [comment]
Paranoia is your friend in these cases, so I agree.

**Comment by tablatronix** [comment]
there is currently 
`   DEBUGV("sta config unchanged");`
but that is the opposite of what you would want
Ill open an issue and try to pr it in the 2-3 places that it happens, would help find really bad stuff like loops
