### ISSUE TITLE
STA and SoftAP conflict; WiFi.begin() not connecting

### ISSUE THREAD

**Issue by FabianaFerreira** [esp8266/Arduino#3643]
### Basic Infos
My project is a mesh network with NodeMCU's. The idea is that each one is working as STA and SoftAP, receiving packets via UDP and sending via UDP as well. 

#### Hardware
Hardware: Node MCU

### Description

The problem is that, with the first two nodes (the first one working as STA only) are working fine, but when I try to send the message to the third one. I run a scan and try to connect to it, using the STA mode of the second one. However, WiFi.begin() does not succeed and gives the "WL_DISCONNECTED" status. I've already looked up about it and tried to use some code lines that interrupt the SoftAP interface while using the STA mode, but it seems that it is not working. I'm sorry if I did not make myself clear, it is a college project and I'm a beginner. 
It is valid to say that it needs to be in void loop(), so I can run the scan multiple times, since the nodes can be at different places.

### Settings in IDE

Module:  			Node MCU 1.0 ESP-12E module
Flash Size: 		4MB
CPU Frequency:		80Mhz
Flash Mode:			?qio?
Upload Using:		Arduino IDE
Upload speed:       115200

### Sketch

#include <ESP8266WiFi.h>
#include <WiFiUdp.h>
#include <String.h>

#define NODE_NUMBER 3
#define TRIES 10
#define SCAN_PERIOD 5000

//Those are the variables that ate going to end the conflict between the station configs and the AP configs
extern "C" void* eagle_lwip_getif(uint8_t);
extern "C" void netif_set_up(void*);
extern "C" void netif_set_down(void*);

String previous_node = "0";
String default_ssid_name = "MeshNode";

const uint16_t node_port = 80 + NODE_NUMBER;
unsigned int next_node_port = 80;
unsigned int tries = 0;
char incomingPacket[255];
char  replyPacket[] = "Message received";
char* received_data;

boolean foundConnection = false;
boolean connectedClientTest = false;
boolean node_connected = false;

//Initializing client and server
WiFiUDP Udp;

//Variables that will be used to configure the network
String ssid;
String password;
IPAddress local_IP(192,168,4,NODE_NUMBER);
IPAddress gateway(192,168,4,9);
IPAddress subnet(255,255,255,0);

//Variables that describe the stronger wifi signal
int stronger_WifiSignal = -200;
String stronger_WifiSSID = "";
IPAddress connectedNode_staticIP;

//Function that will scan available network and get the closer node
boolean getStrongerSignal ()
{
    stronger_WifiSignal = -200;
    stronger_WifiSSID = "";
     //Get the stronger signal and connects to network
    boolean foundMeshNetwork = false;
    Serial.print("\nScan start ... ");
    WiFi.scanNetworks(true);
    delay(SCAN_PERIOD);
    // print out Wi-Fi network scan result uppon completion
    int n = WiFi.scanComplete();
    if(n > 0)
    {
      Serial.printf("%d network(s) found\n", n);
      for (int i = 0; i < n; i++)
      {
        Serial.printf("%d: %s, Ch:%d (%ddBm) %s\n", i+1, WiFi.SSID(i).c_str(), WiFi.channel(i), WiFi.RSSI(i), WiFi.encryptionType(i) == ENC_TYPE_NONE ? "open" : "");   
        //Checks which one has the best signal, as long as it is one of the nodes 
        if (stronger_WifiSignal < WiFi.RSSI(i) && WiFi.SSID(i).startsWith("MeshNode"))
        { 
          if (WiFi.SSID(i).substring(8) != previous_node)
          {
            Serial.println(WiFi.SSID(i));
            foundMeshNetwork = true;
            stronger_WifiSignal = WiFi.RSSI(i);
            stronger_WifiSSID = WiFi.SSID(i);
          }
        }
      }
      WiFi.scanDelete();
      if (!foundMeshNetwork)
        return false;
      return true;
    }
    else if (n = 0)
      Serial.printf ("No network found\n"); 
    WiFi.scanDelete();
    return false;   
} //getStrongerSignal ends

void setup()
{
  ssid = default_ssid_name;
  ssid.concat(NODE_NUMBER);
  password = ssid;
  
  Serial.begin(115200);
  //Serial.setDebugOutput(true);
  WiFi.mode(WIFI_AP_STA);
  WiFi.setAutoConnect(false);
  //WiFi.disconnect();
  
  //Configuring softAP 
  Serial.print("Setting soft-AP configuration ... ");
  Serial.println(WiFi.softAPConfig(local_IP, gateway, subnet) ? "Ready IP config" : "Failed! IP config");
  
  Serial.print("Setting soft-AP ... "); 
  boolean result = false;
  while (!result)
  {
    result = WiFi.softAP(ssid.c_str(), password.c_str());
    if(result == true)
      Serial.println("Ready");
    else
      Serial.println("Failed!");
      delay(100);
  }
  
  //Debugging
  IPAddress this_node_ip = WiFi.softAPIP();   // Obtain the IP of the Server 
  Serial.print("Server IP is: ");             // Print the IP to the monitor window 
  Serial.println(this_node_ip);
    
} //end of setup

void loop()
{
  
  Udp.begin(node_port);
  Serial.println("Checking for packets");
  delay (1000);
  // listen for incoming clients
  int packetSize = Udp.parsePacket();
  if (packetSize)
  {
    // receive incoming UDP packets
    Serial.printf("Received %d bytes from %s, port %d\n", packetSize, Udp.remoteIP().toString().c_str(), Udp.remotePort());
    previous_node = Udp.remoteIP().toString().substring(10);
    Serial.println(previous_node);
    int len = Udp.read(incomingPacket, 255);
    if (len > 0)
    {
      incomingPacket[len] = 0;
    }
    Serial.printf("UDP packet contents: %s\n", incomingPacket);
    received_data = incomingPacket;
    // send back a reply, to the IP address and port we got the packet from
    Udp.beginPacket(Udp.remoteIP(), Udp.remotePort());
    Udp.write(replyPacket);
    Udp.endPacket();
    node_connected = true;
  }
  else
  {
    Serial.println("No packet was received.");
    node_connected = false;
  }
  Udp.stop();
  //if a node has sent data to this node, a connection to the next one will be established
  //in this case, this part is not being used, since the tests are being done with two nodes
  //this one is the server
  if (node_connected)
  {
      // before doing HTTP request, disable SoftAP interface:
      netif_set_down(eagle_lwip_getif(1));
      Serial.println("Received a packet, going to send it to the next one");
      if (!WiFi.isConnected())
      {
        delay(2000);
        foundConnection = getStrongerSignal();
        if (foundConnection)
        {
            Serial.println(stronger_WifiSSID);
            WiFi.begin(stronger_WifiSSID.c_str(), stronger_WifiSSID.c_str());
            WiFi.printDiag(Serial);
            Serial.println(WiFi.status());
            Serial.println(WiFi.getMode());
            Udp.begin(node_port);            
            delay (2000);
            //Configuring IP address that will be used to send data to server
            unsigned int connectedNodeNumber = int (stronger_WifiSSID.charAt(8) - '0');
            next_node_port = next_node_port + connectedNodeNumber;
            connectedNode_staticIP = IPAddress(192,168,4,connectedNodeNumber);
            Serial.println(connectedNode_staticIP);
             //if there is a connection, report via serial
             Serial.println("Wifi connected");
             Serial.println(Udp.remoteIP());
             Udp.beginPacket(Udp.remoteIP(), next_node_port);
             Udp.write(received_data);
             Udp.endPacket();
          }
      } //end if isConnected
      else 
      {
        Serial.println("\nStarting connection with the server...");
        //if there is a connection, report via serial
        Serial.println("Wifi connected");
        Serial.println(Udp.remoteIP());
        Udp.beginPacket(Udp.remoteIP(), next_node_port);
        Udp.write(received_data);
        Udp.endPacket();
      }//end else isConnected 
      //now enable SoftAP interface again
      netif_set_up(eagle_lwip_getif(1));
  }//end if node_connected
}//end of loop

### Debug Messages
MeshNode3
Mode: STA+AP
PHY mode: N
Channel: 1
AP id: 0
Status: 1
Auto connect: 0
SSID(9): MeshNode3
Passphrase(9): MeshNode3
BSSID set: 0
6
3
192.168.4.3
Wifi connected
0.0.0.0

**Comment by devyte** [comment]
@FabianaFerreira there is a PR pending that adds NAPT to the core. It hasn't been fully tested, but I think it may serve your purpose better than trying to do it yourself. Also, if you use it and test it, you could provide feedback, thereby contributing here. Or maybe even help develop the functionality in case anything is missing or you find bugs.
Alternatively, there is a separate project that implements code to make the ESPs work as a mesh, although not a transparent one (also uses NAPT). Just google ESP8266 napt and you should find it.
Finally, there is a mesh api offered by espressif, which allows you to pass messages from node to node. There is an example in this repo, I think, but I seem to remember an issue stating that it doesn't work with recent versions of the code.
About your particular problem, the ESP has only a single radio, which means that, when in STATIONAP mode, if the station scans, it will skip channels, and will drag the AP with it, which means the clients connected to the AP will see it disappear, and likely disconnect.
But this is not the right place to discuss your project. This is an issue tracker, meant to track issues in the core, and your current code has usage errors. Discussions about your particular project should be held at a forum like esp8266.com or stackoverflow.
Closing as off topic.
If you're interested in the Napt PR, just look at the PR tab next to the issues tab. To be honest, I will need to look into that as well at some point, so I'm personally curious about what you would find.
