### ISSUE TITLE
access point / client config

### ISSUE THREAD

**Issue by ramarro123** [esp8266/Arduino#3647]
Hello,

it's possible to configure a single esp8266 as an accesspoint and making it connect to another accesspoint?

i have try

```
WiFi.softAPConfig(apIP, apIP, IPAddress(255, 255, 255, 0))
WiFi.softAP(apname, pwd)

```
and this create an ap, that work (i can see it from my pc)

then i do
` WiFi.begin(wifi_ssid, wifi_pwd);`

and the connection will work.

if then i try to ping 192.168.4.1 (the esp8266 in ap mode) it responde to ping.
trying to ping the ip given from dhcp, again work (hurray)

now, the httpserver configured simply with

`  httpServer.begin();`

serve page only on the ip given from dhcp, but not on 192.168.4.1, where port 80 it's not opened.
how can i make httpServer (and all other services for what matter) bind to both ips?

i am doing something of very wrong? :)

**Comment by devyte** [comment]
@ramarro123 yes, it is possible, there are projects that even implement NAPT to make a mesh of ESPs.
But this is not the right place to ask such questions. This is an issue tracker, meant to track issues in the core. Please refer to esp8266.com or stackoverflow for assistance with your project.
Closing as off topic.
