### ISSUE TITLE
getCoreVersion reports 00000000 on Windows

### ISSUE THREAD

**Issue by tablatronix** [esp8266/Arduino#3657]
Is this normal ? Is there something wrong with my platform environment ?

**Comment by davisonja** [comment]
Are you using the latest version from git, or the latest release package?

**Comment by tablatronix** [comment]
ahhhhh, I am using platformio staging, which uses repo not release.

So this is normal I assume

**Comment by davisonja** [comment]
I believe the coreversion gets computed and stored as part of the release
build process, so this would be expected for repo usage.
I haven't looked, so I'm not sure how simple it would be to change that,
but if people are using direct from repo it might be useful if it could be
something more meaningful (so you can actually tell the version from code,
which I presume is the aim :)

**Comment by igrr** [comment]
It should work for git version, if you are using Arduino IDE. There is a
hook in platform.txt which launches git to figure out the version.
Might be something that hasn't been ported over to platformio build script.

**Comment by davisonja** [comment]
Ah, okay. The version I currently have in operation has `## windows-compatible version may be added later
` which is why it's not done that for me using Windows :)

**Comment by tablatronix** [comment]
I see the hook, let me see if i can figure something out with platformio

**Comment by tablatronix** [comment]
Ahhh bash..

**Comment by tablatronix** [comment]
Looks like I am having issues with this on osx platformio with release
`ARDUINO_ESP8266_GIT_VER`

**Comment by d-a-v** [comment]
I ran into this too.
I just discovered that, from inside core/esp8266/*.cpp
```#include <core_version.h>``` is well behaving
```#include "core_version.h"``` is not
The default file with generic default value lives in the same directory, the other one is generated by platform.txt's recipes in arduino's os-dependant temporary directory. I don't know details about platformio.

**Comment by d-a-v** [comment]
Can you try [my alpha release channel](https://d-a-v.github.io/) to check if this issue is fixed ?

**Comment by d-a-v** [comment]
This issue has received multiple corrections over time, latest related ones are: #6735, #6745 already fixed in git master, verified on the alpha release channel.
Closing. Please wait for core-2.6.1.
