### ISSUE TITLE
Example: how to send client certificate?

### ISSUE THREAD

**Issue by bscheshir** [esp8266/Arduino#3667]
I can see many powerfull examples, great!
[with CA](https://github.com/esp8266/Arduino/blob/f6d232f1ac68fd52a69bb9a03995eaa6d7fde922/libraries/ESP8266WiFi/examples/HTTPSRequestCACert/HTTPSRequestCACert.ino)

But how I can send  `client certificate+key` in `TLS Handshake` phase for case server AND client verification (`Certificate`, `CertificateVerify`)?

I think this case is typical for remote sensor based on esp8266 and mounted out of smartHome local network, right?

**Comment by bscheshir** [comment]
for something like this
```sh
curl -v -k --key ssl/client01.key --cert ssl/client01.crt --url https://smartHomeRESTAPIDomain:8082/v1/sensor/1/measure/create
```

**Comment by bscheshir** [comment]
So... CA self assigned, server and all of clients has been signed by this self assigned CA.

**Comment by devyte** [comment]
Closing as off topic, see #3655 .

**Comment by copercini** [comment]
@bscheshir I have some examples here: https://github.com/copercini/esp8266-aws_iot

But due memory limitations it runs on limit
