### ISSUE TITLE
Not an real issue, but where can I find...

### ISSUE THREAD

**Issue by MarcusF2015** [esp8266/Arduino#3671]
... the source code of funktion ctime(). In time.h there is declaired, but in time.c is no ctime().

Marcus

**Comment by Juppit** [comment]
Instead of ctime() you can use sntp_get_real_time() witch is already in 
the SDK (see sntp.h).


On 02.10.2017 at 21:45 wrote MarcusF2015:
> ... the source code of funktion ctime(). In time.h there is declaired, 
> but in time.c is no ctime().

**Comment by devyte** [comment]
You should look at <TimeLib.h>.

Closing.

**Comment by Juppit** [comment]
On 03.10.2017 at 17:17 wrote Develo:
> You should look at <TimeLib.h>.

Is this part of this project?
