### ISSUE TITLE
HTTP Request to device using hostname

### ISSUE THREAD

**Issue by igorquintal** [esp8266/Arduino#3678]
Hi everyone! 

I'm using a NodeMCU board for a project, which simulates an alarm system. The NodeMCU board will connect to a Raspberry Pi through WiFi, to send HTTP requests referring alarms and other sensors information. The problem I'm facing, is that I don't want to specify any IP addresses on my code. I wanted the NodeMCU to connect to the Raspbery using the Pi's hostname. That way, I shouldn't have to worry when any of the IP address of the Raspberry is changed on my network.

I tried using **ESP8266HTTPClient.h**, but so far, I haven't had any success. I'm using the following line:
**http.begin(NAME_TO_RESOLVE, 3000, "/test");** 
But that does not work. If I replace the hostname with the corresponding IP address, everything works fine.

To overcome this problem, I'm using the library mDNSResolver ([Link](https://github.com/madpilot/mDNSResolver)). Using this library, I can call the begin method like this:
**http.begin(resolver.search(NAME_TO_RESOLVE).toString(), 3000,"/test");.** But I also have to include **WiFiUdp.h** for this to work, and I don't know why.

I wanted some help to see the simplest way to achive this, if it is possible to use only **ESP8266HTTPClient.h** or if any other external librbaries are needed. If so, what do you guys recomend ?

Thanks!!

**Comment by devyte** [comment]
@igorquintal what you need is dnsclient. I see an [object api reference](https://links2004.github.io/Arduino/d3/d7c/class_d_n_s_client.html), but I'm not sure about it, never seen that class. There is also an api that comes from lwip dns_gethostbyname(....).
In any case, this is not the right place to ask for assistance. Closing as off-topic, see #3655 .
