### ISSUE TITLE
ESP8266WiFi compile problem

### ISSUE THREAD

**Issue by Testato** [esp8266/Arduino#368]
Many examples do not work,
i'm on Windows and if try to compile NTPClient.ino all the IDE hang (installed by Board Manager)

after many try i found that the include
#include <WiFiUdp.h>

create rpoblem whit the original #include <WiFiUdp.h> of the WiFi Arduino Directory, instead we need the #include <WiFiUdp.h> on C:\Users\win7\AppData\Roaming\arduino15\packages\esp8266\hardware\esp8266\1.6.4-673-g8cd3697\libraries\ESP8266WiFi\src\WiFiUdp.h

I tried to Rename it in ESP8266WiFiUdp and it work

In the same dire we have some name renamed, ESP8266WiFi.h because it is a WiFi.h modification of the original present in the Arduino library folder.

It is better change all this name in this directory ?

**Comment by igrr** [comment]
Make sure you place ```#include <ESP8266WiFi.h>``` before any other includes from this library, like 
```#include <WiFiUDP.h>```.
