### ISSUE TITLE
.md -> .rst in "new issue" pattern

### ISSUE THREAD

**Issue by bscheshir** [esp8266/Arduino#3689]
> if you have a stack dump decode it:
>https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.md

>for better debug messages:
>https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.md

But actual instructions in `rst` 
[https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst](https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst)
[https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst](https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst)

**Comment by devyte** [comment]
@bscheshir do you mean the links are wrong? or rather, the docs need to be converted to .md?

**Comment by bscheshir** [comment]
@devyte see PR
