### ISSUE TITLE
Variable en modo sleep

### ISSUE THREAD

**Issue by jdelrio810** [esp8266/Arduino#3690]
Estoy tratando de contar por medio de una variable determinada cuantas veces el node MCU entra en modo deep sleep pero cuando el nodeMcu despierta se borra la información que hay en la variable. como puedo almacenar la información del contador gracias.

**Comment by devyte** [comment]
@jdelrio810 este no es lugar correcto para hacer ese tipo de preguntas. Ademas, el idioma elegido aqui es inglés.
Please discuss at a community forum. Closing as off topic, see #3655 .
