### ISSUE TITLE
Scan without disconnecting STA

### ISSUE THREAD

**Issue by diffstorm** [esp8266/Arduino#3708]
Hi,

I want to ask is it possible (by HW) to scan networks around when STA is connecting (without disconnect) ?
If yes, when we can start to develop a code for this?
If no, where it is written in vendor's resources?

Thanks.

**Comment by devyte** [comment]
@diffstorm the ESP has only one radio. When you do a scan, the radio hops channels to listen for beacons, and that means no STA access.
This is not the right place to ask such questions. Closing  per #3655 .
