### ISSUE TITLE
what is maximum sketch size for esp8285 OTA?

### ISSUE THREAD

**Issue by shahabmusic** [esp8266/Arduino#3709]
Sketch uses 330523 bytes (66%) of program storage space. Maximum is 499696 bytes.
when I do OTA, I get error space too small! 

I select 1M (64Kb SPFFS) from the menu. so what is maximum sketch size that can do OTA without going through space issues?

**Comment by devyte** [comment]
@shahabmusic the previous comment is correct. Please research the flash layout for the ESP.
Also, please don't open an issue to ask such questions. This is an issue tracker, not a discussion forum. Closing per #3655 .
