### ISSUE TITLE
wrong type in declaration of ESP.deepSleep()

### ISSUE THREAD

**Issue by 5chufti** [esp8266/Arduino#3719]
### Basic Infos

repeated issue as mentioned in "sdk update 2.1.0" branch

#### Hardware
Hardware:		not relevant
Core Version:      	2.1.0-rc2

### Description

deepsleep argument for µs is uint64 in sdk but only uint32 in esp8266 core
compare definitions in 

esp8266/cores/esp8266/Esp.h 
vs. 
esp8266/tools/sdk/include/user_interface.h

### Settings in IDE

not relevant

### Sketch

not relevant

### Debug Messages

not relevant

messages here

see attached diff
[Esp_core.diff.txt](https://github.com/esp8266/Arduino/files/1385269/Esp_core.diff.txt)

**Comment by igrr** [comment]
Thanks, will add an overload with uint64_t.
What's the cali_proc for in ESP class, by the way?

**Comment by 5chufti** [comment]
according to documentation this value is needed to calculate max. deep_sleep time.
see #3302
but somehow this value even changes during operation, so it is more "orientation" than exact value.

**Comment by igrr** [comment]
Right, but would it then be more useful to add a function to ESP class to
get the max sleep time?

**Comment by 5chufti** [comment]
whatever you like, just wanted to keep it simple.

**Comment by 5chufti** [comment]
@igrr 
again not in current release ....

**Comment by 5chufti** [comment]
@igrr @devyte 
could you please at least tag a milestone so that this topic isn't lost in next release?

**Comment by igrr** [comment]
@5chufti Done, tagged as a bug
