### ISSUE TITLE
minor prob: 2 warnings during compile

### ISSUE THREAD

**Issue by 5chufti** [esp8266/Arduino#3720]
### Basic Infos

two easy solveable warning during compile

#### Hardware
Hardware:		not relevant
Core Version:      	2.4.0-rc2

### Description

superfluous variable declaration in spiffs and core Esp code

### Settings in IDE

not relevant

### Sketch

not relevant

### Debug Messages

esp8266\cores\esp8266\Esp.cpp: In member function "bool EspClass::eraseConfig()":
esp8266\cores\esp8266\Esp.cpp:399:10: warning: unused variable "ret" [-Wunused-variable]
     bool ret = true;
             ^

esp8266\cores\esp8266\spiffs\spiffs_hydrogen.c: In function "SPIFFS_buffer_bytes_for_filedescs":
esp8266\cores\esp8266\spiffs\spiffs_hydrogen.c:16:49: warning: unused parameter "fs" [-Wunused-parameter]
 u32_t SPIFFS_buffer_bytes_for_filedescs(spiffs *fs, u32_t num_descs) {
                                                 ^

**Comment by devyte** [comment]
@5chufti I somehow doubt that the core version specified is correct...

**Comment by 5chufti** [comment]
yep, corrected

**Comment by devyte** [comment]
Closing as a subset of #3778 . Will track there.
