### ISSUE TITLE
On 2.4.0rc2 core , can new esptool using  "erase_flash"  for 16MB?

### ISSUE THREAD

**Issue by TridentTD** [esp8266/Arduino#3729]
On 2.4.0rc2 core , can new esptool using  "erase_flash"  for 16MB?

>esptool  --port COM8 erase_flash
This command for 16MB or 4MB ?

Thank you.

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			WeMos Pro 16M
Core Version:      	2.4.0-rc2

### Description

Problem description

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		16MB/15MB SPIFFS
CPU Frequency:		80Mhz
Flash Mode:			dio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		nodemcu

**Comment by devyte** [comment]
@TridentTD General support for 16MB is being tracked elsewhere.
If all you need is a yes/no answer specific to the esptool, please ask at a forum. This is an issue tracker, meant to track issues, and there is an onoing effort to clean up.
