### ISSUE TITLE
Question regarding static serving on ESP web server.

### ISSUE THREAD

**Issue by Xhantorz** [esp8266/Arduino#3734]
I'm running 2 ESP Wroom's 02, each having the same firmware. I want to be able to OTA update both of them from my personal server, but I want to be able to update both even if only 1 ESP has internet access. My current system works like this: The ESP with internet access uploads his own firmware from the personal web server and then does an OTASPIFFSupdate. It essentially downloads the same exact firmware to SPIFFS. Then that ESP static serves the firmware.bin stored in the SPIFFS. The second ESP that has no internet then can OTA update via the first ESP. That works, but I'm wondering if it would be possible without to much modification that the first ESP could directly static server his own firmware.bin instead of needing to downloading it to SPIFFS?  

It might be odd for some people to why I need this, but I'm looking to build a super dynamic system where both ESP's do not need internet access to update. 

Thanks,
Joe.

**Comment by devyte** [comment]
In theory, yes. In practice, no, but I don't remember the reasons. Serving from SPIFFS is considered the correct approach.
Not the right place to ask such questions. Closing per #3655 .
