### ISSUE TITLE
Serial port quickly receives data problems

### ISSUE THREAD

**Issue by haohanlin** [esp8266/Arduino#3737]
#### Hardware
Hardware:			ESP-12s

Module:  			Generic ESP8266 Module
Flash Size: 		4MB
CPU Frequency:		160Mhz
Flash Frequency:	40Mhz
Reset Method:		 nodemcu

The esp8266 serial port needs to receive data at 100ms per interval, and then use the HTTP.Get() request.But HTTP.GET() performs too long to result in the loss or overlap of data received by the serial port.Is there any solution？

**Comment by d-a-v** [comment]
Perhaps you should use big enough circular buffer between serial and HTTP server.

**Comment by cheng3100** [comment]
Maybe you can use a timer call back function to call the HTTP.GET every period which longer than 100ms

**Comment by haohanlin** [comment]
@cheng3100 However, the timer calls  HTTP. get    time. The serial port to receive data, this will still lead to receive data errors. How to deal with the timely reception of serial data? MCU usually serial port interrupt, but this is not.

**Comment by vdeconinck** [comment]
I guess you need to increase the serial receive buffer using Serial.setRxBufferSize() which was implemented in release 2.4.0 rc1 to prevent loss of bytes during http processing

**Comment by rglissmann** [comment]
I've added Serial.setRxBufferSize(256) to my sketch and am compiling with release release 2.4.0 rc1 and am getting the error:
Arduino: 1.8.5 (Windows Store 1.8.10.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

C:\Users\Randy\Documents\Arduino\CNC_server\CNC_server.ino: In function 'void setup()':

CNC_server:62: error: 'class HardwareSerial' has no member named 'setRxBufferSize'

   Serial.setRxBufferSize(256);

          ^

exit status 1
'class HardwareSerial' has no member named 'setRxBufferSize'

I've used https://github.com/esp8266/Arduino/releases/download/2.4.0-rc1/package_esp8266com_index.json to the Arduino IDE. Is this the correct way to compile?

**Comment by haohanlin** [comment]
Serial.begin (115200 );
Serial.setRxBufferSize(1024); @rglissmann

**Comment by vdeconinck** [comment]
OK, now that's another issue. It seems your board type cannot be found anymore. Maybe the tag of your board has changed between versions...
Can you choose another board type in the boards selection menu (say Wemos D1 mini) and check that it compiles, then select your NodeMCU board and try again ?

**Comment by rglissmann** [comment]
That helped. It compiles and also I don't get an error with the setRxBufferSize. I'm able to receive a larger payload now! I need to retry uploads several times to get OTA to work. I'm getting an error 11.

**Comment by vdeconinck** [comment]
If the serial problem is fixed, could you please close this issue.
If you have another problem, please discuss it first on esp8266.com or other forums, and if there is a consensus that you found an issue in the esp8266 cores, feel free to reopen a new issue here, with a minimal sketch exhibiting the problem.

**Comment by rglissmann** [comment]
Closes #3737

**Comment by jeroenst** [comment]
Works like a charm, thanx
