### ISSUE TITLE
ESPhttpUpdate.update does not work if sketch size more than 50% of the memory.

### ISSUE THREAD

**Issue by renat2985** [esp8266/Arduino#3739]
ESPhttpUpdate.update does not work if sketch size more than 50% of the memory.
Is this fixed in the new 2.4.0-rc2 version? Thanks.

**Comment by Pablo2048** [comment]
New sketch needs to be stored somewhere - how exactly do You think this can be "fixed"? If Your sketch is bigger than 512kB, You have two options:
1. use 3/1M memory model
2. create Your own memory model and linker script (I'm using 2/2)

**Comment by devyte** [comment]
You can't do OTA in that case. Please study the flash layout and you should understand why.
Closing.
