### ISSUE TITLE
ESP8266FS example or tutorial

### ISSUE THREAD

**Issue by robertgregor** [esp8266/Arduino#374]
Heo, how can I use the java tool ESP8266FS ? Is there any documentation or tutorial or howto document?

**Comment by me-no-dev** [comment]
not yet :) requires a binary to deal with creating SPIFFS images, but since support for SPIFFS has been dropped (for now), the tool is useless

**Comment by robertgregor** [comment]
I see, but don't understand, why it is dropped, thus this is I think needed very much. I have webserver and want to serve static pages, javascripts, ccs, pictures and so on...

**Comment by me-no-dev** [comment]
it's coming, but can not give timeframe. You can hook up an SD card and use that for static content (example available).

**Comment by robertgregor** [comment]
I think, there is already the tool for it i.e. spiffy: http://hackersome.com/p/xlfe/spiffy
You download it, create the directory, copy the files and then build it to create the spiff_rom.bin.
I think, here I am not sure, how to burn it to esp, thus if I use 512 flash and 64K for spiffs, which address to use to burn it. And then, there should be support in esp http webserver.

**Comment by me-no-dev** [comment]
we have such tool as well and the Arduino tool calls it to do the same thing for the "data" subfolder of the sketch, then uploads it. We had the needed support in Arduino as well and will be back again there soon (hopefully).

**Comment by igrr** [comment]
Yeah, https://github.com/igrr/mkspiffs

**Comment by hallard** [comment]
Hi guys,
SPIFFS is really, really really a excellent feature, I love it ;-)
in my dreams, a web interface showing FS filesystem in browser with upload/delete/edit files will be the top ;-)

**Comment by Links2004** [comment]
you can use this one as base:
https://github.com/esp8266/Arduino/tree/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WebServer/examples/SDWebServer

**Comment by hallard** [comment]
Damned, you kicked me, I should have read this one before!
But heuuu, sample says I do not have SD, ok I'm kidding ;-)

**Comment by igrr** [comment]
@hallard i've updated the fs browser by @me-no-dev for the new FS API, here's the link:
https://files.gitter.im/esp8266/Arduino/jRlu/FSBrowser.zip

Will add this as an example sketch after some cleanup.

**Comment by hallard** [comment]
@igrr 
Thanks, works fine, nice Graphs ;-)
I needed to dig into the code to list files on SPIFFS to learn that syntax is something like :
`http://192.168.1.51/edit` ;-)
