### ISSUE TITLE
How about add path parameter to execute installer get.py

### ISSUE THREAD

**Issue by bscheshir** [esp8266/Arduino#3741]
I have [problem](https://github.com/docker-library/python/issues/230) with [git installer](https://github.com/esp8266/Arduino#using-git-version)

in part
```sh
python get.py
```
if I run it throw `docker run`

I think we avoid this if we can pass workdir path into script 
```sh
python get.py /usr/src/myapp
```

will replace `..` in path `load_tools_list`

```py
File "Arduino/esp8266com/esp8266/tools/get.py", line 113, in <module>
    tools_to_download = load_tools_list('../package/package_esp8266com_index.template.json', identify_platform())
```

**Comment by pipi61** [comment]
Hi!
the esp8266-2.4.0-rc2.zip not containing package folder.
Goto the main page: https://github.com/esp8266/Arduino and click "CLONE DOWNLOAD"
