### ISSUE TITLE
OTA Update with check md5 From File on a server

### ISSUE THREAD

**Issue by mcmega** [esp8266/Arduino#3746]
Hi All!
On the server is the file DEVICE_MODEL.txt. 
It contains the firmware version and md5 bin files:
1 F52187696F59EE5A1D85285D0F0B62A8 29131F8A6A853402AAB5433D521B1EC0
I'm reading this file and looking at the firmware version (the first number).
If the version is more current, I get the bin files and run the update.
From the file I take md5 and compare. But does not work.
Update:
```
#define OTA_HOST            "updates.soi-tech.com"
#define DEVICE_MODEL        "WalkingLight"

bool _otaUpdate(bool spiffs) {
  Serial.println(spiffs ? "Updating SPIFFS" : "Updating FLASH");
  HTTPClient httpClient;
  httpClient.useHTTP10(true);
  httpClient.setTimeout(5000);
  char url[128];
  sprintf(url, "http://%s/%s-%d-%s.bin", OTA_HOST, DEVICE_MODEL, latVer, spiffs ? "fs" : "esp");
  httpClient.begin(url);
  int code = httpClient.GET();
  if (code != HTTP_CODE_OK) {
    Serial.printf("%d | Unable to fetch update %s\r\n", code, url);
    httpClient.end();
    return false;
  }
  if (!Update.setMD5(spiffs ? ffsMD5 : espMD5)) {
    Serial.printf("Error: Update.setMD5(%s): ", spiffs ? ffsMD5 : espMD5);
    Update.printError(Serial);
    httpClient.end();
    return false;
  }
  if (!Update.begin(httpClient.getSize(), spiffs ? U_SPIFFS : U_FLASH)) {
    Serial.printf("Error: Update.begin(%d, U_FLASH): ", httpClient.getSize());
    Update.printError(Serial);
    httpClient.end();
    return false;
  }
  if (!Update.writeStream(*httpClient.getStreamPtr())) {
    Serial.print("Error: Update.writeStream(): ");
    Update.printError(Serial);
    httpClient.end();
    return false;
  }
  if (!Update.end()) {
    Serial.print("Error: Update.end(): ");
    Update.printError(Serial);
    httpClient.end();
    return false;
  }
  Serial.println(spiffs ? "SPIFFS update OK" : "FLASH update OK");
  httpClient.end();
  return true;
}

void otaUpdate() {
  _otaUpdate(true) && _otaUpdate(false);
}
```
Serial:
Updating SPIFFS␍␊
-1 | Unable to fetch update http://updates.soi-tech.com/WalkingLight-1-fs.bin

**IDE Settings:**
ESP8285
Core 2.4.0
1M (128K SPIFFS)
CPU 80MHz

Checking for an update and reading the WalkingLight.txt file works correctly.
https://updates.soi-tech.com/WalkingLight.txt
```
void otaAvailable() {
  flagCheckUpdate = false;
  WiFiClientSecure httpsClient;
  if (!httpsClient.connect(OTA_HOST, 443)) {
    uartSendEA("Connection OTA Failed");
    httpsClient.stop();
    return;
  }
  if (httpsClient.verify(OTA_FP, OTA_HOST)) {
    httpsClient.print(String("GET ") + OTA_PATH + " HTTP/1.1\r\nHost: " + OTA_HOST + "\r\nConnection: close\r\n\r\n");
    unsigned long timeout = millis();
    while (httpsClient.available() == 0) {
      if (millis() - timeout > 5000) {
        uartSendEA("Client Timeout");
        httpsClient.stop();
        return;
      }
    }
  } else {
    uartSendEA("Certificate");
    httpsClient.stop();
    return;
  }
  String line = "";
  while (httpsClient.available()) {
    line = httpsClient.readStringUntil('\r');
  }
  const char * response = line.c_str();
  const char * _espMD5 = strchr(response, ' ') + 1;
  const char * _ffsMD5 = strchr(_espMD5, ' ') + 1;
  const char * _mcuMD5 = strchr(_ffsMD5, ' ') + 1;
  latVer = strtol(response, NULL, 10);
  strncpy(espMD5, _espMD5, 32); espMD5[32] = '\0';
  strncpy(ffsMD5, _ffsMD5, 32); ffsMD5[32] = '\0';
  strncpy(mcuMD5, _mcuMD5, 32); mcuMD5[32] = '\0';
}
```

**Comment by devyte** [comment]
@mcmega no basic info, no IDE settings, sketch is incomplete. The issue template exists for a reason. Please update your post with the required info.

**Comment by tranpic** [comment]
HI
i copy your OTA library and paste in C:\Users\Tran\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries

but have no ArduinoOTA.getCommand(). -> i delete it.

then can not update via OTA

15:01:52 [ERROR]: No response from device

Error[1]: Begin Failed (debug not arduino ide).

NodeMCU 1.0 (ESP-12E Module)
CPU Frequency: 80MHz
Flash Size: "4M (3MSPIFFS)"
Upload Speed: "115200"
Port: "esp8266-df04c4 at 192.168.25.130"

**Comment by tranpic** [comment]
after install core 2.4.0 

16:01:13 [ERROR]: Bad Answer: ERR: ERROR[8]: Flash config wrong real: 2097152 IDE: 4194304

the selected serial port 
 does not exist or your board is not connected

how to fit it?

**Comment by mcmega** [comment]
The project is large and divided into parts.
IDE Settings:
Board: D1 mini (ESP-12)
CPU Frequency: 80MHz
Flash Size: "1M (256KSPIFFS)"
Upload Speed: "115200"

I call the function otaAvailable(), Function reads a file txt (It contains the firmware version and md5 for bin files:
1 F52187696F59EE5A1D85285D0F0B62A8 29131F8A6A853402AAB5433D521B1EC0
I'm parsing this file (1 - version number, 2 - md5 FS, 3 - md5 Firmware, Separator - space).
Server with SSL

The function otaAvailable() returns true or false.
If true - update started otaUpdate()
Varibles  is global
long latest_version = VERSION;
char *latest_esp_md5 = "";
char *latest_fs_md5 = "";

But I get into the condition check and the update does not happen.
if(!Update.setMD5(spiffs ? latest_fs_md5 : latest_esp_md5)) {
        Serial.printf("Error: Update.setMD5(%s): ", spiffs ? latest_fs_md5 : latest_esp_md5);
        Update.printError(Serial);
        return false;
    }
If you disable this check, everything works correctly.

**Comment by mcmega** [comment]
Updated topic!
