### ISSUE TITLE
AP_MODE after beginWPSConfig() not possible

### ISSUE THREAD

**Issue by gerrylenz** [esp8266/Arduino#3751]
#### Hardware
Hardware:			ESP-12
Core Version:      	2.1.0

### Description

	bool wpsSuccess = WiFi.beginWPSConfig();
	if (wpsSuccess) {
		String newSSID = WiFi.SSID();
		if (newSSID.length() > 0) {
			// WPSConfig has already connected in STA mode successfully to the new station. 
		}
		else {
			wpsSuccess = false;
	                WiFi.disconnect(true);
                        WiFi.softAPdisconnect(true);
                        IPAddress ip(192, 168, 4, 1);
                        IPAddress gateway(192, 168, 4, 1);
                        IPAddress subnet(255, 255, 255, 0);
                        WiFi.mode(WIFI_AP);
                        WiFi.enableAP(true);
                        WiFi.config(ip, gateway, subnet);
                        delay(100);
                        WiFi.softAP("TEST", "");
                        delay(100);
                        Serial.println(ip2str(WiFi.softAPIP());
		}

WPS ok and no connections problems.
But is no WPS connected then don't possible AP established.
WiFi.softAPIP() is 0.0.0.0

What am I doing wrong?

**Comment by devyte** [comment]
@gerrylenz  WiFi.config => WiFi.softAPConfig
Not the right place to ask these questions, this is an issue tracker. Also, please readthedocs.
Closing as user error and off-topic.
