### ISSUE TITLE
ESP8266WebServer has no member named arg

### ISSUE THREAD

**Issue by Thegasman2000** [esp8266/Arduino#3762]
#### Hardware
Hardware:			?wemos D1 Mini ESP8266?
Core Version:      	?2.1.0-rc2?

### Description

When trying to use if server.hasArg I get no member named arg even though I can see in the keywords.txt file that there should be. I have tried updating the board software and also tried the package json fix to no avail. 

### Settings in IDE

Module:  			Wemos D1 Mini
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

#include <ESP8266WebServer.h>
#include <ESP8266WiFi.h>
#include <time.h>

// Wifi Settings
const char* ssid = "PrettyFlyForAWifi";
const char* password = "reidbuck";
WiFiServer server(80);

// Time Settings
int timezone = 3;
int dst = 0;

// LED Settings
int blueLedPin = 5;
int blueLedOn = 4;
int blueLevel = 1000;

int whiteLedPin = 0;
int whiteLedOn = 2;
int whiteLevel = 100;

void setup() {
  pinMode(blueLedPin, OUTPUT);
  pinMode(blueLedOn, OUTPUT);
  pinMode(whiteLedPin, OUTPUT);
  pinMode(whiteLedOn, OUTPUT);
  Serial.begin(115200);
  delay(10);

  // Connect to WiFi network
  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");

  // Start the server
  server.begin();
  Serial.println("Server started");

  // Print the IP address
  Serial.print("Use this URL to connect: ");
  Serial.print("http://");
  Serial.print(WiFi.localIP());
  Serial.println("/");

  // Time Config
  configTime(3 * 1200, 0, "pool.ntp.org");
  Serial.println("\nWaiting for time");
  while (!time(nullptr)) {
    Serial.print(".");
    delay(1000);
  }

  // Turn off LEDS ON BOOT

  digitalWrite(blueLedOn, LOW);
  digitalWrite(whiteLedOn, LOW);
}

void loop() {

  // Get time
  time_t now = time(nullptr);
  Serial.println(ctime(&now));
  delay(1000);

  // Check if a client has connected
  WiFiClient client = server.available();
  if (!client) {
    return;
  }

  // Wait until the client sends some data
  Serial.println("new client");

  // Read the first line of the request
  String request = client.readStringUntil('\r');
  Serial.println(request);
  client.flush();

  //  LED Control
  int value = LOW;

  if (request.indexOf("/blueLED=ON") != -1)  {
    digitalWrite(blueLedOn, HIGH);
    analogWrite(blueLedPin, blueLevel);
    value = HIGH;
  }
  if (request.indexOf("/blueLED=OFF") != -1)  {
    digitalWrite(blueLedOn, LOW);
    value = LOW;
  }

  if (request.indexOf("/whiteLED=ON") != -1)  {
    digitalWrite(whiteLedOn, HIGH);
    analogWrite(whiteLedPin, blueLevel);
    value = HIGH;
  }
  if (request.indexOf("/whiteLED=OFF") != -1)  {
    digitalWrite(whiteLedOn, LOW);
    value = LOW;
  }

  // New Bit
  client.println("HTTP/1.1 200 OK");
  client.println("Content-Type: text/html");
  client.println();

  client.println("<HTML>");
  client.println("<HEAD>");
  client.println("<TITLE>LED Control Module</TITLE>");
  client.println("</HEAD>");
  client.println("<BODY>");

  client.println("<FORM ACTION='/' method=post >"); //uses IP/port of web page

  client.println("Set LED LEVELS: <INPUT TYPE=TEXT NAME='LEDWHITE' VALUE='' SIZE='25' MAXLENGTH='50'><BR>");

  client.println("<INPUT TYPE=SUBMIT NAME='submit' VALUE='Send White LED Level'>");

  client.println("</FORM>");

  client.println("<BR>");

  // Blues
  client.print("The Time is now : ");
  client.print(ctime(&now));
  client.print("Blue Leds are now: ");

  if (blueLedPin == HIGH) {
    client.print("On");
  } else {
    client.print("Off");
  }
  client.println("<br><br>");
  client.println("<a href=\"/blueLED=ON\"\"><button>Turn Blue Leds On </button></a>");
  client.println("<a href=\"/blueLED=OFF\"\"><button>Turn Blue Leds Off </button></a><br />");
  client.println("</html>");

  // Whites

  client.print("White Leds are now: ");

  if (whiteLedPin == HIGH) {
    client.print("On");
  } else {
    client.print("Off");
  }
  client.println("<br><br>");
  client.println("<a href=\"/whiteLED=ON\"\"><button>Turn White Leds On </button></a>");
  client.println("<a href=\"/whiteLED=OFF\"\"><button>Turn White Leds Off </button></a><br />");
  client.println("</html>");

  delay(1);
  Serial.println("Client disonnected");
  Serial.println("");
}

  void getWhiteLevel() {
  if (server.hasArg("whiteLevel")){
    whiteLevel = server.arg("whiteLevel").toInt();
    Serial.print("WHITE LEVEL SET TO: ");
    Serial.println(whiteLevel);
  }

### Debug Messages

```
exit status 1
'class WiFiServer' has no member named 'hasArg'
```

**Comment by devyte** [comment]
@Thegasman2000 WiFiServer => ESP8266Webserver. Please readthedocs.
Closing as user error.
