### ISSUE TITLE
The library does not support a long Router password  

### ISSUE THREAD

**Issue by johann96** [esp8266/Arduino#3777]
I have a long WPA2 password and i could not connect to my router, because the size is limited.
Please change the length from: 
SerialESP8266wifi.h
[...]
char _ssid[16];
char _password[16];
[...]
to a higher value!

**Comment by devyte** [comment]
@johann96 no basic info, no IDE settings, no sketch. You pretty much ignored the entire issue template.
I can't find file SerialESP8266wifi.h in the repo, and I also can't find a declaration of _ssid[16] or _password[16]. In all cases where these are declared, they are of size 32 and 64.
A quick google yields that file SerialESP8266wifi.h is found in [this repo](https://github.com/ekstrand/ESP8266wifi) , and in that file I do see declarations of size 16.
I think you're in the wrong repo.
Closing.
