### ISSUE TITLE
SSL Handling in esp8266HTTPClient is awful

### ISSUE THREAD

**Issue by AHaymond** [esp8266/Arduino#3784]
When will this library be improved so that the SSL Fingerprint is not required to connect to an https address?

It is maddening that this is a requirement for something that is hard coded into an arduino only to inevitably fail when the cert is updated or changed!

**Comment by igrr** [comment]
Please refer to
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/HTTPSRequestCACert/HTTPSRequestCACert.ino
as an example of verification using root certificate. This is available in
2.4.0-rc2.

There is also a work-in-progress option to verify certificate's
subjectPublicKeyInfo, which usually doesn't change when the certificate is
reissued:

https://github.com/esp8266/Arduino/pull/3700
