### ISSUE TITLE
softap_config_equal config comparisons missing

### ISSUE THREAD

**Issue by tablatronix** [esp8266/Arduino#3797]
master 

ESP8266WiFiAP.cpp
softap_config_equal()
does not do comparisons for
`beacon_interval`
`authmode`

This can cause issues with mixing library calls and SDK calls together, if users are directly manipulating `wifi_softap_set_config` and also using startAP etc.

**Comment by tablatronix** [comment]
same could be said for `sta_config_equal` bssid also

**Comment by devyte** [comment]
@tablatronix will you be making a PR for this?

**Comment by tablatronix** [comment]
Sure

**Comment by tablatronix** [comment]
added PR

**Comment by devyte** [comment]
#'3858 is already merged. Closing.
