### ISSUE TITLE
Failure rate of httpUpdate really high.

### ISSUE THREAD

**Issue by zuzy** [esp8266/Arduino#3803]
HttpUpdate is almost 40%. 
When Update, UDP broadcast & TCP server listen & Serial Recv are working in the same time. 
Do the services effect Update?

**Comment by bill-orange** [comment]
I was getting a high failure rate two days ago with the system-wide internet failure covered in the news.  It got better.  Are you still getting a high failure rate today?

**Comment by devyte** [comment]
@zuzy no basic info, no IDE settings, no example sketch. You pretty much ignored the entire issue template.
I suggest trying latest git, on lwip2.
Closing due to lack of info per issue policy.
