### ISSUE TITLE
Cannot upload my sketch to my ESP8266.

### ISSUE THREAD

**Issue by crazyhorse961** [esp8266/Arduino#3807]
#### Hardware
Hardware:			I'm not aware of it, i bought it here tho: https://goo.gl/zs32sC
Core Version:      	Not aware of it

### Description

Cannot upload my sketch to ESP8266.

### Settings in IDE

Module:  			Olimex MOD-WIFI-ESP8266
Flash Size: 		1MB
CPU Frequency:	80Mhz
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Upload Speed:        9600
Programmer:           Arduino ISP

### Debug Messages
```trying to connect
	flush start
	setting serial port timeouts to 1 ms
An error occurred while uploading the sketch
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
warning: espcomm_sync failed
error: espcomm_open failed´´´


I got drivers working, the esp8266 connects successfully to my Windows 10 pc.
I also pressed the RST button so the esp8266 is totally empty.

**Comment by caverna** [comment]
Hi @crazyhorse961, please look at the issue #3547.
There I realize two things: one is that the MCU programmer is more tolerant to errors, second you don't need a 30A power source, but you must have very good capacitors in VCC pins!

**Comment by WereCatf** [comment]
@crazyhorse961 The board you linked to is not an Olimex-board. Change your IDE-settings to NodeMCU 0.9 and try again.

**Comment by crazyhorse961** [comment]
Hello @WereCatf, i changed it to NodeMCU 0.9 and i get the same output.

**Comment by crazyhorse961** [comment]
Updates, now the blue LED turns on, but i still cannot find the WiFi network.
I tried to send commands with RealTerm but i don't receive any output, if this can help.

**Comment by crazyhorse961** [comment]
Updates, now the blue LED turns on, but i still cannot find the WiFi network.
I tried to send commands with RealTerm but i don't receive any output, if this can help.

**Comment by porkyneal** [comment]
Have you set the correct baud rate in RealTerm to match that of the ESP?

**Comment by Pablo2048** [comment]
Guys but this is known problem - raise your upload speed to something higher, NOT 9600bd. I suggest >57600 ...

**Comment by crazyhorse961** [comment]
@Pablo2048 this ESP's recommended bd is 9600, i wont increase it, i also tried running it with 57600 but same thing.
@porkyneal Yes.

**Comment by Pablo2048** [comment]
@crazyhorse961 huh? Where from you got this (IMHO stupid) speed recommendation? Do you imagine how much time take for example upload 3MB SPIFFS image with this speed?

**Comment by crazyhorse961** [comment]
@Pablo2048 it's a text behind my esp8266 on connectors.
It litterally says "Use 9600bps baud rate"

**Comment by Pablo2048** [comment]
But this is for Lua firmware right? Not for Arduino one...

**Comment by crazyhorse961** [comment]
I'm not aware.. ill try with 115200.

**Comment by Pablo2048** [comment]
Ok, it seems that you are a noob with ESP so here are my suggestions:
1. this is not right place to ask such questions (use the forum) - develo probably closes this thread soon...
2. set your serial speed to 115200 and try to upload blink (or another simple sketch)
3. if this fail try to change reset method (i'm using nodemcu) and try to upload sketch again

**Comment by crazyhorse961** [comment]
Yep, its litterally my first project with these cool things, and now it's also working! :)
Thanks to everyone
