### ISSUE TITLE
Unable to use http.setAuthorization for ESPhttpUpdate

### ISSUE THREAD

**Issue by pjunni** [esp8266/Arduino#3812]
I did not find a way to use http.setAuthorization for ESPhttpUpdate, but I solved the issue by adding the line http.setAuthorization("username","password"); on line 181 in https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp. Is there a more "correct" way to do this or could there be an overloaded handleUpdate function that takes these "username" and "password" and pass them into http.setAuthorization("username","password");?

**Comment by devyte** [comment]
@pjunni if I understand the request correctly, what you want to do is update from a webserver that requires user/pass. Is that correct?

**Comment by pjunni** [comment]
That's correct.

**Comment by pjunni** [comment]
@devyte Would you have any suggestions on this matter?

**Comment by jatayu86** [comment]
I face the similar issue,could someone please let us know how to add http authorization headers for ESPHttpUpdate?

**Comment by ngashok** [comment]
Facing same issue. How to do OTA from https server having authorisation with username/password.

**Comment by Swiftnesses** [comment]
Was this ever solved, I have the same issue?

**Comment by drhideg** [comment]
If you are still interested, would you give it a try this PR? #7190

**Comment by earlephilhower** [comment]
Fixed via the mentioned PR (#7190).  Closing.
