### ISSUE TITLE
ESP8266 AT Commands not working

### ISSUE THREAD

**Issue by unclewen** [esp8266/Arduino#3834]
I connected GPIO0 to GND and uploaded an empty sketch as I wasn't able to upload any sketches. I successfully uploaded the empty sketch but I received an fatal error on the serial monitor so I disconnected GPIO0. After that I tried AT commands on the serial monitor but it stopped working. Initially before I connect GPIO0 to GND it was working. Even if I connect GPIO0 to GND it doesn't let me upload any sketches anymore. Any clue how to fix this? Desperately need help on this.

**Comment by devyte** [comment]
This is not the repo for the AT commands. This is the Arduino core repo.
Closing.
