### ISSUE TITLE
nodeMCU ESP8266 queue.h no such file

### ISSUE THREAD

**Issue by XandeGasperini** [esp8266/Arduino#3839]
Hello, i'am having an error using Blynk NodeMCU Wifi example.
When I try to Upload the code to my board, I have this error code:

Arduino: 1.8.5 (Mac OS X), Board: "ESP32 Dev Module, QIO, 80MHz, 4MB (32Mb), 921600, None"

In file included from /Users/Alexandre/Documents/Arduino/libraries/ESP8266WiFi/src/ESP8266WiFi.h:33:0,
                 from /Users/Alexandre/Documents/Arduino/libraries/Blynk/examples/Boards_WiFi/NodeMCU/NodeMCU.ino:41:
/Users/Alexandre/Documents/Arduino/libraries/ESP8266WiFi/src/ESP8266WiFiType.h:26:19: fatal error: queue.h: No such file or directory
 #include <queue.h>

                   ^
compilation terminated.
exit status 1
Error compiling for board ESP32 Dev Module.
.....................................................................................................................................................................
IOS Version : 10.12.6
Board: Goouuu-ESP32 w/ ESP-WROOM-32

**Comment by RudyFiero** [comment]
Can you compile any code without error? To me it looks like you have have messed up the install. You have a ESP32 but you are trying to compile with an ESP8266 compiler?
