### ISSUE TITLE
website that serves Json file down?

### ISSUE THREAD

**Issue by alexmac131** [esp8266/Arduino#3843]
I get this message when attempting to connect after not being able to connect through the arduino board manager..   The directions in this git point specifically  to - its down at time of this writing
"http://arduino.esp8266.com/stable/package_esp8266com_index.json"   

This site can’t be reached

arduino.esp8266.com refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by charliejgallo** [comment]
same here!

**Comment by absk1s3** [comment]
I have the same issue, it seems like arduino.esp8266.com is down.

**Comment by Multiplexer2017** [comment]
same here ;-(

**Comment by an4cr0n** [comment]
same

**Comment by FsFalcon** [comment]
seeing the same

**Comment by rjp663** [comment]
Me too!

**Comment by maslaff** [comment]
Подтверждаю - упало...

**Comment by arthur12320** [comment]
me too

**Comment by kegrad** [comment]
This was also discussed on the arduino forums: https://forum.arduino.cc/index.php?topic=461880.0 
It suggests the alternative address https://github.com/esp8266/Arduino/releases/download/2.3.0/package_esp8266com_index.json which seems to work for me.

**Comment by arthur12320** [comment]
@kegrad changing to that link also worked for me. thanks for the help!

**Comment by rjp663** [comment]
Thank you!!! The alternate URL worked for me.
