### ISSUE TITLE
Exposing spiffs_object_truncate() in FS API

### ISSUE THREAD

**Issue by everslick** [esp8266/Arduino#3846]
SPIFFS offers an function to truncate a file to a specific size. This is very useful, for rotating logfiles without going through a temp file as this needs additional space on the filesystem. Therefor I propose to expose

s32_t spiffs_object_truncate(
    spiffs_fd *fd,
    u32_t new_len,
    u8_t remove_object);

which is defined in spiffs_nucleus.h through the FS API.

**Comment by kristianmitk** [comment]
+1 - will this be added in the near future?

**Comment by earlephilhower** [comment]
Simple enough to add to #5525

**Comment by everslick** [comment]
@earlephilhower THX! That is very much appreciated!
