### ISSUE TITLE
Sketch won't recognize SPI pins

### ISSUE THREAD

**Issue by AlexofAllTrades** [esp8266/Arduino#3866]
Hardware:			ESP-12E
Core Version:      	?2.1.0-rc2?

### Description

I am trying to create a network lighting controller to control Addresable LEDs (WS2811).  I have this same sketch running flawlessly on an Arduino Nano, it has not yet been fully adapted to the Node MCU hence the serial commands still being in place and network commands not yet being there.  The plan is to run it from a Raspberry pi server that will push colors/animations based on scheduling and a webpage.  Anyway the issue I am having is getting the program to recognize the SPI pins on the Node MCU causing it to bit bang, which works but there is visible noise (flickering) in the LEDs that gets worse the further from the controller the LED's are.  I am far from knowledgeable at programming most of my code is stitched together from other peoples projects any input is greatly appreciated.

### Settings in IDE

Module:  			NodeMCU 1.0
Flash Size: 		4MB
CPU Frequency:		160Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		SERIAL (can't get OTA to work brings up a Python error?)
Reset Method:		nodemcu

#include <SerialCommand.h>
#include <FastLED.h>            // Include FastLED library
#include <ArduinoOTA.h>         // Include Over the Air update library
#include <ESP8266WiFi.h>        // Include the Wi-Fi library
#include <ESP8266mDNS.h>        // Include the mDNS library

const char* ssid     = "Kayl House";         // The SSID (name) of the Wi-Fi network you want to connect to
const char* password = "5419355807";     // The password of the Wi-Fi network

int Motion = 1;
#define LED_PIN_1    8
#define NUM_LEDS_1   100
#define BRIGHTNESS   125
#define LED_TYPE    WS2811
#define COLOR_ORDER BRG
CRGB leds1[NUM_LEDS_1];
SerialCommand sCmd;
#define UPDATES_PER_SECOND 50

CRGBPalette16 currentPalette;
TBlendType    currentBlending;

extern CRGBPalette16 myRedWhiteBluePalette;
extern const TProgmemPalette16 myRedWhiteBluePalette_p PROGMEM;

extern CRGBPalette16 myHalloweenPalette;
extern const TProgmemPalette16 myHalloweenPalette_p PROGMEM;

extern CRGBPalette16 myOregonDuckPalette;
extern const TProgmemPalette16 myOregonDuckPalette_p PROGMEM;

extern CRGBPalette16 mySoftLightingPalette;
extern const TProgmemPalette16 mySoftLightingPalette_p PROGMEM;

extern CRGBPalette16 myChristmasPalette;
extern const TProgmemPalette16 myChristmasPalette_p PROGMEM;

extern CRGBPalette16 OffPallete;
extern const TProgmemPalette16 OffPallete_p PROGMEM;

void setup() {
    delay( 3000 ); // power-up safety delay
    FastLED.addLeds<LED_TYPE, LED_PIN_1, COLOR_ORDER>(leds1, NUM_LEDS_1).setCorrection( TypicalLEDStrip );
    FastLED.setBrightness(  BRIGHTNESS );
    Serial.begin(9600); //Open Serial port to send and recieve commands
    delay(10);
    Serial.println('\n');
  
    WiFi.begin(ssid, password);             // Connect to the network
    Serial.print("Connecting to ");
    Serial.print(ssid); Serial.println(" ...");

    int i = 0;
    while (WiFi.status() != WL_CONNECTED) { // Wait for the Wi-Fi to connect
    delay(1000);
    Serial.print(++i); Serial.print(' ');
    }
    Serial.println('\n');
    Serial.println("Connection established!");  
    Serial.print("IP address:\t");
    Serial.println(WiFi.localIP());         // Send the IP address of the ESP8266 to the computer

    if (!MDNS.begin("LED1")) {             // Start the mDNS responder for esp8266.local
    Serial.println("Error setting up MDNS responder!");
    }
    Serial.println("mDNS responder started");

    currentPalette = myChristmasPalette_p;
    currentBlending = NOBLEND;
    //sCmd.addCommand("Palette",       Set_Palette); //Serial Commands not always registered, suspect may need to create an "interupt"
    sCmd.addCommand("A",       Set_SoftLight);
    sCmd.addCommand("B",       Set_Halloween);
    sCmd.addCommand("C",       Set_UofO);
    sCmd.addCommand("D",       Set_USA);
    sCmd.addCommand("E",       Set_Christmas);
    sCmd.addCommand("0",       Stop);   
    sCmd.addCommand("1",       Move);
    sCmd.addCommand("5",       Swap);
    sCmd.addCommand("Off",     Off);
    sCmd.addCommand("BRIGHT",  Set_Brightness);
    sCmd.addCommand("SPEED",   Set_Speed);
    sCmd.setDefaultHandler(unrecognized);
    
    ArduinoOTA.setHostname("LED1");
    ArduinoOTA.setPassword(password);

    ArduinoOTA.onStart([]() {
    Serial.println("Start");
    });
    ArduinoOTA.onEnd([]() {
    Serial.println("\nEnd");
    });
    ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
    Serial.printf("Progress: %u%%\r", (progress / (total / 100)));
    });
    ArduinoOTA.onError([](ota_error_t error) {
    Serial.printf("Error[%u]: ", error);
    if (error == OTA_AUTH_ERROR) Serial.println("Auth Failed");
    else if (error == OTA_BEGIN_ERROR) Serial.println("Begin Failed");
    else if (error == OTA_CONNECT_ERROR) Serial.println("Connect Failed");
    else if (error == OTA_RECEIVE_ERROR) Serial.println("Receive Failed");
    else if (error == OTA_END_ERROR) Serial.println("End Failed");
    });
    ArduinoOTA.begin();
    Serial.println("OTA ready");
}

void loop()
{
    ArduinoOTA.handle();
    sCmd.readSerial();
    static uint8_t startIndex = 0;
    
    startIndex = startIndex + Motion; /* motion speed */
   
    FillLEDsFromPaletteColors( startIndex);
    
    FastLED.show();
    FastLED.delay(1000 / UPDATES_PER_SECOND);
}

void FillLEDsFromPaletteColors( uint8_t colorIndex)
{
    uint8_t brightness = 255;
    
    for( int i = 0; i < NUM_LEDS_1; i++) {
        leds1[i] = ColorFromPalette( currentPalette, colorIndex, brightness, currentBlending);
        colorIndex += 3;
    }
}

//void Set_Pallete(){
//  Serial.println("Set Color Pallete, 'Soft Light', 'Oregon Ducks', 'Halloween', 'Patriotic'.");
//}
void Set_SoftLight(){
    currentPalette = mySoftLightingPalette_p;
    FillLEDsFromPaletteColors(0);
    Serial.println("Soft Lighting");
}
void Set_Halloween(){
    currentPalette = myHalloweenPalette_p;
    FillLEDsFromPaletteColors(0);
    Serial.println("Boo!");
}
void Set_UofO(){
    currentPalette = myOregonDuckPalette_p;
    FillLEDsFromPaletteColors(0);
    Serial.println("Go Ducks!");
}
void Set_USA(){
    currentPalette = myRedWhiteBluePalette_p;
    FillLEDsFromPaletteColors(0);
    Serial.println("God Bless America!");
}
void Set_Christmas(){
    currentPalette = myChristmasPalette_p;
    FillLEDsFromPaletteColors(0);
    Serial.println("Merry Christmas");
}
void Stop(){
    Motion = 0;
    Serial.println("Freeze");
}
void Move(){
    Motion = 1;
    Serial.println("Motion");
}
void Swap(){
    Motion = 5;
    Serial.println("Color Swap");
}
void Off(){
    fill_solid( currentPalette, 16, CRGB::Black);
    FillLEDsFromPaletteColors(0);
    Serial.println("Off");
}
void Set_Brightness(){
  Serial.println("Set speed in updates per second.");
}
void Set_Speed(){
  Serial.println("Set speed in updates per second.");
} 
const TProgmemPalette16 myRedWhiteBluePalette_p PROGMEM =
{
    CRGB::Red,
    CRGB::Gray, // 'white' is too bright compared to red and blue
    CRGB::Blue,
    CRGB::Black,
    
    CRGB::Red,
    CRGB::Gray,
    CRGB::Blue,
    CRGB::Black,
    
    CRGB::Red,
    CRGB::Gray,
    CRGB::Blue,
    CRGB::Black, 

    CRGB::Red,
    CRGB::Gray,
    CRGB::Blue,
    CRGB::Black,
    
};

const TProgmemPalette16 myHalloweenPalette_p PROGMEM =
{
    CRGB::DarkOrange,
    CRGB::DarkOrange, 
    CRGB::Black,
    CRGB::Black,
    
    CRGB::DarkOrange,
    CRGB::DarkOrange,
    CRGB::Black,
    CRGB::Black,
    
    CRGB::DarkOrange,
    CRGB::DarkOrange,
    CRGB::Black,
    CRGB::Black,
    
    CRGB::DarkOrange,
    CRGB::DarkOrange,
    CRGB::Black,
    CRGB::Black
};

const TProgmemPalette16 myOregonDuckPalette_p PROGMEM =
{
    CRGB::Green,
    CRGB::Yellow, 
    CRGB::Green,
    CRGB::Yellow,
    
    CRGB::Green,
    CRGB::Yellow, 
    CRGB::Green,
    CRGB::Yellow,
      
    CRGB::Green,
    CRGB::Yellow, 
    CRGB::Green,
    CRGB::Yellow,
    
    CRGB::Green,
    CRGB::Yellow, 
    CRGB::Green,
    CRGB::Yellow,
};

const TProgmemPalette16 myChristmasPalette_p PROGMEM =
{
    CRGB::Red,
    CRGB::Green, 
    CRGB::Red,
    CRGB::Green,
    
    CRGB::Red,
    CRGB::Green, 
    CRGB::Red,
    CRGB::Green,
    
    CRGB::Red,
    CRGB::Green, 
    CRGB::Red,
    CRGB::Green,
    
    CRGB::Red,
    CRGB::Green, 
    CRGB::Red,
    CRGB::Green,
};

const TProgmemPalette16 mySoftLightingPalette_p PROGMEM =
{
    CRGB::Yellow,
    CRGB::Yellow, 
    CRGB::Yellow,
    CRGB::Yellow,
    
    CRGB::Yellow,
    CRGB::Yellow, 
    CRGB::Yellow,
    CRGB::Yellow,
    
    CRGB::Yellow,
    CRGB::Yellow, 
    CRGB::Yellow,
    CRGB::Yellow,
    
    CRGB::Yellow,
    CRGB::Yellow, 
    CRGB::Yellow,
    CRGB::Yellow,
};

void unrecognized(const char *command) {
  Serial.println("Bad Command");
}
// Additionl notes on FastLED compact palettes:
//
// Normally, in computer graphics, the palette (or "color lookup table")
// has 256 entries, each containing a specific 24-bit RGB color.  You can then
// index into the color palette using a simple 8-bit (one byte) value.
// A 256-entry color palette takes up 768 bytes of RAM, which on Arduino
// is quite possibly "too many" bytes.
//
// FastLED does offer traditional 256-element palettes, for setups that
// can afford the 768-byte cost in RAM.
//
// However, FastLED also offers a compact alternative.  FastLED offers
// palettes that store 16 distinct entries, but can be accessed AS IF
// they actually have 256 entries; this is accomplished by interpolating
// between the 16 explicit entries to create fifteen intermediate palette
// entries between each pair.
//
// So for example, if you set the first two explicit entries of a compact 
// palette to Green (0,255,0) and Blue (0,0,255), and then retrieved 
// the first sixteen entries from the virtual palette (of 256), you'd get
// Green, followed by a smooth gradient from green-to-blue, and then Blue.

### Debug Messages

C:\Users\Alex Kayl\Documents\Arduino\libraries\FastLED-master/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

Archiving built core (caching) in: C:\Users\ALEXKA~1\AppData\Local\Temp\arduino_cache_816424\core\core_esp8266_esp8266_nodemcuv2_CpuFrequency_160,UploadSpeed_115200,FlashSize_4M3M_c45c44664d4a342ceb6ee517316f4ef0.a
Sketch uses 248135 bytes (23%) of program storage space. Maximum is 1044464 bytes.
Global variables use 33936 bytes (41%) of dynamic memory, leaving 47984 bytes for local variables. Maximum is 81920 bytes.

**Comment by igrr** [comment]
It seems that FastLED library doesn't implement hardware SPI support for ESP8266 platform at the moment: https://github.com/FastLED/FastLED/blob/03d12093a92ee2b64fabb03412aa0c3e4f6384dd/fastspi.h

Closing as an issue about third party library.
