### ISSUE TITLE
ETS Timer won't work in class

### ISSUE THREAD

**Issue by nixmeer** [esp8266/Arduino#3885]
Hello :-)

I build a little PCB for the ESP 12 F that has 5 output drivers and 3 inputs for buttons. In order to use it to control 5 different lights, I tried to create one class called SingleColorLight which is supposed to be used to control one output. To smoothly dimm the light I am using a timer which changes the duty cycle of the PWM using the analogWrite() function. It keeps throwing errors when I try to include the class and compile it. Can anyone tell me why?

**The header file:**
#ifndef CSingleColorLight_h
#define CSingleColorLight_h
extern "C" {
  #include "user_interface.h" // Include to use ets_timer
}
class CSingleColorLight {
private:
    int pin;
    int intensitySetPoint;
    int intensityActual;
    int percentageBuffer;
    ETSTimer Dimmer;
    int dimmerCount;
public:
    CSingleColorLight(int _pin);
    bool setIntensity(int _intensity);
    int getIntensity(); 
    bool getStatus(void);
    bool setStatus(bool _status); 
    void DimmerCallback(void *pArg);
};
#endif

**The cpp-file:**
`#include "Arduino.h"
#include "SingleColorLight.h"
CSingleColorLight::CSingleColorLight(int _pin){
    if(_pin >= 0 && _pin <= 12) {
      pin = _pin;
      pinMode(pin, OUTPUT); 
      analogWriteRange(6250);
      analogWriteFreq(150);
      this->setIntensity(100);
      system_timer_reinit();
      ets_timer_setfn(&Dimmer, CSingleColorLight::DimmerCallback, NULL);
    }
    return;  
}

int CSingleColorLight::getIntensity(void) {
  return this->intensitySetPoint;
}

bool CSingleColorLight::setIntensity(int _intensity){
  if(_intensity < 0 || _intensity > 100) {
    return 0;
  }
  
  ets_timer_disarm(&Dimmer);
  dimmerCount = intensitySetPoint - intensityActual;
  ets_timer_arm_new(&Dimmer, 6250, true, false);
  
  return 1;
}

bool CSingleColorLight::getStatus(void) {
  if(this->intensitySetPoint > 0){
    //...
    return true;
  } else {
    //...
    return false;    
  }
}

bool CSingleColorLight::setStatus(bool _status){
  if(_status == true){
    if(setIntensity(100) == true){
      return 1;
    } else {
      return 0;
    }
  } else if (_status == false) {
    if(setIntensity(0) == true){
      return 1;
    } else {
      return 0;
    }
  } else {
    return 0;
  }
`}`
void CSingleColorLight::DimmerCallback(void *pArg) {
  if(dimmerCount>0){
    dimmerCount--;  
    intensityActual++;
  } else if(dimmerCount<0){
    dimmerCount++;
    intensityActual--;
  } else {
    ets_timer_disarm(&Dimmer);
  } 
  analogWrite(pin, percentageToTime[intensityActual]);
}`

Thank you a lot! 
Sorry, I was not able to use the "`", the code was not displayed properly

**Comment by devyte** [comment]
@nixmeer this is an issue tracker, meant to track issues in the core code hosted in this repo, and not a general support group. Please refer to a community forum for assistance with your specific application.
Closing per current issue policy.
