### ISSUE TITLE
Compile process and updates for Arduino IDE

### ISSUE THREAD

**Issue by ajitam** [esp8266/Arduino#389]
(please mark this issue as a question, this is not a bug)

I've been using ESP for a few week now and I have two (maybe stupid) questions.

## 1. Compile process

As far as I understand when you press upload in Arduino IDE the whole program is compiled into "image" (2 or 3 files) which is then uploaded to ESP. Does this mean that everything on the ESP is overwritten including firmware? I read a lot about upgrading the firmware to improve stability, but I don't understand if this is separate task or is it combined with program.

Which brings me to question number...

## 2. Arduino IDE ESP board extension

I installed ESP board with Board manager, what is the upgrade process? I can see that thing are being updated here on GitHub but how do I update on my computer? Do I remove the board and add it back? Or is the only way with 

```
$ git clone https://github.com/esp8266/Arduino.git
$ cd Arduino/build
$ ant dist
```

**Comment by marvinroger** [comment]
1. Yes, the whole firmware is flashed along with the sketch. So if you update your board platform packages and that the SDK has been updated there, then you benefit from the improvements it brings.

2. The GitHub version might not be stable. Releases considered as stable are available in the Board manager, you will see that there is a most up-to-date version in the GUI. [For now, the latest version is 1.6.4-673-g8cd3697.](https://github.com/esp8266/Arduino/blob/esp8266-sdk-1.0/hardware/esp8266com/esp8266/changes.md)
Note that there is also a [staging channel available](http://arduino.esp8266.com/staging/package_esp8266com_index.json), halfway between GitHub and stable.
If you want the most up-to-date version, from GitHub then yes, you have to build it yourself.

Finally, be aware that I am not a contributor here, these are just things I learned while following this repo. ;)
