### ISSUE TITLE
Can't connect to web server. 

### ISSUE THREAD

**Issue by czucker** [esp8266/Arduino#3897]
#### Hardware
Hardware:			ESP-12E

Hi,
I am having a trouble getting the simple web server, or any other web server, sketch working properly. 

It complies and uploads just fine, but I can't connect to the server in a browser. The connection times out. I can ping the IP with no issue. I ran nmap on the IP on port 80 and it is showing the port as filtered. 

I was tinkering with a DHT11 sensor earlier and think I did hook it up to pin 2 for a time. Is it possible that I changed the state of the pin and may be stuck in bootloader mode? I don't know much about microcontrollers, or programming in general, so it seems entirely possible that I unknowingly did something to damage/alter the board.

Any help would be greatly appreciated.

Thanks,
Chris

**Comment by devyte** [comment]
@czucker no basic info, no IDE settings, only a basic referral to a sketch. You pretty much ignored the entire issue template, which exists for good reasons.
Please provide more details about the hardware, about the build settings, and about the specific sketch to try.
Try erasing the entire flash first before flashing the sketch.

**Comment by devyte** [comment]
Closing due to lack of feedback.
