### ISSUE TITLE
EEPROM and retrieving data from arduino

### ISSUE THREAD

**Issue by Manali12** [esp8266/Arduino#3898]
-

#### Hardware
Hardware:			Arduino Uno R3, ESP8266 WiFi?

### Description

I am trying to gather sensor data and store it onto flash memory/EEPROM of the Arduino. So will my ESP8266 connected in the same circuit be able to read the data from the EEPROM of the Arduino board? If not, how do I go about doing this?

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

**Comment by devyte** [comment]
@Manali12 No. This core implements an Arduino-like api to run an application directly on thEe ESP. It doesn't implement specific communication with an Arduino board.
The EEPROM class emulates the AVR api on a sector in the on board flash. It has nothing to do with the EEPROM on the Arduino Uno.
This is not the right place to ask such questions, please refer to a community forum. 
Closing per issue policy doc.
