### ISSUE TITLE
Example code is missing

### ISSUE THREAD

**Issue by waynehuangplus** [esp8266/Arduino#392]
Hi,

After Arduino 1.6.4, you start using the "Boards Manager" way to install esp8266 package into arduino IDE. However, use this way won't install ESP8266 examples into Arduino IDE -> File -> Examples.

Is there is any way to make sure those example codes will be installed into IDE by "Boards Manager" method ?

Thanks,
Wayne

**Comment by Testato** [comment]
the example remain under the esp8266 core directory, under arduino15 directory, but the example appear under the IDE menu. 
But you must select an espboard BEFORE, and after you will find examples under the ide menu
