### ISSUE TITLE
Errorr espcomm ESP8266

### ISSUE THREAD

**Issue by koltipelto** [esp8266/Arduino#3929]
I'm having problem to upload the program, my conections is and I use usb-to-serial convertor:

![image](https://user-images.githubusercontent.com/34337151/33709635-10f4bdbc-db25-11e7-9a84-6793aba6eee8.png)

#### Hardware
Hardware:			ESP8266  12E

C:\Users\*****\Documents\Arduino\sketch_dec04b\sketch_dec04b.ino:34:24: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

 char* subscribeTopic = "MK-SmartHouse/lights/MK-LEDStripControl1"; 

                        ^

O sketch usa 260015 bytes (59%) de espaço de armazenamento para programas. O máximo são 434160 bytes.
Variáveis globais usam 37300 bytes (45%) de memória dinâmica, deixando 44620 bytes para variáveis locais. O máximo são 81920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

**Comment by devyte** [comment]
@koltipelto not the right place.to ask for help. This is an issue tracker for the core, not a support forum. Also, that error message is documented. You either have bad wiring or a dead module. From your drawing, I think it's bad wiring.
Closing per issue policy doc.

**Comment by koltipelto** [comment]
@devyte  Thanks a lot! Was a bad wiring! Sorry for the post!
