### ISSUE TITLE
Esp8266 reset with bulk update of more than 20 data points

### ISSUE THREAD

**Issue by Spirbel1** [esp8266/Arduino#3938]
#### Hardware
Hardware:			ESP-01
Core Version:      	2.1.0-rc2 - <- I am not sure

### Description

Basing on an example "updating bulk data to Thingspeak", I tried to upload 240 temperature values at the same time.
I was successful with uploading 20 data point in one request/message every 30seconds (or other desired upload rate). However, when I am trying to send more data points board resets. I checked connections, board is powered from power supply. I am also resetting watchdog. Could you please have a look and check what might be wrong?

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		512KB (4Mb)
CPU Frequency:		80Mhz
Flash Mode:			DIO
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		ck

### Sketch

#include<EthernetClient.h> //Uncomment this library to work with ESP8266
#include<ESP8266WiFi.h> //Uncomment this library to work with ESP8266

char jsonBuffer[500] = "["; // Initialize the jsonBuffer to hold data

int entries = 50;  
int counter = 0;

char ssid[] = "MotoG"; //  Your network SSID (name)
char pass[] = "Pablo123"; // Your network password
WiFiClient client; // Initialize the WiFi client library

char server[] = "api.thingspeak.com"; // ThingSpeak Server

/* SerialCollect data once every 15 seconds and post data to ThingSpeak channel once every 2 minutes */
unsigned long lastConnectionTime = 0; // Track the last connection time
//unsigned long lastUpdateTime = 0; // Track the last update time
const unsigned long postingInterval =60L * 1000L; // Post data every 20s
//const unsigned long updateInterval = 2L * 1000L; // Update once every 2 seconds

void setup() {
  Serial.begin(115200);
  // Attempt to connect to WiFi network
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(ssid);
    WiFi.begin(ssid, pass);  // Connect to WPA/WPA2 network. Change this line if using open or WEP network
    delay(10000);  // Wait 10 seconds to connect
  }
  
  Serial.println("Connected to wifi");
  printWiFiStatus(); // Print WiFi connection information
  
  ESP.wdtDisable();
  ESP.wdtEnable(WDTO_8S);
}

void loop() {
      
    if(counter < entries) {
    updatesJson(jsonBuffer);
    counter++;
    ESP.wdtFeed();
    }
    
   if (millis() - lastConnectionTime >=  postingInterval) {
        size_t len = strlen(jsonBuffer);
        jsonBuffer[len-1] = ']';
        httpRequest(jsonBuffer);
        ESP.wdtFeed();
    }

ESP.wdtFeed();   
}

void updatesJson(char* jsonBuffer){

  strcat(jsonBuffer,"{\"delta_t\":");
  unsigned long deltaT = 1;
  size_t lengthT = String(deltaT).length();
  char temp[4];
  String(deltaT).toCharArray(temp,lengthT+1);
  strcat(jsonBuffer,temp);
  strcat(jsonBuffer,",");
  long rssi = counter; 
  strcat(jsonBuffer, "\"field4\":");
  lengthT = String(rssi).length();
  String(rssi).toCharArray(temp,lengthT+1);
  strcat(jsonBuffer,temp);
  strcat(jsonBuffer,"},");
}

// Updates the ThingSpeakchannel with data
void httpRequest(char* jsonBuffer) {
   char data[500] = "{\"write_api_key\":\"C09SF5O3LDMCOIDO\",\"updates\":"; 
  strcat(data,jsonBuffer);
  strcat(data,"}");
  
  client.stop();
  String data_length = String(strlen(data)+1); //Compute the data buffer length
 
  if (client.connect(server, 80)) {
    client.println("POST /channels/374700/bulk_update.json HTTP/1.1");
    client.println("Host: api.thingspeak.com");
    client.println("User-Agent: mw.doc.bulk-update (Arduino ESP8266)");
    client.println("Connection: close");
    client.println("Content-Type: application/json");
    client.println("Content-Length: "+data_length);
    client.println();
    client.println(data);
  }
  else {
    Serial.println("Failure: Failed to connect to ThingSpeak");
  }
  delay(250); //Wait to receive the response
  client.parseFloat();
  String resp = String(client.parseInt());
  Serial.println("Response code:"+resp); // Print the response code. 202 indicates that the server has accepted the response
  jsonBuffer[0] = '['; // Reinitialize the jsonBuffer for next batch of data
  jsonBuffer[1] = '\0';
  lastConnectionTime = millis(); // Update the last connection time
  counter = 0;
}

void printWiFiStatus() {
  // Print the SSID of the network you're attached to:
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // Print your device IP address:
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  // Print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
}

### Debug Messages

Panic C:\Users\User\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\cores\esp8266\core_esp8266_main.cpp:133 loop_task

ctx: sys 
sp: 3ffffdd0 end: 3fffffb0 offset: 01b0

>>>stack>>>
3fffff80:  402154b2 3ffed7b0 00000000 3ffef8e0  
3fffff90:  00000000 3fffdad0 3ffef8cc 4020515d  
3fffffa0:  3ffe9e28 40000f49 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,4)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v00000000
~ld

**Comment by devyte** [comment]
@Spirbel1 240 values at the same time with a jsonBuffer[500]?? Yeah, no.
I see all sorts of wrong in your json string manipulation, including one local char[] that is likely too small to hold values. I strongly suggest using ArduinoJson instead of trying to do it yourself. And don't use a global staticJsonBuffer. Use a local dynamicJsonBuffer instead.
Closing as user error.
