### ISSUE TITLE
Error in SmartConfig when use  Events WiFi handler

### ISSUE THREAD

**Issue by tarzan115** [esp8266/Arduino#3951]
#### Hardware
Hardware:			`ESP-12E`
Core Version:      	`2.4.0-rc2`

### Description

I use the event handler to handle events wifi and use smartConfig to config SSID and pass. but when the device connected by using smartConfig, the app `Esptouch` cannot show the result.
if I use normal (not use events) the app `Esptouch` show successful the result.

### Settings in IDE

Module:  			`Generic ESP8266 Module`
Flash Size: 		`4MB/3MB`
CPU Frequency:		`80Mhz`
Flash Mode:			`dio`
Flash Frequency:	`40Mhz`
Upload Using:		`SERIAL`
Reset Method:		`ck`

### Sketch

```cpp

#include <Arduino.h>

static void
onWiFiConnected(const WiFiEventStationModeGotIP &event)
{
  Serial.println(F("WiFi Connected"));
  return;
}

static void
onWiFiDisconnected(const WiFiEventStationModeDisconnected &event)
{
  Serial.println(F("WiFi disconnected"));
}
void setup() {
  wifiConnectHandler = WiFi.onStationModeGotIP(onWiFiConnected);
  wifiDisconnectHandler = WiFi.onStationModeDisconnected(onWiFiDisconnected);
  WiFi.beginSmartConfig();
  while(1)
  {
    if (WiFi.smartConfigDone())
    return;
  }
}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by igrr** [comment]
The loop in your example,

```c++
  while(1)
  {
    if (WiFi.smartConfigDone())
    return;
  }
```

uses 100% CPU time, not allowing WiFi and TCP/IP stacks to process incoming packets. Please try again, adding `delay` or `yield` into the loop to allow for background processing.

Feel free to reopen if the issue is still present after this modification.
