### ISSUE TITLE
How to save second variable into flash

### ISSUE THREAD

**Issue by ted32** [esp8266/Arduino#3956]
Hi
This program is generating sine wave with regulated amplitude and phase by pressing the buttons, it's allow to save phase value but not amplitude value
Please  help me  save second value into flush.

#define SAMPLES 100

#define DEBOUNCE_DELAY 10

#define DEBOUNCE_IDLE 0
#define DEBOUNCE_ACTIVE 1

#include <libmaple/dma.h>
#include <EEPROM.h>

struct debounce_info
{
    int start, state;
    int16 shift;
}left, right, up, down;

dma_tube_config dma_cfg, dma_cfg2;

int flag1 = 0;
int flag2 = 0;

int out1 = PB7;           
int out2 = PA8;

int val1[SAMPLES];
int val2[SAMPLES];

int phasep = PB6;
int phasen = PB5;
int ampp = PB8;
int ampn = PB9;

int16 shift = 0;

int amp = 350;
int cnt = 0;
int time_track = 0;
float stp = 6.2831/SAMPLES;    
int ret = 17;

timer_dev *dev1 = PIN_MAP[out1].timer_device;
timer_dev *dev2 = PIN_MAP[out2].timer_device;
uint8 cc_channel1 = PIN_MAP[out1].timer_channel;
uint8 cc_channel2 = PIN_MAP[out2].timer_channel;

void fun()
{
    flag1++;
}

void fun2()
{
    flag2++;
}

void timer_conf()
{
  
  timer_dma_set_base_addr(dev1, TIMER_DMA_BASE_CCR2);
  timer_dma_set_burst_len(dev1, 1);
  timer_dma_enable_req(dev1, cc_channel1);
  timer_set_reload(dev1, 102);
  timer_set_prescaler(dev1, 0);
  
  timer_dma_set_base_addr(dev2, TIMER_DMA_BASE_CCR1);
  timer_dma_set_burst_len(dev2, 1);
  timer_dma_enable_req(dev2, cc_channel2);
  timer_set_reload(dev2, 102);
  timer_set_prescaler(dev2, 0);
}

void dma_conf()
{
    dma_init(DMA1);
    /* T4C2 DMA C4 */
    dma_cfg.tube_dst = &(dev1->regs.gen->DMAR);
    dma_cfg.tube_dst_size = DMA_SIZE_32BITS;
    dma_cfg.tube_src = val1;
    dma_cfg.tube_src_size = DMA_SIZE_32BITS;
    
    dma_cfg.tube_nr_xfers = SAMPLES;
    dma_cfg.tube_flags = DMA_CFG_SRC_INC | DMA_CFG_CIRC | DMA_CFG_CMPLT_IE;
    
    dma_cfg.tube_req_src = DMA_REQ_SRC_TIM4_CH2;
    dma_cfg.target_data = 0;
    
    ret = dma_tube_cfg(DMA1, DMA_CH4, &dma_cfg);
    
    /* T1C1 DMA C2 */
    dma_cfg.tube_dst = &(dev2->regs.gen->DMAR);
    dma_cfg.tube_dst_size = DMA_SIZE_32BITS;
    dma_cfg.tube_src = val2;
    dma_cfg.tube_src_size = DMA_SIZE_32BITS;
    
    dma_cfg.tube_nr_xfers = SAMPLES;
    dma_cfg.tube_flags = DMA_CFG_SRC_INC | DMA_CFG_CIRC | DMA_CFG_CMPLT_IE;
    
    dma_cfg.tube_req_src = DMA_REQ_SRC_TIM1_CH1;
    dma_cfg.target_data = 0;
    
    ret = dma_tube_cfg(DMA1, DMA_CH2, &dma_cfg);
}

void dma_start()
{
  dma_attach_interrupt(DMA1, DMA_CH4, fun);
    
  dma_enable(DMA1, DMA_CH4);
  timer_resume(dev1);
  
  dma_attach_interrupt(DMA1, DMA_CH2, fun2);
    
  dma_enable(DMA1, DMA_CH2);
  timer_resume(dev2);
}

void init_wave()
{
  int i;
  for(i=0;i<SAMPLES;i++)
  {
      val1[i] = 50 + amp/10.0 * sin(stp * i);
      val2[i] = val1[i];
  }
}

void get_wave(int16 shift)
{
  int i;
  for(i=0;i<SAMPLES;i++)
  {
      val2[i] = 50 + amp/10.0 * sin( stp * i + shift * 0.1 * 6.2831 / 360);
  }
}

void setup() {
  int i;
  pinMode(out1, PWM);
  pinMode(out2, PWM);
  pinMode(phasep, INPUT_PULLDOWN);
  pinMode(phasen, INPUT_PULLDOWN);
  pinMode(ampp, INPUT_PULLDOWN);
  pinMode(ampn, INPUT_PULLDOWN);
  
  memset(&left, 0, sizeof(debounce_info));
  memset(&right, 0, sizeof(debounce_info));
  memset(&up, 0, sizeof(debounce_info));
  memset(&down, 0, sizeof(debounce_info));
  
  left.shift = -1;
  right.shift = 1;
  up.shift = 1;
  down.shift = -1;
  
  Serial.begin(9600);

  timer_conf();
  dma_conf();
  dma_start();
  
  init_wave();
  EEPROM.read(0, (uint16*)&shift);
  get_wave(shift);
  
}

void loop() {
  process_key(digitalRead(phasep), &right);
  process_key(digitalRead(phasen), &left);
  process_key_amp(digitalRead(ampp), &up);
  process_key_amp(digitalRead(ampn), &down);
  delay(100);
  /*Serial.println(shift);
  EEPROM.write(0, shift);*/
}

void process_key(int val, struct debounce_info *k)
{
  switch(k->state)
  {
    case DEBOUNCE_IDLE:
      if(val == HIGH)
      {
        k->state = DEBOUNCE_ACTIVE;
        k->start = millis();
      }
      break;
        
    case DEBOUNCE_ACTIVE:
      if(val == HIGH)
      {
        if(millis() - k->start > DEBOUNCE_DELAY)
        {
          shift += k->shift;
          Serial.println("increasing");
          Serial.println(shift);
          Serial.println(k->shift);
          get_wave(shift);
          
        }
      }
      else
        k->state = DEBOUNCE_IDLE;
        EEPROM.write(0, shift);
        Serial.println(shift);
      break;
  }
}

void process_key_amp(int val, struct debounce_info *k)
{
  switch(k->state)
  {
    case DEBOUNCE_IDLE:
      if(val == HIGH)
      {
        k->state = DEBOUNCE_ACTIVE;
        k->start = millis();
      }
      break;
        
    case DEBOUNCE_ACTIVE:
      if(val == HIGH)
      {
        if(millis() - k->start > DEBOUNCE_DELAY)
        {
          amp += (int)k->shift;
          get_wave(shift);
        }
      }
      else
        k->state = DEBOUNCE_IDLE;
        
      break;
  }
}

**Comment by devyte** [comment]
@ted32 I suggest reading the docs for EEPROM. Don't forget to call EEPROM.commit() after you write a change to actually write it to flash.
This is not the right place to ask for help with your particular project. This is an issue tracker. Please refer to a community forum for help.
Closing per issue policy doc.
