### ISSUE TITLE
How to use ESP-01 Wi-Fi as fast as Bluetooth?

### ISSUE THREAD

**Issue by PeterPeterPan** [esp8266/Arduino#3964]
(my english is poor, I try my best to express my question.)

I want to use two ESP-01 to communicate as bluetooth. 
(one is AP another is STA, no need to connect to the same AP)

I try to use ESP-01 instead of arduino nano and HC-05.
But there are some problems.
I need to send data once by client in 20ms (or lower).
But it's working too slowly by ESP-01 Wi-Fi, from time to time will pause. (Seems to be random?)
What I did wrong? What can I do?

Here is my code.
STA code:
https://gist.github.com/anonymous/8c2d070ed0c7dd20902c2e1b5910a06b
AP code:
https://gist.github.com/anonymous/d1639972a4e0d179d34164f96a1b4a18

**Comment by devyte** [comment]
@PeterPeterPan no basic info, no IDE settinngs. You pretty much ignored the entire issuee template.
I'm going to assume that you used core 2.3.0. Try latest git, and build with lwip2 (menu option).

**Comment by PeterPeterPan** [comment]
I'm sorry...
and thank you very much.

2017-12-14 11:34 GMT+08:00 Develo <notifications@github.com>:
