### ISSUE TITLE
Check for current ADC_MODE

### ISSUE THREAD

**Issue by AndreKR** [esp8266/Arduino#3968]
Hardware: ESP-12F
Core Version: 2.3.0

As far as I know the ADC_MODE can only be configured once for the whole sketch. In a library I would like to use `ESP.getVcc()` *only if* the user has configured `ADC_MODE(ADC_VCC)`. Is there a way to check for that?

**Comment by devyte** [comment]
You have to set this once at the beginning of the sketch, and the ESP has to be restarted after setting.
I don't think there is a straightforward way of checking the current setting. I suspect it's possible to check a byte in the flash config. You'd have to read the Espressif SDK docs and do some research to figure it out. Be aware that the format of that flash space can change from release to release of the Espressif SDK.
Closing.
