### ISSUE TITLE
Arduino not displaying Library version correctly

### ISSUE THREAD

**Issue by dagnall53** [esp8266/Arduino#3969]
My arduino (ver 1.8.5)
displays: 
![image](https://user-images.githubusercontent.com/6950560/34000849-55f58e20-e0e6-11e7-9f2f-f3f9689b755b.png)
but I has 2.3 installed in my App directory..
is there something I need to do to get this to show the correct version number?

**Comment by Pablo2048** [comment]
You have posted image from Library Manager, not the Boards Manager...

**Comment by dagnall53** [comment]
Thanks... !
![image](https://user-images.githubusercontent.com/6950560/34005608-5dc4fdd6-e0f3-11e7-94d7-a394393b3976.png)

What is the difference-- if that is not a stupid question... I thought the Library showed code stuff and boards showed hardware.. 
So just what is the "1.0.0 Library".. and yes, nothing happens for me when I press more info.

**Comment by devyte** [comment]
One is a library, the other is the entire core.
Closing.
