### ISSUE TITLE
ESP8266-01 have not resppnding

### ISSUE THREAD

**Issue by aneequlhaq** [esp8266/Arduino#3986]
#### Hardware
Hardware:			?ESP-01?

Problem description
I connect the ESP8266-01 to ardunio mega ...
Ard RX to ESP TX
Ard TX to ESP RX
Ard Gnd to ESP Gnd
Ard 3.3 to ESP Vcc

by opening the serial monitor send the AT commands they shwo nothing sometimes they show random numbers like 65,10......

**Comment by vdeconinck** [comment]
You're at the wrong place. This github repository is about a firmware that allows you to use the ESP8266 with the Arduino IDE, but without involving actual Arduino hardware. This firmware is an alternative to the firmware implementing AT commands that comes pre-flashed in most ESP modules.
Moreover, this issue tracker is for fixing bugs inside the firmware and not for usage questions.
Please close this issue at direct your questions on forums such as esp8266.com or stackoverflow.
