### ISSUE TITLE
Udp.destinationIP() always resets ESP8266 when not connected

### ISSUE THREAD

**Issue by tonton81** [esp8266/Arduino#3989]
Udp.destinationIP() crashes the ESP8266 every time it's used when not connected to UDP

**Comment by devyte** [comment]
@tonton81 no Basic info, no IDE Settings, no example sketch. You ignored the entire issue template, which exists for a reason.
Which core version? Try with latest git, and build with lwip2 (option in menu).

**Comment by tonton81** [comment]
latest git version, 1.8.3 IDE, lwip2

**Comment by devyte** [comment]
@d-a-v maybe similar to the availableForWrite() crash?

**Comment by tonton81** [comment]
indeed, i was in a middle of a project going through the library functions one at a time, i guess i just stumbled onto them :)

**Comment by igrr** [comment]
@tonton81 Created https://github.com/esp8266/Arduino/pull/4036 to fix this.
