### ISSUE TITLE
Not connecting to WiFi on access points

### ISSUE THREAD

**Issue by ojek** [esp8266/Arduino#3994]
I have bought 2 cheap devkit modules from china (https://www.banggood.com/Geekcreit-Doit-NodeMcu-Lua-ESP8266-ESP-12E-WIFI-Development-Board-p-985891.html?cur_warehouse=CN). One of them works like a charm, the other one... Is weird:

- It works as a wifi webserver
- It connects to my smartphone wifi (when I set up my phone to act as an access point)
- It does not connect to my local network. And I have bought a new access point thinking my old one was broken (turns out the devkit is misbehaving somehow)

Could you please help me out debugging this? It's very weird as the wifi module is clearly functional, yet it's not connecting to home APs for some weird reason. I am pasting my codes below, though these are pretty standard (and they work on the other devkit so I know they are correct).

```
WiFi.mode(WIFI_STA);
for (int i = 0;;++i)
{
    Serial.println("WiFi connecting...");
    Serial.println(WiFi.status());
    if (WiFi.status() == WL_CONNECTED) break;
    if (i%30==0) WiFi.begin(ssid, password);
    delay(1000);
}
Serial.println("WiFi connected!");
```

**Comment by devyte** [comment]
@ojek you ignored the entire issue template.
Given that one module works and the other other doesn't, it's likely that you have a bad module, or bad configuration. I suggest erasing the entire flash with esptool, then reflash your sketch.
Not the right place to request help. Please refer to a community forum.
Closing per issue policy doc.
