### ISSUE TITLE
UpdaterClass::printError() should accept Print class

### ISSUE THREAD

**Issue by puuu** [esp8266/Arduino#4007]
[`UpdaterClass::printError()`](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Updater.cpp#L374) required a Stream object, but only use the Print class subset. Please change `Stream` to `Print`, to enable debugging to other Print objects that are not inherit from Stream.

**Comment by ijm7** [comment]
Hi, is anyone doing this? I would like to look into it.

**Comment by devyte** [comment]
@ijm7 afaik, not at this time, so go ahead. If you make a pr, I'll review it.

**Comment by ijm7** [comment]
Just realised that this issue is still sitting open, it should probably be closed.

**Comment by d-a-v** [comment]
fixed by #4117, thanks!
