### ISSUE TITLE
case WPS_CB_ST_UNK:

### ISSUE THREAD

**Issue by BTCable** [esp8266/Arduino#4023]
Arduino: 1.8.5 (Windows 10), Плата:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp: In function 'void wifi_wps_status_cb(wps_cb_status)':

C:\Program Files (x86)\Arduino\libraries\ESP8266WiFi\src\ESP8266WiFiSTA.cpp:623:14: error: 'WPS_CB_ST_UNK' was not declared in this scope

         case WPS_CB_ST_UNK:

              ^

exit status 1

Full code
-------------------------------------------
`
// This example shows how to connect to Cayenne using an ESP8266 and send/receive sample data.
// Make sure you install the ESP8266 Board Package via the Arduino IDE Board Manager and select the correct ESP8266 board before compiling. 

//#define CAYENNE_DEBUG
#define CAYENNE_PRINT Serial
#include <CayenneMQTTESP8266.h>

// WiFi network info.
char ssid[] = "HomeWifi";
char wifiPassword[] = "**";

// Cayenne authentication info. This should be obtained from the Cayenne Dashboard.
char username[] = "**";
char password[] = "**";
char clientID[] = "**";

unsigned long lastMillis = 0;

void setup() {
  Serial.begin(9600);
  Cayenne.begin(username, password, clientID, ssid, wifiPassword);
}

void loop() {
  Cayenne.loop();
}

// Default function for sending sensor data at intervals to Cayenne.
// You can also use functions for specific channels, e.g CAYENNE_OUT(1) for sending channel 1 data.
CAYENNE_OUT_DEFAULT()
{
  // Write data to Cayenne here. This example just sends the current uptime in milliseconds on virtual channel 0.
  Cayenne.virtualWrite(0, millis());
  // Some examples of other functions you can use to send data.
  //Cayenne.celsiusWrite(1, 22.0);
  //Cayenne.luxWrite(2, 700);
  //Cayenne.virtualWrite(3, 50, TYPE_PROXIMITY, UNIT_CENTIMETER);
}

// Default function for processing actuator commands from the Cayenne Dashboard.
// You can also use functions for specific channels, e.g CAYENNE_IN(1) for channel 1 commands.
CAYENNE_IN_DEFAULT()
{
  CAYENNE_LOG("Channel %u, value %s", request.channel, getValue.asString());
  //Process message here. If there is an error set an error message using getValue.setError(), e.g getValue.setError("Error message");
}
`

**Comment by igrr** [comment]
Verified that this is not an issue in the latest git. 
`WPS_CB_ST_UNK` is declared in tools/sdk/include/user_interface.h, which is included into ESP8266WiFiSTA.cpp.

The error might be caused by a corrupted installation. Suggest removing the ESP8266 package, restarting the IDE, and installing a new one from scratch. Please reopen if the issue is still preset after a fresh install.
