### ISSUE TITLE
Detect Audio Input 

### ISSUE THREAD

**Issue by jannnfe** [esp8266/Arduino#4025]
Hello,
I've been looking for days for a way to build an audio in sensor. I want to connect to a Wemos D1 mini or other esp module an audio port and send with ESPEasy a MQTT command, if at the audio input signal has been detected. does anyone know a component with which this is possible?
Thanks

**Comment by devyte** [comment]
In theory, a fast implementation of ADC read could read audio. Alternatively, something I2S relay could. However, I have yet to see a workable implementation.

Closing per issue policy doc.
