### ISSUE TITLE
ESP8266 VERY HIGH current consumption about 160mA even when in deep sleep! 

### ISSUE THREAD

**Issue by eldonjakee08** [esp8266/Arduino#4030]
Hi guys! I've recently bought a nodemcu board from banggood and I've noticed that when in deep sleep it still has a very high current consumption about 130mA and it sets the chip quite warm too. Also I've noticed that whenever I power the nodeMCU with just the battery the esp8266 runs the sketch just fine. But whenever I connect a multimeter in series with the battery to Vin of the nodeMCU (to measure the current consumption) it won't run the sketch and reads a very high current consumption even when in deep sleep, current consumption is at 130mA. I thought I had a broken multimeter at first so I just bought a new multimeter and did the same test but still the same results the sketch just wont run when a multimeter is in series with the battery. I also tried disconnecting the regulator I disconnected its ground pin but still the same results. Any ideas as to what might be causing this? .... Thanks in advance!! :D (Photos shown underneath)

and here is the test sketch that I uploaded into the board.

`extern "C" {
#include "user_interface.h" // this is for the RTC memory read/write functions
}

// defines pins numbers for ultrasonic
const int trigPin = 5; //D1
const int echoPin = 4; //D2

int sensor_read;
long duration;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  pinMode(trigPin, OUTPUT); // Sets the trigPin as an Output
  pinMode(echoPin, INPUT); // Sets the echoPin as an Input
  system_rtc_mem_read(64, &sensor_read, 4); //reads previous sensor reading stored in RTC memory
   Serial.println("");
  Serial.print("Past Sensor Reading: ");
  Serial.println(sensor_read);
  
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  // Calculating the distance
  sensor_read= duration*0.034/2;
  Serial.print("Actual Read: ");
  Serial.println(sensor_read);
  system_rtc_mem_write(64, &sensor_read, 4); //writes present sensor reading stored in RTC memory
  delay(10);
  system_rtc_mem_read(64, &sensor_read, 4); //reads present sensor reading stored in RTC memory
  Serial.print("Present Sensor Reading: ");
  Serial.println(sensor_read);

  Serial.println("Going Back to Sleep!");
  ESP.deepSleep(5e6); //sleeps for 5 seconds
  delay(100);
  //just a test to see if it did sleep properly, if it did not sleep it would print this out to serial.
  Serial.print("olkpko");

}

void loop() {
  // put your main code here, to run repeatedly:

}`

![p_20171227_203900](https://user-images.githubusercontent.com/33694277/34382316-ec3c1fd6-eb48-11e7-8a22-d90c6c8ac63a.jpg)
**Figure 1.1 The nodeMCU board**

![p_20171227_204303](https://user-images.githubusercontent.com/33694277/34382864-884a76b8-eb4c-11e7-90b0-6325d725c1d2.jpg)
**Figure 1.2 Here I'm measuring the current consumption of the board currently consuming 130mA**

![p_20171227_204316](https://user-images.githubusercontent.com/33694277/34382866-8891ca54-eb4c-11e7-9670-c2cfb7db85b3.jpg)
**Figure 1.3 measuring current shown at a different angle**

![p_20171227_204943](https://user-images.githubusercontent.com/33694277/34382867-88ed3c9a-eb4c-11e7-9f11-74ff24c9ba95.jpg)
**Figure1.4 The sketch would run just good if I just connect the board directly to the battery, without the multimeter in between them.**

![p_20171227_205549](https://user-images.githubusercontent.com/33694277/34382868-895828a2-eb4c-11e7-9675-dba88ed56ae2.jpg)
**Figure 1.5 Here I disconnected the GND pin of the regulator to see if there would be any changes to the current consumption but still shows the same high curretnt.**

**Comment by liebman** [comment]
I see other items connected in the circuit as well...  Have you tried with them removed?

This is probably not the right place to ask for help with your particular project. This is an issue tracker. Please refer to a community forum for help.

**Comment by devyte** [comment]
@eldonjakee08 sounds like an electrical issue, and not a code issue. I suggest:
-Erasing the entire flash with esptool
-doing a clean install to make sure you are building with the correct core
-eliminate the protoboard and test deepsleep with just the nodemcu without any other hardware

This is not the right place to ask what's wrong with your particular project. Please refer to a community forum for help.
Closing per issue policy doc

**Comment by eldonjakee08** [comment]
oh I'm so sorry!! and thanks so much for the suggestions! :D

**Comment by torntrousers** [comment]
@eldonjakee08 I've found that it often doesn't work using cheap multimeters with just a 200ma range connected in series with the ESP during power on. I think its because the ESP has quite a high burst of current at power on an with the 200ma range the multimeter doesn't let enough current be drawn and so the ESP crashes, and the 130ma current you see is what the ESP draws in its crashed state. One way I've got around this is to short the multimeter probes together for power on and then once the ESP is up and running you can break the short and the ESP keeps running and the multimeter can measure the current.

**Comment by eldonjakee08** [comment]
right right!!!!! thank you so much for the enlightenment!!! :D :D

**Comment by eldonjakee08** [comment]
thank you so much! it works now!!!! :D :D
