### ISSUE TITLE
Small issue with UdpContext.h comment

### ISSUE THREAD

**Issue by markusb** [esp8266/Arduino#4041]
The last line of the file ESP8266WiFi/src/include/UdpContext.h reads 

    #endif//CLIENTCONTEXT_H

instead of 

    #endif//UDPCONTEXT_H

While technically irrelevant it would be nice to be fixed.

**Comment by d-a-v** [comment]
If you make a pull-request I guess it will be merged.

**Comment by gchungsy** [comment]
Hi, I just made a pull-request.

**Comment by devyte** [comment]
Fixed via #4068 .
