### ISSUE TITLE
Si4703 library doesn't work with NodeMCU v3 (exit status1, compiling error)

### ISSUE THREAD

**Issue by elektor18** [esp8266/Arduino#4046]
Hi,
I tried to upload adafruits example for Si4703 but it dosn't want work. I have tried diffrent examples for that module but non of them works. 
I have modified clock and data pin but still geting error during compiling 

"C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/include" "-IC:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0/tools/sdk/lwip/include" "-IC:\Users\LENOVO\AppData\Local\Temp\arduino_build_6224/core" -c  -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10805 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_NODEMCU"  -DESP8266 "-IC:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266" "-IC:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\variants\nodemcu" "-IC:\Users\LENOVO\Documents\Arduino\libraries\src" "-IC:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\Wire" "C:\Users\LENOVO\AppData\Local\Temp\arduino_build_6224\sketch\Si4703_Radio_Test.ino.cpp" -o "C:\Users\LENOVO\AppData\Local\Temp\arduino_build_6224\sketch\Si4703_Radio_Test.ino.cpp.o"
In file included from C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/Arduino.h:38:0,

                 from C:\Users\LENOVO\AppData\Local\Temp\arduino_build_6224\sketch\Si4703_Radio_Test.ino.cpp:1:

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:24:31: error: expected unqualified-id before 'volatile'

 #define ESP8266_DREG(addr) *((volatile uint32_t *)(0x3FF00000+(addr)))

                               ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:38:19: note: in expansion of macro 'ESP8266_DREG'

 #define CHIPID    ESP8266_DREG(0x58)

                   ^

C:\Users\LENOVO\Documents\Arduino\libraries\src/SparkFunSi4703.h:82:25: note: in expansion of macro 'CHIPID'

  static const uint16_t  CHIPID = 0x01;

                         ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:24:31: error: expected ')' before 'volatile'

 #define ESP8266_DREG(addr) *((volatile uint32_t *)(0x3FF00000+(addr)))

                               ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:38:19: note: in expansion of macro 'ESP8266_DREG'

 #define CHIPID    ESP8266_DREG(0x58)

                   ^

C:\Users\LENOVO\Documents\Arduino\libraries\src/SparkFunSi4703.h:82:25: note: in expansion of macro 'CHIPID'

  static const uint16_t  CHIPID = 0x01;

                         ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:24:31: error: expected ')' before 'volatile'

 #define ESP8266_DREG(addr) *((volatile uint32_t *)(0x3FF00000+(addr)))

                               ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:38:19: note: in expansion of macro 'ESP8266_DREG'

 #define CHIPID    ESP8266_DREG(0x58)

                   ^

C:\Users\LENOVO\Documents\Arduino\libraries\src/SparkFunSi4703.h:82:25: note: in expansion of macro 'CHIPID'

  static const uint16_t  CHIPID = 0x01;

                         ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:24:30: error: expected ';' at end of member declaration

 #define ESP8266_DREG(addr) *((volatile uint32_t *)(0x3FF00000+(addr)))

                              ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:38:19: note: in expansion of macro 'ESP8266_DREG'

 #define CHIPID    ESP8266_DREG(0x58)

                   ^

C:\Users\LENOVO\Documents\Arduino\libraries\src/SparkFunSi4703.h:82:25: note: in expansion of macro 'CHIPID'

  static const uint16_t  CHIPID = 0x01;

                         ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:24:50: error: expected unqualified-id before ')' token

 #define ESP8266_DREG(addr) *((volatile uint32_t *)(0x3FF00000+(addr)))

                                                  ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:38:19: note: in expansion of macro 'ESP8266_DREG'

 #define CHIPID    ESP8266_DREG(0x58)

                   ^

C:\Users\LENOVO\Documents\Arduino\libraries\src/SparkFunSi4703.h:82:25: note: in expansion of macro 'CHIPID'

  static const uint16_t  CHIPID = 0x01;

                         ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:24:49: error: expected ';' at end of member declaration

 #define ESP8266_DREG(addr) *((volatile uint32_t *)(0x3FF00000+(addr)))

                                                 ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:38:19: note: in expansion of macro 'ESP8266_DREG'

 #define CHIPID    ESP8266_DREG(0x58)

                   ^

C:\Users\LENOVO\Documents\Arduino\libraries\src/SparkFunSi4703.h:82:25: note: in expansion of macro 'CHIPID'

  static const uint16_t  CHIPID = 0x01;

                         ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:24:50: error: expected unqualified-id before ')' token

 #define ESP8266_DREG(addr) *((volatile uint32_t *)(0x3FF00000+(addr)))

                                                  ^

C:\Users\LENOVO\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\cores\esp8266/esp8266_peri.h:38:19: note: in expansion of macro 'ESP8266_DREG'

 #define CHIPID    ESP8266_DREG(0x58)

                   ^

C:\Users\LENOVO\Documents\Arduino\libraries\src/SparkFunSi4703.h:82:25: note: in expansion of macro 'CHIPID'

  static const uint16_t  CHIPID = 0x01;
----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description

### Settings in IDE

Module:  			?Generic ESP8266 Module?
Flash Size: 		?4MB/1MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by devyte** [comment]
@hotchpotch I just took a quick look at the lib, and it doesn't seem to be ported to work on the ESP8266. The error comes from a name clash: our code uses a #define CHIPID macro, their lib uses a static const member variable called CHIPID.
They are violating C++ good practices by using all uppercase for their member variables. They should be using e.g.: camelcase. In contrast, our #defines come from a C-style low-level layer for naming hardware registers, hence the old-style all-uppercase naming convention.
I supposed the above could be debated, and somebody could argue that we could modify our code to make it work. However, what I find unpresentable is that they declared the registers inside the class in the .h, which means the whole thing gets dragged along to every place the .h is #included, causing name clashes with other .h as has happened here. Given the class interface, its implementation in the .cpp, and their provided example ino, I see *absolutely no reason* to expose the register definitions to the user. In fact, I would think that the whole point of the class is to hide all of that! The register definitions should be moved to the .cpp, and put in an anonymous namespace.

I suggest you open an issue in their repo requesting modification to allow interoperability with our code. Either move the register definitions to the .cpp, or at least rename them. Better yet, do both. Or, you can implement it yourself, test it, and do a PR for them.

Closing due to unsupported 3rd party lib with bad design.
