### ISSUE TITLE
Wifi AP SSID Doc Issue

### ISSUE THREAD

**Issue by timpur** [esp8266/Arduino#4067]
In the wifi AP doc there seems to be an error.

https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/soft-access-point-class.html#softap

> ssid - character string containing network SSID (max. 63 characters)

Isn't the max 32 char ? Think this is meant for the password?

**Comment by gicho** [comment]
SSID is different to MAC address - here ssid variable means pointer to
string (text) that is the network name. This name (ssid) is broadcasted by
the AP and you see it as network name on your device (smartphone, PC,
etc.). The MAC address is not designed to be randomly defined by users - it
is allocated by HW manufacturers (and sometimes overriden by developers).
But certified devices need to have a constant, pre-defined one.
For example:
const char ssid[] = "MyNewHotspot";

2018-01-01 23:47 GMT+02:00 timpur <notifications@github.com>:

**Comment by timpur** [comment]
@gicho I didn't mention mac?

**Comment by gicho** [comment]
"Isnt the mac 32 char ? Think this is meant for the password?"

2018-01-02 0:20 GMT+02:00 timpur <notifications@github.com>:

**Comment by timpur** [comment]
My bad meant to be "max", sorry.

**Comment by earlephilhower** [comment]
Fixed via #5325
