### ISSUE TITLE
Exception on NodeMCU 1.0

### ISSUE THREAD

**Issue by majenkotech** [esp8266/Arduino#407]
I had just got my NodeMCU 1.0 working in UECIDE when I pulled the latest changes from here.  Ever since then it's been failing.

I get an exception 0 at 0x402032ec with a blank sketch (empty setup and loop functions).

That address has:

    402032ec:	fffe61        	l32r	a6, 402032e4 <user_uart_wait_tx_fifo_empty+0x3cc>

There is no 0x402032e4 in the program. It's partway though an instruction:

    402032e0:	f00d      	ret.n
    402032e2:	880000        	excw
    402032e5:	ff2c      	movi.n	a15, 47
    402032e7:	3f          	.byte 0x3f

That's all in the `user_uart_wait_tx_fifo_empty` function in libmain.a

Like... wtf is going on here?

Has something changed with the compilation commands recently?

**Comment by Links2004** [comment]
please retry in last release, If it still a problem feel free to reopen.
