### ISSUE TITLE
arduino-esp8266.upload.resetmethod=ck missing in boards.txt

### ISSUE THREAD

**Issue by jandrassy** [esp8266/Arduino#4074]
2.4 release
esptool v0.4.12 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to {upload.resetmethod}
error: unknown board: {upload.resetmethod}
known boards are: none ck wifio nodemcu 

And the CPU frequency should not be selected in menu. The 'arduino' boards have 80 MHz esp8266.

**Comment by d-a-v** [comment]
True. 
This is also true for gen4iod oak wifinfo.
Fix is coming.
For the record current boards.txt is generated from #3722.

**Comment by d-a-v** [comment]
@jandrassy please take and check the file from #3722 (original post, link "latest") until a solution is found to fix current release.

**Comment by jandrassy** [comment]
of course I added the line into my installation and I modified the [instruction in Uno WiFi Wiki](https://github.com/jandrassy/UnoWiFiDevEdSerial1/wiki/Programming-ESP8266) yesterday.

I googled the 160 MHz and I see it is set by software. If I select 160 MHz in IDE will the arduino 8266 core set the frequency?

**Comment by d-a-v** [comment]
> If I select 160 MHz in IDE will the arduino 8266 core set the frequency?

yes

**Comment by d-a-v** [comment]
Fixed by #3722.
