### ISSUE TITLE
ESP8266 after restart or power on/off not work

### ISSUE THREAD

**Issue by karenYerevan** [esp8266/Arduino#4087]
hi there
i have ESP8266-12, it is have other power
I flashing esp8266 from arduino uno
Flashing programm (XTCOM_UTIL)
aruduino uno -- esp8266
RX -> RXD
TX -> TXD
GND -> GND,GPIO0

After flashing all AT commands worck good.
But when esp8266 is restart (AT+RST) , AT commands stopping works
and show this text

> AT
> OK
> 
> AT+RST
> OK
> 
> ets Jan 8 2013,rst cause:4, boot mode:(1,7)
> wdt reset

![img_0291](https://user-images.githubusercontent.com/9501068/34561557-1521af44-f164-11e7-81f2-155d42965c54.jpg)

who can help me ???

**Comment by igrr** [comment]
Hi @karenYerevan, this issue tracker is for bugs and feature requests related to esp8266 Arduino core and libraries. You are using AT commands application, which is out of scope for this repository.
