### ISSUE TITLE
get ssid with WiFiEventSoftAPModeProbeRequestReceived

### ISSUE THREAD

**Issue by hASVAN** [esp8266/Arduino#4093]
### Basic Infos

Core Version:      	2.4.0-rc1

### Description

can't find any code that can get  SSIDs of the networks that the devices are looking for with WiFiEventSoftAPModeProbeRequestReceived
### Settings in IDE

Module: Generic ESP8266 Module
Flash Size: 4MB (1M SPIFFS)
CPU Frequency:	80Mhz
Flash Mode:	dio
Flash Frequency:	40Mhz
Upload Using:	SERIAL
Reset Method:	nodemcu

### Sketch

```cpp

#include <ArduinoJson.h>
#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <ESP8266HTTPClient.h>
#include <vector>

const char* apSsid     = "ap-ssid";
const char* apPassword = "ap-password";
const char* clientSsid     = "client-ssid";
const char* clientPassword = "client-password";

HTTPClient http;

WiFiEventHandler probeRequestPrintHandler;

String macToString(const unsigned char* mac) {
  char buf[20];
  snprintf(buf, sizeof(buf), "%02x:%02x:%02x:%02x:%02x:%02x",
           mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
  return String(buf);
}

std::vector<WiFiEventSoftAPModeProbeRequestReceived> myList;

void onProbeRequestPrint(const WiFiEventSoftAPModeProbeRequestReceived& evt) {
  myList.push_back(evt);
}

void setup() {
  Serial.begin(115200);
  Serial.println("Hello!");

  // Don't save WiFi configuration in flash - optional
  WiFi.persistent(false);

  WiFi.mode(WIFI_AP_STA);
  WiFi.softAP(apSsid, apPassword);
  WiFi.begin(clientSsid, clientPassword);
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(100);
  }
  Serial.println("");
  probeRequestPrintHandler = WiFi.onSoftAPModeProbeRequestReceived(&onProbeRequestPrint);
}

void loop() {
  delay(3000);
  String json = "";
  DynamicJsonBuffer jsonBuffer;
  JsonObject& root = jsonBuffer.createObject();
  JsonArray& probes = root.createNestedArray("probes");
  for(WiFiEventSoftAPModeProbeRequestReceived w : myList){
    JsonObject& probe = probes.createNestedObject();
    probe["address"] = macToString(w.mac);
    probe["rssi"] = w.rssi;
  }
  myList.clear();
  root.printTo(json);
  Serial.println("json:" + json);

  http.begin("http://example.com/api/v1/probe%22);
  http.addHeader("Content-Type", "application/json");
  http.POST(json);
  http.end();
}
```

**Comment by devyte** [comment]
@hASVAN I don't understand your description. You said: 

> get SSIDs of the networks that the devices are looking for

but then your code shows onSoftAPModeProbeRequestReceived().

If you mean other stations probing the ESP's SoftAP:
A probe request is a frame sent by a wifi station to an accesspoint requesting info. When a station, such as your cell phone wifi, probes an ESP's SoftAP, the callback set by WiFi.onSoftAPModeProbeRequestReceived() is triggered. This is what the sketch above does.
There are no SSIDs involved. The arguments are the mac of the station requesting the probe and the rssi.

If you mean the ESP's Station probing other APs:
I don't think probing is available. There is scanning, though. There are code examples for this packaged with the core libs.

In either case, this issue looks off topic per current issue policy.
Closing.

As a side note, the sketch above looks correct, except for one thing: don't use delay(3000), but poll millis() instead.
