### ISSUE TITLE
itoa() function not found

### ISSUE THREAD

**Issue by marcoschwartz** [esp8266/Arduino#41]
I have a sketch that uses the itoa() function, and I got the error when compiling:

```'itoa' was not declared in this scope```

Is this function already included in the project? Thanks!

**Comment by igrr** [comment]
It was included yesterday:
https://github.com/Links2004/Arduino/blob/esp8266/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_noniso.c#L102

**Comment by marcoschwartz** [comment]
Cool! But that's not yet merged into the main repository right?

**Comment by igrr** [comment]
It's not in the release yet, yes.
But you can download the release, clone this git repository, and then replace the contents of **hardware/esp8266com** directory with the contents of the same directory from git.

**Comment by marcoschwartz** [comment]
Got it, thanks!

**Comment by igrr** [comment]
And yeah, it's merged actually:
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/cores/esp8266/core_esp8266_noniso.c#L110

**Comment by marcoschwartz** [comment]
Yeah, works! I just needed to include:

#include "stdlib_noniso.h"
