### ISSUE TITLE
ESP8266 after restart or power on/off.  does not worked 

### ISSUE THREAD

**Issue by karenYerevan** [esp8266/Arduino#4100]
hi there
i have ESP8266-12, it is have other power
I flashing esp8266 from arduino uno
Flashing programm (XTCOM_UTIL)
aruduino uno -- esp8266
RX -> RXD
TX -> TXD
GND -> GND,GPIO0

After flashing all AT commands worck good.
But when esp8266 is restart (AT+RST) , AT commands stopping works
and show this text

> AT
> OK
> 
> AT+RST
> OK
> 
> ets Jan 8 2013,rst cause:4, boot mode:(1,7)
> wdt reset

![img_0291](https://user-images.githubusercontent.com/9501068/34629719-aaabf9e2-f282-11e7-84e6-1c49171e2251.jpg)

**Comment by devyte** [comment]
@karenYerevan you were already advised in #4087 that this is not the AT command firmware repo. The code here has nothing to do with the AT command set.
Closing.

**Comment by karenYerevan** [comment]
what's the difference, any sketch I fill is the same, well I'll open it yet but there will not be written about at. and i hope you will not close my issue

**Comment by devyte** [comment]
@karenYerevan the difference is that this is an issue tracker for issues in our Arduino core libs. We're not a general support forum, and this is not the right place to request help for your particular project. Please read our issue POLICY doc.
