### ISSUE TITLE
SPIFFS BROKEN ON NEW ESP-01 BOARDS

### ISSUE THREAD

**Issue by ondabeach** [esp8266/Arduino#4102]
#### Hardware
Hardware:			esp-01
Core Version:      	2.4.0

### Description
******************************IF YOU USE SPIFFS*********************************
*************************IN A COMMERCIAL PRODUCT**************************
****************************THIS WILL AFFECT YOU******************************
**********************NEW FLASH CHIP HAS KILLED SPIFFS*********************

It seems the Chinese generic esp-01 board makers have switched to chip manufacturer PUYA as the supplier of their flash chips. I have bought from 3 different suppliers and they are all using the PUYA chip now.

I now have 75 esp-01 boards that I can't use.

Module: Generic ESP8266 Module
 Flash Size: 1MB (64k SPIFFS)
 CPU Frequency: 80Mhz
 Flash Mode: QIO
 Flash Frequency: 40Mhz
 Upload Using: SERIAL
 Reset Method: ck

Any sketch you try will fail to write to SPIFFS if you have a new module with the PUYA flash chip on it.

The only thing "Arduino" I've found that can write to SPIFFS is the "Upload Sketch Data" plug in. A sketch can then read the uploaded files, but it will fail to write any data to SPIFFS.

This is a link to the new flash chip from PUYA.
http://www.puyasemi.com/attached/file/20171027/20171027183954_35795.pdf

Unless your supplier still has some has old stock then the chances are that any new esp-01 module out of China will not support SPIFFS. I imagine that many other modules will also start using these flash chips so this is quickly going to become a major issue for a lot of people.

**Comment by devyte** [comment]
Same issue as #3616 , tracking there. Closing this one.
