### ISSUE TITLE
Sketch using Timezone-Lib will not compile in v2.4.0

### ISSUE THREAD

**Issue by digi-thomas2003** [esp8266/Arduino#4106]
#### Hardware
Hardware:			NodeMCU 1.0
Core Version:      	2.4.0

### Description

Any sketch using the Timezone-library from JChristensen will not compile with 2.4.0
There are lots of "... is not declared in this scope" errors referencing to the Timezone lib

Going back to 2.3.0 the compilations run fine without any error.

Can this please be checked? Thanks a lot.

Best regards

**Comment by 5chufti** [comment]
most likely a problem with your includes (sequence of).
without your sketch not reproducable
BUT: why use third party TZlib when newlibc allready supports TZ stuff?

**Comment by digi-thomas2003** [comment]
Hello Schufti (and d-a-v),

is there a kind of documentation about the newlibc and the supported time, TZ and DST functions?
Sorry, if this may be a silly question.

Thank you.

**Comment by 5chufti** [comment]
one can find the newlib documentation here
https://sourceware.org/newlib/libc.html

so since your - not core related - problem is solved, may you please close this issue?

**Comment by digi-thomas2003** [comment]
as desired

**Comment by digi-thomas2003** [comment]
#4122
