### ISSUE TITLE
example with webserver and client on the same device

### ISSUE THREAD

**Issue by juanmol** [esp8266/Arduino#411]
Hi, i think it's needed an example for serving webs (server) and performs gets or posts to other device (client) at the same time on the same device.

**Comment by M0ebiu5** [comment]
Does not work for me - i get a watchdog reset after some minutes.
I have a webserver running for the configuration and a "WiFiClient" to send status info to a server.

**Comment by Links2004** [comment]
you can combine ```ESP8266WebServer``` and ```httpClient```.

please retry in last release, 
If it still a problem feel free to reopen.
