### ISSUE TITLE
ESP is only reachable from one device

### ISSUE THREAD

**Issue by arget888** [esp8266/Arduino#4116]
### Hardware 
Hardware: ESP-01
Core-Version: Where do i find the core-version?

### Description
Hi,
I have implemented a small webservice to controll a temperature and humidty sensor and a strip of ws2812b leds. I connect the ESP to my router. Now it starts to get strange. I receive an IP Adresse of the DHCP server but the DHCP server does not show the connected device (all other connected device are displayed like my iPad or my iPhone or my Mac). Over the Serial Port i can read the IP-Address. It is 10.0.0.48 with is in range of dhcp service and all settings like dns, subnet, gateway are also correct. On my iMac i can connect to my webservice but not with all other devices.
I'm using the latest code version installed yesterday threw arduino ide.
 I used the ESP earlier as AP  and connected from Mac, can this be a reason?
What can i do that the esp is reachable from other devices in network?
The PC which is working is behind a lan switch, could this be a problem, i have a small 4 port switch before my router!

### Settings in IDE
![bildschirmfoto 2018-01-07 um 22 25 03](https://user-images.githubusercontent.com/3680955/34654265-a1ee93d2-f3f9-11e7-9d2f-6e682fd039ee.png)

### Sketch
```cpp
#include <ESP8266WiFi.h>
#include <WiFiClient.h> 
#include <ESP8266WebServer.h>
#include "DHT.h"

#define DHTPIN         0
#define DHTTYPE        DHT22

const char *ssid = "*********";
const char *password = "**********";

ESP8266WebServer server(80);
DHT dht(DHTPIN, DHTTYPE);

String lastState = "";
float humidity = 0.0, temperature = 0.0,heatIndex = 0.0;

void handleRoot() 
{
  Serial.println("Handle Root!!");
	server.send(200, "text/html", "<h1>You are connected!</h1>");
}

void getTemperature()
{
  Serial.println("Get Temperature and Humidity!!");
  server.sendHeader("Access-Control-Allow-Origin","*");
  server.send(200, "application/json","{\"temperature\": "+ String(temperature,1)+", \"humidity\": "+String(humidity,0)+"}");
}
void setup() {
  Serial.begin(9600);

  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
  
  int status = WiFi.waitForConnectResult();

  int status = WiFi.waitForConnectResult();
  if(status != WL_CONNECTED)
  {
      //do Something
  }
  else
  {
    //do something
  }

  server.on("/", handleRoot);
  server.on("/temperature", getTemperature);

  server.begin();

  
  Serial.println("Connected.");
  Serial.print("MAC: ");
  Serial.println(WiFi.macAddress());
  Serial.print("IP:  ");
  Serial.println(WiFi.localIP());
  Serial.print("Subnet: ");
  Serial.println(WiFi.subnetMask());
  Serial.print("Gateway: ");
  Serial.println(WiFi.gatewayIP());
  Serial.print("DNS: ");
  Serial.println(WiFi.dnsIP());
  Serial.print("Channel: ");
  Serial.println(WiFi.channel());
  Serial.print("Status: ");
  Serial.println(WiFi.status());
}

void loop() {
	server.handleClient();

       //refresh LED's

  if((millis() - stop) > 2000)  //every 2 seconds
  {
    humidity = dht.readHumidity();
    temperature = dht.readTemperature();
    
    if (isnan(humidity) || isnan(temperature)) {
      lastState = "Failed to read from DHT sensor!";
      return;
    }
    else lastState = "OK!";
    
    heatIndex = dht.computeHeatIndex(temperature, humidity, false);
    
    stop = millis();
  }
}
```

### Debug Messages
Thats the console output from start and open the root (http://10.0.0.48/)
![bildschirmfoto 2018-01-07 um 22 26 38](https://user-images.githubusercontent.com/3680955/34654277-e78ab6e6-f3f9-11e7-9166-db1d73d8367e.png)

**Comment by devyte** [comment]
@arget888 when you opened the issue, you were presented with an issue template requesting certain information. You have ignored most of it. Please edit your post and add what was requested, or close this issue and correctly open a new one.

**Comment by devyte** [comment]
Also, make sure to include all relevant info, including a complete and minimal sketch, which the above is not.

**Comment by arget888** [comment]
Updated, i hope all needed infos are given

**Comment by d-a-v** [comment]
Can you try the included example sketch HelloServer (File>Examples>ESP8266WebServer>HelloServer) and see if it works better with your router ?
Can you try change your lines around WL_CONNECTED according to this example ?
The core version is showed where you got the "latest code version installed yesterday".
Are you sure you don't have two dhcp servers on your network ? Usually dhcp servers addresses end with .1 or .254, you have .138 which is perfectly legal but unusual.

**Comment by arget888** [comment]
I flashed the HelloServer Example, the result is the same. I know that .128 is not ideal for a router but that was the standard setting from my providers router and i have no need to change that. I also disconnected all other devices from my router (all devices where added by cabel) but the result is the same. The mdns service is also not working, on my iMac i can call the HelloServer site by IP - Adress but not by the name ("esp8266.local").
The version of my library says 1.0.0!

All of my devices have same settings with ip-range, subnet, router and dns server so there should be just one dhcp server running, that would be very confusing if two server has exact the same (unusual) dhcp settings and i did not have a problem with it until now with the esp

**Comment by d-a-v** [comment]
Have you tried with another mDNS or bonjour browser that could scan your network ?
(an android app for example)

**Comment by devyte** [comment]
@d-a-v are you thinking of the compressed dns thing?

**Comment by d-a-v** [comment]
@devyte I don't know, it seems the opposite (here the "dns server" would be the esp).

@arget888 
> I used the ESP earlier as AP and connected from Mac, can this be a reason?

So your router used to show the ESP before that ?

Can you try with the latest version of esp8266/arduino core by removing it and reinstalling with git ([link](https://github.com/esp8266/Arduino#using-git-version)) ?

**Comment by Pablo2048** [comment]
IMHO this is same problem which we have solved here https://github.com/me-no-dev/ESPAsyncWebServer/issues/259 - it seems like @arget888 has his MAC connected via wire and his AP has set AP isolation. @arget888 please try to connect your MAC via Wifi and try to access ESP server. If this fails you need to disable AP isolation in your WiFi AP.

**Comment by devyte** [comment]
Closing due to lack of feedback and age.
