### ISSUE TITLE
Reading from multiple pins give false values

### ISSUE THREAD

**Issue by p1ng54** [esp8266/Arduino#4128]
Hardware:			NodeMcu 1.0 "ESP-12"
Core Version:      	

### Description
Ive connected  nodemcu pins 5,6,7,8 which corresponds to GPIO 14,12,13,15 respectively to read analogue values problem is that when I get all high or all low it reads 0. following code is used for all 4 pins 

### Settings in IDE

Module:  			NodeMcu
Flash Size: 		4MB
CPU Frequency:	80Mhz
Flash Mode:		Using Arduino IDE
Reset Method:		nodemcu

void loop() {
 int count;
  do 
    {
      count++;
      DvcStts = digitalRead(D6);
      Serial.println("DvcStts = " + (String)DvcStts);
    
      delay(100);
      deviceStatus01 = digitalRead(D6);

      Serial.println("deviceStatus01 = " + (String)deviceStatus01);

      if(deviceStatus01 != DvcStts){
        Serial.print("Error in D01 Reading: ");

        Serial.println(count);

      }
    }while(deviceStatus01 != DvcStts);

}

**Comment by dragondaud** [comment]
You cannot "read analogue values" from digital IOs. Also, you do not provide a complete sketch demonstrating the issue, nor a do you provide a explanation of how your hardware is configured or what was connected to the pins. This issue board is for handling specific issues for the ESP8266 Arduino core, and is not a general assistance forum. You may be better served at http://www.esp8266.com/index.php

**Comment by devyte** [comment]
@p1ng54 how exactly do you expect to read analogue values with digitalRead()?

**Comment by devyte** [comment]
Closing due to lack of info.
