### ISSUE TITLE
Set MAC address?

### ISSUE THREAD

**Issue by vshymanskyy** [esp8266/Arduino#413]
I know how to get the MAC address:

    unsigned char mac[6];
    WiFi.macAddress(mac);

Is there any way to set it?
In the AT firmware, there are commands for this, so I think it should be possible:

    AT+CIPSTAMAC=mac
    AT+CIPAPMAC=mac

**Comment by chadouming** [comment]
This is not an issue, ask your question in relevant part of the forum : [Forum](http://www.esp8266.com/viewforum.php?f=25&sid=f82e14927b91bb1b964c93878ef5b1c5)

**Comment by vshymanskyy** [comment]
Actually it was meant as a feature request, as I didn't find anything like that (I looked into the code).
Sorry if I missed something...

**Comment by igrr** [comment]
This isn't implemented currently, but SDK has the ```wifi_set_macaddr``` function to set MAC addresses. There is a limitation though — this function has to be called early at startup, before setup() method is run. So it's not clear how to make this feature available through Arduino APIs. AT firmware saves the new MAC to EEPROM and restart, if I remember correctly.

**Comment by vshymanskyy** [comment]
Thanks for a quick reply! Could we do it the same way, so for example it would change the MAC in the EEPROM, to be applied after restart (no need to restart immediately).

**Comment by sunnyhighway** [comment]
I don't think wifi_set_macaddr would cause a reboot, because (according to the SDK programming guide) it returns true or false depending on succes or failure to do so.

It would be pointless to return anything at all if it would cause a reboot, would it?

**Comment by Links2004** [comment]
with my change it shut work like this:
```cpp
extern "C" void __run_user_rf_pre_init(void) {
    uint8_t mac[] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05};
    wifi_set_macaddr(SOFTAP_IF, &mac[0]);
}
```

**Comment by ikin77** [comment]
Hi, does anybody knows why I do get this compiling error?

   undefined reference to `wifi_set_macaddr(unsigned char, unsigned char*)'

I've used 

#include <user_interface.h>
....

byte mac[6];
.... // Set mac value....
WiFi.macAddress(mac);
wifi_set_macaddr(STATION_IF, mac);
....

**Comment by luc-github** [comment]
did you add ?
```
extern "C" {
#include "user_interface.h"
}
```

**Comment by ikin77** [comment]
@luc-github 
Thanks!!!! I just did "#include <user_interface.h>"

Now I can compile :o) Thanks again!!

**Comment by ikin77** [comment]
Hi. I can now change MAC address as STA and SOFAP. When I check on my router's page, I can see the MAC address, buy I can see the different devices names as "ESP-XXXX"

![router](https://cloud.githubusercontent.com/assets/12951016/11873585/8ee6e27c-a4db-11e5-98aa-47e070d40665.png)

Can it be changed? I do I do it? Thanks again!!

**Comment by Links2004** [comment]
add:
```cpp
WiFi.hostname("your name");
```
before ```WiFi.begin(...);```

**Comment by vogtitec** [comment]
@ikin77 
Could you please give a more complete example, WHERE in a sketch you put these lines of code into to change the MAC address of the unit? 
byte mac[6];
.... // Set mac value....
WiFi.macAddress(mac);
wifi_set_macaddr(STATION_IF, mac);
....
I tried it in Links2004's example with
extern "C" void __run_user_rf_pre_init(void) ...
but I get a compile error as "previous declaration of 'void __run_user_rf_pre_init()' with 'C++' linkage" ...

Thanks a lot!

**Comment by ikin77** [comment]
Hi. Tomorrow morning I'll post the sample code.

Best regards.

**Comment by ikin77** [comment]
Hi. Herer's my code:

     // Set as SoftAP and client
      WiFi.mode(WIFI_AP_STA);       
      
     // Change MAC 
     byte *mac = (byte*)malloc(6);
     WiFi.macAddress(mac);
     mac[0] = 0x19;
     mac[1] = 0x14;
     mac[2] = 0xCA;
     wifi_set_macaddr(STATION_IF, mac);
     mac[2] = 0xCB;
      wifi_set_macaddr(SOFTAP_IF, mac);
      free(mac);

In my sample code I read the original MAC and I change only some bytes. Yo can change others or all or them.

Best regards,

**Comment by vogtitec** [comment]
Thank you very much for your example!
By the way, did you succeed in changing the hostname as proposed by Links2004 ? I tried it but nothing seems to be changed ?!

**Comment by ikin77** [comment]
I couldn't change the hostnamed, the suggested solution doesn't seems to make any difference. Maybe were not using the function at the right moment, I don't know :o/

**Comment by Links2004** [comment]
you need to call it before the DHCP request is made.
may direct after  setup.
```cpp
setup() {
    Serial.begin(115200);
    WiFi.hostname("your_name");
    //.......
}
```

**Comment by Duality4Y** [comment]
for setting a hostname you need to run a dhcp server somewhere.

**Comment by Links2004** [comment]
@Duality4Y I think you mean:
the DHCP server needs to "add" the names to the DNS server.
the DHCP server itself does not response to a DNS request ;)

**Comment by Duality4Y** [comment]
yes sorry that is correct.

**Comment by vshymanskyy** [comment]
It looks it got broken at some point...
```
extern "C" {
  #include "user_interface.h"
}

void initVariant() {
  wifi_set_macaddr(STATION_IF, &mac[0]);
}
...
...
  Serial.println(WiFi.macAddress());
```
And I get the original MAC of the module. The router also shows the original MAC.

**Comment by yoursunny** [comment]
I've posted a complete example of changing MAC and hostname in my blog:
<https://yoursunny.com/t/2017/change-ESP8266-MAC/>

Setting MAC and hostname can be placed in `setup()` function before `WiFi.begin`. No need to `initVariant`.

**Comment by IMAN4K** [comment]
`main.ino:`
```c++
extern "C" void preinit() {
	uint8_t sta_mac[] = { 0xb4, 0xe6, 0x2d, 0x44, 0x86, 0xad };
	wifi_set_opmode(STATIONAP_MODE);
	wifi_set_macaddr(STATION_IF, sta_mac);
}
```
Worked in `core 2.4.2 + ESP12E`

**Comment by sepp89117** [comment]
extern "C" void preinit() {
  uint8_t ap_mac[] = {0xD8, 0x96, 0x85, 0x03, 0x04, 0x05};
  wifi_set_opmode(SOFTAP_MODE);
  wifi_set_macaddr(SOFTAP_IF, ap_mac);
}

Worked for me in core 2.5.2 + ESP-12E for SoftAP

**Comment by happytm** [comment]
Is it possible to dynamically change mac bytes in code by replacing byte with temperature,humidity and pressure sensor values  read from BME280 that way Raspberry running monitor mode can capture these sensor values?

Thanks

**Comment by sepp89117** [comment]
hi, why do you want to do that? 
Please describe your project.

**Comment by happytm** [comment]
Basically I am trying to create adhoc network of esp devices (battery powered) to send sensor values to raspberry pi for further processing these value.I donot want to use time consuming TCP protocol to save power.My goal is to have esp device wake up from deep sleep every 15 minutes, read BME280 sensor, dump sensor values into fake MAC id ,do probe request and go back to sleep.On other side raspberry pi is always on and receive this probe request,save these sensor data in database and  publish values via MQTT.


Thanks

**Comment by sepp89117** [comment]
In that case I would have used a 433Mhz interface.  With a transmitter in the Arduino transfer the data and listen with the Pi simply.
But if you want to stay with your hardware setup, did you try the code above?
Try wifi_set_macaddr in your action. Theoretically, it should work.

**Comment by happytm** [comment]
I want to go with only ESP device for hardware simplicity.Yes I will try wifi_set_macaddr.

Thanks

**Comment by happytm** [comment]
I was able to create ad-hoc network between 2 ESP8266 devices and I can exchange 6 bytes of data between 2 devices reliably in about 200 milliseconds. I am using:
int n = WiFi.scanNetworks(true, true, 7); 
to scan all aps with channel 7 which shows up with 4 AP's in my vicinity.

To reduce the time it takes to scan few AP's (60 millisecponds) I want to scan only one known AP with known SSID. 

Is there any way I can do it ?

Thanks
