### ISSUE TITLE
Handle Espressif's removal of mesh support

### ISSUE THREAD

**Issue by devyte** [esp8266/Arduino#4130]
#### Hardware
Hardware:			all
Core Version:      	        2.4+

### Description

Espressif has removed support for their mesh lib, which means that the lib won't exist starting from their upcoming v2.2 SDK release.
When we migrate to SDK v2.2, we'll need to pull libmesh and update the build system, or freeze the current libmesh, with the understanding that it may become incompatible in the future.

**Comment by yoursunny** [comment]
I don't see how *ESP8266WiFiMesh* library relates to `libmesh`.
*ESP8266WiFiMesh* is implemented on top of *ESP8266WiFi*: each node establishes an AP, and sends message to another node by connecting to its AP.
I searched for `espconn_mesh_create_packet`, a function provided by `libmesh`, and didn't find anything in this repository.

**Comment by devyte** [comment]
@yoursunny updated description.

**Comment by devyte** [comment]
The libmesh is already removed in one of the SDK updates. Closing.
