### ISSUE TITLE
lwip/tcp_impl.h missing in 2.4.0

### ISSUE THREAD

**Issue by DoXer67** [esp8266/Arduino#4133]
Hardware:			ESP-12 - NodeMCU V3 (LoLin)
Core Version:      	2.4.0

Hi,
I get this error after switching from 2.4.0-RC2 to 2.4.0:
/home/michael/Arduino/ESPEasy/ESPEasy.ino:295:27: fatal error: lwip/tcp_impl.h: No such file or directory
 #include "lwip/tcp_impl.h"

**Comment by d-a-v** [comment]
It will compile if you choose lwip v1.4 in menu.
ESPEasy needs an update for it to work with lwip v2.

**Comment by devyte** [comment]
Closing a fix is needed in 3rd party repo and not here.
