### ISSUE TITLE
xtensa-lx106-elf Binaries

### ISSUE THREAD

**Issue by weswitt** [esp8266/Arduino#4141]
Where do the xtensa-lx106-elf binaries come from? I know that the Windows package can be downloaded from this Guthub project, but the package is missing the gdb binary. I've seen various posts that refer to the https://github.com/kireevco/esp-alt-sdk github project that project is a few years old and there are no xtensa-lx106-elf binaries available on that site.

So I'm specifically looking for the gdb binary for xtensa-lx106-elf.

**Comment by earlephilhower** [comment]
Closed, we're building them ourselves and GDB is now available for Windows.
