### ISSUE TITLE
View specific wrong password error upon connecting to network

### ISSUE THREAD

**Issue by L0laapk3** [esp8266/Arduino#4152]
Suggestion for future versions: make a new status() output to specifically reflect wrong password.

https://github.com/esp8266/Arduino/blob/ca250687339659f336157509202f57c2612c8cf6/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp#L493

Of course, it is possible to call wifi_station_get_connect_status() from user_interface.h, but it would be cleaner if this was possible with ESP8622WiFi.h.

**Comment by tablatronix** [comment]
I thought the SDK never exposed this

**Comment by devyte** [comment]
This could actually be a breaking change depending on howna user checks return value. Pushing back to v3.
