### ISSUE TITLE
nodemcu send text file as json

### ISSUE THREAD

**Issue by bigelite** [esp8266/Arduino#4156]
### Basic Infos
Nodemcu send text file as json
#### Hardware
Hardware:			ESP-32

### Description

Problem description
hi everyone, i'm new user in ESP32, i want to send text file as JSON in the fast way. Is there anyway to convert the file contains some records like this: 0001,2000/01/01,00:38:01,315.00,FSK,0AC0, to JSON
and send it to android devices?

**Comment by devyte** [comment]
This is not the ESP32 repo, and in any case, an issue tracker is not the right place to ask such questions. I suggest you refer to a community forum for assistance, like esp8266.com.
Closing per issue POLICY doc.
