### ISSUE TITLE
2.4.0 incorrectly reports WL_CONNECTED immediately after WiFi.mode(WIFI_STA), without waiting for WiFi.begin() or a successful connection.

### ISSUE THREAD

**Issue by Rob58329** [esp8266/Arduino#4166]
Hardware:			D1-mini
Core Version:      	Arduino-IDE(v1.8.5) with ESP8266-board-software-version 2.4.0
                                [IwIP Variant: v2 Prebuilt (both MSS=536 and MSS=1460)]

Problem description
--------------------
After successfully connecting using "WiFi.mode(WIFI_STA)".  If you then disconnect using   "WiFi.disconnect()"  & "WiFi.mode(WIFI_OFF)", and finally try to reconnect again starting with  "WiFi.mode(WIFI_STA)", then "WiFi.status()" reports "WL_CONNECTED" immediately after the "WiFi.mode(WIFI_STA)" (ie. long before it has connected).  It then continues to say "WL_CONNECTED" up until you issue the "WiFi.begin(ssid, password)" command (at which point it starts to correctly say "WL_DISCONNECTED" again).

This means it is not possible to reliably use "while (WiFi.status()!=WL_CONNECTED)" to check for or initiate a "WiFi.begin" command or similar.

(Note that v2.3.0 and v2.4.0-rc2 seemed to correctly report "WL_DISCONNECTED" or "WL_IDLE_STATUS" right up until the connection was successfully re-established.)

(This seems to be different to the issue reported in #4161.)

Example Sketch
----------------

#include <ESP8266WiFi.h>
const char* ssid     = "your_ssid";
const char* password = "your_password";

void setup() {
  Serial.begin(74880); delay(3000);
  Serial.print("About to start:"); display_status();

  WiFi.mode(WIFI_STA);
  Serial.print("WiFi.mode(WIFI_STA):"); display_status(); // correct here gives: "WiFi.status()=WL_DISCONNECTED"
  WiFi.begin(ssid, password);
  Serial.print("WiFi.begin:"); display_status();
  wait_connection();
  Serial.print("WiFi connected: "); display_status();
  Serial.println("--------------------");delay(5000);

  WiFi.disconnect(); delay(5);
  Serial.print("WiFi.disconnect: "); display_status();
  WiFi.mode(WIFI_OFF); delay(5);
  Serial.print("WiFi.mode(WIFI_OFF): "); display_status();
  WiFi.forceSleepBegin(); delay(1); 
  Serial.print("WiFi.forceSleepBegin: "); display_status();
  Serial.println("--------------------");delay(5000);
  
  WiFi.forceSleepWake(); delay(1); 
  Serial.print("WiFi.forceSleepWake: "); display_status();
  WiFi.mode(WIFI_STA); delay(5); 
  Serial.print("WiFi.mode(WIFI_STA):"); display_status(); // error here gives: "WiFi.status()=WL_CONNECTED"
  Serial.println("**NB. I beleive the above should NOT return 'WL_CONNECTED'**");
  Serial.println("(when used with D1-Mini and Arduino-IDE-with-ESP8266-board-sw-v2.4.0)");
  Serial.println("--------------------");delay(5000);

  Serial.print("After Delay:"); display_status();
  WiFi.begin(ssid, password);
  Serial.print("WiFi.begin:"); display_status();
  wait_connection();
  Serial.print("WiFi connected: "); display_status();
  Serial.println("--------END---------");
}

void loop() {}

void wait_connection() {while (WiFi.status()!=WL_CONNECTED) {Serial.print(".");delay(500);}}

void display_status() {
  byte x=WiFi.status(); Serial.print(" WiFi.status()=");
  if      (x==WL_CONNECTED) Serial.println("WL_CONNECTED");
  else if (x==WL_DISCONNECTED) Serial.println("WL_DISCONNECTED");
  else if (x==WL_CONNECT_FAILED) Serial.println("WL_CONNECT_FAILED");
  else if (x==WL_NO_SSID_AVAIL) Serial.println("WL_NO_SSID_AVAIL");
  else if (x==WL_IDLE_STATUS) Serial.println("WL_IDLE_STATUS");
  else Serial.println(x);
}

**Comment by d-a-v** [comment]
Could you please try again with lwip v1.4 in Tools>menu ?
If the issue disappears, could you please retry with lwip v2 and latest git version of core ?

**Comment by Rob58329** [comment]
d-a-v: Thankyou for suggestion!..
(1)  Iwip v1.4 WORKS CORRECTLY (and gives "WiFi.status()=WL_IDLE_STATUS" after the "WiFi.mode(WIFI_STA)")
(2) It will take me some time to figure out how to use the latest git version (I've only ever used the IDE-board-manager before)...

**Comment by pidloop** [comment]
Where is the IDE menu to try lwip 1.4? My Tools menu does not show anything related that I can see (maybe I'm blind). I've attached a screen grab. I'm using IDE 1.8.5 on macOS. Thanks.


<img width="864" alt="screen shot 2018-01-14 at 21 21 32" src="https://user-images.githubusercontent.com/12057700/34927101-fa90876c-f970-11e7-9ab2-c1bf588191ae.png">

**Comment by d-a-v** [comment]
@pidloop The menu appeared in the core release 2.4.0.
For the time beeing, it would be better to install the git version though: [link](https://github.com/esp8266/Arduino#using-git-version)

**Comment by pidloop** [comment]
Ok, now I see it. And yes, using "1.4 Prebuilt" solves the problem, everything seems to work fine now. When Huzzah looses connection WiFi.status() returns to WL_DISCONNECTED then back to CONNECTED automatically when connection returns. In my real sketch it also seems to transfer much faster now also, maybe wishful thinking?? Only downside is I notice my sketch is now about 30 kB larger but that is not a big deal. Many thanks.

**Comment by d-a-v** [comment]
@pidloop 30kBytes larger seems a big lot! If this is confirmed, please open a new issue.
@Rob58329 If all is OK then can you please close the issue ?

**Comment by Rob58329** [comment]
I can confirm that as well as working under  Iwip v1.4, this issue is also fixed in the github clone 14Jan18 to Commit ca25068 using IwIP Variant: v2 Prebuilt (both MSS=536 and MSS=1460).

(ie. gives "WiFi.status()=WL_IDLE_STATUS" as it should after the "WiFi.mode(WIFI_STA)")

Many thanks!
