### ISSUE TITLE
question about eeprom esp8266

### ISSUE THREAD

**Issue by kakaducsy** [esp8266/Arduino#4178]
Hi all
Im using esp8266 node mcu 12E v1
I checked lib eeprom esp8266 at : https://github.com/esp8266/Arduino/blob/master/libraries/EEPROM/EEPROM.cpp
I dont see command : EEPROM.get() and EEPROM.put()
But when I use : EEPROM.get() and EEPROM.put() 
It still work

`Serial.print("EEPROM contents at Address=0 is  : ");
  float floatingpoint_variable = 0;
  EEPROM.get(EEaddress,floatingpoint_variable);
  Serial.println(floatingpoint_variable,8);
  EEaddress = EEaddress + sizeof(float); `
why ??
Should I use 2 command this for esp8266 ?

**Comment by devyte** [comment]
You're looking at the implementation (I.e. the cpp), when you should be looking at the interface (I.e. the .h). In EEPROM.h you'll see templated get and put methods.
Closing as user error.
