### ISSUE TITLE
ESP8285 wifi direct

### ISSUE THREAD

**Issue by stern0m1** [esp8266/Arduino#4180]
Is there specific support for the ESP8285?
The datasheet for ESP8285 mentions it implements Wifi Direct. Did the arduino library implement it?
Where can I find more information about implementing wifi direct with the ESP8285?
Thanks

**Comment by igrr** [comment]
No, there's not support for WiFi direct in Arduino. It's not exposed in the underlying ESP8266 Non-OS SDK either, as far as i can tell.

**Comment by stern0m1** [comment]
![image](https://user-images.githubusercontent.com/18012839/35026264-f901d736-fb17-11e7-98fd-6e8f840cb3af.png)
What does the datasheet mean by wifi direct? 
Is the underlying sdk the same for ESP8285 as esp8266?

**Comment by igrr** [comment]
1) no idea about that, sorry. Please ask on bbs.espressif.com.

2) yes, the SDK is the same

**Comment by Androbin** [comment]
Someone seems to have done it:
https://github.com/youmebangbang/esp8266-wifi-direct-examples
