### ISSUE TITLE
feature request: WiFi.mode(WIFI_AP_STA) / server.send()

### ISSUE THREAD

**Issue by Marcianikus** [esp8266/Arduino#4182]
In  WiFi.mode(WIFI_AP_STA) when the server.send() function is used, the same message is sent to all connected clients in AP and STA.

It could be interesting the possibility of sending independent messages to the AP or the STA connected clients
exmple: server.**send_AP** ()  /   server.**send_STA** ()

A more generic possibility: server.send (200,"text/html", "message", **IPAddress ip**)

**Comment by jandrassy** [comment]
isn't server.send a response to the current http request from one client?

**Comment by devyte** [comment]
I can't think of a use case for this. Also, there has been no interest by others since this was opened.
Closing. 
If you still think the request has merit, please open a new issue, follow the template instructions, and explain the use case in detail.
