### ISSUE TITLE
Change request : SPIFFS autoformat on mount failure

### ISSUE THREAD

**Issue by vdeconinck** [esp8266/Arduino#4185]
This issue to discuss the opportunity to change the default behaviour of SPIFFS mount() and begin().

In the current implementation, if the mounting filesystem fails, the API silently formats the filesystem and mounts it - empty.

Pro: after mount, the programmer is guaranteed to have a mounted filesystem

Con: if the chip is defective, or the API has a bug, or the FS has been formated with incompatible configuration, data gets lost without a warning. This is also contrary to the default behaviour chosen for ESP32

I would suggest to adopt the same convention as the ESP32: SPIFFS.begin() should accept an optional "formatOnFail" parameter, defaulting to false.

This would be breaking change (albeit in the direction of safety), so I guess it would have to be targeted to the next major version,

References: 
https://github.com/esp8266/Arduino/issues/2581#issuecomment-358132613
https://github.com/esp8266/Arduino/issues/4111#issuecomment-355855993
https://github.com/espressif/arduino-esp32/issues/411#issuecomment-329017296

**Comment by devyte** [comment]
@igrr do we want to change this to match the esp32 behavior? If yes, then this should likely be targetd for 3.0.0 release.

**Comment by earlephilhower** [comment]
#5525 will fix this, adding to tracking here.

**Comment by earlephilhower** [comment]
Removing @igrr since this should be in the next revision (with the changes already in a PR).

**Comment by earlephilhower** [comment]
Fixed in #5525 , there are now config helpers to `setAutoFormat(bool)` for filesystems.
