### ISSUE TITLE
client.read(buf,sizeof(buf));

### ISSUE THREAD

**Issue by tonton81** [esp8266/Arduino#4206]
Just tested running a read while disconnected and ESP crashes with error 28.
The crash results in a total lockup until hard reset.
If i connect and then read(buffer,size), it's fine. This may be linked to several libraries having the same error code on core 2.4 that use wificlient.

Tony

**Comment by devyte** [comment]
@tonton81 there was a fix already merged that may be related. Please retest with latest master.
