### ISSUE TITLE
SPIFFS.begin (on WeMos D1 mini Pro) cause device hang.

### ISSUE THREAD

**Issue by bestpika** [esp8266/Arduino#4237]
#### Hardware

Hardware: `WeMos D1 mini Pro`
Core Version: 8a24598d5dbf46effc5ac9189224601950736a70

### Description

After flash, device can't work.
I think this device is hanging.

I use `esptool flash_id` check this device.

```txt
esptool.py v2.3-dev
Connecting....
Detecting chip type... ESP8266
Chip is ESP8266EX
Uploading stub...
Running stub...
Stub running...
Manufacturer: ef
Device: 4018
Detected flash size: 16MB
Hard resetting...
```

### Settings in IDE

This setting, device can't work
Module: `WeMos D1 mini Pro`
Flash Size: `16M (15M SPIFFS)`
CPU Frequency: `80Mhz`
Upload Using: `Serial`

This setting, device can work.
Module: `WeMos D1 R2 & mini`
Flash Size: `4M (1M SPIFFS)`
CPU Frequency: `80Mhz`
Upload Using: `Serial`

### Sketch

Can't provide.

### Debug Messages

I can't get any message.
Because device hang.

```txt

```

**Comment by igrr** [comment]
I see you are using esptool.py. Flashing with that tool is not something we test in this project. Please try to use esptool-ck launched from Arduino IDE.

**Comment by bestpika** [comment]
I use Arduino IDE to flash my project.
I `erase_flash` before flash.

**Comment by bestpika** [comment]
I can't provide my Sketch content, but I can upload bin.

**Comment by bestpika** [comment]
16M build
[qbox.ino.zip](https://github.com/esp8266/Arduino/files/1662383/qbox.ino.zip)

4M build
[qbox.ino.zip](https://github.com/esp8266/Arduino/files/1662391/qbox.ino.zip)

**Comment by igrr** [comment]
Without seeing what the sketch does, I can offer very little in terms of advice. However, please try enabling debug output (in IDE tools menu, with level set to CORE) and add Serial.setDebugOutput(true) after your Serial.begin line. This may result in some output which will help you figure out the issue.

**Comment by bestpika** [comment]
I set debug CORE.
But after flash, this device can't work.
So I can't see any output.

**Comment by bestpika** [comment]
I think this device hang.

**Comment by bestpika** [comment]
@igrr I know what's happen.
After `SPIFFS.begin()`, this device hang.

```cpp
#include <FS.h>

void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.println("setup start");
  SPIFFS.begin(); // die at here
  Serial.println("setup ended");
}

void loop() {
  Serial.println(millis());
  delay(100);
}
```

**Comment by igrr** [comment]
Yes, formatting a 15MB SPIFFS filesystem can take very long time...

**Comment by bestpika** [comment]
Can spiffs add some debug message?

**Comment by igrr** [comment]
I don't see an existing API to have a callback on format process, unfortunately
https://github.com/pellepl/spiffs/blob/1350deb54c097fd06133f3c6d39dd3532a229829/src/spiffs.h#L612-L625
