### ISSUE TITLE
How does make hellomesh code work ?

### ISSUE THREAD

**Issue by WillingLearner** [esp8266/Arduino#4238]
I have two esp8266 12e module and want to create mesh network using these modules. I loaded the same code to the two esp module but they doesn't communicate with each other. I am monitoring whats happening in Serial on the first ESP. Module is reset itself somehow and shows stack info at regular intervals Where am i doing wrong ?

Thanks in advance

**Comment by skadiexe** [comment]
![image](https://user-images.githubusercontent.com/34567532/35384173-834ec336-01d5-11e8-8d67-7cff60d5fd6e.png)

Mine show connections (debug enabled) but regularly reboots too. It is inusable thing, open ESP8266WiFiMesh and see.

Using easymesh/painlessMesh could be very interesting, but now esp8266 lib 2.4.0 does not support easymesh

**Comment by WillingLearner** [comment]
I have never tried another libraries but HelloMesh so far. Did you manage to perform mesh network by using esp8266 in any way skadiexe ?

**Comment by rkoptev** [comment]
I have similar behavior. I flashed HelloMesh example to 2 ESP8266 NodeMCU boards and they stucks on "Setting up mesh node...". While one of nodes just stuck - second one constantly rebooting.

**Comment by devyte** [comment]
Fixed via #4718 .
