### ISSUE TITLE
Transmits a fixed frequency during frequency and amplitude measurement.

### ISSUE THREAD

**Issue by baamiis** [esp8266/Arduino#4249]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

----------------------------- Remove above -----------------------------

#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

To catch both frequency and TX power amplitude more accurately at PCBA level,  I would like to transmit a fixed frequency during frequency and amplitude measurement. is there a test example that I can use ??

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB
CPU Frequency:        80Mhz
Flash Mode:	         dio
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		nodemcu

### Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```![image](https://user-images.githubusercontent.com/5903902/35481402-e18ada56-041a-11e8-9516-d7f76a786e6d.png)![image](https://user-images.githubusercontent.com/5903902/35481405-ec456d80-041a-11e8-8b13-632c0f527f82.png)

**Comment by devyte** [comment]
@baamiis not the right place for such questions. This is an issue tracker, meant to track issues in the core libs.
Off the top of my head, I don't think what you want is possible. Access to the wifi radio functionality is through the Espressif SDK, and you can review the api reference by looking at the NONOS ESP8266 api reference, but I'm not aware of a function that can does something like that.
Closing as off-topic, see issue POLICY doc for details.
