### ISSUE TITLE
Isue

### ISSUE THREAD

**Issue by Videx1** [esp8266/Arduino#4258]
It doesen't work still. Why?
![zajeta slika](https://user-images.githubusercontent.com/35937346/35534257-a02b4a58-0548-11e8-87d3-f96ee2e571ae.JPG)

**Comment by devyte** [comment]
Please read this repo's issue POLICY doc, as well as the issue template you were presented when you opened this. I suggest requesting help at a community forum, as this is an issue tracker, and not meant for general support.
Closing due to lack of info and off topic.
