### ISSUE TITLE
lost wifi cause a reboot

### ISSUE THREAD

**Issue by chongding** [esp8266/Arduino#4267]
#### Hardware
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description
I have the below code to detect lost wifi connection then re-connect (with the existing ssid and pw). and I trigger the lost-wifi by shutting down my router, but when the wifi is lost, it cause 8266 to reboot. 

### Settings in IDE

Module:  			?ESP9266MOD-12E/F
Flash Size: 		?4MB?
CPU Frequency:		?80Mhz?
Flash Mode:			?qio?
Flash Frequency:	?80Mhz?
Upload Using:		?OTA / SERIAL?
Reset Method:		?ck / nodemcu?

### Sketch

```cpp

#include <ESP8266WiFi.h> 

void setup() {
  WiFi.mode(WIFI_AP_STA);
  WiFi.begin(ssid, pass);
}

void loop() {
   if (WiFi.status() == WL_CONNECTED) {
       ....
   }else{
     WiFi.begin(ssid, pass);
   }

}
```

### Debug Messages

```
messages here
```

**Comment by tonton81** [comment]
you do realize your flooding WiFi.begin? im not sure if theres a check inside until its finished, but, your still running it millions of times, it just aint right :P

**Comment by lrmoreno007** [comment]
There is a function that will do that job better:
`WiFi.setAutoReconnect (true);`

**Comment by tonton81** [comment]
and a handler :)

**Comment by chongding** [comment]
thanks for the autoreconnect  tip, it seems reset on lost connection while exchanging data with a website...
