### ISSUE TITLE
varialbe after sleep

### ISSUE THREAD

**Issue by Pablotis** [esp8266/Arduino#429]
Is it possible to store a variable and read it after deep sleep?

**Comment by adalurarun** [comment]
In deep sleep mode....only possible on ESP ,Manually wake a device....i think not possible

**Comment by antelder** [comment]
The RTC has some user memory that is maintained across deep sleep. A post about how to use that [here](http://www.esp8266.com/viewtopic.php?p=20009#p20009).

**Comment by Pablotis** [comment]
OK thanks
