### ISSUE TITLE
link broken in example

### ISSUE THREAD

**Issue by Newk77** [esp8266/Arduino#4290]
### Basic Infos

The link in the [udp-examples.rst](https://github.com/esp8266/Arduino/blob/master/doc/esp8266wifi/udp-examples.rst#udp) pointing to "Quick Start" is a [*.md](https://github.com/esp8266/Arduino/blob/master/doc/esp8266wifi/readme.md#quick-start) file, wich seems to be a [*.rst](https://github.com/esp8266/Arduino/blob/master/doc/esp8266wifi/readme.rst#quick-start)

**Comment by tarzan115** [comment]
I was done with this PR https://github.com/esp8266/Arduino/pull/4221 but it does not merge yet :)))

**Comment by devyte** [comment]
@tarzan115 @Newk77 I merged #4221 , please check. For me it seems to work when browsing the docs within this repo, but the links addressed in the PR still seem broken in readthedocs (different broken now).

**Comment by devyte** [comment]
Both PRs are merged. Closing.
