### ISSUE TITLE
Webserver access by hostname - slow initial connect on mobile device

### ISSUE THREAD

**Issue by caipifrosch** [esp8266/Arduino#4308]
#### Hardware
Hardware:		ESP-12F
Core Version:      	2.4.0

### Description

Webserver pages on my ESP12F module are typically served within 100-300ms when accessing those with a win10 machine. This applies to accesses by IP and hostname, no matter what browser I am using.

Chrome and firefox on android 7 would also serve pages quite fast when accessing them via IP.

But Initial connection for certain files will take up to 3sec when accessing the device by hostname (android 7, same network environment). This can be reproduced every page load and with all webserver pages, no matter what browser used.

Interestingly initial connection time for files is always in the range of 2.9-3.1sec. Looks like some static timeout or retry mechanism. Even the favicon.ico request takes 3sec before answering 204 no content.

Also my ajax/json status request machinery shows timeouts. Typically request runtime is about 30-50ms, but after page access via hostname half of them would run into the self assigned http timeout of 250ms. There are no timeouts when approaching webpage by IP.

Thanks a lot in advace for any suggestions or ideas.

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		4MB
CPU Frequency:	80Mhz
Flash Mode:		qio
Flash Frequency:	80Mhz
Upload Using:		OTA
Reset Method:		nodemcu
IP Stack:       lwip V2 MSS=536

### Test Scenarios
- Win10 => performance ok with IP and hostname access
- Android7 => up to 3sec initial connection for certain files

![image](https://user-images.githubusercontent.com/36002638/35849462-ebad99f2-0b21-11e8-92b6-98b8064ca805.png)

**Comment by devyte** [comment]
A whole lot has changed since this was reported, including several relevant fixes.
Closing. 
If you think the problem still exists, please open a new issue and follow the template instructions.
