### ISSUE TITLE
Ardunio ESP8266 ESP-12 NodeMCU HTML Issue

### ISSUE THREAD

**Issue by Jimcodom** [esp8266/Arduino#4312]
I built a sketch setting up my ESP as an AP Server to monitor my BBQ Smoker Temp. It reads the Max6675 probe and returns the temperature to my HTML Webpage. I'm stumped on an issue and looking for advice.

I want to keep sending updates to the Webpage with Temperature changes and found that I can just loop and continue sending the HTML string below after I update the Ftemp. My Web Screen continues to get the temp messages and just scrolls on forever. Just what I wanted. But the problem is if the connection is broken or I want to exit and check my internet. I cant reconnect with the ESP because my code is apparently still looping. I have to power the ESP down to reconnect.

Q - How to Continuously send the temp to my webpage but exit out of the loop when the connection is lost so that I can start my sketch back at the beginning? Would that be server.begin() . ?

String x = "<!DOCTYPE HTML>\r\n<html>\r\n";
x += "<p>&nbsp;</p>";
x += "<h2>Probe Temperature</h2>";
x += String(Ftemp);
    x += "</html>\n";
   client.print(x);
   delay(5000);

**Comment by devyte** [comment]
Your approach means that the browser is actually never done loading the html, which is not the same as having your loaded html updated periodically.
You're probably looking to update your html doc on the browser side with periodic json files that contain the temp.
Also, if you're serving, don't use such large delays, or your ESP's buffers can blow up.
Having said that, this is an issue tracker, not a support forum for your particular project. If you need further help, please direct your questions to a community forum like esp8266.com.
Closing per issue POLICY doc.
