### ISSUE TITLE
Software Serial  Inestable msg

### ISSUE THREAD

**Issue by pacocuervo** [esp8266/Arduino#4315]
Hardware:		ESP-12N
Core Version:      	2.4.0

### Settings in IDE

Module:  			NodeMCU 1.0 (ESP-12E Modulo)
Flash Size: 		4MB
CPU Frequency:       80Mhz
Upload Using:		SERIAL

Randomly, I am experiencing communication probles between ESP12N and ATM902E device using softwareSerial  to comunicate.

Finally I have isolated the problem. I'll try to show what si happening...

I have create a loop sending 0x55 to serial. 

In the scope you can see the data trace...

![image](https://user-images.githubusercontent.com/36072829/35916443-b4bbd104-0c0a-11e8-8b20-32730f5146ae.png)

Sometimes the scope show  somenthing like that.

![image](https://user-images.githubusercontent.com/36072829/35916810-f80d45ea-0c0b-11e8-9d35-78544c1263bc.png)

The arrows show that this bit has  a 40% width les than normall bit.

Any suggestion about?

Regards.

**Comment by devyte** [comment]
@igrr should this be handled in the SoftwareSerial repo?

**Comment by devyte** [comment]
@pacocuervo BTW, when you opened this issue, you were presented with an issue template requesting certain info. You pretty much ignored it in its entirety. Please edit your post and add the requested info.

**Comment by earlephilhower** [comment]
Closing here as it's being followed in the SWSerial repo (plus it's a really old core).
