### ISSUE TITLE
Using git core in PORTABLE IDE

### ISSUE THREAD

**Issue by s0170071** [esp8266/Arduino#4320]
I found the instructions for the Arduino IDE, but not for the portable version (where you have the portable folder inside the IDE main folder). 
Please add. Thanks.

**Comment by tonton81** [comment]
its the same way, just add it to the portable’s hardware folder following same instructions

**Comment by WereCatf** [comment]
I always use portable IDE myself and there is literally no change in how you set it up, just proceed as usual.

**Comment by devyte** [comment]
Closing per last two comments.

**Comment by s0170071** [comment]
Alright. I'll try that. 
Still, a note in the readme would be nice, especially since for Arduino portable installations usually all the esp stuff ends up in the "portable" folder, just not the git core...

**Comment by tonton81** [comment]
the “git core” never ends up in the arduino installation, core or not..

**Comment by tonton81** [comment]
*portable or not i mean

**Comment by s0170071** [comment]
We all sometimes mean sth. different than we write, don't we ;-)
