### ISSUE TITLE
Connection issues after fail AP login

### ISSUE THREAD

**Issue by lucrua** [esp8266/Arduino#4322]
Thank you for reading this and taking your time to help me. I hope this is going to be useful for others users too.

### Basic Infos
I've been experiencing some problems with WebSocket connection after trying to connect to an invalid AP.
Follow attached a simplified version of my code. Basically ESP8266 creates a SoftAP and a WebSocket server. My client connect to this WebSocket server and submit a ssid and password. This ssid and password is used to connect to a wifi network.
When ESP tries to login in an AP using invalid credentials, it drops my WebSocket connection and I'm not able to reconnect. When it tries using a valid credentials, it drops my connection too (but I can reconnect after some seconds).
I've been trying to understand what is happening, and it seems that behavior changes after a failed connection to an AP. Before trying to connect, this was shown on debug:
```
wifi evt: 7
wifi evt: 7
wifi evt: 7
```
After fail to connect this have been repeatedly shown:
```
.!.!.!.!.!wifi evt: 1
STA disconnect: 201
.!.!.!.!.!wifi evt: 1
STA disconnect: 201
```
This events seems to interfere on WebSocket new connections. The only way that I found to avoid this is changing my "connectWifi()" function: Insert a delay and an WiFi.mode(WIFI_AP) according to AP connection status.
```cpp
void connectWifi() {
  Serial.printf("Network: \"%s\" Password: \"%s\".\n", ssidExt, passExt);
  WiFi.begin(ssidExt,passExt);
  delay(10000);
  if (WiFi.status() == WL_CONNECTED) {
    Serial.println("Success!");
    WiFi.mode(WIFI_AP_STA);
  }
  else {
    Serial.println("Failed");
    WiFi.mode(WIFI_AP);
  }
}
```
Keeping this is mind, I have some questions that are intriguing me:
Why trying to connect to an AP is interfering on my WebSocket connection? Is it possible to keep those "STA disconnect: 201 ... wifi evt:1" events inside "WiFi.begin()" only? Is those events the reason why I cannot reconnect to WebSocket server? If so, this new connectWifi (with delay and WiFi.mode) is the right solution for this problem?
Thank you so much for reading this.

#### Hardware
Hardware:			ESP-12F
Core Version:      	2.4.0

### Description

Problem description

### Settings in IDE

Module:  			Generic ESP8266 Module
Flash Size: 		512K
CPU Frequency:		80Mhz
Flash Mode:			QIO
Flash Frequency:	40Mhz
Upload Using:		SERIAL
Reset Method:		?

### Sketch

```cpp
#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>
#include <WebSocketsServer.h>
#include <ArduinoJson.h>


const char* ssidSoftAP = "SejaBemVindo";
const char* passSoftAP = "internetdascoisas";

char ssidExt[33] = "";
char passExt[33] = "";

WebSocketsServer webSocket = WebSocketsServer(80);

StaticJsonBuffer<500> jsonBuffer;
char messageString[400];

void setup() {
  Serial.begin(115200);
  WiFi.mode(WIFI_AP);
  WiFi.softAP("hello", "password");
  Serial.println(WiFi.softAPIP());
  webSocket.begin();
  webSocket.onEvent(webSocketEvent);
}

void loop() {
  Serial.print(".");
  webSocket.loop();
  Serial.print("!");
  delay (500);
}

void connectWifi() {
  Serial.printf("Network: \"%s\" Password: \"%s\".\n", ssidExt, passExt);
  WiFi.begin(ssidExt,passExt);
}

void webSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length) {
 switch(type) {
   case WStype_DISCONNECTED:
     Serial.println("Disconnected.");
     break;

   case WStype_CONNECTED:
     Serial.printf("Connected.\n");
   break;

   case WStype_BIN:
     Serial.printf("Received: %u\n", length);
     hexdump(payload, length);
   break;

   case WStype_TEXT: {
     Serial.printf("Received: %s\n", payload);
     jsonBuffer.clear();
     JsonObject& messageJson = jsonBuffer.parseObject(payload);
     messageJson.prettyPrintTo(Serial);

     if (messageJson.containsKey("ssid") && messageJson.containsKey("pass")) {
       Serial.print("Network received.");
       sprintf(ssidExt, messageJson["ssid"]);
       sprintf(passExt, messageJson["pass"]);
       connectWifi();
       sprintf(messageString,"Done!");
       Serial.print("Sending: ");
       Serial.println(messageString);
       webSocket.sendTXT(num, messageString);
     }
   }
   break;
  }
}
```

### Debug Messages

```
[AP] softap config unchanged
192.168.4.1
[WS-Server] Server Started.
wifi evt: 7
.!wifi evt: 7
wifi evt: 5
.!.!wifi evt: 7
.[WS-Server][0] new client from 192.168.4.2
[WS-Server][0][handleHeader] RX: GET / HTTP/1.1
!.[WS-Server][0][handleHeader] RX: Host: 192.168.4.1
(... WebSocket DEBUG ...)
[WS][0][sendFrame] sending Frame Done (2111us).
Connected.
!.[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
[readCb] n: 2 t: 9660
(... WebSocket DEBUG ...)
[WS][0][handleWebsocket] get pong ()
!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!wifi evt: 7
wifi evt: 7

wifi evt: 7
wifi evt: 7
.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.!.[WS][0][handleWebsocketWaitFor] size: 2 cWsRXsize: 0
(... WebSocket DEBUG ...)
Received: {"ssid":"wrongSSID","pass":"heyheyhey"}
{
  "ssid": "wrongSSID",
  "pass": "heyheyhey"
}Network received.Network: "wrongSSID" Password: "heyheyhey".
Enviando: Done!
[WS][0][sendFrame] ------- send massage frame -------
(... WebSocket DEBUG ...)
[WS][0][sendFrame] sending Frame Done (3910us).
!.!.!.!.!wifi evt: 1
STA disconnect: 201
.**[WS-Server][0] client connection lost.
[WS-Server][0] client disconnected.**
Disconnected.
!.!.!.!wifi evt: 1
STA disconnect: 201
.!.!.!.!.!wifi evt: 1
STA disconnect: 201
.!.!.!.!wifi evt: 1
STA disconnect: 201
.!.!.!.!wifi evt: 1
STA disconnect: 201
.[WS-Server][0] new client from 192.168.4.2
[WS-Server][0][handleHeader] RX: GET / HTTP/1.1
!.[WS-Server][0][handleHeader] RX: Host: 192.168.4.1
!.[WS-Server][0][handleHeader] RX: Connection: Upgrade
!.[WS-Server][0][handleHeader] RX: Pragma: no-cache
!.[WS-Server][0][handleHeader] RX: Cache-Control: no-cache
!wifi evt: 1
STA disconnect: 201
.[WS-Server][0] client connection lost.
[WS-Server][0] client disconnected.
Disconnected.
!.!.!.!wifi evt: 1
STA disconnect: 201
.!.!.!.!.!wifi evt: 1
STA disconnect: 201
.!.!.!.!wifi evt: 1
```
[test.zip](https://github.com/esp8266/Arduino/files/1705668/test.zip)

**Comment by devyte** [comment]
The ESP has a single radio, and you're using StationAP mode. When you connect tonthe SoftAP side, you do so on one channel, then you tell the Station side to connect to some router serving wifi on a different channel. At that point the Station side drags the SoftAP side along, and you see it drop off the map, hence losing your connection.
When it succeeds, the SoftAP side stabilizes on the Starion channel, so your device can connect again.
When it fails, it probably keeps scanning and retrying, so the SoftAp side never settles down to allow you to connect again.
Workaround: set the SoftAp channel to the channel of the router you tell it to connect to. It should reduce the channel hopping (not sure if it stops it entirely).
The SoftAp side is supposed to send CSA, but there seems to be a bug wheere it sends an extra beacon, and it doesn't work. There's a post about it on espressif's bbs, and an open issue in the nonos sdk repo.
Closing as known issue in sdk, and no available fix.
