### ISSUE TITLE
USB port damaged

### ISSUE THREAD

**Issue by JanashreeA** [esp8266/Arduino#4325]
II have been working with my nodemcu and it was working fine and when plugging in the usb cord unknowingly i damaged my usb connenction in nodemcu so nodemcu is not getting detected by my pc
so is there any way to rectify it
i have a doubt whether i can program my nodemcu with arduino like the same way esp8266 can be programmed by arduino????

**Comment by devyte** [comment]
@JanashreeA why are you asking for help with a damaged board in the issue tracker for the core libs? I suggest asking at a community forum like esp8266.com.
Closing as off-topic, see issue POLICY doc for details.
