### ISSUE TITLE
ESP8266HTTPUpdateServer on W5100 ethernet

### ISSUE THREAD

**Issue by tetye** [esp8266/Arduino#4335]
Please help me guys. 
I using ESP8266 and W5100 ethernet modul working, but l want to use the "webupdater" for firmware update, and problem is arduino loading ESP8266WebServer.cpp. Arduino is not bulid this sketch: 
/*
Simple ESP8266 web httpServer sample for wired connection. 
Connect Wiznet W5100 to GPIO 12 (MSIO), 13 (MOSI), 14 (CLK) and 15 (CS)
Some times W5100 can take long time to start serve TCP. If you have problems with connecting to your ESP8266 check ping first. 
If module does not reply to ping check your wirings. If module reply to ping get cup of coffee and it probably answer also to http after that. 

This sample is taken from ESP8266 repository without Licence header information and modified by Tapio Haapala 2016 for ESP8266EthernetWebhttpServer.
*/

#include <SPI.h>
#include <Ethernet.h>
#include <ESP8266EthernetWebServer.h>
#include <ESP8266HTTPUpdateServer.h>

// Enter a MAC address and IP address for your controller below.

byte mac[] = {
  0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED
};
// The IP address will be dependent on your local network:
IPAddress ip(192, 168, 96, 200);

ESP8266EthernetWebServer httpServer(80);
ESP8266HTTPUpdateServer httpUpdater;

const int led = 13;

void handleRoot() {
  httpServer.send(200, "text/plain", "hello from esp8266 ethernet port!");
}

void handleNotFound(){
  String message = "File Not Found\n\n";
  message += "URI: ";
  message += httpServer.uri();
  message += "\nMethod: ";
  message += (httpServer.method() == HTTP_GET)?"GET":"POST";
  message += "\nArguments: ";
  message += httpServer.args();
  message += "\n";
  for (uint8_t i=0; i<httpServer.args(); i++){
    message += " " + httpServer.argName(i) + ": " + httpServer.arg(i) + "\n";
  }
  httpServer.send(404, "text/plain", message);
  digitalWrite(led, 0);
}

void setup(void){
  // Open serial communications and wait for port to open:
  Serial.begin(9600);  
  Serial.println();

  // start the ethernet connection and the httpServer:
  Ethernet.begin(mac, ip);
//    httpUpdater.setup(&httpServer);
  httpServer.begin();
  Serial.print("httpServer is at ");
  Serial.println(Ethernet.localIP());

  httpServer.on("/", handleRoot);

  httpServer.on("/inline", [](){
    httpServer.send(200, "text/plain", "this works as well");
  });

  httpServer.onNotFound(handleNotFound);

  httpServer.begin();
  Serial.println("HTTP httpServer started");
}

void loop(void){
  httpServer.handleClient();
}

**Comment by devyte** [comment]
@hotchpotch ESP8266EthernetWebServer Is not currently supported in this repo. It is a proposed addition, which is not accepted, and which at least two maintainers don't like due to code duplication.
There are certain core changes that are being discussed that could make the proposal not needed in the future, but it will take some time to get there, as the changes are rather complex.
If you need this now, I suggest you maintain your own local version of the proposal, and make your own version of ESP8266HTTPUpdateServer for it.
Closing per issue POLICY doc (no issues for code not accepted).
