### ISSUE TITLE
flashing esp8266-01s: working, esp8266-01: not working

### ISSUE THREAD

**Issue by StefCoene** [esp8266/Arduino#4344]
Hi,

I have 2 x esp8266-01s and I can flash them fine. Never gives an error.

I also ordered 4 x esp8266-01 and I can't flash them nor can I get any output on the console.
They are just not responding to anything.
I use the same connections for both types. I have a FTDI with RTS connected to RTS and DTR to GPIO0.
For the esp8266-01s I use the 3,3V of the FTDI, but I also tried it with a separate 3,3V. But that didn't helped.

I wonder if these 4 x esp8266-01 are DOA (Dead On Arrival) or am I doing something wrong?

Stef

**Comment by tonton81** [comment]
this isnt a core code related issue, you should be asking on the forums.
