### ISSUE TITLE
Issues #353/#3100 Continue. WiFi only works once after erasing flash

### ISSUE THREAD

**Issue by mlbranchus** [esp8266/Arduino#4345]
Please fill the info fields, it helps to get you faster support ;)

if you have a stack dump decode it:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/stack_dump.rst

for better debug messages:
https://github.com/esp8266/Arduino/blob/master/doc/Troubleshooting/debugging.rst

----------------------------- Remove above -----------------------------

#### Hardware 
Hardware:			?ESP-12?
Core Version:      	?2.1.0-rc2?

### Description

Problem description WiFi only works once after erasing flash

### Settings in IDE

Module:  		Huzzah ESP8266 Module
Flash Size: 		?4MB/1MB?
CPU Frequency:		80Mhz
Flash Mode:			?qio?
Flash Frequency:	?40Mhz?
Upload Using:		/ SERIAL?
Reset Method:		?ck 

### Sketch

```cpp

#include <Arduino.h>

// Adafruit IO Temperature & Humidity Example
// Tutorial Link: https://learn.adafruit.com/adafruit-io-basics-temperature-and-humidity
//
// Adafruit invests time and resources providing this open source code.
// Please support Adafruit and open source hardware by purchasing
// products from Adafruit!
//
// Written by Todd Treece for Adafruit Industries
// Copyright (c) 2016-2017 Adafruit Industries
// Licensed under the MIT license.
//
// All text above must be included in any redistribution.

/************************** Configuration ***********************************/

// edit the config.h tab and enter your Adafruit IO credentials
// and any additional configuration needed for WiFi, cellular,
// or ethernet clients.
#include "config.h"

/************************ Example Starts Here *******************************/
#include <Adafruit_Sensor.h>
#include <DHT.h>
#include <DHT_U.h>
#include <Adafruit_SSD1306.h>

// oled display
Adafruit_SSD1306 oled = Adafruit_SSD1306();

// pin connected to DH22 data line
#define DATA_PIN 2

// create DHT22 instance
DHT_Unified dht(DATA_PIN, DHT22);

// set up the 'temperature' and 'humidity' feeds
AdafruitIO_Feed *temperature = io.feed("temperature");
AdafruitIO_Feed *humidity = io.feed("humidity");

void setup() {
  oled.begin(SSD1306_SWITCHCAPVCC, 0x3C);  // initialize with the I2C addr 0x3C (for the 128x32)
  oled.display();

  // start the serial connection
  Serial.begin(115200);

  // wait for serial monitor to open
  while(! Serial);

  // initialize dht22
  dht.begin();

  // connect to io.adafruit.com
  Serial.print("Connecting to Adafruit IO");
  io.connect();

  // wait for a connection
  while(io.status() < AIO_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  // we are connected
  Serial.println();
  Serial.println(io.statusText());

  // text display tests
  oled.setTextSize(1);
  oled.setTextColor(WHITE);
}

void loop() {

  // io.run(); is required for all sketches.
  // it should always be present at the top of your loop
  // function. it keeps the client connected to
  // io.adafruit.com, and processes any incoming data.
  io.run();

  sensors_event_t event;
  dht.temperature().getEvent(&event);

  float celsius = event.temperature;
  float fahrenheit = (celsius * 1.8) + 32;

  Serial.print("celsius: ");
  Serial.print(celsius);
  Serial.println("C");

  Serial.print("fahrenheit: ");
  Serial.print(fahrenheit);
  Serial.println("F");

  // save fahrenheit (or celsius) to Adafruit IO
  temperature->save(fahrenheit);

  dht.humidity().getEvent(&event);
   
  Serial.print("humidity: ");
  Serial.print(event.relative_humidity);
  Serial.println("%");

  // save humidity to Adafruit IO
  humidity->save(event.relative_humidity);

  // print it to the OLED
  oled.clearDisplay();
  oled.setCursor(0,0);
  oled.print("SSID: "); oled.println(WIFI_SSID);
  oled.print("IP: "); oled.println(WiFi.localIP());
  oled.print("Temp: "); oled.print(fahrenheit,0); oled.print(" *F ");
  oled.print("Hum: "); oled.print(event.relative_humidity,0); oled.println(" %");
  oled.print("IO Status: ");
  aio_status_t aio_status = io.status();
  Serial.print("Status: "); Serial.println(aio_status);
  switch (aio_status) {
     case AIO_IDLE:  oled.println("IDLE"); break;
     case AIO_DISCONNECTED:
     case AIO_NET_DISCONNECTED:  oled.println("DISCONNECT"); break;
     case AIO_NET_CONNECTED:
     case AIO_CONNECTED_INSECURE:
     case AIO_CONNECTED: oled.println("CONNECTED"); break;
  }
  oled.display();

  // wait 5 seconds (5000 milliseconds == 5 seconds)
  delay(2000);
}
void setup() {

}

void loop() {

}
```

### Debug Messages

```
messages here
```

**Comment by tonton81** [comment]
i dont see you running WiFi.begin()?

**Comment by mlbranchus** [comment]
TonTon,
Thanks for the swift response.
Unfortunately I'm fairly new to programming, basically I follow examples to learn.

Ok. I inserted  wifi.begin() in void.loop() but got a scope error. I tried brackets without success.
So, I'm going to need help to do anything to fix this mess.

 

 Thanks

 

-----Original Message-----

**Comment by tonton81** [comment]
it has to be in your setup()
WiFi.begin(“SSID”,”PASSWORD”);

**Comment by tonton81** [comment]
note the upper and lower case “WiFi”, must be exact

**Comment by mlbranchus** [comment]
TonTon,

I installed the fix, restarted IDE and still got status code 21. Shortly thereafter I got a halt. Is there more to this?




Here is the fault info.

Thanks,

Mike

**Comment by mlbranchus** [comment]
TonTon,

BTW...I entered my router SSID and PASSWORD.

 

 Mike

**Comment by beicnet** [comment]
You also need to #include wifi libraries too!

**Comment by mlbranchus** [comment]
TonTon,

BTW...I entered my router SSID and PASSWORD.

 

 Mike

**Comment by mlbranchus** [comment]
Which wifi libraries need to be included?

Mike

**Comment by beicnet** [comment]
As I wrote before above at the top of your code:
`#include "ESP8266WiFi.h"`

**Comment by mlbranchus** [comment]
TonTon and beic,

I've added #include ESP8266WiFi.h 
but I'm still getting fault code 21.

Mike

**Comment by beicnet** [comment]
Did you include ESP8266 Arduino core to your references?

**Comment by mlbranchus** [comment]
beic,

I don't know. I don't think so. What is the specific name and where is it located?


Thanks,

Mike

 

 

 

-----Original Message-----

**Comment by beicnet** [comment]
Open the Arduino IDE and go to:

File > Preferences > Additional Boards Manager URLs and then add this line:

`http://arduino.esp8266.com/stable/package_esp8266com_index.json`

close the IDE, then reopen it.

After that go to the Tools > Board Manager, find ESP8266 Community and install it.

**Comment by mlbranchus** [comment]
Beic,

I already had it installed in prefs and updated as ver 2.3.0.

Next?

Mike

 

 

-----Original Message-----

**Comment by beicnet** [comment]
Ok, can you please post your current code again or update it above, and attach the screenshot of that error code?!

**Comment by mlbranchus** [comment]
// Adafruit IO Temperature & Humidity Example
// Tutorial Link: https://learn.adafruit.com/adafruit-io-basics-temperature-and-humidity
//
// Adafruit invests time and resources providing this open source code.
// Please support Adafruit and open source hardware by purchasing
// products from Adafruit!
//
// Written by Todd Treece for Adafruit Industries
// Copyright (c) 2016-2017 Adafruit Industries
// Licensed under the MIT license.
//
// All text above must be included in any redistribution.

/************************** Configuration ***********************************/

// edit the config.h tab and enter your Adafruit IO credentials
// and any additional configuration needed for WiFi, cellular,
// or ethernet clients.
#include "config.h"

/************************ Example Starts Here *******************************/
#include <Adafruit_Sensor.h>
#include <DHT.h>
#include <DHT_U.h>
#include <Adafruit_SSD1306.h>
#include <ESP8266WiFi.h>

// oled display
Adafruit_SSD1306 oled = Adafruit_SSD1306();

// pin connected to DH22 data line
#define DATA_PIN 2

// create DHT22 instance
DHT_Unified dht(DATA_PIN, DHT22);

// set up the 'temperature' and 'humidity' feeds
AdafruitIO_Feed *temperature = io.feed("temperature");
AdafruitIO_Feed *humidity = io.feed("humidity");

void setup() {
  oled.begin(SSD1306_SWITCHCAPVCC, 0x3C);  // initialize with the I2C addr 0x3C (for the 128x32)
  oled.display();

  WiFi.begin("annwyn","pirate9d"); //ENTRY HERE
  
  // start the serial connection
  Serial.begin(115200);

  // wait for serial monitor to open
  while(! Serial);

  // initialize dht22
  dht.begin();

  // connect to io.adafruit.com
  Serial.print("Connecting to Adafruit IO");
  io.connect();

  // wait for a connection
  while(io.status() < AIO_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  // we are connected
  Serial.println();
  Serial.println(io.statusText());

  // text display tests
  oled.setTextSize(1);
  oled.setTextColor(WHITE);
}

void loop() {

  // io.run(); is required for all sketches.
  // it should always be present at the top of your loop
  // function. it keeps the client connected to
  // io.adafruit.com, and processes any incoming data.
  io.run();
  
  sensors_event_t event;
  dht.temperature().getEvent(&event);

  float celsius = event.temperature;
  float fahrenheit = (celsius * 1.8) + 32;

  Serial.print("celsius: ");
  Serial.print(celsius);
  Serial.println("C");

  Serial.print("fahrenheit: ");
  Serial.print(fahrenheit);
  Serial.println("F");

  // save fahrenheit (or celsius) to Adafruit IO
  temperature->save(fahrenheit);

  dht.humidity().getEvent(&event);
   
  Serial.print("humidity: ");
  Serial.print(event.relative_humidity);
  Serial.println("%");

  // save humidity to Adafruit IO
  humidity->save(event.relative_humidity);

  // print it to the OLED
  oled.clearDisplay();
  oled.setCursor(0,0);
  oled.print("SSID: "); oled.println(WIFI_SSID);
  oled.print("IP: "); oled.println(WiFi.localIP());
  oled.print("Temp: "); oled.print(fahrenheit,0); oled.print(" *F ");
  oled.print("Hum: "); oled.print(event.relative_humidity,0); oled.println(" %");
  oled.print("IO Status: ");
  aio_status_t aio_status = io.status();
  Serial.print("Status: "); Serial.println(aio_status);
  switch (aio_status) {
     case AIO_IDLE:  oled.println("IDLE"); break;
     case AIO_DISCONNECTED:
     case AIO_NET_DISCONNECTED:  oled.println("DISCONNECT"); break;
     case AIO_NET_CONNECTED:
     case AIO_CONNECTED_INSECURE:
     case AIO_CONNECTED: oled.println("CONNECTED"); break;
  }
  oled.display();

  // wait 5 seconds (5000 milliseconds == 5 seconds)
  delay(2000);
}

**Comment by beicnet** [comment]
I see, you need to remove that line in your code `WiFi.begin("annwyn","pirate9d"); //ENTRY HERE` and all configurations/settings has to be done in the `config.h`.

You just need to follow the Adafruit [tutorial](https://learn.adafruit.com/adafruit-io-basics-temperature-and-humidity) included at a top of your code.

**Comment by mlbranchus** [comment]
TonTon told  me to add that line of code.

**Comment by tonton81** [comment]
sorry i was not aware the library had a separate file for that, another reason i hate adafruit libraries

**Comment by mlbranchus** [comment]
Ok, So all of that code  belongs in config.h instead of .ino?

**Comment by beicnet** [comment]
No, there is two file one is `.ino` and the second is `.h`, your settings are located in the `.h` file, there you need to setup your credentials and connection type.

**Comment by mlbranchus** [comment]
Yes I know that. All of my credentials and connection type are already in the .h file.

**Comment by mlbranchus** [comment]
Ok.

Everything is back to where it was before. And the code 21 fault is still there!

Mike

**Comment by beicnet** [comment]
What line give you the fault code? Can you post a screenshot?

**Comment by mlbranchus** [comment]
The serial monitor shows status 21...thats the fault code

**Comment by beicnet** [comment]
Just that outputs? Nothing else?

**Comment by mlbranchus** [comment]
The first 2 show what I get when output fails.
the third shows what serial monitor reports as it is running.
the fourth is just what the status code is i.e. status 21

That's all I have.

**Comment by beicnet** [comment]
Can you post a screenshot of it?

**Comment by mlbranchus** [comment]
Im going offline in 40 minutes.

I'm going offline for 3-4 hours.

Thanks
Mike

**Comment by mlbranchus** [comment]
The first 3 ARE screenshots of it! 
This is all of the imformation about it that ESP is providing.
As I said , the first two screenshots are the error when the connection fails
The third screenshot shows the running serial monitor while the connection is connected.
But the third shows "status 21" every four cycles.

 

 


-----Original Message-----

**Comment by mlbranchus** [comment]
Hi guys.
Thanks for the work on this.

Have you come with any ideas to fix this fault code?

Mike

**Comment by beicnet** [comment]
I don't see / have any screenshots from you!

**Comment by mlbranchus** [comment]
We're having a serious failure to communicate here.

I've sent you all of the screen shots that I have. 

I've sent the beginning  and end of the reset comprising of the first and second screenshot(s).

I've sent a screenshot of the running serial monitor shgowing status fault 21 compriising screenshot 3.

All three were sent via email.

Did you receive them?

Mike

Is there a specific screenshot that you're looking for?

Here is the current sketch. 

// Adafruit IO Temperature & Humidity Example
// Tutorial Link: https://learn.adafruit.com/adafruit-io-basics-temperature-and-humidity
//
// Adafruit invests time and resources providing this open source code.
// Please support Adafruit and open source hardware by purchasing
// products from Adafruit!
//
// Written by Todd Treece for Adafruit Industries
// Copyright (c) 2016-2017 Adafruit Industries
// Licensed under the MIT license.
//
// All text above must be included in any redistribution.

/************************** Configuration ***********************************/

// edit the config.h tab and enter your Adafruit IO credentials
// and any additional configuration needed for WiFi, cellular,
// or ethernet clients.
#include "config.h"

/************************ Example Starts Here *******************************/
#include <Adafruit_Sensor.h>
#include <DHT.h>
#include <DHT_U.h>
#include <Adafruit_SSD1306.h>
//#include <ESP8266WiFi.h>

// oled display
Adafruit_SSD1306 oled = Adafruit_SSD1306();

// pin connected to DH22 data line
#define DATA_PIN 2

// create DHT22 instance
DHT_Unified dht(DATA_PIN, DHT22);

// set up the 'temperature' and 'humidity' feeds
AdafruitIO_Feed *temperature = io.feed("temperature");
AdafruitIO_Feed *humidity = io.feed("humidity");

void setup() {
  oled.begin(SSD1306_SWITCHCAPVCC, 0x3C);  // initialize with the I2C addr 0x3C (for the 128x32)
  oled.display();

  //WiFi.begin("annwyn","pirate9d"); //ENTRY HERE
  
  // start the serial connection
  Serial.begin(115200);

  // wait for serial monitor to open
  while(! Serial);

  // initialize dht22
  dht.begin();

  // connect to io.adafruit.com
  Serial.print("Connecting to Adafruit IO");
  io.connect();

  // wait for a connection
  while(io.status() < AIO_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  // we are connected
  Serial.println();
  Serial.println(io.statusText());

  // text display tests
  oled.setTextSize(1);
  oled.setTextColor(WHITE);
}

void loop() {

  // io.run(); is required for all sketches.
  // it should always be present at the top of your loop
  // function. it keeps the client connected to
  // io.adafruit.com, and processes any incoming data.
  io.run();
  
  sensors_event_t event;
  dht.temperature().getEvent(&event);

  float celsius = event.temperature;
  float fahrenheit = (celsius * 1.8) + 32;

  Serial.print("celsius: ");
  Serial.print(celsius);
  Serial.println("C");

  Serial.print("fahrenheit: ");
  Serial.print(fahrenheit);
  Serial.println("F");

  // save fahrenheit (or celsius) to Adafruit IO
  temperature->save(fahrenheit);

  dht.humidity().getEvent(&event);
   
  Serial.print("humidity: ");
  Serial.print(event.relative_humidity);
  Serial.println("%");

  // save humidity to Adafruit IO
  humidity->save(event.relative_humidity);

  // print it to the OLED
  oled.clearDisplay();
  oled.setCursor(0,0);
  oled.print("SSID: "); oled.println(WIFI_SSID);
  oled.print("IP: "); oled.println(WiFi.localIP());
  oled.print("Temp: "); oled.print(fahrenheit,0); oled.print(" *F ");
  oled.print("Hum: "); oled.print(event.relative_humidity,0); oled.println(" %");
  oled.print("IO Status: ");
  aio_status_t aio_status = io.status();
  Serial.print("Status: "); Serial.println(aio_status);
  switch (aio_status) {
     case AIO_IDLE:  oled.println("IDLE"); break;
     case AIO_DISCONNECTED:
     case AIO_NET_DISCONNECTED:  oled.println("DISCONNECT"); break;
     case AIO_NET_CONNECTED:
     case AIO_CONNECTED_INSECURE:
     case AIO_CONNECTED: oled.println("CONNECTED"); break;
  }
  oled.display();

  // wait 5 seconds (5000 milliseconds == 5 seconds)
  delay(2000);
}

**Comment by beicnet** [comment]
Screenshot is when you press the "Print Screen" button on your keyboard and then save it in the mspaint as image and you attach that image to this post!

**Comment by mlbranchus** [comment]
I know what a screenshot is!

I took 3 of them several times for you.

I just took another one for you just a few minutes ago.

**Comment by mlbranchus** [comment]
what about in the email?

**Comment by mlbranchus** [comment]
No it's not

**Comment by beicnet** [comment]
Just drag and drop your images here!

**Comment by tonton81** [comment]
jeebus, this “issue” is bigger than an average forum topic lol

**Comment by beicnet** [comment]
:rofl:

**Comment by mlbranchus** [comment]
I've sent MANY email messages with screenshots.

**Comment by mlbranchus** [comment]
LOL. driving me insane.

**Comment by beicnet** [comment]
So, did you made already account on Adafruit IO, just a simple question

**Comment by mlbranchus** [comment]
I will provide whatever you want.


Do you want email? Do you want Github?

Just tell me and I'll do it.

**Comment by beicnet** [comment]
Github

**Comment by mlbranchus** [comment]
So...how do I open the GitHub information?

**Comment by beicnet** [comment]
just upload the images to https://imgur.com/ and paste links here...

**Comment by mlbranchus** [comment]
Is this a joke?

**Comment by mlbranchus** [comment]
If we could define the where and what I think we can get to the how.

The issue is that the connection software fails to reset automatically. 
I have to manually reset each occurance.

**Comment by beicnet** [comment]
Not a joke, if you don't know how to attach images here, then I can't help you, another thing, this is not a support forum, it's a core development branch, so, here you will not get any help regarding you sketch.

You basicaly need to ask your questions on your board manufacturer and code sample page.

And it's located [here](https://forums.adafruit.com/index.php).

Regards

**Comment by vdeconinck** [comment]
Guys,
@tonton81 and @beicnet , I know how it feels, I'm always tempted to help users too, but I've been reminded in the past (and rightly so) that this is a tracker for issues in the ESP8266 core for Arduino IDE, not a forum for tracking user errors, and certainly not for teaching people how to attach an image to a comment.
Per https://github.com/esp8266/Arduino/blob/master/POLICY.md , I think the best is to move that discussion over to esp8266.com or stackoverflow and close this issue that is currently just generating spam.

**Comment by beicnet** [comment]
@vdeconinck Yes, thats the reason for my last comment to him and it's not that I wont help!

**Comment by devyte** [comment]
Alright, enough.
@mlbranchus please request help at a community forum, and discuss there. If you reduce your problem to an issue in the core code hosted in this repo, please open a new issue and provide the requested details, including an mcve sketch. Keep in mind that issues with 3rd party libs such as Adafruit are NOT covered here.
Closing per issue POLICY doc.
