### ISSUE TITLE
Mime types in RequestHandlersimpl.h

### ISSUE THREAD

**Issue by Hiddenvision** [esp8266/Arduino#4348]
So perhaps (100%) user issue.
Can someone shed some light on how to access the existing getContentType function, or existing mimeTable[].

I realise that is must be included by something, as the Types are in the Binary.
But how would I call the built-in  static String getContentType(const String& path) {...}
Or how would I access the mimeTable directly.

I have tried a million ways but seem to have missed the one that works.
Done a tank of searching but can only see example of people making their own function .
As I do myself. But I see Two sets of Extensions & descriptors hiding in the Binary.

Guessing this will be "Simple" or Impossible.
Sorry if this is too lame to answer.!

**Comment by tonton81** [comment]
your better off asking on the forums, none of this is relevant to to core code having an issue

**Comment by Hiddenvision** [comment]
Actually I see these have been split to a separate mimetypes.cpp and h in the past few days.
Cool,
