### ISSUE TITLE
ESP8266Webserver warning on string concat

### ISSUE THREAD

**Issue by Sparatutto** [esp8266/Arduino#4354]
Recently I have updated the library as you suggested me with the GIT and I have a warning on a string concatenation.
Second I see new iwIp variant names and not sure what they are.
One is for memory saving and the second for bandwidth. Not sure the meaning of this second.

I'm compiling with the warning and I did test both iwip.
No difference with the two version and no issues with the warning.

#### Hardware

![image](https://user-images.githubusercontent.com/35924963/36106292-3186f53c-1017-11e8-9016-35b17b7f1d63.png)

### Description

I think  + ':auth:' should be with "" instead.

### Sketch

```

### Debug Messages

```
:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266WebServer\src\ESP8266WebServer.cpp:198:93: warning: character constant too long for its type [enabled by default]

         md5.add(_H1 + FPSTR(colon) + _nonce + FPSTR(colon) + _nc + FPSTR(colon) + _cnonce + ':auth:' + _H2);

                                                                                             ^

```

**Comment by earlephilhower** [comment]
Please try the GIT latest.  Commit #4338 fixes this and a few other problems.

**Comment by Sparatutto** [comment]
@earlephilhower thanks, i will try to update tomorrow.
FYI, i did update on friday and the fix seems to be before my git.
Anyway I will tr tomorrow.
thx!

**Comment by Sparatutto** [comment]
Updated now. Ok no more warning. Thanks
