### ISSUE TITLE
Problems downloading very large files through server.streamFile ()

### ISSUE THREAD

**Issue by usonix** [esp8266/Arduino#4362]
Hello, I'm new here and I do not have much experience in programming, I'm using the Nodemcu 1.0 board, my code is based on the SDWebSever example but with a network configured for access point, the example works fine with large files, but in my code it does not. The download then starts, sends a random amount of bytes and then the download suddenly crashes. Unfortunately it is not possible to share the code with you, but could you tell me if there is any way to prevent this crash, something linked to the streamFile function or the webpage that defines that the download should not stop until it is finished.

**Comment by devyte** [comment]
If you're new, you should probably start by asking at a community forum. This is an issue tracker, meant to track issues in the core code, and not meant for general support.
Also, even for a core issue, you're unlikely to get help if you can't provide an MCVE sketch to reproduce it.
Closing per issue POLICY doc.
