### ISSUE TITLE
NODEMCU SERVER SEND

### ISSUE THREAD

**Issue by queenbey91** [esp8266/Arduino#4368]
Hello!
I want to ask if there is any possibility to send a direction with server.send in Nodemcu.
For instance, 

    server.send(200, "text/html", and put here an IP number);    

instead of
    server.send(200, "text/html", "hello");  

Thank you!

**Comment by WereCatf** [comment]
Yes, just convert the IP-address to a String.

**Comment by tonton81** [comment]
isnt it already a “String” when passed to IPAddress?

server.send(200, “text/html”,IPAddress(192,168,2,55));

**Comment by WereCatf** [comment]
No, to convert an IPAddress to a string, you use toString(), ie. `server.send(200, “text/html”,IPAddress(192,168,2,55).toString());`

**Comment by queenbey91** [comment]
Thank you very much for your help guys!!! :D :D :D :D

**Comment by queenbey91** [comment]
g
