### ISSUE TITLE
Release dates for ESP8266WebServerSecure

### ISSUE THREAD

**Issue by esteveavi** [esp8266/Arduino#4376]
Hi,

Please, can anyone tell which is the roadmap and planned dates for including ESP8266WebServerSecure in a new release.

I am trying to pass sensitive information like usernames and passwords to the ESP and it cannot be done over HTTP.

A part from that all software initiatives are pushing hard to enforce HTTPS on all their products. One of them is Google an its Android platform.

Thank you very much.

**Comment by devyte** [comment]
AFAICT, ESP8266WebServerSecure is already in master branch. Be aware that there are fundamental changes ongoing for the secure layer (axTLS fixes, bearSSL integration). 
There are no planned dates, I suggest keeping an eye on relevant issues and PRs, and their assigned milestones.
Closing.
