### ISSUE TITLE
Nodemcu Web Server

### ISSUE THREAD

**Issue by queenbey91** [esp8266/Arduino#4378]
Hi!

I am working with nodemcu, sending some information from Arduino to node by UART 
and then i'm showing all the data to a website, allocated in the ESP.
I frequently refresh the web (4 seconds) but most of the time the web doesn't upload anymore,
or just upload half of the website.

Few time it is working good.
anybody knows how this works ? or what I should do to fix this?
Thanks!

**Comment by devyte** [comment]
@queenbey91 you completely ignored the issue template. Also, this is an issue tracker, not a discussion forum.
Closing due to lack of info, see issue POLICY doc for more details.
