### ISSUE TITLE
wep, wpa upported?

### ISSUE THREAD

**Issue by michielbrink** [esp8266/Arduino#439]
Hello, at "ESP8266WiFi.cpp", I see this:
    int authmode = it->authmode;
    if (authmode == AUTH_OPEN)
        return ENC_TYPE_NONE;
    if (authmode == AUTH_WEP)
        return ENC_TYPE_WEP;
    if (authmode == AUTH_WPA_PSK)
        return ENC_TYPE_TKIP;
    if (authmode == AUTH_WPA2_PSK)
        return ENC_TYPE_CCMP;
    if (authmode == AUTH_WPA_WPA2_PSK)
        return ENC_TYPE_AUTO;

does that mean that I can connect to wep and wpa(1) networks?
I ask this because in the readme, there is only a function for open and wpa2 networks.

**Comment by me-no-dev** [comment]
yes :) you can connect to open, wep, wpa and wpa2 networks
