### ISSUE TITLE
arduino.esp8266.com is down

### ISSUE THREAD

**Issue by ProfFan** [esp8266/Arduino#4403]
### Description

Problem description

The site `arduino.esp8266.com` is down. Unable to retrieve the board definition and it also made current installations unusable.

**Comment by devyte** [comment]
I can't reproduce this. Must have been a transient.
Closing.

**Comment by sparklingsparklers** [comment]
Was also down for me when I last checked.

**Comment by igrr** [comment]
Was down between 20/02/2018 23:06:37 and 21/02/2018 01:27:37. Sorry for the trouble.
