### ISSUE TITLE
OAuth2

### ISSUE THREAD

**Issue by vicatcu** [esp8266/Arduino#441]
Can we get an example of using OAuth2 together with HTTPS to access an API without going through a proxy server like Temboo? Is that possible/practical with the ESP8266?

**Comment by cimba007** [comment]
Did you have a look at this OAuth1 implementation for Twitter+Arduino?

http://www.markkurossi.com/ArduinoTwitter/index.html

**Comment by vicatcu** [comment]
@cimba007 yes I had come across that in my google-fu, I'm not sure what the gap is between OAuth1 and OAuth2 though, nor if work has already been done on an implementation to that end.

**Comment by Links2004** [comment]
HTTPS is supported now,
you can use ```httpClient``` to make http or https requests

https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266httpClient/examples/BasicHttpClient/BasicHttpClient.ino
