### ISSUE TITLE
Question about WiFi.status() in AP mode

### ISSUE THREAD

**Issue by jguille2** [esp8266/Arduino#4431]
Hi,
As I've reported into [firmata/Arduino project](https://github.com/firmata/arduino/issues/392), I had problems using WiFi.status() in AP mode.

Is this function working properly?

Usual check ` WiFi.status() == WL_CONNECTED` is not right for AP mode. After connection (running ok and with IP stablished) _status_ is still not _WL_CONNECTED_. 

Thanks for all!!

Joan

**Comment by devyte** [comment]
WiFi.status() is meant to be used for the STA side, i.e.: it means "is the station side connected to some router?". It doesn't reflect anything about the softAP side, so it's no wonder that in AP mode it never returns WL_CONNECTED.
Closing as user error.
