### ISSUE TITLE
When ESP-01 start WiFi.mode(WIFI_AP_STA). The Web access page generates an error: CONNECTION_REFUSED

### ISSUE THREAD

**Issue by renancapano** [esp8266/Arduino#4441]
When I'm using the ESP8266 via web with it in AP mode, it works normally and in client mode as well. However when I activate AP + Client mode, web access generates a "CONNECTION_REFUSED" error.

If I go back to only one of the modes (AP or Client), the access returns to normal.
The Web Page is simple "HELLO WORLD".

Could you help me? Please!

**Comment by devyte** [comment]
The ESP has a single radio. If there is scanning being done on the STA side, or if the STA side is attempting and failing to connect to some router, then it drags the AP side along on channel hopping. When that happens, your client connected to the AP side will see the AP drop out (there is an outstanding issue about CSA beacons against Espressif SDK, but it's not fixed).

The only workaround is to set the AP channel to the same channel as the router that the STA side is trying to connect to. In that case, you'll see at most one dropout, and after recovery it'll be stable.

Having said the above, this type of question should not be made here. This is an issue tracker, not a general support forum for discussions. Please refer to esp8266.com or stackoverflow for that.
Closing as off topic, see issue POLICY doc for more details.
