### ISSUE TITLE
WiFi Connection Problem !

### ISSUE THREAD

**Issue by Rasoul-Khajavi** [esp8266/Arduino#4449]
#### Hardware
Hardware:       my own board built with exact schematic of esp-12 
Core Version:      	2.4

### Description

I just made my own pcb for esp8266 chip and i picked up all schematics from NodeMcu V1.0 .So Hardware is same as NodeMcu as far as i know ...
So here's the problem my codes works well with NodeMcu But when i upload it to my board every thing works except WiFi .
when i start esp as access point it shows in the wifi list of my phone but i can't connect to it . i think it can't assign ip for my phone
and again when i choose station mode and give it the right ssid and pass to connect my phone's hotspot that is near my board again it recognize all the stations around board but it can't connect to any of them . i've tested these with router and my laptop too .
So how can i fix this ?

- I've attached pcb schematic for double check .

[esp_board](https://user-images.githubusercontent.com/32794325/36858020-3aae7d26-1d8f-11e8-8f03-02ead693eb8d.PNG)

### Settings in IDE

Module:  			Esp8266 based board
Flash Size: 		1MB : W25Q80VSSIG
CPU Frequency:		80Mhz
Flash Mode:			qio
Flash Frequency:	      40Mhz
Upload Using:		    SERIAL
Reset Method:		  nodemcu

### Sketch

```cpp

#include <ESP8266WiFi.h>
#include <WiFiClient.h> 
#include <ESP8266WebServer.h>

/* Set these to your desired credentials. */
const char *ssid = "ESPap";
const char *password = "thereisnospoon";

ESP8266WebServer server(80);

/* Just a little test message.  Go to http://192.168.4.1 in a web browser
 * connected to this access point to see it.
 */
void handleRoot() {
	server.send(200, "text/html", "<h1>You are connected</h1>");
}

void setup() {
	delay(1000);
	Serial.begin(115200);
  Serial.setDebugOutput(true); 
  WiFi.setAutoConnect(false);

	Serial.println();
	Serial.print("Configuring access point...");
        ESP.eraseConfig() ;
        WiFi.disconnect() ; 
        WiFi.mode(WIFI_AP); // this stops the autoconnect
        WiFi.printDiag(Serial);
	/* You can remove the password parameter if you want the AP to be open. */
	WiFi.softAP(ssid, password);
	IPAddress myIP = WiFi.softAPIP();
	Serial.print("AP IP address: ");
	Serial.println(myIP);
	server.on("/", handleRoot);
	server.begin();
	Serial.println("HTTP server started");
}

void loop() {
	server.handleClient();
}
```

### Debug Messages

```
Configuring access point...Mode: AP
PHY mode: N
Channel: 1
AP id: 0
Status: 255
Auto connect: 1
SSID (0): 
Passphrase (0): 
BSSID set: 0
[AP] softap config unchanged
AP IP address: 192.168.4.1
HTTP server started
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
add 1
aid 1
station: 5c:93:a2:e3:34:49 join, AID = 1
wifi evt: 5
wifi evt: 7
station: 5c:93:a2:e3:34:49 leave, AID = 1
rm 1
wifi evt: 6
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
add 1
aid 1
station: 5c:93:a2:e3:34:49 join, AID = 1
wifi evt: 5
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
add 2
aid 2
station: 34:80:b3:f7:83:70 join, AID = 2
wifi evt: 5
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
!

wifi evt: 7
station: 34:80:b3:f7:83:70 leave, AID = 2
rm 2
wifi evt: 6
wifi evt: 7
wifi evt: 7
wifi evt: 7
WS:ac
:ref 1
WS:av
:ref 2
:ur 2
:ref 2
:ur 2
:rn 321
:c0 1, 321
:wr 83 83 0
:wrc 83 83 0
:wr 26 26 0
:wrc 26 26 0
:sent 83
:sent 26
:rcl
:abort
:ur 1
WS:dis 
:del  // at this point we see my laptop connected to it after some tryouts , and i searched 192.168.4.1 and http responded well . this happens maybe every 5 time . (4 time doesn't connects) 
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
add 2
aid 2
station: 34:80:b3:f7:83:70 join, AID = 2
wifi evt: 5
err already associed!
station: 34:80:b3:f7:83:70 leave, AID = 2
rm 2
max connection!
wifi evt: 6
max connection!
max connection!
max connection!
max connection!
max connection!
max connection!
max connection!  // But this happend when i wanted to connect to board with my phone .
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
wifi evt: 7
station: 5c:93:a2:e3:34:49 leave, AID = 1
rm 1
wifi evt: 6
wifi evt: 7
```

**Comment by RudyFiero** [comment]
Why do you think you can just make a PCB and have it work? How much experience have you had designing microwave circuits? Obviously none. It is not a simple thing. You don't know what you are doing. 

> I just made my own pcb for esp8266 chip and i picked up all schematics from NodeMcu V1.0 .So Hardware is same as NodeMcu as far as i know ...

This is not a code issue this is a poor hardware problem. Close the issue since it is not an Arduino code problem.

**Comment by devyte** [comment]
@Rasoul-Khajavi said:
> my codes works well with NodeMcu

That means that your issue is not code-related. Previous comment is correct: PCB design is not trivial when there are rf components involved.

Also, this is not the right place to ask questions about PCB design. This is an issue tracker for the core libs.

Closing.

**Comment by wadwin** [comment]
Hi all,
I have actived the debug wifi on my ESP8266
I see the same debug :

wifi evt: 7
add 1
aid 1
station: 00:b3:62:1e:fa:70 join, AID = 1
wifi evt: 5
wifi evt: 9
wifi evt: 7

I wonder where is the file who generate this debug.
Can somebody can help me please ?
