### ISSUE TITLE
client.readStringUntil and slow connections

### ISSUE THREAD

**Issue by holgerlembke** [esp8266/Arduino#445]
As far as I see, client.readStringUntil returns when finding the terminator char or the wait time of 1000 ms defined in stream.cpp elapsed.

Parsing.cpp of the webserver assumes, that by calling client.readStringUntil it delivers everything until the terminator.

This fails when wait time elapsed.

As a fix I raised the time, but that might not be a enough fix. What for even more slow lines...

line 85 and following:
    uint32_t contentLength = 0;
	// ???
	client.setTimeout(5000);
    //parse headers
    while(1){

**Comment by dilushan** [comment]
thanks for the useful info. I used this kind of solution

      tempMillis = millis();
      while (client.connected() && ((millis() - tempMillis) < 5000))
      {
        while (client.available())
        {
          line = client.readStringUntil('\r');
          tempMillis = millis();

        }

      }
