### ISSUE TITLE
How to create new root CAcert from format 00 01 02 03 to format of 0x00, 0x01, 0x02, 0x03

### ISSUE THREAD

**Issue by jtmoderate876** [esp8266/Arduino#4457]
@igrr  or anyone...

Newby to Certs question.
How are you guys converting the cert key we get in a browser:
00 01 02 03 ...

to the format used to assign the CAcert variable:
0x00, 0x01, 0x02, 0x03 ...
?

**Comment by igrr** [comment]
Search and replace, ' ' (space) to ', 0x' is one option, I guess.

Not sure if you would see the full certificate in the browser, usually it only shows the fingerprint.

**Comment by jtmoderate876** [comment]
thx
