### ISSUE TITLE
OneWire and pinMode as INPUT(_PULLUP)

### ISSUE THREAD

**Issue by jh1995** [esp8266/Arduino#447]
Since May 6th 2015, the pin chosen for OneWire communication has been changed from INPUT to INPUT_PULLUP mode. This breaks existing circuits and introduces a level of hardware randomness.

The OneWire bus specification requires a well defined pull-up resistor, 4k7. With the ESP8266 internal pullup active, the resistor value becomes chip dependant, somehow unknown and hard to define for complex installations with many 1wire slaves. Not counting that existing implementations with an external resistor need a hardware mod to work with newer code.

Please roll back the definition at line 122 in OneWire.cpp and restore pinMode as INPUT. Then add an optional parameter, a function() or a #define that lets the programmer override the default INPUT value.

Thanks.

**Comment by igrr** [comment]
Parameter added in esp8266-1.6.5-804-g2d340c7.
