### ISSUE TITLE
How can I send analog signals to server fast  with d1 mini pro?

### ISSUE THREAD

**Issue by wujiu59** [esp8266/Arduino#4489]
I want to use d1 mini pro to catch signal and send data to server.
this is my code:

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
const char* ssid     = "*****";
const char* password = "*****";
const uint16_t port = 80;
const char * host = "192.168.0.1"; 
char x[]=" ";
ESP8266WiFiMulti WiFiMulti;
void setup() {
    Serial.begin(115200);
    delay(10);
    WiFi.mode(WIFI_STA);
    WiFiMulti.addAP(ssid, password);
    Serial.println();
    Serial.println();
    Serial.print("Wait for WiFi... ");
    while(WiFiMulti.run() != WL_CONNECTED) {
        Serial.print(".");
        delay(500);
    }
    Serial.println("");
    Serial.println("WiFi connected");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());
    delay(500);
}
void loop() {
    WiFiClient client;
    if (!client.connect(host, port)) {
        Serial.println("connection failed");
        return;
    }
    for(int i=0;i<150;i++){
    int sensorValue = analogRead(A0);
    client.print(String(sensorValue)+x); 
    }   
    client.stop();
    delay(1000);
}

I know when it sending data , read A0 is stop.
Is there a better way to shorten the delivery time?
Because I want the signal to be continuous and complete

**Comment by philbowles** [comment]
> I know when it sending data , read A0 is stop.

...because it is in an exclusive loop doing something else. you need to write your program asynchronously

> Is there a better way to shorten the delivery time?

Yes, write your program asynchronously

> Because I want the signal to be continuous and complete

Learn to write your program asynchronously

PS this is NOT a forum for programming advice so you will have to go somewhere else to get more detail
