### ISSUE TITLE
Implement SPISlave.end()

### ISSUE THREAD

**Issue by svofski** [esp8266/Arduino#4511]
My use case is simple: I have a system where devices change roles. ESP begins being a master and configures an FPGA, which then takes over as a master, and ESP becomes a slave. Later on, a firmware update may require this process to repeat, etc. SPI bus role reversal is not very typical, but completely possible, especially with pin shortage or tightness of PCB estate.

A PR for this request: https://github.com/esp8266/Arduino/pull/4248

**Comment by devyte** [comment]
Per @Tech-TX:
Closing due to #4248 already merged.
