### ISSUE TITLE
Feature Request:  Make MDNS _getServiceTxt(char *name, char *proto) public

### ISSUE THREAD

**Issue by chadham** [esp8266/Arduino#4521]
Need to be able to query serviceTextRecord attributes, method is currently private.

Thanks.

**Comment by devyte** [comment]
Are you aware of pr #3107 ?

**Comment by chadham** [comment]
Was not. Seems like it would be simpler to make the existing method public, no?

**Comment by mblythe86** [comment]
I think you misunderstand what _getServiceTxt is doing.  That method is used by the responder to send any Txt records you've added with addServiceTxt to others on the network (i.e. when someone else does a query).  That's all you'd be able to see from the method...what you've already added.

Without #3107, Txt records on responses to your queries are simply discarded.

**Comment by chadham** [comment]
Im looking for a way to get the txt records for a discovered service... (not for txt records I added to the service Im broadcasting)

**Comment by mblythe86** [comment]
> Im looking for a way to get the txt records for a discovered service... (not for txt records I added to the service Im broadcasting)

Ok, then you need #3107.  Just making _getServiceTxt pulic won't get you what you want.

**Comment by devyte** [comment]
Closing in view of #5442 with a full rewrite of mdns.
