### ISSUE TITLE
Error Nodemcu - upload mem

### ISSUE THREAD

**Issue by gorlol3** [esp8266/Arduino#4524]
Good afternoon friends,

I come to ask for help for a "common" error, the: espcomm_upload_mem failed.
I saw that others had the problem, but I could not solve it by using the responses of others.

Nothing is connected to the board.

Someone to help?

![sem titulo](https://user-images.githubusercontent.com/37447394/37526528-62d9535e-290e-11e8-8f3d-47d462d873fa.png)

**Comment by devyte** [comment]
Not the right place to ask this. It essentially means you have problems with the selected serial port.
Closing.
