### ISSUE TITLE
Implement I2C slave

### ISSUE THREAD

**Issue by Sorunome** [esp8266/Arduino#455]
Hey,
It would be awesome if you could implement the slave mode for I2C connections!

**Comment by chadouming** [comment]
This is not an issue, ask your question in relevant part of the forum : [Forum](http://www.esp8266.com/viewforum.php?f=25&sid=f82e14927b91bb1b964c93878ef5b1c5)

**Comment by igrr** [comment]
Closing in favor of #1330
