### ISSUE TITLE
uart_rx_fifo_available considerations

### ISSUE THREAD

**Issue by d-a-v** [esp8266/Arduino#4565]
According to @jasoroony's [comments](https://github.com/esp8266/Arduino/commit/f8f205d54af42f34502ad011fd015e104b63d911#r28247221) and after checking the doc, it appears that:

```
inline size_t uart_rx_fifo_available(uart_t* uart) {
     return (USS(uart->uart_nr) >> USRXC) & 0x7F;
}
```

should be:

```
inline size_t uart_rx_fifo_available(uart_t* uart) {
     return (USS(uart->uart_nr) >> USRXC) & 0xFF;
}
```

[reference](https://www.espressif.com/sites/default/files/documentation/esp8266-technical_reference_en.pdf) section 11.3.7:
```
Rx fifo length:
(READ_PERI_REG(UART_STATUS(UART0))>>UART_RXFIFO_CNT_S)&UART_RXFIFO_CNT;
```
where 
```
tools/sdk/include/uart_register.h:#define UART_RXFIFO_CNT 0x000000FF
```
(both ```USRXC``` and ```UART_RXFIFO_CNT_S``` are 0)

**Comment by jasoroony** [comment]
Good work guys, the new commit works perfectly with all my serial tests, including a simulated DOS attack while WiFi is on.  I did see my S/W buffer as high as 900 characters during that, but it's still running and no errors were detected in the Serial stream.

**Comment by d-a-v** [comment]
Thanks for your feedback !

**Comment by sarfata** [comment]
Just wanted to add a comment here to say that this change fixes a crash in [my project](https://github.com/sarfata/kbox-firmware/) that was very easy to reproduce when there is sufficient messages being sent to the ESP8266 serial port.

With the new version of `uart.c`, I have not been able to reproduce the crash after hours of testing where before it would usually crash in 15 minutes (with load). The symptom was a hardware watchdog timer crash with epc in `uart_isr`.

🙇 🤗 🎁
