### ISSUE TITLE
wifi_get_phy_mode returns wrong mode

### ISSUE THREAD

**Issue by v-a-d-e-r** [esp8266/Arduino#4566]
I'm using current core 2.4.1+ and wifi_get_phy_mode return 'N' (mode 3), but it is in real only connected with 'G' to the AP.

**Comment by devyte** [comment]
wifi_get_phy_mode is an SDK api. We have no control over its functionality in this repo. If it is misbehaving, you should open an issue at Espressif's NONOS sdk repo.
Also, you completely ignored the issue template.
Closing.
