### ISSUE TITLE
Node Mcu, Wemos mcu wifi reset not working as expected. 

### ISSUE THREAD

**Issue by kotran88** [esp8266/Arduino#4577]
It's weird. 
I'm using 2 Wemos Mcu. 
Once those 2 wemos is connected. I want to disconnect one. (all are connected to same wifi said)

I reset it with below code

wifiManager.resetSetting();
delay(1000);
ESP.reset()

then, Serial monitor said below. 

*WM: settings invalidated
*WM: THIS MAY CAUSE AP NOT TO START UP PROPERLY. YOU NEED TO COMMENT IT OUT AFTER ERASING THE DATA.

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
I think I could connect it again right after reset .
 but can't see mcu's wifi to connect.

**Comment by devyte** [comment]
@kotran88 you ignored the issue template. It exists for a reason.
This repo does not host WiFiManager, the repo for that is [here](https://github.com/tzapu/WiFiManager).
Closing due to lack of info.
