### ISSUE TITLE
How to program with ESPFlashDownloadTool_v3.6.3.exe

### ISSUE THREAD

**Issue by gioreva** [esp8266/Arduino#4580]
I do not receive an answer on the express forum.
https://bbs.espressif.com/viewtopic.php?f=7&t=9399

What is the correct method for programming a schetch using ESPFlashDownloadTool ?
The CPU system restarts continuously.

**Comment by devyte** [comment]
This is an issue tracker for the Arduino core, not a support forum. I suggest readthedocs.
Closing, see issue POLICY doc for more details.
