### ISSUE TITLE
TCP Communication problems in new versions

### ISSUE THREAD

**Issue by xhdix** [esp8266/Arduino#4581]
I don't know what made this happen. And what changes have you made In the new versions.
The problem is getting data from Android. (android code:  DOS.writeChars("commandSample") )
Each character transfer also adds a ```null``` character.

I solved this issue in my program.
In this way:

```cpp



  for(i = 0; i < MAX_SRV_CLIENTS; i++){
    if (serverClient[i] && serverClient[i].connected()){
      if(serverClient[i].available()){
        while(serverClient[i].available()) { 
          char inChar = (char)serverClient[i].read();


		  if (inChar != '\0') {        //  I added this line to solve the problem.. *************


			  tlinstr += inChar;
			  if (inChar == '\n') {
				tlntstrCmplt = true;
			  }

                 }
        }
      
      }
      
    }
  }
  
  

```

Maybe this solution will reduce debug time for somebody's. :)

**Comment by mittaldivya01** [comment]
Hello, can you please guide on how can we connect to an IP address.. 
Thank you!!

**Comment by devyte** [comment]
Issue template ignored, none of the required info provided, no MCVE sketch.
Closing.
