### ISSUE TITLE
Will we get the updated version of this Library for ESP32??

### ISSUE THREAD

**Issue by GitAyush** [esp8266/Arduino#4589]
I love this library and it really helps me to use the full potential of my ESP. But recently i have planned to get a upgraded version of ESP i.e. ESP32 and it would be very helpful if we had a updated version of this library, So that i can convert my old code to work on the new ESP32. I know there are other library that works with esp32 but then i think i would have to change a large portion of my code. And i really dont want to do that.
Please help me out.

**Comment by devyte** [comment]
The Arduino core for the ESP 32 is hosted elsewhere.
