### ISSUE TITLE
WiFiTelnetToSerial mentions Serial1

### ISSUE THREAD

**Issue by probonopd** [esp8266/Arduino#459]
WiFiTelnetToSerial mentions Serial1 but to the best of my knowledge ESP modules only have 1 pair of serial pins, so that would be Serial and not Serial1. Commenting out everything related to Serial1 in the WiFiTelnetToSerial sketch seems to make to difference (i.e., it still works as it should).
So I think all references to Serial1 in WiFiTelnetToSerial can be deleted in order not to confuse people, what do you think?

**Comment by igrr** [comment]
Serial1 is available on ESP, please check Readme.

**Comment by probonopd** [comment]
Sorry, my wrong. These ESP chips are wonderful!
