### ISSUE TITLE
Error downloading http://arduino.esp8266.com/stable/package_esp8266com_index.json

### ISSUE THREAD

**Issue by juztinfied** [esp8266/Arduino#4592]
Does anyone have any issues with the board manager for WE MOS D1 R2 ESP8266? The board now does not even appear on my IDE list of arduino boards

**Comment by devyte** [comment]
Works for me.
Closing as can't reproduce.

**Comment by zcattacz** [comment]
Can't Open it Now.

**Comment by devyte** [comment]
Still works for me.

**Comment by zcattacz** [comment]
HTTP error code 416.   Arduino IDE's download manager is to blame. 

https://github.com/arduino/Arduino/issues/6628

**Comment by MuhammadShoaibJahangir** [comment]
The issue with the boards disappearing is definitely a bug with the Arduino IDE. You can get the boards back by:
https://github.com/esp8266/Arduino/releases/download/2.3.0/package_esp8266com_index.json

to File > Preferences > Additional Boards Manager URLs
Tools > Board > Boards Manager
Wait for downloads to complete.
Click "Close" (don't install the ESP8266 boards, you already have them installed)
The ESP8266 boards will now appear in your Tools > Board menu again.
