### ISSUE TITLE
'Serial2' was not declared in this scope

### ISSUE THREAD

**Issue by iemektar** [esp8266/Arduino#4606]
I have Arduino Mega 2560, esp8266-01, gps and bluetooth modules. I need to use 3 serial ports but when i try use them i'm taking " Serial2 was not declared in this scope" error.

I try to fix it but I couldn't. Can you help me?

[Board](https://i.hizliresim.com/dOgRaL.png)

[Error&Code](https://i.hizliresim.com/bB7WaV.png)

**Comment by devyte** [comment]
Your links are bad, and I'm actually getting warned about malware.
Closing due to lack of info.
