### ISSUE TITLE
multiple definition of `_putc_r'

### ISSUE THREAD

**Issue by trlafleur** [esp8266/Arduino#4630]
See issue defined below....
tested with 2.4.0 and 2.4.1
~~~
https://github.com/grzesl/ESPMail/issues/4
~~~

~~~
C:\Users\anonymous\AppData\Local\Temp\arduino_build_962164/arduino.ar(libc_replacements.c.o): In function `_putc_r:

C:\Users\anonymous\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\cores\esp8266/libc_replacements.c:96: multiple definition of `_putc_r'

C:\Users\anonymous\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0/tools/sdk/libc/xtensa-lx106-elf/lib\libc.a(lib_a-putc.o):/Users/igrokhotkov/e/newlib-xtensa/xtensa-lx106-elf/newlib/libc/stdio/../../../.././newlib/libc/stdio/putc.c:97: first defined here

collect2.exe: error: ld returned 1 exit status

~~~

**Comment by igrr** [comment]
Thanks for reporting this! Started investigating this and found another bug: `printf` returns `-1` instead of the number of characters written, when writing to the console.

**Comment by Komse** [comment]
Hi, I had the same issue. I needed to remove the "#include <iostream>" to compile.

**Comment by cristianCarrerasCastillo** [comment]
remover of what file? @Komse

**Comment by Komse** [comment]
Oh yes sorry, to remove the "#include <iostream>" @cristianCarrerasCastillo

**Comment by shineangelic** [comment]
+1 on this. I didn't get what "#include" I shall remove, thanks

**Comment by Komse** [comment]
For me it was the iostream include @shineangelic

**Comment by shineangelic** [comment]
thank you @Komse but that did not help. I have other weird linking errors as reported in #4663

**Comment by shineangelic** [comment]
I was able to solve this commenting out _put_c method already defined in "tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\"
