### ISSUE TITLE
Help me<loading firmware to ESP01> thankss very much....

### ISSUE THREAD

**Issue by hotkpop** [esp8266/Arduino#4645]
when i try to upload firmware  to esp01 from Arduino IDE,  I get a error :
__Erasing 0x80000 bytes starting at 0x00000000
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_BEGIN) failed
An error occurred while uploading the sketch__
i used USB TTL for uploading 
Thanks!

**Comment by hotkpop** [comment]
No. So what is it.? i'm a newbie .

**Comment by Pablo2048** [comment]
So do it again and try to understood this time...

**Comment by hotkpop** [comment]
i'm so sory, i don't known what is your mean. the template for this topic or for esp. so sory.

**Comment by Pablo2048** [comment]
When you create the issue, you have to read the given template (you simply delete it). It starts with:

> If your issue is a general question, starts similar to "How do I..", is related to 3rd party libs, or is related to hardware, please discuss at a community forum like esp8266.com.

Your subject literally starts with that and you give no zero informations about your configuration (ide, core, ...).... you should try the forum first (even the newbie can read right?)

**Comment by hotkpop** [comment]
i'm sory. i didn't notice that. and i will delete . my fault.

**Comment by Pablo2048** [comment]
;-) IMO you can't delete the issue - just close it...

**Comment by hotkpop** [comment]
after close it, i really want to connect with you. if you don't mind, can i do that? 
contact with me nguyenmanh2080@gmail.com .?
