### ISSUE TITLE
Incorporating new boards to the boards.txt

### ISSUE THREAD

**Issue by lazyzero** [esp8266/Arduino#4653]
Hello I am writing here to ask how to get a board to the boards.txt?

I ask because I like to have the Kniwwelino (kniwwelino.lu) to be included into the official list of boards.

Best Christian

**Comment by d-a-v** [comment]
You need to update the generator in ```tools/boards.txt.py```.

**Comment by devyte** [comment]
Is the boars distinct in its hw from all other boards? I.e.: can you select nodemcu and it will work?
If the board is essentially a clone of another board, then it probably shouldn't be added. If it has differences from other boards, e.g. different flash mode, or different pinouts, etc, then you can make a pr with the modifications to boards.txt.py and the new generated boards.txt.
Closing.
