### ISSUE TITLE
Problem with WifiMulti

### ISSUE THREAD

**Issue by trap98** [esp8266/Arduino#4657]
Hey, I have a problem with the WifiMulti since I switched to version 2.4.1 of SDK. So I tested the example available in master/libraries/ESP8266WiFi/examples/WiFiMulti but it does not work either.
Does anyone have a solution to this problem?

**Comment by devyte** [comment]
@trap98 when you opened this issue, you were presented with an issue template that has specific instructions. It exists for a reason, but you completely ignored it.
Closing due to lack of info. Feel free to open a new issue, and fill out the requested info.
