### ISSUE TITLE
scanf / printf : Enabling 8-bit types

### ISSUE THREAD

**Issue by GiovanniCmpaner** [esp8266/Arduino#4660]
Hello everyone!

I need 8-bit types ("hh" length specifiers) when using scanf / printf, but they aren't enabled by default.

I could conclude it by looking at the headers:
```
inttypes.h
stdint.h
stdio.h
newlib.h
```
and noted the macro`_WANT_IO_C99_FORMATS` must be defined to enable them.

Reading the docs [https://sourceware.org/newlib/README](https://sourceware.org/newlib/README), before I compile the newlib, I must configure it with the flag `--enable-newlib-io-c99-formats`, but I don't know how to proceed, where I should do it, how to compile it, I couldn't easily find information about this.

Is there a "simpler"/"easier" way to enable 8-bit types?

**Comment by earlephilhower** [comment]
We don't compile with the full-fat IO types due to code and RAM usage limits, but it may be possible to hack in half-width types at some point

**Comment by GiovanniCmpaner** [comment]
To add some context, it would be especially useful when receiving IPv4 address, as I can't simply switch to int because the (ethernet, wifi) libraries expect byte vectors.
Right now, the simplest way is to convert the int vector to byte vector in a few lines, not that bad.
But thanks for answering after such a long time.

**Comment by GiovanniCmpaner** [comment]
I didn't think it would be done. Thanks for the improvement.
