### ISSUE TITLE
GET or POST from esp8266

### ISSUE THREAD

**Issue by VAIBHAVHEGDE** [esp8266/Arduino#4662]
I am trying to connect to an EC2 server using arduino and ESP8266.
I am using AT commands
I get protocol mismatch error when i use 
GET http://servername/e.php HTTP/1.1

![capture](https://user-images.githubusercontent.com/35395147/39079265-90934286-4534-11e8-8d4b-819116d66b34.PNG)

**Comment by devyte** [comment]
This repo has nothing to do with the AT firmware. You're in the wrong place.
Closing.
