### ISSUE TITLE
Flashing successful, but code doesn't run

### ISSUE THREAD

**Issue by kolorowezworki** [esp8266/Arduino#4664]
- Hardware:				ESP-01
- Development Env:		Arduino IDE
- Operating System:		[Windows|Ubuntu|MacOS]

- Module:  			Generic ESP8266 Module
- Flash Mode:			qio
- Flash Size: 		        1MB
- lwip Variant:                  v2 Lower Memory
- Reset Method:		ck
- Flash Frequency:	        40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:              115200

### Problem Description

I just want to make my ESP-01 working with any arduion sketch. Flashing ends successfull every time, but program seems to not working after restart. It dump only bootloader info to serial (74880 speed):

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0xef
csum 0xef
csum err
ets_main.c 

I bring device into flash mode connecting GPIO0 to GND, and after flashing, I power off it, connect GPIO0 to 3,3 and power on. Only thing I see in serial moniotor is above bootloader info. What I'm doing wrong? I have tested it on 3 ESP-01 devices.

**Comment by WereCatf** [comment]
Begin by trying to set flash mode to dout instead and seeing if that fixes it. Also, this isn't the place to ask for general help; if you still can't get it working, go to esp8266.com and ask for help there.

**Comment by devyte** [comment]
Closing.
