### ISSUE TITLE
Reset after wifi reconnection - Exception (29)

### ISSUE THREAD

**Issue by rufinosilverio** [esp8266/Arduino#4666]
### Basic Infos
Hi everyone! I got Exception (29) in my NodeMcu V1.0 when trying to reconnect to the server.
The problem happens after a Wifi disconnection. When ESP reconnect to Wifi, it give me a Exception (29) and: ets Jan  8 2013,rst cause:2, boot mode:(1,6) and sometimes: ets Jan  8 2013,rst cause:2, boot mode:(3,6).

I read many issues here, but I didnt find solution for my problem. 
I am new with ESP8266, so I ask you patience! 

I read about power source for ESP8266 but I didnt find tips for NodeMcu V1.0, and I dont know if this problem is related to the power source.

Thank you in advance.

#### Platform

- Hardware: NodeMcu 1.0 [ESP-12E]
- Development Env: Arduino IDE
- Operating System: Windows

### Settings in IDE

- Module:  NodeMcu 1.0 [ESP-12E]
- Flash Size: 4MB/3MB
- lwip Variant: v2 Lower Memory
- CPU Frequency: 80Mhz
- Upload Using: Serial
- Upload Speed:  115200

### Sketch

#include <ESP8266WiFi.h>
#include <SPI.h>
#include <MFRC522.h>
#include <EEPROM.h>

void setup()
{
Serial.begin(115200);
delay(100);

EEPROM.begin(EEPROM_ALOC_RANDOM);
for (int n=0; n<13; n++){
ID_EEPROM[n] = EEPROM.read(n);
ID_STR += String(ID_EEPROM[n]);
}

Serial.print("ID: ");
Serial.println(ID_STR);
ID_STR = "";

if (ID_EEPROM[0] != 33) {

  ID_BYTE[0] = 33;//! em ascii
  ID_BYTE[1] = 48;//0 em ascii
  ID_BYTE[2] = 58;//: em ascii

  for (int g = 0; g < 10; g++){
       ID_BYTE[g+3] = random(16);
  }
 
  for (int g = 0; g < 13; g++){
      EEPROM.write(g,ID_BYTE[g]);        
  }    
}

for (int n=0; n<3; n++){
ID_EEPROM[n] = EEPROM.read(n);
ID_STR += char(ID_EEPROM[n]);
}

for (int n=3; n<13; n++){
ID_EEPROM[n] = EEPROM.read(n);
ID_STR += String(ID_EEPROM[n], HEX);
}

ID_STR += ";";
ID_STR.toUpperCase();
Serial.print("ID Final: ");
Serial.println(ID_STR);
EEPROM.end();

AguardaServidor();
}

void loop()
{
yield();
RCV_STR = "";

if (WiFi.status() != WL_CONNECTED) {
if (TAP_FUN == "R"){
SPI.end();
Serial.println("SPI ended");
}
TAP_FUN = "";
AguardaServidor();
return;
}

delay(0);
if (!client.connected()) {
if (TAP_FUN == "R"){
SPI.end();
Serial.println("SPI ended");
}
TAP_FUN = "";
AguardaServidor();
return;
}
}

void AguardaServidor(){

Tenta_Cont = 0;
while (TAP_FUN == ""){

    if (WiFi.status() != WL_CONNECTED) {
        WiFi.disconnect(true);
        Serial.print("Sem conexão rede Wifi: ");
        Serial.println(ssid);  
        Serial.print("WiFi.status(): ");
        Serial.println(WiFi.status());  
        delay(1000);
        yield();
        reconnectWifi();
    }

    while (WiFi.status() == WL_CONNECTED & !client.connected()) {
        Serial.println("Sem conexão com servidor");
        delay(100);
        
        if (!client.connect(host, port)) {
            delay(100);
            Serial.println("Falha na conexão");
        }

        delay(2000);
        
        if (client.connected()) {
            Serial.println("Conexão com servidor estabelecida");
        }
        
    }
    
    if (WiFi.status() == WL_CONNECTED & client.connected()) {
        delay(100);
        Tenta_Cont += 1;
        Serial.println("Conectado! Solicitando Função, Tentativa " + String(Tenta_Cont));
        client.print(ID_STR);
        yield();
        RecebeServidor(); 
    }
    yield();
    delay(1000);
    
    if ((millis() - Print_Tmr) > 5000){
        client.print("#");
        Print_Tmr = millis();  
    }

    if (Print_Tmr > millis()){Print_Tmr = 0;}
}
Serial.print("Função: ");
Serial.println(TAP_FUN);
}

void reconnectWifi() {

if (WiFi.status() != WL_CONNECTED) {
WiFi.begin(ssid, pass);
Serial.println("Tentando conectar");
delay(10000);
}

if (WiFi.status() == WL_CONNECTED) {
Serial.println("Conexão estabelecida!");
WiFiClient client;
Serial.println("WiFi conectado com endereço IP: ");
Serial.println(WiFi.localIP());
delay(100);
}
}

### Debug Messages

Exception (29):
epc1=0x4020c67c epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffcd0 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffe70:  3fff1868 00000000 00000000 fffffffb  
3ffffe80:  3fff03c4 3fff03c4 00000000 4020d518  
3ffffe90:  3ffeef2c 00000267 00000267 fffffffb  
3ffffea0:  3fff03c4 00000000 3fff03c0 4020c72d  
3ffffeb0:  40000f68 3ffe9088 3fff03c0 4020fae4  
3ffffec0:  00000000 00000007 3fff1524 4020f571  
3ffffed0:  3ffe9088 3ffe9088 3fff03c0 4020fb12  
3ffffee0:  00000000 3fff03c0 3fff1524 40212034  
3ffffef0:  0100a8c0 3fffdcb0 3ffee650 4020cb7c  
3fffff00:  00000000 3fff03c0 3fff1524 40212087  
3fffff10:  4020d9a0 3fff001c 3fff04e4 40100690  
3fffff20:  40227842 00000000 0000002d 3fff0018  
3fffff30:  4020d9a0 3fff001c 3ffe901c 4020d9ae  
3fffff40:  40104d7e 04a3db39 00000009 4020da6c  
3fffff50:  3ffe901c 3ffede18 04a3db39 00000000  
3fffff60:  4022c050 3ffee618 3ffee640 60000600  
3fffff70:  0ed9ba5d 3ffee640 3ffee618 4022c05d  
3fffff80:  4022c0a2 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffee658 3fffdab0 00000000 40205ca3  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld

**Comment by devyte** [comment]
Your sketch is incomplete, your use of markup is messed up, your stack dump is not decoded, some fields requested in the issue template are missing, like the core version used.
I suggest opening a new issue and reading through the template as well as the issue POLICY doc carefully. Be aware that this is not a support forum for your particular project, but an issue tracker for the core libs. Open an issue if you think there is a problem in the code hosted in this repo. If your problem is that you can't get you project to work, you should seek help at a community forum like esp8266.com or stackoverflow.
Closing due to lack of info.
