### ISSUE TITLE
MQTT TLS/SSL not working

### ISSUE THREAD

**Issue by dejanra** [esp8266/Arduino#4669]
MQTT TLS/SSL not working in v 2.4.1., but working in v2.4.0 rc1

**Comment by Pablo2048** [comment]
So what?... Why, why you totally ignored issue template?

**Comment by xnorbi** [comment]
You have to set lwIP variant to v1.4 Compile from source, the default is not working for me (others not tested). In v2.4.0 or v2.4.1

See: https://github.com/esp8266/Arduino/issues/4624
