### ISSUE TITLE
Trying to send char data to my node js server

### ISSUE THREAD

**Issue by kotran88** [esp8266/Arduino#4679]
Basic Infos

Hardware

Hardware: ESP-12E
Core Version: ?2.1.0-rc2?

Description

I am trying to send some raw data to another host running. 
It definitely connected to my server well because I can't see connection failed on Serial monitor. 

but when checked my server logs, didn't get any raw data from Arduino. 

Settings in IDE

Module: ?Arducam ESP8266 1.0 (ESP-12E module)?

Sketch

      #include <Arduino.h>
     #include <WiFiClient.h>

      void setup() {
        WiFiClient client;
        Serial.print("connecting to ");
        Serial.println(host);
        if (!client.connect(host, port)) {
           Serial.println("connection failed");
           return;
        }
        Serial.println("connected to ");
        Serial.println(host);

        char msg[10] = "123456789";
        //client.println(msg);
        client.write((const uint8_t *) msg, 10);
        client.stop();
       }

       void loop() {

      }

Sketch for My Node js Server. 
actually...I don't know how to receive data from Arduino....
If someone can advise me, please tell me. 

I don't know to use socket.io...because I'm making product for sale...
if I use socket.io... node server is for only one device. 

      http = require('http');
      fs = require('fs');
      var express=require('express');
      var app=express();
      const request = require('request');
       var router = express.Router();
  
    var server = http.createServer( function(request, response) {
      console.dir("param is : "+request.param);
      console.log(request.method);
      response.setHeader("Content-Type", "text/html");
      response.writeHead(200);
      response.write('<html><head><title>Simple HTTP Server</title></head>');
      response.write('<body>');
         for (var idx in  messages){
           response.write('\n<h1>this is page</h1>');
          }
        response.end('\n</body></html>');

        if (request.method === 'POST') {
       

      
      } else {
        response.statusCode = 404;
        response.end();
      }
   
    });

      server.listen(process.env.PORT || 13339, function () {
        var port = server.address().port;
       console.log("EEEEEExpressss is working on port " + port);
      });

`

**Comment by devyte** [comment]
@kotran88 Your sketch is incomplete, there is no WiFi setup. Given that the code is inside setup, it will only execute once, and never again until reboot.
You said:
> actually...I don't know how to receive data from Arduino

This is not a general support forum. I suggest seeking help at a community forum like esp8266.com or stackoverflow.
