### ISSUE TITLE
port of the TSL2561 library: 2 small compile errors and incorrect output

### ISSUE THREAD

**Issue by hamishcunningham** [esp8266/Arduino#468]
Fantastic project! Thanks!

We tried to port the TSL2561 light sensor library from https://github.com/adafruit/TSL2561-Arduino-Library

It will compile if the include statement for "avr/pgmspace.h" is replaced with "pgmspace.h" and the
"delay.h" include commented out.

The results from the example sketch differ from those running on an Arduino Uno though -- we get lux values of 3 or 4 (rather than 500 or 1000 on the Uno).

Any ideas why this might be? Some difference in number of bits read, or integer type sizing? Or perhaps differences between delay(mS) on the ESP and the Uno?

The code as compiled is here: https://github.com/hamishcunningham/fishy-wifi/tree/master/ardesp/Arduino/libraries/TSL2561
##

**Comment by devyte** [comment]
The referenced link is 404.
Closing du to 3rd party lib and age.
