### ISSUE TITLE
esp8266wifi library

### ISSUE THREAD

**Issue by farahammar** [esp8266/Arduino#4692]
how can i download esp8266wifi library ?

**Comment by WereCatf** [comment]
Change your WiFi-password and your MySQL-password, you just posted them online and someone has definitely grabbed them already!

**Comment by farahammar** [comment]
what do you mean   WereCatf ??

**Comment by WereCatf** [comment]
Look at the sketch you posted, the passwords are right there, visible to 
anyone who reads your sketch! Always remove passwords from any sketches you 
post anywhere!

It's too late now, though, the passwords are on the internet now. Go change 
your passwords.

On 28. huhtikuuta 2018 0.25.26 farahammar <notifications@github.com> wrote:
what do you mean WereCatf ??

**Comment by devyte** [comment]
@WereCatf I don't see a sketch, in this current issue or in the original email notification. What did you see? (Gitter, not here)

**Comment by WereCatf** [comment]
@devyte He seems to have removed the sketch as you can see the post has been edited. In the original post he did have a sketch pasted, which included his WiFi- and SQL-credentials, plus the IP-address to the SQL-server itself. The server was accessible from the Internet, or at least it was responding to ping-requests.
