### ISSUE TITLE
How do I flash ESP8266 S3 chip with Tasmota firmware

### ISSUE THREAD

**Issue by gsksim** [esp8266/Arduino#4699]
Trying to flash ESP8266 S3 chip with sonoff Tasmota firmware so I can use it to control using Home assistant.

#### Platform

![image](https://user-images.githubusercontent.com/38599641/39403402-1a1aabf6-4b49-11e8-9ae7-61c5bcaeafa0.png)

- Hardware:				ESP8266 S3 - https://fccid.io/2AKBPESP8266-S3/Users-Manual/User-Manual-3594791
- Core Version:			[latest git hash or date]
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

![image](https://user-images.githubusercontent.com/38599641/39403370-6a90f5fa-4b48-11e8-8730-664c2b4f0f02.png)

With the help of datasheet able to identify VCC, GND, TX and RX Pins on the board and soldered the wires to connect the board to FTDI. Before start uploading the code, I have connected board to PC while connecting GPIO0 pin to ground, which seems board entered flash mode but not sure. if I connect the board without grounding GPIO0 then board starts normally and LED blinks but with grounding LED stays ON.

Getting this error
esptool v0.4.13 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to nodemcu
	setting baudrate from 115200 to 115200
	setting port from COM1 to COM9
	setting address from 0x00000000 to 0x00000000
	espcomm_upload_file
	espcomm_upload_mem
	setting serial port timeouts to 1000 ms
opening bootloader
resetting board
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

**Comment by devyte** [comment]
The issue template starts with:

> If your issue is a general question, starts similar to "How do I..", is related to 3rd party libs, or is related to hardware, please discuss at a community forum like esp8266.com.

Your title literally starts with How do I...
Closing.
