### ISSUE TITLE
WiFi in station mode does continuously reconnect to configured WLAN network every few seconds

### ISSUE THREAD

**Issue by Schawen** [esp8266/Arduino#4704]
#### Platform

- Hardware:			ESP-01
- Core Version:			2_4_1
- Development Env:		Arduino IDE
- Operating System:		Windows

MCU Info:
--------------------
Last Reset Reason : External System
CPU frequency in MHz : 80
ESP Chip-ID : 2012694
ESP Flash-Chip-ID : 1327328
ESP Flash-Chip-Size : 1048576
ESP Flash-Chip-Speed : 40000000
ESP Core Version : 2_4_1
ESP SDK Version : 2.2.1(cfd48f3)

### Settings in IDE

- Module:  			Generic ESP8266 Module
- Flash Mode:			qio
- Flash Size: 		       1 MB]
- lwip Variant:                  v2 Lower Memory
- Reset Method:		ck
- Flash Frequency:	        40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:               115200

### Problem Description

WiFi in station mode does continuously reconnect to configured WLAN network every few seconds.
Reconnection works immediately - so, what's the reason ...

bcn_timout,ap_probe_send_start
ap_probe_send over, rest wifi status to disassoc
state: 5 -> 0 (1)
rm 0
pm close 7
wifi evt: 1
STA disconnect: 200

The complete sketch has become very large, so I just added the loop and sensor section.
Hope somebody can help to find the reason for this behaviour.
How to debug this problem without wireshark and test network?

###  Sketch

```cpp

**Comment by Pablo2048** [comment]
Your example is a crap. Probably no one will waste his time to do something with this piece of s**t, until You put some effort to make valid MCVE...

**Comment by Schawen** [comment]
Thank you, Pablo2048.
This only happens in station mode, not in AP mode and it occures with or without user action.
I should probably follow the network approach ...

**Comment by Pablo2048** [comment]
Well, where in Your code is WiFi STA initialization? How, do You think, anybody can help when You give only setup(){}?

**Comment by Pablo2048** [comment]
Still didn't compile. Did you try to compile this, or are you too lazy? BTW this is not MCVE - please create one ( https://stackoverflow.com/help/mcve )

**Comment by Schawen** [comment]
No it does not compile.
My original intention was to ask about how to debug such problems with WiFi and wther there is or not

**Comment by Pablo2048** [comment]
> My original intention was to ask about how to debug such problems with WiFi and wther there is or not
For asking this kind of questions there is forum on esp8266.com . This is Core issue tracker (as you have been informed in issue template).

**Comment by Schawen** [comment]
I've now shrinked the Sketch to the supposed minimum.
It compiles and shows the errors, at least in my environment.

**Comment by Schawen** [comment]
Thank's a lot!

**Comment by 5chufti** [comment]
I do think that neither the webserver nor the dht-sensor code is essential to your problem but bloats the sketch seriously. It would be very helpfull to read some words about what you are trying to achieve with your code. From a quick glimpse I see some funtionality to read wifi-config from flash and switch from AP to STA and vice versa but w/o any description what it is ment to do I wouldn't want to invest any more time to analyse your code ans/or look for possible errors ... I can't even find any log where AP is turned off - and if it isn't, it's no wonder that STA disconnects regularily ...

**Comment by WereCatf** [comment]
@Schawen Your sketch is hardly minimal. Remove anything that's not relevant.

**Comment by Schawen** [comment]
Thanks for your reply, Schufti and WereCatf and also to all the other friendly and polite people around here. I thought my code has been very (very) simple.
I'll find other ways to solve the problem.
Thanks

**Comment by 5chufti** [comment]
Hi Schawen,
please don't consider us rude, but you said yourself you want to learn how to tackle such problems.
And first thing is to narrow the problem down with the most minimalistic sketch needed to provoke the error. Not seldom this leads to such straight forward code that the problem gets obvious to oneself.
But as I said, the sketch is much too complex for even any goodwilled individuum to even get an vague idea of its intended function.without a) spending amounts of precious (spare) time or b) a good explanation. It's all voluntary and based on give and take (and up to now we could only see the "take").

**Comment by WereCatf** [comment]
@Schawen To add some more to what @5chufti there said, you need to ask yourself "what can I remove from my sketch while still making the issue happen?" Does the issue still happen if you e.g. remove all the code related to the temperature-sensor? If yes, then you can remove all that code because it's not relevant. Does the issue still happen if you reduce the web-serving code? If yes, then you can remove that, too. Continue until the issue disappears and then you can add back the latest thing that you removed and you'll have a minimal sketch.

**Comment by Schawen** [comment]
Thanks again, Schufti and WereCatf!
