### ISSUE TITLE
No way to resolve mDNS hostnames

### ISSUE THREAD

**Issue by G-glop** [esp8266/Arduino#4706]
The ESP8266 can do everything else with mDNS (advertise services, query services, set it's hostname), apart from the very important thing of querying hostnames.

ESP32 can do it with the MDNS.queryHost function, but it only wraps the one from the sdk, which lives inside a compiled binary. So it's no use for backporting it to the ESP8266.

This is all more unfortunate because the netBIOS library also cannot resolve hostnames

edit: madpilots [mDNSResolver](https://github.com/madpilot/mDNSResolver) did the job, but the functinality should be part of the built in library

**Comment by RudyFiero** [comment]
From [https://github.com/esp8266/Arduino/issues/4591#issuecomment-377728021](https://github.com/esp8266/Arduino/issues/4591#issuecomment-377728021)

> Be aware that I am currently rewriting the mdns responder/query based on the idf implementation. It is very slow going, though, so it will take quite some time.

**Comment by palmerabollo** [comment]
I'm also interested in this feature.
@G-glop do you mean that mDNSResolver suddenly stops working?

**Comment by G-glop** [comment]
@palmerabollo It stops working after about 20 resolutions, and it also blocks all other connections. Probably some kind of resource leak.

**Comment by kosso** [comment]
Glad to find this thread. 

I found myself wondering why there was no ESP8266 equivalent to the `MDNS.queryHost()` method, which makes life a whole lot easier. 

Going to try mDNSResolver for now.

**Comment by RudyFiero** [comment]
I assume that someone made their own library and it had some basic functionality. And because it had useful features it was included in this framework.  I don't believe it was ever claimed to be a full implementation.

**Comment by devyte** [comment]
Closing in view of #5442 with a full rewrite of mdns.
