### ISSUE TITLE
WiFi.printDiag doesn't support softAP

### ISSUE THREAD

**Issue by TimeTravelingOwls** [esp8266/Arduino#471]
This may be outside of the scope of WiFi.printDiag, but it doesn't seem to support softAP. The Mode gets displayed as AP, but status stays set at 255 regardless of the AP's state:

> Mode: AP
> PHY mode: N
> Channel: 1
> AP id: 0
> Status: 255
> Auto connect: 1
> SSID (0): 
> Passphrase (0): 
> BSSID set: 0

I know that some details of the softAP connection are available, because I can see the client's MAC, join, leave, etc., when I have `Serial.setDebugOutput(true);` set, but I'm not sure where that's coming from - is it somewhere in the lwip code? Is there a direct way to query softAP status within a sketch?

I'm trying to flip a token based on whether a client has disconnected from the softAP - any suggestions for a reliable way to track join/leave?
##

**Comment by me-no-dev** [comment]
yeah, I have a fix for that. Will be in the next pull.

**Comment by luc-github** [comment]
I read in SDK : SoftAP only support bg not n - I experienced bad connection in with SoftAP mode and PHY mode to n
do you mean now is it working ?

**Comment by TimeTravelingOwls** [comment]
Thanks @me-no-dev - I'll test when it lands.

In the meanwhile, any suggestion for how to determine when a client has connected/disconnected? Seems like it ought to be easy, but I'm just not seeing it.

**Comment by me-no-dev** [comment]
```cpp
extern "C" {
  #include "user_interface.h"
  #include "ip_addr.h"
  #include "mem.h"

  void _onWiFiEvent(System_Event_t *event){
    if(event->event == EVENT_SOFTAPMODE_STACONNECTED){
      Event_SoftAPMode_StaConnected_t *data = (Event_SoftAPMode_StaConnected_t *)(&event->event_info.sta_connected);
      Serial.printf("Station Connected: id: %d, mac: " MACSTR "\n", data->aid, MAC2STR(data->mac));
    } else if(event->event == EVENT_SOFTAPMODE_STADISCONNECTED){
      Event_SoftAPMode_StaDisconnected_t *data = (Event_SoftAPMode_StaDisconnected_t *)(&event->event_info.sta_disconnected);
      Serial.printf("Station Disconnected: id: %d, mac: " MACSTR "\n", data->aid, MAC2STR(data->mac));
    }
  }
}

void setup(){
  Serial.begin(115200);
  wifi_set_event_handler_cb(_onWiFiEvent);
}

**Comment by igrr** [comment]
Note that this will disable the event handler present in ESP8266Wifi library.

**Comment by me-no-dev** [comment]
We should add it there then

**Comment by TimeTravelingOwls** [comment]
@me-no-dev: perfect - thanks!

Should I close this issue or wait until it's been pulled through?

**Comment by igrr** [comment]
Better leave it open so I don't forget to add this.

**Comment by devyte** [comment]
@igrr I think the current wifi event system supersedes this. Is there anything left to do?

**Comment by igrr** [comment]
Yes, `onStationModeConnected` and `onStationModeDisconnected` functions in WiFi class provide this functionality.
