### ISSUE TITLE
_SPIFFS_end;

### ISSUE THREAD

**Issue by DESAWI** [esp8266/Arduino#4723]
Hi,
I want to know where exactly I can find the definition of "_SPIFFS_end", where I can find its value in which "C" file??

**Comment by hreintke** [comment]
It is not in a C file but in the ld files from the directory tools\sdk\ld

F.e. the eagle.flash.2m.ld contains : 

```
PROVIDE ( _SPIFFS_start = 0x40300000 );
PROVIDE ( _SPIFFS_end = 0x403FB000 );
PROVIDE ( _SPIFFS_page = 0x100 );
PROVIDE ( _SPIFFS_block = 0x2000 );
```

**Comment by DESAWI** [comment]
thanks so much.
