### ISSUE TITLE
arduino wemos d1 r1 + PMS7003 error

### ISSUE THREAD

**Issue by diqmwl** [esp8266/Arduino#4734]
#### Platform

- Hardware:					wemos d1 r1
- Development Env:		Arduino IDE
- Operating System:		windows

### Settings in IDE

- Module:  			Wemos D1 mini r2
- Upload Speed:   115200 (serial upload only)

### Problem Description
#include <dummy.h>
#include <SoftwareSerial.h>
#include <LiquidCrystal_I2C.h>
LiquidCrystal_I2C lcd(0x3F,16,2);
SoftwareSerial mySerial(9,8);

int incomingByte = 0; // my시리얼을 읽어오기위한 변수입니다.

const int MAX_FRAME_LEN = 64; //PMS7003의 데이터를 읽어오기위한 배열의 크기입니다

char frameBuf[MAX_FRAME_LEN]; //PMS7003 데이터를 읽어오기위한 배열입니다.

int detectOff = 0;

int frameLen = MAX_FRAME_LEN;

bool inFrame = false;

char printbuf[256];

 

const bool DEBUG = false;

 

 

uint16_t calcChecksum = 0;

 

struct PMS7003_framestruct {

    uint8_t  frameHeader[2];

    uint16_t frameLen = MAX_FRAME_LEN;

    uint16_t concPM1_0_amb;

    uint16_t concPM2_5_amb;

    uint16_t concPM10_0_amb;

} thisFrame;

 

 

void setup() {

  lcd.init();

  lcd.backlight();

 

    Serial.begin(115200);
    mySerial.begin(9600);
    delay(1000);

    Serial.println("-- Initializing...");

}

 

 

bool pms7003_read() {

    Serial.println("-- Reading PMS7003");

   

    bool packetReceived = false;

    while (!packetReceived) {

      /*  if (Serial1.available() > 32) {

            int drain = Serial1.available();

            for (int i = drain; i > 0; i--) {

                Serial1.read();

            }

        }*/

        if (mySerial.available() > 0) { //PMS7003이 통신하고있다면 

            incomingByte = mySerial.read(); //값을 1바이트씩 읽는다.

            if (!inFrame) {

                if (incomingByte == 0x42 && detectOff == 0) { //처음 PMS7003이 주는값이 0x42인데 이게 맞는지 확인한다.

                    frameBuf[detectOff] = incomingByte;

                    thisFrame.frameHeader[0] = incomingByte;

                    calcChecksum = incomingByte; // Checksum init!

                    detectOff++;

                }

                else if (incomingByte == 0x4D && detectOff == 1) { //두번쨰 주는 값이 0x4D인데 맞는지 확인한다.

                    frameBuf[detectOff] = incomingByte;

                    thisFrame.frameHeader[1] = incomingByte;

                    calcChecksum += incomingByte;

                    inFrame = true;

                    detectOff++;

                }

            }

            else {

                frameBuf[detectOff] = incomingByte;

                detectOff++;

                uint16_t val = frameBuf[detectOff-1]+(frameBuf[detectOff-2]<<8); //구하려는 값이 detectOff가 12 ,14, 16일때 그 데이터를 저장한다.

                switch (detectOff) {

                    case 12:

                        thisFrame.concPM1_0_amb = val;

                        break;

                    case 14:

                        thisFrame.concPM2_5_amb = val;

                        break;

                    case 16:

                        thisFrame.concPM10_0_amb = val;

                        break;

                    default:

                        break;

                }

    

                if (detectOff >= frameLen) {

                    Serial.print("PMS1.0 = ");

                    Serial.print(thisFrame.concPM1_0_amb); //출력코드

                    Serial.print("  PMS2.5 = ");

                    Serial.print(thisFrame.concPM2_5_amb);

                    Serial.print("  PMS10 = ");

                    Serial.print(thisFrame.concPM10_0_amb);

                    Serial.print("\n");

                    packetReceived = true;

                    detectOff = 0;

                    inFrame = false;

                }

            }

        }

    }

    Serial.end();

}

 

void loop () {

    if (!pms7003_read()) {

      lcd.setCursor(0,0);

      lcd.print("PMS1.0=");

      lcd.setCursor(7,0);

    lcd.print(thisFrame.concPM1_0_amb);

        delay(4000);

    }

}
this code run in Uno but  Does not work on d1

### Debug Messages

Soft WDT reset

ctx: cont 
sp: 3ffefa10 end: 3ffefc10 offset: 01b0

>>>stack>>>
3ffefbc0:  3ffe8878 00000000 3ffeeb2c 402024a1  
3ffefbd0:  4020143a 000003e8 3ffeeb2c 3ffeebe4  
3ffefbe0:  3fffdad0 00000000 3ffeebdc 402025e0  
3ffefbf0:  feefeffe 00000000 3ffeebdc 40203494  
3ffefc00:  feefeffe feefeffe 3ffeebf0 40100710  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v614f7c32
~ld

**Comment by devyte** [comment]
This is a 3rd party lib, and I see several long-looking operations in a row without yield().
Closing due to not a core issue and 3rd party lib.
