### ISSUE TITLE
HTTPS example sketch does not work, cannot connect to host address

### ISSUE THREAD

**Issue by DannyTMo** [esp8266/Arduino#4759]
#### Platform

- Hardware:				WeMOS D1 Mini Pro ( ESP8266)
- Operating System:		Windows 7

### Settings in IDE

- Module:  			Wemos D1 mini r2
- Flash Size: 		        4MB
- CPU Frequency:	        80Mhz
- Upload Speed:              921600

### Problem Description

I want to test HTTPS connection with my WeMOS board, and found an example on this Git.

I tried (copied&pasted) the HTTPS [sketch](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/HTTPSRequest/HTTPSRequest.ino), the board can connect to the network, but fail to connect to the host api.github.com (see below message).

I tried on 2 PCs, but have the same result. Could it be the library is not working properly?
Could it be the host is no longer good to access (I can still do it manually though)? Is there any other recommendations for https host?

Many thanks,
Danny

### Debug Messages

```
WiFi connected
IP address: 
10.1.1.109
connecting to api.github.com
connection failed


```

**Comment by DannyTMo** [comment]
Update:
I tried different host, and the code passed the connection and check the finger print. (the host: www.howsmyssl.com)

So my guess is that the api.github.com is not good to test on? If anyone can confirm this, or clarify what I am missing here, please do :).

Many thanks.

**Comment by earlephilhower** [comment]
You're running an older version of the repo.  The GitHub cert was changed and fingerprint updated in the git head (2.4.1 I think).  Update and it will pass for you, just re-verified myself.
