### ISSUE TITLE
Support NodeMCU ESP8266 - 32MB Flash

### ISSUE THREAD

**Issue by laercionit** [esp8266/Arduino#4762]
It recently hit NodeMCU V3 12-E  with 32MB of Flash.

This allows you to use SPIFFS for more complex projects.
I think we need to adjust boards.txt to support this new Flash / SPIFFS modeling

Example:
https://pt.aliexpress.com/item/NodeMCU-WIFI-module-integration-of-ESP8266-extra-memory-32M-flash-USB-serial-CH340G/32739832131.html

I have some boards of this model, if they can guide me on how to change the boards.txt file I can do the tests for you.

**Comment by Deimos1994** [comment]
Hmm.. 32MB? I thought it supports up to 16MB...
How can it be possible? quote from the datasheet:
> ESP8266EX uses external SPI flash to store user programs, and supports up to 16 MB
memory capacity theoretically.

https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf

**Comment by laercionit** [comment]
From what I saw the manufacturer is the robotdyn.
They make boards with upgrades.
https://robotdyn.com/catalog/arduino/boards/wifi-nodem-esp8266-32m-flash-ch340g.html

**Comment by Deimos1994** [comment]
@laercionit It doesn't really matter who makes a board since the chip is designed by espressif, and espressif's datasheet says it supports only 16MB (128Mbits).
My opinion: I think sellers intentionally write it is 32MB (which is wrong should be 32Mb) just to sell those boards to people that don't pay much attention.

**Comment by laercionit** [comment]
I have some cards from other models of this same company, they do some very well made things. They have an Arduino Mega with ESP8266 integrated.

Unfortunately using Generic Esp8266 I can not upload the code via USB.

This board follows the same NodeMCU reference. Selecting the NodeMCU only has version 1.0 that is limited to 4MB of memory.

To perform tests I will have to change the board.txt in NODEMCU to support 16MB equal to board generic.

Would someone have patience to guide me in how to make this change?

**Comment by devyte** [comment]
Please be aware that with 16MB flash, spiffs is already in trouble wrt performance

**Comment by WereCatf** [comment]
@laercionit It's 4MB flash, ie. 32 megabits, not 32 megabytes. Just look at the SPI-Flash on the board, it clearly says Winbond 25q32fvsig, which is a 32Mb-part ( https://www.winbond.com/resource-files/w25q32fv%20revi%2010202015.pdf )

The Chinaman either doesn't know or doesn't care about the difference between MB and Mb -- always keep this in mind when buying stuff like this.

**Comment by devyte** [comment]
@WereCatf thanks for figuring that out!
Closing.
