### ISSUE TITLE
ESP8266 close MDNS and start it with a new MDNS name

### ISSUE THREAD

**Issue by Clainstyle** [esp8266/Arduino#4767]
Hello, i am using the Arduino IDE to program the ESP8266 NodeMCU, where i can not find a way to close the MDNS service, without stopping the webserver.
Even when the webserver got stopped and restarted, the MDNS service still works then and is not able to start with a new name.
Can anyone help me please?

**Comment by RudyFiero** [comment]
mDNS doesn't have anything to do with the webserver. mDNS just lists services. You could list the webserver and not actually have it. That wouldn't make much sense but you could. I often will list services to check if mDNS is being seen and working properly. But I don't need those services to actually be there.

As far as terminating mDNS. I did find 
```
  espconn_mdns_close();
  mdns_server_unregister();
  espconn_mdns_disable();
```
but when I include them I get compile errors. 

I have never seen anyone want to stop it, but it does make sense. The only way that I know of that should work is a restart/reset. Ugly but should work. RTC memory can be used to keep track of what state it should be in. I hope you get a better answer than this.

**Comment by devyte** [comment]
Closing in view of #5442 with a full rewrite of mdns.
