### ISSUE TITLE
Can we debug in Windows using an IDE?

### ISSUE THREAD

**Issue by electronicsguy** [esp8266/Arduino#4770]
Can we use esp8266 gdbstub in Windows and use an IDE like Arduino or VS Code for debugging over serial? I'm asking because all the guides I found refer to using it in Linux, where eclipse IDE and gdb may already be installed.

**Comment by freeck** [comment]
Take a look at Sloeber!

**Comment by electronicsguy** [comment]
@freeck some more details please. I went thru the website, but couldn;t find any details on how to go about debugging. The FAQs do have some videos, but no clear instructions for using it with gdbstub.

**Comment by freeck** [comment]
What about this video:
https://m.youtube.com/watch?v=S_QTMNhaDwM
What do you mis?
