### ISSUE TITLE
ets Jan  8 2013,rst cause:1, boot mode:(3,2)  

### ISSUE THREAD

**Issue by JulienAjdenbaum** [esp8266/Arduino#4772]
Hi,
I am a new user of the ESP-01.
I constantly getting an error while uploading a sketch or even trying to communicate with it.
When I try uploading the sketch I get this:

"Sketch uses 246,319 bytes (49%) of program storage space. Maximum is 499,696 bytes.
Global variables use 32,276 bytes (39%) of dynamic memory, leaving 49,644 bytes for local variables. Maximum is 81,920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed"

When I try serial communication I get all kinds of letters and signs (like when it is not the right baud rate) for 115200 baud with both NL and CR. 

With the 74880 baud rate I get:
"ets Jan  8 2013,rst cause:1, boot mode:(3,0)

load 0x40100000, len 612, room 16 
tail 4
chksum 0x12
load 0x3ffe8000, len 788, room 4 
tail 0
chksum 0x50
load 0x3ffe8314, len 264, room 8 
tail 0
chksum 0x4a
csum 0x4a

2nd boot version : 1.1
  SPI Speed      : 40MHz
  SPI Mode       : QIO
  SPI Flash Size : 4Mbit
jump to run user1

€€€€€€€€€€€€"

With the 9600 baud rate I get:
"0 ]ŠÌ
ÿa+çh„á	V=ü™j!šA3„DaÀA†<@ÃH,Î™ºþ
ready
"

I have no idea why i keep getting this. The AT commands don't seem to do anything.
The red LED is on and the blue LED blinks after resetting.

I am connected to an arduino UNO which is not in reset mode (the is no wire between gnd and rst) and I have no idea what kind of esp 8266 -01 I have.
please help!
Thank you

**Comment by devyte** [comment]
You completely ignored the issue template. The template, together with the isssue POLICY doc, clearly explain that this is not the right place to ask for help. This is an issue tracker, meant to track issues in the core. 
Also, this is not the AT command firmware repo, and the espcomm open errors are documented.
I suggest requesting help at a community forum.
Closing.
