### ISSUE TITLE
WiFiServer needs default constructor

### ISSUE THREAD

**Issue by dmars1972** [esp8266/Arduino#4774]
When attempting to create a WiFiServer member to a custom class, compilation fails due to no default constructor.

The following won't compile:

class MyClass {
  private:
    WiFiServer server;
}

MyClass::MyClass {
  server = WiFiServer(12345);
}

However, simply adding this to esp8266/2.4.1/libraries/ESP8266WiFi/src/WiFiServer.h:

WiFiServer() {};

Fixes it just fine.

**Comment by devyte** [comment]
That is on purpose, to stop precisely what you're trying to do. Your MyClass constructor is wrong, it should forward construction to its members, like so:
MyClass::MyClass 
    : server(12345) {
}
Closing.
