### ISSUE TITLE
Error after update:  SD.h: No such file or directory  

### ISSUE THREAD

**Issue by chessweb01** [esp8266/Arduino#4775]
I'm working with NodeMCU v1.0 using the latest version of platform.io in Visual Studio Code. After an update today, I get the following  compiler error:

C:\users\rsel\\.platformio\packages\framework-arduinoespressif8266@src-31d658a59f41540201fc3726a1394910\libraries\ESP8266WiFi\src\CertStoreSDBearSSL.cpp:20:16: fatal
error: SD.h: No such file or directory

The Arduino SD library (v1.2.2) is installed.

**Comment by earlephilhower** [comment]
Please see #4740.  PlatformIO uses an unsafe optimization that does not detect dependencies correctly by default (hence it doesn't see your library properly).  The referenced bug has a couple fixes for the PIO configuration.

Merging with #4740 as it's the same root issue.
