### ISSUE TITLE
how to save RFID RDM6300 tag number  to database Mysql and NodeCmu (ESP8266)

### ISSUE THREAD

**Issue by emalcheiro** [esp8266/Arduino#4793]
Hi there,

I am building an employee attendance system and I have a big issue.
The PHP code I am using to upload the data to the database is working when I manually put it on the browser but using the below code nodecmu on Arduino IDE nothing is happening.

#include <SPI.h>
#include <SoftwareSerial.h>
#include <ESP8266WiFi.h>
#include <WiFiClient.h> 
#include <ESP8266WebServer.h>
#include <ESP8266HTTPClient.h>

SoftwareSerial rfid(D3, D4);

const char server[] = "192.168.0.188"; 
const char* MY_SSID = "MyWIFI-HOME";
const char* MY_PWD =  "********";

String tagString;
char tagNumber[14];
boolean receivedTag;

WiFiClient client;
WiFiServer terver(80);

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  rfid.begin(9600);
  Serial.print("Connecting to "+*MY_SSID);
  WiFi.begin(MY_SSID, MY_PWD);
  Serial.println("going into wl connect");

  while (WiFi.status() != WL_CONNECTED) //not connected,  ...waiting to connect
    {
      delay(1000);
      Serial.print(".");
    }
  Serial.println("wl connected");
  Serial.println("");
  Serial.println("Credentials accepted! Connected to wifi\n ");
  Serial.println("");

  terver.begin();
  Serial.println("Server started");
  Serial.println(WiFi.localIP());
 
}

void loop() {
  // put your main code here, to run repeatedly:
  checkrfid();
   if (receivedTag)
  {
    tagString=tagNumber;
    Serial.println();
    Serial.print("Tag Number: ");
    Serial.println(tagString);
    delay(2500); // a delay of 1500ms and a flush() seems to stop tag repeats
    rfid.flush();
    Serial.println("\nStarting connection to server..."); 
  // if you get a connection, report back via serial:
    if (client.connect(server, 80)) {
    Serial.println("connected to server");
    WiFi.printDiag(Serial);

    String data = "tagID="+tagString;

     //change URL below if using your Sub-Domain
     client.println("POST /write_test.php? HTTP/1.1"); 
     //change URL below if using your Domain
     client.print("Host: 192.168.0.188\n");                 
     client.println("User-Agent: ESP8266/1.0");
     client.println("Connection: close"); 
     client.println("Content-Type: application/x-www-form-urlencoded");
     client.print("Content-Length: ");
     client.print(data.length());
     client.print("\n\n");
     client.print(data);
     client.stop(); 
     
     Serial.println("\n");
     Serial.println("My data string im POSTing looks like this: ");
     Serial.println(data);
     Serial.println("And it is this many bytes: ");
     Serial.println(data.length());       
     delay(2000);
    } 

  }
  memset(tagNumber,0,sizeof(tagNumber)); //erase tagNumber
 
}

void checkrfid()
{
  receivedTag=false;
  while (rfid.available())
  {
    int BytesRead = rfid.readBytesUntil(3, tagNumber, 15);//EOT (3) is the last character in tag 
    receivedTag=true;
  }
}

  void printWifiStatus() {
  // print the SSID of the network you're attached to:
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());
  
 // print your WiFi shield's IP address:
  
 // IPAddress ip = WiFi.localIP();
 // Serial.print("IP Address: ");
 // Serial.println(ip);
  
  // print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
}

Please help!
I am trying to populate my database with the RFID tag number. Urgent!!!

**Comment by devyte** [comment]
This is not a support forum, but an issue tracker, meant for tracking issues in the core. For help with your particular project please refer to a community forum. See issue POLICY doc for more details, as well as reading the issue template when opening one.
Closing.
