### ISSUE TITLE
Can't use os_printf in user-defined library?

### ISSUE THREAD

**Issue by ly0** [esp8266/Arduino#48]
I created a library, but I can't use os_print in my code, anything instead?
```
: error: 'os_printf_plus' was not declared in this scope
     os_printf("\n\n");
                     ^
```

here is my header 
```
#include "ets_sys.h"
#include "c_types.h"
#include "osapi.h"
#include "user_interface.h"
```

**Comment by igrr** [comment]
Did you place all the include directive in a ``` extern "C" { ... } ``` block?

**Comment by igrr** [comment]
You can now use ```printf``` instead of ```os_printf```.
