### ISSUE TITLE
Problem on uploading code into esp8266 nodemcu

### ISSUE THREAD

**Issue by lsiddiqsunny** [esp8266/Arduino#4802]
Recently I bought a esp8266 nodemcu for my project.
For running the blink code, I followed this tutorial [esp8266 quick start.](http://www.instructables.com/id/Quick-Start-to-Nodemcu-ESP8266-on-Arduino-IDE/) But ended up with this  :

>Sketch uses 246,319 bytes (23%) of program storage space. Maximum is 1,044,464 bytes.
>Global variables use 32,276 bytes (39%) of dynamic memory, leaving 49,644 bytes for local variables. >Maximum is 81,920 bytes.
>Uploading 250464 bytes from C:\Users\test\AppData\Local\Temp\build544514107263874658.tmp/arduinowifi.cpp.bin to flash at 0x00000000
>.error: failed sending 1044 bytes
error: failed sending 0xC0
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_DATA) failed
error: failed sending 0xC0
error: failed sending 8 bytes
error: failed sending 4 bytes
error: failed sending 0xC0
warning: espcomm_send_command: didn't receive command response
error: espcomm_upload_mem failed

I tried with different baud rate but failed.
Arduino IDE: 1.6.5 and 1.8.5
OS: Windows 10 and Linux 16.04LTS

**Comment by devyte** [comment]
The espcomm* errors are documented. Either you have a faulty board, bad drivers, or you're doing something wrong (e.g.: did you reset the board while pressing the flash button?)
Please refer to a support forum for help, as this is an issue tracker, see issue POLICY doc for further details.
Closing.
