### ISSUE TITLE
esp8266 static ip

### ISSUE THREAD

**Issue by zezo00747** [esp8266/Arduino#4803]
I have esp8266 and I have static ip from  my internet provider 
I added the static ip to my esp8266 
but id doesn't work from any mobile phone
but it works very good from my pc

**Comment by devyte** [comment]
The description doesn't make any sense. Also, the entire issue template has been ignored.
Please read the issue POLICY doc, and if you still think you need to open an issue, read the issue template itself.
To be explicit, this is an issue tracker, and not a support forum.
Closing.

**Comment by pipi61** [comment]
Hi!
Use port forwarding in your router to esp8266 static ip in the local network range.
Request from internet provider public ipaddress, if your ipaddress after NAT device...
