### ISSUE TITLE
ArduinoOTA : request for a better error reporting

### ISSUE THREAD

**Issue by destroyedlolo** [esp8266/Arduino#4813]
Hello,

I did some tests with BasicOTA example on an 512k ESP-201.

Uploading fails with following error message on the ESP console
`Error[1]: Begin Failed`
1 came from ArduinoOTA code and means "Write Error" ... which was in fact wrong.

Activating debug messages, I saw the real error is `ERROR[4]: Not Enough Space`

My request is : can you please propagate the right error to user code ? It seems to me the concern is to not overwrite _error field if it is already set after write to flash attempt.

Thanks

Laurent

**Comment by devyte** [comment]
The issue template has been completely ignored. Also, the requirement os for a MCVE sketch. Although in this case the relevant sketch is an example, it should still either be included with an explicit comment showing what you mean, or at the very least you should include a permalink to  the line of code of the repo where you see the error return.
Even better, you could look at the updater code, implement the code change that you want, and make a pr with your proposal.
Please open a new issue and fill in the required fields, including the relevant code line with the error return that you want changed.
Closing.
