### ISSUE TITLE
ltoa != itoa

### ISSUE THREAD

**Issue by mongozmaki** [esp8266/Arduino#4815]
Hi,
I discovered, that the non-ISO `ltoa` function is not equal to `itoa` for the maximal negative value case (`-2147483648` or `LONG_MIN`).

I'm not sure if this is a bug or this behaviour is ok.

The reason is the implementation (usage of the `abs` function) of `ltoa` which cannot convert the maximal negative value to a positive integer (`--2147483648` not representable).

Test code:
```
    Serial.print("INT_MIN String: ");
    Serial.println(String(std::numeric_limits<int>::min())); //-2147483648

    Serial.print("LONG_MIN String: ");
    Serial.println(String(std::numeric_limits<long>::min())); //Weird String

    Serial.print("size long: ");
    Serial.println(sizeof(long));

    Serial.print("size int: ");
    Serial.println(sizeof(int));
```

One workaround would be to add a switch in `core_esp8266_noniso.c::ltoa`:
```
if (sizeof(long) == sizeof(int) {
  return itoa(...);
}
else {
  //Current code ...
}

```
or to handle this border-case separately.

**Comment by devyte** [comment]
@igrr do you have any comments on the proposed fix?

**Comment by earlephilhower** [comment]
@mongozmaki There's a very recent commit fixing this in `String`.  Should be clean, now.

**Comment by mongozmaki** [comment]
I saw it, Thanks a lot!

**Comment by earlephilhower** [comment]
I'll close this, then.  Thx
