### ISSUE TITLE
how to make no install arduino -8266 IDE version

### ISSUE THREAD

**Issue by hznupeter** [esp8266/Arduino#4822]
The arduino IDE has a no install version for non admin.How to make a no install IDE including the Esp8266.  I hope to my students can use the esp8266 easily,install the esp8266 via Board Manager cost too much time.

**Comment by Pablo2048** [comment]
Search for "Arduino IDE portable installation"...

**Comment by devyte** [comment]
Previous comment is correct.
Closing.
