### ISSUE TITLE
Findint the esp in current network.

### ISSUE THREAD

**Issue by ajinkyaw** [esp8266/Arduino#4835]
Hi Guys i have developed a program for esp8266 to connect to any wifi station by providing SSID and password. I am using mDNS to find the device when its in AP Mode. but when in STA mode i cannot find it with the mDNS.
I am using websocket to communicate with the device , but here i need to know the IP address of the esp and then i can communicate with it. 
What i want to achieve here is  , I want to access the esp without knowing its IP address when it is connected to the network i am in. Also i cannot set a static ip address to the esp in my case.

What are the techniques to do so , please guide.

**Comment by 5chufti** [comment]
Hi,
as you are not reporting an error with the esp arduino core but seek help on software design matters, please close this issue (as it is not compliant with issue guidlines) and look for help in a dedicated forum (e.g. www.esp8266.com)
