### ISSUE TITLE
No wifiduino board in package_esp8266com_index.json

### ISSUE THREAD

**Issue by JavaCS3** [esp8266/Arduino#4839]
I saw #4590 this PR is merged but not wifiduino board on package_esp8266com_index.json

**Comment by d-a-v** [comment]
This was pushed after 2.4.1 release.
You'll have to wait for core v2.4.2, or use the git version. Documentation tells you how to get it.

**Comment by JavaCS3** [comment]
@d-a-v when is the next release?

**Comment by devyte** [comment]
2.4.2 is currently planned for August.
