### ISSUE TITLE
Do you NEED to solder the Sparkfun 8266 Thing in order to program it?

### ISSUE THREAD

**Issue by bxrz** [esp8266/Arduino#4846]
For anyone that is familiar with it. Are there any alternatives to this? I'm trying to use a FTDI 3.3 programmer in order to Sparkfun 8266 Thing but apparently, I need to solder it? I don't have that equipment available to me so it is possible to just connect 6 wires to the FTDI to the module (GND connects to GND ect) or do I need to solder it in order to program it? I'm using Arduino to program it and trying to get a code that relates to Blynk to put on it.

Sorry if this is in the wrong place.

**Comment by 5chufti** [comment]
as this is not a problem with the esp arduino core and is not compliant with [issue guidlines](https://github.com/esp8266/Arduino/blob/master/POLICY.md) but a "user fault" please close the issue and look for help in a dedicated forum (e.g. www.esp8266.com)

@devyte

**Comment by duncan-a** [comment]
You can just 'connect and program'...
