### ISSUE TITLE
send image camera from client to server ? or via wifi..

### ISSUE THREAD

**Issue by adamrabbani** [esp8266/Arduino#4849]
Master,...
can we send image camera from client to server ?

Thanks..

**Comment by 5chufti** [comment]
as you are not reporting an error with the esp arduino core but seek help on software design matters, please close this issue as it is not compliant with [issue guidlines](https://github.com/esp8266/Arduino/blob/master/POLICY.md) and look for help in a dedicated forum (e.g. www.esp8266.com)
@devyte
