### ISSUE TITLE
What's the best way to write table data on webpage from SPIFFS and update when client add or deletes a row

### ISSUE THREAD

**Issue by denden4444** [esp8266/Arduino#4852]
Hello all 

I currently have a table on my index page on the ESP8266 and when a client connects I need to read from a file in SPIFFS and update the table with it's content.
I would also like to update it when the client adds or deletes a row.

I have managed to see how to append to a file in SPIFFS but what I can't figure out is how to get it's data out line by line and send this updated data to the client .. ? 

What is the best way to go about this ?

Thank you 

Den

**Comment by devyte** [comment]
Did you read the issue template? The issue POLICY doc?
Closing.
