### ISSUE TITLE
ESP8266 has possible post 1MB .txt file upload HTTP server

### ISSUE THREAD

**Issue by Autobot86** [esp8266/Arduino#4854]
I have create multiple .txt file system in SPIFFS Flash memory. But How to post the .txt large file send to HTTP server it is possible to post SPIFFS 1MB file to Upload HTTP server via ESP8266 12F. my requirement is to upload on HTTP server only through website [Internet] please Help me any one.

**Comment by Pablo2048** [comment]
Why you (again) ignored the issue template? This is definitely 'how do i...' kind of question so it belong to the forum, not the core issue tracker...
