### ISSUE TITLE
nodemcu amica /lua

### ISSUE THREAD

**Issue by aditya1121507** [esp8266/Arduino#4857]
i bought a nodemcu lua 
and suddenly it stopped working

**Comment by aditya1121507** [comment]
i also checked the circuits but all are fine

**Comment by aditya1121507** [comment]
are there any button combinations of rst and flash on the board

**Comment by aditya1121507** [comment]
as i by mistakely pressed them by random and after that its not working i think

**Comment by devyte** [comment]
In some cases you have to explicitly setnthe board in flash mode by pressing and holding flash while pressing reset. Depends on the board.
This is not a support forum,  this is an issue tracker. Please refer to a community forum for further help.
Closing.
