### ISSUE TITLE
ESP8266 possible file send webserver in HTTP GET request

### ISSUE THREAD

**Issue by Autobot86** [esp8266/Arduino#4860]
ESP8266 has support large file[500KB] send to HTTP web server in GET request method...? it is possible how write the code to send data.  any example code is there to send large file.txt GET method to post..

**Comment by Pablo2048** [comment]
Oh, come on. Ignoring issue template third time in a row? Really? ASK THIS KIND OF QUESTIONS IN THE FORUM!

**Comment by Autobot86** [comment]
can you share the forum link i want put the issues.

**Comment by Pablo2048** [comment]
It is part of the issue template (you even did not read it, right?) and has been given to you by 5chufti 2 days ago so check your first issue...

**Comment by devyte** [comment]
@Autobot86 please read the issue POLICY doc and the issue template that you are presented when opening an issue here. They contain instructions and links.
