### ISSUE TITLE
Exception (3)

### ISSUE THREAD

**Issue by kotran88** [esp8266/Arduino#4881]
--
#### Platform

- Hardware:				ESP8285 device|
- Operating System:		[Windows

### Settings in IDE

- Module:  			Wemos D1 mini r2

Exception (3):
epc1=0x401003e9 epc2=0x00000000 epc3=0x00000000 excvaddr=0x400010a9 depc=0x00000000

ctx: sys 
sp: 3fff0700 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fff08a0:  00000031 0000000a 3fff0648 40202509  
3fff08b0:  3fff08ef 3fff0940 401074b8 3fff0624  

...
....
...
3fff1140:  000⸮R⸮F

Can anyone guess why this error happened ? 
It's not restarting but just stucked and I have to press reset button on wemos. 

I think it happened when there are so many of Serial.println()

**Comment by devyte** [comment]
When you opened the issue you were presented with a an issue template, which contains instructions to follow and specific information to fill out. It also links to the issue POLICY doc, which explains how this issue tracker is to be used, and not used. 
Please refer to a community forum like esp8266.com or stackoverflow for assistance.
Closing.
