### ISSUE TITLE
epc1=0x40106b49 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

### ISSUE THREAD

**Issue by nardev** [esp8266/Arduino#4887]
I have problem installing "EspExceptionDecoder", is there a way to decode this error?

```
Exception (28):
epc1=0x40106b49 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3ffffbe0 end: 3fffffd0 offset: 01a0
```
Essentially, the esp restarts after i try to send some data from RFID reader. Very simplified code.

**Comment by bjoernads** [comment]
No it's not, as it depends on your individual code. Furthermore, the right place to ask this question is mentioned in the issue template.
