### ISSUE TITLE
i2c returns error=0, although no device connected

### ISSUE THREAD

**Issue by cimba007** [esp8266/Arduino#49]
I have an 1306 OLED diplsay and wanted to at least verify the i2c address so i thought running http://playground.arduino.cc/Main/I2cScanner might be a nice idea.

I wired up 2 external pullups and changed to code to include

  Wire.pins(12, 14);
  Wire.begin();

But I get the following for all i2c addresses which cant be right:

Scanning...<\r><\n>
I2C device found at address 0x01  !<\r><\n>
I2C device found at address 0x02  !<\r><\n>
I2C device found at address 0x03  !<\r><\n>
I2C device found at address 0x04  !<\r><\n>
I2C device found at address 0x05  !<\r><\n>
I2C device found at address 0x06  !<\r><\n>

Remember: Nothing connected

A logic sniffer seems to return nothing unusual too:

![i2c](https://cloud.githubusercontent.com/assets/3453121/6992415/34162b60-dacd-11e4-996b-1abadc856477.PNG)

**EDIT:** Apparently the esp8266 i2c function does use a different return code. Its the number of successfully received bytes I guess

```c
size_t i2c_master_write_to(int address, const uint8_t* data, size_t size, bool sendStop)
{
	i2c_start();
	i2c_write(address << 1);
	int ack = i2c_get_ack();
	const uint8_t* end = data + size;
	for (;data != end; ++data )
	{
		i2c_write(*data);
		ack = i2c_get_ack();
	}
	if (sendStop)
		i2c_stop();
	return size;
}
```

**EDIT2:** After connecting the 1306 oled to a separate arduino and check the i2c address to be 0x3C i meddled a little bit with the Adafruit_SSD1306master, removing conflicting code and adding the esp8266 i2c init I was able to at least draw some lines. Have still to look why the lib hangups, I guess its a wdt timeout issue

**Comment by igrr** [comment]
New Wire library is included in the latest release.
