### ISSUE TITLE
Cannot compile for ESP based boards in Arduino IDE after installing Simulink Support package for Arduino

### ISSUE THREAD

**Issue by Gergosz2** [esp8266/Arduino#4903]
I would like to add some Embeded Coder generated code to my project, but after installing the Simulink Support Package for Arduino, I am not able to compile my project for ESP based boards. The AVR based boards are not affected.

Everytime I try to compile I am given the following errors:

```
Build options changed, rebuilding all
In file included from c:\programdata\matlab\supportpackages\r2018a\3p.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\algorithm:60:0,

                 from C:\ProgramData\MATLAB\SupportPackages\R2018a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\hardware\esp8266\2.4.1\cores\esp8266/Arduino.h:254,

                 from sketch\Project_Home.ino.cpp:1:

c:\programdata\matlab\supportpackages\r2018a\3p.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\utility:68:28: fatal error: bits/c++config.h: No such file or directory

 #include <bits/c++config.h>

                            ^

compilation terminated.

exit status 1
Error compiling for board WeMos D1 mini Pro.
```

**Comment by devyte** [comment]
We don't provide official support for Embedded Coder or Matlab integration.
Some WAGs:
-the generated code could be assuming full support of the c++std lib, but we only have partial support. E.g.: we don't have exceptions on the ESP.
-the installation directory for the core looks weird, but then again I have never used Embedded Coder.
-It's possible that the core installation is incomplete and you may need to do a manual installation or tweak it somehow.
Closing.
