### ISSUE TITLE
Undocumented function fileSize() on SPIFFS

### ISSUE THREAD

**Issue by jindrichsirucek** [esp8266/Arduino#4916]
Hello, Im not sure where to put info about documentation Issue so if this is not the right palce, pls point me to better one... 

In here in documentation:
http://esp8266.github.io/Arduino/versions/2.0.0/doc/filesystem.html#directory-object-dir

is missing documentation of direct function fileSize() on object Directory

> Directory object (Dir)
> The purpose of Dir object is to iterate over files inside a directory. It provides three methods: next(), fileName(), and openFile(mode).
> 

Also Directory example should be changed to this:

```
Dir dir = SPIFFS.openDir("/data");
while (dir.next()) {
    Serial.print(dir.fileName());
    Serial.println(dir.fileSize());
}

```

**Comment by devyte** [comment]
This is the right place. Please make a PR with your suggestions for discussion.

**Comment by jindrichsirucek** [comment]
Hi, thx for feedback and accepting the issue. Im sorry, really new to colaboration in here.. what should I do? make a "PR"? I dont really understand (PR)..

**Comment by devyte** [comment]
PR is Pull Request, which means you propose your changes for discussion, testing, and merging into the repo.

**Comment by jindrichsirucek** [comment]
@devyte thx for explaining of PR.. I have never done that.. I dont know where to really start with PRs..

**Comment by jindrichsirucek** [comment]
I have also found another undocumented function SPIFFS.end()..
