### ISSUE TITLE
error compiling arduino ota

### ISSUE THREAD

**Issue by dwc56** [esp8266/Arduino#4919]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have searched the issue tracker for a similar issue.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:					ESP-12
- Core Version:			[latest git hash or date]
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			Nodemcu
- Flash Mode:			[qio|dio|other]
- Flash Size: 		4MB
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		nodemcu
- Flash Frequency:	40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   115200

### Problem Description

when i try and upload BasicOTA i get this error

### Debug Messages

```
C:\Users\admin\Documents\Arduino\libraries\ArduinoOTA\ArduinoOTA.cpp: In member function 'void ArduinoOTAClass::_onRx()':

C:\Users\admin\Documents\Arduino\libraries\ArduinoOTA\ArduinoOTA.cpp:232:15: error: 'class String' has no member named 'equalsConstantTime'

     if(result.equalsConstantTime(response)) {

               ^

Multiple libraries were found for "ArduinoOTA.h"
 Used: C:\Users\admin\Documents\Arduino\libraries\ArduinoOTA
 Not used: C:\Users\admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ArduinoOTA
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi 
Using library ESP8266mDNS in folder: C:\Users\admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266mDNS (legacy)
Using library ArduinoOTA at version 1.0 in folder: C:\Users\admin\Documents\Arduino\libraries\ArduinoOTA 
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
```

**Comment by d-a-v** [comment]
> Multiple libraries were found for "ArduinoOTA.h"
 Used: C:\Users\admin\Documents\Arduino\libraries\ArduinoOTA
 Not used: C:\Users\admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ArduinoOTA

`C:\Users\admin\Documents\Arduino\libraries\ArduinoOTA` is in the way. Just move it elsewhere.
I'm not sure how the IDE is choosing which version to use nor whether there is a good way of helping it selecting the good version.

**Comment by dwc56** [comment]
Thank you i moved it and now it works

**Comment by devyte** [comment]
This looks like an installation issue. Closing.
