### ISSUE TITLE
ESP8266 Exception Code 29

### ISSUE THREAD

**Issue by jy824212** [esp8266/Arduino#4923]
I follow the post from this link

https://forum.arduino.cc/index.php?topic=540292.0

I am using my ESP8266 to push data to the cloud
But I have encountered this error:
Every time when push the message to the cloud I saw this issue

I highly doubt if the memory has ran out since I used 60 % of the memory space.

Exception (29):
epc1=0x40220f72 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000004 depc=0x00000000

ctx: cont
sp: 3fff2fa0 end: 3fff3980 offset: 01a0

            stack>>>
            3fff3140: 00820000 00000082 3fffa7ec 4022f3d2
            3fff3150: 3fff2874 3fff8a5c 3fffa7ec 4022f5cc
            3fff3160: 3fffba64 00000208 3fffba64 40100670
            3fff3170: 00000104 00007bc0 00000f78 00000042
            3fff3180: 00000040 00000082 3fffa7d4 4022f8e5
            3fff3190: 00800000 00000080 00000000 00000041
            3fff31a0: 00000040 0000003f 3fffa7a4 00000041
            3fff31b0: 3fffb64c 3fffa7d4 3fffa7a4 3fff9f6c
            3fff31c0: 3fffbb60 ffffffff 3fff8a5c 40217f80
            3fff31d0: 00000040 3fff8a5c 3fffa7d4 3fff8a5c
            3fff31e0: 00000040 3fff8a5c 3fffa7d4 4023041f
            3fff31f0: 3fff8aa4 0000003f 9c2b1f35 00000001
            3fff3200: 3fff8a5c 3fffa7bc 3fffa7d4 00000001
            3fff3210: 00000010 3fff8a5c 0000000f 40230674
            3fff3220: 3fffa7a4 3fff9f54 0000000f 00000001
            3fff3230: 00000001 3fff9324 3fff6a19 4022f478
            3fff3240: 00000100 3fff84bc 3fff697f 00000000
            3fff3250: 00000100 3fff84bc 3fff697f 402317fd
            3fff3260: 3fff3290 00000000 000000d0 00000030
            3fff3270: 07d18ea8 00000016 3fff5b18 00000004
            3fff3280: 3fff7697 3fff85bc 3fff6979 4022c4f8
            3fff3290: cfe90303 7860be45 412cfc9c 2cb9bd1e
            3fff32a0: a1b60e86 82262512 33ab6007 3d46a1a7
            3fff32b0: 1ef84775 f6c45cda b5d26d96 8ea85f7f
            3fff32c0: 3fff7697 00000000 3fff85bc 4022c8da
            3fff32d0: 9c53984d a6139611 b5db6a1a ce35a6b9
            3fff32e0: a3286cdf bd96aa4f 5c953e12 4504a6ee
            3fff32f0: 00000031 3fff7676 3fff7676 3fff988c
            3fff3300: 00000021 00000c4d 3fff97ec 40217f40
            3fff3310: 0000004a 00000000 0000000d 00000004
            3fff3320: 3fff7697 00000004 3fff85bc 00000004
            3fff3330: 3fff7697 00000004 3fff85bc 4022c300
            3fff3340: eb80ae8b 000002e3 000002e3 0000000e
            3fff3350: 00000043 3fff6979 3fff85bc 4022c6dc
            3fff3360: 00000029 3fff69ac 3fff85bc 401004d8
            3fff3370: 3fff33c8 0000000e 00000010 3fff6954
            3fff3380: 402134cc 3fff85bc 3fff33c0 01000000
            3fff3390: 3fff33c8 0002d76a 3fff85bc 4022c468
            3fff33a0: 3fff85bc 3fff55bc 3fff5efc 3fff6954
            3fff33b0: 3fff54ec 0002d76a 3fff5efc 40213cad
            3fff33c0: 3fff85bc 3fff55bc 40217ec8 3fff2960
            3fff33d0: 00002710 00002710 00002710 4020ceab
            3fff33e0: 3fff2650 00000000 3fff54ec 00000000
            3fff33f0: 3fff86c4 00000000 3fff2650 40213efb
            3fff3400: b9474c28 00000000 00000003 00000000
            3fff3410: 3fff86c4 4020ad38 3fff2650 40213f50
            3fff3420: 40107508 b9474c28 3fffa07c 3fff34a0
            3fff3430: 40206328 3fff8694 000022b3 4021458e
            3fff3440: 40107508 b9474c28 40107508 b9474c28
            3fff3450: 40107508 b9474c28 4020aaf0 402065a1
            3fff3460: 3fff9d94 3fff34c0 3fff9d94 401004d8
            3fff3470: 00000000 3fff34c0 0000000c 3fff2398
            3fff3480: 3fffa07c 3fff34e0 3fff9d94 4020dfb2
            3fff3490: 3fff9d94 3fff8694 3ffeb374 3fff2398
            3fff34a0: 3fffa07c 3fff34e0 3fff9d94 4020b6c4
            3fff34b0: 3fff9d94 3fffa0c4 3fff9c64 402044e6
            3fff34c0: 3fff88b4 00000000 00000000 00000000
            3fff34d0: 3fff5f2c 3fffa0c4 3fff9c64 4020565c
            3fff34e0: 3fff9d0c 00000000 00000000 3fff961c
            3fff34f0: 3fffa0c4 000000f0 00000001 00000000
            3fff3500: 00000000 00000000 3fff24b0 4021430c
            3fff3510: 00000001 3fff6964 0000008e 3ffe9c26
            3fff3520: 3fff24b0 7f7f4000 3ffe9c25 3fff2398
            3fff3530: 3fff604c 3fff9fb4 3fff6044 40206068
            3fff3540: 3fff24b0 3ffe85b0 3fff6044 40201a9c
            3fff3550: 000003e8 00000453 00000453 4010020c
            3fff3560: 3fff604c 3ffe85b0 3fff3890 40100690
            3fff3570: 3fff24b0 3ffe85b0 3fff2898 3fff2398
            3fff3580: 3fff24b0 3ffe85b0 3fff2898 40211999
            3fff3590: 5357227b 2244494e 4335223a 46374643
            3fff35a0: 32333343 2c224433 6e655322 44726f73
            3fff35b0: 22617461 227b5b3a 65707954 2c343a22
            3fff35c0: 6c615622 3a226575 2c7d3032 7954227b
            3fff35d0: 3a226570 56222c30 65756c61 325b3a22
            3fff35e0: 2c322e35 332e3432 2e35322c 35322c39
            3fff35f0: 322c322e 2c332e34 392e3532 2e35322c
            3fff3600: 34322c32 322c332e 2c392e35 322e3532
            3fff3610: 2e34322c 35322c33 7d5d392e 00007d5d
            3fff3620: 00000000 00000000 00000000 00000000
            3fff3630: 00000000 00000000 00000000 00000000
            3fff3640: 00000000 00000000 00000000 00000000
            3fff3650: 00000000 00000000 00000000 00000000
            3fff3660: 00000000 00000000 00000000 00000000
            3fff3670: 00000000 00000000 00000000 00000000
            3fff3680: feefeffe feefeffe feefeffe feefeffe
            3fff3690: feefeffe feefeffe feefeffe feefeffe
            3fff36a0: feefeffe feefeffe feefeffe feefeffe
            3fff36b0: feefeffe feefeffe feefeffe feefeffe
            3fff36c0: feefeffe feefeffe feefeffe feefeffe
            3fff36d0: feefeffe feefeffe feefeffe feefeffe
            3fff36e0: feefeffe feefeffe feefeffe feefeffe
            3fff36f0: feefeffe feefeffe feefeffe feefeffe
            3fff3700: feefeffe feefeffe feefeffe feefeffe
            3fff3710: feefeffe feefeffe feefeffe feefeffe
            3fff3720: feefeffe feefeffe feefeffe feefeffe
            3fff3730: feefeffe feefeffe feefeffe feefeffe
            3fff3740: feefeffe feefeffe feefeffe feefeffe
            3fff3750: feefeffe feefeffe feefeffe feefeffe
            3fff3760: feefeffe feefeffe feefeffe feefeffe
            3fff3770: feefeffe feefeffe feefeffe feefeffe
            3fff3780: feefeffe feefeffe feefeffe feefeffe
            3fff3790: feefeffe feefeffe feefeffe feefeffe
            3fff37a0: feefeffe feefeffe feefeffe feefeffe
            3fff37b0: feefeffe feefeffe feefeffe feefeffe
            3fff37c0: feefeffe feefeffe feefeffe feefeffe
            3fff37d0: feefeffe feefeffe feefeffe feefeffe
            3fff37e0: feefeffe feefeffe feefeffe feefeffe
            3fff37f0: feefeffe feefeffe feefeffe feefeffe
            3fff3800: feefeffe feefeffe feefeffe feefeffe
            3fff3810: feefeffe feefeffe feefeffe feefeffe
            3fff3820: feefeffe feefeffe feefeffe feefeffe
            3fff3830: feefeffe feefeffe feefeffe feefeffe
            3fff3840: feefeffe feefeffe feefeffe feefeffe
            3fff3850: feefeffe feefeffe feefeffe feefeffe
            3fff3860: feefeffe feefeffe feefeffe feefeffe
            3fff3870: feefeffe feefeffe feefeffe feefeffe
            3fff3880: feefeffe feefeffe feefeffe feefeffe
            3fff3890: 00000000 00000000 00000000 332e3432
            3fff38a0: 35320030 0030392e 322e3532 34320030
            3fff38b0: 0030332e 392e3532 35320030 0030322e
            3fff38c0: 332e3432 35320030 0030392e 322e3532
            3fff38d0: 34320030 0030332e 392e3532 30350030
            3fff38e0: 00310030 00203032 00000000 00000000
            3fff38f0: 00000000 00000000 00000000 00000000
            3fff3900: 00000000 00000000 00000000 00000000
            3fff3910: 00000000 00000000 3fff4d3c 0000000f
            3fff3920: 00000000 3fff002c 3fff24b0 4020e62d
            3fff3930: 3fff6044 3fff38f4 3fff390c 3fff3590
            3fff3940: 3fff3584 3fff248c 00000000 40216e1c
            3fff3950: 00000000 00000000 00000001 3fff2958
            3fff3960: 3fffdad0 00000000 3fff2951 40217f14
            3fff3970: feefeffe feefeffe 3fff2960 40100710
            <<<stack<<<

I installed everything then I copy paste my exception code into the decoder:

The decoder always fails to decode this exception

Does anyone know what is going on here or if someone's decoder is working would you help me to decode my message and tell me the reason that cause the exception.

Really appreciate.

**Comment by devyte** [comment]
The decoder requires your own binary to decode, nobody else can decode your dump for you.  I have never seen it fail, so If it is failing for you, maybe it's an installation issue, either with the decoder, the core, or both. I suggest backing up your projects, deleting everything related to the core and the IDE/pio/whatever, and installing from scratch.

I can't reproduce this with my own app. I don't think there is anything to do in this repo, so closing.
