### ISSUE TITLE
ESP8266 12E with relay board with 4-channel 

### ISSUE THREAD

**Issue by issa13** [esp8266/Arduino#4928]
Why when the output in certain digital pin in the esp is high, the relay that's connected to that digital pin is off

**Comment by issa13** [comment]
OK, but please can you help me🙏

**Comment by lrmoreno007** [comment]
It's not the best place to solve your problem, this site is for issues in the ESP8666 / Arduino core. Not to solve your electronic knowledge problems. Next time ask in esp8266.com or other forum like stackoverflow.com.

---

Most relay modules have inverted logic. Take a look at this schema:
![t2 e5jxcxaxxxxxxxx_ 407779758](https://user-images.githubusercontent.com/7408539/42786789-cd9b56fc-8957-11e8-8eb9-7fbc9e581224.jpg)

Led in the octocoupler is high when pin is LOW.

**Comment by issa13** [comment]
Ok thank you and I'm sorry if I'm bothering you
