### ISSUE TITLE
Interfacing pin D8 of the NodeMCU into 5v relay board with 4-channel

### ISSUE THREAD

**Issue by issa13** [esp8266/Arduino#4930]
When I connect pin D8 of the NodeMCU to the relay module the program won't run 
What is the problem? Does pin D8 a special pin or what? And how can I solve this problem 
Thank you for your interest.

**Comment by Quiqui64** [comment]
FYI,
http://www.forward.com.au/pfod/ESP8266/GPIOpins/index.html

**Comment by devyte** [comment]
Issue template was ignored, no mcve sketch.
This is an issue tracker, not a general support forum, please read the issue template and the issue POLICY doc for more details.
Closing.
