### ISSUE TITLE
How to download a web image to esp8266  SPIFFS

### ISSUE THREAD

**Issue by wgqkill** [esp8266/Arduino#4954]
I'm trying to download a Web picture to esp8266 SPIFFS, using Arduino IDE.
For example:
https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_120x44dp.png

I'd appreciate suggestions on how to use esp8266 get  the web image to SPIFFS, if possible.
Thank you,
Dave！

void loop() {  
HTTPClient http;  
Serial.println("Try link to http.");  
http.begin("https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_120x44dp.png");

int Code = http.GET();  
if(Code)  
{  
    Serial.printf("HTTP Code:%d\n",Code);    
    String payload = http.getString();  
    Serial.println(payload);  
    }  
    else  
{  
  Serial.println("Couldn't link to server");  
} 

I tried to get images from the syntax above, but failed.
![image](https://user-images.githubusercontent.com/41622082/43131776-6e601518-8f6c-11e8-8a5c-bf49d12bbcc6.png)

**Comment by devyte** [comment]
When you opened the issue, the very first line of the template reads:
> If your issue is a general question, starts similar to "How do I..", is related to 3rd party libs, or is related to hardware, please discuss at a community forum like esp8266.com.

Closing.
