### ISSUE TITLE
SPI::transferBytes pending changes

### ISSUE THREAD

**Issue by devyte** [esp8266/Arduino#4967]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:			        all
- Core Version:			latest git
- Development Env:		all
- Operating System:	        all

### Settings in IDE

- Module:  			all
- Flash Mode:			all
- Flash Size: 		all
- lwip Variant:   all
- Reset Method:		all
- Flash Frequency:	40Mhz
- CPU Frequency:		80Mhz|160MHz
- Upload Using:		SERIAL
- Upload Speed:   115200

### Problem Description

This issue is meant to track pending changes to SPI::transferBytes, specifically a missing assert and some api optimizations.
Ref: #4925 #2677 .

*edit 19/01/22 d-a-v*: The API has to be clarified. `transfer(buffer)` and `transferBytes(buffer)` have the same signature, the first accepts unaligned buffer, not the second.

**Comment by earlephilhower** [comment]
I would suggest supporting a simple alignment check and fix for transferBytes() because I believe it used to support unaligned transfers and libs like SDFat were using it that way.  The simple fixup should decompse to an "AND" of the address and a jump-on-zero (2 or 3 insns total) addition to transferBytes() and make things easier for existing older libs.

**Comment by earlephilhower** [comment]
Specifically, transferBytes needs to handle misaligned pointers and non-by-4 lengths.
https://github.com/greiman/SdFat/pull/125
