### ISSUE TITLE
[Servo] Small jitter without having changed the position in the code.

### ISSUE THREAD

**Issue by rtek1000** [esp8266/Arduino#4968]
Hello,

I would like to know if it is normal for the servo control to have a jitter, a small time offset in the signal sent to the servo, which causes it to move a little, even without having changed the position in the code.

If I use only the sketch below, it will give very little jitter, but if I use with Wifi Manager and Arduino OTA, this problem is quite remarkable.

Thank you.

```
#include <Servo.h>

#define Pin D8

int Pos = 49;

Servo servo;  // create servo object to control a servo

void setup() {
  // put your setup code here, to run once:
  servo.attach(Pin);  // attaches the servo

  servo.write(Pos);
}

void loop() {
  // put your main code here, to run repeatedly:

}
```

**Comment by devyte** [comment]
@rtek1000 when you opened the issue, you were presented with an issue template with instructions, which you have completely ignored. Please open a new one issue with the requested info filled out.
