### ISSUE TITLE
Download web pic to spiffs

### ISSUE THREAD

**Issue by wgqkill** [esp8266/Arduino#4976]
**Platform**
Hardware:	[ESP-WROOM-02](it is based on esp8266 with 2MB flash size)
Core Version:	[latest git hash or date]
Development Env:	[Arduino IDE]
Operating System:	[Windows]

**Settings in IDE**
Module: [Generic ESP8266 Module]
Flash Mode:	[dio]
Flash Size: [2MB]
lwip Variant: [v2 Lower Memory]
Reset Method:	[ck]
Flash Frequency:	[40Mhz]
CPU Frequency:	[80Mhz]
Upload Using:	[SERIAL]
Upload Speed: [115200] (serial upload only)

**Problem Description**

I'm trying to download a Web picture to esp8266 SPIFFS, using Arduino IDE.
png add:
https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_120x44dp.png

....
myFile = SPIFFS.open("google.png","w");
String gogole=(String)("POST ") + PostUrl + " HTTP/1.1\r\n" +   
               "Content-Type: application/force-download"+ "\r\n" +
               "Content-Transfer-Encoding: binary" + "\r\n" +
               "Content-Type: image/png" + "\r\n" +

  if (myFile) {
              while (myFile.available()) {
                myFile.print(client.read());  //考虑read是否存数组，借鉴发送图片的方法，倒退
              }
              myFile.close();
            }     

But it didn't work. I didn't keep this picture in my spiffs. How could I do it more effectively?

**Comment by devyte** [comment]
The very first line of the issue template reads:
> If your issue is a general question, starts similar to "How do I..", is related to 3rd party libs, or is related to hardware, please discuss at a community forum like esp8266.com.

Also, the C in MCVE means Complete, and your sketch isn't.
Closing, see issue template instructions and issue POLICY doc for more details.
