### ISSUE TITLE
Auto upload working in Win7 but not in Ubuntu Linux

### ISSUE THREAD

**Issue by guyelg** [esp8266/Arduino#498]
Hi
I have tried to upload new sketch to Nodemcu Dev Board V0.9 .
Same computer and same USB port.
Its work like charm in Win7  but with Ubuntu i have to press on the upload botton
10x
Guy
##

**Comment by devyte** [comment]
I can flash Nodemcu boards from Ubuntu without issues. 
Closing due to age, lack of info, and can't reproduce.
