### ISSUE TITLE
Unstable system (probably due to mem corruption)

### ISSUE THREAD

**Issue by Raphyyy** [esp8266/Arduino#4991]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12]
- Core Version:			latest git, 2.4.0, 2.3.0
- Development Env:		[Arduino IDE,Platformio]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio]
- Flash Size: 		[4MB]
- lwip Variant:   [v1.4]
- Reset Method:		[ck]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[OTA,SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

Hello

I am getting back to you today with the same issue I opened months ago : https://github.com/esp8266/Arduino/issues/4193

After many talks with @devyte who I am grateful to, I still haven't found the origin of those troubles.

It's obviously some memory corruption problem, but I can't achieve to find where could possibly be the problem. 

**The entiere problem and all of what I tried are well described in the issue I linked above**.

If some of you are interested to helping me to spot those memory problem, I can send you an archive of my code on gitter : https://gitter.im/Raphyyy

I am really sorry to flood here with the same issue, but this concern a professionnal embedded project and I really need to find a solution after months of trouble. 

Best regards

**Comment by devyte** [comment]
@Raphyyy you ignored the issue template again. Please edit the post and add in all of the required info.

**Comment by Raphyyy** [comment]
Hello devyte
My bad. Template filled.

**Comment by Raphyyy** [comment]
@devyte I have lot more mem corruption with > 2.4 so currently the 2.3.0 core run in prod.
I use latest Git, so nothing change from 2.4.1 to 2.4.2.

Some news : I updated all of my code to use stack the less possible. No more char array buffer.
Tested with 2.4.2, 2.4.1, 2.3.0, still the same problems...

**Comment by devyte** [comment]
@Raphyyy what is your status with 2.5.0-beta1? At least two fixes related to mem corruption are included, although I don't know if they apply to you.

**Comment by earlephilhower** [comment]
Closing as no MCVE and no response.
