### ISSUE TITLE
mDNS announces services and then disappear after some minutes (v 2.4.1)

### ISSUE THREAD

**Issue by daspuru** [esp8266/Arduino#4993]
Hi all!

I have tried to implement all reachable mDNS example on the docs and in search engines, however, I am able to see the service announced with any Bonjour or Zeroconf browser, but after some minutes the service disappear, the only way to see it again is restarting the module. The same behavior applies if using the latest firmware AT version command AT+MDNS.

Any suggestions with that? I have searched the web for this and can not find answer to this problem that a lot of users are facing, is it just that mDNS functionality does not work in ESP8266? 

Thank you a lot for your help.

**Comment by devyte** [comment]
Issue template has been ignored. Closing.
