### ISSUE TITLE
small CRQ to platform.txt

### ISSUE THREAD

**Issue by 5chufti** [esp8266/Arduino#5007]
@igrr 
would it be possible to append version to the name, so one gets info about the installed version when selecting an esp board (modules)?

>name=ESP8266 Boards (core 2.4.2) 
version=2.4.2

instead of

>name=ESP8266 Modules
version=2.4.2

"Boards" instead of "Modules" just to be inline with the rest ...

**Comment by igrr** [comment]
Great suggestion @5chufti. Have had times when I thought I was running one of the released versions when if fact it was git version. Would help in such cases as well.
