### ISSUE TITLE
I2C connection with PN532 chip not working

### ISSUE THREAD

**Issue by AldoMyrtaj** [esp8266/Arduino#501]
I am trying to connect my PN532 chip with the elechouse/PN532 library but it seems that even though that Wire.begin(0,2) is set in order to use the SCL and SDA on pins 0 and 2 of my ESP8266 01, it is impossible to recognize the PN532 chip. Judging by what i have debugged so far the Wire.beginTransmition Function is not starting the I2C transmission on the PN532 address. Some ideas how to overcome this?

**Comment by Lstt2005** [comment]
See this - https://github.com/esp8266/Arduino/issues/253
