### ISSUE TITLE
Feature request: wifi_set|get_country

### ISSUE THREAD

**Issue by marcelstoer** [esp8266/Arduino#5031]
Please expose `wifi_get_country` and `wifi_set_country` documented at https://www.espressif.com/sites/default/files/documentation/2c-esp8266_non_os_sdk_api_reference_en.pdf#page=76. The default country is `CN`.

**Comment by luc-github** [comment]
it is available in user_interface.h,  no ?

https://github.com/esp8266/Arduino/blob/master/tools/sdk/include/user_interface.h#L750-L760

**Comment by marcelstoer** [comment]
Arggh, you're right, thanks.

**Comment by devyte** [comment]
@marcelstoer your request is still valid if rephrased as an enhancement to the WiFi interface.
