### ISSUE TITLE
read compleat response in WiFiClientSecure.

### ISSUE THREAD

**Issue by c0otlass** [esp8266/Arduino#5035]
hi.
i used WiFiClientSecure example but in response client read string until new line
`  String line = client.readStringUntil('\n');`
is there any function read complete client response? 
my response is corrupted :
```
WiFi connected
IP address: 
192.168.137.66
connecting to httpbin.org
certificate matches
requesting URL: /get
request sent
headers received
reply was:
==========
{
==========
closing connection
```

**Comment by devyte** [comment]
Issue template and its instructions has been completely ignored => Closing.
Please open a new issue and fill out the required info.
