### ISSUE TITLE
WiFiClientSecure  loadCACert  always returns true

### ISSUE THREAD

**Issue by romelemperado** [esp8266/Arduino#5053]
### Basic Infos

- [x ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [x ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12|ESP-01|ESP-07|ESP8285 device|other]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE|Platformio|Make|other]
- Operating System:		[Windows|Ubuntu|MacOS]

### Settings in IDE

- Module:  			[Generic ESP8266 Module|Wemos D1 mini r2|Nodemcu|other]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

I can connect to the mqtt broker using self signed certs but when I try to disabled my wifi/router I can still see that this line  `bool ret = espClient.loadCACert(ca);` returns true even the absense of internet? If that is the case then it is not really verifying? I need your thoughts on this issue..
```
boolean checkCertificates(){

  // Get certs from file system and load into WiFiSecure client

  SPIFFS.begin();
  File ca = SPIFFS.open(CA_CERT_FILE, "r");
  if(!ca) {
    Serial.println("Couldn't load CA cert");
  } else {
    bool ret = espClient.loadCACert(ca);
    Serial.print("Loading CA cert returned ");
    Serial.println((ret)? "true" : "false");
    ca.close();

  }
```
}

From serial logs..

> Loading CA cert returned true
> Attempting MQTT connection...
> Attempting MQTT connection...
>

**Comment by Eszartek** [comment]
Your program is reading  the CA_CERT_FILE from flash storage, not the internet. You don't need internet access to read from a  flash file system.

**Comment by romelemperado** [comment]
Closing this issue.. Thank you Eszartek... :)
