### ISSUE TITLE
node mcu spi slave information

### ISSUE THREAD

**Issue by prateek027** [esp8266/Arduino#5066]
Hi,
I just know the few things about the spi slave data transfer.
i am follow your library and need some information about the library (SPI Slave in NodeMcu ESP8266

1- What is the SPI Mode you are using.
2- what is the Data Rate you are using.
3- what is the clock configuration.
4- master Sends 16 Byte Data length for 10 Times but it only receive 3 Strings of 16 Bytes in which 11 Bytes are correct rest 5 Not.
5- if I need to Receive only 4 or Less than 4 Bytes in One time then where i can change for receive correct Data.

i need to receive 1024 bytes from master and data comes in 16 Bytes array length.

**Comment by devyte** [comment]
This is a "How do I" type question. The issue template is explicit about not handling such issues in this tracker. Please refer to a community forum, readthedocs, use the source, etc.
Closing.
