### ISSUE TITLE
strage problem with HTTP get

### ISSUE THREAD

**Issue by smartman2012** [esp8266/Arduino#5074]
Hello, guys,
I have a server-side based on PHP and MySQL so the server output is like json array.
from esp, I'm sending HTTP get request to my server to get data. esp gets data and shows it in serial monitor but after changing data on the server using another PHP code esp does not update data correctly. its results fluctuate between old data and new data randomly.
If i check the URL manually in browser data is updated and does not have any problem.
I don't know what should i do. 
is this a server side problem or client-side? 
after about 7 minutes serial monitor shows new data as stable as it should be.

**Comment by 5chufti** [comment]
a) did you carefully read and fill out the template you were presented when opening the issue? "NO"
b) did you present any relevant information about the sketch you are using on which hw? "NO"
c) if it sometimes works (and only sometimes fails) do we think it is an issue with the arduino esp8266 core? "NO" 
so please close this non_issue and seek for help on programming esp8266 arduino ide (and 3rd party libs) in some user forum like www.esp8266.com
