### ISSUE TITLE
Please add 2M flash with smaller SPIFFS (e.g. 2M.512k)

### ISSUE THREAD

**Issue by TD-er** [esp8266/Arduino#5096]
As extension on this PR: https://github.com/esp8266/Arduino/pull/4988

That PR added a config for:

Flash Split for 2M chips
- sketch 1019KB 
- spiffs 1004KB
- eeprom 20KB 

But that layout does only allow for OTA update of sketches up-to 510k (or a bit more when using two-step update)
So I guess for the Shelly1 and other 2M modules it would be more useful to have 256k or 512k SPIFF and 20k EEPROM. The rest should then be available for the sketch, to allow for easier OTA updates.

For example:

- sketch 1516 kB 
- spiffs 512 kB
- eeprom 20 kB 

`flash_size(0x200000,   '2M', '2m512',   '512K SPIFFS',  1044464, 0x17B000,   0x80000, 8192)`

**Comment by SConaway** [comment]
@d-a-v Have you started with any progress? I'll give it a shot.

**Comment by d-a-v** [comment]
#5103 needs testing
