### ISSUE TITLE
Issue with float values/calculation

### ISSUE THREAD

**Issue by ManiackCZ** [esp8266/Arduino#51]
The calculations with floats doesnt work. It averages to integer.
<code>float i;
i = 5/2;
</code>
I have hooked up oled display and when I print the value, it shows just 2.00. First, I thought it may be just problem with display, so I get it to send the value back over serial but I got <code>2.0000000000</code> too.

**Comment by thomasfla** [comment]
Normal, you do an int operation. Do 5/2.0 or ((float)5)/2

**Comment by ManiackCZ** [comment]
Thx, missed that.

**Comment by leandrogs** [comment]
I am also having this issue. I receive different data from sensor using GPIO (Wire library) and at some point I have `scaled.YAxis = ((float)raw.YAxis) + 0.92;` where `scaled.YAxis` is a float and `raw.Yaxis` is an int. I know that `raw.YAxis` is 243, so my output should be 243.92 but what I get is 219.08.
