### ISSUE TITLE
Writing files with SPIFFS very slow with puya patch

### ISSUE THREAD

**Issue by oulahrir** [esp8266/Arduino#5105]
@igrr 

Basic Infos
SPIFFS very slow writing (about 25s for 240kb ! )

Hardware
Hardware:	ESP-01
Flash : P25Q80H

Description
Problem description
SPIFFS worked after making puya patch correcting but now, problem is about speed to write data in SPIFFS. This process take long time (about 25 s for wrting 240 Kb in my case),

DO you think problem could be fix by replacing PUYA flash by WINBOND ?

Settings in IDE
Module: Generic ESP8266 Module
Flash Size: 1MB (512k SPIFFS)
CPU Frequency:	80Mhz
Flash Mode:	QIO (also trie with DIO )
Flash Frequency:	40Mhz
Upload Using:	SERIAL
Reset Method:	ck

**Comment by devyte** [comment]
Right now, the puya patch is the only reason the puya-based boards are even usable. I don't think there is anything in software that can be readily done at this time, so if speed is an issue, either break your data into smaller files, or replace the flash chip.
BTW,  SPIFFS is known to have some performance issues with larger data. Before you go off and start replacing chips,  I suggest testing your code on a non-puya board to check the write time.
Closing for now as non-actionable.
