### ISSUE TITLE
How to access RSA Encryption functions?

### ISSUE THREAD

**Issue by ayushsharma82** [esp8266/Arduino#5109]
### Basic Infos

As the TLS feature has been ported to ESP8266. I Believe it uses RSA Encryption?

I would like to access the RSA encryption and decryption functions for 'end to end encryption' in my application.  Where can i find the relevant header file in the library?

**Comment by devyte** [comment]
The first line of the issue template reads:
> If your issue is a general question, starts similar to "How do I..", is related to 3rd party libs, or is related to hardware, please discuss at a community forum like esp8266.com.

Look at the bearssl WiFiClientSecure examples.
Closing.
