### ISSUE TITLE
problem install library

### ISSUE THREAD

**Issue by MichaelIndra** [esp8266/Arduino#5111]
Hi i'm new in arduino. So i got problem to upload your library. Arduino IDE catch some error log "Invalid library found in C:\Users\user\Documents\Arduino\libraries\Arduino-master: C:\Users\user\Documents\Arduino\libraries\Arduino-master" and i don't know to solve this problem. Can you help me to fix it?? Thank you so much

**Comment by devyte** [comment]
This is an issue tracker, and therefore not the right place to ask support questions. Please refer to a community forum like esp8266.com or stackoverflow. See issue template instructions and issue POLICY doc for details.
Closing.
