### ISSUE TITLE
mDNS query fails to return any results when SRV answer has zero-length answerHostName

### ISSUE THREAD

**Issue by acoulson2000** [esp8266/Arduino#5114]
### Problem Description

I am querying for a service name and get no result even though the service has definitely been announced and can be queried from command line with "dns-sd  -B _colorchord local"

I the debug log in ESPm8266mDNS.cpp and noticed  that there is a zero-length hostname following the SRV response (see below), but further down in the code, the cursor is advanced 1 byte anyway by this code (around line 718):

```
        if (answerRdlength - (6 + 1 + tmp8) > 0) { // Skip any remaining rdata
          _conn_readS(hostName, answerRdlength - (6 + 1 + tmp8));
        }
```
I found that this change corrects the problem:

`        if (tmp8 >0 && answerRdlength - (6 + 1 + tmp8) > 0) { // Skip any remaining rdata
`

Hopefully someone who knows this code better than I do can merge a similar fix in.

###  Sketch
```
...
if (MDNS.begin(hostString)) {
  int n = MDNS.queryService("colorchord", "tcp");
  Serial.println("mDNS query done");
  if (n == 0) {
    Serial.println("no colorchord found");
  } else {
    colorChordIP = MDNS.IP(0);    
  }
  Serial.println(colorChordIP);
}
...
```

### Debug Messages

queryService colorchord tcp
Waiting for answers..
Reading answers RX: REQ, ID:0, Q:0, A:4, NS:0, ADD:0
 11 _colorchord
found matching service: colorchord
 4 _tcp
 5 local
type: 000c rdlength: 13
PTR 13 
esp_67fa9f⸮
 10 esp_67fa9f
Compressed pointer, jumping from 72 to 12
 11 _colorchord
found matching service: colorchord
 4 _tcp
 5 local
Compressed pointer, jumping back to 72
type: 0010 rdlength: 23
TXT 23 A Colorchord Webserver
 10 esp_67fa9f
Compressed pointer, jumping from 118 to 12
 11 _colorchord
found matching service: colorchord
 4 _tcp
 5 local
Compressed pointer, jumping back to 118
type: 0021 rdlength: 8
SRV 0 

Data len too long! 1216

**Comment by devyte** [comment]
Closing in view of #5442 with a full rewrite of mdns.
