### ISSUE TITLE
boot-up problem after using Serial.swap() because of GPIO15 !

### ISSUE THREAD

**Issue by Rasoul-Khajavi** [esp8266/Arduino#5123]
Hi , i'm having a connection through UART and i use serial.swap() to change the pins of UART for having communication with another device . ( i cant use original pins because of problems with Serial programming whitch causes the 2nd device to crash )
after i use serial.swap() the 2 pins for UART are GPIO13 and GPIO15 . 
but we should pull-down GPIO15 for booting up from flash ... 
how can i use the second UART pins but also making sure that if my module resets it will boot up from flash (and not from SD-Card ) ?

**Comment by 5chufti** [comment]
and why do you think this is an issue with the esp srduino core?
Did you read and understand the questionair you were presented when starting the issue?
Please close the issue and discuss your problem on an appropriate user forum (e.g. www.esp8266.com)

**Comment by devyte** [comment]
Closing. See issue POLICY doc and issue template instructions for more details.
