### ISSUE TITLE
Issue of Communication between two esp8266 using arduino 

### ISSUE THREAD

**Issue by thrinasco** [esp8266/Arduino#514]
Hi,

This is venkat,Please ,I would request you to clear one of my doubt.i was using the following library for communication  
https://github.com/INEXTH/Arduino-ESP8266_libs

Server is created and when i am starting server to make communication between them iam getting the following error which was marked.

AT+CIPSTART=(4)("TCP"),("192.16ø.4.1"),(80)
Link typ ERROR

I am doing these commuinication using two esp8266 with two arduino boards.

​
![link](https://cloud.githubusercontent.com/assets/12268500/8540763/2ac35baa-24a6-11e5-8009-aa9937ef7151.png)

**Comment by me-no-dev** [comment]
You show an example that is using an arduino to talk to esp8266 using the AT firmware.
This thing we do here is totally different. We use the ESP instead of AVR arduino and program straight on it.
