### ISSUE TITLE
ESP8266 WIFI_AP with WPS

### ISSUE THREAD

**Issue by ripper121** [esp8266/Arduino#5152]
Is there a Sample about, how to use WIFI_AP with WPS?

Or is this not possible?

**Comment by d-a-v** [comment]
WPS is for connecting the esp8266 STATION interface to a WPS-enabled access point.

To my knowledge, the esp8266 does not provide the WPS access-point side for external wifi stations.

**Comment by ripper121** [comment]
Would it possible to implement it, or is this not possible, because the SDK isnt supporting it?

**Comment by d-a-v** [comment]
Low-level wifi features are indeed beyond the scope of the arduino core.
