### ISSUE TITLE
How "[LWIP] Fix the sequence number error of RST+ACK;" bug fixed by the official SDK relates to this issue?

### ISSUE THREAD

**Issue by NayanKaran** [esp8266/Arduino#5154]
https://github.com/espressif/ESP8266_NONOS_SDK/releases/tag/v2.2.0

_Originally posted by @NayanKaran in https://github.com/esp8266/Arduino/issues/4118

**Comment by d-a-v** [comment]
We are not using lwIP implementation from espressif.
Please note that RST is about ending the connection, so this fix would only fix issues with the last bytes of a stream or smooth closing.

There are recent improvements on original lwIP side (the one used here), namely partial TCP SACK support that improves reliability on large streams.
It is however currently not merged, but you can give a try with either #5126 or #5136.
