### ISSUE TITLE
Check if file is already open?

### ISSUE THREAD

**Issue by lampmaker** [esp8266/Arduino#5177]
Hi,

I've been going trough the docs but couldn't find an answer to this:

what happens if I call spiffs_open() twice with the same path+filename ?     Do I get two different filehandles to the same file?
Is there any way to prevent or detect this?   I have a situation where a file might or might not be open. If it is not open, it should be opened, if it is open, the existing filehandle should be used.    

If course, I can write some code to check the names of open files, but if there is an easy way to do this with SPIFFS, that would have my preference..

Thanks!

**Comment by devyte** [comment]
if(File) {blah;}

This is not the right place to ask such "How do I" type questions. The first line of the issue template, which you completely ignored, has explicit instructions about this.
Closing.
