### ISSUE TITLE
change esptool exe permission on windows build

### ISSUE THREAD

**Issue by hallard** [esp8266/Arduino#518]
Guys,
when I pull repo and build (cygwin) with ant under windows (8.1 x64) the programmer file esptool does not have the execute permission, this makes the IDE unable to launch the tool and fire a error.

![image](https://cloud.githubusercontent.com/assets/2471931/8568327/fdbf8a80-256c-11e5-939a-87dd00bace5c.png)

firing a
`chmod ug+x windows/work/hardware/esp8266com/esp8266/tools/esptool.exe` 
solve the problem. Would it be possible to add this job to the windows build process ?

Thank you very much for your help

Cheers,
Charles

**Comment by igrr** [comment]
Charles,

Please try this patch locally and let me know if it works. I don't have the environment to test.
```diff
diff --git a/build/build.xml b/build/build.xml
index 663bc63..fcbbc1c 100644
--- a/build/build.xml
+++ b/build/build.xml
@@ -987,6 +987,7 @@
     </antcall>
     <move file="${staging_folder}/work/${staging_hardware_folder}/esp8266com/esp8266/tools/esptool-0.4.5-win32/esptool.exe" tofile="${staging_folder}/work/${staging_hardware_folder}/esp8266com/esp8266/tools/esptool.exe" />
     <delete dir="${staging_folder}/work/${staging_hardware_folder}/esp8266com/esp8266/tools/esptool-0.4.5-win32/" />
+    <chmod perm="+x" file="${staging_folder}/work/${staging_hardware_folder}/esp8266com/esp8266/tools/esptool.exe" />
  
   </target>
```

**Comment by hallard** [comment]
Ivan,
did not worked, chmod seems doing nothing in this case !!
But, got the solution, remembering my Windows Server IT Admin years, move keep perms from source so solution is to copy (instead of moving) the file from source, then delete from source
This is done by 

    </antcall>
    <copy file="${staging_folder}/work/${staging_hardware_folder}/esp8266com/esp8266/tools/esptool-0.4.5-win32/esptool.exe" tofile="${staging_folder}/work/${staging_hardware_folder}/esp8266com/esp8266/tools/esptool.exe" />
    <delete file="${staging_folder}/work/${staging_hardware_folder}/esp8266com/esp8266/tools/esptool-0.4.5-win32/esptool.exe" />
    <delete dir="${staging_folder}/work/${staging_hardware_folder}/esp8266com/esp8266/tools/esptool-0.4.5-win32/" />

Then it works ;-)

![image](https://cloud.githubusercontent.com/assets/2471931/8574156/8bdf6a06-2595-11e5-8779-418855b9531c.png)

**Comment by hallard** [comment]
Oh I'm pretty sure the delete line is not needed since the folder is deleted after
