### ISSUE TITLE
How do I use http update timeout?

### ISSUE THREAD

**Issue by ToXIcGaming** [esp8266/Arduino#5184]
Where do I put it and how etc.

[This is what im referencing](https://github.com/esp8266/Arduino/pull/4705/files/20245911a1be7abd8420e3553ce8b105e46ef413)

Sorry for noob question.

**Comment by devyte** [comment]
On construction, shown further down in the same link. Please ask such questions at a community forum, not here, this is an issue tracker.
Closing per issue POLICY doc.
