### ISSUE TITLE
Issue with esp8266 sync failed

### ISSUE THREAD

**Issue by prithiv-prabhu** [esp8266/Arduino#5196]
I got an error while uploading my code from arduino to esp8266, it says:
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed.

I have given all connections correctly.
I have connected TX to RX and RX to TX, and CHPD to 3.3v and GPIO0 to GND.
But still it shows the same.

Can anyone help me out with this??

**Comment by devyte** [comment]
Those errors are documented. In addition, this is an issue tracker, not a support forum. Please seek help at a community forum like esp8266.com or stackoverflow, and also research more.
Off the top of my head, you're not changing into/out of flash mode correctly.
Closing.
