### ISSUE TITLE
connect failes on WM but device is connected

### ISSUE THREAD

**Issue by mstranne** [esp8266/Arduino#5201]
Hey,

When trying to connect to an android hotspot I get the following:
WM: Handle root
WM: WiFi save
WM: Sent wifi save page
WM: Connecting to new AP
WM: Connecting as wifi client...
WM: Connection result:
WM: 4
WM: Failed to connect.

However, my phone shows that the device is connected and when I try again, the WM says it is already connected to the hotspot.

thanks in advance

**Comment by d-a-v** [comment]
cc @tablatronix

**Comment by tablatronix** [comment]
why are there 2 issues, answered the other one

**Comment by tablatronix** [comment]
oh lol, wrong lib , thanks

**Comment by devyte** [comment]
Issue template ignored, no MCVE sketch. Closing due to lack of info.
