### ISSUE TITLE
ESP01s led blinking after connecting deep sleep connections

### ISSUE THREAD

**Issue by kevcavein** [esp8266/Arduino#5202]
Hi all,

I'm having a problem when I use ESP01s.
I need to use the deep sleep mode so I connected reset pin to gpio16. Once I connected, the module built-in led keep on flashing none stop. Once I remove the connection, it works normally.
I read from other post that I need to pull up rst pin to vcc or connect a resistor in between rst and gpio16 but all can't work.
The same sketch I put into esp01, it works well. Only in ESP01s have problem. I tried in 2units of ESP01s.
Does anyone have any solution?

By the way, I read esp01 have v1, v2 and v3. May I know how to differentiate them? 
Thanks

**Comment by devyte** [comment]
This is not a support forum, least of all for hardware issues. It's an issue tracker, meant to track issues in the code hosted in this repo. Please refer to a community forum like esp8266.com or stackoverflow for help.
Closing.
