### ISSUE TITLE
esp8266webserver can not authenticate after password changed

### ISSUE THREAD

**Issue by dEROZA** [esp8266/Arduino#5203]
Trying to change password after when configuration was loaded.. root it's JsonObject!
> ```
> const char  *www_username 	= "admin";
> char	     *www_password 	= "admin";
> const char  *www_realm 		= "Login Required";
> 
> // ... 
> 
> String buf;
> 
> root["auth"]["pass"].printTo(buf);
> buf.replace("\"", "");
> 	
> char str_array[buf.length()+1];
> buf.toCharArray(str_array, buf.length()+1);
> 	
> www_password = str_array; // trying to change the pass
> 	
> Serial.print("\n");
> Serial.println(www_password); //adminsimple, as new password, instead of default admin
> ```
> 
after when password was changed, I can't grad access to the my resource
> 
> ```
> if(!proxy.authenticate(www_username, www_password))
> {
> 	return proxy.requestAuthentication(DIGEST_AUTH, www_realm, authFailResponse);
> }
> ```

> > Request URL: http://192.168.88.244/auth
> > Request Method: GET
> > Status Code: 401 Unauthorized
> > Remote Address: 192.168.88.244:80
> > Referrer Policy: no-referrer-when-downgrade
> 
> > HTTP/1.1 401 Unauthorized
> > Content-Type: text/html
> > WWW-Authenticate: Digest realm="Login Required", qop="auth", nonce="114fde66b12c788fd5d3c89ac4ae0cfc", opaque="966caa9e80a87662a17ff79d311b5675"
> > Content-Length: 21
> > Connection: close
> 
> > GET /auth HTTP/1.1
> > Host: 192.168.88.244
> > Connection: keep-alive
> > Cache-Control: max-age=0
> > Upgrade-Insecure-Requests: 1
> > DNT: 1
> > User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36
> > Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
> > Accept-Encoding: gzip, deflate
> > Accept-Language: en-US,en;q=0.9,ru;q=0.8

P.S. is it possible to change digest www_password on-air?

**Comment by devyte** [comment]
str_array is allocated on the stack, and I somehow doubt you're trying to re-authenticate in the same scope.
This is not a general support forum, this is an issue tracker. Please refer to a community forum for such help.
Closing.
