### ISSUE TITLE
What number is A0 pin

### ISSUE THREAD

**Issue by amirfarazmand** [esp8266/Arduino#5225]
I just bought duinotech wifi mini ESP8266 with wifi. The code in this repository has number for all boards but not A0 which is analogue input.

static const uint8_t D0   = 16;
static const uint8_t D1   = 5;
static const uint8_t D2   = 4;
static const uint8_t D3   = 0;
static const uint8_t D4   = 2;
static const uint8_t D5   = 14;
static const uint8_t D6   = 12;
static const uint8_t D7   = 13;
static const uint8_t D8   = 15;
static const uint8_t RX   = 3;
static const uint8_t TX   = 1;

**Comment by d-a-v** [comment]
[A0](https://github.com/esp8266/Arduino/tree/master/variants/generic/common.h#L53)
