### ISSUE TITLE
Random crash on glue2esp_ifup

### ISSUE THREAD

**Issue by Microsyl** [esp8266/Arduino#5245]
Hi,
   
I have 10 esp8266-1 running the same code and a wemos running another 
code and randomly about each day or two the cpu crash and reboot giving 
this error in the stack dump decoder

I had try at 80Mhz or 160Mhz with the same result.  I also have the lastes core version

:Error:29 -> StoreProhibited: CPU tried to store memory from a region which is protected against writes
   :757 (discriminator 1):::0x402157e8:glue2esp_ifup
   :?:::0x40103d1d:lmacMSDUAged
   :?:::0x4010320d:lmacProcessTXStartData
   0x40215899 netif_sta_status_callback
   0x40218c02 pbuf_copy_partial
   0x40218e04 netif_set_ipaddr
   : ?? ??:0
   0x40218e32 netif_set_netmask
   
   0x4021b05f dhcp_handle_nak
   
   0x4020ce2f loop_task
   :?:::0x4023efc1:get_sar_dout
   0x402190c4 udp_input
   0x4021c594 ip4_input
   0x40215bfd ethernet_input_LWIP2
   0x4010453c esp2glue_ethernet_input
   0x40233172 ethernet_input
   0x40233184 ethernet_input
   :?:::0x4022e06f:ppPeocessRxPktHdr
   :?:::0x402350c7:ets_snprintf
   : ?? ??:0

I can't find the problem I need some help.  I also have more stack dump if you need
Thanks for your time

**Comment by Microsyl** [comment]
Ok,  I had made some modification in my code, I'm in waiting for the next crash or not....
Thanks for your input
Sylvain Bissonnette

**Comment by earlephilhower** [comment]
Closing as no MCVE and it seems to now work for the original user.
