### ISSUE TITLE
Indexing error when using Eclipse Arduino plugin

### ISSUE THREAD

**Issue by miky2k** [esp8266/Arduino#525]
eclipse give this error
../.ino.cpp:7:25: fatal error: ESP8266WiFi.h: No such file or directory

But all header file are not recognized (only Arduino.h).

I'm using eclipse 4.5 under ubuntu , arduino 1.6.4 compile   sketch correctly. 
But not advanced web server.
![notfountesp](https://cloud.githubusercontent.com/assets/6616232/8591637/ed96dace-2629-11e5-89f5-5266724e7336.jpg)
##

**Comment by far5893** [comment]
Create from zero new sketck compile , is existent import sketch from 1.6.4 ide problem

**Comment by Links2004** [comment]
have you load the ESP8266WiFi libary?

![image](https://cloud.githubusercontent.com/assets/974709/8599872/1d1b4efe-2663-11e5-906d-7c83cfd83e37.png)


![image](https://cloud.githubusercontent.com/assets/974709/8599862/0e89d522-2663-11e5-82e6-d012fbfb2c51.png)

**Comment by far5893** [comment]
Ok it works , not so user friendly but wokrs.

Now remain a  :
Function 'snprintf' could not be resolved	WebServices.ino	/WebServices	line 74	

But i can use String object if  i not found what it ask for

**Comment by Links2004** [comment]
you need to include "stdio.h"

**Comment by far5893** [comment]
No , i have stdio.h , and semms only interface trouble i can compile and upload binary.
![eclipse-snprintf](https://cloud.githubusercontent.com/assets/6616232/8692201/3f74407e-2acc-11e5-953d-c9525d9243cf.png)

**Comment by Links2004** [comment]
ok, you need do the include like:
```cpp
extern "C" {
#include <stdio.h>
}
```
the ```snprintf``` is implemented in C not in CPP, you need to tell the compiler this or the function is not found.
https://github.com/esp8266/Arduino/blob/60efe5caed7b8d14636ae5bcc98a1052b55832b1/hardware/esp8266com/esp8266/cores/esp8266/libc_replacements.c#L77

**Comment by igrr** [comment]
I think stdio.h is smart enough to include
#ifdef __cplusplus
extern "C" {
#endif
guards, so that shouldn't be an issue.

Posting the full compiler output would certainly be helpful here.

**Comment by far5893** [comment]
It's not compilation issue , only eclipse interface say that snprintf could not be resolved.

**Comment by Links2004** [comment]
now i get you problem, you mean this:
![image](https://cloud.githubusercontent.com/assets/974709/8696624/31803c94-2aee-11e5-8a21-3160a948df8a.png)
I simply ignore it at the moment, its a problem of the eclipse source indexing.

**Comment by far5893** [comment]
Arduino IDE is a fireworks and eclipse is the zar bomb (nuke bomb) for seriously programming ,
i will investigate about indexing , if you have a hint you are welcome.

**Comment by Links2004** [comment]
I like your compere :+1: 
i think the problem comes from the many ifdef inside the stdio.h,
based on here the indexer is started may some defines are not set
and then the indexing ignore the snprintf be course its "ifdef out".

**Comment by odilonafonso** [comment]
Has this issue been resolved? I'm having the same problem with the eclipse sloeber plugin. 

Compiling a sample from pubsubclient library - mqtt_esp8266.ino:

>     snprintf (msg, 75, "hello world #%ld", value);

is not a sample problem; in the arduino ide this error does not occur.

Modifying to:

>      sprintf (msg, "hello world #% ld", value);


The error no longer occurs.

**Comment by devyte** [comment]
@far5893 @Links2004 this issue is ancient. Is it still valid?

**Comment by devyte** [comment]
Closing due to lack of feedback.
