### ISSUE TITLE
BearSSL_MaxFragmentLength.ino : Unable to connect

### ISSUE THREAD

**Issue by ZinggJM** [esp8266/Arduino#5266]
----------------------------- Delete below -----------------------------
----------------------------- Delete above -----------------------------

### Basic Infos

- [maybe ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ yes] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [no, released version ] I have tested that the issue is present in current master branch (aka latest git).
- [yes ] I have searched the issue tracker for a similar issue.
- [none ] If there is a stack dump, I have decoded it.
- [yes ] I have filled out all fields below.

#### Platform

- Hardware:			ESP8266 Wemos D1 mini pro
- Core Version:			2.4.2
- Development Env:		Arduino IDE
- Operating System:	Windows

### Settings in IDE

- Module:  			Wemos D1 mini r2
- Flash Mode:			[qio|dio|other]
- Flash Size: 		        4MB
- lwip Variant:                  v2 Lower Memory
- Reset Method:		?
- Flash Frequency:	?
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   921600

### Problem Description

Detailed problem description goes here.

BearSSL_MaxFragmentLength.ino

does not work: Unable to connect.

> Connecting to C4A2760E..
WiFi connected
IP address: 
192.168.4.220

> Connecting to https://tls.mbed.org
No MFLN attempted
Unable to connect

> Connecting to https://tls.mbed.org
MFLN supported: yes
Unable to connect

> Default SSL:        48840 bytes used
1024 byte MFLN SSL: 44312 bytes used

This issue is related to issue #4814

**Comment by earlephilhower** [comment]
Rerun at 160MHz.  `Tools->CPU Frequency->160MHz` in the menus.

The mbed.org server times out before we can finish the EC processing on the 8266 when run at 80MHz, so the code and library are running as expected, but ARM is too impatient. :)

**Comment by ZinggJM** [comment]
Thank you for the explanation.
Don't you think the example should be made to work (change site, add fingerprint), marked as nonworking example, or removed?
