### ISSUE TITLE
Flashing with FlashDownloadTool

### ISSUE THREAD

**Issue by mcmega** [esp8266/Arduino#5267]
Hello!
I developed module on ESP8285. I need Flash with FlashDownloadTool.
My config memory 1M + 128K FFS.

Do I need to change something in the file **esp_init_data_default.bin**?
Where can I get a description of the contents of the file?
How to specify the address for the firmwares and correctly programing?
How to write firmware and file system?

**Comment by devyte** [comment]
Wrong place to ask. I suggest seeking help at a community forum.
Closing, see issue POLICY doc and issue template instructions for more details.
