### ISSUE TITLE
OTA - No Network port is shown !

### ISSUE THREAD

**Issue by HamzaHajeir** [esp8266/Arduino#5273]
Hi guys.
I've worked 2 days ago to flash my esp Over The Air.
Uploaded BasicOTA official sketch, All things went fine. Tested file uploading with success.

Today I went to develop the code and merge it in a real project. but after i upload it by serial, Network port won't show anymore (Only Serial) !

So tried back to BasicOTA sketch, with no success.

I've dived into [this topic](https://github.com/esp8266/Arduino/issues/2415) and reached a good point to the final solution.

See @krzychb's [response ](https://github.com/esp8266/Arduino/issues/2415#issuecomment-241339934), I tried a similar command below, See results : 

![image](https://user-images.githubusercontent.com/32960423/47416041-79413300-d77d-11e8-8641-efc2f6f65495.png)

OTA uploading is success! but until now there's no Network port is shown at Arduino IDE.

* I've restarted Arduino IDE many times with no success.

#### Platform
- Hardware:					[ESP8266 NodeMCU 1.0 v3]
- Development Env:		[Arduino IDE 1.8.7]
- Operating System:		[Windows 10 x64]

### Settings in IDE
![image](https://user-images.githubusercontent.com/32960423/47415145-6c234480-d77b-11e8-9894-3ae213138c27.png)

My esp8266's core is updated (2.4.2)

Thanks in advance
Hamza Hajeir

**Comment by devyte** [comment]
After serial upload, did you physically reset the ESP (e.g.: press the reset button)?

**Comment by HamzaHajeir** [comment]
@devyte  Yes i did many times. 

Also tried to re-power it manually by re-plugging its usb cable.

**Comment by devyte** [comment]
Oh, it's windows. Did you disable the firewall, or at least set up a firewall rule? OTA works with the ESP's MDNS responder, which is UDP.

**Comment by devyte** [comment]
Also, closing as this is not an issue with the core.

**Comment by HamzaHajeir** [comment]
Yes I've fully disabled firewall and created rules that works with active firewall.
![image](https://user-images.githubusercontent.com/32960423/47480644-c08cf980-d839-11e8-90e7-5771f7ce4dd0.png)

If i did not, it wouldn't flash OTA manually.

**Comment by peros550** [comment]
> Also, closing as this is not an issue with the core.

I'm having the same issue. Where should we report this issue?

**Comment by devyte** [comment]
It's already fixed post beta1: ArduinoOTA now calls MDNS.update() to maintain it, assuming begin() or begin(true).

**Comment by HamzaHajeir** [comment]
Hi @peros550, I've tried to search for a solution. I've opened a thread at esp8266 forums. 

But i didn't find the solution yet.

Might one approach mentioned there would work well for you.

https://www.esp8266.com/viewtopic.php?f=28&t=18712&p=79014

Please tell me if you get the solution.

**Comment by devyte** [comment]
@HamzaHajeir ArduinoOTA relies on MDNS,  and MDNS was sort of broken before. Try with beta2.
Also, your laptop firewall must allow the traffic, try disabling it for testing.

**Comment by HamzaHajeir** [comment]
> @HamzaHajeir ArduinoOTA relies on MDNS, and MDNS was sort of broken before. Try with beta2.
> Also, your laptop firewall must allow the traffic, try disabling it for testing.

I've reached a point all firewalls are enabled xD 

But for me all firewall settings are ok, Because i can upload binary file OTA but by a command via Command Prompt.
