### ISSUE TITLE
Panic /esp8266/2.4.2/cores/esp8266/core_esp8266_main.cpp:134 loop_task

### ISSUE THREAD

**Issue by fanhuafeng** [esp8266/Arduino#5278]
I debug iotwebconf (https://github.com/prampec/IotWebConf/tree/master/examples/IotWebConf01Minimal) , when i finish config.then console out:

Configuration was updated.
Rebooting after 1 second.

Panic /Users/fhf/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.2/cores/esp8266/core_esp8266_main.cpp:134 loop_task

ctx: sys 
sp: 3fffed40 end: 3fffffb0 offset: 01b0

>>>stack>>>
3fffeef0:  40104d40 01050ce4 3ffee5f8 00000000  
3fffef00:  3ffeee20 3ffee5f8 3fff033c 00000100  
3fffef10:  00000000 0104919a 4021eff7 3ffee5e8  
3fffef20:  3ffedce0 40100ab6 00000001 00000000  
3fffef30:  00000000 40100883 00000000 00000000  
3fffef40:  3fffdcc0 3ffe9c80 00000002 3ffe86e4  
3fffef50:  00000000 3fffdad0 3ffefb2c 4020ec89  
3fffef60:  3ffe9c80 40000f49 3fffdab0 40000f49  
3fffef70:  40000e19 40001878 00000004 00000000  
3fffef80:  3fffff10 aa55aa55 0000001e 40104424  
3fffef90:  4010442a 00000004 00000000 b48a6548  
3fffefa0:  4010000d 577a87b4 3232a1f3 00aa6558  
3fffefb0:  40100774 3fffef4c 40100721 3fffefd8  
3fffefc0:  00000000 4bc6a7f0 0000d593 3ffefb2c  
3fffefd0:  00000000 00000000 3ffe86e4 3ffef798  
3fffefe0:  00000002 3ffefb2c 4020ecb8 3fffefb0  
3fffeff0:  00000000 3fff124c 3ffef770 4020ed72  
3ffff000:  00000002 3ffef798 3ffef770 40208130  
3ffff010:  0000d593 00000001 3ffef850 4020b585  
3ffff020:  0000d593 00000001 40106516 3ffefb2c  
3ffff030:  0000d593 00000001 3ffef470 4020ae65  
3ffff040:  0000d593 00000001 3ffef470 4020aec8  
3ffff050:  0000d593 00000001 3ffef470 4020aed0  
3ffff060:  0000d593 00000001 3ffef470 4020aed0  
3ffff070:  0000d593 00000001 3ffef470 4020aed0  
3ffff080:  0000d593 00000001 3ffef470 4020aed0  
3ffff090:  0000d593 00000001 3ffef470 4020aed0  
3ffff0a0:  0000d593 00000001 3ffef470 4020aed0  
3ffff0b0:  0000d593 00000001 3ffef470 4020aed0  
3ffff0c0:  0000d593 00000001 3ffef470 4020aed0  
3ffff0d0:  0000d593 00000001 3ffef470 4020aed0  
3ffff0e0:  0000d593 00000001 3ffef470 4020aed0  
3ffff0f0:  0000d593 00000001 3ffef470 4020aed0  
3ffff100:  0000d593 00000001 3ffef470 4020aed0  
3ffff110:  0000d593 00000001 3ffef470 4020aed0  
3ffff120:  0000d593 00000001 3ffef470 4020aed0  
3ffff130:  0000d593 00000001 3ffef470 4020aed0  
3ffff140:  0000d593 00000001 3ffef470 4020aed0  
3ffff150:  0000d593 00000001 3ffef470 4020aed0  
3ffff160:  0000d593 00000001 3ffef470 4020aed0  
3ffff170:  0000d593 00000001 3ffef470 4020aed0  
3ffff180:  0000d593 00000001 3ffef470 4020aed0  
3ffff190:  0000d593 00000001 3ffef470 4020aed0  
3ffff1a0:  0000d593 00000001 3ffef470 4020aed0  
3ffff1b0:  0000d593 00000001 3ffef470 4020aed0  
3ffff1c0:  0000d593 00000001 3ffef470 4020aed0  
3ffff1d0:  0000d592 00000001 3ffef470 4020aed0  
3ffff1e0:  0000d592 00000001 3ffef470 4020aed0  
3ffff1f0:  0000d592 00000001 3ffef470 4020aed0  
3ffff200:  0000d592 00000001 3ffef470 4020aed0  
3ffff210:  0000d592 00000001 3ffef470 4020aed0  
3ffff220:  0000d592 00000001 3ffef470 4020aed0  
3ffff230:  0000d592 00000001 3ffef470 4020aed0  
3ffff240:  0000d592 00000001 3ffef470 4020aed0  
3ffff250:  0000d592 00000001 3ffef470 4020aed0  
3ffff260:  0000d592 00000001 3ffef470 4020aed0  
3ffff270:  0000d592 00000001 3ffef470 4020aed0  
3ffff280:  0000d592 00000001 3ffef470 4020aed0  
3ffff290:  0000d592 00000001 3ffef470 4020aed0  
3ffff2a0:  0000d592 00000001 3ffef470 4020aed0  
3ffff2b0:  0000d592 00000001 3ffef470 4020aed0  
3ffff2c0:  0000d592 00000001 3ffef470 4020aed0  
3ffff2d0:  0000d592 00000001 3ffef470 4020aed0  
3ffff2e0:  0000d592 00000001 3ffef470 4020aed0  
3ffff2f0:  0000d592 00000001 3ffef470 4020aed0  
3ffff300:  0000d592 00000001 3ffef470 4020aed0  
3ffff310:  0000d592 00000001 3ffef470 4020aed0  
3ffff320:  0000d592 00000001 3ffef470 4020aed0  
3ffff330:  0000d592 00000001 3ffef470 4020aed0  
3ffff340:  0000d592 00000001 3ffef470 4020aed0  
3ffff350:  0000d592 00000001 3ffef470 4020aed0  
3ffff360:  0000d592 00000001 3ffef470 4020aed0  
3ffff370:  0000d592 00000001 3ffef470 4020aed0  
3ffff380:  0000d592 00000001 3ffef470 4020aed0  
3ffff390:  0000d592 00000001 3ffef470 4020aed0  
3ffff3a0:  0000d591 00000001 3ffef470 4020aed0  
3ffff3b0:  0000d591 00000001 3ffef470 4020aed0  
3ffff3c0:  0000d591 00000001 3ffef470 4020aed0  
3ffff3d0:  0000d591 00000001 3ffef470 4020aed0  
3ffff3e0:  0000d591 00000001 3ffef470 4020aed0  
3ffff3f0:  0000d591 00000001 3ffef470 4020aed0  
3ffff400:  0000d58f 00000001 3ffef470 4020aed0  
3ffff410:  0000d58f 00000001 3ffef470 4020aed0  
3ffff420:  0000d58f 00000001 3ffef470 4020aed0  
3ffff430:  0000d58f 00000001 3ffef470 4020aed0  
3ffff440:  0000d58f 00000001 3ffef470 4020aed0  
3ffff450:  0000d58f 00000001 3ffef470 4020aed0  
3ffff460:  0000d58f 00000001 3ffef470 4020aed0  
3ffff470:  0000d58f 00000001 3ffef470 4020aed0  
3ffff480:  0000d58f 00000001 3ffef470 4020aed0  
3ffff490:  0000d58f 00000001 3ffef470 4020aed0  
3ffff4a0:  0000d58f 00000001 3ffef470 4020aed0  
3ffff4b0:  0000d58f 00000001 3ffef470 4020aed0  
3ffff4c0:  0000d58f 00000001 3ffef470 4020aed0  
3ffff4d0:  0000d58f 00000001 3ffef470 4020aed0  
3ffff4e0:  0000d58f 00000001 3ffef470 4020aed0  
3ffff4f0:  0000d58e 00000001 3ffef470 4020aed0  
3ffff500:  0000d58e 00000001 3ffef470 4020aed0  
3ffff510:  0000d58e 00000001 3ffef470 4020aed0  
3ffff520:  0000d58e 00000001 3ffef470 4020aed0  
3ffff530:  0000d58e 00000001 3ffef470 4020aed0  
3ffff540:  0000d58e 00000001 3ffef470 4020aed0  
3ffff550:  0000d58e 00000001 3ffef470 4020aed0  
3ffff560:  0000d58e 00000001 3ffef470 4020aed0  
3ffff570:  0000d58e 00000001 3ffef470 4020aed0  
3ffff580:  0000d58e 00000001 3ffef470 4020aed0  
3ffff590:  0000d58e 00000001 3ffef470 4020aed0  
3ffff5a0:  0000d58e 00000001 3ffef470 4020aed0  
3ffff5b0:  0000d58e 00000001 3ffef470 4020aed0  
3ffff5c0:  0000d58e 00000001 3ffef470 4020aed0  
3ffff5d0:  0000d58e 00000001 3ffef470 4020aed0  
3ffff5e0:  0000d58e 00000001 3ffef470 4020aed0  
3ffff5f0:  0000d58e 00000001 3ffef470 4020aed0  
3ffff600:  0000d58e 00000001 3ffef470 4020aed0  
3ffff610:  0000d58e 00000001 3ffef470 4020aed0  
3ffff620:  0000d58e 00000001 3ffef470 4020aed0  
3ffff630:  0000d58e 00000001 3ffef470 4020aed0  
3ffff640:  0000d58e 00000001 3ffef470 4020aed0  
3ffff650:  0000d58e 00000001 3ffef470 4020aed0  
3ffff660:  0000d58e 00000001 3ffef470 4020aed0  
3ffff670:  0000d58e 00000001 3ffef470 4020aed0  
3ffff680:  0000d58e 00000001 3ffef470 4020aed0  
3ffff690:  0000d58e 00000001 3ffef470 4020aed0  
3ffff6a0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff6b0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff6c0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff6d0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff6e0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff6f0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff700:  0000d58d 00000001 3ffef470 4020aed0  
3ffff710:  0000d58d 00000001 3ffef470 4020aed0  
3ffff720:  0000d58d 00000001 3ffef470 4020aed0  
3ffff730:  0000d58d 00000001 3ffef470 4020aed0  
3ffff740:  0000d58d 00000001 3ffef470 4020aed0  
3ffff750:  0000d58d 00000001 3ffef470 4020aed0  
3ffff760:  0000d58d 00000001 3ffef470 4020aed0  
3ffff770:  0000d58d 00000001 3ffef470 4020aed0  
3ffff780:  0000d58d 00000001 3ffef470 4020aed0  
3ffff790:  0000d58d 00000001 3ffef470 4020aed0  
3ffff7a0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff7b0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff7c0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff7d0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff7e0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff7f0:  0000d58d 00000001 3ffef470 4020aed0  
3ffff800:  0000d58d 00000001 3ffef470 4020aed0  
3ffff810:  0000d58d 00000001 3ffef470 4020aed0  
3ffff820:  0000d58d 00000001 3ffef470 4020aed0  
3ffff830:  0000d58d 00000001 3ffef470 4020aed0  
3ffff840:  0000d58d 00000001 3ffef470 4020aed0  
3ffff850:  0000d58d 00000001 3ffef470 4020aed0  
3ffff860:  0000d58c 00000001 3ffef470 4020aed0  
3ffff870:  0000d58c 00000001 3ffef470 4020aed0  
3ffff880:  0000d58c 00000001 3ffef470 4020aed0  
3ffff890:  0000d58c 00000001 3ffef470 4020aed0  
3ffff8a0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff8b0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff8c0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff8d0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff8e0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff8f0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff900:  0000d58c 00000001 3ffef470 4020aed0  
3ffff910:  0000d58c 00000001 3ffef470 4020aed0  
3ffff920:  0000d58c 00000001 3ffef470 4020aed0  
3ffff930:  0000d58c 00000001 3ffef470 4020aed0  
3ffff940:  0000d58c 00000001 3ffef470 4020aed0  
3ffff950:  0000d58c 00000001 3ffef470 4020aed0  
3ffff960:  0000d58c 00000001 3ffef470 4020aed0  
3ffff970:  0000d58c 00000001 3ffef470 4020aed0  
3ffff980:  0000d58c 00000001 3ffef470 4020aed0  
3ffff990:  0000d58c 00000001 3ffef470 4020aed0  
3ffff9a0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff9b0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff9c0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff9d0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff9e0:  0000d58c 00000001 3ffef470 4020aed0  
3ffff9f0:  0000d58c 00000001 3ffef470 4020aed0  
3ffffa00:  0000d58c 00000001 3ffef470 4020aed0  
3ffffa10:  0000d58c 00000001 3ffef470 4020aed0  
3ffffa20:  0000d58b 00000001 3ffef470 4020aed0  
3ffffa30:  0000d58b 00000001 3ffef470 4020aed0  
3ffffa40:  0000d58b 00000001 3ffef470 4020aed0  
3ffffa50:  0000d58b 00000001 3ffef470 4020aed0  
3ffffa60:  0000d58b 00000001 3ffef470 4020aed0  
3ffffa70:  0000d58b 00000001 3ffef470 4020aed0  
3ffffa80:  0000d58b 00000001 3ffef470 4020aed0  
3ffffa90:  0000d58b 00000001 3ffef470 4020aed0  
3ffffaa0:  0000d58b 00000001 3ffef470 4020aed0  
3ffffab0:  0000d58b 00000001 3ffef470 4020aed0  
3ffffac0:  0000d58b 00000001 3ffef470 4020aed0  
3ffffad0:  0000d58b 00000001 3ffef470 4020aed0  
3ffffae0:  0000d58b 00000001 3ffef470 4020aed0  
3ffffaf0:  0000d58b 00000001 3ffef470 4020aed0  
3ffffb00:  0000d58b 00000001 3ffef470 4020aed0  
3ffffb10:  0000d58b 00000001 3ffef470 4020aed0  
3ffffb20:  0000d58b 00000001 3ffef470 4020aed0  
3ffffb30:  0000d58b 00000001 3ffef470 4020aed0  
3ffffb40:  0000d58b 00000001 3ffef470 4020aed0  
3ffffb50:  0000d58b 00000001 3ffef470 4020aed0  
3ffffb60:  0000d58b 00000001 3ffef470 4020aed0  
3ffffb70:  0000d58b 00000001 3ffef470 4020aed0  
3ffffb80:  0000d58b 00000001 3ffef470 4020aed0  
3ffffb90:  0000d58b 00000001 3ffef470 4020aed0  
3ffffba0:  0000d58b 00000001 3ffef470 4020aed0  
3ffffbb0:  0000d58b 00000001 3ffef470 4020aed0  
3ffffbc0:  0000d58b 00000001 3ffef470 4020aed0  
3ffffbd0:  0000d58b 00000001 3ffef470 4020aed0  
3ffffbe0:  0000d58a 00000001 3ffef470 4020aed0  
3ffffbf0:  0000d58a 00000001 3ffef470 4020aed0  
3ffffc00:  0000d58a 00000001 3ffef470 4020aed0  
3ffffc10:  0000d58a 00000001 3ffef470 4020aed0  
3ffffc20:  0000d58a 00000001 3ffef470 4020aed0  
3ffffc30:  0000d58a 00000001 3ffef470 4020aed0  
3ffffc40:  0000d58a 00000001 3ffef470 4020aed0  
3ffffc50:  0000d58a 00000001 3ffef470 4020aed0  
3ffffc60:  0000d58a 00000001 3ffef470 4020aed0  
3ffffc70:  0000d58a 00000001 3ffef470 4020aed0  
3ffffc80:  0000d58a 00000001 3ffef470 4020aed0  
3ffffc90:  0000d58a 00000001 3ffef470 4020aed0  
3ffffca0:  0000d58a 00000001 3ffef470 4020aed0  
3ffffcb0:  0000d58a 00000001 3ffef470 4020aed0  
3ffffcc0:  0000d58a 00000001 3ffef470 4020aed0  
3ffffcd0:  0000d58a 00000001 3ffef470 4020aed0  
3ffffce0:  0000d58a 00000001 3ffef470 4020aed0  
3ffffcf0:  0000d58a 00000001 3ffef470 4020aed0  
3ffffd00:  0000d58a 00000001 3ffef470 4020aed0  
3ffffd10:  0000d58a 00000001 3ffef470 4020aed0  
3ffffd20:  0000d58a 00000001 3ffef470 4020aed0  
3ffffd30:  0000d58a 00000001 3ffef470 4020aed0  
3ffffd40:  0000d58a 00000001 3ffef470 4020aed0  
3ffffd50:  0000d58a 00000001 3ffef470 4020aed0  
3ffffd60:  0000d58a 00000001 3ffef470 4020aed0  
3ffffd70:  0000d58a 00000001 3ffef470 4020aed0  
3ffffd80:  0000d58a 00000001 3ffef470 4020aed0  
3ffffd90:  0000d58a 00000001 3ffef470 4020aed0  
3ffffda0:  0000d589 00000001 3ffef470 4020aed0  
3ffffdb0:  0000d589 00000001 3ffef470 4020aed0  
3ffffdc0:  0000d589 00000001 3ffef470 4020aed0  
3ffffdd0:  0000d589 00000001 3ffef470 4020aed0  
3ffffde0:  0000d589 00000001 3ffef470 4020aed0  
3ffffdf0:  0000d589 00000001 3ffef470 4020aed0  
3ffffe00:  0000d589 00000001 3ffef470 4020aed0  
3ffffe10:  0000d589 00000001 3ffef470 4020aed0  
3ffffe20:  0000d589 00000001 3ffef470 4020aed0  
3ffffe30:  0000d589 00000001 3ffef470 4020aed0  
3ffffe40:  0000d589 00000001 3ffef470 4020aed0  
3ffffe50:  0000d589 00000001 3ffef470 4020aed0  
3ffffe60:  0000d589 00000001 3ffef470 4020aed0  
3ffffe70:  0000d589 00000001 3ffef470 4020aed0  
3ffffe80:  0000d589 00000001 3ffef470 4020aed0  
3ffffe90:  0000d589 00000001 3ffef470 4020aed0  
3ffffea0:  0000d589 00000001 3ffef470 4020aed0  
3ffffeb0:  0000d589 00000001 3ffef470 4020aed0  
3ffffec0:  0000d589 00000001 3ffef470 4020aed0  
3ffffed0:  0000d589 00000001 3ffef470 4020aed0  
3ffffee0:  0000d589 00000001 3ffef470 4020aed0  
3ffffef0:  0000d589 00000001 3ffef470 4020aed0  
3fffff00:  0000d589 00000001 3ffef470 4020aed0  
3fffff10:  0000d589 00000001 3ffef470 4020aed0  
3fffff20:  0000d589 00000001 3ffef470 4020aed0  
3fffff30:  0000d588 000003e8 3ffef470 4020aed0  
3fffff40:  3ffef470 3ffef401 3ffef6b0 402042a7  
3fffff50:  3ffe8fee 4021111f 0000000d 4020d47d  
3fffff60:  3ffe8c32 00000000 3ffefa54 4020d630  
3fffff70:  3ffefa54 3ffef6ec 3ffefa54 4020d6a4  
3fffff80:  3fffdad0 3ffef6ec 3ffef6b0 4020410e  
3fffff90:  00000001 feefeffe 40203d18 40203cc8  
3fffffa0:  00000000 00000000 00000001 3ffefb2c  
<<<stack<<<

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
vbb28d4a3
~ld

**Comment by devyte** [comment]
@fanhuafeng that repo is not part of our development, and we don't provide support for 3rd party libs. 
Having said that, I took a quick look, and the messages you provided don't match the example nor the repo code. Additionally, there is at lesat one thing wrong in that repo's code that jumped out at me: the delay method shadows the global delay function.
Finally, your error message says it's a wdt reset. Did you physically reset your ESP after flashing over serial, and before testing?

If you're not the author, I suggest opening an issue in that repo.
If you are the author, then I suggest seeking help from other users at a community forum such as esp8266.com or stackoverflow.
Closing, due to lack of info and 3rd party lib. Please see issue POLICY doc and issue template instructions for further details.
