### ISSUE TITLE
Cannot download esp8288 board package

### ISSUE THREAD

**Issue by rwanauo** [esp8266/Arduino#5282]
http://arduino.esp8266.com/stable/package_esp8266com_index.json

is not accessible.

Tested it from Chrome and got ERR_CONNECTION_REFUSED.
Postman shows "Error: connect ECONNREFUSED 104.131.82.128:80"

I tried from my cell phone, off of my lan, and it is also unable to connect and download that file either.

**Comment by HJMercado** [comment]
Same issue here, cannot access the URL ([http://arduino.esp8266.com/stable/package_esp8266com_index.json]), but I can ping the `arduino.esp8266.com` alias. Tried on different devices with no success.

on Brave: "A connection attempt was refused"

**Comment by rwanauo** [comment]
It looks like someone fixed this. Thanks.
