### ISSUE TITLE
Wire.h is not included in any examples

### ISSUE THREAD

**Issue by mcspr** [esp8266/Arduino#5288]
Related to #5226 and discussion in https://github.com/esp8266/Arduino/commit/cb05b86d49717ce155db618b9cb9e9cc18ced92f#comments

As there are no `.ino` files referencing `Wire.h` compilation tests do not fail:
https://github.com/esp8266/Arduino/blob/d7ca8840070a629d40c6b6d0bacd11d4e652286e/tests/common.sh#L46
https://github.com/esp8266/Arduino/blob/d7ca8840070a629d40c6b6d0bacd11d4e652286e/tests/common.sh#L176
https://github.com/esp8266/Arduino/tree/master/libraries/Wire/examples

In #5287 I referenced twi.h and Wire from avr core. Can those examples be copied here?
https://github.com/arduino/ArduinoCore-avr/tree/master/libraries/Wire/examples

**Comment by devyte** [comment]
> Can those examples be copied here?

Not without testing. In theory, examples that work on avr and other "simple" uCs should work on the ESP. In practice, due tothe wifi radio and tcp/ip stack, they sometimes don't due to timing differences.

Unfortunately, I don't think any of the current developers are involved with i2c at this time, so testing would need to be done by users.

@mcspr care to make a PR yourself with tested examples?

**Comment by mcspr** [comment]
@devyte master<->slave communication seem like a straightforward test target
i.e. from avr repo: master_reader, master_writer, slave_sender, slave_receiver
in similar manner to https://github.com/esp8266/Arduino/tree/master/libraries/SPISlave/examples

two other examples are for devices which i do not have: AD5171 digital potentiometer and SRF10/SRF08 Devantech Ultrasonic Range Finder. But what I do have is DS3231

**Comment by devyte** [comment]
Riight now we don't have any example, so whatever you have. 
Now that slave support is merged, you could also propose an example with one ESP as master and another as slave talking to each other.

**Comment by devyte** [comment]
Note: 4 Wire examples from [avr core repo](https://github.com/arduino/ArduinoCore-avr/tree/master/libraries/Wire/examples), master reader/writer & slave receiver/sender.
Need testing on ESP8266 connected with each other over I2C.

**Comment by devyte** [comment]
@suculent could I ask you to test the referenced standard examples, and add them to your #5360 ? I think your advanced example is better, but these more basic ones are standard for avr, and we should probably include them.
