### ISSUE TITLE
Arduino + ESP8266 RTOS SDK

### ISSUE THREAD

**Issue by inventvictor** [esp8266/Arduino#5294]
Is it possible to use Arduino with the esp8266 RTOS SDK.
I noticed the Arduino port for ESP8266 runs with the Non-OS SDK.

**Comment by devyte** [comment]
Entirely different beast. There is an idf-like sdk, but it has nothing to do with our core.
As a side note, one of the main reasons behind the nonos sdk is to have more available mem. The rtos requires mem for its internals, which leaves less for the user.
Closing.
