### ISSUE TITLE
Node MCU ESP-12E D7 and D8

### ISSUE THREAD

**Issue by vaz83** [esp8266/Arduino#5296]
Hi everyone,
I am using a nodeMCU to control my garage door. I have a reed sensor on the D7 pin and the relay on the D8. Everything is working ok, but when the door is closed, making D7 High, if the nodemcu restarts, it triggers the relay before running any code. Is there a solution for this ?

**Comment by devyte** [comment]
Some pins have activity during boot. That can't be helped, your app must be tolerant to it, or use a different pin.
This is not a general support forum, but an issue tracker for tracking issues in the core.
I suggest asking further at a community forum like esp8266.com or stackoverflow.
Closing.
