### ISSUE TITLE
esp8266 issue- can someone point out error in this code. coz this code does not work for 8 pins for nodemcu.

### ISSUE THREAD

**Issue by gamagelakmana** [esp8266/Arduino#5313]
#include <ESP8266WiFi.h>
#include <DallasTemperature.h>
#include <OneWire.h>

#define ONE_WIRE_BUS1   16          //D0 Temp1
#define ONE_WIRE_BUS2   5           //D1
#define ONE_WIRE_BUS3   4           //D2

#define ONE_WIRE_BUS4   2           //D4
#define ONE_WIRE_BUS5   14          //D5
#define ONE_WIRE_BUS6   12          //D6
#define ONE_WIRE_BUS7   13          //D7
#define ONE_WIRE_BUS8   15          //D8
#define ONE_WIRE_BUS9   3           //D9
#define ONE_WIRE_BUS10  1           //D10
 
OneWire oneWire1(ONE_WIRE_BUS1);
DallasTemperature sensors1(&oneWire1);   // Pass the oneWire reference to Dallas Temperature.

OneWire oneWire2(ONE_WIRE_BUS2);
DallasTemperature sensors2(&oneWire2);   // Pass the oneWire reference to Dallas Temperature.

OneWire oneWire3(ONE_WIRE_BUS3);
DallasTemperature sensors3(&oneWire3);   // Pass the oneWire reference to Dallas Temperature.

OneWire oneWire4(ONE_WIRE_BUS4);
DallasTemperature sensors4(&oneWire4);   // Pass the oneWire reference to Dallas Temperature.

OneWire oneWire5(ONE_WIRE_BUS5);
DallasTemperature sensors5(&oneWire5);   // Pass the oneWire reference to Dallas Temperature.

OneWire oneWire6(ONE_WIRE_BUS6);
DallasTemperature sensors6(&oneWire6);   // Pass the oneWire reference to Dallas Temperature.

OneWire oneWire7(ONE_WIRE_BUS7);
DallasTemperature sensors7(&oneWire7);   // Pass the oneWire reference to Dallas Temperature.

OneWire oneWire8(ONE_WIRE_BUS8);
DallasTemperature sensors8(&oneWire8);   // Pass the oneWire reference to Dallas Temperature.

OneWire oneWire9(ONE_WIRE_BUS9);
DallasTemperature sensors9(&oneWire9);   // Pass the oneWire reference to Dallas Temperature.

OneWire oneWire10(ONE_WIRE_BUS10);
DallasTemperature sensors10(&oneWire10);   // Pass the oneWire reference to Dallas Temperature.

String apiKey = "G6N9A94ILJPFIP1O";     //  Enter your Write API key from ThingSpeak

const char *ssid =  "Deniya";         // replace with your wifi ssid and wpa2 key
const char *pass =  "11111111";
const char* server = "api.thingspeak.com";

WiFiClient client;

//Flow Sensor
const int buttonPin = 0;  //D3
byte sensorInterrupt = 0; //D3 

float calibrationFactor = 4.5;

volatile byte pulseCount = 0;

float flowRate = 0;
unsigned long oldTime = 0; 
void setup() 
{
     sensors1.begin();
     sensors2.begin();
     sensors3.begin();
     sensors4.begin();
     sensors5.begin();
     sensors6.begin();
     sensors7.begin();
     sensors8.begin();
     sensors9.begin();
     sensors10.begin();
     
     Serial.begin(115200);
     delay(10); 
     Serial.println("Connecting to ");
     Serial.println(ssid);

     WiFi.begin(ssid, pass);

     while (WiFi.status() != WL_CONNECTED) 
     {
       delay(500);
       Serial.print(".");
     }
     Serial.println("");
     Serial.println("WiFi connected");
    
     pinMode(buttonPin, INPUT);    
     digitalWrite(buttonPin, HIGH);
     attachInterrupt(digitalPinToInterrupt(buttonPin), pulseCounter, RISING);
}
 
void loop() 
{
    float temp1=0;
    float temp2=0;
    float temp3=0;
    float temp4=0;
    float temp5=0;
    float temp6=0;
    float temp7=0;
    float temp8=0;
    float temp9=0;
    float temp10=0;
    sensors1.requestTemperatures(); // Send the command to get temperatures  
    sensors2.requestTemperatures();
    sensors3.requestTemperatures(); // Send the command to get temperatures  
    sensors4.requestTemperatures();
    sensors5.requestTemperatures(); // Send the command to get temperatures  
    sensors6.requestTemperatures();
    sensors7.requestTemperatures(); // Send the command to get temperatures  
    sensors8.requestTemperatures();
    sensors9.requestTemperatures(); // Send the command to get temperatures  
    sensors10.requestTemperatures();

    temp1 = sensors1.getTempCByIndex(0);    // Why "byIndex"? You can have more than one IC on the same bus. 0 refers to the first IC on the wire
    temp2 = sensors2.getTempCByIndex(0);
    temp3 = sensors3.getTempCByIndex(0);    
    temp4 = sensors4.getTempCByIndex(0);
    temp5 = sensors5.getTempCByIndex(0); 
    temp6 = sensors6.getTempCByIndex(0);
    temp7 = sensors7.getTempCByIndex(0);
    temp8 = sensors8.getTempCByIndex(0);
    temp9 = sensors9.getTempCByIndex(0);
    //temp10 = sensors2.getTempCByIndex(0);          
   
    if (WiFi.status() == WL_CONNECTED && (millis() - oldTime) > 1000) // Only process counters once per second
    {
        detachInterrupt(sensorInterrupt);

        flowRate = ((1000.0 / (millis() - oldTime)) * pulseCount) / calibrationFactor;
        oldTime = millis();

        Serial.println("Flow rate: ");
        Serial.print(flowRate); // Print the integer part of the variable
        Serial.println("L/min");
        Serial.println("Temperature is: ");
        Serial.println(temp1);
        Serial.println(temp2);
        //Serial.println(temp2);
        Serial.println(temp3);
        Serial.println(temp4);
        Serial.println(temp5);
        Serial.println(temp6);
        Serial.println(temp7);
        Serial.println(temp8);
        Serial.println(temp9);
        //Serial.println(temp10);

        if (client.connect(server,80))   //   "184.106.153.149" or api.thingspeak.com
        {  
                  
           String postStr = apiKey;
           postStr +="&field1=";
           postStr += String(temp1);
           postStr +="&field2=";
           postStr += String(temp2);
           postStr +="&field3=";
           postStr += String(temp3);
           postStr +="&field4=";
           postStr += String(temp4);
           postStr +="&field5=";
           postStr += String(temp5);
           postStr +="&field6=";
           postStr += String(temp6);
           postStr +="&field7=";
           postStr += String(temp7);
           postStr +="&field8=";
           postStr += String(temp8);
           postStr +="&field9=";
           postStr += String(temp9);
           postStr +="&field10=";
           postStr += String(temp10);
           postStr +="&field11=";
           postStr += String(flowRate);
           postStr += "\r\n\r\n";

           client.print("POST /update HTTP/1.1\n");
           client.print("Host: api.thingspeak.com\n");
           client.print("Connection: close\n");
           client.print("X-THINGSPEAKAPIKEY: "+apiKey+"\n");
           client.print("Content-Type: application/x-www-form-urlencoded\n");
           client.print("Content-Length: ");
           client.print(postStr.length());
           client.print("\n\n");
           client.print(postStr);
           
           Serial.println("Send to Thingspeak.");
        }
        client.stop();
        Serial.println("Waiting...");
        // Reset the pulse counter so we can start incrementing again
        pulseCount = 0;

        // Enable the interrupt again now that we've finished sending output
        attachInterrupt(sensorInterrupt, pulseCounter, FALLING);
        
    } else if (WiFi.status() != WL_CONNECTED) {
           Serial.println("Connecting to ");
           Serial.println(ssid);
      
           WiFi.begin(ssid, pass);
      
          while (WiFi.status() != WL_CONNECTED) 
          {
             delay(500);
             Serial.print(".");
          }
          Serial.println("");
          Serial.println("WiFi connected");       
    }    
}

void pulseCounter() {
    // Increment the pulse counter
    pulseCount++;
}

**Comment by devyte** [comment]
PulseCounter() is missing the ICACHE_RAM_ATTR decorator for starters.
This is not the right place to ask for help with your code. This is an issue tracker, meant to track issues in the core. Please refer to a community forum for help.
Closing.
