### ISSUE TITLE
Double Slash as a text gives me silly error

### ISSUE THREAD

**Issue by Aggeloz** [esp8266/Arduino#5323]
----------------------------- Delete below -----------------------------

### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-01]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio]
- Flash Size: 		[512K]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description
Hello I've been using the ESP8266 for home automation and i run a website on it to control everything i want. I want to have a button on the website that takes me to the ip of another ESP8266 but i cant because of a bug on the Arduino IDE(Or at least i think it's a bug). It gives me a weird compile error.

```cpp

#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>
#include <ESP8266WebServer.h>
#include <WebSocketsServer.h>

ESP8266WebServer server;
WebSocketsServer webSocket = WebSocketsServer(81);

//char server[]= "www.google.com";
int port = 443;

WiFiClientSecure client;



char* ssid = "AGGELOS SSID";
char* password = "12345678900";
char webpage[] PROGMEM = R"(
<!DOCTYPE html>
  <html>
  <head>
  <title>Contact Info</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name = "viewport" content = "width = device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable=0">
  <style>
  body { background-color: #333333; top: 0; left: 0; margin: 0; font-family: 'Open Sans', sans-serif; }
#Header { padding: 0 30px; margin: 0; font-weight: 300; text-align: center; color: white; }
#Contact { padding: 0 30px; margin: 0; font-weight: 300; text-align: center; color: white; }



  a:link{
    color: white;
    text-decoration: none;
  }
  a:visited{
    color: white;
    text-decoration: none;
  }

  a:hover{
    color: red;
    text-decoration: underline;
  }

  a:active{
    color: grey;
    text-decoration: underline;
  }


  .active{
                  background-color: black;
              }

      ul {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
          background-color: #333;
      }

      li {
          float: left;
      }

      li a {
          display: block;
          color: white;
          padding: 14px 16px;
          text-align: center;
          text-decoration: none;
      }

      li a:hover {
          background-color: #111;
          }


  .grid-container {
      display: grid;
      grid-row-gap: 20px;

      padding: 10px;
    }


  .grid-item{
      text-align: center;
    }
  </style>
  <body>
    <nav>
        <ul>
          <li><a href="http://192.168.1.6/home">Home</a></li>
          <li><a href="#news">News</a></li>
          <li><a href="http:/192.168.1.4/contact">Contact</a></li>
          <li><a href="http:/192.168.1.4/about">About</a></li>
          <li><a class="active" href="home">Second</a></li>
        </ul>
    </nav>
  <div class="grid-container">
<h1 class="grid-item" id="Contact" >Second Esp</h1>

<h3 class="grid-item" id="Contact" >This Is A Test</h3>

<h3 class="grid-item" id="Contact" >This Is A Test</h3>

<h3  id="Contact" >This Is A Test</h3>
</div>
  </body>
  </head>
  </html>

)";


void handleRoot()
{
  server.send_P(200, "text/html", webpage);
}

void handleNotFound()
{
  String message = "File Not Found\n\n";
  message += "URI: ";
  message += server.uri();
  message += "\nMethod: ";
  message += (server.method() == HTTP_GET)?"GET":"POST";
  message += "\nArguments: ";
  message += server.args();
  message += "\n";
  for (uint8_t i=0; i<server.args(); i++){
    message += " " + server.argName(i) + ": " + server.arg(i) + "\n";
  }
  server.send(404, "text/plain", message);
}

void setup()
{
WiFi.begin(ssid,password);
  IPAddress ip(192,168,1,5);   
  IPAddress gateway(192,168,1,254);   
  IPAddress subnet(255,255,255,0);   
  WiFi.config(ip, gateway, subnet);
  Serial.begin(115200);
  while(WiFi.status()!=WL_CONNECTED)
  {
    Serial.print(".");
    delay(500);
  }
  Serial.println("");
  Serial.print("IP Address: ");
  Serial.println(WiFi.localIP());




  server.on("/",[](){
    server.send_P(200, "text/html", webpage);
  });

  
  server.on("/home",[](){
    server.send_P(200, "text/html", webpage);
  });



  
  
  server.begin();
  webSocket.begin();
  //webSocket.onEvent(webSocketEvent);


}

void loop()
{
  webthings();


    }




  

void webthings(){
  webSocket.loop();
  server.handleClient();
  if(Serial.available() > 0){
    char c[] = {(char)Serial.read()};
    webSocket.broadcastTXT(c, sizeof(c));
  }


  }





```

### Debug Messages
Arduino: 1.8.7 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, ck, 26 MHz, 40MHz, QIO, 512K (no SPIFFS), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Build options changed, rebuilding all
C:\Users\Aggelos\Desktop\Web_UI\Web_UI_Second_ESP.ino\Web_UI_Second_ESP.ino.ino: In function 'void loop()':

Web_UI_Second_ESP.ino:182:13: error: 'webthings' was not declared in this scope

   webthings();

             ^

exit status 1
'webthings' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```
Debug messages go here
```

**Comment by Jeroen88** [comment]
If I understand you right, this has nothing to do with the ESP8266, this is just very basic cpp: you should declare a function _before_ it is used. So, either move the void webthings() to just before loop(), or add a line just before loop stating only void webthings(); The latter is called a forward declaration.

**Comment by d-a-v** [comment]
For the record: https://github.com/esp8266/Arduino/issues/4605#issuecomment-378620307
