### ISSUE TITLE
[Feature Request] Update main sketch from a binary that is on SPIFFS

### ISSUE THREAD

**Issue by omersiar** [esp8266/Arduino#5334]
Actually it seems there is no easy way to update the main sketch from a binary file in SPIFFS.

Current Update class depends on writing new sketch's bytes to an empty flash area, which is between currently running sketch and the SPIFFS. If one uses 4m.ld script to build the firmware binary, and resulting firmware is larger than 512kb then the only option is using a different linker script to increase empty space between sketch and SPIFFS.

But this will waste resources, for example one project may require data logging space to be large as much as possible, typical application may have 4mb flash and spare 3mb for SPIFFS, on the other hand if the sketch size is beyond 512mb boundary there is no other option other than to update sketch from UART.

If implemented correctly, user can dump the logged data on SPIFFS (backup) then clear SPIFFS then upload new sketch binary to SPIFFS and after reboot new sketch can be copied from SPIFFS address to replace main sketch.

If this is not somehow limited by proprietary eboot bootloader.

If there is no limit, Updater class can be expanded with update from SPIFFS file.

Let's discuss about it.

**Comment by devyte** [comment]
@omersiar said:
> after reboot new sketch can be copied from SPIFFS address to replace main sketch
Nope. The copying on reboot must rely solely on eboot code, which does flash sector-by-sector copy. The sketch code is not available at that point. That means that eboot has no idea what a SPIFFS is or how to read from a file in it.
Please keep in mind that the update process must survive a power failure at any point.

About the boundaries, I'm not sure about current support above 512KB. I can tell you that I personally have not yet hit that bin size, and my app is huge. Do you have embedded html/css/js/etc?
@d-a-v I think you've delved into the mem layout, do you know what happens in the case with SPIFFS and a bin >512KB and <= 1MB?

**Comment by omersiar** [comment]
Thank you making clear about eboot, i know eboot does not know about spiffs, if only can get address of a file on spiffs, it is doable then.

I believe Fs class does not have getting flash address of a file.

I try to make best looking firmware for esp8266 and i have web files that are minified, gzipped then embedded.

Also logging is important as well

https://github.com/esprfid/esp-rfid

**Comment by earlephilhower** [comment]
SPIFFS does not guarantee any sort of layout in the flash.  Due to fragmentation, other files in the way, or wear leveling, one file could be stored in hundreds of different sections of flash, out of address order, just like on any other filesystem.

**Comment by omersiar** [comment]
Conclusion,

It is not possible due to SPIFFS stores additional meta-data on each page, one simply can not create contiguous file on SPIFFS which is a must for eboot to replace the running sketch.
