### ISSUE TITLE
New serial adapter 'holtek ht42b534' fails to upload 

### ISSUE THREAD

**Issue by anxzhu** [esp8266/Arduino#5336]
### Basic Infos

* [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
* [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
* [x] I have tested that the issue is present in current master branch (aka latest git).
* [x] I have searched the issue tracker for a similar issue.
* [x] If there is a stack dump, I have decoded it.
* [x] I have filled out all fields below.

#### Platform

- Hardware:				[ESP8266 device]
- Core Version:			[latest]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio]
- Flash Size: 		        [1MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

Hi ,i found    /tools/board.txt.py   'description about different Serial Adapter
```cpp           
'Adapters based around the following ICs should work:',
                  '-  FT232RL',
                  '-  CP2102',
                  '-  CH340G',
```
Now, i use a new HT42B534 IC to replace ch340g, it doesn't work well.
The problem is that i have to upload twice before upload success.

First upload setting  
- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio]
- Flash Size: 		        [1MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)
Then upload failed with
Debug Messages
```cpp
esptool v0.4.13 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to dtrset
	setting baudrate from 115200 to 115200
	setting port from COM1 to COM4
	setting address from 0x00000000 to 0x00000000
	espcomm_upload_file
	espcomm_upload_mem
	setting serial port timeouts to 1000 ms
opening bootloader
resetting board
trying to connect
	flush start
	setting serial port timeouts to 1 ms
上传项目出错
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1

trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed""
```

So i try again with different setting
Second upload setting

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio]
- Flash Size: 		        [1MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[dtrset]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

Then upload success with
Debug Messages
```cpp
esptool v0.4.13 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to dtrset
	setting baudrate from 115200 to 115200
	setting port from COM1 to COM4
	setting address from 0x00000000 to 0x00000000
	espcomm_upload_file
	espcomm_upload_mem
	setting serial port timeouts to 1000 ms
opening bootloader
resetting board
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
	espcomm_send_command: receiving 2 bytes of data
Uploading 252080 bytes from C:\Users\anxzh\AppData\Local\Temp\arduino_build_608888/Blink.ino.bin to flash at 0x00000000
	erasing flash
	size: 03d8b0 address: 000000
	first_sector_index: 0
	total_sector_count: 62
	head_sector_count: 16
	adjusted_sector_count: 46
	erase_size: 02e000
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	setting serial port timeouts to 15000 ms
	setting serial port timeouts to 1000 ms
	espcomm_send_command: receiving 2 bytes of data
	writing flash
................................................................................ [ 32% ]
................................................................................ [ 64% ]
................................................................................ [ 97% ]
.......                                                                          [ 100% ]
starting app without reboot
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	espcomm_send_command: receiving 2 bytes of data
closing bootloader
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
```

The only difference between two upload is 'reset method'.
I use 2 transistors  in circuit, each transistor is connected to one pin of the USB serial converter. one for RTS the other for DTR. So I choose' nodemcu' reset method .
The first upload must fail so the second upload could success.I think there must be some thing wrong with 'RESET' , but i  don't know how to solve the problem,

Thanks.

**Comment by 5chufti** [comment]
your "issue" clearly falls under 3) of [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md)
if a circuit you designed does not work as expected, why do you think it is a problem of esp ardiono core?
please close the issue and seek for help in some of the user forums mentioned in linked document

**Comment by devyte** [comment]
Previous comment is correct: this is not the right place to ask.
Closing.
