### ISSUE TITLE
slow flash string print

### ISSUE THREAD

**Issue by devel0** [esp8266/Arduino#5344]
### Platform

- Hardware:				NodeMCU 1.0 (ESP-12E Module)
- Core Version:			2f4380777ef3f1a32a7d539371d910820d0c6f6a
- Development Env:		VSCode + arduino extension
- Operating System:		Ubuntu

### Settings in IDE

- Module:  			[Generic ESP8266 Module|Wemos D1 mini r2|Nodemcu|other]
- Flash Size: 		4MB
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   115200

### Problem Description

using client.print with big flash string ( eg. 2.5k ) have poor performance

<img src="https://user-images.githubusercontent.com/13405008/48620139-49add100-e99f-11e8-8092-d2a431a60f8f.png" width=350/>

### Sketch

just replace [this](https://github.com/devel0/iot-arduino-ioexpander-esp8266-controller-twi/blob/3a0d4776cd5636cc77348d8bbbbdb1448d6961da/esp8266-controller-twi/WiFiUtil.cpp#L145) call with

```cpp
client.println(
#include "index.htm.h"
);
```

### workaround

I wrote a helper to write through a [buffered method](https://github.com/devel0/iot-arduino-ioexpander-esp8266-controller-twi/blob/3a0d4776cd5636cc77348d8bbbbdb1448d6961da/esp8266-controller-twi/WiFiUtil.cpp#L93) that results in faster as shown below

<img src="https://user-images.githubusercontent.com/13405008/48620247-b5903980-e99f-11e8-8e52-5f09ab17324a.png" width=350/>

while [current method](https://github.com/esp8266/Arduino/blob/2f4380777ef3f1a32a7d539371d910820d0c6f6a/cores/esp8266/Print.cpp#L104) write 1 byte at time

**Comment by earlephilhower** [comment]
You are sending out a flash string, but not using the `.write_P` method.  In older releases your code would crash immediately, but with the current SDK Espressif included a special exception handler which catches the machine crash, figures out what you were trying to read, reads it in a safe manner, and restarts your code.

It is now doing that over 2,500 times (probably 3x that) as it reads out your string byte by byte with exceptions on each byte.

Use the `write_P` method which uses flash safe reads and will be significantly faster.
