### ISSUE TITLE
NodeMCU addressing Flash

### ISSUE THREAD

**Issue by pi3dec** [esp8266/Arduino#5345]
Hey Guys,

I am running into issues addressing all 4MB of Flash memory on NodeMCU-12E module.
My memory allocation is 1MB program space + 3MB SPIFFS.

I am doing some sort of CRC check to verify that SPIFFs have change to increase internal write cycle counter. To address from = 1MB <4 MB flash space I assumed that spi_flash_read would work from respective  i=0x100000; i < 0x400000, but apparently it generates fatal error. and only  i=0x100000; i < 0x200000 is addressable.

Is my addressing correct and Flash addresses for 4MB module are indeed form 0 to 0x400000? 
Many thanks.

```
bool checkSpiffsCRC() {

  uint32_t data;
  uint32_t crc = 0;

  for (uint32_t i = 0x100000; i < 0x200000 ; i += 4) {
    if (spi_flash_read(i, &data, 4) == SPI_FLASH_RESULT_OK) {
      crc += data * i;
    }
  }

  if (Settings.spiffsCRC != crc) {
    Settings.flashcount++;
    Settings.spiffsCRC = crc;
    return false;
  } else return true;
}

```

**Comment by devyte** [comment]
There are symbols that specify the spiffs start and end address: _SPIFFS_start and _SPIFFS_end.
Look at file eagle.flash.4m3m.ld.
Also, to read flash, I believe you have to mask interrupts. Look at EspClass for some hints, especially getSketchMD5() (a getSpiffsMD5() method would make a good PR).
Closing in the meantime, given that this is a support question and not an issue.
