### ISSUE TITLE
httpclint.post data in chunks

### ISSUE THREAD

**Issue by prateek027** [esp8266/Arduino#5353]
Hi All,
I am getting data in chunks within 3 second from my device. I need to send that data to my web server. Example:
12 KB... then 1 sec wait.. then 12 KB data.. It's sending 2 separate files in this request, instead of maintaining connection and having 24 KB of file on web server.

I am using httpclient for this and tried passing content-length as well. But doesn't work.

Please guide / help / support.

**Comment by devyte** [comment]
@prateek027 said:
> Please guide / help / support

This is not a support forum, but an issue tracker, meant for tracking issues in the core code hosted in this repo. I suggest seeking help at esp8266.com or stackoverflow.
Closing, see issue POLICY doc and issue template instructions for more details.
