### ISSUE TITLE
spislave onData length increase 

### ISSUE THREAD

**Issue by prateek027** [esp8266/Arduino#5354]
Hi All, 
i need to know about the increase data length in receive or increase the spi frequency. 
in spiSlave.OnData{[Data,len]} in which i can receive only 32 bytes length. 
i just wanted to know that how we can increase this length.

**Comment by devyte** [comment]
Off the top of my head I would use a std::vector to buffer incoming data, then every time the onData cb fires I'd push_back the received data to the vector.
This is not a support forum, but an issue tracker. If you need help, please ask at a community forum like esp8266.com or stackoverflow.
Closing.
