### ISSUE TITLE
"Error Compiling" 

### ISSUE THREAD

**Issue by AllAboutEE** [esp8266/Arduino#54]
I downloaded the windows.zip for release "1.6.1-esp8266-1" 

When I compile a blank sketch:

void setup(){}
void loop(){}

I get "Error Compiling", any ideas what I could be doing wrong?

I'm running Windows 7 64bit.

**Comment by igrr** [comment]
This is an issue with the Windows version of xtensa toolchain. As a workaround, copy libiconv-2.dll from hardware\tools\avr\libexec\gcc\avr\4.8.1 to the root (side by side with arduino.exe).

**Comment by AllAboutEE** [comment]
That worked, thanks!

**Comment by kazma89** [comment]
sorry for ask but, What do you mean with root?

**Comment by ChayD** [comment]
Worked for me too! Thanks!
