### ISSUE TITLE
[SD card] No information available on maximum supported size

### ISSUE THREAD

**Issue by rtek1000** [esp8266/Arduino#5417]
Hi,

Would it be possible to add the information in the SD library presentation (README.adoc), about the maximum size (GB) that the library supports?

Can a larger capacity SD card be used, even though it can only be partially accessed?

I saw a publication from the year 2016 stating that the library only supported 4 GB, even if a larger card was used.

Was there any improvement on this?

**Comment by devyte** [comment]
I believe none of the current developers know details of the current SD implementation. In fact, I understand that the current SD code isn't ours, but an older version of libsdfat.
Therefore, this is unknown, and can't be addressed at this time.
There is an idea to move to a newer SD implementation that I came across, but there is no current plan for it, so if that happens it will be a long while still.
Closing for now.

... unless you would like to take on the investigation and/or migration yourself, in which case I'll reopen!
