### ISSUE TITLE
Add timestamp key to package json files

### ISSUE THREAD

**Issue by probonopd** [esp8266/Arduino#542]
It would be nice if http://arduino.esp8266.com/package_esp8266com_index.json and http://arduino.esp8266.com/staging/package_esp8266com_index.json would mention a timestamp for each entry. This way it would be easier to spot new additions and get a grasp on how recent the entries are.

**Comment by Links2004** [comment]
we now use github release management, so its easy to follow releases.
https://github.com/esp8266/Arduino/releases
