### ISSUE TITLE
error printf for uint64_t,... 

### ISSUE THREAD

**Issue by TienHuyIoT** [esp8266/Arduino#5430]
Sample Code:
uint64_t i = 12345678901234;
Serial.begin(115200);
Serial.printf("\r\nTest: %llu", i);

Get:
"Test: lu"

But, i try test with ESP32. I get "Test: 12345678901234". How to solve for esp8266

**Comment by Jeroen88** [comment]
You could try %lu or even %u?

**Comment by Jeroen88** [comment]
Then I can't help you, sorry!

**Comment by d-a-v** [comment]
%Lu is synonym for %llu and this one neither works (shows 32 bits like %u / %lu).
Is there really a need to show such large numbers ?
