### ISSUE TITLE
Unable to cache built core, please tell esp8266 maintainers to follow http://goo.gl/QdCUjo

### ISSUE THREAD

**Issue by schweini** [esp8266/Arduino#5436]
Hi!

I don't know if this has been reported yet, but when compiling es8266 v2.4.2 with Arduino v1.8.7
Arduino warns:
Unable to cache built core, please tell esp8266 maintainers to follow http://goo.gl/QdCUjo
Which might make compilation quicker.

**Comment by per1234** [comment]
>I don't know if this has been reported yet

You would know if you had done a search. You had a perfect search string that will not give any spurious results.

Duplicate of https://github.com/esp8266/Arduino/issues/5169

**Comment by schweini** [comment]
You are of course right. Mean Maxima culpa, but I was furiously trying to compile some things...
