### ISSUE TITLE
ota and flags to display

### ISSUE THREAD

**Issue by wchpikus** [esp8266/Arduino#5443]
I like to add some extern flags to display status ota (esp web update serwer) and i have with it some problem.
I have status when serwer start and when client connect to server from web and it is displaying.
Could someone tell me, where i can put flags when firmware start upload and where when ok or error and reboot.
I looking in httpupdate.cpp and updateserver.ccp and i can not see (or input there flags) not works.
Regards

**Comment by devyte** [comment]
As stated in the first line of the issue template, this is not the right place to "How do I" type questions. This is an issue tracker, meant to track issues in the core. I suggest seeking help at esp8266.com or stackoverflow.
Closing.
