### ISSUE TITLE
Arduino uno and esp8266

### ISSUE THREAD

**Issue by Samiulpial** [esp8266/Arduino#5447]
I am using this code and getting random value for analog read .I have tested my sensor and its working fine .I have selected NodeMCU board from tool.In client.sendAll(false) ,I have changed it to true or blank but still getting random value .I am using arduino uno.

#include "UbidotsMicroESP8266.h"

#define TOKEN "******" // Put here your Ubidots TOKEN
#define ID_1 "" // Put your variable ID here
//#define ID_2 "Your_variable_ID_here" // Put your variable ID here
#define WIFISSID "" // Put here your Wi-Fi SSID
#define PASSWORD "khaja102" // Put here your Wi-Fi password

Ubidots client(TOKEN);

void setup(){
Serial.begin(115200);
client.wifiConnection(WIFISSID, PASSWORD);
//client.setDebug(true); // Uncomment this line to set DEBUG on
}

void loop(){
float value1 = analogRead(0);
//float value2 = analogRead(2)
client.add(ID_1, value1);
//client.add(ID_2, value2);
client.sendAll(false);
delay(5000);
}

**Comment by devyte** [comment]
This is not a support forum, but an issue tracker meant for tracking issues in the core. I suggest seeking peer help at a community forum like esp8266.com or stackoverflow.
Also, you ignored the ssue template.
Closing.
