### ISSUE TITLE
esp8266Ping can not be Linked.

### ISSUE THREAD

**Issue by marian-craciunescu** [esp8266/Arduino#5448]
- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:					[ESP8266]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE|Platformio|Make|other]
- Operating System:		[Windows|Ubuntu|MacOS]

### Settings in IDE

- Module:  			[NodemcuV2]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB/
- lwip Variant:   [v2]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description
After the latest update in the LWIP I can not use anymore the ESP8266Ping library.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch
Compiling .pioenvs/nodemcuv2/libd48/reef-commons/service/connectivity_service.cpp.o
Linking .pioenvs/nodemcuv2/firmware.elf
.pioenvs/nodemcuv2/libd48/libreef-commons.a(connectivity_service.cpp.o):(.text._ZN9PingClass4pingE9IPAddressh+0x4): undefined reference to `ping_start'
.pioenvs/nodemcuv2/libd48/libreef-commons.a(connectivity_service.cpp.o): In function `PingClass::ping(IPAddress, unsigned char)':
connectivity_service.cpp:(.text._ZN9PingClass4pingE9IPAddressh+0x5e): undefined reference to `ping_start'
collect2: error: ld returned 1 exit status
*** [.pioenvs/nodemcuv2/firmware.elf] Error 1

```cpp
 String url = "8.8.8.8";
 __online = Ping.ping(url.c_str(), 2);

```

### Debug Messages

AFTER MORE DEBUGGING I see that the issue was introduced by @d-a-v  
in commit 
`5c4db3a ("IPv6 on esp8266-nonos-sdk and arduino (#5136)", 2018-11-27)`

https://github.com/esp8266/Arduino/commit/5c4db3acf4353870b6a5663ba06d712d67e6c179

Any suggestion would be highly appreciated.

**Comment by earlephilhower** [comment]
I think this was actually related to #5446 and the replacement of libhal.a with an open source version without the full hidden lwip1.4.0 stack and espconn->tcpconn wrappers.

Can you try pulling the libhal from the latest 2.4.x release and replacing it in tools/sdk/lib/ , just to confirm?

**Comment by earlephilhower** [comment]
Looks to be defined in liblwip_gcc.a
````
~/Arduino/hardware/esp8266com/esp8266/tools/sdk/lib$ nm liblwip_gcc.a  | grep ping_start
00000474 T ping_start
````

**Comment by d-a-v** [comment]
`espconn` had been ported to lwip2, but it was untested (or at least I had no feedback about it and I did not test it myself) and I was thinking nobody was using it.
I indeed disabled it when I did the IPv6 work because it was in my way (untested, maybe unused, no feedback).
I'll try to reenable it before 2.5.0 happens.

If it's only about ping, you can [PingAlive](https://github.com/d-a-v/EspGoodies/blob/master/src/PingAlive.h). Feedback will be apreciated.

**Comment by marian-craciunescu** [comment]
@d-a-v  PingAlive is not what I want.

SHould I make a Pull Request on Builder submodules to re-enable it ?

**Comment by d-a-v** [comment]
> SHould I make a Pull Request on Builder submodules to re-enable it ?

I wish it was that easy. Done in #5444
