### ISSUE TITLE
Fastled freezes I2c connection

### ISSUE THREAD

**Issue by zzxjl1** [esp8266/Arduino#5453]
I‘m currently using esp8266 as a master and arduino nano is a slave, i seems to be fine when i leave it idle, but when there is some light effects going on on my arduino nano the connection freezes and never recover.
NOTE: It won’t have the same issue on my esp8266，is this a performance problem？

This there any ways to recover the connection without doing a force reset?

**Comment by devyte** [comment]
Issue template ignored, no details provided, not even which bus type.
Closing due to lack of info.
I suggest seeking  help at a community forum like esp8266.com or stackoverflow. This is an issue tracker, meant for tracking issues in our core, not for providing general help.
