### ISSUE TITLE
Using getVcc()  =wont compile

### ISSUE THREAD

**Issue by tytower** [esp8266/Arduino#546]
"ESP.getVcc() may be used to measure supply voltage. ESP needs to reconfigure the ADC at startup in order for this feature to be available. Add the following line to the top of your sketch to use getVcc:
ADC_MODE(ADC_VCC);
TOUT pin has to be disconnected in this mode.
Note that by default ADC is configured to read from TOUT pin using analogRead(A0), and ESP.getVCC() is not available."

I tried to use this line "  11  ADC_MODE(ADC_VCC);" but it does not compile
 
"readvdd33.ino:11:9: error: expected constructor, destructor, or type conversion before '(' token
expected constructor, destructor, or type conversion before '(' token"
Do you mean that the trace between TOUT and ADC must be cut in some way or can this be disconnected by setting in a function ?
So can you expand or correct this in the Readme please

**Comment by Duality4Y** [comment]
i assume the 11 part isn't part of the code ?

**Comment by tytower** [comment]
Line number to make it easy to understand by the reader . Didn't work hey?


.................................................................................
On Sun, 12 Jul 2015 15:36:14 -0700
Robert <notifications@github.com> wrote:

> i assume the 11 part isn't part of the code ?
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/esp8266/Arduino/issues/546#issuecomment-120770076


-- 
Yahoo <tytower@yahoo.com>

**Comment by Links2004** [comment]
the macro need to be outside of any function.
```cpp

#include <Arduino.h>

ADC_MODE(ADC_VCC);

void setup(void) {
}

void loop(void) {
}
```

**Comment by tytower** [comment]
You are just guessing now or purposly ignoring it .
#include <Arduino.h>  is standard on all Arduino programs and does not need to be there 

ADC_MODE(ADC_VCC);  Will not compile on the latest Arduino 1.6.5


----------------------------------------------------------------------------On Mon, 13 Jul 2015 01:59:56 -0700
Markus <notifications@github.com> wrote:

> #include <Arduino.h>

-- 
Yahoo <tytower@yahoo.com>

**Comment by igrr** [comment]
I suppose the real reason is that documentation we have here on Github
tracks latest development version, not the one which is delivered via
boards manager package. Some of the changes reflected in Readme are simply
not available in the version you are using, ADC_MODE being one of them.

There is a plan to upload all documentation to a different site, where it
will be kept stable between releases. I started working on this yesterday
in
https://github.com/esp8266/Arduino/commit/32910546e9f4914e1f1b127e402ece3db58751c0,
so documentation update should be complete in a couple of days.

**Comment by tytower** [comment]
Oh OK I see now . So will they come through on the next boards update? or am I better to install it directly from your site?
---------------------------------------------------------------------------On Mon, 13 Jul 2015 02:47:29 -0700
Ivan Grokhotkov <notifications@github.com> wrote:

> I suppose the real reason is that documentation we have here on Github
> tracks latest development version, not the one which is delivered via
> boards manager package. Some of the changes reflected in Readme are simply
> not available in the version you are using, ADC_MODE being one of them.
> 
> There is a plan to upload all documentation to a different site, where it
> will be kept stable between releases. I started working on this yesterday
> in
> https://github.com/esp8266/Arduino/commit/32910546e9f4914e1f1b127e402ece3db58751c0,
> so documentation update should be complete in a couple of days.
> 
> 
> 
> 
> On Mon, Jul 13, 2015 at 12:35 PM, tytower <notifications@github.com> wrote:
> 
> > You are just guessing now or purposly ignoring it .
> > #include <Arduino.h> is standard on all Arduino programs and does not need
> > to be there
> >
> > ADC_MODE(ADC_VCC); Will not compile on the latest Arduino 1.6.5
> >
> >
> > ----------------------------------------------------------------------------On
> > Mon, 13 Jul 2015 01:59:56 -0700
> > Markus <notifications@github.com> wrote:
> >
> > > #include <Arduino.h>
> >
> > --
> > Yahoo <tytower@yahoo.com>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/esp8266/Arduino/issues/546#issuecomment-120871906>.
> >
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/esp8266/Arduino/issues/546#issuecomment-120875194

-- 
Yahoo <tytower@yahoo.com>

**Comment by canadaduane** [comment]
@igrr you are amazing. Keep up the great work.

**Comment by tytower** [comment]
I got down the latest version (staging) yesterday but still the thing will not compile with the same error so I don't seem to understand what you are doing here . The Readme has almost disappeared since last time so where do I find what works and what doesn't now ?

**Comment by tytower** [comment]
Read me is found now at https://github.com/esp8266/Arduino/tree/32910546e9f4914e1f1b127e402ece3db58751c0

ADC_MODE(ADC_VCC);  will still not compile sorry

**Comment by Links2004** [comment]
Stable readme:   http://arduino.esp8266.com/stable/doc/reference.html
Staging readme: http://arduino.esp8266.com/staging/doc/reference.html
(see https://github.com/esp8266/Arduino#available-versions)

**Comment by Links2004** [comment]
please retry in last release, 
If it still a problem feel free to reopen.
