### ISSUE TITLE
Problema con libreria FS.h Error "ets Jan 8 2013,rst cause:2, boot mode:(3,7) ets_main.c"

### ISSUE THREAD

**Issue by gaston206** [esp8266/Arduino#5466]
----------------------------- Delete below -----------------------------

Esimados
Tengo un Nodemcu 1.0 V3 CH340 - al usar el ejemplo del IDE Arduino ESP8266 / ConfigFile del IDE de Arduino cargo el programa con "ESP8266 Scketch Data Upload" (según instrucciones de https://github.com/esp8266/Arduino/blob/master/doc/filesystem.rst) - con el correspondiente archivo "config.json" dentro de la carpeta data. El problema es que el serial monitor me da el siguiente error "ets Jan 8 2013,rst cause:2, boot mode:(3,7) ets_main.c". Para poder leerlo lo tengo que setear en 74880 baudios

Librerias: Estoy usando la ultima versión de la librería ArduinoJson.h (versión 6.6.0 Beta) Probe con varias versiones anteriores y nada versión 5.10  - V 5.5 - etc.

IDE Arduino version 1.8.7

S.O. Windows 10 64 bits

Probe con otras placas de iguales caracteristicas "ESP8266 NodemCu 1.0 V3 CH340"  libres de todo conexionado electonico y me da el mismo problema. 

Archivo Config.json 
{
"serverName": "yourSERVER",
"accessToken": "passWoRd"
}

#### Platform

- Hardware:					[ESP-12|X|X|X|X]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE|x|xr]
- Operating System:		[Windows|x|x]

### Settings in IDE

- Module:  			Nodemcu ESP12 - V3 CH340- 
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB/1MB]
- lwip Variant:  |v2 Lower Memory
- Reset Method:		
- Flash Frequency:	
- CPU Frequency:		[80Mhz|
- Upload Using:		SERIAL]
- Upload Speed:   [115200

### Problem Description

al usar el ejemplo del IDE Arduino ESP8266 / ConfigFile del IDE de Arduino cargo el programa con "ESP8266 Scketch Data Upload" - con el correspondiente archivo "config.json" dentro de la carpeta data. El problema es que el serial monitor me da el siguiente error "ets Jan 8 2013,rst cause:2, boot mode:(3,7) ets_main.c". Para poder leerlo lo tengo que setear en 74880 baudios

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp


#include <ArduinoJson.h>
#include "FS.h"

bool loadConfig() {
  File configFile = SPIFFS.open("/config.json", "r");
  if (!configFile) {
    Serial.println("Failed to open config file");
    return false;
  }

  size_t size = configFile.size();
  if (size > 1024) {
    Serial.println("Config file size is too large");
    return false;
  }

  // Allocate a buffer to store contents of the file.
  std::unique_ptr<char[]> buf(new char[size]);

  // We don't use String here because ArduinoJson library requires the input
  // buffer to be mutable. If you don't use ArduinoJson, you may as well
  // use configFile.readString instead.
  configFile.readBytes(buf.get(), size);

  StaticJsonBuffer<200> jsonBuffer;
  JsonObject& json = jsonBuffer.parseObject(buf.get());

  if (!json.success()) {
    Serial.println("Failed to parse config file");
    return false;
  }

  const char* serverName = json["serverName"];
  const char* accessToken = json["accessToken"];

  // Real world application would store these values in some variables for
  // later use.

  Serial.print("Loaded serverName: ");
  Serial.println(serverName);
  Serial.print("Loaded accessToken: ");
  Serial.println(accessToken);
  return true;
}

bool saveConfig() {
  StaticJsonBuffer<200> jsonBuffer;
  JsonObject& json = jsonBuffer.createObject();
  json["serverName"] = "api.example.com";
  json["accessToken"] = "128du9as8du12eoue8da98h123ueh9h98";

  File configFile = SPIFFS.open("/config.json", "w");
  if (!configFile) {
    Serial.println("Failed to open config file for writing");
    return false;
  }

  json.printTo(configFile);
  return true;
}


void setup() {
Serial.begin(115200);
  Serial.println("");
  delay(1000);
  Serial.println("Mounting FS...");

  if (!SPIFFS.begin()) {
    Serial.println("Failed to mount file system");
    return;
  }


  if (!saveConfig()) {
    Serial.println("Failed to save config");
  } else {
    Serial.println("Config saved");
  }

  if (!loadConfig()) {
    Serial.println("Failed to load config");
  } else {
    Serial.println("Config loaded");
  }
}

}

void loop() {

}

```

### Debug Messages

```
Debug messages go here
```

**Comment by devyte** [comment]
@gaston206 Estimado, este no es el lugar correcto para preguntas tipo "porque no me funciona?". Aqui se hace seguimiento a problemas encontrados en nuestro core, y no se da soporte general. 
Ademas, el lenguaje de este repo es ingles, no español.
A primera vista sugiero usar DynamicJsonBuffer en vez de StaticJsonBuffer. 
I suggest seeking further help at a community forum like esp8266.com or stackoverflow.
Closing.
