### ISSUE TITLE
Stop AP server

### ISSUE THREAD

**Issue by Chagui-** [esp8266/Arduino#549]
There is no function to stop the AP server. I want to change from AP to STA, but it doesn't stop transmiting the AP network.

**Comment by Links2004** [comment]
take a look #539 and #529.

**Comment by Chagui-** [comment]
Allright, so for now i have to call `WiFi.mode(WIFI_STA)` after calling `WiFi.begin()`. That seems to stop transmitting the network.
Thanks.

**Comment by igrr** [comment]
Patch from @Links2004 has been merged, available in staging package.
