### ISSUE TITLE
Firmware size got bigger after recently updates

### ISSUE THREAD

**Issue by mustafayuce33** [esp8266/Arduino#5498]
After updating sdk version to 2.5.0-beta1 then my firmware image's size increased from 400kb to 500kb. This causes update problem because of memory issue? When i install 14 days ago sdk and build firmware then it is about 400kb. So something has been changed recently but i can not find the reason

**Comment by d-a-v** [comment]
If you use git version or wait for 2.5.0-beta2, you can use the menu option "Tool>Exceptions>Disable".
This option has been fixed after release 2.5.0-beta1.

**Comment by devyte** [comment]
Previous comment is correct. Closing as already fixed.
