### ISSUE TITLE
Can't connect to Losant MESSAGE: mqttClient.state -1

### ISSUE THREAD

**Issue by mslawo95** [esp8266/Arduino#5508]
Hi, I made a code to my WEMOS D1 Controller and ths code should be send data (temp, humidity) to Losant,  Connecting to WiFi is ok, but when the Controller connecting to Losant is a message:

WiFi connected
IP address: 
192.168.43.222

Authenticating Device...This device is authorized!

`WiFi connected
IP address: 
192.168.43.222

Authenticating Device...This device is authorized!

Connecting to Losant...-1
.-1
.-1
.-1
.-1
.-1
`

My code: 
https://pastebin.com/XGDwJfHL

In Logs in Losant website I have only message: 

`Device RoomSensor1 authenticated with Losant
Authentication succeeded
ndz 16 gru 2018 21:45:41 GMT+01:00`

so the Controller had a connection/authentication succeeded, but next process is won't be gone.. all the time this message which I paste over.

Please HELP ME!

I made this Tutorial/Course with Losant:

https://www.losant.com/blog/getting-started-with-the-esp8266-and-dht22-sensor

**Comment by devyte** [comment]
At first glance it looks like the -1 is coming from mqttClient. That lib is not hosted in this repo. I suggest seeking help either at their repo, or at a community forum like esp8266.com or  stackoverflow.
Closing due to 3rd party lib.
