### ISSUE TITLE
esp8266HTTPUpdate versioning examples

### ISSUE THREAD

**Issue by pbezant** [esp8266/Arduino#5523]
This may not be allowed here, so please remove if so.

I'm trying to get versioning working with ESP8266HttpUpdate. Currently the device will update no matter what version the file is on the server. Are there any examples of how to do this on nginx either by date modified or version number in .update()?

**Comment by devyte** [comment]
You are correct: this isn't the right place to ask, this is an issue tracker, and I thinknot meant for general support questions. I suggest asking at a community forum like esp8266.com or stackoverflow.
Closing.
