### ISSUE TITLE
Upload problems

### ISSUE THREAD

**Issue by palsbo** [esp8266/Arduino#5540]
Se the following post!

**Comment by palsbo** [comment]
Uploading to ESP8266 is somtimes a nightmare. Only after several retries upload starts, and somtimes only at a very low speed.

When viewing output from the upload I can find the compiled .bin file, and I tried to upload this using the expressif tool flash_download_tools_v3.6.5.exe.  (Arduino IDE uses ESPTOOL.EXE)

It not only uploads the first time I try, but I can also set upload speed to 1,500,000 bps - and still uploading first time.

Is it possible to change the Arduino IDE installation (ESP8266 device) to use the expressif tool?

This is output from ESPTOOL.exe (sucsessfull after several retries);

`C:\Users\erik\Desktop\flash_download_tools_v3.6.5\flash_download_tools_v3.6.5>C:\Users\erik\AppData\Local\Arduino15\packages\esp8266\tools\esptool\0.4.13/esptool.exe -vv -cd ck -cb 921600 -cp COM22 -ca 0x00000 -cf C:\Users\erik\AppData\Local\Temp\arduino_build_687075/Blink.ino.bin
esptool v0.4.13 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
        setting board to ck
        setting baudrate from 115200 to 921600
        setting port from COM1 to COM22
        setting address from 0x00000000 to 0x00000000
        espcomm_upload_file
        espcomm_upload_mem
        setting serial port timeouts to 1000 ms
opening bootloader
resetting board
trying to connect
        flush start
        setting serial port timeouts to 1 ms
        setting serial port timeouts to 1000 ms
        flush complete
        espcomm_send_command: sending command header
        espcomm_send_command: sending command payload
        read 0, requested 1
trying to connect
        flush start
        setting serial port timeouts to 1 ms
        setting serial port timeouts to 1000 ms
        flush complete
        espcomm_send_command: sending command header
        espcomm_send_command: sending command payload
        read 0, requested 1
trying to connect
        flush start
        setting serial port timeouts to 1 ms
        setting serial port timeouts to 1000 ms
        flush complete
        espcomm_send_command: sending command header
        espcomm_send_command: sending command payload
        read 0, requested 1
resetting board
trying to connect
        flush start
        setting serial port timeouts to 1 ms
        setting serial port timeouts to 1000 ms
        flush complete
        espcomm_send_command: sending command header
        espcomm_send_command: sending command payload
        read 0, requested 1
trying to connect
        flush start
        setting serial port timeouts to 1 ms
        setting serial port timeouts to 1000 ms
        flush complete
        espcomm_send_command: sending command header
        espcomm_send_command: sending command payload
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
        espcomm_send_command: receiving 2 bytes of data
Uploading 255328 bytes from C:\Users\erik\AppData\Local\Temp\arduino_build_687075/Blink.ino.bin to flash at 0x00000000
        erasing flash
        size: 03e560 address: 000000
        first_sector_index: 0
        total_sector_count: 63
        head_sector_count: 16
        adjusted_sector_count: 47
        erase_size: 02f000
        espcomm_send_command: sending command header
        espcomm_send_command: sending command payload
        setting serial port timeouts to 15000 ms
        setting serial port timeouts to 1000 ms
        espcomm_send_command: receiving 2 bytes of data
        writing flash
................................................................................ [ 32% ]
................................................................................ [ 64% ]
................................................................................ [ 96% ]
..........                                                                       [ 100% ]
starting app without reboot
        espcomm_send_command: sending command header
        espcomm_send_command: sending command payload
        espcomm_send_command: receiving 2 bytes of data
closing bootloader
        flush start
        setting serial port timeouts to 1 ms
        setting serial port timeouts to 1000 ms
        flush complete
`


This is output from esp8266_download_tool_v3.6.5:

`test offset :  0 0x0
case ok
======
CONNECT BAUD: 115200
============
.Uploading stub...
Running stub...
Stub running...
Changing baud rate to 1500000
Changed.
24bit mac
('chip_flg', 5L)
`

**Comment by earlephilhower** [comment]
You are not using the Arduino shipped esptool.exe, and upload errors are not related to the core.  Closing.

**Comment by earlephilhower** [comment]
Reopening as I didn't catch that there were two outputs.  I don't think others are seeing your issue, though, so you may want to make sure you're running the latest 2.5.0-dev2.

**Comment by earlephilhower** [comment]
#5635 replaces esptool-ck.exe w/esptool.py, the one that Espressif maintains, so that PR would close this.

**Comment by earlephilhower** [comment]
Closing as #5635 merged.  esptool.py seems much more resilient for uploading on my own HW.
