### ISSUE TITLE
ArduinoOTA.handle not running in setup{}, frequency of ArduinoOTA.handle(); calls?

### ISSUE THREAD

**Issue by jbrepogmailcom** [esp8266/Arduino#5541]
Hello.

I see that ArduinoOTA.handle(); is called in the loop{}, it does not work if included in setup{}. Does it run repeatedly or does it wait for OTA - meaning that following code is not executed until OTA is completed?

If it runs repeatedly, how often does it needs to be called, what is the timeout?

Thanks, Jan

**Comment by devyte** [comment]
It must be called in the loop for its internal upkeep. One example of its upkeep is the update() internal call for the MDNS responder, where internal polled timers trigger real work every so often. 
The calling frequency doesn't impact much. You don't need to worry about the details, just know that it's correct to call the method every pass through loop.
If you really want to know details, I suggest investigating the source code to understand the reasons.
This is not the right place to ask info questions, this is an issue tracker, meant for tracking issues in the core. I suggest seeking further support at a community forum like esp8266.com or stackoverflow.
Closing.
