### ISSUE TITLE
Exception (9) when connecting to router while in AP

### ISSUE THREAD

**Issue by llucixxeu** [esp8266/Arduino#5571]
Hello everyone, I believe that this problem may be already discussed in another topics, but, I still can't manage to make it work, so I would really appreciate some help here please.
In my sketch I start by creating a webserver over port 80, which is exposed on a local AP. On roothandle ESP scan all networks in the area and display them in a dropdown list from which you can choose and fill in the password. On formular submission, the ESP then takes SID and Password and connects to that router. 
When the connection is done, it suddenly throw Exception and wdt_reset. I've tried many things but nothing seems to work:

#include <ESP8266WiFi.h>
#include <ESP8266WebServer.h>

char ssid[] = "";
char pass[] = "";

IPAddress timeServerIP(192, 168, 100, 99);
IPAddress gateway(192, 168, 100, 1);
IPAddress subnet(255, 255, 255, 0);
IPAddress webServerIp(192, 168, 100, 1);

ESP8266WebServer server(webServerIp, 80);

char wlanList[100][100];

void setup() {
  Serial.begin(115200);
  WiFi.mode(WIFI_AP_STA);
  WiFi.softAP("ESP_CLOCK", "", 1);
  WiFi.softAPConfig(webServerIp, gateway, subnet);

  server.on("/", handleRoot);
  server.on("/change-wlan", changeWlan);
  server.begin();
}

void scanWLAN() {
  int n = WiFi.scanNetworks();
  for (int i = 0; i < n; ++i) {
    Serial.print(WiFi.SSID(i));
    Serial.print(" - channel: ");
    Serial.print(WiFi.channel(i));
    Serial.println();
    WiFi.SSID(i).toCharArray(wlanList[i], WiFi.SSID(i).length() + 1);
  }
}

void changeWlan() {
  Serial.println("- change WLAN: ");
  Serial.print(server.arg("sid"));
  if (server.arg("sid") && server.arg("pass")) {
    server.arg("sid").toCharArray(ssid, server.arg("sid").length() + 1);
    server.arg("pass").toCharArray(ssid, server.arg("pass").length() + 1);
  }
  server.send(200, "text/plain", "connected");
  delay(1000);
  // CONECTION TO ROUTER IS CALLED
  connectToLan();
}

void connectToLan() {
  Serial.println("- connecting to WLAN: ");

  WiFi.begin(ssid, pass);

  while (WiFi.status() != WL_CONNECTED) {
    delay(1000);
    Serial.print(".");
  }
}

void handleRoot() {
  Serial.println("- handel root request");
  // SCAN ALL NETWORKS AND LIST ON WEBPAGE
  scanWLAN();
  String options = "";
  String response = "";
  for (int i = 0; i < 30; ++i) {
    options += "<option value='" + String(wlanList[i]) + "'>" + String(wlanList[i]) + "</option>";
  }
  response += String("<hmtl><form action='/change-wlan'>") + "<select name='sid'>" + String(options) + "</select>" +
              "<input type='password' name='pass'>" +
              "<input type='submit' value='Connect'>" +
              "</form></html>";
  server.send(200, "text/html", response);
}

void loop() {
  server.handleClient();
}

#######################################################################
Exception (9):
epc1=0x40202938 epc2=0x00000000 epc3=0x00000000 excvaddr=0x38393169 depc=0x00000000

ctx: sys 
sp: 3ffffdd0 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffff70:  4021cb48 3ffe9054 3fff46ec 40202930  
3fffff80:  4021cb6e 3fffdab0 00000000 3ffee5a8  
3fffff90:  3fffdc10 00000000 3fff46ec 4021fea0  
3fffffa0:  40000f49 3fffdab0 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)

 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

So, everything works well, until method connectToLan() is called, more precisely, after WiFi.status() == WL_CONNECTED, because I manage to see those dots printed in Serial monitor while making the connection.

**Comment by devyte** [comment]
```
char ssid[] = "";
char pass[] = "";
...
server.arg("sid").toCharArray(ssid, server.arg("sid").length() + 1);
server.arg("pass").toCharArray(ssid, server.arg("pass").length() + 1);
...
```

ssid and pass have size 1 (the hidden null term in ""). You then proceed to copy strings into them, which corrupts mem.

Please request such help at a community forum. This is an issue tracker and not meant for general support.

Closing due to user error.
