### ISSUE TITLE
STA Connect callback

### ISSUE THREAD

**Issue by Menion2k** [esp8266/Arduino#5579]
Hello
Is there any way to use the ESP8266 wifi library in order to call a callback upon STA connect (and maybe disconnec) events (like the LUA library)?

**Comment by devyte** [comment]
https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/generic-class.html#generic-class

https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/WiFiEvents/WiFiEvents.ino

Please [readthedocs ](https://arduino-esp8266.readthedocs.io/en/latest/) before asking such questions. In addition, this isn't the right place to ask for help, this is an issue tracker, meant for tracking issues in the core, and not for general support. 

Closing.
