### ISSUE TITLE
[Question] openDir and Dir object

### ISSUE THREAD

**Issue by GMagician** [esp8266/Arduino#5584]
I'm newbie so sorry if this is not correct place to ask

I downloaded library using:
http://arduino.esp8266.com/stable/package_esp8266com_index.json

I have a sketch where I can write files using spiffs but when I try to use openDir I get an error about Dir was not declared in this scope. is there a reason?

I wrote: `Dir dir = SPIFFS.openDir("/");`
writting: `SPIFFS.openDir("/");` compiles correctly

**Comment by GMagician** [comment]
ok found when FS_NO_GLOBALS is defined I have to use fs::Dir

**Comment by rabinniroula** [comment]
@GMagician , can you elaborate? I have the same problem.
