### ISSUE TITLE
Adding the custom libraries

### ISSUE THREAD

**Issue by robertgregor** [esp8266/Arduino#56]
Hello, would it be possible to add a SimpleTimer? I am not sure, how it should work, but to be able to find e.g. SimpleTimer, I have to copy the .h and .cpp file to the arduino-1.6.1\hardware\esp8266com\esp8266\cores\esp8266. I have tried to copy is to the C:\RH\arduino-1.6.1\libraries\ but it didn't worked. BTW this library works well and could be used without any change.
##

**Comment by igrr** [comment]
Which one is the right SimpleTimer, https://github.com/infomaniac50/SimpleTimer or https://github.com/jfturcot/SimpleTimer?

**Comment by robertgregor** [comment]
Hello, I used https://github.com/infomaniac50/SimpleTimer written by mromani@ottotecnica.com
. Working great.

**Comment by devyte** [comment]
I think the Ticker lib addresses this. Also, the previous comment says the 3rd party lib works.
Closing.
