### ISSUE TITLE
ILI9341 white screen

### ISSUE THREAD

**Issue by ManiackCZ** [esp8266/Arduino#562]
Hello,
i have ESP07 module (later version /w ADC pin) on my own breakout board hooked to 2,2" TFT with ILI9341 driver. I have it wired according to pin map on readme page but all I get is white screen. For CS and DC pins I tried to use multiple combinations of pins (15,16,2...). I used latest Arduino + board manager and also tried version i built from souce. None of it worked, all i got was white screen.

**Comment by tontito** [comment]
add pinMode(2, OUTPUT); in setup() . Work tft

**Comment by Links2004** [comment]
the Reset pin of the display need an pullup if you not connect it.

**Comment by ManiackCZ** [comment]
I found the trick with pinMode(2, OUTPUT); in other thread and already tried it. Doesnt work for me. I will try to add pullup on reset pin and see if it helps.

**Comment by ManiackCZ** [comment]
I added pullup on RST and added pinMode(2,OUTPUT); into my code. Neither of it helps. Just white screen again.

**Comment by Links2004** [comment]
i have here running 2 screens connected like this:
i connect the screen like this:

 TFT       |      ESP 
----------- | ----------------
MISO     |  12
SCK       | 14
MOSI     | 13
DC         |  4
RESET  |  5 or 3V3 (pullup)
CS         |  15

with reset:
```cpp
#define TFT_DC 5
#define TFT_CS 15
#define TFT_RESET 4

Adafruit_ILI9341 tft = Adafruit_ILI9341(TFT_CS, TFT_DC, TFT_RESET);
```

no reset:
```cpp
#define TFT_DC 5
#define TFT_CS 15

Adafruit_ILI9341 tft = Adafruit_ILI9341(TFT_CS, TFT_DC);
```

if you power the TFT with 3V3 volt you need to solder the pad on the Back of the screen (near the LDO).
hope this helps.

**Comment by ManiackCZ** [comment]
Oh, I forgo that the board has its own LDO and I was powering it from 3v3. Thanks man, that fixed my problem :)

**Comment by pfabri** [comment]
@Links2004  Holly Cow! Thanks so much!
