### ISSUE TITLE
esp8266 problems with download json file (180kB) and its parser

### ISSUE THREAD

**Issue by robcim** [esp8266/Arduino#5623]
Hi all,
I must download a json file (180kB) from a server and I must do its parser. I use an esp8266 with Arduino IDE using the HTTPClient.h library and its examples.
The instructions used are http.GET() and http.GetString(). The GET give me a result ok (=200) but the getString return a empty string. Why? Because the file it's big? There are a solutions?
Can you help me please?
Thank you.

**Comment by earlephilhower** [comment]
This is not the forum for coding questions.  Please use something like www.esp8266.com for this.  You obviously can't read 180KB of JSON into a 40KB processor before parsing, so you will need to parse things on the fly byte-by-byte.
