### ISSUE TITLE
Why is default softap ip 192.168.244.1 ?

### ISSUE THREAD

**Issue by tablatronix** [esp8266/Arduino#5627]
It seems a bunch of people seem to think this is the default ip for softap mode, when it is not.

192.168.4.1 is the default, but it does look like this IS the default ip by lib when ip config fails.

Any ideas why, and why not use the same ip as SDK

https://github.com/esp8266/Arduino/blob/dd6333ee8b26dd9cc82dea252ba150e85c0ebb11/libraries/ESP8266WiFi/src/ESP8266WiFiAP.cpp#L173

**Comment by devyte** [comment]
No idea. The referenced code was introduced by @Links2004 and dates back to Jan 2016.

If we change it, it would have to be in 3.0.0.

**Comment by tablatronix** [comment]
I need to PR this..
