### ISSUE TITLE
e_servoIndex 0 when using Servo library with HTTP server

### ISSUE THREAD

**Issue by giannoug** [esp8266/Arduino#566]
Using the latest "staging" version and the Servo library directly downloaded from git, I'm getting the following error during boot and right after flashing. The ESP hangs and reboots itself indefinitely.

     ets Jan  8 2013,rst cause:4, boot mode:(3,7)

    wdt reset
    load 0x4010f000, len 1464, room 16 
    tail 8
    chksum 0x7a
    csum 0x7a
    e_servoIndex 0

I have pushed some code to reproduce the problem: https://github.com/giannoug/turtle-feeder

**Comment by giannoug** [comment]
In the example provided, I've moved `feeder.attach(2);` after `server.begin();` and the issue magically disappeared. I still get `_servoIndex 0` in the Serial console, but at least the ESP doesn't hang and reboot repeatedly.

**Comment by Makuna** [comment]
I can't reproduce your problem.  I have tried it with the order of the two statements as it is listed in the file and swapped them without having a problem.  

What device do you have?  How have you connected it?

Please do the following to capture more information:
1) after ```Serial.begin(115200);``` add ```Serial.setDebugOutput(true);``` The exception should now contain more information.
2) objdump of the elf file and look up the address of the error to find the code causing the problem
```
xtensa-lx106-elf-objdump -S your_elf_file.elf > dum.dobj
```

**Comment by Makuna** [comment]
@giannoug do you still reproduce this problem?

**Comment by giannoug** [comment]
@Makuna I haven't forgot about this issue, I do have another one too. Give me a couple of days and I'll report back

**Comment by Links2004** [comment]
please retry in last release, 
If it still a problem feel free to reopen.
