### ISSUE TITLE
Board manager error downloading issue

### ISSUE THREAD

**Issue by bandaru5** [esp8266/Arduino#5700]
can you help me with the following error. I'm using Arduino IDE 1.8.8 and using Olimexino 32U4 board.
I'm getting the following error 
   Error downloading https://raw.githubusercontent.com/OLIMEX/Arduino_configurations/master/AVR/package_olimex _avr_index.json

I tried opening the page with the link but it says 404 : not found.

please help me, I'm stuck here.
![capture](https://user-images.githubusercontent.com/46452635/52077039-4da9c200-2590-11e9-8863-dabd965e0030.PNG)

**Comment by earlephilhower** [comment]
This is not the OLIMEX repo nor the AVR arduino (as shown in your URL), so please direct your question there.  Closing.

**Comment by bandaru5** [comment]
I don't understand the error. where should I direct this. can you help me with this.
