### ISSUE TITLE
Issue with updateSketch function

### ISSUE THREAD

**Issue by ItayRosen** [esp8266/Arduino#5714]
Hi,

I'm trying to use the ESP.updateSketch function with no luck.

I'm using the following sketch (only updating the WiFi credentials and MQTT server credentials): **https://github.com/Imroy/pubsubclient/blob/master/examples/ESP8266-OTA/ESP8266-OTA.ino**.

I uploaded the sketch's compiled bin file to my server and sent it to the ESP8266 over MQTT. It arrives at its full (I compared the file size with what ESP8266 receives).

I'm using NodeMCU v0.9.

What I'm getting in the Serial Monitor is this:
```
Receiving OTA of 276432 bytes...
sleep disable
state: 5 -> 0 (0)
rm 0
del if0
bcn 0
del if1
usl
?3⸮⸮1⸮D⸮
```

**Comment by earlephilhower** [comment]
This looks like it's related to a 3rd party library, and the issue template was ignored.  Please consider opening up an issue on the 3rd party library or using the https://www.esp8266.com forum for support.
