### ISSUE TITLE
[API Request] new progress API for ESPhttpUpdate download + upload ?

### ISSUE THREAD

**Issue by IMAN4K** [esp8266/Arduino#5715]
Would it be possible to have two new APIs for `ESPhttpUpdate` class to notify user code for download + upload progress?
Like this:
```cpp
using prog_cb_t = std::function<void(size_t total, size_t got /* or written */)>();

ESP8266HTTPUpdate::onDownloadProgress(prog_cb_t);
ESP8266HTTPUpdate::onUploadProgress(prog_cb_t)
```

**Comment by bendtherules** [comment]
Doc link: https://github.com/esp8266/Arduino/issues/4010#issuecomment-590050032
