### ISSUE TITLE
EEPROM write/put not checking every single byte

### ISSUE THREAD

**Issue by mamama1** [esp8266/Arduino#5767]
Hi

it seems to me, that EEPROM.commit(), write and put don't check every single byte if it has changed (using the _dirty flag) but as soon as one byte gets changed, the whole area will be rewritten to flash.

Is this intended or was it some getting-things-done-whoopsie?

eg. I change just one byte but I have reserved 4k of EEPROM, all 4k will be erased and rewritten, if I understand the code correctly.

Thanks

**Comment by penfold42** [comment]
This is intended behaviour.
It’s an emulation layer on top of a SPI flash sector and SPI flash sectors must be erased before writing.

**Comment by mamama1** [comment]
> It’s an emulation layer on top of a SPI flash sector and SPI flash sectors must be erased before writing.

I know that, but how big is one sector? 4k?

**Comment by devyte** [comment]
Correct. Closing as intended behavior.
