### ISSUE TITLE
Bigger EEPROM than 512 ?

### ISSUE THREAD

**Issue by robertgregor** [esp8266/Arduino#577]
Hello I want to have bigger eeprom i.e. 1024. Is it enough just to initialize it like EEPROM.begin(1024); or should I do something more?

Robert

**Comment by Gianbacchio** [comment]
Hello Robert,
yes, correct, you can write in that way.
Have in mind that the limit is 4k.
Giancarlo

**Comment by asetyde** [comment]
Giancarlo , ciao .

Could I expand 4k of virtual Eproom  or not ?

**Comment by far5893** [comment]
Developers says that they will re-implement SPIFFS soon , i hope this would be very very soon.

**Comment by asetyde** [comment]
You can use progmem to supply lack of virtual eeprom at moment. But I hope too. Many thanks
