### ISSUE TITLE
Help: HTTP POST method for csv file upload to remote server from sd card

### ISSUE THREAD

**Issue by bidyutper** [esp8266/Arduino#5803]
Hi,
Below is my POSTMAN code generated with "TEST.CSV" file.

Can anyone guide me to form the HTTP POST method for the same

`POST /web.tnd/csv_upload/csv.php HTTP/1.1
Host: 89.50.221.95:80
Accept: application/json
Cache-Control: no-cache

Postman-Token: 3aaa21fc-d84f-484b-6788-de7dc5311e0d

Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file_name"; filename="TEST.CSV"
Content-Type: application/vnd.ms-excel
------WebKitFormBoundary7MA4YWxkTrZu0gW--`

**Comment by devyte** [comment]
This is not the right place to ask for general support. This is an issue tracker, meant to track issues in the core. I suggest seeking such help from peers at esp8266.com or stackoverflow.
Closing per issue POLICY doc and ISSUE_TEMPLATE doc instructions.
