### ISSUE TITLE
esp32 hard reset require after powering up

### ISSUE THREAD

**Issue by cyberrocker** [esp8266/Arduino#5808]
Hello,
I am a first time poster, so i am not sure if this is the correct forum for this issue. Please advise me if it should be somewhere else.

I have an ESP32 with wifi code, but after powering up the board to run the code, I need to hit the reset button to actually start running from the start. The board will be in a box which will make it impossible for users to reset.

Can some one help with this issue?

Many thanks

**Comment by oddstr13** [comment]
This repository is for ESP8266 specifically, and not ESP32.
I am not sure of which repository is the correct one, but it could quite possibly be https://github.com/espressif/arduino-esp32 .
