### ISSUE TITLE
New SDK Patch Memory optimization save 8kb ram

### ISSUE THREAD

**Issue by tontito** [esp8266/Arduino#581]
http://bbs.espressif.com/viewtopic.php?f=5&t=743 very stable and very good patch save 8 kb.

i have testing 4 days no problem.

@Links2004 you love innovation, too :)

**Comment by far5893** [comment]
8k of ram is gold for our projects, i use old stable  WEBserver library (that use a lot of String copy) and to serve a 1500 byte page  heap reach 1500-800bytes!!!

**Comment by tontito** [comment]
http://bbs.espressif.com/download/file.php?id=594 download file and replace 
Arduino/hardware/esp8266com/esp8266/tools/sdk/lib/ 

libnet80211.a
libpp.a
libsmartconfig.a
libssl.a

save kb ram my project freeheap 27 kb to 33 kb

**Comment by Links2004** [comment]
yes it is waiting for merge #539

**Comment by igrr** [comment]
Merged, available in stable build.
