### ISSUE TITLE
Python3 does not respond with ArduinoUNO

### ISSUE THREAD

**Issue by simeon9446** [esp8266/Arduino#5837]
Hello.

I have a simple circuit on a breadboard with single LED and a resistor. 
Codes on Arduino IDE works just fine (I've tried to play around with integrated Arduino IDE example - Blink.ino). 

I cannot get a response from ArduinoUNO when using Python3.
I run the python3 code (find it below) but my ArduinoUNO keeps looping previous ArduinoIDE code.

Here is my Python Code:
```
#This should keep LED OFF and if ser.write is changed from 0 to 1 - LED should get ON
import serial
import time
from serial import Serial

ser = serial.Serial("COM3", 9600)
time.sleep(3)
print (ser.readline())
ser.write(bytes(b"0"))
```

**Comment by devyte** [comment]
I think you're in the wrong place. This is the esp8266 repo, not the ArduinoUNO repo.
Closing.
