### ISSUE TITLE
STR(ARDUINO_ESP8266_GIT_DESC) results in "unspecified"

### ISSUE THREAD

**Issue by luffykesh** [esp8266/Arduino#5842]
I am using the git version.
SDK: 2.2.1

- When a sketch is compiled for the first time
`STR(ARDUINO_ESP8266_GIT_DESC)` renders to "unspecified"

- Then if the sketch is recompiled again
`STR(ARDUINO_ESP8266_GIT_DESC)` results in a appropriate string "2.5.0-42-g82da5c76"

**Comment by AyushMarsian** [comment]
I am using windows machine with windows8.1 OS and git version.
SDK: 2.2.1

I am also facing the same issue.

**Comment by earlephilhower** [comment]
@d-a-v, didn't you push a fix for this a while back?

**Comment by d-a-v** [comment]
@luffykesh @AyushMarsian Is this still true with 2.6.1 or current git ?

**Comment by luffykesh** [comment]
Will try it out and report today.

**Comment by earlephilhower** [comment]
No update in a couple months.  I'm pretty sure @d-a-v fixed this a while back.  If it's still a problem, please open a new issue and we'll look at it.
