### ISSUE TITLE
WiFiClientSecure without a fingerprint

### ISSUE THREAD

**Issue by Colobox** [esp8266/Arduino#5851]
Some time ago I used WiFiClientSecure in my sketches without a fingerprint, but now I can't. My sketches work only with a fingerprint now.

**Comment by earlephilhower** [comment]
You didn't add a MCVE as requested. However, the solution is related to the deprecated axTLS (which doesn't verify connections by default) and the new BearSSL which does.

Either apply the fingerprint or use the `setInsecure()` option on the connection.

Closing.
