### ISSUE TITLE
PlatformIO get error at ArduinoOTA

### ISSUE THREAD

**Issue by Findus76** [esp8266/Arduino#5852]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[see below]
- Development Env:		Platformio
- Operating System:		Windows

### Settings in IDE

- Module:  			Generic ESP8266 Module
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[OTA]
- Upload Speed:   [NA] (serial upload only)

### Problem Description

Detailed problem description goes here.

Hello
My compilation environment has stopped working for no reason.
With the same project set up on another computer, the compilation works.
Earlier projects can also no longer be comiled.

**Error code from compilation**
`Compiling .pioenvs\esp12e\lib6b8\ESP8266WiFi\ESP8266WiFiSTA.cpp.o

Compiling .pioenvs\esp12e\lib6b8\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pioenvs\esp12e\lib6b8\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pioenvs\esp12e\lib6b8\ESP8266WiFi\WiFiClientSecureAxTLS.cpp.o
Compiling .pioenvs\esp12e\lib6b8\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
Compiling .pioenvs\esp12e\lib6b8\ESP8266WiFi\WiFiServer.cpp.o
Compiling .pioenvs\esp12e\lib6b8\ESP8266WiFi\WiFiServerSecureAxTLS.cpp.o
Compiling .pioenvs\esp12e\lib6b8\ESP8266WiFi\WiFiServerSecureBearSSL.cpp.o
Compiling .pioenvs\esp12e\lib6b8\ESP8266WiFi\WiFiUdp.cpp.o
Compiling .pioenvs\esp12e\lib19b\ArduinoOTA_ID6178\InternalStorage.cpp.o
Compiling .pioenvs\esp12e\lib19b\ArduinoOTA_ID6178\InternalStorageAVR.cpp.o
Compiling .pioenvs\esp12e\lib19b\ArduinoOTA_ID6178\OTAStorage.cpp.o
.piolibdeps\ArduinoOTA_ID6178\src\InternalStorage.cpp:43:21: warning: 'long_call' attribute directive ignored [-Wattributes]
void waitForReady() {
^
.piolibdeps\ArduinoOTA_ID6178\src\InternalStorage.cpp:52:63: warning: 'long_call' attribute directive ignored [-Wattributes]
static void eraseFlash(int address, int length, int pageSize)
^
.piolibdeps\ArduinoOTA_ID6178\src\InternalStorage.cpp:82:76: warning: 'long_call' attribute directive ignored [-Wattributes]
static void copyFlashAndReset(int dest, int src, int length, int pageSize)
^
.piolibdeps\ArduinoOTA_ID6178\src\InternalStorage.cpp: In function 'void copyFlashAndReset(int, int, int, int)':
.piolibdeps\ArduinoOTA_ID6178\src\InternalStorage.cpp:95:22: error: 'NVIC_SystemReset' was not declared in this scope
NVIC_SystemReset();
^
Compiling .pioenvs\esp12e\lib19b\ArduinoOTA_ID6178\WiFiOTA.cpp.o
*** [.pioenvs\esp12e\lib19b\ArduinoOTA_ID6178\InternalStorage.cpp.o] Error 1
.piolibdeps\ArduinoOTA_ID6178\src\OTAStorage.cpp: In constructor 'OTAStorage::OTAStorage()':
.piolibdeps\ArduinoOTA_ID6178\src\OTAStorage.cpp:32:1: error: expected identifier before '{' token
{
^
.piolibdeps\ArduinoOTA_ID6178\src\OTAStorage.cpp:18:1: error: uninitialized member 'OTAStorage::SKETCH_START_ADDRESS' with 'const' type 'const uint32_t {aka const unsigned int}' [-fpermissive]
OTAStorage::OTAStorage() :
^
.piolibdeps\ArduinoOTA_ID6178\src\OTAStorage.cpp:18:1: error: uninitialized member 'OTAStorage::PAGE_SIZE' with 'const' type 'const uint32_t {aka const unsigned int}' [-fpermissive]
.piolibdeps\ArduinoOTA_ID6178\src\OTAStorage.cpp:18:1: error: uninitialized member 'OTAStorage::MAX_FLASH' with 'const' type 'const uint32_t {aka const unsigned int}' [-fpermissive]
.piolibdeps\ArduinoOTA_ID6178\src\OTAStorage.cpp: In member function 'virtual void ExternalOTAStorage::apply()':
.piolibdeps\ArduinoOTA_ID6178\src\OTAStorage.cpp:50:20: error: 'NVIC_SystemReset' was not declared in this scope
NVIC_SystemReset();
^
*** [.pioenvs\esp12e\lib19b\ArduinoOTA_ID6178\OTAStorage.cpp.o] Error 1
 [ERROR] Took 5.21 seconds`

**Libraries version installed at home (station not working)**
`2.0.0·Core 4.0.0a3
 
 
ArduinoOTA by Ivan Grokhotkov and Miguel Angel Ajo
 1.0
Enables Over The Air upgrades, via wifi and espota.py UDP request/TCP download.
communication
Reveal
DNSServer by Kristijan Novoselić
 1.1.1
A simple DNS server for ESP8266.
communication
Reveal
EEPROM by Ivan Grokhotkov
 1.0
Enables reading and writing data to the permanent FLASH storage, up to 4kb.
datastorage
Reveal
ESP8266AVRISP by Kiril Zyapkov
 1.0
AVR In-System Programming over WiFi for ESP8266
communication
Reveal
ESP8266HTTPClient by Markus Sattler
 1.2
http Client for ESP8266
communication
Reveal
ESP8266HTTPUpdateServer by Ivan Grokhotkov, Miguel Ángel Ajo
 1.0
Simple HTTP Update server based on the ESP8266WebServer
communication
Reveal
ESP8266LLMNR by swarren@wwwdotorg.org
 1.0
ESP8266 LLMNR (Link-Local Multicast Name Resolution)
communication
Reveal
ESP8266NetBIOS by Pablo@xpablo.cz
 1.0
Enables NBNS (NetBIOS) name resolution.
communication
Reveal
ESP8266SSDP by Hristo Gochkov
 1.0
ESP8266 Simple Service Discovery library
communication
Reveal
ESP8266WebServer by Ivan Grokhotkov
 1.0
Simple web server library
communication
Reveal
ESP8266WiFi by Ivan Grokhotkov
 1.0
Enables network connection (local and Internet) using the ESP8266 built-in WiFi.
communication
Reveal
ESP8266WiFiMesh by Julian Fell
 2.1
Mesh network library
communication
Reveal
ESP8266httpUpdate by Markus Sattler
 1.3
Http Update for ESP8266
dataprocessing
Reveal
ESP8266mDNS by multiple, see files
 1.2
Creates a mDNS responder.
communication
Reveal
Ethernet(esp8266) by Arduino
 1.0.4
Enables network connection (local and Internet) using the Arduino Ethernet board or shield. For all Arduino boards.
communication
Reveal
GDBStub by Jeroen Domburg
 0.3
GDB server stub helps debug crashes when JTAG isn't an option.
gdbdebug
Reveal
Hash by Markus Sattler
 1.0
Generate Hash from data
dataprocessing
Reveal
SD(esp8266) by Arduino, SparkFun
 1.0.5
Enables reading and writing on SD cards. For all Arduino boards.
datastorage
Reveal
SPI by Arduino
 1.0
Enables the communication with devices that use the Serial Peripheral Interface (SPI) Bus. For all Arduino boards, BUT Arduino DUE.
signalinputoutput
Reveal
SPISlave by Hristo Gochkov
 1.0
SPI Slave library for ESP8266
signalinputoutput
Reveal
Servo(esp8266) by Michael C. Miller
 1.0.2
Allows Esp8266 boards to control a variety of servo motors.
devicecontrol
Reveal
EspSoftwareSerial
 3.4.1
Implementation of the Arduino software serial for ESP8266.
serialiosoftwareserial
Reveal
TFT_Touch_Shield_V2 by luweicong@seeedstudio.com
 2.0
TFT_Touch_Shield_V2 library
communication
Reveal
Ticker by Ivan Grokhtokov <ivan@esp8266.com>
 1.0
Allows to call functions with a given interval.
timing
Reveal
Wire by Arduino
 1.0
Allows the communication between devices or sensors connected via Two Wire Interface Bus. For esp8266 boards.
signalinputoutput
Reveal
ESP8266 by Simon Peter,Markus Sattler,Ivan Grokhotkov
 1.0
ESP8266 sketches examples
other
Reveal`

**Libraries version installed at work (station working)**
`ArduinoOTA by Ivan Grokhotkov and Miguel Angel Ajo
 1.0
Enables Over The Air upgrades, via wifi and espota.py UDP request/TCP download.
communication
Reveal
DNSServer by Kristijan Novoselić
 1.1.0
A simple DNS server for ESP8266.
communication
Reveal
EEPROM by Ivan Grokhotkov
 1.0
Enables reading and writing data to the permanent FLASH storage, up to 4kb.
datastorage
Reveal
ESP8266AVRISP by Kiril Zyapkov
 1.0
AVR In-System Programming over WiFi for ESP8266
communication
Reveal
ESP8266HTTPClient by Markus Sattler
 1.1
http Client for ESP8266
communication
Reveal
ESP8266HTTPUpdateServer by Ivan Grokhotkov, Miguel Ángel Ajo
 1.0
Simple HTTP Update server based on the ESP8266WebServer
communication
Reveal
ESP8266LLMNR
 0.0.0
uncategorized
Reveal
ESP8266NetBIOS by Pablo@xpablo.cz
 1.0
Enables NBNS (NetBIOS) name resolution.
communication
Reveal
ESP8266SSDP
 0.0.0
uncategorized
Reveal
ESP8266WebServer by Ivan Grokhotkov
 1.0
Simple web server library
communication
Reveal
ESP8266WiFi by Ivan Grokhotkov
 1.0
Enables network connection (local and Internet) using the ESP8266 built-in WiFi.
communication
Reveal
ESP8266WiFiMesh by Julian Fell
 2.0
Mesh network library
communication
Reveal
ESP8266httpUpdate by Markus Sattler
 1.2
Http Update for ESP8266
dataprocessing
Reveal
ESP8266mDNS
 0.0.0
uncategorized
Reveal
Ethernet(esp8266) by Arduino
 1.0.4
Enables network connection (local and Internet) using the Arduino Ethernet board or shield. For all Arduino boards.
communication
Reveal
GDBStub by Jeroen Domburg
 0.2
GDB server stub helps debug crashes when JTAG isn't an option.
gdbdebug
Reveal
Hash by Markus Sattler
 1.0
Generate Hash from data
dataprocessing
Reveal
SD(esp8266) by Arduino, SparkFun
 1.0.5
Enables reading and writing on SD cards. For all Arduino boards.
datastorage
Reveal
SPI by Arduino
 1.0
Enables the communication with devices that use the Serial Peripheral Interface (SPI) Bus. For all Arduino boards, BUT Arduino DUE.
signalinputoutput
Reveal
SPISlave by Hristo Gochkov
 1.0
SPI Slave library for ESP8266
signalinputoutput
Reveal
Servo(esp8266) by Michael C. Miller
 1.0.2
Allows Esp8266 boards to control a variety of servo motors.
devicecontrol
Reveal
EspSoftwareSerial
 3.4.1
Implementation of the Arduino software serial for ESP8266.
serialiosoftwareserial
Reveal
TFT_Touch_Shield_V2
 0.0.0
uncategorized
Reveal
Ticker by Ivan Grokhtokov <ivan@esp8266.com>
 1.0
Allows to call functions with a given interval.
timing
Reveal
Wire by Arduino
 1.0
Allows the communication between devices or sensors connected via Two Wire Interface Bus. For esp8266 boards.
signalinputoutput
Reveal
ESP8266 by Simon Peter,Markus Sattler,Ivan Grokhotkov
 1.0
ESP8266 sketches examples
other
Reveal
Web·Open Source·Get Started·Docs·News·Community·Contact Us`

Brg
Findus

**Comment by jandrassy** [comment]
you have the non esp ArduinoOTA library. the ArduinoOTA library in esp8266 core package should have precedence

**Comment by Findus76** [comment]
Many thanks!
My weekend is saved!

Brg
Findus
