### ISSUE TITLE
compile error: cannot declare field to be of abstract type

### ISSUE THREAD

**Issue by aster94** [esp8266/Arduino#5858]
#### Platform

- Hardware:				any but tested on MODE MCU 0.9 (ESP12)
- Core Version:			1.0 from arduino package manager
- Development Env:		Arduino IDE
- Operating System:		any Windows Ubuntu

### Settings in IDE
not relevant

### Problem Description
I am writing a library ([GoProControl](https://github.com/aster94/GoProControl)) it works on all boards with wifi, to make HTTP request i use [ArduinoHttpClient](https://github.com/arduino-libraries/ArduinoHttpClient) because it is cross platform. I know that ESP8266 has its own HTTP library but since the API is not the same I can't use it

on ESP32 all works well, could someone help me understand what this error mean and how could it be fixed? It seems to be something related to the `virtual` definition

here the complete compile log:
https://hastebin.com/bipopeyuhu.sql

###
any example which include the library GoProControl:
``` ino
#include <GoProControl.h>
GoProControl gp("a", "b", HERO3);

void setup(){}
void loop(){}
```

**Comment by jandrassy** [comment]
it is this https://github.com/esp8266/Arduino/issues/5749
