### ISSUE TITLE
Feature Request:  Add method to WiFIMulti to query which AP entry was selected and/or connected to?

### ISSUE THREAD

**Issue by dachshund-digital** [esp8266/Arduino#5868]
Title above pretty much defines the feature request.  Add method to WiFIMulti to query which AP entry was selected and/or connected to?  Which entry was selected as best?

**Comment by Zeron** [comment]
You can use WiFi.SSID() to get the AP you are connected to.

**Comment by devyte** [comment]
Previous comment is coorrect.
Closing.
