### ISSUE TITLE
Writing 2x 4 bytes to SPIFFs taking 16 bytes

### ISSUE THREAD

**Issue by atrjt** [esp8266/Arduino#5869]
----------------------------- Delete below -----------------------------

If your issue is a general question, starts similar to "How do I..", is related to 3rd party libs, or is related to hardware, please discuss at a community forum like esp8266.com.

INSTRUCTIONS
============
If you do not follow these instructions, your issue may be dismissed.

1. Follow the checklist under Basic Infos and fill in the [ ] spaces with an X.
2. Fill in all the fields under Platform and Settings in IDE marked with [ ] (pick the correct option for you in each case, delete the others).
3. If you haven't already done so, test your issue against current master branch (aka latest git), because it may have been already fixed.
4. Describe your problem.
5. If you have a STACK DUMP decode it:

https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/stack_dump.html

6. Include a Minimal Complete Reproducible Example sketch that shows your issue. Do not include your entire project, or a huge piece of code.
7. Include debug messages:

https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/debugging.html 

8. Use markup (buttons above) and the Preview tab to check what the issue will look like.
9. Delete these instructions from the above to the below marker lines before submitting this issue.

----------------------------- Delete above -----------------------------

### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12]
- Core Version:			[V2.5.0]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  		[other]
- Flash Mode:		[qio|dio|other]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:	[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:	[80Mhz|160MHz]
- Upload Using:	[OTA]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

I'm writing and reading a struct containing two doubles with SPIFFs. From Arduino documentation I expected each double to occupy 4 bytes, giving a total of 8 bytes per struct read/write, but instead it appears to be 16 bytes per struct read/write. I've checked this with sizeof() and also file.seek

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

struct calData {
  double a;
  double b;
};
struct calData myCalData; 

void setup() {
Sprintln("sizeof(myCalData)=" + String(sizeof(myCalData)));
}

void loop() {

}

```

### Debug Messages

```
sizeof(myCalData)=16
```

**Comment by earlephilhower** [comment]
Doubles are 8 bytes, not 4.  Closing.
