### ISSUE TITLE
fatal error: avr/interrupt.h: No such file or directory

### ISSUE THREAD

**Issue by princeabhishek** [esp8266/Arduino#5876]
Arduino: 1.8.3 (Windows 10), Board: "ESP32 Dev Module, Disabled, Default, 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 115200, None"

C:\Users\Actab\OneDrive\Documents\Arduino\libraries\SoftwareSerial-master\SoftwareSerial.cpp:41:27: fatal error: avr/interrupt.h: No such file or directory

compilation terminated.

Multiple libraries were found for "WiFi.h"
 Used: C:\Users\Actab\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.1\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
Error compiling for board ESP32 Dev Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by earlephilhower** [comment]
This is the ESP8266 Arduino repo, you're posting an ESP32 compile bug.  Please move to the appropriate tracker.
