### ISSUE TITLE
New Reference not working

### ISSUE THREAD

**Issue by itay-grudev** [esp8266/Arduino#589]
This might not be related to this code or just the links in the README file to the Reference might be broken, but since you've updated the `README.md` I can't access the Reference.

**Comment by igrr** [comment]
There are three Reference links in Readme: "stable", "staging", and "development".
First one (stable) doesn't work because there was no HTML documentation when stable release was built. 
"Staging" reference and "development" reference seem to work fine.

**Comment by itay-grudev** [comment]
And it is rather pretty. Thanks mate.

P.S. I will leave this open so you can decide whether to close it now or after the stable reference works.

**Comment by igrr** [comment]
Should work now.
