### ISSUE TITLE
ESP8226 Interrupt Switch

### ISSUE THREAD

**Issue by pfz4** [esp8266/Arduino#5909]
Hi,
is it possible to have ESP in DeepSleep and wake him up, when an interrupt changes and read the current state? I wan't to make some kind of an OpenHAB connected switch. 

Thank you very much.
PS: I don't know if I'm right here to ask this question, but esp9266.com didn't want to take my Robot verification Result :)

**Comment by fsommer1968** [comment]
It is not possible during DeepSleep. During deepsleep only RST can be used.

N.B. What is the product you are asking for? This is a repo for 8266. Your title asks for 8226  and you are referring to esp9266??
