### ISSUE TITLE
Upgrade SDK to 1.2.0

### ISSUE THREAD

**Issue by georgkreimer** [esp8266/Arduino#591]
Current version uses 1.0.1_15_05_04_p1. It would be great if the SDK could be upgraded to 1.2.0 since there have been a bunch of important fixes in the past releases. I think the most important one is the fix of SSL.

**Comment by igrr** [comment]
SDK has already been upgraded to 1.2+, but this change didn't make it into the stable release yet. Please wait a bit for the release update.

**Comment by georgkreimer** [comment]
Thanks!

**Comment by igrr** [comment]
Released in stable package (1.6.5-947-g39819f0).
