### ISSUE TITLE
Streaming audio(.3gp)from FIREBASE to NODEMCU to SPEAKER #REALTIME 

### ISSUE THREAD

**Issue by AbeeB** [esp8266/Arduino#5913]
How do I fetch audio saved as .3gp in firebase and send to nodemcu and then to speaker?

#i used MIT app Inventor to create app and store the recording (.3gp) in Firebase

would I need an arduino?or some other hardware to do the operation.What would be the procedure.

Please sort this query friends...

**Comment by AbeeB** [comment]
can u specify the solution in detail sir

**Comment by d-a-v** [comment]
Maybe [ESP8266Audio](https://github.com/earlephilhower/ESP8266Audio) is what you need. You will not get details here or there. Use discussion forum.

Quoting [Policy](https://github.com/esp8266/Arduino/blob/master/POLICY.md):

> Questions of type "**How do I**..." or "Can you please help me with..." or "Can the ESP do..." won't be handled here. Such questions should be directed at a discussion forum, like esp8266.com or stackoverflow. All issues of this type will be closed [...]

**Comment by AbeeB** [comment]
Ok sir I'll see towards it
Thanku sir

**Comment by freddymagne** [comment]
sad
