### ISSUE TITLE
valgrind: WString: strings overlap

### ISSUE THREAD

**Issue by d-a-v** [esp8266/Arduino#5949]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:				any
- Core Version:			git
- Development Env:		other: host emulation
- Operating System:		linux

### Settings in IDE

- Module:  			any
- Flash Mode:			any
- Flash Size: 		any
- lwip Variant:   any
- Reset Method:		any
- Flash Frequency:	any
- CPU Frequency:		any
- Upload Using:		any
- Upload Speed:   any

### Problem Description

valgrind complains with `core/esp8266/WString.cpp`:
```
Source and destination overlap in strcpy(0x1fff0000e0, 0x1fff0000e0)
```

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp
void setup ()
{
        String blah = "blah";
        blah.replace("xx","y");
}

void loop ()
{
}
```

### How to reproduce:

```
cd tests/host
mkdir -p ino/WString
# put MCVE in ino/WString/WString.ino
make -j FORCE32=0 ino/WString/WString
# ...
valgrind bin/WString/WString
```

line 747: https://github.com/esp8266/Arduino/blob/f0eb5509a02134aad2158ecc97167e209fa1c098/cores/esp8266/WString.cpp#L747

**Comment by TD-er** [comment]
It looks like the fix needs to: (first two are too obvious, but just for completeness)
- check pointers differ
- determine nr of bytes to move/copy
- Do not use copy, but use memmove (see warnings at both [memcpy](http://www.cplusplus.com/reference/cstring/memcpy/) and [strcpy](http://www.cplusplus.com/reference/cstring/strcpy/))

N.B. `memcpy` is used at more places in the same function on the same arrays.
