### ISSUE TITLE
Trying to upload files via XMLHttpRequest/FormData

### ISSUE THREAD

**Issue by holgerlembke** [esp8266/Arduino#5956]
I try to upload a file via html5 + XMLHttpRequest. I use
```
    var xhr = new XMLHttpRequest(); 
    xhr.open('POST', '/r.html'); 
    var formdata = new FormData();  
    formdata.append('uploadfile', file);
    xhr.send(formdata);   
```

my Webservers receiving event is created via 
```
  mgr.on("/r.html", HTTP_POST, rcvr);
```
In my receiver I have it stripped down to

```
void rcvr(void) {
  HTTPUpload& upload = fileManager->upload();
  Serial.println("Server upload Status: " + String(upload.status));
}
```
I only see a "Server upload Status: 2" (UPLOAD_FILE_END) on small files, on larger files esp hangs.

Any ideas?

**Comment by d-a-v** [comment]
No idea without the filled out issue template that were presented to you when you opened the issue.

Do that, and retry with git version, all debug option enabled.
