### ISSUE TITLE
Serial upload pattern

### ISSUE THREAD

**Issue by roberttidey** [esp8266/Arduino#5963]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12|
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE
- Operating System:		[Windows

### Settings in IDE

- Module:  			[espino]
- Flash Mode:			[qio]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[ck]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200]

### Problem Description
Serial upload throws an error with usage of esptool shown.

platform.txt has
tools.esptool.upload.pattern="{cmd}" "{runtime.platform.path}/tools/upload.py" --chip esp8266 --port "{serial.port}" --baud "{upload.speed}" "{upload.verbose}" {upload.erase_cmd} --end --chip esp8266 --port "{serial.port}" --baud "{upload.speed}" "{upload.verbose}" write_flash 0x0 "{build.path}/{build.project_name}.bin" --end

where the region between --chip and --end seems to be a duplicate

I removed this to give 
tools.esptool.upload.pattern="{cmd}" "{runtime.platform.path}/tools/upload.py" --chip esp8266 --port "{serial.port}" --baud "{upload.speed}" "{upload.verbose}" write_flash 0x0 "{build.path}/{build.project_name}.bin" --end

The serial upload then worked fine.

Is this correct or am I misunderstanding something?

**Comment by earlephilhower** [comment]
It is correct as-is in the platform.txt.  `cmd` is the `upload.py`and not `esptool.py`.  The Arduino IDE does not allow multiple commands for the upload rules, so you need to specify a single command line and hence the upload.py wrapper.

`upload.py` will call esptool w/the first set of options up to the first `--end`, then call esptool.py again with the next set of options.  The first set is related to the erase option menu (full chip, only program space, include configuration sector, etc.) and the second is the actual upload.
