### ISSUE TITLE
Streaming Audio

### ISSUE THREAD

**Issue by Pablotis** [esp8266/Arduino#597]
It would be awesome to support audio in streaming

**Comment by fredericplante** [comment]
Let's see if' it's possible to adapt the old SDaudio library. They pushed the support up to sending audio using a NDR24 device, but i remember that they say that it was wrap to make it easy to use other kind of device.

https://www.google.com/search?q=SDaudio+library.&ie=utf-8&oe=utf-8

http://forum.arduino.cc/index.php?topic=233857.0

Let's have a look ;)
