### ISSUE TITLE
Is there any different way to login into web server?

### ISSUE THREAD

**Issue by ChipTechno** [esp8266/Arduino#5971]
Hello. I want to ask if there is any different way to login into web server?

In the library example, the following code will show the login form to login into the web server.
<pre>
if (!server.authenticate(www_username, www_password)) 
{
      return server.requestAuthentication();
}
</pre>

But I want to login into the web server (or set the authenticated to true) via a function call instead of showing a login form.
(something like the below code).
<pre>
login("myid","mypassword");
</pre>
Is there any way to do that? 
Thank in advance and sorry for my bad English!

**Comment by devyte** [comment]
Closing due to "how do I..." type question.
