### ISSUE TITLE
http.GET() returns code of -11

### ISSUE THREAD

**Issue by bill-orange** [esp8266/Arduino#5979]
Using ESP8266HTTPClient  to collect data from OpenWeatherMap with an `http.GET(); ` I get a return code of -11.  It happens once very 15 or 20 calls.  I can not find any documentation of this code.  The normal return code on successful attempts is 200.

Does anybody know what a -11 code means?

**Comment by bill-orange** [comment]
answered my own question.  Its a timeout.

**Comment by santigo171** [comment]
How did you solved it?

**Comment by santigo171** [comment]
How did you solve it?

**Comment by bill-orange** [comment]
II made multiple attempts.  If it failed repeatedly, I had the option to restarted the ESP8266.

Serial.println("  ");
   OWMError = getOWMWeatherCondition();
   Serial.print("OWM Error Return Code: "); Serial.println(OWMError);
   if (OWMError != 200) {
     WiFiFix();
     OWMError = getOWMWeatherCondition();
     Serial.print("OWM Error Return Code: "); Serial.println(OWMError);
     if (OWMError != 200) {
       OWMError = getOWMWeatherCondition();
       if ( testJSON() != 200 ) {
         Serial.println("                                            Bad OWM Test Return Code ........ Skipping");
         //esp_restart();
