### ISSUE TITLE
2.5.0-beta3 IPAddress   initialized by default  (not nullptr)

### ISSUE THREAD

**Issue by dzanis** [esp8266/Arduino#5984]
#### Platform

- Hardware:					[ESP-12]
- Core Version:			[2.5.0-beta3]
- Development Env:		[Arduino IDE|vMicro]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Wemos D1 mini r2|Nodemcu]
- Flash Mode:			[dio]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] 

### Problem Description
IPAddress    initialized by default  (not nullptr)
I compiled a sketch AutoConnect.ino from the library WiFiManager
and static  IPAddress    _sta_static_ip
https://github.com/tzapu/WiFiManager/blob/740005b21e5f5e5c6092dbd4d3037e4edee19113/WiFiManager.h#L141
is turned on here
https://github.com/tzapu/WiFiManager/blob/740005b21e5f5e5c6092dbd4d3037e4edee19113/WiFiManager.cpp#L280
what looks like some kind of compilation error.
This knocks down wifi settings
I already returned the version 2.5.0. Just warned you. Thanks.

**Comment by Jason2866** [comment]
You know that beta3 was before 2.5.0? 
Actual dev version is 2.6 and not availiable via board manager.
