### ISSUE TITLE
Arduino IDE - cohabitation between esp32 and esp8266 2.5.0  

### ISSUE THREAD

**Issue by Shuptuu** [esp8266/Arduino#5988]
Hi,
There's apparently a cohabitation problem on the arduino IDE when are installed both esp8266 2.5.0 and esp32 1.0.2-rc2
When selecting the Generic ESP8266 Module in the board manager, the settings list displayed in the tools menu belong to an ESP32 board. For exemple, it shows: CPU Frequency "240MHz (Wifi/BT)". But when having a look to the different parameter's values, it shows this time the correct esp8266 options (i.e. 80MHz and 160MHz for the CPU Frequency).
The problem appeard after the update to version 2.5.0
Going back to 2.4.2 and the problem disappear.
Tested with Arduino IDE 1.8.8 and 1.8.9 : same thing
Tested on 2 laptops: same thing

**Comment by earlephilhower** [comment]
Sorry, but this doesn't seem reproducible by others and looks like it's completely in the Arduino IDE and not in the core.  I would suggest popping over to their repo and seeing if others are seeing similar issues.  https://github.com/arduino/Arduino
