### ISSUE TITLE
How to receive a raw json over Get with server.arg() ?

### ISSUE THREAD

**Issue by RobertHolscher** [esp8266/Arduino#6014]
--Hi I am setting up a webserver and everything is working well with webserver library.
It is working a bit too well: I am receiving a json get message through server.arg() and get all the separate variables with their value. However, I need the raw json instead of all the separate values.
Of course I can put them together again as json but I was wondering if there is a way to get the raw json into a variable with your library?

I hope one of you can help me with this

**Comment by d-a-v** [comment]
If the answer is not the undocumented `server.arg("plain")`, please fill the issue template instead of deleting it.
