### ISSUE TITLE
Wrong mac address in softAP mode.

### ISSUE THREAD

**Issue by mbm60** [esp8266/Arduino#6017]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:			ESP-12
- Core Version:			both 2.5.0 and 2.6.0
- Development Env:		Arduino IDE
- Operating System:         Windows

### Settings in IDE

- Module:  			Generic ESP8266 Module
- Flash Mode:			qio
- Flash Size: 		        4MB/1MB
- lwip Variant:                   v2 Lower Memory
- Reset Method:		ck
- Flash Frequency:	        40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:                115200

### Problem Description

When i use software access point mode, return MAC address : A2:20:A6:10:DC:3D
But when i use station mode, return MAC address : A0:20:A6:10:DC:3D
and also esptool.py 2.6 return MAC address : a0:20:a6:10:dc:3d
i guss sofAP mode return wrong MAC address.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <ESP8266WiFi.h>


const char* ssid = "...";
const char* password = "...";

void setup() {
  Serial.begin(115200);
  Serial.println();
  
  WiFi.softAP(ssid, password);

  Serial.printf("MAC address = %s\n", WiFi.softAPmacAddress().c_str());
  
}

void loop() {

}

**Comment by devyte** [comment]
Different MACs for AP and STA is normal, they are different wifi interfaces.
Closing.
