### ISSUE TITLE
Wemos D1 R1

### ISSUE THREAD

**Issue by Kamil34138** [esp8266/Arduino#6018]
Hi, 
I have problem with Wemos D1 R1. 
I want connect with wifi and mobile app "Blynk" but when i upload program for connect arduino to wifi, I have problem. 
Some Errors.
When i conncect GND and D9(GPI02) the LED on wifi module turn on... 

Errors:

warning: espcomm_sync failed 
error: espcomm_open failed 
error: espcomm_open failed  

Code: 

#define BLYNK_PRINT Serial
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

// You should get Auth Token in the Blynk App.
// Go to the Project Settings (nut icon).
char auth[] = "...";

// Your WiFi credentials.
// Set password to "" for open networks.
char ssid[] = "...";
char pass[] = "...";

void setup()
{
  // Debug console
  Serial.begin(9600);

  Blynk.begin(auth, ssid, pass);
}

void loop()
{
  Blynk.run();
}

**Comment by devyte** [comment]
This is an issue tracker, meant for tracking issues in our core code. It is not a general support forum. I suggest seeking help at esp8266.com or stackoverflow for basic questions. 
The LED connected to gpio2 is inverted on esp12 modules, so pulling the pin low makes it light up. That is normal. 
Closing.
