### ISSUE TITLE
Deep sleep sometimes sleeps for hours instead of seconds. 

### ISSUE THREAD

**Issue by zoidicus** [esp8266/Arduino#602]
I have a sketch that is supposed to go into deep-sleep for 15 seconds between sensor samples.  It works correctly for a while, and then it'll sleep for an unexpectedly long time, sometimes as long as an hour.  Normal operation resumes for a while, and then there'll be another really long sleep.  

The sleep interval is defined as a constant:
&nbsp;&nbsp;const uint32_t SLEEP_INTERVAL = 15 * 1000 * 1000;
The call to deepSleep is shown here:
&nbsp;&nbsp;ESP.deepSleep(SLEEP_INTERVAL, WAKE_RF_DISABLED); 

I have not noticed whether the other WAKE_RF_...... modes are affected.

**Comment by Links2004** [comment]
please retry in last release, 
If it still a problem feel free to reopen.
