### ISSUE TITLE
HTTP Authentication with hash H(A1) to avoid storing password in flash memory.

### ISSUE THREAD

**Issue by overtone1000** [esp8266/Arduino#6021]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Core Version:			[cdb5495]

#### Other Pertinent Issues/PRs
- have only found one issue (#4392) that asked a related question about digest authentication, but this was closed as the question was about the security of the transmission, not about its storage. This issue was quickly closed.
- I have found two pull requests (#3328 and #4404) that address a similar issue with basic authentication.

#### Description

This is a feature request.

[RFC 2617 4.13](https://tools.ietf.org/html/rfc2617#section-4.13) discusses storing credentials as the username and H(A1) rather than the username and password, but this isn't possible with the current implementation of Digest authentication in the ESP8266WebServer class because the authenticate function takes username and password as arguments.

I've implemented this feature in PR #6020, but my primary reason for creating this issue is to facilitate discussion as suggested in the documents. The primary question I have is whether this proposed feature offers such a small benefit in security that it isn't even worth the trouble.

Thanks for your time.

**Comment by earlephilhower** [comment]
Closing as #6020 is now merged.
