### ISSUE TITLE
[Static IP] Code that previously worked no longer works

### ISSUE THREAD

**Issue by rtek1000** [esp8266/Arduino#6024]
Hi,

Without setting a fixed address, the ESP8266 can get the IP address via DHCP, so the hello webserver example works normally. But if I add the static IP configuration, then the browser can not find the server (The serial monitor shows the static IP address correctly)

The code worked correctly until about November 2018 (it was the last time I tested it).

Were there any radical changes in the library?

Arduino IDE 1.8.9
ESP8266 2.5.0 (library installed using the Board Manager)
Windows 10 x64
NodeMCU Lolin V3

I will downgrade the library version to try to find a version that works.

Ref.: https://arduino-esp8266.readthedocs.io/en/2.5.0/esp8266wifi/station-class.html#config

Basic code:
```
WiFi.begin(ssid, password);
IPAddress ip(192,168,1,74);   
IPAddress gateway(192,168,1,1);   
IPAddress subnet(255,255,255,0);   
IPAddress dns(8,8,8,8); 
WiFi.config(ip, gateway, subnet, dns);
```

Thank you.

**Comment by rtek1000** [comment]
Yep, It worked with version 2.4.0 (but what a giant package this is!)

**Comment by rtek1000** [comment]
I uninstalled version 2.4.0 and installed version 2.5.0 and then IDE showed this error:

> cc1plus.exe: out of memory allocating 65536 bytes

If someone else receives this error: I've seen this error before, and to resolve it just reboot the computer.

**Comment by d-a-v** [comment]
It will work if you move `WiFi.config()` before `WiFi.begin()`.
This is #5839 duplicate

**Comment by rtek1000** [comment]
Yep, It worked with version 2.5.0 now.

It looks like the problem was waiting for the connection before setting the IP address.

Thank you.

![static ip](https://user-images.githubusercontent.com/8660811/56932695-15485000-6abb-11e9-9ba0-9a3ca2eec3d4.jpg)
