### ISSUE TITLE
remove INPUT_PULLDOWN for GPIO16? 

### ISSUE THREAD

**Issue by mhanuel26** [esp8266/Arduino#604]
on version 1.6.4-673-g8cd3697, this instruction compiles and works correctly 

pinMode(16, INPUT_PULLDOWN);           

On new release, I got:

REMOTE_SENSOR_ONE_WIRE.ino: In function 'void setup()':
REMOTE_SENSOR_ONE_WIRE.ino:490:15: error: 'INPUT_PULLDOWN' was not declared in this scope
REMOTE_SENSOR_ONE_WIRE.ino: In lambda function:
REMOTE_SENSOR_ONE_WIRE.ino:680:40: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
'INPUT_PULLDOWN' was not declared in this scope

**Comment by reaper7** [comment]
I think that pin16 must be pull down via INPUT_PULLDOWN_16
check line 68 core_esp8266_wiring_digital.c
so...README must be changed

**Comment by mhanuel26** [comment]
Thank you.
