### ISSUE TITLE
ICACHE_RAM_ATTR problem

### ISSUE THREAD

**Issue by Microsyl** [esp8266/Arduino#6042]
- ESP8266 wemos mini
- Visual Micro over Visual Studio

Hi,  I use the library fast led who use ICACHE_RAM_ATT it's work fine, but in my code I use another very short interrupt "3 line of code" and if I didn't define my int at ICACHE_RAM_ATT the cpu crash every 5 min with the stack dump I included.  the problem is I can't define my interrupt with ICACHE_RAM_ATT the compiler give me this error

clockless_esp8266.h: In static member function static uint32_t ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::showRGBInternal(PixelController<RGB_ORDER>) [with int DATA_PIN = 0; int T1 = 52; int T2 = 52; int T3 = 103; EOrder RGB_ORDER = (EOrder)66u; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 50; uint32_t = unsigned int]
 
clockless_esp8266.h: 73:34: error: static uint32_t ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::showRGBInternal(PixelController<RGB_ORDER>) [with int DATA_PIN = 0; int T1 = 52; int T2 = 52; int T3 = 103; EOrder RGB_ORDER = (EOrder)66u; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 50; uint32_t = unsigned int] causes a section type conflict with void NTP_ESPClockInterupt()
   static uint32_t ICACHE_RAM_ATTR showRGBInternal(PixelController<RGB_ORDER> pixels) {
NTP.ino:49: note  void NTP_ESPClockInterupt() was declared here
   void  ICACHE_RAM_ATTR NTP_ESPClockInterupt()

Thanks for your time
Sylvain Bissonnette

Failed to resolve hardware exception from the monitor text
Exception:Error:29 -> StoreProhibited: CPU tried to store memory from a region which is protected against writes

Exception (29):
epc1=0x4000e1c3 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000018 depc=0x00000000

ctx: sys 
sp: 3ffffc50 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffdf0:  00000000 00000000 00000020 40100ec6  
3ffffe00:  4021ba76 4021b994 3fff113c 3ffedcb4  
3ffffe10:  4021fdf5 3ffffed0 3ffee0c8 00000016  
3ffffe20:  00000018 3ffed8f0 3ffed86c 00000000  
3ffffe30:  4021bb37 3ff20a00 3fff113c 3ffea3ca  
3ffffe40:  3ffea3b0 3ffffed0 3ffffed0 00000000  
3ffffe50:  7263694d 6c79536f 40102100 3ffea3b0  
3ffffe60:  3ffea3ca 0000002c 00000008 401004f4  
3ffffe70:  3ffea3ba 3fff15a4 402186f8 3ff20a00  
3ffffe80:  3fff113c 3fff2bfc 00000015 402185cb  
3ffffe90:  3ffee750 3fff0d8c 00000000 4021e5cf  
3ffffea0:  00000000 062706a5 4021e63a 3fff0d8c  
3ffffeb0:  3fff0d74 ffffffd3 00000000 ffffffff  
3ffffec0:  40000f3d 00000023 00000000 00000064  
3ffffed0:  402101f0 3ffe9128 3ffe9128 401004d8  
3ffffee0:  3ffe9d90 000000ad 3ffe9da3 40215f14  
3ffffef0:  3ffe9da9 3ffe9d90 00000023 4020f378  
3fffff00:  402203a1 ffffffc3 00000000 4020f3b4  
3fffff10:  40217e07 3ffea3b0 3ffece58 3fff113c  
3fffff20:  00000000 3ffea3ba 3ffea3d0 3fff07f0  
3fffff30:  402101f0 00000000 00000000 3ffea3ba  
3fffff40:  40104d7e 00000066 00000000 3fff15a4  
3fffff50:  3ffea3a4 00000000 00000023 4022788a  
3fffff60:  3ffece58 3ffea3a4 3fffdcc0 3ffe95b8  
3fffff70:  3ffea3c0 3fff13e4 00000040 3ffe95b8  
3fffff80:  00000040 3ffece58 00000000 3ffef680  
3fffff90:  40227167 3fffdab0 00000000 402079b3  
3fffffa0:  3ffe95b8 40000f49 3fffdab0 40000f49  
<<<stack<<<

----------------------------- Delete 

### Debug Messages

```
Debug messages go here
```

**Comment by devyte** [comment]
This is not the right place to ask general support questions. This is an issue tracker, meant for tracking issues in the core hosted in this repo. I suggest seeking help at esp8266.com or stackoverflow.
Closing.
