### ISSUE TITLE
nodemcu complining problum

### ISSUE THREAD

**Issue by karthik1434** [esp8266/Arduino#6052]
cide is
#include <ESP8266HTTPClient.h>

#include <ESP8266WiFi.h>

#include <FirebaseArduino.h>

including esp8266 http andesp8266 wifi in not complini
In file included from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:36:0,

                 from C:\Users\KARTHIK\Desktop\JHVSDFKBDB\JHVSDFKBDB.ino:1:

C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiClient.h:56:15: error: 'virtual int WiFiClient::connect(IPAddress, uint16_t)' marked override, but does not override

   virtual int connect(IPAddress ip, uint16_t port) override;

               ^C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiClient.h:76:16: error: 'virtual void WiFiClient::stop()' marked override, but does not override

   virtual void stop() override { (void)stop(0); }

In file included from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/ESP8266WiFi.h:40:0,

                 from C:\Users\KARTHIK\Desktop\JHVSDFKBDB\JHVSDFKBDB.ino:3:

C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiServer.h:52:14: error: invalid abstract return type for member function 'WiFiClient WiFiServer::available(uint8_t*)'

   WiFiClient available(uint8_t* status = NULL);

              ^

In file included from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:36:0,

                 from C:\Users\KARTHIK\Desktop\JHVSDFKBDB\JHVSDFKBDB.ino:1:

C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiClient.h:45:7: note:   because the following virtual functions are pure within 'WiFiClient':

 class WiFiClient : public Client, public SList<WiFiClient> {

       ^

In file included from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiClient.h:27:0,

                 from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:36,

                 from C:\Users\KARTHIK\Desktop\JHVSDFKBDB\JHVSDFKBDB.ino:1:

C:\Users\KARTHIK\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266/Client.h:29:21: note: 	virtual int Client::connect(const IPAddress&, uint16_t)

         virtual int connect(CONST IPAddress& ip, uint16_t port) =0;

                     ^

In file included from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41:0,

                 from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,

                 from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,

                 from C:\Users\KARTHIK\Desktop\JHVSDFKBDB\JHVSDFKBDB.ino:3:

C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h: In member function 'int BearSSL::WiFiClientSecure::getMFLNStatus()':

C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:110:67: error: 'br_ssl_engine_get_mfln_negotiated' was not declared in this scope

       return connected() && br_ssl_engine_get_mfln_negotiated(_eng);

                                                                   ^

In file included from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiServerSecure.h:23:0,

                 from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,

                 from C:\Users\KARTHIK\Desktop\JHVSDFKBDB\JHVSDFKBDB.ino:3:

C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiServerSecureBearSSL.h: At global scope:

C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiServerSecureBearSSL.h:59:22: error: invalid abstract return type for member function 'BearSSL::WiFiClientSecure BearSSL::WiFiServerSecure::available(uint8_t*)'

     WiFiClientSecure available(uint8_t* status = NULL);

                      ^

In file included from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41:0,

                 from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,

                 from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,

                 from C:\Users\KARTHIK\Desktop\JHVSDFKBDB\JHVSDFKBDB.ino:3:

C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:34:7: note:   because the following virtual functions are pure within 'BearSSL::WiFiClientSecure':

 class WiFiClientSecure : public WiFiClient {

       ^

In file included from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266WiFi\src/WiFiClient.h:27:0,

                 from C:\Users\KARTHIK\Desktop\arduino-1.8.9\libraries\ESP8266HTTPClient\src/ESP8266HTTPClient.h:36,

                 from C:\Users\KARTHIK\Desktop\JHVSDFKBDB\JHVSDFKBDB.ino:1:

C:\Users\KARTHIK\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\cores\esp8266/Client.h:29:21: note: 	virtual int Client::connect(const IPAddress&, uint16_t)

         virtual int connect(CONST IPAddress& ip, uint16_t port) =0;

                     ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by devyte** [comment]
Zero information provided from what is required in the issue template.
Off the top of my head, this looks like an installation problem or 3rd party lib problem. If our core classes really had an override problem or incompatible return types, CI would be dead.
Closing due to lack of info.
