### ISSUE TITLE
Rel 2.5.1 CRC error

### ISSUE THREAD

**Issue by Testato** [esp8266/Arduino#6073]
Via BoardManager on last arduino Ide 1.8.9 on Win10, it is not possible install the version 2.5.1 of the core.
If you try to install the ver 2.5.0 it works regularly

`CRC doesn't match, file is corrupted.`

**Comment by elgerg** [comment]
Same on 1.8.8

**Comment by artafakharide** [comment]
Me 2

**Comment by makermelissa** [comment]
I downloaded the file that the .json file points to, ran a manual CRC and am getting `SHA-256:77874cf43f9bb22024ed9f23296517854c8d4cd8352a5ded27b60c90d2af6873` instead of the listed `SHA-256:a433b764ca75d90c3df632949ff91777afe06e4e07a691cd68e7cf8c51eafc8c` which is causing the failure.

**Comment by sanchosk** [comment]
Same here, tried to download from multiple workstations, I always end up with SHA256 
77874cf43f9bb22024ed9f23296517854c8d4cd8352a5ded27b60c90d2af6873

**Comment by fape** [comment]
Same here. 1.8.9.
https://arduino.esp8266.com/stable/package_esp8266com_index.json
But hash is different what is in https://github.com/esp8266/Arduino/releases/download/2.5.1/package_esp8266com_index.json


![image](https://user-images.githubusercontent.com/1052464/57573741-ee7c0900-742c-11e9-9d80-aa7f2e3850d1.png)

**Comment by Jason2866** [comment]
zip file is missing under the link 
https://github.com/esp8266/Arduino/releases/download/2.5.1/esp8266-2.5.1.zip

**Comment by d-a-v** [comment]
Well this one has to be good, please retry

**Comment by makermelissa** [comment]
Looks like it was fixed a few minutes ago and is working.
