### ISSUE TITLE
String+char gives strange result

### ISSUE THREAD

**Issue by testvideos** [esp8266/Arduino#6075]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:					ESP-12
- Core Version:			2.5.0
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			Wemos D1 mini r2
- Flash Mode:			?
- Flash Size: 		4MB
- lwip Variant:  v2 Lower Memory
- Reset Method:		?
- Flash Frequency:	[40Mhz]
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:  921600

d only)
### Problem Description

adding String and char function gives a strange result

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

void setup() {
  Serial.begin(9600);
}

void loop() {
  String a = "0x"+ b()+ b()+ b()+ b()+ b();

  Serial.println(a);
  Serial.println("0x5");
delay(1000);
}
char b(){
return '5';
}

```

### Debug Messages

```
Debug messages go here
```
![image](https://user-images.githubusercontent.com/45394789/57575749-8d1e5f00-7459-11e9-8186-34d2ef35b98f.png)

![image](https://user-images.githubusercontent.com/45394789/57575779-e9817e80-7459-11e9-8a2b-63a60098aba6.png)

**Comment by d-a-v** [comment]
`"0xhello"` is a `char*` pointer, not a String. 
`"0xhello" + 2` is `"hello"`.
You need to `String(F("0x")) + b() + b() ...`
