### ISSUE TITLE
esp8266 mDNS fails to respond to client request 

### ISSUE THREAD

**Issue by dgbalharrie** [esp8266/Arduino#6083]
### Basic Infos

- [x ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [x ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ x] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[latest release]
- Development Env:		[Visual Micro]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Wemos D1 mini r2]
- Flash Mode:			[other]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200]

### Problem Description

mDNS fails to respond to client request when used as part of a webserver. A client request using the IP address works fine. This is not a permanent fail, after a period of time it will work again. 

I have tried the example webserver sketch mDNS_Web_Server.ino and seen the same problems.

I have not been able to determine a pattern of failure as it is intermittent.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

Failed using mDNS_Web_Server.ino example sketch.
```

### Debug Messages

```
Debug messages go here
```

**Comment by earlephilhower** [comment]
Closing as not containing an MCVE or detailed repro instructions, and >1yr old so MDNS used != current one.
