### ISSUE TITLE
ESP.deepSleep function behavior 

### ISSUE THREAD

**Issue by mhanuel26** [esp8266/Arduino#609]
I notice the following behavior,

when calling the function ESP.deepSleep(sleeptimeout, WAKE_RF_DEFAULT);

it cannot be use in a closing function call or if clause,  you can try the blink example, but call the function blink directly from loop.
Even you cannot put the instruction ESP.deepSleep(tmp, WAKE_RF_DEFAULT); like this 

void loop(){
       print("going to sleep");
       ESP.deepSleep(tmp, WAKE_RF_DEFAULT);
}

The sleep never execute. Instead the esp print to serial at max speed...

My workaround is to do this 

void loop(){
       print("going to sleep");
       ESP.deepSleep(tmp, WAKE_RF_DEFAULT);
       delay(1000);  // the time is not important
}

**Comment by giannoug** [comment]
I'm troubleshooting the same problem. Which board are you using?

Also, the second example you gave is exactly the same as the first one.

**Comment by mhanuel26** [comment]
giannoug,

I have updated the snippet.

**Comment by torntrousers** [comment]
deepSleep seems to take a while to happen after the making the call, about 40 or so milliseconds in tests i've done, and in that time the sketch continues on executing, and it gets confused if in that time another deepSleep call is executed. So i always add the delay(1000) right after the deepSleep call too.

I suppose it could be handy if the delay(1000) call was inside the ESP.deepSleep function itself.

**Comment by igrr** [comment]
Or better yet, to call `esp_yield();` inside deepSleep (like we now do for `ESP.restart`).

**Comment by garrettmoon** [comment]
Calling yield() didn't work for me, only delay(1000).

**Comment by igrr** [comment]
`esp_yield()`, not `yield()`.

**Comment by garrettmoon** [comment]
Aha, I'm new to this. Is yield not the correct function to call to, uh, yield? That's more of a general question tangentially related to this.

**Comment by igrr** [comment]
That's not the best function naming, admittedly.
`yield()` will return control to OS and then start sketch.

`esp_yield()` is an internal function which will return control to OS. To resume sketch execution again there is another internal function, `esp_schedule()`. These two functions are normally used inside the core.

**Comment by garrettmoon** [comment]
Cool, thank you for the explanation :)
