### ISSUE TITLE
linker script does not put .cc files into flash

### ISSUE THREAD

**Issue by hkahl** [esp8266/Arduino#6096]
In tools/sdk/ld/eagle.app.v6.common.ld.h files matching *.c.o and *.cpp .o are considered. The suffix ".cc" is a also pretty common for c++ files. Currently, if .cc is used somewhere, this code goes to iram by default which is quickly filled and linking fails.

This line in the script makes cpp files go to iram by default:
*.cpp.o(.literal*, .text*)

 I suggest adding a line like this:
*.cc.o(.literal*, .text*)

to the linker script so that .cc file go to flash by default like .cpp files.

**Comment by earlephilhower** [comment]
Seems like a reasonable request.  Do you want to submit a PR?
