### ISSUE TITLE
Problem in FS after updating the core

### ISSUE THREAD

**Issue by lucasromeiro** [esp8266/Arduino#6097]
Hello, I'm using PlatformIO in its latest version. I have now updated to use the Arduino 2.5.1 core to use ESP8266 12-F and now my code does not compile anymore!
Accuses error in FS.
I do not understand why. It worked before updating.
I can not find the problem.
Can someone help me?

Thank you

**Comment by earlephilhower** [comment]
Please use the PIO boards since this is a PIO question, and be sure to supply some code because there's no way for anyone to help without it.
