### ISSUE TITLE
About bootloader.tool

### ISSUE THREAD

**Issue by adoph** [esp8266/Arduino#61]
I download ESP8266 Arduino IDE for Windows version.
When I burn bootloader to ESP 8266 and always get the error message:

Arduino: 1.6.1 (Windows 7), Board: "Generic ESP8266 board"
Error while burning bootloader: missing 'bootloader.tool' configuration parameter
  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

I tried run the IDE on Windows 8.1 and Windows 7 sp1 and get the same error message.
Do you know how to solve this problem?
Thank you!

**Comment by igrr** [comment]
No need to burn the bootloader, it is already in ESP's ROM.
Was discussed is a similar issue: #24.
