### ISSUE TITLE
Eclipse uploading problem [SOLVED]

### ISSUE THREAD

**Issue by lrmoreno007** [esp8266/Arduino#610]
I'm using:
Eclipse for Arduino from http://www.baeyens.it/eclipse/nightly-win.html version win32.2015-07-22_02-06-58.tar.gz
ESP8266/Arduino 1.6.6 compiled recently from the git
ESP8266 ESP-12

And esptool.exe never upload the file and no one output problem. I research the problem and eclipse call to esptool:
C:\Program Files (x86)\arduino\hardware\esp8266com\esp8266/tools/esptool.exe false -cd ck -cb 921600 -cp COM2 -ca 0x00000 -cf C:\Eclipse\workspace\xxx/Release/xxx.bin

The problem is the "false" option and I research this is the option for verbose, but esptool don't have this option "false".

To solve the problem I edit ..\Arduino\hardware\esp8266com\esp8266\boards.txt and insert "nodemcu.upload.verbose=-v"   (I don't know if for other boards it's needed too)

After this change i go to properties of the project, re-apply configuration in Arduino tab and now... 
C:\Program Files (x86)\arduino\hardware\esp8266com\esp8266/tools/esptool.exe -v -cd ck -cb 921600 -cp COM2 -ca 0x00000 -cf C:\Eclipse\workspace\xxx/Release/xxx.bin

Everything go OK     Ouu yeah!!!

If you want i can make a "How to install", everything in the net is very old.

Thanks to all for this great job.

**Comment by Links2004** [comment]
i have make a basic setup doc here:
https://github.com/esp8266/Arduino/blob/esp8266/docs/eclipse/eclipse.md
if you have improvements commits are welcome.
