### ISSUE TITLE
Compiler errors in FS.h using new V2.5.1

### ISSUE THREAD

**Issue by mars000** [esp8266/Arduino#6102]
Hi
I've just upgraded to core V2.5.1 using PlatformIO Espressif 8266 dev/platform v2.1.0

I now get the following compiler errors (I've made no changes to my code). Code compiles fine with previous version of Arduino ESP8266 code V2.5.0

I get the following compiler errors - any help would be appreciated:
![image](https://user-images.githubusercontent.com/19469711/57844476-7b4f0a00-7813-11e9-963c-09f79b434048.png)

**Comment by earlephilhower** [comment]
Please try PR #6101.

**Comment by mars000** [comment]
thanks - got it working. Is there a fix coming in next release ?

btw: casted info[x] from char to uint8_t and it removed compiler errors.
i.e. f.write( ((uint8_t) info[x]) );

**Comment by earlephilhower** [comment]
The bugfix will be out in a week or so, with this and some other fixes included.

**Comment by earlephilhower** [comment]
2.5.2 is out with the fix. Closing.
