### ISSUE TITLE
Wrong data type in core_esp8266_si2c.cpp

### ISSUE THREAD

**Issue by enjoyneering** [esp8266/Arduino#6108]
In Arduino/cores/esp8266/core_esp8266_si2c.cpp there is a wrong data type for variable:

`unsigned int preferred_si2c_clock = 100000;`

max value for unsigned int is 65535 should be unsigned long or uint32_t:

`unsigned long preferred_si2c_clock = 100000;`

**Comment by d-a-v** [comment]
sizeof(int) is 4 (32 bits) on this core.

**Comment by devyte** [comment]
Previous comment is correct: the ESP has a 32bit CPU, not a 16bit CPU.
Closing.
