### ISSUE TITLE
16 byte stack alignment problem in cont_yield() & cont_run()

### ISSUE THREAD

**Issue by mhightower83** [esp8266/Arduino#6150]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in the current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				ESP-12
- Core Version:			2d9253e46c41ef6949759ec028a356917d289831
- Development Env:		Arduino IDE
- Operating System:		Ubuntu

### Settings in IDE

- Module:  			Generic ESP8266 Module
- Flash Mode:			qio
- Flash Size: 		        16MB
- lwip Variant:                   v2 Lower Memory
- Reset Method:		nodemcu
- Flash Frequency:	        40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:              460800

### Problem Description

There is no sketch for this. Just an observation while reading code. I am not sure how I could write a sketch that could force this issue.

I noticed that in the file `cores/esp8266/const.S` the stack pointer was temporarily adjusted to a non-16 byte aligned value. (-24 in `cont_yield()` and -20 in `cont_run()`)  From what I have read so far about Xtensa architecture, it requires the stack pointer be aligned to 16 bytes. Not sure what would happen if an interrupt occurred during this window of time. 

The middle line in each link below has the lines I am referring to:

https://github.com/esp8266/Arduino/blob/2d9253e46c41ef6949759ec028a356917d289831/cores/esp8266/cont.S#L29-L31
https://github.com/esp8266/Arduino/blob/2d9253e46c41ef6949759ec028a356917d289831/cores/esp8266/cont.S#L56-L58
https://github.com/esp8266/Arduino/blob/2d9253e46c41ef6949759ec028a356917d289831/cores/esp8266/cont.S#L97-L99
https://github.com/esp8266/Arduino/blob/2d9253e46c41ef6949759ec028a356917d289831/cores/esp8266/cont.S#L147-L149

**Comment by earlephilhower** [comment]
The hard macro Espressif used only requires 4-byte alignment, not 16.  GCC also happily only aligns to 4 bytes for locals as well.  More advanced cores with additional caches might have the 16 byte limitation, though.
