### ISSUE TITLE
HTTP basic authentication is *missing* for WifiServerSecure 

### ISSUE THREAD

**Issue by slackwaree** [esp8266/Arduino#6183]
Hello,

I am using the latest git version of this library with the **WifiServerSecure** function.

This unlike the standard HTTP webserver **does NOT provide server.authenticate**(www_username, www_password).

**Comment by earlephilhower** [comment]
WiFiServerSecure is a TCP socket connection, not a web server.  You need to use ESP8266WebServerSecure, which does have this method.
