### ISSUE TITLE
is compatible or can be with DOIT NODEMCU ?

### ISSUE THREAD

**Issue by asetyde** [esp8266/Arduino#620]
Hi, seems that this NOdemcu is best quality of "marasma" of board on internet ...
There are on his site accurate description and support .
For Nodemcu 1.0 12e or called v2/v3  .. Support how is it ?

Useful links here : 

http://smartarduino.gitbooks.io/user-manual-for-esp-12e-devkit/content/
http://doit.am

**Comment by asetyde** [comment]
I 've no reply from there bu doit say ok , therefore full compatibility . Be warning on different mask of pin gip etc ..

**Comment by Makuna** [comment]
This seems less like an issue and more like a forum question.

Did you try it?

**Comment by asetyde** [comment]
Yes,  it's true. i hope a reply about who develop hardware support . i close it .
