### ISSUE TITLE
upload.py --trace output

### ISSUE THREAD

**Issue by psytribalogical** [esp8266/Arduino#6236]
### Basic Infos

- [X ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ X] I have tested that the issue is present in current master branch (aka latest git).
- [ X] I have searched the issue tracker for a similar issue.
- [ X] If there is a stack dump, I have decoded it.
- [ X] I have filled out all fields below.

#### Platform

- Hardware:					[Adafruit Huzzah]
- Core Version:			[8b899c1]
- Development Env:		[vMicro]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266]
- Flash Mode:			[dio]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[ck]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

When uploading using the new upload.py with the "--trace parameter", the output is so detailed, to the point that the sketch can take a number of minutes to upload to the board.
I assume this is due to the volume of output / application rendering it (same in command prompt).

**Example Command:** 
%USERPROFILE%\AppData\Local\arduino15\packages\esp8266\tools\python\3.7.2-post1\python "%USERPROFILE%\AppData\Local\arduino15\packages\esp8266\hardware\esp8266\2.5.2/tools/upload.py" --chip esp8266 --port "COM10" --baud "115200" "--trace" version --end --chip esp8266 --port "COM10" --baud "115200" "--trace" write_flash 0x0 "%USERPROFILE%\AppData\Local\Temp\VMBuilds\SPIFFS~1\ESP826~2\Debug/SPIFFS Upload Test.ino.bin" --end

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>

void setup()
{
	pinMode(LED_BUILTIN, OUTPUT);
}


void loop()
{
	digitalWrite(LED_BUILTIN, HIGH);
	delay(500);
	digitalWrite(LED_BUILTIN, LOW);
	delay(500);
}

```

### Debug Messages

```
Debug messages go here
```
**Output from Running Command (first snippet)**
esptool.py v2.6
2.6
esptool.py v2.6
Serial port COM10
Connecting...TRACE +0.000 command op=0x08 data len=36 wait_response=1 timeout=0.100 data=
    0707122055555555 5555555555555555 | ... UUUUUUUUUUUU
    5555555555555555 5555555555555555 | UUUUUUUUUUUUUUUU
    55555555                          | UUUU
TRACE +0.001 Write 46 bytes:
    c000082400000000 0007071220555555 | ...$........ UUU
    5555555555555555 5555555555555555 | UUUUUUUUUUUUUUUU
    5555555555555555 5555555555c0     | UUUUUUUUUUUUU.
TRACE +0.102 Timed out waiting for packet header
.TRACE +0.052 command op=0x08 data len=36 wait_response=1 timeout=0.100 data=
    0707122055555555 5555555555555555 | ... UUUUUUUUUUUU
    5555555555555555 5555555555555555 | UUUUUUUUUUUUUUUU
    55555555                          | UUUU
TRACE +0.003 Write 46 bytes:
    c000082400000000 0007071220555555 | ...$........ UUU
    5555555555555555 5555555555555555 | UUUUUUUUUUUUUUUU
    5555555555555555 5555555555c0     | UUUUUUUUUUUUU.
TRACE +0.005 Read 1 bytes: c0
TRACE +0.000 Read 2 bytes: 0108
TRACE +0.021 Read 1 bytes: 02
TRACE +0.000 Read 92 bytes:
    00070712200000c0 c001080200070712 | .... ...........
    200000c0c0010802 00070712200000c0 |  ........... ...
    c001080200070712 200000c0c0010802 | ........ .......
    00070712200000c0 c001080200070712 | .... ...........
    200000c0c0010802 00070712200000c0 |  ........... ...
    c001080200070712 200000c0         | ........ ...
TRACE +0.002 Received full packet: 01080200070712200000
TRACE +0.002 Received full packet: 01080200070712200000
TRACE +0.002 Received full packet: 01080200070712200000
TRACE +0.002 Received full packet: 01080200070712200000
TRACE +0.002 Received full packet: 01080200070712200000
TRACE +0.002 Received full packet: 01080200070712200000
TRACE +0.002 Received full packet: 01080200070712200000
TRACE +0.002 Received full packet: 01080200070712200000

TRACE +0.002 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5c00f03f
TRACE +0.000 Write 14 bytes: c0000a0400000000005c00f03fc0
TRACE +0.014 Read 1 bytes: c0
TRACE +0.000 Read 11 bytes: 010a0200000000000000c0
TRACE +0.002 Received full packet: 010a0200000000000000
TRACE +0.003 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5800f03f
TRACE +0.000 Write 14 bytes: c0000a0400000000005800f03fc0
TRACE +0.011 Read 1 bytes: c0
TRACE +0.000 Read 11 bytes: 010a020000a000000000c0
TRACE +0.001 Received full packet: 010a020000a000000000
TRACE +0.002 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5400f03f
TRACE +0.000 Write 14 bytes: c0000a0400000000005400f03fc0
TRACE +0.013 Read 1 bytes: c0
TRACE +0.000 Read 11 bytes: 010a020003a600020000c0
TRACE +0.001 Received full packet: 010a020003a600020000
TRACE +0.002 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5000f03f
TRACE +0.000 Write 14 bytes: c0000a0400000000005000f03fc0
TRACE +0.013 Read 1 bytes: c0
TRACE +0.000 Read 11 bytes: 010a02000000a8d60000c0
TRACE +0.002 Received full packet: 010a02000000a8d60000
Chip is ESP8266EX
TRACE +0.003 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5c00f03f
TRACE +0.000 Write 14 bytes: c0000a0400000000005c00f03fc0
TRACE +0.011 Read 1 bytes: c0
TRACE +0.000 Read 11 bytes: 010a0200000000000000c0
TRACE +0.002 Received full packet: 010a0200000000000000
TRACE +0.001 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5800f03f
TRACE +0.001 Write 14 bytes: c0000a0400000000005800f03fc0
TRACE +0.012 Read 1 bytes: c0
TRACE +0.001 Read 11 bytes: 010a020000a000000000c0
TRACE +0.001 Received full packet: 010a020000a000000000
TRACE +0.002 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5400f03f
TRACE +0.001 Write 14 bytes: c0000a0400000000005400f03fc0
TRACE +0.011 Read 1 bytes: c0
TRACE +0.001 Read 11 bytes: 010a020003a600020000c0
TRACE +0.001 Received full packet: 010a020003a600020000
TRACE +0.002 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5000f03f
TRACE +0.000 Write 14 bytes: c0000a0400000000005000f03fc0
TRACE +0.012 Read 1 bytes: c0
TRACE +0.000 Read 11 bytes: 010a02000000a8d60000c0
TRACE +0.001 Received full packet: 010a02000000a8d60000
Features: WiFi
TRACE +0.003 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5000f03f
TRACE +0.001 Write 14 bytes: c0000a0400000000005000f03fc0
TRACE +0.011 Read 1 bytes: c0
TRACE +0.000 Read 11 bytes: 010a02000000a8d60000c0
TRACE +0.001 Received full packet: 010a02000000a8d60000
TRACE +0.002 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5400f03f
TRACE +0.000 Write 14 bytes: c0000a0400000000005400f03fc0
TRACE +0.013 Read 1 bytes: c0
TRACE +0.001 Read 11 bytes: 010a020003a600020000c0
TRACE +0.001 Received full packet: 010a020003a600020000
TRACE +0.002 command op=0x0a data len=4 wait_response=1 timeout=3.000 data=5c00f03f
TRACE +0.000 Write 14 bytes: c0000a0400000000005c00f03fc0
TRACE +0.012 Read 1 bytes: c0
TRACE +0.000 Read 11 bytes: 010a0200000000000000c0
TRACE +0.001 Received full packet: 010a0200000000000000
MAC: 18:fe:34:a6:03:d6

**Comment by earlephilhower** [comment]
Unfortunately, "chatty" (default, no option) and "verbose as all heck" (-trace) are the only two options available in esptool.py.  Unless you're debugging some upload problems, there is no reason to actually use verbose upload.

Closing as there's nothing we can do here, sorry.

**Comment by adavidzh** [comment]
Hi @earlephilhower, like @psytribalogical I have just found out that somehow `--trace` is the default and that means that programming takes 25% longer than usual:
- 10 s: from the Arduino IDE,
- 8 s: from the shell after removing `--trace`, and (just for comparison)
- 6 s: as above and using `--baud 3000000` instead of `--baud 921600`.

Should I edit `boards.txt` directly or is there some way to change this from the Arduino IDE that I have missed?
