### ISSUE TITLE
wifi multi AP is not working and esp-01 is restart automatically  

### ISSUE THREAD

**Issue by kumarmohan7** [esp8266/Arduino#624]
Hi 
  i am using ESP-01 module i used multi AP in previews version its work finely but now i used same program in new updated version multi AP is not work.

problem is take ssid and pass is default change ssid and pass in program cannot changed...

if sum times to send serial.print esp-01 is restart automatically and print sum hex values address is printed in serial terminal...   

please give any ideas recover this types of errors

**Comment by Links2004** [comment]
please retry in last release, 
If it still a problem feel free to reopen.
