### ISSUE TITLE
edit html problem

### ISSUE THREAD

**Issue by praveens-git** [esp8266/Arduino#6243]
Hi,
after uploading fsbrowser example and data folder. I can access through its ip/edit when i try to open filename.htm it works no problem but when try to edit filename.html it doesnot open to editing (even no filehandleread occurs for the file i clicked) it seems that it works with htm and not with html i do know why but please help me out

**Comment by TD-er** [comment]
Try to find places in your code where ".htm" is used and see if one of them is also missing ".html"
