### ISSUE TITLE
I2C Wire.write() always sets first bit after address to 1

### ISSUE THREAD

**Issue by TuxRobotics** [esp8266/Arduino#6255]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:			ESP-12e
- Core Version:		6c5269a74b19c7a0c5889f0f48a31e3cf24bfeda
- Development Env:	Arduino IDE 1.8.5
- Operating System:	Linux 4.15.0-45-generic

### Settings in IDE

- Module:  			Wemos D1 mini r2
- Flash Mode:			?
- Flash Size: 		4MB, 2MB SPIFFS
- lwip Variant:   v2 Higher Bandwidth
- Reset Method:		ck
- Flash Frequency:	?
- CPU Frequency:		160MHz
- Upload Using:		SERIAL
- Upload Speed:   115200

### Problem Description

1. The Wire library always sets the first bit of the first data byte after an address.  The example sketch below is copied directly out of the examples, with the only modification being the addresses and data sent.

2. (Possibly related?) After the STOP is sent, there is an extra negative pulse on the clock line.

The circuit:
The "Wemos D1 mini r2" is connected to an Adafruit CAP1188 board, and I have added pull up resistors.  The board responds to reads with valid data, so I have verified the circuit is correct.
Pinout:
D1 => SCK
D2 => SDA

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Wire.h>
#include <PolledTimeout.h>

#define SDA_PIN 4
#define SCL_PIN 5
const int16_t I2C_MASTER = 0x42;
const int16_t I2C_SLAVE = 0x56 >>1;

void setup() {
  Wire.begin(0x03);
  Wire.setClock(400000);  // use 400 kHz I2C
}

byte x = 0;

void loop() {
  using periodic = esp8266::polledTimeout::periodic;
  static periodic nextPing(1000);

  if (nextPing) {
    Wire.beginTransmission(I2C_SLAVE);
    Wire.write((uint8_t)0);        // sends one byte **The most significant bit is always 1**
    Wire.write((uint8_t)0);        // sends one byte (correct)
    Wire.endTransmission();    // stop transmitting

    x++;
  }
}

```

### Debug Messages

Runs normally, but first bit of the data byte is always set:

![image](https://user-images.githubusercontent.com/37251040/60643650-a05e0300-9de8-11e9-9f55-b4c2bf4e961c.png)

Modifying the code to write any other value for the first data byte results in the first bit always being set. A 

A few more examples:

```cpp
  ...
    Wire.beginTransmission(I2C_SLAVE);
    Wire.write((uint8_t)0xAA);        
    Wire.write((uint8_t)0); 
    Wire.endTransmission();
 ...
```
Produces:
![image](https://user-images.githubusercontent.com/37251040/60643909-6c371200-9de9-11e9-8dd7-daf4b21da808.png)

```cpp
  ...
    Wire.beginTransmission(I2C_SLAVE);
    Wire.write((uint8_t)0x66);        
    Wire.write((uint8_t)0); 
    Wire.endTransmission();
 ...
```
Produces:
![image](https://user-images.githubusercontent.com/37251040/60644017-b6b88e80-9de9-11e9-8243-01cad2cdfacb.png)

And here is a shot with the analog channels enabled to show the ramp rate looks good on each line:

![image](https://user-images.githubusercontent.com/37251040/60644236-4fe7a500-9dea-11e9-8187-b8b1778c5f92.png)

Thanks!

**Comment by TuxRobotics** [comment]
Avoided the issue by using brzo i2c library instead.

**Comment by devyte** [comment]
@TuxRobotics beware brzo, it is GPL, unlike our core. My understanding is that it's ok to use with our core only for personal use, and can't be distributed, because we rely on closed source prebuilt libs that aren't ours, and are therefore incompatible with any GPL.

About the issue, I'm rather surprised that nobody has seen it before. Is there any chance you could investigate our lib and try to find a fix?
