### ISSUE TITLE
WebUpdate sketch and module ESP-01

### ISSUE THREAD

**Issue by folny** [esp8266/Arduino#626]
Hi

You can sketch WebUpdate can also use the module with ESP-01 ?.

**Comment by igrr** [comment]
All ESP-01s I've seen come with 512k flash. At this time, you need at least 1M flash for OTA to work. So unless you change the flash chip on your module, OTA won't be possible.

**Comment by folny** [comment]
Ok Thanks for the reply I thought it 512kB will be a little :-)
