### ISSUE TITLE
GET request with pc name

### ISSUE THREAD

**Issue by GJGits** [esp8266/Arduino#6264]
I'm tryng to perform a GET request using pc name instead of IP, this is the code

```cpp

  HTTPClient http;
  http.begin("http://gjcode-vb:3000/device-info/ip"); // da cambiare con raspberrypi
  int code = http.GET();
  if (code < 0) {
  Serial.printf("[HTTP] GET... failed, error: %s\n", http.errorToString(code).c_str());
  }
  String payload = http.getString();
  http.end();

```

When I use an IP everything work fine, I tried to perform the same get request from a browser and from a smartphone and everything work fine but when I use the request above it gives me a connection refused error

**Comment by Pablo2048** [comment]
Problem is obvious - SDK uses only DNS for name recognition. No NBNS and/or mDNS queries are involved...
