### ISSUE TITLE
Download and write of bin file serially from server

### ISSUE THREAD

**Issue by samyusha** [esp8266/Arduino#6284]
Hello all,

I am able to upload a new .bin file into esp8266 using  ESP8266HTTPUpdate Server lib, but what i need is to download this bin file from the server and send it serially to another microcontroller. How to implement it coz ESP8266HTTPUpdate.update() function downloads and does ota, I just want to download the bin file send it serially. How to do it? if so

Regards.

**Comment by ElectricBeat** [comment]
@samyusha  Are you Got It OTA ?

Please Help Me, I Have Struggle In Same Problem
