### ISSUE TITLE
Eprom useful function

### ISSUE THREAD

**Issue by asetyde** [esp8266/Arduino#629]
this function that i found is useful to copy struct : 

`// EEprom block read & write`

`void eeprom_read_block(uint8_t * data, uint32_t address, size_t len){`
	`int i;`
	`for(i=0; i<len; i++){`
		`data[i] = EEPROM.read(address+i);`
	`}`
`}`

`void eeprom_write_block(uint8_t * data, uint32_t address, size_t len){`
	`int i;`
	`for(i=0; i<len; i++){`
		`EEPROM.write(address+i, data[i]);`
	`}`
	`EEPROM.commit();`
`}`

(if you want to add to example or better to eprom.h/ccp)

**Comment by igrr** [comment]
We have 
```c++
template<typename T> 
T &get(int address, T &t)
```
and
```c++
template<typename T> 
const T &put(int address, const T &t)
```

Which may be used to get/put structs from/to flash.
```c++
struct Settings {
ip_addr remote_ip;
int port;
char password[32];
};

// later
void saveSettings(const Settings& settings) {
   EEPROM.put(0, settings);
}
```

Which is nice because you don't have to use C-casts :)

**Comment by asetyde** [comment]
Thx ;)
