### ISSUE TITLE
Hard resetting via RTS Pin on write

### ISSUE THREAD

**Issue by larrywal** [esp8266/Arduino#6314]
Hi folks - bought some new ESP8266 boards and downloaded NodeMCU drivers.  Every time I try to upload a sketch, I get the attached

I've tried with NodeMCU 0.9 (worked for me before with these boards), NodeMCU 1.0, as well as generic ESP8266.  Same issue every time.  Can somone help me debug?  Writing to Arduino Uno is working fine.

<img width="768" alt="resetRTS" src="https://user-images.githubusercontent.com/43455985/61481547-5b3fe200-a94d-11e9-8f43-703e33df01bb.png">

**Comment by 5chufti** [comment]
yes, where is the problem?
It writes your sketch, verifies ok and with reset via RTS starts it ... ???

**Comment by earlephilhower** [comment]
Yes, everything looks just fine on the screenshot.  After uploading it *always* resets the chip to start the new program running.
