### ISSUE TITLE
AudioFileSourceBuffer.cpp  compile error on Arduino IDE

### ISSUE THREAD

**Issue by Gulfboy** [esp8266/Arduino#6319]
Get the following error trying to compile using Arduino  IDE on win 10 (x86)

C:\Users\Dan\Arduino\libraries\ESP8266Audio-master\src\AudioFileSourceBuffer.cpp:30:23: error: 'class HardwareSerial' has no member named 'printf_P'

   if (!buffer) Serial.printf_P(PSTR("Unable to allocate AudioFileSourceBuffer::buffer[]\n"));

**Comment by earlephilhower** [comment]
You're running a really old version of the ESP8266 core.  Please update to the latest release and all should be well.
