### ISSUE TITLE
Integrate LWIP critical section changes

### ISSUE THREAD

**Issue by earlephilhower** [esp8266/Arduino#6347]
Just a friendly reminder to @d-a-v so the LWIP fixes he's done get pulled into the main repo.  I've gone through and updated the other 3 submodules, and think that (and UMM) are the only ones left...

**Comment by d-a-v** [comment]
Once UMM is merged, I'll make an update for both lwip1 and lwip2

**Comment by devyte** [comment]
umm changes were merged with #6274.
