### ISSUE TITLE
library.properties version number

### ISSUE THREAD

**Issue by porlock** [esp8266/Arduino#6354]
File ESP8266WiFi/library.properties in every release contains information that is a version 1.0, that is confusing.

**Comment by earlephilhower** [comment]
@porlock , how is it confusing?  The `ESP8266WiFi` library is never distributed outside of a release as part of the core install, and is not a port not compatible with the AVR Arduino WiFi shield library (`WiFi`), so I'm not even sure how you'd go about seeing the version without a text editor...

**Comment by earlephilhower** [comment]
Closing.
