### ISSUE TITLE
WiFiClientSecureBearSSL.h & compiler issue

### ISSUE THREAD

**Issue by marcostrullato** [esp8266/Arduino#6361]
Hi all,

I'm having a compiler issue.  

### Basic Infos

- [X ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [X ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [X ] I have filled out all fields below.

#### Platform

- Hardware:					ESP12
- Core Version:			1.8.9 
- Development Env:		Arduino IDE
- Operating System:	        Ubuntu

### Settings in IDE

- Module:  			Wemos D1 mini r2
- Flash Mode:			default
- Flash Size: 		        4MB
- lwip Variant:                   v2 Lower Memory
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	        don't know
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:             [115200

### Problem Description

compiler issue, all on cascade. I've pasted the beginning...

Arduino: 1.8.9 (Linux), Board: "LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), 4M (no SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

Build options changed, rebuilding all
Multiple libraries were found for "WiFiUdp.h"
In file included from /home/marco/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WiFi/src/WiFiClientSecure.h:41:0,
 Used: /home/marco/opt/arduino-1.8.9/libraries/WiFi
 Not used: /home/marco/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WiFi
                 from /home/marco/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WiFi/src/WiFiServerSecure.h:20,
                 from /home/marco/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WiFi/src/ESP8266WiFi.h:41,
                 from /home/marco/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WebServer/src/ESP8266WebServer.h:29,
                 from /home/marco/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WebServer/src/Parsing.cpp:25:
/home/marco/.arduino15/packages/esp8266/hardware/esp8266/2.5.2/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:258:36: error: expected ')' before '*' token
     WiFiClientSecure(ClientContext *client, const X509List *chain, unsigned cert_issuer_key_type,

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

These are my includes:

#include <Adafruit_BMP085.h>
#include <DNSServer.h>
#include <ESP8266WiFi.h>
#include <EEPROM.h>
#include <ESP8266WebServer.h>
#include <ESP8266HTTPClient.h>
#include <ESP8266httpUpdate.h>
#include <NTPClient.h>
#include <PubSubClient.h>
#include <stdlib.h>
#include <WiFiClient.h>
#include <WiFiUdp.h>
#include <Wire.h>
#include "msiot4.h"
```

### Debug Messages

```
Debug messages go here
```

**Comment by earlephilhower** [comment]
You have a set of Arduino Ethernet shield libraries installed, like the warning message says.  They are incompatible with the ESP8266.  Remove them to avoid the warning and later errors.
