### ISSUE TITLE
problem whit program

### ISSUE THREAD

**Issue by programnoober** [esp8266/Arduino#6375]
![Knipsel1](https://user-images.githubusercontent.com/53604760/62361833-148ce300-b51c-11e9-85c2-02859c5d7616.PNG)
I
![IMG_0541](https://user-images.githubusercontent.com/53604760/62361759-ec9d7f80-b51b-11e9-82c7-1134ab1cd5ec.JPG)
 bought the wifi-shield esp-wroom-02. I want to connect it whit my phone but i tryed several programs to test it but the program arduino IDE gif me always a error that says that failed to connect to ESP8266: Timed out waiting for packet header. I don't know what I need to do for to make sure the connecting don't failed and which program I need to use? Can someone help me?

**Comment by d-a-v** [comment]
Check your shield documentation. The two blue jumpers probably have a "programmation" mode.

**Comment by programnoober** [comment]
I just tried several combinations of the blue jumpers but I still get that error. or the error that my port didn't work when i set the first switch different.

**Comment by devyte** [comment]
@programnoober this is not a support forum, this is an issue tracker, meant for tracking issues in the core. Please seek help at a forum like esp8266.com or stackoverflow.
Closing.
