### ISSUE TITLE
Suggestion: Flash size 1M by default

### ISSUE THREAD

**Issue by dimitre** [esp8266/Arduino#6379]
Suggestion. I have about 80 different ESP-01 modules and they are all 1Mb flash.
As Arduino IDE has 512kb as default sometimes I upload with the wrong configuration and I'm not able to do updates over the air.
I think most of them are at least 1Mb so what about having this as the default Flash Size option?
Thank you

**Comment by d-a-v** [comment]
This should be already the case in git master.
Default flash size for esp8266 generic board should be:
`1MB (FS:64KB OTA:~470KB)`

**Comment by dimitre** [comment]
Yes! thank you
