### ISSUE TITLE
no headers files (.h) found in C:\Program Files (x86)\Arduino\libraries\libraries

### ISSUE THREAD

**Issue by yashmadankar** [esp8266/Arduino#6388]
when I'm compiling a sketch the error is occurring "Invalid library found in C:\Program Files (x86)\Arduino\libraries\libraries: no headers files (.h) found in C:\Program Files (x86)\Arduino\libraries\libraries". 

what should I do plz help

**Comment by devyte** [comment]
The error tells you what is wrong: libraries/libraries. You have some kind of bad installation.
This is not a support forum, this is an issue tracker. Please seek further help at esp8266.com or stackoverflow.
