### ISSUE TITLE
Timing Issues with WiFiClientSecureBearSSL

### ISSUE THREAD

**Issue by Bytestrike** [esp8266/Arduino#6415]
Hey, 
I'm currently developing with an self-made ESP8266 Board. I implemented a way to publish different Values over MQTT with PubSubClient.
Now I've encountered and issue with the `publish()` function from PubSubClient, which in itself uses WiFiClientSecureBearSSL.cpp

When publishing the timing between the device and broker seems off (a lot of re-transmitted Packages from the Broker) so the Device just waits for a few seconds after handshake before finally publishing the package. 
I've fixed it by adding `delay(10);` in [this](https://github.com/esp8266/Arduino/blob/adfc28d7d8a8c97ecfc8aed0a5fff66e4e61c3c5/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.cpp#L443) Line after the yield. 

I don't hink it's a Bug and probably just an issues I specifically have with my hardware, but I wanted to share it...

**Comment by earlephilhower** [comment]
Without some sort of MCVE, there's nothing we can do here.  The handshake does take a few seconds, but after that the encryption is not nearly as CPU intensive so shouldn't have much impact on actual throughput.  AES is relatively straightforward.

Closing
