### ISSUE TITLE
Build consumes a lot of time by recompiling unchanged core library files every other run

### ISSUE THREAD

**Issue by dok-net** [esp8266/Arduino#6416]
It has been found that when using ESP8266 Arduino from git, not the packaged version available through Arduino board manager, every other build causes a recompilation of many sources files in "core libraries".
Thanks to the kind analysis of this problem by the Visual Micro support team, the issue could be tracked down to tools/makecorever.py constantly recreating core_version.h.
This is fixed by PR #6414

**Comment by earlephilhower** [comment]
Closing since the associated PR has been merged.
