### ISSUE TITLE
collectHeaders doesn't support repeated names

### ISSUE THREAD

**Issue by lgg2** [esp8266/Arduino#6433]
Hello,

With a M5Stack grey (ESP32)

I am trying to recovery the cookies from a server that send three lines of "Set-Cookie"

> Set-Cookie: LoginError=0; Expires=Thu, 01 Jan 1970 01:00:00 CET; Max-Age=0; Path=/; Version="1"
Set-Cookie: setInitVars=1; Expires=Tue, 19 Jan 2038 04:13:43 CET; Max-Age=10; Path=/; Version="1"
Set-Cookie: pksession=11670; Expires=Tue, 19 Jan 2038 04:13:43 CET; Max-Age=600; Path=/; Version="1"

But `collectHeaders` only saves the last one.

``` C/C++
HTTPClient http;
.
.
const char *hdrs[] = {"Set-Cookie","Set-Cookie","Set-Cookie"};
size_t numhdrs = sizeof(hdrs)/sizeof(char*);
.
.
http.collectHeaders(hdrs, numhdrs);
.
.
printf("%s\n%s\n%s\n", http.header((size_t) 0).c_str()), http.header((size_t) 1).c_str()), http.header((size_t) 2).c_str()));
```
Prints only
```
Set-Cookie: pksession=11670; Expires=Tue, 19 Jan 2038 04:13:43 CET; Max-Age=600; Path=/; Version="1"
```

**Comment by earlephilhower** [comment]
You're posting in the wrong core for the ESP32.  Please try https://github.com/espressif/arduino-esp32/
