### ISSUE TITLE
Update espressif binaries for DOS protection

### ISSUE THREAD

**Issue by earlephilhower** [esp8266/Arduino#6436]
See https://github.com/esp8266/Arduino/issues/6016#issuecomment-522591603

**Comment by partofthething** [comment]
Related vulns have remote-takeover proofs-of-concept now in the wild: https://github.com/Matheus-Garbelini/esp32_esp8266_attacks

Some discussion (on top of Hacker News): https://news.ycombinator.com/item?id=20867758

**Comment by Matheus-Garbelini** [comment]
The master is already updated against the beacon crash. Only the stable release 2.5.2 is still vulnerable.

**Comment by earlephilhower** [comment]
@d-a-v, this seems closed to me.  If not, please reopen.
