### ISSUE TITLE
Support to store files locally on the ESP8266

### ISSUE THREAD

**Issue by mazloumi** [esp8266/Arduino#645]
Hi, I was wondering if there is support to store files on the ESP itself like it is possible in the NodeMCU firmware. Interesting enough I first used the NodeMCU firmware and uploaded some files. Then I flashed the device with an application I wrote in Arduino. Then I went back to NodeMCU and the files I uploaded were still there. I assume different address spaces are used? How much space has the ESP to store firmware and other files? Can we support files with the Arduino IDE on the ESP itself?

**Comment by igrr** [comment]
Yes, both storing and uploading are features in progress.

**Comment by mazloumi** [comment]
When do you expect a release? Also, how much space is available on the ESP for firmware and other files?

**Comment by far5893** [comment]
i suppose that in staging is supported spiffs

**Comment by igrr** [comment]
Available in staging:
http://arduino.esp8266.com/versions/1.6.5-1160-gef26c5f/doc/reference.html#file-system
