### ISSUE TITLE
OTA updation error

### ISSUE THREAD

**Issue by wounder123** [esp8266/Arduino#6468]
OTA updation error from https server address:ESP8266
ARDUINO serial window::::::

Connection: close
x-ESP8266-STA-MAC: A0:20:A6:14:F7:CC
x-ESP8266-AP-MAC: A2:20:A6:14:F7:CC
x-ESP8266-free-space: 3870720
x-ESP8266-sketch-size: 301280
x-ESP8266-sketch-md5: 97f5e2566e973e5d0327bf535fd30496
x-ESP8266-chip-size: 4194304
x-ESP8266-sdk-version: 3.0.0-dev(c0f7b44)
x-ESP8266-mode: sketch

[HTTP-Client][handleHeaderResponse] RX: 'HTTP/1.1 400 Bad Request'
[HTTP-Client][handleHeaderResponse] RX: 'Date: Wed, 28 Aug 2019 04:46:49 GMT'
[HTTP-Client][handleHeaderResponse] RX: 'Server: Apache'
[HTTP-Client][handleHeaderResponse] RX: 'Content-Length: 483'
[HTTP-Client][handleHeaderResponse] RX: 'Connection: close'
[HTTP-Client][handleHeaderResponse] RX: 'Content-Type: text/html; charset=iso-8859-1'
[HTTP-Client][handleHeaderResponse] RX: ''
[HTTP-Client][handleHeaderResponse] code: 400
[HTTP-Client][handleHeaderResponse] size: 483
[HTTP-Client][end] still data in buffer (483), clean up.
[HTTP-Client][end] tcp stop
[update] Update failed.
pm open,type:2 0

    ota UPDATION function (i am using )
    WiFiClient client;
     void update_ota()
    {
      Serial.println("OTA RECEIVE OK");

        t_httpUpdate_return retr = ESPhttpUpdate.update(client,"https address");
        delay(100);
        switch (retr)
        {
        case HTTP_UPDATE_FAILED:
        //USE_SERIAL.printf("HTTP_UPDATE_FAILED Error (%d): %s\n", 
       ESPhttpUpdate.getLastError(), ESPhttpUpdate.getLastErrorString().c_str());
     //USE_SERIAL.println(binFile);
     Serial.println("[update] Update failed.");
     break;

     case HTTP_UPDATE_NO_UPDATES:
     //USE_SERIAL.println("HTTP_UPDATE_NO_UPDATES");
     Serial.println("[update] Update no Update.");
      break;

     case HTTP_UPDATE_OK:
     //USE_SERIAL.println("HTTP_UPDATE_OK");
      Serial.println("[update] Update ok.");
       break;
       }
       }

**Comment by devyte** [comment]
Assuming your intent is to update from an https address, you're using a WiFiClient instead of a WiFiSecureClient.
No issue template, no MCVE, lack of details. Closing.
