### ISSUE TITLE
SD Webserver Index File

### ISSUE THREAD

**Issue by charleslin525** [esp8266/Arduino#6473]
I am using the index file from Github: Arduino/libraries/ESP8266WebServer/examples/SDWebServer/SdRoot/edit/.

However, I am not familiar with CSS and HTML. I don't know how I can modify the code, so that the code in index file not display when loading from SD card. All I need is to display the folder and text files.

**Comment by earlephilhower** [comment]
As the form you were requested to fill out said, this is not the spot for general how-to questions.  Please use https://www.esp8266.com or https://gitter.im/esp8266/Arduino for these kinds of general programming questions.
