### ISSUE TITLE
Firebase Stream not working as expected.

### ISSUE THREAD

**Issue by kalyan123143** [esp8266/Arduino#6480]
Firebase.available() is not working and returning a bunch of stack on serial moniter.
 The decoded stack error is as follows:
Exception 28: LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads
PC: 0x40208eee: FirebaseArduino::available() at C:\Users\kallu\OneDrive\Documents\Arduino\libraries\firebase-arduino-master\src\FirebaseArduino.cpp line 134
0x40201118: loop() at C:\Users\kallu\OneDrive\Documents\Arduino\sketch_feb27a/sketch_feb27a.ino line 29
0x40206188: loop_wrapper() at C:\Users\kallu\OneDrive\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_main.cpp line 125
EXCVADDR: 0x00000000

Decoding stack results
0x40201118: loop() at C:\Users\kallu\OneDrive\Documents\Arduino\sketch_feb27a/sketch_feb27a.ino line 29
0x40206188: loop_wrapper() at C:\Users\kallu\OneDrive\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.5.2\cores\esp8266\core_esp8266_main.cpp line 125

what is happening?? im trying to check whether my firebase database is getting updated or not.

**Comment by earlephilhower** [comment]
You've completely ignored the template provided, supplied no reproduction code, and asked a general question about a 3rd party library.  I suggest filling out the requested info in that library's repo, or going to https://esp8266.com or https://gitter.im/esp8266/Arduino for support.
