### ISSUE TITLE
Send audio streaming from NodeMCU to Firebase

### ISSUE THREAD

**Issue by chathuravithakshana** [esp8266/Arduino#6481]
I need to send audio stream as .wav format from NodeMCU (microphone is attached) to Firebase, so that later it can be access to Firebase and streaming stored .wav to Android app. So first I need to know how to send audio stream continuously from NodeMCU (microphone is attached) to Firebase? Any help is highly appreciate.

**Comment by d-a-v** [comment]
You can use `WiFiClient` to establish a TCP connection to a TCP server, and `client.write()` to it.
Or `WiFiUdp`  for UDP connections.
Check examples in `ESP8266WiFi` library on how to use them, and official arduino documentation on the base the class `Client`.
This is not an issue, so I suggest going to https://esp8266.com or https://gitter.im/esp8266/Arduino for more help.

**Comment by chathuravithakshana** [comment]
thank u @d-a-v
