### ISSUE TITLE
migrating from 2.4.2 to 2.5.x cause esp crash when calling attachInterrupt function on GPIO0

### ISSUE THREAD

**Issue by OmarAlkassab** [esp8266/Arduino#6499]
after update of the core from 2.4.2 to 2.5.x, the esp always restart when calling the attachInterrupt function.
Anyone have face similar issue?
The code is still running on 2.4.2!

**Comment by earlephilhower** [comment]
See #6142 and the documentation.  IRQ handlers need to be in IRAM, if not the core will panic().

**Comment by OmarAlkassab** [comment]
Thank you dear, solved
