### ISSUE TITLE
2.5.3 release

### ISSUE THREAD

**Issue by cziter15** [esp8266/Arduino#6502]
@igrr @devyte 

Due to important fix #6484  maybe it is worth to release current git version as 2.5.3-beta or something, so it can be reached via Arduino Boards Manager?

It is also worth to add in release notes, that 22y SDK is much more stable.

**Comment by Jason2866** [comment]
A good reason too https://github.com/esp8266/Arduino/issues/6436#issuecomment-528192690

**Comment by earlephilhower** [comment]
Pushing betas out on the Arduino channel causes difficulty, because the ide will take it as an "update" and Dolls will install it without looking.

That said, 2.6 official is getting close so it's not going to be a great wait...

**Comment by Jason2866** [comment]
Mhh, dont call it beta. 
2.5.3 will be better than 2.5.2. Since you fixed a lot of issues!
So Dolls will get a better core ;-)

**Comment by devyte** [comment]
We've discussed this internally, and the decision is to go with 2.6.0 next.
Closing.

**Comment by d-a-v** [comment]
Please have a look to experimental snapshot page https://d-a-v.github.io/
