### ISSUE TITLE
Wdt reset in function attachInterrupt() 

### ISSUE THREAD

**Issue by kosmonavtX** [esp8266/Arduino#6515]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12E]
- Core Version:			[2.5.2]
- Development Env:		[Platformio]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[ck]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[Serial]
- Upload Speed:   [115200]

### Problem Description

On versions 2.5.2, 2.5.1, the watchdog is triggered in the attachInterrupt () function.
In version 2.5.0, everything works well.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>

class cCosmoiler
{
private:
.......
     static void SensorSpeed();
......
}

void cCosmoiler::begin(uint8_t speed_pin, uint8_t pin1, uint8_t pin2, AESCrypt *l_paes, Dashboard *_tele)
{
	p_setting = new Settings();
	p_setting->LoadMode();
	p_setting->LoadConfig();

	noInterrupts();
        Serial.print("Int 1\r\n");
	attachInterrupt(speed_pin, SensorSpeed, FALLING);
	interrupts();
}

void setup() {
.....
    cCosmoiler::instance()->begin(4, PUMP_C1A, PUMP_C1B, &aes, &telemetry);
.....
}

void loop() {
........
}

```

### Debug Messages

```
......
Int 1
 ets Jan  8 2013,rst cause:4, boot mode:(3,1)
wdt reset
load 0x4010f000, len 1384, room 16 

```

**Comment by d-a-v** [comment]
try with
```
ICACHE_RAM_ATTR
void cCosmoiler::SensorSpeed() {
  code...
}
```

(it's documented)
