### ISSUE TITLE
Git checkout of libraries/SoftwareSerial does fail with VSC/

### ISSUE THREAD

**Issue by Jason2866** [esp8266/Arduino#6527]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:			NodeMCU
- Core Version:			[latest git hash]
- Development Env:		[VSC / Platformio]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266]
- Flash Mode:			[DOUT]
- Flash Size: 		[1MB]
- lwip Variant:   [v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200]

### Problem Description

Compiling fails with this error:

```
error: Server does not allow request for unadvertised object dd9d2326f85a22ca96ef5922df044884a2f3b529
Fetched in submodule path 'libraries/SoftwareSerial', but it did not contain dd9d2326f85a22ca96ef5922df044884a2f3b529. Direct fetching of that commit failed.
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/esp8266/Arduino.git', 'C:\\Users\\Hans\\.platformio\\packages\\_tmp_installing-mxlx8k-package']
```

**Comment by bertmelis** [comment]
Although the issue's contents is not like it should, I face the sale issue. Checking out using Platformio doesn't work because of software serial submodule hash mismatch.

**Comment by d-a-v** [comment]
You can rename the `libraries/SoftwareSerial` directory (I'd remove it) and retry,
git should restore it to the good version.

**Comment by d-a-v** [comment]
fixed by #6526

**Comment by Jason2866** [comment]
Thx for the quick fix!!

**Comment by d-a-v** [comment]
Maybe @dok-net has mistakenly removed the previous submodule reference
