### ISSUE TITLE
Issue downloading the link copied to preferences as shown in boards manager

### ISSUE THREAD

**Issue by Sabakalsoom** [esp8266/Arduino#6535]
When i paste the link into the other boards URL preferences, board manager doesn't show ESP8266 and the following error shows up.

![image](https://user-images.githubusercontent.com/49126976/65220996-76f27080-dad5-11e9-9b1c-f130e6c0c5c9.png)

Please give a feedback on this issue.

**Comment by d-a-v** [comment]
https://github.com/esp8266/Arduino#quick-links > Installing > Boards Manager
gives:
https://arduino.esp8266.com/stable/package_esp8266com_index.json

**Comment by Sabakalsoom** [comment]
> https://arduino.esp8266.com/stable/package_esp8266com_index.json

I did use the same link in the other boards manager URL, still the same error shows up.

**Comment by d-a-v** [comment]
I assume clicking on the above link with the browser works and shows the json file.
Try reinstalling arduino from scrach, after having [properly removed all previous installations](https://forum.arduino.cc/index.php?topic=362507.0) then following [this process](https://arduino-esp8266.readthedocs.io/en/2.5.2/installing.html#boards-manager).

**Comment by Sabakalsoom** [comment]
> I assume clicking on the above link with the browser works and shows the json file.
> Try reinstalling arduino from scrach, after having [properly removed all previous installations](https://forum.arduino.cc/index.php?topic=362507.0) then following [this process](https://arduino-esp8266.readthedocs.io/en/2.5.2/installing.html#boards-manager).

Got it right. Thank you!
