### ISSUE TITLE
Scan networks for specific SSID

### ISSUE THREAD

**Issue by happytm** [esp8266/Arduino#6547]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ x] I have tested that the issue is present in current master branch (aka latest git).
- [ x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[latest git hash]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

I am trying to scan network for specific SSID but I can not do it. I do not know what parameter I have to use to limit scan to only one SSID. I was able to scan for specific channel using following statement but in my location there are few AP's with same channel number and I wanted to avoid scanning all those to speed up scanning. 

int n = WiFi.scanNetworks(true, true, 7); 

Please anyone have solution?

Thanks

**Comment by devyte** [comment]
https://github.com/esp8266/Arduino/blob/69f3e81fb9a1ddb1e0bd5fc3266057dd756a29ae/libraries/ESP8266WiFi/src/ESP8266WiFiScan.h#L37

Please don't ask support questions here, this is an issue tracker, not a support forum. The very first line of the issue template you saw when opening this issue explicitly instructs not to ask "How do I" type questions here.
Closing due to non compliance.
