### ISSUE TITLE
OTA Flash Says Not Enough Space

### ISSUE THREAD

**Issue by weswitt** [esp8266/Arduino#6549]
### Basic Infos

- [x ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x ] I have tested that the issue is present in current master branch (aka latest git).
- [x ] I have searched the issue tracker for a similar issue.
- [x ] If there is a stack dump, I have decoded it.
- [x ] I have filled out all fields below.

#### Platform

- Hardware:					[Wemos D1 Mini]
- Core Version:			[2.5.2]
- Development Env:		[Arduino IDE 1.8.9]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module|Wemos D1 mini r2|Nodemcu|other]
- Flash Mode:			[dio]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v2 Lower Memory]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[OTA]
- Upload Speed:   [115200]

### Problem Description

Attempting an OTA update I get the error message:

09:42:58 [INFO]: Upload size: 5113700
09:42:58 [INFO]: Sending invitation to: 192.168.1.182
09:42:58 [ERROR]: Bad Answer: ERR: ERROR[4]: Not Enough Space

In reading the docs at https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html#update-process-memory-view it seems there should be enough space.

The Wemod D1 has a 4mb flash and I'm using 1mb for SPIFFS. The SPIFFS area starts at 0x300000 which leaves 3mb for the sketch. So for OTA that is 1.5mb for each OTA sketch. My sketch is only 511kb so there should be plenty of space.

What am I missing?

**Comment by devyte** [comment]
5113700 is 5.1MB, not 511KB.
Closing.
