### ISSUE TITLE
UDP packet not sent before deepsleep

### ISSUE THREAD

**Issue by gdpl** [esp8266/Arduino#658]
I code like this:

void loop ()
....

  WiFi.begin(ssid, pass);
  while (WiFi.status() != WL_CONNECTED) {
     delay(100);
   }
   udp.beginPacket(dataServer, 555);
  udp.write(packetBuffer, (bpos));
  udp.endPacket();   
  delay(1000);
  ESP.deepSleep(30000000)
}  //end of loop

Everything was OK before one of my last update (due ADC_MODE(ADC_VCC) did not compile).

Now module connects to wifi, udp.write and udp.endPacket return proper values (1 and buffersize), but no data are received by router and before module goes sleep.

If I change delay to 2000ms, watchdog restarts module before it  goes deepsleep and ...  udp packet is received properly.

**Comment by Links2004** [comment]
please retry in last release, 
If it still a problem feel free to reopen.
