### ISSUE TITLE
HelloServerBearSSL example. Expected type-specifier error while compiling

### ISSUE THREAD

**Issue by Roman1820** [esp8266/Arduino#6596]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				Wemos D1 R1
- Core Version:			latest git hash
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			Wemos D1 R1
- Flash Mode:			
- Flash Size: 		4MB/3MB
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   115200

### Problem Description

When I try to run the example HelloServerBearSSL I get the message: exit status 1 expected type-specifier pointed to the line: server.getServer().setRSACert(new BearSSL::X509List(serverCert), new BearSSL::PrivateKey(serverKey)); 

### Debug Messages

In file included from D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer.h:214:0,

                 from D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServerSecure.h:22,

                 from D:\Users\User\Arduino\Scetches\HelloServerBearSSL\HelloServerBearSSL.ino:14:

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In member function 'String esp8266webserver::ESP8266WebServerTemplate<ServerType>::_extractParam(String&, const String&, char) const':

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:117:12: error: 'emptyString' was not declared in this scope

     return emptyString;

            ^

In file included from D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer.h:214:0,

                 from D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServerSecure.h:22,

                 from D:\Users\User\Arduino\Scetches\HelloServerBearSSL\HelloServerBearSSL.ino:14:

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In member function 'void esp8266webserver::ESP8266WebServerTemplate<ServerType>::_streamFileCore(size_t, const String&, const String&)':

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:542:26: error: 'emptyString' was not declared in this scope

   send(200, contentType, emptyString);

                          ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In member function 'const String& esp8266webserver::ESP8266WebServerTemplate<ServerType>::arg(String) const':

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:556:10: error: 'emptyString' was not declared in this scope

   return emptyString;

          ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In member function 'const String& esp8266webserver::ESP8266WebServerTemplate<ServerType>::arg(int) const':

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:563:10: error: 'emptyString' was not declared in this scope

   return emptyString;

          ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In member function 'const String& esp8266webserver::ESP8266WebServerTemplate<ServerType>::argName(int) const':

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:570:10: error: 'emptyString' was not declared in this scope

   return emptyString;

          ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In member function 'const String& esp8266webserver::ESP8266WebServerTemplate<ServerType>::header(String) const':

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:598:10: error: 'emptyString' was not declared in this scope

   return emptyString;

          ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In member function 'const String& esp8266webserver::ESP8266WebServerTemplate<ServerType>::header(int) const':

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:617:10: error: 'emptyString' was not declared in this scope

   return emptyString;

          ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In member function 'const String& esp8266webserver::ESP8266WebServerTemplate<ServerType>::headerName(int) const':

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:624:10: error: 'emptyString' was not declared in this scope

   return emptyString;

          ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In member function 'void esp8266webserver::ESP8266WebServerTemplate<ServerType>::_finalizeResponse()':

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:691:17: error: 'emptyString' was not declared in this scope

     sendContent(emptyString);

                 ^

In file included from D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServerSecure.h:22:0,

                 from D:\Users\User\Arduino\Scetches\HelloServerBearSSL\HelloServerBearSSL.ino:14:

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer.h: In instantiation of 'class esp8266webserver::ESP8266WebServerTemplate<BearSSL::WiFiServerSecure>':

D:\Users\User\Arduino\Scetches\HelloServerBearSSL\HelloServerBearSSL.ino:25:39:   required from here

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer.h:79:53: error: no type named 'ClientType' in 'class BearSSL::WiFiServerSecure'

   using ClientType = typename ServerType::ClientType;

                                                     ^

D:\Users\User\Arduino\Scetches\HelloServerBearSSL\HelloServerBearSSL.ino: In function 'void setup()':

HelloServerBearSSL:132:37: error: expected type-specifier

   server.getServer().setRSACert(new BearSSL::X509List(serverCert), new BearSSL::PrivateKey(serverKey));

                                     ^

HelloServerBearSSL:132:72: error: expected type-specifier

   server.getServer().setRSACert(new BearSSL::X509List(serverCert), new BearSSL::PrivateKey(serverKey));

                                                                        ^

In file included from D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer.h:214:0,

                 from D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServerSecure.h:22,

                 from D:\Users\User\Arduino\Scetches\HelloServerBearSSL\HelloServerBearSSL.ino:14:

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In instantiation of 'void esp8266webserver::ESP8266WebServerTemplate<ServerType>::send(int, const char*, const String&) [with ServerType = BearSSL::WiFiServerSecure]':

D:\Users\User\Arduino\Scetches\HelloServerBearSSL\HelloServerBearSSL.ino:86:66:   required from here

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:438:5: error: using invalid field 'esp8266webserver::ESP8266WebServerTemplate<ServerType>::_currentClient'

     _currentClient.write((const uint8_t *)header.c_str(), header.length());

     ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h: In instantiation of 'void esp8266webserver::ESP8266WebServerTemplate<ServerType>::handleClient() [with ServerType = BearSSL::WiFiServerSecure]':

D:\Users\User\Arduino\Scetches\HelloServerBearSSL\HelloServerBearSSL.ino:147:23:   required from here

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:314:20: error: using invalid field 'esp8266webserver::ESP8266WebServerTemplate<ServerType>::_currentClient'

     _currentClient = client;

                    ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:322:3: error: using invalid field 'esp8266webserver::ESP8266WebServerTemplate<ServerType>::_currentClient'

   if (_currentClient.connected()) {

   ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:329:7: error: using invalid field 'esp8266webserver::ESP8266WebServerTemplate<ServerType>::_currentClient'

       if (_currentClient.available()) {

       ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:330:41: error: using invalid field 'esp8266webserver::ESP8266WebServerTemplate<ServerType>::_currentClient'

         if (_parseRequest(_currentClient)) {

                                         ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:330:41: error: '_parseRequest' was not declared in this scope

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:331:11: error: using invalid field 'esp8266webserver::ESP8266WebServerTemplate<ServerType>::_currentClient'

           _currentClient.setTimeout(HTTP_MAX_SEND_WAIT);

           ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:335:11: error: using invalid field 'esp8266webserver::ESP8266WebServerTemplate<ServerType>::_currentClient'

           if (_currentClient.connected()) {

           ^

D:\Users\User\Arduino\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:358:20: error: using invalid field 'esp8266webserver::ESP8266WebServerTemplate<ServerType>::_currentClient'

     _currentClient = ClientType();

                    ^
exit status 1
expected type-specifier

**Comment by devyte** [comment]
You most likely have an installation issue. CI guards against build errors like this, so confidence is high that this isn't a core issue.
I suggest a complete clean reinstall from scratch of your core, per current install instructions, or you can try the alpha channel install from the IDE for a snapshot of latest git (experimental, identified by v0.0.x).
Closing.

**Comment by Roman1820** [comment]
I have upgraded to IDE 1.8.10 for Windows and got the same error.

**Comment by devyte** [comment]
By reinstall from scratch I meant the core, not the IDE. The IDE has nothing to do with it, it's just a gui and has zero idea about anything.
If you need further help, please ask at a community forum like esp8266.com or stackoverflow, because this isn't a general support forum.

**Comment by Roman1820** [comment]
I upgraded ESP8266 core to 2.5.2 but the error was present.

**Comment by Roman1820** [comment]
I tried to install arduino-master.zip in IDE 1.8.10 for Windows and got the error that the chosen file has no correct libraries. Regardless whether the folder ~/Arduino15 exists or not.

**Comment by pfeerick** [comment]
Go to the board manager (Tools -> Board -> Boards Manager) and _Remove_ the esp8266 package if it's installed. Then re-follow the installation instructions as needed. You can delete the `/Arduino15/packages/esp8266` folder before re-installing the esp8266 board support package if you want to make 100% certain it is a clean re-installed. 

https://arduino-esp8266.readthedocs.io/en/latest/installing.html#instructions
