### ISSUE TITLE
Unused lines of code causing program to crash

### ISSUE THREAD

**Issue by nextguyover** [esp8266/Arduino#6632]
I had a problem where my code would crash after connecting to WiFi. By commenting out functions in my loop, I narrowed down the crash problem to my function that handles LED control. Here I ran into a problem, commenting out each block of code individually, and even a few at once, I wasn't able to prevent the crash. There must be more than one line causing the crash. Commenting out the entire function was the only thing that worked.

The crash info is as follows: rst cause:4, boot mode:(3,6), wdt reset.

After hours of troubleshooting, I was left at the stage where I had the contents of all the if statements and loops and such commented out. Here is what left me utterly confused. Here is an if statement:

```
if(webSocketActive){
    Serial.println("websocket is active, setting brightness");
    analogWrite(LED_BUILTIN, 1024 - lightBrightnessAdjust);
} else {
    //other stuff with more if-statements that are empty
}
```

At this point, if I comment out the analogWrite line, the program works fine. But if I leave it like this, it crashes after connecting to WiFi. (I didn't post my entire program because it is over 1000 lines long).

The baffling part about all this is, webSocketActive is never set to true prior to this point in the code... The Serial.println() never does anything, meaning the ESP definitely doesn't execute the instructions inside the if statement. But, for some inexplicable reason, simply having the analogWrite() uncommented crashes the program, even if it never executes that line.

The other thing. I can fix this issue by putting a Serial.print() in the loop, or by enabling debugging, which would do lots of Serial prints.

Why would this be happening?

**Comment by devyte** [comment]
These are signs of stack or heap corruption. I suggest careful and systemic debugging of your code.
I don't see a core issue. Also, issue is non-compliant. Closing.
