### ISSUE TITLE
OnStart called after wifi disabled

### ISSUE THREAD

**Issue by jj-uk** [esp8266/Arduino#6636]
I've had a look in the code, and the onstart callback is called AFTER wifi is disabled.

Is there a reason for this?  I think it would be better if onstart was called when the code detects an update is pending, e.g. before it shuts off the wifi.

My usecase means when an update is about to start (therefore the module will be 'offline'), I need to send a message over wifi before the update starts.

**Comment by devyte** [comment]
I don't even understand this.
Closing due to non-compliance (template and instructions ignored).

**Comment by jj-uk** [comment]
I'm asking why wifi is disabled just before the onstart callback is called.
