### ISSUE TITLE
ESP8266 post in REST local

### ISSUE THREAD

**Issue by tegusg** [esp8266/Arduino#6638]
i have made a connection from esp8266 to Ubidots and y can send success the string in JSON format that's  correct but when i try change the server to a local server in java don't recibe the JSON in java, in java i have a REST server but whole it's correct because i used with others programs like POSTMAN to POST information and it's working, can you help me to find out the problem? thank you.

`#include <ESP8266HTTPClient.h>
#include <ESP8266WiFi.h>

// Sustituir con datos de nuestra red
const char* ssid     = "SOLARTE";
const char* password = "Jefferson2012";

double var1;
int sensor1;
const double a=0.003;
String Json;

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);     // Initialize the LED_BUILTIN pin as an output
    
   Serial.begin(115200);
    

//coneccion a wifi
  Serial.println("Wifi test!");

  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  Serial.println("WiFi connected");
  Serial.println(WiFi.localIP());

}

// the loop function runs over and over again forever
void loop() {
  sensor1 = analogRead(A0);
  var1 = sensor1*(a);
  digitalWrite(LED_BUILTIN, HIGH);   
  delay(500);                      // Wait for a second
  digitalWrite(LED_BUILTIN, LOW);  // Turn the LED off by making the voltage HIGH
  delay(500);
  Json = "{\"var1\" : "+ String(var1) + "}";
  Serial.println("dato a enviar: "+ Json);
  

 if(WiFi.status()== WL_CONNECTED){   //Check WiFi connection status
 
   HTTPClient http;    //Declare object of class HTTPClient
 
//here i can try change
//http://things.ubidots.com/api/v1.6/devices/prueba/?token=****************************
//http://localhost:8080/RestLocal/app/ws

   http.begin("http://localhost:8080/RestLocal/app/ws");      //Specify request destination
   http.addHeader("Content-Type", "application/json");  //Specify content-type header
 
   int httpCode = http.POST("{\"var1\":"+ String(var1)+"}");   //Send the request
   String payload = http.getString();                  //Get the response payload
 
   Serial.println(httpCode);   //Print HTTP return code
   Serial.println(payload);    //Print request response payload
 
   http.end();  //Close connection
 
 }else{
 
    Serial.println("Error in WiFi connection");   
 
 }
 
  delay(5000);

 
}`

**Comment by devyte** [comment]
@tegusg this is not a general support forum. This is an issue tracker, meant for tracking issues in the core. Please ask such questions at esp8266.com, stackoverflow, or gitter.
Also, issue template was ignored. 
Closing.
