### ISSUE TITLE
Add support for esp_wifi_set_promiscuous_data_len(uint32_t len);

### ISSUE THREAD

**Issue by codemasterPL** [esp8266/Arduino#6652]
# Missing extern void esp_wifi_set_promiscuous_data_len(uint32_t len);

Available in ESP8266_RTOS_SDK-3.2	

Allows to set the promisc buffer length.

**Comment by earlephilhower** [comment]
We don't use the RTOS SDK, we use NONOS.  And only the 2.2.X or the 3.0 NONOS releases.

**Comment by devyte** [comment]
Previous comment is correct. If you need this, first make the request at Espressif's NONOS SDK repo, and request it be backported to the 2.x branch. Once that is done, let us know and we can pick up the updated SDK from their repo.
Closing for now.
