### ISSUE TITLE
Getting more then 128 bytes from wifi_set_promiscuous_rx_cb

### ISSUE THREAD

**Issue by JRWR** [esp8266/Arduino#6658]
Currently I am only able to get 128 Bytes back from wifi_set_promiscuous_rx_cb are there any bypasses currently to get a full datapacket (trying to get FRAMEID: 0, SUBTYPE: 0 Packets) but none are being returned at all from the CB as well. only management packets are getting returned.

**Comment by devyte** [comment]
@JRWR wifi_set_promiscuous_rx_cb() is an SDK API function. While accessible from our core, it isn't part of it. You should ask that at the Espressif NONOS SDK repo. Also, read their API reference doc 2c.
Closing.
