### ISSUE TITLE
Deep Sleep Wake

### ISSUE THREAD

**Issue by lhh31** [esp8266/Arduino#666]
I have had this command working previously. Now it does not wake the ESP8266 into the correct mode. This is using the stable release. I have not tried the staging release.

ESP.deepSleep(25000000, WAKE_RF_DISABLED);

**Comment by gdpl** [comment]
I have the same - Issue 658. After wakeup Wifi connects, but no data transfer.

**Comment by igrr** [comment]
#658 is obviously not the same as this one.
This one is related to RTC memory not being preserved (as in #619), and is fixed in ac459eb.
Fix will be available in the next staging package release.

**Comment by lhh31** [comment]
Merged that patch in and it is working.

**Comment by wb8wka** [comment]
Not working on 2.3.0     WAKE_NO_RFCAL does not disable RF calibration
