### ISSUE TITLE
Captive portal with authentication not working.

### ISSUE THREAD

**Issue by mbm60** [esp8266/Arduino#6662]
Hi
How to use the captive portal with authentication? I used both in one sketch but the captive portal didn't work!

**Comment by mbm60** [comment]
Just close without any explanation or guidance?

**Comment by devyte** [comment]
The reason for closing isnin the issue template, which you completely ignored when opening this:
This is not the place to ask "how do I" type questions. For general support, please refer to a community forum like esp8266.com or stackoverflow.
