### ISSUE TITLE
Call "delay ()" will cause "WDT reset"  in the timer callback function

### ISSUE THREAD

**Issue by chzhewl** [esp8266/Arduino#668]
I Using the "Ticker" class to start a timer, call the "delay (3000)" in the callback function to cause the program to have no response, and after a while, "WDT reset".
Sample code:
#include <Ticker.h>
Ticker test;
void test_callback()
{
  Serial1.println("start");
  delay(3000);  //wdt reset
  Serial1.println("end"); //not print
}
void setup() {
  Serial1.begin(115200);
  test.once(3, test_callback);
}
void loop() {}

**Comment by igrr** [comment]
This is expected behavior. Do not call any blocking functions from Ticker
callbacks.

**Comment by chzhewl** [comment]
tks!

**Comment by romuye123** [comment]
what if i want to use blocking delay()?
what should i use ?
