### ISSUE TITLE
error:  'U_FS' was not declared in this scope

### ISSUE THREAD

**Issue by tung256** [esp8266/Arduino#6683]
my sketch includes "ArduinoOTA.h"
in my library folder, i have ArduinoOTA.h ArduinoOTA.cpp.  when i compile, i get this error:
C:\Program Files (x86)\Arduino\libraries\blinds\ArduinoOTA.cpp:189:34: error: 'U_FS' was not declared in this scope

if (cmd != U_FLASH && cmd != U_FS)

how to resolve this issue?
thanks!

**Comment by devyte** [comment]
Build issues issues like this are covered by CI. You likely have an installation issue.
Closing due to can't reproduce and non-compliant issue (issue template ignored).
