### ISSUE TITLE
WDT Reset on analogRead(A0)

### ISSUE THREAD

**Issue by kevin789900** [esp8266/Arduino#669]
When adding call to analogRead(A0), my esp8266 will intermittently WDT reset typically within 5 minutes.  Commenting out this line I have 15 days of uptime.

``` c
lightSensor=analogRead(A0);
```
##

**Comment by kevin789900** [comment]
related? https://github.com/esp8266/Arduino/issues/391

anyone have problems with analogRead?

**Comment by Johanescobar** [comment]
yo!!! quiero leer un pot con el adc tengo un esp8266-07 e imprimirlo en html me podrias ayudar?

**Comment by devyte** [comment]
I can't reproduce this with latest git. I suggest checking your power supply.
Closing as can't reproduce.
