### ISSUE TITLE
WiFi.RSSI() doesn't work

### ISSUE THREAD

**Issue by kevin789900** [esp8266/Arduino#670]
Any chance this will be supported?

**Comment by Links2004** [comment]
check if you have the latest version.
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp#L385
support is added since 25 May.

**Comment by Juppit** [comment]
Stable Readme still says (ver. 1.6.5-947-g39819f0, built on Jul 23, 
2015) "WiFi.RSSI() doesn't work", also Staging version (ver. 
1.6.5-990-gc8a63ce, built on Aug 03, 2015)

Upps: still in the Documentation for latest development version 
(https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/doc/reference.md)

**Comment by igrr** [comment]
Duh... forgot to edit this out from documentation. Sorry.

**Comment by kevin789900** [comment]
New to github, looks like I have this version of the library as delivered through the Arduino IDE:  1.6.4-673-g8cd3697  Is the library updated to include the RSSI?  How would I tell that via github (sorry for newbie questions)?
