### ISSUE TITLE
NodeMCU Reset and Boot Mode

### ISSUE THREAD

**Issue by JoseeMallah** [esp8266/Arduino#6707]
Hello everyone,
My NodeMCU keeps resetting and rebooting with exceptions and stack errors, so the program keeps getting data from an Adafruit io feed although no new data is added. Can Anyone help me solve this?
Does anyone know if Adafruit handleMessage methods are not affected by global variables changing values?
Thank you.

**Comment by devyte** [comment]
As explained in the issue template, this is not the right place to ask for general help. Please ask at a community forum like esp8266.com or stackoverflow.
Closing.
