### ISSUE TITLE
ECLIPSE: Type 'CLOSED' is ambiguous ' Candidates are: '	ClientContext.h	line 182	

### ISSUE THREAD

**Issue by far5893** [esp8266/Arduino#671]
wl_definitions.h
lwip/tcp.h

Eclipse parser find and error, only ide  parser, compile is fine

arduino 1.6.5 / esp8266 stable release 23Jul
##

**Comment by igrr** [comment]
Perhaps it would make sense to file a bug against Eclipse parser since the
code compiles fine?

**Comment by far5893** [comment]
Or arduino plugin!!

**Comment by Links2004** [comment]
have you something named ```CLOSED``` in your code?
the latest git show me only warnings:
 - reorder
 - sign-compare
 - unused variable
 - unused function

**Comment by far5893** [comment]
No but i suppose that there is something wrong in included library chain , compiler use makefile but i feel that  ide use another logic to parse code

**Comment by Links2004** [comment]
yes build is makefile (created by eclipse), but for some strange reason the indexer sometimes do something different from the makefiles.

**Comment by Links2004** [comment]
see: #525

**Comment by devyte** [comment]
@far5893 @Links2004 this issue is ancient. Is it still valid?

**Comment by far5893** [comment]
On eclipse oxygen and last slober arduino plugin  seem resolved.
