### ISSUE TITLE
Cannot connect to Telegram with WiFiClientSecure using BearSSL, axTLS works ok

### ISSUE THREAD

**Issue by AcuarioCat** [esp8266/Arduino#6716]
### Basic Infos

- [x ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x ] I have filled out all fields below.

#### Platform

- Hardware:					ESP-12
- Core Version:			30-Oct-19
- Development Env:		Visual Studio
- Operating System:		Windows

### Settings in IDE

- Module:  			Wemos D1 mini r2,other
- Flash Mode:			[qio|dio|other]
- Flash Size: 		4MB
- lwip Variant:   v2 Lower Memory|Higher Bandwidth]
- Reset Method:		nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|
- Upload Using:		SERIAL]
- Upload Speed:   [115200

### Problem Description

When using the default (BearSSL) client the device cannot connect to Telegram server,
Using the axTLS implementation works perfectly.

BOT library: https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/tree/V1.2.0

### [MCVE](https://stackoverflow.com/help/mcve) Sketch
#define USING_AXTLS
#include <ESP8266WiFi.h>

// Initialize Wifi connection to the router
char ssid[] = "SSID";     // your network SSID (name)
char password[] = "PASSWORD"; // your network key

// Initialize Telegram BOT
#define BOTtoken "MY TOKEN HERE"  // your Bot Token (Get from Botfather)

//#include <WiFiClientSecure.h>
#include "WiFiClientSecureAxTLS.h"
using namespace axTLS;
#include <UniversalTelegramBot.h>

//WiFiClientSecure client;
WiFiClientSecure client; 
UniversalTelegramBot bot(BOTtoken, client);

int Bot_mtbs = 1000; //mean time between scan messages
long Bot_lasttime;   //last time messages' scan has been done

void setup() {
	Serial.begin(115200);

	// Set WiFi to station mode and disconnect from an AP if it was Previously connected
	WiFi.mode(WIFI_STA);
	WiFi.disconnect();
	delay(100);

	// Attempt to connect to Wifi network:
	Serial.print("Connecting Wifi: ");
	Serial.println(ssid);
	WiFi.begin(ssid, password);

	while (WiFi.status() != WL_CONNECTED) {
		Serial.print(".");
		delay(500);
	}

	Serial.println("");
	Serial.println("WiFi connected");
	Serial.print("IP address: ");
	Serial.println(WiFi.localIP());
}

void loop() {
	if (millis() > Bot_lasttime + Bot_mtbs) {
		int numNewMessages = bot.getUpdates(bot.last_message_received + 1);

		while (numNewMessages) {
			Serial.println("got response");
			for (int i = 0; i < numNewMessages; i++) {
				bot.sendMessage(bot.messages[i].chat_id, bot.messages[i].text, "");
			}
			numNewMessages = bot.getUpdates(bot.last_message_received + 1);
		}

		Bot_lasttime = millis();
	}
}

### Debug Messages
Debug enabled in UniversalTelegramBot.h
```
### Using axTLS:
WiFi connected
IP address: 192.168.0.115
GET Update Messages
[BOT]Call sendGetToTelegram
[BOT]Connecting to server
.... connected to server

{"ok":true,"result":[]}

incoming message length 23
Creating DynamicJsonBuffer
GetUpdates parsed jsonDoc: {"ok":true,"result":[]}
GetUpdates parsed jsonObj: {"ok":true,"result":[]}
no new messages
Closing client

### Using BearSSL:
WiFi connected
IP address: 192.168.0.115
GET Update Messages
[BOT]Call sendGetToTelegram
[BOT]Connecting to server
[BOT]Conection error 0
Received empty string in response!
```

**Comment by devyte** [comment]
The old axTLS works by default in insecure mode. The new bssl changed the default, and now the user has to explicitly call setInsecure() to be fully aware of what is being done.
I see a pending PR at the bot repo with the added call. 
I would suggest not using insecure mode at all, bit figuring out the certs required. 
Whatever else, this is not an issue with the core, but with the telegram 3rd party lib.
BTW, axtls has been deprecated for a while now, and is scheduled to be dropped completely for release v3, which isn't too far away. 
Closing.
