### ISSUE TITLE
[Feature Req] HardwareSerial: Add support for 9 bit UART (9N1, 9N2, 9P1 etc)

### ISSUE THREAD

**Issue by TargoDove** [esp8266/Arduino#6723]
Would it be possible to add support for transmitting 9 bits over UART? I need to use the 9th bit to differentiate between "commands" and "data". It has been done here: https://forum.arduino.cc/index.php?topic=517063.0

Would it be possible to adapt that for the ESP8266 "HardwareSerial" library?

**Comment by devyte** [comment]
I am not 100% sure, but I think the hw doesn't support 9bits (did anqyick search and code lookup) 
SoftwareSerial was recently improved to support 9bits.
Closing due to not an issue.

**Comment by TargoDove** [comment]
@devyte SoftwareSerial doesn't currently support 9bits either. Where would I post a feature request then?

**Comment by devyte** [comment]
Ah, looks like it's still wip, I thought it was done already.
Look at the espsoftwareserial repo, issues/prs etc.
