### ISSUE TITLE
How to set request Headers and Payload in HTTPSRequest.h?

### ISSUE THREAD

**Issue by tecPhoenix** [esp8266/Arduino#6726]

**Comment by Jeroen88** [comment]
ESP8266HTTPClient::addHeader() see [here](https://github.com/esp8266/Arduino/blob/453eb2d0642fd12a73327ee5e8cdad885b014aa6/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h#L193)

ESP8266HTTPClient::POST() see [here](https://github.com/esp8266/Arduino/blob/453eb2d0642fd12a73327ee5e8cdad885b014aa6/libraries/ESP8266HTTPClient/src/ESP8266HTTPClient.h#L183)
