### ISSUE TITLE
NodeMCU disconnects itself after 10 minutes

### ISSUE THREAD

**Issue by pryadav333** [esp8266/Arduino#6729]
Hi,

I am using nodemcu for 8 channel relay with hilink 5 volt power supply to each. My nodemcu automatically disconnects after 10-15 minutes time. I tried  WiFi.setSleepMode(WIFI_NONE_SLEEP); but it did not worked for me. I am using Arduino 1.8.1. Following is my code, kindly suggest to keep nodemcu all time connected and aliive.

**Code I am using**

 ****************************************************/
#include <ESP8266WiFi.h>
#include "Adafruit_MQTT.h"
#include "Adafruit_MQTT_Client.h"

/************************* WiFi Access Point *********************************/

#define WLAN_SSID       "xxxxxxxxxxxx"
#define WLAN_PASS       "xxxxxxxxxxx"

/************************* Adafruit.io Setup *********************************/

#define AIO_SERVER      "io.adafruit.com"
#define AIO_SERVERPORT  1883                   // use 8883 for SSL
#define AIO_USERNAME    "xxxxxxxxxxxx"
#define AIO_KEY         "xxxxxxxxxxxxxxxxxxxxx"

/************ Global State (you don't need to change this!) ******************/

// Create an ESP8266 WiFiClient class to connect to the MQTT server.
WiFiClient client;
// or... use WiFiFlientSecure for SSL
//WiFiClientSecure client;

// Setup the MQTT client class by passing in the WiFi client and MQTT server and login details.
Adafruit_MQTT_Client mqtt(&client, AIO_SERVER, AIO_SERVERPORT, AIO_USERNAME, AIO_KEY);

/****************************** Feeds ***************************************/

// Setup a feed called 'photocell' for publishing.
// Notice MQTT paths for AIO follow the form: <username>/feeds/<feedname>
//Adafruit_MQTT_Publish photocell = Adafruit_MQTT_Publish(&mqtt, AIO_USERNAME "/feeds/photocell");

// Setup a feed called 'onoff' for subscribing to changes.

Adafruit_MQTT_Subscribe R1 = Adafruit_MQTT_Subscribe(&mqtt, AIO_USERNAME "/feeds/R1");
Adafruit_MQTT_Subscribe R2 = Adafruit_MQTT_Subscribe(&mqtt, AIO_USERNAME "/feeds/R2");
Adafruit_MQTT_Subscribe R3 = Adafruit_MQTT_Subscribe(&mqtt, AIO_USERNAME "/feeds/R3");
Adafruit_MQTT_Subscribe R4 = Adafruit_MQTT_Subscribe(&mqtt, AIO_USERNAME "/feeds/R4");
Adafruit_MQTT_Subscribe R5 = Adafruit_MQTT_Subscribe(&mqtt, AIO_USERNAME "/feeds/R5");
Adafruit_MQTT_Subscribe R6 = Adafruit_MQTT_Subscribe(&mqtt, AIO_USERNAME "/feeds/R6");
Adafruit_MQTT_Subscribe R7 = Adafruit_MQTT_Subscribe(&mqtt, AIO_USERNAME "/feeds/R7");
Adafruit_MQTT_Subscribe R8 = Adafruit_MQTT_Subscribe(&mqtt, AIO_USERNAME "/feeds/R8");

/*************************** Sketch Code ************************************/

// Bug workaround for Arduino 1.6.6, it seems to need a function declaration
// for some reason (only affects ESP8266, likely an arduino-builder bug).
void MQTT_connect();

void setup() {
  Serial.begin(115200);
  delay(10);
  pinMode(5, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(0, OUTPUT);
  pinMode(2, OUTPUT);
  pinMode(14, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);
  pinMode(15, OUTPUT);

 
  Serial.println(F("Adafruit MQTT demo"));

  // Connect to WiFi access point.
  WiFi.setSleepMode(WIFI_NONE_SLEEP);  //keeps wifi on all time, consumes more power but supports all bradcasted messages
  Serial.println(); Serial.println();
  Serial.print("Connecting to ");
  Serial.println(WLAN_SSID);
    
  WiFi.begin(WLAN_SSID, WLAN_PASS);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");

   
  }
  Serial.println();

  Serial.println("WiFi connected");
  Serial.println("IP address: "); Serial.println(WiFi.localIP());

  // Setup MQTT subscription for onoff feed.
  mqtt.subscribe(&R1);
  mqtt.subscribe(&R2);
  mqtt.subscribe(&R3);
  mqtt.subscribe(&R4);
  mqtt.subscribe(&R5);
  mqtt.subscribe(&R6);
  mqtt.subscribe(&R7);
  mqtt.subscribe(&R8);

}

uint32_t x=0;

void loop() {
  // Ensure the connection to the MQTT server is alive (this will make the first
  // connection and automatically reconnect when disconnected).  See the MQTT_connect
  // function definition further below.
  MQTT_connect();

  // this is our 'wait for incoming subscription packets' busy subloop
  // try to spend your time here

  Adafruit_MQTT_Subscribe *subscription;
  while ((subscription = mqtt.readSubscription(5000))) {
    if (subscription == &R1) {
      Serial.print(F("Got_R1: "));
      Serial.println((char *)R1.lastread);
      int num = atoi((char *)R1.lastread);
      digitalWrite (5,num);
    }
  
     if (subscription == &R2) {
      Serial.print(F("Got_R2: "));
      Serial.println((char *)R2.lastread);
      int num = atoi((char *)R2.lastread);
      digitalWrite (4,num);
    }

       if (subscription == &R3) {
      Serial.print(F("Got_R3: "));
      Serial.println((char *)R3.lastread);
      int num = atoi((char *)R3.lastread);
      digitalWrite (0,num);
    }

     if (subscription == &R4) {
      Serial.print(F("Got_R4: "));
      Serial.println((char *)R4.lastread);
      int num = atoi((char *)R4.lastread);
      digitalWrite (2,num);
    }

       if (subscription == &R5) {
      Serial.print(F("Got_R5: "));
      Serial.println((char *)R5.lastread);
      int num = atoi((char *)R5.lastread);
      digitalWrite (14,num);
    }

       if (subscription == &R6) {
      Serial.print(F("Got_R6: "));
      Serial.println((char *)R6.lastread);
      int num = atoi((char *)R6.lastread);
      digitalWrite (12,num);
    }

       if (subscription == &R7) {
      Serial.print(F("Got_R7: "));
      Serial.println((char *)R7.lastread);
      int num = atoi((char *)R7.lastread);
      digitalWrite (13,num);
    }

       if (subscription == &R8) {
      Serial.print(F("Got_R8: "));
      Serial.println((char *)R8.lastread);
      int num = atoi((char *)R8.lastread);
      digitalWrite (15,num);
     }
  }

  // Now we can publish stuff! - If you want publishing use the following code
 // Serial.print(F("\nSending photocell val "));
 // Serial.print(x);
 //Serial.print("...");
 // if (! photocell.publish(x++)) {
  //  Serial.println(F("Failed"));
 // } else {
  //  Serial.println(F("OK!"));
 // }

  // ping the server to keep the mqtt connection alive
  // NOT required if you are publishing once every KEEPALIVE seconds
  /*
  if(! mqtt.ping()) {
    mqtt.disconnect();
  }
  */
}

// Function to connect and reconnect as necessary to the MQTT server.
// Should be called in the loop function and it will take care if connecting.
void MQTT_connect() {
  int8_t ret;

  // Stop if already connected.
  if (mqtt.connected()) {
    return;
  }

  Serial.print("Connecting to MQTT... ");

  uint8_t retries = 3;
  while ((ret = mqtt.connect()) != 0) { // connect will return 0 for connected
       Serial.println(mqtt.connectErrorString(ret));
       Serial.println("Retrying MQTT connection in 5 seconds...");
       mqtt.disconnect();
       delay(5000);  // wait 5 seconds
       retries--;
       if (retries == 0) {
         // basically die and wait for WDT to reset me
         while (1);
       }
  }
  Serial.println("MQTT Connected!");
}

**Comment by devyte** [comment]
Off the top of my head, hilink is rated for 0. 6A, which sucks. The ESP has large power spikes, especially when writing to flash or wifi usage. For development I use a 25A power supply to make sure issues aren't power related. For production I use a 2A mini psu.
This is not the right place to ask such questions for general help. This is an issue tracker meant for tracking issues in the core. Please request such help at a community forum like esp8266.com or stackoverflow.
Also, you ignored the issue template and didn't comply with any of the instructions contained in it. 
Closing.
