### ISSUE TITLE
ESP.getCoreVersion() returns ffffffff in core 2.6.0

### ISSUE THREAD

**Issue by marcobrianza** [esp8266/Arduino#6735]
in core 2.5.2 and below was returning a string such 2_5_2

Example:
void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.println(ESP.getCoreVersion());
}

**Comment by d-a-v** [comment]
Thanks for the report, we will fix that in release 2.6.1

**Comment by d-a-v** [comment]
Can you try [my alpha release channel](https://d-a-v.github.io/) to check if this issue is fixed.

**Comment by marcobrianza** [comment]
Yep, got a very detailed 2_6_0_8_G4E5BF118
thank you
Marco

**Comment by marcobrianza** [comment]
Is there a way to get the lwIP version?

**Comment by mikekgr** [comment]
> Is there a way to get the lwIP version?

I think this include IwIP
ESP.getFullVersion();
Thanks

**Comment by d-a-v** [comment]
Fixed by #6747
