### ISSUE TITLE
2.6.0 SPIFFS upload data problem !

### ISSUE THREAD

**Issue by ErfanDL** [esp8266/Arduino#6738]
Hi. the spiff data can not be uploading ! I installed the latest python for windows but not working. any idea to fix ?

`Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640SPIFFS Upload failed!`

**Comment by devyte** [comment]
@ErfanDL please take a moment to gather your thoughts, read what you wrote, and compare that against the instructions in the issue template.
Closing due to not compliant.
