### ISSUE TITLE
2.6.0 Software Serial causes exception when initialized with large buffer (2k buffer)

### ISSUE THREAD

**Issue by egzola** [esp8266/Arduino#6739]
Problem when used large buffer.

ss.begin(57600, rx, tx, false, 2048);

Causes Exception...

In 2.5.0 core  it works fine...

**Comment by bill-orange** [comment]
@egzola See closed issue #6737

**Comment by egzola** [comment]
> @egzola See closed issue #6737

This is not the same issue.

**Comment by devyte** [comment]
@egzola please report at the espsoftwareserial repo, not here. Also, please provide an MCVE as well as context for the usage. The info you provided here is not nearly enough to consider.
Closing.
