### ISSUE TITLE
retrieve bearssl fingerprint

### ISSUE THREAD

**Issue by or78rXxZ** [esp8266/Arduino#6753]
### Basic Infos

- [ x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ x] I have tested that the issue is present in current master branch (aka latest git).
- [ x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:					[Sonoff Dual R2]
- Core Version:			[Release 2.6.0]
- Development Env:		[Arduino IDE]
- Operating System:		[Debian]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[dout]
- Flash Size: 		[1MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[dtr]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200)

### Problem Description
In issue #6209 @earlephilhower said

I added some debugging info to the FP mismatch case, will do a PR later, but the problem is simply the FP doesn't match:
You could either use the BSSL calculated FP ...

I am working on converting my sketches from ax to bear. Is there a sketch available with tis extra debug info that will return the the bear calculated fingerprint? I specifically am trying to get the fingerprint for my mqtt server.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}

```

### Debug Messages

```
Debug messages go here
```

**Comment by earlephilhower** [comment]
Just enable debugging for SSL and you get the dumps to serial.  Or use OpenSSL or any other SSL utility and they can give the FPs as well.

Closing as a general question and not a core issue.
