### ISSUE TITLE
ESP8266SdFat and SDFS linked when not used

### ISSUE THREAD

**Issue by TD-er** [esp8266/Arduino#6760]
Similar to #6691 
The PlatformIO inspect tool shows both libraries `ESP8266SdFat` and `SDFS` are linked in the binary and thus taking both around 20k of flash size. (debug build, release size may differ)

![image](https://user-images.githubusercontent.com/3751318/68658158-34796d00-0535-11ea-8872-b08e2d2a8167.png)

As far as I can see, all includes for `SD.h` in my code are in #ifdef wrappers and I cannot see where the file `SD.h` is included in the code of esp8266/Arduino.

Right now, I am using https://github.com/Jason2866/platform-espressif8266.git#core_2_6_0 as platform (has the latest build toolchain included).

Does any of you have an idea why it is linked?

**Comment by Jason2866** [comment]
Not linked in Tasmota using https://github.com/Jason2866/platform-espressif8266.git#core_2_6_0 as platform
![image](https://user-images.githubusercontent.com/24528715/68660233-0d249f00-0539-11ea-9d85-3cff18f2b2f0.png)

**Comment by TD-er** [comment]
@Jason2866 You are not using SPIFFS in Tasmota, right?

**Comment by Jason2866** [comment]
Ahhh, sorry overlooked (read not exactly...)
It is NOT the SPIFFS / LittleFs stuff. It is about `SDFS` and `ESP8266SdFat`

**Comment by TD-er** [comment]
> It is NOT the SPIFFS / LittleFs stuff. It is about `SDFS` and `ESP8266SdFat`

Yep, but I wanted to check if there may be a link somewhere.
Like I said, I did check the source of this repo also and could not find an include of SD.h

**Comment by d-a-v** [comment]
SDFS.h replaces SD.h

**Comment by TD-er** [comment]
> SDFS.h replaces SD.h

Do you have any idea what these include and if it is needed when you don't use the SD functionality?

**Comment by d-a-v** [comment]
I find none.
Can you copy-paste the linker line, and run it without SDFS library/object files, in the hope the linker will tell where the symbols are missing ?

**Comment by TD-er** [comment]
I just renamed the files `SD.h` and `SDFS.h` so they would not be compiled and then the build completes just fine but without the libraries.

Clean build with the original file names:
![2019-11-13 14_29_45-PIO Home - ESPEasy - Visual Studio Code](https://user-images.githubusercontent.com/3751318/68768791-7a146380-0623-11ea-9a26-701a528d15bf.png)

Clean build with the 2 .h files renamed:
![2019-11-13 14_37_52-PIO Home - ESPEasy - Visual Studio Code](https://user-images.githubusercontent.com/3751318/68768794-7da7ea80-0623-11ea-96f1-de563531596f.png)


So I wonder, what could be wrong here? (maybe this is a PlatformIO bug? Linker bug?)

**Comment by devyte** [comment]
> PlatformIO bug

Maybe retest building with Arduino IDE?

**Comment by TD-er** [comment]
That's easier said than done.
The only way I know I could check then is by comparing sizes.
And is the build toolchain the same?

**Comment by Jason2866** [comment]
@TD-er  Build chain for platformIO used (with my setup for core 2.6.0) is
https://github.com/earlephilhower/esp-quick-toolchain/releases/tag/2.5.0-4

**Comment by TD-er** [comment]
Just as a test, I added those libraries to the platformIO `lib_ignore` list, which does help in no longer including it.
```
lib_ignore                = SD(esp8266), SDFS
```

**Comment by Jason2866** [comment]
In Tasmota the behaviour you have does not occur
![image](https://user-images.githubusercontent.com/24528715/68772421-12ade200-062a-11ea-899b-f3047ae57291.png)

**Comment by Misiu** [comment]
@TD-er adding those libraries to `lib_ignore` is more of a workaround. Maybe this is a bug in PlatformIO or build chain?

**Comment by TD-er** [comment]
@Misiu Yep, I agree.
It was not reported as the final fix, but more to collect data for someone to interpret what may cause this issue.
And it does help me to get the build size down.

This issue (and the one with loosing all available RAM when including SD.h) has already taken a lot of time, so for now it is a quick work-around to make sure I can continue.

**Comment by earlephilhower** [comment]
@TD-er, I think this is probably best handled at the Platform.IO GH site, no?  We're not seeing it on the Arduino IDE builds, and it seems like not everyone with PIO is seeing it, either.

**Comment by TD-er** [comment]
I guess so. I will open one on the PIO github repo
Not sure where it is caused.

At least something is fishy with SD.h, see my other issue.  (which is reproducible in Arduino IDE)

**Comment by earlephilhower** [comment]
OK, I'll close this on the Arduino side.  If something comes up w/PIO and they need Core changes, we can re-open and track.  The SD.h F() problem is repro'd and on its way in #6767 .

**Comment by TD-er** [comment]
Let's first see if this linking is still an issue after the #6767 is fixed and if it is still an issue, I will add an issue on PIO's issues list for it.
