### ISSUE TITLE
using schedule_function() within scheduled function prevents loop from running

### ISSUE THREAD

**Issue by hreintke** [esp8266/Arduino#6764]
#### Platform

- Hardware:				Wemos D1
- Core Version:			Latest git
- Development Env:		Sloeber ide
- Operating System:		Windows

### Problem Description

When using schedule_function() within a scheduled function, the run_scheduled_functions() will never return,
This has been working before, I do not know yet which of the scheduled functions PR removed the functionality.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include "Arduino.h"
#include "Schedule.h"

void cp()
{
	static int c = 0;
	if ((c++ % 10000) == 0 ) Serial.printf(".");
	schedule_function(cp);
}

void setup()
{
	Serial.begin(115200);
	schedule_function(cp);
}

void loop()
{
	static int l = 0;
	if ((l++ % 10000) == 0 ) Serial.printf(":");
}

**Comment by d-a-v** [comment]
@dok-net I haven't check yet, maybe you already have an idea.
