### ISSUE TITLE
ESP8266 webserver disappearing after few send data from browser 

### ISSUE THREAD

**Issue by grittinjames** [esp8266/Arduino#6771]
Hi,
This is simple project using esp8266 and P10 led display module.
Its working fine for while and when i send some data from browser frequently, THe server hangs and Access point disappeared. I have to restart to regain the board. 
I have tried solution mentioned for similar issues in many other post, Nothing worked.
Seeking help from some experts

[Score.txt](https://github.com/esp8266/Arduino/files/3844304/Score.txt)

**Comment by devyte** [comment]
Closing due to not compliant.
