### ISSUE TITLE
What's new?

### ISSUE THREAD

**Issue by Teddyz** [esp8266/Arduino#6795]
The front page directs me to[ Latest release documentation](https://arduino-esp8266.readthedocs.io/en/2.6.1/) for insight on what is included. 

Is it possible to have some executive version of change-log for us who would like to just understand what changes and new features we might need to change our previous code for?

I like the level of detail in [Arduino - ReleaseNotes ](https://www.arduino.cc/en/Main/ReleaseNotes)

**Comment by jandrassy** [comment]
https://github.com/esp8266/Arduino/releases
