### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by thethereza** [esp8266/Arduino#682]
docs say that .RSSI() doesn't work - it does,  after you .scanNetworks()

    void scan(void) {
    	byte numNetworks = WiFi.scanNetworks();
    	for (int i = 0; i < numNetworks; i++)  Serial.printf("Found %s RSSI = %d\n", WiFi.SSID(i), WiFi.RSSI(i));
    	WiFi.scanDelete(); //clear ram
    }

**Comment by igrr** [comment]
Just fixed that today in
https://github.com/esp8266/Arduino/commit/fa9d102b6a42dde92ce41fe5440227bd9c9e75c4
