### ISSUE TITLE
Web server dosent work with /23(255.255.254.0) networks.

### ISSUE THREAD

**Issue by fableman73** [esp8266/Arduino#6822]
I have a /23 network and it is impossible to get the webserver to work with DHCP.
Ping dose work fine and in router everything looks ok.

Fix: Set the IP address manually it is ok but not from DHCP.

Problem: I think the Webserver can't handle bigger networks then /24 (255.255.255.0) and (255.255.254.0) will fail.

**Comment by devyte** [comment]
Closing due to non-compliance with issue template.

**Comment by d-a-v** [comment]
/23 networks are unusual but exist. 
I have access to a /21 network I will give a try.

@fableman73 please open a new issue and fill in the issue template with details.
