### ISSUE TITLE
showing Python was not found during uploading spiffs

### ISSUE THREAD

**Issue by ranap040** [esp8266/Arduino#6829]
showing Python was not found during uploading spiffs
![Screenshot (59)](https://user-images.githubusercontent.com/58132121/69492732-22e87b80-0ecc-11ea-8093-9a3a750b73d4.png)
![Screenshot (58)](https://user-images.githubusercontent.com/58132121/69492734-22e87b80-0ecc-11ea-9c47-27e2301ac737.png)

**Comment by earlephilhower** [comment]
Yes, we've got a PR into the Spiffs uploader to fix this.

**Comment by ranap040** [comment]
thanks for the help... Its working fine with the my rgb strip but i want to change the strip with 4 in 1 rgb strip(each led in the strip packed with red,green,blue and a white/warm white). so for that strip should I need to change anything in the code ?
If yes then plz help!
it will enough to have option to toggle the white light on and off and control the brightness doesn't need to change anything in the effects or presets!

**Comment by earlephilhower** [comment]
Please try the plugin ZIP embedded in my comment:
https://github.com/esp8266/arduino-esp8266fs-plugin/pull/65#issuecomment-558234472
https://github.com/esp8266/arduino-esp8266fs-plugin/files/3887643/ESP8266FS-0.5.0.zip

You can also try the one that was released in the plugin repo (but it did not work for me w/Arduino 1.8.8).

If you could report back on that PR which one worked/didn't work it would be helpful.

**Comment by devyte** [comment]
The relevant PR is merged. Closing.
