### ISSUE TITLE
geting this error 

### ISSUE THREAD

**Issue by sagarushi** [esp8266/Arduino#6840]
Arduino: 1.8.10 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

C:\Users\JCS\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Users\JCS\Arduino\hardware -hardware C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages -tools C:\Users\JCS\Arduino\tools-builder -tools C:\Users\JCS\Arduino\hardware\tools\avr -tools C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages -built-in-libraries C:\Users\JCS\Arduino\libraries -libraries C:\Users\JCS\AppData\Local\Arduino15\libraries -fqbn=esp8266:esp8266:nodemcuv2:CpuFrequency=80,VTable=flash,FlashSize=4M1M,LwIPVariant=v2mss536,Debug=Disabled,DebugLevel=None____,FlashErase=none,UploadSpeed=115200 -ide-version=10810 -build-path C:\Users\JCS\AppData\Local\Temp\arduino_build_956991 -warnings=none -build-cache C:\Users\JCS\AppData\Local\Temp\arduino_cache_584466 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2 -prefs=runtime.tools.xtensa-lx106-elf-gcc-1.20.0-26-gb404fb9-2.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2 -prefs=runtime.tools.esptool.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\esptool\0.4.13 -prefs=runtime.tools.esptool-0.4.13.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\esptool\0.4.13 -prefs=runtime.tools.mkspiffs.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\mkspiffs\0.2.0 -prefs=runtime.tools.mkspiffs-0.2.0.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\mkspiffs\0.2.0 -verbose C:\Users\JCS\Documents\Arduino\libraries\Adafruit_MQTT_Library\examples\mqtt_esp8266\mqtt_esp8266.ino
C:\Users\JCS\Arduino\arduino-builder -compile -logger=machine -hardware C:\Users\JCS\Arduino\hardware -hardware C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages -tools C:\Users\JCS\Arduino\tools-builder -tools C:\Users\JCS\Arduino\hardware\tools\avr -tools C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages -built-in-libraries C:\Users\JCS\Arduino\libraries -libraries C:\Users\JCS\AppData\Local\Arduino15\libraries -fqbn=esp8266:esp8266:nodemcuv2:CpuFrequency=80,VTable=flash,FlashSize=4M1M,LwIPVariant=v2mss536,Debug=Disabled,DebugLevel=None____,FlashErase=none,UploadSpeed=115200 -ide-version=10810 -build-path C:\Users\JCS\AppData\Local\Temp\arduino_build_956991 -warnings=none -build-cache C:\Users\JCS\AppData\Local\Temp\arduino_cache_584466 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2 -prefs=runtime.tools.xtensa-lx106-elf-gcc-1.20.0-26-gb404fb9-2.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2 -prefs=runtime.tools.esptool.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\esptool\0.4.13 -prefs=runtime.tools.esptool-0.4.13.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\esptool\0.4.13 -prefs=runtime.tools.mkspiffs.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\mkspiffs\0.2.0 -prefs=runtime.tools.mkspiffs-0.2.0.path=C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\mkspiffs\0.2.0 -verbose C:\Users\JCS\Documents\Arduino\libraries\Adafruit_MQTT_Library\examples\mqtt_esp8266\mqtt_esp8266.ino
Using board 'nodemcuv2' from platform in folder: C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\hardware\esp8266\2.4.2
Using core 'esp8266' from platform in folder: C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\hardware\esp8266\2.4.2
Detecting libraries used...
"C:\\ProgramData\\MATLAB\\SupportPackages\\R2017a\\3P.instrset\\arduinoide.instrset\\idepkgs\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\\ProgramData\\MATLAB\\SupportPackages\\R2017a\\3P.instrset\\arduinoide.instrset\\idepkgs\\packages\\esp8266\\hardware\\esp8266\\2.4.2/tools/sdk/include" "-IC:\\ProgramData\\MATLAB\\SupportPackages\\R2017a\\3P.instrset\\arduinoide.instrset\\idepkgs\\packages\\esp8266\\hardware\\esp8266\\2.4.2/tools/sdk/lwip2/include" "-IC:\\ProgramData\\MATLAB\\SupportPackages\\R2017a\\3P.instrset\\arduinoide.instrset\\idepkgs\\packages\\esp8266\\hardware\\esp8266\\2.4.2/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\\Users\\JCS\\AppData\\Local\\Temp\\arduino_build_956991/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -ffunction-sections -fdata-sections -w -x c++ -E -CC -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DARDUINO=10810 -DARDUINO_ESP8266_NODEMCU -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU\"" -DESP8266 "-IC:\\ProgramData\\MATLAB\\SupportPackages\\R2017a\\3P.instrset\\arduinoide.instrset\\idepkgs\\packages\\esp8266\\hardware\\esp8266\\2.4.2\\cores\\esp8266" "-IC:\\ProgramData\\MATLAB\\SupportPackages\\R2017a\\3P.instrset\\arduinoide.instrset\\idepkgs\\packages\\esp8266\\hardware\\esp8266\\2.4.2\\variants\\nodemcu" "C:\\Users\\JCS\\AppData\\Local\\Temp\\arduino_build_956991\\sketch\\mqtt_esp8266.ino.cpp" -o nul
Alternatives for bits/stl_iterator_base_types.h: []
ResolveLibrary(bits/stl_iterator_base_types.h)
  -> candidates: []
In file included from c:\programdata\matlab\supportpackages\r2017a\3p.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\algorithm:61:0,

                 from C:\ProgramData\MATLAB\SupportPackages\R2017a\3P.instrset\arduinoide.instrset\idepkgs\packages\esp8266\hardware\esp8266\2.4.2\cores\esp8266/Arduino.h:255,

                 from C:\Users\JCS\AppData\Local\Temp\arduino_build_956991\sketch\mqtt_esp8266.ino.cpp:1:

c:\programdata\matlab\supportpackages\r2017a\3p.instrset\arduinoide.instrset\idepkgs\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\bits\stl_algobase.h:65:42: fatal error: bits/stl_iterator_base_types.h: No such file or directory

 #include <bits/stl_iterator_base_types.h>

                                          ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by devyte** [comment]
Issue template ignored. 
Logs show core 2.4.2, which is beyond ancient. 
Build is from within Matlab, which we don't support.
As a WAG, you may be running into the windows max path length issue. 
Closing due to not compliant.
