### ISSUE TITLE
C:\Users\Moin Ahamad\Documents\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFiGeneric.h:27:10: fatal error: functional: No such file or directory

### ISSUE THREAD

**Issue by moin786ahamad** [esp8266/Arduino#6856]
#include <functional>            ^~~~~~~~~~~~  compilation terminated 
Where I have to add this functional file and what will be the extension of this file.
Can someone help me, please?

**Comment by d-a-v** [comment]
You seem to ***not*** be using an esp8266-based board to compile esp8266 source files.
Check your board selection, or check your installation.
