### ISSUE TITLE
Upload speed 921600 is working at 460800 bps

### ISSUE THREAD

**Issue by gkswngh05** [esp8266/Arduino#6859]
#6439 # Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] I have filled out all fields below.

#### Platform

- Hardware:				Wemos d1 mini
- Core Version:			2.6.2
- Development Env:		Arduino IDE 1.8.10
- Operating System:		Ubuntu 18.0.4 LTS amd64

### Settings in IDE

- Module:  			Wemos D1 mini
- Flash Mode:			Unsure
- Flash Size: 		4MB
- lwip Variant:   v2 Lower Memory
- Reset Method:		Unsure
- Flash Frequency:	40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		Serial(CH340G)
- Upload Speed:   921600

### Problem Description

I'm really new on github and my main language is not English, so please understand my mistake.

When I select Upload speed to 921600 bps, the esptool is saying `Changing baud rate to 460800` and it works at 460800 bps.

I downgraded to 2.5.2 and it works well at 921600 bps.
Not sure what is causing the issue...

### Debug Messages
```
esptool.py v2.8
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: dc:4f:22:7e:0d:12
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 259184 bytes to 189892...

Writing at 0x00000000... (8 %)
Writing at 0x00004000... (16 %)
Writing at 0x00008000... (25 %)
Writing at 0x0000c000... (33 %)
Writing at 0x00010000... (41 %)
Writing at 0x00014000... (50 %)
Writing at 0x00018000... (58 %)
Writing at 0x0001c000... (66 %)
Writing at 0x00020000... (75 %)
Writing at 0x00024000... (83 %)
Writing at 0x00028000... (91 %)
Writing at 0x0002c000... (100 %)
Wrote 259184 bytes (189892 compressed) at 0x00000000 in 4.3 seconds (effective 485.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

**Comment by devyte** [comment]
This is on purpose. I believe esptool.py doesn't support speeds higher than 460K.  In any case, esptool.py @460K is faster than the old esptool-ck @921K for several reasons.
To not break everyone's ui out there, 921K was kept as a menu option when the transition to esptool.py was made, but under the hood the speed gets dropped to the highest supported which is 460K.
Closing due to intentional.
