### ISSUE TITLE
Arduino sending data to esp8266(softwareserial) not working

### ISSUE THREAD

**Issue by cacs200281** [esp8266/Arduino#6899]
Hello,

I am trying to send data between arduino uno R3(sender) and esp8266-12(receiver) by software serial.
My problem is that esp doesn't work using software serial :(
I read a lot of info on the internet but any solution not helped me yet.
-Arduino is working very nice sending the data, when I choose to receive the data on ESP rx pin(not emulated) I can see the received data;
-I am also using Json to easily send/receive data;
-Arduino emulated pins(5,6) and esp pins(4,5) and yes I am using a level converter 5v - 3v3, the ground is connected between 2 chips;
-I tried to change the baud rate without success;

In the name of God anybody can help me please? I am so sad cause a did test and tests but without success.

Thanks in advance!

**Comment by earlephilhower** [comment]
The best place to get help for this kind of question is the forums at https://esp8266.com or https://gitter.im/esp8266/Arduino .

Closing as not a core issue, but a "How do I..." one.
