### ISSUE TITLE
FSFile::rewindDirectory() appears to be missing ..

### ISSUE THREAD

**Issue by seclorum** [esp8266/Arduino#690]
.. as far as I can tell, a recent refactor/rewrite of the FileSystem library was done, and the subsequent results are sub-par in comparison to what was .. once .. there .. so I've got some code that references FSFile::rewindDirectory() - bam, its gone now.

Whoever did the rewrite - did you consider that some of us might be using the old functions?  Can you please explain what happened and why the FS rewrite was so badly needed .. it has broken our code and means our project can no longer be in sync with espy8266-Arduino without a major bit of work.  Very frustrating!

**Comment by igrr** [comment]
FSFile never became part of the public API (it was present only in staging
version, and wasn't documented). Did you consider that fact when writing
your code? Plus, it was mentioned in other issues that the old API is going
away somewhere in the end of May.
