### ISSUE TITLE
arduino.esp8266.com dns issue

### ISSUE THREAD

**Issue by stef-ladefense** [esp8266/Arduino#6901]
hello,

the url https://arduino.esp8266.com/stable/package_esp8266com_index.json
in Arduino#installing-with-boards-manager don't work for install.
ERR_CONNECTION_TIMED_OUT

thank

**Comment by earlephilhower** [comment]
Looks to have been a temporary hiccup. It's working now.  Closing.

**Comment by stef-ladefense** [comment]
no not work

![image](https://user-images.githubusercontent.com/43587190/70720879-eeaaf280-1cf4-11ea-94d7-2d51154b64a3.png)

sorry but it's wrong 95% of the time,
9 times out of 10 since 2.60 when I use the IDE, I have an error of access to this json and any reference to the 8266 disappears!
it's not usable at all, I'm forced to use the url of the current version, without the possibility of updating

**Comment by d-a-v** [comment]
@stef-ladefense It seems to be an issue with your network.
You can open a ping tool, or a terminal with the following command and check responsiveness.
```
ping arduino.esp8266.com
```
Alternatively you can try with the one described there https://d-a-v.github.io/
(the official 2.6.2 version is the same)
(both this source and installable zip files are from github)

**Comment by stef-ladefense** [comment]
Not work from France 

 Direct fiber internet

 

[C:\Program Files\JPSoft\TCCLE14x64]ping arduino.esp8266.com

 

Envoi d’une requête 'ping' sur arduino.esp8266.com [104.131.82.128] avec 32 octets de données :

Délai d’attente de la demande dépassé.

Délai d’attente de la demande dépassé.

Délai d’attente de la demande dépassé.

Délai d’attente de la demande dépassé.

 

Statistiques Ping pour 104.131.82.128:

    Paquets : envoyés = 4, reçus = 0, perdus = 4 (perte 100%),

 

De : david gauchard <notifications@github.com> 
Envoyé : jeudi 12 décembre 2019 15:44
À : esp8266/Arduino <Arduino@noreply.github.com>
Cc : Stéphane <stboudin@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [esp8266/Arduino] Arduino#installing-with-boards-manager URL ERR_CONNECTION_TIMED_OUT (#6901)

 

@stef-ladefense <https://github.com/stef-ladefense>  It seems to be an issue with your network.
You can open a ping tool, or a terminal with the following command and check responsiveness.

ping arduino.esp8266.com

Alternatively you can try with the one described there https://d-a-v.github.io/
(the official 2.6.2 version is the same)
(both this source and installable zip files are from github)

**Comment by stef-ladefense** [comment]
But ping esp8266.com is ok

 

[C:\Program Files\JPSoft\TCCLE14x64]ping esp8266.com

 

Envoi d’une requête 'ping' sur esp8266.com [119.9.116.93] avec 32 octets de données :

Réponse de 119.9.116.93 : octets=32 temps=347 ms TTL=54

Réponse de 119.9.116.93 : octets=32 temps=353 ms TTL=54

Réponse de 119.9.116.93 : octets=32 temps=348 ms TTL=54

Réponse de 119.9.116.93 : octets=32 temps=346 ms TTL=54

 

Statistiques Ping pour 119.9.116.93:

    Paquets : envoyés = 4, reçus = 4, perdus = 0 (perte 0%),

Durée approximative des boucles en millisecondes :

    Minimum = 346ms, Maximum = 353ms, Moyenne = 348ms

 

De : david gauchard <notifications@github.com> 
Envoyé : jeudi 12 décembre 2019 15:44
À : esp8266/Arduino <Arduino@noreply.github.com>
Cc : Stéphane <stboudin@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [esp8266/Arduino] Arduino#installing-with-boards-manager URL ERR_CONNECTION_TIMED_OUT (#6901)

 

@stef-ladefense <https://github.com/stef-ladefense>  It seems to be an issue with your network.
You can open a ping tool, or a terminal with the following command and check responsiveness.

ping arduino.esp8266.com

Alternatively you can try with the one described there https://d-a-v.github.io/
(the official 2.6.2 version is the same)
(both this source and installable zip files are from github)

**Comment by d-a-v** [comment]
It seems to be a dns problem.

Here (in France too btw), arduino.esp8266.com is 185.199.111.153 but for you it's 104.131.82.128 which is reversed with `download.igrr.me`.

@igrr might help here.

In the meantime you can try
- https://185.199.111.153/stable/package_esp8266com_index.json
- or (as proposed above) https://d-a-v.github.io/esp8266/Arduino/package_esp8266com_index.json

**Comment by stef-ladefense** [comment]
thanks, actually on this machine, my dns were broken, now it works

sorry and thank you again

 

De : david gauchard <notifications@github.com> 
Envoyé : jeudi 12 décembre 2019 16:03
À : esp8266/Arduino <Arduino@noreply.github.com>
Cc : Stéphane <stboudin@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [esp8266/Arduino] Arduino#installing-with-boards-manager URL ERR_CONNECTION_TIMED_OUT (#6901)

 

It seems to be a dns problem.

Here (in France too btw), arduino.esp8266.com is 185.199.111.153 but for you it's 104.131.82.128 which is reversed with download.igrr.me.

@igrr <https://github.com/igrr>  might help here.

In the meantime you can try

*	https://185.199.111.153/stable/package_esp8266com_index.json
*	or (as proposed above) https://d-a-v.github.io/esp8266/Arduino/package_esp8266com_index.json
