### ISSUE TITLE
no not work

### ISSUE THREAD

**Issue by stef-ladefense** [esp8266/Arduino#6903]
no not work

![image](https://user-images.githubusercontent.com/43587190/70720879-eeaaf280-1cf4-11ea-94d7-2d51154b64a3.png)

sorry but it's wrong 95% of the time,
9 times out of 10 since 2.60 when I use the IDE, I have an error of access to this json and any reference to the 8266 disappears!
it's not usable at all, I'm forced to use the url of the current version, without the possibility of updating

_Originally posted by @stef-ladefense in https://github.com/esp8266/Arduino/issues/6901#issuecomment-565032686_

**Comment by d-a-v** [comment]
duplicate #6901
