### ISSUE TITLE
hostname not working

### ISSUE THREAD

**Issue by CorpusCallosum** [esp8266/Arduino#6913]
### Basic Infos

- [ x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [x ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x ] I have filled out all fields below.

#### Platform

- Hardware:				esp8266
- Core Version:			2.6.2
- Development Env:		Arduino
- Operating System:		Mac

### Settings in IDE

- Module:  			Adafruit Feather Huzzah esp8266
- Flash Mode:			?
- Flash Size: 		4MB
- lwip Variant:   v1.4
- Reset Method:		?
- Flash Frequency:	?
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   115200

### Problem Description

I'm unable to connect to the device using hostname since updating the library. This was working before with an earlier version of the library. When I try to connect to the device using it's hostname (http://myhostname.local/), I am getting this error in my browser: "This site can’t be reached myhostname.local’s server IP address could not be found." On the other hand, I have another one of these devices running an older version of this library, and I am able to connect to that one through it's hostname without issue.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <ESP8266WebServer.h>
#include <ESP8266mDNS.h>

#ifndef STASSID
#define STASSID "networkname"
#define STAPSK  "password"
#endif

const char* ssid = STASSID;
const char* password = STAPSK;

ESP8266WebServer server(80);

const int led = 13;

void handleRoot() {
  digitalWrite(led, 1);
  server.send(200, "text/plain", "hello from esp8266!");
  digitalWrite(led, 0);
}

void setup(void) {
  pinMode(led, OUTPUT);
  digitalWrite(led, 0);
  Serial.begin(115200);
  WiFi.mode(WIFI_STA);
  WiFi.hostname("myhostname");
  WiFi.begin(ssid, password);
  Serial.println("");

  // Wait for connection
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.print("Connected to ");
  Serial.println(ssid);
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  if (MDNS.begin("esp8266")) {
    Serial.println("MDNS responder started");
  }

  server.on("/", handleRoot);

  server.begin();
  Serial.println("HTTP server started");

  Serial.print(WiFi.hostname());
}

void loop(void) {
  server.handleClient();
  MDNS.update();
}

```

### Debug Messages

```
Debug messages go here
```

**Comment by devyte** [comment]
Your code has:
```cpp
WiFi.hostname("myhostname");
...
if (MDNS.begin("esp8266")) {
...
```

That means your MDNS hostname is being set up as `esp8266.local`, not `myhostname.local`.

I suggest looking at the MDNS examples.

Closing due to user error.
