### ISSUE TITLE
Update docs for Updater/etc. explaining how to use gzip uploads

### ISSUE THREAD

**Issue by earlephilhower** [esp8266/Arduino#6923]
#6820 was merged w/o docs to allow @ChocolateFrogsNuts to do his magic on combining the XMC flash patch into eboot without delay, but lacked specific documentation updates.

Documentation the capabilities and process eboot now uses.

**Comment by TD-er** [comment]
The active sketch should have support for gzipped files right?
Or is the newly flashed sketch executed?

**Comment by earlephilhower** [comment]
Yes.  If you try to upload a GZ sketch to the old updater.cpp, it will disallow it as an invalid app and the eboot present in flash won't understand it, either.  You need one uncompressed upload compiled with the new updater.cpp and then you can just send .GZs up.  Or, if using direct serial upload (esptool.py), then a simple compile and upload will get the new eboot compressed support.

**Comment by TD-er** [comment]
Good to know, so I will make a new version of our 2-step OTA image including this.
One GZip'ed and one raw .bin.

**Comment by earlephilhower** [comment]
Per @pfalcon:



If you give credit to me, please give credit to the original authors too, from uzlib's README:

uzlib is based on:
    tinf library by Joergen Ibsen (Deflate decompression)
    Deflate Static Huffman tree routines by Simon Tatham
    LZ77 compressor by Paul Sokolovsky

Library integrated and maintained by Paul Sokolovsky.

I guess the same wording as above for LittleFS would work, i.e. "uzlib library written by Joergen Ibsen, Simon Tatham, Paul Sokolovsky, licensed under the ZLib license". (That may be not entirely formally correct, but if Joergen or Simon will ever object claim that they wrote that lib, could be rewritten with "based on code by".)

**Comment by earlephilhower** [comment]
@AdrianEddy found a bug in the format string setup.
> "0' is not '\0', is this intentional?

**Comment by HenkV74** [comment]
Is it correct that this does not work for the spiffs partition? Would be great as 2mb becomes 60kb after zip.
