### ISSUE TITLE
[2.6.x] Error compiling NodeMCU

### ISSUE THREAD

**Issue by crashcoq** [esp8266/Arduino#6941]
I have a program on NodeMCU ESP8266.
It works fine with the 2.52 and older version

On 2.6.x (X with 0, 1 or 2), i can't compile any program, or example !!
I have error only: "exit status 1, Error compiling for board NodeMCU"
no error

I have warning on the char* on debug mode

I have uninstall and install arduino, same problem ...

could you help me?

**Comment by devyte** [comment]
It sounds like you need to fix your warning.

This isn't the right place to ask for general help. This is an issue tracker, meant for tracking issues in the core. I suggest asking at a community forum like esp8266.com or stackoverflow, or in our gitter channel. 
Closing due to not compliant.
