### ISSUE TITLE
is there a simple standard example shipping with this repo about how to get UTC time and Serial.println(time)?

### ISSUE THREAD

**Issue by dsyleixa** [esp8266/Arduino#6942]
is there a simple standard example shipping with this repo about how to get UTC time and Serial.println(time)?

**Comment by jandrassy** [comment]
https://github.com/esp8266/Arduino/blob/master/libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino

**Comment by dsyleixa** [comment]
Merry Christmas!
@jandrassy:
thanks, bt that s utterly complciaed, I don't understand anything of that monster code. I mean a simple introductional example, just calling a time server, get time, write time to Serial. No timezone, no setting, no extras.

**Comment by jandrassy** [comment]
look better. there is a simple setup()  and a simple loop() and a function to print time

**Comment by dsyleixa** [comment]
thanks for your efforts, but I think I resign...

**Comment by d-a-v** [comment]
@dsyleixa 

```
struct timeval tv;
gettimeofday(&tv, nullptr);
// tv.tv_sec is the number of seconds since EPOCH, it is UTC time
```
You can use [`gmtime()`](https://linux.die.net/man/3/gmtime) to get details about it.
(used in the example: [in the example](https://github.com/esp8266/Arduino/blob/master/libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino#L109))

**Comment by dsyleixa** [comment]
yes, thank you, I got it working.
but as to the TOP:
is such an example shipping with the esp8266 standard examples?
