### ISSUE TITLE
Happy Holidays

### ISSUE THREAD

**Issue by devyte** [esp8266/Arduino#6944]
### Basic Infos

- [Nope] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [Nope] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [Nope] I have tested that the issue is present in current master branch (aka latest git).
- [Nope] I have searched the issue tracker for a similar issue.
- [Nope] If there is a stack dump, I have decoded it.
- [Nope] I have filled out all fields below.

### Platform

- Hardware:					Yes
- Core Version:			Installed
- Development Env:		No idea
- Operating System:		What's an Operating System 

### Settings in IDE

- Module:  			The one I have
- Flash Mode:			Auto
- Flash Size: 		The big one
- lwip Variant:   What's lwip
- Reset Method:		Yes
- Flash Frequency:	Maybe
- CPU Frequency:		2.4GHz
- Upload Using:		Button
- Upload Speed:   Pretty fast

### Problem Description

Happy Holidays everyone. May you all have the utmost stability in your code, and may your applications be bug free.

Cheers!

**Comment by earlephilhower** [comment]
First closed bug of the year.  Happy New Year, all!
