### ISSUE TITLE
cannot connect to maker.ifttt.com randomly

### ISSUE THREAD

**Issue by DavidAntonin** [esp8266/Arduino#6948]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12e]
- Core Version:			[latest git hash]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Wemos D1 mini r2|]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v2 Lower Memory]
- CPU Frequency:		[80Mhz]

### Problem Description

My home gateway sends weather informations to my local SQL server  every two minutes and when it receive trigger from 433MHz sensors (CC1101 receiver) sends event over IFTTT. 
There is absolutely no problem with connecting and sending data to local SQL (Synology NAS).
I use same method of connectiont to maker.ifttt.com but connection randomly fail. 

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp
... connection procedure...
  #define httpPort 80
  IPAddress host2(34,234,65,77); //tried to use IP instead of name
  Serial.print(F("ESP heap:")); Serial.println(ESP.getFreeHeap());
  client.setTimeout(5000); // 5 Seconds
  Serial.print(F("WIFI state:")); Serial.println(WiFi.status());
  Serial.println(F("HTTP Connecting "));
  int r = 0; //retry counter

  while ((!client.connect(host2, httpPort)) && (r < 5)) {
    delay(500);
    Serial.print(".");
    r++;
  }
  if (r == 5) {
    Serial.println(F("Connection failed"));
    return;
  }
  else {
    Serial.println(F("Connected to web"));
  }
```

### Debug Messages

```
susscessfull connection:
ESP heap:45464
WIFI state:3
HTTP Connecting 
:ur 1
:del
:ref 1
Connected to web
:wr 66 0
:wrc 66 66 0
:wr 2 0
:wrc 2 2 0
:wr 21 0
:wrc 21 21 0
....

connection fail:
ESP heap:45712
WIFI state:3
HTTP Connecting 
:ur 1
:del
:ref 1
:ctmo
:abort
:ur 1
:del
.:ref 1
:ctmo
:abort
:ur 1
:del
.:ref 1
:ctmo
:abort
:ur 1
:del
.:ref 1
:ctmo
:abort
:ur 1
:del
.:ref 1
:ctmo
:abort
:ur 1
:del
.:ref 1
:ctmo
:abort
:ur 1
:del
Connection failed



```

**Comment by earlephilhower** [comment]
This looks like a networking issue somewhere between the 8266 and the maker server.  Not sure there is any problem indicated.  @d-a-v, should this be closed?
