### ISSUE TITLE
Sketch with old SD software no longer compiles

### ISSUE THREAD

**Issue by NicoZuid** [esp8266/Arduino#6966]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:			[ESP-12]
- Core Version:			[2.5.0  --->2.5.1 …. 2.6.3]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Wemos D1  r2]
- Flash Mode:			[?]
- Flash Size: 		        [4MB]
- lwip Variant:   [?]
- Reset Method:		[?]
- Flash Frequency:	[?]
- CPU Frequency:		[80Mhz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [all)

### Problem Description

Sketch with old SD software no longer compiles with SDK version 2.5.1 and newer.
From core version 2.5.1 the folder is missing: ... libraries / SD / src / utility

The Cardinfo example is also missing.
The functions from the map utility were used in this example.

The File system documentation states:
_For legacy applications, the classic SD filesystem may continue to be used, but for new applications, directly access the SDFS filesystem is recommended as it may expose additional functionality that the old Arduino SD filesystem didn't have._

Can the utility (with associated files) be added again or does that conflict with the current version?

**Comment by earlephilhower** [comment]
No, that was part of the ancient SD.h snapshot that Arduino took.

The utility was updated and maintained, though, by grieman (author and maintainer of the SD stuff) so if you look in the ESP8266SDFat library you can find something better in SdInfo (granted, I haven't tried it myself as it's not FS related):
https://github.com/earlephilhower/ESP8266SdFat/blob/b240d2231a117bbd89b79902eb54cae948ee2f42/examples/SdInfo/SdInfo.ino
