### ISSUE TITLE
CRC error on installing "Stable" Esp8266 support from boards manager

### ISSUE THREAD

**Issue by Muftman** [esp8266/Arduino#6967]
#### Platform

- Hardware:			---
- Core Version:			2.6.3
- Development Env:		Arduino IDE   1.8.10
- Operating System:		Windows10

### Problem Description

When adding support for the esp8266 to the Arduino IDE using the stable json link the install fails and states theres a CRC error and the install fails.

http://arduino.esp8266.com/stable/package_esp8266com_index.json
the download took very long, more than 30min

![grafik](https://user-images.githubusercontent.com/35936050/71622251-bea88e00-2bd4-11ea-8c25-5090cbf3f0fe.png)

**Comment by earlephilhower** [comment]
Looks like network issues between you and the repo.  Please do as the IDE says, please retry later.  Nothing we can do on our end.
