### ISSUE TITLE
can't update the   WiFi.softAP(ssid, password);

### ISSUE THREAD

**Issue by liorhal1** [esp8266/Arduino#6970]
i allredy update from git the esp as you write in the oldest issues
but it is dont work , the ssid dont change and pass ignore
plz help me

**Comment by shalom198** [comment]
why did you closed it
i dont success to run it 
plz help me

**Comment by devyte** [comment]
Because you ignored the issue template instructions. This is an issue tracker, and not a support forum for general help. Please request such help at a community forum like esp8266.com or stackoverflow.

**Comment by shalom198** [comment]
got it, thanks alot
