### ISSUE TITLE
Bandwidth throttling by github

### ISSUE THREAD

**Issue by andreas83** [esp8266/Arduino#6973]
I downloaded the esp8266 package via Arduino Board Manager and it took ages
 (10KB/sec. instead of 2 MB /sec) 
https://github.com/esp8266/Arduino/releases/download/2.6.3/esp8266-2.6.3.zip

To me it looks like Github does some sort of bandwidth throtteling here, since other github services works flawlessly.

**Comment by earlephilhower** [comment]
Sorry, I can't repro this.  GitHub is good enough to provide free hosting for this project, and there's not much we could do about it ourselves, even if we could repro it.  As I believe GW hosts thru S3 buckets (maybe migrating to Azure?), you could check the availability zone nearest to you and see if there's anything up.  Closing as not repro'able and out of our control.
