### ISSUE TITLE
I2C error

### ISSUE THREAD

**Issue by petrd** [esp8266/Arduino#698]
Hello,
I tried to connect ESP-12E I2C humidity and temperature sensor AM2321. I2C communication is not working. I tried it on Modemcu 0.9 (ESP-12) and on Modemcu 1.0 (ESP-12E). The same code works with the Arduino Due. I reduced the pull-up resistors from 10k to 2k2. Also it is not working. I tried HTU21D, it is similar to the humidity and temperature sensor. Also not working.
I do not know what I'm doing wrong, but it looks like it is not working I2C?

Configuration:
SDA = GPIO4
SCL = GPIO5
Pull-up resistors 2x10K or 2x2k2
Version: 1.6.5-1044-g170995a

Code:
<pre><code>
#include &lt;Wire.h&gt;

#define I2C_ADDR_AM2321 (0xB8 >> 1)
#define PARAM_AM2321_READ 0x03
#define REG_AM2321_HUMIDITY_MSB 0x00
#define REG_AM2321_HUMIDITY_LSB 0x01
#define REG_AM2321_TEMPERATURE_MSB 0x02
#define REG_AM2321_TEMPERATURE_LSB 0x03
#define REG_AM2321_DEVICE_ID_BIT_24_31 0x0B

void setup() {
  Serial.begin(9600);
  //Wire.pins(4,5); // SDA, SCL  
  //Wire.setClock(100000);
  Wire.begin(4, 5);
}

void loop() {

        //
        // Wakeup
        //
        Wire.beginTransmission(I2C_ADDR_AM2321);
        Wire.endTransmission();

        //
        // Read Command
        //
        Wire.beginTransmission(I2C_ADDR_AM2321);
        Wire.write(PARAM_AM2321_READ);
        Wire.write(REG_AM2321_HUMIDITY_MSB);
        Wire.write(4);
        Wire.endTransmission();

        //
        // Waiting
        //
        //delayMicroseconds(1600); //>1.5ms
        delay(2);
        //
        // Read
        //
        Wire.requestFrom(I2C_ADDR_AM2321, 8); // COMMAND + REGCOUNT + DATA + CRCLSB + CRCMSB
        //int i = 0;
        uint8_t buf[6];
        for (int i = 0; i < 6; ++i)
            buf[i] = Wire.read();

        unsigned short crc = 0;
        crc  = Wire.read();     //CRC LSB
        crc |= Wire.read() << 8;//CRC MSB

       // if (crc == crc16(buf, i))
       //     return true;
       // return false;

        unsigned int humidity;
        int temperature;
        humidity     = buf[2] << 8;
        humidity    += buf[3];
        temperature  = buf[4] << 8;
        temperature += buf[5];

        Serial.print("Temperature = ");
        Serial.print(temperature);
        Serial.print("\t Humidity = ");
        Serial.println(humidity);
        delay(3000);
}
</code></pre>

**Comment by igrr** [comment]
Which pins on Nodemcu board are you using? You know that silkscreen labels
do not correspond to GPIO number right?

**Comment by petrd** [comment]
Hello,
I use D1 and D2, it should correspond GPIO5 and GPIO4.

**Comment by petrd** [comment]
I tried also GPIO12 and GPIO14, the result is the same.

**Comment by igrr** [comment]
Ok, I don't have these sensors at hand, please attach oscilloscope traces
so that we can figure out what is the cause of this issue.

**Comment by petrd** [comment]
Hello,
so for me does not work Wire.write ()

First shot of the Arduino UNO + AM2321:
![1](https://cloud.githubusercontent.com/assets/7544713/9310061/c4a8ba80-450d-11e5-8ffe-3322ba14aa5e.png)
![1d](https://cloud.githubusercontent.com/assets/7544713/9310068/ca7b1836-450d-11e5-9894-faa1ec24269f.png)

The following is a picture ESP-12E + AM2321:
![2](https://cloud.githubusercontent.com/assets/7544713/9310091/f019130e-450d-11e5-867b-d1dd9faa7faf.png)
![2d](https://cloud.githubusercontent.com/assets/7544713/9310095/f5cbb982-450d-11e5-965b-1f012f5272eb.png)

**Comment by igrr** [comment]
I can't zoom the traces enough to see the pulses, but from the log it looks like the difference is that ESP doesn't generate STOP condition after a NACK.

**Comment by igrr** [comment]
You can try to edit twi_writeTo function in core_esp8266_si2c.c. Make it call twi_write_stop on errors (i.e. before `return 2` statement).

**Comment by petrd** [comment]
Sending an enlarged graph which corresponds to the following code:

<pre><code>
        //
        // Wakeup
        //
        Wire.beginTransmission(I2C_ADDR_AM2321);
        Wire.endTransmission();

        //
        // Read Command
        //
        Wire.beginTransmission(I2C_ADDR_AM2321);
        Wire.write(PARAM_AM2321_READ);
        Wire.write(REG_AM2321_HUMIDITY_MSB);
        Wire.write(4);
        Wire.endTransmission();

</code></pre>

Arduino Uno:
        Wire.beginTransmission(0xB8);
        Wire.endTransmission();
        Wire.beginTransmission(0xB8);
        Wire.write(0x03);
        Wire.write(0x00);
        Wire.write(0x04);
        Wire.endTransmission();


![screenshot 2015-08-17 21 03 53](https://cloud.githubusercontent.com/assets/7544713/9313776/208e87d2-4525-11e5-9a88-187aa921c80e.png)

![screenshot 2015-08-17 21 04 29](https://cloud.githubusercontent.com/assets/7544713/9313782/285b9c3e-4525-11e5-99bb-0e6c241c4959.png)

Arduino ESP-12E:
        Wire.beginTransmission(0xB8);
        Wire.endTransmission();
        Wire.beginTransmission(0xB8);
        Wire.write(0x03); // Error
        Wire.write(0x00); // Error
        Wire.write(0x04); // Error
        Wire.endTransmission();

![screenshot 2015-08-17 21 05 45](https://cloud.githubusercontent.com/assets/7544713/9313786/304a3ad6-4525-11e5-920e-a7fdfe82b22e.png)

![screenshot 2015-08-17 21 06 07](https://cloud.githubusercontent.com/assets/7544713/9313793/3895252a-4525-11e5-878b-050f82b8f87f.png)

**Comment by igrr** [comment]
Okay, graphs show that ESP doesn't generate a STOP condition after the first NACK. Please try the edit suggested above — it might resolve the issue.

**Comment by petrd** [comment]
Hello,
I edited core_esp8266_si2c.c and AM2321 works.
Thank you very much for your help.

**Comment by igrr** [comment]
That's great! Could you please post the diff or the changed code for the
record? (just to be sure I won't mess up anything when doing this change).

**Comment by petrd** [comment]
OK, Thank you very much.

**Comment by Rorschac** [comment]
Hi, Ivan.

I want to transform "ESP test code" to Arduino uno for CAN-BUS comunication. I removed specified ESP code from your code, and compiled for UNO with no errors. Then I send for example "X" on arduino serial interface. I can see the messages with scope but Attiny85 did not response this message. Where I am doing wrong. I added that removed codes from your code and scope screen.

![img_20180716_144551](https://user-images.githubusercontent.com/25567370/42759276-1bc418ee-890f-11e8-8bd9-293c3e3e92c5.jpg)
```
/*extern "C"
{
  #include "user_interface.h"
}*/

//os_timer_t myTimer;

//  os_timer_setfn(&myTimer, timerCallback, NULL);
//  os_timer_arm(&myTimer, 1000, true);

Wire.setClockStretchLimit(1000);
```
