### ISSUE TITLE
[Question] ESP8266 mDNS: How to advertise on the network?

### ISSUE THREAD

**Issue by probonopd** [esp8266/Arduino#7]
I would like to use mDNS in order to advertise the web server running on the ESP8266 to the network, so that it is easily found by guests and other devices on the network. How can this be done?

**Comment by igrr** [comment]
I would suggest you to check the [example](https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266mDNS/examples/mDNS_Web_Server/mDNS_Web_Server.ino) provided with ESP8266mDNS library.

**Comment by probonopd** [comment]
Others seem to have the same issue:

"Also used the App Bonjour Browser, but the ESP is not seen as Bonjour device.
Anyone having success with this example on a Mac?"

http://www.esp8266.com/viewtopic.php?f=29&t=2270

**Comment by igrr** [comment]
To be seen as a bonjour service we need to support DNS-SD, not just bare
mDNS. DNS-SD may be implemented on top of mDNS, but I haven't yet done this.

**Comment by gregslomin** [comment]
I can also confirm that the mDNS example is not working at all for me.

**Comment by igrr** [comment]
I've added missing interface address setup for multicast PCBs, so this example works properly now.

Note that it only works in station mode, see my comment [here](https://github.com/esp8266/Arduino/issues/74#issuecomment-96730305) for details.
