### ISSUE TITLE
Library LittleFS example LittleFS_Timestamp

### ISSUE THREAD

**Issue by NicoZuid** [esp8266/Arduino#7001]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[2.6.3]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Wemos D1 mini r2]
- Flash Mode:			[?]
- Flash Size: 		[4MB]
- lwip Variant:   [?]
- Reset Method:		[?]
- Flash Frequency:	[?]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200)

### Problem Description

_(I doubted whether I would report the issue below.)_
The filesystem is formatted (**LittleFS.format();**) at the start of the example.
Any files already present are thereby deleted.
Formatting seems unnecessary to me.
If a file system is not present at LittleFS.begin, it will be formatted automatically.
After formatting,  **listDir("/");** and  **deleteFile("/hello.txt")**; are also unnecessary:

### [MCVE](https://stackoverflow.com/help/mcve) Sketch
```
  Serial.println("Formatting LittleFS filesystem");
  LittleFS.format();
  Serial.println("Mount LittleFS");
  if (!LittleFS.begin()) {
    Serial.println("LittleFS mount failed");
    return;
  }
  listDir("/");
  deleteFile("/hello.txt");
  writeFile("/hello.txt", "Hello ");
  appendFile("/hello.txt", "World!\n");
  listDir("/");

```

**Comment by earlephilhower** [comment]
For the examples, I like to ensure a clean format (i.e. in case there was a SPIFFS FS there before), so I believe we should leave it as-is.  Thanks.
