### ISSUE TITLE
Using different interrupt levels at run time?  

### ISSUE THREAD

**Issue by sticilface** [esp8266/Arduino#701]
These are defined in the arduino.h

```
#define xt_rsil(level) (__extension__({uint32_t state; __asm__ __volatile__("rsil %0," __STRINGIFY(level) : "=a" (state)); state;}))
#define xt_wsr_ps(state)  __asm__ __volatile__("wsr %0,ps; isync" :: "a" (state) : "memory")
```

I tried to use something like this so that I could change the interrupt levels at run time, in order to experiment with stability... But nothing would compile...   Error: invalid symbolic operand

```
uint8_t level; // - nothing works here... 

  uint32_t savedPS = xt_rsil(level); // this routine will allow level 2 and above
//    // do work here
  xt_wsr_ps(savedPS); // restore the state
```

would i have to make a function to do it that had 1 - 15 preplaced?  sorry for my lack of understanding.  

PS. Where can I get the info as to what is allowed at each level of interrupt... 0 - 15.  I've struggled, despite lots of dr google...

**Comment by igrr** [comment]
Compiler tells you that you need to provide a symbolic operand to xt_rsil macro, not a variable.
I.e. `xt_rsil(2)` will work.

Regarding interrupt levels, the right place to find this information is the core-isa config file.
https://github.com/espressif/esp_iot_rtos_sdk/blob/master/extra_include/xtensa/config/core-isa.h#L292-L309
Basically, all interrupts except for NMI and Debug are level 1.
