### ISSUE TITLE
No format in the new FS module

### ISSUE THREAD

**Issue by plerup** [esp8266/Arduino#702]
The new file system is great. I'm just missing the format function.

BR
/Peter

**Comment by far5893** [comment]
I m waiting to test fs in next stable release , but i suppose that you must prepare partition before upload sketch with java tools

**Comment by plerup** [comment]
That's an interesting point. I've tried using the file system, writing an reading files back and forth and it works initially but quite soon it get corrupted or the system resets. Sometimes the complete flash gets corrupted and the ESP doesn't start until reflashing...

**Comment by far5893** [comment]
I suppose that FS is not stable enough to release e new stable version of arduino-esp8266 (last stable is 23 jul).
