### ISSUE TITLE
'Stream' has not been declared

### ISSUE THREAD

**Issue by stepanurban** [esp8266/Arduino#7028]
Hi,
I'm getting following error when trying to compile ScanNetworksAdvanced example for Arduino nano 33
/home/.../Arduino/libraries/WiFiEspAT/src/utility/EspAtDrvTypes.h:61:30: error: 'Stream' has not been declared
   virtual uint8_t readRxData(Stream* serial, size_t len) = 0;

Where is the problem? How to get it?
Thank you

**Comment by olsonap** [comment]
Did you figure this out? I'm having the same issue.

**Comment by d-a-v** [comment]
Try with `#include <Stream.h>`

**Comment by olsonap** [comment]
No luck.

C:\esp\myProjects\a2dp_gatts_coex>idf.py build 
Executing action: all (aliases: build)
Running ninja in directory c:\esp\myprojects\a2dp_gatts_coex\build
Executing "ninja all"...
[1/13] Performing build step for 'bootloader'
[1/1] cmd.exe /C "cd /D C:\esp\myProjects\a2dp_gatts_coex\build\bootloader\esp-idf\esptool_py && C:\Users\aman_\.espressif\python_env\idf4.4_py3.9_env\Scripts\python.exe C:/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 C:/esp/myProjects/a2dp_gatts_coex/build/bootloader/bootloader.bin"
Bootloader binary size 0x6350 bytes. 0xcb0 bytes (11%) free.
[4/13] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/PulseSensorPlayground.cpp.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/PulseSensorPlayground.cpp.obj 
ccache C:\Users\aman_\.espressif\tools\xtensa-esp32-elf\esp-2021r2-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../main -IC:/esp/esp-idf/components/newlib/platform_include -IC:/esp/esp-idf/components/freertos/include -IC:/esp/esp-idf/components/freertos/include/esp_additions/freertos -IC:/esp/esp-idf/components/freertos/port/xtensa/include -IC:/esp/esp-idf/components/freertos/include/esp_additions -IC:/esp/esp-idf/components/esp_hw_support/include -IC:/esp/esp-idf/components/esp_hw_support/include/soc -IC:/esp/esp-idf/components/esp_hw_support/include/soc/esp32 -IC:/esp/esp-idf/components/esp_hw_support/port/esp32/. -IC:/esp/esp-idf/components/heap/include -IC:/esp/esp-idf/components/log/include -IC:/esp/esp-idf/components/lwip/include/apps -IC:/esp/esp-idf/components/lwip/include/apps/sntp -IC:/esp/esp-idf/components/lwip/lwip/src/include -IC:/esp/esp-idf/components/lwip/port/esp32/include -IC:/esp/esp-idf/components/lwip/port/esp32/include/arch -IC:/esp/esp-idf/components/soc/include -IC:/esp/esp-idf/components/soc/esp32/. -IC:/esp/esp-idf/components/soc/esp32/include -IC:/esp/esp-idf/components/hal/esp32/include -IC:/esp/esp-idf/components/hal/include -IC:/esp/esp-idf/components/hal/platform_port/include -IC:/esp/esp-idf/components/esp_rom/include -IC:/esp/esp-idf/components/esp_rom/include/esp32 -IC:/esp/esp-idf/components/esp_rom/esp32 -IC:/esp/esp-idf/components/esp_common/include -IC:/esp/esp-idf/components/esp_system/include -IC:/esp/esp-idf/components/esp_system/port/soc -IC:/esp/esp-idf/components/esp_system/port/public_compat -IC:/esp/esp-idf/components/esp32/include -IC:/esp/esp-idf/components/xtensa/include -IC:/esp/esp-idf/components/xtensa/esp32/include -IC:/esp/esp-idf/components/driver/include -IC:/esp/esp-idf/components/driver/esp32/include -IC:/esp/esp-idf/components/esp_pm/include -IC:/esp/esp-idf/components/esp_ringbuf/include -IC:/esp/esp-idf/components/efuse/include -IC:/esp/esp-idf/components/efuse/esp32/include -IC:/esp/esp-idf/components/vfs/include -IC:/esp/esp-idf/components/esp_wifi/include -IC:/esp/esp-idf/components/esp_event/include -IC:/esp/esp-idf/components/esp_netif/include -IC:/esp/esp-idf/components/esp_eth/include -IC:/esp/esp-idf/components/tcpip_adapter/include -IC:/esp/esp-idf/components/esp_phy/include -IC:/esp/esp-idf/components/esp_phy/esp32/include -IC:/esp/esp-idf/components/esp_ipc/include -IC:/esp/esp-idf/components/app_trace/include -IC:/esp/esp-idf/components/esp_timer/include -IC:/esp/esp-idf/components/mbedtls/port/include -IC:/esp/esp-idf/components/mbedtls/mbedtls/include -IC:/esp/esp-idf/components/mbedtls/esp_crt_bundle/include -IC:/esp/esp-idf/components/app_update/include -IC:/esp/esp-idf/components/spi_flash/include -IC:/esp/esp-idf/components/bootloader_support/include -IC:/esp/esp-idf/components/nvs_flash/include -IC:/esp/esp-idf/components/pthread/include -IC:/esp/esp-idf/components/esp_gdbstub/include -IC:/esp/esp-idf/components/esp_gdbstub/xtensa -IC:/esp/esp-idf/components/esp_gdbstub/esp32 -IC:/esp/esp-idf/components/espcoredump/include -IC:/esp/esp-idf/components/espcoredump/include/port/xtensa -IC:/esp/esp-idf/components/wpa_supplicant/include -IC:/esp/esp-idf/components/wpa_supplicant/port/include -IC:/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include -IC:/esp/esp-idf/components/ieee802154/include -IC:/esp/esp-idf/components/console -IC:/esp/esp-idf/components/mdns/include -IC:/esp/esp-idf/components/esp_adc_cal/include -IC:/esp/esp-idf/components/bt/common/osi/include -IC:/esp/esp-idf/components/bt/include/esp32/include -IC:/esp/esp-idf/components/bt/common/api/include/api -IC:/esp/esp-idf/components/bt/common/btc/profile/esp/blufi/include -IC:/esp/esp-idf/components/bt/common/btc/profile/esp/include -IC:/esp/esp-idf/components/bt/host/bluedroid/api/include/api -IC:/esp/esp-idf/components/protobuf-c/protobuf-c -IC:/esp/esp-idf/components/nghttp/port/include -IC:/esp/esp-idf/components/nghttp/nghttp2/lib/includes -IC:/esp/esp-idf/components/esp_http_server/include -IC:/esp/esp-idf/components/protocomm/include/common -IC:/esp/esp-idf/components/protocomm/include/security -IC:/esp/esp-idf/components/protocomm/include/transports -IC:/esp/esp-idf/components/json/cJSON -IC:/esp/esp-idf/components/wifi_provisioning/include -IC:/esp/esp-idf/components/wear_levelling/include -IC:/esp/esp-idf/components/sdmmc/include -IC:/esp/esp-idf/components/fatfs/diskio -IC:/esp/esp-idf/components/fatfs/vfs -IC:/esp/esp-idf/components/fatfs/src -IC:/esp/esp-idf/components/spiffs/include -IC:/esp/esp-idf/components/openssl/include -IC:/esp/esp-idf/components/esp_hid/include -I../components/arduino/variants/esp32 -I../components/arduino/cores/esp32 -I../components/arduino/libraries/ArduinoOTA/src -I../components/arduino/libraries/AsyncUDP/src -I../components/arduino/libraries/BLE/src -I../components/arduino/libraries/BluetoothSerial/src -I../components/arduino/libraries/DNSServer/src -I../components/arduino/libraries/EEPROM/src -I../components/arduino/libraries/ESP32/src -I../components/arduino/libraries/ESPmDNS/src -I../components/arduino/libraries/FFat/src -I../components/arduino/libraries/FS/src -I../components/arduino/libraries/HTTPClient/src -I../components/arduino/libraries/HTTPUpdate/src -I../components/arduino/libraries/LittleFS/src -I../components/arduino/libraries/NetBIOS/src -I../components/arduino/libraries/Preferences/src -I../components/arduino/libraries/RainMaker/src -I../components/arduino/libraries/SD_MMC/src -I../components/arduino/libraries/SD/src -I../components/arduino/libraries/SimpleBLE/src -I../components/arduino/libraries/SPIFFS/src -I../components/arduino/libraries/SPI/src -I../components/arduino/libraries/Ticker/src -I../components/arduino/libraries/Update/src -I../components/arduino/libraries/USB/src -I../components/arduino/libraries/WebServer/src -I../components/arduino/libraries/WiFiClientSecure/src -I../components/arduino/libraries/WiFi/src -I../components/arduino/libraries/WiFiProv/src -I../components/arduino/libraries/Wire/src -IC:/esp/esp-idf/components/esp_https_ota/include -IC:/esp/esp-idf/components/esp_http_client/include -IC:/esp/esp-idf/components/asio/asio/asio/include -IC:/esp/esp-idf/components/asio/port/include -IC:/esp/esp-idf/components/cbor/port/include -IC:/esp/esp-idf/components/unity/include -IC:/esp/esp-idf/components/unity/unity/src -IC:/esp/esp-idf/components/cmock/CMock/src -IC:/esp/esp-idf/components/coap/port/include -IC:/esp/esp-idf/components/coap/libcoap/include -IC:/esp/esp-idf/components/esp-tls -IC:/esp/esp-idf/components/esp-tls/esp-tls-crypto -IC:/esp/esp-idf/components/tcp_transport/include -IC:/esp/esp-idf/components/esp_lcd/include -IC:/esp/esp-idf/components/esp_lcd/interface -IC:/esp/esp-idf/components/esp_local_ctrl/include -IC:/esp/esp-idf/components/esp_serial_slave_link/include -IC:/esp/esp-idf/components/esp_websocket_client/include -IC:/esp/esp-idf/components/expat/expat/expat/lib -IC:/esp/esp-idf/components/expat/port/include -IC:/esp/esp-idf/components/freemodbus/common/include -IC:/esp/esp-idf/components/idf_test/include -IC:/esp/esp-idf/components/idf_test/include/esp32 -IC:/esp/esp-idf/components/jsmn/include -IC:/esp/esp-idf/components/libsodium/libsodium/src/libsodium/include -IC:/esp/esp-idf/components/libsodium/port_include -IC:/esp/esp-idf/components/mqtt/esp-mqtt/include -IC:/esp/esp-idf/components/perfmon/include -IC:/esp/esp-idf/components/ulp/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/esp/myProjects/a2dp_gatts_coex=. -fmacro-prefix-map=C:/esp/esp-idf=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu++11 -fno-exceptions -fno-rtti -D_GNU_SOURCE -DIDF_VER=\"v4.4-dev-3657-gdf0929009a\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -DARDUINO=10812 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 -DARDUINO_BOARD=\"ESP32_DEV\" -DARDUINO_VARIANT=\"esp32\" -DESP32 -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/PulseSensorPlayground.cpp.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\PulseSensorPlayground.cpp.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/PulseSensorPlayground.cpp.obj -c ../main/PulseSensorPlayground.cpp
../main/PulseSensorPlayground.cpp:199:6: error: no declaration matches 'void PulseSensorPlayground::setSerial(Stream&)'     
 void PulseSensorPlayground::setSerial(Stream &output) {
      ^~~~~~~~~~~~~~~~~~~~~
../main/PulseSensorPlayground.cpp:199:6: note: no functions named 'void PulseSensorPlayground::setSerial(Stream&)'
In file included from ../main/PulseSensorPlayground.cpp:17:
../main/PulseSensorPlayground.h:126:7: note: 'class PulseSensorPlayground' defined here
 class PulseSensorPlayground {
       ^~~~~~~~~~~~~~~~~~~~~
[7/13] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/utility/PulseSensor.cpp.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by olsonap** [comment]
Nevermind. User error. Accidentally deleted an entire function somehow.
