### ISSUE TITLE
Dreaded ssl->need_bytes error (again)

### ISSUE THREAD

**Issue by mischmerz** [esp8266/Arduino#7074]
We have a number of older ESP devices hardwired in a building. Those use arduino-PR-beta1.9-BUILD-37 and related libraries. At the time we deployed them, the OTA seemed to work just fine. We needed to send an OTA update and .. well .. it failed. 

What IS weird is that we even re-installed an old backup and flashed it so that we are able to experiment.

GET /ota/1.25/plug-hw8012-14-0-2-13.bin HTTP/1.0
Host: lumosur.local:8080
User-Agent: ESP8266-http-Update
Connection: close
x-ESP8266-STA-MAC: DC:4F:22:4D:BB:62
x-ESP8266-AP-MAC: DE:4F:22:4D:BB:62
x-ESP8266-free-space: 638976
x-ESP8266-sketch-size: 387728
x-ESP8266-sketch-md5: 6dd312f2e9c80143580adad78ad42efd
x-ESP8266-chip-size: 1048576
x-ESP8266-sdk-version: 2.2.1(cfd48f3)
x-ESP8266-mode: sketch

-----
[HTTP-Client][handleHeaderResponse] RX: 'HTTP/1.0 200 OK'
[HTTP-Client][handleHeaderResponse] RX: 'Connection: close'
[HTTP-Client][handleHeaderResponse] RX: 'Date: Tue, 11 Feb 2020 04:50:38 GMT'
[HTTP-Client][handleHeaderResponse] RX: 'Server: Lumosur HA V0.1'
[HTTP-Client][handleHeaderResponse] RX: 'Cache-Control: no-cache, must-revalidate'
[HTTP-Client][handleHeaderResponse] RX: 'Content-Type: application/binary'
[HTTP-Client][handleHeaderResponse] RX: 'Expires: Sat, 28 Nov 2009 05:36:25 GMT'
[HTTP-Client][handleHeaderResponse] RX: 'Content-Length: 383712'
[HTTP-Client][handleHeaderResponse] RX: ''
[HTTP-Client][handleHeaderResponse] code: 200
[HTTP-Client][handleHeaderResponse] size: 383712
ssl->need_bytes=8240 > 6859

It looks to me as if the SSL negotiation went fine (as we have  the server's response), but we are unable to send the update. Which is a bummer as it would be a lot of work to pull all switches from the walls.

Any ideas how to get the update onto the devices?
Michaela

**Comment by devyte** [comment]
@mischmerz we follow a format for issues here, which you saw in the issue template when opening this. It requires specific information.
Closing due to not compliant. 
Please open a new issue and fill out the template.
