### ISSUE TITLE
Can't connect to the wifi network of ESP8266 microcontroller

### ISSUE THREAD

**Issue by SteliosLL** [esp8266/Arduino#7086]
I recently bought an ESP8266 microcontroller. I want to use it to control a lightbulb in my house via wifi. I wrote some code and then uploaded it on the board. It is a Soft Access Point. It worked the first time. The second time, windows said that it failed to connect, the third time, same results. I tried many times. I searched for potential fixes but nothing worked. Sometimes i won't be able to connect to it, sometimes i will connect it but windows will say that im connected with restricted access. I bought a second ESP8266 because i thought that it was problematic. But i had the same problems with the second one. This happens to all my devices
Sorry for my bad english

**Comment by devyte** [comment]
This is not a general support forum. This is an issue tracker, meant for tracking issues in the core. Please refer to a community forum like esp8266.com or stackoverflow.
Closing due to not compliant.
