### ISSUE TITLE
Wire.begin() doesn't initialize the SDA 20 and SCL 21 of arduino due 

### ISSUE THREAD

**Issue by rafaccount123** [esp8266/Arduino#7094]
Hello,

I try to communicate between the arduino due and the VEML6030 of sparkfun via the pins SDA 20 and SCL 21. But when I write Wire.begin() and try to communicate in I2C via SDA 20 and SCL 21 between the VEML6030 and the arduino due I can't. The connections are fine and the VEML6030 and the arduino due are well powered. 

Maybe there is an issue on the library for the arduino due to use SDA 20 and SCL 21.

Thanks for the help.

**Comment by devyte** [comment]
I think you're in the wrong place, this repo is for the esp8266 Arduino core and has nothing to do with the Due.
Closing.
