### ISSUE TITLE
PR #6887 generates execptions in Project Tasmota

### ISSUE THREAD

**Issue by Jason2866** [esp8266/Arduino#7103]
#### Platform
-  device                                 |ESP01 ]
- Core Version:			[latest git]
- Development Env:		[Platformio]
- Operating System:		[Windows|Linux]

### Settings in IDE

- Module:  			[|Nodemcu|other]
- Flash Mode:			[DOUT]
- Flash Size: 		[1MB]
- lwip Variant:   [v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

Tasmota does generate exceptions when using latest git.

Reverting https://github.com/esp8266/Arduino/pull/6887 does solve the issue.
Without this and using all other PR until to the latest Tasmota does not generate exceptions anymore.

**Comment by d-a-v** [comment]
Can you give more details ?
When and what exceptions ?

**Comment by Jason2866** [comment]
@d-a-v  exceptions 3 and 9 right after device comes up.

GOOD NEWS. Tried PR #7096 and this seems to solve. Test device now 5 minutes up. 
no exception and responsive as it is with core 2.6.1

So the PR #7096 should be merged ASAP

**Comment by arendst** [comment]
Verified too that #7096 fixes this issue.
