### ISSUE TITLE
Debounce interrupt (can't use delay)

### ISSUE THREAD

**Issue by charsome** [esp8266/Arduino#711]
I normally use a 300ms delay in my interrupts to debounce. In the ESP8266 Arduino firmware it's not possible to use a delay inside an interrupt function (crash -> reboot). How can i debounce my input (software)?

**Comment by Juppit** [comment]
In Readme.md you find this link to documention:
http://arduino.esp8266.com/stable/doc/reference.html

There you find instruction for the Ticker libaray, which is somehow an 
iterrupt routine like yours:

"It is currently not recommended to do blocking IO operations (network, 
serial, file) from Ticker callback functions. Instead, set a flag inside 
the ticker callback and check for that flag inside the loop function."
