### ISSUE TITLE
My Gsm is only response on  rx pin and d8 pin 

### ISSUE THREAD

**Issue by jenil163** [esp8266/Arduino#7111]
Details of my device 

esptool.py v2.8
Serial port COM3
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0341
Compressed 310224 bytes to 224898...

Also the time of load I want to remove the d8 pin any solution?

**Comment by earlephilhower** [comment]
Issue template ignored, and problem doesn't seem to be anything with the core.  Closing.  Please use https://www.esp8266.com or https://gitter.im/esp8266/Arduino for general help with your apps.
