### ISSUE TITLE
A part of my nodemcu code is not working

### ISSUE THREAD

**Issue by ameyadalvi99** [esp8266/Arduino#7113]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ x] I have tested that the issue is present in current master branch (aka latest git).
- [x ] I have searched the issue tracker for a similar issue.
- [x ] If there is a stack dump, I have decoded it.
- [x ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12|ESP-01|ESP-07|ESP8285 device|other]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE|Platformio|Make|other]
- Operating System:		[Windows|Ubuntu|MacOS]

### Settings in IDE

- Module:  			[Generic ESP8266 Module|Wemos D1 mini r2|Nodemcu|other]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

Arduino uno with a DHT11 sends data via UART to the nodemcu. The data sending format is<data> The nodemcu reads the data successfully and uploads the data to firebase.
The problem starts when the nodemcu tries to read data from firebase. The following part of the code does not execute. 
 
 threshold =Firebase.getInt(fireThreshold);
  if (Firebase.failed()) {
      Serial.print("pushing /logs failed:3");
      Serial.println(Firebase.error());  
      return;
  }
  delay(10);
  if(int(volume)>>threshold)
  {
   Firebase.setString(fireSolenoid,"off");
    if (Firebase.failed()) {
      Serial.print("pushing /logs failed:4");
      Serial.println(Firebase.error());  
      return;
  }
    Serial.print("*********Threshold Reached...Please Recharge********");
    Serial.println(threshold);
    }
    else
    {
      Firebase.setString(fireSolenoid,"on");
      if (Firebase.failed()) {
      Serial.print("pushing /logs failed:5");
      Serial.println(Firebase.error());  
      return;
  }
      Serial.print("\nThreshold :");
      Serial.print(threshold);
//    delay(10);

I belive particularly this part does not work.
 if(int(volume)>>threshold).Please tell me what mistake i am doing.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <ESP8266WiFi.h>
#include <FirebaseArduino.h>
#include<SoftwareSerial.h>
SoftwareSerial msp(D2,D3);

const byte numChars = 20;
char receivedChars[numChars];

boolean newData = false;
int integer1 = 0;

// Set these to run example.
//#define FIREBASE_HOST "mam-course-project.firebaseio.com" // for testing 
//#define FIREBASE_AUTH "BDPvXVIXR49ttCuPm75sOBQPoBxJa3q5frjR2Kdq"// for testing
#define FIREBASE_HOST "smart-water-meters.firebaseio.com" // for main project
#define FIREBASE_AUTH "0GcHSJQb7SCnvBYtrVPUlz3to5z4PnwMypt1O8qK"// for main project

#define WIFI_SSID "ameya"
#define WIFI_PASSWORD "ameya123"
int n = 0;

String solenoid=""; // variable for solenoid valve
int threshold;
int volume ;
String myString;

void setup() 
{
  Serial.begin(9600);
  delay(10);
  msp.begin(9600);
  delay(10);
  pinMode(D6,OUTPUT);

  // connect to wifi.
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("connecting");
  while (WiFi.status() != WL_CONNECTED) 
  {
    Serial.print(".");
    delay(500);
  }
  Serial.println();
  Serial.print("connected: ");
  Serial.println(WiFi.localIP());
  
  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
 }

void loop()
{
  String fireSolenoid= String("Provider_1/Flat_1/Solenoid");
  String fireThreshold= String("Provider_1/Flat_1/Threshold");
  String fireVolume= String("Provider_1/Flat_1/Volume"); 

    solenoid = Firebase.getString(fireSolenoid);
    delay(10);
    if (Firebase.failed()) {
      Serial.print("pushing /logs failed:1");
      Serial.println(Firebase.error());  
      return;
  }

    if(solenoid=="on")
  {
    Serial.print("\n solenoid ON");
    digitalWrite(D6,HIGH);
//    delay(10);
  }
   else if(solenoid=="off")
   {
    Serial.println("\n solenoid OFF");
    digitalWrite(D6,HIGH);
//    delay(10);
   }
    else
    {
    Serial.println("Wrong Credential! Please send on/off");
    } 
    
    static boolean recvInProgress = false;
    static byte ndx = 0;
    char startMarker = '<';
    char endMarker = '>';
    byte rc;
    char * strtokIndx;
    
       while (msp.available() > 0 && newData == false)
       {
        rc = msp.read();
        if (recvInProgress == true) 
        {
          if (rc != endMarker)
           {
             receivedChars[ndx] = rc;
             ndx++;
             if (ndx >= numChars)
             {
                ndx = numChars - 1;
              }
            }
            else
            {
                receivedChars[ndx] = '\0'; // terminate the string
                recvInProgress = false;
                ndx = 0;
                newData = true;
                /*separate the data*/
                strtokIndx = strtok(receivedChars,",");
                integer1 = atoi(strtokIndx);
             }
        }

        else if (rc == startMarker) {
            recvInProgress = true;
        }
    }
    
   if (newData == true)
  {
  newData = false;
  volume=integer1;
  }

    myString = String(volume); 
  Serial.print("\nVolume :");
  Serial.print(myString); 
  delay(10);
  Firebase.setString(fireVolume,myString);           
  if (Firebase.failed()) {
      Serial.print("setting /number failed:2 ");
      Serial.println(Firebase.error());  
      return;
  } 
  
   
  threshold =Firebase.getInt(fireThreshold);
  if (Firebase.failed()) {
      Serial.print("pushing /logs failed:3");
      Serial.println(Firebase.error());  
      return;
  }
  delay(10);
  if(int(volume)>>threshold)
  {
   Firebase.setString(fireSolenoid,"off");
    if (Firebase.failed()) {
      Serial.print("pushing /logs failed:4");
      Serial.println(Firebase.error());  
      return;
  }
    Serial.print("*********Threshold Reached...Please Recharge********");
    Serial.println(threshold);
    }
    else
    {
      Firebase.setString(fireSolenoid,"on");
      if (Firebase.failed()) {
      Serial.print("pushing /logs failed:5");
      Serial.println(Firebase.error());  
      return;
  }
      Serial.print("\nThreshold :");
      Serial.print(threshold);
//    delay(10);
      }
    
   // append a new value to /logs
  String name = Firebase.pushInt("logs", n++);
  // handle error
  if (Firebase.failed()) {
      Serial.print("pushing /logs failed:6");
      Serial.println(Firebase.error());  
      return;
  }
  Serial.print("\n pushed: /logs/");
  Serial.print(name);
  delay(10);
}
```

### Debug Messages

```
Debug messages go here
```

**Comment by devyte** [comment]
This is not the right place to ask for help with your particular project. This is an issue tracker, meant for tracking issues in the core hosted in the repo. For general support please refer to a community forum like esp8266.com or stackoverflow.
Closing due to not compliant.
