### ISSUE TITLE
Burn files to FS filesystem

### ISSUE THREAD

**Issue by robertgregor** [esp8266/Arduino#713]
Hello, I want to store some static webpages in the new filesystem. How can I burn some files, which exist on my PC to the new filesystem? Is there any tool, which pack / compress it  and create a bin, which can be then burn?

**Comment by igrr** [comment]
You have already asked this question in another ticket: https://github.com/esp8266/Arduino/issues/374#issuecomment-110032945
Let's move the discussion there.
