### ISSUE TITLE
HostByNameAsync

### ISSUE THREAD

**Issue by hzhh110** [esp8266/Arduino#7135]
你好,你是不是有解决异步请求的方法呢?我这边遇到的问题跟你描述的一样,我也是有些数据需要mqtt 有些数据需要进行http post请求 HostByNameAsync 您有进行优化吗?

**Comment by hzhh110** [comment]
Hello, do you have a solution for asynchronous requests? The problem I encountered here is the same as what you described. I also need MQTT for some data and HTTP post request for HostByNameAsync. Have you optimized it?

**Comment by d-a-v** [comment]
@hzhh110 

> the same as what you described

Where is it described ?

**Comment by devyte** [comment]
We do not have an async hostByName at this time. Our functionality is mostly synchronous.
Closing due to not compliant.
