### ISSUE TITLE
 VSCode "Exit with code = 3"

### ISSUE THREAD

**Issue by luhua2018** [esp8266/Arduino#7153]
In VSCode, if the upload speed is set to greater than 115200 (such as 230400), the compilation will report "Exit with code = 3"; if it is adjusted small, it will be fine (such as 57600).

**Comment by Jason2866** [comment]
This is in no way related to Arduino Esp8266/Arduino
You have to open in PlatformIO github

**Comment by luhua2018** [comment]
It is newly discovered that this situation only occurs in projects that use "Serial.begin ()" to initialize the serial port. If the baud rate of the serial port is set to be the same as the upload baud rate in the code, it is no problem.
