### ISSUE TITLE
Support ESP8285 (2MB flash)

### ISSUE THREAD

**Issue by mcmega** [esp8266/Arduino#7161]
Hello!
I have ESP8285 installed with 2MB flash (new version of chips).
I understand you need to edit the file boards.txt
How to make support for these chips?

**Comment by d-a-v** [comment]
`tools/boards.txt.py` needs to be updated (it generates `boards.txt`)
I wasn't aware of this new version, that's nice

**Comment by TD-er** [comment]
Hmm that's a nice development.
What products do use this new version and how can we distinguish them?

**Comment by Tech-TX** [comment]
If it's as simple as this in boards.txt.py, I can do a quick PR for it:
```
    ( 'esp8285', {
        'name': 'Generic ESP8285 Module',
        'opts': {
            '.build.board': 'ESP8266_ESP01',
            '.build.variant': 'esp8285'
            },
        'macro': [
            'resetmethod_menu',
            'resetmethod_menu_extra',
            'crystalfreq_menu',
            'flashmode_dout',
            'flashfreq_40',
            '1M', '2M',  <<<
            'led',
            ],
```
I only have the N08 chips, so I can't verity it works correctly.

**Comment by mcmega** [comment]
ESP8285N08 - 1 MB (–40°C ~ 85°C)
ESP8285H08 - 1 MB (–40°C ~ 105°C)
ESP8285H16 - 2 MB (–40°C ~ 105°C)

**Comment by d-a-v** [comment]
@Tech-TX I guess you're right
Also #6690 would help to have flash-size agnostic sketches
