### ISSUE TITLE
node mcu not giving acess to internet

### ISSUE THREAD

**Issue by Eletroholic** [esp8266/Arduino#7168]
hello,
I am trying to use nodemcu as a wifi repeater.I am a beginner and had some basic concepts only 
I followed the .bin files given on github and than used a flash tool to upload it to node mcu now a new wifi network is created and i can connect to it but it is not giving access to internet 
Moreover now after uploading the code the windows doesn't recognize it and if i try to upload again a .bin file it says a "COM error"
please help me

**Comment by d-a-v** [comment]
Please read https://arduino-esp8266.readthedocs.io/en/latest/faq/readme.html

**Comment by devyte** [comment]
Closing due to not compliant.
