### ISSUE TITLE
No such file or directory:'../package/package_esp8266com_index.template.json'

### ISSUE THREAD

**Issue by vigiles** [esp8266/Arduino#7176]
$ pwd
/Applications/Arduino.app/Contents/Java/hardware/esp8266com/esp8266/tools
$ python3 get.py 
Platform: x86_64-apple-darwin
Traceback (most recent call last):
  File "get.py", line 131, in <module>
    main()
  File "get.py", line 125, in main
    tools_to_download = load_tools_list('../package/package_esp8266com_index.template.json', identify_platform())
  File "get.py", line 92, in load_tools_list
    tools_info = json.load(open(filename))['packages'][0]['tools']
FileNotFoundError: [Errno 2] No such file or directory: '../package/package_esp8266com_index.template.json'
$
-=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=--=-=-=-=-
Can i use https://github.com/esp8266/Arduino/releases/download/2.6.3/package_esp8266com_index.json to replace it ?

**Comment by devyte** [comment]
You seem to have an installation issue. I suggest doing a clean install from scratch.
Closing for now.
