### ISSUE TITLE
warning: espcomm_sync failed error: espcomm_open failed esp8266-01 wifi module

### ISSUE THREAD

**Issue by jaysuthar743** [esp8266/Arduino#7177]
I am using 1.8.10 Arduino IDE with the esp8266-01 wifi module and Arduino Uno. I just want to upload simple program but I always get the error:

warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

Connection:
Arduino Uno -----  esp
Tx --- Rx
Rx --- Tx
5v --- ch_pd
5v --- VCC
GND --- GPIO 0
GND --- GND
  
I have tried some changes in connection but that didn't work for me:
1) 3.3v for VCC and ch_pd.
2) reset pin of Arduino to reset pin of esp and also to GND pin of esp.
3) Rx to Rx and Tx to Tx.

Note: I don't have any external power supply or resistor. 
Please help me to get rid of this error. Correct me if my connections are wrong.

**Comment by devyte** [comment]
The espcomm errors are documented.
Closing.
