### ISSUE TITLE
Can't make ANY HTTP GET request

### ISSUE THREAD

**Issue by ireun** [esp8266/Arduino#7181]
# Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have searched the issue tracker for a similar issue.
- [x] I have filled out all fields below.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have tested that the issue is present in current master branch (aka latest git).

#### Platform

- Hardware:				ESP-12E
- Core Version:			2.6.3
- Development Env:		Visual Micro ( Ardunio IDE )
- Operating System:		Windows

### Settings in IDE
![](https://i.imgur.com/YClZe9S.png)

### Problem Description

I've tried the minimal sketch from the example, linked below, unfortunately i can't connect at all.. Could you please update the example so it would actually work? 

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266HTTPClient/examples/BasicHttpClient/BasicHttpClient.ino 

### Debug Messages

```
[HTTP] begin...
[HTTP-Client][begin] url: http://jigsaw.w3.org/HTTP/connection.html
[HTTP-Client][begin] host: jigsaw.w3.org port: 80 url: /HTTP/connection.html
[HTTP] GET...
[HTTP-Client][sendRequest] type: 'GET' redirCount: 0
[HTTP-Client] failed connect to jigsaw.w3.org:80
[HTTP-Client][returnError] error(-1): connection refused
[HTTP] GET... failed, error: connection refused
[HTTP-Client][end] tcp is closed
```

**Comment by Tech-TX** [comment]
From the error,  you haven't edited the example.  You asked for nothing,  and got nothing in return.  
https://www.tutorialspoint.com/http/http_requests.htm
Google Is Your Friend

**Comment by MarkyAD** [comment]
The error is "connection refused". Both the example and the url work here without issue, can't reproduce.

**Comment by ireun** [comment]
Finally got it to work. Though I have no idea what was wrong there. Thanks and sorry. :)
