### ISSUE TITLE
I wasn't able to connect to the ESP8266 ESP-12F.

### ISSUE THREAD

**Issue by oguzhansari** [esp8266/Arduino#7199]
Hello,

This is the first time I am using a wifi module.
Cannot find a port in the installation process.
All details are available in the pictures.
My English is not good. I used Google translate.

Error;
`Arduino: 1.8.12 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), no dtr (aka ck), 26 MHz, 40MHz, DIO, 1MB (FS:512KB OTA:~246KB), 0, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Executable segment sizes:

IROM   : 231892          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 26908   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 

DATA   : 1252  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 712   ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 24928 )         - zeroed variables      (global, static) in RAM/HEAP 

Sketch uses 260764 bytes (52%) of program storage space. Maximum is 499696 bytes.
Global variables use 26892 bytes (32%) of dynamic memory, leaving 55028 bytes for local variables. Maximum is 81920 bytes.
esptool.py v2.8
Serial port COM5
Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
  File "C:\Users\OSPC\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "C:/Users/OSPC/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.3/tools/esptool\esptool.py", line 2890, in main
    esp.connect(args.before)
  File "C:/Users/OSPC/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.3/tools/esptool\esptool.py", line 483, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

_

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

![resim-1](https://user-images.githubusercontent.com/13555457/78743244-c2337a00-7966-11ea-8f38-bacf91a835ea.JPG)
![resassa](https://user-images.githubusercontent.com/13555457/78743401-31a96980-7967-11ea-8a56-e2c019b3070d.JPG)

![20200408_064454](https://user-images.githubusercontent.com/13555457/78743256-c5c70100-7966-11ea-9538-e40d482db614.jpg)
![20200408_064416](https://user-images.githubusercontent.com/13555457/78743260-c790c480-7966-11ea-9078-793a896225c8.jpg)

**Comment by devyte** [comment]
This is an issue tracker, meant for tracking issues in the core code hosted here. This is not meant for general support questions or requests for help. Please refer to a community forum like esp8266.com or stackoverflow for that.
Closing due to not compliant.
