### ISSUE TITLE
Heap problem with WPS - WiFi.beginWPSConfig()

### ISSUE THREAD

**Issue by Socket2000** [esp8266/Arduino#7220]
It seems to be an issue with the use of WiFi.beginWPSConfig() when the heap has a free memory lower than a certain amount. After many test i found that in my large code, that is using many ram and left about 10000..14000 bytes free, a call to WiFi.beginWPSConfig() never connect to router. It find the ssid but not the shared password so it fails to connect. After resizing String allocation escluding some, obtaining about 20000..23000 bytes free, the  function success.

**Comment by devyte** [comment]
Issue template ignored, no version information, no mcve.
Closing due to not compliant. 
Please open a new issue and follow the issue template instructions.
