### ISSUE TITLE
[hostByName] Host:... lookup error: -5

### ISSUE THREAD

**Issue by jboudreau77** [esp8266/Arduino#7224]
Thanks in advance:
Trying to re-create project (https://www.electroniclinic.com/nodemcu-firebase-database-tutorial/#Programming)

Using FirebaseArduino.h and ArduinoJson.h (5.13.1)
No problem compiling, but unable to connect to firebaseio.com
Verified my fingerprint. . .Any thoughts would greatly be appreciated.

Debug Info:
connected: 10.0.0.93
[HTTP-Client][begin] host: https://electronicclinic-897b6.firebaseio.com/ port: 443 url: /Variable/Value.json?auth=Pz0oinU7kqz2unlUqblahblahx22IVyONcHOHMR7 httpsFingerprint: 03:D6:42:23:03:D1:0C:06:73:F7:E2:BD:29:47:13:C3:22:71:37:1B
[HTTP-Client][sendRequest] type: 'PUT' redirCount: 0
[hostByName] request IP for: https://electronicclinic-897b6.firebaseio.com/
[hostByName] Host: https://electronicclinic-897b6.firebaseio.com/ lookup error: -5!
[HTTP-Client] failed connect to https://electronicclinic-897b6.firebaseio.com/:443
[HTTP-Client][returnError] error(-1): connection refused
[HTTP-Client][returnError] error(-4): not connected

code:
#include <ESP8266WiFi.h>
#include <SoftwareSerial.h>
#include <FirebaseArduino.h>
#include <ArduinoJson.h>
 #include <ESP8266HTTPClient.h>
 
// Set these to run example.
#define FIREBASE_HOST "https://electronicclinic-897b6.firebaseio.com/"
#define FIREBASE_AUTH "Pz0oinU7kqz2unlUqblahblahx22IVyONcHOHMR7"
#define WIFI_SSID "PurplePanda"
#define WIFI_PASSWORD "catbear74"
 
String myString;
int vr = A0; // variable resistor connected 
int sdata = 0; // The variable resistor value will be stored in sdata.
 
void setup()
{
  // Debug console
  Serial.begin(9600);
  pinMode(vr ,INPUT);
  // connect to wifi.
  pinMode(D0,OUTPUT);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("connecting");
  while (WiFi.status() != WL_CONNECTED)
      {
    Serial.print(".");
    delay(500);
      }
  Serial.println();
  Serial.print("connected: ");
  Serial.println(WiFi.localIP());
  
  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
 
   Firebase.setString("Variable/Value","fahad");
}
 
void loop()
{
 
sdata = analogRead(vr);
myString = String(sdata); 
Serial.println(myString); 
delay(1000);            
}

**Comment by devyte** [comment]
This isn't the right place to request help, especially not for 3rd party libraries. I suggest you ask at the Firebase repo, which I think is [this one](https://github.com/FirebaseExtended).
Also, issue template ignored.
Closing due to not compliant.
