### ISSUE TITLE
creating a FS file, an onDisconnect event is fired.

### ISSUE THREAD

**Issue by olonsoft** [esp8266/Arduino#7225]
I am creating an app that uses wifi events (on Connect, on Disconnect etc). 
When my app starts, defines the wifi event functions and then load some settings from SPIFFS. If the settings file does not exist, it creates it with default values.
To test my program, I later trigger an action to delete this file. When I reset my ESP, as soon as the file is created, an onDisconnect event is fired.
I printed the values of `WiFiEventStationModeDisconnected& event` which are:
```
ssid: XXXXXXXX
bssid: 00:00:00:00:00:00
Reason: No AP found
```
Note that `WiFi.begin` is after this file is loaded.
Did anybody experience this?

**Comment by earlephilhower** [comment]
This is not the forum for "How do I ..." questions, as the template said.  Please use https://gitter.im/esp8266/Arduino or https://www.esp8266.com for such questions.
