### ISSUE TITLE
esp8266_OTA update using httpupdate

### ISSUE THREAD

**Issue by sowmimalu** [esp8266/Arduino#7250]
Hi,
i am using esp8266 development board...i am trying to download a file from local server by using http..
In my application i need to update ota in esp8266 by using http....
I got an example in arduino (webupdater) when i tried with this example web page has opened and i am able to choose a bin file which i want ,from that i can able to update the bin file by OTA.

Now i need to download a file in my source code by using http ...i tried basic example in ardunio (httpupdate) but its not work ...i got connection refused error ....when I tried to download a bin file from local server.

can you please suggest me.. to how to download a file by http from my local server..

i am using arduino for esp8266
For this i am using following example
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266httpUpdate/examples/httpUpdate/httpUpdate.ino

it is always showing error, tried with system IP as below command
http://ip/new/hello_world.bin

**Comment by devyte** [comment]
This is a "how do I" type question. The issue template you saw when opening this clearly says that this isn't the right place to ask that. Please seek such help at a community forum like esp8266.com or stackoverflow.
Closing due to not compliant.
