### ISSUE TITLE
ESP8266 ESP-201 Can't' read SPIFFS Data 

### ISSUE THREAD

**Issue by rserroyen** [esp8266/Arduino#7282]
### Basic Infos

- [] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [] I have tested that the issue is present in current master branch (aka latest git).
- [] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [] I have filled out all fields below.

#### Platform

- Hardware:					ESP-201
- Core Version:			??
- Development Env:		Arduino IDE
- Operating System:		Windows|

### Settings in IDE

- Module:  			Generic ESP8266 Modul|
- Flash Mode:			dio
- Flash Size: 		1MB
- lwip Variant:   [v2 Lower Memory|Higher Bandwidth
- Reset Method:		dtr
- Flash Frequency:	40Mh
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   115200

### Problem Description

Hello
I changed index.html, style.css in / data
When I execute the code with the remarks "/ * * /"
you're fine he recognizes Flash.

But with the remarks he does not recognize the SPIFF

Why ??

Thank you

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <ESP8266WiFi.h>
#include <FS.h>   //Include File System Headers
 
const char* filename = "/samplefile.txt";

void setup(void) {
  Serial.begin(115200);
  while (!Serial){}  // papy Tirrer çà quand tout est bon
  Serial.println("\n");

  uint32_t realSize = ESP.getFlashChipRealSize();
  uint32_t ideSize = ESP.getFlashChipSize();
  FlashMode_t ideMode = ESP.getFlashChipMode();

  Serial.printf("Flash real id:   %08X\n", ESP.getFlashChipId());
  Serial.printf("Flash real size: %u bytes\n\n", realSize);

  Serial.printf("Flash ide  size: %u bytes\n", ideSize);
  Serial.printf("Flash ide speed: %u Hz\n", ESP.getFlashChipSpeed());
  Serial.printf("Flash ide mode:  %s\n", (ideMode == FM_QIO ? "QIO" : ideMode == FM_QOUT ? "QOUT" : ideMode == FM_DIO ? "DIO" : ideMode == FM_DOUT ? "DOUT" : "UNKNOWN"));

  if (ideSize != realSize) {
    Serial.println("Flash Chip configuration wrong!\n");
  } else {
    Serial.println("Flash Chip configuration ok.\n");
  }

//Initialize File System

/*SPIFFSConfig cfg;
cfg.setAutoFormat(false);
SPIFFS.setConfig(cfg);

Serial.println("SPIFFSConfig\n");

  if(SPIFFS.begin())
  {
    Serial.println("SPIFFS Initialize....ok");
  }
  else
  {
    Serial.println("SPIFFS Initialization...failed");
  }

  Dir dir = SPIFFS.openDir("/data");
while (dir.next()) {
    Serial.print(dir.fileName());
    if(dir.fileSize()) {
        File f = dir.openFile("r");
        Serial.println(f.size());
    }
}*/
}

void loop() {


  delay(5000);
}

```

### Debug Messages

```

with

Flash real id:   001440E0     
Flash real size: 1048576 bytes

Flash ide  size: 1048576 bytes
Flash ide speed: 26000000 Hz  
Flash ide mode:  DIO        
Flash Chip configuration ok.

without

;l␀d��|␀�$�|␃␄␌␄�␌d�␄c<ǃ␃�␛�{�c�␌b��og�l'o���␌#␜p��${$sdp�g�␐␂␄␌�␄l␄��␄␌␄c␌n�|␃l�$�␄c��g'�␀lćd`␂�␛␒'o␌$`␃␏␃g{���o␌␄�␃l`␃␏r��g␄␌�␃l`␃�s␌�x�␌d�s␇�`␃��n�␂;l␀l��|␀�d�|␂␄␌␌�␌d�␌c<��␃�␛�s�c�␌#��ng�lgn���␌c␜p��d{$sdp�g�␐␂␄␄�␄l␄��␄␌␄c␌n�|␃$�d�␄c��o'�␀l��d`␃�␛␒'o␌d`␃␎␃gs���o␌␄�␃$`␃␏r��g␄␌�␃l`␃�s␄�x�␌d�r␇�`␃��'�␂;l␀d��|␀�$�|␂␄␌␌�␌d�␌c<��␃�␛�{�c�␌#��ng�lgn���␌c␜p��${$sdp�g�␐␂␄␄�␄l␄��␄␌␄c␌n�|␃$�d�␄c��o'�␀l��d`␃�␛␒'o␌$`␃␎␃gs���o␌␄�␃$`␃␏r��g␄␌�␃l`␃�s␄�x�␌d�r␇�`␃��'�␂sd␀lܟ<␀�l�<␃␌␄␌�␄l�␌c|��␃�␓�r�#�␄c��gn�dog���␄c␜8��lrd;lx�o�␘␃␌␄�␌d␌��␌␄␌#␄g�|␃d�l�␌#��no�␀$��l ␃�␓␛g'␄l`␃␇␃o;Ǜ�'␄␌�␃d`␃␇{ۓo␌␄�␃$`␃�;␄�p�␄l�{␏�`␃��g�␃

```

**Comment by devyte** [comment]
With #7263 SPIFFS was deprecated in favor of LittleFS. We're not accepting issues related to SPIFFS any longer, unless they're accompanied by a proposed fix or enhancement.
Closing.
