### ISSUE TITLE
java.lang.nullpointerexception error when installing via board mngr

### ISSUE THREAD

**Issue by quietNightTime** [esp8266/Arduino#7325]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[2.5.1]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[dio]
- Flash Size: 		[4MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

I get a java.lang.nullpointerexception error when I want to install the ESP8266 via board manager. I had some conection issues yesterday and put downgraded to the 2.5.1 version that fixed the connetion issues but today there was this error.
I tried updating the ESP8266 to the new vesion and updating arduino, also reinstalled arduino nothing works.
I also tried to install it manually but then there was the python3 error. (fille didn't exist or something)

some pictures: (it says it's installed and it doesn't show up)

![image](https://user-images.githubusercontent.com/16447853/82763938-6f752b00-9e0b-11ea-99b9-cea2e2c76ef0.png)

![image](https://user-images.githubusercontent.com/16447853/82764030-40ab8480-9e0c-11ea-9dd5-177728b413cd.png)

**Comment by earlephilhower** [comment]
This isn't a core problem, it's very likely related to your specific Windows installation.

I suggest you quit all Arduino IDE instances, then blow away your `%LOCALAPPDATA%\Arduino15` directory along with your `%userprofile%\documents\Arduino` dir (rename or delete), uninstall the Arduino IDE, reinstall it, and try again.
