### ISSUE TITLE
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

### ISSUE THREAD

**Issue by sathiyaraj45** [esp8266/Arduino#7329]
Arduino: 1.8.12 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

env: python3: No such file or directory
exit status 127
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Arduino IDE version 1.8.12
Python version 3.8

**Comment by Tech-TX** [comment]
It's telling you how to solve you installation problem,  but you didn't read it:

>This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Googly31** [comment]
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Executable segment sizes:

ICACHE : 32768           - flash instruction cache 

IROM   : 271632          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 27449   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 

DATA   : 1520  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 1304  ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 26024 )         - zeroed variables      (global, static) in RAM/HEAP 

Sketch uses 301905 bytes (28%) of program storage space. Maximum is 1044464 bytes.

Global variables use 28848 bytes (35%) of dynamic memory, leaving 53072 bytes for local variables. Maximum is 81920 bytes.

esptool.py v3.0

Serial port COM6

Traceback (most recent call last):

  File "C:\Users\skc\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.2/tools/upload.py", line 66, in <module>

    esptool.main(cmdline)

  File "C:/Users/skc/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool\esptool.py", line 3551, in main

    esp = chip_class(each_port, initial_baud, args.trace)

  File "C:/Users/skc/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool\esptool.py", line 271, in __init__

    self._port = serial.serial_for_url(port)

  File "C:/Users/skc/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/pyserial\serial\__init__.py", line 90, in serial_for_url

    instance.open()

  File "C:/Users/skc/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/pyserial\serial\serialwin32.py", line 64, in open

    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))

serial.serialutil.SerialException: could not open port 'COM6': OSError(22, 'The semaphore timeout period has expired.', None, 121)

serial.serialutil.SerialException: could not open port 'COM6': OSError(22, 'The semaphore timeout period has expired.', None, 121)





This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by chiranjeevi751** [comment]
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Arduino, Primo, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Executable segment sizes:

ICACHE : 32768           - flash instruction cache 

IROM   : 231724          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 26797   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 

DATA   : 1496  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 876   ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 25608 )         - zeroed variables      (global, static) in RAM/HEAP 

Sketch uses 260893 bytes (24%) of program storage space. Maximum is 1044464 bytes.

Global variables use 27980 bytes (34%) of dynamic memory, leaving 53940 bytes for local variables. Maximum is 81920 bytes.

esptool.py v3.0

Serial port COM7

Connecting........_____....._____....._____....._____....._____....._____....._____

Traceback (most recent call last):

  File "C:\Users\Chiranjeevi\OneDrive\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.1/tools/upload.py", line 66, in <module>

    esptool.main(cmdline)

  File "C:/Users/Chiranjeevi/OneDrive/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 3552, in main

    esp.connect(args.before, args.connect_attempts)

  File "C:/Users/Chiranjeevi/OneDrive/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.1/tools/esptool\esptool.py", line 529, in connect

    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))

esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header



Invalid library found in C:\Users\Chiranjeevi\OneDrive\Documents\Arduino\libraries\Adafruit_GFX_Library: no headers files (.h) found in C:\Users\Chiranjeevi\OneDrive\Documents\Arduino\libraries\Adafruit_GFX_Library

Invalid library found in C:\Users\Chiranjeevi\OneDrive\Documents\Arduino\libraries\MikroMatrix-main: no headers files (.h) found in C:\Users\Chiranjeevi\OneDrive\Documents\Arduino\libraries\MikroMatrix-main



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by brayan-beltran** [comment]
Hola tenemos este error 

Arduino:1.8.19 (Windows Store 1.8.57.0) (Windows 10), Tarjeta:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

water_level_new_blynk:5:10: fatal error: LiquidCrystal_I2C.h: No such file or directory

compilation terminated.

exit status 1

LiquidCrystal_I2C.h: No such file or directory



Este informe podría contener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by elmejor507pty** [comment]
Arduino:1.8.19 (Windows Store 1.8.57.0) (Windows 10), Tarjeta:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from C:\Users\josué ramírez\Desktop\Nueva carpeta\estacion meteorologica\EstacionMeteorologicaYT\EstacionMeteorologicaYT.ino:8:

C:\Users\josu� ram�rez\Documents\Arduino\libraries\ubidots-mqtt-esp-master\src/UbidotsESPMQTT.h:30:10: fatal error: PubSubClient.h: No such file or directory

   30 | #include "PubSubClient.h"

      |          ^~~~~~~~~~~~~~~~

compilation terminated.

exit status 1

Error compilando para la tarjeta NodeMCU 1.0 (ESP-12E Module).



Este informe podría contener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

Ayuda por favor
