### ISSUE TITLE
can't find esp8266 via boardmanager

### ISSUE THREAD

**Issue by perlchamp** [esp8266/Arduino#7332]
hi there,
using arduino ide 1.8.12 opened preferences window and did enter https://arduino.esp8266.com/stable/package_esp8266com_index.json and https://arduino.esp8266.com/stable/package_esp8266com_index.json (comma separated) into the Additional Board Manager URLs field.
then i opened the boardmanager (Strg+Shift+I) and enter 'esp' in the search field. BUT I CAN'T FIND "esp8266 by ESP8266 Community". it's not listed. WHAT CAN I DO NOW ?
thanks in advance

**Comment by devyte** [comment]
Both links above seem to be the same.
Please seek such generic help at a community forum like esp8266.com or stackoverflow, this is not the right place to ask such questions. 
Closing due to not compliant.
