### ISSUE TITLE
Core  2.7.0 and 2.7.1 problem

### ISSUE THREAD

**Issue by szybkijanek** [esp8266/Arduino#7341]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[2.7.0 and 2.7.1]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Nodemcu]
- Flash Mode:			[dio]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200

### Problem Description

I have a problem with time display and device operation after installing core 2.7.0 and 2.7.1; On 2.6.3, I didn't have these problems. I use the Weather ThingPulse project and on new cores the time does not adapt to my current despite the time zone settings in the project, in the Bodmer weather project also after 10 minutes when the program is to download weather data the device resets by returning memory errors but only when the data are inserted into the memory SPIFFS. The same situations are on the 2nd laptop. I tried to reinstall Arduino but it did not help, re-upload the library but it is not. I am sure these problems are on the 2.7.0 and 2.7.1 cores; On 2.6.3, everything is ok
[errors.txt](https://github.com/esp8266/Arduino/files/4705533/errors.txt)

**Comment by earlephilhower** [comment]
The issue template was ignored, there is no MCVE, and the stack was not decoded.  Please read and follow the template directions to help us help you.

Nothing we can do here, closing.
