### ISSUE TITLE
Exception (28): epc1=0x40203876 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000When i upload the file from the form the nodemcu restarts and then in the serial motinor i get the exception.

### ISSUE THREAD

**Issue by saqibmanan329** [esp8266/Arduino#7343]
----------------------------- Delete below -----------------------------

If your issue is a general question, starts similar to "How do I..", is related to 3rd party libs, or is related to hardware, please discuss at a community forum like esp8266.com.

INSTRUCTIONS
============
If you do not follow these instructions, your issue may be dismissed.

1. Follow the checklist under Basic Infos and fill in the [ ] spaces with an X.
2. Fill in all the fields under Platform and Settings in IDE marked with [ ] (pick the correct option for you in each case, delete the others).
3. If you haven't already done so, test your issue against current master branch (aka latest git), because it may have been already fixed.
4. Describe your problem.
5. If you have a STACK DUMP decode it:

https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/stack_dump.html

6. Include a Minimal Complete Reproducible Example sketch that shows your issue. Do not include your entire project, or a huge piece of code.
7. Include debug messages:

https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/debugging.html 

8. Use markup (buttons above) and the Preview tab to check what the issue will look like.
9. Delete these instructions from the above to the below marker lines before submitting this issue.

----------------------------- Delete above -----------------------------

### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:					NODEMCU (ESP 12-E)
- Core Version:			[latest git hash or date]
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			Nodemcu
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		nodemcu
- Flash Frequency:	[40Mhz]
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   115200|

### Problem Description

Detailed problem description goes here.

Exception (28):
epc1=0x40203876 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffcd0 end: 3fffffc0 offset: 01a0
3ffffe70:  3fff014c 3ffffe90 3fff02d0 40205f10  
3ffffe80:  00000001 3ffee4e4 3fff02d0 40202f8d  
3ffffe90:  3fff0100 00000001 3ffffee0 00000001  
3ffffea0:  3ffffee0 3ffefefc 00000000 40206760  
3ffffeb0:  00000003 00000001 3ffefed4 4020fd5a  
3ffffec0:  00000003 4020107c 3ffefed4 401000e1  
3ffffed0:  3ffefed4 3ffee500 3ffefed4 4020164e  
3ffffee0:  3ffe0000 3fff0000 80fee658 80000030  
3ffffef0:  3ffefed4 3ffee500 3ffee4c0 402033b6  
3fffff00:  0000002f 80000000 81ff0a00 0000008f  
3fffff10:  80005454 0efd5abc 40100200 0000ddfe  
3fffff20:  00000001 00000001 00000001 3ffee570  
3fffff30:  00000003 00000001 3ffee4c0 3ffee658  
3fffff40:  00000001 3ffee4e4 3ffee4c0 3ffee658  
3fffff50:  00000001 3ffee4e4 3ffee4c0 402034d3  
3fffff60:  007a1200 0efd5b42 00001300 402106a0  
3fffff70:  00000000 3fff0034 feefeffe feefeffe  
3fffff80:  3ffee490 00000000 00000000 402036c1  
3fffff90:  3fffdad0 00000000 3ffee618 3ffee658  
3fffffa0:  3fffdad0 00000000 3ffee618 40207000  
3fffffb0:  feefeffe feefeffe 3ffe8504 40100c55  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1392, room 16 
tail 0
chksum 0xd0
csum 0xd0
v3d128e5c
~ld
*
Server IP:192.168.4.1
HTTP server started

### [MCVE](https://stackoverflow.com/help/mcve) Sketch
Here's the code can anybody help with this.
```cpp

#include<ESP8266WiFi.h>
#include<WiFiClient.h> // this file use to send requist to web server
#include<ESP8266WebServer.h> // this is to handle on http protocol
#include<FS.h>
//SSID and Password to your ESP Access Point
const char *ssid = "tgs00001";
const char *password = "tgs00002";
ESP8266WebServer server(80); //Server on port 80
File fsUploadFile;
//--------------------------------------------
//const unsigned long eventInterval = 60000;
//unsigned long previousTime = 0;
//unsigned long PT = 0;
//unsigned long OnTime = 0;
//==========================================
int sensor4 = D5 ; // PIR2 pin D2
int sensor3 = D7; // PIR2 pin D1
int sensor2 = D1; // PIR2 pin D5
int sensor = D2; // PIR1 pin D7
int Status = D6 ; // Relay pin D6
int uvs = 0;
int process = 0;
unsigned long starting = 0;
unsigned long stimer = 0;
//================
//void handleuv();
//void handleStatus();
// =================================
// =================================
void setup() {
Serial.begin(115200);
Serial.println("*");
WiFi.mode(WIFI_AP_STA); //Only Access point
WiFi.softAP(ssid, password); //Start HOTspot removing password will disable security
IPAddress myIP = WiFi.softAPIP(); //Get IP address
Serial.print("Server IP:");
Serial.println(myIP);
//========================Server setup=======================
server.on("/", HTTP_GET, handleStatus); // Call the 'handleStatus' function when a client requests URI "/"
server.on("/", HTTP_POST, handlefirmware);
// // server.onNotFound ( invalidurl );
server.begin(); //Start server
Serial.println("HTTP server started");
// // ===========================================================
pinMode(Status, OUTPUT); // relay output
pinMode(sensor, INPUT);
pinMode(sensor2, INPUT); //having problem over here
pinMode(sensor3, INPUT);
pinMode(sensor4, INPUT);
}
//====================================================
//==========================================================================================================//
void loop() {
if ((uvs == 1 || uvs == 2 ) && process == 0) {
//beginging delay loop for 60000ms
Serial.print("BB");
starting = millis();
process = 1;
}
if ((uvs == 1 || uvs == 2 ) && process == 1 && (millis() - starting) >= 10000) {
//setting uv= on;
Serial.print("begin");
digitalWrite (Status, HIGH);
stimer = millis();
process = 2;
}
if ((uvs == 1 || uvs == 2 ) && process == 2 && (millis() - stimer) >= 10000) {
//setting uv= on;
Serial.print("Complete");
digitalWrite (Status, LOW);
process = 0;
uvs=0;
}
if (uvs == 0 && (process == 1 || process == 2)) {
digitalWrite (Status, LOW);
process = 0;
Serial.print("Stop");
}
//.............................motion sensor.........................................................................................................
if (uvs == 1) {
long state4 = digitalRead(sensor4);
long state3 = digitalRead(sensor3);
long state2 = digitalRead(sensor2);
long state = digitalRead(sensor);
if (state4 == 1 || state3 == 1 || state == 1 || state2 == 1) {
// digitalWrite (Status, LOW);
Serial.println("Motion detected!");
delay(10);
}
}
//****************************************************************************************************..................................................................
//***********************************************************************************************************************.....................................................
server.handleClient(); //Handle client requests
}
//===============================================================================================================
void handleStatus() {

server.send(200, "text/html", "<form method=\"POST\" enctype=\"multipart/firm-data\"><input type=\"file\" name=\"name\"><input class=\"button\" type=\"submit\" value=\"Upload\"></form>");
}
//========================================================================================
//========================================================================================

void handlefirmware()
{
 HTTPUpload& upload = server.upload();
  if(upload.status == UPLOAD_FILE_START){
    String filename = upload.filename;
    if(!filename.startsWith("/")) filename = "/"+filename;
    Serial.print("handleFileUpload Name: "); Serial.println(filename);
    fsUploadFile = SPIFFS.open(filename, "w");            // Open the file for writing in SPIFFS (create if it doesn't exist)
    filename = String();
  } else if(upload.status == UPLOAD_FILE_WRITE){
    if(fsUploadFile)
      fsUploadFile.write(upload.buf, upload.currentSize); // Write the received bytes to the file
  } else if(upload.status == UPLOAD_FILE_END){
    if(fsUploadFile) {                                    // If the file was successfully created
      fsUploadFile.close();                               // Close the file again
      Serial.print("handleFileUpload Size: "); Serial.println(upload.totalSize);
      server.sendHeader("Location","/success.html");      // Redirect the client to the success page
      server.send(303);
    } else {
      server.send(500, "text/plain", "500: couldn't create file");
    }
  }
}

```

### Debug Messages

```
Debug messages go here
```

**Comment by earlephilhower** [comment]
Please decode the stack and fix the title.  We can't help with what you've given.

**Comment by saqibmanan329** [comment]
> 
> 
> Please decode the stack and fix the title. We can't help with what you've given.

https://github.com/esp8266/Arduino/issues/7345
sir, check the updated issue and help.
