### ISSUE TITLE
python3: error: unable to find utility "python3", not a developer tool or in PATH

### ISSUE THREAD

**Issue by sathiyaraj45** [esp8266/Arduino#7347]
We installed python3 in my new mac environment but we unable to compile in Arduino IDE for NodeMCU.

We updated the python env path in ~/.bash_profile
#Python env path
export PATH=/usr/local/bin:$PATH

**Comment by Tech-TX** [comment]
https://github.com/esp8266/Arduino/issues/6931

I see Mac users don't understand the basics of SEARCH.

**Comment by earlephilhower** [comment]
That's a MacOS + Brew issue, but easily fixed w/o hacks using the Apple-supported python3 toolset...

I just installed and ran the Arduino IDE on a fresh Catalina install and I get the helpful error:
![image](https://user-images.githubusercontent.com/11875/83434814-06377e00-a3f0-11ea-89bc-608c68734517.png)

I also get a nice dialog from Apple letting me click one button to install Python:
![image](https://user-images.githubusercontent.com/11875/83434875-1f402f00-a3f0-11ea-886e-bb2c9b9634e0.png)

Clicking thru the license/etc. and waiting a few mins to install, when I rerun the build it works fine (don't need to restart Arduino):
![image](https://user-images.githubusercontent.com/11875/83435558-56631000-a3f1-11ea-823d-21b6d109b299.png)

**Comment by earlephilhower** [comment]
@sathiyaraj45 Can you remove that `.bashrc` change and take a look at #7348?  You'll need to re-run the `get.py` to download a new OSX bundle with a portable python3 interpreter included (so not path changes, no need to use `brew` or install Xcode.

**Comment by sathiyaraj45** [comment]
Thanks to @Tech-TX and @earlephilhower.
