### ISSUE TITLE
Problem while send code to NODE-MCU ESP32

### ISSUE THREAD

**Issue by danilocarrarac** [esp8266/Arduino#7371]
Hi Everyone!

I am tryig to send a code, using Arduino-core with genetic board ESP8266 to my NODE MCU ESP32 (ESP8266EX) But when I send the code to board this error occurs:

`esptool.py v2.8
Serial port COM5
Connecting....
Chip is ESP8266EX
Features: WiFi
WARNING: Detected crystal freq 20.39MHz is quite different to normalized freq 26MHz. Unsupported crystal in use?
Crystal is 26MHz`

I´ve tried to change the baund rate to low values , adjust the clock but all effort didn't works!

Thanks!

**Comment by devyte** [comment]
Please seek such generic help at a community forum like esp8266.com or stackoverflow. This is an issue tracker and not meant for general support questions. 
Also, issue template ignored. 
Closing due to not compliant.
