### ISSUE TITLE
Does ESP8266/Arduino support SSH client connection?

### ISSUE THREAD

**Issue by DrakoPD** [esp8266/Arduino#7378]
I can't find any documentation or example about this. I want to do an HttpUpdate to a private GitHub repository acceding with a SSH key. But I need first to know if is supported. (ESP8266 generic - 12E)

**Comment by earlephilhower** [comment]
No, SSH is not supported.  Only TLS and things built on top (HTTPS, etc.).

SSH requires a 32KB buffer, 2x the size of TLS, so I doubt it's doable while leaving enough RAM to do any processing on the 8266.

I'd be happy to be proven wrong, though, with a PR.  :)

**Comment by d-a-v** [comment]
I'm happily using telnet over SSL though :)

**Comment by authorizedengineer** [comment]
Ssh server supported on esp8266 arduino in this repo : https://github.com/Suraj151/pdi-framework
