### ISSUE TITLE
HTTP_UPDATE_FAILED Error (-1) when I add more headers to httpupdate

### ISSUE THREAD

**Issue by DrakoPD** [esp8266/Arduino#7383]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12]
- Core Version:			[date]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows 10]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

I need to add two more headers for my update, I added directly to the httpupdate library:

The next line was added to the `HTTPUpdateResult ESP8266HTTPUpdate::handleUpdate` function, in the **ESP8266httpUpdate.cpp** file, in the `http.addHeader` secction:
```
http.addHeader(F("Accept"), "application/vnd.github.v3+json");
http.addHeader(F("authorization"), "Bearer my_token");
```

Because I need to download an update from a private GitHub repository, i using a token for the request. 
I can connect and get the code with http.GET() and print through serial (with HTTP code 200).

But if I try do it in the Httpupdate library, I get `HTTP_UPDATE_FAILED Error (-1): HTTP error: connection refused`.

Is there a way to solved this? or a way to pass the code that I download by .GET() for update? if exist something like `ESP.update(http.GET())`.

I had configured certs and NTP time.

Edit: added more info.

### Code

```
/**
   httpUpdateSecure.ino
    Created on: 20.06.2018 as an adaptation of httpUpdate.ino
*/

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

#include <ESP8266HTTPClient.h>
#include <ESP8266httpUpdate.h>

#include <time.h>

#include <FS.h>
#include <LittleFS.h>

#ifndef APSSID
#define APSSID ""
#define APPSK  ""
#endif

ESP8266WiFiMulti WiFiMulti;

// A single, global CertStore which can be used by all
// connections.  Needs to stay live the entire time any of
// the WiFiClientBearSSLs are present.
#include <CertStoreBearSSL.h>
BearSSL::CertStore certStore;

//const char * headerKeys[] = {"Accept", "authorization"} ;
//const size_t numberOfHeaders = 2;



// Set time via NTP, as required for x.509 validation
void setClock() {
  configTime(4*3600, 0, "pool.ntp.org", "time.nist.gov");  // UTC

  Serial.print(F("Waiting for NTP time sync: "));
  time_t now = time(nullptr);
  while (now < 8 * 3600 * 2) {
    yield();
    delay(500);
    Serial.print(F("."));
    now = time(nullptr);
  }

  Serial.println(F(""));
  struct tm timeinfo;
  gmtime_r(&now, &timeinfo);
  Serial.print(F("Current time: "));
  Serial.print(asctime(&timeinfo));
}

void setup() {

  Serial.begin(115200);
  // Serial.setDebugOutput(true);

  Serial.println();
  Serial.println();
  Serial.println();

  for (uint8_t t = 4; t > 0; t--) {
    Serial.printf("[SETUP] WAIT %d...\n", t);
    Serial.flush();
    delay(1000);
  }

  WiFi.mode(WIFI_STA);
  WiFiMulti.addAP(APSSID, APPSK);

  LittleFS.begin();

  int numCerts = certStore.initCertStore(LittleFS, PSTR("/certs.idx"), PSTR("/certs.ar"));
  Serial.print(F("Number of CA certs read: "));
  Serial.println(numCerts);
  if (numCerts == 0) {
    Serial.println(F("No certs found. Did you run certs-from-mozill.py and upload the LittleFS directory before running?"));
    return; // Can't connect to anything w/o certs!
  }
}

void loop() {
  // wait for WiFi connection
  if ((WiFiMulti.run() == WL_CONNECTED)) {

    setClock();

    BearSSL::WiFiClientSecure client;
    bool mfln = client.probeMaxFragmentLength("https://api.github.com", 443, 1024);  // server must be the same as in ESPhttpUpdate.update()
    Serial.printf("MFLN supported: %s\n", mfln ? "yes" : "no");
    if (mfln) {
      client.setBufferSizes(1024, 1024);
    }
    client.setCertStore(&certStore);

/*    
    HTTPClient http;
 
    http.begin(client, "https://api.github.com/repos/user/reponame/contents/firmware.bin");
    http.addHeader(F("Accept"), "application/vnd.github.v3+json");
    http.addHeader(F("authorization"), "Bearer token");
    //http.setAuthorization("token");

    Serial.print("[HTTP] GET...\n");
    // start connection and send HTTP header
   int httpCode = http.GET();
   Serial.printf("[HTTP] GET... code: %d\n", httpCode);

    // httpCode will be negative on error
    if (httpCode > 0) {
      // HTTP header has been send and Server response header has been handled
      Serial.printf("[HTTP] GET... code: %d\n", httpCode);

      // file found at server
      if (httpCode == HTTP_CODE_OK) {
       String payload = http.getString();
       Serial.println(payload);
      }
    } else {
      Serial.printf("[HTTP] GET... failed, error: %s\n", http.errorToString(httpCode).c_str());
    }

    http.end();
  */

    ESPhttpUpdate.setLedPin(LED_BUILTIN, LOW);

    t_httpUpdate_return ret = ESPhttpUpdate.update(client, "https://api.github.com/repos/user/reponame/contents/firmware.bin");

    switch (ret) {
      case HTTP_UPDATE_FAILED:
        Serial.printf("HTTP_UPDATE_FAILED Error (%d): %s\n", ESPhttpUpdate.getLastError(), ESPhttpUpdate.getLastErrorString().c_str());
        break;

      case HTTP_UPDATE_NO_UPDATES:
        Serial.println("HTTP_UPDATE_NO_UPDATES");
        break;

      case HTTP_UPDATE_OK:
        Serial.println("HTTP_UPDATE_OK");
        break;
    }
  }
  delay(5000);
}
```

### Debug message

```
[HTTP-Client][sendRequest] type: 'GET' redirCount: 0
[HTTP-Client] connect: HTTPClient::begin was not called or returned error
[HTTP-Client][returnError] error(-1): connection refused
[httpUpdate] HTTP error: connection refused
[HTTP-Client][end] tcp is closed
HTTP_UPDATE_FAILED Error (-1): HTTP error: connection refused
```

**Comment by earlephilhower** [comment]
@DrakoPD, please post a full MCVE and full debug logs, as requested in the template.  W/o them, we can't really do anything for you.

**Comment by DrakoPD** [comment]
@earlephilhower Done. I updated my question with more code.

**Comment by earlephilhower** [comment]
Couple of things right off the bat:
* I assume the `/*  ...*/` block is not really commented out in your code
* `bool mfln = client.probeMaxFragmentLength("https://api.github.com", 443, 1024);` is wrong and will always fail.  Just pass in the hostname, not a URL.  api.github.com
* `    BearSSL::WiFiClientSecure client;` <- Use a global for this because it is a very large structure to put on the stack.

Can you max out the debug logging (2nd from last in the menu, dumps a ton more stuff including BearSSL and TCP stuff) and re-capture?

**Comment by earlephilhower** [comment]
Another quick thing to check is to ass a `.setInsecure` (for testing only) before passing in the client.  That would allow you to narrow down whether it's the SSL negotiation failing or something else, since the insecure mode will not check anything and always connect if it can.

**Comment by DrakoPD** [comment]
> I assume the /* ...*/ block is not really commented out in your code
Is commented, I only used for test the connection to GitHub, and its work.

> Just pass in the hostname, not a URL. api.github.com
I don't understand, that mean just "Github"?

> Can you max out the debug logging...
I already have in this mode, also, I clean all BearSSL and TCP, just let the wifi client an set insecure. The problem was that I accidentally deleted the line `http.begin()` inside the library.

Now I get the first error when I add more headers (before of the mistake of http.begin):
`HTTP_UPDATE_FAILED Error (-106): Verify Bin Header Failed`

**Comment by DrakoPD** [comment]
Also, the debug console is too long now, do I really need to put all here?

**Comment by earlephilhower** [comment]
If it gets to `HTTP_UPDATE_FAILED Error (-106): Verify Bin Header Failed` then it is most likely an issue in your code or .BIN file since the connection was made, SSL was negotiated, and something was transferred back.  At this point, your best bet it to go to esp8266.com or https://gitter.im/esp8266/Arduino to get help with your setup.

Given the info here, I'm closing as it's not looking like the core at this point.

**Comment by DrakoPD** [comment]
I really don't like esp8266.com, it have an annoying publicity and we have to wait for the approbation of any post (from 6 to 24 hours), making difficult have a stable communication with others.
