### ISSUE TITLE
Tasmota/ESP8266 Drops WiFi Connection - Cannot Reconnect

### ISSUE THREAD

**Issue by gwrichard** [esp8266/Arduino#7389]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12|ESP-01|ESP-07|ESP8285 device|other]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE|Platformio|Make|other]
- Operating System:		[Windows|Ubuntu|MacOS]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio]
- Flash Size: 		[1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[OTA]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

I am having tissues with my Tasmota devices dropping the Wi-Fi connection. They are flashed to 8.3.1.

I have disabled band steering on my router. Changing to separate 2.4 and 5Ghz frequencies seemed to help (instead of being blocked after Tasmota reboot, it is stable for a couple of days now).

Eventually the Tasmota devices drop their Wi-Fi connection (usually after a day or two) and fail to reconnect. The only remedy is to reboot the router.

Following are my router details:

    Firmware Number: 18.1.c.0462-950-RB
    Modem Make Model: Technicolor DJA0231

Tasmota devices are the ONLY devices on my network that experience this problem. All other devices do not have trouble connecting or reconnecting.

I was advised by the Tasmota Discord channel to post the issue here, since they said the issue is not Tasmota, but rather the Arduino module.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>

void setup() {

}

void loop() {

}

```

### Debug Messages

```
Debug messages go here
```

**Comment by devyte** [comment]
@gwrichard we have certain rules here for reporting issues. One of them, as shown in the issue template above, is that a MCVE is required, where only core code is used.
If the Tasmota guys are correct and your issue is a core one, then indeed you need to report here. However, you need the MCVE, so either you need to reduce your code to a pure core example, or the Tasmota guys need to help you do it. Without that, we can't help.

**Comment by earlephilhower** [comment]
No MCVE, no response for ~2 weeks.  Closing as nothing to do here.
