### ISSUE TITLE
esptool not listed in programmer menu

### ISSUE THREAD

**Issue by AkhilReddyMandadi** [esp8266/Arduino#739]
im using the arduino ide 1.6.5 but esptool is not listed in the programmer menu

**Comment by igrr** [comment]
@AkhilReddyMandadi 
Please provide some description for this, i.e. why do you believe this is an issue.

**Comment by AkhilReddyMandadi** [comment]
actually i selected the genericesp in the boards menu but esptool is not listed under the programmer menu. I tried uploading the code but it showing error

**Comment by igrr** [comment]
Esptool is not supposed to be listed in programmers list. It doesn't matter what you select in that menu — upload will always happen using esptool.

Check your connections according to the [docs](https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/doc/boards.md). Visit the esp8266.com forum for guidance to troubleshooth this error.

**Comment by AkhilReddyMandadi** [comment]
thank you @igrr
