### ISSUE TITLE
libc_replacements.c:408:22: warning: 'struct tm' declared inside parameter list

### ISSUE THREAD

**Issue by Juppit** [esp8266/Arduino#740]
With the latest version I get this new warning on windows:
C:\Users\Peter\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-1089-gf9b86c7\cores\esp8266\libc_replacements.c:408:22: warning: 'struct tm' declared inside parameter list [enabled by default]
 time_t mktime(struct tm *timp) {
                      ^
C:\Users\Peter\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-1089-gf9b86c7\cores\esp8266\libc_replacements.c:408:22: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]

Unfortunately, my skills are not as good to fix this.
Of course, I'm ignoring this warning at the time.

**Comment by igrr** [comment]
Thanks, I'm aware of that. You can safely ignore this warning, I'll fix it along with the next round of TLS-related stuff.
