### ISSUE TITLE
ESP8266 doens't work

### ISSUE THREAD

**Issue by PaulvRhee** [esp8266/Arduino#7400]
My NodeMCU Esp8266-12F is automatically resetting after every uploaded sketch.

it's giving me this

> Executable segment sizes:
> 
> 
> IROM   : 233964          - code in flash         (default or ICACHE_FLASH_ATTR) 
> 
> 
> IRAM   : 26928   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
> 
> 
> DATA   : 1248  )         - initialized variables (global, static) in RAM/HEAP 
> 
> 
> RODATA : 756   ) / 81920 - constants             (global, static) in RAM/HEAP 
> 
> 
> BSS    : 24960 )         - zeroed variables      (global, static) in RAM/HEAP 
> 
> 
> De schets gebruikt 262896 bytes (25%)  programma-opslagruimte. Maximum is 1044464 bytes.
> Globale variabelen gebruiken 26964 bytes (32%) van het dynamisch geheugen. Resteren 54956 bytes voor lokale variabelen. Maximum is 81920 bytes.
> esptool.py v2.8
> Serial port COM3
> Connecting....
> Chip is ESP8266EX
> Features: WiFi
> Crystal is 26MHz
> MAC: a4:cf:12:dd:5d:XX
> Uploading stub...
> Running stub...
> Stub running...
> Configuring flash size...
> Auto-detected Flash size: 4MB
> Compressed 267056 bytes to 196760...
> 
> Writing at 0x00000000... (7 %)
> Writing at 0x00004000... (15 %)
> Writing at 0x00008000... (23 %)
> Writing at 0x0000c000... (30 %)
> Writing at 0x00010000... (38 %)
> Writing at 0x00014000... (46 %)
> Writing at 0x00018000... (53 %)
> Writing at 0x0001c000... (61 %)
> Writing at 0x00020000... (69 %)
> Writing at 0x00024000... (76 %)
> Writing at 0x00028000... (84 %)
> Writing at 0x0002c000... (92 %)
> Writing at 0x00030000... (100 %)
> Wrote 267056 bytes (196760 compressed) at 0x00000000 in 17.4 seconds (effective 122.5 kbit/s)...
> Hash of data verified.
> 
> Leaving...
> Hard resetting via RTS pin...
>

**Comment by d-a-v** [comment]
You don't help us help you @PaulvRhee.

esp8266 is always reset after flashing. We can't be of any help with such bug report.

Please open a new issue and fill in the issue template instead of deleting it.
