### ISSUE TITLE
Analog read with Arduino and Nodemcu Esp8266

### ISSUE THREAD

**Issue by thiagoconsales** [esp8266/Arduino#7407]
Hello,

I'm developing a project that uses the A0 port to receive the sensor data, the problem is that the measurements I did with Arduino Uno are very different when I use Nodemcu, and I need to use nodemcu in the project.

Below is a measurement chart using ECG module AD8232 using Arduino and NodeMCU.

Nodemcu:

![nodemcu](https://user-images.githubusercontent.com/55933228/85906370-7f09da00-b7e4-11ea-9c79-035311afe266.png)

Arduino:
![Arduino](https://user-images.githubusercontent.com/55933228/85906444-b6788680-b7e4-11ea-8926-86523250e129.png)

The Arduino readings is better than Nodemcu. 

Bellow a simple test I did in order to find the problem:

![image](https://user-images.githubusercontent.com/55933228/85906657-56361480-b7e5-11ea-90f5-fb9aeee07fbd.png)

Any idea what is happen?

Thanks!

**Comment by JiriBilek** [comment]
Most probably you are stuck on the fact, that ESP8266 ADC pin input voltage range is 0 to 1V.

**Comment by earlephilhower** [comment]
Interesting use case, @thiagoconsales, but as @JiriBilek noted the ADC on the 8266 and the AVR are very different.  The 8266 has a 0-1V, low bandwidth, low quality hardware ADC.  The A0 input itself is also modified by some boards to give a 3.3V range via an R-divider network (potentially changing the frequency response and the impedance), but you need to talk w/your board manufacturer or search online for details.

That said, this is not the place for general discussion like this.  Use the https://esp8266.com/forum or https://gitter.im/esp8266/Arduino IRC-like to get general help on projects.
