### ISSUE TITLE
ESP 01 not scanning WiFi.

### ISSUE THREAD

**Issue by JohanJomy** [esp8266/Arduino#7409]
#### Platform

- Hardware:				ESP-01
- Core Version:			latest git hash or date
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			Generic ESP8266 Module
- Flash Mode:			other DOUT
- Flash Size: 		        1MB
- lwip Variant:                   v2 Lower Memory
- Reset Method:		nodemcu
- Flash Frequency:	         40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		OTA
- Upload Speed:              115200

### Problem Description

I am using an ESP 01 and uploaded the code from the examples but the serial monitor doesn't print anything.

Connections for Programming the ESP 0, that I used:

Arduino.GND - Arduino.RST - ESP.GND - ESP.GPIO0
ESP.CHPD - ESP.VCC - Arduino.3.3
Arduino.RX - ESP.RX
Arduino.TX - ESP.TX

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

/*
    This sketch demonstrates how to scan WiFi networks.
    The API is almost the same as with the WiFi Shield library,
    the most obvious difference being the different file you need to include:
*/
#include "ESP8266WiFi.h"

void setup() {
  Serial.begin(115200);

  // Set WiFi to station mode and disconnect from an AP if it was previously connected
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  delay(100);

  Serial.println("Setup done");
}

void loop() {
  Serial.println("scan start");

  // WiFi.scanNetworks will return the number of networks found
  int n = WiFi.scanNetworks();
  Serial.println("scan done");
  if (n == 0) {
    Serial.println("no networks found");
  } else {
    Serial.print(n);
    Serial.println(" networks found");
    for (int i = 0; i < n; ++i) {
      // Print SSID and RSSI for each network found
      Serial.print(i + 1);
      Serial.print(": ");
      Serial.print(WiFi.SSID(i));
      Serial.print(" (");
      Serial.print(WiFi.RSSI(i));
      Serial.print(")");
      Serial.println((WiFi.encryptionType(i) == ENC_TYPE_NONE) ? " " : "*");
      delay(10);
    }
  }
  Serial.println("");

  // Wait a bit before scanning again
  delay(5000);
}
### Debug Messages

Executable segment sizes:
IROM: 239608          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27728   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1252  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 976   ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 25184 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 269564 bytes (28%) of program storage space. Maximum is 958448 bytes.
Global variables use 27412 bytes (33%) of dynamic memory, leaving 54508 bytes for local variables. Maximum is 81920 bytes.
esptool.py v2.8
Serial port COM4
Connecting....
Chip is ESP8266EX
Features: WiFi
Crystal is 26MHz
MAC: 5*:*2:**:*a:*0:*a
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 1MB
Compressed 273712 bytes to 201637...
Wrote 273712 bytes (201637 compressed) at 0x00000000 in 17.7 seconds (effective 123.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

**Comment by earlephilhower** [comment]
Again, this is a HW or setup issue on your end and not related to the core.  Please use the forum or gitter discussion for general help like this.
