### ISSUE TITLE
HelloMesh, no connections.

### ISSUE THREAD

**Issue by gamecompiler** [esp8266/Arduino#741]
Hi, id uploaded the HelloMesh example to six Esp´s. But no one connect to each other.
It fails while connecting to any _suitable_ APs which contain _ssid_prefix.

Id checked if the sketch scans correct for Ap s and if it filter the chip id s out.
That works fine. 

Maybe its import: current_ssid is always empty if id print them out over Serial with Serial.println(current_ssid);

The if sentence
if (index >= 0 && (target_chip_id < _chip_id)) {}
does never happen.

Sorry for my English.
Thanks in Advance.
##

**Comment by grahamehorner** [comment]
I to have this issue I have 10 ESP8266 developer kits all running the same firmware version and the HelloMesh sketch, no data is getting transmitted/received by any node; or the Raspberry PI Internet gateway.

**Comment by devyte** [comment]
@gamecompiler is this issue still valid with latest git?

**Comment by gamecompiler** [comment]
No, it works now. Thank you very much!

**Comment by WillingLearner** [comment]
I also have the same problem, I loaded the same code into the two ESP module but doesn't work. How did you solve your problem gamecompiler ?

**Comment by sriksh9** [comment]
@WillingLearner I've uploaded the "HelloMesh" example to three ESP12Es without any modifications, they've connected each other and printed the messages. I don't think there is any such sort of problem anymore.
