### ISSUE TITLE
Change EEPROM.end() return type from void to bool

### ISSUE THREAD

**Issue by mrv96** [esp8266/Arduino#7423]
According to docs, EEPROM.end() in https://github.com/esp8266/Arduino/blob/master/libraries/EEPROM/EEPROM.cpp is a commit() followed by a free of used RAM.

Since commit() return a bool, also end() should return a bool to check if the commit failed or not.

**Comment by d-a-v** [comment]
Will you propose a pull-request for that suggestion ?
