### ISSUE TITLE
My NodeMcu 1.0 keep disconnecting and connecting to wifi hotspot

### ISSUE THREAD

**Issue by Sofiane-apk** [esp8266/Arduino#7460]
**Platform**
Hardware: NodeMCU 1.0 (ESP12E-Module)
Core Version: latest git 
Development Env: Arduino IDE (last git) 
Operating System: Windows 10
**Settings in IDE**
Module: Nodemcu
Flash Size: 4MB
CPU Frequency: 80Mhz
Upload Using: OTA && SERIAL
Upload Speed: [115200 (Serial)]
**Problem Description**
I looked for a solution between the various issues but none worked right now.
The connection to the WiFi remains active for a time ranging from 30 seconds.
The module disconnects and reconnects to the wifi hotspot.
and the dht11 not reading fine .
**note:** when I try script using only dht11 it 's reading very good .
**I hope someone can help me.**
**Sketch**
![Screenshot (91)](https://user-images.githubusercontent.com/57842224/87658416-0f886a00-c754-11ea-8de0-b8e3f9168173.png)

![Screenshot (92)](https://user-images.githubusercontent.com/57842224/87658376-03041180-c754-11ea-9653-159435846e41.png)
![Screenshot (93)](https://user-images.githubusercontent.com/57842224/87658381-05666b80-c754-11ea-8d9c-3eef69c7dfe6.png)
![Screenshot (94)](https://user-images.githubusercontent.com/57842224/87658406-0c8d7980-c754-11ea-9ec2-f9e21894e1e0.png)
![Screenshot (95)](https://user-images.githubusercontent.com/57842224/87658411-0e573d00-c754-11ea-8b64-2588d19a9395.png)

**Debug Messages**
`10:45:37.240 -> Humidity: 157.80%  Temperature: 15.10C°
10:45:37.240 -> 4
10:45:37.613 -> Pump active manual
10:45:37.817 -> 
10:45:37.817 -> Exception (28):
10:45:37.817 -> epc1=0x40212294 epc2=0x00000000 epc3=0x00000000 excvaddr=0x022e0184 depc=0x00000000
10:45:37.852 -> 
10:45:37.852 -> >>>stack>>>
10:45:37.852 -> 
10:45:37.852 -> ctx: cont
10:45:37.852 -> sp: 3ffffac0 end: 3fffffc0 offset: 01a0
10:45:37.852 -> 3ffffc60:  00000001 00000003 3ffefd40 402051f4  
10:45:37.852 -> 3ffffc70:  3ffffcc0 3fffff40 3ffefd40 402060c4  
10:45:37.852 -> 3ffffc80:  431dcccd 3fffff40 3ffffef0 402030b4  
10:45:37.852 -> 3ffffc90:  431dcccd 3ffffcc0 3ffffcc0 402015ac  
10:45:37.852 -> 3ffffca0:  00000002 3fffff40 3ffffef0 40201668  
10:45:37.852 -> 3ffffcb0:  431dcccd 3fffff40 3ffe87bc 40202f84  
10:45:37.852 -> 3ffffcc0:  00220000 00000000 80ffc228 402128e8  
10:45:37.886 -> 3ffffcd0:  4000050c 00000000 3fff08a4 40227ccf  
10:45:37.886 -> 3ffffce0:  40204d58 00000030 00000013 ffffffff  
10:45:37.886 -> 3ffffcf0:  40204d4e 0000002f 00000000 00000001  
10:45:37.886 -> 3ffffd00:  60000808 00000004 00000020 00000009  
10:45:37.886 -> 3ffffd10:  00000009 3fffc6fc 00000001 3ffeeac4  
10:45:37.886 -> 3ffffd20:  3fffff20 3fffff20 3ffeecac 00000030  
10:45:37.886 -> 3ffffd30:  3ffffd68 00000001 3fff08a4 0000001f  
10:45:37.919 -> 3ffffd40:  000011c0 40202658 00000020 40100a6c  
10:45:37.919 -> 3ffffd50:  00000000 4bc6a7f0 3ef9db22 00000000  
10:45:37.919 -> 3ffffd60:  00000000 00000000 4bc6a7f0 00000000  
10:45:37.919 -> 3ffffd70:  4010504d 00c66baa 40100274 0000a2be  
10:45:37.919 -> 3ffffd80:  00000000 6a5abd47 00c66b00 00000000  
10:45:37.919 -> 3ffffd90:  00bc2bf8 00c6841f 3ffeed0c 00000000  
10:45:37.919 -> 3ffffda0:  3ffee490 3ffeed0c 00000014 3ffeeac4  
10:45:37.919 -> 3ffffdb0:  00000000 00000000 3ffeeac4 40204c91  
10:45:37.952 -> 3ffffdc0:  401002cc 3ffeeac4 00000000 4020891a  
10:45:37.952 -> 3ffffdd0:  3fffff20 3fffff18 3ffeeac4 40204d4e  
10:45:37.952 -> 3ffffde0:  0000007b 0000008a 00000055 00000026  
10:45:37.952 -> 3ffffdf0:  00000055 00000025 00000055 0000006f  
10:45:37.952 -> 3ffffe00:  00000055 00000026 00000054 00000026  
10:45:37.952 -> 3ffffe10:  00000055 00000025 00000055 0000006f  
10:45:37.952 -> 3ffffe20:  3ffffea0 00000000 30206b51 4020a175  
10:45:37.952 -> 3ffffe30:  3ffffea0 00000025 00000055 00000025  
10:45:37.986 -> 3ffffe40:  3ffffec0 00000000 3531002e 3ffeeb7c  
10:45:37.986 -> 3ffffe50:  3ffffed0 00000000 34207318 4020a175  
10:45:37.986 -> 3ffffe60:  3ffffed0 3ffeeb7c 3ffffe9f 402069a1  
10:45:37.986 -> 3ffffe70:  00000030 0000000a 3ffffe9e 3ffeeb7c  
10:45:37.986 -> 3ffffe80:  402066cc 3ffeeb7c 3ffffecf 402066d8  
10:45:37.986 -> 3ffffe90:  402066cc 3ffeeb7c 3ffffecf 402069a1  
10:45:37.986 -> 3ffffea0:  00000034 0000000a 3ffffece 40206b51  
10:45:38.019 -> 3ffffeb0:  00000005 00000030 3fffff00 0000002e  
10:45:38.019 -> 3ffffec0:  3ffe8a41 00000000 7468000a 4020a175  
10:45:38.019 -> 3ffffed0:  3ffe8a41 00000000 00000000 00000002  
10:45:38.019 -> 3ffffee0:  3ffffcc0 7f8d9a00 3fffff40 80fe8742  
10:45:38.019 -> 3ffffef0:  40212880 3ffefd3c 00000000 3ffeeb18  
10:45:38.019 -> 3fffff00:  3ffefd00 40212820 3ffe8a3f 00000000  
10:45:38.019 -> 3fffff10:  00000100 3ffeeb18 3fffff00 40207318  
10:45:38.053 -> 3fffff20:  801dcccd 3fffff4c 3ffe8757 4020734e  
10:45:38.053 -> 3fffff30:  431dcccd 3ffeeb7c 3ffeeaf8 40201370  
10:45:38.053 -> 3fffff40:  312e0031 b0c24330 81fefd00 616c6e6f  
10:45:38.053 -> 3fffff50:  0000706d 86ffff80 312e3500 40000030  
10:45:38.053 -> 3fffff60:  807a1200 312e3531 b0c24330 88207100  
10:45:38.053 -> 3fffff70:  2e373531 00253038 87feeb7c 40201115  
10:45:38.053 -> 3fffff80:  4171999a 00000000 00000001 4010017c  
10:45:38.053 -> 3fffff90:  3fffdad0 00000000 3ffeec6c 3ffeecac  
10:45:38.086 -> 3fffffa0:  3fffdad0 00000000 3ffeec6c 40208228  
10:45:38.086 -> 3fffffb0:  feefeffe feefeffe 3ffe8568 40100cf9  
10:45:38.086 -> <<<stack<<<
10:45:38.086 -> 
10:45:38.086 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
10:45:38.086 -> 
10:45:38.086 -> load 0x4010f000, len 1392, room 16 
10:45:38.086 -> tail 0
10:45:38.086 -> chksum 0xd0
10:45:38.086 -> csum 0xd0
10:45:38.121 -> v3d128e5c
10:45:38.121 -> ~ld
10:45:38.662 -> .....
10:45:40.686 -> WiFi Connected!
10:45:40.686 -> 192.168.137.47
10:45:40.686 -> Humidity: 157.80%  Temperature: 15.10C°
`

**Comment by TD-er** [comment]
I doubt anyone will help here if the source code is only available in screenshots.
You better post the source in the text and wrap it with code block formatting. (add at the start and end of the code block 3x a back-tick which is the single quote right below the Escape key)

**Comment by earlephilhower** [comment]
Closing.
