### ISSUE TITLE
Serial.printf(" %02.1f | ", variable); does not print leading zeros.

### ISSUE THREAD

**Issue by rin67630** [esp8266/Arduino#7465]
#7384 # Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:			        [ESP-12]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows 10]

### Settings in IDE

- Module:  			[Generic Wemos D1 mini r2]
- Flash Mode:			[irrelevant]
- ...
- Upload Speed:              [irrelevant]

### Problem Description

`Serial.printf(" %02.1f | ", variable);`
does not print leading zeros.

Admittedly, I am glad that printf() works at least for floats, but not completely according to the C++ spec.

**Comment by earlephilhower** [comment]
Looks like it works to me.
````
Serial.printf(" %02.1f | ", .2);
````
outputs
````
 0.2 |
````
while
````
Serial.printf(" %05.1f | ", .2);
````
outputs
````
 000.2 |
````

This matches the same format string on Linux:
````
cat /tmp/a.c
#include <stdio.h>
int main(int argc, char **argv) {
        printf("%0.1f\n", 0.2);
        return 0;
}
earle@server:~/Arduino/hardware/esp8266com/esp8266$ gcc -o /tmp/a /tmp/a.c
earle@server:~/Arduino/hardware/esp8266com/esp8266$ /tmp/a
0.2
````

The digit after the `%0` is the **total width**, not the width before the decimal point.

http://www.cplusplus.com/reference/cstdio/printf/
