### ISSUE TITLE
Doubt about EEPROM and OTA

### ISSUE THREAD

**Issue by franciscogimeno2000** [esp8266/Arduino#7466]
Doubt about EEPROM and OTA

Hello my question is:
When OTA is done on a device, the EEPROM values (which are not really in the eeprom but in the program area) are overwritten? 

If so, how do we avoid removing them when doing OTA?
Where is the EEPROM data exactly?

Greetings and thank you
Francisco

**Comment by Tech-TX** [comment]
AFAIK the only 'EEPROM values'  are the WiFi parameters,  and they aren't overwritten unless you do 'erase all'

**Comment by franciscogimeno2000** [comment]
Hello, I mean the data that we keep with the eeprom instruction.

**Comment by earlephilhower** [comment]
For general questions please use https://esp8266.com forums or https://gitter.im/esp8266/Arduino .  As the template you removed says, this area is for issues with the core and not general coding questions.
