### ISSUE TITLE
OTA on http server authentication

### ISSUE THREAD

**Issue by mugginsjm** [esp8266/Arduino#7482]

**Comment by mugginsjm** [comment]
Hi
My bin files reside on a remote server and are protected with "htaccess"  requiring username and password.
Is there any way of introducing these credentials when using:
t_httpUpdate_return  ret = ESPhttpUpdate.update(myHost/myBin);
thanks

**Comment by JiriBilek** [comment]
I am afraid, it is not implemented. You will have to add the authentication header to the http client yourself - see https://github.com/esp8266/Arduino/blob/83fc47f6d97d6a82acb6cf2c856381bcd101f0c0/libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp#L262

**Comment by mugginsjm** [comment]
Thanks for that but I'm very poor on html. Can you guide me a little further please.

**Comment by JiriBilek** [comment]
I hope `http.setAuthorization(user, password)` inserted in the section I pointed at in the previous post will do the trick. I suggest to copy and rename the two source files (ESP8266httpUpdate.h and .cpp) to your project instead of modifying the library in place.

**Comment by mugginsjm** [comment]
Great.. I’ll try that

**Comment by devyte** [comment]
This is an issue tracker, not a general support forum. As explained in the issue template, please ask such questions at a community forum like esp8266.com or stackoverflow instead of here.
Closing due to not compliant.
