### ISSUE TITLE
error while executing the code using nodemcu--please help regarding this issue

### ISSUE THREAD

**Issue by rashid2005** [esp8266/Arduino#7485]
Arduino: 1.8.13 (Windows Store 1.8.39.0) (Windows 10), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

c:/users/lenovo/documents/arduinodata/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Lenovo\AppData\Local\Temp\arduino_cache_972163\core\core_9a07512a3d3ef0f8e73f5a98f031ff4c.a(core_esp8266_main.cpp.o): in function `__loop_end':

C:\Users\Lenovo\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.7.2\cores\esp8266/core_esp8266_main.cpp:185: undefined reference to `loop'

c:/users/lenovo/documents/arduinodata/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Lenovo\AppData\Local\Temp\arduino_cache_972163\core\core_9a07512a3d3ef0f8e73f5a98f031ff4c.a(core_esp8266_main.cpp.o): in function `loop_wrapper()':

C:\Users\Lenovo\Documents\ArduinoData\packages\esp8266\hardware\esp8266\2.7.2\cores\esp8266/core_esp8266_main.cpp:192: undefined reference to `loop'

collect2.exe: error: ld returned 1 exit status

exit status 1

Error compiling for board NodeMCU 0.9 (ESP-12 Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Tech-TX** [comment]
This is an area for issues with the core or libraries, not basic installation errors or 'how-to' questions, as was detailed in the template that you ignored.  The last three lines of your post should have given you a hint on what to try next, though realistically a wipe and reinstall of the Arduino core files and the esp8266,
https://arduino-esp8266.readthedocs.io/en/latest/installing.html

You'll have better luck at https://www.esp8266.com/
