### ISSUE TITLE
The infrared sensor outputs 1 level change, but the Arduino reads multiple

### ISSUE THREAD

**Issue by tanghui0102** [esp8266/Arduino#7507]
Hello everyone, novice ask for advice.
Thinking of the arduino infrared obstacle avoidance module to recognize the white sticker and realize the speed measurement function.
code show as below:
`int LED = 13; // Use the onboard Uno
volatile float n = 0;
float dt;
float Speed;
float begin_time;
const byte interruptPin = 2;  //用2号引脚作为中断触发引脚

void setup() {
  pinMode(LED, OUTPUT);
  pinMode(interruptPin, INPUT);
  attachInterrupt(digitalPinToInterrupt(interruptPin),count_pulse,FALLING);
  begin_time=millis();
  Serial.begin(9600);
}

void count_pulse(){
  Serial.println("I am being called");
  n += 1;
}

void loop() {
  dt=millis()-begin_time;
  /*每隔500ms输出一次转速，并重新开始计算下一个500ms的转速 */
  if(dt > 1000.0 ){
    //每一圈有6个脉冲，下面返回的值为rpm
    //delayMicroseconds(50);
    Serial.print("脉冲个数：");
    Serial.println(n);
    Serial.print("dt: ");
    Serial.println(dt);
    Serial.print("转速：");
    Speed =  (n/6) / (dt/60000);
    Serial.println(Speed);
    n = 0;
    begin_time = millis();
    Serial.flush();  // 确定都已经打印出去

  }
}`

Below is the output：
![eafb906b3c1dde857c913f2599a6cb8](https://user-images.githubusercontent.com/47203090/89486682-2ca1dd00-d7d6-11ea-90cf-34665c88af02.png)

The number of output pulses is obviously wrong, and when the white sticker is recognized, pulses are continuously output.
However, the waveforms viewed by the data acquisition card, the 6 white paper stickers identified after one revolution of the wheel, exactly output 6 pulses. The number of pulses output by the arduino is as shown above, which is not the change of high and low levels but adds 1
I am very grateful to ask the great master for advice!

**Comment by tanghui0102** [comment]
![eafb906b3c1dde857c913f2599a6cb8](https://user-images.githubusercontent.com/47203090/89486704-39263580-d7d6-11ea-98a5-da6e50307921.png)

**Comment by earlephilhower** [comment]
The template was ignored, closing.

https://gitter.im/esp8266/Arduino or https://www.esp8266.com are the appropriate forums for general questions like this.
