### ISSUE TITLE
http.getString() returns empty

### ISSUE THREAD

**Issue by JohnGooiker** [esp8266/Arduino#7511]
### Problem Description

I expect the following string as a responce to a API call and when I use following String it works and get parsed fine:

String json = "{\"state\":{\"on\":true,\"bri\":254,\"hue\":7688,\"sat\":199,\"effect\":\"none\",\"xy\":[0.5014,0.4153],\"ct\":443,\"alert\":\"select\",\"colormode\":\"xy\",\"mode\":\"homeautomation\",\"reachable\":true},\"swupdate\":{\"state\":\"noupdates\",\"lastinstall\":null},\"type\":\"Extended color light\",\"name\":\"Hue lightstrip\",\"modelid\":\"LST002\",\"manufacturername\":\"Signify Netherlands B.V.\",\"productname\":\"Hue lightstrip plus\",\"capabilities\":{\"certified\":true,\"control\":{\"mindimlevel\":40,\"maxlumen\":1600,\"colorgamuttype\":\"C\",\"colorgamut\":[[0.6915,0.3083],[0.17,0.7],[0.1532,0.0475]],\"ct\":{\"min\":153,\"max\":500}},\"streaming\":{\"renderer\":true,\"proxy\":true}},\"config\":{\"archetype\":\"huelightstrip\",\"function\":\"mixed\",\"direction\":\"omnidirectional\",\"startup\":{\"mode\":\"safety\",\"configured\":true}},\"uniqueid\":\"00:17:88:01:04:48:f5:84-0b\",\"swversion\":\"1.50.2_r30933\",\"swconfigid\":\"59F2C3A3\",\"productid\":\"Philips-LST002-1-LedStripsv3\"}";

but when I use the http.getString() to fill the String it keeps empty (despite the GET code is 200)

String json = http.getString();

**Comment by devyte** [comment]
Issue template was completely ignored, no context available.
Closing due to not compliant.
