### ISSUE TITLE
ERROR - 

### ISSUE THREAD

**Issue by BBELLIDO** [esp8266/Arduino#7518]
Hello, 

Thanks in advance. I'm developing a project on ESP32. I've been trying to use hash library for more than  a week, I'm desperate. I always get de same error on platformio o arduino IDE, I've tried ever thing. What can I do to solve this error? 
I would be very grateful if you gave me light on this matter. This is the error on platformio (on arduino IDE is very similar).

Building in release mode
Linking .pio\build\esp32dev\firmware.elf
C:\Users\bbellido\.platformio\packages\framework-arduinoespressif32\tools\sdk\lib\libwpa_supplicant.a(sha1-internal.o): In function `SHA1Transform':
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/wpa_supplicant/src/crypto/sha1-internal.c:180: multiple definition of `SHA1Transform'
.pio\build\esp32dev\lib51f\libSHA-1 Hash.a(sha1.c.o):C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:66: first defined here
C:\Users\bbellido\.platformio\packages\framework-arduinoespressif32\tools\sdk\lib\libwpa_supplicant.a(sha1-internal.o): In function `SHA1Init':
sha1-internal.c:(.text.SHA1Init+0x0): multiple definition of `SHA1Init'
.pio\build\esp32dev\lib51f\libSHA-1 Hash.a(sha1.c.o):C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:109: first defined here
C:\Users\bbellido\.platformio\packages\framework-arduinoespressif32\tools\sdk\lib\libwpa_supplicant.a(sha1-internal.o): In function `SHA1Update':
sha1-internal.c:(.text.SHA1Update+0x0): multiple definition of `SHA1Update'
.pio\build\esp32dev\lib51f\libSHA-1 Hash.a(sha1.c.o):C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:111: first defined here
C:\Users\bbellido\.platformio\packages\framework-arduinoespressif32\tools\sdk\lib\libwpa_supplicant.a(sha1-internal.o): In function `SHA1Final':
sha1-internal.c:(.text.SHA1Final+0x0): multiple definition of `SHA1Final'
.pio\build\esp32dev\lib51f\libSHA-1 Hash.a(sha1.c.o):C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:151: first defined here
.pio\build\esp32dev\lib51f\libSHA-1 Hash.a(sha1.c.o): In function `SHA1Transform':
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:90:(.irom0.text+0x20): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x4)
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:90:(.irom0.text+0x28): dangerous relocation: l32r: literal placed after use: .irom0.literal
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:90:(.irom0.text+0x42): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x8)
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:95:(.irom0.text+0x4af): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0xc)
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:100:(.irom0.text+0x8b4): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x10)
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:105:(.irom0.text+0xd38): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x14)
.pio\build\esp32dev\lib51f\libSHA-1 Hash.a(sha1.c.o): In function `SHA1Init':
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:129:(.irom0.text+0x113f): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x1c)
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:130:(.irom0.text+0x1144): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x20)
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:131:(.irom0.text+0x1149): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x24)
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:132:(.irom0.text+0x114e): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x28)
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:133:(.irom0.text+0x1153): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x2c)
.pio\build\esp32dev\lib51f\libSHA-1 Hash.a(sha1.c.o): In function `SHA1Final':
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:166:(.irom0.text+0x11d7): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x38)
.pio\build\esp32dev\lib51f\libSHA-1 Hash.a(sha1.c.o): In function `SHA1Transform':
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:74:(.irom0.text+0xe): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x18)
.pio\build\esp32dev\lib51f\libSHA-1 Hash.a(sha1.c.o): In function `SHA1Update':
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:151:(.irom0.text+0x119a): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x30)
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:159:(.irom0.text+0x11ca): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x34)
.pio\build\esp32dev\lib51f\libSHA-1 Hash.a(sha1.c.o): In function `SHA1Final':
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:205:(.irom0.text+0x127a): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x3c)
C:\Users\bbellido\.platformio\lib\SHA-1 Hash\src\sha1/sha1.c:207:(.irom0.text+0x128e): dangerous relocation: l32r: literal placed after use: (.irom0.literal+0x40)
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp32dev\firmware.elf] Error 1

**Comment by d-a-v** [comment]
This is esp8266 :)
