### ISSUE TITLE
MD5 Verification fails on HTTPUpdate after unsuccessful OTAUpdate

### ISSUE THREAD

**Issue by CriPstian** [esp8266/Arduino#7524]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:					[ESP8266]
- Core Version:			[a5432625d93f60d7e28cfdc5ed8abb3e0151951d]
- Development Env:		[CLion] 
- Operating System:		[Ubuntu|]

### Settings in IDE

- Module:  			[Nodemcu]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB]
- lwip Variant:   [?]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[OTA]
- Upload Speed:   [9600]

### Problem Description

MD5 Verification fails on HTTP Update (with no `x-MD5` header response) after unsuccessful OTA Update because the `_target_md5` string in `Updater` class is not restored to default value.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

No need for a sketch, This is a reproducible issue by following two basic steps:
1. Fail an `OTAUpdate` by cancelling the update in the middle of the process
2. Trigger an `HTTPUpdate` with a server that has no `x-MD5` header set on the response.
=> The update will fail with MD5 Check fail

### Debug Messages

```
MD5 Failed: expected:<_target_md5>, calculated:<md5>

```

**Comment by earlephilhower** [comment]
Fixed via #7534
