### ISSUE TITLE
connect to database

### ISSUE THREAD

**Issue by dinurwahyu** [esp8266/Arduino#7525]
i try connect my arduino adn esp8266 to local database.
my database and php file is normal (test with manual input localhost/arduino_mysql/control.php?dataKelembaban=611.00&dataSuhu=611.00).

but the value from arduino doesnt input to data base
----------------------------- Remove above -----------------------------

Hardware:
Board: arduino uno and esp8266

//Change the code below by your sketch
#include <SoftwareSerial.h>

SoftwareSerial wifi(2, 3); // RX Arduino, TX Arduino

String mySSID = "waipai"; // ssid
String myPass = "dindin46"; // pass
String ServerIP = "192.168.43.101"; // Ip server/laptop kita 192.168.43.101
String host = "localhost"; //host
float DataKelembaban;
float DataSuhu;
int potPin = A0; // deklarasi pin 2 untuk input potensio
int ledPin = 13; // deklarasi pin 13 untuk LED
//float val; // deklarasi variabel untuk penyimpanan data pembacaan

String url = "GET /arduino_esp01/tytomulyonoesp01/index.php";
String data2server;

void setup() {
Serial.begin(9600);
wifi.begin(9600);

Serial.println("-------------------------------MULAI KONEK ----------------------------------");
wifi.println("AT");
ShowResponse(3000);//delay(3000);

wifi.println("AT+CWMODE=1");
ShowResponse(3000);//delay(3000);

Serial.println("Reset ESP");
wifi.println("AT+RST");
ShowResponse(3000);//delay(3000);

Serial.print("Connect AP : ");
Serial.println(mySSID);
connectAP(mySSID, myPass);

}

void connectAP(String SSID, String Pass){ // fungsi koneksi ke AP
//bila ESP baru harus set Mode ke station (AT+CWMODE=1) terlebih dahulu
Serial.println("Connecting...");
wifi.print("AT+CWJAP="");
wifi.print(SSID);
wifi.print("","");
wifi.print(Pass);
wifi.println(""");
ShowResponse(3000);//delay (5000);
wifi.println("AT+CIFSR");
ShowResponse(5000);
//delay (3000);
}

void loop() {
Serial.println("-------------------------------MULAI LOOPING ----------------------------------");
DataSuhu = analogRead(potPin); // memasukan nilai pembacaan analog pin potensio ke variabel val
DataKelembaban = analogRead(potPin);

digitalWrite(ledPin,HIGH); // menyalakan LED
delay(DataSuhu); // menunggu selama nilai variabel val
digitalWrite(ledPin,LOW); // mematikan LED
delay(DataKelembaban); // menunggu selama nilai variabel val

Serial.println (DataSuhu);
Serial.println (DataKelembaban);

//Serial.println("Check Mode Device From Server = ");
String url = "GET /arduino_mysql/control.php?dataKelembaban=";
data2server = url;
data2server += DataKelembaban;
data2server += "&dataSuhu=";
data2server += DataSuhu;
data2server += " HTTP/1.1\r\n";

Serial.println("-------------------------------SENDING DATA ----------------------------------");
Sending_To_phpmyadmindatabase();
delay(3000);

Serial.println("-------------------------------CLOSE CONNECTION ----------------------------------");
wifi.println("AT+CIPCLOSE=4");
ShowResponse(3000);//delay(5000);
Serial.println("connection closed");
}
void Sending_To_phpmyadmindatabase() //CONNECTING WITH MYSQL
{
Serial.println ("sending data ke database ....");
wifi.println("AT+CIPMUX=1");//biar bisa diakses web
ShowResponse(3000);//delay(2000);

wifi.print("AT+CIPSTART=4,"TCP","");//memulai koneksi
wifi.print(ServerIP);
wifi.println("",80");
ShowResponse(3000);//delay(3000);

wifi.print("AT+CIPSEND=4,");
wifi.println(data2server.length()+host.length()+12); //6 for \r\n
ShowResponse(3000);//delay(2000);

//wifi.print("&temperature=");
//wifi.print(DataSuhu);

wifi.print(data2server);
wifi.print("Host: ");
wifi.print(host);
wifi.print("\r\n");
//wifi.print();

Serial.println (data2server + host);
}

void ShowResponse(int wait){
Serial.print("response ESP : ");
long timeNOW = millis();
String hasilread;
while(millis()-timeNOW < wait){
while(wifi.available()){
hasilread = wifi.readString();
Serial.println(hasilread);
delay(10);
return;
}
}
}

i have no problem when compiling

**Comment by devyte** [comment]
This is an issue tracker, meant for tracking issues in the core hosted in this repo, and not a general support forum.
Also, this repo is an Arduino core running directly on tje esp8266, and has nothing to do with the UNO or the AT command firmware which you seem to be using. 
Also, issue template was ignored. 
Closing due to not compliant.
