### ISSUE TITLE
MFRC and SSD 1306 Interfacing nodemcu problem

### ISSUE THREAD

**Issue by ghulamhyderpalli** [esp8266/Arduino#7539]
Help Needed!!!
I am using MFRC and ssd 1306 with node mcu but very confused because I have used the sda pin for both mfrc and ssd 1306 and it is not working together if comment ssd1306 code then it works fine.
so can anyone guide me how can I use sda pin for both of them
the code is given below ;
//SDA and SCL pins are defined below;
#define SS_PIN 4 //D2
#define RST_PIN 0 //D3
#include <SPI.h>
#include <MFRC522.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include <Fonts/FreeSansBold12pt7b.h>
#define OLED_RESET -1
Adafruit_SSD1306 display(128, 64, &Wire, OLED_RESET);
MFRC522 mfrc522(SS_PIN, RST_PIN); // Create MFRC522 instance.
int statuss = 0;
int out = 0;
void setup()
{
Serial.begin(115200); // Initiate a serial communication
SPI.begin();
display.begin(SSD1306_SWITCHCAPVCC, 0x3C);
delay(2000);
display.clearDisplay();
display.setTextColor(WHITE);
//SPI.begin(); // Initiate SPI bus
mfrc522.PCD_Init(); // Initiate MFRC522
}
void loop()
{
//welcome();
// Look for new cards
if ( ! mfrc522.PICC_IsNewCardPresent())
{
return;
}
// Select one of the cards
if ( ! mfrc522.PICC_ReadCardSerial())
{
return;
}
//Show UID on serial monitor
Serial.println();
Serial.print(" UID tag :");
String content= "";
byte letter;
for (byte i = 0; i < mfrc522.uid.size; i++)
{
Serial.print(mfrc522.uid.uidByte[i] < 0x10 ? " 0" : " ");
Serial.print(mfrc522.uid.uidByte[i], HEX);
content.concat(String(mfrc522.uid.uidByte[i] < 0x10 ? " 0" : " "));
content.concat(String(mfrc522.uid.uidByte[i], HEX));
}
content.toUpperCase();
Serial.println();
if (content.substring(1) == "42 13 44 1E") //change UID of the card that you want to give access
{
Serial.println(" Access Granted ");
Serial.println(" Welcome ");
//ssd1306 code
display.clearDisplay();
display.setTextSize(1); // Normal 1:1 pixel scale
display.setTextColor(WHITE); // Draw white text
display.setCursor(14,25); // Start at top-left corner
display.println("Verified");
display.display();
delay(1000);
Serial.println(" Have FUN ");
Serial.println();
statuss = 1;
}
else {
Serial.println(" Access Denied ");
delay(3000);
}
}
PLEASE GUIDE ME I WILL BE VERY THANKFUL

**Comment by devyte** [comment]
This is not the right place to ask for general help, this is an issue tracker, meant for tracking issues in the core hosted in this repo. Please ask such questions at a community forum like esp8266.com or stackoverflow.
Also, issue template was ignored. 
Closing due to not compliant.
