### ISSUE TITLE
Second nibble of MAC address returned by Wifi.macAddress() is wrong

### ISSUE THREAD

**Issue by ASL07** [esp8266/Arduino#7565]
### Basic Infos

- [x ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x ] I have tested that the issue is present in current master branch (aka latest git).
- [x ] I have searched the issue tracker for a similar issue.
- [x ] If there is a stack dump, I have decoded it.
- [x ] I have filled out all fields below.

#### Platform

- Hardware:		                ESP8285
- Core Version:			latest git hash or date
- Development Env:		Platformio
- Operating System:		MacOS

### Settings in IDE

- Module:  			sonoff_mini
- Flash Mode:			dout
- Flash Size: 		  1MB
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

Wifi.macAddress() returned MAC's byte 1 is wrong.

This MAC differs from the real MAC of the device in the network. Specifically, the second nibble of the first byte is wrong.
I have tried in different devices and all of them ave the same problem.
Please see below:

```bash
sudo nmap 192.168.4.1
Password:
Starting Nmap 7.70 ( https://nmap.org ) at 2020-08-31 11:36 CEST
Nmap scan report for 192.168.4.1
Host is up (0.011s latency).
Not shown: 998 closed ports
PORT   STATE SERVICE
80/tcp open  http
81/tcp open  hosts2-ns
MAC Address: E2:98:06:C2:07:C1 (Unknown) // This is the MAC address of the ESP8266 seen by the router
```

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>

void setup() {
    Serial.begin(115200);
    Serial.print("MAC: ");
    Serial.println(WiFi.macAddress());
}

void loop() {

}

```

### Debug Messages

Expected:
```
MAC: E2:98:06:C2:07:C1
```

Actual:
```
MAC: E0:98:06:C2:07:C1 // Second nibble of the first byte is wrong
```

**Comment by d-a-v** [comment]
`WiFi.macAddress()` is STA's one.
`WiFi.softAPmacAddress()` is AP's one.
