### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by jack-the-hack** [esp8266/Arduino#7584]
how do I fix this?

` ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
vac02aff5
~ld`
I was testing a temp probe when this happened.
nothing I've read helps.
I have a Nodemcu v3.
I got this output from serial monitor baud 115200.
Ask me if you need code.
HELP!

**Comment by jack-the-hack** [comment]
why is this closed?

**Comment by jandrassy** [comment]
> why is this closed?

because you ignored the template

**Comment by pipi61** [comment]
Hi!
too little information.
This not a chat forum.
Go to [https://www.esp8266.com/viewforum.php?f=25](url)
