### ISSUE TITLE
Bypass 8 client limit esp8266

### ISSUE THREAD

**Issue by notsolowki** [esp8266/Arduino#7606]
Is there a way to allow the esp8266 soft_ap to allow up to 10 clients connected at one time?

**Comment by notsolowki** [comment]
Everything im reading is showing 8 maximum. i am hoping for a slightly different answer.  Is the esp32 a different stry? can it handle more than 8?

**Comment by Tech-TX** [comment]
Google suggests the limit is in the 2.2.1 SDK,  so that'll be a 'no'.
https://arduino.stackexchange.com/questions/72845/increasing-esp32-ap-max-connections/73143#73143
That stackexchange is for ESP32, but I don't expect it's any different for the '8266.

**Comment by jandrassy** [comment]
https://arduino.stackexchange.com/questions/55693/how-many-clients-can-connect-to-an-esp32/55780#55780

**Comment by notsolowki** [comment]
Actually esp now looks pretty interesting for this
