### ISSUE TITLE
NTP network flood

### ISSUE THREAD

**Issue by skorokithakis** [esp8266/Arduino#7632]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:					WeMos D1 mini
- Core Version:			Unsure
- Development Env:		Platformio
- Operating System:		Ubuntu

### Problem Description

I have this code that doesn't use NTP:

https://gitlab.com/stavros/internet-cube/-/blob/master/src/main.ino

However, I see tens of NTP packets per second onto my network's NTP server. The NTP server is advertised by DHCP, so I assume that's how the ESP discovers it. I noticed the NTP flood when using Wireshark for an unrelated issue.

**Comment by pipi61** [comment]
Poweroff this ESP, and check again the NTP req. packets?

**Comment by skorokithakis** [comment]
What do you mean? There are no packets if I power off the ESP, which packets are you referring to?

**Comment by pipi61** [comment]
Yes, check if power off esp, with wireshark.
Check another Esp example, then check NTP packet exist? If not, then analyze used libraryes

**Comment by skorokithakis** [comment]
How would the ESP send packets if it's not powered on? I am very confused.

**Comment by pipi61** [comment]
If ESP not powered, and NTP packet found, then other device requ NTP...
This first check...

**Comment by skorokithakis** [comment]
I can see the source IP in the packet dump, it's definitely coming from the ESP.

**Comment by pipi61** [comment]
ok. Next check, another simple example check. If not see NTP packet, then check the used libraries (include files, and source) in your main.ino

**Comment by skorokithakis** [comment]
I have another project where I see the NTP flood from as well. I also have various others where I don't, but those are older. I will try to remove libraries one by one, but WiFiManager is the only one that could be interfering...

**Comment by pipi61** [comment]
Yes remove step by step, and check :)

**Comment by d-a-v** [comment]
@skorokithakis Any news ?

Can you filter incoming/outgoing packets by mac address (not IP) and show dhcp (udp ports 67, 68) and ntp (udp, port 123) so we try and understand what happens.

Also in the source code you give in OP, `WiFiManager` instance is declared as local in `setup()`. I'm not sure that's the best way to use it. Can you try to move it as global instance ?

FYI, current master has an integrated "wireshark" facility in the Netdump library.

**Comment by skorokithakis** [comment]
Moving WiFiManager to a global seems to have fixed the issue, thank you!
