### ISSUE TITLE
OTA HTTP Server Header Information Incorrect in Documentation 

### ISSUE THREAD

**Issue by sidwarkd** [esp8266/Arduino#7634]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

### Problem Description

In the documentation for the OTA [HTTP Server method](https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html#http-server) the information surrounding headers passed to the server is incorrect.

The  [code](https://github.com/esp8266/Arduino/blob/70e4457041eeb723033fc8011f3d724245d004ae/libraries/ESP8266httpUpdate/src/ESP8266httpUpdate.cpp#L262) has been updated but the documentation hasn't. 

I have submitted #7633 to address this.

**Comment by earlephilhower** [comment]
Closed via #7633
