### ISSUE TITLE
ESP8266 stack dumps

### ISSUE THREAD

**Issue by LolLeetx** [esp8266/Arduino#7635]
### Basic Infos

- x This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- x If there is a stack dump, I have decoded it.
- x I have filled out all fields below.

#### Platform

- Hardware:			ESP-12E
- Core Version:			latest git hash 
- Development Env:		Arduino IDE
- Operating System:	Windows

### Settings in IDE

![image](https://user-images.githubusercontent.com/44112492/95013755-e7cee100-0674-11eb-9c1e-560f7ad5a042.png)

### Problem Description

stack dumps in ESP8266

**my code:**
#include <ESP8266WiFi.h>                                                
#include <FirebaseArduino.h>                                            

#define FIREBASE_HOST "xxxxxxxxxxxxxx"
#define FIREBASE_AUTH "xxxxxxxxxxxxx"
#define WIFI_SSID "xxxxxxxxxx"
#define WIFI_PASSWORD "xxxxxxxxxxxxxx#"                               

void setup() {
Serial.begin(9600);
pinMode(D1, OUTPUT);
// connect to wifi.
WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
Serial.print("connecting");
while (WiFi.status() != WL_CONNECTED) {
Serial.print(".");
delay(500);
}
Serial.println();
Serial.print("connected: ");
Serial.println(WiFi.localIP());
Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
Firebase.set("LED_STATUS", 0);
}
int n = 0;
void loop() {
// get value
n = Firebase.getInt("LED_STATUS");
// handle error
if (n==1) {
Serial.println("LED ON");
digitalWrite(D1,HIGH);  
delay(500);
return;

}
else {
Serial.println("LED OFF");
digitalWrite(D1,LOW); 
delay(500); 
return;
}
}

**Exception decode:**
![image](https://user-images.githubusercontent.com/44112492/95013842-89563280-0675-11eb-963f-ddbd76595bcb.png)

**Comment by Tech-TX** [comment]
This is an issue tracker for problems with the Arduino ESP-8266 core files and libraries, not a "my code blows chunks" help forum.  http://esp8266.com is probably the right venue for this.

You don't have any problem description, merely a decoded dump.  When you've figured out whether it's that third-party library in your MCVE or one of the core files/libraries, you're half way to solving your own problem.
