### ISSUE TITLE
I can’t see datas in grafana + influxdb using GKE/GCP platform/tutorial

### ISSUE THREAD

**Issue by patusaembedded** [esp8266/Arduino#7645]
Hi,

I stay trying this: https://github.com/Nilhcem/esp32-cloud-iot-core-k8s/tree/master/05-influxdb_grafana_k8s 1 of this: http://nilhcem.com/iot/cloud-iot-core-with-the-esp32-and-arduino

In function i put: host: http:influxdb, port: 8086, db: iot.

In New dashboard -> Graph -> metrics, I can’t see datas from temperature AND humidity. I don’t think I know how to use the query options (since I’ve tried several and several) or the data is not being stored correctly in influxDB.

In kubectl get services I can’t access external ip: 3X.7X.108.40 :8086 of the influxDB. But grafana And influxdb stay running in GKE

https://community.grafana.com/t/i-cant-see-datas-in-grafana-influxdb-using-gke-gcp-platform-tutorial/37651

**Comment by Tech-TX** [comment]
You apparently can't read the address in your browser...  this issue tracker for esp8266/Arduino has **nothing** to do with what you're describing.
