### ISSUE TITLE
Broken link I think

### ISSUE THREAD

**Issue by fredericplante** [esp8266/Arduino#766]
On this page,

http://arduino.esp8266.com/versions/1.6.5-1106-g8253b82/doc/reference.html

this link:

http://arduino.esp8266.com/ESP8266FS-1.6.5-1105-g98d2458.zip

return this:

"Cannot GET /ESP8266FS-1.6.5-1105-g98d2458.zip "

How is your day?

**Comment by pgollor** [comment]
I have the same problem. The old esp8266.jar file from the old link works for me:
http://arduino.esp8266.com/ESP8266FS-1.6.5-1092-g6c7557b.zip

Greets
Kalle

**Comment by igrr** [comment]
Sorry about that guys. Should be fixed now.
