### ISSUE TITLE
Arduino IDE:  esptool.FatalError: Invalid head of packet (0x46)

### ISSUE THREAD

**Issue by FrFrey98** [esp8266/Arduino#7669]
Hey,
I have a problem while trying to use the Feather Huzzah (https://www.adafruit.com/product/3213) with the Ardurino IDE. I configurated the IDE like it is recommended in here : https://learn.adafruit.com/adafruit-fea ... rduino-ide, but when I try to upload my code I get the message "esptool.FatalError: Invalid head of packet (0x46)". I even tried it not with my own code but with the Blink test code from the same article, but the error message stays the same.
Maybe someone has an idea where this problem comes from.
I am from Germany so excuse me if my english is not perfect.
Here ist the completet log of the Arduino IDE:

Arduino: 1.8.13 (Windows 10), Board: "Adafruit Feather HUZZAH ESP8266, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Executable segment sizes:

IROM : 237664 - code in flash (default or ICACHE_FLASH_ATTR)

IRAM : 28080 / 32768 - code in IRAM (ICACHE_RAM_ATTR, ISRs...)

DATA : 1260 ) - initialized variables (global, static) in RAM/HEAP

RODATA : 804 ) / 81920 - constants (global, static) in RAM/HEAP

BSS : 25464 ) - zeroed variables (global, static) in RAM/HEAP

Der Sketch verwendet 267808 Bytes (25%) des Programmspeicherplatzes. Das Maximum sind 1044464 Bytes.

Globale Variablen verwenden 27528 Bytes (33%) des dynamischen Speichers, 54392 Bytes für lokale Variablen verbleiben. Das Maximum sind 81920 Bytes.

esptool.py v2.8

Serial port COM3

Connecting....

Chip is ESP8266EX

Features: WiFi

WARNING: Detected crystal freq 20.22MHz is quite different to normalized freq 26MHz. Unsupported crystal in use?

Crystal is 26MHz

MAC: 00:08:ff:00:00:00

Uploading stub...

Running stub...

Traceback (most recent call last):

File "C:\IoTW\arduino-1.8.13\portable\packages\esp8266\hardware\esp8266\2.7.2/tools/upload.py", line 65, in

esptool.main(cmdline)

File "C:/IoTW/arduino-1.8.13/portable/packages/esp8266/hardware/esp8266/2.7.2/tools/esptool\esptool.py", line 2909, in main

esp = esp.run_stub()

File "C:/IoTW/arduino-1.8.13/portable/packages/esp8266/hardware/esp8266/2.7.2/tools/esptool\esptool.py", line 637, in run_stub

p = self.read()

File "C:/IoTW/arduino-1.8.13/portable/packages/esp8266/hardware/esp8266/2.7.2/tools/esptool\esptool.py", line 292, in read

return next(self._slip_reader)

File "C:/IoTW/arduino-1.8.13/portable/packages/esp8266/hardware/esp8266/2.7.2/tools/esptool\esptool.py", line 2057, in slip_reader

raise FatalError('Invalid head of packet (0x%s)' % hexify(b))

esptool.FatalError: Invalid head of packet (0x46)

esptool.FatalError: Invalid head of packet (0x46)

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

**Comment by earlephilhower** [comment]
This is not a general support board.  As directed in the template, please use https://esp8266.com or https://gitter.im/esp8266/Arduino for help with this kind of question.
