### ISSUE TITLE
wifi_station_set_hostname()

### ISSUE THREAD

**Issue by mtnbrit** [esp8266/Arduino#768]
Hi, when I check my DHCP server, the esp8266's don't have hostnames, but when I look in my Ubiquiti UniFi controller, I see ESP_xxyyzz hostnames made up from the last 3 of the mac address. Wondering how this name was set, I found the sdk has this function wifi_station_set_hostname(). Is this function exposed in Arduino/esp8266? Or some other way to set this hostname outside of dhcp or mDNS?

**Comment by Humancell** [comment]
The first three octets of a MAC Address are the registered vendor ID.  My guess is that your Ubiquiti UniFi is using this information to look up and display an abbreviation of the vendor name?

**Comment by pgollor** [comment]
Hi,
You can call the function directly in yout `setup()` function. Please see the [CallSDKFunctions](https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/esp8266/examples/CallSDKFunctions/CallSDKFunctions.ino) example sketch for more details.

```
wifi_station_set_hostname("foobar");
```
This is working for me. :-)
Please close your issue if it works.

**Comment by Links2004** [comment]
here is an APIfor this in the WiFi class

https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.h#L310-L321

**Comment by mtnbrit** [comment]
When I include the espressif sdk, I get several compile errors

```error: 'size_t' was not declared in this scope```

I tried including ```#include <stdlib.h>``` but it didn't help.

**Comment by mtnbrit** [comment]
never mind, i fixed the compile error by putting stdlib.h include before the sdk include...

**Comment by mtnbrit** [comment]
```wifi_station_set_hostname("foobar")``` works a treat, thanks!
