### ISSUE TITLE
how does .serveStatic(...) works?

### ISSUE THREAD

**Issue by Yoshi20** [esp8266/Arduino#769]
I saved index.html in the FS ("/data/index.html") and tryed the following functioncall:

server.serveStatic("/", SPIFFS, "/data/index.html");

but it doesn't seems to work.
Is this function still a work in progress or do I do something wrong?

**Comment by pgollor** [comment]
```
void ESP8266WebServer::serveStatic(const char* uri, FS& fs, const char* path) {
    _addRequestHandler(new StaticRequestHandler(fs, uri));
}
```

This code snippet is out `ESP8266WebServer.cpp`. The function seems to be not finished yet.

**Comment by igrr** [comment]
Well spotted, looks like StaticRequestHandler doesn't take FS "path" into account. Will fix.

**Comment by Yoshi20** [comment]
nice :+1: 
I'm looking forward to it.

**Comment by Yoshi20** [comment]
The Fix: "ESP8266WebServer::serveStatic to work for both files and directories"
Seems to work perfectly  -> Close issue

**Comment by mbenitez01** [comment]
was this (server.serveStatic) ever fixed?!?!? I have NEVER been able to serve a miserable file with this method... 8-(
