### ISSUE TITLE
Arduino Problem

### ISSUE THREAD

**Issue by BALQISALHOSNI** [esp8266/Arduino#7700]
I get this message in Arduino.. what is the problem?
No GPS detected: check wiring.

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffdf0 end: 3fffffc0 offset: 01a0
3fffff90:  3fffdad0 00000000 3ffee4f8 40201b6a  
3fffffa0:  3fffdad0 00000000 3ffee760 402057ec  
3fffffb0:  feefeffe feefeffe 3ffe84f4 401011d9  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:1, boot mode:(3,0)

load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld

**Comment by 5chufti** [comment]
most probably your sketch can't find the gps and therefor goes into enldess loop w/o yielding to keep watchdog happy.
But this is not a problem with the esp8266 arduino core, it is a problem of your Arduino sketch. 
So please close the issue and ask the nice people over at https://www.esp8266.com for further help.
