### ISSUE TITLE
Motor driver like #l2983d# available or not?

### ISSUE THREAD

**Issue by ShahriarShafin** [esp8266/Arduino#7701]
Is there any motor driver like #l2983d# available for esp8266? I want to control multiple motor and servo.

**Comment by 5chufti** [comment]
and what would this hw related request have to do with an issue of the esp8266 arduino core?
please close the issue (it will be closed anyway w/o the filled questionaire) and politely ask again over at 
https://www.esp8266.com where such questions will be answered
