### ISSUE TITLE
Exception (28): epc1=0x4020b274 epc2=0x00000000 epc3=0x00000000 excvaddr=0x0000006c depc=0x00000000

### ISSUE THREAD

**Issue by metaphaz** [esp8266/Arduino#7711]
Hi, a have a problem with my NodeMCU esp8266. Thats my code. I am new at codding and arduino ı have no idea to how to fix it .It resets itself.  I need some help.
 

CODE
----------------------------------------------------------------------------
#include <ESP8266WiFi.h>
#include <FirebaseArduino.h>

#define FIREBASE_HOST "...."
#define FIREBASE_AUTH "........"
#define WIFI_SSID "........."
#define WIFI_PASSWORD "........."

void setup() {
  Serial.begin(9600);
  pinMode(D7,OUTPUT);
  
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("connecting");
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }
  Serial.println();
  Serial.print("connected: ");
  Serial.println(WiFi.localIP());
  
  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);
}

int n = 0;

void loop() {
String lampStatus = Firebase.getString("lamp");
if (Firebase.failed()) {
      Serial.print("setting /number failed:");
      Serial.println(Firebase.error());  
      return;
  }
Serial.print("lampStatus"); Serial.println(lampStatus);

if (lampStatus == "1"){
  digitalWrite(D7,LOW);
  }
else if (lampStatus == "0") {
  digitalWrite(D7,HIGH);
  }
}
---------------------------------------------------------------------------------------------------

ERROR
------------------------------------------------------------------------------------------------------
Exception (28):
epc1=0x4020b274 epc2=0x00000000 epc3=0x00000000 excvaddr=0x0000006c depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffc80 end: 3fffffc0 offset: 0190
3ffffe10:  00000000 00000001 3ffffed4 3ffee928  
3ffffe20:  0000000b 3ffee8f0 3ffeffa0 40205760  
3ffffe30:  3ffe8762 000001bb 3ffeffa0 40206688  
3ffffe40:  3ffe8816 0000003b 3ffeffa0 40206ab8  
3ffffe50:  0000003b 3ffee8f0 0000002e 4020355c  
3ffffe60:  3ffffea8 0000003b 3ffffe90 40207484  
3ffffe70:  3ffee8ec 3ffffe90 3ffe8816 3fffff10  
3ffffe80:  3ffee8ec 3ffffed4 3ffeff9c 40204de7  
3ffffe90:  3fff2d0c 003b003f 00fffed4 3fff029c  
3ffffea0:  0038003f 00ffff80 3fff0084 001c001f  
3ffffeb0:  00fe87ac 3ffee8e8 3fffff84 3fffff10  
3ffffec0:  3ffee8ec 3ffe8793 3ffefd1c 40202bac  
3ffffed0:  3ffe87ac 3fff0040 3fff2f2c 3ffee9c4  
3ffffee0:  3fffff80 3fffff10 3ffe87ac 40203520  
3ffffef0:  3fffff18 3fffff30 3fffff30 3ffee9c4  
3fffff00:  3fffff80 3ffefd1c 3ffee8e8 40203e11  
3fffff10:  3ffee928 3fff00d0 40100030 40209219  
3fffff20:  3fffdad0 3ffee8e8 3fffff8c 40203e52  
3fffff30:  40206b34 3ffee948 3ffe88a4 40206b40  
3fffff40:  00000004 3ffee948 3ffe88a4 40206e09  
3fffff50:  00000000 00000004 3fffff80 40207484  
3fffff60:  3fffdad0 3fffff80 3ffe8730 402074ba  
3fffff70:  3fffdad0 3ffee8e8 3ffee984 4020111f  
3fffff80:  706d616c 00000000 84000001 40100154  
3fffff90:  3fffdad0 00000000 3ffee984 40100175  
3fffffa0:  3fffdad0 00000000 3ffee984 40208304  
3fffffb0:  feefeffe feefeffe 3ffe857c 40100c39  
<<<stack<<<
--------------------------------------------------------------------------------------------------

**Comment by earlephilhower** [comment]
Template was ignored and exception was not decoded, closing.
