### ISSUE TITLE
ESP8266EX can support 32MB?

### ISSUE THREAD

**Issue by AMBULATUR** [esp8266/Arduino#7718]
Hello,recently i recieve these package [https://aliexpress.ru/item/1005001290915248.html](url)
Seller said that board have ESP8266EX + 32MB(M-Byte?) but in datasheet[https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf](url)
ESP8266EX can "uses external SPI flash to store user programs, and supports up to 16 MB
memory capacity theoretically."  
And under a magnifying glass I saw that i have 

![vUsJokk 1](https://user-images.githubusercontent.com/30321471/99918720-d9727c80-2d29-11eb-86b9-4b484a152b43.png)

Datashit of flash memory says that it 32M-BIT not 32-M-Byte
Datasheet - [https://www.winbond.com/resource-files/w25q32fv%20revi%2010202015.pdf](url).

So, is i'm right or not and plate realy ESP8266 + 32MB(M-Byte)?

Which settings should i use? Is my settings right(sry 4 rus lang)?
![2MG5DY3 1](https://user-images.githubusercontent.com/30321471/99918648-87c9f200-2d29-11eb-9536-139645e195d9.png)

**Comment by d-a-v** [comment]
`esptool.py flash_id` will tell you the true size. It's probably 4MBytes = 32Mbits.
(I don't think 32MBytes flash chips are supported).

**Comment by earlephilhower** [comment]
Good eyes!

10 seconds on a search engine shows that "25Q32BSIG" is a 32Mbit*, and hence 4M*byte* chip.  Nothing to do here, closing.

**Comment by AMBULATUR** [comment]
By the way, sorry for being annoying, what am i doing wrong?
![gE25zMf 1](https://user-images.githubusercontent.com/30321471/99921145-899bb180-2d39-11eb-82cc-c3cd22200ec8.png)
In code i set Serial.Begin(115200) as all guides request, but when i set in Serial Monitor baud to 115200 i receive wrong data, or nothing, but when i set 74880 baud in Serial Montior, and press "RST" button i get "Error?" and data goes correct, what does this error mean?

**Comment by d-a-v** [comment]
ESP boot-up babbling works at 115200/40*26 baud.
Then in your sketch you can set 115200 and ESP will speak at 115200.
That is it for everybody.
If that's not the case for you, you can open a new issue and this time don't avoid to fill the issue template.
