### ISSUE TITLE
WiFiWebServer example not stable

### ISSUE THREAD

**Issue by ThomasCLee** [esp8266/Arduino#772]
I am not sure why the WiFiWebServer example sometimes work and sometimes doesn't.

When it doesn't work, it seems to reach to this point but never detects a client . Any idea why?

 WiFiClient client = server.available();
  if (!client) {
    return;
  }

**Comment by igrr** [comment]
This may happen for a number of reasons. For instance you might end up in a situation when all the TCP connections at the ESP side are in TIME_WAIT state. The server will not respond to another request until one of the connections gets freed up after timeout (four minutes as per TCP spec).

You might want to use wireshark to see what's going on at the network level when this condition happens.

**Comment by drmpf** [comment]
I am looking at this problem at the moment.
Would you add an option to change the connection timeout if no traffic in either direction,
I my case I would set it to 5secs.

**Comment by ThomasCLee** [comment]
How do I add connection timeout?

**Comment by ThomasCLee** [comment]
Problem is resolved. It turns out that it is an issue with the router. My router has a feature called 'HT 20/40 Coexistence'. After turning it off, it works.
