### ISSUE TITLE
https://github.com/esp8266/Arduino/pull/7543 corrupt binary upload like index.html.gz

### ISSUE THREAD

**Issue by luc-github** [esp8266/Arduino#7723]
### Basic Infos

- [ X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X ] I have tested that the issue is present in current master branch (aka latest git).
- [X ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it. N/A
- [ X] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[latest git 25/11/2020] 
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Nodemcu]
- Flash Mode:			[dio]
- Flash Size: 		[4MB/FS2MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[160MHz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200r] (serial upload only)

### Problem Description

Since this commit https://github.com/esp8266/Arduino/pull/7543,  binary upload like index.html.gz is corrupted
so the result is when web access to corrupted file the encodding is not recognized

Need to upload file - then try to access it using webserver
with commit the page cannot be displayed 
without commit everything is fine

No issue with text file as there is not need for browser to expand the file, even corrupted it is loaded
good file [index.html(2).gz](https://github.com/esp8266/Arduino/files/5596591/index.html.2.gz)
corrupted file [index.html(1).gz](https://github.com/esp8266/Arduino/files/5596592/index.html.1.gz)

![image](https://user-images.githubusercontent.com/8822552/100226890-a47c4a80-2f20-11eb-97a5-ad3950a0fccc.png)

For what I can see the 0D 0A code is modified in uploaded file - corrupting it

### [MCVE](https://stackoverflow.com/help/mcve) Sketch
I used FSBrowser sample to check

**Comment by earlephilhower** [comment]
Thanks for the clear repro steps.  I was able to duplicate locally.  Basically, once a `0x0d` comes in the following byte is garbled on writing to flash, so the change listed has an issue.  I'll look into it.
