### ISSUE TITLE
Earl is not correct and sscanf() is not following the POSIX standard see Linux manual page. 

### ISSUE THREAD

**Issue by tvonderhaar** [esp8266/Arduino#7731]
Earl I don't know what your talking about. The last standard from POSIX stated in the Linux manual page for sscanf() is POSIX.1-2001 was not 30 years ago and that standard requires exactly what I wrote in my issue. You can close out my issue but it doesn't make your comment correct or civil. See Linux manual page at link below.

[https://man7.org/linux/man-pages/man3/scanf.3.html](url)

**Comment by earlephilhower** [comment]
"Above our pay grade" isn't meant to be uncivil.  It means it's too big to be handled here, upstream is where this code comes from.

GLIBC and Newlib both perform the same way with your code, as shown in the prior closed bug, so if you believe they are wrong then please do be my guest and bring it up on the GCC or RedHat mailing lists.  But there's nothing to do here about it, and opening up issues like this really isn't helping your cause.
