### ISSUE TITLE
LittleFS-Example vs. Documentation

### ISSUE THREAD

**Issue by holgerlembke** [esp8266/Arduino#7756]
All LittleFS-Examples do
```
#include <FS.h>
#include <LittleFS.h>
```

https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html says to use
```
#include <LittleFS.h>
```

What is the correct way?

(A user of my ESPxWebFlMgr had a problem because I use the first style and she fixed all problems by switching to the later style...)

**Comment by earlephilhower** [comment]
Either is fine, but the second, single-include version probably should be in all the examples.  Would you like to do a PR changing them all to just the 1-include version?

**Comment by holgerlembke** [comment]
Thanks and no.
