### ISSUE TITLE
mDNS discovery with IDE cannot detect the board name

### ISSUE THREAD

**Issue by luc-github** [esp8266/Arduino#7759]
- [x ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x ] I have tested that the issue is present in current master branch (aka latest git).
- x[ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:					ESP-12
- Core Version:			[latest git ]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 ]
- Flash Mode:			[dio]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[160MHz]
- Upload Using:		[OTA]
- Upload Speed:   [115200|] 

### Problem Description
OTA description is incomplete - variant is missing  in description in  Arduino OTA menu unlike for ESP32

![image](https://user-images.githubusercontent.com/8822552/101990159-7da27000-3ca5-11eb-8c1f-f57be9ff04ca.png)
it is due to property board which should contain the variant name, but ESP8266 put another string 
![image](https://user-images.githubusercontent.com/8822552/101990163-8a26c880-3ca5-11eb-9e8c-c59e9e8c9fba.png)
 string is put here (thanks @tobozo to find out)
https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266mDNS/src/LEAmDNS.cpp#L1278
and also https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266mDNS/src/LEAmDNS2Host.cpp#L792
So arduino IDE cannot match the variant with one present in board.txt

if I hardcode "generic" for the variant on board property - the result is correct

![image](https://user-images.githubusercontent.com/8822552/101989816-33b88a80-3ca3-11eb-92ba-2035b2b413ff.png)
![image](https://user-images.githubusercontent.com/8822552/101989826-3fa44c80-3ca3-11eb-89b5-e54f2b7f9998.png)

**Comment by mcspr** [comment]
Slight correction: "board" from mDNS (for some reason) should be equal to the ID of the board, not the whatever value we set to either board= or variant=
This is true for both the old IDE and the new one; see `arduino-cli board list` with mDNS discovery enabled
https://github.com/arduino/Arduino/blob/57a931c9c4c084057417837239ad8136f8a7b1aa/arduino-core/src/cc/arduino/packages/discoverers/NetworkDiscovery.java#L113-L119
https://github.com/arduino/arduino-cli/blob/63b53c0fa6830ce77cfb5508f06b2b4e601c90b5/cli/board/list.go#L134
(where identification prop map of this specific board is `{board: d1_mini}`)

For example, if we select `LOLIN(WEMOS) D1 R2 & mini`, mDNS should return `d1_mini`. No relation to the similarly named `build.variant=`, just the root of the property.
https://github.com/esp8266/Arduino/blob/a2982f96a49f40197a56207d6a6a0a4a34fcf90a/boards.txt#L3848

esp32 seems to use a different scheme btw, by introducing `ARDUINO_VARIANT` flag and using it's value

**Comment by mcspr** [comment]
> (where identification prop map of this specific board is {board: d1_mini})

...which we could find out normally, without going too far into the arduino-cli code
```console
$ arduino-cli.exe board details -b $board_fqbn
```
for example, huzzah
```console
$ arduino-cli.exe board details -b esp8266com:esp8266:huzzah
Board name:                Adafruit Feather HUZZAH ESP8266
FQBN:                      esp8266com:esp8266:huzzah
Board version:             3.1.0-dev

Identification properties: board=huzzah
...
```
