### ISSUE TITLE
Problems uploading sketches on OSX

### ISSUE THREAD

**Issue by antlomb** [esp8266/Arduino#777]
Hello,

I'm trying to program my new Olimex ESP8266 DEV board. I installed Arduino 1.6.5 and the last board manager (not the staging one). I'm using an adafruit console USB-Serial cable with prolifix chip.

The error I'm getting (with a void sketch) is the following:

Uploading 205184 bytes from /var/folders/f4/zcvcsf7937792h6ypzc5d_r80000gn/T/build8890676663436683318.tmp/sketch_sep13a.cpp.bin to flash at 0x00000000
error: failed reading byte
warning: espcomm_send_command: cant receive slip payload data
warning: espcomm_send_command(FLASH_DOWNLOAD_BEGIN) failed

Thanks for any help 

Kind regards

Antonio

**Comment by igrr** [comment]
This is a known issue, mentioned on the [supported boards page](https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/doc/boards.md#serial-adapter).

> PL2303-based adapters are known not to work on Mac OS X. See https://github.com/igrr/esptool-ck/issues/9 for more info.

Please follow the issue linked above for any updates.
