### ISSUE TITLE
LEAmDNS.cpp:30:47: fatal error

### ISSUE THREAD

**Issue by liwajaya** [esp8266/Arduino#7784]
C:\Users\liw566\Documents\Arduino\libraries\ESP8266mDNS\src\LEAmDNS.cpp:30:47: fatal error: LwipIntf.h: No such file or directory

 #include <LwipIntf.h> // LwipIntf::stateUpCB()

**Comment by d-a-v** [comment]
@liwajaya please update your local repository to [latest master](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/LwipIntf.h).

**Comment by earlephilhower** [comment]
No update in 2wks and nobody else seems to have the same problem, so closing for now.
