### ISSUE TITLE
Esp8266 resetting again and again

### ISSUE THREAD

**Issue by shubham1520** [esp8266/Arduino#7794]
----------------------------- Delete above -----------------------------

### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[latest git ]
- Development Env:		[Arduino IDE|]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Nodemcu]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200)

### Problem Description

Hey guys i am new to IoT and this is my second project so yes i am a newbie. I am trying to make a project in which Esp8266(nodeMCU) records distance using HC-SR04(Ultrasonic sensor and upload the data to firebase(real time database). I have also added some if else statements but my nodemcu is resetting again and again. I have tried to using multiple solutions but nothing is working out.  I am tried using both 5V and 3.3V for nodemcu but nothing is working out it keeps resetting.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp
#include <ESP8266WiFi.h>
#include "FirebaseESP8266.h"
#include <HCSR04.h>
UltraSonicDistanceSensor distanceSensor(13, 12);
#define FIREBASE_HOST "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#define FIREBASE_AUTH "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#define WIFI_SSID "xxxxxxxxxxxxxxxxxxxx"
#define WIFI_PASSWORD "xxxxxxxxxxxxxxxxxxxxxxxx"
FirebaseData firebaseData;
int SetLevelVal = 30;
int LastSetLevelVal =30;
int water_pump = 2;
boolean WP_ON=false;
boolean  wp=false;
int Dist = 0;
int recivedCMD =0;
int Tanklevel = 0;
int Length = 0;
int MinimumLevel = 30;


const int numReadings = 20;  
int readings[numReadings];
float total = 0;                 
float average = 0;



void setup() {
Serial.begin(115200);
  pinMode(water_pump,OUTPUT);
  digitalWrite(water_pump,LOW);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  Serial.print("Connecting to Wi-Fi");
  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(300);
  }
  Serial.println();
  Serial.print("Connected with IP: ");
  Serial.println(WiFi.localIP());
  Serial.println();


  //3. Set your Firebase info

  Firebase.begin(FIREBASE_HOST, FIREBASE_AUTH);

  //4. Enable auto reconnect the WiFi when connection lost
  Firebase.reconnectWiFi(true);
  
}



void loop() {
if(Firebase.get(firebaseData, "/LengthOfWaterTank"))
  {
      Length = firebaseData.intData();
      Serial.print("recivedCMD = ");
      Serial.println(recivedCMD );
  }
  else
  {
    Serial.print("Error in get, ");
    Serial.println(firebaseData.errorReason());
  }

  
 //Recive CMD from  firebase for level set/
  if(Firebase.get(firebaseData, "/SetLevel"))
  {
      SetLevelVal = firebaseData.intData();
      Serial.print("recivedCMD = ");
      Serial.println(recivedCMD );
  }
  else
  {
    Serial.print("Error in get, ");
    Serial.println(firebaseData.errorReason());
  }

 
  for (int i = 0; i < numReadings; i++)  // take 5 readings in array for find avarage of 5 values for smooth the value of time
   {
     readings[i] = distanceSensor.measureDistanceCm();
     
   }
   for (int i = 0; i < numReadings; i++) // for add all value
   {
  total=total+readings[i];
   }

    average=total/numReadings; // For average out
    
  Tanklevel = map(average,0,Length,100,0);
  Serial.print("Tanklevel  = ");
      Serial.println(Tanklevel);
// /Send water level status to firebase/

if(Firebase.setInt(firebaseData, "/waterLevel", Tanklevel))
  {
     Serial.println(" Data successfully sent");
  }
  else
  {
    Serial.print("Error in setInt, ");
    Serial.println(firebaseData.errorReason());
  }
  
 



if((LastSetLevelVal =! SetLevelVal))
{
  
  if(Tanklevel < SetLevelVal && WP_ON==false)// if water level is less then set level
  { 
    WP_ON=true;
    digitalWrite(water_pump,LOW); // turn on wp 
    //Send water pump status to firebase/

if(Firebase.setInt(firebaseData, "/WP_Status", WP_ON))
  {
     Serial.println(" Data of pump on successfully sent");
  }
  else
  {
    Serial.print("Error in setInt, ");
    Serial.println(firebaseData.errorReason());
  }
  }
  LastSetLevelVal = SetLevelVal;
 
  
  }




  
   if(Tanklevel>=SetLevelVal && WP_ON==true) // if water level is grater than maximum level tun off water pump
   {
     WP_ON=false;
    digitalWrite(water_pump,HIGH); // turn off wp
   

   //Send water pump status to firebase/

if(Firebase.setInt(firebaseData, "/WP_Status", WP_ON))
  {
     Serial.println("Data of pump off successfully sent");

  }
  else
  {
    //Failed?, get the error reason from firebaseData

    Serial.print("Error in setInt, ");
    Serial.println(firebaseData.errorReason());
  }
   }


   

if(Tanklevel<(0.3*Length)) // if water level is less than 30% turn of wp
{
  digitalWrite(water_pump,LOW); // turn on wp 
    //Send water pump status to firebase/

if(Firebase.setInt(firebaseData, "/WP_Status", 1))
  {
     Serial.println(" Data of pump on successfully sent");
  }
  else
  {
    Serial.print("Error in setInt, ");
    Serial.println(firebaseData.errorReason());
  }
  }



  

if(Tanklevel>=(0.8*Length)) //if water level is grater than 80%
{
   digitalWrite(water_pump,HIGH); // turn off wp 
    //Send water pump status to firebase/

if(Firebase.setInt(firebaseData, "/WP_Status", 0))
  {
     Serial.println(" Data of pump on successfully sent");
  }
  else
  {
    Serial.print("Error in setInt, ");
    Serial.println(firebaseData.errorReason());
  }
  
  
  }

     total=0;
   }
}

```

### Debug Messages
16:50:22.360 -> Exception (0):
16:50:22.360 -> epc1=0x4000dce5 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000
16:50:22.360 -> 
16:50:22.360 -> >>>stack>>>
16:50:22.360 -> 
16:50:22.360 -> ctx: cont
16:50:22.360 -> sp: 3ffffdc0 end: 3fffffc0 offset: 0190
16:50:22.394 -> 3fffff50:  3ffeecf0 3ffee740 3ffeedc8 4020fcd8  
16:50:22.394 -> 3fffff60:  3ffeecf0 3ffee740 3ffeedc8 40201317  
16:50:22.394 -> 3fffff70:  74655300 6576654c 80fe006c 4020112a  
16:50:22.394 -> 3fffff80:  00000050 c1980000 3ffee6e0 3fff1d00  
16:50:22.394 -> 3fffff90:  0022002f 80efeffe feefeffe 3ffeee5c  
16:50:22.394 -> 3fffffa0:  3fffdad0 00000000 3ffeee1c 4021113c  
16:50:22.394 -> 3fffffb0:  feefeffe feefeffe 3ffe8544 40100c89  
16:50:22.429 -> <<<stack<<<
16:50:22.429 -> 
'''
Debug messages go here
```


Exception 0: Illegal instruction
PC: 0x4000dce5
EXCVADDR: 0x00000000

Decoding stack results
0x4020fcd8: UltraSonicDistanceSensor::measureDistanceCm() at C:\Users\sansk\Documents\Arduino\libraries\HCSR04\src\HCSR04.cpp line 20
0x40201317: loop() at C:\Users\sansk\Documents\Arduino\mix1\trial1/trial1.ino line 103
0x4020112a: setup() at C:\Users\sansk\Documents\Arduino\mix1\trial1/trial1.ino line 60
0x4021113c: loop_wrapper() at C:\Users\sansk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 197

**Comment by devyte** [comment]
The stack dump shows the crash is in the ultrasonic lib:
> distanceSensor.measureDistanceCm()

I suggest asking for help from the lib author or at a community forum like esp8266.com or stackoverflow. Alternatively, you could try the Discussions section here, but that's brand new and we're still considering whether we'll keep it or not. 
This issue tracker is for tracking issues in the core, and not meant for general help. Closing.
