### ISSUE TITLE
Alternative call for server.on()

### ISSUE THREAD

**Issue by 69thPi** [esp8266/Arduino#7830]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12]
- Core Version:			[latest git hash]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[qio]
- Flash Size: 		[4MB]
- lwip Variant:   [v1.4]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[OTA]

### Problem Description
need an alternative for server.on(/get,handlerFunction)

Detailed problem description goes here.
I need to return 32 different values stored in an array to 32 different clients upon request.
Is there a way to override the server.on() method to look something like this server.on(/caller,response(arr[0]))

#include "ESP8266WiFi.h"
#include `"ESP8266WebServer.h"`

ESP8266WebServer server(8000);

String arr[3]={"one","two","three"};//holds data to transmit

void setup() {
  Serial.begin(115200);
  WiFi.begin("black", "pyrad007");  //Connect to the WiFi network
  while (WiFi.status() != WL_CONNECTED) {  //Wait for connection
    delay(500);
    Serial.println(".");
  }
 
  server.on("/", handleRootPath);    //Associate the handler function to the path
  server.on("/client1",response(0));
  server.begin();                    //Start the server
}
 
void loop() {
  server.handleClient();         //Handling of incoming requests
}
 
void handleRootPath() {            //Handler for the rooth path
  server.send(200, "text/html", index_html);
}
void response(int i) {            //Handler for the rooth path
  server.send(200, "text/html", arr[i]);
}

**Comment by earlephilhower** [comment]
This is a "How do I..." kind of question and belongs on www.esp8266.com or https://gitter.im/esp8266/Arduino as discussed in the issue template.

Closing.
