### ISSUE TITLE
Unable to read the analog/digital gpio on AI THINKER 

### ISSUE THREAD

**Issue by NJenny** [esp8266/Arduino#7833]
### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:				[AI THINKER BOARD (OV2640)]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino ide]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module|Wemos D1 mini r2|Nodemcu|other]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

Detailed problem description goes here.
I want to use an array of ir sensors along with the camera on OV2640 AI THINKER board. So right now I am just testing it with one ir sensor on gpio16. But I am unable to digital/analog read this pin as it always give a HIGH state. N i am not using the SD FS here. So i should be able to use other gpio16 as a normal gpio right? how do i do that?

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>

void setup() {
Serial.begin(115200);
pinMode(13,INPUT);
pinMode(16,INPUT);
}

void loop() {
if (digitalRead(16) == 1)
  {
    motion = 1;
    Serial.println("Motion detected");
  }
  else
  {
    motion = 0;
    Serial.println("no motion");
  }
}

```

### Debug Messages

```
Debug messages go here
```

**Comment by earlephilhower** [comment]
Because this is a "How do I ..." type question and not related to the core, please use the forums on esp8266.com or chat on https://gitter.im/esp8266/Arduino for assistance.  Closing.
