### ISSUE TITLE
std::remainder: undefined reference to `__ieee754_remainder'

### ISSUE THREAD

**Issue by mcspr** [esp8266/Arduino#7845]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				ESP8285
- Core Version:			c2393d05bebf18a12f21696be660ba34fec1deda
- Development Env:		PlatformIO
- Operating System:		Windows

### Settings in IDE

Defaults:

```ini
[env]
platform = espressif8266
board = d1_mini
framework = arduino

[env:git]
platform_packages =
    platformio/framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git
    mcspr/toolchain-xtensa @ 5.100200.201223
```

### Problem Description

`std::remainder` breaks the linker 

ref. https://gitter.im/esp8266/Arduino?at=6011fd5f063b6c68d520a704
@earlephilhower 

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp
#include <Arduino.h>
#include <cmath>

double does_this_work(double, double) __attribute((noinline));
double does_this_work(double a, double b) {
    return std::remainder(a, b);
}

void setup() {
    Serial.println(does_this_work(1.2345, 5.4321));
}

void loop() {
}
```

### Debug Messages

```
Compiling .pio\build\git\src\main.cpp.o
Linking .pio\build\git\firmware.elf
c:/users/maxim/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.2.0/../../../../xtensa-lx106-elf/bin/ld.exe: c:/users/maxim/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.2.0/../../../../xtensa-lx106-elf/lib\libm.a(lib_a-w_remainder.o):(.literal+0x0): undefined reference to `__ieee754_remainder'
c:/users/maxim/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.2.0/../../../../xtensa-lx106-elf/bin/ld.exe: c:/users/maxim/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.2.0/../../../../xtensa-lx106-elf/lib\libm.a(lib_a-w_remainder.o): in function `remainder':
/workdir/repo/newlib/newlib/libm/math/w_remainder.c:60: undefined reference to `__ieee754_remainder'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\git\firmware.elf] Error 1
```

**Comment by earlephilhower** [comment]
Seems it's a known issue w/newlib on the Xtensa.  Just needs a rebuild of the toolchain after a simple patch.

https://github.com/espressif/newlib-esp32/commit/d833a539d04478b3c56d82ceb7485661fd9a8c9b
