### ISSUE TITLE
Missing makeTime() function  setTime()

### ISSUE THREAD

**Issue by rin67630** [esp8266/Arduino#7860]
The ESP Arduino built-in time library should support full makeTime() and breakTime() functions . 

The function is even highlighted in the code:
*[red]*setTime*[red]*(Hour,Minute,Second,Day,Month,Year);

 But the compiler* issues:

exit status 1
'setTime' was not declared in this scope

*Arduino 1.8.13

Thank you for fixing the library or the doc.

**Comment by earlephilhower** [comment]
This is not a core issue.  Install the appropriate library using the Library Manager.  
https://github.com/PaulStoffregen/Time

**Comment by rin67630** [comment]
I found that library being conflicting with the ESP8266 time library.
