### ISSUE TITLE
TZ _Asia_Bangkok corrupt?

### ISSUE THREAD

**Issue by rin67630** [esp8266/Arduino#7870]
Using Arduino IDE 1.8.13 and the latest ESP8266 Toolchain, 
I get a weird time from the NTP server using 
TZ_Asia_Bangkok. 
TZ_Asia_Jakarta (same time zone) is OK.
Could you please check?
Thank you.

**Comment by d-a-v** [comment]
Thanks for reporting !
[This is fixed in git version](https://github.com/esp8266/Arduino/pull/7702).
Using [git version](https://arduino-esp8266.readthedocs.io/en/latest/installing.html#using-git-version) or [snapshot release](https://d-a-v.github.io/esp8266/Arduino).

**Comment by rin67630** [comment]
Wow! That was fast!
