### ISSUE TITLE
Deauth failure

### ISSUE THREAD

**Issue by Dada47** [esp8266/Arduino#7878]
Hi,
I'm using esp8266 with 2.5 bin and while i am attacking with deauth my network all the devices getting disconnecting and failure to reconnect except my smartphones (3) that they are still using my wifi as nothing ever happened.

Any idea why is that happening?

**Comment by earlephilhower** [comment]
Closing as this is unrelated to the core and the template was ignored.  Please use https://esp8266.com or https://gitter.im/esp8266/Arduino for general questions like this.
