### ISSUE TITLE
Doubtful ESP8266 card manager

### ISSUE THREAD

**Issue by droidprova** [esp8266/Arduino#7904]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:					[ESP8266
- Core Version:			[2.7.4]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[WIFI D1 MINI ESP8266 dev. board, USB CP2104 (32Mb flash)]
- Flash Mode:			[ ]
- Flash Size: 		[32MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[160MHz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200)

### Problem Description

Hi,

so I have this D1 MINI card with CP2104 USB interface and 32MB of flash:

https://robotdyn.com/wifi-d1-mini-esp8266-dev-board-usb-cp2104.html

I have difficulty understanding which, among the many, is the right board to select in the menu of the card manager of the arduino ide. I have never had problems with the classic Wemos D1 Mini Lite with 1 MB of flash that I have used so far, but now in a project where I need to use the FW update via OTA, I need more flash.

Using a lot of writing on EEPROM in my works, I noticed that this board, if associated with the choice in the board manager -> "**LOLIN (WEMOS) D1 MINI PRO**, does not handle it well.

I paste a stupid code into it that I tested with:

`#include <EEPROM.h>               // https://github.com/esp8266/Arduino/tree/master/libraries/EEPROM

int addr = 0;           // indice memoria EEPROM

int value = 5;

void setup() {
  Serial.begin(9600);
  EEPROM.begin(512);
  EEPROM.write(addr, value);
  EEPROM.commit();
  delay(200);
}

void loop() {
  Serial.println(EEPROM.read(addr));
  delay(1000);
}`

so I write 5 in EEPROM and print the value correctly by reading it from the EEPROM. Then I comment the lines and put this code on the board:

`#include <EEPROM.h>               // https://github.com/esp8266/Arduino/tree/master/libraries/EEPROM

int addr = 0;           // indice memoria EEPROM

int value = 5;

void setup() {
  Serial.begin(9600);
  EEPROM.begin(512);
 // EEPROM.write(addr, value);
 // EEPROM.commit();
 // delay(200);
}

void loop() {
  Serial.println(EEPROM.read(addr));
  delay(1000);
}
`
I open the monitor and print 0.

On the other hand, if I select **ESPino (esp 12 module)** everything works fine. So then I switch to transfer the code of my work, but I notice you keep rebooting. Ideas and advice?

Thanks so much

**Comment by d-a-v** [comment]
What you call `32MB` is probably 32Mbits, so 4MBytes.
The official D1 mini (not pro) has 4MBytes. Try with this board model.
ESPino model works because it has a 4MBytes flash chip, but pin mapping is different.
This is not a support forum but an issue tracker for the esp8266 arduino core.
Try the examples included in the arduino IDE, and use the official arduino forum, stackoverflow or gitter (esp8266 arduino) to seek help for your personal use.
