### ISSUE TITLE
Redirect to MSN

### ISSUE THREAD

**Issue by yaroshd81** [esp8266/Arduino#7919]
Good day.
I have a problem on ESP32. When i conect to AP from smartphone i redirect to 192.168.4.1 and all good working. But if i connect to AP from PC, where i have internet by ethernet, my redirected to msn.com. Why? Where i can change msn.com to 192.168.4.1? PC by OS Windows. If i disconect PC from ethernet - all good working, because i redirect to 192.168.4.1. But if i connect to ethernet by ethernet i have problem. Do you can help my?
Sorry for my bad english.

**Comment by d-a-v** [comment]
You might try with an esp8266 and have different results.

😆 

Or ask on some help forum about ESP32

Closing as not an issue with the esp8266 arduino core.
