### ISSUE TITLE
ESP8266WiFiClass::begin Starts in STA + AP mode?

### ISSUE THREAD

**Issue by Lstt2005** [esp8266/Arduino#796]
is there a reason for starting in WIFI_AP_STA mode?
in the default config the AP is "open" (no WPA2, no password), this can be a big risk of the security for the application or the network. 

int ESP8266WiFiClass::begin(const char* ssid, const char *passphrase)
{
    if (wifi_get_opmode() == WIFI_AP)
    {
        // turn on AP+STA mode
        mode(WIFI_AP_STA);
    }
The same problem, as in issue https://github.com/esp8266/Arduino/issues/529

**Comment by Links2004** [comment]
```WIFI_AP_STA ``` is only used when the AP is already configured. 

your code snipped looks really old which version do you use?
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src/ESP8266WiFi.cpp#L92-L101
