### ISSUE TITLE
ESP8266HTTPUpdateServer FileSystem Update no GZ

### ISSUE THREAD

**Issue by ripper121** [esp8266/Arduino#7971]
When i try to update the FileSystem with a myFS.bin.gz it will corrupt my FileSystem .
When I upload the original non compressed myFS.bin it works.

For Firmware update it works with myFW.bin.gz and also with the non compressed myFW.bin.

So is the compression for the FileSystem yet not implemented?

**Comment by earlephilhower** [comment]
As documented, you can only gzip the FS if you use ATOMIC_FS_UPDATE.  There is simply not enough RAM in a running system to do decompression while handling the WiFi and TCP links.
