### ISSUE TITLE
OTA stops after a few seconds with 'Error Uploading'

### ISSUE THREAD

**Issue by paai** [esp8266/Arduino#7980]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:					[robotdyn D1R2]
- Core Version:			[latest git]
- Development Env:		[Arduino IDE]
- Operating System:		[Ubuntu]

### Settings in IDE

- Module:  			Wemos D1 mini r2
- Flash Mode:			???
- Flash Size: 		4MB
- lwip Variant:        v2 Lower Memory
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	      ???
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		OTA
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

OTA upload stops after a few seconds with 'Error Uploading'. There is no firewall active. Problem seems related to distance to AP.

I tried all possible combinations of board manager installation and git installation. Problem persists with different esp8266 boards of same type.

After complete reinstallation of both Arduino IDE (1.8.13) and git with empty directories, problem still there.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiUdp.h>
#include <ArduinoOTA.h>

#ifndef STASSID
#define STASSID "xxxx"
#define STAPSK  "yyyy"
#endif

const char* ssid = STASSID;
const char* password = STAPSK;

IPAddress nameserver(8,8,8,8);
IPAddress ip(192, 168, 178, 225);
IPAddress gateway(192, 168, 178, 1); // set gateway to match your network
IPAddress subnet(255, 255, 255, 0); // set subnet mask to match your network

void setup() {
  Serial.begin(115200);
  Serial.println("Booting");
  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);
   WiFi.config(ip, gateway, subnet, nameserver); 

  while (WiFi.waitForConnectResult() != WL_CONNECTED) {
    Serial.println("Connection Failed! Rebooting...");
    yield();delay(5000);
    ESP.restart();
  }

  // Port defaults to 8266
  // ArduinoOTA.setPort(8266);

  // Hostname defaults to esp8266-[ChipID]
  ArduinoOTA.setHostname("paai2");

  // No authentication by default
  // ArduinoOTA.setPassword("admin");

  // Password can be set with it's md5 value as well
  // MD5(admin) = 21232f297a57a5a743894a0e4a801fc3
  // ArduinoOTA.setPasswordHash("21232f297a57a5a743894a0e4a801fc3");

  ArduinoOTA.onStart([]() {
  //   Serial.end();
    String type;
    if (ArduinoOTA.getCommand() == U_FLASH) {
      type = "sketch";
    } else { // U_FS
      type = "filesystem";
    }

    // NOTE: if updating FS this would be the place to unmount FS using FS.end()
    Serial.println("Start updating " + type);
  });
  ArduinoOTA.onEnd([]() {
    Serial.println("\nEnd");
  });
  ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
    Serial.printf("Progress: %u%%\r", (progress / (total / 100)));
  });
  ArduinoOTA.onError([](ota_error_t error) {
    Serial.printf("Error[%u]: ", error);
    if (error == OTA_AUTH_ERROR) {
      Serial.println("Auth Failed");
    } else if (error == OTA_BEGIN_ERROR) {
      Serial.println("Begin Failed");
    } else if (error == OTA_CONNECT_ERROR) {
      Serial.println("Connect Failed");
    } else if (error == OTA_RECEIVE_ERROR) {
      Serial.println("Receive Failed");
    } else if (error == OTA_END_ERROR) {
      Serial.println("End Failed");
    }
  });
  ArduinoOTA.begin();
//  Serial.begin(115200);
  Serial.println("Ready");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
}

void loop() {
  ArduinoOTA.handle();
  Serial.println("een");
  yield();delay (1000);
 Serial.println (ESP.getSdkVersion());
 
}
```

### Debug Messages

Executable segment sizes:
ICACHE : 32768           - flash instruction cache 
IROM   : 286092          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27820   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 
DATA   : 1504  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 1384  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 26112 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 316800 bytes (30%) of program storage space. Maximum is 1044464 bytes.
Global variables use 29000 bytes (35%) of dynamic memory, leaving 52920 bytes for local variables. Maximum is 81920 bytes.
Uploading.......................................
12:02:31 [ERROR]: Error Uploading
12:02:31 [ERROR]: Error Uploading

Debug messages in second screen:
[12:18:21:534] Start updating sketch␍␊
[12:18:21:534] Progress: 0%␍Progress: 0%␍Progress: 0%␍Progress: 0%␍Progress: 0%␍Progress: 0%␍Progress: 0%␍Progress: 0%␍Progress: 1%␍Progress: 1%␍Progress: 1%␍Progress: 1%␍Progress: 1%␍Progress: 2%␍Progress: 2%␍Progress: 2%␍Progress: 2%␍Progress: 3%␍Progress: 3%␍Progress: 3%␍Progress: 3%␍Progress: 4%␍Progress: 4%␍Progress: 4%␍Progress: 4%␍Progress: 4%␍Progress: 5%␍Progress: 5%␍Progress: 5%␍Progress: 6%␍Progress: 6%␍Progress: 6%␍Progress: 6%␍Progress: 7%␍Progress: 7%␍Progress: 7%␍Progress: 8%␍Progress: 8%␍Progress: 8%␍Progress: 8%␍Progress: 8%␍Progress: 9%␍Progress: 9%␍Progress: 9%␍Progress: 9%␍Progress: 9%␍Progress: 10%␍Progress: 10%␍Progress: 10%␍Progress: 10%␍Progress: 11%␍Progress: 11%␍Progress: 11%␍

Debug after CORE+WIFI+HTTP>.. logging:

Progress: 7%
:rn 536
:rd 456, 536, 0
:rdi 536, 456
:ack 4
:rch 536, 536
:ack 3
:rch 1072, 536
:ack 3
:rd 1152, 1608, 456
:rdi 80, 80
:c 80, 536, 1608
:rdi 536, 536
:c 536, 536, 1072
:rdi 536, 536
:c0 536, 536
:wr 4 0
:wrc 4 4 0
Progress: 7%
:ack 3
:ack 4
:urch 77, 49
[MDNSResponder] _callProcess (125604, triggered by: 192.168.178.15)
[MDNSResponder] _parseMessage (Time: 125605 ms, heap: 42552 bytes, from 192.168.178.15(5353), to 224.0.0.251(5353))
:urd 2, 49, 0
:urd 1, 49, 2
:urd 1, 49, 3
:urd 2, 49, 4
:urd 2, 49, 6
:urd 2, 49, 8
:urd 2, 49, 10
[MDNSResponder] _parseMessage: Done (Succeeded after 25 ms, ate 0 bytes, remaining 42552)

:urch 77, 49
[MDNSResponder] _callProcess (135659, triggered by: 192.168.178.15)
[MDNSResponder] _parseMessage (Time: 135660 ms, heap: 42552 bytes, from 192.168.178.15(5353), to 224.0.0.251(5353))
:urd 2, 49, 0
:urd 1, 49, 2
:urd 1, 49, 3
:urd 2, 49, 4
:urd 2, 49, 6
:urd 2, 49, 8
:urd 2, 49, 10
[MDNSResponder] _parseMessage: Done (Succeeded after 25 ms, ate 0 bytes, remaining 42552)

**Comment by castillo92** [comment]
Could you try this...? It is similar like yours but works for me:



I call this function in the main `setup()`
```

#define OTA_HOSTNAME espName

void SETUP_OTA(){
  // Port defaults to 8266
  // ArduinoOTA.setPort(8266);

  // Hostname defaults to esp8266-[ChipID]
  ArduinoOTA.setHostname(OTA_HOSTNAME);

  // No authentication by default
  // ArduinoOTA.setPassword("admin");

  // Password can be set with it's md5 value as well
  // MD5(admin) = 21232f297a57a5a743894a0e4a801fc3
  // ArduinoOTA.setPasswordHash("21232f297a57a5a743894a0e4a801fc3");

  ArduinoOTA.onStart([]() {
    String type;
    if (ArduinoOTA.getCommand() == U_FLASH) {
      type = "sketch";
    } else { // U_SPIFFS
      type = "filesystem";
    }

    // NOTE: if updating SPIFFS this would be the place to unmount SPIFFS using SPIFFS.end()
    Serial.println("Start updating " + type);
  });

  ArduinoOTA.onEnd([]() {
    Serial.println("\nEnd");
  });

  ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
    Serial.printf("Progress: %u%%\r", (progress / (total / 100)));
  });

  ArduinoOTA.onError([](ota_error_t error) {
    Serial.printf("Error[%u]: ", error);
    if (error == OTA_AUTH_ERROR) {
      Serial.println("Auth Failed");
    } else if (error == OTA_BEGIN_ERROR) {
      Serial.println("Begin Failed");
    } else if (error == OTA_CONNECT_ERROR) {
      Serial.println("Connect Failed");
    } else if (error == OTA_RECEIVE_ERROR) {
      Serial.println("Receive Failed");
    } else if (error == OTA_END_ERROR) {
      Serial.println("End Failed");
    }
  });

  ArduinoOTA.begin();
  Serial.println("");
  Serial.println("[SETUP] OTA iniciado");
}

```




And add this to the main `loop()`
`
    ArduinoOTA.handle();
`

And do not forget the library at the top of yours sketch:
`#include <ArduinoOTA.h>               // Update Over The Air`

**Comment by earlephilhower** [comment]
Closing as this appears to be a coding error.  Long `delay()` is not appropriate in a web using app as discussed in prior comments.  Please use https://esp8266.com or https://gitter.im/esp8266/Arduino if you still need help.
