### ISSUE TITLE
Having problems with the wire connection for the NodeMCU ESP8266 to the MQ-7 gas sensor and also the (GPS) module (GY-NEO6MV2, NEO-6M).

### ISSUE THREAD

**Issue by azamkamal99** [esp8266/Arduino#7983]
Hi. I am currently doing a final year project (FYP). My project is about detecting carbon monoxide gas leaks in the car and sending the location where the car is via a mobile application. I have included a schematic diagram for all my hardware connections for my project. I have tried to install hardware based on the schematic. But my NodeMCU ESP8266 cannot be detected in the computer if I connect the two sensors. If I only connect the MQ-7 gas sensor without the GPS module, my computer detects my NodeMCU. The pin that I just found to cause my computer not to detect NodeMCU is to connect the GPS module which is the GROUND pin. I want to ask here, what is my problem? Have a wrong wire connection or other problems?

https://imgur.com/a/Yl4s5yT

https://imgur.com/a/0wcKhPE

Thanks for the help :)

**Comment by d-a-v** [comment]
> The pin that I just found to cause my computer not to detect NodeMCU is to connect the GPS module which is the GROUND pin. I want to ask here, what is my problem? Have a wrong wire connection or other problems?

Please reformulate, also check your GPS module with a a USB<->serial module.

Here, is the place to discuss about the esp8266 arduino core issues with source code.
You deliberately deleted the issue template that was presented to you, I will deliberately close your issue and advise you to ask about hardware issues on forums or discussion boards like [gitter](https://gitter.im/esp8266/Arduino), esp8266.com, stackoverflow or others.
