### ISSUE TITLE
WPS between two ESP's

### ISSUE THREAD

**Issue by tusharvb19** [esp8266/Arduino#8001]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:			        [ESP-12|ESP-01|ESP-07|ESP8285 device|other]
- Core Version:			[latest]
- Development Env:		[Arduino IDE|
- Operating System:		[Windows|

### Settings in IDE

- Module:  			|Nodemcu|
- Flash Mode:			[qio|dio|other]
- Flash Size: 		        [4MB]
- lwip Variant:                  [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	        [40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

I want to create a WPS capability in esp AP mode, to which another ESP can connect using WPSconfig() in STA mode
So, these two ESP's will get connected to each other

**Comment by earlephilhower** [comment]
This is a "how do I" type of question which is better handled on https://esp8266.com or https://gitter.im/esp8266/Arduino, as mentioned in the template. Please move it there if you still need help.
