### ISSUE TITLE
Compiler warning: comparison between signed and unsigned integer

### ISSUE THREAD

**Issue by Teddyz** [esp8266/Arduino#8016]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12|ESP-01|ESP-07|ESP8285 device|other]
- Core Version:			[2_7_4]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[dio]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[dtr]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[N/A]
- Upload Speed:   [N/A]

### Problem Description

I get a compiler warning for the second if-case when compiling this for ESP8266. When compiling the same code for AVR I see no warning. OK or is it a problem?

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

void setup() {
  Serial.begin(115200);
  uint16_t adc_idle_val = 580;
  uint32_t ADC_AVG = 555;

  if ( ADC_AVG > adc_idle_val ) {
    Serial.println("123");
  }
  
  if ( ADC_AVG > (adc_idle_val + 3) ) {
    Serial.println("456");
  }
}

void loop() {
  // put your main code here, to run repeatedly:

}

```

### Debug Messages

```
D:\Mina Dokument\Arduino\test_signed_unsigned_compare\test_signed_unsigned_compare.ino: In function 'void setup()':
D:\Mina Dokument\Arduino\test_signed_unsigned_compare\test_signed_unsigned_compare.ino:10:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if ( ADC_AVG > (adc_idle_val + 3) ) {

```

**Comment by d-a-v** [comment]
That's on gcc, I get the same warning with cmdline gcc or [`cpp.sh`](http://cpp.sh/4j7le)

You can replace `3` by `3U` to make the warning disappear.
Depending on the selected warning level (and compiler version, I don't know), gcc will warn, or not.
Closing as not an error with the core.
