### ISSUE TITLE
iam newbie ,i have some problem with wdt

### ISSUE THREAD

**Issue by kendrikjustino** [esp8266/Arduino#8019]
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffd70 end: 3fffffc0 offset: 01a0
3fffff10:  00000001 00005df0 3fffff90 4020161b  
3fffff20:  3fff4eb9 00000000 ffffffff 402026f1  
3fffff30:  3ffefc62 00005dfd 3fffff90 402016fc  
3fffff40:  00000001 3ffef0bc 00000000 3ffee36c  
3fffff50:  3fffdad0 00000000 3ffee304 40201108  
3fffff60:  402010fc 3ffee304 3ffe8610 40201341  
3fffff70:  3fffdad0 00000000 3ffee304 40201385  
3fffff80:  00002580 00000000 3ffee304 40201082  
3fffff90:  3ffef0bc 5dfd5dff 0a00ffff 40201035  
3fffffa0:  feefeffe feefeffe 3ffee32c 40201994  
3fffffb0:  feefeffe feefeffe 3ffe84e0 40100b85  
<<<stack<<<

i dont know what that mean
i'm trying Communication serial adruino uno with my wemos  but if i run my wemos running like that

my code wemos

void setup(){
  Serial.begin(9600);
  }
void loop(){
  
  

  String data="";
  while(Serial.available()<=0){
  
    data += char(Serial.read());
    }
    Serial.print("data Adruino = ");
    Serial.println(data);
 
    delay(6000);
  }

code adruino

void setup() {
  // put your setup code here, to run once:
Serial.begin(9600);

}
void loop() {
  // put your main code here, to run repeatedly:
Serial.println("Hallo G");
delay(1000);
}

please help me :(

**Comment by d-a-v** [comment]
```cpp
  while(Serial.available()<=0){
```
Did you write this code by yourself or did you copy it from somewhere ?
In the first case, you did not read the documentation, in the second case you may ask to the author.
I will deliberately close this issue because you deliberately replaced the issue template, that you should have filled, by a question unrelated to the esp8266 Arduino core.
