### ISSUE TITLE
`.text' will not fit in region `iram1_0_seg' with c modules

### ISSUE THREAD

**Issue by burner-** [esp8266/Arduino#803]
There has been earlier issues with same error message but I think this is different case. 
If you use .c libraries iram gets full quite fast. 
I note that there is at file packages\esp8266\hardware\esp8266\1.6.5-947-g39819f0\tools\sdk\ld\eagle.app.v6.common.ld
following line:
*.cpp.o(.literal*, .text*) 
So I add also:
*.c.o(.literal*, .text*)
and it resolve my problem. I am not expert with c neither esp so I do not know is that bad setting as default. But if does not cause another problems then it can be good setting by default at future releases.

**Comment by igrr** [comment]
Applied this along with other changes in #857. Thanks!
