### ISSUE TITLE
ESP8266 ESP-01 MONITOR DOESN´T APPEAR ANSWER INSIDE MINGW32

### ISSUE THREAD

**Issue by paulotirapelle2** [esp8266/Arduino#8031]
#### Platform

- Hardware:		                [ESP-01]
- Core Version:			[https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples/get-started/hello_world]
- Development Env:		[mingw32]
- Operating System:		[Windows10]

### Settings in IDE

- Module:  			[ESP-IDF]
- Flash Mode:			[qio]
- Flash Size: 		[2MB]
- lwip Variant:   
- Reset Method:		[ck]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[160MHz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200]

### Problem Description

After program esp8266 with FTDI programmer, the command "make monitor" doesn´t answer. 

### Debug Messages Error
```
Leaving...
Hard resetting via RTS pin...

Paulo@DESKTOP-LJ7FF2A MINGW32 ~/esp/ESP8266_RTOS_SDK/examples/get-started/hello_world
$ make monitor
Toolchain path: /opt/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc
Toolchain version: esp-2020r3-49-gd5524c1
Compiler version: 8.4.0
Python requirements from C:/msys32/home/Paulo/esp/ESP8266_RTOS_SDK/requirements.txt are satisfied.
MONITOR
--- idf_monitor on C:/msys32/dev/COM3 74880 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---


```

### Solution

 After program the chip, disconnect USB programmer, disconnect GPIO_0  from GND and plug USB again. 
 Make a new command "make monitor".
 

### Debug Messages Working

```
Hello world!
This is ESP8266 chip with 1 CPU cores, WiFi, silicon revision 1, 2MB external fl
ash
Restarting in 10 seconds...
Restarting in 9 seconds...
Restarting in 8 seconds...
Restarting in 7 seconds...
Restarting in 6 seconds...
Restarting in 5 seconds...
Restarting in 4 seconds...
Restarting in 3 seconds...
```

**Comment by earlephilhower** [comment]
This is not related to the ESP8266 Arduino core.  Please use the IDF repo for reporting/asking this.

**Comment by paulotirapelle2** [comment]
sorry
