### ISSUE TITLE
FragAttacks vulnerability

### ISSUE THREAD

**Issue by brenard** [esp8266/Arduino#8042]
Hello,

I would like to know is ESP8266/Arduino is concerned [FragAttacks vulnerability](https://www.fragattacks.com/)? If so, is there any work in progress on these topics?

Thank you

Benjamin

**Comment by earlephilhower** [comment]
The ESP8266 Arduino core doesn't have any access or control to the actual WiFi hardware or logic, so the best place to pose this question would be the Espressif support forums.

**Comment by gleeds** [comment]
@brenard This looks like the issue in ESP-IDF: https://github.com/espressif/esp-idf/issues/7019

**Comment by d-a-v** [comment]
And the one in nonos-sdk: https://github.com/espressif/ESP8266_NONOS_SDK/issues/343
