### ISSUE TITLE
Mklittlefs not listed in platform.json for 3.0.0 release

### ISSUE THREAD

**Issue by earlephilhower** [esp8266/Arduino#8057]
The JSON for the 3.0.0 release does not contain an entry for `mklittlefs` in the `toolsDependencies`, meaning that file uploads no longer work through the IDE.

See reports in https://github.com/earlephilhower/arduino-esp8266littlefs-plugin/issues/15 and the JSON file at https://arduino.esp8266.com/stable/package_esp8266com_index.json

**Comment by d-a-v** [comment]
That was in [#6294 (package.json)](https://github.com/esp8266/Arduino/pull/6294/files#diff-cb68cbae35897b26fd319a2401526da0ebb5e374c8c12ecbdd223352a8b44b36)
