### ISSUE TITLE
Websocket connection not working with 3.0

### ISSUE THREAD

**Issue by Ciapas-Linux** [esp8266/Arduino#8071]
Hello!

My application on esp8266 use websocket communnication with web browser by using this library: 
https://github.com/Links2004/arduinoWebSockets , web browser for example firefox return error while trying to connect with esp 

WebSocket Error  
error
​bubbles: false
​cancelBubble: false
​cancelable: false
​composed: false
​currentTarget: null
​defaultPrevented: false
​eventPhase: 0
​explicitOriginalTarget: WebSocket { url: "ws://192.168.1.2:81/", readyState: 3, bufferedAmount: 0, … }
​isTrusted: true
​originalTarget: WebSocket { url: "ws://192.168.1.2:81/", readyState: 3, bufferedAmount: 0, … }
​returnValue: true
​srcElement: WebSocket { url: "ws://192.168.1.2:81/", readyState: 3, bufferedAmount: 0, … }
​target: WebSocket { url: "ws://192.168.1.2:81/", readyState: 3, bufferedAmount: 0, … }
​timeStamp: 445
​type: "error"
​<get isTrusted()>: function isTrusted()
​<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … } 

Also i  made application for android that uses websocket and the same issue. Ewerything else in my app on esp working normal.

Maybe somebody know something about this issue ?

Best regards

**Comment by d-a-v** [comment]
This not the place to post issues about external libraries.
Please try arduinoWebSockets's examples: https://github.com/Links2004/arduinoWebSockets/tree/master/examples/esp8266 .
Please report there if there's an issue with this library.
Next time, do not deliberately delete the issue template that was presented to you, or your question will be deliberately closed, like this one is.
