### ISSUE TITLE
Error compiling for board NodeMCU 1.0 (ESP-12E Module)

### ISSUE THREAD

**Issue by thiruppugazhan** [esp8266/Arduino#8087]
I can't find solution for this Error,
IDE can't compile programs,I've checked preference's board manager url, deleted existing board in hardware.  
Error compiling for board NodeMCU 1.0 (ESP-12E Module)

**Comment by d-a-v** [comment]
You don't give the error details,
we don't know which version or the core you are using,
we don't know the OS of your computer.

The installation through the Arduino IDE is currently and for sure working with a lot of people.

I am now deliberately closing your issue per not respecting the issue template that was presented to you, and that you deliberately deleted and replaced by absence of description.
