### ISSUE TITLE
I2S compilation fails

### ISSUE THREAD

**Issue by mdmitry** [esp8266/Arduino#8107]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:			ESP8266
- Core Version:			e8b411fafb100200b1379526448d75a0e06a69dd
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			LOLIN(WEMOS) D1 R2 & mini
- Flash Size: 			4MB
- lwip Variant:   		v2 Lower Memory
- CPU Frequency:		160MHz

### Problem Description

Projects which include I2S library <I2S.h> fail to link.

### Sketch

Examples -> I2S -> SimpleTone
Examples -> I2S -> InputSerialPlotter (copy below)

```cpp

#include <I2S.h>

void setup() {
  Serial.begin(115200);
  while (!Serial) {}

  if (!I2S.begin(I2S_PHILIPS_MODE, 8000, 24)) {
    Serial.println("Failed to initialize I2S!");
    while (1); // do nothing
  }
}

void loop() {
  int sample = I2S.read();
  if (sample)
    Serial.println(sample);
}

```

### Debug Messages

```
Arduino: 1.8.15 (Windows 7), Board: "LOLIN(WEMOS) D1 R2 & mini, 160 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"



c:/users/user/documents/arduino/hardware/esp8266com/esp8266/tools/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\InputSerialPlotter.ino.cpp.o:(.text.setup+0x4): undefined reference to `I2S'

c:/users/user/documents/arduino/hardware/esp8266com/esp8266/tools/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\InputSerialPlotter.ino.cpp.o:(.text.setup+0xc): undefined reference to `_ZN8I2SClass5beginE10i2s_mode_tli'

c:/users/user/documents/arduino/hardware/esp8266com/esp8266/tools/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\InputSerialPlotter.ino.cpp.o: in function `setup':

C:\Users\user\Documents\Arduino\hardware\esp8266com\esp8266\libraries\I2S\examples\InputSerialPlotter/InputSerialPlotter.ino:22: undefined reference to `_ZN8I2SClass5beginE10i2s_mode_tli'

c:/users/user/documents/arduino/hardware/esp8266com/esp8266/tools/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\user\Documents\Arduino\hardware\esp8266com\esp8266\libraries\I2S\examples\InputSerialPlotter/InputSerialPlotter.ino:26: undefined reference to `_ZN8I2SClass4readEv'

c:/users/user/documents/arduino/hardware/esp8266com/esp8266/tools/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\InputSerialPlotter.ino.cpp.o:(.text.loop+0xd): undefined reference to `_ZN8I2SClass4readEv'

collect2.exe: error: ld returned 1 exit status

exit status 1

Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

```

**Comment by earlephilhower** [comment]
Looks like Arduino IDE is not actually compiling the I2S library for some reason.

Can you please use File->Prefs->Enable Verbose Output->Compile and rerun and capture the entire build log (i.e. set the preference, exit the ide, restart the ide, and build)?

The I2S examples are part of CI run under Linux without incident, but maybe there is some Windows-only issue (case sensitivity/etc.) which this log would show.

**Comment by mdmitry** [comment]
[i2s_build_log.txt](https://github.com/esp8266/Arduino/files/6617596/i2s_build_log.txt)

**Comment by earlephilhower** [comment]
Yup, it's Windows case-insensitivity causing the issue.  The IDE was not detecting the library as required and therefore not building it because it opened "i2s.h" and not "I2S.h".

Try #8108 (or just remove `cores/esp8266/i2s.h`) and you should be good to go.

**Comment by mdmitry** [comment]
Renamed `cores/esp8266/i2s.h` and everything compiles perfectly. Thank you!
