### ISSUE TITLE
never ending AT at serial monitor on arduino IDE 

### ISSUE THREAD

**Issue by unknown0116** [esp8266/Arduino#8132]
The code 
/*
   -- New project --
   
   This source code of graphical user interface 
   has been generated automatically by RemoteXY editor.
   To compile this code using RemoteXY library 3.1.6 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.7.12 or later version;
     - for iOS 1.4.7 or later version;
    
   This source code is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.    
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP8266_HARDSERIAL_POINT

#include <RemoteXY.h>

// RemoteXY connection settings 
#define REMOTEXY_SERIAL Serial
#define REMOTEXY_SERIAL_SPEED 115200
#define REMOTEXY_WIFI_SSID "control"
#define REMOTEXY_WIFI_PASSWORD "12345678"
#define REMOTEXY_SERVER_PORT 6377

// RemoteXY configurate  
#pragma pack(push, 1)
uint8_t RemoteXY_CONF[] =
  { 255,5,0,0,0,186,0,11,16,1,
  130,1,31,0,32,100,17,2,1,36,
  29,22,11,136,26,24,24,79,78,0,
  79,70,70,0,2,1,36,65,22,11,
  135,26,24,24,79,78,0,79,70,70,
  0,2,1,36,83,22,11,135,26,8,
  24,79,78,0,79,70,70,0,2,1,
  36,48,22,11,135,26,24,8,79,78,
  0,79,70,70,0,2,1,36,10,22,
  11,135,26,24,24,79,78,0,79,70,
  70,0,130,1,0,0,31,100,16,129,
  0,4,12,21,6,24,87,65,84,69,
  82,0,129,0,2,32,27,4,24,76,
  73,86,73,78,71,32,82,79,79,77,
  0,129,0,3,50,26,6,24,75,73,
  84,67,72,69,78,0,129,0,1,68,
  29,3,24,77,65,83,84,69,82,32,
  66,69,68,82,79,79,77,0,129,0,
  2,86,26,5,24,66,69,68,82,79,
  79,77,0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  uint8_t switch_1; // =1 if switch ON and =0 if OFF 
  uint8_t switch_2; // =1 if switch ON and =0 if OFF 
  uint8_t switch_3; // =1 if switch ON and =0 if OFF 
  uint8_t KITCHEN; // =1 if switch ON and =0 if OFF 
  uint8_t WATER; // =1 if switch ON and =0 if OFF 

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0 

} RemoteXY;
#pragma pack(pop)

/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

#define PIN_SWITCH_1 8
#define PIN_SWITCH_2 10
#define PIN_SWITCH_3 11
#define PIN_KITCHEN 9
#define PIN_WATER 7

void setup() 
{
  RemoteXY_Init (); 
  
  pinMode (PIN_SWITCH_1, OUTPUT);
  pinMode (PIN_SWITCH_2, OUTPUT);
  pinMode (PIN_SWITCH_3, OUTPUT);
  pinMode (PIN_KITCHEN, OUTPUT);
  pinMode (PIN_WATER, OUTPUT);
  
  // TODO you setup code
  
}

void loop() 
{ 
  RemoteXY_Handler ();
  
  digitalWrite(PIN_SWITCH_1, (RemoteXY.switch_1==0)?LOW:HIGH);
  digitalWrite(PIN_SWITCH_2, (RemoteXY.switch_2==0)?LOW:HIGH);
  digitalWrite(PIN_SWITCH_3, (RemoteXY.switch_3==0)?LOW:HIGH);
  digitalWrite(PIN_KITCHEN, (RemoteXY.KITCHEN==0)?LOW:HIGH);
  digitalWrite(PIN_WATER, (RemoteXY.WATER==0)?LOW:HIGH);
  
  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay() 

}

The Issue

![image](https://user-images.githubusercontent.com/57890792/122333765-34d8b600-cf6b-11eb-8c42-71a535e4ad16.png)

Help please

**Comment by earlephilhower** [comment]
Template was ignored and deleted.  Closing.
