### ISSUE TITLE
suggest master & slave sketches support as espressif's non-OS SDK archieved

### ISSUE THREAD

**Issue by zhfei1979** [esp8266/Arduino#8133]
It's possible that power off happens as https://github.com/esp8266/Arduino/issues/8121 during the downloaded new sketch copying to current sketch area; nobody can guarantee a power off will not happen for millions of IOT devices.

why Ardunio uses eboot instead of boot_v1.7.bin of the SDK? the SDK uses pretty good system_upgrade_* API for FOTA.

**Comment by earlephilhower** [comment]
This is also a dup of #6538 .  That PR will implement a way to guarantee that the flash update eventually gets properly finished even in case of powerfail.
