### ISSUE TITLE
ESP8266NetBIOS library only works in wifi STA mode, and not in wifi AP

### ISSUE THREAD

**Issue by pabloandresm** [esp8266/Arduino#8139]
Title says it all. The problem is the same as the NetBIOS library for esp32 (https://github.com/espressif/arduino-esp32/issues/5300)

If you look at the code, file ESP8266NetBIOS.cpp, line 215, in the netbios answer, you can see:
	nbnsa.NBNSA_NODEADDRESS = WiFi.localIP(); // ulozime nasi IP adresu

Which works only if WiFi is in STA mode, but not AP mode.

The fix would be something like this:
	if (WiFi.getMode()==WIFI_STA)
		nbnsa.NBNSA_NODEADDRESS = WiFi.localIP(); // ulozime nasi IP adresu
	else
		nbnsa.NBNSA_NODEADDRESS = WiFi.softAPIP(); // ulozime nasi IP adresu

**Comment by earlephilhower** [comment]
@pabloandresm you've found a problem and potential solution.  Why not try your hand at a [pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) so your work would be preserved in the `git` logs?

**Comment by pabloandresm** [comment]
I'll do that right now. Thanks.
