### ISSUE TITLE
EEPROM Flash Sector

### ISSUE THREAD

**Issue by plinioseniore** [esp8266/Arduino#814]
On the reference documentation is written: "EEPROM library uses one sector of flash located at 0x7b000 for storage" is this address independent on size of FLASH and SPIFFS reserved memory?

**Comment by Links2004** [comment]
it is dynamical, see here:
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/doc/reference.md#file-system
https://github.com/esp8266/Arduino/blob/esp8266/hardware/esp8266com/esp8266/libraries/EEPROM/EEPROM.cpp#L120

the documentation needs an update.

**Comment by plinioseniore** [comment]
https://github.com/esp8266/Arduino/pull/818
