### ISSUE TITLE
Random crashes that get fixed by recompiling the code without changes (GCC 10/3.0.0)

### ISSUE THREAD

**Issue by sascha432** [esp8266/Arduino#8149]
I notices that every 10-20th upload, I get a random crash at a random place. Mostly load prohibited exceptions with PROGMEM, but there were a couple accessing RAM too.

Recompiling/uploading the code fixes the issue. I put debug code at those places, but since they change every time, I probably won't get lucky that it happens twice at the same place.

I noticed that the pointer where it wants to read memory is completely off, something like 0x015f0000. Lots of zeros at the end is a pattern.

I experience the issue with serveral different modules, ESP-12F ESP-01... all have 4MB of flash and were doing fine before.

PLATFORM: Espressif 8266 (3.0.0) > NodeMCU 0.9 (ESP-12 Module)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.30000.210519 (3.0.0)      
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.30000.201119 (3.0.0)
 - tool-mklittlefs 1.203.210203 (2.3)
 - tool-mkspiffs 1.200.0 (2.0)
 - toolchain-xtensa 2.100200.0 (10.2.0)

I have the full stack trace and ELF binary that belong to the crash, this is an overview of the recent ones.
I am bit bit clueless here if it is the new compiler, my code or something in the new framework. If anyone has an idea what to look for or experiencing similar issues LMK

`<005> 1969-12-31T17:05:49 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x4000bf80 epc3=0x00000000 excvaddr=0x00000000 depc=0x15fc0000 version=0.0.5.b8242
 md5=6e728241795a407bb1fc093c338016df stack-size=1200
<006> 2021-06-18T18:35:05 PDT reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40291eed epc3=0x00000000 excvaddr=0x00000000 depc=0x1be00000 version=0.0.5.b8246
 md5=eb2ef0bd0aae148806a5b3f7a3ec795b stack-size=1200
<007> 2021-06-18T18:35:14 PDT reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40291eed epc3=0x00000000 excvaddr=0x00000000 depc=0x1be00000 version=0.0.5.b8246
 md5=eb2ef0bd0aae148806a5b3f7a3ec795b stack-size=1200
<008> 2021-06-18T18:35:24 PDT reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40291eed epc3=0x00000000 excvaddr=0x00000000 depc=0x1be00000 version=0.0.5.b8246
 md5=eb2ef0bd0aae148806a5b3f7a3ec795b stack-size=1200
<009> 2021-06-18T18:35:33 PDT reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40291eed epc3=0x00000000 excvaddr=0x00000000 depc=0x1be00000 version=0.0.5.b8246
 md5=eb2ef0bd0aae148806a5b3f7a3ec795b stack-size=1200
<010> 1969-12-31T16:00:09 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40291eed epc3=0x00000000 excvaddr=0x00000000 depc=0x1be00000 version=0.0.5.b8246
 md5=9a6b74f1650194f112c7dbe4973c9ebe stack-size=1200
<015> 1969-12-31T16:00:07 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x4029277c epc3=0x00000000 excvaddr=0x00000000 depc=0x15800000 version=0.0.5.b8261
 md5=03a48c820a03641417df879065558afc stack-size=1200
<016> 1969-12-31T16:00:06 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x4029277c epc3=0x00000000 excvaddr=0x00000000 depc=0x15800000 version=0.0.5.b8261
 md5=03a48c820a03641417df879065558afc stack-size=1200
<017> 1969-12-31T16:00:08 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x4029277c epc3=0x00000000 excvaddr=0x00000000 depc=0x15800000 version=0.0.5.b8261
 md5=03a48c820a03641417df879065558afc stack-size=1200
<018> 1969-12-31T16:00:06 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x4029277c epc3=0x00000000 excvaddr=0x00000000 depc=0x15800000 version=0.0.5.b8261
 md5=03a48c820a03641417df879065558afc stack-size=1200
<019> 1969-12-31T16:00:21 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x4029277c epc3=0x00000000 excvaddr=0x00000000 depc=0x15800000 version=0.0.5.b8261
 md5=03a48c820a03641417df879065558afc stack-size=1200
<020> 1969-12-31T16:00:08 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x4029277c epc3=0x00000000 excvaddr=0x00000000 depc=0x15800000 version=0.0.5.b8261
 md5=03a48c820a03641417df879065558afc stack-size=1200
<021> 1969-12-31T16:00:05 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x4029277c epc3=0x00000000 excvaddr=0x00000000 depc=0x15800000 version=0.0.5.b8261
 md5=03a48c820a03641417df879065558afc stack-size=1200
<022> 1969-12-31T16:00:21 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x4029277c epc3=0x00000000 excvaddr=0x00000000 depc=0x15800000 version=0.0.5.b8261
<026> 2021-06-19T08:21:18 PDT reason=LoadProhibitedCause epc1=0x0000001c epc2=0x402360a7 epc3=0x00000000 excvaddr=0x00000000 depc=0x18d80000 version=0.0.5.b8322
 md5=5595decf746eb3a7515387610d640fa3 stack-size=368
<027> 2021-06-19T08:21:20 PDT reason=LoadProhibitedCause epc1=0x0000001c epc2=0x402360a7 epc3=0x00000000 excvaddr=0x00000000 depc=0x18d80000 version=0.0.5.b8322
 md5=5595decf746eb3a7515387610d640fa3 stack-size=368
<028> 1969-12-31T16:00:01 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x402360a7 epc3=0x00000000 excvaddr=0x00000000 depc=0x18d80000 version=0.0.5.b8322
 md5=5595decf746eb3a7515387610d640fa3 stack-size=368
<029> 1969-12-31T16:00:02 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x402360a7 epc3=0x00000000 excvaddr=0x00000000 depc=0x18d80000 version=0.0.5.b8322
 md5=5595decf746eb3a7515387610d640fa3 stack-size=368
<030> 1969-12-31T16:00:03 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x402360a7 epc3=0x00000000 excvaddr=0x00000000 depc=0x18d80000 version=0.0.5.b8322
 md5=5595decf746eb3a7515387610d640fa3 stack-size=368
<031> 1969-12-31T16:00:04 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x402360a7 epc3=0x00000000 excvaddr=0x00000000 depc=0x18d80000 version=0.0.5.b8322
 md5=5595decf746eb3a7515387610d640fa3 stack-size=368
<032> 2021-06-19T09:01:10 PDT reason=StoreProhibitedCause epc1=0x0000001d epc2=0x4000e1c3 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000054 version=0.0.5.b8328
 md5=7589fa2712af0f8b83b314b5aabfc31a stack-size=1200
<033> 1969-12-31T16:00:01 PST reason=IllegalInstructionCause epc1=0x00000000 epc2=0x4000dce5 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000 version=0.0.5.b8264
 md5=7ed4aa86e8e22c3c81fab04f580c2c80 stack-size=1200
<036> 2021-06-19T05:34:15 PDT reason=LoadProhibitedCause epc1=0x0000001c epc2=0x4026c53c epc3=0x00000000 excvaddr=0x00000000 depc=0x07411d81 version=0.0.5.b8317
 md5=9d7f658ffb6f4bc23aa9da8f5b54ba49 stack-size=288
<037> 2021-06-20T00:57:35 PDT reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40281fb1 epc3=0x00000000 excvaddr=0x00000000 depc=0x07980000 version=0.0.5.b8347
 md5=d88360fe23298af807f64fb3ad19e7fc stack-size=1120
<038> 2021-06-20T00:57:36 PDT reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40281fb1 epc3=0x00000000 excvaddr=0x00000000 depc=0x07980000 version=0.0.5.b8347
 md5=d88360fe23298af807f64fb3ad19e7fc stack-size=1120
<039> 1969-12-31T16:00:03 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40281fb1 epc3=0x00000000 excvaddr=0x00000000 depc=0x07980000 version=0.0.5.b8347
 md5=d88360fe23298af807f64fb3ad19e7fc stack-size=1120
<040> 2021-06-20T00:57:36 PDT reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40281fb1 epc3=0x00000000 excvaddr=0x00000000 depc=0x07980000 version=0.0.5.b8347
 md5=d88360fe23298af807f64fb3ad19e7fc stack-size=1120
<041> 1969-12-31T16:00:16 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40281fb1 epc3=0x00000000 excvaddr=0x00000000 depc=0x07980000 version=0.0.5.b8347
 md5=d88360fe23298af807f64fb3ad19e7fc stack-size=1120
<042> 1969-12-31T16:00:08 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40281fb1 epc3=0x00000000 excvaddr=0x00000000 depc=0x07980000 version=0.0.5.b8347
 md5=d88360fe23298af807f64fb3ad19e7fc stack-size=1120
<043> 1969-12-31T16:00:01 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40281fb1 epc3=0x00000000 excvaddr=0x00000000 depc=0x07980000 version=0.0.5.b8347
 md5=d88360fe23298af807f64fb3ad19e7fc stack-size=1120
<044> 1969-12-31T16:00:02 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40281fb1 epc3=0x00000000 excvaddr=0x00000000 depc=0x07980000 version=0.0.5.b8347
 md5=d88360fe23298af807f64fb3ad19e7fc stack-size=1120
<045> 1969-12-31T16:00:03 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40281fb1 epc3=0x00000000 excvaddr=0x00000000 depc=0x07980000 version=0.0.5.b8347
 md5=d88360fe23298af807f64fb3ad19e7fc stack-size=1120
<046> 1969-12-31T16:00:16 PST reason=LoadProhibitedCause epc1=0x0000001c epc2=0x40281fb1 epc3=0x00000000 excvaddr=0x00000000 depc=0x07980000 version`

**Comment by earlephilhower** [comment]
Template was ignored, no MCVE, not even a good description.  Closing.  Suggest you go to https://esp8266.com for general help with your app.
