### ISSUE TITLE
-DNO_GLOBAL_INSTANCES breaks ESP8266HttpClient

### ISSUE THREAD

**Issue by paulocsanz** [esp8266/Arduino#8183]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:				ESP-12
- Core Version:			master
- Development Env:		Platformio
- Operating System:		Ubuntu

### Problem Description

Defining `NO_GLOBAL_INSTANCES` breaks `ESP8266HttpClient` because it depends on `devnull` being defined. But it seems that if it's needed, it shouldn't be disable by that option. And since it's one byte it seems acceptable.

```cpp
/src/ESP8266HTTPClient.cpp:850:32: error: 'devnull' was not declared in this scope
  850 |         _client->sendAvailable(devnull); // clear _client's output (all of it, no timeout)
      |                                ^~~~~~~
*** [.pio/build/release/libc18/ESP8266HTTPClient/ESP8266HTTPClient.cpp.o] Error 1
```

**Comment by paulocsanz** [comment]
`Serial` is always declared as external in the header, but not defined when NO_GLOBAL_INSTANCES is defined. But other globals aren't even declared in the headers if NO_GLOBAL_INSTANCES is defined.

Should it also not be defined in that case?

**Comment by dok-net** [comment]
@paulocsanz Both `Serial` and `Serial1`, to be precise. Now while you are at it, there shouldn't be a problem enclosing that in `#ifdef`, given that your results indicate it passes the linker phase just fine. From my POV, go ahead and add the `#ifdef` to your PR.
