### ISSUE TITLE
Unwanted WI-FI Jamming by ESP8266-01

### ISSUE THREAD

**Issue by alihakimtaskiran** [esp8266/Arduino#8188]
I'm using ESP8266-01 module. It's first time to use the module. I uploaded a blink code from examples in order to test it. Code uploaded successfully. But if I attempt to power it, it starts warming, it sends message on serial line and my computer no longer connect to wifi.
```

Exception (0):
epc1=0x4022b082 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: sys
sp: 3fffe7d0 end: 3fffffb0 offset: 0190
3fffe960:  00000135 00000138 00000006 ffffffa1  
3fffe970:  00000138 00000000 00000002 40006784  
3fffe980:  00000001 3ffe8c90 40464a4e 0000383c  
3fffe990:  00000000 4022b531 00000000 3ffe8c90  
3fffe9a0:  3ffe8ca0 00000001 00000004 00000000  
3fffe9b0:  00000000 00000000 00000000 00000000  
3fffe9c0:  05303f37 4022cc0f 3ffe8c98 3ffe8ca0  

```

**Comment by earlephilhower** [comment]
Template deleted and not followed, dump not decoded.  Closing.

I suggest you try https://esp8266.com or https://gitter.im/esp8266/Arduino for general help.
