### ISSUE TITLE
ESP8266HTTPClient problem

### ISSUE THREAD

**Issue by Alis-Dev-idn** [esp8266/Arduino#8191]
when I want to retrieve data through the website, the message that appears does not match there is other information and the following data results:

:ref 1
:wr 179 0
:wrc 179 179 0
:ack 179
:rn 251
:c0 1, 251
1#0#90#0.06#230#0.02 -> this my data from database
:close
:ur 1
:dsrcv 0
:del

==== the code I use: ====

String Link;
  HTTPClient https;
  Link = "http://" + String(host) + "/getdata";
  https.begin(Link);
  https.GET();

  //menambil respond server
  String respon = https.getString();
  Serial.println(respon);
  https.end();

please help.

**Comment by earlephilhower** [comment]
You've deleted the template, and have no MCVE.  Closing.

Please read and follow the requested template if you want assistance here, or use http://esp8266.com if you are unable to.

FWIW, it looks like you have enabled Debug Port->Serial and enabled some debugging of the TCP stack.
