### ISSUE TITLE
ESP8266 shows up in DHCP list only when connected to internet

### ISSUE THREAD

**Issue by sh-user** [esp8266/Arduino#8197]
When I browse into the dhcp devices tab in my router I can't see the ESP8266 device with the IP it got from the router. ESP8266 shows up in DHCP list only when connected to internet and sending some data when connected. I think that the lease time for the IP address is not set, I do not have enough knowledge to check it.

**Comment by Tech-TX** [comment]
That's an issue with your router,  not the core files or libraries.  My router shows the ESP as soon as the connection is established.

**Comment by d-a-v** [comment]
@sh-user did you try with a smartphone acting as AP ?

**Comment by sh-user** [comment]
Indeed, the problem is in the TP-LINK TL-WR841N v14 router, it displays the ESP8266 in the DHCP device list only when there is traffic, and then saves the IP address lease. For example, there is no such problem on a Tenda router, it displays the IP address immediately after connecting. The access point created by the smartphone only shows the MAC address.
