### ISSUE TITLE
HttpClient.sendRequest("POST",Stream never sends data

### ISSUE THREAD

**Issue by asturcon3** [esp8266/Arduino#8202]
It's really late here, and I've just taken too much work to update some hundred nodes not uploading photos from multiple VCRs to the web by just downgrading to 2.7.4 so.. let me elaborate tomorrow.

https://github.com/esp8266/Arduino/issues/8055 is also happening on httpClient

Just that. No minimal code, sorry. I'm going bed now.

**Comment by d-a-v** [comment]
MCVE is required for help, or a more detailed report once you've recovered.

**Comment by earlephilhower** [comment]
Closing as no feedback and no MCVE.
