### ISSUE TITLE
ESP8266WiFi.h getting compile errors (new)

### ISSUE THREAD

**Issue by SteveRMann** [esp8266/Arduino#8259]
----------------------------- Delete below -----------------------------

----------------------------- Delete above -----------------------------

### Basic Infos

- [ ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [ ] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [ ] I have filled out all fields below.

#### Platform

- Hardware:	Wemos D1 Mini
- Core Version:			[latest git hash or date]
- Development Env:		Arduino IDE|Platformio|Make|other]
- Operating System:		Windows 10

### Settings in IDE

- Module:  			Wemos D1 mini r2
- Flash Mode:			unknown
- Flash Size: 		4MB
- lwip Variant:   unknown
- Reset Method:		unknown
- Flash Frequency:	unknown
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   921600

### Problem Description
Used the Arduino IDE to upload to ESP Community Version 3.02 
Sketches that formerly compiled OK now getting errors.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```#include <ESP8266WiFi.h>

void setup(){
  Serial.begin(115200);
  Serial.println();
  Serial.print("ESP Board MAC Address:  ");
  Serial.println(WiFi.macAddress());
}
 
void loop(){

}```

### Debug Messages

```
Arduino: 1.8.13 (Windows 10), Board: "LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

In file included from C:\Users\steve\Documents\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFi.h:39,

                 from C:\Users\steve\Documents\Arduino\ShowMacAddress\ShowMacAddress.ino:1:

C:\Users\steve\Documents\Arduino\libraries\ESP8266WiFi\src/WiFiClient.h:89:10: error: conflicting return type specified for 'virtual size_t WiFiClient::availableForWrite()'

   89 |   size_t availableForWrite();

      |          ^~~~~~~~~~~~~~~~~

In file included from C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\cores\esp8266/Stream.h:27,

                 from C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\cores\esp8266/HardwareSerial.h:32,

                 from C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\cores\esp8266/Arduino.h:288,

                 from sketch\ShowMacAddress.ino.cpp:1:

C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\cores\esp8266/Print.h:80:21: note: overridden function is 'virtual int Print::availableForWrite()'

   80 |         virtual int availableForWrite() { return 0; }

      |                     ^~~~~~~~~~~~~~~~~

Multiple libraries were found for "ESP8266WiFi.h"

 Used: C:\Users\steve\Documents\Arduino\libraries\ESP8266WiFi

 Not used: C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\libraries\ESP8266WiFi

exit status 1

Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

**Comment by earlephilhower** [comment]
The error message was quite clear about your problem.  For some reason, you have a bad copy of a private core librari in your Arduino/libraries/ESP8266WiFi directory.  Delete that bad copy and you should be fine.
````
Multiple libraries were found for "ESP8266WiFi.h"
 Used: C:\Users\steve\Documents\Arduino\libraries\ESP8266WiFi
 Not used: C:\Users\steve\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\libraries\ESP8266WiFi
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.
````
