### ISSUE TITLE
Netdump is not working with 3.0.1 release

### ISSUE THREAD

**Issue by saikek** [esp8266/Arduino#8265]
I've converted into issue for easier tracking:

_Originally posted by @saikek in https://github.com/esp8266/Arduino/discussions/8210_

**Comment by saikek** [comment]
@mcspr do we know when this change would be integrated into official release? Thank you.

**Comment by mcspr** [comment]
@saikek it's already a part of the https://github.com/esp8266/Arduino/releases/tag/3.0.2
for PIO, see https://github.com/platformio/platform-espressif8266/issues/255 (no tag yet there)

**Comment by saikek** [comment]
Understood, closing defect & discussion. Duplicate of #8215
