### ISSUE TITLE
Ota update error

### ISSUE THREAD

**Issue by Duality4Y** [esp8266/Arduino#827]
Hi,
When i start a ota update I get this on the serial output:
Update Start: ip:10.42.4.77, port:48266, size:327920
Update Begin Error

and then the update times out.

any ideas?

**Comment by igrr** [comment]
My guess is that free flash space is less than 327k you are trying to upload. This may be the case if you are using a 512k module (or you have selected 512k flash size in Arduino > Tools menu).

**Comment by Duality4Y** [comment]
I solved it, turns out that the code I compiled was for 512K, but while infact I had 4Mb of flash.
