### ISSUE TITLE
delay in receive data from client (in this case is Android App.)

### ISSUE THREAD

**Issue by HoseinSL** [esp8266/Arduino#8270]
Hello there. I setting up my ESP8266 as soft Access Point with ESP8266.h lib. When I try to receive data from my android application  the ESP has delay about 4-5 second to receive my data that second from app.
What should I do to solve this issue?
Is there a solution for?

**Comment by earlephilhower** [comment]
Closing for not following the template.  Please use the discussions or https://esp8266.com for general "How do I..." questions.
