### ISSUE TITLE
axTLS api's deprecated

### ISSUE THREAD

**Issue by suraj9657** [esp8266/Arduino#8282]
### Basic Infos

- [ x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x ] I have tested that the issue is present in current master branch (aka latest git).
- [x ] I have searched the issue tracker for a similar issue.
- [x ] If there is a stack dump, I have decoded it.
- [ x] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12]
- Core Version:			[3.0.0]
- Development Env:		[Arduino IDE|Platformio]
- Operating System:		[Windows|Ubuntu]

### Settings in IDE

- Module:  			[Generic ESP8266 Module||Nodemcu]
- Flash Mode:			[qio|dio]
- Flash Size: 		        [4MB]
- lwip Variant:                  [Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	        [40Mhz]
- CPU Frequency:		[160MHz]
- Upload Using:		[SERIAL]
- Upload Speed:              [115200]

### Problem Description

axTLS api's deprecated in core version 3.0.0 and above

below api are not found,

bool BearSSL::WiFiClientSecure::setCertificate(const uint8_t*, size_t)' is deprecated
bool BearSSL::WiFiClientSecure::setPrivateKey(const uint8_t*, size_t)' is deprecated
bool BearSSL::WiFiClientSecure::setCACert(const uint8_t*, size_t)' is deprecated

what are the alternative option available to use such functionalities?

**Comment by earlephilhower** [comment]
Closing as this is a "How do I..." question and more appropriate as a discussion or on https://esp8266.com.  There are examples for setting certs/etc. in the repo as well as online documentaiton you can refer to as well.
