### ISSUE TITLE
Problems with Sketch Upload (Linux Manjaro): Connecting.....______.....______

### ISSUE THREAD

**Issue by basementmedia2** [esp8266/Arduino#8283]
----------------------------- Delete below -----------------------------

If your issue is a general question, starts similar to "How do I..", is related to 3rd party libs, or is related to hardware, please discuss at a community forum like esp8266.com.

INSTRUCTIONS
============
If you do not follow these instructions, your issue may be dismissed.

1. Follow the checklist under Basic Infos and fill in the [ ] spaces with an X.
2. Fill in all the fields under Platform and Settings in IDE marked with [ ] (pick the correct option for you in each case, delete the others).
3. If you haven't already done so, test your issue against current master branch (aka latest git), because it may have been already fixed.
4. Describe your problem.
5. If you have a STACK DUMP decode it:

https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/stack_dump.html

6. Include a Minimal Complete Reproducible Example sketch that shows your issue. Do not include your entire project, or a huge piece of code.
7. Include debug messages:

https://arduino-esp8266.readthedocs.io/en/latest/Troubleshooting/debugging.html 

8. Use markup (buttons above) and the Preview tab to check what the issue will look like.
9. Delete these instructions from the above to the below marker lines before submitting this issue.

----------------------------- Delete above -----------------------------

### Basic Infos

- [X ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [ X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X ] I have tested that the issue is present in current master branch (aka latest git).
- [X ] I have searched the issue tracker for a similar issue.
- [X ] If there is a stack dump, I have decoded it.
- [X ] I have filled out all fields below.

#### Platform

- Hardware:			        Wemos D1-Mini
- Core Version:			?
- Development Env:		Arduino IDE 1.8.15
- Operating System:		Manjaro 21.1.0

### Settings in IDE

- Module:  			[Generic ESP8266 Modulr]
- Flash Mode:			dout
- Flash Size: 		1MB
- lwip Variant:   v2 Lower Memory
- Reset Method:		nodemcu (dtr)
- Flash Frequency:	[40Mhz]
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   115200

### Problem Description

I have set up a fresh Manjaro system and installed a fresh Arduino version 1.8.15 from the Repository.
Uploading Sketches on my Arduino Nano works.
But i cant upload Sketches on all of my ESP boards.

When i start uploading i get a message like this

```
esptool.py v3.0
Connecting........_____....._____....._____....._____....._____....._____...
```

I have a dual boot system with Windows 10.
When i boot into Windows 10 and upload Sketches everything works fine.
So i think the problem must be Linux Manjaro.

I use the /dev/ttyUSB0 port and the Permissions are set (as said, uploading via this port onto Arduino Nano works perfectly).

i tried already uploading without opened serial monitor and holding the flash button while uploading.
But also this doesnt work.

Do you have further tips?

Best wishes 

Daniel

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <Arduino.h>

void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(LED_BUILTIN, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED_BUILTIN, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);                       // wait for a second
  digitalWrite(LED_BUILTIN, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);                       // wait for a second
}

```
.
### Debug Messages

```
Executable segment sizes:
ICACHE : 32768           - flash instruction cache 
IROM   : 231724          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 26793   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 
DATA   : 1496  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 876   ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 25608 )         - zeroed variables      (global, static) in RAM/HEAP 
Der Sketch verwendet 260889 Bytes (24%) des Programmspeicherplatzes. Das Maximum sind 1044464 Bytes.
Globale Variablen verwenden 27980 Bytes (34%) des dynamischen Speichers, 53940 Bytes für lokale Variablen verbleiben. Das Maximum sind 81920 Bytes.
esptool.py v3.0
Serial port /dev/ttyUSB0
Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
  File "/home/basementmedia/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/upload.py", line 66, in <module>
    esptool.main(cmdline)
  File "/home/basementmedia/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool/esptool.py", line 3552, in main
    esp.connect(args.before, args.connect_attempts)
  File "/home/basementmedia/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool/esptool.py", line 529, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

_
```

**Comment by earlephilhower** [comment]
You will have better luck getting a general question like this answered on https://esp8266.com.

The ESP8266 isn't resetting and responding to the uploader.  Double check the port, the USB cable (which can cause brownouts), try a different port on your machine, etc.  

Also, mnake sure you have the correct reset method.  If you really used "Generic ESP8266" as the board type, you may need to manually reset the board somehow to get it into upload mode.  If you have a commercial board, select the proper one from the menus as they will have the proper reset configs.  Also, you can try different reset modes in the core w/the generic options (Tools->Reset Mode).
