### ISSUE TITLE
Core 3.x looses connection after a while and can't reconnect.

### ISSUE THREAD

**Issue by sblantipodi** [esp8266/Arduino#8284]
Hi,
same code as always have some problems on core 3.x, works well on core 2.7x.

Using ESP8266 D1 Mini from Lolin.

After some hours the ESP looses connection, the only things I can do to make it reconnect is to reset the ESP or reset the router.

Is there a fix for this?

Thanks
Davide

**Comment by earlephilhower** [comment]
Closing as template ignored and deleted, no MCVE, etc.  For general questions please use https://esp8266.com or https://gitter.im/esp8266/Arduino
