### ISSUE TITLE
Не могу загрузить скетч в Wemos D1 mini

### ISSUE THREAD

**Issue by Dairies** [esp8266/Arduino#8293]
----------------------------- Delete below -----------------------------

Здравствуйте, занимался программированием на Arduino IDE, до этого использовал платформы UNO и NANO, недавно купил Wemos D1 mini, но столкнулся с проблемой, что менеджер плат в Arduino IDE не воспринимает Wemos D1 mini. То есть при попытке загрузить любой скетч вылезает ошибка. 
![IMG_20210827_180529](https://user-images.githubusercontent.com/89645154/131132140-b986064c-517f-41c5-8485-e029b5c330e1.jpg)

После этого попытался решить проблему благодаря различным сайтам, но все равно ничего не выходит, вылазит вот такое окно с ошибкой.
![IMG_20210827_135245](https://user-images.githubusercontent.com/89645154/131132080-cdb80b80-86d7-4655-aba8-82e1f37c0228.jpg)
Может кто-то подсказать, как решить данную проблему?

**Comment by eltnpay** [comment]
у меня тоже
