### ISSUE TITLE
Ability to change .local to anything in ESP8266mDNS

### ISSUE THREAD

**Issue by jitendra1607** [esp8266/Arduino#8301]
".local" tld doesn't work in chromium/chrome/edge in android mobiles, you can find this issue easily on google. So please let users have the ability to use any other tld as they wish.

_https://www.google.com/search?q=.local+tld+chromium+bug&rlz=1C5CHFA_enIN754IN754&oq=.local+tld+chromium+bug&aqs=chrome..69i57j33i22i29i30.11912j0j7&sourceid=chrome&ie=UTF-8_

**Comment by mcspr** [comment]
At least from what I've gathered, it would not work as you expect. The google search you linked has at 3 three WontFix answers from the Google Chrome team:
https://bugs.chromium.org/p/chromium/issues/detail?id=30636
https://bugs.chromium.org/p/chromium/issues/detail?id=362356
https://bugs.chromium.org/p/chromium/issues/detail?id=403363

And with Chrome specifically, I only see the DNS request going out. You might want to look into dns->mdns resolving done with the DNS server that you are using locally? At least one example with unbound forward feature
https://superuser.com/questions/821099/configuring-unbound-to-resolve-resolve-on-mdns
