### ISSUE TITLE
Bluepill with ESP8266

### ISSUE THREAD

**Issue by BRoboticsSHADO** [esp8266/Arduino#8303]
Hi

Is there any library support for using esp8266 wifi module with BluePill board (STM32F103C8)?
The ESP8266 wifi module i used is as shown in picture below:
![Screenshot 2021-09-07 130653](https://user-images.githubusercontent.com/88086597/132287332-e25784dc-ffe5-4a65-9473-d1273f115ec0.png)

Best,
Samuel

**Comment by earlephilhower** [comment]
Closing as not core related.  As the template you deleted said, you will be better served using https://esp8266.com or https://gitter.im/esp8266/Arduino or a Bluepill forum to get general help like this.

**Comment by BRoboticsSHADO** [comment]
Thanks for redirecting of the links.
