### ISSUE TITLE
ESP01 connects to wifi through at commands but not from program

### ISSUE THREAD

**Issue by olo00olo** [esp8266/Arduino#8315]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-01]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Generic ESP8266 Module]
- Flash Mode:			[dout]
- Flash Size: 		[1MB]
- lwip Variant:   [Higher Bandwidth]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Speed:   [115200)

### Problem Description

Hello, I'm trying connect my ESP to wifi through program below but every time it can't connect. But after flashing firmware AT commands work properly. It happens on all my 3 ESPs. I've tried a lot of fix ideas but any didn't work. I've also tried a few wifi networks but also this didn't helped

I'm using usb uart converter with CH_PD connected to 3V3.

Do you have any idea to run this?

#include "ESP8266WiFi.h"

const char* ssid = "xxxxx"; //Enter SSID
const char* password = "xxxxx"; //Enter Password

void setup(void)
{ 
  Serial.begin(115200);
  // Connect to WiFi
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) 
  {
     delay(500);
     Serial.print("*");
  }
  
  Serial.println("");
  Serial.println("WiFi connection Successful");
  Serial.print("The IP Address of ESP8266 Module is: ");
  Serial.print(WiFi.localIP());// Print the IP address
}

void loop() 
{
  // EMPTY
}

**Comment by earlephilhower** [comment]
This seems like a general "How do I..." question.  Please use https://gitter.im/esp8266/Arduino or https://esp8266.com for general assistance requests.
