### ISSUE TITLE
Bricked after setting static IP. Cant access it without wifi connection

### ISSUE THREAD

**Issue by SeMdhl** [esp8266/Arduino#8320]
[](url)### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				[ESP8266 ESP-f](https://github.com/roarfred/AmsToMqttBridge)
- Core Version:			[Dont know]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[ESP8266 ESP-f]

### Problem Description

I got 5 ESP8266 based boards set up like [this](https://github.com/roarfred/AmsToMqttBridge). And they all worked fine for a long time, until the wifi setup changed. I had to set static IP on them, and they still worked for about 2 days(DHCP lease time?) and then they stopped sending data over mqtt. When i tried to access them via IP, that did not work either.
I checked the google auto fill database to see if i typed something wrong in the static IP settings. But nope, everything is correct.

So im assuming static IP just does not work on them? which is fine, but i have no way of changing it back to DHCP. The only way to access them is through IP, so i have to make them go into AP mode.

The documentation only once mentions a restart option, which is to short GPIO13 and 3.3V. That did absolutely nothing. Theres also a button thats supposed to reset it([SW1](https://github.com/roarfred/AmsToMqttBridge/tree/master/Electrical/HAN_ESP_TSS721#readme)), but also does nothing.
I tried taking them to another place, where that wifi does not exists, but still no AP.

Is there any other way that could make them go into AP mode?

**Comment by earlephilhower** [comment]
There's no MCVE and the problem seems to be w/a 3rd party library.  I suggest posting something there as there's nothing we can do here.  You can also use https://esp8266.com or https://gitter.im/esp8266/Arduino
