### ISSUE TITLE
changed the fingerprints  too but not connecting to firebase 

### ISSUE THREAD

**Issue by naazkakria** [esp8266/Arduino#8322]
Arduino: 1.8.16 (Windows Store 1.8.51.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

In file included from C:\Users\HP\Documents\Arduino\libraries\firebase-arduino-master\src/Firebase.h:30:0,

                 from C:\Users\HP\Documents\Arduino\libraries\firebase-arduino-master\src/FirebaseArduino.h:22,

                 from C:\Users\HP\Documents\Arduino\sketch_sep26a\sketch_sep26a.ino:3:

C:\Users\HP\Documents\Arduino\libraries\firebase-arduino-master\src/FirebaseObject.h:109:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see https://arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

     std::shared_ptr<StaticJsonBuffer<FIREBASE_JSONBUFFER_SIZE>> buffer_;

           ^

In file included from C:\Users\HP\Documents\Arduino\libraries\firebase-arduino-master\src/FirebaseArduino.h:22:0,

                 from C:\Users\HP\Documents\Arduino\sketch_sep26a\sketch_sep26a.ino:3:

C:\Users\HP\Documents\Arduino\libraries\firebase-arduino-master\src/Firebase.h:86:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see https://arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

   std::shared_ptr<StaticJsonBuffer<FIREBASE_JSONBUFFER_SIZE>> buffer_;

           ^

Multiple libraries were found for "ArduinoJson.h"

 Used: C:\Users\HP\Documents\Arduino\libraries\ArduinoJson

 Not used: C:\Users\HP\Documents\Arduino\libraries\ArduinoJson-5.13.1

 Not used: C:\Users\HP\Documents\Arduino\libraries\Antares_ESP8266_HTTP

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by earlephilhower** [comment]
Template ignored, problem with 3rd party library compilation.  Closing.
