### ISSUE TITLE
Wifi.begin(ssid, password) : delay 

### ISSUE THREAD

**Issue by ruem2802** [esp8266/Arduino#8324]
Hi, im using esp8266 nodeMCU 1.0
i use  WiFi.begin(WiFi.SSID(), WiFi.psk()); to connect wifi 
But i want to control relay and it delay about 1500ms so i cant' control relay about 1500ms
How to fix this?
Error in esp: 3.0.2
When i download esp 2.7.4 everything is ok

**Comment by mcspr** [comment]
There's no MCVE, which was suggested in the template to allow everyone to reproduce the issue.

afaik, the delay is expected, internal routines take a while to connect. you might want to explore the channel and bssid settings?
https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/station-class.html#begin
(maybe also the static IP, gateway, mask and DNS)

**Comment by ruem2802** [comment]
@mcspr Thank you!
