### ISSUE TITLE
lwip2 problems, works nicely with lwip 1.4

### ISSUE THREAD

**Issue by buitre-buitaker** [esp8266/Arduino#8333]
Hi,

There are some issues identified using lwip 2 instead of lwip 1.4 with some really good libraries. See for example: 

[https://github.com/martin-ger/uMQTTBroker/issues/12](https://github.com/martin-ger/uMQTTBroker/issues/12)

Is there any way to integrate lwip 1.4 in the 3.X branch of esp8266?

Is the only way to use really good libraries, like uMQTTbroker, just to downgrade the ESP8266 core version to latest 2.X version and to adapt the sketches?

Thank you

**Comment by d-a-v** [comment]
see https://github.com/martin-ger/uMQTTBroker/issues/12#issuecomment-504710446

- [espconn has been ported](https://github.com/d-a-v/esp82xx-nonos-linklayer/tree/master/glue-lwip) in lwip2 but not tested yet to my knowledge.

- It is not planned and unlikely that lwip1.4 which has been [removed in release 3.0.0](https://github.com/esp8266/Arduino/releases/tag/3.0.0) is backported in future releases.
