### ISSUE TITLE
New Version (3.0.0 ->3.0.2) crashes with MySQL connect

### ISSUE THREAD

**Issue by Falkenstone** [esp8266/Arduino#8335]
Hi,
since the new Board Version ESP8266 3.0..0 the connect to MySQL (Library MySQL_Connector_Arduino) crashes every time. I am not the professional to find out what is different to version 2.7.3. That was my last attempt with which version the "connect" function worked. Could you inspect this issue and modify the library? You could use one of the example from the library and you see what happened.

thx 
Falke

**Comment by mcspr** [comment]
...also a duplicate of #8250 

notice that the current version of the library can't be built successfully with the Core 3.0.2 anyway, only 3.0.0. and I'd suggest to look at the piece of code it stops compiling at and fix the issue
```
building `.pio\build\nodemcuv2\lib3d7\MySQL_Connector_Arduino\MySQL_Encrypt_Sha1.cpp.o' because it doesn't exist
Compiling .pio\build\nodemcuv2\lib3d7\MySQL_Connector_Arduino\MySQL_Encrypt_Sha1.cpp.o
lib\MySQL_Connector_Arduino\src\MySQL_Encrypt_Sha1.cpp: In member function 'virtual size_t Encrypt_SHA1::write(uint8_t)':
lib\MySQL_Connector_Arduino\src\MySQL_Encrypt_Sha1.cpp:89:1: error: no return statement in function returning non-void [-Werror=return-type]
   89 | }
      | ^
lib\MySQL_Connector_Arduino\src\MySQL_Encrypt_Sha1.cpp: In member function 'virtual size_t Encrypt_SHA1::write(uint8_t*, int)':
lib\MySQL_Connector_Arduino\src\MySQL_Encrypt_Sha1.cpp:95:1: error: no return statement in function returning non-void [-Werror=return-type]
   95 | }
      |
```
it is literally saying what is wrong :) both Encrypt_SHA1::write() result is never used, so just add `return 0;`

**Comment by d-a-v** [comment]
You may edit the *first* post in [your PR](https://github.com/ChuckBell/MySQL_Connector_Arduino/pull/177) and add "fixes # 171 # 173 # 176 and maybe # 145"
(without spaces)

**Comment by Pablo2048** [comment]
Done, thanks for the guidance...
