### ISSUE TITLE
Host tests: LittleFS SpeedTest SIGFPE (Floating point exception)

### ISSUE THREAD

**Issue by mcspr** [esp8266/Arduino#8339]
Running 40b26b769c794be2a2afad4d2c8a10a00b0d6f6d
```
> cd host/tests
> make ../../libraries/LittleFS/examples/SpeedTest/SpeedTest
> ./bin/SpeedTest/SpeedTest
SPIFFS: 1048576 bytes
SPIFFS: loading 1048576 bytes from './bin/SpeedTest/SpeedTest-spiffs1024KB'
LittleFS: 1048576 bytes
LittleFS: loading 1048576 bytes from './bin/SpeedTest/SpeedTest-littlefs1024KB'
Beginning test
Creating 512KB file, may take a while...
==> Time to write 512KB in 256b chunks = 2 milliseconds
==> Created file size = 524288
Reading 512KB file sequentially in 256b chunks
==> Time to read 512KB sequentially in 256b chunks = 1 milliseconds = 524288000 bytes/s
Reading 512KB file MISALIGNED in flash and RAM sequentially in 256b chunks
fish: './bin/SpeedTest/SpeedTest' terminated by signal SIGFPE (Floating point exception)
```

`stop - start` can be 0
```
Program received signal SIGFPE, Arithmetic exception.
0x000055555555917c in DoTest (fs=0x5555555874f0 <LittleFS>) at ./../../libraries/LittleFS/examples/SpeedTest//SpeedTest.ino:75
75        Serial.printf("==> Time to read %dKB sequentially MISALIGNED in flash and RAM in 256b chunks = %ld milliseconds = %ld bytes/s\n", TESTSIZEKB, stop - start, TESTSIZEKB * 1024 / (stop - start) * 1000);
```

There are more offending lines though
https://github.com/esp8266/Arduino/blob/40b26b769c794be2a2afad4d2c8a10a00b0d6f6d/libraries/LittleFS/examples/SpeedTest/SpeedTest.ino#L62
https://github.com/esp8266/Arduino/blob/40b26b769c794be2a2afad4d2c8a10a00b0d6f6d/libraries/LittleFS/examples/SpeedTest/SpeedTest.ino#L75
https://github.com/esp8266/Arduino/blob/40b26b769c794be2a2afad4d2c8a10a00b0d6f6d/libraries/LittleFS/examples/SpeedTest/SpeedTest.ino#L95
https://github.com/esp8266/Arduino/blob/40b26b769c794be2a2afad4d2c8a10a00b0d6f6d/libraries/LittleFS/examples/SpeedTest/SpeedTest.ino#L106
https://github.com/esp8266/Arduino/blob/40b26b769c794be2a2afad4d2c8a10a00b0d6f6d/libraries/LittleFS/examples/SpeedTest/SpeedTest.ino#L117

I suppose there should be a helper function for example(s) or the tests specifically that handles time tracing instead of manual approach like this

**Comment by earlephilhower** [comment]
While I see your point, I'm not sure it's worth the code to patch an onboard flash speed test to run on the host which is using DRAM and can end up with div-by-0 error errors.  This example in particular was meant to compare on-device speeds of LittleFS, SDFS, and SPIFFS, and running on the host is not really useful IMHO.
