### ISSUE TITLE
UpdaterClass doesn't allow restarting the update process. 

### ISSUE THREAD

**Issue by mangelajo** [esp8266/Arduino#834]
If the streaming connection disconnects, or the Http upgrade stops, you're left in a situation where you cannot begin the update again, it will say:

"already running", and return false.

We need to get an specific error code for that, and then have a method to forcefully reset the updater to a clean state (next http download, OTA, or http post)

**Comment by mtnbrit** [comment]
Update.end()

**Comment by mangelajo** [comment]
whoops, you're right. I somehow misinterpreted _reset for a board reset, but of course, it's the class reset... 

Thanks @mtnbrit
