### ISSUE TITLE
Arduino 2.0.0-beta.12 No hostname shown in OTA update, only IP address...

### ISSUE THREAD

**Issue by tomtdl** [esp8266/Arduino#8344]
![Screenshot at 2021-10-17 02-45-21](https://user-images.githubusercontent.com/48753150/137621647-d3ebd92e-3278-44cb-be14-7b802fb1c58a.png)

Arduino 1.8.13 will list IP address AND hostname of all online  ESP8266's
Arduino 2.0.0-beta.12 ONLY lists IP addreses

This is difficult as I have many OTA-updateable ESP's online and most are DHCP addressed.

Anyone else notice this different behavior?  Believe me, I googled the issue, checked the forums
and found no answer.  This is in Linux Mint 20 on a new installation of Arduino 2.0

I am new to posting here.  Please forgive me if this is the wrong way to ask or post an issue.

Tom Leitschuh

(screenshot attached as png)

**Comment by vincentVDB** [comment]
I haven-t Port item under Board in Tools menu !
i'm in beta 12

**Comment by mcspr** [comment]
Fixed in https://github.com/arduino/arduino-ide/pull/1335
