### ISSUE TITLE
Python version mismatch in OTA doc

### ISSUE THREAD

**Issue by kifort** [esp8266/Arduino#8416]
### Basic Infos

- [?] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [-] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:				none
- Core Version:			2021.12.19
- Development Env:		none
- Operating System:		all

### Settings in IDE

- Module:  			none
- Flash Mode:			none
- Flash Size: 		all
- lwip Variant:   none
- Reset Method:		none
- Flash Frequency:	none
- CPU Frequency:		none
- Upload Using:		OTA
- Upload Speed:   none (serial upload only)

### Problem Description

In [OTA update documentation]
(https://github.com/esp8266/Arduino/blob/master/doc/ota_updates/readme.rst#:~:text=select%20%E2%80%9CAdd%20python.exe%20to%20Path%E2%80%9D), text is about Python 3.x, but screenshot is Python 2.7.

See the confusion it causes at this [OTA tutorial](https://randomnerdtutorials.com/esp8266-ota-updates-with-arduino-ide-over-the-air/)

**Comment by earlephilhower** [comment]
Good catch!

Users don't even need to install Python anymore (we ship and use our own private version), so that whole bit of the docs should be deleted.
