### ISSUE TITLE
WiFi.begin("MySSID", "MyPWD") function causes code failor

### ISSUE THREAD

**Issue by TavakoliAli** [esp8266/Arduino#8420]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-07]
- Core Version:			[3.0.2]
- Development Env:		[Platformio]
- Operating System:		[Ubuntu]

### Settings in IDE

- Module:  			[ESP07]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[160MHz]
- Upload Using:		[SERIAL]
- Upload Speed:   [921600] (serial upload only)

### Problem Description

I have 4 large programs. The programs are divided into 2 section logically:  
1.  The section one controls configuration(I use ***smartconfig***) and connections and 
2. section two controls user interface (i.e. switches, LEDs and relays).  
  
Section two is differ between programs and section one is same (I use Git diff tool to check that). However one of my programs get fails on ***smartconfig*** process.  
I tried a lot and found out that once i comment the  WiFi.begin(mySSID, MyPass)  line my program work perfectly. I decided to debug the program so un-comment that line and and enable debug output on *Serial1* as :

```cpp
  Serial1.begin(115200);
  Serial1.setDebugOutput(true);
```

But the program worked again without problem. I disable debuging but program don't work again.
I change WiFi.begin("mySSID", "MyPass") with WiFi.begin() and its work again.

I Think my programs don't have problem and this problem is related to Arduino core.
**Tell me if you need more information?**

*Note:* I tested all programs on one module.
*Note:* I can't write a small program to recreates same issue (I can send programs if you want).

**Comment by janike** [comment]
Hello,
i encountered similar problem but with WiFi.softAP method.
Problem was with password length - default encryption method WPA2 requires minimum password length of 8.
When password was shorter, it created last succesfully created wifi.
Hope that solves your problem.
