### ISSUE TITLE
Compiler directive to compile a block of code depending ESP8266 core version

### ISSUE THREAD

**Issue by cniedzi** [esp8266/Arduino#8424]
Hi,

What is Arduino IDE compiler directive to compile a block of code depending ESP8266 core version, for example:

```
#if (core version > 3.0.0) 
    compile this block
#else
    compile this block
```

**Comment by earlephilhower** [comment]
As the template said, this is not the place for general questions like this.  Look at the `core_version.h` header file for info in detecting the version at compile time.  Closing.

**Comment by cniedzi** [comment]
ok. Thx.
