### ISSUE TITLE
String: API must be fixed

### ISSUE THREAD

**Issue by d-a-v** [esp8266/Arduino#8430]
Per [this comment](https://github.com/esp8266/Arduino/issues/8404#issuecomment-1003521423),
`String` API has changed since release 2.7.4 and should be fixed.

(cc: @Ciapas-Linux)

**Comment by mcspr** [comment]
Notice that this is esp8266 & esp32 Core feature, ArduinoCore-API's String does not implement this and will fail with `No viable overloaded '='`
```diff
diff --git a/test/src/String/test_operators.cpp b/test/src/String/test_operators.cpp
index 67cb39b..e48fc4f 100644
--- a/test/src/String/test_operators.cpp
+++ b/test/src/String/test_operators.cpp
@@ -164,3 +164,10 @@ TEST_CASE ("Testing & String::operator = (StringSumHelper &&)", "[String-operato
   str1 = static_cast<arduino::StringSumHelper&&>(str+ch);
   REQUIRE(str1 == "Hello!");
 }
+
+TEST_CASE ("Testing assignment operator")
+{
+  arduino::String str;
+  str = 12345;
+  REQUIRE(str == "12345");
+}
```
```
/home/runner/dev/ArduinoCore-API/test/src/String/test_operators.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____36()’:
/home/jhdtl/dev/ArduinoCore-API/test/src/String/test_operators.cpp:171:9: error: ambiguous overload for ‘operator=’ (operand types are ‘arduino::String’ and ‘int’)
  171 |   str = 12345;
      |         ^~~~~
```
https://github.com/arduino/ArduinoCore-API/blob/e03b65374c614130aa1b11597e07b3b5089a726d/api/String.h#L102

With 2.7.4, and earlier versions, this would've called `String::operator=(StringSumHelper&&)` and converted the `int` through `String::String(int, base=10)`
https://github.com/espressif/arduino-esp32/blob/caef4006af491130136b219c1205bdcf8f08bf2b/cores/esp32/WString.h#L105
(and, esp32 Core still does this :)

`String::operator=(char)` was added after looking at `std::string` API
gnu.org/onlinedocs/gcc-11.2.0/libstdc++/api/a02039.html#a79cf5ca6fa3860d67ddde51fc19f4a2d
And only our string has it, I wonder if ArduinoCore API should have it as well
