### ISSUE TITLE
FS.h not found

### ISSUE THREAD

**Issue by adityaghosh1209** [esp8266/Arduino#8431]
the library fs.h is not being detected suddenly!
1 day before, it was working, but now?
and when I removed it, your library, i.e. esp8266wifi is not being detected.
online is saying fs is an inbuilt one and not a library to import.

Please help me out, thanks.

**Comment by d-a-v** [comment]
This is an installation issue.
You can try to remove the "arduino15" directory (in your local data) and start over with the installation of this core.
