### ISSUE TITLE
Unable to Mine 

### ISSUE THREAD

**Issue by kamalmoharana** [esp8266/Arduino#8457]
Hi,
I'm trying to min with ESP32 board, and not able to mine

13:27:41.042 -> [ 31331][E][ssl_client.cpp:127] start_ssl_client(): socket error on fd 49, errno: 113, "Software caused connection abort"
13:27:41.042 -> [ 31331][E][WiFiClientSecure.cpp:135] connect(): start_ssl_client: -1
13:27:41.042 -> [ 31332][D][HTTPClient.cpp:1134] connect(): failed connect to server.duinocoin.com:443
13:27:41.042 -> [ 31334][W][HTTPClient.cpp:1437] returnError(): error(-1): connection refused
13:27:41.042 -> Poolpicker fetch failed - error: connection refused
13:27:41.042 -> [ 31338][D][HTTPClient.cpp:405] disconnect(): tcp is closed
13:27:41.042 -> 
13:27:42.026 -> Fetching mining node from the poolpicker in 2s
13:27:42.026 -> [ 32339][D][HTTPClient.cpp:298] beginInternal(): protocol: https, host: server.duinocoin.com port: 443 url: /getPool
13:27:42.026 -> [ 32339][D][HTTPClient.cpp:595] sendRequest(): request type: 'GET' redirCount: 0
13:27:42.060 -> 
13:27:43.114 -> Core 0 is waiting for the poolpicker...

----------------------------- Delete below -----------------------------

**Comment by d-a-v** [comment]
Please head to [esp32/Arduino](https://github.com/espressif/arduino-esp32)
