### ISSUE TITLE
hal-time in timer interrupt cause esp32 reset

### ISSUE THREAD

**Issue by SynonZelra** [esp8266/Arduino#8473]
So I'm working on a project on interrupts.
```
  //Set Timer, Change divider after changed frequency
  TimerInterrupt = timerBegin(0, 80, true);
  //Timer 0 runs at 80Mh
  //Divider at 80 makes 1 tick 1s/(80M/80) = 1us
  timerAttachInterrupt(TimerInterrupt, onTimer, true);
  timerAlarmWrite(TimerInterrupt, 2000000, true);
  //interrupt at 1us*2000000 = 2s
  timerAlarmEnable(TimerInterrupt);
```
and every time esp32 resets while the interrupt occurs
so I go through line by line, finding out
`configTime(UTCOffset,DayLightOffset,ntpServer);`
this line cause the problem.

Any solution?
Thanks

**Comment by d-a-v** [comment]
Please head to the [Arduino core for ESP32](https://github.com/espressif/arduino-esp32#arduino-core-for-the-esp32-esp32-s2-and-esp32-c3).
