### ISSUE TITLE
IDE no longer caching since new staging?

### ISSUE THREAD

**Issue by mtnbrit** [esp8266/Arduino#848]
Hi since upgrading to the latest staging yesterday, I notice the IDE no longer seems to be caching the already-compiled sections as it used to. Now it seems to re-compile everything, after even a minor code change. This obviously slows down the development cycle quite a bit. Any ideas what may have changed here?

**Comment by igrr** [comment]
Does it say "build options changed, rebuilding all" at the top of compiler output (if you enable verbose output in preferences?)

**Comment by gorec2005** [comment]
Yes for me... it says "build options changed, rebuilding all" at the top of compiler output

**Comment by mtnbrit** [comment]
I dont know why but today its caching just fine.
