### ISSUE TITLE
Latest master branch fails to ping my router.

### ISSUE THREAD

**Issue by sblantipodi** [esp8266/Arduino#8494]
Hi all,
this class have a method to ping the router.

```
#if defined(ESP8266)

#include "PingESP.h"

extern "C" void esp_schedule();
extern "C" void esp_yield();

PingESP::PingESP() {}

byte PingESP::pingError = 0;
byte PingESP::pingSuccess = 0;

/**
 * Ping gateway to keep the connection alive
 * @param dest gateway to ping
 * @return
 */
bool PingESP::ping(IPAddress dest) {
  pingError = 0;
  pingSuccess = 0;
  memset(&pingOptions, 0, sizeof(struct ping_option));
  pingOptions.count = 1; // repeat only 1 time
  pingOptions.coarse_time = 1;
  pingOptions.ip = dest;
  pingOptions.recv_function = reinterpret_cast<ping_recv_function>(&PingESP::receivePingCallback);
  pingOptions.sent_function = NULL;
  if (ping_start(&pingOptions)) {
    // Sleep until the ping is finished
    esp_yield();
  }
  return (pingSuccess > 0);
}

/**
 * Callback from the ESP core ping_start
 * @param opt options
 * @param resp response
 */
void PingESP::receivePingCallback(void *opt, void *resp) {
  // ping_resp from ESP core
  ping_resp *ping_resp = reinterpret_cast<struct ping_resp *>(resp);
  // Check for errors
  if (ping_resp->ping_err == -1) {
    pingError++;
    Serial.println(F("PING KO"));
  } else {
    pingSuccess++;
  }
  if (pingSuccess + pingError == 1) {
    // ping sent, return
    esp_schedule();
  }
}

#endif
```

If I use this class with the Arduino 3.0.2 sources it works awesome,
it I update the arduino sources to the latest master branch (#fd53a080ee670dfc973d44c584b2d0385987790e) it fails to ping the router.

Is there some regression in the latest master branch?

**Comment by mcspr** [comment]
`esp_yield()` was changed in c312a2eaf1356ceaafad7c4935fa850e087c84fe

The code above expects to 'sleep' by calling `esp_yield()` and be woken up after recv callback calls `esp_schedule()`. With the master, `esp_yield()` *also* schedules immediately, thus never executing recv in time and never updating the variables related to success of failure. Direct alternative would be to use new `esp_suspend()`.
What it does not take into an account is that any other part of the program could call `esp_schedule()` while we are in the SYS (timer, pending wificlient, etc.). It is not a truly reliable method to wait for things.

With the master, I'd suggest to have a flag tracking recv success (i.e. when we are really done with pings) and use either `esp_suspend([&]() { return blocking_for_recv; });` or `esp_delay(5000, [&]() { return blocking_for_recv; }, 100);` to block.
1st one waits indefinitely for the boolean attached to the class instance to switch from true to false, 2nd one does `esp_schedule()` every 100ms and time-outs after 5seconds

**Comment by sblantipodi** [comment]
last question if possible, what do you mean that is not a truly reliable method to wait for things?
can I simply miss a ping or can I have bigger problems?

what does it happen if I call esp_schedule() when I'm in SYS?

suppose that I'm inside the SYS timer, it delays the timer?
and what about if I'm inside the pending wificlient?
