### ISSUE TITLE
Making the Core ESP8266 Support pre-compiled libraries

### ISSUE THREAD

**Issue by InqOnThat** [esp8266/Arduino#8499]
I'm new to Github, so I don't know if this is the appropriate place for this request.  Apologies. 

I'd like to request the addition of a single file to the ESP8266 distribution.  By placing this in the same folder as the _platform.txt_ file, it permits the use of **any** pre-compiled libraries.  

On my Windows installation, this was in the folder:
C:\Users\Inq\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2

**Before adding the file, the compiler will error with something like**
_Library Inq has been declared precompiled:
Using precompiled library in C:\Users\Inq\Documents\Arduino\libraries\Inq\src\esp8266
The platform does not support 'compiler.libraries.ldflags' for precompiled libraries.
<and several dozen other errors>_

**After adding the file, the compiler reports a successful build**
_Library Inq has been declared precompiled:
Using precompiled library in C:\Users\Dennis\Documents\ArduinoLW\libraries\Inq\src\esp8266
Executable segment sizes:
ICACHE : 32768           - flash instruction cache 
IROM   : 360304          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27373   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 
DATA   : 1552  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 5936  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 26080 )         - zeroed variables      (global, static) in RAM/HEAP 
Sketch uses 395165 bytes (37%) of program storage space. Maximum is 1044464 bytes.
Global variables use 33568 bytes (40%) of dynamic memory, leaving 48352 bytes for local variables. Maximum is 81920 bytes._

[platform.local.txt](https://github.com/esp8266/esp8266.github.io/files/8171965/platform.local.txt)

**Comment by mcspr** [comment]
Should already be fixed by https://github.com/esp8266/Arduino/pull/8392 for the (pending) 3.1.0
https://github.com/esp8266/Arduino/blob/ead5f94dd3b24229818876877a9591e9ec51ce7e/platform.txt#L67-L68

I don't believe .local.txt should not be provided by us
https://arduino.github.io/arduino-cli/0.21/platform-specification/#platformlocaltxt

**Comment by InqOnThat** [comment]
Thank you for your quick response.

You are totally right about the second statement.  I forgot who was going
to receive the request... since you are the library provider, you are
supposed to put it in platform.txt as I see you have done in your first
statement.

Do you have an estimate when normal Arduino IDE users might see 3.1.0?
