### ISSUE TITLE
TelnetToSerial code Telnet echo issue

### ISSUE THREAD

**Issue by vishalc07** [esp8266/Arduino#8502]
Hello,

I'm using Serial access via WiFi(Telnet), currently facing issue with Telnet Echo. If I press "enter" key it reflect twice. I try to suppress, but no luck 

pls check attached snap

![image](https://user-images.githubusercontent.com/64244691/156868425-3d0ddb6d-ed4b-4e0c-ae94-7d25ebcf46c8.png)

**Comment by d-a-v** [comment]
Your telnet client probably sends `\r\n` / `\10\13`.
There's probably some settings to change that.

**Comment by vishalc07** [comment]
When I'm pressing "enter" key,  I'm sending \r\n, but I'm receiving \r\n twice, I got it with help of Wireshark.

is there any way to suppress that
