### ISSUE TITLE
memmem missing?

### ISSUE THREAD

**Issue by plerup** [esp8266/Arduino#854]
Hi,

Seems like standard function memmem is missing in the libs:

    undefined reference to `memmem'
    collect2: error: ld returned 1 exit status
    Error compiling.

Other mem-fuctions works ok

BR
/Peter

**Comment by vicatcu** [comment]
fwiw grep'ing for memmem in the core reveals the existence of:

```
void* memmem_P(const void* buf, size_t bufSize, PGM_VOID_P findP, size_t findPSize);
```

... in cores/esp8266/pgmspace.h

**Comment by igrr** [comment]
Since we don't use libc at the moment, we don't have memmem.
You could port newlib's implementation and add it into libc_replacements.c.

**Comment by plerup** [comment]
Ok, I see, thanks
