### ISSUE TITLE
AdaFruit_MLX90614 fatal eror, and i ditdn't use library I2Cdevice in my program. 

### ISSUE THREAD

**Issue by wansyar** [esp8266/Arduino#8542]
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "Arduino Nano, ATmega328P"

In file included from D:\Program\Percobaan\Percobaan.ino:3:0:

C:\Users\Wansya\OneDrive\Documents\Arduino\libraries\Adafruit-MLX90614-Library-master/Adafruit_MLX90614.h:18:10: fatal error: Adafruit_I2CDevice.h: No such file or directory

 #include <Adafruit_I2CDevice.h>

          ^~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1

Error compiling for board Arduino Nano.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by earlephilhower** [comment]
You deleted the template, didn't give any useful information, and are reporting on a problem in a 3rd party library on a board that's not even an ESP8266.  Closing.
