### ISSUE TITLE
Can EEPROM be larger than 4096 bytes (multiple sectors)?

### ISSUE THREAD

**Issue by samw3** [esp8266/Arduino#858]
I understand that this is the size of one flash sector, can multiple sectors be supported?

**Comment by igrr** [comment]
Reading and writing flash is quite straightforward, so yes, someone could easily add multiple sectors support to EEPROM. Take a look at EEPROM library source, there's not much of it.
The only issue one would have to solve is where to allocate these EEPROM sectors. If you are using EEPROM i imagine you're not using file system, so you could occupy a few sectors dedicated to file system. See the reference page for an illustration of flash layout.
