### ISSUE TITLE
I think that it's time to release a new version. isn't it?

### ISSUE THREAD

**Issue by sblantipodi** [esp8266/Arduino#8592]
As title.
Is there any sense in not releasing a new version ?

**Comment by d-a-v** [comment]
1. https://arduino-esp8266.readthedocs.io/en/latest/installing.html#using-git-version
2. https://d-a-v.github.io/esp8266/Arduino/index.htm
3. there is no due date yet for the 3.1 release (but fwiw we're on it)

**Comment by enjoyneering** [comment]
> 1. https://arduino-esp8266.readthedocs.io/en/latest/installing.html#using-git-version
> 2. https://d-a-v.github.io/esp8266/Arduino/index.html
> 3. there is no due date yet for the 3.1 release (but fwiw we're on it)

Hi d-a-v can you update your snapshot to the latest dev?

**Comment by d-a-v** [comment]
> Hi d-a-v can you update your snapshot to the latest dev?

done
