### ISSUE TITLE
Unable to disable DHCP client in ESP8266WiFiSTA.h

### ISSUE THREAD

**Issue by innerspacepilot** [esp8266/Arduino#8594]
Hello!
Looking at the code in ESP8266WiFiSTA.h, there is protected member `static bool _useStaticIp`, but there is no way to set it to true.
Seems something like `static void enableStaticIP (bool enable = true) { _useStaticI = enable; }` should be added.
So, there is no way to disable DHCP client if it's not needed, check the code [here](https://github.com/esp8266/Arduino/blob/9e2103f27e9eacba39d25697bacc5142a7aa5e66/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp#L203)

Please add an option to disable dhcp client.
Thanks.

**Comment by mcspr** [comment]
Use static config?
https://github.com/esp8266/Arduino/blob/9e2103f27e9eacba39d25697bacc5142a7aa5e66/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp#L266
https://github.com/esp8266/Arduino/blob/9e2103f27e9eacba39d25697bacc5142a7aa5e66/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp#L302
