### ISSUE TITLE
..... folder/zip file doesn't contain valid library

### ISSUE THREAD

**Issue by acp-usrmbu** [esp8266/Arduino#8632]
Hello,
can you please help me with installing the esp8266 library?
After choosing the zip file the arduino IDE inform me that the zip file doesn't contain valid library... do you have some idea where can be the problem?
Many thnaks
BR
Martin

**Comment by JAndrassy** [comment]
https://github.com/esp8266/Arduino#installing-with-boards-manager

**Comment by acp-usrmbu** [comment]
great... many thanks
Martin :)
