### ISSUE TITLE
Bug in sendContent_P

### ISSUE THREAD

**Issue by JohnSL** [esp8266/Arduino#864]
It looks like there is a bug in the following line of sendContent_P:
```C
contentUnitLen = contentNext - content;
```
I believe the memccpy_P function returns the last copied byte in the buffer, not the source. So therefore the line above should be this:
```C
contentUnitLen = contentNext - contentUnit;
```
This is in the file ESP8266WebServer.cpp. I've created a pull request, #880, for this issue.

**Comment by igrr** [comment]
#880 merged, thank you!

**Comment by JohnSL** [comment]
Thank you!
