### ISSUE TITLE
New example for esptocuh v2 protocol

### ISSUE THREAD

**Issue by mralperem** [esp8266/Arduino#8669]
Hello,

Could you add a new exaple for smart config featuring esptouch v2 protocol. Since it does come with security improvemnts i was hoping that implementing would be a good idea. Thank you

**Comment by mcspr** [comment]
Looking at the sources, not yet. I believe this depends on #5790, RTOS update to IDF sources definitely picked this feature up https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/components/esp8266/source/smartconfig_ack.c
