### ISSUE TITLE
User is unable to define if WiFi.disconnect should null-ify SSID and Password or not

### ISSUE THREAD

**Issue by cziter15** [esp8266/Arduino#8689]
This issue is not really related to any board, but directly to the source code, using template is not necessary here.

The problem is that WiFi.disconnect function always set SSID and Password to NULL. On ESP32's version of Arduino, user can define if the config should be ever touched or not. When manually implementing reconnection, current state requires to store credentials externally between disconnect and connect method calls.

This should be unified somehow or at least eraseAP switch should be added to allow calling underlying methods without zeroing credentials.

Current workaround is calling wifi_station_disconnect directly.

https://github.com/espressif/arduino-esp32/blob/a5f03a86512b270be1080d7e7cb82e4fd71c9a1a/libraries/WiFi/src/WiFiSTA.cpp#L345
https://github.com/esp8266/Arduino/blob/da6ec83b5fdbd5b02f04cf143dcf8e158a8cfd36/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp#L350

**Comment by d-a-v** [comment]
> On ESP32's version of Arduino, user can define if the config should be ever touched or not

Would you be ready to make an API addition proposal [to match esp32's](https://github.com/espressif/arduino-esp32/blob/9275dbff942bb2ccce62632607500ad27dd0513a/libraries/WiFi/src/WiFiSTA.cpp#L345) ?

**Comment by cziter15** [comment]
I will issue PR, but give me few hours :)

**Comment by cziter15** [comment]
I think it's better to erase whole AP data. We don't know how user will use it, but in case we want to forget AP data, we should erase at least whole password field.

**Comment by cziter15** [comment]
I've re-issued PR !8758
