### ISSUE TITLE
ESP8266 default power mode

### ISSUE THREAD

**Issue by shirish47** [esp8266/Arduino#870]
what is the default power mode based on this chart.
http://bbs.espressif.com/download/file.php?id=177&sid=ece47e1a03b85c5a4c9f395381d56e7a

Please and how can we change it.

**Comment by asetyde** [comment]
Depends what are you doing with esp ... If you use wifi with modern router you can see 2 value , tx and rx with N type . but this are oscillating value between 50/120 milliampere i think .
you connect a sensor 100ma ? 220ma max and 150ma min .. or you can use a tester

**Comment by shirish47** [comment]
thanks ..I mean't those set in this library ... But we later found the setting git..

**Comment by asetyde** [comment]
ook

**Comment by igrr** [comment]
@shirish47 so is this question resolved for you? If so, could you please mark it closed?
