### ISSUE TITLE
rror compiling for board NodeMCU 1.0 (ESP-12E Module).

### ISSUE THREAD

**Issue by kentachiri** [esp8266/Arduino#8729]
Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Serial1, None, Only Sketch, 115200"

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\hardware -hardware C:\Users\lenovo\Documents\ArduinoData\packages -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\tools-builder -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\hardware\tools\avr -tools C:\Users\lenovo\Documents\ArduinoData\packages -built-in-libraries C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\libraries -libraries C:\Users\lenovo\Documents\Arduino\libraries -fqbn=esp8266:esp8266:nodemcuv2:xtal=80,vt=flash,exception=disabled,stacksmash=disabled,ssl=all,mmu=3232,non32xfer=fast,eesz=4M2M,led=2,ip=lm2f,dbg=Serial1,lvl=None____,wipe=none,baud=115200 -vid-pid=1A86_7523 -ide-version=10819 -build-path C:\Users\lenovo\AppData\Local\Temp\arduino_build_78708 -warnings=none -build-cache C:\Users\lenovo\AppData\Local\Temp\arduino_cache_985655 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.python3.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\python3\3.7.2-post1 -prefs=runtime.tools.python3-3.7.2-post1.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\python3\3.7.2-post1 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.4-gcc10.3-1757bed -prefs=runtime.tools.xtensa-lx106-elf-gcc-3.0.4-gcc10.3-1757bed.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.4-gcc10.3-1757bed -prefs=runtime.tools.mklittlefs.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\mklittlefs\3.0.4-gcc10.3-1757bed -prefs=runtime.tools.mklittlefs-3.0.4-gcc10.3-1757bed.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\mklittlefs\3.0.4-gcc10.3-1757bed -prefs=runtime.tools.mkspiffs.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\mkspiffs\3.0.4-gcc10.3-1757bed -prefs=runtime.tools.mkspiffs-3.0.4-gcc10.3-1757bed.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\mkspiffs\3.0.4-gcc10.3-1757bed -verbose C:\Users\lenovo\Documents\Arduino\sketch_nov24a\sketch_nov24a.ino

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\arduino-builder -compile -logger=machine -hardware C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\hardware -hardware C:\Users\lenovo\Documents\ArduinoData\packages -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\tools-builder -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\hardware\tools\avr -tools C:\Users\lenovo\Documents\ArduinoData\packages -built-in-libraries C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\libraries -libraries C:\Users\lenovo\Documents\Arduino\libraries -fqbn=esp8266:esp8266:nodemcuv2:xtal=80,vt=flash,exception=disabled,stacksmash=disabled,ssl=all,mmu=3232,non32xfer=fast,eesz=4M2M,led=2,ip=lm2f,dbg=Serial1,lvl=None____,wipe=none,baud=115200 -vid-pid=1A86_7523 -ide-version=10819 -build-path C:\Users\lenovo\AppData\Local\Temp\arduino_build_78708 -warnings=none -build-cache C:\Users\lenovo\AppData\Local\Temp\arduino_cache_985655 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.python3.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\python3\3.7.2-post1 -prefs=runtime.tools.python3-3.7.2-post1.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\python3\3.7.2-post1 -prefs=runtime.tools.xtensa-lx106-elf-gcc.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.4-gcc10.3-1757bed -prefs=runtime.tools.xtensa-lx106-elf-gcc-3.0.4-gcc10.3-1757bed.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\xtensa-lx106-elf-gcc\3.0.4-gcc10.3-1757bed -prefs=runtime.tools.mklittlefs.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\mklittlefs\3.0.4-gcc10.3-1757bed -prefs=runtime.tools.mklittlefs-3.0.4-gcc10.3-1757bed.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\mklittlefs\3.0.4-gcc10.3-1757bed -prefs=runtime.tools.mkspiffs.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\mkspiffs\3.0.4-gcc10.3-1757bed -prefs=runtime.tools.mkspiffs-3.0.4-gcc10.3-1757bed.path=C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\tools\mkspiffs\3.0.4-gcc10.3-1757bed -verbose C:\Users\lenovo\Documents\Arduino\sketch_nov24a\sketch_nov24a.ino

Using board 'nodemcuv2' from platform in folder: C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.2

Using core 'esp8266' from platform in folder: C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.2

Detecting libraries used...

"C:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/include" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/lwip2/include" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\\Users\\lenovo\\AppData\\Local\\Temp\\arduino_build_78708/core" -c -w -Werror=return-type -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -w -x c++ -E -CC -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DDEBUG_ESP_PORT=Serial1 -DARDUINO=10819 -DARDUINO_ESP8266_NODEMCU_ESP12E -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU_ESP12E\"" -DLED_BUILTIN=2 -DFLASHMODE_DIO -DESP8266 "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\cores\\esp8266" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\variants\\nodemcu" "C:\\Users\\lenovo\\AppData\\Local\\Temp\\arduino_build_78708\\sketch\\sketch_nov24a.ino.cpp" -o nul

Alternatives for ESP8266WiFi.h: [ESP8266WiFi@1.0]

ResolveLibrary(ESP8266WiFi.h)

  -> candidates: [ESP8266WiFi@1.0]

"C:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/include" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/lwip2/include" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\\Users\\lenovo\\AppData\\Local\\Temp\\arduino_build_78708/core" -c -w -Werror=return-type -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -w -x c++ -E -CC -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DDEBUG_ESP_PORT=Serial1 -DARDUINO=10819 -DARDUINO_ESP8266_NODEMCU_ESP12E -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU_ESP12E\"" -DLED_BUILTIN=2 -DFLASHMODE_DIO -DESP8266 "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\cores\\esp8266" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\variants\\nodemcu" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\libraries\\ESP8266WiFi\\src" "C:\\Users\\lenovo\\AppData\\Local\\Temp\\arduino_build_78708\\sketch\\sketch_nov24a.ino.cpp" -o nul

Alternatives for SPI.h: [SPI@1.0]

ResolveLibrary(SPI.h)

  -> candidates: [SPI@1.0]

"C:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/include" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/lwip2/include" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\\Users\\lenovo\\AppData\\Local\\Temp\\arduino_build_78708/core" -c -w -Werror=return-type -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -w -x c++ -E -CC -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DDEBUG_ESP_PORT=Serial1 -DARDUINO=10819 -DARDUINO_ESP8266_NODEMCU_ESP12E -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU_ESP12E\"" -DLED_BUILTIN=2 -DFLASHMODE_DIO -DESP8266 "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\cores\\esp8266" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\variants\\nodemcu" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\libraries\\ESP8266WiFi\\src" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\libraries\\SPI" "C:\\Users\\lenovo\\AppData\\Local\\Temp\\arduino_build_78708\\sketch\\sketch_nov24a.ino.cpp" -o nul

Alternatives for Wire.h: [Wire@1.0]

ResolveLibrary(Wire.h)

  -> candidates: [Wire@1.0]

"C:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/include" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/lwip2/include" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\\Users\\lenovo\\AppData\\Local\\Temp\\arduino_build_78708/core" -c -w -Werror=return-type -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -w -x c++ -E -CC -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DDEBUG_ESP_PORT=Serial1 -DARDUINO=10819 -DARDUINO_ESP8266_NODEMCU_ESP12E -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU_ESP12E\"" -DLED_BUILTIN=2 -DFLASHMODE_DIO -DESP8266 "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\cores\\esp8266" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\variants\\nodemcu" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\libraries\\ESP8266WiFi\\src" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\libraries\\SPI" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\libraries\\Wire" "C:\\Users\\lenovo\\AppData\\Local\\Temp\\arduino_build_78708\\sketch\\sketch_nov24a.ino.cpp" -o nul

Alternatives for Adafruit_GFX.h: [Adafruit-GFX-Library-master@1.11.3]

ResolveLibrary(Adafruit_GFX.h)

  -> candidates: [Adafruit-GFX-Library-master@1.11.3]

"C:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -D_GNU_SOURCE "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/include" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/lwip2/include" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\\Users\\lenovo\\AppData\\Local\\Temp\\arduino_build_78708/core" -c -w -Werror=return-type -Os -g -free -fipa-pta -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++17 -ffunction-sections -fdata-sections -fno-exceptions -DMMU_IRAM_SIZE=0x8000 -DMMU_ICACHE_SIZE=0x8000 -w -x c++ -E -CC -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DDEBUG_ESP_PORT=Serial1 -DARDUINO=10819 -DARDUINO_ESP8266_NODEMCU_ESP12E -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_NODEMCU_ESP12E\"" -DLED_BUILTIN=2 -DFLASHMODE_DIO -DESP8266 "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\cores\\esp8266" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\variants\\nodemcu" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\libraries\\ESP8266WiFi\\src" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\libraries\\SPI" "-IC:\\Users\\lenovo\\Documents\\ArduinoData\\packages\\esp8266\\hardware\\esp8266\\3.0.2\\libraries\\Wire" "-IC:\\Users\\lenovo\\Documents\\Arduino\\libraries\\Adafruit-GFX-Library-master" "C:\\Users\\lenovo\\AppData\\Local\\Temp\\arduino_build_78708\\sketch\\sketch_nov24a.ino.cpp" -o nul

Alternatives for Adafruit_I2CDevice.h: []

ResolveLibrary(Adafruit_I2CDevice.h)

  -> candidates: []

In file included from C:\Users\lenovo\Documents\Arduino\sketch_nov24a\sketch_nov24a.ino:4:

C:\Users\lenovo\Documents\Arduino\libraries\Adafruit-GFX-Library-master/Adafruit_GFX.h:12:10: fatal error: Adafruit_I2CDevice.h: No such file or directory

   12 | #include <Adafruit_I2CDevice.h>

      |          ^~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

Using library ESP8266WiFi at version 1.0 in folder: C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WiFi 

Using library SPI at version 1.0 in folder: C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.2\libraries\SPI 

Using library Wire at version 1.0 in folder: C:\Users\lenovo\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.2\libraries\Wire 

Using library Adafruit-GFX-Library-master at version 1.11.3 in folder: C:\Users\lenovo\Documents\Arduino\libraries\Adafruit-GFX-Library-master 

exit status 1

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

Invalid library found in C:\Users\lenovo\Documents\Arduino\libraries\folder: no headers files (.h) found in C:\Users\lenovo\Documents\Arduino\libraries\folder

**Comment by mcspr** [comment]
> 12 | #include <Adafruit_I2CDevice.h>
>
>  |          ^~~~~~~~~~~~~~~~~~~~~~

Install I2CDevice lib?
