### ISSUE TITLE
Can I access pending UDP incoming packets ?

### ISSUE THREAD

**Issue by penfold42** [esp8266/Arduino#875]
In driving ws2812s and want to drop any pending update frames andnjustbgrab the most recent one.

Is there any way to access the pending packets queue ?

**Comment by igrr** [comment]
Using WiFiUDP class, I suppose no. Just allocate a buffer and dump packets into it one by one. When done, you will have the latest packet in buffer.

**Comment by far5893** [comment]
penfold42 do you have a place to describe your work ? 
I would like to create some xmas effects and i'm starting work maybe similar to yours.
