### ISSUE TITLE
Is there a way to get Arduino IDE to pass --host_port (-p) to espota.py?

### ISSUE THREAD

**Issue by sprior** [esp8266/Arduino#8750]
### Discussed in https://github.com/esp8266/Arduino/discussions/8749

<div type='discussions-op-text'>

<sup>Originally posted by **sprior** December  8, 2022</sup>
I recently set up a VLAN for my IOT devices so they live in a more secure network with a pfSense firewall between my development laptop and the devices.  I am trying to restrict what port connections are allowed between the two networks.
I have set up a MDNS bridge between the networks so in the Arduino IDE I can see the esp8266 devices as available network ports.

What I have discovered is that the espota.py tool requires the esp8266 device to connect back to it on a host port and by default that port is random between 10000 and 60000.  This works great when everything is on the same network, but in a firewall situation would require quite a large port range to be opened.  espota.py does take a --host_port (-p) option to specify the port which seems promising, but I haven't found any way to configure the Arduino IDE to invoke espota.py with that option specified.

As a temporary hack in the 
group.add_option("-P", "--host_port",
section I replaced the default = random.randint(10000, 60000) with a default = <port of my choosing>
but I dislike this option because it'll go away when I update.

Is there anywhere less fragile where I could set this as a preference?</div>

**Comment by mcspr** [comment]
either by changing platform.txt directly, or placing platform.local.txt near it
https://arduino.github.io/arduino-cli/0.31/platform-specification/#platformlocaltxt

same thing as script modification, though, as we can't control multiple Cores at once
maybe some time in the future, through [sketch project file](https://arduino.github.io/arduino-cli/0.31/sketch-project-file/) or some other way that uses files in user-controlled directories

or, using arduino-cli `--build-property` outside of IDE
https://arduino.github.io/arduino-cli/0.31/commands/arduino-cli_compile/

`tools.esptool.upload.network_pattern` is the main cmdline
https://github.com/esp8266/Arduino/blob/210897ef83305496947c4e73c937bab52a33cb48/platform.txt#L183

`tools.esptool.network_cmd` is just python3 alias
https://github.com/esp8266/Arduino/blob/210897ef83305496947c4e73c937bab52a33cb48/platform.txt#L172
