### ISSUE TITLE
snprintf_P uses printf and doesn't honor size limits

### ISSUE THREAD

**Issue by mamama1** [esp8266/Arduino#8767]
Hi

in the current core 3.0.2 snprintf_P seems to just use printf and also seems to discard things like size limit strSize:
`int     snprintf_P(char *str, size_t strSize, PGM_P formatP, ...) __attribute__((format(printf, 3, 4)));`

How is this different from using snprintf then? The documentation clearly says to use snprintf_P for PROGMEM strings, as only with that it is guaranteed that reading is 4 byte aligned. However I can't see that happening anywhere.
[](https://arduino-esp8266.readthedocs.io/en/latest/PROGMEM.html)

Please clarify whether the documentation is incorrect or whether I am misunderstanding the code...?

Thanks

**Comment by earlephilhower** [comment]
You''re misunderstanding the code.

This is the prototype with an attribute telling GCC that some params look like printf format strings to it can check your string and passed in params match. The implementation is in Newlib and should take care of len/etc. as expected.
