### ISSUE TITLE
How to access raw POST request content

### ISSUE THREAD

**Issue by Diaoul** [esp8266/Arduino#878]
Sorry if this is a dumb question I couldn't find any mention of this in the docs or examples.
Using ESP8266WebServer, I want to process the raw content of an incoming POST request.

Is that possible?
##

**Comment by Duality4Y** [comment]
How do you meen the raw content of the POST request ?

**Comment by Diaoul** [comment]
Well, the data POST, after the headers. I'm not using `application/x-www-form-urlencoded` but json.

**Comment by Diaoul** [comment]
After digging in the source code of the library I found the answer, raw content is considered as an argument named "plain".

I leave the issue open because this is quite unusual and should be documented somewhere.

**Comment by me-no-dev** [comment]
what do you think is the proper way to do it?

**Comment by Diaoul** [comment]
RFC defines the content of a request as the "message-body" (see https://tools.ietf.org/html/rfc7230#section-3)
I think "content" is also a good name and is used in the popular python library [requests](http://docs.python-requests.org/en/latest/user/quickstart/#response-content)

**Comment by me-no-dev** [comment]
I vote for "messageBody" :) or just "body"

**Comment by marvinroger** [comment]
I also vote for `body`, the message part is implicit. It is also a name used by popular libraries, like the `request` module in Node.js

**Comment by dave-prosee** [comment]
Another vote for getting this documented. Thanks for posting the issue and your findings; it helped me.

**Comment by tinxx** [comment]
This issue can be closed. The documentation is available in the [README](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/README.rst).

> ``arg`` - get request argument value, use ``arg("plain")`` to get POST body
