### ISSUE TITLE
Code working in 3.0.2 not working in 3.1.0 or 3.1.1

### ISSUE THREAD

**Issue by NaezT** [esp8266/Arduino#8824]
#### Platform

- Hardware:				 other
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE| 
- Operating System:		[Windows| 

### Settings in IDE

- Module:  			[Generic ESP8266 Module|
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB/ 
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description
Noob here.

I have copied some code from this link , which compiles aand runs fine in 3.0.2 - but it throws an error in both 3.1.0 and 3.1.1 
I added the row number that always starts the error, it seem to be when creating the new instance.
There might be a new  mothod for this , I'll check in the documentation....

https://www.survivingwithandroid.com/invoke-https-rest-json-api-esp8266/

Code and error is below: 

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

`

````
String rest_query(char* question){
  Serial.println("Connecting to the HTTP server....");
 row 112 **### std::unique_ptr<BearSSL::WiFiClientSecure>client(new BearSSL::WiFiClientSecure);**
  client->setInsecure();
  
  char apiURL[1024];
  const char* query = question;
  Serial.println("Building URL...");
  sprintf(apiURL, "%s/%s", server, query);
  Serial.printf("API URL=%s \r\n",apiURL);

if (http.begin(*client, apiURL)) {
    Serial.println("Connected");
    http.addHeader("Accept", "application/json");
    http.addHeader("Ocp-Apim-Subscription-Key", API_KEY);
    int code = http.GET();
    Serial.printf("HTTP Code [%d]", code);
    if (code > 0) {
      if (code == HTTP_CODE_OK || code == HTTP_CODE_MOVED_PERMANENTLY) {
        Serial.println("GET OK");
        String payload = http.getString();
        Serial.println(payload);
        Serial.println("...JSON..");
        return payload;
      }
    }
    else {
      Serial.printf("[HTTP] GET... failed, error: %s", http.errorToString(code).c_str());
         }
}
}
````

### Debug Messages
````
C:\Users\krister\Documents\Arduino\nodeMCU-hisingsbro\nodeMCU-hisingsbro.ino:112:81: error: control reaches end of non-void function [-Werror=return-type]
  112 |   std::unique_ptr<BearSSL::WiFiClientSecure>client(new BearSSL::WiFiClientSecure);
      |                                                                                 ^
cc1plus.exe: some warnings being treated as errors

exit status 1

Compilation error: control reaches end of non-void function [-Werror=return-type]

````

**Comment by earlephilhower** [comment]
The code you snipped is in error and should be fixed.  The compiler warning is that "control reaches end of non-void function" which is the case on the `else` bit of either `if` condition.

You should return an appropriate value in that case, or the compiler generated code's behavior is undefined (as in crash or do other unexpected things).
