### ISSUE TITLE
ESP8266WebServer streamFile() with File32

### ISSUE THREAD

**Issue by TheNitek** [esp8266/Arduino#8835]
#### Platform

- Hardware:				Espressif 8266 (4.1.0) > NodeMCU 1.0 (ESP-12E Module)
- Core Version:			framework-arduinoespressif8266 @ 3.30101.0 (3.1.1)
- Development Env:		Platformio
- Operating System:		Windows

### Problem Description

With 3.0.x I used to use ESP8266WebServer.streamFile() in combination with SdFat to provide file downloads from an SD card.
With 3.1.1 this fails to compile:
```
In member function 'size_t esp8266webserver::ESP8266WebServerTemplate<ServerType>::streamFile(T&, const String&, HTTPMethod) [with T = File32; ServerType = WiFiServer]',
    inlined from 'bool ShelfWeb::_loadFromSdCard(const char*)' at C:\Users\Nitek\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WebServer\src/ESP8266WebServer.h:225:22:
C:\Users\Nitek\.platformio\packages\framework-arduinoespressif8266\libraries\ESP8266WebServer\src/ESP8266WebServer.h:233:20: error: call to 'StreamFile<FatFile, unsigned int>::name' declared with attribute error: use getName(name, size)
  233 |     _streamFileCore(file.size(), file.name(), contentType);
```
Isn't streamFile supposed to work with File32?

### Sketch

```cpp

ESP8266WebServer _server;
SdFat _SD;

File32 dataFile = _SD.open(path);
if (_server.streamFile(dataFile, F("application/octet-stream")) != dataFile.size()) {
 Serial.println(F("Sent less data than expected!"));
}
dataFile.close();
```

**Comment by earlephilhower** [comment]
The Core libraries only work with this Arduino Core's `File` implementation, not the internal SdFat ones.  They have a different API, etc.

Check out the SDFS filesystem which wraps the SdFat internals, and returns a `File` object that the core can work with.  You could also look at the SD library/filesystem as well which also wraps the SdFat lib in an old-style Arduino compatible way.
