### ISSUE TITLE
Arduino uses the stock Wire.h library instead of the ESP8266 Version

### ISSUE THREAD

**Issue by karpour** [esp8266/Arduino#885]
Arduino 1.6.5, latest staging version.
Arduino prefers using the stock Wire.h even when Board is set to ESP8266. Not sure if this is an Arduino issue or if there is anything additional to do to convince Arduino to use the ESP8266 library.

**Comment by roccomuso** [comment]
Do you think this could be related to the issue i'm currently having: https://github.com/esp8266/Arduino/issues/887 ?

**Comment by pgollor** [comment]
Do you have a other library namend Wire in your library dir in your sketch workspace?

This could be the Problem. If i remember correctly, arduino prefers the library in your sketchfolder.

**Comment by igrr** [comment]
@karpour please enable verbose compiler output in Arduino preferences and paste the whole output. First few lines should tell us what's wrong with your setup.
