### ISSUE TITLE
Incorrect lwIP_w5100 library name in library.properties?

### ISSUE THREAD

**Issue by blue-wind-25** [esp8266/Arduino#8878]
In this file:
https://github.com/esp8266/Arduino/blob/master/libraries/lwIP_w5100/library.properties

I found:
name=lwIP_w5500

Should not it be:
name=lwIP_w5100

Thank you.

**Comment by d-a-v** [comment]
Thanks for the report, fix will be shipped in next release

**Comment by blue-wind-25** [comment]
You are welcome.
