### ISSUE TITLE
I am still getting errors trying to compile this ESP8266 library on Arduino UNO

### ISSUE THREAD

**Issue by adamsstephen** [esp8266/Arduino#8895]
Updated board manager to ESP8266 to 3.1.2
Still using ESP8266wifi.h produces the error 
"In file included from C:\Users\stephen\Documents\Arduino\Android_Arduino_webserver\Android_Arduino_webserver.ino:5:0:
C:\Users\stephen\Documents\Arduino\libraries\ESP8266WiFi\src/ESP8266WiFi.h:28:10: fatal error: wl_definitions.h: No such file or directory
 #include <wl_definitions.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Uno.
"
You previously stated this library is not for Arduino UNO, so my question is what library should be used for esp8266 (ESP01) boards connected via software serial port to a Arduino UNO?
This software is often quoted in documentation such as https://arduino-esp8266.readthedocs.io/en/3.1.2/esp8266wifi/soft-access-point-class.html#softap
and it uses exactly the same setup a Arduino connected via serial port to the ESP8266 board.
I need to use the library facilities such as server, client etc in the sketch.

**Comment by d-a-v** [comment]
> ` Error compiling for board Arduino Uno.`

Do not try so select the UNO board when flashing the esp8266. This will never work.

Two options
- If not already done, flash an "AT firmware" in the esp8266 ([example](https://robertoostenveld.nl/esp8266-at-firmware/)) (and by that stop using esp8266/Arduino)
  and on your UNO use for example [this library](https://github.com/JAndrassy/WiFiEspAT)
- Port & flash your UNO sketch into your esp8266/Arduino
