### ISSUE TITLE
Extract WiFi.localIP() and assign to a string - Help needed

### ISSUE THREAD

**Issue by championc** [esp8266/Arduino#8897]
I'm sure this is stupidly simple to do, but I can't figure it out.  As the subject says, I have an Oled board and I am getting an address by DHCP and I simply want to display the IP address on the mini screen.

So the logic is simply
myipaddress = WiFi.localIP();
updateOLED("NULL", "NULL", "NULL", myipaddress);

but clearly I don't have the syntax correct at all.  I know that I need to declare "myipaddress", but as a char or String ?

Sorry, I'm a noob, so unfamiliar with this programming language

Thanks in advance

**Comment by mcspr** [comment]
https://github.com/esp8266/Arduino/blob/01d1c8e46f96d37d3597e6ce296cca37567a7030/cores/esp8266/IPAddress.h#L137

Check out IDE 2.0, you'll have a better idea which arguments go where and what type they are
