### ISSUE TITLE
Undefined reference to static members and functions

### ISSUE THREAD

**Issue by Webbly25** [esp8266/Arduino#8898]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:					ESP-12
- Core Version:			3.1.1
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			Nodemcu
- Flash Size: 		4MB
- Flash Frequency:	40Mhz
- CPU Frequency:		80Mhz
- Upload Using:		OTA|

### Problem Description

Whenever I use any static members or functions I get an error from `xtensa-lx106-elf/bin/ld.exe`, saying there is an `undefined reference to '_ZN11MySingleton9_instanceE'`

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

sketch.ino
```cpp

#include <Arduino.h>
#include "mySingleton.h"

MySingleton *singleton = MySingleton::getInstance();

void setup()
{
	// put your setup code here, to run once:
	Serial.begin(115200);
}

```
mySingleton.h
```cpp
#ifndef MY_SINGLETON_H
#define MY_SINGLETON_H

#include <Arduino.h>

class MySingleton;

class MySingleton
{
private:
	static MySingleton *_instance;

	MySingleton() = default;

public:
	static MySingleton *getInstance();

	MySingleton(const MySingleton &) = delete; // no copying
	MySingleton &operator=(const MySingleton &) = delete;
};

#endif
```
mySingleton.cpp
```cpp

#include "mySingleton.h"

MySingleton *MySingleton::getInstance()
{
	if (!_instance)
	{
		_instance = new MySingleton();
	}

	return _instance;
}
```

### Debug Messages

```
c:/users/ryan/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.1.0-gcc10.3-e5f9fec/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Ryan\AppData\Local\Temp\arduino\sketches\2543C2B7B00BE1FEF187904ECE9F5797\sketch\mySingleton.cpp.o:(.text._ZN11MySingleton11getInstanceEv+0x0): undefined reference to `_ZN11MySingleton9_instanceE'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1
```

**Comment by d-a-v** [comment]
Your code is missing `MySingleton::MySingleton* _instance;` in `mySingleton.cpp`, like a global variable declaration.
