### ISSUE TITLE
package_esp8266com_index.json incorrect URL specified for ESPtool

### ISSUE THREAD

**Issue by jkennard** [esp8266/Arduino#890]
The json file for loading the ESP8266 board is incorrect (http://arduino.esp8266.com/stable/package_esp8266com_index.json). The url for IGRR's ESPtool is https://github.com/igrr/esptool-ck/releases/download/0.4.5/esptool-0.4.5-win32.zip but it should be https://github.com/igrr/esptool-ck/releases/tag/0.4.5/esptool-0.4.5-win32.zip

**Comment by lrmoreno007** [comment]
Read again it...
https://github.com/esp8266/Arduino/blob/esp8266/README.md

**Comment by pgollor** [comment]
I think https://github.com/igrr/esptool-ck/releases/download/0.4.5/esptool-0.4.5-win32.zip is correct.

**Comment by igrr** [comment]
releases/download/<tag>/<file> works for me.
@jkennard could you please elaborate why do you think this is the wrong one?
