### ISSUE TITLE
esp8266 doesnt connect to socket.io server (Nodejs)

### ISSUE THREAD

**Issue by marwan211** [esp8266/Arduino#8937]
### Basic Infos

- [X ] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X ] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ X] I have tested that the issue is present in current master branch (aka latest git).
- [X ] I have searched the issue tracker for a similar issue.
- [ X] If there is a stack dump, I have decoded it.
- [ X] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-12|ESP-01|ESP-07|ESP8285 device|other]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE|Platformio|Make|other]
- Operating System:		[Windows|Ubuntu|MacOS]

### Settings in IDE

- Module:  			[ESP-12E module]
- Flash Mode:			[qio]
- Flash Size: 		[4MB]
- lwip Variant:   [v2|Higher Bandwidth]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

im trying to connect esp8266 to socket.io server , esp keep connecting and disconnecting and i tried all IwIp variants but still same issue, my server is working perfectly with react app

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp
#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>
#include <WebSocketsClient.h>
#include <Hash.h>

ESP8266WiFiMulti WiFiMulti;
WebSocketsClient webSocket;

#define USE_SERIAL Serial1

void webSocketEvent(WStype_t type, uint8_t *payload, size_t length) {
  switch (type) {
    case WStype_DISCONNECTED:
      Serial.println("[WSc] Disconnected!");
      break;
    case WStype_CONNECTED:
      {
        Serial.println("[WSc] Connected to url: " + String((char *)payload));

        // send message to server when Connected
        webSocket.sendTXT("Connected");
      }
      break;
    case WStype_TEXT:
      Serial.println("[WSc] get text: " + String((char *)payload));

      // send message to server
      // webSocket.sendTXT("message here");
      break;
    case WStype_BIN:
      Serial.println("[WSc] get binary length: " + String(length));
      hexdump(payload, length);

      // send data to server
      // webSocket.sendBIN(payload, length);
      break;
  }
}

void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.println();
  Serial.println();
  Serial.println("starting");

  for (uint8_t t = 4; t > 0; t--) {
    Serial.printf("[SETUP] BOOT WAIT %d...\n", t);
    Serial.flush();
    delay(1000);
  }

  WiFiMulti.addAP("ssid","passpass");

  while (WiFiMulti.run() != WL_CONNECTED) {
    Serial.println("not connected");
    delay(100);
  }

  if (WiFi.status() == WL_CONNECTED) {
    Serial.println("Connected to the internet.");
  } else {
    Serial.println("Not connected to the internet.");
  }

  webSocket.beginSSL("iot-test-l3vv.onrender.com", 10000);
  webSocket.onEvent(webSocketEvent);
}

void loop() {
  webSocket.loop();
}


```

### Debug Messages

```
Debug messages go here
```

**Comment by mcspr** [comment]
From our side, the failure *may* be from beginSSL. I'd start by checking whether insecure version works first.
Some logs might also help, server or client side.

Please re-open if this still a problem, but I'd suggest to go to https://github.com/Links2004/arduinoWebSockets/issues first
