### ISSUE TITLE
python3 Parameters are incorrect?

### ISSUE THREAD

**Issue by JTzLinux** [esp8266/Arduino#8945]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [X] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [X] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:			LOLIN D1
- Core Version:			3.1.1
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			Wemos D1 mini r2
- Flash Mode:			other
- Flash Size: 		        Unknown
- lwip Variant:                   Unknown
- Reset Method:		Button on hw
- Flash Frequency:	        40Mhz?
- CPU Frequency:		80Mhz?
- Upload Using:		SERIAL
- Upload Speed:               115200

### Problem Description

When I try to upload it I receive that the parameters are incorrect 

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

void setup() {
  
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED_BUILTIN, HIGH);  // turn the LED on (HIGH is the voltage level)
  delay(1000);                      // wait for a second
  digitalWrite(LED_BUILTIN, LOW);   // turn the LED off by making the voltage LOW
  delay(1000);                      // wait for a second
}

```

### Debug Messages

```

fork/exec C:\Users\Admin\AppData\Local\Arduino15\packages\esp8266\tools\python3\3.7.2-post1/python3.exe: The parameter is incorrect.

Compilation error: fork/exec C:\Users\Admin\AppData\Local\Arduino15\packages\esp8266\tools\python3\3.7.2-post1/python3.exe: The parameter is incorrect.
```

**Comment by JTzLinux** [comment]
Had to downgrade from 3.X.X to 2.X.X

**Comment by mcspr** [comment]
> Had to downgrade from 3.X.X to 2.X.X

> 3.1.1

What about 3.1.2 aka latest version?

**Comment by JTzLinux** [comment]
Same jizz aka same error
   Am Sonntag, 18. Juni 2023 um 07:49:50 MESZ hat Max Prokhorov ***@***.***> Folgendes geschrieben:  
 
 



Had to downgrade from 3.X.X to 2.X.X



3.1.1


What about 3.1.2 aka latest version?

**Comment by JTzLinux** [comment]
no only what i wrote came back

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mcspr** [comment]
Win+R - C:\Users\Admin\AppData\Local\Arduino15\packages\esp8266\tools\python3\3.7.2-post1\python3.exe does work though?

Is it portable IDE, Microsoft Store, or globally installed one? 1.x or 2.x?
Antivirus / 'security' sw interfering, maybe?
