### ISSUE TITLE
esp8266 doesnt work after the code is uploaded

### ISSUE THREAD

**Issue by retrojokerr** [esp8266/Arduino#8946]
Pretty much the title. I have tried uploading all example codes such as blinking code, print ip address code but it just doesnt work. While any code is being uploaded it blinks but after the upload is completed it totally shuts off. Is my esp8266 faulty?

**Comment by mcspr** [comment]
Try changing flash mode to dout?

See our troubleshooting guides first? We have no idea with zero context provided
https://arduino-esp8266.readthedocs.io/en/latest/faq/readme.html

Plus, whatever debug messages rom bootloader and our own might be of interest. Switch to 74880 baud speed in terminal and watch what happens on boot
https://docs.espressif.com/projects/esptool/en/latest/esp8266/esptool/serial-connection.html#serial-port-settings
