### ISSUE TITLE
nodemcu esp8266 uploading timeout

### ISSUE THREAD

**Issue by moeinrahimi** [esp8266/Arduino#8965]
#### Platform

- Hardware:					nodemcu esp8266
- Core Version:			ESP8266 CP2102
- Development Env:		Arduino IDE
- Operating System:		Windows 11 64bit

### Settings in IDE

- Module:  			nodemcu 1 esp 12e module
- Flash Mode:			[qio|dio|other]
- Flash Size: 		4MB
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		80Mhz
- Upload Using:		SERIAL
- Upload Speed:   115200

### Problem Description

hi i have a nodemcu esp
i downloaded driver from https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads and when I plug nodemcu I can confirm it is detected by windows
![image](https://github.com/esp8266/Arduino/assets/13715024/3cd9eecf-e903-4855-bdf4-0da21192236c)
program stuck in uploading part. it seems in process of uploading code. my code works because esp module led blinks but after getting error the led turns off

```cpp

#include <Arduino.h>

void setup()
{
    pinMode(D0, OUTPUT);
}
void loop()
{
    digitalWrite(D0, HIGH);
    delay(500);
    digitalWrite(D0, LOW);
    delay(500);
}

```

### Debug Messages

"C:\Users\moein\AppData\Local\Arduino15\packages\esp8266\tools\python3\3.7.2-post1/python3" -I "C:\Users\moein\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/upload.py" --chip esp8266 --port "COM3" --baud "115200" "" erase_region "0x3FC000" 0x4000 --before default_reset --after hard_reset write_flash 0x0 "C:\Users\moein\AppData\Local\Temp\arduino\sketches\B6425EC33532C935FD22A3D090A9F9EF/water_pump.ino.ino.bin"
esptool.py v3.0
Serial port COM3
Connecting........_____....._____....._____....._____....._____....._____....._____
A fatal esptool.py error occurred: Failed to connect to ESP8266: Timed out waiting for packet headerTraceback (most recent call last):
  File "C:\Users\moein\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/upload.py", line 72, in <module>
    os.remove(erase_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\moein\\AppData\\Local\\Temp\\tmphobjxgy5'

Failed uploading: uploading error: exit status 1
Debug messages go here
```

**Comment by mcspr** [comment]
Make sure you are actually uploading. Usually we do boot-to-upload switch automatically, but it can be done manually as well. Power the board on with GPIO0 connected to GND, and then disconnect them.

Usually can be verified with 74880 baud terminal before doing the usual build & upload
https://arduino-esp8266.readthedocs.io/en/latest/boards.html#boot-messages-and-modes

2nd error with PermissionError 32 is probably because of something inside of esptool missing file close() on errors. (Likely) unrelated, but something to note
