### ISSUE TITLE
What Dial Switch do in ESP8266-DEVKITC

### ISSUE THREAD

**Issue by ktauchathuranga** [esp8266/Arduino#8972]
guys,
I have ESP8266-DEVKITC dev board, and it has a dial switch. When I reached in documents, it said its for " Auto Download and Flow Control"
I don't know what that means, can someone please explain that to me?
i need detailed explanation...

![260636186-d97a7c26-8861-4bc4-8573-a120fe567382](https://github.com/esp8266/Arduino/assets/79928743/e113fa5e-8e3d-486f-9d25-b0d8556500fd)

**Comment by mcspr** [comment]
Already answered?
https://esp32.com/viewtopic.php?f=2&p=118528#p118565

> Auto download will enable RTS and DTR to reset and put the chip into download mode using software, similar to what all ESP32 boards do by default. Flow control will connect RTS and DTR from the USB-serial chip to the corresponding pins on the ESP8266 so you can do hardware handshaking for flow control.

So it is related to serial communication, 'UART RTS CTS flow control' might be a better search term for what and why. As for auto-download, this is what allows the board to reboot to bootloader and enter upload mode without fiddling with GPIO0, GND and RST pin manually.
