### ISSUE TITLE
ESPPerfectTime.cpp:7:10: fatal error: sntp-lwip2.h: No such file or directory

### ISSUE THREAD

**Issue by tutoduino** [esp8266/Arduino#8979]
I face a compilation issue using ESPPerfectTime on Generic ESP8266 Module on Arduino IDE

#include <ESPPerfectTime.h>

/home/tutoduino/Arduino/libraries/ESPPerfectTime/src/ESPPerfectTime.cpp:7:10: fatal error: sntp-lwip2.h: No such file or directory
    7 | #include <sntp-lwip2.h>
      |          ^~~~~~~~~~~~~~

**Comment by enjoyneering** [comment]
Arduino esp8266 can do this right out of the box, without any additional libraries - [NTP-TZ-DST.ino](https://github.com/esp8266/Arduino/blob/1a4663fbe8dca5ee3992aa7b0fc98794d956ac30/libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino)

**Comment by mcspr** [comment]
Right, see above

https://github.com/esp8266/Arduino/pull/7595 (40eb5747e4b7d3458e9406c3c446948bbffa767b) removed the file in question.

https://github.com/hunamizawa/ESPPerfectTime/issues/4 is the upstream issue

Patch *should* solve the build issue (but idk whether it works :), lib can skip some of the platform-specific code
```diff
diff --git a/src/ESPPerfectTime.cpp b/src/ESPPerfectTime.cpp
index edd65da..cc2dfee 100644
--- a/src/ESPPerfectTime.cpp
+++ b/src/ESPPerfectTime.cpp
@@ -3,9 +3,6 @@
 #include <stdlib.h>
 #include <sys/time.h>
 #include <time.h>
-#ifdef ESP8266
-#include <sntp-lwip2.h>
-#endif // ESP8266
 #ifdef ESP32
 #include <esp32-hal.h>
 #endif // ESP32
diff --git a/src/sntp_pt.cpp b/src/sntp_pt.cpp
index ffc1c02..acb5198 100644
--- a/src/sntp_pt.cpp
+++ b/src/sntp_pt.cpp
@@ -43,9 +43,6 @@
 #include <lwip/ip_addr.h>
 #include <lwip/timeouts.h>
 #include <lwip/udp.h>
-#ifdef ESP8266
-#include <sntp-lwip2.h>
-#endif // ESP8266
 #include "ESPPerfectTime.h"
 #include <sntp_pt.h>

@@ -851,4 +848,4 @@ set_update_delay(uint32 ms) {

 } // namespace pftime_sntp

-#undef PFTIME_DEBUG_LOG
\ No newline at end of file
+#undef PFTIME_DEBUG_LOG
```
