### ISSUE TITLE
By mistake I uninstalled CH341 driver from device manager in windows 11 and it is not detecting, but another ESP8266 connecting. Any Suggestions to detect that ESP.

### ISSUE THREAD

**Issue by bhanupro123** [esp8266/Arduino#8982]
By mistake I **uninstalled CH341 driver** from Device Manager in windows 11 and it is not detecting.
But when I inserted another ESP8266 it is detecting in Device Manager.
Any suggestions to detect that ESP.
or
is any other way to flash the code into ESP via Rx and Tx pins.

please guide me to make it workable.

Board: ESP8266
OS: Windows 11.

**All drivers like CH34X and CP210X Drivers are installed and another ESP is detecting.**

**Comment by mcspr** [comment]
See https://github.com/esp8266/Arduino/issues/3551 discussion at the end, make sure driver is correct one and actually installed for the device in question
Same discussion also has a bunch of links describing usb<->serial, /ch340/ would give you the idea of what to get for tx & rx connection without usb driving it
