### ISSUE TITLE
WiFi disconnected

### ISSUE THREAD

**Issue by LIN1JIARONG** [esp8266/Arduino#8993]
When I use ESP8266 as an access point,and connect iPhone to ESP8266's WiFi.Sometimes,iPhone woule disconnect WiFi,and usually connect to another WiFi，such as routers.Does anyone have the same question?

**Comment by ktauchathuranga** [comment]
maybe becuz ESP8266 AP don't have internet or signal strength is too low

**Comment by d-a-v** [comment]
You should check the serial console and verify it is not rebooting or any message related to your AP application.
Closing per not properly following the issue reporting instructions.
