### ISSUE TITLE
INARP - Implementation in lwip2

### ISSUE THREAD

**Issue by MoegerleS** [esp8266/Arduino#9015]
My application requires to resolve the IP adress via the MAC address by using Inverse ARP (INARP).

In order to implement this feature I need to modify the etharp.c file in lwip. 
In an older lwip 1.4 version I was already able to compile from lwip source and implement this functionality in the file. 
Where can I download the latest lwip2 source, so that I can modify the files? How can I build them for the arduino core?

**Comment by d-a-v** [comment]
Can you check this directory ?
https://github.com/esp8266/Arduino/tree/master/tools/sdk/lwip2

**Comment by MoegerleS** [comment]
Thanks for your help! I solved it.
