### ISSUE TITLE
lwip esp-ping noisy serial output

### ISSUE THREAD

**Issue by SteveRMann** [esp8266/Arduino#9049]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				All ESP, I have a library issue
- Core Version:			latest managed by Arduino IDE
- Development Env:		Arduino IDE
- Operating System:		Windows

### Settings in IDE

- Module:  			All ESP. The issue is in the core library
- Flash Mode:			qio
- Flash Size: 			All ESP. The issue is in the core library
- lwip Variant:
- Reset Method:
- Flash Frequency:
- CPU Frequency:
- Upload Using:
- Upload Speed:

### Problem Description

PLEASE make a quiet mode for the ping function.

I use ping to monitor the state of my local servers, but the debug output of ping clutters an already busy terminal screen.
PLEASE make a quiet mode that simply returns a Boolean true or false if the ping is successful or not.

I just want a simple response if the target is present or not:
if (Ping.ping(remote_ip) == 0){

I DO NOT want the library to print other unwanted data to my terminal:
"ping 5, timeout 0, total payload 160 bytes, 5098 ms"

If I want to see that, then it should be up to me, not the library.

**Comment by ACE1046** [comment]
Assign `sent_function` in `ping_option` structure and messages will go away.
