### ISSUE TITLE
Joy Stick using javascript

### ISSUE THREAD

**Issue by rickalex** [esp8266/Arduino#906]
we tried adding to a string and the size was outside the string limit 

then made several strings and when called asked for them to be added together 

nothing seems to work

does anyone have and idea ,  I can post the code or send it to you 

thanks much

**Comment by igrr** [comment]
Hi, please post a more detailed description of the issue you are having: code which you use, expected and observed behaviour, and steps to reproduce the issue.
If you are looking for coding help, please take this discussion to the esp8266.com forum, as this is off-topic here.
