### ISSUE TITLE
ESP8266 01 Spamming random characters after firmware update

### ISSUE THREAD

**Issue by itsosmx** [esp8266/Arduino#9063]
Hello, I'm trying to update my esp8266 to the latest version of firmware but as you see below it spamming and the model is flash like crazy i have tried a lot of version 
- ESP8266_NONOS_SDK-2.2.1
- ESP8266_NONOS_SDK-3.0.5

the only version that seems to work is the but this version is very old and does not support what I need to do.
- Ai-Thinker_ESP8266_DOUT_8Mbit_v1.5.4.1-a_20171130

also tried all Mode
- QIO
- DIO
- DOUT

![image](https://github.com/esp8266/Arduino/assets/49457438/6692d938-b0da-48c6-af23-10b1251f1626)
![image](https://github.com/esp8266/Arduino/assets/49457438/4f810ca9-8aef-45ce-b402-aefa45fc2e58)
![image](https://github.com/esp8266/Arduino/assets/49457438/32fbb04b-9e7e-4f4f-964f-4a78185d2212)

**Comment by mcspr** [comment]
[Check output w/ 74880 baudrate.](https://arduino-esp8266.readthedocs.io/en/latest/ideoptions.html#crystal-frequency)
Also note that this is esp8266 Arduino repo, not NONOS
