### ISSUE TITLE
 Certs.h file from example, free to use?

### ISSUE THREAD

**Issue by Jumbo125** [esp8266/Arduino#9066]
Hello
i use some esp8266 with some sensors.
most of them use http request to send datas. for the http request i need to include a certificat.
i found a certs.h in github and use this.

works great!!!
May i can use the Certs.h file from example?
can everyone can use it, is it free and avaible for all? or should i create a "own" certificate? i don't know how it works.

i use at the moment this certificat

thank you a lot

**Comment by d-a-v** [comment]
You shall not use these certificates.
[There are multiple warnings telling you not doing so](https://github.com/esp8266/Arduino/blob/d5eb265f78bff9deb7063d10030a02d021c8c66c/libraries/ESP8266WiFi/examples/BearSSL_ServerClientCert/BearSSL_ServerClientCert.ino#L50-L54).

While they are very valid for testing, using them exposes your application to anyone who knows where your source code comes from.

In the link above, there are instructions to generate your own certificates.
