### ISSUE TITLE
constant reboot of the microcontroller

### ISSUE THREAD

**Issue by 1MaxSpb** [esp8266/Arduino#9067]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [x] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.
Duplicate of #

#### Platform

- Hardware:					[ESP-12|ESP-01|ESP-07|**ESP8285 device**|other]
- Core Version:			2.7.4
- Development Env:		[**Arduino IDE**|Platformio|Make|other]
- Operating System:		[**Windows**|Ubuntu|MacOS]

### Settings in IDE

- Module:  			[Generic ESP8266 Module|**Wemos D1 mini r2**|Nodemcu|other]
- Flash Mode:			[qio|dio|other]
- Flash Size: 		[4MB/1MB]
- lwip Variant:   [v1.4|v2 Lower Memory|Higher Bandwidth]
- Reset Method:		[ck|nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz|160MHz]
- Upload Using:		[OTA|SERIAL]
- Upload Speed:   [115200|other] (serial upload only)

### Problem Description

constant reboot of the microcontroller

### [MCVE](https://stackoverflow.com/help/mcve) Sketch
```
#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include "GyverButton.h"
/////////////////// SETTINGS /////////////////////////////

// Wi-Fi
const char* ssid = "****";
const char* password = "*********";

// MQTT
const char* mqtt_server = "**.wqtt.ru";
const int mqtt_port = 000000;
const char* mqtt_user = "****";
const char* mqtt_password = "****";

//Button
const bool retain_flag = false;
#define BTN_PIN 8   // кнопка подключена сюда (BTN_PIN --- КНОПКА --- GND)
GButton butt1(BTN_PIN);
/////////////////////////////////////////////////////////


WiFiClient espClient;
PubSubClient client(espClient);
uint32_t tmr1;

void setup_wifi() {

  delay(10);
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);

  WiFi.mode(WIFI_STA);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}

void reconnect() {
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    String clientId = "ESP8266-" + WiFi.macAddress();
    if (client.connect(clientId.c_str(), mqtt_user, mqtt_password) ) {
      Serial.println("connected");
      
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      delay(5000);
    }
  }
}



void setup() {
  Serial.begin(115200);
  setup_wifi();
  client.setServer(mqtt_server, mqtt_port);
}

void loop() {
  if (!client.connected()) {
    reconnect();
  }
  client.loop();
  butt1.tick();  // обязательная функция отработки. Должна постоянно опрашиваться
  if (butt1.isSingle()) client.publish("button", "click", retain_flag);     // проверка на один клик
  if (butt1.isDouble()) client.publish("button", "double_click", retain_flag);     // проверка на двойной клик
  if (butt1.isTriple()) client.publish("button", "long_press", retain_flag);     // проверка на тройной клик

}

```

### Debug Messages

```
ets Jan  8 2013,rst cause:4, boot mode:(3,5)

wdt reset
load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld
```

**Comment by d-a-v** [comment]
`#define BTN_PIN 8`
This might be the issue.

Change it to a real GPIO (D8 is often GPIO15: use 15 or D8).

GPIO0 and GPIO2 must be 1 at boot
GPIO15 must be 0 at boot.
