### ISSUE TITLE
 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

### ISSUE THREAD

**Issue by sova32** [esp8266/Arduino#9122]
ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 3424, room 16 
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8 
tail 0
chksum 0x2b
csum 0x2b
v0004fc60
~ld
��n�r��n|�l�l`bbrl�nb�nl`�rl�l��
 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

**Comment by mcspr** [comment]
> ������n��r��n|�l�l��b���b�r��l�nb�n�l���r�l�l���

change baud rate?
