### ISSUE TITLE
Any idea, how to join open network with username/password via the http form? Usual in the hotels i.e.

### ISSUE THREAD

**Issue by robertgregor** [esp8266/Arduino#914]

**Comment by grahamehorner** [comment]
normally this is done with cookies; the proxy service hotels using look for a session cookie which if present allows traffic to be sent/received as it indicates a valid active session for the client.

**Comment by torntrousers** [comment]
I've an example of doing that [here](https://github.com/HarringayMakerSpace/IoT/blob/master/HygrometerOnceADay/HygrometerOnceADay.ino). That is for a BT FON logon in the UK, which wants an HTTPS POST with userid and password. It most likely wouldn't work exactly as-is for a non-BT FON system, but the code might give you something to start with. I think i used the HttpFox Firefox plugin to capture a browser logon to see what it did.

**Comment by igrr** [comment]
I honestly feel that esp8266.com forums are a better place for "how do I..." kind of questions. We have a whole subforum devoted to usage of ESP8266 with Arduino there, see http://esp8266.com/arduino.

**Comment by robertgregor** [comment]
Yes, you are right, this is only for submitting an issues and bugs. Sorry...
