### ISSUE TITLE
What's up with `WiFiClient::write()`? Why is it deprecated when there is no `Stream::sendHow()`?

### ISSUE THREAD

**Issue by everslick** [esp8266/Arduino#9149]
https://github.com/esp8266/Arduino/blob/685f2c97ff4b3c76b437a43be86d1dfdf6cb33e3/libraries/ESP8266WiFi/src/WiFiClient.h#L74

```
Arduino-ESP8266$ grep sendHow -r
libraries/ESP8266WiFi/src/WiFiClient.h:  [[ deprecated("use stream.sendHow(client...)") ]]
```

I'm confused. :-)

Should we just remove the `[[ deprecated("use stream.sendHow(client...)") ]]` line?

**Comment by igrr** [comment]
I think it refers to the various `send*` methods declared here: https://github.com/esp8266/Arduino/blob/685f2c97ff4b3c76b437a43be86d1dfdf6cb33e3/cores/esp8266/Stream.h#L197

**Comment by everslick** [comment]
oh. thanks. now I feel stupid. *LOL*
