### ISSUE TITLE
NTP using domain name, not IP

### ISSUE THREAD

**Issue by adrianrb** [esp8266/Arduino#915]
Hi all.

How use NTP using DNS?
NTP servers IPs changes sometimes...

Adrian

**Comment by AndyKirby** [comment]
Usually only if you are using the pool ntp servers.

It is customary on an internal network to run up the NTP service on
something that doesn't get turned off. Like ummm the DNS server or
something else that is providing your local infrastructure services. In
this case then the IP doesn't change. But that server can if needs be
use the pool NTP servers.

Local infrastructure services are something that should ideally be given
some serious thought for IoT work..... Especially when using lightweight
embedded wifi kit like the ESP. It is a very useful and inexpensive
device but it does have it's limitations and benefits greatly from being
helped along.

For my ESP devices I run a Raspberry Pi as the IoT/wifi gateway and put
all the necessary supporting services for the IoT network on there, so
DNS (Dynamic),DHCP(Updating the DNS so the esp units don't need to do
it),NTP, MQTT etc.

Admittedly if you want to run the ESP standalone you don't have the
benefit of a fully supporting infrastructure.


Kirbs


On 21/10/15 19:45, Adrian wrote:
>
> Hi all.
>
> How use NTP using DNS?
> NTP servers IPs changes sometimes...
>
> Adrian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/esp8266/Arduino/issues/915>.
>

-- 
andy@kirbyand.co.uk
www.kirbyand.co.uk

**Comment by adrianrb** [comment]
Yes, I want NTP by name...
Examples:
time.nist.gov, 
 a.st1.ntp.br,
c.st1.ntp.br,
d.st1.ntp.br,
a.ntp.br,
b.ntp.br,
c.ntp.br

Adrian

**Comment by adrianrb** [comment]
Perfect, Igrr! Tks!
But, there´s a problem with WiFi.hostByName that prevents to become stable?

**Comment by igrr** [comment]
hostByName works fine in stable. It's just the change to the sample sketch has been done after last stable release.
