### ISSUE TITLE
ethernet object does not have a dnsIP method.

### ISSUE THREAD

**Issue by nopnop2002** [esp8266/Arduino#9168]
### Basic Infos

- [x] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [x] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [x] I have tested that the issue is present in current master branch (aka latest git).
- [x] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [x] I have filled out all fields below.

#### Platform

- Hardware:				[ESP-12 device]
- Core Version:			[Core:3.1.2]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Wemos D1 mini r2]
- Flash Mode:			[qio]
- Flash Size: 		[4MB]
- lwip Variant:   [v1.4]
- Reset Method:		[nodemcu]
- Flash Frequency:	[40Mhz]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

The WiFi object has a dnsIP method.

The ethernet object does not have a dnsIP method.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include <SPI.h>
#include <ESP8266WiFi.h>
#include <W5500lwIP.h>
//#include <W5100lwIP.h>
//#include <ENC28J60lwIP.h>

#define CSPIN 16

Wiznet5500lwIP eth(CSPIN);
//Wiznet5100lwIP eth(CSPIN);
//ENC28J60lwIP eth(CSPIN);
byte mac[] = {0x00, 0xAA, 0xBB, 0xCC, 0xDE, 0x02};

void setup() {
  delay(1000);
  Serial.begin(115200);
  Serial.println();
  Serial.print(ESP.getFullVersion());
  Serial.println();

  SPI.begin();
  SPI.setBitOrder(MSBFIRST);
  SPI.setDataMode(SPI_MODE0);
  SPI.setFrequency(4000000);

  eth.setDefault(); // use ethernet for default route

  int present = eth.begin(mac);
  if (!present) {
    Serial.println("no ethernet hardware present");
    while(1);
  }
  
  Serial.print("connecting ethernet");
  while (!eth.connected()) {
    Serial.print(".");
    delay(1000);
  }
  Serial.println();
  Serial.print("ethernet ip address: ");
  Serial.println(eth.localIP());
  Serial.print("ethernet subnetMask: ");
  Serial.println(eth.subnetMask());
  Serial.print("ethernet gateway: ");
  Serial.println(eth.gatewayIP());
  Serial.println(eth.dnsIP());
}

void loop() {
  if (eth.status() == WL_CONNECTED) {
    //Serial.println("Ethernet Connected!");
  } else {
    Serial.println("Ethernet Not Connected!");
  }
  delay(1000);
}

```

### Debug Messages

```
\\LANDISK-HDL-AA1\disk1\Arduino\ESP8266_Ethernet\connectEthernet\connectEthernet.ino: In function 'void setup()':
connectEthernet:57:22: error: 'using Wiznet5500lwIP = class LwipIntfDev<Wiznet5500>' {aka 'class LwipIntfDev<Wiznet5500>'} has no member named 'dnsIP'
   57 |   Serial.println(eth.dnsIP());
      |                      ^~~~~
```

**Comment by JAndrassy** [comment]
it will be in the next version
https://github.com/esp8266/Arduino/blob/7e0d20e2b9034994f573a236364e0aef17fd66de/cores/esp8266/LwipIntfDev.h#L103
