### ISSUE TITLE
ESP32 WEBSERVER Home automation using relay

### ISSUE THREAD

**Issue by dheenaven** [esp8266/Arduino#9188]
i have one issue 
my project was home automation on esp32 by controlling webserver page using relay hardware  when i connect the mobile hotspot to control eps32 by web server page its working 
after some days hotspot are comnected esp32 but webserver page are not reached 
i use simple webserver program i put my mobile ip address after a time its not working properly

**Comment by JAndrassy** [comment]
this is the esp8266 Arduino platform's repository

**Comment by dheenaven** [comment]
yes
