### ISSUE TITLE
Type not complete

### ISSUE THREAD

**Issue by asetyde** [esp8266/Arduino#919]
![screen shot 2015-10-22 at 12 22 04](https://cloud.githubusercontent.com/assets/6162152/10662876/973b2848-78b7-11e5-8146-b03fe206d3e0.png)

Someone know in another issue and how correct it ?

**Comment by igrr** [comment]
The issue is due to the fact that ESP8266AVRISP.h doesn't have `#include <WiFiServer.h>`.
Add 
```cpp
#include <WiFiServer.h>
#include <WiFiClient.h>
```
into your sketch *before* `#include <ESP8266AVRISP.h>` as a workaround.

**Comment by asetyde** [comment]
thx !
