### ISSUE TITLE
Serial.available()  have a issue, its not able to return availiable bytes

### ISSUE THREAD

**Issue by The3ven** [esp8266/Arduino#9195]
### Basic Infos

- [X] This issue complies with the [issue POLICY doc](https://github.com/esp8266/Arduino/blob/master/POLICY.md).
- [X] I have read the documentation at [readthedocs](https://arduino-esp8266.readthedocs.io/en/latest) and the issue is not addressed there.
- [ ] I have tested that the issue is present in current master branch (aka latest git).
- [X] I have searched the issue tracker for a similar issue.
- [ ] If there is a stack dump, I have decoded it.
- [X] I have filled out all fields below.

#### Platform

- Hardware:					[ESP-07]
- Core Version:			[latest git hash or date]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]

### Settings in IDE

- Module:  			[Nodemcu v1.0 (ESP12E Module) ]
- Flash Mode:			[Not a Option]
- Flash Size: 		[4MB]
- lwip Variant:   [v2 Lower Memory]
- Reset Method:		[nodemcu]
- Flash Frequency:	[Not a Option]
- CPU Frequency:		[80Mhz]
- Upload Using:		[SERIAL]
- Upload Speed:   [115200] (serial upload only)

### Problem Description

Nodemcu `Serial.available();` function is not able to send total bytes available on serial it just send 1.

### [MCVE](https://stackoverflow.com/help/mcve) Sketch

```cpp

#include "Arduino.h"

void setup()
{
    Serial.begin(9600);
}

String tmp = "";

void loop()
{
    while (Serial.available() > 0)
    {
        Serial.println("data in buffer : ");
        Serial.print(Serial.available());
        Serial.println("\n");
        tmp = Serial.readString();
    }

    if (tmp.length() > 4)
    {
        Serial.println("Data : " + tmp);
        Serial.println("Data length : " + String(tmp.length()));
        Serial.flush();
        tmp = "";
    }
}

```

### Debug Messages

```
⸮R⸮⸮⸮⸮data in buffer : 
1

Data : hi hi hi

Data length : 10
⸮R⸮⸮⸮⸮R⸮⸮fgFj⸮data in buffer : 
1

Data : hihihih

Data length : 9

```

**Comment by mcspr** [comment]
> function is not able to send total bytes available on serial it just send 1.

does exactly what you have asked, though?
`tmp = readString()` **replaces** the whole string, perhaps you meant `+=`

**Comment by The3ven** [comment]
> > function is not able to send total bytes available on serial it just send 1.
> 
> does exactly what you have asked, though? `tmp = readString()` **replaces** the whole string, perhaps you meant `+=`

why should i append it?

i have to know all the available data, readString() from serial send all the data which is available on serial at the present time and empty the serial buffer, 

Now back to the available part before i get all the data from serial i wan to know the length and it says one but it got read 9 characters from the buffer, 

How??

if available told me there is only 1 character then how it read 9 characters from buffer??
