### ISSUE TITLE
which network to send UDP/TCP packet

### ISSUE THREAD

**Issue by grahamehorner** [esp8266/Arduino#926]
The ESP8266 can be both a client and an access point and as such can have two ip/subnets; how can I configure routing so the packet is set out on the correct network and reaches the destination.

**Comment by me-no-dev** [comment]
Packet should go out depending on the destination address. For the AP network, you can send only to the devices in the subnet (your clients), the rest should go through the STA network and it's gateway.
Is that what you are asking? What do you want to achieve? Some things can not run on the AP network, but that comes from espresif
