### ISSUE TITLE
Define replacements in static pages

### ISSUE THREAD

**Issue by robertgregor** [esp8266/Arduino#927]
Hello, is it possible to somehow serve the static pages like 
server.serveStatic("/st/", SPIFFS, "/");

But define in these static pages replacements strings like i.e. !!!user!!! and then the webserver will replace is with a variable, i.e.:
server.setStaticReplacement("!!!user!!!",user);
I think, this can be very handy....

Robert

**Comment by sticilface** [comment]
Yes.

Ive written a lib that does exactly this. Just last week and still ironing
out some stuff. I'll put an example up today. But it works well. Serves
dynamic pages in 100ms, doesn't use any heap really, 8 bytes per variable,
and uses a different method to get content length correctly so the client
closes the connection.

**Comment by sticilface** [comment]
Here you go
https://github.com/sticilface/HTTPPrinter/tree/master
