### ISSUE TITLE
Export compiled binary

### ISSUE THREAD

**Issue by dragonnn** [esp8266/Arduino#932]
I need to export my complied binary because I need to program many ESP from Rassberry PI from CMD. When I try export in Arduino IDE the binary it shows:

Warning: This core does not support exporting sketches. Please consider upgrading it or contacting its author

Not sure if it works and I don't know where should I find my binary.

**Comment by igrr** [comment]
Duplicate of https://github.com/esp8266/Arduino/issues/859 ?

**Comment by dragonnn** [comment]
Yes, I think this is the same problem, didn't see that.
