### ISSUE TITLE
Ad Hoc Mode

### ISSUE THREAD

**Issue by ycedenoo** [esp8266/Arduino#936]
Hi, 

I searched for information about configuring the ESP8266 in ad hoc or IBSS  mode, but can not find nothing. I am very interested in whether is possible, or in the development of new libraries for this mode because its versatility in sensor networks.
Regards

**Comment by igrr** [comment]
I don't think Espressif has released information regarding ad hoc mode
support. They do have Mesh SDK though. Check their BBS for documentation.
