### ISSUE TITLE
Register list

### ISSUE THREAD

**Issue by Rickgg** [esp8266/Arduino#937]
Hello, is there a place where I can see the registers of the ESP8266? I want to modify some of them like with an AVR. Is it possible?
Mainly UART registers.

**Comment by igrr** [comment]
Go to http://bbs.espressif.com/viewtopic.php?f=51&t=819 and look for "UART
registers" document.
Register names are defined in eagle_soc.h

**Comment by Rickgg** [comment]
Great! thanks :+1:  :smiley:
