### ISSUE TITLE
New editor: setForeground doesn't change default text color

### ISSUE THREAD

**Issue by szpapas** [esp8266/Arduino#944]
This issure have been solved on this refer "https://github.com/arduino/Arduino/commit/ee006271d86185e6e3b2f038eb511062cbca615f". but the code has not merged. Would you please update this.

       IOUtils.closeQuietly(defaultXmlInputStream);
     }
 
-    setForeground(processing.app.Theme.getColor("editor.fgcolor"));
     setBackground(processing.app.Theme.getColor("editor.bgcolor"));
     setCurrentLineHighlightColor(processing.app.Theme.getColor("editor.linehighlight.color"));
     setCaretColor(processing.app.Theme.getColor("editor.caret.color"));
 @@ -129,6 +128,10 @@ private void setTheme(String name) throws IOException {
     setSyntaxTheme(TokenTypes.LITERAL_BOOLEAN, "literal_boolean");
     setSyntaxTheme(TokenTypes.LITERAL_CHAR, "literal_char");
     setSyntaxTheme(TokenTypes.LITERAL_STRING_DOUBLE_QUOTE, "literal_string_double_quote");
+
+    Style style = getSyntaxScheme().getStyle(TokenTypes.IDENTIFIER);
+    style.foreground = processing.app.Theme.getColor("editor.fgcolor");
+    getSyntaxScheme().setStyle(TokenTypes.IDENTIFIER, style);
   }
 
   private void setSyntaxTheme(int tokenType, String id) {
 @@ -391,7 +394,7 @@ public void mouseMoved(MouseEvent e) {
         // Copy token, viewToModel() unfortunately modifies Token
         t = new TokenImpl(t);
       }
-      Cursor c2 = null;
+      Cursor c2;
       if (t != null && t.isHyperlink()) {
         if (hoveredOverLinkOffset == -1 ||
           hoveredOverLinkOffset != t.getOffset()) {

**Comment by igrr** [comment]
This repository doesn't contain IDE code now, so this change can not be applied here.

**Comment by szpapas** [comment]
Thanks!
