### ISSUE TITLE
Boards Manager install fail - Error downloading esptool 

### ISSUE THREAD

**Issue by torntrousers** [esp8266/Arduino#949]
On a fresh install of Arduino ESP8266 and installing the esp bit with Boards Manager it fails with:

Error Downloading https://github/igrr/esptool-ck/releases/download/0.4.5/esptool-0.4.5-win32.zip

Happens with both staging and stable versions.

**Comment by igrr** [comment]
Perhaps github was temporary unavailable to you? I just tried that on windows — worked fine.
Anyone else on Windows can reproduce this?

**Comment by Juppit** [comment]
Worked fine for me in the last hours and I tried often the last hours.

On 01.11.2015 at 19:53 wrote Ivan Grokhotkov:

**Comment by torntrousers** [comment]
Mmm, it does work ok now.
