### ISSUE TITLE
Netbeans

### ISSUE THREAD

**Issue by czopas** [esp8266/Arduino#951]
Hello,

is it possible to configure Netbeans to programming ESP8266with Arduino code ? With Eclipse it is possible but I can't find solution with Netbeans.

Marcin

**Comment by asetyde** [comment]
Use visual studio 2015 community with visual micro plugin

**Comment by grahamehorner** [comment]
@asetyde :+1: or try AtmelStudio 7

**Comment by asetyde** [comment]
Please close this issue , only Visual Studio is compatible , no way to Atmel .
