### ISSUE TITLE
Change esp parameter using another apps

### ISSUE THREAD

**Issue by Lexander24** [esp8266/Arduino#968]
Hello guys, i want to ask.
Can i change the parameter of espModule by sending command from server.

I want to change the parameter like APname,APpass,device(ip,subnet,gateway),Server(ip,port) and safe at the esp memory

So i just need to flash the board one time, and i can change the board parameter using other application.

Thanks

**Comment by drmpf** [comment]
check out this ESP project which includes webpage config.
http://www.forward.com.au/pfod/CheapWifiShield/ESP2866_01_WiFi_Shield/index.html
