### ISSUE TITLE
[staging] ArduinoJson example and libc_replacements compiler warnings

### ISSUE THREAD

**Issue by andig** [esp8266/Arduino#978]
This is fyi- not sure there is any actual problem:

	C:\Users\Arduino\libraries\ArduinoJson\src\JsonVariant.cpp:38:18: warning: always_inline function might not be inlinable [-Wattributes]
	 FORCE_INLINE int parse<int>(const char *s) {
			  ^
	C:\Users\Arduino\libraries\ArduinoJson\src\JsonVariant.cpp:33:19: warning: always_inline function might not be inlinable [-Wattributes]
	 FORCE_INLINE long parse<long>(const char *s) {
			   ^
	C:\Users\Arduino\libraries\ArduinoJson\src\JsonVariant.cpp:28:21: warning: always_inline function might not be inlinable [-Wattributes]
	 FORCE_INLINE double parse<double>(const char *s) {
			     ^
	C:\Users\Arduino\libraries\ArduinoJson\src\JsonVariant.cpp:23:20: warning: always_inline function might not be inlinable [-Wattributes]
	 FORCE_INLINE float parse<float>(const char *s) {
			    ^
	C:\Users\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-1160-gef26c5f\cores\esp8266\libc_replacements.c:408:22: warning: 'struct tm' declared inside parameter list [enabled by default]
	 time_t mktime(struct tm *timp) {
			      ^
	C:\Users\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\1.6.5-1160-gef26c5f\cores\esp8266\libc_replacements.c:408:22: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]

**Comment by igrr** [comment]
I think the first 4 warnings should be reported in https://github.com/bblanchon/ArduinoJson.
The other two have been fixed in git (#740).
