### ISSUE TITLE
Installer vs Full fork?

### ISSUE THREAD

**Issue by jeff-hamm** [esp8266/Arduino#99]
Not really an issue -- but not certain the best place for this:

Is there a terribly good reason that this project is a full fork of the IDE? It seems like wrapping up the hardware/libraries in an installer-type package that works with the users already-installed version of Arduino would be way more user friendly.  That's the model followed by lots of other boards (Teensy for example).

The only immediately obvious modification I could find to the actual IDE was the code for disableRTS and disableDTR or whatever. And that doesn't feel essential (and could probably be implemented differently). I haven't done a deep search of the source tree though. Does it sound feasible?

Would my effort along these lines be welcome? I'm very interested in helping make this thing as easy to use as possible.

**Comment by webguy16** [comment]
like https://github.com/sandeepmistry/esp8266-Arduino ?

also, duplicate of #14 ?

**Comment by jeff-hamm** [comment]
Thanks!
